export const n5part1 = {
  Lesson1: [
    {
      id: 1,
      kanji: "青",
      reading: "あお",
      meanings: {
        ja: "青",
        en: "blue",
        zh: "蓝色",
        tw: "藍色",
        ko: "파란색",
        vi: "màu xanh (lam)",
        th: "สีน้ำเงิน",
        my: "အပြာရောင်",
        km: "ពណ៌ខៀវ",
      },
      furigana: [
        {
          rb: "青",
          rt: "あお",
        },
      ],
      kanjiInfo: [
        {
          char: "青",
          on: ["セイ", "ショウ"],
          kun: ["あお", "あお-", "あお.い"],
          strokes: 8,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2,
      kanji: "赤",
      reading: "あか",
      meanings: {
        ja: "赤",
        en: "red",
        zh: "红色",
        tw: "紅色",
        ko: "빨간색",
        vi: "màu đỏ",
        th: "สีแดง",
        my: "အနီရောင်",
        km: "ពណ៌ក្រហម",
      },
      furigana: [
        {
          rb: "赤",
          rt: "あか",
        },
      ],
      kanjiInfo: [
        {
          char: "赤",
          on: ["セキ", "シャク"],
          kun: ["あか", "あか-", "あか.い", "あか.らむ", "あか.らめる"],
          strokes: 7,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 3,
      kanji: "秋",
      reading: "あき",
      meanings: {
        ja: "秋",
        en: "autumn",
        zh: "秋天",
        tw: "秋天",
        ko: "가을",
        vi: "mùa thu",
        th: "ฤดูใบไม้ร่วง",
        my: "ဆောင်းဦးရာသီ",
        km: "រដូវស្លឹកឈើជ្រុះ",
      },
      furigana: [
        {
          rb: "秋",
          rt: "あき",
        },
      ],
      kanjiInfo: [
        {
          char: "秋",
          on: ["シュウ"],
          kun: ["あき", "とき"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 4,
      kanji: "朝",
      reading: "あさ",
      meanings: {
        ja: "朝",
        en: "morning",
        zh: "早晨",
        tw: "早晨",
        ko: "아침",
        vi: "buổi sáng",
        th: "ตอนเช้า",
        my: "မနက်",
        km: "ព្រឹក",
      },
      furigana: [
        {
          rb: "朝",
          rt: "あさ",
        },
      ],
      kanjiInfo: [
        {
          char: "朝",
          on: ["チョウ"],
          kun: ["あさ"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 5,
      kanji: "朝ご飯",
      reading: "あさごはん",
      meanings: {
        ja: "朝ご飯",
        en: "breakfast",
        zh: "早餐",
        tw: "早餐",
        ko: "아침밥",
        vi: "bữa sáng",
        th: "อาหารเช้า",
        my: "နံနက်စာ",
        km: "អាហារពេលព្រឹក",
      },
      furigana: [
        {
          rb: "朝ご飯",
          rt: "あさごはん",
        },
      ],
      kanjiInfo: [
        {
          char: "朝",
          on: ["チョウ"],
          kun: ["あさ"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "飯",
          on: ["ハン"],
          kun: ["めし"],
          strokes: 12,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 6,
      kanji: "明後日",
      reading: "あさって",
      meanings: {
        ja: "明後日",
        en: "day after tomorrow",
        zh: "后天",
        tw: "後天",
        ko: "모레",
        vi: "ngày kia",
        th: "มะรืนนี้",
        my: "သန်ဘက်ခါ",
        km: "មស្អែក",
      },
      furigana: [
        {
          rb: "明後日",
          rt: "あさって",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 7,
      kanji: "明日",
      reading: "あした",
      meanings: {
        ja: "明日",
        en: "tomorrow",
        zh: "明天",
        tw: "明天",
        ko: "내일",
        vi: "ngày mai",
        th: "พรุ่งนี้",
        my: "မနက်ဖြန်",
        km: "ស្អែក",
      },
      furigana: [
        {
          rb: "明日",
          rt: "あした",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 8,
      kanji: "頭",
      reading: "あたま",
      meanings: {
        ja: "頭",
        en: "head",
        zh: "头",
        tw: "頭",
        ko: "머리",
        vi: "đầu",
        th: "ศีรษะ",
        my: "ဦးခေါင်း",
        km: "ក្បាល",
      },
      furigana: [
        {
          rb: "頭",
          rt: "あたま",
        },
      ],
      kanjiInfo: [
        {
          char: "頭",
          on: ["トウ", "ズ", "ト"],
          kun: ["あたま", "かしら", "-がしら", "かぶり"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 9,
      kanji: "後",
      reading: "あと",
      meanings: {
        ja: "後ろ／後",
        en: "behind; after",
        zh: "后面；之后",
        tw: "後面；之後",
        ko: "뒤; 이후",
        vi: "đằng sau; sau",
        th: "ข้างหลัง; หลังจาก",
        my: "နောက်ဘက်; နောက်မှ",
        km: "ខាងក្រោយ; បន្ទាប់ពី",
      },
      furigana: [
        {
          rb: "後",
          rt: "あと",
        },
      ],
      kanjiInfo: [
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 10,
      kanji: "兄",
      reading: "あに",
      meanings: {
        ja: "兄",
        en: "older brother",
        zh: "哥哥",
        tw: "哥哥",
        ko: "형/오빠",
        vi: "anh trai",
        th: "พี่ชาย",
        my: "အစ်ကို",
        km: "បងប្រុស",
      },
      furigana: [
        {
          rb: "兄",
          rt: "あに",
        },
      ],
      kanjiInfo: [
        {
          char: "兄",
          on: ["ケイ", "キョウ"],
          kun: ["あに"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 11,
      kanji: "姉",
      reading: "あね",
      meanings: {
        ja: "姉",
        en: "older sister",
        zh: "姐姐",
        tw: "姐姐",
        ko: "누나/언니",
        vi: "chị gái",
        th: "พี่สาว",
        my: "အစ်မ",
        km: "បងស្រី",
      },
      furigana: [
        {
          rb: "姉",
          rt: "あね",
        },
      ],
      kanjiInfo: [
        {
          char: "姉",
          on: ["シ"],
          kun: ["あね", "はは"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 12,
      kanji: "アパート",
      reading: "アパート",
      meanings: {
        ja: "アパート",
        en: "apartment building",
        zh: "公寓",
        tw: "公寓",
        ko: "아파트",
        vi: "căn hộ",
        th: "อพาร์ตเมนต์",
        my: "အာပတ်မင့်",
        km: "អាផាតមេនต์",
      },
      furigana: [
        {
          rb: "アパート",
          rt: "アパート",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 13,
      kanji: "余り",
      reading: "あまり",
      meanings: {
        ja: "余り",
        en: "remainder",
        zh: "余数；剩余",
        tw: "餘數；剩餘",
        ko: "나머지",
        vi: "phần còn lại",
        th: "เศษ; ส่วนที่เหลือ",
        my: "ကျန်ရှိ部分",
        km: "ចំណែកនៅសល់",
      },
      furigana: [
        {
          rb: "余り",
          rt: "あまり",
        },
      ],
      kanjiInfo: [
        {
          char: "余",
          on: ["ヨ"],
          kun: ["あま.る", "あま.り", "あま.す", "あんま.り"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 14,
      kanji: "雨",
      reading: "あめ",
      meanings: {
        ja: "雨",
        en: "rain",
        zh: "雨",
        tw: "雨",
        ko: "비",
        vi: "mưa",
        th: "ฝน",
        my: "မိုး",
        km: "ភ្លៀង",
      },
      furigana: [
        {
          rb: "雨",
          rt: "あめ",
        },
      ],
      kanjiInfo: [
        {
          char: "雨",
          on: ["ウ"],
          kun: ["あめ", "あま-", "-さめ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 15,
      kanji: "飴",
      reading: "あめ",
      meanings: {
        ja: "飴",
        en: "(hard) candy",
        zh: "糖果",
        tw: "糖果",
        ko: "사탕",
        vi: "kẹo cứng",
        th: "ลูกอมแข็ง",
        my: "ဆားတင် (ခဲမုန့်)",
        km: "ស្ករគ្រាប់",
      },
      furigana: [
        {
          rb: "飴",
          rt: "あめ",
        },
      ],
      kanjiInfo: [
        {
          char: "飴",
          on: ["イ", "シ"],
          kun: ["あめ", "やしな.う"],
          strokes: 13,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 16,
      kanji: "家",
      reading: "いえ",
      meanings: {
        ja: "家",
        en: "house",
        zh: "房子；家",
        tw: "房子；家",
        ko: "집",
        vi: "nhà",
        th: "บ้าน",
        my: "အိမ်",
        km: "ផ្ទះ",
      },
      furigana: [
        {
          rb: "家",
          rt: "いえ",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 17,
      kanji: "いくら",
      reading: "いくら",
      meanings: {
        ja: "いくら（魚卵）",
        en: "salted salmon roe",
        zh: "鲑鱼子",
        tw: "鮭魚卵",
        ko: "연어알",
        vi: "trứng cá hồi muối",
        th: "ไข่ปลาแซลมอนดอง",
        my: "ဆယ်မြင်းငါးဥငန်",
        km: "ស៊ាយម៉ុនអំបិល (ស៊ាយម៊ុនអ៊ូម)",
      },
      furigana: [
        {
          rb: "いくら",
          rt: "いくら",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 18,
      kanji: "池",
      reading: "いけ",
      meanings: {
        ja: "池",
        en: "pond",
        zh: "池塘",
        tw: "池塘",
        ko: "연못",
        vi: "ao",
        th: "สระน้ำ",
        my: "အို",
        km: "អណ្ដូងទឹក/ស្រះ",
      },
      furigana: [
        {
          rb: "池",
          rt: "いけ",
        },
      ],
      kanjiInfo: [
        {
          char: "池",
          on: ["チ"],
          kun: ["いけ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 19,
      kanji: "医者",
      reading: "いしゃ",
      meanings: {
        ja: "医者",
        en: "doctor",
        zh: "医生",
        tw: "醫生",
        ko: "의사",
        vi: "bác sĩ",
        th: "หมอ/แพทย์",
        my: "ဆေးကုသရေး ဝန်ထမ်း",
        km: "វេជ្ជបណ្ឌិត",
      },
      furigana: [
        {
          rb: "医者",
          rt: "いしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "医",
          on: ["イ"],
          kun: ["い.やす", "い.する", "くすし"],
          strokes: 7,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "者",
          on: ["シャ"],
          kun: ["もの"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 20,
      kanji: "椅子",
      reading: "いす",
      meanings: {
        ja: "椅子",
        en: "chair",
        zh: "椅子",
        tw: "椅子",
        ko: "의자",
        vi: "ghế",
        th: "เก้าอี้",
        my: "ခုံ/ပေ့အုံ",
        km: "កៅអី",
      },
      furigana: [
        {
          rb: "椅子",
          rt: "いす",
        },
      ],
      kanjiInfo: [
        {
          char: "椅",
          on: ["イ"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 21,
      kanji: "一",
      reading: "いち",
      meanings: {
        ja: "一",
        en: "one",
        zh: "一",
        tw: "一",
        ko: "하나",
        vi: "một",
        th: "หนึ่ง",
        my: "တစ်",
        km: "មួយ",
      },
      furigana: [
        {
          rb: "一",
          rt: "いち",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 22,
      kanji: "一日",
      reading: "いちにち",
      meanings: {
        ja: "一日",
        en: "one day",
        zh: "一天",
        tw: "一天",
        ko: "하루",
        vi: "một ngày",
        th: "หนึ่งวัน",
        my: "တစ်ရက်",
        km: "មួយថ្ងៃ",
      },
      furigana: [
        {
          rb: "一日",
          rt: "いちにち",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 23,
      kanji: "一番",
      reading: "いちばん",
      meanings: {
        ja: "一番",
        en: "number one",
        zh: "第一；最……",
        tw: "第一；最……",
        ko: "제일",
        vi: "nhất; số một",
        th: "อันดับหนึ่ง; ที่สุด",
        my: "တစ်နံပါတ်; အကောင်းဆုံး",
        km: "លេខទីមួយ; ល្អបំផុត",
      },
      furigana: [
        {
          rb: "一番",
          rt: "いちばん",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "番",
          on: ["バン"],
          kun: ["つが.い"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 24,
      kanji: "五日",
      reading: "いつか",
      meanings: {
        ja: "五日（5日）",
        en: "5th day of the month",
        zh: "五日（5号）",
        tw: "五日（5號）",
        ko: "5일",
        vi: "ngày mồng 5",
        th: "วันที่ 5",
        my: "၅ ရက်နေ့",
        km: "ថ្ងៃទី ៥",
      },
      furigana: [
        {
          rb: "五日",
          rt: "いつか",
        },
      ],
      kanjiInfo: [
        {
          char: "五",
          on: ["ゴ"],
          kun: ["いつ", "いつ.つ"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 25,
      kanji: "一緒",
      reading: "いっしょ",
      meanings: {
        ja: "一緒",
        en: "(doing) together",
        zh: "一起",
        tw: "一起",
        ko: "함께",
        vi: "cùng nhau",
        th: "ด้วยกัน",
        my: "အတူတကွ",
        km: "ជាមួយគ្នា",
      },
      furigana: [
        {
          rb: "一緒",
          rt: "いっしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "緒",
          on: ["ショ", "チョ"],
          kun: ["お", "いとぐち"],
          strokes: 14,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 26,
      kanji: "五つ",
      reading: "いつつ",
      meanings: {
        ja: "五つ（数量）",
        en: "five",
        zh: "五个",
        tw: "五個",
        ko: "다섯",
        vi: "năm (số lượng)",
        th: "ห้า (ชิ้น/อัน)",
        my: "ငါး (အရေအတွက်)",
        km: "ប្រាំ (ចំនួន)",
      },
      furigana: [
        {
          rb: "五つ",
          rt: "いつつ",
        },
      ],
      kanjiInfo: [
        {
          char: "五",
          on: ["ゴ"],
          kun: ["いつ", "いつ.つ"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 27,
      kanji: "犬",
      reading: "いぬ",
      meanings: {
        ja: "犬",
        en: "dog (domestic)",
        zh: "狗",
        tw: "狗",
        ko: "개",
        vi: "chó",
        th: "สุนัข",
        my: "ခွေး",
        km: "ឆ្កែ",
      },
      furigana: [
        {
          rb: "犬",
          rt: "いぬ",
        },
      ],
      kanjiInfo: [
        {
          char: "犬",
          on: ["ケン"],
          kun: ["いぬ", "いぬ-"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 28,
      kanji: "今",
      reading: "いま",
      meanings: {
        ja: "今",
        en: "now",
        zh: "现在",
        tw: "現在",
        ko: "지금",
        vi: "bây giờ",
        th: "ตอนนี้",
        my: "အခု",
        km: "ឥឡូវនេះ",
      },
      furigana: [
        {
          rb: "今",
          rt: "いま",
        },
      ],
      kanjiInfo: [
        {
          char: "今",
          on: ["コン", "キン"],
          kun: ["いま"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 29,
      kanji: "意味",
      reading: "いみ",
      meanings: {
        ja: "意味",
        en: "meaning",
        zh: "意思；含义",
        tw: "意思；含義",
        ko: "의미",
        vi: "ý nghĩa",
        th: "ความหมาย",
        my: "အဓိပ္ပါယ်",
        km: "អត្ថន័យ",
      },
      furigana: [
        {
          rb: "意味",
          rt: "いみ",
        },
      ],
      kanjiInfo: [
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 30,
      kanji: "妹",
      reading: "いもうと",
      meanings: {
        ja: "妹",
        en: "younger sister",
        zh: "妹妹",
        tw: "妹妹",
        ko: "여동생",
        vi: "em gái",
        th: "น้องสาว",
        my: "ညီမ",
        km: "ប្អូនស្រី",
      },
      furigana: [
        {
          rb: "妹",
          rt: "いもうと",
        },
      ],
      kanjiInfo: [
        {
          char: "妹",
          on: ["マイ"],
          kun: ["いもうと"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 31,
      kanji: "入口",
      reading: "いりぐち",
      meanings: {
        ja: "入口",
        en: "entrance",
        zh: "入口",
        tw: "入口",
        ko: "입구",
        vi: "lối vào",
        th: "ทางเข้า",
        my: "ဝင်ပေါက်",
        km: "ច្រកចូល",
      },
      furigana: [
        {
          rb: "入口",
          rt: "いりぐち",
        },
      ],
      kanjiInfo: [
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "口",
          on: ["コウ", "ク"],
          kun: ["くち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 32,
      kanji: "色",
      reading: "いろ",
      meanings: {
        ja: "色",
        en: "colour",
        zh: "颜色",
        tw: "顏色",
        ko: "색",
        vi: "màu sắc",
        th: "สี",
        my: "အရောင်",
        km: "ពណ៌",
      },
      furigana: [
        {
          rb: "色",
          rt: "いろ",
        },
      ],
      kanjiInfo: [
        {
          char: "色",
          on: ["ショク", "シキ"],
          kun: ["いろ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 33,
      kanji: "上",
      reading: "うえ",
      meanings: {
        ja: "上",
        en: "above",
        zh: "上面",
        tw: "上面",
        ko: "위",
        vi: "trên",
        th: "ข้างบน",
        my: "အပေါ်",
        km: "ខាងលើ",
      },
      furigana: [
        {
          rb: "上",
          rt: "うえ",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 34,
      kanji: "後ろ",
      reading: "うしろ",
      meanings: {
        ja: "後ろ",
        en: "back",
        zh: "后面",
        tw: "後面",
        ko: "뒤",
        vi: "đằng sau",
        th: "ข้างหลัง",
        my: "နောက်ဘက်",
        km: "ខាងក្រោយ",
      },
      furigana: [
        {
          rb: "後ろ",
          rt: "うしろ",
        },
      ],
      kanjiInfo: [
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 35,
      kanji: "歌",
      reading: "うた",
      meanings: {
        ja: "歌",
        en: "song",
        zh: "歌曲",
        tw: "歌曲",
        ko: "노래",
        vi: "bài hát",
        th: "เพลง",
        my: "သီချင်း",
        km: "ចម្រៀង",
      },
      furigana: [
        {
          rb: "歌",
          rt: "うた",
        },
      ],
      kanjiInfo: [
        {
          char: "歌",
          on: ["カ"],
          kun: ["うた", "うた.う"],
          strokes: 14,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 36,
      kanji: "海",
      reading: "うみ",
      meanings: {
        ja: "海",
        en: "sea",
        zh: "海",
        tw: "海",
        ko: "바다",
        vi: "biển",
        th: "ทะเล",
        my: "ပင်လယ်",
        km: "សមុទ្រ",
      },
      furigana: [
        {
          rb: "海",
          rt: "うみ",
        },
      ],
      kanjiInfo: [
        {
          char: "海",
          on: ["カイ"],
          kun: ["うみ"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 37,
      kanji: "上着",
      reading: "うわぎ",
      meanings: {
        ja: "上着",
        en: "coat",
        zh: "外套",
        tw: "外套",
        ko: "겉옷/코트",
        vi: "áo khoác",
        th: "เสื้อโค้ต/เสื้อคลุม",
        my: "အဆာပေါ်အင်္ကျီ",
        km: "អាវក្រៅ",
      },
      furigana: [
        {
          rb: "上着",
          rt: "うわぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 38,
      kanji: "絵",
      reading: "え",
      meanings: {
        ja: "絵",
        en: "picture",
        zh: "画；图画",
        tw: "畫；圖畫",
        ko: "그림",
        vi: "tranh",
        th: "ภาพวาด",
        my: "ရုပ်ပုံ/ပန်းချီ",
        km: "រូបភាព",
      },
      furigana: [
        {
          rb: "絵",
          rt: "え",
        },
      ],
      kanjiInfo: [
        {
          char: "絵",
          on: ["カイ", "エ"],
          kun: [],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 39,
      kanji: "映画",
      reading: "えいが",
      meanings: {
        ja: "映画",
        en: "movie",
        zh: "电影",
        tw: "電影",
        ko: "영화",
        vi: "phim",
        th: "ภาพยนตร์",
        my: "ရုပ်ရှင်",
        km: "ភាពយន្ត",
      },
      furigana: [
        {
          rb: "映画",
          rt: "えいが",
        },
      ],
      kanjiInfo: [
        {
          char: "映",
          on: ["エイ"],
          kun: ["うつ.る", "うつ.す", "は.える", "-ば.え"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "画",
          on: ["ガ", "カク", "エ", "カイ"],
          kun: ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 40,
      kanji: "映画館",
      reading: "えいがかん",
      meanings: {
        ja: "映画館",
        en: "movie theatre",
        zh: "电影院",
        tw: "電影院",
        ko: "영화관",
        vi: "rạp chiếu phim",
        th: "โรงภาพยนตร์",
        my: "ရုပ်ရှင်ရုံ",
        km: "រោងភាពយន្ត",
      },
      furigana: [
        {
          rb: "映画館",
          rt: "えいがかん",
        },
      ],
      kanjiInfo: [
        {
          char: "映",
          on: ["エイ"],
          kun: ["うつ.る", "うつ.す", "は.える", "-ば.え"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "画",
          on: ["ガ", "カク", "エ", "カイ"],
          kun: ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "館",
          on: ["カン"],
          kun: ["やかた", "たて"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 41,
      kanji: "英語",
      reading: "えいご",
      meanings: {
        ja: "英語",
        en: "English (language)",
        zh: "英语",
        tw: "英語",
        ko: "영어",
        vi: "tiếng Anh",
        th: "ภาษาอังกฤษ",
        my: "အင်္ဂလိပ်ဘာသာ",
        km: "ភាសាអង់គ្លេស",
      },
      furigana: [
        {
          rb: "英語",
          rt: "えいご",
        },
      ],
      kanjiInfo: [
        {
          char: "英",
          on: ["エイ"],
          kun: ["はなぶさ"],
          strokes: 8,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 42,
      kanji: "駅",
      reading: "えき",
      meanings: {
        ja: "駅",
        en: "railway station",
        zh: "车站",
        tw: "車站",
        ko: "역",
        vi: "nhà ga",
        th: "สถานีรถไฟ",
        my: "ရထားဘူတာ",
        km: "ស្ថានីយរថភ្លើង",
      },
      furigana: [
        {
          rb: "駅",
          rt: "えき",
        },
      ],
      kanjiInfo: [
        {
          char: "駅",
          on: ["エキ"],
          kun: [],
          strokes: 14,
          grade: 3,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 43,
      kanji: "エレベーター",
      reading: "エレベーター",
      meanings: {
        ja: "エレベーター",
        en: "elevator",
        zh: "电梯",
        tw: "電梯",
        ko: "엘리베이터",
        vi: "thang máy",
        th: "ลิฟต์",
        my: "ဧလီဗေတာ",
        km: "លីហ្វท์",
      },
      furigana: [
        {
          rb: "エレベーター",
          rt: "エレベーター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 44,
      kanji: "鉛筆",
      reading: "えんぴつ",
      meanings: {
        ja: "鉛筆",
        en: "pencil",
        zh: "铅笔",
        tw: "鉛筆",
        ko: "연필",
        vi: "bút chì",
        th: "ดินสอ",
        my: "ခဲတံ",
        km: "ខ្មៅដៃ",
      },
      furigana: [
        {
          rb: "鉛筆",
          rt: "えんぴつ",
        },
      ],
      kanjiInfo: [
        {
          char: "鉛",
          on: ["エン"],
          kun: ["なまり"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "筆",
          on: ["ヒツ"],
          kun: ["ふで"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 45,
      kanji: "大勢",
      reading: "おおぜい",
      meanings: {
        ja: "大勢",
        en: "crowd of people",
        zh: "许多人；人山人海",
        tw: "許多人；人潮",
        ko: "많은 사람들",
        vi: "đông người",
        th: "ผู้คนจำนวนมาก",
        my: "လူအများအပြား",
        km: "មនុស្សច្រើន",
      },
      furigana: [
        {
          rb: "大勢",
          rt: "おおぜい",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "勢",
          on: ["セイ", "ゼイ"],
          kun: ["いきお.い", "はずみ"],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 46,
      kanji: "お母さん",
      reading: "おかあさん",
      meanings: {
        ja: "お母さん",
        en: "mother",
        zh: "妈妈",
        tw: "媽媽",
        ko: "어머니/엄마",
        vi: "mẹ",
        th: "คุณแม่",
        my: "မေမေ",
        km: "ម៉ាក់",
      },
      furigana: [
        {
          rb: "お母さん",
          rt: "おかあさん",
        },
      ],
      kanjiInfo: [
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 47,
      kanji: "お菓子",
      reading: "おかし",
      meanings: {
        ja: "お菓子",
        en: "confections; sweets",
        zh: "点心；零食",
        tw: "點心；零食",
        ko: "과자",
        vi: "bánh kẹo",
        th: "ขนม",
        my: "မုန့်မျိုးစုံ",
        km: "បង្អែម",
      },
      furigana: [
        {
          rb: "お菓子",
          rt: "おかし",
        },
      ],
      kanjiInfo: [
        {
          char: "菓",
          on: ["カ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 48,
      kanji: "お金",
      reading: "おかね",
      meanings: {
        ja: "お金",
        en: "money",
        zh: "钱",
        tw: "錢",
        ko: "돈",
        vi: "tiền",
        th: "เงิน",
        my: "ပိုက်ဆံ",
        km: "លុយ",
      },
      furigana: [
        {
          rb: "お金",
          rt: "おかね",
        },
      ],
      kanjiInfo: [
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 49,
      kanji: "奥さん",
      reading: "おくさん",
      meanings: {
        ja: "奥さん",
        en: "wife",
        zh: "（别人的）妻子",
        tw: "（別人的）太太",
        ko: "아내(남의)/부인",
        vi: "vợ (người khác)",
        th: "ภรรยา (ของผู้อื่น)",
        my: "ဇနီး (သူอื่น)",
        km: "ភរិយា (របស់អ្នកផ្សេង)",
      },
      furigana: [
        {
          rb: "奥さん",
          rt: "おくさん",
        },
      ],
      kanjiInfo: [
        {
          char: "奥",
          on: ["オウ"],
          kun: ["おく", "おく.まる", "くま"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 50,
      kanji: "お酒",
      reading: "おさけ",
      meanings: {
        ja: "お酒",
        en: "alcohol",
        zh: "酒；酒精飲料",
        tw: "酒；酒精飲料",
        ko: "술",
        vi: "rượu (đồ có cồn)",
        th: "เครื่องดื่มแอลกอฮอล์",
        my: "အရက်",
        km: "ស្រា (ភេសជ្ជៈជាតិអាល់កុល)",
      },
      furigana: [
        {
          rb: "お酒",
          rt: "おさけ",
        },
      ],
      kanjiInfo: [
        {
          char: "酒",
          on: ["シュ"],
          kun: ["さけ", "さか-"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
