export const n5part6 = {
  Lesson6: [
    {
      id: 251,
      kanji: "パーティー",
      reading: "パーティー",
      meanings: {
        ja: "パーティー",
        en: "party (social gathering)",
        zh: "聚会",
        tw: "派對",
        ko: "파티",
        vi: "bữa tiệc",
        th: "งานเลี้ยง",
        my: "ပါတီ",
        km: "ពិធីជប់លៀង",
      },
      furigana: [
        {
          rb: "パーティー",
          rt: "パーティー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 252,
      kanji: "灰皿",
      reading: "はいざら",
      meanings: {
        ja: "灰皿",
        en: "ashtray",
        zh: "烟灰缸",
        tw: "煙灰缸",
        ko: "재떨이",
        vi: "gạt tàn thuốc",
        th: "ที่เขี่ยบุหรี่",
        my: "ဆေးလိပ်ခွက်",
        km: "ប្រអប់សំរាមបារី",
      },
      furigana: [
        {
          rb: "灰皿",
          rt: "はいざら",
        },
      ],
      kanjiInfo: [
        {
          char: "灰",
          on: ["カイ"],
          kun: ["はい"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "皿",
          on: ["ベイ"],
          kun: ["さら"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 253,
      kanji: "葉書",
      reading: "はがき",
      meanings: {
        ja: "葉書",
        en: "postcard",
        zh: "明信片",
        tw: "明信片",
        ko: "엽서",
        vi: "bưu thiếp",
        th: "ไปรษณียบัตร",
        my: "ပို့ကဒ်",
        km: "កាតប៉ុស្ត៍",
      },
      furigana: [
        {
          rb: "葉書",
          rt: "はがき",
        },
      ],
      kanjiInfo: [
        {
          char: "葉",
          on: ["ヨウ"],
          kun: ["は"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 254,
      kanji: "箱",
      reading: "はこ",
      meanings: {
        ja: "箱",
        en: "box",
        zh: "箱子",
        tw: "箱子",
        ko: "상자",
        vi: "cái hộp",
        th: "กล่อง",
        my: "သေတ္တာ",
        km: "ប្រអប់",
      },
      furigana: [
        {
          rb: "箱",
          rt: "はこ",
        },
      ],
      kanjiInfo: [
        {
          char: "箱",
          on: ["ソウ"],
          kun: ["はこ"],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 255,
      kanji: "橋",
      reading: "はし",
      meanings: {
        ja: "橋",
        en: "bridge",
        zh: "桥",
        tw: "橋",
        ko: "다리",
        vi: "cây cầu",
        th: "สะพาน",
        my: "တံတား",
        km: "ស្ពាន",
      },
      furigana: [
        {
          rb: "橋",
          rt: "はし",
        },
      ],
      kanjiInfo: [
        {
          char: "橋",
          on: ["キョウ"],
          kun: ["はし"],
          strokes: 16,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 256,
      kanji: "箸",
      reading: "はし",
      meanings: {
        ja: "箸",
        en: "chopsticks",
        zh: "筷子",
        tw: "筷子",
        ko: "젓가락",
        vi: "đũa",
        th: "ตะเกียบ",
        my: "တူ",
        km: "ចង្កឹះ",
      },
      furigana: [
        {
          rb: "箸",
          rt: "はし",
        },
      ],
      kanjiInfo: [
        {
          char: "箸",
          on: ["チョ", "チャク"],
          kun: ["はし"],
          strokes: 15,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 257,
      kanji: "バス",
      reading: "バス",
      meanings: {
        ja: "バス",
        en: "bus",
        zh: "公共汽车",
        tw: "公車",
        ko: "버스",
        vi: "xe buýt",
        th: "รถบัส",
        my: "ဘတ်စ်ကား",
        km: "ក្រុមហ៊ុនឡានក្រុង",
      },
      furigana: [
        {
          rb: "バス",
          rt: "バス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 258,
      kanji: "バター",
      reading: "バター",
      meanings: {
        ja: "バター",
        en: "butter",
        zh: "黄油",
        tw: "奶油",
        ko: "버터",
        vi: "bơ",
        th: "เนย",
        my: "နွားနို့ထူ",
        km: "ប៊ឺ",
      },
      furigana: [
        {
          rb: "バター",
          rt: "バター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 259,
      kanji: "二十歳",
      reading: "はたち",
      meanings: {
        ja: "二十歳",
        en: "20 years old",
        zh: "二十岁",
        tw: "二十歲",
        ko: "스무 살",
        vi: "20 tuổi",
        th: "อายุ 20 ปี",
        my: "နှစ်ပေါင်း ၂၀",
        km: "អាយុ២០ឆ្នាំ",
      },
      furigana: [
        {
          rb: "二十歳",
          rt: "はたち",
        },
      ],
      kanjiInfo: [
        {
          char: "二",
          on: ["ニ", "ジ"],
          kun: ["ふた", "ふた.つ", "ふたたび"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "十",
          on: ["ジュウ", "ジッ", "ジュッ"],
          kun: ["とお", "と", "そ"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "歳",
          on: ["サイ", "セイ"],
          kun: ["とし", "とせ", "よわい"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 260,
      kanji: "八",
      reading: "はち",
      meanings: {
        ja: "八",
        en: "eight",
        zh: "八",
        tw: "八",
        ko: "여덟",
        vi: "tám",
        th: "แปด",
        my: "ရှစ်",
        km: "ប្រាំបី",
      },
      furigana: [
        {
          rb: "八",
          rt: "はち",
        },
      ],
      kanjiInfo: [
        {
          char: "八",
          on: ["ハチ", "ハツ"],
          kun: ["や", "や.つ", "やっ.つ", "よう"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 261,
      kanji: "二十日",
      reading: "はつか",
      meanings: {
        ja: "二十日（20日）",
        en: "20th day of the month",
        zh: "二十日（20号）",
        tw: "二十日（20號）",
        ko: "20일",
        vi: "ngày 20",
        th: "วันที่ 20",
        my: "၂၀ ရက်နေ့",
        km: "ថ្ងៃទី ២០",
      },
      furigana: [
        {
          rb: "二十日",
          rt: "はつか",
        },
      ],
      kanjiInfo: [
        {
          char: "二",
          on: ["ニ", "ジ"],
          kun: ["ふた", "ふた.つ", "ふたたび"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "十",
          on: ["ジュウ", "ジッ", "ジュッ"],
          kun: ["とお", "と", "そ"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 262,
      kanji: "花",
      reading: "はな",
      meanings: {
        ja: "花",
        en: "flower",
        zh: "花",
        tw: "花",
        ko: "꽃",
        vi: "hoa",
        th: "ดอกไม้",
        my: "ပန်း",
        km: "ផ្កា",
      },
      furigana: [
        {
          rb: "花",
          rt: "はな",
        },
      ],
      kanjiInfo: [
        {
          char: "花",
          on: ["カ", "ケ"],
          kun: ["はな"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 263,
      kanji: "鼻",
      reading: "はな",
      meanings: {
        ja: "鼻",
        en: "nose",
        zh: "鼻子",
        tw: "鼻子",
        ko: "코",
        vi: "mũi",
        th: "จมูก",
        my: "နှာခေါင်း",
        km: "ច្រមុះ",
      },
      furigana: [
        {
          rb: "鼻",
          rt: "はな",
        },
      ],
      kanjiInfo: [
        {
          char: "鼻",
          on: ["ビ"],
          kun: ["はな"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 264,
      kanji: "話",
      reading: "はなし",
      meanings: {
        ja: "話",
        en: "talk; story",
        zh: "谈话；故事",
        tw: "談話；故事",
        ko: "이야기",
        vi: "câu chuyện; lời nói",
        th: "เรื่องราว; การพูด",
        my: "စကား; အကြောင်းအရာ",
        km: "រឿងរ៉ាវ; ការនិយាយ",
      },
      furigana: [
        {
          rb: "話",
          rt: "はなし",
        },
      ],
      kanjiInfo: [
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 265,
      kanji: "母",
      reading: "はは",
      meanings: {
        ja: "母",
        en: "mother",
        zh: "母亲",
        tw: "母親",
        ko: "어머니",
        vi: "mẹ",
        th: "แม่",
        my: "အမေ",
        km: "ម្ដាយ",
      },
      furigana: [
        {
          rb: "母",
          rt: "はは",
        },
      ],
      kanjiInfo: [
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 266,
      kanji: "春",
      reading: "はる",
      meanings: {
        ja: "春",
        en: "spring",
        zh: "春天",
        tw: "春天",
        ko: "봄",
        vi: "mùa xuân",
        th: "ฤดูใบไม้ผลิ",
        my: "နွေဥတု",
        km: "រដូវផ្ការីក",
      },
      furigana: [
        {
          rb: "春",
          rt: "はる",
        },
      ],
      kanjiInfo: [
        {
          char: "春",
          on: ["シュン"],
          kun: ["はる"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 267,
      kanji: "晴れ",
      reading: "はれ",
      meanings: {
        ja: "晴れ",
        en: "clear weather",
        zh: "晴天",
        tw: "晴天",
        ko: "맑음",
        vi: "trời nắng",
        th: "อากาศแจ่มใส",
        my: "အလင်းရောင်",
        km: "អាកាសធាតុថ្ងៃភ្លឺ",
      },
      furigana: [
        {
          rb: "晴れ",
          rt: "はれ",
        },
      ],
      kanjiInfo: [
        {
          char: "晴",
          on: ["セイ"],
          kun: ["は.れる", "は.れ", "は.れ-", "-ば.れ", "は.らす"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 268,
      kanji: "半",
      reading: "はん",
      meanings: {
        ja: "半",
        en: "half",
        zh: "一半",
        tw: "一半",
        ko: "반",
        vi: "một nửa",
        th: "ครึ่ง",
        my: "တစ်ဝက်",
        km: "ពាក់កណ្តាល",
      },
      furigana: [
        {
          rb: "半",
          rt: "はん",
        },
      ],
      kanjiInfo: [
        {
          char: "半",
          on: ["ハン"],
          kun: ["なか.ば"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 269,
      kanji: "晩",
      reading: "ばん",
      meanings: {
        ja: "晩",
        en: "evening",
        zh: "晚上",
        tw: "晚上",
        ko: "저녁",
        vi: "buổi tối",
        th: "ตอนเย็น",
        my: "ညနေ",
        km: "ល្ងាច",
      },
      furigana: [
        {
          rb: "晩",
          rt: "ばん",
        },
      ],
      kanjiInfo: [
        {
          char: "晩",
          on: ["バン"],
          kun: [],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 270,
      kanji: "パン",
      reading: "パン",
      meanings: {
        ja: "パン",
        en: "bread",
        zh: "面包",
        tw: "麵包",
        ko: "빵",
        vi: "bánh mì",
        th: "ขนมปัง",
        my: "ပေါင်မုန့်",
        km: "នំបុ័ង",
      },
      furigana: [
        {
          rb: "パン",
          rt: "パン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 271,
      kanji: "ハンカチ",
      reading: "ハンカチ",
      meanings: {
        ja: "ハンカチ",
        en: "handkerchief",
        zh: "手帕",
        tw: "手帕",
        ko: "손수건",
        vi: "khăn tay",
        th: "ผ้าเช็ดหน้า",
        my: "လက်သွေးပွတ်ပဝါ",
        km: "កន្សែងជូតមុខ",
      },
      furigana: [
        {
          rb: "ハンカチ",
          rt: "ハンカチ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 272,
      kanji: "番号",
      reading: "ばんごう",
      meanings: {
        ja: "番号",
        en: "number",
        zh: "号码",
        tw: "號碼",
        ko: "번호",
        vi: "số (thứ tự)",
        th: "หมายเลข",
        my: "နံပါတ်",
        km: "លេខ",
      },
      furigana: [
        {
          rb: "番号",
          rt: "ばんごう",
        },
      ],
      kanjiInfo: [
        {
          char: "番",
          on: ["バン"],
          kun: ["つが.い"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "号",
          on: ["ゴウ"],
          kun: ["さけ.ぶ", "よびな"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 273,
      kanji: "晩御飯",
      reading: "ばんごはん",
      meanings: {
        ja: "晩御飯",
        en: "dinner",
        zh: "晚饭",
        tw: "晚餐",
        ko: "저녁밥",
        vi: "bữa tối",
        th: "อาหารเย็น",
        my: "ညစာ",
        km: "អាហារពេលល្ងាច",
      },
      furigana: [
        {
          rb: "晩御飯",
          rt: "ばんごはん",
        },
      ],
      kanjiInfo: [
        {
          char: "晩",
          on: ["バン"],
          kun: [],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "御",
          on: ["ギョ", "ゴ"],
          kun: ["おん-", "お-", "み-"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "飯",
          on: ["ハン"],
          kun: ["めし"],
          strokes: 12,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 274,
      kanji: "東",
      reading: "ひがし",
      meanings: {
        ja: "東",
        en: "east",
        zh: "东方",
        tw: "東方",
        ko: "동쪽",
        vi: "phía đông",
        th: "ทิศตะวันออก",
        my: "အရှေ့",
        km: "ខាងកើត",
      },
      furigana: [
        {
          rb: "東",
          rt: "ひがし",
        },
      ],
      kanjiInfo: [
        {
          char: "東",
          on: ["トウ"],
          kun: ["ひがし"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 275,
      kanji: "飛行機",
      reading: "ひこうき",
      meanings: {
        ja: "飛行機",
        en: "airplane",
        zh: "飞机",
        tw: "飛機",
        ko: "비행기",
        vi: "máy bay",
        th: "เครื่องบิน",
        my: "လေယာဉ်",
        km: "យន្តហោះ",
      },
      furigana: [
        {
          rb: "飛行機",
          rt: "ひこうき",
        },
      ],
      kanjiInfo: [
        {
          char: "飛",
          on: ["ヒ"],
          kun: ["と.ぶ", "と.ばす", "-と.ばす"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "機",
          on: ["キ"],
          kun: ["はた"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 276,
      kanji: "左",
      reading: "ひだり",
      meanings: {
        ja: "左",
        en: "left",
        zh: "左边",
        tw: "左邊",
        ko: "왼쪽",
        vi: "bên trái",
        th: "ซ้าย",
        my: "ဘယ်",
        km: "ឆ្វេង",
      },
      furigana: [
        {
          rb: "左",
          rt: "ひだり",
        },
      ],
      kanjiInfo: [
        {
          char: "左",
          on: ["サ", "シャ"],
          kun: ["ひだり"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 277,
      kanji: "人",
      reading: "ひと",
      meanings: {
        ja: "人",
        en: "person",
        zh: "人",
        tw: "人",
        ko: "사람",
        vi: "người",
        th: "คน",
        my: "လူ",
        km: "មនុស្ស",
      },
      furigana: [
        {
          rb: "人",
          rt: "ひと",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 278,
      kanji: "一つ",
      reading: "ひとつ",
      meanings: {
        ja: "一つ（数量）",
        en: "one (count)",
        zh: "一个",
        tw: "一個",
        ko: "하나",
        vi: "một cái",
        th: "หนึ่ง (จำนวน)",
        my: "တစ်ခု",
        km: "មួយ (ចំនួន)",
      },
      furigana: [
        {
          rb: "一つ",
          rt: "ひとつ",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 279,
      kanji: "一月",
      reading: "ひとつき",
      meanings: {
        ja: "一月（ひとつき）",
        en: "one month",
        zh: "一个月",
        tw: "一個月",
        ko: "한 달",
        vi: "một tháng",
        th: "หนึ่งเดือน",
        my: "တစ်လ",
        km: "១ ខែ",
      },
      furigana: [
        {
          rb: "一月",
          rt: "ひとつき",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 280,
      kanji: "一人",
      reading: "ひとり",
      meanings: {
        ja: "一人",
        en: "one person",
        zh: "一人",
        tw: "一人",
        ko: "한 사람",
        vi: "một người",
        th: "คนเดียว",
        my: "လူတစ်ယောက်",
        km: "មនុស្សម្នាក់",
      },
      furigana: [
        {
          rb: "一人",
          rt: "ひとり",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 281,
      kanji: "暇",
      reading: "ひま",
      meanings: {
        ja: "暇",
        en: "spare time",
        zh: "空闲时间",
        tw: "空閒時間",
        ko: "한가함",
        vi: "thời gian rảnh",
        th: "เวลาว่าง",
        my: "အချိန်အပေါက်",
        km: "ពេលទំនេរ",
      },
      furigana: [
        {
          rb: "暇",
          rt: "ひま",
        },
      ],
      kanjiInfo: [
        {
          char: "暇",
          on: ["カ"],
          kun: ["ひま", "いとま"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 282,
      kanji: "百",
      reading: "ひゃく",
      meanings: {
        ja: "百",
        en: "hundred",
        zh: "一百",
        tw: "一百",
        ko: "백",
        vi: "một trăm",
        th: "หนึ่งร้อย",
        my: "ရာ",
        km: "មួយរយ",
      },
      furigana: [
        {
          rb: "百",
          rt: "ひゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "百",
          on: ["ヒャク", "ビャク"],
          kun: ["もも"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 283,
      kanji: "病院",
      reading: "びょういん",
      meanings: {
        ja: "病院",
        en: "hospital",
        zh: "医院",
        tw: "醫院",
        ko: "병원",
        vi: "bệnh viện",
        th: "โรงพยาบาล",
        my: "ဆေးရုံ",
        km: "មន្ទីរពេទ្យ",
      },
      furigana: [
        {
          rb: "病院",
          rt: "びょういん",
        },
      ],
      kanjiInfo: [
        {
          char: "病",
          on: ["ビョウ", "ヘイ"],
          kun: ["や.む", "-や.み", "やまい"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "院",
          on: ["イン"],
          kun: [],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 284,
      kanji: "病気",
      reading: "びょうき",
      meanings: {
        ja: "病気",
        en: "illness",
        zh: "疾病",
        tw: "疾病",
        ko: "병",
        vi: "bệnh",
        th: "ความเจ็บป่วย",
        my: "ရောဂါ",
        km: "ជំងឺ",
      },
      furigana: [
        {
          rb: "病気",
          rt: "びょうき",
        },
      ],
      kanjiInfo: [
        {
          char: "病",
          on: ["ビョウ", "ヘイ"],
          kun: ["や.む", "-や.み", "やまい"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 285,
      kanji: "平仮名",
      reading: "ひらがな",
      meanings: {
        ja: "平仮名",
        en: "hiragana",
        zh: "平假名",
        tw: "平假名",
        ko: "히라가나",
        vi: "chữ Hiragana",
        th: "ฮิรางานะ",
        my: "ဟီရာဂနာ",
        km: "ហិរ៉ាហ្គាណា",
      },
      furigana: [
        {
          rb: "平仮名",
          rt: "ひらがな",
        },
      ],
      kanjiInfo: [
        {
          char: "平",
          on: ["ヘイ", "ビョウ", "ヒョウ"],
          kun: ["たい.ら", "たい.らげる", "ひら"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "仮",
          on: ["カ", "ケ"],
          kun: ["かり", "かり-"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 286,
      kanji: "昼",
      reading: "ひる",
      meanings: {
        ja: "昼",
        en: "noon",
        zh: "中午",
        tw: "中午",
        ko: "낮",
        vi: "buổi trưa",
        th: "กลางวัน",
        my: "နေ့လယ်",
        km: "ថ្ងៃត្រង់",
      },
      furigana: [
        {
          rb: "昼",
          rt: "ひる",
        },
      ],
      kanjiInfo: [
        {
          char: "昼",
          on: ["チュウ"],
          kun: ["ひる"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 287,
      kanji: "昼御飯",
      reading: "ひるごはん",
      meanings: {
        ja: "昼御飯",
        en: "lunch",
        zh: "午饭",
        tw: "午飯",
        ko: "점심",
        vi: "bữa trưa",
        th: "อาหารกลางวัน",
        my: "နေ့လယ်စာ",
        km: "អាហារពេលថ្ងៃត្រង់",
      },
      furigana: [
        {
          rb: "昼御飯",
          rt: "ひるごはん",
        },
      ],
      kanjiInfo: [
        {
          char: "昼",
          on: ["チュウ"],
          kun: ["ひる"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "御",
          on: ["ギョ", "ゴ"],
          kun: ["おん-", "お-", "み-"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "飯",
          on: ["ハン"],
          kun: ["めし"],
          strokes: 12,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 288,
      kanji: "フィルム",
      reading: "フィルム",
      meanings: {
        ja: "フィルム",
        en: "film",
        zh: "胶卷；电影胶片",
        tw: "底片；膠片",
        ko: "필름",
        vi: "phim",
        th: "ฟิล์ม",
        my: "ဖီလင်",
        km: "ហ្វីលិម្ព",
      },
      furigana: [
        {
          rb: "フィルム",
          rt: "フィルム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 289,
      kanji: "封筒",
      reading: "ふうとう",
      meanings: {
        ja: "封筒",
        en: "envelope",
        zh: "信封",
        tw: "信封",
        ko: "봉투",
        vi: "phong bì",
        th: "ซองจดหมาย",
        my: "စာအိတ်",
        km: "ស្រោមលិខិត",
      },
      furigana: [
        {
          rb: "封筒",
          rt: "ふうとう",
        },
      ],
      kanjiInfo: [
        {
          char: "封",
          on: ["フウ", "ホウ"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "筒",
          on: ["トウ"],
          kun: ["つつ"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 290,
      kanji: "プール",
      reading: "プール",
      meanings: {
        ja: "プール",
        en: "swimming pool",
        zh: "游泳池",
        tw: "游泳池",
        ko: "수영장",
        vi: "hồ bơi",
        th: "สระว่ายน้ำ",
        my: "ရေကူးကန်",
        km: "អាងហែលទឹក",
      },
      furigana: [
        {
          rb: "プール",
          rt: "プール",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 291,
      kanji: "フォーク",
      reading: "フォーク",
      meanings: {
        ja: "フォーク",
        en: "fork",
        zh: "叉子",
        tw: "叉子",
        ko: "포크",
        vi: "nĩa",
        th: "ส้อม",
        my: "ဖိုးခ်",
        km: "ចង្កឹះ",
      },
      furigana: [
        {
          rb: "フォーク",
          rt: "フォーク",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 292,
      kanji: "服",
      reading: "ふく",
      meanings: {
        ja: "服",
        en: "clothes",
        zh: "衣服",
        tw: "衣服",
        ko: "옷",
        vi: "quần áo",
        th: "เสื้อผ้า",
        my: "အဝတ်အစား",
        km: "សំលៀកបំពាក់",
      },
      furigana: [
        {
          rb: "服",
          rt: "ふく",
        },
      ],
      kanjiInfo: [
        {
          char: "服",
          on: ["フク"],
          kun: [],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 293,
      kanji: "二つ",
      reading: "ふたつ",
      meanings: {
        ja: "二つ（数量）",
        en: "two (count)",
        zh: "两个",
        tw: "兩個",
        ko: "두 개",
        vi: "hai cái",
        th: "สอง (จำนวน)",
        my: "နှစ်ခု",
        km: "ពីរ (ចំនួន)",
      },
      furigana: [
        {
          rb: "二つ",
          rt: "ふたつ",
        },
      ],
      kanjiInfo: [
        {
          char: "二",
          on: ["ニ", "ジ"],
          kun: ["ふた", "ふた.つ", "ふたたび"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 294,
      kanji: "豚肉",
      reading: "ぶたにく",
      meanings: {
        ja: "豚肉",
        en: "pork",
        zh: "猪肉",
        tw: "豬肉",
        ko: "돼지고기",
        vi: "thịt heo",
        th: "เนื้อหมู",
        my: "ဝက်သား",
        km: "សាច់ជ្រូក",
      },
      furigana: [
        {
          rb: "豚肉",
          rt: "ぶたにく",
        },
      ],
      kanjiInfo: [
        {
          char: "豚",
          on: ["トン"],
          kun: ["ぶた"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "肉",
          on: ["ニク"],
          kun: ["しし"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 295,
      kanji: "二人",
      reading: "ふたり",
      meanings: {
        ja: "二人",
        en: "two persons",
        zh: "两个人",
        tw: "兩個人",
        ko: "두 사람",
        vi: "hai người",
        th: "สองคน",
        my: "လူနှစ်ယောက်",
        km: "មនុស្សពីរ",
      },
      furigana: [
        {
          rb: "二人",
          rt: "ふたり",
        },
      ],
      kanjiInfo: [
        {
          char: "二",
          on: ["ニ", "ジ"],
          kun: ["ふた", "ふた.つ", "ふたたび"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 296,
      kanji: "二日",
      reading: "ふつか",
      meanings: {
        ja: "二日（2日）",
        en: "2nd day of the month",
        zh: "二日（2号）",
        tw: "二日（2號）",
        ko: "2일",
        vi: "ngày mồng 2",
        th: "วันที่ 2",
        my: "၂ ရက်နေ့",
        km: "ថ្ងៃទី២",
      },
      furigana: [
        {
          rb: "二日",
          rt: "ふつか",
        },
      ],
      kanjiInfo: [
        {
          char: "二",
          on: ["ニ", "ジ"],
          kun: ["ふた", "ふた.つ", "ふたたび"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 297,
      kanji: "冬",
      reading: "ふゆ",
      meanings: {
        ja: "冬",
        en: "winter",
        zh: "冬天",
        tw: "冬天",
        ko: "겨울",
        vi: "mùa đông",
        th: "ฤดูหนาว",
        my: "ဆောင်းရာသီ",
        km: "រដូវរងារ",
      },
      furigana: [
        {
          rb: "冬",
          rt: "ふゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "冬",
          on: ["トウ"],
          kun: ["ふゆ"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 298,
      kanji: "文章",
      reading: "ぶんしょう",
      meanings: {
        ja: "文章",
        en: "writing; text",
        zh: "文章",
        tw: "文章",
        ko: "문장",
        vi: "bài văn; đoạn văn",
        th: "ข้อความ; บทความ",
        my: "စာပိုဒ်",
        km: "អត្ថបទ",
      },
      furigana: [
        {
          rb: "文章",
          rt: "ぶんしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "章",
          on: ["ショウ"],
          kun: [],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 299,
      kanji: "ベッド",
      reading: "ベッド",
      meanings: {
        ja: "ベッド",
        en: "bed",
        zh: "床",
        tw: "床",
        ko: "침대",
        vi: "giường",
        th: "เตียงนอน",
        my: "ခုံအိပ်",
        km: "គ្រែ",
      },
      furigana: [
        {
          rb: "ベッド",
          rt: "ベッド",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 300,
      kanji: "ペット",
      reading: "ペット",
      meanings: {
        ja: "ペット",
        en: "pet",
        zh: "宠物",
        tw: "寵物",
        ko: "애완동물",
        vi: "thú cưng",
        th: "สัตว์เลี้ยง",
        my: "အိမ်မွေးတိရစ္ဆာန်",
        km: "សត្វចិញ្ចឹម",
      },
      furigana: [
        {
          rb: "ペット",
          rt: "ペット",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
