export const n5part13 = {
  Lesson13: [
    {
      id: 458,
      kanji: "会う",
      reading: "あう",
      meanings: {
        ja: "会う",
        en: "to meet",
        zh: "见面",
        tw: "見面",
        ko: "만나다",
        vi: "gặp",
        th: "พบ; เจอ",
        my: "တွေ့ဆုံ",
        km: "ជួប",
      },
      furigana: [
        {
          rb: "会う",
          rt: "あう",
        },
      ],
      kanjiInfo: [
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 459,
      kanji: "開く",
      reading: "あく",
      meanings: {
        ja: "開く（自）",
        en: "to open (intrans.)",
        zh: "开（着）",
        tw: "開（著）",
        ko: "열리다",
        vi: "mở (tự động)",
        th: "เปิดอยู่ (อกรรม)",
        my: "ဖွင့်ထားသည်",
        km: "បើក (អកម្ម)",
      },
      furigana: [
        {
          rb: "開く",
          rt: "あく",
        },
      ],
      kanjiInfo: [
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 460,
      kanji: "開ける",
      reading: "あける",
      meanings: {
        ja: "開ける（他）",
        en: "to open (trans.)",
        zh: "打开",
        tw: "打開",
        ko: "열다",
        vi: "mở (tha động)",
        th: "เปิด (สกรรม)",
        my: "ဖွင့်သည်",
        km: "បើក (កម្ម)",
      },
      furigana: [
        {
          rb: "開ける",
          rt: "あける",
        },
      ],
      kanjiInfo: [
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 461,
      kanji: "上げる",
      reading: "あげる",
      meanings: {
        ja: "上げる",
        en: "to raise; to lift",
        zh: "举起; 提高",
        tw: "舉起；提高",
        ko: "올리다",
        vi: "nâng lên",
        th: "ยกขึ้น",
        my: "မြှင့်တင်",
        km: "លើកឡើង",
      },
      furigana: [
        {
          rb: "上げる",
          rt: "あげる",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 462,
      kanji: "遊ぶ",
      reading: "あそぶ",
      meanings: {
        ja: "遊ぶ",
        en: "to play",
        zh: "玩耍",
        tw: "玩耍",
        ko: "놀다",
        vi: "chơi",
        th: "เล่น",
        my: "ကစား",
        km: "លេង",
      },
      furigana: [
        {
          rb: "遊ぶ",
          rt: "あそぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "遊",
          on: ["ユウ", "ユ"],
          kun: ["あそ.ぶ", "あそ.ばす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 463,
      kanji: "浴びる",
      reading: "あびる",
      meanings: {
        ja: "浴びる",
        en: "to bathe; to pour over oneself",
        zh: "淋; 沐浴",
        tw: "淋; 沐浴",
        ko: "뒤집어쓰다; 목욕하다",
        vi: "dội; tắm",
        th: "ราด; อาบน้ำ",
        my: "ရေပေါက်လောင်း; स्नಾನ",
        km: "លាង/ងូតទឹក",
      },
      furigana: [
        {
          rb: "浴びる",
          rt: "あびる",
        },
      ],
      kanjiInfo: [
        {
          char: "浴",
          on: ["ヨク"],
          kun: ["あ.びる", "あ.びせる"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 464,
      kanji: "洗う",
      reading: "あらう",
      meanings: {
        ja: "洗う",
        en: "to wash",
        zh: "洗",
        tw: "洗",
        ko: "씻다/빨다",
        vi: "rửa/giặt",
        th: "ล้าง/ซัก",
        my: "လုှတ်/လျှော်",
        km: "លាង/បោក",
      },
      furigana: [
        {
          rb: "洗う",
          rt: "あらう",
        },
      ],
      kanjiInfo: [
        {
          char: "洗",
          on: ["セン"],
          kun: ["あら.う"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 465,
      kanji: "在る",
      reading: "ある",
      meanings: {
        ja: "在る（無生物）",
        en: "to exist; to be (inanimate)",
        zh: "在; 存在",
        tw: "在；存在",
        ko: "있다(무생물)",
        vi: "có (vật vô tri)",
        th: "มี/อยู่ (ไม่มีชีวิต)",
        my: "ရှိ (မသက်ရှူ)",
        km: "មាន/ស្ថិត (អវយវៈ)",
      },
      furigana: [
        {
          rb: "在る",
          rt: "ある",
        },
      ],
      kanjiInfo: [
        {
          char: "在",
          on: ["ザイ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 466,
      kanji: "有る",
      reading: "ある",
      meanings: {
        ja: "有る（無生物）",
        en: "to have; to be (inanimate)",
        zh: "有; 存在",
        tw: "有；存在",
        ko: "있다(무생물)",
        vi: "có; hiện hữu",
        th: "มี; อยู่ (ไม่มีชีวิต)",
        my: "ရှိတယ်",
        km: "មាន",
      },
      furigana: [
        {
          rb: "有る",
          rt: "ある",
        },
      ],
      kanjiInfo: [
        {
          char: "有",
          on: ["ユウ", "ウ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 467,
      kanji: "歩く",
      reading: "あるく",
      meanings: {
        ja: "歩く",
        en: "to walk",
        zh: "走路",
        tw: "走路",
        ko: "걷다",
        vi: "đi bộ",
        th: "เดิน",
        my: "လမ်းလျှောက်",
        km: "ដើរ",
      },
      furigana: [
        {
          rb: "歩く",
          rt: "あるく",
        },
      ],
      kanjiInfo: [
        {
          char: "歩",
          on: ["ホ", "ブ", "フ"],
          kun: ["ある.く", "あゆ.む"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 468,
      kanji: "言う",
      reading: "いう",
      meanings: {
        ja: "言う",
        en: "to say",
        zh: "说",
        tw: "說",
        ko: "말하다",
        vi: "nói",
        th: "พูดว่า",
        my: "ဆိုသည်",
        km: "និយាយ",
      },
      furigana: [
        {
          rb: "言う",
          rt: "いう",
        },
      ],
      kanjiInfo: [
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 469,
      kanji: "居る",
      reading: "いる",
      meanings: {
        ja: "居る（有情物）",
        en: "to be (animate)",
        zh: "在（有生命）",
        tw: "在（有生命）",
        ko: "있다(사람/동물)",
        vi: "có/ở (sinh vật)",
        th: "มี/อยู่ (สิ่งมีชีวิต)",
        my: "ရှိ (အသက်ရှူ)",
        km: "មាន/ស្ថិត (មានជីវិត)",
      },
      furigana: [
        {
          rb: "居る",
          rt: "いる",
        },
      ],
      kanjiInfo: [
        {
          char: "居",
          on: ["キョ", "コ"],
          kun: ["い.る", "-い", "お.る"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 470,
      kanji: "要る",
      reading: "いる",
      meanings: {
        ja: "要る",
        en: "to need",
        zh: "需要",
        tw: "需要",
        ko: "필요하다",
        vi: "cần",
        th: "ต้องการ",
        my: "လိုအပ်",
        km: "ត្រូវការ",
      },
      furigana: [
        {
          rb: "要る",
          rt: "いる",
        },
      ],
      kanjiInfo: [
        {
          char: "要",
          on: ["ヨウ"],
          kun: ["い.る", "かなめ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 471,
      kanji: "入れる",
      reading: "いれる",
      meanings: {
        ja: "入れる",
        en: "to put in; insert",
        zh: "放入",
        tw: "放入",
        ko: "넣다",
        vi: "cho vào",
        th: "ใส่เข้า",
        my: "ထည့်",
        km: "ដាក់ចូល",
      },
      furigana: [
        {
          rb: "入れる",
          rt: "いれる",
        },
      ],
      kanjiInfo: [
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 472,
      kanji: "歌う",
      reading: "うたう",
      meanings: {
        ja: "歌う",
        en: "to sing",
        zh: "唱歌",
        tw: "唱歌",
        ko: "노래하다",
        vi: "hát",
        th: "ร้องเพลง",
        my: "သီချင်းဆို",
        km: "ច្រៀង",
      },
      furigana: [
        {
          rb: "歌う",
          rt: "うたう",
        },
      ],
      kanjiInfo: [
        {
          char: "歌",
          on: ["カ"],
          kun: ["うた", "うた.う"],
          strokes: 14,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 473,
      kanji: "生まれる",
      reading: "うまれる",
      meanings: {
        ja: "生まれる",
        en: "to be born",
        zh: "出生",
        tw: "出生",
        ko: "태어나다",
        vi: "sinh ra",
        th: "เกิด",
        my: "ဖွားမွေး",
        km: "កើត",
      },
      furigana: [
        {
          rb: "生まれる",
          rt: "うまれる",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 474,
      kanji: "売る",
      reading: "うる",
      meanings: {
        ja: "売る",
        en: "to sell",
        zh: "卖",
        tw: "賣",
        ko: "팔다",
        vi: "bán",
        th: "ขาย",
        my: "ရောင်း",
        km: "លក់",
      },
      furigana: [
        {
          rb: "売る",
          rt: "うる",
        },
      ],
      kanjiInfo: [
        {
          char: "売",
          on: ["バイ"],
          kun: ["う.る", "う.れる"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 475,
      kanji: "起きる",
      reading: "おきる",
      meanings: {
        ja: "起きる",
        en: "to get up",
        zh: "起床",
        tw: "起床",
        ko: "일어나다",
        vi: "dậy",
        th: "ตื่น/ลุกขึ้น",
        my: "ထ",
        km: "ភ្ញាក់ឡើង",
      },
      furigana: [
        {
          rb: "起きる",
          rt: "おきる",
        },
      ],
      kanjiInfo: [
        {
          char: "起",
          on: ["キ"],
          kun: ["お.きる", "お.こる", "お.こす", "おこ.す", "た.つ"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 476,
      kanji: "置く",
      reading: "おく",
      meanings: {
        ja: "置く",
        en: "to put; place",
        zh: "放; 置",
        tw: "放；置",
        ko: "놓다",
        vi: "đặt; để",
        th: "วาง",
        my: "ထား",
        km: "ដាក់",
      },
      furigana: [
        {
          rb: "置く",
          rt: "おく",
        },
      ],
      kanjiInfo: [
        {
          char: "置",
          on: ["チ"],
          kun: ["お.く", "-お.き"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 477,
      kanji: "教える",
      reading: "おしえる",
      meanings: {
        ja: "教える",
        en: "to teach; tell",
        zh: "教; 告诉",
        tw: "教；告訴",
        ko: "가르치다",
        vi: "dạy; chỉ",
        th: "สอน; บอก",
        my: "သင်ပေး; ပြောပြ",
        km: "បង្រៀន; ប្រាប់",
      },
      furigana: [
        {
          rb: "教える",
          rt: "おしえる",
        },
      ],
      kanjiInfo: [
        {
          char: "教",
          on: ["キョウ"],
          kun: ["おし.える", "おそ.わる"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 478,
      kanji: "押す",
      reading: "おす",
      meanings: {
        ja: "押す",
        en: "to push",
        zh: "推",
        tw: "推",
        ko: "밀다",
        vi: "đẩy",
        th: "ผลัก",
        my: "တွန်း",
        km: "រុញ",
      },
      furigana: [
        {
          rb: "押す",
          rt: "おす",
        },
      ],
      kanjiInfo: [
        {
          char: "押",
          on: ["オウ"],
          kun: ["お.す", "お.し-", "お.っ-", "お.さえる", "おさ.える"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 479,
      kanji: "覚える",
      reading: "おぼえる",
      meanings: {
        ja: "覚える",
        en: "to memorize; remember",
        zh: "记住",
        tw: "記住",
        ko: "외우다; 기억하다",
        vi: "nhớ; ghi nhớ",
        th: "จำ",
        my: "မှတ်မိ",
        km: "ចងចាំ",
      },
      furigana: [
        {
          rb: "覚える",
          rt: "おぼえる",
        },
      ],
      kanjiInfo: [
        {
          char: "覚",
          on: ["カク"],
          kun: ["おぼ.える", "さ.ます", "さ.める", "さと.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 480,
      kanji: "泳ぐ",
      reading: "およぐ",
      meanings: {
        ja: "泳ぐ",
        en: "to swim",
        zh: "游泳",
        tw: "游泳",
        ko: "수영하다",
        vi: "bơi",
        th: "ว่ายน้ำ",
        my: "ရေကူး",
        km: "ហែលទឹក",
      },
      furigana: [
        {
          rb: "泳ぐ",
          rt: "およぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "泳",
          on: ["エイ"],
          kun: ["およ.ぐ"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 481,
      kanji: "降りる",
      reading: "おりる",
      meanings: {
        ja: "降りる",
        en: "to get off; descend",
        zh: "下（车/山）",
        tw: "下（車/山）",
        ko: "내리다",
        vi: "xuống",
        th: "ลง (รถ/เขา)",
        my: "ဆင်း",
        km: "ចុះ",
      },
      furigana: [
        {
          rb: "降りる",
          rt: "おりる",
        },
      ],
      kanjiInfo: [
        {
          char: "降",
          on: ["コウ", "ゴ"],
          kun: ["お.りる", "お.ろす", "ふ.る", "ふ.り", "くだ.る", "くだ.す"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 482,
      kanji: "終る",
      reading: "おわる",
      meanings: {
        ja: "終わる",
        en: "to end; finish",
        zh: "结束",
        tw: "結束",
        ko: "끝나다",
        vi: "kết thúc",
        th: "จบ",
        my: "ပြီးဆုံး",
        km: "បញ្ចប់",
      },
      furigana: [
        {
          rb: "終る",
          rt: "おわる",
        },
      ],
      kanjiInfo: [
        {
          char: "終",
          on: ["シュウ"],
          kun: ["お.わる", "-お.わる", "おわ.る", "お.える", "つい", "つい.に"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 483,
      kanji: "買う",
      reading: "かう",
      meanings: {
        ja: "買う",
        en: "to buy",
        zh: "买",
        tw: "買",
        ko: "사다",
        vi: "mua",
        th: "ซื้อ",
        my: "ဝယ်",
        km: "ទិញ",
      },
      furigana: [
        {
          rb: "買う",
          rt: "かう",
        },
      ],
      kanjiInfo: [
        {
          char: "買",
          on: ["バイ"],
          kun: ["か.う"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 484,
      kanji: "返す",
      reading: "かえす",
      meanings: {
        ja: "返す",
        en: "to return (something)",
        zh: "归还",
        tw: "歸還",
        ko: "돌려주다",
        vi: "trả lại",
        th: "คืน",
        my: "ပြန်ပေး",
        km: "ត្រឡប់ឲ្យ",
      },
      furigana: [
        {
          rb: "返す",
          rt: "かえす",
        },
      ],
      kanjiInfo: [
        {
          char: "返",
          on: ["ヘン"],
          kun: ["かえ.す", "-かえ.す", "かえ.る", "-かえ.る"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 485,
      kanji: "帰る",
      reading: "かえる",
      meanings: {
        ja: "帰る",
        en: "to return (home)",
        zh: "回家/返回",
        tw: "回家/返回",
        ko: "돌아가다",
        vi: "về",
        th: "กลับ",
        my: "ပြန်သွား",
        km: "ត្រលប់",
      },
      furigana: [
        {
          rb: "帰る",
          rt: "かえる",
        },
      ],
      kanjiInfo: [
        {
          char: "帰",
          on: ["キ"],
          kun: ["かえ.る", "かえ.す", "おく.る", "とつ.ぐ"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 486,
      kanji: "書く",
      reading: "かく",
      meanings: {
        ja: "書く",
        en: "to write",
        zh: "写; 写字",
        tw: "寫; 書寫",
        ko: "쓰다",
        vi: "viết",
        th: "เขียน",
        my: "ရေး",
        km: "សរសេរ",
      },
      furigana: [
        {
          rb: "書く",
          rt: "かく",
        },
      ],
      kanjiInfo: [
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 487,
      kanji: "掛ける",
      reading: "かける",
      meanings: {
        ja: "掛ける",
        en: "to hang (up); to call (phone)",
        zh: "挂; 打（电话）",
        tw: "掛；打（電話）",
        ko: "걸다",
        vi: "treo; gọi điện",
        th: "แขวน; โทร",
        my: "แขวน/ဖုန်းခေါ်",
        km: "ព្យួរ; ទូរស័ព្ទ",
      },
      furigana: [
        {
          rb: "掛ける",
          rt: "かける",
        },
      ],
      kanjiInfo: [
        {
          char: "掛",
          on: ["カイ", "ケイ"],
          kun: [
            "か.ける",
            "-か.ける",
            "か.け",
            "-か.け",
            "-が.け",
            "か.かる",
            "-か.かる",
            "-が.かる",
            "か.かり",
            "-が.かり",
            "かかり",
            "-がかり",
          ],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 488,
      kanji: "貸す",
      reading: "かす",
      meanings: {
        ja: "貸す",
        en: "to lend",
        zh: "借出",
        tw: "借出",
        ko: "빌려주다",
        vi: "cho mượn",
        th: "ให้ยืม",
        my: "ချေးပေး",
        km: "ខ្ចីឲ្យ",
      },
      furigana: [
        {
          rb: "貸す",
          rt: "かす",
        },
      ],
      kanjiInfo: [
        {
          char: "貸",
          on: ["タイ"],
          kun: ["か.す", "か.し-", "かし-"],
          strokes: 12,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 489,
      kanji: "借りる",
      reading: "かりる",
      meanings: {
        ja: "借りる",
        en: "to borrow; rent",
        zh: "借; 租",
        tw: "借；租",
        ko: "빌리다",
        vi: "mượn; thuê",
        th: "ยืม; เช่า",
        my: "အခလုပ်ယူ/ငှား",
        km: "ខ្ចី; ជួល",
      },
      furigana: [
        {
          rb: "借りる",
          rt: "かりる",
        },
      ],
      kanjiInfo: [
        {
          char: "借",
          on: ["シャク"],
          kun: ["か.りる"],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 490,
      kanji: "消える",
      reading: "きえる",
      meanings: {
        ja: "消える（自）",
        en: "to go out; disappear",
        zh: "消失; 熄灭",
        tw: "消失；熄滅",
        ko: "꺼지다; 사라지다",
        vi: "tắt; biến mất",
        th: "ดับ; หายไป",
        my: "ပျောက်/ငြိမ်း",
        km: "ភ្លឺរលត់; អស់ទៅ",
      },
      furigana: [
        {
          rb: "消える",
          rt: "きえる",
        },
      ],
      kanjiInfo: [
        {
          char: "消",
          on: ["ショウ"],
          kun: ["き.える", "け.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 491,
      kanji: "聞く",
      reading: "きく",
      meanings: {
        ja: "聞く",
        en: "to hear; listen; ask",
        zh: "听; 问",
        tw: "聽；問",
        ko: "듣다; 묻다",
        vi: "nghe; hỏi",
        th: "ฟัง; ถาม",
        my: "နားထောင်; မေး",
        km: "ស្តាប់; សួរ",
      },
      furigana: [
        {
          rb: "聞く",
          rt: "きく",
        },
      ],
      kanjiInfo: [
        {
          char: "聞",
          on: ["ブン", "モン"],
          kun: ["き.く", "き.こえる"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 492,
      kanji: "切る",
      reading: "きる",
      meanings: {
        ja: "切る",
        en: "to cut",
        zh: "切; 剪",
        tw: "切；剪",
        ko: "자르다",
        vi: "cắt",
        th: "ตัด",
        my: "ပြတ်တောက်",
        km: "កាត់",
      },
      furigana: [
        {
          rb: "切る",
          rt: "きる",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 493,
      kanji: "着る",
      reading: "きる",
      meanings: {
        ja: "着る",
        en: "to wear (from shoulders down)",
        zh: "穿（衣服）",
        tw: "穿（衣服）",
        ko: "입다",
        vi: "mặc (áo)",
        th: "สวม (เสื้อผ้า)",
        my: "ဝတ်",
        km: "ពាក់ (អាវ)",
      },
      furigana: [
        {
          rb: "着る",
          rt: "きる",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 494,
      kanji: "曇る",
      reading: "くもる",
      meanings: {
        ja: "曇る",
        en: "to become cloudy",
        zh: "多云",
        tw: "多雲",
        ko: "구름끼다",
        vi: "trở nên nhiều mây",
        th: "มีเมฆมาก",
        my: "မိုးတိမ်ထူ",
        km: "អាប់អួរ",
      },
      furigana: [
        {
          rb: "曇る",
          rt: "くもる",
        },
      ],
      kanjiInfo: [
        {
          char: "曇",
          on: ["ドン"],
          kun: ["くも.る"],
          strokes: 16,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 495,
      kanji: "来る",
      reading: "くる",
      meanings: {
        ja: "来る",
        en: "to come",
        zh: "来",
        tw: "來",
        ko: "오다",
        vi: "đến",
        th: "มา",
        my: "လာ",
        km: "មក",
      },
      furigana: [
        {
          rb: "来る",
          rt: "くる",
        },
      ],
      kanjiInfo: [
        {
          char: "来",
          on: ["ライ", "タイ"],
          kun: [
            "く.る",
            "きた.る",
            "きた.す",
            "き.たす",
            "き.たる",
            "き",
            "こ",
          ],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 496,
      kanji: "消す",
      reading: "けす",
      meanings: {
        ja: "消す（他）",
        en: "to erase; turn off",
        zh: "消除; 关掉",
        tw: "消除；關掉",
        ko: "지우다; 끄다",
        vi: "xóa; tắt",
        th: "ลบ; ปิด",
        my: "ဖျက်; ပိတ်",
        km: "លុប; បិទ",
      },
      furigana: [
        {
          rb: "消す",
          rt: "けす",
        },
      ],
      kanjiInfo: [
        {
          char: "消",
          on: ["ショウ"],
          kun: ["き.える", "け.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 497,
      kanji: "答える",
      reading: "こたえる",
      meanings: {
        ja: "答える",
        en: "to answer",
        zh: "回答",
        tw: "回答",
        ko: "대답하다",
        vi: "trả lời",
        th: "ตอบ",
        my: "အဖြေပြန်",
        km: "ឆ្លើយ",
      },
      furigana: [
        {
          rb: "答える",
          rt: "こたえる",
        },
      ],
      kanjiInfo: [
        {
          char: "答",
          on: ["トウ"],
          kun: ["こた.える", "こた.え"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 498,
      kanji: "困る",
      reading: "こまる",
      meanings: {
        ja: "困る",
        en: "to be troubled; in a bind",
        zh: "为难; 困扰",
        tw: "為難；困擾",
        ko: "곤란하다",
        vi: "khó xử; khốn đốn",
        th: "ลำบากใจ",
        my: "ဒုက္ခရောက်",
        km: "លំបាក",
      },
      furigana: [
        {
          rb: "困る",
          rt: "こまる",
        },
      ],
      kanjiInfo: [
        {
          char: "困",
          on: ["コン"],
          kun: ["こま.る"],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 499,
      kanji: "咲く",
      reading: "さく",
      meanings: {
        ja: "咲く",
        en: "to bloom",
        zh: "开花",
        tw: "開花",
        ko: "피다",
        vi: "nở hoa",
        th: "บาน",
        my: "ပွင့်",
        km: "ផុសផង/ឆ្លាក់ផ្កា",
      },
      furigana: [
        {
          rb: "咲く",
          rt: "さく",
        },
      ],
      kanjiInfo: [
        {
          char: "咲",
          on: ["ショウ"],
          kun: ["さ.く", "-ざき"],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 500,
      kanji: "差す",
      reading: "さす",
      meanings: {
        ja: "差す",
        en: "to shine; to hold up (umbrella)",
        zh: "照耀; 撑伞",
        tw: "照耀；撐傘",
        ko: "비치다; 우산쓰다",
        vi: "chiếu; che (ô)",
        th: "ส่อง; กางร่ม",
        my: "တောက်ပ; ကာကွယ် (ထီး)",
        km: "បំភ្លឺ; កាន់ឆ័ត្រ",
      },
      furigana: [
        {
          rb: "差す",
          rt: "さす",
        },
      ],
      kanjiInfo: [
        {
          char: "差",
          on: ["サ"],
          kun: ["さ.す", "さ.し"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 501,
      kanji: "死ぬ",
      reading: "しぬ",
      meanings: {
        ja: "死ぬ",
        en: "to die",
        zh: "死",
        tw: "死",
        ko: "죽다",
        vi: "chết",
        th: "ตาย",
        my: "သေ",
        km: "ស្លាប់",
      },
      furigana: [
        {
          rb: "死ぬ",
          rt: "しぬ",
        },
      ],
      kanjiInfo: [
        {
          char: "死",
          on: ["シ"],
          kun: ["し.ぬ", "し.に-"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 502,
      kanji: "閉まる",
      reading: "しまる",
      meanings: {
        ja: "閉まる（自）",
        en: "to be closed; shut",
        zh: "关着",
        tw: "關著",
        ko: "닫히다",
        vi: "đóng (tự)",
        th: "ปิดอยู่",
        my: "ပိတ်နေ",
        km: "បិទ (អកម្ម)",
      },
      furigana: [
        {
          rb: "閉まる",
          rt: "しまる",
        },
      ],
      kanjiInfo: [
        {
          char: "閉",
          on: ["ヘイ"],
          kun: ["と.じる", "と.ざす", "し.める", "し.まる", "た.てる"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 503,
      kanji: "閉める",
      reading: "しめる",
      meanings: {
        ja: "閉める（他）",
        en: "to close; shut",
        zh: "关闭",
        tw: "關閉",
        ko: "닫다",
        vi: "đóng (tha)",
        th: "ปิด",
        my: "ပိတ်",
        km: "បិទ (កម្ម)",
      },
      furigana: [
        {
          rb: "閉める",
          rt: "しめる",
        },
      ],
      kanjiInfo: [
        {
          char: "閉",
          on: ["ヘイ"],
          kun: ["と.じる", "と.ざす", "し.める", "し.まる", "た.てる"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 504,
      kanji: "締める",
      reading: "しめる",
      meanings: {
        ja: "締める",
        en: "to tighten; tie",
        zh: "系紧; 扎",
        tw: "繫緊；綁",
        ko: "조이다; 매다",
        vi: "thắt; buộc",
        th: "รัด; ผูก",
        my: "ဆွဲတံ; ချည်",
        km: "រឹត; ចង",
      },
      furigana: [
        {
          rb: "締める",
          rt: "しめる",
        },
      ],
      kanjiInfo: [
        {
          char: "締",
          on: ["テイ"],
          kun: ["し.まる", "し.まり", "し.める", "-し.め", "-じ.め"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 505,
      kanji: "知る",
      reading: "しる",
      meanings: {
        ja: "知る",
        en: "to know",
        zh: "知道",
        tw: "知道",
        ko: "알다",
        vi: "biết",
        th: "รู้",
        my: "သိ",
        km: "ដឹង",
      },
      furigana: [
        {
          rb: "知る",
          rt: "しる",
        },
      ],
      kanjiInfo: [
        {
          char: "知",
          on: ["チ"],
          kun: ["し.る", "し.らせる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 506,
      kanji: "吸う",
      reading: "すう",
      meanings: {
        ja: "吸う",
        en: "to smoke; inhale",
        zh: "吸; 抽（烟）",
        tw: "吸；抽（菸）",
        ko: "피우다; 들이마시다",
        vi: "hút; hít",
        th: "สูบ/ดูด",
        my: "သောက်ဆေးလိပ်; စုပ်",
        km: "ជក់; ស្រូប",
      },
      furigana: [
        {
          rb: "吸う",
          rt: "すう",
        },
      ],
      kanjiInfo: [
        {
          char: "吸",
          on: ["キュウ"],
          kun: ["す.う"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 507,
      kanji: "住む",
      reading: "すむ",
      meanings: {
        ja: "住む",
        en: "to live; reside",
        zh: "居住",
        tw: "居住",
        ko: "살다",
        vi: "sống; cư trú",
        th: "อาศัยอยู่",
        my: "နေသည်",
        km: "រស់នៅ",
      },
      furigana: [
        {
          rb: "住む",
          rt: "すむ",
        },
      ],
      kanjiInfo: [
        {
          char: "住",
          on: ["ジュウ", "ヂュウ", "チュウ"],
          kun: ["す.む", "す.まう", "-ず.まい"],
          strokes: 7,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
