export const n5part2 = {
  Lesson2: [
    {
      id: 51,
      kanji: "お皿",
      reading: "おさら",
      meanings: {
        ja: "お皿",
        en: "plate",
        zh: "盘子",
        tw: "盤子",
        ko: "접시",
        vi: "đĩa",
        th: "จาน",
        my: "ပန်းကန်",
        km: "ចាន",
      },
      furigana: [
        {
          rb: "お皿",
          rt: "おさら",
        },
      ],
      kanjiInfo: [
        {
          char: "皿",
          on: ["ベイ"],
          kun: ["さら"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 52,
      kanji: "お茶",
      reading: "おちゃ",
      meanings: {
        ja: "お茶",
        en: "tea (esp. green or barley)",
        zh: "茶",
        tw: "茶",
        ko: "차",
        vi: "trà",
        th: "ชา",
        my: "လက်ဖက်ရည်",
        km: "តែ",
      },
      furigana: [
        {
          rb: "お茶",
          rt: "おちゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "茶",
          on: ["チャ", "サ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 53,
      kanji: "お手洗い",
      reading: "おてあらい",
      meanings: {
        ja: "お手洗い",
        en: "toilet",
        zh: "洗手间",
        tw: "洗手間",
        ko: "화장실",
        vi: "nhà vệ sinh",
        th: "ห้องน้ำ",
        my: "အိမ်သာ",
        km: "បង្គន់",
      },
      furigana: [
        {
          rb: "お手洗い",
          rt: "おてあらい",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "洗",
          on: ["セン"],
          kun: ["あら.う"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 54,
      kanji: "お父さん",
      reading: "おとうさん",
      meanings: {
        ja: "お父さん",
        en: "father",
        zh: "爸爸",
        tw: "爸爸",
        ko: "아버지",
        vi: "bố",
        th: "คุณพ่อ",
        my: "အဖေ",
        km: "ប៉ា",
      },
      furigana: [
        {
          rb: "お父さん",
          rt: "おとうさん",
        },
      ],
      kanjiInfo: [
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 55,
      kanji: "弟",
      reading: "おとうと",
      meanings: {
        ja: "弟",
        en: "younger brother",
        zh: "弟弟",
        tw: "弟弟",
        ko: "남동생",
        vi: "em trai",
        th: "น้องชาย",
        my: "ညီ",
        km: "ប្អូនប្រុស",
      },
      furigana: [
        {
          rb: "弟",
          rt: "おとうと",
        },
      ],
      kanjiInfo: [
        {
          char: "弟",
          on: ["テイ", "ダイ", "デ"],
          kun: ["おとうと"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 56,
      kanji: "男",
      reading: "おとこ",
      meanings: {
        ja: "男",
        en: "man",
        zh: "男人",
        tw: "男人",
        ko: "남자",
        vi: "người đàn ông",
        th: "ผู้ชาย",
        my: "ယောက္ခ",
        km: "បុរស",
      },
      furigana: [
        {
          rb: "男",
          rt: "おとこ",
        },
      ],
      kanjiInfo: [
        {
          char: "男",
          on: ["ダン", "ナン"],
          kun: ["おとこ", "お"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 57,
      kanji: "一昨日",
      reading: "おととい",
      meanings: {
        ja: "一昨日",
        en: "day before yesterday",
        zh: "前天",
        tw: "前天",
        ko: "그저께",
        vi: "hôm kia",
        th: "เมื่อวานซืน",
        my: "တစ်မနေ့က",
        km: "ម្សិលមិញមុន",
      },
      furigana: [
        {
          rb: "一昨日",
          rt: "おととい",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "昨",
          on: ["サク"],
          kun: [],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 58,
      kanji: "大人",
      reading: "おとな",
      meanings: {
        ja: "大人",
        en: "adult",
        zh: "大人",
        tw: "大人",
        ko: "어른",
        vi: "người lớn",
        th: "ผู้ใหญ่",
        my: "လူကြီး",
        km: "មនុស្សពេញវ័យ",
      },
      furigana: [
        {
          rb: "大人",
          rt: "おとな",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 59,
      kanji: "お腹",
      reading: "おなか",
      meanings: {
        ja: "お腹",
        en: "belly",
        zh: "肚子",
        tw: "肚子",
        ko: "배",
        vi: "bụng",
        th: "ท้อง",
        my: "ဝမ်းဗိုက်",
        km: "ពោះ",
      },
      furigana: [
        {
          rb: "お腹",
          rt: "おなか",
        },
      ],
      kanjiInfo: [
        {
          char: "腹",
          on: ["フク"],
          kun: ["はら"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 60,
      kanji: "お兄さん",
      reading: "おにいさん",
      meanings: {
        ja: "お兄さん",
        en: "older brother",
        zh: "哥哥",
        tw: "哥哥",
        ko: "형/오빠",
        vi: "anh trai",
        th: "พี่ชาย",
        my: "အစ်ကို",
        km: "បងប្រុស",
      },
      furigana: [
        {
          rb: "お兄さん",
          rt: "おにいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "兄",
          on: ["ケイ", "キョウ"],
          kun: ["あに"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 61,
      kanji: "お姉さん",
      reading: "おねえさん",
      meanings: {
        ja: "お姉さん",
        en: "older sister",
        zh: "姐姐",
        tw: "姐姐",
        ko: "누나/언니",
        vi: "chị gái",
        th: "พี่สาว",
        my: "အစ်မ",
        km: "បងស្រី",
      },
      furigana: [
        {
          rb: "お姉さん",
          rt: "おねえさん",
        },
      ],
      kanjiInfo: [
        {
          char: "姉",
          on: ["シ"],
          kun: ["あね", "はは"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 62,
      kanji: "お風呂",
      reading: "おふろ",
      meanings: {
        ja: "お風呂",
        en: "bath",
        zh: "浴室；澡堂",
        tw: "浴室；澡堂",
        ko: "목욕",
        vi: "bồn tắm; tắm",
        th: "อ่างอาบน้ำ",
        my: "ရေချိုးကန်",
        km: "អាងងូតទឹក",
      },
      furigana: [
        {
          rb: "お風呂",
          rt: "おふろ",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "呂",
          on: ["ロ", "リョ"],
          kun: ["せぼね"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 63,
      kanji: "お弁当",
      reading: "おべんとう",
      meanings: {
        ja: "お弁当",
        en: "bento",
        zh: "便当",
        tw: "便當",
        ko: "도시락",
        vi: "cơm hộp",
        th: "ข้าวกล่อง",
        my: "ထမင်းအုပ်",
        km: "អាហារបន្ទាន់ (បេនតូ)",
      },
      furigana: [
        {
          rb: "お弁当",
          rt: "おべんとう",
        },
      ],
      kanjiInfo: [
        {
          char: "弁",
          on: ["ベン", "ヘン"],
          kun: ["かんむり", "わきま.える", "わ.ける", "はなびら", "あらそ.う"],
          strokes: 5,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 64,
      kanji: "音楽",
      reading: "おんがく",
      meanings: {
        ja: "音楽",
        en: "music",
        zh: "音乐",
        tw: "音樂",
        ko: "음악",
        vi: "âm nhạc",
        th: "ดนตรี",
        my: "ဂီတ",
        km: "តន្រ្តី",
      },
      furigana: [
        {
          rb: "音楽",
          rt: "おんがく",
        },
      ],
      kanjiInfo: [
        {
          char: "音",
          on: ["オン", "イン", "-ノン"],
          kun: ["おと", "ね"],
          strokes: 9,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "楽",
          on: ["ガク", "ラク", "ゴウ"],
          kun: ["たの.しい", "たの.しむ", "この.む"],
          strokes: 13,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 65,
      kanji: "女",
      reading: "おんな",
      meanings: {
        ja: "女",
        en: "woman",
        zh: "女人",
        tw: "女人",
        ko: "여자",
        vi: "người phụ nữ",
        th: "ผู้หญิง",
        my: "မိန်းမ",
        km: "ស្ត្រី",
      },
      furigana: [
        {
          rb: "女",
          rt: "おんな",
        },
      ],
      kanjiInfo: [
        {
          char: "女",
          on: ["ジョ", "ニョ", "ニョウ"],
          kun: ["おんな", "め"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 66,
      kanji: "外国",
      reading: "がいこく",
      meanings: {
        ja: "外国",
        en: "foreign country",
        zh: "外国",
        tw: "外國",
        ko: "외국",
        vi: "nước ngoài",
        th: "ต่างประเทศ",
        my: "နိုင်ငံခြား",
        km: "បរទេស",
      },
      furigana: [
        {
          rb: "外国",
          rt: "がいこく",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "国",
          on: ["コク"],
          kun: ["くに"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 67,
      kanji: "外国人",
      reading: "がいこくじん",
      meanings: {
        ja: "外国人",
        en: "foreigner",
        zh: "外国人",
        tw: "外國人",
        ko: "외국인",
        vi: "người nước ngoài",
        th: "ชาวต่างชาติ",
        my: "နိုင်ငံခြားသား",
        km: "ជនបរទេស",
      },
      furigana: [
        {
          rb: "外国人",
          rt: "がいこくじん",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "国",
          on: ["コク"],
          kun: ["くに"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 68,
      kanji: "会社",
      reading: "かいしゃ",
      meanings: {
        ja: "会社",
        en: "company",
        zh: "公司",
        tw: "公司",
        ko: "회사",
        vi: "công ty",
        th: "บริษัท",
        my: "ကုမ္ပဏီ",
        km: "ក្រុមហ៊ុន",
      },
      furigana: [
        {
          rb: "会社",
          rt: "かいしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "社",
          on: ["シャ"],
          kun: ["やしろ"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 69,
      kanji: "階段",
      reading: "かいだん",
      meanings: {
        ja: "階段",
        en: "stairs",
        zh: "楼梯",
        tw: "樓梯",
        ko: "계단",
        vi: "cầu thang",
        th: "บันได",
        my: "ထစ်",
        km: "ជណ្ដើរ",
      },
      furigana: [
        {
          rb: "階段",
          rt: "かいだん",
        },
      ],
      kanjiInfo: [
        {
          char: "階",
          on: ["カイ"],
          kun: ["きざはし"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "段",
          on: ["ダン", "タン"],
          kun: [],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 70,
      kanji: "買い物",
      reading: "かいもの",
      meanings: {
        ja: "買い物",
        en: "shopping",
        zh: "购物",
        tw: "購物",
        ko: "쇼핑",
        vi: "mua sắm",
        th: "ช้อปปิ้ง",
        my: "ဈေးဝယ်",
        km: "ការទិញឥវ៉ាន់",
      },
      furigana: [
        {
          rb: "買い物",
          rt: "かいもの",
        },
      ],
      kanjiInfo: [
        {
          char: "買",
          on: ["バイ"],
          kun: ["か.う"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 71,
      kanji: "顔",
      reading: "かお",
      meanings: {
        ja: "顔",
        en: "face",
        zh: "脸",
        tw: "臉",
        ko: "얼굴",
        vi: "khuôn mặt",
        th: "ใบหน้า",
        my: "မျက်နှာ",
        km: "មុខ",
      },
      furigana: [
        {
          rb: "顔",
          rt: "かお",
        },
      ],
      kanjiInfo: [
        {
          char: "顔",
          on: ["ガン"],
          kun: ["かお"],
          strokes: 18,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 72,
      kanji: "鍵",
      reading: "かぎ",
      meanings: {
        ja: "鍵",
        en: "key",
        zh: "钥匙",
        tw: "鑰匙",
        ko: "열쇠",
        vi: "chìa khóa",
        th: "กุญแจ",
        my: "သော့",
        km: "សោ",
      },
      furigana: [
        {
          rb: "鍵",
          rt: "かぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "鍵",
          on: ["ケン"],
          kun: ["かぎ"],
          strokes: 17,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 73,
      kanji: "学生",
      reading: "がくせい",
      meanings: {
        ja: "学生",
        en: "student (esp. university)",
        zh: "学生",
        tw: "學生",
        ko: "학생",
        vi: "sinh viên; học sinh",
        th: "นักศึกษา; นักเรียน",
        my: "ကျောင်းသား",
        km: "និស្សិត; សិស្ស",
      },
      furigana: [
        {
          rb: "学生",
          rt: "がくせい",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 74,
      kanji: "傘",
      reading: "かさ",
      meanings: {
        ja: "傘",
        en: "umbrella",
        zh: "伞",
        tw: "傘",
        ko: "우산",
        vi: "cái ô",
        th: "ร่ม",
        my: "ထီး",
        km: "ឆ័ត្រ",
      },
      furigana: [
        {
          rb: "傘",
          rt: "かさ",
        },
      ],
      kanjiInfo: [
        {
          char: "傘",
          on: ["サン"],
          kun: ["かさ"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 75,
      kanji: "風",
      reading: "かぜ",
      meanings: {
        ja: "風",
        en: "wind",
        zh: "风",
        tw: "風",
        ko: "바람",
        vi: "gió",
        th: "ลม",
        my: "လေ",
        km: "ខ្យល់",
      },
      furigana: [
        {
          rb: "風",
          rt: "かぜ",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 76,
      kanji: "風邪",
      reading: "かぜ",
      meanings: {
        ja: "風邪",
        en: "cold (illness)",
        zh: "感冒",
        tw: "感冒",
        ko: "감기",
        vi: "cảm lạnh",
        th: "หวัด",
        my: "အအေးမိ",
        km: "ផ្តាសាយ",
      },
      furigana: [
        {
          rb: "風邪",
          rt: "かぜ",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "邪",
          on: ["ジャ"],
          kun: ["よこし.ま"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 77,
      kanji: "方",
      reading: "かた",
      meanings: {
        ja: "方",
        en: "direction",
        zh: "方向",
        tw: "方向",
        ko: "방향",
        vi: "hướng",
        th: "ทิศทาง",
        my: "ဦးတည်ရာ",
        km: "ទិសដៅ",
      },
      furigana: [
        {
          rb: "方",
          rt: "かた",
        },
      ],
      kanjiInfo: [
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 78,
      kanji: "家族",
      reading: "かぞく",
      meanings: {
        ja: "家族",
        en: "family",
        zh: "家人",
        tw: "家人",
        ko: "가족",
        vi: "gia đình",
        th: "ครอบครัว",
        my: "မိသားစု",
        km: "គ្រួសារ",
      },
      furigana: [
        {
          rb: "家族",
          rt: "かぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "族",
          on: ["ゾク"],
          kun: [],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 79,
      kanji: "片仮名",
      reading: "かたかな",
      meanings: {
        ja: "片仮名",
        en: "katakana",
        zh: "片假名",
        tw: "片假名",
        ko: "가타카나",
        vi: "chữ Katakana",
        th: "คาตาคานะ",
        my: "ကာတာကနာ",
        km: "កាតាកាណា",
      },
      furigana: [
        {
          rb: "片仮名",
          rt: "かたかな",
        },
      ],
      kanjiInfo: [
        {
          char: "片",
          on: ["ヘン"],
          kun: ["かた-", "かた"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "仮",
          on: ["カ", "ケ"],
          kun: ["かり", "かり-"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 80,
      kanji: "学校",
      reading: "がっこう",
      meanings: {
        ja: "学校",
        en: "school",
        zh: "学校",
        tw: "學校",
        ko: "학교",
        vi: "trường học",
        th: "โรงเรียน",
        my: "ကျောင်း",
        km: "សាលា",
      },
      furigana: [
        {
          rb: "学校",
          rt: "がっこう",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "校",
          on: ["コウ", "キョウ"],
          kun: [],
          strokes: 10,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 81,
      kanji: "カップ",
      reading: "カップ",
      meanings: {
        ja: "カップ",
        en: "cup (drinking vessel)",
        zh: "杯子",
        tw: "杯子",
        ko: "컵",
        vi: "cốc; ly",
        th: "ถ้วย",
        my: "ခွက်",
        km: "ពែង",
      },
      furigana: [
        {
          rb: "カップ",
          rt: "カップ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 82,
      kanji: "家庭",
      reading: "かてい",
      meanings: {
        ja: "家庭",
        en: "home; household",
        zh: "家庭",
        tw: "家庭",
        ko: "가정",
        vi: "gia đình (tổ ấm)",
        th: "ครอบครัว",
        my: "အိမ်ထောင်",
        km: "គ្រួសារ",
      },
      furigana: [
        {
          rb: "家庭",
          rt: "かてい",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "庭",
          on: ["テイ"],
          kun: ["にわ"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 83,
      kanji: "角",
      reading: "かど",
      meanings: {
        ja: "角",
        en: "corner",
        zh: "角落",
        tw: "角落",
        ko: "모퉁이",
        vi: "góc",
        th: "มุม",
        my: "ထောင့်",
        km: "ជ្រុង",
      },
      furigana: [
        {
          rb: "角",
          rt: "かど",
        },
      ],
      kanjiInfo: [
        {
          char: "角",
          on: ["カク"],
          kun: ["かど", "つの"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 84,
      kanji: "花瓶",
      reading: "かびん",
      meanings: {
        ja: "花瓶",
        en: "(flower) vase",
        zh: "花瓶",
        tw: "花瓶",
        ko: "꽃병",
        vi: "bình hoa",
        th: "แจกัน",
        my: "ပန်းပုံး",
        km: "ដបទទូច",
      },
      furigana: [
        {
          rb: "花瓶",
          rt: "かびん",
        },
      ],
      kanjiInfo: [
        {
          char: "花",
          on: ["カ", "ケ"],
          kun: ["はな"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "瓶",
          on: ["ビン", "ヘイ"],
          kun: ["かめ"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 85,
      kanji: "紙",
      reading: "かみ",
      meanings: {
        ja: "紙",
        en: "paper",
        zh: "纸",
        tw: "紙",
        ko: "종이",
        vi: "giấy",
        th: "กระดาษ",
        my: "စာရွက်",
        km: "ក្រដាស",
      },
      furigana: [
        {
          rb: "紙",
          rt: "かみ",
        },
      ],
      kanjiInfo: [
        {
          char: "紙",
          on: ["シ"],
          kun: ["かみ"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 86,
      kanji: "カメラ",
      reading: "カメラ",
      meanings: {
        ja: "カメラ",
        en: "camera",
        zh: "相机",
        tw: "相機",
        ko: "카메라",
        vi: "máy ảnh",
        th: "กล้องถ่ายรูป",
        my: "ကင်မရာ",
        km: "ម៉ាស៊ីនថតរូប",
      },
      furigana: [
        {
          rb: "カメラ",
          rt: "カメラ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 87,
      kanji: "火曜日",
      reading: "かようび",
      meanings: {
        ja: "火曜日",
        en: "Tuesday",
        zh: "星期二",
        tw: "星期二",
        ko: "화요일",
        vi: "thứ ba",
        th: "วันอังคาร",
        my: "အင်္ဂါနေ့",
        km: "ថ្ងៃអង្គារ",
      },
      furigana: [
        {
          rb: "火曜日",
          rt: "かようび",
        },
      ],
      kanjiInfo: [
        {
          char: "火",
          on: ["カ"],
          kun: ["ひ", "-び", "ほ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "曜",
          on: ["ヨウ"],
          kun: [],
          strokes: 18,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 88,
      kanji: "体",
      reading: "からだ",
      meanings: {
        ja: "体",
        en: "body",
        zh: "身体",
        tw: "身體",
        ko: "몸",
        vi: "cơ thể",
        th: "ร่างกาย",
        my: "ကိုယ်ခန္ဓာ",
        km: "រាងកាយ",
      },
      furigana: [
        {
          rb: "体",
          rt: "からだ",
        },
      ],
      kanjiInfo: [
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 89,
      kanji: "カレンダー",
      reading: "カレンダー",
      meanings: {
        ja: "カレンダー",
        en: "calendar",
        zh: "日历",
        tw: "日曆",
        ko: "달력",
        vi: "lịch",
        th: "ปฏิทิน",
        my: "ပြက္ခဒိန်",
        km: "ប្រតិទិន",
      },
      furigana: [
        {
          rb: "カレンダー",
          rt: "カレンダー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 90,
      kanji: "漢字",
      reading: "かんじ",
      meanings: {
        ja: "漢字",
        en: "kanji",
        zh: "汉字",
        tw: "漢字",
        ko: "한자",
        vi: "chữ Hán",
        th: "คันจิ",
        my: "ဟန်ဇာ",
        km: "អក្សរចិន",
      },
      furigana: [
        {
          rb: "漢字",
          rt: "かんじ",
        },
      ],
      kanjiInfo: [
        {
          char: "漢",
          on: ["カン"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 91,
      kanji: "木",
      reading: "き",
      meanings: {
        ja: "木",
        en: "tree",
        zh: "树",
        tw: "樹",
        ko: "나무",
        vi: "cây",
        th: "ต้นไม้",
        my: "အပင်",
        km: "ដើមឈើ",
      },
      furigana: [
        {
          rb: "木",
          rt: "き",
        },
      ],
      kanjiInfo: [
        {
          char: "木",
          on: ["ボク", "モク"],
          kun: ["き", "こ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 92,
      kanji: "黄色",
      reading: "きいろ",
      meanings: {
        ja: "黄色",
        en: "yellow",
        zh: "黄色",
        tw: "黃色",
        ko: "노란색",
        vi: "màu vàng",
        th: "สีเหลือง",
        my: "အဝါရောင်",
        km: "ពណ៌លឿង",
      },
      furigana: [
        {
          rb: "黄色",
          rt: "きいろ",
        },
      ],
      kanjiInfo: [
        {
          char: "黄",
          on: ["コウ", "オウ"],
          kun: ["き", "こ-"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "色",
          on: ["ショク", "シキ"],
          kun: ["いろ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 93,
      kanji: "北",
      reading: "きた",
      meanings: {
        ja: "北",
        en: "north",
        zh: "北方",
        tw: "北方",
        ko: "북쪽",
        vi: "phía bắc",
        th: "ทิศเหนือ",
        my: "မြောက်",
        km: "ជើង",
      },
      furigana: [
        {
          rb: "北",
          rt: "きた",
        },
      ],
      kanjiInfo: [
        {
          char: "北",
          on: ["ホク"],
          kun: ["きた"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 94,
      kanji: "ギター",
      reading: "ギター",
      meanings: {
        ja: "ギター",
        en: "guitar",
        zh: "吉他",
        tw: "吉他",
        ko: "기타",
        vi: "đàn ghi-ta",
        th: "กีตาร์",
        my: "ဂီတာ",
        km: "ហ្គីតា",
      },
      furigana: [
        {
          rb: "ギター",
          rt: "ギター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 95,
      kanji: "喫茶店",
      reading: "きっさてん",
      meanings: {
        ja: "喫茶店",
        en: "coffee shop",
        zh: "咖啡店",
        tw: "咖啡店",
        ko: "다방; 커피숍",
        vi: "quán cà phê",
        th: "ร้านกาแฟ",
        my: "ကော်ဖီဆိုင်",
        km: "ហាងកាហ្វេ",
      },
      furigana: [
        {
          rb: "喫茶店",
          rt: "きっさてん",
        },
      ],
      kanjiInfo: [
        {
          char: "喫",
          on: ["キツ"],
          kun: ["の.む"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "茶",
          on: ["チャ", "サ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "店",
          on: ["テン"],
          kun: ["みせ", "たな"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 96,
      kanji: "切手",
      reading: "きって",
      meanings: {
        ja: "切手",
        en: "stamp (postage)",
        zh: "邮票",
        tw: "郵票",
        ko: "우표",
        vi: "tem thư",
        th: "แสตมป์",
        my: "တံဆိပ်စာ",
        km: "តែកប្រាក់ប្រៃសណីយ៍",
      },
      furigana: [
        {
          rb: "切手",
          rt: "きって",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 97,
      kanji: "切符",
      reading: "きっぷ",
      meanings: {
        ja: "切符",
        en: "ticket",
        zh: "票（车票等）",
        tw: "票（車票等）",
        ko: "표",
        vi: "vé (tàu/xe)",
        th: "ตั๋ว",
        my: "လက်မှတ်",
        km: "សំបុត្រ",
      },
      furigana: [
        {
          rb: "切符",
          rt: "きっぷ",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "符",
          on: ["フ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 98,
      kanji: "昨日",
      reading: "きのう",
      meanings: {
        ja: "昨日",
        en: "yesterday",
        zh: "昨天",
        tw: "昨天",
        ko: "어제",
        vi: "hôm qua",
        th: "เมื่อวาน",
        my: "မနေ့က",
        km: "ម្សិលមិញ",
      },
      furigana: [
        {
          rb: "昨日",
          rt: "きのう",
        },
      ],
      kanjiInfo: [
        {
          char: "昨",
          on: ["サク"],
          kun: [],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 99,
      kanji: "九",
      reading: "きゅう",
      meanings: {
        ja: "九",
        en: "nine",
        zh: "九",
        tw: "九",
        ko: "아홉",
        vi: "chín",
        th: "เก้า",
        my: "ကိုး",
        km: "ប៉ែត",
      },
      furigana: [
        {
          rb: "九",
          rt: "きゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "九",
          on: ["キュウ", "ク"],
          kun: ["ここの", "ここの.つ"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 100,
      kanji: "牛肉",
      reading: "ぎゅうにく",
      meanings: {
        ja: "牛肉",
        en: "beef",
        zh: "牛肉",
        tw: "牛肉",
        ko: "쇠고기",
        vi: "thịt bò",
        th: "เนื้อวัว",
        my: "အမဲသား",
        km: "សាច់គោ",
      },
      furigana: [
        {
          rb: "牛肉",
          rt: "ぎゅうにく",
        },
      ],
      kanjiInfo: [
        {
          char: "牛",
          on: ["ギュウ"],
          kun: ["うし"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "肉",
          on: ["ニク"],
          kun: ["しし"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
