export const n5part7 = {
  Lesson7: [
    {
      id: 301,
      kanji: "部屋",
      reading: "へや",
      meanings: {
        ja: "部屋",
        en: "room",
        zh: "房间",
        tw: "房間",
        ko: "방",
        vi: "phòng",
        th: "ห้อง",
        my: "အခန်း",
        km: "បន្ទប់",
      },
      furigana: [
        {
          rb: "部屋",
          rt: "へや",
        },
      ],
      kanjiInfo: [
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "屋",
          on: ["オク"],
          kun: ["や"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 302,
      kanji: "辺",
      reading: "へん",
      meanings: {
        ja: "辺",
        en: "area; vicinity",
        zh: "附近",
        tw: "附近",
        ko: "주변",
        vi: "khu vực",
        th: "บริเวณ",
        my: "ဧရိယာ",
        km: "តំបន់",
      },
      furigana: [
        {
          rb: "辺",
          rt: "へん",
        },
      ],
      kanjiInfo: [
        {
          char: "辺",
          on: ["ヘン"],
          kun: ["あた.り", "ほと.り", "-べ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 303,
      kanji: "ペン",
      reading: "ペン",
      meanings: {
        ja: "ペン",
        en: "pen",
        zh: "钢笔",
        tw: "鋼筆",
        ko: "펜",
        vi: "bút",
        th: "ปากกา",
        my: "ခဲပေါ်",
        km: "ប៊ិច",
      },
      furigana: [
        {
          rb: "ペン",
          rt: "ペン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 304,
      kanji: "帽子",
      reading: "ぼうし",
      meanings: {
        ja: "帽子",
        en: "hat",
        zh: "帽子",
        tw: "帽子",
        ko: "모자",
        vi: "mũ",
        th: "หมวก",
        my: "ဦးထုပ်",
        km: "មួក",
      },
      furigana: [
        {
          rb: "帽子",
          rt: "ぼうし",
        },
      ],
      kanjiInfo: [
        {
          char: "帽",
          on: ["ボウ", "モウ"],
          kun: ["ずきん", "おお.う"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 305,
      kanji: "ボールペン",
      reading: "ボールペン",
      meanings: {
        ja: "ボールペン",
        en: "ball-point pen",
        zh: "圆珠笔",
        tw: "原子筆",
        ko: "볼펜",
        vi: "bút bi",
        th: "ปากกาลูกลื่น",
        my: "ဘောပင်",
        km: "ប៊ិចកោរ",
      },
      furigana: [
        {
          rb: "ボールペン",
          rt: "ボールペン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 306,
      kanji: "外",
      reading: "ほか",
      meanings: {
        ja: "外",
        en: "another place; other",
        zh: "别处；其他",
        tw: "別處；其他",
        ko: "다른 곳",
        vi: "nơi khác",
        th: "ที่อื่น",
        my: "အခြား",
        km: "កន្លែងផ្សេង",
      },
      furigana: [
        {
          rb: "外",
          rt: "ほか",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 307,
      kanji: "ポケット",
      reading: "ポケット",
      meanings: {
        ja: "ポケット",
        en: "pocket",
        zh: "口袋",
        tw: "口袋",
        ko: "주머니",
        vi: "túi",
        th: "กระเป๋าเสื้อ/กางเกง",
        my: "အိတ်လျှို",
        km: "ហោប៉ៅ",
      },
      furigana: [
        {
          rb: "ポケット",
          rt: "ポケット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 308,
      kanji: "ポスト",
      reading: "ポスト",
      meanings: {
        ja: "ポスト",
        en: "postbox",
        zh: "邮箱",
        tw: "郵筒",
        ko: "우체통",
        vi: "hòm thư",
        th: "ตู้ไปรษณีย์",
        my: "စာပုံး",
        km: "ប្រអប់សំបុត្រ",
      },
      furigana: [
        {
          rb: "ポスト",
          rt: "ポスト",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 309,
      kanji: "ホテル",
      reading: "ホテル",
      meanings: {
        ja: "ホテル",
        en: "hotel",
        zh: "旅馆",
        tw: "飯店",
        ko: "호텔",
        vi: "khách sạn",
        th: "โรงแรม",
        my: "ဟိုတယ်",
        km: "សណ្ឋាគារ",
      },
      furigana: [
        {
          rb: "ホテル",
          rt: "ホテル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 310,
      kanji: "本",
      reading: "ほん",
      meanings: {
        ja: "本",
        en: "book",
        zh: "书",
        tw: "書",
        ko: "책",
        vi: "sách",
        th: "หนังสือ",
        my: "စာအုပ်",
        km: "សៀវភៅ",
      },
      furigana: [
        {
          rb: "本",
          rt: "ほん",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 311,
      kanji: "本棚",
      reading: "ほんだな",
      meanings: {
        ja: "本棚",
        en: "bookshelf",
        zh: "书架",
        tw: "書架",
        ko: "책장",
        vi: "kệ sách",
        th: "ชั้นหนังสือ",
        my: "စာအုပ်စင်",
        km: "ទូសៀវភៅ",
      },
      furigana: [
        {
          rb: "本棚",
          rt: "ほんだな",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "棚",
          on: ["ホウ"],
          kun: ["たな", "-だな"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 312,
      kanji: "本当",
      reading: "ほんとう",
      meanings: {
        ja: "本当",
        en: "truth",
        zh: "真的；真相",
        tw: "真的；真相",
        ko: "진실",
        vi: "sự thật",
        th: "ความจริง",
        my: "အမှန်တရား",
        km: "ការពិត",
      },
      furigana: [
        {
          rb: "本当",
          rt: "ほんとう",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 313,
      kanji: "毎朝",
      reading: "まいあさ",
      meanings: {
        ja: "毎朝",
        en: "every morning",
        zh: "每天早晨",
        tw: "每天早晨",
        ko: "매일 아침",
        vi: "mỗi sáng",
        th: "ทุกเช้า",
        my: "တိုင်းမနက်",
        km: "រៀងរាល់ព្រឹក",
      },
      furigana: [
        {
          rb: "毎朝",
          rt: "まいあさ",
        },
      ],
      kanjiInfo: [
        {
          char: "毎",
          on: ["マイ"],
          kun: ["ごと", "-ごと.に"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "朝",
          on: ["チョウ"],
          kun: ["あさ"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 314,
      kanji: "毎週",
      reading: "まいしゅう",
      meanings: {
        ja: "毎週",
        en: "every week",
        zh: "每周",
        tw: "每週",
        ko: "매주",
        vi: "mỗi tuần",
        th: "ทุกสัปดาห์",
        my: "အပတ်တိုင်း",
        km: "រៀងរាល់សប្តាហ៍",
      },
      furigana: [
        {
          rb: "毎週",
          rt: "まいしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "毎",
          on: ["マイ"],
          kun: ["ごと", "-ごと.に"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "週",
          on: ["シュウ"],
          kun: [],
          strokes: 11,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 315,
      kanji: "毎日",
      reading: "まいにち",
      meanings: {
        ja: "毎日",
        en: "every day",
        zh: "每天",
        tw: "每天",
        ko: "매일",
        vi: "mỗi ngày",
        th: "ทุกวัน",
        my: "နေ့တိုင်း",
        km: "រៀងរាល់ថ្ងៃ",
      },
      furigana: [
        {
          rb: "毎日",
          rt: "まいにち",
        },
      ],
      kanjiInfo: [
        {
          char: "毎",
          on: ["マイ"],
          kun: ["ごと", "-ごと.に"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 316,
      kanji: "毎晩",
      reading: "まいばん",
      meanings: {
        ja: "毎晩",
        en: "every night",
        zh: "每天晚上",
        tw: "每天晚上",
        ko: "매일 밤",
        vi: "mỗi tối",
        th: "ทุกคืน",
        my: "ညတိုင်း",
        km: "រៀងរាល់យប់",
      },
      furigana: [
        {
          rb: "毎晩",
          rt: "まいばん",
        },
      ],
      kanjiInfo: [
        {
          char: "毎",
          on: ["マイ"],
          kun: ["ごと", "-ごと.に"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "晩",
          on: ["バン"],
          kun: [],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 317,
      kanji: "前",
      reading: "まえ",
      meanings: {
        ja: "前",
        en: "in front (of)",
        zh: "前面",
        tw: "前面",
        ko: "앞",
        vi: "phía trước",
        th: "ข้างหน้า",
        my: "ရှေ့",
        km: "មុខ",
      },
      furigana: [
        {
          rb: "前",
          rt: "まえ",
        },
      ],
      kanjiInfo: [
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 318,
      kanji: "町",
      reading: "まち",
      meanings: {
        ja: "町",
        en: "town",
        zh: "城镇",
        tw: "城鎮",
        ko: "마을; 도시",
        vi: "thị trấn; thành phố",
        th: "เมือง; เขต",
        my: "မြို့",
        km: "ទីក្រុង",
      },
      furigana: [
        {
          rb: "町",
          rt: "まち",
        },
      ],
      kanjiInfo: [
        {
          char: "町",
          on: ["チョウ"],
          kun: ["まち"],
          strokes: 7,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 319,
      kanji: "マッチ",
      reading: "マッチ",
      meanings: {
        ja: "マッチ",
        en: "match (contest; also matches)",
        zh: "比赛；火柴",
        tw: "比賽；火柴",
        ko: "시합; 성냥",
        vi: "trận đấu; diêm",
        th: "การแข่งขัน; ไม้ขีดไฟ",
        my: "ယှဉ်ပြိုင်ပွဲ; မီးတောင်",
        km: "ការប្រកួត; ខ្មាំងភ្លើង",
      },
      furigana: [
        {
          rb: "マッチ",
          rt: "マッチ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 320,
      kanji: "窓",
      reading: "まど",
      meanings: {
        ja: "窓",
        en: "window",
        zh: "窗户",
        tw: "窗戶",
        ko: "창문",
        vi: "cửa sổ",
        th: "หน้าต่าง",
        my: "ပြတင်းပေါက်",
        km: "បង្អួច",
      },
      furigana: [
        {
          rb: "窓",
          rt: "まど",
        },
      ],
      kanjiInfo: [
        {
          char: "窓",
          on: ["ソウ", "ス"],
          kun: ["まど", "てんまど", "けむだし"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 321,
      kanji: "万",
      reading: "まん",
      meanings: {
        ja: "万",
        en: "ten thousand",
        zh: "一万",
        tw: "一萬",
        ko: "만",
        vi: "mười nghìn",
        th: "หนึ่งหมื่น",
        my: "တစ်သောင်း",
        km: "មួយម៉ឺន",
      },
      furigana: [
        {
          rb: "万",
          rt: "まん",
        },
      ],
      kanjiInfo: [
        {
          char: "万",
          on: ["マン", "バン"],
          kun: ["よろず"],
          strokes: 3,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 322,
      kanji: "万年筆",
      reading: "まんねんひつ",
      meanings: {
        ja: "万年筆",
        en: "fountain pen",
        zh: "钢笔",
        tw: "鋼筆",
        ko: "만년필",
        vi: "bút máy",
        th: "ปากกาหมึกซึม",
        my: "ခဲစက်",
        km: "ប៊ិចទឹក",
      },
      furigana: [
        {
          rb: "万年筆",
          rt: "まんねんひつ",
        },
      ],
      kanjiInfo: [
        {
          char: "万",
          on: ["マン", "バン"],
          kun: ["よろず"],
          strokes: 3,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "筆",
          on: ["ヒツ"],
          kun: ["ふで"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 323,
      kanji: "右",
      reading: "みぎ",
      meanings: {
        ja: "右",
        en: "right",
        zh: "右边",
        tw: "右邊",
        ko: "오른쪽",
        vi: "bên phải",
        th: "ขวา",
        my: "ညာ",
        km: "ស្ដាំ",
      },
      furigana: [
        {
          rb: "右",
          rt: "みぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "右",
          on: ["ウ", "ユウ"],
          kun: ["みぎ"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 324,
      kanji: "水",
      reading: "みず",
      meanings: {
        ja: "水",
        en: "water",
        zh: "水",
        tw: "水",
        ko: "물",
        vi: "nước",
        th: "น้ำ",
        my: "ရေ",
        km: "ទឹក",
      },
      furigana: [
        {
          rb: "水",
          rt: "みず",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 325,
      kanji: "店",
      reading: "みせ",
      meanings: {
        ja: "店",
        en: "store",
        zh: "商店",
        tw: "商店",
        ko: "가게",
        vi: "cửa hàng",
        th: "ร้านค้า",
        my: "ဆိုင်",
        km: "ហាង",
      },
      furigana: [
        {
          rb: "店",
          rt: "みせ",
        },
      ],
      kanjiInfo: [
        {
          char: "店",
          on: ["テン"],
          kun: ["みせ", "たな"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 326,
      kanji: "道",
      reading: "みち",
      meanings: {
        ja: "道",
        en: "road",
        zh: "道路",
        tw: "道路",
        ko: "길",
        vi: "con đường",
        th: "ถนน",
        my: "လမ်း",
        km: "ផ្លូវ",
      },
      furigana: [
        {
          rb: "道",
          rt: "みち",
        },
      ],
      kanjiInfo: [
        {
          char: "道",
          on: ["ドウ", "トウ"],
          kun: ["みち", "いう"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 327,
      kanji: "三日",
      reading: "みっか",
      meanings: {
        ja: "三日（3日）",
        en: "3rd day of the month",
        zh: "三日（3号）",
        tw: "三日（3號）",
        ko: "3일",
        vi: "ngày mồng 3",
        th: "วันที่ 3",
        my: "၃ ရက်နေ့",
        km: "ថ្ងៃទី៣",
      },
      furigana: [
        {
          rb: "三日",
          rt: "みっか",
        },
      ],
      kanjiInfo: [
        {
          char: "三",
          on: ["サン", "ゾウ"],
          kun: ["み", "み.つ", "みっ.つ"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 328,
      kanji: "三つ",
      reading: "みっつ",
      meanings: {
        ja: "三つ（数量）",
        en: "three (count)",
        zh: "三个",
        tw: "三個",
        ko: "세 개",
        vi: "ba cái",
        th: "สาม (จำนวน)",
        my: "သုံးခု",
        km: "បី (ចំនួន)",
      },
      furigana: [
        {
          rb: "三つ",
          rt: "みっつ",
        },
      ],
      kanjiInfo: [
        {
          char: "三",
          on: ["サン", "ゾウ"],
          kun: ["み", "み.つ", "みっ.つ"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 329,
      kanji: "緑",
      reading: "みどり",
      meanings: {
        ja: "緑",
        en: "green",
        zh: "绿色",
        tw: "綠色",
        ko: "초록색",
        vi: "màu xanh lá cây",
        th: "สีเขียว",
        my: "အစိမ်း",
        km: "ពណ៌បៃតង",
      },
      furigana: [
        {
          rb: "緑",
          rt: "みどり",
        },
      ],
      kanjiInfo: [
        {
          char: "緑",
          on: ["リョク", "ロク"],
          kun: ["みどり"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 330,
      kanji: "皆さん",
      reading: "みなさん",
      meanings: {
        ja: "皆さん",
        en: "everyone",
        zh: "大家",
        tw: "大家",
        ko: "여러분",
        vi: "mọi người",
        th: "ทุกคน",
        my: "အားလုံး",
        km: "អ្នកទាំងអស់គ្នា",
      },
      furigana: [
        {
          rb: "皆さん",
          rt: "みなさん",
        },
      ],
      kanjiInfo: [
        {
          char: "皆",
          on: ["カイ"],
          kun: ["みな", "みんな"],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 331,
      kanji: "南",
      reading: "みなみ",
      meanings: {
        ja: "南",
        en: "south",
        zh: "南方",
        tw: "南方",
        ko: "남쪽",
        vi: "phía nam",
        th: "ทิศใต้",
        my: "တောင်",
        km: "ខាងត្បូង",
      },
      furigana: [
        {
          rb: "南",
          rt: "みなみ",
        },
      ],
      kanjiInfo: [
        {
          char: "南",
          on: ["ナン", "ナ"],
          kun: ["みなみ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 332,
      kanji: "耳",
      reading: "みみ",
      meanings: {
        ja: "耳",
        en: "ear",
        zh: "耳朵",
        tw: "耳朵",
        ko: "귀",
        vi: "tai",
        th: "หู",
        my: "နား",
        km: "ត្រចៀក",
      },
      furigana: [
        {
          rb: "耳",
          rt: "みみ",
        },
      ],
      kanjiInfo: [
        {
          char: "耳",
          on: ["ジ"],
          kun: ["みみ"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 333,
      kanji: "六日",
      reading: "むいか",
      meanings: {
        ja: "六日（6日）",
        en: "6th day of the month",
        zh: "六日（6号）",
        tw: "六日（6號）",
        ko: "6일",
        vi: "ngày mồng 6",
        th: "วันที่ 6",
        my: "၆ ရက်နေ့",
        km: "ថ្ងៃទី៦",
      },
      furigana: [
        {
          rb: "六日",
          rt: "むいか",
        },
      ],
      kanjiInfo: [
        {
          char: "六",
          on: ["ロク", "リク"],
          kun: ["む", "む.つ", "むっ.つ", "むい"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 334,
      kanji: "向こう",
      reading: "むこう",
      meanings: {
        ja: "向こう",
        en: "opposite side; over there",
        zh: "那边",
        tw: "那邊",
        ko: "건너편",
        vi: "phía bên kia",
        th: "ฝั่งโน้น",
        my: "အနောက်ဘက်",
        km: "ផ្នែកឆ្លងមុខ",
      },
      furigana: [
        {
          rb: "向こう",
          rt: "むこう",
        },
      ],
      kanjiInfo: [
        {
          char: "向",
          on: ["コウ"],
          kun: [
            "む.く",
            "む.い",
            "-む.き",
            "む.ける",
            "-む.け",
            "む.かう",
            "む.かい",
            "む.こう",
            "む.こう-",
            "むこ",
            "むか.い",
          ],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 335,
      kanji: "六つ",
      reading: "むっつ",
      meanings: {
        ja: "六つ（数量）",
        en: "six (count)",
        zh: "六个",
        tw: "六個",
        ko: "여섯 개",
        vi: "sáu cái",
        th: "หก (จำนวน)",
        my: "ခြောက်ခု",
        km: "ប្រាំមួយ (ចំនួន)",
      },
      furigana: [
        {
          rb: "六つ",
          rt: "むっつ",
        },
      ],
      kanjiInfo: [
        {
          char: "六",
          on: ["ロク", "リク"],
          kun: ["む", "む.つ", "むっ.つ", "むい"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 336,
      kanji: "村",
      reading: "むら",
      meanings: {
        ja: "村",
        en: "village",
        zh: "村庄",
        tw: "村莊",
        ko: "마을",
        vi: "làng",
        th: "หมู่บ้าน",
        my: "ရွာ",
        km: "ភូមិ",
      },
      furigana: [
        {
          rb: "村",
          rt: "むら",
        },
      ],
      kanjiInfo: [
        {
          char: "村",
          on: ["ソン"],
          kun: ["むら"],
          strokes: 7,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 337,
      kanji: "目",
      reading: "め",
      meanings: {
        ja: "目",
        en: "eye",
        zh: "眼睛",
        tw: "眼睛",
        ko: "눈",
        vi: "mắt",
        th: "ตา",
        my: "မျက်စိ",
        km: "ភ្នែក",
      },
      furigana: [
        {
          rb: "目",
          rt: "め",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 338,
      kanji: "眼鏡",
      reading: "めがね",
      meanings: {
        ja: "眼鏡",
        en: "glasses",
        zh: "眼镜",
        tw: "眼鏡",
        ko: "안경",
        vi: "kính mắt",
        th: "แว่นตา",
        my: "မျက်မှန်",
        km: "វ៉ែនតា",
      },
      furigana: [
        {
          rb: "眼鏡",
          rt: "めがね",
        },
      ],
      kanjiInfo: [
        {
          char: "眼",
          on: ["ガン", "ゲン"],
          kun: ["まなこ", "め"],
          strokes: 11,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "鏡",
          on: ["キョウ", "ケイ"],
          kun: ["かがみ"],
          strokes: 19,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 339,
      kanji: "木曜日",
      reading: "もくようび",
      meanings: {
        ja: "木曜日",
        en: "Thursday",
        zh: "星期四",
        tw: "星期四",
        ko: "목요일",
        vi: "thứ năm",
        th: "วันพฤหัสบดี",
        my: "ကြာသပတေး",
        km: "ថ្ងៃព្រហស្បតិ៍",
      },
      furigana: [
        {
          rb: "木曜日",
          rt: "もくようび",
        },
      ],
      kanjiInfo: [
        {
          char: "木",
          on: ["ボク", "モク"],
          kun: ["き", "こ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "曜",
          on: ["ヨウ"],
          kun: [],
          strokes: 18,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 340,
      kanji: "物",
      reading: "もの",
      meanings: {
        ja: "物",
        en: "thing",
        zh: "东西",
        tw: "東西",
        ko: "물건",
        vi: "đồ vật",
        th: "สิ่งของ",
        my: "အရာ",
        km: "របស់",
      },
      furigana: [
        {
          rb: "物",
          rt: "もの",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 341,
      kanji: "門",
      reading: "もん",
      meanings: {
        ja: "門",
        en: "gate",
        zh: "大门",
        tw: "大門",
        ko: "문",
        vi: "cổng",
        th: "ประตูใหญ่",
        my: "တံခါးဝ",
        km: "ច្រកទ្វារ",
      },
      furigana: [
        {
          rb: "門",
          rt: "もん",
        },
      ],
      kanjiInfo: [
        {
          char: "門",
          on: ["モン"],
          kun: ["かど", "と"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 342,
      kanji: "問題",
      reading: "もんだい",
      meanings: {
        ja: "問題",
        en: "problem; question",
        zh: "问题",
        tw: "問題",
        ko: "문제",
        vi: "vấn đề",
        th: "ปัญหา; คำถาม",
        my: "ပြဿနာ",
        km: "បញ្ហា",
      },
      furigana: [
        {
          rb: "問題",
          rt: "もんだい",
        },
      ],
      kanjiInfo: [
        {
          char: "問",
          on: ["モン"],
          kun: ["と.う", "と.い", "とん"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "題",
          on: ["ダイ"],
          kun: [],
          strokes: 18,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 343,
      kanji: "八百屋",
      reading: "やおや",
      meanings: {
        ja: "八百屋",
        en: "greengrocer",
        zh: "蔬果店",
        tw: "蔬果店",
        ko: "야채가게",
        vi: "cửa hàng rau quả",
        th: "ร้านขายผัก",
        my: "ဟင်းသီးဟင်းရွက်ဆိုင်",
        km: "ហាងលក់បន្លែ",
      },
      furigana: [
        {
          rb: "八百屋",
          rt: "やおや",
        },
      ],
      kanjiInfo: [
        {
          char: "八",
          on: ["ハチ", "ハツ"],
          kun: ["や", "や.つ", "やっ.つ", "よう"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "百",
          on: ["ヒャク", "ビャク"],
          kun: ["もも"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "屋",
          on: ["オク"],
          kun: ["や"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 344,
      kanji: "野菜",
      reading: "やさい",
      meanings: {
        ja: "野菜",
        en: "vegetable",
        zh: "蔬菜",
        tw: "蔬菜",
        ko: "야채",
        vi: "rau",
        th: "ผัก",
        my: "ဟင်းသီးဟင်းရွက်",
        km: "បន្លែ",
      },
      furigana: [
        {
          rb: "野菜",
          rt: "やさい",
        },
      ],
      kanjiInfo: [
        {
          char: "野",
          on: ["ヤ", "ショ"],
          kun: ["の", "の-"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "菜",
          on: ["サイ"],
          kun: ["な"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 345,
      kanji: "休み",
      reading: "やすみ",
      meanings: {
        ja: "休み",
        en: "rest; holiday",
        zh: "休息；假期",
        tw: "休息；假期",
        ko: "휴식; 휴일",
        vi: "nghỉ ngơi; kỳ nghỉ",
        th: "การพักผ่อน; วันหยุด",
        my: "အနားယူခြင်း",
        km: "ថ្ងៃឈប់សម្រាក",
      },
      furigana: [
        {
          rb: "休み",
          rt: "やすみ",
        },
      ],
      kanjiInfo: [
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 346,
      kanji: "八つ",
      reading: "やっつ",
      meanings: {
        ja: "八つ（数量）",
        en: "eight (count)",
        zh: "八个",
        tw: "八個",
        ko: "여덟 개",
        vi: "tám cái",
        th: "แปด (จำนวน)",
        my: "ရှစ်ခု",
        km: "ប្រាំបី (ចំនួន)",
      },
      furigana: [
        {
          rb: "八つ",
          rt: "やっつ",
        },
      ],
      kanjiInfo: [
        {
          char: "八",
          on: ["ハチ", "ハツ"],
          kun: ["や", "や.つ", "やっ.つ", "よう"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 347,
      kanji: "山",
      reading: "やま",
      meanings: {
        ja: "山",
        en: "mountain",
        zh: "山",
        tw: "山",
        ko: "산",
        vi: "núi",
        th: "ภูเขา",
        my: "တောင်",
        km: "ភ្នំ",
      },
      furigana: [
        {
          rb: "山",
          rt: "やま",
        },
      ],
      kanjiInfo: [
        {
          char: "山",
          on: ["サン", "セン"],
          kun: ["やま"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 348,
      kanji: "夕方",
      reading: "ゆうがた",
      meanings: {
        ja: "夕方",
        en: "evening (around 3–6pm)",
        zh: "傍晚",
        tw: "傍晚",
        ko: "저녁 무렵",
        vi: "chiều tối",
        th: "ตอนเย็น (3–6 โมง)",
        my: "ညနေစောင်း",
        km: "ល្ងាច",
      },
      furigana: [
        {
          rb: "夕方",
          rt: "ゆうがた",
        },
      ],
      kanjiInfo: [
        {
          char: "夕",
          on: ["セキ"],
          kun: ["ゆう"],
          strokes: 3,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 349,
      kanji: "夕飯",
      reading: "ゆうはん",
      meanings: {
        ja: "夕飯",
        en: "evening meal",
        zh: "晚饭",
        tw: "晚餐",
        ko: "저녁 식사",
        vi: "bữa tối",
        th: "อาหารค่ำ",
        my: "ညစာ",
        km: "អាហារពេលល្ងាច",
      },
      furigana: [
        {
          rb: "夕飯",
          rt: "ゆうはん",
        },
      ],
      kanjiInfo: [
        {
          char: "夕",
          on: ["セキ"],
          kun: ["ゆう"],
          strokes: 3,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "飯",
          on: ["ハン"],
          kun: ["めし"],
          strokes: 12,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 350,
      kanji: "郵便局",
      reading: "ゆうびんきょく",
      meanings: {
        ja: "郵便局",
        en: "post office",
        zh: "邮局",
        tw: "郵局",
        ko: "우체국",
        vi: "bưu điện",
        th: "ที่ทำการไปรษณีย์",
        my: "စာတိုက်",
        km: "ការិយាល័យប្រៃសណីយ៍",
      },
      furigana: [
        {
          rb: "郵便局",
          rt: "ゆうびんきょく",
        },
      ],
      kanjiInfo: [
        {
          char: "郵",
          on: ["ユウ"],
          kun: [],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "便",
          on: ["ベン", "ビン"],
          kun: ["たよ.り"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "局",
          on: ["キョク"],
          kun: ["つぼね"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
