export const n5part19 = {
  Lesson19: [
    {
      id: 709,
      kanji: "～屋",
      reading: "～や",
      meanings: {
        ja: "～屋",
        en: "shop; store; seller of ~",
        zh: "～店",
        tw: "～店",
        ko: "~가게",
        vi: "cửa hàng ~",
        th: "ร้าน ~",
        my: "~ ဆိုင်",
        km: "ហាង ~",
      },
      furigana: [
        {
          rb: "～屋",
          rt: "～や",
        },
      ],
      kanjiInfo: [
        {
          char: "屋",
          on: ["オク"],
          kun: ["や"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 710,
      kanji: "やる",
      reading: "やる",
      meanings: {
        ja: "やる",
        en: "to do; to give",
        zh: "做; 给",
        tw: "做；給",
        ko: "하다; 주다",
        vi: "làm; cho",
        th: "ทำ; ให้",
        my: "လုပ်; ပေး",
        km: "ធ្វើ; ឲ្យ",
      },
      furigana: [
        {
          rb: "やる",
          rt: "やる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 711,
      kanji: "ゆっくりと",
      reading: "ゆっくりと",
      meanings: {
        ja: "ゆっくりと",
        en: "slowly; at ease",
        zh: "慢慢地",
        tw: "慢慢地",
        ko: "천천히",
        vi: "từ từ",
        th: "ช้าๆ",
        my: "တဖြည်းဖြည်း",
        km: "យឺតៗ",
      },
      furigana: [
        {
          rb: "ゆっくりと",
          rt: "ゆっくりと",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 712,
      kanji: "よく",
      reading: "よく",
      meanings: {
        ja: "よく",
        en: "often; well",
        zh: "经常; 很好地",
        tw: "經常；很好地",
        ko: "자주; 잘",
        vi: "thường; giỏi",
        th: "บ่อย; เก่ง",
        my: "မကြာခဏ; သေချာ",
        km: "ញឹកញាប់; ល្អ",
      },
      furigana: [
        {
          rb: "よく",
          rt: "よく",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 713,
      kanji: "ラジオカセ",
      reading: "ラジオカセ",
      meanings: {
        ja: "ラジオカセ",
        en: "radio cassette player",
        zh: "收录音机",
        tw: "收錄音機",
        ko: "라디오 카세트",
        vi: "máy cassette radio",
        th: "วิทยุเทป",
        my: "ရေဒီယို ကတ်ဆက်",
        km: "ម៉ាស៊ីនកាសែតវិទ្យុ",
      },
      furigana: [
        {
          rb: "ラジオカセ",
          rt: "ラジオカセ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 714,
      kanji: "りっぱ",
      reading: "りっぱ",
      meanings: {
        ja: "りっぱ",
        en: "splendid; fine",
        zh: "了不起; 出色",
        tw: "了不起；出色",
        ko: "훌륭하다",
        vi: "tuyệt vời",
        th: "ยอดเยี่ยม",
        my: "ထူးခြား",
        km: "ល្អឥតខ្ចោះ",
      },
      furigana: [
        {
          rb: "りっぱ",
          rt: "りっぱ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 715,
      kanji: "練習",
      reading: "れんしゅう (する)",
      meanings: {
        ja: "練習 (する)",
        en: "practice; to practice",
        zh: "练习",
        tw: "練習",
        ko: "연습 (하다)",
        vi: "luyện tập",
        th: "ฝึกซ้อม",
        my: "လေ့ကျင့်",
        km: "ហាត់ប្រាណ",
      },
      furigana: [
        {
          rb: "練習",
          rt: "れんしゅう （する）",
        },
      ],
      kanjiInfo: [
        {
          char: "練",
          on: ["レン"],
          kun: ["ね.る", "ね.り"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "習",
          on: ["シュウ", "ジュ"],
          kun: ["なら.う", "なら.い"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 716,
      kanji: "ワイシャツ",
      reading: "ワイシャツ",
      meanings: {
        ja: "ワイシャツ",
        en: "dress shirt",
        zh: "衬衫",
        tw: "襯衫",
        ko: "와이셔츠",
        vi: "áo sơ mi",
        th: "เสื้อเชิ้ต",
        my: "အင်္ကျီဝိုင်း",
        km: "អាវកែវ",
      },
      furigana: [
        {
          rb: "ワイシャツ",
          rt: "ワイシャツ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 717,
      kanji: "私",
      reading: "わたし",
      meanings: {
        ja: "私",
        en: "I; me",
        zh: "我",
        tw: "我",
        ko: "나",
        vi: "tôi",
        th: "ฉัน",
        my: "ကျွန်တော်/ကျွန်မ",
        km: "ខ្ញុំ",
      },
      furigana: [
        {
          rb: "私",
          rt: "わたし",
        },
      ],
      kanjiInfo: [
        {
          char: "私",
          on: ["シ"],
          kun: ["わたくし", "わたし"],
          strokes: 7,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 718,
      kanji: "私",
      reading: "わたくし",
      meanings: {
        ja: "私",
        en: "I (formal)",
        zh: "我 (正式)",
        tw: "我 (正式)",
        ko: "저 (격식)",
        vi: "tôi (trang trọng)",
        th: "ดิฉัน (ทางการ)",
        my: "ကျွန်တော် (အလွန်လေးစား)",
        km: "ខ្ញុំ (ផ្លូវការ)",
      },
      furigana: [
        {
          rb: "私",
          rt: "わたくし",
        },
      ],
      kanjiInfo: [
        {
          char: "私",
          on: ["シ"],
          kun: ["わたくし", "わたし"],
          strokes: 7,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
