export const n5part4 = {
  Lesson4: [
    {
      id: 151,
      kanji: "塩",
      reading: "しお",
      meanings: {
        ja: "塩",
        en: "salt",
        zh: "盐",
        tw: "鹽",
        ko: "소금",
        vi: "muối",
        th: "เกลือ",
        my: "ဆား",
        km: "អំបិល",
      },
      furigana: [
        {
          rb: "塩",
          rt: "しお",
        },
      ],
      kanjiInfo: [
        {
          char: "塩",
          on: ["エン"],
          kun: ["しお"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 152,
      kanji: "時間",
      reading: "じかん",
      meanings: {
        ja: "時間",
        en: "time",
        zh: "时间",
        tw: "時間",
        ko: "시간",
        vi: "thời gian",
        th: "เวลา",
        my: "အချိန်",
        km: "ពេលវេលា",
      },
      furigana: [
        {
          rb: "時間",
          rt: "じかん",
        },
      ],
      kanjiInfo: [
        {
          char: "時",
          on: ["ジ"],
          kun: ["とき", "-どき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 153,
      kanji: "仕事",
      reading: "しごと",
      meanings: {
        ja: "仕事",
        en: "work; job",
        zh: "工作",
        tw: "工作",
        ko: "일",
        vi: "công việc",
        th: "งาน",
        my: "အလုပ်",
        km: "ការងារ",
      },
      furigana: [
        {
          rb: "仕事",
          rt: "しごと",
        },
      ],
      kanjiInfo: [
        {
          char: "仕",
          on: ["シ", "ジ"],
          kun: ["つか.える"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 154,
      kanji: "辞書",
      reading: "じしょ",
      meanings: {
        ja: "辞書",
        en: "dictionary",
        zh: "词典",
        tw: "字典",
        ko: "사전",
        vi: "từ điển",
        th: "พจนานุกรม",
        my: "အဘိဓာန်",
        km: "វចនានុក្រម",
      },
      furigana: [
        {
          rb: "辞書",
          rt: "じしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "辞",
          on: ["ジ"],
          kun: ["や.める", "いな.む"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 155,
      kanji: "下",
      reading: "した",
      meanings: {
        ja: "下",
        en: "below",
        zh: "下面",
        tw: "下面",
        ko: "아래",
        vi: "dưới",
        th: "ข้างล่าง",
        my: "အောက်",
        km: "ក្រោម",
      },
      furigana: [
        {
          rb: "下",
          rt: "した",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 156,
      kanji: "七",
      reading: "しち",
      meanings: {
        ja: "七",
        en: "seven",
        zh: "七",
        tw: "七",
        ko: "일곱",
        vi: "bảy",
        th: "เจ็ด",
        my: "ခုနှစ်",
        km: "ប្រាំពីរ",
      },
      furigana: [
        {
          rb: "七",
          rt: "しち",
        },
      ],
      kanjiInfo: [
        {
          char: "七",
          on: ["シチ"],
          kun: ["なな", "なな.つ", "なの"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 157,
      kanji: "質問",
      reading: "しつもん",
      meanings: {
        ja: "質問",
        en: "question",
        zh: "问题",
        tw: "問題",
        ko: "질문",
        vi: "câu hỏi",
        th: "คำถาม",
        my: "မေးခွန်း",
        km: "សំណួរ",
      },
      furigana: [
        {
          rb: "質問",
          rt: "しつもん",
        },
      ],
      kanjiInfo: [
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
        {
          char: "問",
          on: ["モン"],
          kun: ["と.う", "と.い", "とん"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 158,
      kanji: "自転車",
      reading: "じてんしゃ",
      meanings: {
        ja: "自転車",
        en: "bicycle",
        zh: "自行车",
        tw: "自行車",
        ko: "자전거",
        vi: "xe đạp",
        th: "จักรยาน",
        my: "စက်ဘီး",
        km: "កង់",
      },
      furigana: [
        {
          rb: "自転車",
          rt: "じてんしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 159,
      kanji: "自動車",
      reading: "じどうしゃ",
      meanings: {
        ja: "自動車",
        en: "car; automobile",
        zh: "汽车",
        tw: "汽車",
        ko: "자동차",
        vi: "xe ô tô",
        th: "รถยนต์",
        my: "ကားယာဉ်",
        km: "យានយន្ត",
      },
      furigana: [
        {
          rb: "自動車",
          rt: "じどうしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 160,
      kanji: "字引",
      reading: "じびき",
      meanings: {
        ja: "字引（辞書）",
        en: "dictionary",
        zh: "字典",
        tw: "字典",
        ko: "사전",
        vi: "từ điển",
        th: "พจนานุกรม",
        my: "အဘိဓာန်",
        km: "វចនានុក្រម",
      },
      furigana: [
        {
          rb: "字引",
          rt: "じびき",
        },
      ],
      kanjiInfo: [
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "引",
          on: ["イン"],
          kun: ["ひ.く", "ひ.ける"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 161,
      kanji: "写真",
      reading: "しゃしん",
      meanings: {
        ja: "写真",
        en: "photograph",
        zh: "照片",
        tw: "照片",
        ko: "사진",
        vi: "ảnh",
        th: "รูปถ่าย",
        my: "ဓါတ်ပုံ",
        km: "រូបថត",
      },
      furigana: [
        {
          rb: "写真",
          rt: "しゃしん",
        },
      ],
      kanjiInfo: [
        {
          char: "写",
          on: ["シャ", "ジャ"],
          kun: ["うつ.す", "うつ.る", "うつ-", "うつ.し"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 162,
      kanji: "シャツ",
      reading: "シャツ",
      meanings: {
        ja: "シャツ",
        en: "shirt (undergarment)",
        zh: "衬衫（内衣）",
        tw: "襯衫（內衣）",
        ko: "셔츠(속옷)",
        vi: "áo sơ mi (lót)",
        th: "เสื้อเชิ้ต (ชั้นใน)",
        my: "ရှပ်အင်္ကျီ (အတွင်း)",
        km: "អាវអក្នុង",
      },
      furigana: [
        {
          rb: "シャツ",
          rt: "シャツ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 163,
      kanji: "シャワー",
      reading: "シャワー",
      meanings: {
        ja: "シャワー",
        en: "shower",
        zh: "淋浴",
        tw: "淋浴",
        ko: "샤워",
        vi: "vòi sen",
        th: "ฝักบัว",
        my: "ရေချိုးပစ္စည်း",
        km: "ផ្នែកងូតទឹក (シャワー)",
      },
      furigana: [
        {
          rb: "シャワー",
          rt: "シャワー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 164,
      kanji: "十",
      reading: "じゅう",
      meanings: {
        ja: "十",
        en: "ten",
        zh: "十",
        tw: "十",
        ko: "열",
        vi: "mười",
        th: "สิบ",
        my: "ဆယ့်",
        km: "ដប់",
      },
      furigana: [
        {
          rb: "十",
          rt: "じゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "十",
          on: ["ジュウ", "ジッ", "ジュッ"],
          kun: ["とお", "と", "そ"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 165,
      kanji: "授業",
      reading: "じゅぎょう",
      meanings: {
        ja: "授業",
        en: "lesson; class",
        zh: "授课；课程",
        tw: "上課；課程",
        ko: "수업",
        vi: "tiết học",
        th: "คาบเรียน",
        my: "စာသင်တန်း",
        km: "មេរៀន",
      },
      furigana: [
        {
          rb: "授業",
          rt: "じゅぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "授",
          on: ["ジュ"],
          kun: ["さず.ける", "さず.かる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 166,
      kanji: "宿題",
      reading: "しゅくだい",
      meanings: {
        ja: "宿題",
        en: "homework",
        zh: "作业",
        tw: "作業",
        ko: "숙제",
        vi: "bài tập về nhà",
        th: "การบ้าน",
        my: "အိမ်စာ",
        km: "ការ​ងារ​ផ្ទះ",
      },
      furigana: [
        {
          rb: "宿題",
          rt: "しゅくだい",
        },
      ],
      kanjiInfo: [
        {
          char: "宿",
          on: ["シュク"],
          kun: ["やど", "やど.る", "やど.す"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "題",
          on: ["ダイ"],
          kun: [],
          strokes: 18,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 167,
      kanji: "醤油",
      reading: "しょうゆ",
      meanings: {
        ja: "醤油",
        en: "soy sauce",
        zh: "酱油",
        tw: "醬油",
        ko: "간장",
        vi: "xì dầu",
        th: "ซีอิ๊ว",
        my: "ဆီချက်",
        km: "ស៊ីអ៊ីវ",
      },
      furigana: [
        {
          rb: "醤油",
          rt: "しょうゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "醤",
          on: ["ショウ"],
          kun: ["ひしお"],
          strokes: 17,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
        {
          char: "油",
          on: ["ユ", "ユウ"],
          kun: ["あぶら"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 168,
      kanji: "食堂",
      reading: "しょくどう",
      meanings: {
        ja: "食堂",
        en: "dining room; cafeteria",
        zh: "食堂",
        tw: "食堂",
        ko: "식당",
        vi: "nhà ăn; căn tin",
        th: "โรงอาหาร",
        my: "စားသောက်ဆိုင်",
        km: "អាហារដ្ឋាន",
      },
      furigana: [
        {
          rb: "食堂",
          rt: "しょくどう",
        },
      ],
      kanjiInfo: [
        {
          char: "食",
          on: ["ショク", "ジキ"],
          kun: ["く.う", "く.らう", "た.べる", "は.む"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "堂",
          on: ["ドウ"],
          kun: [],
          strokes: 11,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 169,
      kanji: "白",
      reading: "しろ",
      meanings: {
        ja: "白",
        en: "white",
        zh: "白色",
        tw: "白色",
        ko: "흰색",
        vi: "màu trắng",
        th: "สีขาว",
        my: "အဖြူရောင်",
        km: "ពណ៌ស",
      },
      furigana: [
        {
          rb: "白",
          rt: "しろ",
        },
      ],
      kanjiInfo: [
        {
          char: "白",
          on: ["ハク", "ビャク"],
          kun: ["しろ", "しら-", "しろ.い"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 170,
      kanji: "新聞",
      reading: "しんぶん",
      meanings: {
        ja: "新聞",
        en: "newspaper",
        zh: "报纸",
        tw: "報紙",
        ko: "신문",
        vi: "báo",
        th: "หนังสือพิมพ์",
        my: "သတင်းစာ",
        km: "សារព័ត៌មាន (កាសែត)",
      },
      furigana: [
        {
          rb: "新聞",
          rt: "しんぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "新",
          on: ["シン"],
          kun: ["あたら.しい", "あら.た", "あら-", "にい-"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "聞",
          on: ["ブン", "モン"],
          kun: ["き.く", "き.こえる"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 171,
      kanji: "水曜日",
      reading: "すいようび",
      meanings: {
        ja: "水曜日",
        en: "Wednesday",
        zh: "星期三",
        tw: "星期三",
        ko: "수요일",
        vi: "thứ tư",
        th: "วันพุธ",
        my: "ဗုဒ္ဓဟူးနေ့",
        km: "ថ្ងៃពុធ",
      },
      furigana: [
        {
          rb: "水曜日",
          rt: "すいようび",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "曜",
          on: ["ヨウ"],
          kun: [],
          strokes: 18,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 172,
      kanji: "スカート",
      reading: "スカート",
      meanings: {
        ja: "スカート",
        en: "skirt",
        zh: "裙子",
        tw: "裙子",
        ko: "치마",
        vi: "váy",
        th: "กระโปรง",
        my: "စကတ်",
        km: "សំពត់",
      },
      furigana: [
        {
          rb: "スカート",
          rt: "スカート",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 173,
      kanji: "ストーブ",
      reading: "ストーブ",
      meanings: {
        ja: "ストーブ",
        en: "(room) heater",
        zh: "火炉；暖炉",
        tw: "火爐；暖爐",
        ko: "스토브",
        vi: "lò sưởi",
        th: "เตาทำความร้อน",
        my: "အပူပေးစက်",
        km: "ម៉ាស៊ីនកំដៅ",
      },
      furigana: [
        {
          rb: "ストーブ",
          rt: "ストーブ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 174,
      kanji: "スプーン",
      reading: "スプーン",
      meanings: {
        ja: "スプーン",
        en: "spoon",
        zh: "勺子",
        tw: "湯匙",
        ko: "숟가락",
        vi: "thìa (muỗng)",
        th: "ช้อน",
        my: "စူပွန်",
        km: "ស្លាបព្រា",
      },
      furigana: [
        {
          rb: "スプーン",
          rt: "スプーン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 175,
      kanji: "スポーツ",
      reading: "スポーツ",
      meanings: {
        ja: "スポーツ",
        en: "sport",
        zh: "运动",
        tw: "運動",
        ko: "스포츠",
        vi: "thể thao",
        th: "กีฬา",
        my: "အားကစား",
        km: "កីឡា",
      },
      furigana: [
        {
          rb: "スポーツ",
          rt: "スポーツ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 176,
      kanji: "背",
      reading: "せい",
      meanings: {
        ja: "背（身長）",
        en: "height (stature)",
        zh: "身高",
        tw: "身高",
        ko: "키(신장)",
        vi: "chiều cao",
        th: "ความสูง",
        my: "အမြင့်",
        km: "កម្ពស់",
      },
      furigana: [
        {
          rb: "背",
          rt: "せい",
        },
      ],
      kanjiInfo: [
        {
          char: "背",
          on: ["ハイ"],
          kun: ["せ", "せい", "そむ.く", "そむ.ける"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 177,
      kanji: "生徒",
      reading: "せいと",
      meanings: {
        ja: "生徒",
        en: "pupil",
        zh: "学生（中小学）",
        tw: "學生（中小學）",
        ko: "생도/학생",
        vi: "học sinh",
        th: "นักเรียน",
        my: "ကျောင်းသား",
        km: "សិស្ស",
      },
      furigana: [
        {
          rb: "生徒",
          rt: "せいと",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "徒",
          on: ["ト"],
          kun: ["いたずら", "あだ"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 178,
      kanji: "セーター",
      reading: "セーター",
      meanings: {
        ja: "セーター",
        en: "sweater",
        zh: "毛衣",
        tw: "毛衣",
        ko: "스웨터",
        vi: "áo len",
        th: "เสื้อสเวตเตอร์",
        my: "စွယ်တာအင်္ကျီ",
        km: "អាវក្រាស់",
      },
      furigana: [
        {
          rb: "セーター",
          rt: "セーター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 179,
      kanji: "石鹸",
      reading: "せっけん",
      meanings: {
        ja: "石鹸",
        en: "soap",
        zh: "肥皂",
        tw: "肥皂",
        ko: "비누",
        vi: "xà phòng",
        th: "สบู่",
        my: "ဆပ်ပြာ",
        km: "សាប៊ូ",
      },
      furigana: [
        {
          rb: "石鹸",
          rt: "せっけん",
        },
      ],
      kanjiInfo: [
        {
          char: "石",
          on: ["セキ", "シャク", "コク"],
          kun: ["いし"],
          strokes: 5,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
        {
          char: "鹸",
          on: ["ケン", "カン", "セン"],
          kun: ["あ.く"],
          strokes: 19,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 180,
      kanji: "背広",
      reading: "せびろ",
      meanings: {
        ja: "背広（スーツ）",
        en: "business suit",
        zh: "西装",
        tw: "西裝",
        ko: "양복",
        vi: "com-lê",
        th: "ชุดสูท",
        my: "အလုပ်အင်္ကျီ套",
        km: "ឈុតស៊ូត",
      },
      furigana: [
        {
          rb: "背広",
          rt: "せびろ",
        },
      ],
      kanjiInfo: [
        {
          char: "背",
          on: ["ハイ"],
          kun: ["せ", "せい", "そむ.く", "そむ.ける"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "広",
          on: ["コウ"],
          kun: ["ひろ.い", "ひろ.まる", "ひろ.める", "ひろ.がる", "ひろ.げる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 181,
      kanji: "千",
      reading: "せん",
      meanings: {
        ja: "千",
        en: "thousand",
        zh: "千",
        tw: "千",
        ko: "천",
        vi: "nghìn",
        th: "หนึ่งพัน",
        my: "ထောင်",
        km: "ពាន់",
      },
      furigana: [
        {
          rb: "千",
          rt: "せん",
        },
      ],
      kanjiInfo: [
        {
          char: "千",
          on: ["セン"],
          kun: ["ち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 182,
      kanji: "先月",
      reading: "せんげつ",
      meanings: {
        ja: "先月",
        en: "last month",
        zh: "上个月",
        tw: "上個月",
        ko: "지난달",
        vi: "tháng trước",
        th: "เดือนที่แล้ว",
        my: "ပြီးခဲ့သည့်လ",
        km: "ខែមុន",
      },
      furigana: [
        {
          rb: "先月",
          rt: "せんげつ",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 183,
      kanji: "先週",
      reading: "せんしゅう",
      meanings: {
        ja: "先週",
        en: "last week",
        zh: "上周",
        tw: "上週",
        ko: "지난주",
        vi: "tuần trước",
        th: "สัปดาห์ที่แล้ว",
        my: "ပြီးခဲ့သည့်အပတ်",
        km: "សប្តាហ៍មុន",
      },
      furigana: [
        {
          rb: "先週",
          rt: "せんしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "週",
          on: ["シュウ"],
          kun: [],
          strokes: 11,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 184,
      kanji: "先生",
      reading: "せんせい",
      meanings: {
        ja: "先生",
        en: "teacher",
        zh: "老师",
        tw: "老師",
        ko: "선생님",
        vi: "giáo viên",
        th: "ครู/อาจารย์",
        my: "ဆရာ/ဆရာမ",
        km: "គ្រូ",
      },
      furigana: [
        {
          rb: "先生",
          rt: "せんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 185,
      kanji: "洗濯",
      reading: "せんたく",
      meanings: {
        ja: "洗濯",
        en: "washing; laundry",
        zh: "洗衣",
        tw: "洗衣",
        ko: "세탁",
        vi: "giặt giũ",
        th: "ซักผ้า",
        my: "ဘောင်းဘီစသည့်သည်း",
        km: "បោកគក់",
      },
      furigana: [
        {
          rb: "洗濯",
          rt: "せんたく",
        },
      ],
      kanjiInfo: [
        {
          char: "洗",
          on: ["セン"],
          kun: ["あら.う"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "濯",
          on: ["タク"],
          kun: ["すす.ぐ", "ゆす.ぐ"],
          strokes: 17,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 186,
      kanji: "全部",
      reading: "ぜんぶ",
      meanings: {
        ja: "全部",
        en: "all; everything",
        zh: "全部",
        tw: "全部",
        ko: "전부",
        vi: "toàn bộ",
        th: "ทั้งหมด",
        my: "အားလုံး",
        km: "ទាំងអស់",
      },
      furigana: [
        {
          rb: "全部",
          rt: "ぜんぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "全",
          on: ["ゼン"],
          kun: ["まった.く", "すべ.て"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 187,
      kanji: "外",
      reading: "そと",
      meanings: {
        ja: "外",
        en: "outside",
        zh: "外面",
        tw: "外面",
        ko: "밖",
        vi: "bên ngoài",
        th: "ข้างนอก",
        my: "အပြင်",
        km: "ខាងក្រៅ",
      },
      furigana: [
        {
          rb: "外",
          rt: "そと",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 188,
      kanji: "空",
      reading: "そら",
      meanings: {
        ja: "空",
        en: "sky",
        zh: "天空",
        tw: "天空",
        ko: "하늘",
        vi: "bầu trời",
        th: "ท้องฟ้า",
        my: "ကောင်းကင်",
        km: "មេឃ",
      },
      furigana: [
        {
          rb: "空",
          rt: "そら",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 189,
      kanji: "大学",
      reading: "だいがく",
      meanings: {
        ja: "大学",
        en: "university",
        zh: "大学",
        tw: "大學",
        ko: "대학",
        vi: "đại học",
        th: "มหาวิทยาลัย",
        my: "တက္ကသိုလ်",
        km: "សាកលវិទ្យាល័យ",
      },
      furigana: [
        {
          rb: "大学",
          rt: "だいがく",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 190,
      kanji: "大使館",
      reading: "たいしかん",
      meanings: {
        ja: "大使館",
        en: "embassy",
        zh: "大使馆",
        tw: "大使館",
        ko: "대사관",
        vi: "đại sứ quán",
        th: "สถานทูต",
        my: "တက်ဆစ်ဂွန်း",
        km: "ស្ថានទូត",
      },
      furigana: [
        {
          rb: "大使館",
          rt: "たいしかん",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "使",
          on: ["シ"],
          kun: ["つか.う", "つか.い", "-つか.い", "-づか.い"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "館",
          on: ["カン"],
          kun: ["やかた", "たて"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 191,
      kanji: "台所",
      reading: "だいどころ",
      meanings: {
        ja: "台所",
        en: "kitchen",
        zh: "厨房",
        tw: "廚房",
        ko: "부엌",
        vi: "nhà bếp",
        th: "ห้องครัว",
        my: "ချက်ပြုတ်ခန်း",
        km: "ផ្ទះបាយ",
      },
      furigana: [
        {
          rb: "台所",
          rt: "だいどころ",
        },
      ],
      kanjiInfo: [
        {
          char: "台",
          on: ["ダイ", "タイ"],
          kun: ["うてな", "われ", "つかさ"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "所",
          on: ["ショ"],
          kun: ["ところ", "-ところ", "どころ", "とこ"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 192,
      kanji: "タクシー",
      reading: "タクシー",
      meanings: {
        ja: "タクシー",
        en: "taxi",
        zh: "出租车",
        tw: "計程車",
        ko: "택시",
        vi: "xe taxi",
        th: "แท็กซี่",
        my: "တက္ကစီ",
        km: "តាក់ស៊ី",
      },
      furigana: [
        {
          rb: "タクシー",
          rt: "タクシー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 193,
      kanji: "建物",
      reading: "たてもの",
      meanings: {
        ja: "建物",
        en: "building",
        zh: "建筑物",
        tw: "建築物",
        ko: "건물",
        vi: "tòa nhà",
        th: "อาคาร",
        my: "အဆောက်အဦး",
        km: "អគារ",
      },
      furigana: [
        {
          rb: "建物",
          rt: "たてもの",
        },
      ],
      kanjiInfo: [
        {
          char: "建",
          on: ["ケン", "コン"],
          kun: ["た.てる", "た.て", "-だ.て", "た.つ"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 194,
      kanji: "食べ物",
      reading: "たべもの",
      meanings: {
        ja: "食べ物",
        en: "food",
        zh: "食物",
        tw: "食物",
        ko: "음식",
        vi: "thức ăn",
        th: "อาหาร",
        my: "အစားအစာ",
        km: "អាហារ",
      },
      furigana: [
        {
          rb: "食べ物",
          rt: "たべもの",
        },
      ],
      kanjiInfo: [
        {
          char: "食",
          on: ["ショク", "ジキ"],
          kun: ["く.う", "く.らう", "た.べる", "は.む"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 195,
      kanji: "卵",
      reading: "たまご",
      meanings: {
        ja: "卵",
        en: "eggs",
        zh: "鸡蛋",
        tw: "雞蛋",
        ko: "달걀/계란",
        vi: "trứng",
        th: "ไข่",
        my: "ကြက်ဉ",
        km: "ពងមាន់",
      },
      furigana: [
        {
          rb: "卵",
          rt: "たまご",
        },
      ],
      kanjiInfo: [
        {
          char: "卵",
          on: ["ラン"],
          kun: ["たまご"],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 196,
      kanji: "誕生日",
      reading: "たんじょうび",
      meanings: {
        ja: "誕生日",
        en: "birthday",
        zh: "生日",
        tw: "生日",
        ko: "생일",
        vi: "sinh nhật",
        th: "วันเกิด",
        my: "မွေးနေ့",
        km: "ថ្ងៃកំណើត",
      },
      furigana: [
        {
          rb: "誕生日",
          rt: "たんじょうび",
        },
      ],
      kanjiInfo: [
        {
          char: "誕",
          on: ["タン"],
          kun: [],
          strokes: 15,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 197,
      kanji: "近く",
      reading: "ちかく",
      meanings: {
        ja: "近く",
        en: "near; nearby",
        zh: "附近；附近地方",
        tw: "附近；附近地方",
        ko: "가까이; 근처",
        vi: "gần; khu vực gần",
        th: "ใกล้; แถวนี้",
        my: "နီးမှာ",
        km: "ជិតៗ",
      },
      furigana: [
        {
          rb: "近く",
          rt: "ちかく",
        },
      ],
      kanjiInfo: [
        {
          char: "近",
          on: ["キン", "コン"],
          kun: ["ちか.い"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 198,
      kanji: "地下鉄",
      reading: "ちかてつ",
      meanings: {
        ja: "地下鉄",
        en: "subway",
        zh: "地铁",
        tw: "捷運/地鐵",
        ko: "지하철",
        vi: "tàu điện ngầm",
        th: "รถไฟใต้ดิน",
        my: "မြေအောက်ရထား",
        km: "រថភ្លើងក្រោមដី",
      },
      furigana: [
        {
          rb: "地下鉄",
          rt: "ちかてつ",
        },
      ],
      kanjiInfo: [
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "鉄",
          on: ["テツ"],
          kun: ["くろがね"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 199,
      kanji: "地図",
      reading: "ちず",
      meanings: {
        ja: "地図",
        en: "map",
        zh: "地图",
        tw: "地圖",
        ko: "지도",
        vi: "bản đồ",
        th: "แผนที่",
        my: "မြေပုံ",
        km: "ផែនទី",
      },
      furigana: [
        {
          rb: "地図",
          rt: "ちず",
        },
      ],
      kanjiInfo: [
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "図",
          on: ["ズ", "ト"],
          kun: ["え", "はか.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 200,
      kanji: "父",
      reading: "ちち",
      meanings: {
        ja: "父",
        en: "father",
        zh: "父亲",
        tw: "父親",
        ko: "아버지",
        vi: "cha",
        th: "พ่อ",
        my: "ဖေ",
        km: "ឪពុក",
      },
      furigana: [
        {
          rb: "父",
          rt: "ちち",
        },
      ],
      kanjiInfo: [
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
