export const n3part33 = {
  Lesson33: [
    {
      id: 1866,
      kanji: "次ぐ",
      reading: "つぐ",
      meanings: {
        ja: "次ぐ",
        en: "to follow; to come after",
        zh: "次于",
        tw: "次於",
        ko: "뒤따르다",
        vi: "theo sau",
        th: "ตามมา",
        my: "နောက်ဆက်",
        km: "តាមក្រោយ",
      },
      furigana: [
        {
          rb: "次ぐ",
          rt: "つぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "次",
          on: ["ジ", "シ"],
          kun: ["つ.ぐ", "つぎ"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1867,
      kanji: "注ぐ",
      reading: "つぐ",
      meanings: {
        ja: "注ぐ",
        en: "to pour into (a vessel)",
        zh: "倒入",
        tw: "倒入",
        ko: "붓다",
        vi: "rót vào",
        th: "เทลง",
        my: "ထည့်",
        km: "ចាក់ចូល",
      },
      furigana: [
        {
          rb: "注ぐ",
          rt: "つぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "注",
          on: ["チュウ"],
          kun: ["そそ.ぐ", "さ.す", "つ.ぐ"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1868,
      kanji: "付ける",
      reading: "つける",
      meanings: {
        ja: "付ける",
        en: "to attach; to apply",
        zh: "附上",
        tw: "附上",
        ko: "붙이다",
        vi: "gắn vào",
        th: "ติด",
        my: "ပေါင်းထည့်",
        km: "ភ្ជាប់",
      },
      furigana: [
        {
          rb: "付ける",
          rt: "つける",
        },
      ],
      kanjiInfo: [
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1869,
      kanji: "着ける",
      reading: "つける",
      meanings: {
        ja: "着ける",
        en: "to put on (clothes, accessories)",
        zh: "穿戴",
        tw: "穿戴",
        ko: "착용하다",
        vi: "mặc; đeo",
        th: "สวมใส่",
        my: "ဝတ်ဆင်",
        km: "ពាក់",
      },
      furigana: [
        {
          rb: "着ける",
          rt: "つける",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1870,
      kanji: "伝わる",
      reading: "つたわる",
      meanings: {
        ja: "伝わる",
        en: "to be transmitted; to spread",
        zh: "传达",
        tw: "傳達",
        ko: "전해지다",
        vi: "được truyền lại",
        th: "ถูกส่งต่อ",
        my: "ပြန့်",
        km: "បន្តផ្តល់",
      },
      furigana: [
        {
          rb: "伝わる",
          rt: "つたわる",
        },
      ],
      kanjiInfo: [
        {
          char: "伝",
          on: ["デン", "テン"],
          kun: [
            "つた.わる",
            "つた.える",
            "つた.う",
            "つだ.う",
            "-づた.い",
            "つて",
          ],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1871,
      kanji: "繋がる",
      reading: "つながる",
      meanings: {
        ja: "繋がる",
        en: "to be connected",
        zh: "连接",
        tw: "連接",
        ko: "연결되다",
        vi: "kết nối",
        th: "เชื่อมต่อ",
        my: "ချိတ်ဆက်",
        km: "តភ្ជាប់",
      },
      furigana: [
        {
          rb: "繋がる",
          rt: "つながる",
        },
      ],
      kanjiInfo: [
        {
          char: "繋",
          on: ["ケイ"],
          kun: ["つな.ぐ", "かか.る", "か.ける"],
          strokes: 17,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1872,
      kanji: "繋ぐ",
      reading: "つなぐ",
      meanings: {
        ja: "繋ぐ",
        en: "to connect; to tie",
        zh: "连接",
        tw: "連接",
        ko: "잇다",
        vi: "nối",
        th: "เชื่อม",
        my: "ချိတ်ဆက်",
        km: "ភ្ជាប់",
      },
      furigana: [
        {
          rb: "繋ぐ",
          rt: "つなぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "繋",
          on: ["ケイ"],
          kun: ["つな.ぐ", "かか.る", "か.ける"],
          strokes: 17,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1873,
      kanji: "繋げる",
      reading: "つなげる",
      meanings: {
        ja: "繋げる",
        en: "to connect; to link",
        zh: "连接",
        tw: "連接",
        ko: "연결하다",
        vi: "kết nối",
        th: "เชื่อมโยง",
        my: "ချိတ်ဆက်",
        km: "ភ្ជាប់",
      },
      furigana: [
        {
          rb: "繋げる",
          rt: "つなげる",
        },
      ],
      kanjiInfo: [
        {
          char: "繋",
          on: ["ケイ"],
          kun: ["つな.ぐ", "かか.る", "か.ける"],
          strokes: 17,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1874,
      kanji: "積む",
      reading: "つむ",
      meanings: {
        ja: "積む",
        en: "to pile up; to stack",
        zh: "堆积",
        tw: "堆積",
        ko: "쌓다",
        vi: "chồng chất",
        th: "กอง",
        my: "ထပ်တူတိုး",
        km: "កក់ក្តោប",
      },
      furigana: [
        {
          rb: "積む",
          rt: "つむ",
        },
      ],
      kanjiInfo: [
        {
          char: "積",
          on: ["セキ"],
          kun: ["つ.む", "-づ.み", "つ.もる", "つ.もり"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1875,
      kanji: "詰める",
      reading: "つめる",
      meanings: {
        ja: "詰める",
        en: "to stuff into; to fill",
        zh: "塞入",
        tw: "塞入",
        ko: "채우다",
        vi: "nhét vào",
        th: "อัดใส่",
        my: "အတွင်းထည့်",
        km: "បញ្ចូល",
      },
      furigana: [
        {
          rb: "詰める",
          rt: "つめる",
        },
      ],
      kanjiInfo: [
        {
          char: "詰",
          on: ["キツ", "キチ"],
          kun: ["つ.める", "つ.め", "-づ.め", "つ.まる", "つ.む"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1876,
      kanji: "積もる",
      reading: "つもる",
      meanings: {
        ja: "積もる",
        en: "to pile up (naturally, e.g. snow)",
        zh: "积累",
        tw: "積累",
        ko: "쌓이다",
        vi: "chất đống",
        th: "ทับถม",
        my: "အရံပြည့်",
        km: "កក់ក្តោប",
      },
      furigana: [
        {
          rb: "積もる",
          rt: "つもる",
        },
      ],
      kanjiInfo: [
        {
          char: "積",
          on: ["セキ"],
          kun: ["つ.む", "-づ.み", "つ.もる", "つ.もり"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1877,
      kanji: "出会う",
      reading: "であう",
      meanings: {
        ja: "出会う",
        en: "to meet (by chance)",
        zh: "遇见",
        tw: "遇見",
        ko: "우연히 만나다",
        vi: "gặp tình cờ",
        th: "พบโดยบังเอิญ",
        my: "တွေ့ဆုံ",
        km: "ជួបប្រទះ",
      },
      furigana: [
        {
          rb: "出会う",
          rt: "であう",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1878,
      kanji: "適する",
      reading: "てきする",
      meanings: {
        ja: "適する",
        en: "to be suitable; to fit",
        zh: "适合",
        tw: "適合",
        ko: "적합하다",
        vi: "phù hợp",
        th: "เหมาะสม",
        my: "သင့်တင့်",
        km: "សមស្រប",
      },
      furigana: [
        {
          rb: "適する",
          rt: "てきする",
        },
      ],
      kanjiInfo: [
        {
          char: "適",
          on: ["テキ"],
          kun: ["かな.う"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1879,
      kanji: "通す",
      reading: "とおす",
      meanings: {
        ja: "通す",
        en: "to let pass through",
        zh: "通过",
        tw: "通過",
        ko: "통과시키다",
        vi: "cho đi qua",
        th: "ปล่อยผ่าน",
        my: "ဖြတ်လွှတ်",
        km: "ឲ្យឆ្លង",
      },
      furigana: [
        {
          rb: "通す",
          rt: "とおす",
        },
      ],
      kanjiInfo: [
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1880,
      kanji: "通り過ぎる",
      reading: "とおりすぎる",
      meanings: {
        ja: "通り過ぎる",
        en: "to go past; to pass by",
        zh: "经过",
        tw: "經過",
        ko: "지나가다",
        vi: "đi qua",
        th: "ผ่านเลย",
        my: "ဖြတ်သွား",
        km: "ឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "通り過ぎる",
          rt: "とおりすぎる",
        },
      ],
      kanjiInfo: [
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1881,
      kanji: "溶く",
      reading: "とく",
      meanings: {
        ja: "溶く",
        en: "to dissolve (paint, etc.)",
        zh: "溶解",
        tw: "溶解",
        ko: "풀다",
        vi: "hòa tan",
        th: "ละลาย",
        my: "ပျော်",
        km: "លាយ",
      },
      furigana: [
        {
          rb: "溶く",
          rt: "とく",
        },
      ],
      kanjiInfo: [
        {
          char: "溶",
          on: ["ヨウ"],
          kun: ["と.ける", "と.かす", "と.く"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1882,
      kanji: "解く",
      reading: "とく",
      meanings: {
        ja: "解く",
        en: "to untie; to solve",
        zh: "解开；解决",
        tw: "解開；解決",
        ko: "풀다",
        vi: "giải (bài toán; cởi)",
        th: "แก้ปัญหา",
        my: "ဖြေရှင်း",
        km: "ដោះស្រាយ",
      },
      furigana: [
        {
          rb: "解く",
          rt: "とく",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1883,
      kanji: "退く",
      reading: "どく",
      meanings: {
        ja: "退く",
        en: "to step aside",
        zh: "让开",
        tw: "讓開",
        ko: "비키다",
        vi: "tránh ra",
        th: "หลีกทาง",
        my: "လှည့်ပေါ့",
        km: "ជៀស",
      },
      furigana: [
        {
          rb: "退く",
          rt: "どく",
        },
      ],
      kanjiInfo: [
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1884,
      kanji: "溶ける",
      reading: "とける",
      meanings: {
        ja: "溶ける",
        en: "to melt; to dissolve",
        zh: "融化",
        tw: "融化",
        ko: "녹다",
        vi: "tan chảy",
        th: "ละลาย",
        my: "အရည်ပျော်",
        km: "រលាយ",
      },
      furigana: [
        {
          rb: "溶ける",
          rt: "とける",
        },
      ],
      kanjiInfo: [
        {
          char: "溶",
          on: ["ヨウ"],
          kun: ["と.ける", "と.かす", "と.く"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1885,
      kanji: "解ける",
      reading: "とける",
      meanings: {
        ja: "解ける",
        en: "to be solved; to be untied",
        zh: "解决；解开",
        tw: "解決；解開",
        ko: "풀리다",
        vi: "được giải quyết",
        th: "ถูกแก้",
        my: "ဖြေရှင်း",
        km: "ត្រូវដោះ",
      },
      furigana: [
        {
          rb: "解ける",
          rt: "とける",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1886,
      kanji: "閉じる",
      reading: "とじる",
      meanings: {
        ja: "閉じる",
        en: "to close (book, eyes)",
        zh: "闭上",
        tw: "閉上",
        ko: "닫다",
        vi: "đóng lại",
        th: "ปิด",
        my: "ပိတ်",
        km: "បិទ",
      },
      furigana: [
        {
          rb: "閉じる",
          rt: "とじる",
        },
      ],
      kanjiInfo: [
        {
          char: "閉",
          on: ["ヘイ"],
          kun: ["と.じる", "と.ざす", "し.める", "し.まる", "た.てる"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1887,
      kanji: "届く",
      reading: "とどく",
      meanings: {
        ja: "届く",
        en: "to reach; to arrive",
        zh: "到达",
        tw: "到達",
        ko: "닿다",
        vi: "tới; đến",
        th: "ไปถึง",
        my: "ရောက်",
        km: "ឈានដល់",
      },
      furigana: [
        {
          rb: "届く",
          rt: "とどく",
        },
      ],
      kanjiInfo: [
        {
          char: "届",
          on: ["カイ"],
          kun: ["とど.ける", "-とど.け", "とど.く"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1888,
      kanji: "飛ばす",
      reading: "とばす",
      meanings: {
        ja: "飛ばす",
        en: "to let fly; to skip",
        zh: "使飞；跳过",
        tw: "使飛；跳過",
        ko: "날리다",
        vi: "thổi bay; bỏ qua",
        th: "ปลิวไป; ข้ามไป",
        my: "ပစ်ပေါက်",
        km: "ឲ្យហោះ",
      },
      furigana: [
        {
          rb: "飛ばす",
          rt: "とばす",
        },
      ],
      kanjiInfo: [
        {
          char: "飛",
          on: ["ヒ"],
          kun: ["と.ぶ", "と.ばす", "-と.ばす"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1889,
      kanji: "飛び出す",
      reading: "とびだす",
      meanings: {
        ja: "飛び出す",
        en: "to jump out; to rush out",
        zh: "跳出",
        tw: "跳出",
        ko: "뛰어나가다",
        vi: "nhảy ra",
        th: "กระโดดออกมา",
        my: "ခုန်ထွက်",
        km: "លោតចេញ",
      },
      furigana: [
        {
          rb: "飛び出す",
          rt: "とびだす",
        },
      ],
      kanjiInfo: [
        {
          char: "飛",
          on: ["ヒ"],
          kun: ["と.ぶ", "と.ばす", "-と.ばす"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1890,
      kanji: "留める",
      reading: "とめる",
      meanings: {
        ja: "留める",
        en: "to fasten; to stop",
        zh: "固定；停下",
        tw: "固定；停下",
        ko: "고정하다",
        vi: "cố định",
        th: "หยุด; ตรึง",
        my: "တပ်ဆင်",
        km: "ចាក់ឈប់",
      },
      furigana: [
        {
          rb: "留める",
          rt: "とめる",
        },
      ],
      kanjiInfo: [
        {
          char: "留",
          on: ["リュウ", "ル"],
          kun: ["と.める", "と.まる", "とど.める", "とど.まる", "るうぶる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1891,
      kanji: "泊める",
      reading: "とめる",
      meanings: {
        ja: "泊める",
        en: "to give shelter; to let stay overnight",
        zh: "留宿",
        tw: "留宿",
        ko: "재워 주다",
        vi: "cho ở lại",
        th: "ให้พักแรม",
        my: "အိမ်တွင်အိပ်ခို",
        km: "ឲ្យស្នាក់",
      },
      furigana: [
        {
          rb: "泊める",
          rt: "とめる",
        },
      ],
      kanjiInfo: [
        {
          char: "泊",
          on: ["ハク"],
          kun: ["と.まる", "と.める"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1892,
      kanji: "取り上げる",
      reading: "とりあげる",
      meanings: {
        ja: "取り上げる",
        en: "to take up; to adopt",
        zh: "采纳；拿起",
        tw: "採納；拿起",
        ko: "집어 들다",
        vi: "nhặt lên; tiếp nhận",
        th: "หยิบขึ้นมา",
        my: "ယူ",
        km: "យកឡើង",
      },
      furigana: [
        {
          rb: "取り上げる",
          rt: "とりあげる",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1893,
      kanji: "取れる",
      reading: "とれる",
      meanings: {
        ja: "取れる",
        en: "to come off; to be removed",
        zh: "脱落",
        tw: "脫落",
        ko: "빠지다",
        vi: "bong ra",
        th: "หลุด",
        my: "ဖြုတ်",
        km: "រលុង",
      },
      furigana: [
        {
          rb: "取れる",
          rt: "とれる",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1894,
      kanji: "流す",
      reading: "ながす",
      meanings: {
        ja: "流す",
        en: "to drain; to shed (tears, blood)",
        zh: "流出",
        tw: "流出",
        ko: "흘리다",
        vi: "xả; chảy",
        th: "ปล่อยไหล",
        my: "စီးဆင်းစေ",
        km: "បញ្ចេញ",
      },
      furigana: [
        {
          rb: "流す",
          rt: "ながす",
        },
      ],
      kanjiInfo: [
        {
          char: "流",
          on: ["リュウ", "ル"],
          kun: ["なが.れる", "なが.れ", "なが.す", "-なが.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1895,
      kanji: "眺める",
      reading: "ながめる",
      meanings: {
        ja: "眺める",
        en: "to look at; to gaze",
        zh: "眺望",
        tw: "眺望",
        ko: "바라보다",
        vi: "ngắm nhìn",
        th: "ชม",
        my: "ငေးကြည့်",
        km: "ស្ទូចមើល",
      },
      furigana: [
        {
          rb: "眺める",
          rt: "ながめる",
        },
      ],
      kanjiInfo: [
        {
          char: "眺",
          on: ["チョウ"],
          kun: ["なが.める"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1896,
      kanji: "流れる",
      reading: "ながれる",
      meanings: {
        ja: "流れる",
        en: "to flow; to stream",
        zh: "流动",
        tw: "流動",
        ko: "흐르다",
        vi: "chảy",
        th: "ไหล",
        my: "စီးဆင်း",
        km: "ហូរ",
      },
      furigana: [
        {
          rb: "流れる",
          rt: "ながれる",
        },
      ],
      kanjiInfo: [
        {
          char: "流",
          on: ["リュウ", "ル"],
          kun: ["なが.れる", "なが.れ", "なが.す", "-なが.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1897,
      kanji: "亡くす",
      reading: "なくす",
      meanings: {
        ja: "亡くす",
        en: "to lose (by death)",
        zh: "失去（因死亡）",
        tw: "失去（因死亡）",
        ko: "잃다",
        vi: "mất (vì ai chết)",
        th: "สูญเสีย (การตาย)",
        my: "ဆုံးရှုံး",
        km: "បាត់បង់",
      },
      furigana: [
        {
          rb: "亡くす",
          rt: "なくす",
        },
      ],
      kanjiInfo: [
        {
          char: "亡",
          on: ["ボウ", "モウ"],
          kun: ["な.い", "な.き-", "ほろ.びる", "ほろ.ぶ", "ほろ.ぼす"],
          strokes: 3,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1898,
      kanji: "殴る",
      reading: "なぐる",
      meanings: {
        ja: "殴る",
        en: "to hit; to strike",
        zh: "殴打",
        tw: "毆打",
        ko: "때리다",
        vi: "đấm; đánh",
        th: "ต่อย; ตี",
        my: "ရိုက်",
        km: "វាយ",
      },
      furigana: [
        {
          rb: "殴る",
          rt: "なぐる",
        },
      ],
      kanjiInfo: [
        {
          char: "殴",
          on: ["オウ"],
          kun: ["なぐ.る"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1899,
      kanji: "怠ける",
      reading: "なまける",
      meanings: {
        ja: "怠ける",
        en: "to be lazy; to neglect work",
        zh: "懒惰",
        tw: "懶惰",
        ko: "게으르다",
        vi: "lười biếng",
        th: "ขี้เกียจ",
        my: "အပျင်း",
        km: "ខ្ជិល",
      },
      furigana: [
        {
          rb: "怠ける",
          rt: "なまける",
        },
      ],
      kanjiInfo: [
        {
          char: "怠",
          on: ["タイ"],
          kun: ["おこた.る", "なま.ける"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1900,
      kanji: "悩む",
      reading: "なやむ",
      meanings: {
        ja: "悩む",
        en: "to worry; to be troubled",
        zh: "烦恼",
        tw: "煩惱",
        ko: "고민하다",
        vi: "lo lắng",
        th: "กังวล",
        my: "စိုးရိမ်",
        km: "ព្រួយបារម្ភ",
      },
      furigana: [
        {
          rb: "悩む",
          rt: "なやむ",
        },
      ],
      kanjiInfo: [
        {
          char: "悩",
          on: ["ノウ"],
          kun: ["なや.む", "なや.ます", "なや.ましい", "なやみ"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1901,
      kanji: "鳴らす",
      reading: "ならす",
      meanings: {
        ja: "鳴らす",
        en: "to ring; to sound",
        zh: "发出声响",
        tw: "發出聲響",
        ko: "울리다",
        vi: "làm vang lên",
        th: "ทำให้ดังขึ้น",
        my: "အသံထွက်စေ",
        km: "បង្កើតសំឡេង",
      },
      furigana: [
        {
          rb: "鳴らす",
          rt: "ならす",
        },
      ],
      kanjiInfo: [
        {
          char: "鳴",
          on: ["メイ"],
          kun: ["な.く", "な.る", "な.らす"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1902,
      kanji: "為る",
      reading: "なる",
      meanings: {
        ja: "為る",
        en: "to become; to result in",
        zh: "成为",
        tw: "成為",
        ko: "되다",
        vi: "trở thành",
        th: "กลายเป็น",
        my: "ဖြစ်",
        km: "ក្លាយជា",
      },
      furigana: [
        {
          rb: "為る",
          rt: "なる",
        },
      ],
      kanjiInfo: [
        {
          char: "為",
          on: ["イ"],
          kun: ["ため", "な.る", "な.す", "す.る", "たり", "つく.る", "なり"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1903,
      kanji: "生る",
      reading: "なる",
      meanings: {
        ja: "生る",
        en: "to bear fruit",
        zh: "结果",
        tw: "結果",
        ko: "열리다",
        vi: "ra quả",
        th: "ออกผล",
        my: "ဖွားဖက်",
        km: "ផ្លែចេញ",
      },
      furigana: [
        {
          rb: "生る",
          rt: "なる",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1904,
      kanji: "馴れる",
      reading: "なれる",
      meanings: {
        ja: "馴れる",
        en: "to get used to",
        zh: "习惯",
        tw: "習慣",
        ko: "익숙해지다",
        vi: "quen với",
        th: "คุ้นเคย",
        my: "နောက်ကျကျွမ်း",
        km: "ស៊ាំ",
      },
      furigana: [
        {
          rb: "馴れる",
          rt: "なれる",
        },
      ],
      kanjiInfo: [
        {
          char: "馴",
          on: ["ジュン", "シュン", "クン"],
          kun: ["な.れる", "な.らす", "したが.う"],
          strokes: 13,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1905,
      kanji: "似合う",
      reading: "にあう",
      meanings: {
        ja: "似合う",
        en: "to suit; to match",
        zh: "适合",
        tw: "適合",
        ko: "어울리다",
        vi: "hợp với",
        th: "เหมาะกับ",
        my: "တော်တော်တူ",
        km: "សមស្រប",
      },
      furigana: [
        {
          rb: "似合う",
          rt: "にあう",
        },
      ],
      kanjiInfo: [
        {
          char: "似",
          on: ["ジ"],
          kun: ["に.る", "ひ.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1906,
      kanji: "煮える",
      reading: "にえる",
      meanings: {
        ja: "煮える",
        en: "to be boiled; to be cooked",
        zh: "煮熟",
        tw: "煮熟",
        ko: "끓다",
        vi: "sôi",
        th: "เดือด",
        my: "ကြွေ",
        km: "រំពុះ",
      },
      furigana: [
        {
          rb: "煮える",
          rt: "にえる",
        },
      ],
      kanjiInfo: [
        {
          char: "煮",
          on: ["シャ"],
          kun: ["に.る", "-に", "に.える", "に.やす"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1907,
      kanji: "握る",
      reading: "にぎる",
      meanings: {
        ja: "握る",
        en: "to grasp; to hold",
        zh: "握",
        tw: "握",
        ko: "쥐다",
        vi: "nắm chặt",
        th: "กำ",
        my: "ဆုပ်ကိုင်",
        km: "កាន់",
      },
      furigana: [
        {
          rb: "握る",
          rt: "にぎる",
        },
      ],
      kanjiInfo: [
        {
          char: "握",
          on: ["アク"],
          kun: ["にぎ.る"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1908,
      kanji: "煮る",
      reading: "にる",
      meanings: {
        ja: "煮る",
        en: "to boil; to simmer",
        zh: "煮",
        tw: "煮",
        ko: "끓이다",
        vi: "nấu",
        th: "ต้ม",
        my: "ချက်",
        km: "រំពុះ",
      },
      furigana: [
        {
          rb: "煮る",
          rt: "にる",
        },
      ],
      kanjiInfo: [
        {
          char: "煮",
          on: ["シャ"],
          kun: ["に.る", "-に", "に.える", "に.やす"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1909,
      kanji: "抜く",
      reading: "ぬく",
      meanings: {
        ja: "抜く",
        en: "to pull out; to extract",
        zh: "拔出",
        tw: "拔出",
        ko: "뽑다",
        vi: "nhổ; rút ra",
        th: "ดึงออก",
        my: "ဆွဲထုတ်",
        km: "ដកចេញ",
      },
      furigana: [
        {
          rb: "抜く",
          rt: "ぬく",
        },
      ],
      kanjiInfo: [
        {
          char: "抜",
          on: ["バツ", "ハツ", "ハイ"],
          kun: ["ぬ.く", "-ぬ.く", "ぬ.き", "ぬ.ける", "ぬ.かす", "ぬ.かる"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1910,
      kanji: "抜ける",
      reading: "ぬける",
      meanings: {
        ja: "抜ける",
        en: "to come out; to fall out",
        zh: "脱落",
        tw: "脫落",
        ko: "빠지다",
        vi: "rụng ra",
        th: "หลุดออก",
        my: "ကျဉ်းကျဉ်းထွက်",
        km: "រលុង",
      },
      furigana: [
        {
          rb: "抜ける",
          rt: "ぬける",
        },
      ],
      kanjiInfo: [
        {
          char: "抜",
          on: ["バツ", "ハツ", "ハイ"],
          kun: ["ぬ.く", "-ぬ.く", "ぬ.き", "ぬ.ける", "ぬ.かす", "ぬ.かる"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1911,
      kanji: "濡らす",
      reading: "ぬらす",
      meanings: {
        ja: "濡らす",
        en: "to wet; to soak",
        zh: "弄湿",
        tw: "弄濕",
        ko: "적시다",
        vi: "làm ướt",
        th: "ทำให้เปียก",
        my: "စိုစွတ်စေ",
        km: "បន្សាប",
      },
      furigana: [
        {
          rb: "濡らす",
          rt: "ぬらす",
        },
      ],
      kanjiInfo: [
        {
          char: "濡",
          on: ["ジュ", "ニュ"],
          kun: [
            "ぬれ.る",
            "ぬら.す",
            "ぬ.れる",
            "ぬ.らす",
            "うるお.い",
            "うるお.う",
            "うるお.す",
          ],
          strokes: 17,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1912,
      kanji: "願う",
      reading: "ねがう",
      meanings: {
        ja: "願う",
        en: "to wish; to desire",
        zh: "希望",
        tw: "希望",
        ko: "원하다",
        vi: "ước; mong",
        th: "ปรารถนา",
        my: "ဆန္ဒထား",
        km: "ប្រាថ្នា",
      },
      furigana: [
        {
          rb: "願う",
          rt: "ねがう",
        },
      ],
      kanjiInfo: [
        {
          char: "願",
          on: ["ガン"],
          kun: ["ねが.う", "-ねがい"],
          strokes: 19,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1913,
      kanji: "残す",
      reading: "のこす",
      meanings: {
        ja: "残す",
        en: "to leave behind",
        zh: "留下",
        tw: "留下",
        ko: "남기다",
        vi: "để lại",
        th: "เหลือไว้",
        my: "ပျက်စီး",
        km: "ទុកសល់",
      },
      furigana: [
        {
          rb: "残す",
          rt: "のこす",
        },
      ],
      kanjiInfo: [
        {
          char: "残",
          on: ["ザン", "サン"],
          kun: ["のこ.る", "のこ.す", "そこな.う", "のこ.り"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1914,
      kanji: "乗せる",
      reading: "のせる",
      meanings: {
        ja: "乗せる",
        en: "to place on; to give a ride",
        zh: "放上；载",
        tw: "放上；載",
        ko: "태우다",
        vi: "chở; đặt lên",
        th: "วางขึ้น",
        my: "တင်ပို့",
        km: "ដាក់ឡើង",
      },
      furigana: [
        {
          rb: "乗せる",
          rt: "のせる",
        },
      ],
      kanjiInfo: [
        {
          char: "乗",
          on: ["ジョウ", "ショウ"],
          kun: ["の.る", "-の.り", "の.せる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1915,
      kanji: "載せる",
      reading: "のせる",
      meanings: {
        ja: "載せる",
        en: "to place on; to publish",
        zh: "刊登；放上",
        tw: "刊登；放上",
        ko: "싣다",
        vi: "đăng tải; đặt lên",
        th: "ลงพิมพ์; วางขึ้น",
        my: "တင်သွင်း",
        km: "ផ្សាយ",
      },
      furigana: [
        {
          rb: "載せる",
          rt: "のせる",
        },
      ],
      kanjiInfo: [
        {
          char: "載",
          on: ["サイ"],
          kun: ["の.せる", "の.る"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
