export const n3part10 = {
  Lesson10: [
    {
      id: 451,
      kanji: "器械",
      reading: "きかい",
      meanings: {
        ja: "道具・装置。機械に似た語。",
        en: "apparatus; instrument (device)",
        zh: "器械；仪器",
        tw: "器械；儀器",
        ko: "기계 장치; 기구",
        vi: "thiết bị; dụng cụ",
        th: "เครื่องมือ; อุปกรณ์",
        my: "ကိရိယာ; ကိရိယာပစ္စည်း",
        km: "ឧបករណ៍; ឧបករណ៍វាស់វែង",
      },
      furigana: [
        {
          rb: "器械",
          rt: "きかい",
        },
      ],
      kanjiInfo: [
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "械",
          on: ["カイ"],
          kun: ["かせ"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 452,
      kanji: "議会",
      reading: "ぎかい",
      meanings: {
        ja: "立法機関。国会・州議会など。",
        en: "parliament; assembly",
        zh: "议会",
        tw: "議會",
        ko: "의회",
        vi: "nghị viện; quốc hội",
        th: "รัฐสภา; สภานิติบัญญัติ",
        my: "လွှတ်တော်; အစည်းအဝေး",
        km: "រដ្ឋសភា; សភា",
      },
      furigana: [
        {
          rb: "議会",
          rt: "ぎかい",
        },
      ],
      kanjiInfo: [
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 453,
      kanji: "期間",
      reading: "きかん",
      meanings: {
        ja: "ある始まりから終わりまでの時間。",
        en: "period; term; duration",
        zh: "期间",
        tw: "期間",
        ko: "기간",
        vi: "thời kỳ; khoảng thời gian",
        th: "ช่วงเวลา; ระยะเวลา",
        my: "ကာလ; ကြာချိန်",
        km: "រយៈពេល",
      },
      furigana: [
        {
          rb: "期間",
          rt: "きかん",
        },
      ],
      kanjiInfo: [
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 454,
      kanji: "機関",
      reading: "きかん",
      meanings: {
        ja: "①組織・機構 ②エンジン。",
        en: "organization body; engine",
        zh: "机关；机构；引擎",
        tw: "機關；機構；引擎",
        ko: "기관(조직); 기관(엔진)",
        vi: "cơ quan/tổ chức; động cơ",
        th: "หน่วยงาน/องค์กร; เครื่องยนต์",
        my: "အဖွဲ့အစည်း; အင်ဂျင်",
        km: "ស្ថាប័ន/អង្គភាព; ម៉ាស៊ីន",
      },
      furigana: [
        {
          rb: "機関",
          rt: "きかん",
        },
      ],
      kanjiInfo: [
        {
          char: "機",
          on: ["キ"],
          kun: ["はた"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "関",
          on: ["カン"],
          kun: ["せき", "-ぜき", "かか.わる", "からくり", "かんぬき"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 455,
      kanji: "企業",
      reading: "きぎょう",
      meanings: {
        ja: "営利を目的とする組織。会社。",
        en: "enterprise; company; business",
        zh: "企业",
        tw: "企業",
        ko: "기업",
        vi: "doanh nghiệp; công ty",
        th: "กิจการ; บริษัท",
        my: "စီးပွားရေးလုပ်ငန်း; ကုမ္ပဏီ",
        km: "សហគ្រាស; ក្រុមហ៊ុន",
      },
      furigana: [
        {
          rb: "企業",
          rt: "きぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "企",
          on: ["キ"],
          kun: ["くわだ.てる", "たくら.む"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 456,
      kanji: "期限",
      reading: "きげん",
      meanings: {
        ja: "定められた終わりの時。",
        en: "deadline; time limit; due date",
        zh: "期限；截止日期",
        tw: "期限；截止日",
        ko: "기한; 마감",
        vi: "kỳ hạn; hạn chót",
        th: "กำหนดเวลา; เส้นตาย",
        my: "သတ်မှတ်ထားသောကာလအဆုံး; နောက်ဆုံးရက်",
        km: "កាលកំណត់; ថ្ងៃផុតកំណត់",
      },
      furigana: [
        {
          rb: "期限",
          rt: "きげん",
        },
      ],
      kanjiInfo: [
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "限",
          on: ["ゲン"],
          kun: ["かぎ.る", "かぎ.り", "-かぎ.り"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 457,
      kanji: "機嫌",
      reading: "きげん",
      meanings: {
        ja: "気分・気持ちの良し悪し。",
        en: "mood; temper; spirits",
        zh: "心情；情绪",
        tw: "心情；情緒",
        ko: "기분; 심기",
        vi: "tâm trạng; tính khí",
        th: "อารมณ์; อารมณ์ดี/เสีย",
        my: "စိတ်အနေအထား",
        km: "អារម្មណ៍; មនោសញ្ចេតនា",
      },
      furigana: [
        {
          rb: "機嫌",
          rt: "きげん",
        },
      ],
      kanjiInfo: [
        {
          char: "機",
          on: ["キ"],
          kun: ["はた"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "嫌",
          on: ["ケン", "ゲン"],
          kun: ["きら.う", "きら.い", "いや"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 458,
      kanji: "気候",
      reading: "きこう",
      meanings: {
        ja: "ある地域で長期的に見られる天候の傾向。",
        en: "climate",
        zh: "气候",
        tw: "氣候",
        ko: "기후",
        vi: "khí hậu",
        th: "ภูมิอากาศ",
        my: "အခြေအနေရာသီဥတု",
        km: "អាកាសធាតុ",
      },
      furigana: [
        {
          rb: "気候",
          rt: "きこう",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "候",
          on: ["コウ"],
          kun: ["そうろう"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 459,
      kanji: "岸",
      reading: "きし",
      meanings: {
        ja: "水辺の陸地。岸辺。",
        en: "bank; shore",
        zh: "岸；岸边",
        tw: "岸；岸邊",
        ko: "기슭; 강둑; 해안",
        vi: "bờ (sông/biển)",
        th: "ฝั่ง; ชายฝั่ง",
        my: "ကမ်းပါး",
        km: "កំពង់ច្រាំង; ឆ្នេរ",
      },
      furigana: [
        {
          rb: "岸",
          rt: "きし",
        },
      ],
      kanjiInfo: [
        {
          char: "岸",
          on: ["ガン"],
          kun: ["きし"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 460,
      kanji: "生地",
      reading: "きじ",
      meanings: {
        ja: "布地。素材そのもの。",
        en: "fabric; cloth; dough/batter",
        zh: "布料；生坯；（面）团/面糊",
        tw: "布料；材質本體；麵糰/麵糊",
        ko: "옷감; 원단; 반죽",
        vi: "vải; chất liệu; bột (bánh)",
        th: "ผ้าหรือเนื้อผ้า; แป้งโด/แป้งเหลว",
        my: "အဝတ်အိပ်; ပစ္စည်းမူရင်း; ထောင်းဆန်/မုန့်သုတ်",
        km: "ក្រណាត់; វត្ថុធាតុដើម; ម្សៅ (សាំងវិច/នំ)",
      },
      furigana: [
        {
          rb: "生地",
          rt: "きじ",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 461,
      kanji: "記事",
      reading: "きじ",
      meanings: {
        ja: "新聞・雑誌などの文章。",
        en: "news article; report",
        zh: "报道；文章",
        tw: "報導；文章",
        ko: "기사; 보도문",
        vi: "bài báo; phóng sự",
        th: "บทความข่าว; รายงาน",
        my: "စာနယ်ဇင်းဆောင်းပါး",
        km: "អត្ថបទព័ត៌មាន",
      },
      furigana: [
        {
          rb: "記事",
          rt: "きじ",
        },
      ],
      kanjiInfo: [
        {
          char: "記",
          on: ["キ"],
          kun: ["しる.す"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 462,
      kanji: "技師",
      reading: "ぎし",
      meanings: {
        ja: "専門技術者。",
        en: "engineer; technician (licensed)",
        zh: "工程师；技师",
        tw: "工程師；技師",
        ko: "기사(기술자)",
        vi: "kỹ sư; kỹ thuật viên",
        th: "วิศวกร; ช่างเทคนิค",
        my: "အင်ဂျင်နီယာ; နည်းပညာရှင်",
        km: "វិស្វករ; បច្ចេកទេសករ",
      },
      furigana: [
        {
          rb: "技師",
          rt: "ぎし",
        },
      ],
      kanjiInfo: [
        {
          char: "技",
          on: ["ギ"],
          kun: ["わざ"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "師",
          on: ["シ"],
          kun: ["いくさ"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 463,
      kanji: "記者",
      reading: "きしゃ",
      meanings: {
        ja: "取材して記事を書く人。",
        en: "reporter; journalist",
        zh: "记者",
        tw: "記者",
        ko: "기자",
        vi: "phóng viên; nhà báo",
        th: "ผู้สื่อข่าว; นักข่าว",
        my: "သတင်းထောက်",
        km: "អ្នកនិពន្ធព័ត៌មាន; អ្នកកាសែត",
      },
      furigana: [
        {
          rb: "記者",
          rt: "きしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "記",
          on: ["キ"],
          kun: ["しる.す"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "者",
          on: ["シャ"],
          kun: ["もの"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 464,
      kanji: "傷",
      reading: "きず",
      meanings: {
        ja: "けがや欠点。傷あと。",
        en: "wound; injury; scar; flaw",
        zh: "伤口；伤害；疤痕；瑕疵",
        tw: "傷口；傷害；疤痕；瑕疵",
        ko: "상처; 흉터; 결점",
        vi: "vết thương; sẹo; khiếm khuyết",
        th: "บาดแผล; รอยแผล; ข้อบกพร่อง",
        my: "ဒဏ်ရာ; အမာရွတ်; ချို့ယွင်းချက်",
        km: "របួស; ស្នាម; ខ្វះខាត",
      },
      furigana: [
        {
          rb: "傷",
          rt: "きず",
        },
      ],
      kanjiInfo: [
        {
          char: "傷",
          on: ["ショウ"],
          kun: ["きず", "いた.む", "いた.める"],
          strokes: 13,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 465,
      kanji: "期待",
      reading: "きたい",
      meanings: {
        ja: "よい結果を望む気持ち。",
        en: "expectation; hope",
        zh: "期待",
        tw: "期待",
        ko: "기대",
        vi: "kỳ vọng; mong đợi",
        th: "ความคาดหวัง",
        my: "မျှော်လင့်ချက်",
        km: "ការរំពឹងទុក",
      },
      furigana: [
        {
          rb: "期待",
          rt: "きたい",
        },
      ],
      kanjiInfo: [
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "待",
          on: ["タイ"],
          kun: ["ま.つ", "-ま.ち"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 466,
      kanji: "気体",
      reading: "きたい",
      meanings: {
        ja: "物質の三態の一つ。ガス。",
        en: "gas (gaseous state)",
        zh: "气体",
        tw: "氣體",
        ko: "기체",
        vi: "khí (trạng thái khí)",
        th: "แก๊ส (สถานะแก๊ส)",
        my: "ငွေ့ရည်အခြေအနေ; ဂတ်",
        km: "ឧស្ម័ន",
      },
      furigana: [
        {
          rb: "気体",
          rt: "きたい",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 467,
      kanji: "帰宅",
      reading: "きたく",
      meanings: {
        ja: "自宅へ帰ること。",
        en: "returning home",
        zh: "回家",
        tw: "回家",
        ko: "귀가",
        vi: "về nhà",
        th: "กลับบ้าน",
        my: "အိမ်ပြန်သွားခြင်း",
        km: "ត្រឡប់ទៅផ្ទះ",
      },
      furigana: [
        {
          rb: "帰宅",
          rt: "きたく",
        },
      ],
      kanjiInfo: [
        {
          char: "帰",
          on: ["キ"],
          kun: ["かえ.る", "かえ.す", "おく.る", "とつ.ぐ"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "宅",
          on: ["タク"],
          kun: [],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 468,
      kanji: "議長",
      reading: "ぎちょう",
      meanings: {
        ja: "会議を主宰する人。",
        en: "chairperson (of a meeting)",
        zh: "议长；主席",
        tw: "議長；主席",
        ko: "의장",
        vi: "chủ tọa; chủ tịch (phiên họp)",
        th: "ประธานสภา/ที่ประชุม",
        my: "အစည်းအဝေး ဥက္ကဋ္ဌ",
        km: "ប្រធានកិច្ចប្រជុំ",
      },
      furigana: [
        {
          rb: "議長",
          rt: "ぎちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "長",
          on: ["チョウ"],
          kun: ["なが.い", "おさ"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 469,
      kanji: "記入",
      reading: "きにゅう",
      meanings: {
        ja: "用紙などに書き込むこと。",
        en: "entry; filling in (a form)",
        zh: "填写；填入",
        tw: "填寫；填入",
        ko: "기입; 작성",
        vi: "điền (vào mẫu); ghi vào",
        th: "การกรอก; การเขียนลง",
        my: "ဖြည့်သွင်းရေးသားခြင်း",
        km: "បំពេញ (សំណុំបែបបទ)",
      },
      furigana: [
        {
          rb: "記入",
          rt: "きにゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "記",
          on: ["キ"],
          kun: ["しる.す"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 470,
      kanji: "記念",
      reading: "きねん",
      meanings: {
        ja: "思い出として残すこと。",
        en: "commemoration; memento",
        zh: "纪念",
        tw: "紀念",
        ko: "기념",
        vi: "kỷ niệm",
        th: "การรำลึก; ของที่ระลึก",
        my: "ဦးတည်မှတ်ဉာဏ်; မှတ်တမ်းရာ",
        km: "អនុស្សាវរីយ៍; វត្ថុអនុស្សាវរីយ៍",
      },
      furigana: [
        {
          rb: "記念",
          rt: "きねん",
        },
      ],
      kanjiInfo: [
        {
          char: "記",
          on: ["キ"],
          kun: ["しる.す"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "念",
          on: ["ネン"],
          kun: [],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 471,
      kanji: "機能",
      reading: "きのう",
      meanings: {
        ja: "働き。役割。機能。",
        en: "function; capability",
        zh: "功能",
        tw: "功能",
        ko: "기능",
        vi: "chức năng",
        th: "ฟังก์ชัน; ความสามารถ",
        my: "လုပ်ဆောင်ချက်",
        km: "មុខងារ; សមត្ថភាព",
      },
      furigana: [
        {
          rb: "機能",
          rt: "きのう",
        },
      ],
      kanjiInfo: [
        {
          char: "機",
          on: ["キ"],
          kun: ["はた"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 472,
      kanji: "寄付",
      reading: "きふ",
      meanings: {
        ja: "金品などを贈ること。",
        en: "donation; contribution",
        zh: "捐献；捐款",
        tw: "捐獻；捐款",
        ko: "기부",
        vi: "quyên góp; đóng góp",
        th: "การบริจาค",
        my: "လှူဒါန်းမှု",
        km: "បរិច្ចាគ; ការរួមចំណែក",
      },
      furigana: [
        {
          rb: "寄付",
          rt: "きふ",
        },
      ],
      kanjiInfo: [
        {
          char: "寄",
          on: ["キ"],
          kun: ["よ.る", "-よ.り", "よ.せる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 473,
      kanji: "希望",
      reading: "きぼう",
      meanings: {
        ja: "のぞみ。かなえたい事柄。",
        en: "hope; wish; desire",
        zh: "希望；愿望",
        tw: "希望；願望",
        ko: "희망; 소망",
        vi: "hy vọng; nguyện vọng",
        th: "ความหวัง; ความปรารถนา",
        my: "မျှော်လင့်ချက်; ဆန္ဒ",
        km: "សង្ឃឹម; បំណងប្រាថ្នា",
      },
      furigana: [
        {
          rb: "希望",
          rt: "きぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "希",
          on: ["キ", "ケ"],
          kun: ["まれ", "こいねが.う"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "望",
          on: ["ボウ", "モウ"],
          kun: ["のぞ.む", "もち"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 474,
      kanji: "基本",
      reading: "きほん",
      meanings: {
        ja: "物事の土台・基礎。",
        en: "basics; foundation; fundamentals",
        zh: "基本；基础",
        tw: "基本；基礎",
        ko: "기본",
        vi: "cơ bản; nền tảng",
        th: "พื้นฐาน",
        my: "အခြေခံ; အုတ်မြစ်",
        km: "មូលដ្ឋាន; ជាតិដ្ឋាន",
      },
      furigana: [
        {
          rb: "基本",
          rt: "きほん",
        },
      ],
      kanjiInfo: [
        {
          char: "基",
          on: ["キ"],
          kun: ["もと", "もとい"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 475,
      kanji: "決まり",
      reading: "きまり",
      meanings: {
        ja: "定められた規則・きまり。",
        en: "rule; regulation; convention",
        zh: "规定；规矩",
        tw: "規定；規矩",
        ko: "규정; 규칙",
        vi: "quy định; luật lệ",
        th: "กฎเกณฑ์; ธรรมเนียม",
        my: "စည်းကမ်းချက်",
        km: "ច្បាប់; នីតិវិធី",
      },
      furigana: [
        {
          rb: "決まり",
          rt: "きまり",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 476,
      kanji: "気味",
      reading: "きみ",
      meanings: {
        ja: "…の感じがすること（例：疲れ気味）。",
        en: "tendency; touch/tinge of (…-ish)",
        zh: "有点…的倾向",
        tw: "有點…的傾向",
        ko: "…기미; …기는",
        vi: "hơi có xu hướng …; có vẻ …",
        th: "ออกจะ…; มีแนวโน้ม…",
        my: "အနည်းငယ် … သဘော",
        km: "មានទំនោរ…; ម្រិតហ្នឹង…បន្តិច",
      },
      furigana: [
        {
          rb: "気味",
          rt: "きみ",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 477,
      kanji: "義務",
      reading: "ぎむ",
      meanings: {
        ja: "しなければならない務め。",
        en: "duty; obligation",
        zh: "义务",
        tw: "義務",
        ko: "의무",
        vi: "nghĩa vụ",
        th: "หน้าที่ (ตามกฎหมาย/ศีลธรรม)",
        my: "တာဝန်; ဝတ္တရား",
        km: "កាតព្វកិច្ច",
      },
      furigana: [
        {
          rb: "義務",
          rt: "ぎむ",
        },
      ],
      kanjiInfo: [
        {
          char: "義",
          on: ["ギ"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "務",
          on: ["ム"],
          kun: ["つと.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 478,
      kanji: "疑問",
      reading: "ぎもん",
      meanings: {
        ja: "疑い・わからない点。",
        en: "doubt; question",
        zh: "疑问",
        tw: "疑問",
        ko: "의문",
        vi: "nghi vấn; thắc mắc",
        th: "ข้อสงสัย; คำถาม",
        my: "သ nghi သံသယ; မေးခွန်း",
        km: "សំណួរ; ជម្រាបសុំសង្ស័យ",
      },
      furigana: [
        {
          rb: "疑問",
          rt: "ぎもん",
        },
      ],
      kanjiInfo: [
        {
          char: "疑",
          on: ["ギ"],
          kun: ["うたが.う"],
          strokes: 14,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "問",
          on: ["モン"],
          kun: ["と.う", "と.い", "とん"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 479,
      kanji: "キャプテン",
      reading: "キャプテン",
      meanings: {
        ja: "主将。チームのまとめ役。",
        en: "captain (team leader)",
        zh: "队长；船长（语境依赖）",
        tw: "隊長；船長（依語境）",
        ko: "캡틴; 주장",
        vi: "đội trưởng; thuyền trưởng (ngữ cảnh)",
        th: "กัปตัน; หัวหน้าทีม",
        my: "ကက်ပတိန် (အသင်းခေါင်းဆောင်)",
        km: "កាប្តង់; ខេបថិន (មេក្រុម)",
      },
      furigana: [
        {
          rb: "キャプテン",
          rt: "キャプテン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 480,
      kanji: "キャンプ",
      reading: "キャンプ",
      meanings: {
        ja: "野外での宿泊・活動。",
        en: "camping; camp",
        zh: "露营；营地",
        tw: "露營；營地",
        ko: "캠핑; 캠프",
        vi: "cắm trại; trại",
        th: "แคมป์; การตั้งแคมป์",
        my: "စခန်းချခြင်း; စခန်း",
        km: "ជំរុំ; ការជំរុំជាយព្រៃ",
      },
      furigana: [
        {
          rb: "キャンプ",
          rt: "キャンプ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 481,
      kanji: "級",
      reading: "きゅう",
      meanings: {
        ja: "等級・ランク。",
        en: "grade; class; level",
        zh: "等级；级别",
        tw: "等級；級別",
        ko: "급; 등급",
        vi: "cấp; hạng",
        th: "ระดับ; ชั้น",
        my: "အဆင့်; အတန်း",
        km: "កម្រិត; ថ្នាក់",
      },
      furigana: [
        {
          rb: "級",
          rt: "きゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "級",
          on: ["キュウ"],
          kun: [],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 482,
      kanji: "球",
      reading: "きゅう",
      meanings: {
        ja: "球状のもの。ボール。",
        en: "sphere; ball",
        zh: "球；球体",
        tw: "球；球體",
        ko: "구; 공",
        vi: "quả cầu; bóng",
        th: "ลูกบอล; ทรงกลม",
        my: "စက်ကွင်း; ဘောလုံး",
        km: "បាល់; រង្វង់មូល",
      },
      furigana: [
        {
          rb: "球",
          rt: "きゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "球",
          on: ["キュウ"],
          kun: ["たま"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 483,
      kanji: "休暇",
      reading: "きゅうか",
      meanings: {
        ja: "仕事・学校を休む期間。",
        en: "holiday; vacation; leave",
        zh: "休假；假期",
        tw: "休假；假期",
        ko: "휴가",
        vi: "kỳ nghỉ; nghỉ phép",
        th: "วันหยุดพักผ่อน; ลาพัก",
        my: "အလုပ်ပိတ်ရက်; အားလပ်ရက်",
        km: "វិស្សមកាល; រយៈពេលឈប់សម្រាក",
      },
      furigana: [
        {
          rb: "休暇",
          rt: "きゅうか",
        },
      ],
      kanjiInfo: [
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "暇",
          on: ["カ"],
          kun: ["ひま", "いとま"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 484,
      kanji: "休憩",
      reading: "きゅうけい",
      meanings: {
        ja: "途中で少し休むこと。",
        en: "rest; break (short pause)",
        zh: "休息（短暂）",
        tw: "休息（短暫）",
        ko: "휴식; 휴게",
        vi: "nghỉ giải lao",
        th: "พักเบรก; พักชั่วคราว",
        my: "တိုက်တစ်ဝက်နားချင်ခြင်း",
        km: "សម្រាកខ្លី; សម្រាកពេលតិច",
      },
      furigana: [
        {
          rb: "休憩",
          rt: "きゅうけい",
        },
      ],
      kanjiInfo: [
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "憩",
          on: ["ケイ"],
          kun: ["いこ.い", "いこ.う"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 485,
      kanji: "吸収",
      reading: "きゅうしゅう",
      meanings: {
        ja: "吸い取って取り込むこと。",
        en: "absorption; uptake",
        zh: "吸收",
        tw: "吸收",
        ko: "흡수",
        vi: "hấp thụ",
        th: "การดูดซึม",
        my: "စုပ်ယူခြင်း",
        km: "ការស្រូបយក",
      },
      furigana: [
        {
          rb: "吸収",
          rt: "きゅうしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "吸",
          on: ["キュウ"],
          kun: ["す.う"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "収",
          on: ["シュウ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 486,
      kanji: "救助",
      reading: "きゅうじょ",
      meanings: {
        ja: "困っている人を助けること。",
        en: "rescue; relief",
        zh: "救助；救援",
        tw: "救助；救援",
        ko: "구조; 구호",
        vi: "cứu trợ; cứu hộ",
        th: "การช่วยเหลือ; กู้ภัย",
        my: "ကယ်ဆယ်ရေး",
        km: "សង្គ្រោះ; ជួយសង្គ្រោះ",
      },
      furigana: [
        {
          rb: "救助",
          rt: "きゅうじょ",
        },
      ],
      kanjiInfo: [
        {
          char: "救",
          on: ["キュウ"],
          kun: ["すく.う"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "助",
          on: ["ジョ"],
          kun: ["たす.ける", "たす.かる", "す.ける", "すけ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 487,
      kanji: "休息",
      reading: "きゅうそく",
      meanings: {
        ja: "体や心を休めること。",
        en: "rest; repose",
        zh: "休息",
        tw: "休息",
        ko: "휴식",
        vi: "nghỉ ngơi",
        th: "พักผ่อน",
        my: "အနားယူမှု",
        km: "ការសម្រាក",
      },
      furigana: [
        {
          rb: "休息",
          rt: "きゅうそく",
        },
      ],
      kanjiInfo: [
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "息",
          on: ["ソク"],
          kun: ["いき"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 488,
      kanji: "給料",
      reading: "きゅうりょう",
      meanings: {
        ja: "働きの対価として支払われる金銭。",
        en: "salary; pay; wages",
        zh: "工资；薪水",
        tw: "薪水；工資",
        ko: "급여; 월급",
        vi: "tiền lương",
        th: "เงินเดือน; ค่าจ้าง",
        my: "လစာ; လခ",
        km: "ប្រាក់ខែ; ចំណូល",
      },
      furigana: [
        {
          rb: "給料",
          rt: "きゅうりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "給",
          on: ["キュウ"],
          kun: ["たま.う", "たも.う", "-たま.え"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "料",
          on: ["リョウ"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 489,
      kanji: "教科書",
      reading: "きょうかしょ",
      meanings: {
        ja: "学習用の本。テキスト。",
        en: "textbook",
        zh: "教科书",
        tw: "教科書",
        ko: "교과서",
        vi: "sách giáo khoa",
        th: "หนังสือเรียน",
        my: "သင်ခန်းစာစာအုပ်",
        km: "សៀវភៅសិក្សា",
      },
      furigana: [
        {
          rb: "教科書",
          rt: "きょうかしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "教",
          on: ["キョウ"],
          kun: ["おし.える", "おそ.わる"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 490,
      kanji: "競技",
      reading: "きょうぎ",
      meanings: {
        ja: "一定の規則で優劣を競うスポーツ。",
        en: "competition; sporting event",
        zh: "竞技；比赛（体育）",
        tw: "競技；比賽（體育）",
        ko: "경기; 시합",
        vi: "thi đấu; môn thi",
        th: "การแข่งขันกีฬา",
        my: "ပြိုင်ပွဲ (အားကစား)",
        km: "ការប្រកួតកីឡា",
      },
      furigana: [
        {
          rb: "競技",
          rt: "きょうぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "競",
          on: ["キョウ", "ケイ"],
          kun: ["きそ.う", "せ.る", "くら.べる"],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "技",
          on: ["ギ"],
          kun: ["わざ"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 491,
      kanji: "行儀",
      reading: "ぎょうぎ",
      meanings: {
        ja: "作法・礼儀のよさ。",
        en: "manners; behavior",
        zh: "举止；礼貌",
        tw: "舉止；禮貌",
        ko: "예의범절; 행실",
        vi: "cách cư xử; lễ nghi",
        th: "มารยาท; ระเบียบวินัย",
        my: "ယဥ်ကျေးမှု; အပြုအမူ",
        km: "មាឌធ្មត់; មាឌសំរាប់ការ",
      },
      furigana: [
        {
          rb: "行儀",
          rt: "ぎょうぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "儀",
          on: ["ギ"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 492,
      kanji: "供給",
      reading: "きょうきゅう",
      meanings: {
        ja: "必要なものを供すること。サプライ。",
        en: "supply; provisioning",
        zh: "供给",
        tw: "供給",
        ko: "공급",
        vi: "cung cấp",
        th: "การจัดหา; อุปทาน",
        my: "ပြည်ထောင်စုပစ္စည်းပေးအပ်မှု",
        km: "ការផ្គត់ផ្គង់",
      },
      furigana: [
        {
          rb: "供給",
          rt: "きょうきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "供",
          on: ["キョウ", "ク", "クウ", "グ"],
          kun: ["そな.える", "とも", "-ども"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "給",
          on: ["キュウ"],
          kun: ["たま.う", "たも.う", "-たま.え"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 493,
      kanji: "教授",
      reading: "きょうじゅ",
      meanings: {
        ja: "大学の最高位の教員。教えること。",
        en: "professor; instruction",
        zh: "教授；教授（教学）",
        tw: "教授；教導",
        ko: "교수",
        vi: "giáo sư; giảng dạy",
        th: "ศาสตราจารย์; การสอน",
        my: "ပညာခွင့်ပေးသူ (စာတမ်းကြီး); သင်ကြားခြင်း",
        km: "សាស្ដ្រាចារ្យ; ការបង្រៀន",
      },
      furigana: [
        {
          rb: "教授",
          rt: "きょうじゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "教",
          on: ["キョウ"],
          kun: ["おし.える", "おそ.わる"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "授",
          on: ["ジュ"],
          kun: ["さず.ける", "さず.かる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 494,
      kanji: "強調",
      reading: "きょうちょう",
      meanings: {
        ja: "特に強く述べること。",
        en: "emphasis; stress (emphasizing)",
        zh: "强调",
        tw: "強調",
        ko: "강조",
        vi: "nhấn mạnh",
        th: "การเน้นย้ำ",
        my: "အလေးထားပြောခြင်း",
        km: "ការផ្តោតសំខាន់; ដាក់សំឡេងលើ",
      },
      furigana: [
        {
          rb: "強調",
          rt: "きょうちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "強",
          on: ["キョウ", "ゴウ"],
          kun: ["つよ.い", "つよ.まる", "つよ.める", "し.いる", "こわ.い"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "調",
          on: ["チョウ"],
          kun: ["しら.べる", "しら.べ", "ととの.う", "ととの.える"],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 495,
      kanji: "共同",
      reading: "きょうどう",
      meanings: {
        ja: "一緒に行うこと。協働。",
        en: "cooperation; joint effort",
        zh: "共同；协同",
        tw: "共同；協同",
        ko: "공동; 협동",
        vi: "cùng làm; hợp tác",
        th: "ร่วมมือ; ร่วมกัน",
        my: "ပူးပေါင်းဆောင်ရှောင်မှု",
        km: "សហការ; រួមគ្នា",
      },
      furigana: [
        {
          rb: "共同",
          rt: "きょうどう",
        },
      ],
      kanjiInfo: [
        {
          char: "共",
          on: ["キョウ"],
          kun: ["とも", "とも.に", "-ども"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "同",
          on: ["ドウ"],
          kun: ["おな.じ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 496,
      kanji: "恐怖",
      reading: "きょうふ",
      meanings: {
        ja: "ひどくこわがる気持ち。",
        en: "fear; terror",
        zh: "恐惧；恐怖",
        tw: "恐懼；恐怖",
        ko: "공포",
        vi: "sợ hãi; kinh hoàng",
        th: "ความหวาดกลัว",
        my: "ကြောက်ရွံ့မှု",
        km: "ការភ័យខ្លាច",
      },
      furigana: [
        {
          rb: "恐怖",
          rt: "きょうふ",
        },
      ],
      kanjiInfo: [
        {
          char: "恐",
          on: ["キョウ"],
          kun: ["おそ.れる", "おそ.る", "おそ.ろしい", "こわ.い", "こわ.がる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "怖",
          on: ["フ", "ホ"],
          kun: ["こわ.い", "こわ.がる", "お.じる", "おそ.れる"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 497,
      kanji: "協力",
      reading: "きょうりょく",
      meanings: {
        ja: "力を合わせて助け合うこと。",
        en: "cooperation; collaboration",
        zh: "协力；合作",
        tw: "協力；合作",
        ko: "협력",
        vi: "hợp lực; hợp tác",
        th: "ความร่วมมือ",
        my: "ပူးပေါင်းအလုပ်လုပ်ခြင်း",
        km: "សហការណ៍; សហការងារ",
      },
      furigana: [
        {
          rb: "協力",
          rt: "きょうりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "協",
          on: ["キョウ"],
          kun: [],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 498,
      kanji: "許可",
      reading: "きょか",
      meanings: {
        ja: "してよいと認めること。許し。",
        en: "permission; approval; license",
        zh: "许可；准许",
        tw: "許可；准許",
        ko: "허가; 승인",
        vi: "cho phép; giấy phép",
        th: "การอนุญาต",
        my: "လိုင်စင်; ခွင့်ပြုချက်",
        km: "អនុញ្ញាត; អាជ្ញាប័ណ្ណ",
      },
      furigana: [
        {
          rb: "許可",
          rt: "きょか",
        },
      ],
      kanjiInfo: [
        {
          char: "許",
          on: ["キョ"],
          kun: ["ゆる.す", "もと"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "可",
          on: ["カ", "コク"],
          kun: ["-べ.き", "-べ.し"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 499,
      kanji: "局",
      reading: "きょく",
      meanings: {
        ja: "役所などの部局。放送局など。",
        en: "bureau; department; (TV/radio) station",
        zh: "局；部门；电台/电视台",
        tw: "局；部門；電台/電視台",
        ko: "국(부서); 방송국",
        vi: "cục; vụ; đài (truyền hình/phát thanh)",
        th: "กรม/กอง; สถานีโทรทัศน์/วิทยุ",
        my: "ဌာန; ရေဒီယို/တီဗီ စခန်း",
        km: "នាយកដ្ឋាន; ស្ថានីយ (ទូរទស្សន៍/វិទ្យុ)",
      },
      furigana: [
        {
          rb: "局",
          rt: "きょく",
        },
      ],
      kanjiInfo: [
        {
          char: "局",
          on: ["キョク"],
          kun: ["つぼね"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 500,
      kanji: "霧",
      reading: "きり",
      meanings: {
        ja: "細かな水滴が空気中に漂う現象。",
        en: "fog; mist",
        zh: "雾；薄雾",
        tw: "霧；薄霧",
        ko: "안개",
        vi: "sương mù",
        th: "หมอก",
        my: "မိုးအုံ့; မိုးခေါင် (အုတ်မြွှာ)",
        km: "អ័ព្ទ",
      },
      furigana: [
        {
          rb: "霧",
          rt: "きり",
        },
      ],
      kanjiInfo: [
        {
          char: "霧",
          on: ["ム", "ボウ", "ブ"],
          kun: ["きり"],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
