export const n3part14 = {
  Lesson14: [
    {
      id: 651,
      kanji: "今日",
      reading: "こんにち",
      meanings: {
        ja: "今日",
        en: "today",
        zh: "今日/当今",
        tw: "今日/當今",
        ko: "오늘/현대",
        vi: "ngày nay",
        th: "ปัจจุบัน/สมัยนี้",
        my: "ယနေ့/ယခုခေတ်",
        km: "សព្វថ្ងៃ",
      },
      furigana: [
        {
          rb: "今日",
          rt: "こんにち",
        },
      ],
      kanjiInfo: [
        {
          char: "今",
          on: ["コン", "キン"],
          kun: ["いま"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 652,
      kanji: "婚約",
      reading: "こんやく",
      meanings: {
        ja: "婚約",
        en: "engagement",
        zh: "订婚",
        tw: "訂婚",
        ko: "약혼",
        vi: "đính hôn",
        th: "หมั้นหมาย",
        my: "လက်ဆောင်ကမ်းလှမ်းခြင်း/ရန်သတ်မှတ်",
        km: "ការរៀបការ​ជាមុន (និពន្ធ)",
      },
      furigana: [
        {
          rb: "婚約",
          rt: "こんやく",
        },
      ],
      kanjiInfo: [
        {
          char: "婚",
          on: ["コン"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "約",
          on: ["ヤク"],
          kun: ["つづ.まる", "つづ.める", "つづま.やか"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 653,
      kanji: "混乱",
      reading: "こんらん",
      meanings: {
        ja: "混乱",
        en: "disorder/confusion",
        zh: "混乱",
        tw: "混亂",
        ko: "혼란",
        vi: "hỗn loạn",
        th: "ความโกลาหล",
        my: "အရေးပေါ်ပေါက်ကွဲ/ကပ်လှန်",
        km: "ភាពវឹកវរលំអ",
      },
      furigana: [
        {
          rb: "混乱",
          rt: "こんらん",
        },
      ],
      kanjiInfo: [
        {
          char: "混",
          on: ["コン"],
          kun: ["ま.じる", "-ま.じり", "ま.ざる", "ま.ぜる", "こ.む"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "乱",
          on: ["ラン", "ロン"],
          kun: [
            "みだ.れる",
            "みだ.る",
            "みだ.す",
            "みだ",
            "おさ.める",
            "わた.る",
          ],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 654,
      kanji: "差",
      reading: "さ",
      meanings: {
        ja: "差",
        en: "difference",
        zh: "差别/差距",
        tw: "差異/差距",
        ko: "차이/격차",
        vi: "sự chênh lệch",
        th: "ความแตกต่าง",
        my: "ကွာဟမှု",
        km: "ភាពខុសគ្នា",
      },
      furigana: [
        {
          rb: "差",
          rt: "さ",
        },
      ],
      kanjiInfo: [
        {
          char: "差",
          on: ["サ"],
          kun: ["さ.す", "さ.し"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 655,
      kanji: "サービス",
      reading: "サービス",
      meanings: {
        ja: "サービス",
        en: "service",
        zh: "服务",
        tw: "服務",
        ko: "서비스",
        vi: "dịch vụ",
        th: "บริการ",
        my: "ဝန်ဆောင်မှု",
        km: "សេវាកម្ម",
      },
      furigana: [
        {
          rb: "サービス",
          rt: "サービス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 656,
      kanji: "際",
      reading: "さい",
      meanings: {
        ja: "際",
        en: "occasion",
        zh: "时机/场合",
        tw: "時機/場合",
        ko: "때/경우",
        vi: "dịp/khía cạnh",
        th: "โอกาส/คราว",
        my: "အခွင့်အလမ်း/အခငါး",
        km: "ឱកាស/ពេលវេលា",
      },
      furigana: [
        {
          rb: "際",
          rt: "さい",
        },
      ],
      kanjiInfo: [
        {
          char: "際",
          on: ["サイ"],
          kun: ["きわ", "-ぎわ"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 657,
      kanji: "財産",
      reading: "ざいさん",
      meanings: {
        ja: "財産",
        en: "property/assets",
        zh: "财产",
        tw: "財產",
        ko: "재산",
        vi: "tài sản",
        th: "ทรัพย์สิน",
        my: "ကုန်ပစ္စည်း/ပိုင်ဆိုင်မှု",
        km: "ទ្រព្យសម្បត្តិ",
      },
      furigana: [
        {
          rb: "財産",
          rt: "ざいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "財",
          on: ["ザイ", "サイ", "ゾク"],
          kun: ["たから"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 658,
      kanji: "最中",
      reading: "さいちゅう",
      meanings: {
        ja: "最中",
        en: "in the middle of",
        zh: "正当…之中",
        tw: "正當…之中",
        ko: "한창 … 중",
        vi: "đang lúc/giữa lúc",
        th: "อยู่ระหว่าง/กำลัง",
        my: "တစ်ဝက်လည်ပတ်中",
        km: "កណ្ដាលនៃ…",
      },
      furigana: [
        {
          rb: "最中",
          rt: "さいちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "最",
          on: ["サイ", "シュ"],
          kun: ["もっと.も", "つま"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 659,
      kanji: "才能",
      reading: "さいのう",
      meanings: {
        ja: "才能",
        en: "talent",
        zh: "才能",
        tw: "才能",
        ko: "재능",
        vi: "tài năng",
        th: "พรสวรรค์",
        my: "တမန်",
        km: "ទេពកោសល្យ",
      },
      furigana: [
        {
          rb: "才能",
          rt: "さいのう",
        },
      ],
      kanjiInfo: [
        {
          char: "才",
          on: ["サイ"],
          kun: [],
          strokes: 3,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 660,
      kanji: "裁判",
      reading: "さいばん",
      meanings: {
        ja: "裁判",
        en: "trial",
        zh: "审判",
        tw: "審判",
        ko: "재판",
        vi: "phiên toà",
        th: "การพิจารณาคดี",
        my: "တရားရုံးစီရင်ရေး",
        km: "ការកាត់ក្ដី",
      },
      furigana: [
        {
          rb: "裁判",
          rt: "さいばん",
        },
      ],
      kanjiInfo: [
        {
          char: "裁",
          on: ["サイ"],
          kun: ["た.つ", "さば.く"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "判",
          on: ["ハン", "バン"],
          kun: ["わか.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 661,
      kanji: "材料",
      reading: "ざいりょう",
      meanings: {
        ja: "材料",
        en: "materials/ingredients",
        zh: "材料",
        tw: "材料",
        ko: "재료",
        vi: "vật liệu/nguyên liệu",
        th: "วัสดุ/ส่วนผสม",
        my: "အရည်အသွေး/ယူနစ်",
        km: "សម្ភារៈ/គ្រឿងផ្សំ",
      },
      furigana: [
        {
          rb: "材料",
          rt: "ざいりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "材",
          on: ["ザイ"],
          kun: [],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "料",
          on: ["リョウ"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 662,
      kanji: "サイン",
      reading: "サイン",
      meanings: {
        ja: "サイン",
        en: "autograph/signature",
        zh: "签名",
        tw: "簽名",
        ko: "사인",
        vi: "chữ ký",
        th: "ลายเซ็น",
        my: "လက်မှတ်",
        km: "ហត្ថលេខា",
      },
      furigana: [
        {
          rb: "サイン",
          rt: "サイン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 663,
      kanji: "境",
      reading: "さかい",
      meanings: {
        ja: "境",
        en: "border/boundary",
        zh: "边界",
        tw: "邊界",
        ko: "경계",
        vi: "ranh giới",
        th: "เขตแดน",
        my: "နယ်နိမိတ်",
        km: "ព្រំដែន",
      },
      furigana: [
        {
          rb: "境",
          rt: "さかい",
        },
      ],
      kanjiInfo: [
        {
          char: "境",
          on: ["キョウ", "ケイ"],
          kun: ["さかい"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 664,
      kanji: "盛り",
      reading: "さかり",
      meanings: {
        ja: "盛り",
        en: "height/peak (of season)",
        zh: "鼎盛/正旺",
        tw: "旺盛/正盛",
        ko: "절정/한창",
        vi: "đỉnh điểm",
        th: "ช่วงพีค/กำลังสุด",
        my: "အထွား",
        km: "កំពូល/កំពុងរីក",
      },
      furigana: [
        {
          rb: "盛り",
          rt: "さかり",
        },
      ],
      kanjiInfo: [
        {
          char: "盛",
          on: ["セイ", "ジョウ"],
          kun: ["も.る", "さか.る", "さか.ん"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 665,
      kanji: "作業",
      reading: "さぎょう",
      meanings: {
        ja: "作業",
        en: "work/task",
        zh: "作业/工作",
        tw: "作業/工作",
        ko: "작업",
        vi: "tác nghiệp/công việc",
        th: "งาน",
        my: "အလုပ်",
        km: "ការងារ",
      },
      furigana: [
        {
          rb: "作業",
          rt: "さぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 666,
      kanji: "作品",
      reading: "さくひん",
      meanings: {
        ja: "作品",
        en: "(artistic) work",
        zh: "作品",
        tw: "作品",
        ko: "작품",
        vi: "tác phẩm",
        th: "ผลงาน",
        my: "လက်ရာ",
        km: "ស្នាដៃ",
      },
      furigana: [
        {
          rb: "作品",
          rt: "さくひん",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 667,
      kanji: "作物",
      reading: "さくもつ",
      meanings: {
        ja: "作物",
        en: "crop",
        zh: "作物",
        tw: "作物",
        ko: "농작물",
        vi: "hoa màu",
        th: "พืชผล",
        my: "စိုက်ပျိုးဖွားပိုး",
        km: "ដំណាំ",
      },
      furigana: [
        {
          rb: "作物",
          rt: "さくもつ",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 668,
      kanji: "桜",
      reading: "さくら",
      meanings: {
        ja: "桜",
        en: "cherry tree",
        zh: "樱花树",
        tw: "櫻花樹",
        ko: "벚나무",
        vi: "cây anh đào",
        th: "ต้นซากุระ",
        my: "စကူရာ",
        km: "ដើមសាកુરា",
      },
      furigana: [
        {
          rb: "桜",
          rt: "さくら",
        },
      ],
      kanjiInfo: [
        {
          char: "桜",
          on: ["オウ", "ヨウ"],
          kun: ["さくら"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 669,
      kanji: "酒",
      reading: "さけ",
      meanings: {
        ja: "酒",
        en: "alcohol/sake",
        zh: "酒",
        tw: "酒",
        ko: "술",
        vi: "rượu",
        th: "สุรา/เหล้า",
        my: "အရက်",
        km: "ស្រា",
      },
      furigana: [
        {
          rb: "酒",
          rt: "さけ",
        },
      ],
      kanjiInfo: [
        {
          char: "酒",
          on: ["シュ"],
          kun: ["さけ", "さか-"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 670,
      kanji: "座席",
      reading: "ざせき",
      meanings: {
        ja: "座席",
        en: "seat",
        zh: "座位",
        tw: "座位",
        ko: "좌석",
        vi: "chỗ ngồi",
        th: "ที่นั่ง",
        my: "ထိုင်ခုံ",
        km: "កៅអី/កន្លែងអង្គុយ",
      },
      furigana: [
        {
          rb: "座席",
          rt: "ざせき",
        },
      ],
      kanjiInfo: [
        {
          char: "座",
          on: ["ザ"],
          kun: ["すわ.る"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "席",
          on: ["セキ"],
          kun: ["むしろ"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 671,
      kanji: "札",
      reading: "さつ",
      meanings: {
        ja: "札",
        en: "banknote",
        zh: "纸币",
        tw: "紙鈔",
        ko: "지폐",
        vi: "tiền giấy",
        th: "ธนบัตร",
        my: "ဟောင်းပုံစံဓမ္မစာ",
        km: "ប្រាក់ក្រដាស់",
      },
      furigana: [
        {
          rb: "札",
          rt: "さつ",
        },
      ],
      kanjiInfo: [
        {
          char: "札",
          on: ["サツ"],
          kun: ["ふだ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 672,
      kanji: "作家",
      reading: "さっか",
      meanings: {
        ja: "作家",
        en: "author",
        zh: "作家",
        tw: "作家",
        ko: "작가",
        vi: "tác giả/nhà văn",
        th: "นักเขียน",
        my: "စာရေးဆရာ",
        km: "អ្នកនិពន្ធ",
      },
      furigana: [
        {
          rb: "作家",
          rt: "さっか",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 673,
      kanji: "作曲",
      reading: "さっきょく",
      meanings: {
        ja: "作曲",
        en: "composition (music)",
        zh: "作曲",
        tw: "作曲",
        ko: "작곡",
        vi: "sáng tác nhạc",
        th: "แต่งเพลง",
        my: "တေးရေး",
        km: "និពន្ធទំនុកច្រៀង",
      },
      furigana: [
        {
          rb: "作曲",
          rt: "さっきょく",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "曲",
          on: ["キョク"],
          kun: ["ま.がる", "ま.げる", "くま"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 674,
      kanji: "砂漠",
      reading: "さばく",
      meanings: {
        ja: "砂漠",
        en: "desert",
        zh: "沙漠",
        tw: "沙漠",
        ko: "사막",
        vi: "sa mạc",
        th: "ทะเลทราย",
        my: "သဲကန္တာရာ",
        km: "វាលខ្សាច់",
      },
      furigana: [
        {
          rb: "砂漠",
          rt: "さばく",
        },
      ],
      kanjiInfo: [
        {
          char: "砂",
          on: ["サ", "シャ"],
          kun: ["すな"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "漠",
          on: ["バク"],
          kun: [],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 675,
      kanji: "差別",
      reading: "さべつ",
      meanings: {
        ja: "差別",
        en: "discrimination",
        zh: "歧视",
        tw: "歧視",
        ko: "차별",
        vi: "phân biệt đối xử",
        th: "การเลือกปฏิบัติ",
        my: "ခြားချက်ပြုခြင်း",
        km: "ការរើសអើង",
      },
      furigana: [
        {
          rb: "差別",
          rt: "さべつ",
        },
      ],
      kanjiInfo: [
        {
          char: "差",
          on: ["サ"],
          kun: ["さ.す", "さ.し"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "別",
          on: ["ベツ"],
          kun: ["わか.れる", "わ.ける"],
          strokes: 7,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 676,
      kanji: "ママ",
      reading: "ママ",
      meanings: {
        ja: "ママ",
        en: "mom",
        zh: "妈妈",
        tw: "媽媽",
        ko: "엄마",
        vi: "mẹ",
        th: "แม่",
        my: "မိဘမ",
        km: "ម៉ាក់",
      },
      furigana: [
        {
          rb: "ママ",
          rt: "ママ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 677,
      kanji: "豆",
      reading: "まめ",
      meanings: {
        ja: "豆",
        en: "legume/bean",
        zh: "豆/豆类",
        tw: "豆/豆類",
        ko: "콩",
        vi: "đậu",
        th: "ถั่ว",
        my: "ပဲ",
        km: "សណ្តែក",
      },
      furigana: [
        {
          rb: "豆",
          rt: "まめ",
        },
      ],
      kanjiInfo: [
        {
          char: "豆",
          on: ["トウ", "ズ"],
          kun: ["まめ", "まめ-"],
          strokes: 7,
          grade: 3,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 678,
      kanji: "丸",
      reading: "まる",
      meanings: {
        ja: "丸",
        en: "circle",
        zh: "圆形",
        tw: "圓形",
        ko: "원/동그라미",
        vi: "hình tròn",
        th: "วงกลม",
        my: "စက်ဝိုင်း",
        km: "រង្វង់",
      },
      furigana: [
        {
          rb: "丸",
          rt: "まる",
        },
      ],
      kanjiInfo: [
        {
          char: "丸",
          on: ["ガン"],
          kun: ["まる", "まる.める", "まる.い"],
          strokes: 3,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 679,
      kanji: "円",
      reading: "まる",
      meanings: {
        ja: "円（形）",
        en: "circle",
        zh: "圆",
        tw: "圓",
        ko: "원",
        vi: "hình tròn",
        th: "วงกลม",
        my: "စက်ဝိုင်း",
        km: "រង្វង់",
      },
      furigana: [
        {
          rb: "円",
          rt: "まる",
        },
      ],
      kanjiInfo: [
        {
          char: "円",
          on: ["エン"],
          kun: ["まる.い", "まる", "まど", "まど.か", "まろ.やか"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 680,
      kanji: "万一",
      reading: "まんいち",
      meanings: {
        ja: "万一",
        en: "in case of emergency/if by any chance",
        zh: "万一/以防万一",
        tw: "萬一/以防萬一",
        ko: "만일/만약",
        vi: "nhỡ khi/phòng khi",
        th: "เผื่อว่า/กรณีฉุกเฉิน",
        my: "မဖြစ်မနေလျှင်",
        km: "បើសិនជា/ក្នុងករណីចៃដន្យ",
      },
      furigana: [
        {
          rb: "万一",
          rt: "まんいち",
        },
      ],
      kanjiInfo: [
        {
          char: "万",
          on: ["マン", "バン"],
          kun: ["よろず"],
          strokes: 3,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 681,
      kanji: "満足",
      reading: "まんぞく",
      meanings: {
        ja: "満足",
        en: "satisfaction",
        zh: "满足",
        tw: "滿足",
        ko: "만족",
        vi: "hài lòng",
        th: "ความพอใจ",
        my: "ကျေနပ်မှု",
        km: "ការពេញចិត្ត",
      },
      furigana: [
        {
          rb: "満足",
          rt: "まんぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "満",
          on: ["マン", "バン"],
          kun: ["み.ちる", "み.つ", "み.たす"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "足",
          on: ["ソク"],
          kun: ["あし", "た.りる", "た.る", "た.す"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 682,
      kanji: "身",
      reading: "み",
      meanings: {
        ja: "身",
        en: "one's body/self",
        zh: "身/自身",
        tw: "身/自身",
        ko: "몸/신분",
        vi: "thân mình",
        th: "ตัวตน/ร่างกาย",
        my: "ကိုယ်ခန္ဓာ",
        km: "ខ្លួន/សាច់ឈាម",
      },
      furigana: [
        {
          rb: "身",
          rt: "み",
        },
      ],
      kanjiInfo: [
        {
          char: "身",
          on: ["シン"],
          kun: ["み"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 683,
      kanji: "実",
      reading: "み",
      meanings: {
        ja: "実",
        en: "fruit/nut",
        zh: "果实",
        tw: "果實",
        ko: "열매",
        vi: "quả/nhân",
        th: "ผล/เมล็ด",
        my: "ဖျားသီး",
        km: "ផ្លែ/គ្រាប់",
      },
      furigana: [
        {
          rb: "実",
          rt: "み",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 684,
      kanji: "見送り",
      reading: "みおくり",
      meanings: {
        ja: "見送り",
        en: "seeing off",
        zh: "送行",
        tw: "送行",
        ko: "배웅",
        vi: "tiễn",
        th: "ไปส่ง",
        my: "နှုတ်ဆက်ပို့",
        km: "សង្រ្គោះ/ទៅអម",
      },
      furigana: [
        {
          rb: "見送り",
          rt: "みおくり",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "送",
          on: ["ソウ"],
          kun: ["おく.る"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 685,
      kanji: "味方",
      reading: "みかた",
      meanings: {
        ja: "味方",
        en: "ally/supporter",
        zh: "盟友/我方",
        tw: "我方/同盟",
        ko: "아군/편",
        vi: "đồng minh",
        th: "ฝ่ายเดียวกัน/พวก",
        my: "ဖက်စပ်",
        km: "សម្ព័ន្ធមិត្ត",
      },
      furigana: [
        {
          rb: "味方",
          rt: "みかた",
        },
      ],
      kanjiInfo: [
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 686,
      kanji: "ミス",
      reading: "ミス",
      meanings: {
        ja: "ミス",
        en: "mistake",
        zh: "错误",
        tw: "錯誤",
        ko: "실수",
        vi: "lỗi",
        th: "ความผิดพลาด",
        my: "ချော့မွေ့",
        km: "កំហុស",
      },
      furigana: [
        {
          rb: "ミス",
          rt: "ミス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 687,
      kanji: "見舞い",
      reading: "みまい",
      meanings: {
        ja: "見舞い",
        en: "visit (someone ill or in trouble)",
        zh: "探望/慰问",
        tw: "探望/慰問",
        ko: "문안/병문안",
        vi: "thăm hỏi",
        th: "ไปเยี่ยม (คนป่วย/ประสบภัย)",
        my: "ပြန်လည်က慰問",
        km: "ទៅទស្សនារបួស/ជំងឺ",
      },
      furigana: [
        {
          rb: "見舞い",
          rt: "みまい",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "舞",
          on: ["ブ"],
          kun: ["ま.う", "-ま.う", "まい"],
          strokes: 15,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 688,
      kanji: "土産",
      reading: "みやげ",
      meanings: {
        ja: "土産",
        en: "souvenir/local specialty",
        zh: "土产/伴手礼",
        tw: "土產/伴手禮",
        ko: "토산품/기념품",
        vi: "đặc sản/đồ lưu niệm",
        th: "ของฝาก",
        my: "လက်ဆောင်မြို့ပြ",
        km: "អំណោយ/ផលដឹកនាំតំបន់",
      },
      furigana: [
        {
          rb: "土産",
          rt: "みやげ",
        },
      ],
      kanjiInfo: [
        {
          char: "土",
          on: ["ド", "ト"],
          kun: ["つち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 689,
      kanji: "都",
      reading: "みやこ",
      meanings: {
        ja: "都",
        en: "capital (esp. Kyoto)",
        zh: "都城/京城",
        tw: "都 (京城)",
        ko: "도읍/수도",
        vi: "kinh đô (đặc biệt Kyoto)",
        th: "นครหลวง (โดยเฉพาะเกียวโต)",
        my: "မြို့တော်",
        km: "រាជធានី",
      },
      furigana: [
        {
          rb: "都",
          rt: "みやこ",
        },
      ],
      kanjiInfo: [
        {
          char: "都",
          on: ["ト", "ツ"],
          kun: ["みやこ"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 690,
      kanji: "明後日",
      reading: "みょうごにち",
      meanings: {
        ja: "明後日",
        en: "day after tomorrow",
        zh: "后天",
        tw: "後天",
        ko: "모레",
        vi: "ngày kia",
        th: "มะรืนนี้",
        my: "တနှစ်နေ့",
        km: "ស្អែកម៉ាត់",
      },
      furigana: [
        {
          rb: "明後日",
          rt: "みょうごにち",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 691,
      kanji: "未来",
      reading: "みらい",
      meanings: {
        ja: "未来",
        en: "(distant) future",
        zh: "未来",
        tw: "未來",
        ko: "미래",
        vi: "tương lai",
        th: "อนาคต",
        my: "အနာဂတ်",
        km: "អនាគត",
      },
      furigana: [
        {
          rb: "未来",
          rt: "みらい",
        },
      ],
      kanjiInfo: [
        {
          char: "未",
          on: ["ミ", "ビ"],
          kun: ["いま.だ", "ま.だ", "ひつじ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "来",
          on: ["ライ", "タイ"],
          kun: [
            "く.る",
            "きた.る",
            "きた.す",
            "き.たす",
            "き.たる",
            "き",
            "こ",
          ],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 692,
      kanji: "魅力",
      reading: "みりょく",
      meanings: {
        ja: "魅力",
        en: "charm/attraction",
        zh: "魅力",
        tw: "魅力",
        ko: "매력",
        vi: "sức hấp dẫn",
        th: "เสน่ห์",
        my: "ဆွဲဆောင်မှု",
        km: "ការ​ទាក់ទាញ",
      },
      furigana: [
        {
          rb: "魅力",
          rt: "みりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "魅",
          on: ["ミ"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 693,
      kanji: "ミルク",
      reading: "ミルク",
      meanings: {
        ja: "ミルク",
        en: "milk",
        zh: "牛奶",
        tw: "牛奶",
        ko: "우유",
        vi: "sữa",
        th: "นม",
        my: "နို့",
        km: "ទឹកដោះគោ",
      },
      furigana: [
        {
          rb: "ミルク",
          rt: "ミルク",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 694,
      kanji: "無",
      reading: "む",
      meanings: {
        ja: "無",
        en: "nothing/none",
        zh: "无/没有",
        tw: "無/沒有",
        ko: "무/없음",
        vi: "vô/không",
        th: "ไม่มี/ความว่าง",
        my: "မရှိခြင်း",
        km: "គ្មាន",
      },
      furigana: [
        {
          rb: "無",
          rt: "む",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 695,
      kanji: "向かい",
      reading: "むかい",
      meanings: {
        ja: "向かい",
        en: "facing/opposite",
        zh: "对面/相对",
        tw: "對面/相對",
        ko: "맞은편",
        vi: "đối diện",
        th: "ฝั่งตรงข้าม",
        my: "အဖြစ်တန်ပြန်",
        km: "ម្ខាងមុខ/ផ្ទុយមុខ",
      },
      furigana: [
        {
          rb: "向かい",
          rt: "むかい",
        },
      ],
      kanjiInfo: [
        {
          char: "向",
          on: ["コウ"],
          kun: [
            "む.く",
            "む.い",
            "-む.き",
            "む.ける",
            "-む.け",
            "む.かう",
            "む.かい",
            "む.こう",
            "む.こう-",
            "むこ",
            "むか.い",
          ],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 696,
      kanji: "迎え",
      reading: "むかえ",
      meanings: {
        ja: "迎え",
        en: "meeting/welcoming",
        zh: "迎接",
        tw: "迎接",
        ko: "마중",
        vi: "đón tiếp",
        th: "ไปรับ",
        my: "ကြိုဆိုခြင်း",
        km: "ទៅទទួល",
      },
      furigana: [
        {
          rb: "迎え",
          rt: "むかえ",
        },
      ],
      kanjiInfo: [
        {
          char: "迎",
          on: ["ゲイ"],
          kun: ["むか.える"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 697,
      kanji: "無視",
      reading: "むし",
      meanings: {
        ja: "無視",
        en: "disregarding/ignoring",
        zh: "无视",
        tw: "無視",
        ko: "무시",
        vi: "phớt lờ",
        th: "เมินเฉย",
        my: "လွတ်လပ်စွာလျှော့",
        km: "មិនអើពើ",
      },
      furigana: [
        {
          rb: "無視",
          rt: "むし",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "視",
          on: ["シ"],
          kun: ["み.る"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 698,
      kanji: "虫歯",
      reading: "むしば",
      meanings: {
        ja: "虫歯",
        en: "tooth decay/cavity",
        zh: "蛀牙",
        tw: "蛀牙",
        ko: "충치",
        vi: "sâu răng",
        th: "ฟันผุ",
        my: "ဝါးခွံပျက်",
        km: "ធ្មេញពុក",
      },
      furigana: [
        {
          rb: "虫歯",
          rt: "むしば",
        },
      ],
      kanjiInfo: [
        {
          char: "虫",
          on: ["チュウ", "キ"],
          kun: ["むし"],
          strokes: 6,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
        {
          char: "歯",
          on: ["シ"],
          kun: ["よわい", "は", "よわ.い", "よわい.する"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 699,
      kanji: "無駄",
      reading: "むだ",
      meanings: {
        ja: "無駄",
        en: "futility/waste",
        zh: "徒劳/浪费",
        tw: "徒勞/浪費",
        ko: "헛됨/낭비",
        vi: "lãng phí/vô ích",
        th: "สูญเปล่า/สิ้นเปลือง",
        my: "ဖြူဘက်မရှိမှု/အလဟာ",
        km: "បាត់បង់ឥតប្រយោជន៍",
      },
      furigana: [
        {
          rb: "無駄",
          rt: "むだ",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "駄",
          on: ["ダ", "タ"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 700,
      kanji: "胸",
      reading: "むね",
      meanings: {
        ja: "胸",
        en: "chest",
        zh: "胸部",
        tw: "胸部",
        ko: "가슴",
        vi: "ngực",
        th: "หน้าอก",
        my: "ဉီးရေကောက်/ရင်ဘတ်",
        km: "ទ្រូង",
      },
      furigana: [
        {
          rb: "胸",
          rt: "むね",
        },
      ],
      kanjiInfo: [
        {
          char: "胸",
          on: ["キョウ"],
          kun: ["むね", "むな-"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
