export const n3part27 = {
  Lesson27: [
    {
      id: 1598,
      kanji: "次々",
      reading: "つぎつぎ",
      meanings: {
        ja: "次々",
        en: "in succession; one after another",
        zh: "接连不断",
        tw: "接連不斷",
        ko: "차례차례",
        vi: "liên tiếp",
        th: "ต่อๆ กัน",
        my: "တစ်ခုပြီးတစ်ခု",
        km: "ជាបន្តបន្ទាប់",
      },
      furigana: [
        {
          rb: "次々",
          rt: "つぎつぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "次",
          on: ["ジ", "シ"],
          kun: ["つ.ぐ", "つぎ"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1599,
      kanji: "常に",
      reading: "つねに",
      meanings: {
        ja: "常に",
        en: "always; constantly",
        zh: "经常；总是",
        tw: "經常；總是",
        ko: "항상",
        vi: "luôn luôn",
        th: "เสมอ",
        my: "အမြဲတမ်း",
        km: "ជានិច្ច",
      },
      furigana: [
        {
          rb: "常に",
          rt: "つねに",
        },
      ],
      kanjiInfo: [
        {
          char: "常",
          on: ["ジョウ"],
          kun: ["つね", "とこ-"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1600,
      kanji: "共に",
      reading: "ともに",
      meanings: {
        ja: "共に",
        en: "together; both",
        zh: "共同；一起",
        tw: "共同；一起",
        ko: "함께",
        vi: "cùng với; đều",
        th: "ด้วยกัน",
        my: "အတူတကွ",
        km: "រួមគ្នា",
      },
      furigana: [
        {
          rb: "共に",
          rt: "ともに",
        },
      ],
      kanjiInfo: [
        {
          char: "共",
          on: ["キョウ"],
          kun: ["とも", "とも.に", "-ども"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1601,
      kanji: "どんなに",
      reading: "どんなに",
      meanings: {
        ja: "どんなに",
        en: "how; how much",
        zh: "多么；如何",
        tw: "多麼；如何",
        ko: "얼마나",
        vi: "biết bao; đến mức nào",
        th: "มากเพียงใด",
        my: "ဘယ်လောက်လောက်",
        km: "យ៉ាងណា; ប៉ុន្មាន",
      },
      furigana: [
        {
          rb: "どんなに",
          rt: "どんなに",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1602,
      kanji: "何で",
      reading: "なんで",
      meanings: {
        ja: "何で",
        en: "why?",
        zh: "为什么？",
        tw: "為什麼？",
        ko: "왜?",
        vi: "tại sao?",
        th: "ทำไม?",
        my: "ဘာကြောင့်?",
        km: "ហេតុអ្វី?",
      },
      furigana: [
        {
          rb: "何で",
          rt: "なんで",
        },
      ],
      kanjiInfo: [
        {
          char: "何",
          on: ["カ"],
          kun: ["なに", "なん", "なに-", "なん-"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1603,
      kanji: "にっこり",
      reading: "にっこり",
      meanings: {
        ja: "にっこり",
        en: "smiling sweetly",
        zh: "莞尔一笑",
        tw: "莞爾一笑",
        ko: "방긋 미소",
        vi: "mỉm cười tươi",
        th: "ยิ้มแย้ม",
        my: "ပြုံးရွှင်",
        km: "ញញឹម",
      },
      furigana: [
        {
          rb: "にっこり",
          rt: "にっこり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1604,
      kanji: "のんびり",
      reading: "のんびり",
      meanings: {
        ja: "のんびり",
        en: "at leisure; laid-back",
        zh: "悠闲地",
        tw: "悠閒地",
        ko: "悠然히; 느긋하게",
        vi: "thong thả",
        th: "สบายๆ",
        my: "အားလျော်စွာ",
        km: "សម្រាកលំហែ",
      },
      furigana: [
        {
          rb: "のんびり",
          rt: "のんびり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1605,
      kanji: "ばったり",
      reading: "ばったり",
      meanings: {
        ja: "ばったり",
        en: "with a clash; by chance meet",
        zh: "突然相遇；扑通倒下",
        tw: "突然相遇；撲通倒下",
        ko: "딱 마주침; 털썩",
        vi: "bất ngờ gặp; ngã uỵch",
        th: "บังเอิญเจอ; ล้มตึง",
        my: "ကြုံဖတ်; ကုန်းလန်",
        km: "ជាងគប់; ជួបចៃដន្យ",
      },
      furigana: [
        {
          rb: "ばったり",
          rt: "ばったり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1606,
      kanji: "ぴったり",
      reading: "ぴったり",
      meanings: {
        ja: "ぴったり",
        en: "exactly; tightly; perfectly",
        zh: "恰好；紧贴",
        tw: "恰好；緊貼",
        ko: "딱 맞게; 꼭",
        vi: "vừa khít; đúng",
        th: "พอดี; แนบสนิท",
        my: "တိတိကျကျ; တင်းတင်းကျပ်ကျပ်",
        km: "ពេញលេញ; តឹងぴ",
      },
      furigana: [
        {
          rb: "ぴったり",
          rt: "ぴったり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1607,
      kanji: "一人一人",
      reading: "ひとりひとり",
      meanings: {
        ja: "一人一人",
        en: "each person; one by one",
        zh: "每个人",
        tw: "每個人",
        ko: "한 사람 한 사람",
        vi: "từng người một",
        th: "ทีละคน",
        my: "လူတစ်ယောက်ချင်း",
        km: "នាក់ម្នាក់ៗ",
      },
      furigana: [
        {
          rb: "一人一人",
          rt: "ひとりひとり",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1608,
      kanji: "再び",
      reading: "ふたたび",
      meanings: {
        ja: "再び",
        en: "again; once more",
        zh: "再次",
        tw: "再次",
        ko: "다시",
        vi: "lại; nữa",
        th: "อีกครั้ง",
        my: "ထပ်မံ",
        km: "ម្តងទៀត",
      },
      furigana: [
        {
          rb: "再び",
          rt: "ふたたび",
        },
      ],
      kanjiInfo: [
        {
          char: "再",
          on: ["サイ", "サ"],
          kun: ["ふたた.び"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1609,
      kanji: "別に",
      reading: "べつに",
      meanings: {
        ja: "別に",
        en: "(not) particularly",
        zh: "并不；并没有",
        tw: "並不；並沒有",
        ko: "딱히 (…않다)",
        vi: "không … đặc biệt",
        th: "ไม่ได้...เป็นพิเศษ",
        my: "အထူးမ",
        km: "មិនសូវ",
      },
      furigana: [
        {
          rb: "別に",
          rt: "べつに",
        },
      ],
      kanjiInfo: [
        {
          char: "別",
          on: ["ベツ"],
          kun: ["わか.れる", "わ.ける"],
          strokes: 7,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1610,
      kanji: "方々",
      reading: "ほうぼう",
      meanings: {
        ja: "方々",
        en: "here and there; various places",
        zh: "到处；各处",
        tw: "到處；各處",
        ko: "이곳저곳",
        vi: "khắp nơi",
        th: "ทั่วทุกแห่ง",
        my: "နေရာအနှံ့",
        km: "គ្រប់ទីកន្លែង",
      },
      furigana: [
        {
          rb: "方々",
          rt: "ほうぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1611,
      kanji: "ぼんやり",
      reading: "ぼんやり",
      meanings: {
        ja: "ぼんやり",
        en: "vaguely; absentmindedly",
        zh: "恍惚地；模糊地",
        tw: "恍惚地；模糊地",
        ko: "멍하게; 어렴풋이",
        vi: "lơ đãng; mơ hồ",
        th: "เหม่อลอย; เลือนราง",
        my: "စိတ်မနေရာ",
        km: "មមាយមម៉ង",
      },
      furigana: [
        {
          rb: "ぼんやり",
          rt: "ぼんやり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1612,
      kanji: "まあ",
      reading: "まあ",
      meanings: {
        ja: "まあ",
        en: "well; just (e.g., 'just wait')",
        zh: "嗯；先…吧",
        tw: "嗯；先…吧",
        ko: "자; 글쎄",
        vi: "ờ thì; cứ (đợi)",
        th: "ก็…; (เช่น) แค่รอ",
        my: "အေးအေးလေး",
        km: "អីង…",
      },
      furigana: [
        {
          rb: "まあ",
          rt: "まあ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1613,
      kanji: "全く",
      reading: "まったく",
      meanings: {
        ja: "全く",
        en: "really; entirely",
        zh: "真是；完全",
        tw: "真是；完全",
        ko: "정말; 완전히",
        vi: "thật sự; hoàn toàn",
        th: "จริงๆ; ทั้งหมด",
        my: "အမွန်တကယ်; လုံးဝ",
        km: "ពិតៗ; ពេញលេញ",
      },
      furigana: [
        {
          rb: "全く",
          rt: "まったく",
        },
      ],
      kanjiInfo: [
        {
          char: "全",
          on: ["ゼン"],
          kun: ["まった.く", "すべ.て"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1614,
      kanji: "ほっと",
      reading: "ほっと",
      meanings: {
        ja: "ほっと",
        en: "with relief; feel relieved",
        zh: "松口气地",
        tw: "鬆一口氣地",
        ko: "한숨 놓고",
        vi: "thở phào nhẹ nhõm",
        th: "โล่งอก",
        my: "အနားရ",
        km: "ស្រាលចិត្ត",
      },
      furigana: [
        {
          rb: "ほっと",
          rt: "ほっと",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1615,
      kanji: "前もって",
      reading: "まえもって",
      meanings: {
        ja: "前もって",
        en: "in advance; beforehand",
        zh: "事先",
        tw: "事先",
        ko: "미리",
        vi: "trước; sẵn",
        th: "ล่วงหน้า",
        my: "ကြိုတင်",
        km: "ជាមុន",
      },
      furigana: [
        {
          rb: "前もって",
          rt: "まえもって",
        },
      ],
      kanjiInfo: [
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1301,
      kanji: "本人",
      reading: "ほんにん",
      meanings: {
        ja: "本人",
        en: "the person in question",
        zh: "本人",
        tw: "本人",
        ko: "본인",
        vi: "đương sự; bản thân",
        th: "ตัว本人",
        my: "သူတိုင်",
        km: "ខ្លួនឯង",
      },
      furigana: [
        {
          rb: "本人",
          rt: "ほんにん",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1302,
      kanji: "本物",
      reading: "ほんもの",
      meanings: {
        ja: "本物",
        en: "genuine article; real thing",
        zh: "真品",
        tw: "真品",
        ko: "진품",
        vi: "đồ thật",
        th: "ของจริง",
        my: "အမှန်တကယ်",
        km: "អ្វីពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "本物",
          rt: "ほんもの",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1303,
      kanji: "間",
      reading: "ま",
      meanings: {
        ja: "間",
        en: "interval; space; time",
        zh: "间隔；时间",
        tw: "間隔；時間",
        ko: "사이; 간격; 시간",
        vi: "khoảng; thời gian",
        th: "ช่องว่าง; เวลา",
        my: "ကြားကာလ",
        km: "ចន្លោះ",
      },
      furigana: [
        {
          rb: "間",
          rt: "ま",
        },
      ],
      kanjiInfo: [
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1304,
      kanji: "マーケット",
      reading: "マーケット",
      meanings: {
        ja: "マーケット",
        en: "market",
        zh: "市场",
        tw: "市場",
        ko: "마켓",
        vi: "chợ; thị trường",
        th: "ตลาด",
        my: "စျေး",
        km: "ផ្សារ",
      },
      furigana: [
        {
          rb: "マーケット",
          rt: "マーケット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1305,
      kanji: "マイク",
      reading: "マイク",
      meanings: {
        ja: "マイク",
        en: "microphone",
        zh: "话筒",
        tw: "麥克風",
        ko: "마이크",
        vi: "micrô",
        th: "ไมโครโฟน",
        my: "မိုက်ကရိုဖုန်း",
        km: "មីក្រូហ្វូន",
      },
      furigana: [
        {
          rb: "マイク",
          rt: "マイク",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1306,
      kanji: "迷子",
      reading: "まいご",
      meanings: {
        ja: "迷子",
        en: "lost child",
        zh: "走失的孩子",
        tw: "走失的孩子",
        ko: "미아",
        vi: "trẻ lạc",
        th: "เด็กหลงทาง",
        my: "ပျောက်ဆုံးသောကလေး",
        km: "ក្មេងបាត់",
      },
      furigana: [
        {
          rb: "迷子",
          rt: "まいご",
        },
      ],
      kanjiInfo: [
        {
          char: "迷",
          on: ["メイ"],
          kun: ["まよ.う"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1307,
      kanji: "マイナス",
      reading: "マイナス",
      meanings: {
        ja: "マイナス",
        en: "minus; disadvantage",
        zh: "负数；减",
        tw: "負數；減",
        ko: "마이너스",
        vi: "âm; bất lợi",
        th: "ลบ; ข้อเสีย",
        my: "マイナス",
        km: "អវិជ្ជមាន",
      },
      furigana: [
        {
          rb: "マイナス",
          rt: "マイナス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1308,
      kanji: "幕",
      reading: "まく",
      meanings: {
        ja: "幕",
        en: "curtain; act (in play)",
        zh: "幕布；幕",
        tw: "幕布；幕",
        ko: "막",
        vi: "màn",
        th: "ม่าน; องก์ละคร",
        my: "စင်း پردہ",
        km: "វាំងនន",
      },
      furigana: [
        {
          rb: "幕",
          rt: "まく",
        },
      ],
      kanjiInfo: [
        {
          char: "幕",
          on: ["マク", "バク"],
          kun: ["とばり"],
          strokes: 13,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1309,
      kanji: "負け",
      reading: "まけ",
      meanings: {
        ja: "負け",
        en: "defeat; loss",
        zh: "失败",
        tw: "失敗",
        ko: "패배",
        vi: "thua",
        th: "การพ่ายแพ้",
        my: "ပျက်ကွက်",
        km: "ចាញ់",
      },
      furigana: [
        {
          rb: "負け",
          rt: "まけ",
        },
      ],
      kanjiInfo: [
        {
          char: "負",
          on: ["フ"],
          kun: ["ま.ける", "ま.かす", "お.う"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1310,
      kanji: "孫",
      reading: "まご",
      meanings: {
        ja: "孫",
        en: "grandchild",
        zh: "孙子",
        tw: "孫子",
        ko: "손자/손녀",
        vi: "cháu (nội/ngoại)",
        th: "หลาน (ลูกของลูก)",
        my: "မြေး",
        km: "ចៅ",
      },
      furigana: [
        {
          rb: "孫",
          rt: "まご",
        },
      ],
      kanjiInfo: [
        {
          char: "孫",
          on: ["ソン"],
          kun: ["まご"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1311,
      kanji: "街",
      reading: "まち",
      meanings: {
        ja: "街",
        en: "town; street",
        zh: "街道；城市",
        tw: "街道；城市",
        ko: "거리; 도시",
        vi: "thành phố; phố",
        th: "ถนน; เมือง",
        my: "လမ်း; မြို့",
        km: "ទីក្រុង; ផ្លូវ",
      },
      furigana: [
        {
          rb: "街",
          rt: "まち",
        },
      ],
      kanjiInfo: [
        {
          char: "街",
          on: ["ガイ", "カイ"],
          kun: ["まち"],
          strokes: 12,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1312,
      kanji: "間違い",
      reading: "まちがい",
      meanings: {
        ja: "間違い",
        en: "mistake; error",
        zh: "错误",
        tw: "錯誤",
        ko: "잘못",
        vi: "sai lầm",
        th: "ความผิดพลาด",
        my: "အမှား",
        km: "កំហុស",
      },
      furigana: [
        {
          rb: "間違い",
          rt: "まちがい",
        },
      ],
      kanjiInfo: [
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "違",
          on: ["イ"],
          kun: [
            "ちが.う",
            "ちが.い",
            "ちが.える",
            "-ちが.える",
            "たが.う",
            "たが.える",
          ],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1313,
      kanji: "松",
      reading: "まつ",
      meanings: {
        ja: "松",
        en: "pine tree",
        zh: "松树",
        tw: "松樹",
        ko: "소나무",
        vi: "cây thông",
        th: "ต้นสน",
        my: "ထင်းရှူး",
        km: "ដើមស្រល់",
      },
      furigana: [
        {
          rb: "松",
          rt: "まつ",
        },
      ],
      kanjiInfo: [
        {
          char: "松",
          on: ["ショウ"],
          kun: ["まつ"],
          strokes: 8,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1314,
      kanji: "祭",
      reading: "まつり",
      meanings: {
        ja: "祭",
        en: "festival",
        zh: "节日；祭典",
        tw: "節日；祭典",
        ko: "축제",
        vi: "lễ hội",
        th: "เทศกาล",
        my: "ပွဲတော်",
        km: "ពិធីបុណ្យ",
      },
      furigana: [
        {
          rb: "祭",
          rt: "まつり",
        },
      ],
      kanjiInfo: [
        {
          char: "祭",
          on: ["サイ"],
          kun: ["まつ.る", "まつ.り", "まつり"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1315,
      kanji: "真似",
      reading: "まね",
      meanings: {
        ja: "真似",
        en: "imitation; mimicry",
        zh: "模仿",
        tw: "模仿",
        ko: "흉내",
        vi: "bắt chước",
        th: "การเลียนแบบ",
        my: "ဟန်ဆောင်မှု",
        km: "ការត្រៀម",
      },
      furigana: [
        {
          rb: "真似",
          rt: "まね",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "似",
          on: ["ジ"],
          kun: ["に.る", "ひ.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1316,
      kanji: "柵",
      reading: "さく",
      meanings: {
        ja: "柵",
        en: "fence",
        zh: "栅栏",
        tw: "柵欄",
        ko: "울타리",
        vi: "hàng rào",
        th: "รั้ว",
        my: "ကံ့ကော်",
        km: "របង",
      },
      furigana: [
        {
          rb: "柵",
          rt: "さく",
        },
      ],
      kanjiInfo: [
        {
          char: "柵",
          on: ["サク", "サン"],
          kun: ["しがら.む", "しがらみ", "とりで", "やらい"],
          strokes: 9,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1317,
      kanji: "酸化",
      reading: "さんか",
      meanings: {
        ja: "酸化",
        en: "oxidation",
        zh: "氧化",
        tw: "氧化",
        ko: "산화",
        vi: "oxy hóa",
        th: "การเกิดออกซิเดชัน",
        my: "အောစီဂျင်ချိတ်ဆက်မှု",
        km: "អុកស៊ីតកម្ម",
      },
      furigana: [
        {
          rb: "酸化",
          rt: "さんか",
        },
      ],
      kanjiInfo: [
        {
          char: "酸",
          on: ["サン"],
          kun: ["す.い"],
          strokes: 14,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1318,
      kanji: "死",
      reading: "し",
      meanings: {
        ja: "死",
        en: "death",
        zh: "死亡",
        tw: "死亡",
        ko: "죽음",
        vi: "cái chết",
        th: "ความตาย",
        my: "သေခြင်း",
        km: "ស្លាប់",
      },
      furigana: [
        {
          rb: "死",
          rt: "し",
        },
      ],
      kanjiInfo: [
        {
          char: "死",
          on: ["シ"],
          kun: ["し.ぬ", "し.に-"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1319,
      kanji: "資格",
      reading: "しかく",
      meanings: {
        ja: "資格",
        en: "qualification",
        zh: "资格",
        tw: "資格",
        ko: "자격",
        vi: "tư cách; bằng cấp",
        th: "คุณสมบัติ",
        my: "လက်မှတ်အရည်အချင်း",
        km: "សមត្ថភាព",
      },
      furigana: [
        {
          rb: "資格",
          rt: "しかく",
        },
      ],
      kanjiInfo: [
        {
          char: "資",
          on: ["シ"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "格",
          on: ["カク", "コウ", "キャク", "ゴウ"],
          kun: [],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1320,
      kanji: "視覚",
      reading: "しかく",
      meanings: {
        ja: "視覚",
        en: "sense of sight",
        zh: "视觉",
        tw: "視覺",
        ko: "시각",
        vi: "thị giác",
        th: "การมองเห็น",
        my: "မြင်မြင်သာသာ",
        km: "ចក្ខុវិស័យ",
      },
      furigana: [
        {
          rb: "視覚",
          rt: "しかく",
        },
      ],
      kanjiInfo: [
        {
          char: "視",
          on: ["シ"],
          kun: ["み.る"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "覚",
          on: ["カク"],
          kun: ["おぼ.える", "さ.ます", "さ.める", "さと.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1321,
      kanji: "指揮",
      reading: "しき",
      meanings: {
        ja: "指揮",
        en: "command; conducting (music)",
        zh: "指挥",
        tw: "指揮",
        ko: "지휘",
        vi: "chỉ huy",
        th: "การบังคับบัญชา",
        my: "ညွှန်ကြားမှု",
        km: "ការបញ្ជា",
      },
      furigana: [
        {
          rb: "指揮",
          rt: "しき",
        },
      ],
      kanjiInfo: [
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "揮",
          on: ["キ"],
          kun: ["ふる.う"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1322,
      kanji: "磁気",
      reading: "じき",
      meanings: {
        ja: "磁気",
        en: "magnetism",
        zh: "磁性",
        tw: "磁性",
        ko: "자기",
        vi: "từ tính",
        th: "สนามแม่เหล็ก",
        my: "စွမ်းအားလိုက်",
        km: "មេដែក",
      },
      furigana: [
        {
          rb: "磁気",
          rt: "じき",
        },
      ],
      kanjiInfo: [
        {
          char: "磁",
          on: ["ジ"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1323,
      kanji: "磁器",
      reading: "じき",
      meanings: {
        ja: "磁器",
        en: "porcelain",
        zh: "瓷器",
        tw: "瓷器",
        ko: "자기",
        vi: "đồ sứ",
        th: "เครื่องลายคราม",
        my: "ပန်းကန်",
        km: "ភារកម្មសិលា",
      },
      furigana: [
        {
          rb: "磁器",
          rt: "じき",
        },
      ],
      kanjiInfo: [
        {
          char: "磁",
          on: ["ジ"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1324,
      kanji: "自己",
      reading: "じこ",
      meanings: {
        ja: "自己",
        en: "self",
        zh: "自己",
        tw: "自己",
        ko: "자기",
        vi: "tự bản thân",
        th: "ตนเอง",
        my: "ကိုယ်တိုင်",
        km: "ខ្លួនឯង",
      },
      furigana: [
        {
          rb: "自己",
          rt: "じこ",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "己",
          on: ["コ", "キ"],
          kun: ["おのれ", "つちのと", "な"],
          strokes: 3,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1325,
      kanji: "字体",
      reading: "じたい",
      meanings: {
        ja: "字体",
        en: "typeface; style of character",
        zh: "字体",
        tw: "字體",
        ko: "서체",
        vi: "kiểu chữ",
        th: "รูปแบบตัวอักษร",
        my: "ဖောင့်",
        km: "ពុម្ពអក្សរ",
      },
      furigana: [
        {
          rb: "字体",
          rt: "じたい",
        },
      ],
      kanjiInfo: [
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1326,
      kanji: "辞退",
      reading: "じたい",
      meanings: {
        ja: "辞退",
        en: "refusal; declining",
        zh: "辞退",
        tw: "辭退",
        ko: "사양",
        vi: "từ chối",
        th: "การปฏิเสธ",
        my: "ငြင်းဆန်ခြင်း",
        km: "ការបដិសេធ",
      },
      furigana: [
        {
          rb: "辞退",
          rt: "じたい",
        },
      ],
      kanjiInfo: [
        {
          char: "辞",
          on: ["ジ"],
          kun: ["や.める", "いな.む"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1327,
      kanji: "視点",
      reading: "してん",
      meanings: {
        ja: "視点",
        en: "point of view",
        zh: "视点",
        tw: "視點",
        ko: "시점",
        vi: "quan điểm",
        th: "มุมมอง",
        my: "မြင်ကွင်း",
        km: "ទស្សនៈ",
      },
      furigana: [
        {
          rb: "視点",
          rt: "してん",
        },
      ],
      kanjiInfo: [
        {
          char: "視",
          on: ["シ"],
          kun: ["み.る"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1328,
      kanji: "脂肪",
      reading: "しぼう",
      meanings: {
        ja: "脂肪",
        en: "fat; grease",
        zh: "脂肪",
        tw: "脂肪",
        ko: "지방",
        vi: "mỡ; chất béo",
        th: "ไขมัน",
        my: "အဆီ",
        km: "ខ្លាញ់",
      },
      furigana: [
        {
          rb: "脂肪",
          rt: "しぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "脂",
          on: ["シ"],
          kun: ["あぶら"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "肪",
          on: ["ボウ"],
          kun: [],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1329,
      kanji: "志望",
      reading: "しぼう",
      meanings: {
        ja: "志望",
        en: "aspiration; wish",
        zh: "志愿",
        tw: "志願",
        ko: "지망",
        vi: "nguyện vọng",
        th: "ความปรารถนา",
        my: "ဆန္ဒ",
        km: "បំណងប្រាថ្នា",
      },
      furigana: [
        {
          rb: "志望",
          rt: "しぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "志",
          on: ["シ"],
          kun: ["シリング", "こころざ.す", "こころざし"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "望",
          on: ["ボウ", "モウ"],
          kun: ["のぞ.む", "もち"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1330,
      kanji: "衆",
      reading: "しゅう",
      meanings: {
        ja: "衆",
        en: "multitude; masses",
        zh: "群众",
        tw: "群眾",
        ko: "중",
        vi: "đám đông",
        th: "ฝูงชน",
        my: "လူအစုအဝေး",
        km: "មហាជន",
      },
      furigana: [
        {
          rb: "衆",
          rt: "しゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "衆",
          on: ["シュウ", "シュ"],
          kun: ["おお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1331,
      kanji: "住",
      reading: "じゅう",
      meanings: {
        ja: "住",
        en: "dwelling; residence",
        zh: "住所",
        tw: "住所",
        ko: "주거",
        vi: "nơi ở",
        th: "ที่อยู่อาศัย",
        my: "နေရာ",
        km: "លំនៅដ្ឋាន",
      },
      furigana: [
        {
          rb: "住",
          rt: "じゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "住",
          on: ["ジュウ", "ヂュウ", "チュウ"],
          kun: ["す.む", "す.まう", "-ず.まい"],
          strokes: 7,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1332,
      kanji: "修飾",
      reading: "しゅうしょく",
      meanings: {
        ja: "修飾",
        en: "ornament; modification",
        zh: "修饰",
        tw: "修飾",
        ko: "수식",
        vi: "tô điểm; bổ nghĩa",
        th: "การขยายความ",
        my: "ထပ်ဆောင်း",
        km: "ការតុបតែង",
      },
      furigana: [
        {
          rb: "修飾",
          rt: "しゅうしょく",
        },
      ],
      kanjiInfo: [
        {
          char: "修",
          on: ["シュウ", "シュ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "飾",
          on: ["ショク"],
          kun: ["かざ.る", "かざ.り"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1333,
      kanji: "私用",
      reading: "しよう",
      meanings: {
        ja: "私用",
        en: "personal use; private business",
        zh: "私用",
        tw: "私用",
        ko: "사사로운 용무",
        vi: "việc riêng",
        th: "การใช้ส่วนตัว",
        my: "ကိုယ်ပိုင်အသုံး",
        km: "ការប្រើផ្ទាល់ខ្លួន",
      },
      furigana: [
        {
          rb: "私用",
          rt: "しよう",
        },
      ],
      kanjiInfo: [
        {
          char: "私",
          on: ["シ"],
          kun: ["わたくし", "わたし"],
          strokes: 7,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1334,
      kanji: "仕様",
      reading: "しよう",
      meanings: {
        ja: "仕様",
        en: "specification; way",
        zh: "规格；方式",
        tw: "規格；方式",
        ko: "사양; 방식",
        vi: "quy cách; cách thức",
        th: "ข้อกำหนด; วิธีการ",
        my: "အသုံးပြုပုံ",
        km: "លក្ខណៈពិសេស",
      },
      furigana: [
        {
          rb: "仕様",
          rt: "しよう",
        },
      ],
      kanjiInfo: [
        {
          char: "仕",
          on: ["シ", "ジ"],
          kun: ["つか.える"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "様",
          on: ["ヨウ", "ショウ"],
          kun: ["さま", "さん"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1335,
      kanji: "情",
      reading: "じょう",
      meanings: {
        ja: "情",
        en: "feelings; emotion",
        zh: "感情",
        tw: "感情",
        ko: "정",
        vi: "tình cảm",
        th: "ความรู้สึก",
        my: "စိတ်ခံစားချက်",
        km: "អារម្មណ៍",
      },
      furigana: [
        {
          rb: "情",
          rt: "じょう",
        },
      ],
      kanjiInfo: [
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1336,
      kanji: "生涯",
      reading: "しょうがい",
      meanings: {
        ja: "生涯",
        en: "lifetime",
        zh: "一生",
        tw: "一生",
        ko: "생애",
        vi: "suốt đời",
        th: "ตลอดชีวิต",
        my: "ဘဝတစ်လျှောက်",
        km: "ជីវិតពេញមួយ",
      },
      furigana: [
        {
          rb: "生涯",
          rt: "しょうがい",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "涯",
          on: ["ガイ"],
          kun: ["はて"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1337,
      kanji: "上司",
      reading: "じょうし",
      meanings: {
        ja: "上司",
        en: "boss; superior",
        zh: "上司",
        tw: "上司",
        ko: "상사",
        vi: "cấp trên",
        th: "เจ้านาย",
        my: "အကြီးအကဲ",
        km: "អ្នកគ្រប់គ្រង",
      },
      furigana: [
        {
          rb: "上司",
          rt: "じょうし",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "司",
          on: ["シ"],
          kun: ["つかさど.る"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1338,
      kanji: "正体",
      reading: "しょうたい",
      meanings: {
        ja: "正体",
        en: "true character; identity",
        zh: "真面目；本性",
        tw: "真面目；本性",
        ko: "정체",
        vi: "chân tướng; thân phận",
        th: "ตัวตนที่แท้จริง",
        my: "မှန်ကန်သောအဖြစ်",
        km: "អត្តសញ្ញាណពិត",
      },
      furigana: [
        {
          rb: "正体",
          rt: "しょうたい",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1339,
      kanji: "照明",
      reading: "しょうめい",
      meanings: {
        ja: "照明",
        en: "illumination; lighting",
        zh: "照明",
        tw: "照明",
        ko: "조명",
        vi: "chiếu sáng",
        th: "การส่องสว่าง",
        my: "မီးအလင်း",
        km: "ពន្លឺ",
      },
      furigana: [
        {
          rb: "照明",
          rt: "しょうめい",
        },
      ],
      kanjiInfo: [
        {
          char: "照",
          on: ["ショウ"],
          kun: ["て.る", "て.らす", "て.れる"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1340,
      kanji: "女史",
      reading: "じょし",
      meanings: {
        ja: "女史",
        en: "Ms.; lady (honorific)",
        zh: "女士",
        tw: "女士",
        ko: "여사",
        vi: "nữ sĩ",
        th: "คุณผู้หญิง",
        my: "မကြီး",
        km: "លោកស្រី",
      },
      furigana: [
        {
          rb: "女史",
          rt: "じょし",
        },
      ],
      kanjiInfo: [
        {
          char: "女",
          on: ["ジョ", "ニョ", "ニョウ"],
          kun: ["おんな", "め"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "史",
          on: ["シ"],
          kun: [],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1341,
      kanji: "助詞",
      reading: "じょし",
      meanings: {
        ja: "助詞",
        en: "particle (grammar)",
        zh: "助词",
        tw: "助詞",
        ko: "조사",
        vi: "trợ từ",
        th: "คำช่วย",
        my: "အဖြည့်စကား",
        km: "អនុវាទ",
      },
      furigana: [
        {
          rb: "助詞",
          rt: "じょし",
        },
      ],
      kanjiInfo: [
        {
          char: "助",
          on: ["ジョ"],
          kun: ["たす.ける", "たす.かる", "す.ける", "すけ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1342,
      kanji: "ショック",
      reading: "ショック",
      meanings: {
        ja: "ショック",
        en: "shock",
        zh: "震惊",
        tw: "震驚",
        ko: "쇼크",
        vi: "sốc",
        th: "ช็อก",
        my: "အံ့အားသင့်မှု",
        km: "ឆក់",
      },
      furigana: [
        {
          rb: "ショック",
          rt: "ショック",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1343,
      kanji: "進行",
      reading: "しんこう",
      meanings: {
        ja: "進行",
        en: "progress; advance",
        zh: "进行",
        tw: "進行",
        ko: "진행",
        vi: "tiến hành",
        th: "ความคืบหน้า",
        my: "တိုးတက်မှု",
        km: "វឌ្ឍនភាព",
      },
      furigana: [
        {
          rb: "進行",
          rt: "しんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1344,
      kanji: "振興",
      reading: "しんこう",
      meanings: {
        ja: "振興",
        en: "promotion; encouragement",
        zh: "振兴",
        tw: "振興",
        ko: "진흥",
        vi: "chấn hưng",
        th: "การส่งเสริม",
        my: "တိုးတက်အောင်မြင်ခြင်း",
        km: "ការលើកកម្ពស់",
      },
      furigana: [
        {
          rb: "振興",
          rt: "しんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "振",
          on: ["シン"],
          kun: ["ふ.る", "ふ.れる", "ふ.るう"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "興",
          on: ["コウ", "キョウ"],
          kun: ["おこ.る", "おこ.す"],
          strokes: 16,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1345,
      kanji: "申告",
      reading: "しんこく",
      meanings: {
        ja: "申告",
        en: "report; declaration",
        zh: "申报",
        tw: "申報",
        ko: "신고",
        vi: "khai báo",
        th: "การรายงาน",
        my: "အစီရင်ခံ",
        km: "របាយការណ៍",
      },
      furigana: [
        {
          rb: "申告",
          rt: "しんこく",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "告",
          on: ["コク"],
          kun: ["つ.げる"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1346,
      kanji: "真理",
      reading: "しんり",
      meanings: {
        ja: "真理",
        en: "truth",
        zh: "真理",
        tw: "真理",
        ko: "진리",
        vi: "chân lý",
        th: "ความจริงแท้",
        my: "အမှန်တရား",
        km: "សេចក្ដីពិត",
      },
      furigana: [
        {
          rb: "真理",
          rt: "しんり",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "理",
          on: ["リ"],
          kun: ["ことわり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1347,
      kanji: "水洗",
      reading: "すいせん",
      meanings: {
        ja: "水洗",
        en: "washing with water",
        zh: "水洗",
        tw: "水洗",
        ko: "수세",
        vi: "rửa bằng nước",
        th: "การล้างด้วยน้ำ",
        my: "ရေနှင့်ဆေးခြင်း",
        km: "លាងទឹក",
      },
      furigana: [
        {
          rb: "水洗",
          rt: "すいせん",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "洗",
          on: ["セン"],
          kun: ["あら.う"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1348,
      kanji: "ストレス",
      reading: "ストレス",
      meanings: {
        ja: "ストレス",
        en: "stress",
        zh: "压力",
        tw: "壓力",
        ko: "스트레스",
        vi: "căng thẳng",
        th: "ความเครียด",
        my: "ဖိအားစိတ်",
        km: "ស្ត្រេស",
      },
      furigana: [
        {
          rb: "ストレス",
          rt: "ストレス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1349,
      kanji: "精算",
      reading: "せいさん",
      meanings: {
        ja: "精算",
        en: "exact calculation; settlement",
        zh: "清算",
        tw: "清算",
        ko: "정산",
        vi: "tính toán chính xác",
        th: "การคำนวณที่ถูกต้อง",
        my: "တိကျသေချာတွက်ချက်ခြင်း",
        km: "គណនា",
      },
      furigana: [
        {
          rb: "精算",
          rt: "せいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "精",
          on: ["セイ", "ショウ"],
          kun: ["しら.げる", "くわ.しい"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1350,
      kanji: "成年",
      reading: "せいねん",
      meanings: {
        ja: "成年",
        en: "adult age; majority",
        zh: "成年",
        tw: "成年",
        ko: "성년",
        vi: "thành niên",
        th: "ผู้ใหญ่",
        my: "အရွယ်ရောက်ခြင်း",
        km: "ពេញវ័យ",
      },
      furigana: [
        {
          rb: "成年",
          rt: "せいねん",
        },
      ],
      kanjiInfo: [
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
