export const n3part28 = {
  Lesson28: [
    {
      id: 1351,
      kanji: "声明",
      reading: "せいめい",
      meanings: {
        ja: "声明",
        en: "declaration; statement",
        zh: "声明",
        tw: "聲明",
        ko: "성명",
        vi: "tuyên bố",
        th: "คำแถลง",
        my: "ကြေညာချက်",
        km: "សេចក្តីប្រកាស",
      },
      furigana: [
        {
          rb: "声明",
          rt: "せいめい",
        },
      ],
      kanjiInfo: [
        {
          char: "声",
          on: ["セイ", "ショウ"],
          kun: ["こえ", "こわ-"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1352,
      kanji: "姓名",
      reading: "せいめい",
      meanings: {
        ja: "姓名",
        en: "full name",
        zh: "姓名",
        tw: "姓名",
        ko: "성명",
        vi: "họ tên",
        th: "ชื่อเต็ม",
        my: "အမည်အပြည့်",
        km: "ឈ្មោះពេញ",
      },
      furigana: [
        {
          rb: "姓名",
          rt: "せいめい",
        },
      ],
      kanjiInfo: [
        {
          char: "姓",
          on: ["セイ", "ショウ"],
          kun: [],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1353,
      kanji: "生理",
      reading: "せいり",
      meanings: {
        ja: "生理",
        en: "physiology; menstruation",
        zh: "生理",
        tw: "生理",
        ko: "생리",
        vi: "sinh lý; kinh nguyệt",
        th: "สรีรวิทยา; ประจำเดือน",
        my: "သဘာဝအခြေအနေ; အိမ်မက်",
        km: "រូបសាស្ត្រ; រដូវ",
      },
      furigana: [
        {
          rb: "生理",
          rt: "せいり",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "理",
          on: ["リ"],
          kun: ["ことわり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1354,
      kanji: "節",
      reading: "せつ",
      meanings: {
        ja: "節",
        en: "occasion; season; joint",
        zh: "节日；关节",
        tw: "節日；關節",
        ko: "절기; 마디",
        vi: "tiết; dịp; khớp",
        th: "ช่วงเวลา; ข้อต่อ",
        my: "အချိန်; အဆစ်",
        km: "រដូវ; សន្លាក់",
      },
      furigana: [
        {
          rb: "節",
          rt: "せつ",
        },
      ],
      kanjiInfo: [
        {
          char: "節",
          on: ["セツ", "セチ"],
          kun: ["ふし", "-ぶし", "のっと"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1355,
      kanji: "膳",
      reading: "ぜん",
      meanings: {
        ja: "膳",
        en: "small dining table (for one)",
        zh: "餐桌",
        tw: "餐桌",
        ko: "밥상",
        vi: "bàn ăn nhỏ",
        th: "โต๊ะอาหารเล็ก",
        my: "စားပွဲငယ်",
        km: "តុបាយតូច",
      },
      furigana: [
        {
          rb: "膳",
          rt: "ぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "膳",
          on: ["ゼン", "セン"],
          kun: ["かしわ", "すす.める", "そな.える"],
          strokes: 16,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1356,
      kanji: "禅",
      reading: "ぜん",
      meanings: {
        ja: "禅",
        en: "Zen; meditation",
        zh: "禅",
        tw: "禪",
        ko: "선",
        vi: "thiền",
        th: "เซน; สมาธิ",
        my: "ဇန်း; စေတနာ",
        km: "សមាធិ",
      },
      furigana: [
        {
          rb: "禅",
          rt: "ぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "禅",
          on: ["ゼン", "セン"],
          kun: ["しずか", "ゆず.る"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1357,
      kanji: "選挙",
      reading: "せんきょ",
      meanings: {
        ja: "選挙",
        en: "election",
        zh: "选举",
        tw: "選舉",
        ko: "선거",
        vi: "bầu cử",
        th: "การเลือกตั้ง",
        my: "ရွေးကောက်ပွဲ",
        km: "ការបោះឆ្នោត",
      },
      furigana: [
        {
          rb: "選挙",
          rt: "せんきょ",
        },
      ],
      kanjiInfo: [
        {
          char: "選",
          on: ["セン"],
          kun: ["えら.ぶ", "え.る", "よ.る"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "挙",
          on: ["キョ"],
          kun: ["あ.げる", "あ.がる", "こぞ.る"],
          strokes: 10,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1358,
      kanji: "先行",
      reading: "せんこう",
      meanings: {
        ja: "先行",
        en: "precedence; going ahead",
        zh: "先行",
        tw: "先行",
        ko: "선행",
        vi: "đi trước",
        th: "นำหน้า",
        my: "ရှေ့ဆောင်",
        km: "នាំមុខ",
      },
      furigana: [
        {
          rb: "先行",
          rt: "せんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1359,
      kanji: "選考",
      reading: "せんこう",
      meanings: {
        ja: "選考",
        en: "selection; screening",
        zh: "选拔",
        tw: "選拔",
        ko: "선발",
        vi: "tuyển chọn",
        th: "การคัดเลือก",
        my: "ရွေးချယ်မှု",
        km: "ការជ្រើសរើស",
      },
      furigana: [
        {
          rb: "選考",
          rt: "せんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "選",
          on: ["セン"],
          kun: ["えら.ぶ", "え.る", "よ.る"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "考",
          on: ["コウ"],
          kun: ["かんが.える", "かんが.え"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1360,
      kanji: "相",
      reading: "そう",
      meanings: {
        ja: "相",
        en: "phase; aspect",
        zh: "相貌；方面",
        tw: "相貌；方面",
        ko: "상; 모습",
        vi: "tướng; diện mạo",
        th: "ลักษณะ; ด้าน",
        my: "အရိပ်အမြွက်",
        km: "ទម្រង់",
      },
      furigana: [
        {
          rb: "相",
          rt: "そう",
        },
      ],
      kanjiInfo: [
        {
          char: "相",
          on: ["ソウ", "ショウ"],
          kun: ["あい-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1361,
      kanji: "僧",
      reading: "そう",
      meanings: {
        ja: "僧",
        en: "monk",
        zh: "僧侣",
        tw: "僧侶",
        ko: "승려",
        vi: "nhà sư",
        th: "พระ",
        my: "ဘုန်းသား",
        km: "ព្រះសង្ឃ",
      },
      furigana: [
        {
          rb: "僧",
          rt: "そう",
        },
      ],
      kanjiInfo: [
        {
          char: "僧",
          on: ["ソウ"],
          kun: [],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1362,
      kanji: "像",
      reading: "ぞう",
      meanings: {
        ja: "像",
        en: "image; statue",
        zh: "形象；雕像",
        tw: "形象；雕像",
        ko: "상",
        vi: "tượng",
        th: "รูปปั้น",
        my: "ရုပ်ထု",
        km: "រូបចម្លាក់",
      },
      furigana: [
        {
          rb: "像",
          rt: "ぞう",
        },
      ],
      kanjiInfo: [
        {
          char: "像",
          on: ["ゾウ"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1363,
      kanji: "捜査",
      reading: "そうさ",
      meanings: {
        ja: "捜査",
        en: "criminal investigation",
        zh: "侦查",
        tw: "偵查",
        ko: "수사",
        vi: "điều tra hình sự",
        th: "การสืบสวน",
        my: "အမှုစုံစမ်း",
        km: "ស៊ើបអង្កេត",
      },
      furigana: [
        {
          rb: "捜査",
          rt: "そうさ",
        },
      ],
      kanjiInfo: [
        {
          char: "捜",
          on: ["ソウ", "シュ", "シュウ"],
          kun: ["さが.す"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "査",
          on: ["サ"],
          kun: [],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1364,
      kanji: "操縦",
      reading: "そうじゅう",
      meanings: {
        ja: "操縦",
        en: "steering; control",
        zh: "操纵",
        tw: "操縱",
        ko: "조종",
        vi: "điều khiển",
        th: "การบังคับ",
        my: "ထိန်းချုပ်ခြင်း",
        km: "បញ្ជា",
      },
      furigana: [
        {
          rb: "操縦",
          rt: "そうじゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "操",
          on: ["ソウ", "サン"],
          kun: ["みさお", "あやつ.る"],
          strokes: 16,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "縦",
          on: ["ジュウ"],
          kun: ["たて"],
          strokes: 16,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1365,
      kanji: "創造",
      reading: "そうぞう",
      meanings: {
        ja: "創造",
        en: "creation",
        zh: "创造",
        tw: "創造",
        ko: "창조",
        vi: "sáng tạo",
        th: "การสร้างสรรค์",
        my: "ဖန်တီးမှု",
        km: "ការបង្កើត",
      },
      furigana: [
        {
          rb: "創造",
          rt: "そうぞう",
        },
      ],
      kanjiInfo: [
        {
          char: "創",
          on: ["ソウ", "ショウ"],
          kun: ["つく.る", "はじ.める", "きず", "けず.しける"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "造",
          on: ["ゾウ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1366,
      kanji: "隊",
      reading: "たい",
      meanings: {
        ja: "隊",
        en: "squad; group",
        zh: "队",
        tw: "隊",
        ko: "대",
        vi: "đội; nhóm",
        th: "ทีม; หน่วย",
        my: "အဖွဲ့",
        km: "ក្រុម",
      },
      furigana: [
        {
          rb: "隊",
          rt: "たい",
        },
      ],
      kanjiInfo: [
        {
          char: "隊",
          on: ["タイ"],
          kun: [],
          strokes: 12,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1367,
      kanji: "退学",
      reading: "たいがく",
      meanings: {
        ja: "退学",
        en: "dropping out of school",
        zh: "退学",
        tw: "退學",
        ko: "퇴학",
        vi: "bỏ học",
        th: "ลาออกจากโรงเรียน",
        my: "ကျောင်းထွက်ခြင်း",
        km: "ចេញពីសាលា",
      },
      furigana: [
        {
          rb: "退学",
          rt: "たいがく",
        },
      ],
      kanjiInfo: [
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1368,
      kanji: "タイトル",
      reading: "タイトル",
      meanings: {
        ja: "タイトル",
        en: "title",
        zh: "标题",
        tw: "標題",
        ko: "타이틀",
        vi: "tiêu đề",
        th: "ชื่อเรื่อง",
        my: "ခေါင်းစဉ်",
        km: "ចំណងជើង",
      },
      furigana: [
        {
          rb: "タイトル",
          rt: "タイトル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1369,
      kanji: "ダウン",
      reading: "ダウン",
      meanings: {
        ja: "ダウン",
        en: "down; decline",
        zh: "下降",
        tw: "下降",
        ko: "다운",
        vi: "giảm xuống",
        th: "ลดลง",
        my: "ကျဆင်း",
        km: "ធ្លាក់ចុះ",
      },
      furigana: [
        {
          rb: "ダウン",
          rt: "ダウン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1370,
      kanji: "盾",
      reading: "たて",
      meanings: {
        ja: "盾",
        en: "shield",
        zh: "盾牌",
        tw: "盾牌",
        ko: "방패",
        vi: "cái khiên",
        th: "โล่",
        my: "ဒိုင်း",
        km: "កំបាំង",
      },
      furigana: [
        {
          rb: "盾",
          rt: "たて",
        },
      ],
      kanjiInfo: [
        {
          char: "盾",
          on: ["ジュン"],
          kun: ["たて"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1371,
      kanji: "例え",
      reading: "たとえ",
      meanings: {
        ja: "例え",
        en: "example; metaphor",
        zh: "例子",
        tw: "例子",
        ko: "비유",
        vi: "ví dụ",
        th: "ตัวอย่าง",
        my: "ဥပမာ",
        km: "ឧទាហរណ៍",
      },
      furigana: [
        {
          rb: "例え",
          rt: "たとえ",
        },
      ],
      kanjiInfo: [
        {
          char: "例",
          on: ["レイ"],
          kun: ["たと.える"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1372,
      kanji: "チャイム",
      reading: "チャイム",
      meanings: {
        ja: "チャイム",
        en: "chime; bell",
        zh: "门铃",
        tw: "門鈴",
        ko: "차임벨",
        vi: "chuông báo",
        th: "กริ่ง",
        my: "ခေါင်းမြည်",
        km: "កណ្តឹង",
      },
      furigana: [
        {
          rb: "チャイム",
          rt: "チャイム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1373,
      kanji: "挑戦",
      reading: "ちょうせん",
      meanings: {
        ja: "挑戦",
        en: "challenge",
        zh: "挑战",
        tw: "挑戰",
        ko: "도전",
        vi: "thử thách",
        th: "ความท้าทาย",
        my: "စိန်ခေါ်မှု",
        km: "ការប្រកួតប្រជែង",
      },
      furigana: [
        {
          rb: "挑戦",
          rt: "ちょうせん",
        },
      ],
      kanjiInfo: [
        {
          char: "挑",
          on: ["チョウ"],
          kun: ["いど.む"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "戦",
          on: ["セン"],
          kun: ["いくさ", "たたか.う", "おのの.く", "そよ.ぐ", "わなな.く"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1374,
      kanji: "治療",
      reading: "ちりょう",
      meanings: {
        ja: "治療",
        en: "medical treatment",
        zh: "治疗",
        tw: "治療",
        ko: "치료",
        vi: "điều trị",
        th: "การรักษา",
        my: "ကုသမှု",
        km: "ការព្យាបាល",
      },
      furigana: [
        {
          rb: "治療",
          rt: "ちりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "治",
          on: ["ジ", "チ"],
          kun: ["おさ.める", "おさ.まる", "なお.る", "なお.す"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "療",
          on: ["リョウ"],
          kun: [],
          strokes: 17,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1375,
      kanji: "対",
      reading: "つい",
      meanings: {
        ja: "対",
        en: "pair; versus",
        zh: "对",
        tw: "對",
        ko: "대",
        vi: "cặp; đối",
        th: "คู่; การแข่งขัน",
        my: "စုံ",
        km: "គូ",
      },
      furigana: [
        {
          rb: "対",
          rt: "つい",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1376,
      kanji: "露",
      reading: "つゆ",
      meanings: {
        ja: "露",
        en: "dew",
        zh: "露水",
        tw: "露水",
        ko: "이슬",
        vi: "sương",
        th: "น้ำค้าง",
        my: "မြူ",
        km: "ទឹកអាប់",
      },
      furigana: [
        {
          rb: "露",
          rt: "つゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "露",
          on: ["ロ", "ロウ"],
          kun: ["つゆ"],
          strokes: 21,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1377,
      kanji: "データ",
      reading: "データ",
      meanings: {
        ja: "データ",
        en: "data",
        zh: "数据",
        tw: "數據",
        ko: "데이터",
        vi: "dữ liệu",
        th: "ข้อมูล",
        my: "ဒေတာ",
        km: "ទិន្នន័យ",
      },
      furigana: [
        {
          rb: "データ",
          rt: "データ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1378,
      kanji: "デザイン",
      reading: "デザイン",
      meanings: {
        ja: "デザイン",
        en: "design",
        zh: "设计",
        tw: "設計",
        ko: "디자인",
        vi: "thiết kế",
        th: "การออกแบบ",
        my: "ဒီဇိုင်း",
        km: "រចនា",
      },
      furigana: [
        {
          rb: "デザイン",
          rt: "デザイン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1379,
      kanji: "デザート",
      reading: "デザート",
      meanings: {
        ja: "デザート",
        en: "dessert",
        zh: "甜点",
        tw: "甜點",
        ko: "디저트",
        vi: "món tráng miệng",
        th: "ของหวาน",
        my: "မီးအဆင်း",
        km: "បង្អែម",
      },
      furigana: [
        {
          rb: "デザート",
          rt: "デザート",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1380,
      kanji: "転校",
      reading: "てんこう",
      meanings: {
        ja: "転校",
        en: "changing schools",
        zh: "转学",
        tw: "轉學",
        ko: "전학",
        vi: "chuyển trường",
        th: "ย้ายโรงเรียน",
        my: "ကျောင်းပြောင်း",
        km: "ផ្លាស់សាលា",
      },
      furigana: [
        {
          rb: "転校",
          rt: "てんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "校",
          on: ["コウ", "キョウ"],
          kun: [],
          strokes: 10,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1381,
      kanji: "伝言",
      reading: "でんごん",
      meanings: {
        ja: "伝言",
        en: "verbal message",
        zh: "口信",
        tw: "口信",
        ko: "전언",
        vi: "lời nhắn",
        th: "ฝากข้อความ",
        my: "သတင်းပို့",
        km: "សារ",
      },
      furigana: [
        {
          rb: "伝言",
          rt: "でんごん",
        },
      ],
      kanjiInfo: [
        {
          char: "伝",
          on: ["デン", "テン"],
          kun: [
            "つた.わる",
            "つた.える",
            "つた.う",
            "つだ.う",
            "-づた.い",
            "つて",
          ],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1382,
      kanji: "棟",
      reading: "とう",
      meanings: {
        ja: "棟",
        en: "building; ridge (of roof)",
        zh: "房屋；栋",
        tw: "房屋；棟",
        ko: "동",
        vi: "tòa nhà",
        th: "อาคาร",
        my: "အဆောက်အဦး",
        km: "អាគារ",
      },
      furigana: [
        {
          rb: "棟",
          rt: "とう",
        },
      ],
      kanjiInfo: [
        {
          char: "棟",
          on: ["トウ"],
          kun: ["むね", "むな-"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1383,
      kanji: "倒産",
      reading: "とうさん",
      meanings: {
        ja: "倒産",
        en: "bankruptcy (corporate)",
        zh: "倒闭",
        tw: "倒閉",
        ko: "도산",
        vi: "phá sản",
        th: "ล้มละลาย",
        my: "ပေါက်ကျ",
        km: "ក្ស័យធន",
      },
      furigana: [
        {
          rb: "倒産",
          rt: "とうさん",
        },
      ],
      kanjiInfo: [
        {
          char: "倒",
          on: ["トウ"],
          kun: [
            "たお.れる",
            "-だお.れ",
            "たお.す",
            "さかさま",
            "さかさ",
            "さかしま",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1384,
      kanji: "同士",
      reading: "どうし",
      meanings: {
        ja: "同士",
        en: "fellow; companion",
        zh: "同伴",
        tw: "同伴",
        ko: "동지",
        vi: "đồng chí; đồng nghiệp",
        th: "เพื่อนร่วม",
        my: "မိတ်ဆွေ",
        km: "មិត្តភក្តិ",
      },
      furigana: [
        {
          rb: "同士",
          rt: "どうし",
        },
      ],
      kanjiInfo: [
        {
          char: "同",
          on: ["ドウ"],
          kun: ["おな.じ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "士",
          on: ["シ"],
          kun: ["さむらい"],
          strokes: 3,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1385,
      kanji: "同志",
      reading: "どうし",
      meanings: {
        ja: "同志",
        en: "comrade; like-minded person",
        zh: "同志",
        tw: "同志",
        ko: "동지",
        vi: "đồng chí",
        th: "สหาย",
        my: "မိတ်ဆွေ",
        km: "មិត្តរួមគំនិត",
      },
      furigana: [
        {
          rb: "同志",
          rt: "どうし",
        },
      ],
      kanjiInfo: [
        {
          char: "同",
          on: ["ドウ"],
          kun: ["おな.じ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "志",
          on: ["シ"],
          kun: ["シリング", "こころざ.す", "こころざし"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1386,
      kanji: "動揺",
      reading: "どうよう",
      meanings: {
        ja: "動揺",
        en: "disturbance; shaking",
        zh: "动摇",
        tw: "動搖",
        ko: "동요",
        vi: "dao động; lo lắng",
        th: "ความสั่นคลอน",
        my: "ငြိမ်းမငြိမ်းဖြစ်",
        km: "អស្ថិរភាព",
      },
      furigana: [
        {
          rb: "動揺",
          rt: "どうよう",
        },
      ],
      kanjiInfo: [
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "揺",
          on: ["ヨウ"],
          kun: [
            "ゆ.れる",
            "ゆ.る",
            "ゆ.らぐ",
            "ゆ.るぐ",
            "ゆ.する",
            "ゆ.さぶる",
            "ゆ.すぶる",
            "うご.く",
          ],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1387,
      kanji: "供",
      reading: "とも",
      meanings: {
        ja: "供",
        en: "companion; offering",
        zh: "供品；同伴",
        tw: "供品；同伴",
        ko: "동반자; 공양",
        vi: "bạn đồng hành; đồ cúng",
        th: "เพื่อน; ของถวาย",
        my: "အသိုက်",
        km: "មិត្តរួមដំណើរ",
      },
      furigana: [
        {
          rb: "供",
          rt: "とも",
        },
      ],
      kanjiInfo: [
        {
          char: "供",
          on: ["キョウ", "ク", "クウ", "グ"],
          kun: ["そな.える", "とも", "-ども"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1388,
      kanji: "難",
      reading: "なん",
      meanings: {
        ja: "難",
        en: "difficulty; hardship",
        zh: "困难",
        tw: "困難",
        ko: "난관",
        vi: "khó khăn",
        th: "ความยากลำบาก",
        my: "အခက်အခဲ",
        km: "ភាពលំបាក",
      },
      furigana: [
        {
          rb: "難",
          rt: "なん",
        },
      ],
      kanjiInfo: [
        {
          char: "難",
          on: ["ナン"],
          kun: [
            "かた.い",
            "-がた.い",
            "むずか.しい",
            "むづか.しい",
            "むつか.しい",
            "-にく.い",
          ],
          strokes: 18,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1389,
      kanji: "音",
      reading: "ね",
      meanings: {
        ja: "音",
        en: "sound",
        zh: "声音",
        tw: "聲音",
        ko: "소리",
        vi: "âm thanh",
        th: "เสียง",
        my: "အသံ",
        km: "សំឡេង",
      },
      furigana: [
        {
          rb: "音",
          rt: "ね",
        },
      ],
      kanjiInfo: [
        {
          char: "音",
          on: ["オン", "イン", "-ノン"],
          kun: ["おと", "ね"],
          strokes: 9,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1390,
      kanji: "年鑑",
      reading: "ねんかん",
      meanings: {
        ja: "年鑑",
        en: "yearbook; annual",
        zh: "年鉴",
        tw: "年鑑",
        ko: "연감",
        vi: "niên giám",
        th: "หนังสือรายปี",
        my: "နှစ်စဉ်စာအုပ်",
        km: "សៀវភៅប្រចាំឆ្នាំ",
      },
      furigana: [
        {
          rb: "年鑑",
          rt: "ねんかん",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "鑑",
          on: ["カン"],
          kun: ["かんが.みる", "かがみ"],
          strokes: 23,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1391,
      kanji: "脳",
      reading: "のう",
      meanings: {
        ja: "脳",
        en: "brain",
        zh: "脑",
        tw: "腦",
        ko: "뇌",
        vi: "não",
        th: "สมอง",
        my: "ဦးနှောက်",
        km: "ខួរក្បាល",
      },
      furigana: [
        {
          rb: "脳",
          rt: "のう",
        },
      ],
      kanjiInfo: [
        {
          char: "脳",
          on: ["ノウ", "ドウ"],
          kun: ["のうずる"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1392,
      kanji: "肺",
      reading: "はい",
      meanings: {
        ja: "肺",
        en: "lung",
        zh: "肺",
        tw: "肺",
        ko: "폐",
        vi: "phổi",
        th: "ปอด",
        my: "အဆုတ်",
        km: "សួត",
      },
      furigana: [
        {
          rb: "肺",
          rt: "はい",
        },
      ],
      kanjiInfo: [
        {
          char: "肺",
          on: ["ハイ"],
          kun: [],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1393,
      kanji: "班",
      reading: "はん",
      meanings: {
        ja: "班",
        en: "group; team",
        zh: "班组",
        tw: "班組",
        ko: "반",
        vi: "tổ; nhóm",
        th: "กลุ่ม",
        my: "အဖွဲ့",
        km: "ក្រុម",
      },
      furigana: [
        {
          rb: "班",
          rt: "はん",
        },
      ],
      kanjiInfo: [
        {
          char: "班",
          on: ["ハン"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1394,
      kanji: "判",
      reading: "はん",
      meanings: {
        ja: "判",
        en: "seal; judgment",
        zh: "印章；判决",
        tw: "印章；判決",
        ko: "판",
        vi: "con dấu; phán quyết",
        th: "ตราประทับ; คำตัดสิน",
        my: "တံဆိပ်; စီရင်ချက်",
        km: "ត្រា; សាលក្រម",
      },
      furigana: [
        {
          rb: "判",
          rt: "はん",
        },
      ],
      kanjiInfo: [
        {
          char: "判",
          on: ["ハン", "バン"],
          kun: ["わか.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1395,
      kanji: "版",
      reading: "はん",
      meanings: {
        ja: "版",
        en: "edition; printing",
        zh: "版本",
        tw: "版本",
        ko: "판",
        vi: "phiên bản",
        th: "ฉบับ",
        my: "ပုံနှိပ်စုံ",
        km: "កំណែ",
      },
      furigana: [
        {
          rb: "版",
          rt: "はん",
        },
      ],
      kanjiInfo: [
        {
          char: "版",
          on: ["ハン"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1396,
      kanji: "碑",
      reading: "ひ",
      meanings: {
        ja: "碑",
        en: "stone monument; memorial",
        zh: "碑石",
        tw: "碑石",
        ko: "비석",
        vi: "bia đá",
        th: "หินอนุสรณ์",
        my: "ဂူတုံး",
        km: "បូជាអក្សរ",
      },
      furigana: [
        {
          rb: "碑",
          rt: "ひ",
        },
      ],
      kanjiInfo: [
        {
          char: "碑",
          on: ["ヒ"],
          kun: ["いしぶみ"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1397,
      kanji: "非行",
      reading: "ひこう",
      meanings: {
        ja: "非行",
        en: "delinquency",
        zh: "不良行为",
        tw: "不良行為",
        ko: "비행",
        vi: "hành vi sai trái",
        th: "ความผิดพลาด",
        my: "မကောင်းမှု",
        km: "អំពើខុស",
      },
      furigana: [
        {
          rb: "非行",
          rt: "ひこう",
        },
      ],
      kanjiInfo: [
        {
          char: "非",
          on: ["ヒ"],
          kun: ["あら.ず"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1398,
      kanji: "票",
      reading: "ひょう",
      meanings: {
        ja: "票",
        en: "vote; ballot",
        zh: "选票",
        tw: "選票",
        ko: "표",
        vi: "lá phiếu",
        th: "บัตรเลือกตั้ง",
        my: "မဲစာ",
        km: "សំបុត្របោះឆ្នោត",
      },
      furigana: [
        {
          rb: "票",
          rt: "ひょう",
        },
      ],
      kanjiInfo: [
        {
          char: "票",
          on: ["ヒョウ"],
          kun: [],
          strokes: 11,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1399,
      kanji: "福",
      reading: "ふく",
      meanings: {
        ja: "福",
        en: "fortune; blessing",
        zh: "福",
        tw: "福",
        ko: "복",
        vi: "phúc; may mắn",
        th: "โชคดี; ความสุข",
        my: "ကံကောင်းခြင်း",
        km: "សំណាង",
      },
      furigana: [
        {
          rb: "福",
          rt: "ふく",
        },
      ],
      kanjiInfo: [
        {
          char: "福",
          on: ["フク"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1400,
      kanji: "振り",
      reading: "ふり",
      meanings: {
        ja: "振り",
        en: "swing; appearance",
        zh: "摆动；样子",
        tw: "擺動；樣子",
        ko: "흔들림; 모습",
        vi: "vung vẩy; dáng vẻ",
        th: "การแกว่ง; ลักษณะ",
        my: "လှုပ်ရှားမှု",
        km: "របៀប; ទម្រង់",
      },
      furigana: [
        {
          rb: "振り",
          rt: "ふり",
        },
      ],
      kanjiInfo: [
        {
          char: "振",
          on: ["シン"],
          kun: ["ふ.る", "ふ.れる", "ふ.るう"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1616,
      kanji: "冷ます",
      reading: "さます",
      meanings: {
        ja: "冷ます",
        en: "to cool (from hot to room temp)",
        zh: "冷却",
        tw: "冷卻",
        ko: "식히다",
        vi: "làm nguội",
        th: "ทำให้เย็น",
        my: "အေးစေသည်",
        km: "បង្ហាប់ឲ្យត្រជាក់",
      },
      furigana: [
        {
          rb: "冷ます",
          rt: "さます",
        },
      ],
      kanjiInfo: [
        {
          char: "冷",
          on: ["レイ"],
          kun: [
            "つめ.たい",
            "ひ.える",
            "ひ.や",
            "ひ.ややか",
            "ひ.やす",
            "ひ.やかす",
            "さ.める",
            "さ.ます",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1617,
      kanji: "覚ます",
      reading: "さます",
      meanings: {
        ja: "覚ます",
        en: "to awaken (someone)",
        zh: "叫醒",
        tw: "叫醒",
        ko: "깨우다",
        vi: "đánh thức",
        th: "ปลุกให้ตื่น",
        my: "နိုးရာလုပ်သည်",
        km: "បញ្ចុះឲ្យភ្ញាក់",
      },
      furigana: [
        {
          rb: "覚ます",
          rt: "さます",
        },
      ],
      kanjiInfo: [
        {
          char: "覚",
          on: ["カク"],
          kun: ["おぼ.える", "さ.ます", "さ.める", "さと.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1618,
      kanji: "冷める",
      reading: "さめる",
      meanings: {
        ja: "冷める",
        en: "to cool down",
        zh: "变凉",
        tw: "變涼",
        ko: "식다",
        vi: "nguội đi",
        th: "เย็นลง",
        my: "အေးသွားသည်",
        km: "ត្រជាក់ចុះ",
      },
      furigana: [
        {
          rb: "冷める",
          rt: "さめる",
        },
      ],
      kanjiInfo: [
        {
          char: "冷",
          on: ["レイ"],
          kun: [
            "つめ.たい",
            "ひ.える",
            "ひ.や",
            "ひ.ややか",
            "ひ.やす",
            "ひ.やかす",
            "さ.める",
            "さ.ます",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1619,
      kanji: "覚める",
      reading: "さめる",
      meanings: {
        ja: "覚める",
        en: "to wake (up)",
        zh: "醒来",
        tw: "醒來",
        ko: "깨다",
        vi: "tỉnh dậy",
        th: "ตื่น",
        my: "နိုးသည်",
        km: "ភ្ញាក់ឡើង",
      },
      furigana: [
        {
          rb: "覚める",
          rt: "さめる",
        },
      ],
      kanjiInfo: [
        {
          char: "覚",
          on: ["カク"],
          kun: ["おぼ.える", "さ.ます", "さ.める", "さと.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1620,
      kanji: "去る",
      reading: "さる",
      meanings: {
        ja: "去る",
        en: "to leave; depart",
        zh: "离开",
        tw: "離開",
        ko: "떠나다",
        vi: "rời đi",
        th: "จากไป",
        my: "ထွက်ခွာသည်",
        km: "ចាកចេញ",
      },
      furigana: [
        {
          rb: "去る",
          rt: "さる",
        },
      ],
      kanjiInfo: [
        {
          char: "去",
          on: ["キョ", "コ"],
          kun: ["さ.る", "-さ.る"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1621,
      kanji: "沈む",
      reading: "しずむ",
      meanings: {
        ja: "沈む",
        en: "to sink",
        zh: "下沉",
        tw: "下沉",
        ko: "가라앉다",
        vi: "chìm",
        th: "จม",
        my: "မြှုပ်မောင်းသွားသည်",
        km: "លិច",
      },
      furigana: [
        {
          rb: "沈む",
          rt: "しずむ",
        },
      ],
      kanjiInfo: [
        {
          char: "沈",
          on: ["チン", "ジン"],
          kun: ["しず.む", "しず.める"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1622,
      kanji: "従う",
      reading: "したがう",
      meanings: {
        ja: "従う",
        en: "to obey (an order); follow",
        zh: "服从；遵从",
        tw: "服從；遵從",
        ko: "따르다",
        vi: "tuân theo",
        th: "เชื่อฟัง",
        my: "လိုက်နာသည်",
        km: "គោរពតាម",
      },
      furigana: [
        {
          rb: "従う",
          rt: "したがう",
        },
      ],
      kanjiInfo: [
        {
          char: "従",
          on: ["ジュウ", "ショウ", "ジュ"],
          kun: ["したが.う", "したが.える", "より"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1623,
      kanji: "しばしば",
      reading: "しばしば",
      meanings: {
        ja: "しばしば",
        en: "often; frequently",
        zh: "时常；经常",
        tw: "時常；經常",
        ko: "자주",
        vi: "thường xuyên",
        th: "บ่อยครั้ง",
        my: "မကြာခဏ",
        km: "ញឹកញាប់",
      },
      furigana: [
        {
          rb: "しばしば",
          rt: "しばしば",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1624,
      kanji: "支払う",
      reading: "しはらう",
      meanings: {
        ja: "支払う",
        en: "to pay",
        zh: "支付",
        tw: "支付",
        ko: "지불하다",
        vi: "trả tiền",
        th: "ชำระเงิน",
        my: "ငွေပေးချေသည်",
        km: "បង់ប្រាក់",
      },
      furigana: [
        {
          rb: "支払う",
          rt: "しはらう",
        },
      ],
      kanjiInfo: [
        {
          char: "支",
          on: ["シ"],
          kun: ["ささ.える", "つか.える", "か.う"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "払",
          on: ["フツ", "ヒツ", "ホツ"],
          kun: ["はら.う", "-はら.い", "-ばら.い"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1625,
      kanji: "示す",
      reading: "しめす",
      meanings: {
        ja: "示す",
        en: "to show; display",
        zh: "出示；表示",
        tw: "出示；表示",
        ko: "보여 주다",
        vi: "cho thấy",
        th: "แสดงให้เห็น",
        my: "ပြသသည်",
        km: "បង្ហាញ",
      },
      furigana: [
        {
          rb: "示す",
          rt: "しめす",
        },
      ],
      kanjiInfo: [
        {
          char: "示",
          on: ["ジ", "シ"],
          kun: ["しめ.す"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1626,
      kanji: "占める",
      reading: "しめる",
      meanings: {
        ja: "占める",
        en: "to occupy; account for",
        zh: "占据；占",
        tw: "佔據；佔",
        ko: "차지하다",
        vi: "chiếm",
        th: "ครอง; คิดเป็น",
        my: "စီးနင်းသည်",
        km: "កាន់កាប់",
      },
      furigana: [
        {
          rb: "占める",
          rt: "しめる",
        },
      ],
      kanjiInfo: [
        {
          char: "占",
          on: ["セン"],
          kun: ["し.める", "うらな.う"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1627,
      kanji: "湿る",
      reading: "しめる",
      meanings: {
        ja: "湿る",
        en: "to become damp",
        zh: "变潮湿",
        tw: "變潮濕",
        ko: "축축해지다",
        vi: "ẩm ướt",
        th: "ชื้น",
        my: "စိုစွတ်လာသည်",
        km: "សើមឡើង",
      },
      furigana: [
        {
          rb: "湿る",
          rt: "しめる",
        },
      ],
      kanjiInfo: [
        {
          char: "湿",
          on: ["シツ", "シュウ"],
          kun: ["しめ.る", "しめ.す", "うるお.う", "うるお.す"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1628,
      kanji: "生じる",
      reading: "しょうじる",
      meanings: {
        ja: "生じる",
        en: "to produce; arise",
        zh: "产生；发生",
        tw: "產生；發生",
        ko: "생じ다",
        vi: "phát sinh",
        th: "เกิดขึ้น",
        my: "ဖြစ်ပေါ်သည်",
        km: "កើតមាន",
      },
      furigana: [
        {
          rb: "生じる",
          rt: "しょうじる",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1629,
      kanji: "信じる",
      reading: "しんじる",
      meanings: {
        ja: "信じる",
        en: "to believe; trust",
        zh: "相信",
        tw: "相信",
        ko: "믿다",
        vi: "tin",
        th: "เชื่อ",
        my: "ယုံကြည်သည်",
        km: "ជឿ",
      },
      furigana: [
        {
          rb: "信じる",
          rt: "しんじる",
        },
      ],
      kanjiInfo: [
        {
          char: "信",
          on: ["シン"],
          kun: [],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1630,
      kanji: "救う",
      reading: "すくう",
      meanings: {
        ja: "救う",
        en: "to rescue; save",
        zh: "拯救",
        tw: "拯救",
        ko: "구하다",
        vi: "cứu",
        th: "ช่วยชีวิต",
        my: "ကယ်ဆယ်သည်",
        km: "សង្គ្រោះ",
      },
      furigana: [
        {
          rb: "救う",
          rt: "すくう",
        },
      ],
      kanjiInfo: [
        {
          char: "救",
          on: ["キュウ"],
          kun: ["すく.う"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1631,
      kanji: "優れる",
      reading: "すぐれる",
      meanings: {
        ja: "優れる",
        en: "to excel; be superior",
        zh: "出众；优秀",
        tw: "出眾；優秀",
        ko: "뛰어나다",
        vi: "xuất sắc",
        th: "โดดเด่น",
        my: "ထူးချွန်သည်",
        km: "ល្អប្រសើរ",
      },
      furigana: [
        {
          rb: "優れる",
          rt: "すぐれる",
        },
      ],
      kanjiInfo: [
        {
          char: "優",
          on: ["ユウ", "ウ"],
          kun: ["やさ.しい", "すぐ.れる", "まさ.る"],
          strokes: 17,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1632,
      kanji: "過ごす",
      reading: "すごす",
      meanings: {
        ja: "過ごす",
        en: "to spend (time)",
        zh: "度过",
        tw: "度過",
        ko: "보내다",
        vi: "trải qua",
        th: "ใช้เวลา",
        my: "အချိန်ကုန်သည်",
        km: "កន្លងផុត",
      },
      furigana: [
        {
          rb: "過ごす",
          rt: "すごす",
        },
      ],
      kanjiInfo: [
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1633,
      kanji: "進める",
      reading: "すすめる",
      meanings: {
        ja: "進める",
        en: "to advance; move forward",
        zh: "推进",
        tw: "推進",
        ko: "진척시키다",
        vi: "thúc đẩy; tiến hành",
        th: "เดินหน้า",
        my: "တိုးတက်စေသည်",
        km: "推进／អូសទៅមុខ",
      },
      furigana: [
        {
          rb: "進める",
          rt: "すすめる",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1634,
      kanji: "勧める",
      reading: "すすめる",
      meanings: {
        ja: "勧める",
        en: "to recommend; urge",
        zh: "劝告；推荐",
        tw: "勸告；推薦",
        ko: "권하다",
        vi: "khuyên; giới thiệu",
        th: "แนะนำ",
        my: "ထောက်ခံရန်ပြောသည်",
        km: "ណែនាំ",
      },
      furigana: [
        {
          rb: "勧める",
          rt: "すすめる",
        },
      ],
      kanjiInfo: [
        {
          char: "勧",
          on: ["カン", "ケン"],
          kun: ["すす.める"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1635,
      kanji: "済ませる",
      reading: "すませる",
      meanings: {
        ja: "済ませる",
        en: "to finish; settle",
        zh: "了结；办完",
        tw: "了結；辦完",
        ko: "끝내다",
        vi: "hoàn tất",
        th: "ทำให้เสร็จ",
        my: "ပြီးစီးစေသည်",
        km: "បញ្ចប់",
      },
      furigana: [
        {
          rb: "済ませる",
          rt: "すませる",
        },
      ],
      kanjiInfo: [
        {
          char: "済",
          on: ["サイ", "セイ"],
          kun: [
            "す.む",
            "-ず.み",
            "-ずみ",
            "す.まない",
            "す.ます",
            "-す.ます",
            "すく.う",
            "な.す",
            "わたし",
            "わた.る",
          ],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1636,
      kanji: "澄む",
      reading: "すむ",
      meanings: {
        ja: "澄む",
        en: "to become clear (water/air)",
        zh: "变清澈",
        tw: "變清澈",
        ko: "맑아지다",
        vi: "trở nên trong",
        th: "ใสขึ้น",
        my: "ကျယ်ပေါကြားလာသည်",
        km: "ថ្លាឡើង",
      },
      furigana: [
        {
          rb: "澄む",
          rt: "すむ",
        },
      ],
      kanjiInfo: [
        {
          char: "澄",
          on: ["チョウ"],
          kun: ["す.む", "す.ます", "-す.ます"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1637,
      kanji: "清む",
      reading: "すむ",
      meanings: {
        ja: "清む",
        en: "to become clear (water)",
        zh: "变清澈",
        tw: "變清澈",
        ko: "맑아지다",
        vi: "trong lại",
        th: "ใสขึ้น",
        my: "ထွက်ကြီးထွား",
        km: "ថ្លាឡើង",
      },
      furigana: [
        {
          rb: "清む",
          rt: "すむ",
        },
      ],
      kanjiInfo: [
        {
          char: "清",
          on: ["セイ", "ショウ", "シン"],
          kun: ["きよ.い", "きよ.まる", "きよ.める"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1638,
      kanji: "刷る",
      reading: "する",
      meanings: {
        ja: "刷る",
        en: "to print",
        zh: "印刷",
        tw: "印刷",
        ko: "인쇄하다",
        vi: "in ấn",
        th: "พิมพ์",
        my: "ပုံနှိပ်သည်",
        km: "បោះពុម្ព",
      },
      furigana: [
        {
          rb: "刷る",
          rt: "する",
        },
      ],
      kanjiInfo: [
        {
          char: "刷",
          on: ["サツ"],
          kun: ["す.る", "-ず.り", "-ずり", "は.く"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1639,
      kanji: "為る",
      reading: "する",
      meanings: {
        ja: "為る",
        en: "to do",
        zh: "做",
        tw: "做",
        ko: "하다",
        vi: "làm",
        th: "ทำ",
        my: "လုပ်သည်",
        km: "ធ្វើ",
      },
      furigana: [
        {
          rb: "為る",
          rt: "する",
        },
      ],
      kanjiInfo: [
        {
          char: "為",
          on: ["イ"],
          kun: ["ため", "な.る", "な.す", "す.る", "たり", "つく.る", "なり"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1640,
      kanji: "すれ違う",
      reading: "すれちがう",
      meanings: {
        ja: "すれ違う",
        en: "to pass by each other; miss",
        zh: "擦肩而过",
        tw: "擦肩而過",
        ko: "스치듯 지나가다",
        vi: "lướt qua nhau",
        th: "สวนกัน",
        my: "ဆန့်ကျင်ဖြတ်သန်း",
        km: "ឆ្លងផុតគ្នា",
      },
      furigana: [
        {
          rb: "すれ違う",
          rt: "すれちがう",
        },
      ],
      kanjiInfo: [
        {
          char: "違",
          on: ["イ"],
          kun: [
            "ちが.う",
            "ちが.い",
            "ちが.える",
            "-ちが.える",
            "たが.う",
            "たが.える",
          ],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1641,
      kanji: "ずれる",
      reading: "ずれる",
      meanings: {
        ja: "ずれる",
        en: "to slip; be off; shift",
        zh: "偏移；滑动",
        tw: "偏移；滑動",
        ko: "어긋나다; 미끄러지다",
        vi: "trệch; xê dịch",
        th: "เลื่อน; เคลื่อน",
        my: "ရွေ့လျားသည်",
        km: "ផ្លាស់ទីបន្តិច",
      },
      furigana: [
        {
          rb: "ずれる",
          rt: "ずれる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1642,
      kanji: "愛する",
      reading: "あいする",
      meanings: {
        ja: "愛する",
        en: "to love",
        zh: "爱",
        tw: "愛",
        ko: "사랑하다",
        vi: "yêu",
        th: "รัก",
        my: "ချစ်သည်",
        km: "ស្រលាញ់",
      },
      furigana: [
        {
          rb: "愛する",
          rt: "あいする",
        },
      ],
      kanjiInfo: [
        {
          char: "愛",
          on: ["アイ"],
          kun: ["いと.しい", "かな.しい", "め.でる", "お.しむ", "まな"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1643,
      kanji: "遭う",
      reading: "あう",
      meanings: {
        ja: "遭う",
        en: "to encounter (e.g., trouble/accident)",
        zh: "遭遇",
        tw: "遭遇",
        ko: "당하다; 맞닥뜨리다",
        vi: "gặp phải",
        th: "ประสบ (อุบัติเหตุ)",
        my: "ကြုံတွေ့သည်",
        km: "ប្រទះឃើញ",
      },
      furigana: [
        {
          rb: "遭う",
          rt: "あう",
        },
      ],
      kanjiInfo: [
        {
          char: "遭",
          on: ["ソウ"],
          kun: ["あ.う", "あ.わせる"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1644,
      kanji: "諦める",
      reading: "あきらめる",
      meanings: {
        ja: "諦める",
        en: "to give up",
        zh: "放弃",
        tw: "放棄",
        ko: "포기하다",
        vi: "từ bỏ",
        th: "ยอมแพ้",
        my: "လက်လျှော့သည်",
        km: "បោះបង់",
      },
      furigana: [
        {
          rb: "諦める",
          rt: "あきらめる",
        },
      ],
      kanjiInfo: [
        {
          char: "諦",
          on: ["テイ", "タイ"],
          kun: ["あきら.める", "つまびらか", "まこと"],
          strokes: 16,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1645,
      kanji: "飽きる",
      reading: "あきる",
      meanings: {
        ja: "飽きる",
        en: "to get tired of",
        zh: "腻烦",
        tw: "膩煩",
        ko: "질리다",
        vi: "chán",
        th: "เบื่อ",
        my: "倦ဉ်းမြန်းသည်",
        km: "ធុញឆ្អែរ",
      },
      furigana: [
        {
          rb: "飽きる",
          rt: "あきる",
        },
      ],
      kanjiInfo: [
        {
          char: "飽",
          on: ["ホウ"],
          kun: ["あ.きる", "あ.かす", "あ.く"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1646,
      kanji: "明ける",
      reading: "あける",
      meanings: {
        ja: "明ける",
        en: "to open (e.g., a door); to dawn",
        zh: "打开；天亮",
        tw: "打開；天亮",
        ko: "열다; 날이 새다",
        vi: "mở; rạng sáng",
        th: "เปิด; รุ่งสาง",
        my: "ဖွင့်; လူရွေ့",
        km: "បើក; ព្រលឹម",
      },
      furigana: [
        {
          rb: "明ける",
          rt: "あける",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1647,
      kanji: "揚げる",
      reading: "あげる",
      meanings: {
        ja: "揚げる",
        en: "to deep-fry",
        zh: "油炸",
        tw: "油炸",
        ko: "튀기다",
        vi: "chiên ngập dầu",
        th: "ทอด (น้ำมันมาก)",
        my: "ဖရန်揚သည်",
        km: "ចៀនក្នុងប្រេង",
      },
      furigana: [
        {
          rb: "揚げる",
          rt: "あげる",
        },
      ],
      kanjiInfo: [
        {
          char: "揚",
          on: ["ヨウ"],
          kun: ["あ.げる", "-あ.げ", "あ.がる"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1648,
      kanji: "挙げる",
      reading: "あげる",
      meanings: {
        ja: "挙げる",
        en: "to raise; to give (an example)",
        zh: "举起；举例",
        tw: "舉起；舉例",
        ko: "들다; (예를) 들다",
        vi: "nêu; giơ lên",
        th: "ยก; ยกตัวอย่าง",
        my: "မြှောက်; ဥပမာပေး",
        km: "លើក; ឧទាហរណ៍",
      },
      furigana: [
        {
          rb: "挙げる",
          rt: "あげる",
        },
      ],
      kanjiInfo: [
        {
          char: "挙",
          on: ["キョ"],
          kun: ["あ.げる", "あ.がる", "こぞ.る"],
          strokes: 10,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1649,
      kanji: "預かる",
      reading: "あずかる",
      meanings: {
        ja: "預かる",
        en: "to look after; keep",
        zh: "代为保管",
        tw: "代為保管",
        ko: "맡다",
        vi: "giữ hộ",
        th: "รับฝาก",
        my: "ကိုင်ဆောင်ခံယူ",
        km: "ទទួលរក្សាទុក",
      },
      furigana: [
        {
          rb: "預かる",
          rt: "あずかる",
        },
      ],
      kanjiInfo: [
        {
          char: "預",
          on: ["ヨ"],
          kun: ["あず.ける", "あず.かる"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1650,
      kanji: "預ける",
      reading: "あずける",
      meanings: {
        ja: "預ける",
        en: "to deposit; leave in someone's care",
        zh: "寄存；托付",
        tw: "寄存；託付",
        ko: "맡기다",
        vi: "gửi; giao cho",
        th: "ฝากไว้",
        my: "အပ်နှံသည်",
        km: "ដាក់ឲ្យរក្សាទុក",
      },
      furigana: [
        {
          rb: "預ける",
          rt: "あずける",
        },
      ],
      kanjiInfo: [
        {
          char: "預",
          on: ["ヨ"],
          kun: ["あず.ける", "あず.かる"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1651,
      kanji: "与える",
      reading: "あたえる",
      meanings: {
        ja: "与える",
        en: "to give; grant (to lower status)",
        zh: "给予；赋予",
        tw: "給予；賦予",
        ko: "주다; 부여하다",
        vi: "ban cho; cho",
        th: "มอบให้",
        my: "ပေးအပ်သည်",
        km: "ផ្តល់ឲ្យ",
      },
      furigana: [
        {
          rb: "与える",
          rt: "あたえる",
        },
      ],
      kanjiInfo: [
        {
          char: "与",
          on: ["ヨ"],
          kun: ["あた.える", "あずか.る", "くみ.する", "ともに"],
          strokes: 3,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1652,
      kanji: "暖まる",
      reading: "あたたまる",
      meanings: {
        ja: "暖まる",
        en: "to get warm (oneself)",
        zh: "变暖",
        tw: "變暖",
        ko: "따뜻해지다",
        vi: "ấm lên",
        th: "อุ่นขึ้น",
        my: "ပူချိန်မြင့်လာ",
        km: "ក្តៅឡើង",
      },
      furigana: [
        {
          rb: "暖まる",
          rt: "あたたまる",
        },
      ],
      kanjiInfo: [
        {
          char: "暖",
          on: ["ダン", "ノン"],
          kun: ["あたた.か", "あたた.かい", "あたた.まる", "あたた.める"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1653,
      kanji: "温まる",
      reading: "あたたまる",
      meanings: {
        ja: "温まる",
        en: "to get warm (oneself)",
        zh: "变暖",
        tw: "變暖",
        ko: "따뜻해지다",
        vi: "ấm lên",
        th: "อุ่นขึ้น",
        my: "အပူတိုးလာ",
        km: "កក់ក្តៅឡើង",
      },
      furigana: [
        {
          rb: "温まる",
          rt: "あたたまる",
        },
      ],
      kanjiInfo: [
        {
          char: "温",
          on: ["オン"],
          kun: [
            "あたた.か",
            "あたた.かい",
            "あたた.まる",
            "あたた.める",
            "ぬく",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1654,
      kanji: "暖める",
      reading: "あたためる",
      meanings: {
        ja: "暖める",
        en: "to warm (up)",
        zh: "使变暖",
        tw: "使變暖",
        ko: "따뜻하게 하다",
        vi: "làm ấm",
        th: "ทำให้อุ่น",
        my: "အပူပေးသည်",
        km: "កម្ដៅឲ្យ",
      },
      furigana: [
        {
          rb: "暖める",
          rt: "あたためる",
        },
      ],
      kanjiInfo: [
        {
          char: "暖",
          on: ["ダン", "ノン"],
          kun: ["あたた.か", "あたた.かい", "あたた.まる", "あたた.める"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1655,
      kanji: "温める",
      reading: "あたためる",
      meanings: {
        ja: "温める",
        en: "to warm (up)",
        zh: "加热",
        tw: "加熱",
        ko: "데우다",
        vi: "hâm nóng",
        th: "อุ่น (อาหาร)",
        my: "အပူပေး (အစားအစာ)",
        km: "កម្ដៅឡើង",
      },
      furigana: [
        {
          rb: "温める",
          rt: "あたためる",
        },
      ],
      kanjiInfo: [
        {
          char: "温",
          on: ["オン"],
          kun: [
            "あたた.か",
            "あたた.かい",
            "あたた.まる",
            "あたた.める",
            "ぬく",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1656,
      kanji: "当たる",
      reading: "あたる",
      meanings: {
        ja: "当たる",
        en: "to be hit; to be right",
        zh: "击中；命中",
        tw: "擊中；命中",
        ko: "맞다; 맞추다",
        vi: "trúng; đúng",
        th: "ถูก; โดน",
        my: "ထိသည်; မှန်သည်",
        km: "បុកត្រូវ; ត្រឹមត្រូវ",
      },
      furigana: [
        {
          rb: "当たる",
          rt: "あたる",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1657,
      kanji: "扱う",
      reading: "あつかう",
      meanings: {
        ja: "扱う",
        en: "to handle; deal with",
        zh: "处理；对待",
        tw: "處理；對待",
        ko: "다루다",
        vi: "xử lý; đối xử",
        th: "จัดการ; ปฏิบัติต่อ",
        my: "ကိုင်တွယ်သည်",
        km: "ដោះស្រាយ; ប្រព្រឹត្តិ",
      },
      furigana: [
        {
          rb: "扱う",
          rt: "あつかう",
        },
      ],
      kanjiInfo: [
        {
          char: "扱",
          on: ["ソウ", "キュウ"],
          kun: ["あつか.い", "あつか.う", "あつか.る", "こ.く"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1658,
      kanji: "当てる",
      reading: "あてる",
      meanings: {
        ja: "当てる",
        en: "to hit; apply; guess",
        zh: "碰上；贴上；猜中",
        tw: "碰上；貼上；猜中",
        ko: "맞히다; 대다",
        vi: "đánh trúng; áp vào; đoán",
        th: "ทายถูก; กระทบ",
        my: "ထိမိစေ; ခန့်မှန်း",
        km: "ប៉ះឲ្យត្រូវ; ទាយ",
      },
      furigana: [
        {
          rb: "当てる",
          rt: "あてる",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1659,
      kanji: "争う",
      reading: "あらそう",
      meanings: {
        ja: "争う",
        en: "to compete; fight",
        zh: "争夺；斗争",
        tw: "爭奪；鬥爭",
        ko: "다투다; 겨루다",
        vi: "tranh đấu; thi đua",
        th: "แข่งขัน; โต้แย้ง",
        my: "ယှဉ်ပြိုင်သည်",
        km: "ប្រកួតប្រជែង",
      },
      furigana: [
        {
          rb: "争う",
          rt: "あらそう",
        },
      ],
      kanjiInfo: [
        {
          char: "争",
          on: ["ソウ"],
          kun: ["あらそ.う", "いか.でか"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1660,
      kanji: "表す",
      reading: "あらわす",
      meanings: {
        ja: "表す",
        en: "to express; represent",
        zh: "表达；表示",
        tw: "表達；表示",
        ko: "나타내다",
        vi: "biểu thị",
        th: "แสดงออก",
        my: "ဖော်ပြသည်",
        km: "បង្ហាញ",
      },
      furigana: [
        {
          rb: "表す",
          rt: "あらわす",
        },
      ],
      kanjiInfo: [
        {
          char: "表",
          on: ["ヒョウ"],
          kun: ["おもて", "-おもて", "あらわ.す", "あらわ.れる", "あら.わす"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1661,
      kanji: "現す",
      reading: "あらわす",
      meanings: {
        ja: "現す",
        en: "to reveal; show",
        zh: "显现；揭示",
        tw: "顯現；揭示",
        ko: "드러내다",
        vi: "bộc lộ; làm hiện ra",
        th: "เผยให้เห็น",
        my: "ဖော်ထုတ်ပြသည်",
        km: "បង្ហាញចេញ",
      },
      furigana: [
        {
          rb: "現す",
          rt: "あらわす",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1662,
      kanji: "著す",
      reading: "あらわす",
      meanings: {
        ja: "著す",
        en: "to write; author",
        zh: "著述；写作",
        tw: "著述；寫作",
        ko: "저술하다",
        vi: "trước tác; viết",
        th: "ประพันธ์",
        my: "ရေးသားသည်",
        km: "តែងសរសេរ",
      },
      furigana: [
        {
          rb: "著す",
          rt: "あらわす",
        },
      ],
      kanjiInfo: [
        {
          char: "著",
          on: ["チョ", "チャク"],
          kun: ["あらわ.す", "いちじる.しい"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1663,
      kanji: "現れる",
      reading: "あらわれる",
      meanings: {
        ja: "現れる",
        en: "to appear; emerge",
        zh: "出现",
        tw: "出現",
        ko: "나타나다",
        vi: "xuất hiện",
        th: "ปรากฏ",
        my: "ပေါ်ထွက်သည်",
        km: "បង្ហាញខ្លួន",
      },
      furigana: [
        {
          rb: "現れる",
          rt: "あらわれる",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1664,
      kanji: "合わせる",
      reading: "あわせる",
      meanings: {
        ja: "合わせる",
        en: "to match; combine; align",
        zh: "配合；对齐",
        tw: "配合；對齊",
        ko: "맞추다; 합치다",
        vi: "phối hợp; điều chỉnh",
        th: "ปรับให้เข้ากัน",
        my: "ကိုက်ညီစေသည်",
        km: "ផ្គុំឲ្យសម",
      },
      furigana: [
        {
          rb: "合わせる",
          rt: "あわせる",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1665,
      kanji: "慌てる",
      reading: "あわてる",
      meanings: {
        ja: "慌てる",
        en: "to panic; become flustered",
        zh: "慌张",
        tw: "慌張",
        ko: "당황하다",
        vi: "hoảng hốt",
        th: "ลนลาน",
        my: "ဇဗျာဖြစ်သည်",
        km: "ស្ទះស្ទាក់",
      },
      furigana: [
        {
          rb: "慌てる",
          rt: "あわてる",
        },
      ],
      kanjiInfo: [
        {
          char: "慌",
          on: ["コウ"],
          kun: ["あわ.てる", "あわ.ただしい"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
