export const n3part4 = {
  Lesson4: [
    {
      id: 151,
      kanji: "作法",
      reading: "さほう",
      meanings: {
        ja: "manners",
        en: "manners",
        zh: "manners",
        tw: "manners",
        ko: "manners",
        vi: "manners",
        th: "manners",
        my: "manners",
        km: "manners",
      },
      furigana: [
        {
          rb: "作法",
          rt: "さほう",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "法",
          on: ["ホウ", "ハッ", "ホッ", "フラン"],
          kun: ["のり"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 152,
      kanji: "左右",
      reading: "さゆう",
      meanings: {
        ja: "left and right",
        en: "left and right",
        zh: "left and right",
        tw: "left and right",
        ko: "left and right",
        vi: "left and right",
        th: "left and right",
        my: "left and right",
        km: "left and right",
      },
      furigana: [
        {
          rb: "左右",
          rt: "さゆう",
        },
      ],
      kanjiInfo: [
        {
          char: "左",
          on: ["サ", "シャ"],
          kun: ["ひだり"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "右",
          on: ["ウ", "ユウ"],
          kun: ["みぎ"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 153,
      kanji: "皿",
      reading: "さら",
      meanings: {
        ja: "plate",
        en: "plate",
        zh: "plate",
        tw: "plate",
        ko: "plate",
        vi: "plate",
        th: "plate",
        my: "plate",
        km: "plate",
      },
      furigana: [
        {
          rb: "皿",
          rt: "さら",
        },
      ],
      kanjiInfo: [
        {
          char: "皿",
          on: ["ベイ"],
          kun: ["さら"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 154,
      kanji: "猿",
      reading: "さる",
      meanings: {
        ja: "monkey (esp. the Japanese macaque",
        en: "monkey (esp. the Japanese macaque",
        zh: "monkey (esp. the Japanese macaque",
        tw: "monkey (esp. the Japanese macaque",
        ko: "monkey (esp. the Japanese macaque",
        vi: "monkey (esp. the Japanese macaque",
        th: "monkey (esp. the Japanese macaque",
        my: "monkey (esp. the Japanese macaque",
        km: "monkey (esp. the Japanese macaque",
      },
      furigana: [
        {
          rb: "猿",
          rt: "さる",
        },
      ],
      kanjiInfo: [
        {
          char: "猿",
          on: ["エン"],
          kun: ["さる"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 155,
      kanji: "騒ぎ",
      reading: "さわぎ",
      meanings: {
        ja: "uproar",
        en: "uproar",
        zh: "uproar",
        tw: "uproar",
        ko: "uproar",
        vi: "uproar",
        th: "uproar",
        my: "uproar",
        km: "uproar",
      },
      furigana: [
        {
          rb: "騒ぎ",
          rt: "さわぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "騒",
          on: ["ソウ"],
          kun: ["さわ.ぐ", "うれい", "さわ.がしい"],
          strokes: 18,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 156,
      kanji: "参加",
      reading: "さんか",
      meanings: {
        ja: "participation",
        en: "participation",
        zh: "participation",
        tw: "participation",
        ko: "participation",
        vi: "participation",
        th: "participation",
        my: "participation",
        km: "participation",
      },
      furigana: [
        {
          rb: "参加",
          rt: "さんか",
        },
      ],
      kanjiInfo: [
        {
          char: "参",
          on: ["サン", "シン"],
          kun: ["まい.る", "まい-", "まじわる", "みつ"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "加",
          on: ["カ"],
          kun: ["くわ.える", "くわ.わる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 157,
      kanji: "参考",
      reading: "さんこう",
      meanings: {
        ja: "reference",
        en: "reference",
        zh: "reference",
        tw: "reference",
        ko: "reference",
        vi: "reference",
        th: "reference",
        my: "reference",
        km: "reference",
      },
      furigana: [
        {
          rb: "参考",
          rt: "さんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "参",
          on: ["サン", "シン"],
          kun: ["まい.る", "まい-", "まじわる", "みつ"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "考",
          on: ["コウ"],
          kun: ["かんが.える", "かんが.え"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 158,
      kanji: "賛成",
      reading: "さんせい",
      meanings: {
        ja: "approval",
        en: "approval",
        zh: "approval",
        tw: "approval",
        ko: "approval",
        vi: "approval",
        th: "approval",
        my: "approval",
        km: "approval",
      },
      furigana: [
        {
          rb: "賛成",
          rt: "さんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "賛",
          on: ["サン"],
          kun: ["たす.ける", "たた.える"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 159,
      kanji: "酸性",
      reading: "さんせい",
      meanings: {
        ja: "acidity",
        en: "acidity",
        zh: "acidity",
        tw: "acidity",
        ko: "acidity",
        vi: "acidity",
        th: "acidity",
        my: "acidity",
        km: "acidity",
      },
      furigana: [
        {
          rb: "酸性",
          rt: "さんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "酸",
          on: ["サン"],
          kun: ["す.い"],
          strokes: 14,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "性",
          on: ["セイ", "ショウ"],
          kun: ["さが"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 160,
      kanji: "酸素",
      reading: "さんそ",
      meanings: {
        ja: "oxygen (O)",
        en: "oxygen (O)",
        zh: "oxygen (O)",
        tw: "oxygen (O)",
        ko: "oxygen (O)",
        vi: "oxygen (O)",
        th: "oxygen (O)",
        my: "oxygen (O)",
        km: "oxygen (O)",
      },
      furigana: [
        {
          rb: "酸素",
          rt: "さんそ",
        },
      ],
      kanjiInfo: [
        {
          char: "酸",
          on: ["サン"],
          kun: ["す.い"],
          strokes: 14,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 161,
      kanji: "詩",
      reading: "し",
      meanings: {
        ja: "poem",
        en: "poem",
        zh: "poem",
        tw: "poem",
        ko: "poem",
        vi: "poem",
        th: "poem",
        my: "poem",
        km: "poem",
      },
      furigana: [
        {
          rb: "詩",
          rt: "し",
        },
      ],
      kanjiInfo: [
        {
          char: "詩",
          on: ["シ"],
          kun: ["うた"],
          strokes: 13,
          grade: 3,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 162,
      kanji: "幸せ",
      reading: "しあわせ",
      meanings: {
        ja: "happiness",
        en: "happiness",
        zh: "happiness",
        tw: "happiness",
        ko: "happiness",
        vi: "happiness",
        th: "happiness",
        my: "happiness",
        km: "happiness",
      },
      furigana: [
        {
          rb: "幸せ",
          rt: "しあわせ",
        },
      ],
      kanjiInfo: [
        {
          char: "幸",
          on: ["コウ"],
          kun: ["さいわ.い", "さち", "しあわ.せ"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 163,
      kanji: "ジーンズ",
      reading: "ジーンズ",
      meanings: {
        ja: "jeans",
        en: "jeans",
        zh: "jeans",
        tw: "jeans",
        ko: "jeans",
        vi: "jeans",
        th: "jeans",
        my: "jeans",
        km: "jeans",
      },
      furigana: [
        {
          rb: "ジーンズ",
          rt: "ジーンズ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 164,
      kanji: "ジェット機",
      reading: "ジェットき",
      meanings: {
        ja: "jet aeroplane",
        en: "jet aeroplane",
        zh: "jet aeroplane",
        tw: "jet aeroplane",
        ko: "jet aeroplane",
        vi: "jet aeroplane",
        th: "jet aeroplane",
        my: "jet aeroplane",
        km: "jet aeroplane",
      },
      furigana: [
        {
          rb: "ジェット機",
          rt: "じぇっとき",
        },
      ],
      kanjiInfo: [
        {
          char: "機",
          on: ["キ"],
          kun: ["はた"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 165,
      kanji: "四季",
      reading: "しき",
      meanings: {
        ja: "the four seasons",
        en: "the four seasons",
        zh: "the four seasons",
        tw: "the four seasons",
        ko: "the four seasons",
        vi: "the four seasons",
        th: "the four seasons",
        my: "the four seasons",
        km: "the four seasons",
      },
      furigana: [
        {
          rb: "四季",
          rt: "しき",
        },
      ],
      kanjiInfo: [
        {
          char: "四",
          on: ["シ"],
          kun: ["よ", "よ.つ", "よっ.つ", "よん"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "季",
          on: ["キ"],
          kun: [],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 166,
      kanji: "時期",
      reading: "じき",
      meanings: {
        ja: "time",
        en: "time",
        zh: "time",
        tw: "time",
        ko: "time",
        vi: "time",
        th: "time",
        my: "time",
        km: "time",
      },
      furigana: [
        {
          rb: "時期",
          rt: "じき",
        },
      ],
      kanjiInfo: [
        {
          char: "時",
          on: ["ジ"],
          kun: ["とき", "-どき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 167,
      kanji: "支給",
      reading: "しきゅう",
      meanings: {
        ja: "provision",
        en: "provision",
        zh: "provision",
        tw: "provision",
        ko: "provision",
        vi: "provision",
        th: "provision",
        my: "provision",
        km: "provision",
      },
      furigana: [
        {
          rb: "支給",
          rt: "しきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "支",
          on: ["シ"],
          kun: ["ささ.える", "つか.える", "か.う"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "給",
          on: ["キュウ"],
          kun: ["たま.う", "たも.う", "-たま.え"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 168,
      kanji: "刺激",
      reading: "しげき",
      meanings: {
        ja: "stimulus",
        en: "stimulus",
        zh: "stimulus",
        tw: "stimulus",
        ko: "stimulus",
        vi: "stimulus",
        th: "stimulus",
        my: "stimulus",
        km: "stimulus",
      },
      furigana: [
        {
          rb: "刺激",
          rt: "しげき",
        },
      ],
      kanjiInfo: [
        {
          char: "刺",
          on: ["シ"],
          kun: ["さ.す", "さ.さる", "さ.し", "さし", "とげ"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "激",
          on: ["ゲキ"],
          kun: ["はげ.しい"],
          strokes: 16,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 169,
      kanji: "資源",
      reading: "しげん",
      meanings: {
        ja: "resources",
        en: "resources",
        zh: "resources",
        tw: "resources",
        ko: "resources",
        vi: "resources",
        th: "resources",
        my: "resources",
        km: "resources",
      },
      furigana: [
        {
          rb: "資源",
          rt: "しげん",
        },
      ],
      kanjiInfo: [
        {
          char: "資",
          on: ["シ"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "源",
          on: ["ゲン"],
          kun: ["みなもと"],
          strokes: 13,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 170,
      kanji: "事件",
      reading: "じけん",
      meanings: {
        ja: "event",
        en: "event",
        zh: "event",
        tw: "event",
        ko: "event",
        vi: "event",
        th: "event",
        my: "event",
        km: "event",
      },
      furigana: [
        {
          rb: "事件",
          rt: "じけん",
        },
      ],
      kanjiInfo: [
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "件",
          on: ["ケン"],
          kun: ["くだん"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 171,
      kanji: "時刻",
      reading: "じこく",
      meanings: {
        ja: "time",
        en: "time",
        zh: "time",
        tw: "time",
        ko: "time",
        vi: "time",
        th: "time",
        my: "time",
        km: "time",
      },
      furigana: [
        {
          rb: "時刻",
          rt: "じこく",
        },
      ],
      kanjiInfo: [
        {
          char: "時",
          on: ["ジ"],
          kun: ["とき", "-どき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "刻",
          on: ["コク"],
          kun: ["きざ.む", "きざ.み"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 172,
      kanji: "自殺",
      reading: "じさつ",
      meanings: {
        ja: "suicide",
        en: "suicide",
        zh: "suicide",
        tw: "suicide",
        ko: "suicide",
        vi: "suicide",
        th: "suicide",
        my: "suicide",
        km: "suicide",
      },
      furigana: [
        {
          rb: "自殺",
          rt: "じさつ",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "殺",
          on: ["サツ", "サイ", "セツ"],
          kun: ["ころ.す", "-ごろ.し", "そ.ぐ", "あや.める"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 173,
      kanji: "支出",
      reading: "ししゅつ",
      meanings: {
        ja: "expenditure",
        en: "expenditure",
        zh: "expenditure",
        tw: "expenditure",
        ko: "expenditure",
        vi: "expenditure",
        th: "expenditure",
        my: "expenditure",
        km: "expenditure",
      },
      furigana: [
        {
          rb: "支出",
          rt: "ししゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "支",
          on: ["シ"],
          kun: ["ささ.える", "つか.える", "か.う"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 174,
      kanji: "事情",
      reading: "じじょう",
      meanings: {
        ja: "circumstances",
        en: "circumstances",
        zh: "circumstances",
        tw: "circumstances",
        ko: "circumstances",
        vi: "circumstances",
        th: "circumstances",
        my: "circumstances",
        km: "circumstances",
      },
      furigana: [
        {
          rb: "事情",
          rt: "じじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 175,
      kanji: "詩人",
      reading: "しじん",
      meanings: {
        ja: "poet",
        en: "poet",
        zh: "poet",
        tw: "poet",
        ko: "poet",
        vi: "poet",
        th: "poet",
        my: "poet",
        km: "poet",
      },
      furigana: [
        {
          rb: "詩人",
          rt: "しじん",
        },
      ],
      kanjiInfo: [
        {
          char: "詩",
          on: ["シ"],
          kun: ["うた"],
          strokes: 13,
          grade: 3,
          jlpt: 1,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 176,
      kanji: "自身",
      reading: "じしん",
      meanings: {
        ja: "(one's) self",
        en: "(one's) self",
        zh: "(one's) self",
        tw: "(one's) self",
        ko: "(one's) self",
        vi: "(one's) self",
        th: "(one's) self",
        my: "(one's) self",
        km: "(one's) self",
      },
      furigana: [
        {
          rb: "自身",
          rt: "じしん",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "身",
          on: ["シン"],
          kun: ["み"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 177,
      kanji: "自然",
      reading: "しぜん",
      meanings: {
        ja: "nature",
        en: "nature",
        zh: "nature",
        tw: "nature",
        ko: "nature",
        vi: "nature",
        th: "nature",
        my: "nature",
        km: "nature",
      },
      furigana: [
        {
          rb: "自然",
          rt: "しぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "然",
          on: ["ゼン", "ネン"],
          kun: ["しか", "しか.り", "しか.し", "さ"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 178,
      kanji: "思想",
      reading: "しそう",
      meanings: {
        ja: "thought",
        en: "thought",
        zh: "thought",
        tw: "thought",
        ko: "thought",
        vi: "thought",
        th: "thought",
        my: "thought",
        km: "thought",
      },
      furigana: [
        {
          rb: "思想",
          rt: "しそう",
        },
      ],
      kanjiInfo: [
        {
          char: "思",
          on: ["シ"],
          kun: ["おも.う", "おもえら.く", "おぼ.す"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "想",
          on: ["ソウ", "ソ"],
          kun: ["おも.う"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 179,
      kanji: "舌",
      reading: "した",
      meanings: {
        ja: "tongue",
        en: "tongue",
        zh: "tongue",
        tw: "tongue",
        ko: "tongue",
        vi: "tongue",
        th: "tongue",
        my: "tongue",
        km: "tongue",
      },
      furigana: [
        {
          rb: "舌",
          rt: "した",
        },
      ],
      kanjiInfo: [
        {
          char: "舌",
          on: ["ゼツ"],
          kun: ["した"],
          strokes: 6,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 180,
      kanji: "質",
      reading: "しつ",
      meanings: {
        ja: "quality",
        en: "quality",
        zh: "quality",
        tw: "quality",
        ko: "quality",
        vi: "quality",
        th: "quality",
        my: "quality",
        km: "quality",
      },
      furigana: [
        {
          rb: "質",
          rt: "しつ",
        },
      ],
      kanjiInfo: [
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 181,
      kanji: "失業",
      reading: "しつぎょう",
      meanings: {
        ja: "unemployment",
        en: "unemployment",
        zh: "unemployment",
        tw: "unemployment",
        ko: "unemployment",
        vi: "unemployment",
        th: "unemployment",
        my: "unemployment",
        km: "unemployment",
      },
      furigana: [
        {
          rb: "失業",
          rt: "しつぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "失",
          on: ["シツ"],
          kun: ["うしな.う", "う.せる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 182,
      kanji: "湿気",
      reading: "しっけ",
      meanings: {
        ja: "moisture",
        en: "moisture",
        zh: "moisture",
        tw: "moisture",
        ko: "moisture",
        vi: "moisture",
        th: "moisture",
        my: "moisture",
        km: "moisture",
      },
      furigana: [
        {
          rb: "湿気",
          rt: "しっけ",
        },
      ],
      kanjiInfo: [
        {
          char: "湿",
          on: ["シツ", "シュウ"],
          kun: ["しめ.る", "しめ.す", "うるお.う", "うるお.す"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 183,
      kanji: "実験",
      reading: "じっけん",
      meanings: {
        ja: "experiment",
        en: "experiment",
        zh: "experiment",
        tw: "experiment",
        ko: "experiment",
        vi: "experiment",
        th: "experiment",
        my: "experiment",
        km: "experiment",
      },
      furigana: [
        {
          rb: "実験",
          rt: "じっけん",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "験",
          on: ["ケン", "ゲン"],
          kun: ["あかし", "しるし", "ため.す", "ためし"],
          strokes: 18,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 184,
      kanji: "実現",
      reading: "じつげん",
      meanings: {
        ja: "implementation (e.g. of a system)",
        en: "implementation (e.g. of a system)",
        zh: "implementation (e.g. of a system)",
        tw: "implementation (e.g. of a system)",
        ko: "implementation (e.g. of a system)",
        vi: "implementation (e.g. of a system)",
        th: "implementation (e.g. of a system)",
        my: "implementation (e.g. of a system)",
        km: "implementation (e.g. of a system)",
      },
      furigana: [
        {
          rb: "実現",
          rt: "じつげん",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 185,
      kanji: "実行",
      reading: "じっこう",
      meanings: {
        ja: "execution (e.g. of a plan)",
        en: "execution (e.g. of a plan)",
        zh: "execution (e.g. of a plan)",
        tw: "execution (e.g. of a plan)",
        ko: "execution (e.g. of a plan)",
        vi: "execution (e.g. of a plan)",
        th: "execution (e.g. of a plan)",
        my: "execution (e.g. of a plan)",
        km: "execution (e.g. of a plan)",
      },
      furigana: [
        {
          rb: "実行",
          rt: "じっこう",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 186,
      kanji: "実際",
      reading: "じっさい",
      meanings: {
        ja: "reality",
        en: "reality",
        zh: "reality",
        tw: "reality",
        ko: "reality",
        vi: "reality",
        th: "reality",
        my: "reality",
        km: "reality",
      },
      furigana: [
        {
          rb: "実際",
          rt: "じっさい",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "際",
          on: ["サイ"],
          kun: ["きわ", "-ぎわ"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 187,
      kanji: "実施",
      reading: "じっし",
      meanings: {
        ja: "enforcement",
        en: "enforcement",
        zh: "enforcement",
        tw: "enforcement",
        ko: "enforcement",
        vi: "enforcement",
        th: "enforcement",
        my: "enforcement",
        km: "enforcement",
      },
      furigana: [
        {
          rb: "実施",
          rt: "じっし",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "施",
          on: ["シ", "セ"],
          kun: ["ほどこ.す"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 188,
      kanji: "湿度",
      reading: "しつど",
      meanings: {
        ja: "humidity",
        en: "humidity",
        zh: "humidity",
        tw: "humidity",
        ko: "humidity",
        vi: "humidity",
        th: "humidity",
        my: "humidity",
        km: "humidity",
      },
      furigana: [
        {
          rb: "湿度",
          rt: "しつど",
        },
      ],
      kanjiInfo: [
        {
          char: "湿",
          on: ["シツ", "シュウ"],
          kun: ["しめ.る", "しめ.す", "うるお.う", "うるお.す"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "度",
          on: ["ド", "ト", "タク"],
          kun: ["たび", "-た.い"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 189,
      kanji: "失望",
      reading: "しつぼう",
      meanings: {
        ja: "disappointment",
        en: "disappointment",
        zh: "disappointment",
        tw: "disappointment",
        ko: "disappointment",
        vi: "disappointment",
        th: "disappointment",
        my: "disappointment",
        km: "disappointment",
      },
      furigana: [
        {
          rb: "失望",
          rt: "しつぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "失",
          on: ["シツ"],
          kun: ["うしな.う", "う.せる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "望",
          on: ["ボウ", "モウ"],
          kun: ["のぞ.む", "もち"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 190,
      kanji: "実力",
      reading: "じつりょく",
      meanings: {
        ja: "(real) ability",
        en: "(real) ability",
        zh: "(real) ability",
        tw: "(real) ability",
        ko: "(real) ability",
        vi: "(real) ability",
        th: "(real) ability",
        my: "(real) ability",
        km: "(real) ability",
      },
      furigana: [
        {
          rb: "実力",
          rt: "じつりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 191,
      kanji: "支店",
      reading: "してん",
      meanings: {
        ja: "branch office",
        en: "branch office",
        zh: "branch office",
        tw: "branch office",
        ko: "branch office",
        vi: "branch office",
        th: "branch office",
        my: "branch office",
        km: "branch office",
      },
      furigana: [
        {
          rb: "支店",
          rt: "してん",
        },
      ],
      kanjiInfo: [
        {
          char: "支",
          on: ["シ"],
          kun: ["ささ.える", "つか.える", "か.う"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "店",
          on: ["テン"],
          kun: ["みせ", "たな"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 192,
      kanji: "指導",
      reading: "しどう",
      meanings: {
        ja: "guidance",
        en: "guidance",
        zh: "guidance",
        tw: "guidance",
        ko: "guidance",
        vi: "guidance",
        th: "guidance",
        my: "guidance",
        km: "guidance",
      },
      furigana: [
        {
          rb: "指導",
          rt: "しどう",
        },
      ],
      kanjiInfo: [
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "導",
          on: ["ドウ"],
          kun: ["みちび.く"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 193,
      kanji: "児童",
      reading: "じどう",
      meanings: {
        ja: "children",
        en: "children",
        zh: "children",
        tw: "children",
        ko: "children",
        vi: "children",
        th: "children",
        my: "children",
        km: "children",
      },
      furigana: [
        {
          rb: "児童",
          rt: "じどう",
        },
      ],
      kanjiInfo: [
        {
          char: "児",
          on: ["ジ", "ニ", "ゲイ"],
          kun: ["こ", "-こ", "-っこ"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "童",
          on: ["ドウ"],
          kun: ["わらべ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 194,
      kanji: "品",
      reading: "しな",
      meanings: {
        ja: "article",
        en: "article",
        zh: "article",
        tw: "article",
        ko: "article",
        vi: "article",
        th: "article",
        my: "article",
        km: "article",
      },
      furigana: [
        {
          rb: "品",
          rt: "しな",
        },
      ],
      kanjiInfo: [
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 195,
      kanji: "支配",
      reading: "しはい",
      meanings: {
        ja: "rule",
        en: "rule",
        zh: "rule",
        tw: "rule",
        ko: "rule",
        vi: "rule",
        th: "rule",
        my: "rule",
        km: "rule",
      },
      furigana: [
        {
          rb: "支配",
          rt: "しはい",
        },
      ],
      kanjiInfo: [
        {
          char: "支",
          on: ["シ"],
          kun: ["ささ.える", "つか.える", "か.う"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "配",
          on: ["ハイ"],
          kun: ["くば.る"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 196,
      kanji: "芝居",
      reading: "しばい",
      meanings: {
        ja: "play",
        en: "play",
        zh: "play",
        tw: "play",
        ko: "play",
        vi: "play",
        th: "play",
        my: "play",
        km: "play",
      },
      furigana: [
        {
          rb: "芝居",
          rt: "しばい",
        },
      ],
      kanjiInfo: [
        {
          char: "芝",
          on: ["シ"],
          kun: ["しば"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "居",
          on: ["キョ", "コ"],
          kun: ["い.る", "-い", "お.る"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 197,
      kanji: "芝生",
      reading: "しばふ",
      meanings: {
        ja: "lawn",
        en: "lawn",
        zh: "lawn",
        tw: "lawn",
        ko: "lawn",
        vi: "lawn",
        th: "lawn",
        my: "lawn",
        km: "lawn",
      },
      furigana: [
        {
          rb: "芝生",
          rt: "しばふ",
        },
      ],
      kanjiInfo: [
        {
          char: "芝",
          on: ["シ"],
          kun: ["しば"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 198,
      kanji: "支払",
      reading: "しはらい",
      meanings: {
        ja: "payment",
        en: "payment",
        zh: "payment",
        tw: "payment",
        ko: "payment",
        vi: "payment",
        th: "payment",
        my: "payment",
        km: "payment",
      },
      furigana: [
        {
          rb: "支払",
          rt: "しはらい",
        },
      ],
      kanjiInfo: [
        {
          char: "支",
          on: ["シ"],
          kun: ["ささ.える", "つか.える", "か.う"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "払",
          on: ["フツ", "ヒツ", "ホツ"],
          kun: ["はら.う", "-はら.い", "-ばら.い"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 199,
      kanji: "死亡",
      reading: "しぼう",
      meanings: {
        ja: "death",
        en: "death",
        zh: "death",
        tw: "death",
        ko: "death",
        vi: "death",
        th: "death",
        my: "death",
        km: "death",
      },
      furigana: [
        {
          rb: "死亡",
          rt: "しぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "死",
          on: ["シ"],
          kun: ["し.ぬ", "し.に-"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "亡",
          on: ["ボウ", "モウ"],
          kun: ["な.い", "な.き-", "ほろ.びる", "ほろ.ぶ", "ほろ.ぼす"],
          strokes: 3,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 200,
      kanji: "資本",
      reading: "しほん",
      meanings: {
        ja: "funds",
        en: "funds",
        zh: "funds",
        tw: "funds",
        ko: "funds",
        vi: "funds",
        th: "funds",
        my: "funds",
        km: "funds",
      },
      furigana: [
        {
          rb: "資本",
          rt: "しほん",
        },
      ],
      kanjiInfo: [
        {
          char: "資",
          on: ["シ"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
