export const n3part30 = {
  Lesson30: [
    {
      id: 1716,
      kanji: "掻く",
      reading: "かく",
      meanings: {
        ja: "掻く",
        en: "to scratch",
        zh: "抓；搔",
        tw: "抓；搔",
        ko: "긁다",
        vi: "gãi",
        th: "เกา",
        my: "အဖုချဉ်း",
        km: "ខូស",
      },
      furigana: [
        {
          rb: "掻く",
          rt: "かく",
        },
      ],
      kanjiInfo: [
        {
          char: "掻",
          on: ["ソウ"],
          kun: ["か.く"],
          strokes: 11,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1717,
      kanji: "描く",
      reading: "かく",
      meanings: {
        ja: "描く",
        en: "to draw; depict",
        zh: "描绘",
        tw: "描繪",
        ko: "그리다",
        vi: "vẽ; miêu tả",
        th: "วาด; พรรณนา",
        my: "ရေးဆွဲ",
        km: "គូរ",
      },
      furigana: [
        {
          rb: "描く",
          rt: "かく",
        },
      ],
      kanjiInfo: [
        {
          char: "描",
          on: ["ビョウ"],
          kun: ["えが.く", "か.く"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1718,
      kanji: "嗅ぐ",
      reading: "かぐ",
      meanings: {
        ja: "嗅ぐ",
        en: "to sniff; smell",
        zh: "闻",
        tw: "聞",
        ko: "냄새 맡다",
        vi: "ngửi",
        th: "ดม",
        my: "နံ့ဝေ့",
        km: "ដកដង្ហើមដកក្លិន",
      },
      furigana: [
        {
          rb: "嗅ぐ",
          rt: "かぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "嗅",
          on: ["キュウ"],
          kun: ["か.ぐ"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1719,
      kanji: "隠す",
      reading: "かくす",
      meanings: {
        ja: "隠す",
        en: "to hide",
        zh: "隐藏",
        tw: "隱藏",
        ko: "숨기다",
        vi: "che giấu",
        th: "ซ่อน",
        my: "ဖုံးကွယ်",
        km: "លាក់",
      },
      furigana: [
        {
          rb: "隠す",
          rt: "かくす",
        },
      ],
      kanjiInfo: [
        {
          char: "隠",
          on: ["イン", "オン"],
          kun: ["かく.す", "かく.し", "かく.れる", "よ.る"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1720,
      kanji: "隠れる",
      reading: "かくれる",
      meanings: {
        ja: "隠れる",
        en: "to hide oneself",
        zh: "躲藏",
        tw: "躲藏",
        ko: "숨다",
        vi: "ẩn náu",
        th: "ซ่อนตัว",
        my: "ဖုံးလွှမ်း",
        km: "លាក់ខ្លួន",
      },
      furigana: [
        {
          rb: "隠れる",
          rt: "かくれる",
        },
      ],
      kanjiInfo: [
        {
          char: "隠",
          on: ["イン", "オン"],
          kun: ["かく.す", "かく.し", "かく.れる", "よ.る"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1721,
      kanji: "欠ける",
      reading: "かける",
      meanings: {
        ja: "欠ける",
        en: "to chip; be lacking",
        zh: "缺损；欠缺",
        tw: "缺損；欠缺",
        ko: "깨지다; 부족하다",
        vi: "mẻ; thiếu",
        th: "บิ่น; ขาด",
        my: "ပေါက်စေ",
        km: "បាក់; ខ្វះ",
      },
      furigana: [
        {
          rb: "欠ける",
          rt: "かける",
        },
      ],
      kanjiInfo: [
        {
          char: "欠",
          on: ["ケツ", "ケン"],
          kun: ["か.ける", "か.く"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1722,
      kanji: "囲む",
      reading: "かこむ",
      meanings: {
        ja: "囲む",
        en: "to surround",
        zh: "围绕",
        tw: "圍繞",
        ko: "둘러싸다",
        vi: "bao quanh",
        th: "ล้อมรอบ",
        my: "ဝိုင်း",
        km: "ព័ទ្ធជុំវិញ",
      },
      furigana: [
        {
          rb: "囲む",
          rt: "かこむ",
        },
      ],
      kanjiInfo: [
        {
          char: "囲",
          on: ["イ"],
          kun: ["かこ.む", "かこ.う", "かこ.い"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1723,
      kanji: "重なる",
      reading: "かさなる",
      meanings: {
        ja: "重なる",
        en: "to be piled up",
        zh: "重叠",
        tw: "重疊",
        ko: "겹치다",
        vi: "chồng chất",
        th: "ซ้อนกัน",
        my: "အထပ်ထပ်တူတူ",
        km: "ជាន់គ្នា",
      },
      furigana: [
        {
          rb: "重なる",
          rt: "かさなる",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1724,
      kanji: "重ねる",
      reading: "かさねる",
      meanings: {
        ja: "重ねる",
        en: "to pile up; repeat",
        zh: "堆叠；重复",
        tw: "堆疊；重複",
        ko: "포개다; 거듭하다",
        vi: "chồng lên; lặp lại",
        th: "ซ้อน; ทำซ้ำ",
        my: "ထပ်၍တိုး",
        km: "ដាក់ជាន់; ធ្វើម្ដងទៀត",
      },
      furigana: [
        {
          rb: "重ねる",
          rt: "かさねる",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1725,
      kanji: "稼ぐ",
      reading: "かせぐ",
      meanings: {
        ja: "稼ぐ",
        en: "to earn (income)",
        zh: "赚钱",
        tw: "賺錢",
        ko: "벌다",
        vi: "kiếm tiền",
        th: "หาเงิน",
        my: "ငွေရှာ",
        km: "រកប្រាក់",
      },
      furigana: [
        {
          rb: "稼ぐ",
          rt: "かせぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "稼",
          on: ["カ"],
          kun: ["かせ.ぐ"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1726,
      kanji: "数える",
      reading: "かぞえる",
      meanings: {
        ja: "数える",
        en: "to count",
        zh: "数数",
        tw: "數數",
        ko: "세다",
        vi: "đếm",
        th: "นับ",
        my: "ရေတွက်",
        km: "រាប់",
      },
      furigana: [
        {
          rb: "数える",
          rt: "かぞえる",
        },
      ],
      kanjiInfo: [
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1727,
      kanji: "片付く",
      reading: "かたづく",
      meanings: {
        ja: "片付く",
        en: "to be put in order; be settled",
        zh: "整理好",
        tw: "整理好",
        ko: "정리되다",
        vi: "được dọn dẹp",
        th: "เรียบร้อย",
        my: "စနစ်တကျဖြစ်",
        km: "រៀបចំរួច",
      },
      furigana: [
        {
          rb: "片付く",
          rt: "かたづく",
        },
      ],
      kanjiInfo: [
        {
          char: "片",
          on: ["ヘン"],
          kun: ["かた-", "かた"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1728,
      kanji: "語る",
      reading: "かたる",
      meanings: {
        ja: "語る",
        en: "to talk about",
        zh: "讲述",
        tw: "講述",
        ko: "이야기하다",
        vi: "kể chuyện",
        th: "เล่าเรื่อง",
        my: "အကြောင်းပြော",
        km: "និយាយអំពី",
      },
      furigana: [
        {
          rb: "語る",
          rt: "かたる",
        },
      ],
      kanjiInfo: [
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1729,
      kanji: "がっかり",
      reading: "がっかり",
      meanings: {
        ja: "がっかり",
        en: "to be disappointed",
        zh: "失望",
        tw: "失望",
        ko: "실망하다",
        vi: "thất vọng",
        th: "ผิดหวัง",
        my: "နှাশကြ",
        km: "ខកចិត្ត",
      },
      furigana: [
        {
          rb: "がっかり",
          rt: "がっかり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1730,
      kanji: "悲しむ",
      reading: "かなしむ",
      meanings: {
        ja: "悲しむ",
        en: "to be sad",
        zh: "悲伤",
        tw: "悲傷",
        ko: "슬퍼하다",
        vi: "buồn",
        th: "เสียใจ",
        my: "စိတ်မကောင်း",
        km: "ព្រួយចិត្ត",
      },
      furigana: [
        {
          rb: "悲しむ",
          rt: "かなしむ",
        },
      ],
      kanjiInfo: [
        {
          char: "悲",
          on: ["ヒ"],
          kun: ["かな.しい", "かな.しむ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1731,
      kanji: "被る",
      reading: "かぶる",
      meanings: {
        ja: "被る",
        en: "to put on (one's head)",
        zh: "戴（帽子等）",
        tw: "戴（帽子等）",
        ko: "쓰다",
        vi: "đội (mũ)",
        th: "สวม (หมวก)",
        my: "ခေါင်းစွပ်",
        km: "ពាក់ (មួក)",
      },
      furigana: [
        {
          rb: "被る",
          rt: "かぶる",
        },
      ],
      kanjiInfo: [
        {
          char: "被",
          on: ["ヒ"],
          kun: ["こうむ.る", "おお.う", "かぶ.る", "かぶ.せる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1732,
      kanji: "刈る",
      reading: "かる",
      meanings: {
        ja: "刈る",
        en: "to cut (grass)",
        zh: "割草",
        tw: "割草",
        ko: "풀을 베다",
        vi: "cắt cỏ",
        th: "ตัดหญ้า",
        my: "မြက်ထွန်",
        km: "កាប់ស្មៅ",
      },
      furigana: [
        {
          rb: "刈る",
          rt: "かる",
        },
      ],
      kanjiInfo: [
        {
          char: "刈",
          on: ["ガイ", "カイ"],
          kun: ["か.る"],
          strokes: 4,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1733,
      kanji: "乾かす",
      reading: "かわかす",
      meanings: {
        ja: "乾かす",
        en: "to dry (clothes, etc.)",
        zh: "晾干",
        tw: "晾乾",
        ko: "말리다",
        vi: "phơi khô",
        th: "ตากให้แห้ง",
        my: "အဝတ်များခြောက်စေ",
        km: "សម្ងួត",
      },
      furigana: [
        {
          rb: "乾かす",
          rt: "かわかす",
        },
      ],
      kanjiInfo: [
        {
          char: "乾",
          on: ["カン", "ケン"],
          kun: ["かわ.く", "かわ.かす", "ほ.す", "ひ.る", "いぬい"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1734,
      kanji: "渇く",
      reading: "かわく",
      meanings: {
        ja: "渇く",
        en: "to be thirsty",
        zh: "口渴",
        tw: "口渴",
        ko: "목마르다",
        vi: "khát nước",
        th: "กระหายน้ำ",
        my: "ငတ်တယ်",
        km: "ស្រេកទឹក",
      },
      furigana: [
        {
          rb: "渇く",
          rt: "かわく",
        },
      ],
      kanjiInfo: [
        {
          char: "渇",
          on: ["カツ"],
          kun: ["かわ.く"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1735,
      kanji: "代る",
      reading: "かわる",
      meanings: {
        ja: "代る",
        en: "to succeed; substitute",
        zh: "代替；接替",
        tw: "代替；接替",
        ko: "대신하다; 계승하다",
        vi: "thay thế; kế tục",
        th: "แทนที่",
        my: "အစားထိုး",
        km: "ជំនួស; ស្នង",
      },
      furigana: [
        {
          rb: "代る",
          rt: "かわる",
        },
      ],
      kanjiInfo: [
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1736,
      kanji: "感じる",
      reading: "かんじる",
      meanings: {
        ja: "感じる",
        en: "to feel",
        zh: "感觉",
        tw: "感覺",
        ko: "느끼다",
        vi: "cảm thấy",
        th: "รู้สึก",
        my: "ခံစား",
        km: "មានអារម្មណ៍",
      },
      furigana: [
        {
          rb: "感じる",
          rt: "かんじる",
        },
      ],
      kanjiInfo: [
        {
          char: "感",
          on: ["カン"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1737,
      kanji: "関する",
      reading: "かんする",
      meanings: {
        ja: "関する",
        en: "to concern; relate to",
        zh: "关于",
        tw: "關於",
        ko: "관하다",
        vi: "liên quan đến",
        th: "เกี่ยวกับ",
        my: "ဆိုင်သော",
        km: "ទាក់ទង",
      },
      furigana: [
        {
          rb: "関する",
          rt: "かんする",
        },
      ],
      kanjiInfo: [
        {
          char: "関",
          on: ["カン"],
          kun: ["せき", "-ぜき", "かか.わる", "からくり", "かんぬき"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1738,
      kanji: "効く",
      reading: "きく",
      meanings: {
        ja: "効く",
        en: "to be effective",
        zh: "有效",
        tw: "有效",
        ko: "효과가 있다",
        vi: "có hiệu quả",
        th: "ได้ผล",
        my: "အကျိုးရှိ",
        km: "មានប្រសិទ្ធភាព",
      },
      furigana: [
        {
          rb: "効く",
          rt: "きく",
        },
      ],
      kanjiInfo: [
        {
          char: "効",
          on: ["コウ"],
          kun: ["き.く", "ききめ", "なら.う"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1739,
      kanji: "気付く",
      reading: "きづく",
      meanings: {
        ja: "気付く",
        en: "to notice; realize",
        zh: "注意到；察觉",
        tw: "注意到；察覺",
        ko: "깨닫다",
        vi: "nhận ra",
        th: "สังเกตเห็น",
        my: "သတိထားမိ",
        km: "យល់ឃើញ",
      },
      furigana: [
        {
          rb: "気付く",
          rt: "きづく",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1740,
      kanji: "嫌う",
      reading: "きらう",
      meanings: {
        ja: "嫌う",
        en: "to hate; dislike",
        zh: "讨厌",
        tw: "討厭",
        ko: "싫어하다",
        vi: "ghét",
        th: "เกลียด",
        my: "မုန်းတီး",
        km: "ស្អប់",
      },
      furigana: [
        {
          rb: "嫌う",
          rt: "きらう",
        },
      ],
      kanjiInfo: [
        {
          char: "嫌",
          on: ["ケン", "ゲン"],
          kun: ["きら.う", "きら.い", "いや"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1741,
      kanji: "切れる",
      reading: "きれる",
      meanings: {
        ja: "切れる",
        en: "to break; snap; be sharp",
        zh: "断开；锋利",
        tw: "斷開；鋒利",
        ko: "끊어지다; 날카롭다",
        vi: "bị đứt; sắc bén",
        th: "ขาด; คม",
        my: "ဖြတ်တောက်",
        km: "ខូច; មុត",
      },
      furigana: [
        {
          rb: "切れる",
          rt: "きれる",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1742,
      kanji: "食う",
      reading: "くう",
      meanings: {
        ja: "食う",
        en: "to eat",
        zh: "吃",
        tw: "吃",
        ko: "먹다",
        vi: "ăn",
        th: "กิน",
        my: "စားသည်",
        km: "ញ៉ាំ",
      },
      furigana: [
        {
          rb: "食う",
          rt: "くう",
        },
      ],
      kanjiInfo: [
        {
          char: "食",
          on: ["ショク", "ジキ"],
          kun: ["く.う", "く.らう", "た.べる", "は.む"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1743,
      kanji: "腐る",
      reading: "くさる",
      meanings: {
        ja: "腐る",
        en: "to rot",
        zh: "腐烂",
        tw: "腐爛",
        ko: "썩다",
        vi: "thối rữa",
        th: "เน่า",
        my: "ပုပ်",
        km: "ខូច",
      },
      furigana: [
        {
          rb: "腐る",
          rt: "くさる",
        },
      ],
      kanjiInfo: [
        {
          char: "腐",
          on: ["フ"],
          kun: [
            "くさ.る",
            "-くさ.る",
            "くさ.れる",
            "くさ.れ",
            "くさ.らす",
            "くさ.す",
          ],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1744,
      kanji: "下る",
      reading: "くだる",
      meanings: {
        ja: "下る",
        en: "to descend",
        zh: "下降",
        tw: "下降",
        ko: "내려가다",
        vi: "xuống",
        th: "ลง",
        my: "ဆင်း",
        km: "ចុះ",
      },
      furigana: [
        {
          rb: "下る",
          rt: "くだる",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1745,
      kanji: "組む",
      reading: "くむ",
      meanings: {
        ja: "組む",
        en: "to cross; to pair up",
        zh: "交叉；搭配",
        tw: "交叉；搭配",
        ko: "짜다; 짝짓다",
        vi: "ghép; phối hợp",
        th: "ไขว้; จับคู่",
        my: "ချိတ်ဆက်",
        km: "ភ្ជាប់",
      },
      furigana: [
        {
          rb: "組む",
          rt: "くむ",
        },
      ],
      kanjiInfo: [
        {
          char: "組",
          on: ["ソ"],
          kun: ["く.む", "くみ", "-ぐみ"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1746,
      kanji: "汲む",
      reading: "くむ",
      meanings: {
        ja: "汲む",
        en: "to draw (water)",
        zh: "汲水",
        tw: "汲水",
        ko: "물을 긷다",
        vi: "múc (nước)",
        th: "ตักน้ำ",
        my: "ရေထုတ်",
        km: "ច្រាស់ទឹក",
      },
      furigana: [
        {
          rb: "汲む",
          rt: "くむ",
        },
      ],
      kanjiInfo: [
        {
          char: "汲",
          on: ["キュウ"],
          kun: ["く.む"],
          strokes: 7,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1747,
      kanji: "酌む",
      reading: "くむ",
      meanings: {
        ja: "酌む",
        en: "to pour (sake)",
        zh: "斟酒",
        tw: "斟酒",
        ko: "술을 따르다",
        vi: "rót rượu",
        th: "รินเหล้า",
        my: "ရေစဉ်း",
        km: "ចាក់ទឹកស្រា",
      },
      furigana: [
        {
          rb: "酌む",
          rt: "くむ",
        },
      ],
      kanjiInfo: [
        {
          char: "酌",
          on: ["シャク"],
          kun: ["く.む"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1748,
      kanji: "暮らす",
      reading: "くらす",
      meanings: {
        ja: "暮らす",
        en: "to live",
        zh: "生活",
        tw: "生活",
        ko: "살다",
        vi: "sống",
        th: "ใช้ชีวิต",
        my: "ဘဝဖြတ်သန်း",
        km: "រស់នៅ",
      },
      furigana: [
        {
          rb: "暮らす",
          rt: "くらす",
        },
      ],
      kanjiInfo: [
        {
          char: "暮",
          on: ["ボ"],
          kun: ["く.れる", "く.らす"],
          strokes: 14,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1749,
      kanji: "繰り返す",
      reading: "くりかえす",
      meanings: {
        ja: "繰り返す",
        en: "to repeat",
        zh: "重复",
        tw: "重複",
        ko: "되풀이하다",
        vi: "lặp lại",
        th: "ทำซ้ำ",
        my: "ထပ်ခါထပ်ခါလုပ်",
        km: "ធ្វើម្ដងទៀត",
      },
      furigana: [
        {
          rb: "繰り返す",
          rt: "くりかえす",
        },
      ],
      kanjiInfo: [
        {
          char: "繰",
          on: ["ソウ"],
          kun: ["く.る"],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "返",
          on: ["ヘン"],
          kun: ["かえ.す", "-かえ.す", "かえ.る", "-かえ.る"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1750,
      kanji: "狂う",
      reading: "くるう",
      meanings: {
        ja: "狂う",
        en: "to go mad",
        zh: "发狂",
        tw: "發狂",
        ko: "미치다",
        vi: "phát điên",
        th: "บ้า",
        my: "မူးမိုက်",
        km: "ឆ្កួត",
      },
      furigana: [
        {
          rb: "狂う",
          rt: "くるう",
        },
      ],
      kanjiInfo: [
        {
          char: "狂",
          on: ["キョウ"],
          kun: ["くる.う", "くる.おしい", "くるお.しい"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1751,
      kanji: "苦しむ",
      reading: "くるしむ",
      meanings: {
        ja: "苦しむ",
        en: "to suffer",
        zh: "痛苦",
        tw: "痛苦",
        ko: "고통받다",
        vi: "chịu đựng",
        th: "ทนทุกข์",
        my: "စွမ်းဆောင်နေရသည်",
        km: "ទទួលទោស",
      },
      furigana: [
        {
          rb: "苦しむ",
          rt: "くるしむ",
        },
      ],
      kanjiInfo: [
        {
          char: "苦",
          on: ["ク"],
          kun: [
            "くる.しい",
            "-ぐる.しい",
            "くる.しむ",
            "くる.しめる",
            "にが.い",
            "にが.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1752,
      kanji: "加える",
      reading: "くわえる",
      meanings: {
        ja: "加える",
        en: "to add",
        zh: "增加",
        tw: "增加",
        ko: "더하다",
        vi: "thêm vào",
        th: "เพิ่ม",
        my: "ထပ်ထည့်",
        km: "បន្ថែម",
      },
      furigana: [
        {
          rb: "加える",
          rt: "くわえる",
        },
      ],
      kanjiInfo: [
        {
          char: "加",
          on: ["カ"],
          kun: ["くわ.える", "くわ.わる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1753,
      kanji: "咥える",
      reading: "くわえる",
      meanings: {
        ja: "咥える",
        en: "to hold in one's mouth",
        zh: "叼着",
        tw: "叼著",
        ko: "물다",
        vi: "ngậm",
        th: "คาบไว้",
        my: "အဖျားထား",
        km: "ដាក់ក្នុងមាត់",
      },
      furigana: [
        {
          rb: "咥える",
          rt: "くわえる",
        },
      ],
      kanjiInfo: [
        {
          char: "咥",
          on: ["テツ", "キ"],
          kun: ["か.む", "くわ.える"],
          strokes: 9,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1754,
      kanji: "加わる",
      reading: "くわわる",
      meanings: {
        ja: "加わる",
        en: "to be added to",
        zh: "加入",
        tw: "加入",
        ko: "가담하다",
        vi: "gia nhập",
        th: "เข้าร่วม",
        my: "ပါဝင်",
        km: "ចូលរួម",
      },
      furigana: [
        {
          rb: "加わる",
          rt: "くわわる",
        },
      ],
      kanjiInfo: [
        {
          char: "加",
          on: ["カ"],
          kun: ["くわ.える", "くわ.わる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1755,
      kanji: "蹴る",
      reading: "ける",
      meanings: {
        ja: "蹴る",
        en: "to kick",
        zh: "踢",
        tw: "踢",
        ko: "차다",
        vi: "đá",
        th: "เตะ",
        my: "လက်သီးနဲ့ထိုး",
        km: "ក្បាច់ជើង",
      },
      furigana: [
        {
          rb: "蹴る",
          rt: "ける",
        },
      ],
      kanjiInfo: [
        {
          char: "蹴",
          on: ["シュク", "シュウ"],
          kun: ["け.る"],
          strokes: 19,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1756,
      kanji: "越える",
      reading: "こえる",
      meanings: {
        ja: "越える",
        en: "to cross over",
        zh: "越过",
        tw: "越過",
        ko: "넘다",
        vi: "vượt qua",
        th: "ข้าม",
        my: "ကျော်ဖြတ်",
        km: "ឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "越える",
          rt: "こえる",
        },
      ],
      kanjiInfo: [
        {
          char: "越",
          on: ["エツ", "オツ"],
          kun: ["こ.す", "-こ.す", "-ご.し", "こ.える", "-ご.え"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1757,
      kanji: "超える",
      reading: "こえる",
      meanings: {
        ja: "超える",
        en: "to cross over",
        zh: "超越",
        tw: "超越",
        ko: "넘다",
        vi: "vượt qua",
        th: "ข้าม",
        my: "ကျော်လွန်",
        km: "លើស",
      },
      furigana: [
        {
          rb: "超える",
          rt: "こえる",
        },
      ],
      kanjiInfo: [
        {
          char: "超",
          on: ["チョウ"],
          kun: ["こ.える", "こ.す"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1758,
      kanji: "凍る",
      reading: "こおる",
      meanings: {
        ja: "凍る",
        en: "to freeze",
        zh: "冻结",
        tw: "凍結",
        ko: "얼다",
        vi: "đóng băng",
        th: "กลายเป็นน้ำแข็ง",
        my: "ခဲတယ်",
        km: "កក",
      },
      furigana: [
        {
          rb: "凍る",
          rt: "こおる",
        },
      ],
      kanjiInfo: [
        {
          char: "凍",
          on: ["トウ"],
          kun: ["こお.る", "こご.える", "こご.る", "い.てる", "し.みる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1759,
      kanji: "越す",
      reading: "こす",
      meanings: {
        ja: "越す",
        en: "to cross over (mountain)",
        zh: "越过",
        tw: "越過",
        ko: "넘다",
        vi: "băng qua",
        th: "ข้ามไป",
        my: "ကျော်သွား",
        km: "ឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "越す",
          rt: "こす",
        },
      ],
      kanjiInfo: [
        {
          char: "越",
          on: ["エツ", "オツ"],
          kun: ["こ.す", "-こ.す", "-ご.し", "こ.える", "-ご.え"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1760,
      kanji: "超す",
      reading: "こす",
      meanings: {
        ja: "超す",
        en: "to cross over (mountain)",
        zh: "超越",
        tw: "超越",
        ko: "넘다",
        vi: "vượt qua",
        th: "ข้ามไป",
        my: "ကျော်သွား",
        km: "លើស",
      },
      furigana: [
        {
          rb: "超す",
          rt: "こす",
        },
      ],
      kanjiInfo: [
        {
          char: "超",
          on: ["チョウ"],
          kun: ["こ.える", "こ.す"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1761,
      kanji: "異なる",
      reading: "ことなる",
      meanings: {
        ja: "異なる",
        en: "to differ",
        zh: "不同",
        tw: "不同",
        ko: "다르다",
        vi: "khác nhau",
        th: "แตกต่าง",
        my: "မတူ",
        km: "ខុសគ្នា",
      },
      furigana: [
        {
          rb: "異なる",
          rt: "ことなる",
        },
      ],
      kanjiInfo: [
        {
          char: "異",
          on: ["イ"],
          kun: ["こと", "こと.なる", "け"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1762,
      kanji: "断る",
      reading: "ことわる",
      meanings: {
        ja: "断る",
        en: "to refuse",
        zh: "拒绝",
        tw: "拒絕",
        ko: "거절하다",
        vi: "từ chối",
        th: "ปฏิเสธ",
        my: "ငြင်းပယ်",
        km: "បដិសេធ",
      },
      furigana: [
        {
          rb: "断る",
          rt: "ことわる",
        },
      ],
      kanjiInfo: [
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1763,
      kanji: "好む",
      reading: "このむ",
      meanings: {
        ja: "好む",
        en: "to like",
        zh: "喜欢",
        tw: "喜歡",
        ko: "좋아하다",
        vi: "ưa thích",
        th: "ชอบ",
        my: "ကြိုက်တယ်",
        km: "ចូលចិត្ត",
      },
      furigana: [
        {
          rb: "好む",
          rt: "このむ",
        },
      ],
      kanjiInfo: [
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1764,
      kanji: "殺す",
      reading: "ころす",
      meanings: {
        ja: "殺す",
        en: "to kill",
        zh: "杀",
        tw: "殺",
        ko: "죽이다",
        vi: "giết",
        th: "ฆ่า",
        my: "သတ်",
        km: "សម្លាប់",
      },
      furigana: [
        {
          rb: "殺す",
          rt: "ころす",
        },
      ],
      kanjiInfo: [
        {
          char: "殺",
          on: ["サツ", "サイ", "セツ"],
          kun: ["ころ.す", "-ごろ.し", "そ.ぐ", "あや.める"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1765,
      kanji: "転ぶ",
      reading: "ころぶ",
      meanings: {
        ja: "転ぶ",
        en: "to fall down",
        zh: "跌倒",
        tw: "跌倒",
        ko: "넘어지다",
        vi: "ngã",
        th: "ล้ม",
        my: "လဲကျ",
        km: "ដួល",
      },
      furigana: [
        {
          rb: "転ぶ",
          rt: "ころぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
