export const n3part25 = {
  Lesson25: [
    {
      id: 1441,
      kanji: "様々",
      reading: "さまざま",
      meanings: {
        ja: "様々",
        en: "various",
        zh: "各种各样",
        tw: "各種各樣",
        ko: "여러 가지",
        vi: "đa dạng",
        th: "หลากหลาย",
        my: "အမျိုးမျိုး",
        km: "ផ្សេងៗ",
      },
      furigana: [
        {
          rb: "様々",
          rt: "さまざま",
        },
      ],
      kanjiInfo: [
        {
          char: "様",
          on: ["ヨウ", "ショウ"],
          kun: ["さま", "さん"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1442,
      kanji: "四角",
      reading: "しかく",
      meanings: {
        ja: "四角",
        en: "quadrilateral; square",
        zh: "四角形",
        tw: "四角形",
        ko: "사각형",
        vi: "tứ giác",
        th: "สี่เหลี่ยม",
        my: "စတုဂံ",
        km: "ចតុកោណ",
      },
      furigana: [
        {
          rb: "四角",
          rt: "しかく",
        },
      ],
      kanjiInfo: [
        {
          char: "四",
          on: ["シ"],
          kun: ["よ", "よ.つ", "よっ.つ", "よん"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "角",
          on: ["カク"],
          kun: ["かど", "つの"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1443,
      kanji: "直",
      reading: "じき",
      meanings: {
        ja: "直",
        en: "soon; immediately",
        zh: "马上",
        tw: "馬上",
        ko: "곧",
        vi: "ngay",
        th: "ทันที",
        my: "မကြာမီ",
        km: "ឆាប់ៗ",
      },
      furigana: [
        {
          rb: "直",
          rt: "じき",
        },
      ],
      kanjiInfo: [
        {
          char: "直",
          on: ["チョク", "ジキ", "ジカ"],
          kun: [
            "ただ.ちに",
            "なお.す",
            "-なお.す",
            "なお.る",
            "なお.き",
            "す.ぐ",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1444,
      kanji: "至急",
      reading: "しきゅう",
      meanings: {
        ja: "至急",
        en: "urgent; immediate",
        zh: "火急",
        tw: "火急",
        ko: "지급",
        vi: "khẩn cấp",
        th: "ด่วน",
        my: "အရေးပေါ်",
        km: "បន្ទាន់",
      },
      furigana: [
        {
          rb: "至急",
          rt: "しきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "至",
          on: ["シ"],
          kun: ["いた.る"],
          strokes: 6,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "急",
          on: ["キュウ"],
          kun: ["いそ.ぐ", "いそ.ぎ", "せ.く"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1445,
      kanji: "自動",
      reading: "じどう",
      meanings: {
        ja: "自動",
        en: "automatic",
        zh: "自动",
        tw: "自動",
        ko: "자동",
        vi: "tự động",
        th: "อัตโนมัติ",
        my: "အလိုအလျောက်",
        km: "ស្វ័យប្រវត្តិ",
      },
      furigana: [
        {
          rb: "自動",
          rt: "じどう",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1446,
      kanji: "地味",
      reading: "じみ",
      meanings: {
        ja: "地味",
        en: "plain; subdued",
        zh: "朴素",
        tw: "樸素",
        ko: "수수하다",
        vi: "giản dị",
        th: "เรียบง่าย",
        my: "ရိုးရှင်းသော",
        km: "សាមញ្ញ",
      },
      furigana: [
        {
          rb: "地味",
          rt: "じみ",
        },
      ],
      kanjiInfo: [
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1447,
      kanji: "重大",
      reading: "じゅうだい",
      meanings: {
        ja: "重大",
        en: "serious; important",
        zh: "重大",
        tw: "重大",
        ko: "중대하다",
        vi: "trọng đại",
        th: "ร้ายแรง",
        my: "အလွန်အရေးကြီးသော",
        km: "ធ្ងន់ធ្ងរ",
      },
      furigana: [
        {
          rb: "重大",
          rt: "じゅうだい",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1448,
      kanji: "重要",
      reading: "じゅうよう",
      meanings: {
        ja: "重要",
        en: "important",
        zh: "重要",
        tw: "重要",
        ko: "중요하다",
        vi: "quan trọng",
        th: "สำคัญ",
        my: "အရေးကြီးသော",
        km: "សំខាន់",
      },
      furigana: [
        {
          rb: "重要",
          rt: "じゅうよう",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "要",
          on: ["ヨウ"],
          kun: ["い.る", "かなめ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1449,
      kanji: "主要",
      reading: "しゅよう",
      meanings: {
        ja: "主要",
        en: "chief; principal",
        zh: "主要",
        tw: "主要",
        ko: "주요하다",
        vi: "chủ yếu",
        th: "หลัก",
        my: "အဓိက",
        km: "សំខាន់បំផុត",
      },
      furigana: [
        {
          rb: "主要",
          rt: "しゅよう",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "要",
          on: ["ヨウ"],
          kun: ["い.る", "かなめ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1450,
      kanji: "順調",
      reading: "じゅんちょう",
      meanings: {
        ja: "順調",
        en: "favourable; smooth",
        zh: "顺利",
        tw: "順利",
        ko: "순조롭다",
        vi: "thuận lợi",
        th: "ราบรื่น",
        my: "အဆင်ပြေသော",
        km: "ស្រួលរលូន",
      },
      furigana: [
        {
          rb: "順調",
          rt: "じゅんちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "順",
          on: ["ジュン"],
          kun: [],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "調",
          on: ["チョウ"],
          kun: ["しら.べる", "しら.べ", "ととの.う", "ととの.える"],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1451,
      kanji: "正直",
      reading: "しょうじき",
      meanings: {
        ja: "正直",
        en: "honest",
        zh: "老实",
        tw: "老實",
        ko: "정직하다",
        vi: "thành thật",
        th: "ซื่อสัตย์",
        my: "တိကျမှန်ကန်သော",
        km: "ស្មោះត្រង់",
      },
      furigana: [
        {
          rb: "正直",
          rt: "しょうじき",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "直",
          on: ["チョク", "ジキ", "ジカ"],
          kun: [
            "ただ.ちに",
            "なお.す",
            "-なお.す",
            "なお.る",
            "なお.き",
            "す.ぐ",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1452,
      kanji: "上等",
      reading: "じょうとう",
      meanings: {
        ja: "上等",
        en: "superior; high-class",
        zh: "上等",
        tw: "上等",
        ko: "상등",
        vi: "thượng đẳng",
        th: "ชั้นยอด",
        my: "အဆင့်မြင့်",
        km: "ល្អឥតខ្ចោះ",
      },
      furigana: [
        {
          rb: "上等",
          rt: "じょうとう",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "等",
          on: ["トウ"],
          kun: ["ひと.しい", "など", "-ら"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1453,
      kanji: "真剣",
      reading: "しんけん",
      meanings: {
        ja: "真剣",
        en: "serious; earnest",
        zh: "认真",
        tw: "認真",
        ko: "진지하다",
        vi: "nghiêm túc",
        th: "จริงจัง",
        my: "စိတ်တိုးကြီးသော",
        km: "យកចិត្តទុកដាក់",
      },
      furigana: [
        {
          rb: "真剣",
          rt: "しんけん",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "剣",
          on: ["ケン"],
          kun: ["つるぎ"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1454,
      kanji: "深刻",
      reading: "しんこく",
      meanings: {
        ja: "深刻",
        en: "serious; grave",
        zh: "严重",
        tw: "嚴重",
        ko: "심각하다",
        vi: "nghiêm trọng",
        th: "ร้ายแรง",
        my: "စိုးရိမ်ဖွယ်",
        km: "ធ្ងន់ធ្ងរ",
      },
      furigana: [
        {
          rb: "深刻",
          rt: "しんこく",
        },
      ],
      kanjiInfo: [
        {
          char: "深",
          on: ["シン"],
          kun: ["ふか.い", "-ぶか.い", "ふか.まる", "ふか.める", "み-"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "刻",
          on: ["コク"],
          kun: ["きざ.む", "きざ.み"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1455,
      kanji: "新鮮",
      reading: "しんせん",
      meanings: {
        ja: "新鮮",
        en: "fresh",
        zh: "新鲜",
        tw: "新鮮",
        ko: "신선하다",
        vi: "tươi mới",
        th: "สดใหม่",
        my: "သန့်ရှင်းစွာသော",
        km: "ស្រស់",
      },
      furigana: [
        {
          rb: "新鮮",
          rt: "しんせん",
        },
      ],
      kanjiInfo: [
        {
          char: "新",
          on: ["シン"],
          kun: ["あたら.しい", "あら.た", "あら-", "にい-"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "鮮",
          on: ["セン"],
          kun: ["あざ.やか"],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1456,
      kanji: "慎重",
      reading: "しんちょう",
      meanings: {
        ja: "慎重",
        en: "careful; cautious",
        zh: "慎重",
        tw: "慎重",
        ko: "신중하다",
        vi: "thận trọng",
        th: "ระมัดระวัง",
        my: "အထူးဂရုပြုသော",
        km: "ប្រុងប្រយ័ត្ន",
      },
      furigana: [
        {
          rb: "慎重",
          rt: "しんちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "慎",
          on: ["シン"],
          kun: ["つつし.む", "つつ.ましい", "つつし", "つつし.み"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1457,
      kanji: "正確",
      reading: "せいかく",
      meanings: {
        ja: "正確",
        en: "accurate; correct",
        zh: "正确",
        tw: "正確",
        ko: "정확하다",
        vi: "chính xác",
        th: "ถูกต้อง",
        my: "မှန်ကန်သော",
        km: "ត្រឹមត្រូវ",
      },
      furigana: [
        {
          rb: "正確",
          rt: "せいかく",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "確",
          on: ["カク", "コウ"],
          kun: ["たし.か", "たし.かめる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1458,
      kanji: "清潔",
      reading: "せいけつ",
      meanings: {
        ja: "清潔",
        en: "clean",
        zh: "清洁",
        tw: "清潔",
        ko: "청결하다",
        vi: "sạch sẽ",
        th: "สะอาด",
        my: "သန့်ရှင်းသော",
        km: "ស្អាត",
      },
      furigana: [
        {
          rb: "清潔",
          rt: "せいけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "清",
          on: ["セイ", "ショウ", "シン"],
          kun: ["きよ.い", "きよ.まる", "きよ.める"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "潔",
          on: ["ケツ"],
          kun: ["いさぎよ.い"],
          strokes: 15,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1459,
      kanji: "正式",
      reading: "せいしき",
      meanings: {
        ja: "正式",
        en: "formal; official",
        zh: "正式",
        tw: "正式",
        ko: "정식이다",
        vi: "chính thức",
        th: "เป็นทางการ",
        my: "အတည်ပြုထားသော",
        km: "ផ្លូវការ",
      },
      furigana: [
        {
          rb: "正式",
          rt: "せいしき",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "式",
          on: ["シキ"],
          kun: [],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1460,
      kanji: "積極的",
      reading: "せっきょくてき",
      meanings: {
        ja: "積極的",
        en: "positive; active",
        zh: "积极的",
        tw: "積極的",
        ko: "적극적이다",
        vi: "tích cực",
        th: "เชิงบวก",
        my: "အကျိုးရှိစွာ",
        km: "សកម្ម",
      },
      furigana: [
        {
          rb: "積極的",
          rt: "せっきょくてき",
        },
      ],
      kanjiInfo: [
        {
          char: "積",
          on: ["セキ"],
          kun: ["つ.む", "-づ.み", "つ.もる", "つ.もり"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "極",
          on: ["キョク", "ゴク"],
          kun: [
            "きわ.める",
            "きわ.まる",
            "きわ.まり",
            "きわ.み",
            "き.める",
            "-ぎ.め",
            "き.まる",
          ],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "的",
          on: ["テキ"],
          kun: ["まと"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1461,
      kanji: "明らか",
      reading: "あきらか",
      meanings: {
        ja: "明らか",
        en: "clear; obvious",
        zh: "明显",
        tw: "明顯",
        ko: "분명하다",
        vi: "rõ ràng",
        th: "ชัดเจน",
        my: "ရှင်းလင်းသော",
        km: "ច្បាស់លាស់",
      },
      furigana: [
        {
          rb: "明らか",
          rt: "あきらか",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1462,
      kanji: "当たり前",
      reading: "あたりまえ",
      meanings: {
        ja: "当たり前",
        en: "natural; obvious",
        zh: "理所当然",
        tw: "理所當然",
        ko: "당연하다",
        vi: "đương nhiên",
        th: "เป็นธรรมดา",
        my: "အကျိုးရှိသော",
        km: "ធម្មតា",
      },
      furigana: [
        {
          rb: "当たり前",
          rt: "あたりまえ",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1463,
      kanji: "新た",
      reading: "あらた",
      meanings: {
        ja: "新た",
        en: "new; fresh",
        zh: "新的",
        tw: "新的",
        ko: "새로운",
        vi: "mới mẻ",
        th: "ใหม่",
        my: "အသစ်",
        km: "ថ្មី",
      },
      furigana: [
        {
          rb: "新た",
          rt: "あらた",
        },
      ],
      kanjiInfo: [
        {
          char: "新",
          on: ["シン"],
          kun: ["あたら.しい", "あら.た", "あら-", "にい-"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1464,
      kanji: "意外",
      reading: "いがい",
      meanings: {
        ja: "意外",
        en: "unexpected",
        zh: "意外",
        tw: "意外",
        ko: "의외이다",
        vi: "ngoài dự đoán",
        th: "เกินคาด",
        my: "မျှော်လင့်မထားသော",
        km: "មិនបានគិត",
      },
      furigana: [
        {
          rb: "意外",
          rt: "いがい",
        },
      ],
      kanjiInfo: [
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1465,
      kanji: "異常",
      reading: "いじょう",
      meanings: {
        ja: "異常",
        en: "abnormal; unusual",
        zh: "异常",
        tw: "異常",
        ko: "이상하다",
        vi: "khác thường",
        th: "ผิดปกติ",
        my: "ပုံမှန်မဟုတ်သော",
        km: "ខុសប្រក្រតី",
      },
      furigana: [
        {
          rb: "異常",
          rt: "いじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "異",
          on: ["イ"],
          kun: ["こと", "こと.なる", "け"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "常",
          on: ["ジョウ"],
          kun: ["つね", "とこ-"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1466,
      kanji: "意地悪",
      reading: "いじわる",
      meanings: {
        ja: "意地悪",
        en: "malicious; mean",
        zh: "恶毒",
        tw: "惡毒",
        ko: "심술궂다",
        vi: "xấu bụng",
        th: "ใจร้าย",
        my: "စိတ္မကောင်းဖွယ်",
        km: "អាក្រក់",
      },
      furigana: [
        {
          rb: "意地悪",
          rt: "いじわる",
        },
      ],
      kanjiInfo: [
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "悪",
          on: ["アク", "オ"],
          kun: [
            "わる.い",
            "わる-",
            "あ.し",
            "にく.い",
            "-にく.い",
            "ああ",
            "いずくに",
            "いずくんぞ",
            "にく.む",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1467,
      kanji: "偉大",
      reading: "いだい",
      meanings: {
        ja: "偉大",
        en: "great; mighty",
        zh: "伟大",
        tw: "偉大",
        ko: "위대하다",
        vi: "vĩ đại",
        th: "ยิ่งใหญ่",
        my: "ကြီးမြတ်သော",
        km: "អស្ចារ្យ",
      },
      furigana: [
        {
          rb: "偉大",
          rt: "いだい",
        },
      ],
      kanjiInfo: [
        {
          char: "偉",
          on: ["イ"],
          kun: ["えら.い"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1468,
      kanji: "一般",
      reading: "いっぱん",
      meanings: {
        ja: "一般",
        en: "general; common",
        zh: "一般",
        tw: "一般",
        ko: "일반적이다",
        vi: "thông thường",
        th: "ทั่วไป",
        my: "ယေဘုယျ",
        km: "ទូទៅ",
      },
      furigana: [
        {
          rb: "一般",
          rt: "いっぱん",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "般",
          on: ["ハン"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1469,
      kanji: "お洒落",
      reading: "おしゃれ",
      meanings: {
        ja: "お洒落",
        en: "stylish; fashionable",
        zh: "时髦",
        tw: "時髦",
        ko: "멋지다",
        vi: "thời trang",
        th: "ทันสมัย",
        my: "ဈေးကြီးကျသော",
        km: "សំលៀកបំពាក់ស្អាត",
      },
      furigana: [
        {
          rb: "お洒落",
          rt: "おしゃれ",
        },
      ],
      kanjiInfo: [
        {
          char: "洒",
          on: ["シャ", "ソン", "サイ", "セン", "セイ"],
          kun: ["すす.ぐ", "あら.う"],
          strokes: 9,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
        {
          char: "落",
          on: ["ラク"],
          kun: ["お.ちる", "お.ち", "お.とす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1470,
      kanji: "穏やか",
      reading: "おだやか",
      meanings: {
        ja: "穏やか",
        en: "calm; gentle",
        zh: "温和",
        tw: "溫和",
        ko: "온화하다",
        vi: "êm đềm; hiền lành",
        th: "สงบ; อ่อนโยน",
        my: "ငြိမ်းချမ်းသော",
        km: "ស្ងប់ស្ងាត់",
      },
      furigana: [
        {
          rb: "穏やか",
          rt: "おだやか",
        },
      ],
      kanjiInfo: [
        {
          char: "穏",
          on: ["オン"],
          kun: ["おだ.やか"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1201,
      kanji: "額",
      reading: "ひたい",
      meanings: {
        ja: "額",
        en: "forehead",
        zh: "额头",
        tw: "額頭",
        ko: "이마",
        vi: "trán",
        th: "หน้าผาก",
        my: "နဖူး",
        km: "ថ្ពាល់",
      },
      furigana: [
        {
          rb: "額",
          rt: "ひたい",
        },
      ],
      kanjiInfo: [
        {
          char: "額",
          on: ["ガク"],
          kun: ["ひたい"],
          strokes: 18,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1202,
      kanji: "日付",
      reading: "ひづけ",
      meanings: {
        ja: "日付",
        en: "date",
        zh: "日期",
        tw: "日期",
        ko: "날짜",
        vi: "ngày tháng",
        th: "วันที่",
        my: "ရက်စွဲ",
        km: "កាលបរិច្ឆេទ",
      },
      furigana: [
        {
          rb: "日付",
          rt: "ひづけ",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1203,
      kanji: "引越し",
      reading: "ひっこし",
      meanings: {
        ja: "引越し",
        en: "moving (house)",
        zh: "搬家",
        tw: "搬家",
        ko: "이사",
        vi: "chuyển nhà",
        th: "ย้ายบ้าน",
        my: "အိမ်ပြောင်း",
        km: "ផ្លាស់ទីផ្ទះ",
      },
      furigana: [
        {
          rb: "引越し",
          rt: "ひっこし",
        },
      ],
      kanjiInfo: [
        {
          char: "引",
          on: ["イン"],
          kun: ["ひ.く", "ひ.ける"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "越",
          on: ["エツ", "オツ"],
          kun: ["こ.す", "-こ.す", "-ご.し", "こ.える", "-ご.え"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1204,
      kanji: "否定",
      reading: "ひてい",
      meanings: {
        ja: "否定",
        en: "denial; negation",
        zh: "否定",
        tw: "否定",
        ko: "부정",
        vi: "phủ định",
        th: "การปฏิเสธ",
        my: "ငြင်းဆန်မှု",
        km: "ការបដិសេធ",
      },
      furigana: [
        {
          rb: "否定",
          rt: "ひてい",
        },
      ],
      kanjiInfo: [
        {
          char: "否",
          on: ["ヒ"],
          kun: ["いな", "いや"],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1205,
      kanji: "ビデオ",
      reading: "ビデオ",
      meanings: {
        ja: "ビデオ",
        en: "video",
        zh: "录像",
        tw: "錄影",
        ko: "비디오",
        vi: "video",
        th: "วิดีโอ",
        my: "ဗီဒီယို",
        km: "វីដេអូ",
      },
      furigana: [
        {
          rb: "ビデオ",
          rt: "ビデオ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1206,
      kanji: "一言",
      reading: "ひとこと",
      meanings: {
        ja: "一言",
        en: "a word; brief remark",
        zh: "一句话",
        tw: "一句話",
        ko: "한마디",
        vi: "một lời",
        th: "คำพูดสั้นๆ",
        my: "စကားတို",
        km: "ពាក្យខ្លី",
      },
      furigana: [
        {
          rb: "一言",
          rt: "ひとこと",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1207,
      kanji: "人込み",
      reading: "ひとごみ",
      meanings: {
        ja: "人込み",
        en: "crowd of people",
        zh: "人群",
        tw: "人群",
        ko: "인파",
        vi: "đám đông",
        th: "ฝูงชน",
        my: "လူအများစု",
        km: "មនុស្សច្រើន",
      },
      furigana: [
        {
          rb: "人込み",
          rt: "ひとごみ",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "込",
          on: [],
          kun: ["-こ.む", "こ.む", "こ.み", "-こ.み", "こ.める"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1208,
      kanji: "独り",
      reading: "ひとり",
      meanings: {
        ja: "独り",
        en: "one person; alone",
        zh: "一个人；独自",
        tw: "一個人；獨自",
        ko: "혼자",
        vi: "một mình",
        th: "คนเดียว",
        my: "တစ်ယောက်တည်း",
        km: "ម្នាក់ឯង",
      },
      furigana: [
        {
          rb: "独り",
          rt: "ひとり",
        },
      ],
      kanjiInfo: [
        {
          char: "独",
          on: ["ドク", "トク"],
          kun: ["ひと.り"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1209,
      kanji: "批判",
      reading: "ひはん",
      meanings: {
        ja: "批判",
        en: "criticism; judgment",
        zh: "批判",
        tw: "批判",
        ko: "비판",
        vi: "phê phán",
        th: "การวิจารณ์",
        my: "ဝေဖန်မှု",
        km: "ការរិះគន់",
      },
      furigana: [
        {
          rb: "批判",
          rt: "ひはん",
        },
      ],
      kanjiInfo: [
        {
          char: "批",
          on: ["ヒ"],
          kun: [],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "判",
          on: ["ハン", "バン"],
          kun: ["わか.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1210,
      kanji: "批評",
      reading: "ひひょう",
      meanings: {
        ja: "批評",
        en: "critique; review",
        zh: "批评",
        tw: "批評",
        ko: "비평",
        vi: "bình luận; phê bình",
        th: "คำวิจารณ์",
        my: "သုံးသပ်ချက်",
        km: "ការវាយតម្លៃ",
      },
      furigana: [
        {
          rb: "批評",
          rt: "ひひょう",
        },
      ],
      kanjiInfo: [
        {
          char: "批",
          on: ["ヒ"],
          kun: [],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "評",
          on: ["ヒョウ"],
          kun: [],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1211,
      kanji: "秘密",
      reading: "ひみつ",
      meanings: {
        ja: "秘密",
        en: "secret",
        zh: "秘密",
        tw: "秘密",
        ko: "비밀",
        vi: "bí mật",
        th: "ความลับ",
        my: "လျှို့ဝှက်ချက်",
        km: "សម្ងាត់",
      },
      furigana: [
        {
          rb: "秘密",
          rt: "ひみつ",
        },
      ],
      kanjiInfo: [
        {
          char: "秘",
          on: ["ヒ"],
          kun: ["ひ.める", "ひそ.か", "かく.す"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "密",
          on: ["ミツ"],
          kun: ["ひそ.か"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1212,
      kanji: "紐",
      reading: "ひも",
      meanings: {
        ja: "紐",
        en: "string; cord",
        zh: "绳子；带子",
        tw: "繩子；帶子",
        ko: "끈",
        vi: "dây",
        th: "เชือก; สาย",
        my: "ကြိုး",
        km: "ខ្សែ",
      },
      furigana: [
        {
          rb: "紐",
          rt: "ひも",
        },
      ],
      kanjiInfo: [
        {
          char: "紐",
          on: ["チュウ", "ジュウ"],
          kun: ["ひも"],
          strokes: 10,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1213,
      kanji: "費用",
      reading: "ひよう",
      meanings: {
        ja: "費用",
        en: "expenses; cost",
        zh: "费用",
        tw: "費用",
        ko: "비용",
        vi: "chi phí",
        th: "ค่าใช้จ่าย",
        my: "ကုန်ကျစရိတ်",
        km: "ចំណាយ",
      },
      furigana: [
        {
          rb: "費用",
          rt: "ひよう",
        },
      ],
      kanjiInfo: [
        {
          char: "費",
          on: ["ヒ"],
          kun: ["つい.やす", "つい.える"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1214,
      kanji: "表",
      reading: "ひょう",
      meanings: {
        ja: "表",
        en: "table; chart; list",
        zh: "表格",
        tw: "表格",
        ko: "표",
        vi: "bảng biểu",
        th: "ตาราง",
        my: "ဇယား",
        km: "តារាង",
      },
      furigana: [
        {
          rb: "表",
          rt: "ひょう",
        },
      ],
      kanjiInfo: [
        {
          char: "表",
          on: ["ヒョウ"],
          kun: ["おもて", "-おもて", "あらわ.す", "あらわ.れる", "あら.わす"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1215,
      kanji: "秒",
      reading: "びょう",
      meanings: {
        ja: "秒",
        en: "second (time)",
        zh: "秒",
        tw: "秒",
        ko: "초",
        vi: "giây",
        th: "วินาที",
        my: "စက္ကန့်",
        km: "វិនាទី",
      },
      furigana: [
        {
          rb: "秒",
          rt: "びょう",
        },
      ],
      kanjiInfo: [
        {
          char: "秒",
          on: ["ビョウ"],
          kun: [],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1216,
      kanji: "評価",
      reading: "ひょうか",
      meanings: {
        ja: "評価",
        en: "evaluation; assessment",
        zh: "评价",
        tw: "評價",
        ko: "평가",
        vi: "đánh giá",
        th: "การประเมิน",
        my: "အကဲဖြတ်ချက်",
        km: "ការវាយតម្លៃ",
      },
      furigana: [
        {
          rb: "評価",
          rt: "ひょうか",
        },
      ],
      kanjiInfo: [
        {
          char: "評",
          on: ["ヒョウ"],
          kun: [],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "価",
          on: ["カ", "ケ"],
          kun: ["あたい"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1217,
      kanji: "表現",
      reading: "ひょうげん",
      meanings: {
        ja: "表現",
        en: "expression",
        zh: "表现；表达",
        tw: "表現；表達",
        ko: "표현",
        vi: "biểu hiện",
        th: "การแสดงออก",
        my: "ဖော်ပြချက်",
        km: "ការបង្ហាញ",
      },
      furigana: [
        {
          rb: "表現",
          rt: "ひょうげん",
        },
      ],
      kanjiInfo: [
        {
          char: "表",
          on: ["ヒョウ"],
          kun: ["おもて", "-おもて", "あらわ.す", "あらわ.れる", "あら.わす"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1218,
      kanji: "表情",
      reading: "ひょうじょう",
      meanings: {
        ja: "表情",
        en: "facial expression",
        zh: "表情",
        tw: "表情",
        ko: "표정",
        vi: "nét mặt",
        th: "สีหน้า",
        my: "မျက်နှာအကျက်အတန်း",
        km: "សញ្ញាមុខ",
      },
      furigana: [
        {
          rb: "表情",
          rt: "ひょうじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "表",
          on: ["ヒョウ"],
          kun: ["おもて", "-おもて", "あらわ.す", "あらわ.れる", "あら.わす"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1219,
      kanji: "平等",
      reading: "びょうどう",
      meanings: {
        ja: "平等",
        en: "equality; impartiality",
        zh: "平等",
        tw: "平等",
        ko: "평등",
        vi: "bình đẳng",
        th: "ความเท่าเทียม",
        my: "တန်းတူညီမျှ",
        km: "សមធម៌",
      },
      furigana: [
        {
          rb: "平等",
          rt: "びょうどう",
        },
      ],
      kanjiInfo: [
        {
          char: "平",
          on: ["ヘイ", "ビョウ", "ヒョウ"],
          kun: ["たい.ら", "たい.らげる", "ひら"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "等",
          on: ["トウ"],
          kun: ["ひと.しい", "など", "-ら"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1220,
      kanji: "評判",
      reading: "ひょうばん",
      meanings: {
        ja: "評判",
        en: "reputation",
        zh: "名声；口碑",
        tw: "名聲；口碑",
        ko: "평판",
        vi: "tiếng tăm; danh tiếng",
        th: "ชื่อเสียง",
        my: "အကျိုးသက်ရောက်မှု",
        km: "កេរ្តិ៍ឈ្មោះ",
      },
      furigana: [
        {
          rb: "評判",
          rt: "ひょうばん",
        },
      ],
      kanjiInfo: [
        {
          char: "評",
          on: ["ヒョウ"],
          kun: [],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "判",
          on: ["ハン", "バン"],
          kun: ["わか.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1221,
      kanji: "表面",
      reading: "ひょうめん",
      meanings: {
        ja: "表面",
        en: "surface; appearance",
        zh: "表面",
        tw: "表面",
        ko: "표면",
        vi: "bề mặt",
        th: "พื้นผิว",
        my: "မျက်နှာပြင်",
        km: "ផ្ទៃ",
      },
      furigana: [
        {
          rb: "表面",
          rt: "ひょうめん",
        },
      ],
      kanjiInfo: [
        {
          char: "表",
          on: ["ヒョウ"],
          kun: ["おもて", "-おもて", "あらわ.す", "あらわ.れる", "あら.わす"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1222,
      kanji: "品",
      reading: "ひん",
      meanings: {
        ja: "品",
        en: "article; goods",
        zh: "商品；物品",
        tw: "商品；物品",
        ko: "물품",
        vi: "hàng hóa; phẩm chất",
        th: "สินค้า",
        my: "ကုန်စည်",
        km: "ទំនិញ",
      },
      furigana: [
        {
          rb: "品",
          rt: "ひん",
        },
      ],
      kanjiInfo: [
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1223,
      kanji: "瓶",
      reading: "びん",
      meanings: {
        ja: "瓶",
        en: "bottle",
        zh: "瓶子",
        tw: "瓶子",
        ko: "병",
        vi: "chai; lọ",
        th: "ขวด",
        my: "ဘူး",
        km: "ដប",
      },
      furigana: [
        {
          rb: "瓶",
          rt: "びん",
        },
      ],
      kanjiInfo: [
        {
          char: "瓶",
          on: ["ビン", "ヘイ"],
          kun: ["かめ"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1224,
      kanji: "便",
      reading: "びん",
      meanings: {
        ja: "便",
        en: "flight; mail service",
        zh: "航班；邮件",
        tw: "航班；郵件",
        ko: "편 (비행편)",
        vi: "chuyến bay; bưu kiện",
        th: "เที่ยวบิน; ไปรษณีย์",
        my: "လေယာဉ်ခရီးစဉ်",
        km: "ជើងហោះហើរ",
      },
      furigana: [
        {
          rb: "便",
          rt: "びん",
        },
      ],
      kanjiInfo: [
        {
          char: "便",
          on: ["ベン", "ビン"],
          kun: ["たよ.り"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1225,
      kanji: "ピン",
      reading: "ピン",
      meanings: {
        ja: "ピン",
        en: "pin",
        zh: "针；大头针",
        tw: "針；大頭針",
        ko: "핀",
        vi: "ghim",
        th: "หมุด",
        my: "မူး",
        km: "ម្ជុល",
      },
      furigana: [
        {
          rb: "ピン",
          rt: "ピン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1226,
      kanji: "分",
      reading: "ぶ",
      meanings: {
        ja: "分",
        en: "one tenth; portion",
        zh: "一成；部分",
        tw: "一成；部分",
        ko: "푼 (1/10)",
        vi: "một phần mười",
        th: "หนึ่งในสิบ",
        my: "တစ်ဆယ့်တစ်ပိုင်း",
        km: "ដប់ភាគមួយ",
      },
      furigana: [
        {
          rb: "分",
          rt: "ぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1227,
      kanji: "不安",
      reading: "ふあん",
      meanings: {
        ja: "不安",
        en: "anxiety; uneasiness",
        zh: "不安",
        tw: "不安",
        ko: "불안",
        vi: "bất an",
        th: "ความกังวล",
        my: "စိုးရိမ်ခြင်း",
        km: "ភាពមិនសុខសាន្ត",
      },
      furigana: [
        {
          rb: "不安",
          rt: "ふあん",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "安",
          on: ["アン"],
          kun: ["やす.い", "やす.まる", "やす", "やす.らか"],
          strokes: 6,
          grade: 3,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1228,
      kanji: "風景",
      reading: "ふうけい",
      meanings: {
        ja: "風景",
        en: "scenery; landscape",
        zh: "风景",
        tw: "風景",
        ko: "풍경",
        vi: "phong cảnh",
        th: "ทิวทัศน์",
        my: "ပုံရိပ်",
        km: "ទេសភាព",
      },
      furigana: [
        {
          rb: "風景",
          rt: "ふうけい",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "景",
          on: ["ケイ"],
          kun: [],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1229,
      kanji: "夫婦",
      reading: "ふうふ",
      meanings: {
        ja: "夫婦",
        en: "married couple",
        zh: "夫妇",
        tw: "夫婦",
        ko: "부부",
        vi: "vợ chồng",
        th: "สามีภรรยา",
        my: "ဇနီးမောင်နှံ",
        km: "ប្តីប្រពន្ធ",
      },
      furigana: [
        {
          rb: "夫婦",
          rt: "ふうふ",
        },
      ],
      kanjiInfo: [
        {
          char: "夫",
          on: ["フ", "フウ", "ブ"],
          kun: ["おっと", "それ"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "婦",
          on: ["フ"],
          kun: ["よめ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1230,
      kanji: "笛",
      reading: "ふえ",
      meanings: {
        ja: "笛",
        en: "flute; whistle",
        zh: "笛子；哨子",
        tw: "笛子；哨子",
        ko: "피리",
        vi: "sáo; còi",
        th: "ขลุ่ย; นกหวีด",
        my: "ဘောင်းလုံး",
        km: "ប៉ី",
      },
      furigana: [
        {
          rb: "笛",
          rt: "ふえ",
        },
      ],
      kanjiInfo: [
        {
          char: "笛",
          on: ["テキ"],
          kun: ["ふえ"],
          strokes: 11,
          grade: 3,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1231,
      kanji: "武器",
      reading: "ぶき",
      meanings: {
        ja: "武器",
        en: "weapon",
        zh: "武器",
        tw: "武器",
        ko: "무기",
        vi: "vũ khí",
        th: "อาวุธ",
        my: "လက်နက်",
        km: "អាវុធ",
      },
      furigana: [
        {
          rb: "武器",
          rt: "ぶき",
        },
      ],
      kanjiInfo: [
        {
          char: "武",
          on: ["ブ", "ム"],
          kun: ["たけ", "たけ.し"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1232,
      kanji: "服装",
      reading: "ふくそう",
      meanings: {
        ja: "服装",
        en: "clothes; attire",
        zh: "服装",
        tw: "服裝",
        ko: "복장",
        vi: "trang phục",
        th: "การแต่งกาย",
        my: "အဝတ်အစား",
        km: "សម្លៀកបំពាក់",
      },
      furigana: [
        {
          rb: "服装",
          rt: "ふくそう",
        },
      ],
      kanjiInfo: [
        {
          char: "服",
          on: ["フク"],
          kun: [],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "装",
          on: ["ソウ", "ショウ"],
          kun: ["よそお.う", "よそお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1233,
      kanji: "袋",
      reading: "ふくろ",
      meanings: {
        ja: "袋",
        en: "bag; sack",
        zh: "袋子",
        tw: "袋子",
        ko: "주머니",
        vi: "túi",
        th: "ถุง",
        my: "အိတ်",
        km: "កាបូប",
      },
      furigana: [
        {
          rb: "袋",
          rt: "ふくろ",
        },
      ],
      kanjiInfo: [
        {
          char: "袋",
          on: ["タイ", "ダイ"],
          kun: ["ふくろ"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1234,
      kanji: "不幸",
      reading: "ふこう",
      meanings: {
        ja: "不幸",
        en: "unhappiness; misfortune",
        zh: "不幸",
        tw: "不幸",
        ko: "불행",
        vi: "bất hạnh",
        th: "ความโชคร้าย",
        my: "ဒုက္ခ",
        km: "អសំណាង",
      },
      furigana: [
        {
          rb: "不幸",
          rt: "ふこう",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "幸",
          on: ["コウ"],
          kun: ["さいわ.い", "さち", "しあわ.せ"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1235,
      kanji: "節",
      reading: "ふし",
      meanings: {
        ja: "節",
        en: "joint; node",
        zh: "关节；节",
        tw: "關節；節",
        ko: "마디",
        vi: "đốt; khớp",
        th: "ข้อ; ข้อต่อ",
        my: "အဆစ်",
        km: "សន្លាក់",
      },
      furigana: [
        {
          rb: "節",
          rt: "ふし",
        },
      ],
      kanjiInfo: [
        {
          char: "節",
          on: ["セツ", "セチ"],
          kun: ["ふし", "-ぶし", "のっと"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1236,
      kanji: "無事",
      reading: "ぶじ",
      meanings: {
        ja: "無事",
        en: "safety; peace",
        zh: "平安；无事",
        tw: "平安；無事",
        ko: "무사",
        vi: "bình an",
        th: "ปลอดภัย",
        my: "အေးချမ်း",
        km: "សុខសាន្ត",
      },
      furigana: [
        {
          rb: "無事",
          rt: "ぶじ",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1237,
      kanji: "不自由",
      reading: "ふじゆう",
      meanings: {
        ja: "不自由",
        en: "discomfort; inconvenience; disability",
        zh: "不便；残疾",
        tw: "不便；殘疾",
        ko: "불편; 장애",
        vi: "khó khăn; tàn tật",
        th: "ไม่สะดวก; พิการ",
        my: "အဆင်မပြေ; မသန်စွမ်း",
        km: "ភាពពិការភាព",
      },
      furigana: [
        {
          rb: "不自由",
          rt: "ふじゆう",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "由",
          on: ["ユ", "ユウ", "ユイ"],
          kun: ["よし", "よ.る"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1238,
      kanji: "夫人",
      reading: "ふじん",
      meanings: {
        ja: "夫人",
        en: "lady; madam; wife",
        zh: "夫人；女士",
        tw: "夫人；女士",
        ko: "부인",
        vi: "phu nhân",
        th: "ภริยา; สุภาพสตรี",
        my: "မယားကြီး",
        km: "ភរិយា",
      },
      furigana: [
        {
          rb: "夫人",
          rt: "ふじん",
        },
      ],
      kanjiInfo: [
        {
          char: "夫",
          on: ["フ", "フウ", "ブ"],
          kun: ["おっと", "それ"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1239,
      kanji: "婦人",
      reading: "ふじん",
      meanings: {
        ja: "婦人",
        en: "woman; lady",
        zh: "妇人；女性",
        tw: "婦人；女性",
        ko: "부인",
        vi: "phụ nữ",
        th: "สตรี",
        my: "မိန်းမ",
        km: "ស្ត្រី",
      },
      furigana: [
        {
          rb: "婦人",
          rt: "ふじん",
        },
      ],
      kanjiInfo: [
        {
          char: "婦",
          on: ["フ"],
          kun: ["よめ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1240,
      kanji: "不正",
      reading: "ふせい",
      meanings: {
        ja: "不正",
        en: "injustice; unfairness; corruption",
        zh: "不正；腐败",
        tw: "不正；腐敗",
        ko: "부정",
        vi: "bất chính; tham nhũng",
        th: "ไม่เป็นธรรม; ทุจริต",
        my: "မမှန်မှု",
        km: "អំពើអយុត្តិធម៌",
      },
      furigana: [
        {
          rb: "不正",
          rt: "ふせい",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1241,
      kanji: "不足",
      reading: "ふそく",
      meanings: {
        ja: "不足",
        en: "insufficiency; shortage",
        zh: "不足；缺乏",
        tw: "不足；缺乏",
        ko: "부족",
        vi: "thiếu hụt",
        th: "ไม่พอ",
        my: "မလုံလောက်မှု",
        km: "ការខ្វះខាត",
      },
      furigana: [
        {
          rb: "不足",
          rt: "ふそく",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "足",
          on: ["ソク"],
          kun: ["あし", "た.りる", "た.る", "た.す"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1242,
      kanji: "舞台",
      reading: "ぶたい",
      meanings: {
        ja: "舞台",
        en: "stage (theater)",
        zh: "舞台",
        tw: "舞台",
        ko: "무대",
        vi: "sân khấu",
        th: "เวที",
        my: "ဇတိကျင်း",
        km: "ឆាក",
      },
      furigana: [
        {
          rb: "舞台",
          rt: "ぶたい",
        },
      ],
      kanjiInfo: [
        {
          char: "舞",
          on: ["ブ"],
          kun: ["ま.う", "-ま.う", "まい"],
          strokes: 15,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "台",
          on: ["ダイ", "タイ"],
          kun: ["うてな", "われ", "つかさ"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1243,
      kanji: "双子",
      reading: "ふたご",
      meanings: {
        ja: "双子",
        en: "twins",
        zh: "双胞胎",
        tw: "雙胞胎",
        ko: "쌍둥이",
        vi: "sinh đôi",
        th: "ฝาแฝด",
        my: "ဇနီးဦး",
        km: "ភ្លោះ",
      },
      furigana: [
        {
          rb: "双子",
          rt: "ふたご",
        },
      ],
      kanjiInfo: [
        {
          char: "双",
          on: ["ソウ"],
          kun: ["ふた", "たぐい", "ならぶ", "ふたつ"],
          strokes: 4,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1244,
      kanji: "縁",
      reading: "ふち",
      meanings: {
        ja: "縁",
        en: "edge; rim; relation",
        zh: "边缘；缘分",
        tw: "邊緣；緣分",
        ko: "가장자리; 인연",
        vi: "mép; duyên",
        th: "ขอบ; บุญสัมพันธ์",
        my: "အနား; ဆက်ဆံရေး",
        km: "គែម; វាសនា",
      },
      furigana: [
        {
          rb: "縁",
          rt: "ふち",
        },
      ],
      kanjiInfo: [
        {
          char: "縁",
          on: ["エン", "-ネン"],
          kun: ["ふち", "ふち.どる", "ゆかり", "よすが", "へり", "えにし"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1245,
      kanji: "不通",
      reading: "ふつう",
      meanings: {
        ja: "不通",
        en: "suspension; blockage",
        zh: "不通；中断",
        tw: "不通；中斷",
        ko: "불통",
        vi: "tắc nghẽn",
        th: "ไม่ผ่าน; ตัดขาด",
        my: "မဆက်သွယ်နိုင်",
        km: "ផ្អាក",
      },
      furigana: [
        {
          rb: "不通",
          rt: "ふつう",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1246,
      kanji: "物価",
      reading: "ぶっか",
      meanings: {
        ja: "物価",
        en: "prices of commodities",
        zh: "物价",
        tw: "物價",
        ko: "물가",
        vi: "vật giá",
        th: "ค่าครองชีพ",
        my: "ဈေးနှုန်း",
        km: "តម្លៃទំនិញ",
      },
      furigana: [
        {
          rb: "物価",
          rt: "ぶっか",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "価",
          on: ["カ", "ケ"],
          kun: ["あたい"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1247,
      kanji: "物質",
      reading: "ぶっしつ",
      meanings: {
        ja: "物質",
        en: "material; substance",
        zh: "物质",
        tw: "物質",
        ko: "물질",
        vi: "vật chất",
        th: "สสาร",
        my: "ပစ္စည်းအရာဝတ္ထု",
        km: "សារធាតុ",
      },
      furigana: [
        {
          rb: "物質",
          rt: "ぶっしつ",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1248,
      kanji: "物理",
      reading: "ぶつり",
      meanings: {
        ja: "物理",
        en: "physics; law of nature",
        zh: "物理",
        tw: "物理",
        ko: "물리",
        vi: "vật lý",
        th: "ฟิสิกส์",
        my: "ရူပဗေဒ",
        km: "រូបវិទ្យា",
      },
      furigana: [
        {
          rb: "物理",
          rt: "ぶつり",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "理",
          on: ["リ"],
          kun: ["ことわり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1249,
      kanji: "筆",
      reading: "ふで",
      meanings: {
        ja: "筆",
        en: "writing brush",
        zh: "毛笔",
        tw: "毛筆",
        ko: "붓",
        vi: "bút lông",
        th: "พู่กัน",
        my: "ထင်းရှူးခဲ",
        km: "ជក់សរសេរ",
      },
      furigana: [
        {
          rb: "筆",
          rt: "ふで",
        },
      ],
      kanjiInfo: [
        {
          char: "筆",
          on: ["ヒツ"],
          kun: ["ふで"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1250,
      kanji: "部分",
      reading: "ぶぶん",
      meanings: {
        ja: "部分",
        en: "portion; part",
        zh: "部分",
        tw: "部分",
        ko: "부분",
        vi: "bộ phận; phần",
        th: "ส่วนหนึ่ง",
        my: "အပိုင်းအစ",
        km: "ផ្នែក",
      },
      furigana: [
        {
          rb: "部分",
          rt: "ぶぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
