export const n3part23 = {
  Lesson23: [
    {
      id: 1101,
      kanji: "流れ",
      reading: "ながれ",
      meanings: {
        ja: "流れ",
        en: "flow; stream",
        zh: "流动；水流",
        tw: "流動；水流",
        ko: "흐름",
        vi: "dòng chảy",
        th: "การไหล",
        my: "စီးဆင်းမှု",
        km: "លំហូរ",
      },
      furigana: [
        {
          rb: "流れ",
          rt: "ながれ",
        },
      ],
      kanjiInfo: [
        {
          char: "流",
          on: ["リュウ", "ル"],
          kun: ["なが.れる", "なが.れ", "なが.す", "-なが.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1102,
      kanji: "無し",
      reading: "なし",
      meanings: {
        ja: "無し",
        en: "without; none",
        zh: "没有",
        tw: "沒有",
        ko: "없음",
        vi: "không có",
        th: "ไม่มี",
        my: "မရှိခြင်း",
        km: "គ្មាន",
      },
      furigana: [
        {
          rb: "無し",
          rt: "なし",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1103,
      kanji: "謎",
      reading: "なぞ",
      meanings: {
        ja: "謎",
        en: "riddle; mystery",
        zh: "谜；谜语",
        tw: "謎；謎語",
        ko: "수수께끼",
        vi: "câu đố; bí ẩn",
        th: "ปริศนา",
        my: "မေးပဟေဠိ",
        km: "ល្បែងល្បិច",
      },
      furigana: [
        {
          rb: "謎",
          rt: "なぞ",
        },
      ],
      kanjiInfo: [
        {
          char: "謎",
          on: ["メイ", "ベイ"],
          kun: ["なぞ"],
          strokes: 16,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1104,
      kanji: "納得",
      reading: "なっとく",
      meanings: {
        ja: "納得",
        en: "consent; understanding; agreement",
        zh: "理解；同意",
        tw: "理解；同意",
        ko: "납득",
        vi: "hiểu; đồng ý",
        th: "ความเข้าใจ; การยอมรับ",
        my: "သဘောတူသိမြင်မှု",
        km: "យល់ព្រម",
      },
      furigana: [
        {
          rb: "納得",
          rt: "なっとく",
        },
      ],
      kanjiInfo: [
        {
          char: "納",
          on: ["ノウ", "ナッ", "ナ", "ナン", "トウ"],
          kun: ["おさ.める", "-おさ.める", "おさ.まる"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "得",
          on: ["トク"],
          kun: ["え.る", "う.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1105,
      kanji: "鍋",
      reading: "なべ",
      meanings: {
        ja: "鍋",
        en: "pot; pan",
        zh: "锅子",
        tw: "鍋子",
        ko: "냄비",
        vi: "nồi",
        th: "หม้อ",
        my: "အိုး",
        km: "ចានស៊ុប",
      },
      furigana: [
        {
          rb: "鍋",
          rt: "なべ",
        },
      ],
      kanjiInfo: [
        {
          char: "鍋",
          on: ["カ"],
          kun: ["なべ"],
          strokes: 17,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1106,
      kanji: "波",
      reading: "なみ",
      meanings: {
        ja: "波",
        en: "wave",
        zh: "波浪",
        tw: "波浪",
        ko: "파도",
        vi: "sóng",
        th: "คลื่น",
        my: "လှိုင်း",
        km: "រលក",
      },
      furigana: [
        {
          rb: "波",
          rt: "なみ",
        },
      ],
      kanjiInfo: [
        {
          char: "波",
          on: ["ハ"],
          kun: ["なみ"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1107,
      kanji: "涙",
      reading: "なみだ",
      meanings: {
        ja: "涙",
        en: "tear (drop)",
        zh: "眼泪",
        tw: "眼淚",
        ko: "눈물",
        vi: "nước mắt",
        th: "น้ำตา",
        my: "မျက်ရည်",
        km: "ទឹកភ្នែក",
      },
      furigana: [
        {
          rb: "涙",
          rt: "なみだ",
        },
      ],
      kanjiInfo: [
        {
          char: "涙",
          on: ["ルイ", "レイ"],
          kun: ["なみだ"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1108,
      kanji: "縄",
      reading: "なわ",
      meanings: {
        ja: "縄",
        en: "rope",
        zh: "绳子",
        tw: "繩子",
        ko: "밧줄",
        vi: "dây thừng",
        th: "เชือก",
        my: "ကြိုးကြပ်",
        km: "ខ្សែចង",
      },
      furigana: [
        {
          rb: "縄",
          rt: "なわ",
        },
      ],
      kanjiInfo: [
        {
          char: "縄",
          on: ["ジョウ"],
          kun: ["なわ", "ただ.す"],
          strokes: 15,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1109,
      kanji: "日",
      reading: "にち",
      meanings: {
        ja: "日",
        en: "day; sun; Sunday",
        zh: "日；太阳；星期日",
        tw: "日；太陽；星期日",
        ko: "날; 해; 일요일",
        vi: "ngày; mặt trời; chủ nhật",
        th: "วัน; ดวงอาทิตย์; วันอาทิตย์",
        my: "နေ့; နေမင်း; တနင်္ဂနွေ",
        km: "ថ្ងៃ; ព្រះអាទិត្យ; ថ្ងៃអាទិត្យ",
      },
      furigana: [
        {
          rb: "日",
          rt: "にち",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1110,
      kanji: "日光",
      reading: "にっこう",
      meanings: {
        ja: "日光",
        en: "sunlight",
        zh: "阳光",
        tw: "陽光",
        ko: "햇빛",
        vi: "ánh sáng mặt trời",
        th: "แสงแดด",
        my: "နေပုံ",
        km: "ពន្លឺព្រះអាទិត្យ",
      },
      furigana: [
        {
          rb: "日光",
          rt: "にっこう",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "光",
          on: ["コウ"],
          kun: ["ひか.る", "ひかり"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1111,
      kanji: "日中",
      reading: "にっちゅう",
      meanings: {
        ja: "日中",
        en: "daytime",
        zh: "白天",
        tw: "白天",
        ko: "낮 동안",
        vi: "ban ngày",
        th: "กลางวัน",
        my: "နေ့အတွင်း",
        km: "ពេលថ្ងៃ",
      },
      furigana: [
        {
          rb: "日中",
          rt: "にっちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1112,
      kanji: "日本",
      reading: "にっぽん",
      meanings: {
        ja: "日本",
        en: "Japan (Nippon)",
        zh: "日本",
        tw: "日本",
        ko: "일본",
        vi: "Nhật Bản",
        th: "ญี่ปุ่น",
        my: "ဂျပန်",
        km: "ជប៉ុន",
      },
      furigana: [
        {
          rb: "日本",
          rt: "にっぽん",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1113,
      kanji: "日本",
      reading: "にほん",
      meanings: {
        ja: "日本",
        en: "Japan (Nihon)",
        zh: "日本",
        tw: "日本",
        ko: "일본",
        vi: "Nhật Bản",
        th: "ญี่ปุ่น",
        my: "ဂျပန်",
        km: "ជប៉ុន",
      },
      furigana: [
        {
          rb: "日本",
          rt: "にほん",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1114,
      kanji: "入場",
      reading: "にゅうじょう",
      meanings: {
        ja: "入場",
        en: "entrance; admission",
        zh: "入场",
        tw: "入場",
        ko: "입장",
        vi: "vào cửa",
        th: "การเข้าชม",
        my: "ဝင်ခွင့်",
        km: "ចូល",
      },
      furigana: [
        {
          rb: "入場",
          rt: "にゅうじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1115,
      kanji: "人気",
      reading: "にんき",
      meanings: {
        ja: "人気",
        en: "popularity",
        zh: "人气",
        tw: "人氣",
        ko: "인기",
        vi: "sự nổi tiếng",
        th: "ความนิยม",
        my: "ကျော်ကြားမှု",
        km: "ប្រជាប្រិយភាព",
      },
      furigana: [
        {
          rb: "人気",
          rt: "にんき",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1116,
      kanji: "人間",
      reading: "にんげん",
      meanings: {
        ja: "人間",
        en: "human being",
        zh: "人类",
        tw: "人類",
        ko: "인간",
        vi: "con người",
        th: "มนุษย์",
        my: "လူသား",
        km: "មនុស្ស",
      },
      furigana: [
        {
          rb: "人間",
          rt: "にんげん",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1117,
      kanji: "布",
      reading: "ぬの",
      meanings: {
        ja: "布",
        en: "cloth; fabric",
        zh: "布料",
        tw: "布料",
        ko: "천",
        vi: "vải",
        th: "ผ้า",
        my: "အထည်",
        km: "ក្រណាត់",
      },
      furigana: [
        {
          rb: "布",
          rt: "ぬの",
        },
      ],
      kanjiInfo: [
        {
          char: "布",
          on: ["フ", "ホ"],
          kun: ["ぬの", "し.く", "きれ"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1118,
      kanji: "根",
      reading: "ね",
      meanings: {
        ja: "根",
        en: "root (of a plant)",
        zh: "根",
        tw: "根",
        ko: "뿌리",
        vi: "rễ",
        th: "ราก",
        my: "အမြစ်",
        km: "ឫស",
      },
      furigana: [
        {
          rb: "根",
          rt: "ね",
        },
      ],
      kanjiInfo: [
        {
          char: "根",
          on: ["コン"],
          kun: ["ね", "-ね"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1119,
      kanji: "値",
      reading: "ね",
      meanings: {
        ja: "値",
        en: "value; price",
        zh: "价值；价格",
        tw: "價值；價格",
        ko: "값",
        vi: "giá trị; giá cả",
        th: "ราคา; มูลค่า",
        my: "တန်ဖိုး; ဈေးနှုန်း",
        km: "តម្លៃ",
      },
      furigana: [
        {
          rb: "値",
          rt: "ね",
        },
      ],
      kanjiInfo: [
        {
          char: "値",
          on: ["チ"],
          kun: ["ね", "あたい"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1120,
      kanji: "願い",
      reading: "ねがい",
      meanings: {
        ja: "願い",
        en: "wish; desire; request",
        zh: "愿望；请求",
        tw: "願望；請求",
        ko: "소원; 바람",
        vi: "ước nguyện",
        th: "ความปรารถนา; คำขอ",
        my: "ဆန္ဒ",
        km: "បំណង",
      },
      furigana: [
        {
          rb: "願い",
          rt: "ねがい",
        },
      ],
      kanjiInfo: [
        {
          char: "願",
          on: ["ガン"],
          kun: ["ねが.う", "-ねがい"],
          strokes: 19,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1121,
      kanji: "鼠",
      reading: "ねずみ",
      meanings: {
        ja: "鼠",
        en: "mouse; rat",
        zh: "老鼠",
        tw: "老鼠",
        ko: "쥐",
        vi: "chuột",
        th: "หนู",
        my: "ကြွက်",
        km: "កណ្តុរ",
      },
      furigana: [
        {
          rb: "鼠",
          rt: "ねずみ",
        },
      ],
      kanjiInfo: [
        {
          char: "鼠",
          on: ["ソ", "ショ"],
          kun: ["ねずみ", "ねず"],
          strokes: 13,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1122,
      kanji: "熱帯",
      reading: "ねったい",
      meanings: {
        ja: "熱帯",
        en: "tropics",
        zh: "热带",
        tw: "熱帶",
        ko: "열대",
        vi: "nhiệt đới",
        th: "เขตร้อน",
        my: "အပူပိုင်း",
        km: "តំបន់ក្តៅ",
      },
      furigana: [
        {
          rb: "熱帯",
          rt: "ねったい",
        },
      ],
      kanjiInfo: [
        {
          char: "熱",
          on: ["ネツ"],
          kun: ["あつ.い"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "帯",
          on: ["タイ"],
          kun: ["お.びる", "おび"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1123,
      kanji: "熱中",
      reading: "ねっちゅう",
      meanings: {
        ja: "熱中",
        en: "being enthusiastic about",
        zh: "热衷",
        tw: "熱衷",
        ko: "열중",
        vi: "say mê",
        th: "หมกมุ่น",
        my: "အလွန်စိတ်ပါဝင်စားခြင်း",
        km: "ចូលចិត្តខ្លាំង",
      },
      furigana: [
        {
          rb: "熱中",
          rt: "ねっちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "熱",
          on: ["ネツ"],
          kun: ["あつ.い"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1124,
      kanji: "年間",
      reading: "ねんかん",
      meanings: {
        ja: "年間",
        en: "(period of) a year",
        zh: "一年间",
        tw: "一年間",
        ko: "연간",
        vi: "trong năm",
        th: "ต่อปี",
        my: "တစ်နှစ်တာ",
        km: "មួយឆ្នាំ",
      },
      furigana: [
        {
          rb: "年間",
          rt: "ねんかん",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1125,
      kanji: "年月",
      reading: "ねんげつ",
      meanings: {
        ja: "年月",
        en: "months and years",
        zh: "年月",
        tw: "年月",
        ko: "세월",
        vi: "năm tháng",
        th: "กาลเวลา",
        my: "နှစ်နှင့်လ",
        km: "ឆ្នាំខែ",
      },
      furigana: [
        {
          rb: "年月",
          rt: "ねんげつ",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1126,
      kanji: "年中",
      reading: "ねんじゅう",
      meanings: {
        ja: "年中",
        en: "all year round",
        zh: "整年；一年到头",
        tw: "整年；一年到頭",
        ko: "연중",
        vi: "quanh năm",
        th: "ตลอดทั้งปี",
        my: "တစ်နှစ်ပတ်လုံး",
        km: "ពេញមួយឆ្នាំ",
      },
      furigana: [
        {
          rb: "年中",
          rt: "ねんじゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1127,
      kanji: "年代",
      reading: "ねんだい",
      meanings: {
        ja: "年代",
        en: "era; age; period",
        zh: "年代",
        tw: "年代",
        ko: "연대",
        vi: "niên đại",
        th: "ยุค; สมัย",
        my: "ခေတ်ကာလ",
        km: "សម័យ",
      },
      furigana: [
        {
          rb: "年代",
          rt: "ねんだい",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1128,
      kanji: "年齢",
      reading: "ねんれい",
      meanings: {
        ja: "年齢",
        en: "age (years)",
        zh: "年龄",
        tw: "年齡",
        ko: "연령",
        vi: "tuổi tác",
        th: "อายุ",
        my: "အသက်",
        km: "អាយុ",
      },
      furigana: [
        {
          rb: "年齢",
          rt: "ねんれい",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "齢",
          on: ["レイ"],
          kun: ["よわい", "とし"],
          strokes: 17,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1129,
      kanji: "野",
      reading: "の",
      meanings: {
        ja: "野",
        en: "field; plain",
        zh: "野地",
        tw: "野地",
        ko: "들판",
        vi: "cánh đồng",
        th: "ทุ่ง; ท้องทุ่ง",
        my: "ပြင်",
        km: "វាល",
      },
      furigana: [
        {
          rb: "野",
          rt: "の",
        },
      ],
      kanjiInfo: [
        {
          char: "野",
          on: ["ヤ", "ショ"],
          kun: ["の", "の-"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1130,
      kanji: "能",
      reading: "のう",
      meanings: {
        ja: "能",
        en: "ability; talent",
        zh: "才能；能力",
        tw: "才能；能力",
        ko: "능력",
        vi: "năng lực; tài năng",
        th: "ความสามารถ",
        my: "တတ်နိုင်စွမ်း",
        km: "សមត្ថភាព",
      },
      furigana: [
        {
          rb: "能",
          rt: "のう",
        },
      ],
      kanjiInfo: [
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1131,
      kanji: "農家",
      reading: "のうか",
      meanings: {
        ja: "農家",
        en: "farmhouse; farmer",
        zh: "农家",
        tw: "農家",
        ko: "농가",
        vi: "nhà nông",
        th: "เกษตรกร",
        my: "လယ်သမားအိမ်",
        km: "កសិករ",
      },
      furigana: [
        {
          rb: "農家",
          rt: "のうか",
        },
      ],
      kanjiInfo: [
        {
          char: "農",
          on: ["ノウ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1132,
      kanji: "農業",
      reading: "のうぎょう",
      meanings: {
        ja: "農業",
        en: "agriculture",
        zh: "农业",
        tw: "農業",
        ko: "농업",
        vi: "nông nghiệp",
        th: "การเกษตร",
        my: "စိုက်ပျိုးရေး",
        km: "កសិកម្ម",
      },
      furigana: [
        {
          rb: "農業",
          rt: "のうぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "農",
          on: ["ノウ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1133,
      kanji: "農民",
      reading: "のうみん",
      meanings: {
        ja: "農民",
        en: "farmer; peasant",
        zh: "农民",
        tw: "農民",
        ko: "농민",
        vi: "nông dân",
        th: "ชาวนา; เกษตรกร",
        my: "လယ်သမား",
        km: "កសិករ",
      },
      furigana: [
        {
          rb: "農民",
          rt: "のうみん",
        },
      ],
      kanjiInfo: [
        {
          char: "農",
          on: ["ノウ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "民",
          on: ["ミン"],
          kun: ["たみ"],
          strokes: 5,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1134,
      kanji: "能力",
      reading: "のうりょく",
      meanings: {
        ja: "能力",
        en: "ability; capacity",
        zh: "能力",
        tw: "能力",
        ko: "능력",
        vi: "khả năng",
        th: "ความสามารถ",
        my: "စွမ်းရည်",
        km: "សមត្ថភាព",
      },
      furigana: [
        {
          rb: "能力",
          rt: "のうりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1135,
      kanji: "軒",
      reading: "のき",
      meanings: {
        ja: "軒",
        en: "eaves",
        zh: "屋檐",
        tw: "屋簷",
        ko: "처마",
        vi: "mái hiên",
        th: "ชายคา",
        my: "အိမ်အရံ",
        km: "ដំបូលផ្ទះ",
      },
      furigana: [
        {
          rb: "軒",
          rt: "のき",
        },
      ],
      kanjiInfo: [
        {
          char: "軒",
          on: ["ケン"],
          kun: ["のき"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1136,
      kanji: "残り",
      reading: "のこり",
      meanings: {
        ja: "残り",
        en: "remainder; leftover",
        zh: "剩余",
        tw: "剩餘",
        ko: "나머지",
        vi: "phần còn lại",
        th: "ส่วนที่เหลือ",
        my: "ကျန်ရှိ",
        km: "អ្វីដែលនៅសល់",
      },
      furigana: [
        {
          rb: "残り",
          rt: "のこり",
        },
      ],
      kanjiInfo: [
        {
          char: "残",
          on: ["ザン", "サン"],
          kun: ["のこ.る", "のこ.す", "そこな.う", "のこ.り"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1137,
      kanji: "望み",
      reading: "のぞみ",
      meanings: {
        ja: "望み",
        en: "wish; hope",
        zh: "希望",
        tw: "希望",
        ko: "희망",
        vi: "hy vọng",
        th: "ความหวัง",
        my: "ဆန္ဒလက္ခံ",
        km: "សង្ឃឹម",
      },
      furigana: [
        {
          rb: "望み",
          rt: "のぞみ",
        },
      ],
      kanjiInfo: [
        {
          char: "望",
          on: ["ボウ", "モウ"],
          kun: ["のぞ.む", "もち"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1138,
      kanji: "後",
      reading: "のち",
      meanings: {
        ja: "後",
        en: "after; later",
        zh: "以后；之后",
        tw: "以後；之後",
        ko: "후; 나중",
        vi: "sau; về sau",
        th: "ภายหลัง",
        my: "နောက်ပိုင်း",
        km: "ក្រោយ; ពេលក្រោយ",
      },
      furigana: [
        {
          rb: "後",
          rt: "のち",
        },
      ],
      kanjiInfo: [
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1139,
      kanji: "ノック",
      reading: "ノック",
      meanings: {
        ja: "ノック",
        en: "knock",
        zh: "敲门",
        tw: "敲門",
        ko: "노크",
        vi: "gõ cửa",
        th: "เคาะประตู",
        my: "တံခါးခေါက်ခြင်း",
        km: "ក្រឡុកទ្វារ",
      },
      furigana: [
        {
          rb: "ノック",
          rt: "ノック",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1140,
      kanji: "場",
      reading: "ば",
      meanings: {
        ja: "場",
        en: "place; scene",
        zh: "场所",
        tw: "場所",
        ko: "장소",
        vi: "địa điểm",
        th: "สถานที่",
        my: "နေရာ",
        km: "កន្លែង",
      },
      furigana: [
        {
          rb: "場",
          rt: "ば",
        },
      ],
      kanjiInfo: [
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1141,
      kanji: "パーセント",
      reading: "パーセント",
      meanings: {
        ja: "パーセント",
        en: "percent",
        zh: "百分比",
        tw: "百分比",
        ko: "퍼센트",
        vi: "phần trăm",
        th: "เปอร์เซ็นต์",
        my: "ရာခိုင်နှုန်း",
        km: "ភាគរយ",
      },
      furigana: [
        {
          rb: "パーセント",
          rt: "パーセント",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1142,
      kanji: "灰",
      reading: "はい",
      meanings: {
        ja: "灰",
        en: "ash",
        zh: "灰烬",
        tw: "灰燼",
        ko: "재",
        vi: "tro",
        th: "เถ้า",
        my: "ပြာ",
        km: "ផេះ",
      },
      furigana: [
        {
          rb: "灰",
          rt: "はい",
        },
      ],
      kanjiInfo: [
        {
          char: "灰",
          on: ["カイ"],
          kun: ["はい"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1143,
      kanji: "梅雨",
      reading: "ばいう",
      meanings: {
        ja: "梅雨",
        en: "rainy season (East Asia)",
        zh: "梅雨",
        tw: "梅雨",
        ko: "장마",
        vi: "mùa mưa",
        th: "ฤดูฝน",
        my: "မိုးရာသီ",
        km: "រដូវវស្សា",
      },
      furigana: [
        {
          rb: "梅雨",
          rt: "ばいう",
        },
      ],
      kanjiInfo: [
        {
          char: "梅",
          on: ["バイ"],
          kun: ["うめ"],
          strokes: 10,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
        {
          char: "雨",
          on: ["ウ"],
          kun: ["あめ", "あま-", "-さめ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1144,
      kanji: "バイオリン",
      reading: "バイオリン",
      meanings: {
        ja: "バイオリン",
        en: "violin",
        zh: "小提琴",
        tw: "小提琴",
        ko: "바이올린",
        vi: "violin",
        th: "ไวโอลิน",
        my: "ဗိုင်ယိုလင်း",
        km: "វីយ៉ូលុង",
      },
      furigana: [
        {
          rb: "バイオリン",
          rt: "バイオリン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1145,
      kanji: "ハイキング",
      reading: "ハイキング",
      meanings: {
        ja: "ハイキング",
        en: "hiking",
        zh: "远足",
        tw: "遠足",
        ko: "하이킹",
        vi: "đi bộ đường dài",
        th: "การเดินป่า",
        my: "တောလမ်းလျှောက်",
        km: "ដើរព្រៃ",
      },
      furigana: [
        {
          rb: "ハイキング",
          rt: "ハイキング",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1146,
      kanji: "配達",
      reading: "はいたつ",
      meanings: {
        ja: "配達",
        en: "delivery",
        zh: "投递；配送",
        tw: "投遞；配送",
        ko: "배달",
        vi: "giao hàng",
        th: "การส่งของ",
        my: "ပစ္စည်းပို့",
        km: "ការដឹកជញ្ជូន",
      },
      furigana: [
        {
          rb: "配達",
          rt: "はいたつ",
        },
      ],
      kanjiInfo: [
        {
          char: "配",
          on: ["ハイ"],
          kun: ["くば.る"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "達",
          on: ["タツ", "ダ"],
          kun: ["-たち"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1147,
      kanji: "パイプ",
      reading: "パイプ",
      meanings: {
        ja: "パイプ",
        en: "pipe; tube",
        zh: "管子",
        tw: "管子",
        ko: "파이프",
        vi: "ống",
        th: "ท่อ",
        my: "ပိုက်",
        km: "បំពង់",
      },
      furigana: [
        {
          rb: "パイプ",
          rt: "パイプ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1148,
      kanji: "俳優",
      reading: "はいゆう",
      meanings: {
        ja: "俳優",
        en: "actor; performer",
        zh: "演员",
        tw: "演員",
        ko: "배우",
        vi: "diễn viên",
        th: "นักแสดง",
        my: "မင်းသား",
        km: "តារាសម្តែង",
      },
      furigana: [
        {
          rb: "俳優",
          rt: "はいゆう",
        },
      ],
      kanjiInfo: [
        {
          char: "俳",
          on: ["ハイ"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "優",
          on: ["ユウ", "ウ"],
          kun: ["やさ.しい", "すぐ.れる", "まさ.る"],
          strokes: 17,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1149,
      kanji: "パイロット",
      reading: "パイロット",
      meanings: {
        ja: "パイロット",
        en: "pilot",
        zh: "飞行员",
        tw: "飛行員",
        ko: "파일럿",
        vi: "phi công",
        th: "นักบิน",
        my: "မောင်းသူ",
        km: "អ្នកបើកយន្តហោះ",
      },
      furigana: [
        {
          rb: "パイロット",
          rt: "パイロット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1150,
      kanji: "墓",
      reading: "はか",
      meanings: {
        ja: "墓",
        en: "grave; tomb",
        zh: "坟墓",
        tw: "墳墓",
        ko: "무덤",
        vi: "mộ phần",
        th: "หลุมศพ",
        my: "အုတ်ဂူ",
        km: "ផ្នូរ",
      },
      furigana: [
        {
          rb: "墓",
          rt: "はか",
        },
      ],
      kanjiInfo: [
        {
          char: "墓",
          on: ["ボ"],
          kun: ["はか"],
          strokes: 13,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
