export const n3part8 = {
  Lesson8: [
    {
      id: 351,
      kanji: "カード",
      reading: "カード",
      meanings: {
        ja: "カード。厚紙やプラスチック製の小片。",
        en: "card",
        zh: "卡片",
        tw: "卡片",
        ko: "카드",
        vi: "thẻ",
        th: "บัตร",
        my: "ကဒ်",
        km: "កាត",
      },
      furigana: [
        {
          rb: "カード",
          rt: "カード",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 352,
      kanji: "貝",
      reading: "かい",
      meanings: {
        ja: "貝殻をもつ水生動物の総称。",
        en: "shellfish; mollusk",
        zh: "贝类",
        tw: "貝類",
        ko: "조개류",
        vi: "động vật có vỏ (nhuyễn thể)",
        th: "หอย",
        my: "ခဲအုံးရှိသောရေသတ္တဝါ (shellfish)",
        km: "សត្វសមុទ្រមានសំបក (សត្វខ្យង)",
      },
      furigana: [
        {
          rb: "貝",
          rt: "かい",
        },
      ],
      kanjiInfo: [
        {
          char: "貝",
          on: ["バイ"],
          kun: ["かい"],
          strokes: 7,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 353,
      kanji: "害",
      reading: "がい",
      meanings: {
        ja: "損害。悪い影響。",
        en: "harm; damage; injury",
        zh: "害；损害",
        tw: "害；損害",
        ko: "해; 피해",
        vi: "hại; tổn hại",
        th: "โทษ; ความเสียหาย",
        my: "ထိခိုက်ပျက်စီးမှု",
        km: "គ្រោះថ្នាក់; ការខូចខាត",
      },
      furigana: [
        {
          rb: "害",
          rt: "がい",
        },
      ],
      kanjiInfo: [
        {
          char: "害",
          on: ["ガイ"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 354,
      kanji: "会員",
      reading: "かいいん",
      meanings: {
        ja: "会や団体に属する人。",
        en: "member",
        zh: "会员",
        tw: "會員",
        ko: "회원",
        vi: "thành viên",
        th: "สมาชิก",
        my: "အဖွဲ့ဝင်",
        km: "សមាជិក",
      },
      furigana: [
        {
          rb: "会員",
          rt: "かいいん",
        },
      ],
      kanjiInfo: [
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "員",
          on: ["イン"],
          kun: [],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 355,
      kanji: "絵画",
      reading: "かいが",
      meanings: {
        ja: "絵や絵画作品。",
        en: "painting; artwork",
        zh: "绘画；画作",
        tw: "繪畫；畫作",
        ko: "회화; 그림",
        vi: "hội họa; bức tranh",
        th: "จิตรกรรม; ภาพวาด",
        my: "ရုပ်ပုံရေးရာ; ပန်းချီကား",
        km: "គំនូរ; ស្នាដៃគំនូរ",
      },
      furigana: [
        {
          rb: "絵画",
          rt: "かいが",
        },
      ],
      kanjiInfo: [
        {
          char: "絵",
          on: ["カイ", "エ"],
          kun: [],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "画",
          on: ["ガ", "カク", "エ", "カイ"],
          kun: ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 356,
      kanji: "海外",
      reading: "かいがい",
      meanings: {
        ja: "外国。海外。",
        en: "overseas; abroad",
        zh: "海外；国外",
        tw: "海外；國外",
        ko: "해외",
        vi: "nước ngoài; hải ngoại",
        th: "ต่างประเทศ",
        my: "နိုင်ငံခြား",
        km: "បរទេស; ក្រៅប្រទេស",
      },
      furigana: [
        {
          rb: "海外",
          rt: "かいがい",
        },
      ],
      kanjiInfo: [
        {
          char: "海",
          on: ["カイ"],
          kun: ["うみ"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 357,
      kanji: "会計",
      reading: "かいけい",
      meanings: {
        ja: "金銭の出納・計算。または会計担当。",
        en: "accounting; checkout (at a store)",
        zh: "会计；结账",
        tw: "會計；結帳",
        ko: "회계; 계산",
        vi: "kế toán; tính tiền",
        th: "บัญชี; ชำระเงิน",
        my: "စာရင်းကိုင်; ငွေနှုန်းချိန်",
        km: "គណនេយ្យ; គិតលុយ",
      },
      furigana: [
        {
          rb: "会計",
          rt: "かいけい",
        },
      ],
      kanjiInfo: [
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "計",
          on: ["ケイ"],
          kun: ["はか.る", "はか.らう"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 358,
      kanji: "解決",
      reading: "かいけつ",
      meanings: {
        ja: "問題などを解き終えること。",
        en: "solution; resolution (of a problem)",
        zh: "解决",
        tw: "解決",
        ko: "해결",
        vi: "giải quyết; lời giải",
        th: "การแก้ปัญหา",
        my: "ဖြေရှင်းချက်",
        km: "ដោះស្រាយ; ಪರಿಹារ (solution)",
      },
      furigana: [
        {
          rb: "解決",
          rt: "かいけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 359,
      kanji: "会合",
      reading: "かいごう",
      meanings: {
        ja: "人が集まること。集会。",
        en: "meeting; gathering",
        zh: "会合；聚会",
        tw: "會合；聚會",
        ko: "모임; 회합",
        vi: "cuộc họp; buổi gặp mặt",
        th: "การประชุม; การรวมตัว",
        my: "အစည်းအဝေး",
        km: "សន្និសីទ; ការជួបប្រជុំ",
      },
      furigana: [
        {
          rb: "会合",
          rt: "かいごう",
        },
      ],
      kanjiInfo: [
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 360,
      kanji: "外交",
      reading: "がいこう",
      meanings: {
        ja: "国家間の公式な交渉・関係。",
        en: "diplomacy; foreign affairs",
        zh: "外交",
        tw: "外交",
        ko: "외교",
        vi: "ngoại giao",
        th: "การทูต",
        my: "နိုင်ငံတကာရေးရာ (နိုင်ငံခြားရေး)",
        km: "ការទូត; ការផ្តោតលើការបរទេស",
      },
      furigana: [
        {
          rb: "外交",
          rt: "がいこう",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "交",
          on: ["コウ"],
          kun: [
            "まじ.わる",
            "まじ.える",
            "ま.じる",
            "まじ.る",
            "ま.ざる",
            "ま.ぜる",
            "-か.う",
            "か.わす",
            "かわ.す",
            "こもごも",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 361,
      kanji: "開始",
      reading: "かいし",
      meanings: {
        ja: "始めること。スタート。",
        en: "start; commencement",
        zh: "开始",
        tw: "開始",
        ko: "개시; 시작",
        vi: "khai bắt đầu; khởi đầu",
        th: "เริ่มต้น",
        my: "အစပြုခြင်း",
        km: "ការចាប់ផ្តើម",
      },
      furigana: [
        {
          rb: "開始",
          rt: "かいし",
        },
      ],
      kanjiInfo: [
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "始",
          on: ["シ"],
          kun: ["はじ.める", "-はじ.める", "はじ.まる"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 362,
      kanji: "解釈",
      reading: "かいしゃく",
      meanings: {
        ja: "意味や意図を説明・理解すること。",
        en: "interpretation; explanation",
        zh: "解释；阐释",
        tw: "解釋；詮釋",
        ko: "해석",
        vi: "diễn giải; giải thích",
        th: "การตีความ; การอธิบาย",
        my: "ဖော်ကျူးဖော်ပြခြင်း; အဓိပ္ပါယ်ဖော်ထုတ်ခြင်း",
        km: "ការបកស្រាយ",
      },
      furigana: [
        {
          rb: "解釈",
          rt: "かいしゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "釈",
          on: ["シャク", "セキ"],
          kun: ["とく", "す.てる", "ゆる.す"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 363,
      kanji: "外出",
      reading: "がいしゅつ",
      meanings: {
        ja: "家や職場の外へ出ること。",
        en: "going out (leaving home/office)",
        zh: "外出",
        tw: "外出",
        ko: "외출",
        vi: "ra ngoài",
        th: "ออกไปข้างนอก",
        my: "အပြင်ထွက်ခြင်း",
        km: "ចេញទៅក្រៅ",
      },
      furigana: [
        {
          rb: "外出",
          rt: "がいしゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 364,
      kanji: "改善",
      reading: "かいぜん",
      meanings: {
        ja: "よりよく改めること。",
        en: "improvement",
        zh: "改善",
        tw: "改善",
        ko: "개선",
        vi: "cải thiện",
        th: "การปรับปรุง",
        my: "တိုးတက်ကောင်းမွန်စေခြင်း",
        km: "កែលម្អ",
      },
      furigana: [
        {
          rb: "改善",
          rt: "かいぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "改",
          on: ["カイ"],
          kun: ["あらた.める", "あらた.まる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "善",
          on: ["ゼン"],
          kun: ["よ.い", "い.い", "よ.く", "よし.とする"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 365,
      kanji: "回復",
      reading: "かいふく",
      meanings: {
        ja: "元の良い状態に戻ること。",
        en: "recovery; restoration",
        zh: "恢复",
        tw: "恢復",
        ko: "회복",
        vi: "phục hồi",
        th: "การฟื้นตัว",
        my: "နေပြန်ကောင်းလာခြင်း",
        km: "ស្តារឡើងវិញ; ការជាសះស្បើយ",
      },
      furigana: [
        {
          rb: "回復",
          rt: "かいふく",
        },
      ],
      kanjiInfo: [
        {
          char: "回",
          on: ["カイ", "エ"],
          kun: [
            "まわ.る",
            "-まわ.る",
            "-まわ.り",
            "まわ.す",
            "-まわ.す",
            "まわ.し-",
            "-まわ.し",
            "もとお.る",
            "か.える",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "復",
          on: ["フク"],
          kun: ["また"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 366,
      kanji: "香り",
      reading: "かおり",
      meanings: {
        ja: "よいにおい。芳香。",
        en: "scent; fragrance; aroma",
        zh: "香味；香气",
        tw: "香味；香氣",
        ko: "향기",
        vi: "hương thơm; mùi thơm",
        th: "กลิ่นหอม",
        my: "မွှေးနံ့",
        km: "ក្លិនក្រអូប",
      },
      furigana: [
        {
          rb: "香り",
          rt: "かおり",
        },
      ],
      kanjiInfo: [
        {
          char: "香",
          on: ["コウ", "キョウ"],
          kun: ["か", "かお.り", "かお.る"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 367,
      kanji: "画家",
      reading: "がか",
      meanings: {
        ja: "絵を職業とする人。",
        en: "painter (artist)",
        zh: "画家",
        tw: "畫家",
        ko: "화가",
        vi: "họa sĩ",
        th: "จิตรกร",
        my: "ပန်းချီဝါကြီး",
        km: "សិល្បករ​គំនូរ",
      },
      furigana: [
        {
          rb: "画家",
          rt: "がか",
        },
      ],
      kanjiInfo: [
        {
          char: "画",
          on: ["ガ", "カク", "エ", "カイ"],
          kun: ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 368,
      kanji: "価格",
      reading: "かかく",
      meanings: {
        ja: "品物の値段。",
        en: "price; cost",
        zh: "价格",
        tw: "價格",
        ko: "가격",
        vi: "giá; giá cả",
        th: "ราคา",
        my: "စျေးနှုန်း",
        km: "តម្លៃ",
      },
      furigana: [
        {
          rb: "価格",
          rt: "かかく",
        },
      ],
      kanjiInfo: [
        {
          char: "価",
          on: ["カ", "ケ"],
          kun: ["あたい"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "格",
          on: ["カク", "コウ", "キャク", "ゴウ"],
          kun: [],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 369,
      kanji: "化学",
      reading: "かがく",
      meanings: {
        ja: "物質とその変化を研究する学問。",
        en: "chemistry",
        zh: "化学",
        tw: "化學",
        ko: "화학",
        vi: "hóa học",
        th: "เคมี",
        my: "ဓာတုဗေဒ",
        km: "គីមីវិទ្យា",
      },
      furigana: [
        {
          rb: "化学",
          rt: "かがく",
        },
      ],
      kanjiInfo: [
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 370,
      kanji: "係",
      reading: "かかり",
      meanings: {
        ja: "担当者。係の人。",
        en: "person in charge; clerk",
        zh: "负责人；经办人",
        tw: "負責人；承辦人",
        ko: "담당자",
        vi: "người phụ trách",
        th: "ผู้รับผิดชอบ; เจ้าหน้าที่",
        my: "တာဝန်ခံ; ဝန်ထမ်း",
        km: "អ្នកទទួលខុសត្រូវ; មន្រ្តី",
      },
      furigana: [
        {
          rb: "係",
          rt: "かかり",
        },
      ],
      kanjiInfo: [
        {
          char: "係",
          on: ["ケイ"],
          kun: ["かか.る", "かかり", "-がかり", "かか.わる"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 371,
      kanji: "家具",
      reading: "かぐ",
      meanings: {
        ja: "室内で使用する大型の道具。",
        en: "furniture",
        zh: "家具",
        tw: "家具",
        ko: "가구",
        vi: "đồ nội thất",
        th: "เฟอร์นิเจอร์",
        my: "အိမ်ပရိဘောဂ",
        km: "គ្រឿងសង្ហារឹម",
      },
      furigana: [
        {
          rb: "家具",
          rt: "かぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "具",
          on: ["グ"],
          kun: ["そな.える", "つぶさ.に"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 372,
      kanji: "学",
      reading: "がく",
      meanings: {
        ja: "学問。学び。",
        en: "learning; scholarship",
        zh: "学问；学习",
        tw: "學問；學習",
        ko: "학문; 배움",
        vi: "sự học; học thuật",
        th: "การเรียนรู้; วิชาการ",
        my: "စာပေသင်ကြားမှု; ပညာ",
        km: "ការសិក្សា; វិជ្ជា",
      },
      furigana: [
        {
          rb: "学",
          rt: "がく",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 373,
      kanji: "額",
      reading: "がく",
      meanings: {
        ja: "絵などを入れる枠。額縁。",
        en: "(picture) frame",
        zh: "画框；相框",
        tw: "畫框；相框",
        ko: "액자",
        vi: "khung (tranh)",
        th: "กรอบรูป/กรอบภาพ",
        my: "ပန်းချီဘောင်",
        km: "ស៊ុមរូបភាព",
      },
      furigana: [
        {
          rb: "額",
          rt: "がく",
        },
      ],
      kanjiInfo: [
        {
          char: "額",
          on: ["ガク"],
          kun: ["ひたい"],
          strokes: 18,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 374,
      kanji: "覚悟",
      reading: "かくご",
      meanings: {
        ja: "結果を受け止める心の準備。",
        en: "readiness; resolve; preparedness",
        zh: "觉悟；心理准备",
        tw: "覺悟；心理準備",
        ko: "각오; 대비",
        vi: "quyết tâm; sự sẵn sàng",
        th: "ความตั้งใจแน่วแน่; การเตรียมใจ",
        my: "သူ့စိတ်ပြင်ဆင်ချက်; ဆုံးဖြတ်ချက်",
        km: "ការរៀបចំចិត្ត; សេចក្តីសម្រេចចិត្ត",
      },
      furigana: [
        {
          rb: "覚悟",
          rt: "かくご",
        },
      ],
      kanjiInfo: [
        {
          char: "覚",
          on: ["カク"],
          kun: ["おぼ.える", "さ.ます", "さ.める", "さと.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "悟",
          on: ["ゴ"],
          kun: ["さと.る"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 375,
      kanji: "学者",
      reading: "がくしゃ",
      meanings: {
        ja: "学問を専門とする人。",
        en: "scholar",
        zh: "学者",
        tw: "學者",
        ko: "학자",
        vi: "học giả",
        th: "นักปราชญ์; นักวิชาการ",
        my: "ပညာတော်ဦး; အတ္ထုပ္ပတ္တိကျော်",
        km: "អ្នកប្រាជ្ញ; អ្នកវិទ្យាសាស្ត្រ",
      },
      furigana: [
        {
          rb: "学者",
          rt: "がくしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "者",
          on: ["シャ"],
          kun: ["もの"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 376,
      kanji: "学習",
      reading: "がくしゅう",
      meanings: {
        ja: "学び習うこと。",
        en: "learning; study",
        zh: "学习",
        tw: "學習",
        ko: "학습",
        vi: "học tập",
        th: "การเรียนรู้",
        my: "လေ့လာသင်ယူမှု",
        km: "ការសិក្សា; ការរៀន",
      },
      furigana: [
        {
          rb: "学習",
          rt: "がくしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "習",
          on: ["シュウ", "ジュ"],
          kun: ["なら.う", "なら.い"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 377,
      kanji: "拡大",
      reading: "かくだい",
      meanings: {
        ja: "大きくすること。広げること。",
        en: "enlargement; expansion",
        zh: "扩大；放大",
        tw: "擴大；放大",
        ko: "확대",
        vi: "mở rộng; phóng to",
        th: "การขยาย",
        my: "ချဲ့ထွင်မှု; ထွင်ခြင်း",
        km: "ពង្រីក; ពង្រីកទំហំ",
      },
      furigana: [
        {
          rb: "拡大",
          rt: "かくだい",
        },
      ],
      kanjiInfo: [
        {
          char: "拡",
          on: ["カク", "コウ"],
          kun: ["ひろ.がる", "ひろ.げる", "ひろ.める"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 378,
      kanji: "確認",
      reading: "かくにん",
      meanings: {
        ja: "確かめること。検証。",
        en: "confirmation; verification",
        zh: "确认；核实",
        tw: "確認；核實",
        ko: "확인",
        vi: "xác nhận; kiểm chứng",
        th: "การยืนยัน; การตรวจสอบ",
        my: "အတည်ပြုခြင်း; စစ်ဆေးခြင်း",
        km: "ការបញ្ជាក់; ផ្ទៀងផ្ទាត់",
      },
      furigana: [
        {
          rb: "確認",
          rt: "かくにん",
        },
      ],
      kanjiInfo: [
        {
          char: "確",
          on: ["カク", "コウ"],
          kun: ["たし.か", "たし.かめる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "認",
          on: ["ニン"],
          kun: ["みと.める", "したた.める"],
          strokes: 14,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 379,
      kanji: "学問",
      reading: "がくもん",
      meanings: {
        ja: "系統立てて学ぶ学術。",
        en: "scholarship; academic study",
        zh: "学问；学术研究",
        tw: "學問；學術研究",
        ko: "학문",
        vi: "học vấn; học thuật",
        th: "วิชาการ; การศึกษาทางวิชาการ",
        my: "ပညာရပ်; အင်အားပညာ",
        km: "វិជ្ជាជីវៈ; សិក្សាវិទ្យាសាស្ត្រ",
      },
      furigana: [
        {
          rb: "学問",
          rt: "がくもん",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "問",
          on: ["モン"],
          kun: ["と.う", "と.い", "とん"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 380,
      kanji: "影",
      reading: "かげ",
      meanings: {
        ja: "光がさえぎられてできる黒い形。",
        en: "shadow; silhouette",
        zh: "影子；阴影",
        tw: "影子；陰影",
        ko: "그림자",
        vi: "bóng; bóng đổ",
        th: "เงา",
        my: "အရိပ်",
        km: "ស្រមោល",
      },
      furigana: [
        {
          rb: "影",
          rt: "かげ",
        },
      ],
      kanjiInfo: [
        {
          char: "影",
          on: ["エイ"],
          kun: ["かげ"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 381,
      kanji: "陰",
      reading: "かげ",
      meanings: {
        ja: "日が当たらない所。暗がり。",
        en: "shade; shadow (out of light)",
        zh: "阴处；背阴",
        tw: "陰處；背陰",
        ko: "그늘",
        vi: "bóng râm; chỗ râm mát",
        th: "ร่มเงา; ที่มืด",
        my: "အရိပ်နေရာ; အရိပ်ချနေရာ",
        km: "ឋានកន្លែងខាងស្រមោល; កន្លែងត្រជាក់",
      },
      furigana: [
        {
          rb: "陰",
          rt: "かげ",
        },
      ],
      kanjiInfo: [
        {
          char: "陰",
          on: ["イン"],
          kun: ["かげ", "かげ.る"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 382,
      kanji: "加減",
      reading: "かげん",
      meanings: {
        ja: "程度。具合。調節すること。",
        en: "degree; condition; adjustment",
        zh: "程度；状况；调节",
        tw: "程度；狀況；調節",
        ko: "정도; 상태; 조절",
        vi: "mức độ; tình trạng; điều chỉnh",
        th: "ระดับ; สภาพ; การปรับ",
        my: "အဆင့်အတန်း; အခွအေန; စိစစ်ညှိနှိုင်း",
        km: "កម្រិត; ស្ថានភាព; ការកែសម្រួល",
      },
      furigana: [
        {
          rb: "加減",
          rt: "かげん",
        },
      ],
      kanjiInfo: [
        {
          char: "加",
          on: ["カ"],
          kun: ["くわ.える", "くわ.わる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "減",
          on: ["ゲン"],
          kun: ["へ.る", "へ.らす"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 383,
      kanji: "過去",
      reading: "かこ",
      meanings: {
        ja: "今までに過ぎ去った時間。",
        en: "the past",
        zh: "过去",
        tw: "過去",
        ko: "과거",
        vi: "quá khứ",
        th: "อดีต",
        my: "အတိတ်",
        km: "អតីតកាល",
      },
      furigana: [
        {
          rb: "過去",
          rt: "かこ",
        },
      ],
      kanjiInfo: [
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "去",
          on: ["キョ", "コ"],
          kun: ["さ.る", "-さ.る"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 384,
      kanji: "籠",
      reading: "かご",
      meanings: {
        ja: "物を入れて運ぶ入れ物。買い物かごなど。",
        en: "basket (e.g., shopping basket)",
        zh: "篮子（如购物篮）",
        tw: "籃子（如購物籃）",
        ko: "바구니 (쇼핑 바구니 등)",
        vi: "giỏ (ví dụ: giỏ mua sắm)",
        th: "ตะกร้า (เช่น ตะกร้าช้อปปิ้ง)",
        my: "ခြုံ (စျေးဝယ်ခြုံ)",
        km: "កន្ត្រក (ឧ. កន្ត្រកទិញឥវ៉ាន់)",
      },
      furigana: [
        {
          rb: "籠",
          rt: "かご",
        },
      ],
      kanjiInfo: [
        {
          char: "籠",
          on: ["ロウ", "ル"],
          kun: ["かご", "こ.める", "こも.る", "こ.む"],
          strokes: 22,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 385,
      kanji: "火災",
      reading: "かさい",
      meanings: {
        ja: "建物などが焼ける大きな火事。",
        en: "fire; conflagration",
        zh: "火灾",
        tw: "火災",
        ko: "화재",
        vi: "hỏa hoạn",
        th: "อัคคีภัย",
        my: "မီးလောင်မှု",
        km: "អគ្គីភ័យ",
      },
      furigana: [
        {
          rb: "火災",
          rt: "かさい",
        },
      ],
      kanjiInfo: [
        {
          char: "火",
          on: ["カ"],
          kun: ["ひ", "-び", "ほ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "災",
          on: ["サイ"],
          kun: ["わざわ.い"],
          strokes: 7,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 386,
      kanji: "飾り",
      reading: "かざり",
      meanings: {
        ja: "装飾・飾り付け。飾ること。",
        en: "decoration; ornament",
        zh: "装饰；点缀",
        tw: "裝飾；點綴",
        ko: "장식",
        vi: "trang trí; đồ trang trí",
        th: "การประดับ; เครื่องประดับตกแต่ง",
        my: "အလှဆင်ခြင်း; အလှပစ္စည်း",
        km: "ការតុបតែង; វត្ថុតុបតែង",
      },
      furigana: [
        {
          rb: "飾り",
          rt: "かざり",
        },
      ],
      kanjiInfo: [
        {
          char: "飾",
          on: ["ショク"],
          kun: ["かざ.る", "かざ.り"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 387,
      kanji: "貸し",
      reading: "かし",
      meanings: {
        ja: "貸していること。または借りを作らせたこと。",
        en: "loan; favor owed",
        zh: "借出；人情债",
        tw: "借出；人情債",
        ko: "빌려줌; 신세 (빚)",
        vi: "cho vay; ơn nợ",
        th: "การให้ยืม; บุญคุณที่ติดค้าง",
        my: "အမြန်ဒေဏ; အကျေးဇူးတင်ခြင်း",
        km: "ការខ្ចីឲ្យ; បំណុលគុណ",
      },
      furigana: [
        {
          rb: "貸し",
          rt: "かし",
        },
      ],
      kanjiInfo: [
        {
          char: "貸",
          on: ["タイ"],
          kun: ["か.す", "か.し-", "かし-"],
          strokes: 12,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 388,
      kanji: "菓子",
      reading: "かし",
      meanings: {
        ja: "砂糖などを使った甘い食べ物。",
        en: "confectionery; sweets",
        zh: "点心；甜食",
        tw: "點心；甜食",
        ko: "과자",
        vi: "bánh kẹo",
        th: "ขนมหวาน",
        my: "မုန့်များ; ချိုဟင်း",
        km: "នំផ្អែម; ភេសជ្ជៈផ្អែម",
      },
      furigana: [
        {
          rb: "菓子",
          rt: "かし",
        },
      ],
      kanjiInfo: [
        {
          char: "菓",
          on: ["カ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 389,
      kanji: "家事",
      reading: "かじ",
      meanings: {
        ja: "家で行う日常の作業。",
        en: "housework; household chores",
        zh: "家务",
        tw: "家務",
        ko: "가사일",
        vi: "việc nhà",
        th: "งานบ้าน",
        my: "အိမ်အလုပ်",
        km: "ការងារផ្ទះ",
      },
      furigana: [
        {
          rb: "家事",
          rt: "かじ",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 390,
      kanji: "歌手",
      reading: "かしゅ",
      meanings: {
        ja: "歌を職業として歌う人。",
        en: "singer",
        zh: "歌手",
        tw: "歌手",
        ko: "가수",
        vi: "ca sĩ",
        th: "นักร้อง",
        my: "အဆိုတော်",
        km: "អ្នកចម្រៀង",
      },
      furigana: [
        {
          rb: "歌手",
          rt: "かしゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "歌",
          on: ["カ"],
          kun: ["うた", "うた.う"],
          strokes: 14,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 391,
      kanji: "数",
      reading: "かず",
      meanings: {
        ja: "ものの多さ・数量。数字。",
        en: "number; quantity",
        zh: "数目；数量",
        tw: "數；數量",
        ko: "숫자; 수량",
        vi: "số; số lượng",
        th: "จำนวน",
        my: "အရေအတွက်; နံပါတ်",
        km: "ចំនួន; លេខ",
      },
      furigana: [
        {
          rb: "数",
          rt: "かず",
        },
      ],
      kanjiInfo: [
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 392,
      kanji: "型",
      reading: "かた",
      meanings: {
        ja: "形の種類。型式。型枠。",
        en: "type; pattern; mold",
        zh: "类型；样式；模具",
        tw: "類型；樣式；模型/模具",
        ko: "유형; 형식; 거푸집",
        vi: "kiểu; mẫu; khuôn",
        th: "แบบ; รูปแบบ; แม่พิมพ์",
        my: "အမျိုးအစား; နမူနာ; ဖုံ",
        km: "ប្រភេទ; លំនាំ; ពង្រាត់ (ម៉ូល្ត)",
      },
      furigana: [
        {
          rb: "型",
          rt: "かた",
        },
      ],
      kanjiInfo: [
        {
          char: "型",
          on: ["ケイ"],
          kun: ["かた", "-がた"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 393,
      kanji: "肩",
      reading: "かた",
      meanings: {
        ja: "首と腕の付け根の部分。",
        en: "shoulder",
        zh: "肩膀",
        tw: "肩膀",
        ko: "어깨",
        vi: "vai",
        th: "ไหล่",
        my: "ပခုံး",
        km: "ស្មា",
      },
      furigana: [
        {
          rb: "肩",
          rt: "かた",
        },
      ],
      kanjiInfo: [
        {
          char: "肩",
          on: ["ケン"],
          kun: ["かた"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 394,
      kanji: "方々",
      reading: "かたがた",
      meanings: {
        ja: "多くの人々（丁寧）。",
        en: "people; everyone (polite)",
        zh: "各位；诸位（敬称）",
        tw: "各位；諸位（敬稱）",
        ko: "여러 분들 (존칭)",
        vi: "quý vị; mọi người (lịch sự)",
        th: "ทุกท่าน (คำสุภาพ)",
        my: "လူကြီးမင်းများ; များစွာသော လူများ",
        km: "លោកអើយទាំងអស់គ្នា (បំរាប់សរសើរ)",
      },
      furigana: [
        {
          rb: "方々",
          rt: "かたがた",
        },
      ],
      kanjiInfo: [
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 395,
      kanji: "刀",
      reading: "かたな",
      meanings: {
        ja: "日本の片刃の剣。刀。",
        en: "sword (esp. Japanese single-edged)",
        zh: "刀（日本武士刀）",
        tw: "刀（日本刀）",
        ko: "칼 (일본도)",
        vi: "kiếm Nhật (katana)",
        th: "ดาบ (โดยเฉพาะดาบญี่ปุ่น)",
        my: "ကြိမ်တဆိုက်ဓား (ဂျပန် ဒါဘ)",
        km: "ដាវ (ជាពិសេស​ដាវជប៉ុន)",
      },
      furigana: [
        {
          rb: "刀",
          rt: "かたな",
        },
      ],
      kanjiInfo: [
        {
          char: "刀",
          on: ["トウ"],
          kun: ["かたな", "そり"],
          strokes: 2,
          grade: 2,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 396,
      kanji: "勝ち",
      reading: "かち",
      meanings: {
        ja: "勝つこと。勝利。",
        en: "win; victory",
        zh: "胜利；赢",
        tw: "勝利；贏",
        ko: "승리",
        vi: "chiến thắng",
        th: "ชัยชนะ",
        my: "အောင်ပွဲ",
        km: "ជ័យជម្នះ",
      },
      furigana: [
        {
          rb: "勝ち",
          rt: "かち",
        },
      ],
      kanjiInfo: [
        {
          char: "勝",
          on: ["ショウ"],
          kun: ["か.つ", "-が.ち", "まさ.る", "すぐ.れる", "かつ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 397,
      kanji: "価値",
      reading: "かち",
      meanings: {
        ja: "どれだけ重要・有用かという度合い。",
        en: "value; worth",
        zh: "价值",
        tw: "價值",
        ko: "가치",
        vi: "giá trị",
        th: "คุณค่า; มูลค่า",
        my: "တန်ဖိုး",
        km: "តម្លៃ; គុណតម្លៃ",
      },
      furigana: [
        {
          rb: "価値",
          rt: "かち",
        },
      ],
      kanjiInfo: [
        {
          char: "価",
          on: ["カ", "ケ"],
          kun: ["あたい"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "値",
          on: ["チ"],
          kun: ["ね", "あたい"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 398,
      kanji: "活気",
      reading: "かっき",
      meanings: {
        ja: "生き生きとした勢い。にぎわい。",
        en: "liveliness; vigor; bustle",
        zh: "活力；生气；热闹",
        tw: "活力；朝氣；熱鬧",
        ko: "활기",
        vi: "sinh khí; sôi động",
        th: "ความคึกคัก; มีชีวิตชีวา",
        my: "လှုပ်ရှားစွာရှိမှု; ရွှင်လန်းမှု",
        km: "សកម្មភាពក្លៀវក្លា; រវល់រវល់",
      },
      furigana: [
        {
          rb: "活気",
          rt: "かっき",
        },
      ],
      kanjiInfo: [
        {
          char: "活",
          on: ["カツ"],
          kun: ["い.きる", "い.かす", "い.ける"],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 399,
      kanji: "楽器",
      reading: "がっき",
      meanings: {
        ja: "音楽を奏する道具。",
        en: "musical instrument",
        zh: "乐器",
        tw: "樂器",
        ko: "악기",
        vi: "nhạc cụ",
        th: "เครื่องดนตรี",
        my: "တူရိယာ",
        km: "ឧបករណ៍តន្ត្រី",
      },
      furigana: [
        {
          rb: "楽器",
          rt: "がっき",
        },
      ],
      kanjiInfo: [
        {
          char: "楽",
          on: ["ガク", "ラク", "ゴウ"],
          kun: ["たの.しい", "たの.しむ", "この.む"],
          strokes: 13,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 400,
      kanji: "学期",
      reading: "がっき",
      meanings: {
        ja: "学校の授業の区切りとなる期間。",
        en: "school term; semester",
        zh: "学期；学段",
        tw: "學期；學段",
        ko: "학기",
        vi: "học kỳ",
        th: "ภาคการศึกษา; เทอม",
        my: "သင်တန်းကာလ; ဆယ်မီစတာ",
        km: "វគ្គសិក្សា; ឆមាសសិក្សា",
      },
      furigana: [
        {
          rb: "学期",
          rt: "がっき",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
