export const n3part35 = {
  Lesson35: [
    {
      id: 1966,
      kanji: "蒔く",
      reading: "まく",
      meanings: {
        ja: "蒔く",
        en: "to sow (seeds)",
        zh: "播种",
        tw: "播種",
        ko: "씨를 뿌리다",
        vi: "gieo hạt",
        th: "หว่านเมล็ด",
        my: "စပါးပျိုး",
        km: "សាបព្រោះ",
      },
      furigana: [
        {
          rb: "蒔く",
          rt: "まく",
        },
      ],
      kanjiInfo: [
        {
          char: "蒔",
          on: ["シ", "ジ"],
          kun: ["う.える", "ま.く"],
          strokes: 13,
          grade: 9,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1967,
      kanji: "撒く",
      reading: "まく",
      meanings: {
        ja: "撒く",
        en: "to scatter; to sprinkle",
        zh: "撒",
        tw: "撒",
        ko: "뿌리다",
        vi: "rải",
        th: "โปรย",
        my: "ချ",
        km: "បោះ",
      },
      furigana: [
        {
          rb: "撒く",
          rt: "まく",
        },
      ],
      kanjiInfo: [
        {
          char: "撒",
          on: ["サン", "サツ"],
          kun: ["ま.く"],
          strokes: 15,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1968,
      kanji: "混ざる",
      reading: "まざる",
      meanings: {
        ja: "混ざる",
        en: "to be mixed",
        zh: "混合",
        tw: "混合",
        ko: "섞이다",
        vi: "bị trộn",
        th: "ผสม",
        my: "ရော",
        km: "លាយ",
      },
      furigana: [
        {
          rb: "混ざる",
          rt: "まざる",
        },
      ],
      kanjiInfo: [
        {
          char: "混",
          on: ["コン"],
          kun: ["ま.じる", "-ま.じり", "ま.ざる", "ま.ぜる", "こ.む"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1969,
      kanji: "交ざる",
      reading: "まざる",
      meanings: {
        ja: "交ざる",
        en: "to be mixed",
        zh: "混杂",
        tw: "混雜",
        ko: "섞이다",
        vi: "bị xen lẫn",
        th: "ปน",
        my: "ပေါင်း",
        km: "ច្របល់",
      },
      furigana: [
        {
          rb: "交ざる",
          rt: "まざる",
        },
      ],
      kanjiInfo: [
        {
          char: "交",
          on: ["コウ"],
          kun: [
            "まじ.わる",
            "まじ.える",
            "ま.じる",
            "まじ.る",
            "ま.ざる",
            "ま.ぜる",
            "-か.う",
            "か.わす",
            "かわ.す",
            "こもごも",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1970,
      kanji: "混じる",
      reading: "まじる",
      meanings: {
        ja: "混じる",
        en: "to be mixed; to mingle",
        zh: "混合",
        tw: "混合",
        ko: "섞이다",
        vi: "trộn lẫn",
        th: "ผสม",
        my: "ရောထွေး",
        km: "លាយចូល",
      },
      furigana: [
        {
          rb: "混じる",
          rt: "まじる",
        },
      ],
      kanjiInfo: [
        {
          char: "混",
          on: ["コン"],
          kun: ["ま.じる", "-ま.じり", "ま.ざる", "ま.ぜる", "こ.む"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1971,
      kanji: "交じる",
      reading: "まじる",
      meanings: {
        ja: "交じる",
        en: "to be mixed; to associate",
        zh: "交杂",
        tw: "交雜",
        ko: "섞이다",
        vi: "hòa lẫn",
        th: "คละเคล้า",
        my: "ပေါင်းသင်း",
        km: "ចូលរួម",
      },
      furigana: [
        {
          rb: "交じる",
          rt: "まじる",
        },
      ],
      kanjiInfo: [
        {
          char: "交",
          on: ["コウ"],
          kun: [
            "まじ.わる",
            "まじ.える",
            "ま.じる",
            "まじ.る",
            "ま.ざる",
            "ま.ぜる",
            "-か.う",
            "か.わす",
            "かわ.す",
            "こもごも",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1972,
      kanji: "増す",
      reading: "ます",
      meanings: {
        ja: "増す",
        en: "to increase; to grow",
        zh: "增加",
        tw: "增加",
        ko: "늘다",
        vi: "tăng lên",
        th: "เพิ่มขึ้น",
        my: "တိုး",
        km: "បន្ថែម",
      },
      furigana: [
        {
          rb: "増す",
          rt: "ます",
        },
      ],
      kanjiInfo: [
        {
          char: "増",
          on: ["ゾウ"],
          kun: ["ま.す", "ま.し", "ふ.える", "ふ.やす"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1973,
      kanji: "マスター",
      reading: "マスター",
      meanings: {
        ja: "マスター",
        en: "to master; to learn",
        zh: "掌握",
        tw: "掌握",
        ko: "숙달하다",
        vi: "thành thạo",
        th: "เชี่ยวชาญ",
        my: "ကျွမ်းကျင်",
        km: "ជំនាញ",
      },
      furigana: [
        {
          rb: "マスター",
          rt: "マスター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1974,
      kanji: "混ぜる",
      reading: "まぜる",
      meanings: {
        ja: "混ぜる",
        en: "to mix",
        zh: "混合",
        tw: "混合",
        ko: "섞다",
        vi: "trộn",
        th: "ผสม",
        my: "ရောစပ်",
        km: "លាយ",
      },
      furigana: [
        {
          rb: "混ぜる",
          rt: "まぜる",
        },
      ],
      kanjiInfo: [
        {
          char: "混",
          on: ["コン"],
          kun: ["ま.じる", "-ま.じり", "ま.ざる", "ま.ぜる", "こ.む"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1975,
      kanji: "交ぜる",
      reading: "まぜる",
      meanings: {
        ja: "交ぜる",
        en: "to mix; to blend",
        zh: "搀和",
        tw: "攙和",
        ko: "섞다",
        vi: "pha trộn",
        th: "คลุกเคล้า",
        my: "ပေါင်းစပ်",
        km: "លាយបញ្ចូល",
      },
      furigana: [
        {
          rb: "交ぜる",
          rt: "まぜる",
        },
      ],
      kanjiInfo: [
        {
          char: "交",
          on: ["コウ"],
          kun: [
            "まじ.わる",
            "まじ.える",
            "ま.じる",
            "まじ.る",
            "ま.ざる",
            "ま.ぜる",
            "-か.う",
            "か.わす",
            "かわ.す",
            "こもごも",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1976,
      kanji: "学ぶ",
      reading: "まなぶ",
      meanings: {
        ja: "学ぶ",
        en: "to learn; to study",
        zh: "学习",
        tw: "學習",
        ko: "배우다",
        vi: "học tập",
        th: "เรียนรู้",
        my: "လေ့လာ",
        km: "រៀន",
      },
      furigana: [
        {
          rb: "学ぶ",
          rt: "まなぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1977,
      kanji: "招く",
      reading: "まねく",
      meanings: {
        ja: "招く",
        en: "to invite; to cause",
        zh: "招待；引起",
        tw: "招待；引起",
        ko: "초대하다; 일으키다",
        vi: "mời; gây ra",
        th: "เชิญ; ก่อให้เกิด",
        my: "ဖိတ်ကြား",
        km: "អញ្ជើញ",
      },
      furigana: [
        {
          rb: "招く",
          rt: "まねく",
        },
      ],
      kanjiInfo: [
        {
          char: "招",
          on: ["ショウ"],
          kun: ["まね.く"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1978,
      kanji: "裂ける",
      reading: "さける",
      meanings: {
        ja: "裂ける",
        en: "to split; to tear",
        zh: "裂开",
        tw: "裂開",
        ko: "찢어지다",
        vi: "rách",
        th: "ฉีกขาด",
        my: "ချိုးဖောက်",
        km: "ប្រេះ",
      },
      furigana: [
        {
          rb: "裂ける",
          rt: "さける",
        },
      ],
      kanjiInfo: [
        {
          char: "裂",
          on: ["レツ"],
          kun: ["さ.く", "さ.ける", "-ぎ.れ"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1979,
      kanji: "裁く",
      reading: "さばく",
      meanings: {
        ja: "裁く",
        en: "to judge; to try",
        zh: "审判",
        tw: "審判",
        ko: "재판하다",
        vi: "xét xử",
        th: "ตัดสิน",
        my: "တရားစီရင်",
        km: "វិនិច្ឆ័យ",
      },
      furigana: [
        {
          rb: "裁く",
          rt: "さばく",
        },
      ],
      kanjiInfo: [
        {
          char: "裁",
          on: ["サイ"],
          kun: ["た.つ", "さば.く"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1980,
      kanji: "擦る",
      reading: "する",
      meanings: {
        ja: "擦る",
        en: "to rub; to scrub",
        zh: "摩擦",
        tw: "摩擦",
        ko: "문지르다",
        vi: "chà xát",
        th: "ถู",
        my: "ပွတ်",
        km: "តិត",
      },
      furigana: [
        {
          rb: "擦る",
          rt: "する",
        },
      ],
      kanjiInfo: [
        {
          char: "擦",
          on: ["サツ"],
          kun: ["す.る", "す.れる", "-ず.れ", "こす.る", "こす.れる"],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1981,
      kanji: "沿う",
      reading: "そう",
      meanings: {
        ja: "沿う",
        en: "to run along; to follow",
        zh: "沿着",
        tw: "沿著",
        ko: "따르다",
        vi: "dọc theo",
        th: "เลียบ",
        my: "တလျောက်လိုက်",
        km: "តាម",
      },
      furigana: [
        {
          rb: "沿う",
          rt: "そう",
        },
      ],
      kanjiInfo: [
        {
          char: "沿",
          on: ["エン"],
          kun: ["そ.う", "-ぞ.い"],
          strokes: 8,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1982,
      kanji: "添う",
      reading: "そう",
      meanings: {
        ja: "添う",
        en: "to accompany; to meet (expectations)",
        zh: "陪伴；符合",
        tw: "陪伴；符合",
        ko: "따르다; 맞추다",
        vi: "đi cùng; đáp ứng",
        th: "ตาม; สนอง",
        my: "လိုက်ပါ",
        km: "បន្ថែម",
      },
      furigana: [
        {
          rb: "添う",
          rt: "そう",
        },
      ],
      kanjiInfo: [
        {
          char: "添",
          on: ["テン"],
          kun: ["そ.える", "そ.う"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1983,
      kanji: "高まる",
      reading: "たかまる",
      meanings: {
        ja: "高まる",
        en: "to rise; to increase",
        zh: "提高",
        tw: "提高",
        ko: "높아지다",
        vi: "tăng cao",
        th: "สูงขึ้น",
        my: "မြင့်မားလာ",
        km: "កើនឡើង",
      },
      furigana: [
        {
          rb: "高まる",
          rt: "たかまる",
        },
      ],
      kanjiInfo: [
        {
          char: "高",
          on: ["コウ"],
          kun: ["たか.い", "たか", "-だか", "たか.まる", "たか.める"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1984,
      kanji: "断つ",
      reading: "たつ",
      meanings: {
        ja: "断つ",
        en: "to cut off; to sever",
        zh: "切断",
        tw: "切斷",
        ko: "끊다",
        vi: "cắt đứt",
        th: "ตัดขาด",
        my: "ဖြတ်တောက်",
        km: "កាត់ផ្តាច់",
      },
      furigana: [
        {
          rb: "断つ",
          rt: "たつ",
        },
      ],
      kanjiInfo: [
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1985,
      kanji: "接ぐ",
      reading: "つぐ",
      meanings: {
        ja: "接ぐ",
        en: "to join; to graft",
        zh: "接合",
        tw: "接合",
        ko: "잇다",
        vi: "nối",
        th: "เชื่อมต่อ",
        my: "ဆက်စပ်",
        km: "ភ្ជាប់",
      },
      furigana: [
        {
          rb: "接ぐ",
          rt: "つぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "接",
          on: ["セツ", "ショウ"],
          kun: ["つ.ぐ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1986,
      kanji: "継ぐ",
      reading: "つぐ",
      meanings: {
        ja: "継ぐ",
        en: "to succeed; to inherit",
        zh: "继承",
        tw: "繼承",
        ko: "잇다",
        vi: "kế thừa",
        th: "สืบทอด",
        my: "ဆက်ခံ",
        km: "បន្សំ",
      },
      furigana: [
        {
          rb: "継ぐ",
          rt: "つぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "継",
          on: ["ケイ"],
          kun: ["つ.ぐ", "まま-"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1987,
      kanji: "摘む",
      reading: "つむ",
      meanings: {
        ja: "摘む",
        en: "to pick; to pluck",
        zh: "摘",
        tw: "摘",
        ko: "따다",
        vi: "hái",
        th: "เด็ด",
        my: "ခူး",
        km: "ប្រមូល",
      },
      furigana: [
        {
          rb: "摘む",
          rt: "つむ",
        },
      ],
      kanjiInfo: [
        {
          char: "摘",
          on: ["テキ"],
          kun: ["つ.む"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1988,
      kanji: "強まる",
      reading: "つよまる",
      meanings: {
        ja: "強まる",
        en: "to get strong",
        zh: "变强",
        tw: "變強",
        ko: "강해지다",
        vi: "mạnh lên",
        th: "แข็งแกร่งขึ้น",
        my: "အင်အားကြီးလာ",
        km: "ក្លាយជាខ្លាំង",
      },
      furigana: [
        {
          rb: "強まる",
          rt: "つよまる",
        },
      ],
      kanjiInfo: [
        {
          char: "強",
          on: ["キョウ", "ゴウ"],
          kun: ["つよ.い", "つよ.まる", "つよ.める", "し.いる", "こわ.い"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1989,
      kanji: "強める",
      reading: "つよめる",
      meanings: {
        ja: "強める",
        en: "to strengthen; to emphasize",
        zh: "加强",
        tw: "加強",
        ko: "강화하다",
        vi: "làm mạnh thêm",
        th: "เสริมแรง",
        my: "အားဖြည့်",
        km: "ពង្រឹង",
      },
      furigana: [
        {
          rb: "強める",
          rt: "つよめる",
        },
      ],
      kanjiInfo: [
        {
          char: "強",
          on: ["キョウ", "ゴウ"],
          kun: ["つよ.い", "つよ.まる", "つよ.める", "し.いる", "こわ.い"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1990,
      kanji: "問う",
      reading: "とう",
      meanings: {
        ja: "問う",
        en: "to ask; to inquire",
        zh: "询问",
        tw: "詢問",
        ko: "묻다",
        vi: "hỏi",
        th: "ถาม",
        my: "မေး",
        km: "សួរ",
      },
      furigana: [
        {
          rb: "問う",
          rt: "とう",
        },
      ],
      kanjiInfo: [
        {
          char: "問",
          on: ["モン"],
          kun: ["と.う", "と.い", "とん"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1991,
      kanji: "説く",
      reading: "とく",
      meanings: {
        ja: "説く",
        en: "to explain; to preach",
        zh: "说明",
        tw: "說明",
        ko: "설명하다",
        vi: "giải thích",
        th: "อธิบาย",
        my: "ရှင်းပြ",
        km: "ពន្យល់",
      },
      furigana: [
        {
          rb: "説く",
          rt: "とく",
        },
      ],
      kanjiInfo: [
        {
          char: "説",
          on: ["セツ", "ゼイ"],
          kun: ["と.く"],
          strokes: 14,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1992,
      kanji: "綴じる",
      reading: "とじる",
      meanings: {
        ja: "綴じる",
        en: "to bind (documents)",
        zh: "装订",
        tw: "裝訂",
        ko: "철하다",
        vi: "đóng tập",
        th: "เย็บเล่ม",
        my: "ချုပ်",
        km: "ចង",
      },
      furigana: [
        {
          rb: "綴じる",
          rt: "とじる",
        },
      ],
      kanjiInfo: [
        {
          char: "綴",
          on: ["テイ", "テツ", "テチ", "ゲツ"],
          kun: ["と.じる", "つづ.る", "つづり", "すみ.やか"],
          strokes: 14,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1993,
      kanji: "慣らす",
      reading: "ならす",
      meanings: {
        ja: "慣らす",
        en: "to accustom; to train",
        zh: "使习惯",
        tw: "使習慣",
        ko: "익숙하게 하다",
        vi: "làm quen",
        th: "ทำให้เคยชิน",
        my: "ကျင့်သား",
        km: "ឱ្យស្គាល់",
      },
      furigana: [
        {
          rb: "慣らす",
          rt: "ならす",
        },
      ],
      kanjiInfo: [
        {
          char: "慣",
          on: ["カン"],
          kun: ["な.れる", "な.らす"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1994,
      kanji: "馴らす",
      reading: "ならす",
      meanings: {
        ja: "馴らす",
        en: "to tame; to domesticate",
        zh: "驯养",
        tw: "馴養",
        ko: "길들이다",
        vi: "thuần hóa",
        th: "ฝึกเชื่อง",
        my: "ထိန်းသိမ်း",
        km: "ចិញ្ចឹម",
      },
      furigana: [
        {
          rb: "馴らす",
          rt: "ならす",
        },
      ],
      kanjiInfo: [
        {
          char: "馴",
          on: ["ジュン", "シュン", "クン"],
          kun: ["な.れる", "な.らす", "したが.う"],
          strokes: 13,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1995,
      kanji: "臨む",
      reading: "のぞむ",
      meanings: {
        ja: "臨む",
        en: "to face; to attend",
        zh: "面临",
        tw: "面臨",
        ko: "임하다",
        vi: "đối mặt",
        th: "เผชิญหน้า",
        my: "ကြုံတွေ့",
        km: "ប្រឈម",
      },
      furigana: [
        {
          rb: "臨む",
          rt: "のぞむ",
        },
      ],
      kanjiInfo: [
        {
          char: "臨",
          on: ["リン"],
          kun: ["のぞ.む"],
          strokes: 18,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1996,
      kanji: "映える",
      reading: "はえる",
      meanings: {
        ja: "映える",
        en: "to shine; to look attractive",
        zh: "照耀；显眼",
        tw: "照耀；顯眼",
        ko: "빛나다",
        vi: "tỏa sáng",
        th: "โดดเด่น",
        my: "အလင်းပွင့်",
        km: "រះ",
      },
      furigana: [
        {
          rb: "映える",
          rt: "はえる",
        },
      ],
      kanjiInfo: [
        {
          char: "映",
          on: ["エイ"],
          kun: ["うつ.る", "うつ.す", "は.える", "-ば.え"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1997,
      kanji: "諮る",
      reading: "はかる",
      meanings: {
        ja: "諮る",
        en: "to consult; to discuss",
        zh: "商议",
        tw: "商議",
        ko: "의논하다",
        vi: "tham khảo ý kiến",
        th: "ปรึกษา",
        my: "တိုင်ပင်",
        km: "ពិភាក្សា",
      },
      furigana: [
        {
          rb: "諮る",
          rt: "はかる",
        },
      ],
      kanjiInfo: [
        {
          char: "諮",
          on: ["シ"],
          kun: ["はか.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1998,
      kanji: "図る",
      reading: "はかる",
      meanings: {
        ja: "図る",
        en: "to plan; to devise",
        zh: "计划",
        tw: "計畫",
        ko: "계획하다",
        vi: "lập kế hoạch",
        th: "วางแผน",
        my: "အစီအစဉ်ချ",
        km: "រៀបចំ",
      },
      furigana: [
        {
          rb: "図る",
          rt: "はかる",
        },
      ],
      kanjiInfo: [
        {
          char: "図",
          on: ["ズ", "ト"],
          kun: ["え", "はか.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1999,
      kanji: "生やす",
      reading: "はやす",
      meanings: {
        ja: "生やす",
        en: "to grow; to cultivate",
        zh: "使生长",
        tw: "使生長",
        ko: "기르게 하다",
        vi: "nuôi trồng",
        th: "เพาะเลี้ยง",
        my: "ပေါက်စေ",
        km: "ដាំ",
      },
      furigana: [
        {
          rb: "生やす",
          rt: "はやす",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2000,
      kanji: "広まる",
      reading: "ひろまる",
      meanings: {
        ja: "広まる",
        en: "to spread; to become popular",
        zh: "传播",
        tw: "傳播",
        ko: "퍼지다",
        vi: "lan rộng",
        th: "แพร่หลาย",
        my: "ပြန့်ပွား",
        km: "រីករាលដាល",
      },
      furigana: [
        {
          rb: "広まる",
          rt: "ひろまる",
        },
      ],
      kanjiInfo: [
        {
          char: "広",
          on: ["コウ"],
          kun: ["ひろ.い", "ひろ.まる", "ひろ.める", "ひろ.がる", "ひろ.げる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2001,
      kanji: "深める",
      reading: "ふかめる",
      meanings: {
        ja: "深める",
        en: "to deepen; to heighten",
        zh: "加深",
        tw: "加深",
        ko: "깊게 하다",
        vi: "làm sâu thêm",
        th: "ทำให้ลึก",
        my: "နက်စေ",
        km: "ធ្វើឱ្យជ្រៅ",
      },
      furigana: [
        {
          rb: "深める",
          rt: "ふかめる",
        },
      ],
      kanjiInfo: [
        {
          char: "深",
          on: ["シン"],
          kun: ["ふか.い", "-ぶか.い", "ふか.まる", "ふか.める", "み-"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2002,
      kanji: "経る",
      reading: "へる",
      meanings: {
        ja: "経る",
        en: "to pass; to go through",
        zh: "经过",
        tw: "經過",
        ko: "경과하다",
        vi: "trải qua",
        th: "ผ่าน",
        my: "ကြုံခဲ့",
        km: "ឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "経る",
          rt: "へる",
        },
      ],
      kanjiInfo: [
        {
          char: "経",
          on: ["ケイ", "キョウ", "キン"],
          kun: ["へ.る", "た.つ", "たていと", "はか.る", "のり"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2003,
      kanji: "見掛ける",
      reading: "みかける",
      meanings: {
        ja: "見掛ける",
        en: "to happen to see",
        zh: "看见",
        tw: "看見",
        ko: "우연히 보다",
        vi: "tình cờ thấy",
        th: "เห็นโดยบังเอิญ",
        my: "တွေ့မိ",
        km: "ឃើញចៃដន្យ",
      },
      furigana: [
        {
          rb: "見掛ける",
          rt: "みかける",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "掛",
          on: ["カイ", "ケイ"],
          kun: [
            "か.ける",
            "-か.ける",
            "か.け",
            "-か.け",
            "-が.け",
            "か.かる",
            "-か.かる",
            "-が.かる",
            "か.かり",
            "-が.かり",
            "かかり",
            "-がかり",
          ],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2004,
      kanji: "捲る",
      reading: "めくる",
      meanings: {
        ja: "捲る",
        en: "to turn over (pages)",
        zh: "翻页",
        tw: "翻頁",
        ko: "넘기다",
        vi: "lật trang",
        th: "เปิดหน้า",
        my: "စာရွက်လှန်",
        km: "បិទបើកទំព័រ",
      },
      furigana: [
        {
          rb: "捲る",
          rt: "めくる",
        },
      ],
      kanjiInfo: [
        {
          char: "捲",
          on: ["ケン"],
          kun: ["ま.く", "ま.くる", "まく.る", "めく.る", "まく.れる"],
          strokes: 11,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 2005,
      kanji: "弱まる",
      reading: "よわまる",
      meanings: {
        ja: "弱まる",
        en: "to weaken; to abate",
        zh: "减弱",
        tw: "減弱",
        ko: "약해지다",
        vi: "yếu đi",
        th: "อ่อนลง",
        my: "အားနည်းလာ",
        km: "ខ្សោយ",
      },
      furigana: [
        {
          rb: "弱まる",
          rt: "よわまる",
        },
      ],
      kanjiInfo: [
        {
          char: "弱",
          on: ["ジャク"],
          kun: ["よわ.い", "よわ.る", "よわ.まる", "よわ.める"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2006,
      kanji: "弱める",
      reading: "よわめる",
      meanings: {
        ja: "弱める",
        en: "to weaken; to make weak",
        zh: "削弱",
        tw: "削弱",
        ko: "약화시키다",
        vi: "làm yếu",
        th: "ทำให้อ่อนแอ",
        my: "အင်အားလျော့",
        km: "បន្ថយកម្លាំង",
      },
      furigana: [
        {
          rb: "弱める",
          rt: "よわめる",
        },
      ],
      kanjiInfo: [
        {
          char: "弱",
          on: ["ジャク"],
          kun: ["よわ.い", "よわ.る", "よわ.まる", "よわ.める"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
