export const n3part15 = {
  Lesson15: [
    {
      id: 701,
      kanji: "芽",
      reading: "め",
      meanings: {
        ja: "芽",
        en: "sprout; bud",
        zh: "芽; 萌芽",
        tw: "芽; 萌芽",
        ko: "싹; 새싹",
        vi: "mầm; chồi",
        th: "หน่อ; ตา",
        my: "မုကျောင်း",
        km: "មេគល់; តំណើម",
      },
      furigana: [
        {
          rb: "芽",
          rt: "め",
        },
      ],
      kanjiInfo: [
        {
          char: "芽",
          on: ["ガ"],
          kun: ["め"],
          strokes: 8,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 702,
      kanji: "名刺",
      reading: "めいし",
      meanings: {
        ja: "名刺",
        en: "business card",
        zh: "名片",
        tw: "名片",
        ko: "명함",
        vi: "danh thiếp",
        th: "นามบัตร",
        my: "လုပ်ငန်းကဒ်",
        km: "កាតសំណេះសំណាល",
      },
      furigana: [
        {
          rb: "名刺",
          rt: "めいし",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "刺",
          on: ["シ"],
          kun: ["さ.す", "さ.さる", "さ.し", "さし", "とげ"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 703,
      kanji: "名詞",
      reading: "めいし",
      meanings: {
        ja: "名詞",
        en: "noun",
        zh: "名词",
        tw: "名詞",
        ko: "명사",
        vi: "danh từ",
        th: "คำนาม",
        my: "နာမ်စု",
        km: "នាម",
      },
      furigana: [
        {
          rb: "名詞",
          rt: "めいし",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 704,
      kanji: "名人",
      reading: "めいじん",
      meanings: {
        ja: "名人",
        en: "master; expert",
        zh: "名家; 行家",
        tw: "名家; 行家",
        ko: "명인; 달인",
        vi: "cao thủ; chuyên gia",
        th: "ผู้เชี่ยวชาญ",
        my: "ကျွမ်းကျင်ပညာရှင်",
        km: "អ្នកជំនាញ",
      },
      furigana: [
        {
          rb: "名人",
          rt: "めいじん",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 705,
      kanji: "命令",
      reading: "めいれい",
      meanings: {
        ja: "命令",
        en: "order; command",
        zh: "命令",
        tw: "命令",
        ko: "명령",
        vi: "mệnh lệnh",
        th: "คำสั่ง",
        my: "အမိန့်",
        km: "បញ្ជា",
      },
      furigana: [
        {
          rb: "命令",
          rt: "めいれい",
        },
      ],
      kanjiInfo: [
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "令",
          on: ["レイ"],
          kun: [],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 706,
      kanji: "迷惑",
      reading: "めいわく",
      meanings: {
        ja: "迷惑",
        en: "trouble; nuisance",
        zh: "麻烦; 困扰",
        tw: "麻煩; 困擾",
        ko: "폐; 성가심",
        vi: "phiền toái",
        th: "ความรบกวน",
        my: "အနှောက်အနှေး",
        km: "ការខកខាន; លំបាក",
      },
      furigana: [
        {
          rb: "迷惑",
          rt: "めいわく",
        },
      ],
      kanjiInfo: [
        {
          char: "迷",
          on: ["メイ"],
          kun: ["まよ.う"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "惑",
          on: ["ワク"],
          kun: ["まど.う"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 707,
      kanji: "目上",
      reading: "めうえ",
      meanings: {
        ja: "目上（年長者・上司）",
        en: "one's superior; elder",
        zh: "长辈; 上级",
        tw: "長輩; 上司",
        ko: "윗사람",
        vi: "bề trên; cấp trên",
        th: "ผู้ใหญ่; ผู้บังคับบัญชา",
        my: "မိဘကြီး; အထက်လူကြီး",
        km: "មនុស្សជាន់លើ",
      },
      furigana: [
        {
          rb: "目上",
          rt: "めうえ",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 708,
      kanji: "飯",
      reading: "めし",
      meanings: {
        ja: "飯（めし）",
        en: "cooked rice; meal",
        zh: "饭; 餐",
        tw: "飯; 餐",
        ko: "밥; 식사",
        vi: "cơm; bữa ăn",
        th: "ข้าว; มื้ออาหาร",
        my: "ထမင်း; အစားအစာ",
        km: "បាយ; អាហារ",
      },
      furigana: [
        {
          rb: "飯",
          rt: "めし",
        },
      ],
      kanjiInfo: [
        {
          char: "飯",
          on: ["ハン"],
          kun: ["めし"],
          strokes: 12,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 709,
      kanji: "メモ",
      reading: "メモ",
      meanings: {
        ja: "メモ",
        en: "note; memo",
        zh: "便条; 备忘",
        tw: "便條; 備忘",
        ko: "메모",
        vi: "ghi chú",
        th: "บันทึกย่อ",
        my: "မှတ်စု",
        km: "ចំណាំ",
      },
      furigana: [
        {
          rb: "メモ",
          rt: "メモ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 710,
      kanji: "面",
      reading: "めん",
      meanings: {
        ja: "面（おも）; 側面",
        en: "face; surface; aspect",
        zh: "面; 表面; 方面",
        tw: "面; 表面; 方面",
        ko: "면; 표면; 측면",
        vi: "mặt; bề mặt; phương diện",
        th: "ด้าน; ผิวหน้า",
        my: "မျက်နှာပြင်; ကျိုးကြောင်း",
        km: "ផ្ទៃ; ជ្រុង",
      },
      furigana: [
        {
          rb: "面",
          rt: "めん",
        },
      ],
      kanjiInfo: [
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 711,
      kanji: "綿",
      reading: "めん",
      meanings: {
        ja: "綿（わた）; コットン",
        en: "cotton",
        zh: "棉花; 棉质",
        tw: "棉花; 棉質",
        ko: "면; 솜",
        vi: "bông; vải cotton",
        th: "ฝ้าย; ผ้าฝ้าย",
        my: "ပုတ်ပိုး; ကော့တုံး",
        km: "កប្បាស",
      },
      furigana: [
        {
          rb: "綿",
          rt: "めん",
        },
      ],
      kanjiInfo: [
        {
          char: "綿",
          on: ["メン"],
          kun: ["わた"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 712,
      kanji: "免許",
      reading: "めんきょ",
      meanings: {
        ja: "免許",
        en: "license; permit",
        zh: "执照; 许可证",
        tw: "執照; 許可證",
        ko: "면허",
        vi: "giấy phép; bằng",
        th: "ใบอนุญาต",
        my: "လိုင်စင်",
        km: "បណ្ណអនុញ្ញាត",
      },
      furigana: [
        {
          rb: "免許",
          rt: "めんきょ",
        },
      ],
      kanjiInfo: [
        {
          char: "免",
          on: ["メン"],
          kun: ["まぬか.れる", "まぬが.れる"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "許",
          on: ["キョ"],
          kun: ["ゆる.す", "もと"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 713,
      kanji: "面接",
      reading: "めんせつ",
      meanings: {
        ja: "面接",
        en: "interview (job etc.)",
        zh: "面试",
        tw: "面試",
        ko: "면접",
        vi: "phỏng vấn",
        th: "สัมภาษณ์",
        my: "မေးမြန်းစစ်ဆေးခြင်း",
        km: "សម្ភាសន៍",
      },
      furigana: [
        {
          rb: "面接",
          rt: "めんせつ",
        },
      ],
      kanjiInfo: [
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "接",
          on: ["セツ", "ショウ"],
          kun: ["つ.ぐ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 714,
      kanji: "面倒",
      reading: "めんどう",
      meanings: {
        ja: "面倒",
        en: "trouble; hassle; care",
        zh: "麻烦; 照料",
        tw: "麻煩; 照料",
        ko: "번거로움; 보살핌",
        vi: "phiền phức; chăm sóc",
        th: "ความยุ่งยาก; การดูแล",
        my: "အလုပ်ရှုပ်; စောင့်ရှောက်မှု",
        km: "ធ្វើឲ្យលំបាក; ថែកទាំ",
      },
      furigana: [
        {
          rb: "面倒",
          rt: "めんどう",
        },
      ],
      kanjiInfo: [
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "倒",
          on: ["トウ"],
          kun: [
            "たお.れる",
            "-だお.れ",
            "たお.す",
            "さかさま",
            "さかさ",
            "さかしま",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 715,
      kanji: "メンバー",
      reading: "メンバー",
      meanings: {
        ja: "メンバー",
        en: "member",
        zh: "成员",
        tw: "成員",
        ko: "멤버; 구성원",
        vi: "thành viên",
        th: "สมาชิก",
        my: "အဖွဲ့ဝင်",
        km: "សមាជិក",
      },
      furigana: [
        {
          rb: "メンバー",
          rt: "メンバー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 716,
      kanji: "申し訳",
      reading: "もうしわけ",
      meanings: {
        ja: "申し訳",
        en: "apology; excuse",
        zh: "歉意; 抱歉",
        tw: "歉意; 抱歉",
        ko: "변명; 사과",
        vi: "lời xin lỗi",
        th: "คำขอโทษ",
        my: "တောင်းပန်စကား",
        km: "ការសូមទោស",
      },
      furigana: [
        {
          rb: "申し訳",
          rt: "もうしわけ",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "訳",
          on: ["ヤク"],
          kun: ["わけ"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 717,
      kanji: "毛布",
      reading: "もうふ",
      meanings: {
        ja: "毛布",
        en: "blanket",
        zh: "毛毯",
        tw: "毛毯",
        ko: "담요",
        vi: "chăn bông",
        th: "ผ้าห่ม",
        my: "ဖောင်းထည်",
        km: "កំចាត់ត្រជាក់",
      },
      furigana: [
        {
          rb: "毛布",
          rt: "もうふ",
        },
      ],
      kanjiInfo: [
        {
          char: "毛",
          on: ["モウ"],
          kun: ["け"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "布",
          on: ["フ", "ホ"],
          kun: ["ぬの", "し.く", "きれ"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 718,
      kanji: "目的",
      reading: "もくてき",
      meanings: {
        ja: "目的",
        en: "purpose; aim",
        zh: "目的",
        tw: "目的",
        ko: "목적",
        vi: "mục đích",
        th: "วัตถุประสงค์",
        my: "ရည်ရွယ်ချက်",
        km: "គោលបំណង",
      },
      furigana: [
        {
          rb: "目的",
          rt: "もくてき",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "的",
          on: ["テキ"],
          kun: ["まと"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 719,
      kanji: "目標",
      reading: "もくひょう",
      meanings: {
        ja: "目標",
        en: "goal; target",
        zh: "目标",
        tw: "目標",
        ko: "목표",
        vi: "mục tiêu",
        th: "เป้าหมาย",
        my: "ပန်းတိုင်",
        km: "គោលដៅ",
      },
      furigana: [
        {
          rb: "目標",
          rt: "もくひょう",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "標",
          on: ["ヒョウ"],
          kun: ["しるべ", "しるし"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 720,
      kanji: "文字",
      reading: "もじ",
      meanings: {
        ja: "文字（もじ）",
        en: "letter; character",
        zh: "文字; 字母",
        tw: "文字; 字母",
        ko: "문자; 글자",
        vi: "chữ; ký tự",
        th: "ตัวอักษร",
        my: "အက္ခရာ; စာလုံး",
        km: "អក្សរ",
      },
      furigana: [
        {
          rb: "文字",
          rt: "もじ",
        },
      ],
      kanjiInfo: [
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 721,
      kanji: "文字",
      reading: "もんじ",
      meanings: {
        ja: "文字（もんじ）",
        en: "letter; character",
        zh: "文字",
        tw: "文字",
        ko: "문자",
        vi: "chữ",
        th: "ตัวอักษร",
        my: "စာလုံး",
        km: "អក្សរ",
      },
      furigana: [
        {
          rb: "文字",
          rt: "もんじ",
        },
      ],
      kanjiInfo: [
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 722,
      kanji: "元",
      reading: "もと",
      meanings: {
        ja: "元（起源）",
        en: "origin; source",
        zh: "根源; 本源",
        tw: "根源; 本源",
        ko: "원천; 근원",
        vi: "nguồn gốc",
        th: "ต้นกำเนิด",
        my: "အမြစ်; ရင်းမြစ်",
        km: "ប្រភព",
      },
      furigana: [
        {
          rb: "元",
          rt: "もと",
        },
      ],
      kanjiInfo: [
        {
          char: "元",
          on: ["ゲン", "ガン"],
          kun: ["もと"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 723,
      kanji: "基",
      reading: "もと",
      meanings: {
        ja: "基（基盤）",
        en: "basis; foundation",
        zh: "基础; 根基",
        tw: "基礎; 根基",
        ko: "기초; 기반",
        vi: "nền tảng; cơ sở",
        th: "รากฐาน",
        my: "အခြေခံ; အုတ်မြစ်",
        km: "មូលដ្ឋាន",
      },
      furigana: [
        {
          rb: "基",
          rt: "もと",
        },
      ],
      kanjiInfo: [
        {
          char: "基",
          on: ["キ"],
          kun: ["もと", "もとい"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 724,
      kanji: "素",
      reading: "もと",
      meanings: {
        ja: "素（素材・素質）",
        en: "element; essence",
        zh: "素; 本质",
        tw: "素; 本質",
        ko: "소(素); 본질",
        vi: "tố chất; bản chất",
        th: "ธาตุแท้; แก่น",
        my: "အမြစ်အရင်း",
        km: "ធាតុដើម; សារៈសំខាន់",
      },
      furigana: [
        {
          rb: "素",
          rt: "もと",
        },
      ],
      kanjiInfo: [
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 725,
      kanji: "者",
      reading: "もの",
      meanings: {
        ja: "者（人）",
        en: "person; one",
        zh: "人; 者",
        tw: "人; 者",
        ko: "사람; 자",
        vi: "người; kẻ",
        th: "ผู้; คน",
        my: "လူ; သူ",
        km: "មនុស្ស; អ្នក",
      },
      furigana: [
        {
          rb: "者",
          rt: "もの",
        },
      ],
      kanjiInfo: [
        {
          char: "者",
          on: ["シャ"],
          kun: ["もの"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 726,
      kanji: "物音",
      reading: "ものおと",
      meanings: {
        ja: "物音",
        en: "(a) noise; sound",
        zh: "声响; 动静",
        tw: "聲響; 動靜",
        ko: "물소리; 기척",
        vi: "tiếng động",
        th: "เสียง (วัตถุ)",
        my: "အသံညဏ်",
        km: "សំឡេងរបស់របរ",
      },
      furigana: [
        {
          rb: "物音",
          rt: "ものおと",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "音",
          on: ["オン", "イン", "-ノン"],
          kun: ["おと", "ね"],
          strokes: 9,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 727,
      kanji: "物語",
      reading: "ものがたり",
      meanings: {
        ja: "物語",
        en: "story; tale",
        zh: "故事; 传说",
        tw: "故事; 故事集",
        ko: "이야기; 이야기책",
        vi: "truyện; câu chuyện",
        th: "เรื่องเล่า; นิทาน",
        my: "ပုံပြင်",
        km: "រឿងនិទាន",
      },
      furigana: [
        {
          rb: "物語",
          rt: "ものがたり",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 728,
      kanji: "物事",
      reading: "ものごと",
      meanings: {
        ja: "物事",
        en: "things; matters",
        zh: "事物; 事情",
        tw: "事物; 事情",
        ko: "일; 사물",
        vi: "sự việc; mọi điều",
        th: "เรื่องราว; สิ่งต่างๆ",
        my: "အရာရာ",
        km: "រឿងរ៉ាវ; សកម្មភាព",
      },
      furigana: [
        {
          rb: "物事",
          rt: "ものごと",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 729,
      kanji: "模様",
      reading: "もよう",
      meanings: {
        ja: "模様（パターン）",
        en: "pattern; design",
        zh: "花样; 图案",
        tw: "花樣; 圖案",
        ko: "무늬; 양식",
        vi: "hoa văn; kiểu mẫu",
        th: "ลวดลาย",
        my: "ပုံစံလက်ရာ",
        km: "លំនាំ",
      },
      furigana: [
        {
          rb: "模様",
          rt: "もよう",
        },
      ],
      kanjiInfo: [
        {
          char: "模",
          on: ["モ", "ボ"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "様",
          on: ["ヨウ", "ショウ"],
          kun: ["さま", "さん"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 730,
      kanji: "文句",
      reading: "もんく",
      meanings: {
        ja: "文句（不平）",
        en: "complaint; grumble",
        zh: "抱怨; 怨言",
        tw: "抱怨; 怨言",
        ko: "불평; 투덜거림",
        vi: "lời phàn nàn",
        th: "คำบ่น; ข้อร้องเรียน",
        my: "တိုင်ကြားချက်",
        km: "ពាក្យបណ្តឹង",
      },
      furigana: [
        {
          rb: "文句",
          rt: "もんく",
        },
      ],
      kanjiInfo: [
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "句",
          on: ["ク"],
          kun: [],
          strokes: 5,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 731,
      kanji: "役",
      reading: "やく",
      meanings: {
        ja: "役（役割）",
        en: "role; part",
        zh: "角色; 作用",
        tw: "角色; 作用",
        ko: "역; 역할",
        vi: "vai trò",
        th: "บทบาท",
        my: "တာဝန်ရဲ့အခန်းကဏ္ဍ",
        km: "តួនាទី",
      },
      furigana: [
        {
          rb: "役",
          rt: "やく",
        },
      ],
      kanjiInfo: [
        {
          char: "役",
          on: ["ヤク", "エキ"],
          kun: [],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 732,
      kanji: "訳",
      reading: "やく",
      meanings: {
        ja: "訳（翻訳）",
        en: "translation",
        zh: "翻译",
        tw: "翻譯",
        ko: "번역",
        vi: "bản dịch; dịch thuật",
        th: "คำแปล",
        my: "ဘာသာပြန်",
        km: "បកប្រែ",
      },
      furigana: [
        {
          rb: "訳",
          rt: "やく",
        },
      ],
      kanjiInfo: [
        {
          char: "訳",
          on: ["ヤク"],
          kun: ["わけ"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 733,
      kanji: "役割",
      reading: "やくわり",
      meanings: {
        ja: "役割",
        en: "part; role; assignment",
        zh: "角色; 职责",
        tw: "角色; 職責",
        ko: "역할; 임무",
        vi: "vai trò; nhiệm vụ",
        th: "บทบาท; หน้าที่",
        my: "တာဝန်ခန့်ထားမှု",
        km: "តួនាទី; ភារកិច្ច",
      },
      furigana: [
        {
          rb: "役割",
          rt: "やくわり",
        },
      ],
      kanjiInfo: [
        {
          char: "役",
          on: ["ヤク", "エキ"],
          kun: [],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "割",
          on: ["カツ"],
          kun: ["わ.る", "わり", "わ.り", "わ.れる", "さ.く"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 734,
      kanji: "家賃",
      reading: "やちん",
      meanings: {
        ja: "家賃",
        en: "rent (house/apartment)",
        zh: "房租",
        tw: "房租",
        ko: "집세; 월세",
        vi: "tiền thuê nhà",
        th: "ค่าเช่าบ้าน",
        my: "အိမ်ငှါးကြေး",
        km: "ថ្លៃជួលផ្ទះ",
      },
      furigana: [
        {
          rb: "家賃",
          rt: "やちん",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "賃",
          on: ["チン"],
          kun: [],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 735,
      kanji: "宿",
      reading: "やど",
      meanings: {
        ja: "宿; 宿泊先",
        en: "lodging; inn",
        zh: "住宿; 客栈",
        tw: "住宿; 客棧",
        ko: "숙소; 여관",
        vi: "nhà trọ; chỗ ở",
        th: "ที่พัก; โรงแรมเล็ก",
        my: "တည်းခိုရာ",
        km: "ទីស្នាក់ការ; ផ្ទះសំណាក់",
      },
      furigana: [
        {
          rb: "宿",
          rt: "やど",
        },
      ],
      kanjiInfo: [
        {
          char: "宿",
          on: ["シュク"],
          kun: ["やど", "やど.る", "やど.す"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 736,
      kanji: "屋根",
      reading: "やね",
      meanings: {
        ja: "屋根",
        en: "roof",
        zh: "屋顶",
        tw: "屋頂",
        ko: "지붕",
        vi: "mái nhà",
        th: "หลังคา",
        my: "အိမ်မိုး",
        km: "ដំបូល",
      },
      furigana: [
        {
          rb: "屋根",
          rt: "やね",
        },
      ],
      kanjiInfo: [
        {
          char: "屋",
          on: ["オク"],
          kun: ["や"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "根",
          on: ["コン"],
          kun: ["ね", "-ね"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 737,
      kanji: "勇気",
      reading: "ゆうき",
      meanings: {
        ja: "勇気",
        en: "courage",
        zh: "勇气",
        tw: "勇氣",
        ko: "용기",
        vi: "dũng khí; can đảm",
        th: "ความกล้าหาญ",
        my: "သတ္တိ",
        km: "កងរិះរឹង",
      },
      furigana: [
        {
          rb: "勇気",
          rt: "ゆうき",
        },
      ],
      kanjiInfo: [
        {
          char: "勇",
          on: ["ユウ"],
          kun: ["いさ.む"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 738,
      kanji: "友好",
      reading: "ゆうこう",
      meanings: {
        ja: "友好",
        en: "friendship; amity",
        zh: "友好",
        tw: "友好",
        ko: "우호",
        vi: "hữu hảo",
        th: "มิตรภาพ",
        my: "ချစ်ကြည်ရေး",
        km: "មិត្តភាព",
      },
      furigana: [
        {
          rb: "友好",
          rt: "ゆうこう",
        },
      ],
      kanjiInfo: [
        {
          char: "友",
          on: ["ユウ"],
          kun: ["とも"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 739,
      kanji: "優勝",
      reading: "ゆうしょう",
      meanings: {
        ja: "優勝",
        en: "overall victory; championship",
        zh: "优胜; 冠军",
        tw: "優勝; 冠軍",
        ko: "우승",
        vi: "vô địch; quán quân",
        th: "ชนะเลิศ",
        my: "အောင်လက်မှတ်ရ",
        km: "ជ័យលាភី",
      },
      furigana: [
        {
          rb: "優勝",
          rt: "ゆうしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "優",
          on: ["ユウ", "ウ"],
          kun: ["やさ.しい", "すぐ.れる", "まさ.る"],
          strokes: 17,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "勝",
          on: ["ショウ"],
          kun: ["か.つ", "-が.ち", "まさ.る", "すぐ.れる", "かつ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 740,
      kanji: "友情",
      reading: "ゆうじょう",
      meanings: {
        ja: "友情",
        en: "friendship",
        zh: "友情",
        tw: "友情",
        ko: "우정",
        vi: "tình bạn",
        th: "มิตรภาพ",
        my: "မိတ်ဆွေမှု",
        km: "មិត្តភាព",
      },
      furigana: [
        {
          rb: "友情",
          rt: "ゆうじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "友",
          on: ["ユウ"],
          kun: ["とも"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 741,
      kanji: "友人",
      reading: "ゆうじん",
      meanings: {
        ja: "友人",
        en: "friend",
        zh: "友人; 朋友",
        tw: "友人; 朋友",
        ko: "벗; 친구",
        vi: "bạn bè",
        th: "เพื่อน",
        my: "သူငယ်ချင်း",
        km: "មិត្ត",
      },
      furigana: [
        {
          rb: "友人",
          rt: "ゆうじん",
        },
      ],
      kanjiInfo: [
        {
          char: "友",
          on: ["ユウ"],
          kun: ["とも"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 742,
      kanji: "郵便",
      reading: "ゆうびん",
      meanings: {
        ja: "郵便",
        en: "mail service; post",
        zh: "邮政; 邮件",
        tw: "郵政; 郵件",
        ko: "우편",
        vi: "bưu điện; bưu phẩm",
        th: "ไปรษณีย์",
        my: "စာတိုက်ဝန်ဆောင်မှု",
        km: "ប្រៃសណីយ៍",
      },
      furigana: [
        {
          rb: "郵便",
          rt: "ゆうびん",
        },
      ],
      kanjiInfo: [
        {
          char: "郵",
          on: ["ユウ"],
          kun: [],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "便",
          on: ["ベン", "ビン"],
          kun: ["たよ.り"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 743,
      kanji: "ユーモア",
      reading: "ユーモア",
      meanings: {
        ja: "ユーモア",
        en: "humor",
        zh: "幽默",
        tw: "幽默",
        ko: "유머",
        vi: "hài hước",
        th: "อารมณ์ขัน",
        my: "ဟာသ",
        km: "កំប្លែង",
      },
      furigana: [
        {
          rb: "ユーモア",
          rt: "ユーモア",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 744,
      kanji: "床",
      reading: "ゆか",
      meanings: {
        ja: "床（ゆか）",
        en: "floor",
        zh: "地板; 地面",
        tw: "地板; 地面",
        ko: "바닥",
        vi: "sàn nhà",
        th: "พื้น",
        my: "ခြံမြေ",
        km: "ជាន់",
      },
      furigana: [
        {
          rb: "床",
          rt: "ゆか",
        },
      ],
      kanjiInfo: [
        {
          char: "床",
          on: ["ショウ"],
          kun: ["とこ", "ゆか"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 745,
      kanji: "夜",
      reading: "よ",
      meanings: {
        ja: "夜",
        en: "night",
        zh: "夜; 夜晚",
        tw: "夜; 夜晚",
        ko: "밤",
        vi: "đêm",
        th: "กลางคืน",
        my: "ည",
        km: "យប់",
      },
      furigana: [
        {
          rb: "夜",
          rt: "よ",
        },
      ],
      kanjiInfo: [
        {
          char: "夜",
          on: ["ヤ"],
          kun: ["よ", "よる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 746,
      kanji: "夜明け",
      reading: "よあけ",
      meanings: {
        ja: "夜明け",
        en: "dawn; daybreak",
        zh: "拂晓; 破晓",
        tw: "拂曉; 破曉",
        ko: "새벽; 동틀녘",
        vi: "rạng đông",
        th: "รุ่งสาง",
        my: "ရေတံခွန်အချိန်",
        km: "ព្រលឹម",
      },
      furigana: [
        {
          rb: "夜明け",
          rt: "よあけ",
        },
      ],
      kanjiInfo: [
        {
          char: "夜",
          on: ["ヤ"],
          kun: ["よ", "よる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 747,
      kanji: "容器",
      reading: "ようき",
      meanings: {
        ja: "容器",
        en: "container; vessel",
        zh: "容器; 器皿",
        tw: "容器; 器皿",
        ko: "용기",
        vi: "đồ chứa; bình",
        th: "ภาชนะ",
        my: "Containar/လိပ်ပုံး",
        km: "ឥវ៉ាន់ដាក់",
      },
      furigana: [
        {
          rb: "容器",
          rt: "ようき",
        },
      ],
      kanjiInfo: [
        {
          char: "容",
          on: ["ヨウ"],
          kun: ["い.れる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 748,
      kanji: "要求",
      reading: "ようきゅう",
      meanings: {
        ja: "要求",
        en: "demand; request",
        zh: "要求; 需求",
        tw: "要求; 需求",
        ko: "요구",
        vi: "yêu cầu; đòi hỏi",
        th: "การเรียกร้อง; ความต้องการ",
        my: "တောင်းဆိုချက်",
        km: "តម្រូវការ; ស្នើសុំ",
      },
      furigana: [
        {
          rb: "要求",
          rt: "ようきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "要",
          on: ["ヨウ"],
          kun: ["い.る", "かなめ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "求",
          on: ["キュウ", "グ"],
          kun: ["もと.める"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 749,
      kanji: "用心",
      reading: "ようじん",
      meanings: {
        ja: "用心（注意）",
        en: "care; caution",
        zh: "留神; 小心",
        tw: "留神; 小心",
        ko: "조심; 경계",
        vi: "cẩn thận; đề phòng",
        th: "ระวัง; รอบคอบ",
        my: "အရေးကြီးစဉ်းစား",
        km: "ប្រយ័ត្ន",
      },
      furigana: [
        {
          rb: "用心",
          rt: "ようじん",
        },
      ],
      kanjiInfo: [
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 750,
      kanji: "様子",
      reading: "ようす",
      meanings: {
        ja: "様子; 様子見",
        en: "state; condition; appearance",
        zh: "情况; 样子",
        tw: "情況; 樣子",
        ko: "상태; 모습",
        vi: "tình trạng; dáng vẻ",
        th: "สภาพ; ลักษณะ",
        my: "အနေအထား; အခြေအနေ",
        km: "សភាព; របៀប",
      },
      furigana: [
        {
          rb: "様子",
          rt: "ようす",
        },
      ],
      kanjiInfo: [
        {
          char: "様",
          on: ["ヨウ", "ショウ"],
          kun: ["さま", "さん"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
