export const n3part16 = {
  Lesson16: [
    {
      id: 751,
      kanji: "要素",
      reading: "ようそ",
      meanings: {
        ja: "要素",
        en: "component",
        zh: "要素",
        tw: "要素",
        ko: "요소",
        vi: "yếu tố",
        th: "องค์ประกอบ",
        my: "အစိတ်အပိုင်း",
        km: "ធាតុ",
      },
      furigana: [
        {
          rb: "要素",
          rt: "ようそ",
        },
      ],
      kanjiInfo: [
        {
          char: "要",
          on: ["ヨウ"],
          kun: ["い.る", "かなめ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 752,
      kanji: "要点",
      reading: "ようてん",
      meanings: {
        ja: "要点",
        en: "gist",
        zh: "要点",
        tw: "要點",
        ko: "요점",
        vi: "điểm chính",
        th: "ประเด็นสำคัญ",
        my: "အဓိကချက်",
        km: "ចំណុចសំខាន់",
      },
      furigana: [
        {
          rb: "要点",
          rt: "ようてん",
        },
      ],
      kanjiInfo: [
        {
          char: "要",
          on: ["ヨウ"],
          kun: ["い.る", "かなめ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 753,
      kanji: "曜日",
      reading: "ようび",
      meanings: {
        ja: "曜日",
        en: "day of the week",
        zh: "星期",
        tw: "星期",
        ko: "요일",
        vi: "thứ (ngày trong tuần)",
        th: "วันในสัปดาห์",
        my: "အပတ်နေ့",
        km: "ថ្ងៃក្នុងសប្តាហ៍",
      },
      furigana: [
        {
          rb: "曜日",
          rt: "ようび",
        },
      ],
      kanjiInfo: [
        {
          char: "曜",
          on: ["ヨウ"],
          kun: [],
          strokes: 18,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 754,
      kanji: "予期",
      reading: "よき",
      meanings: {
        ja: "予期",
        en: "expectation",
        zh: "预期",
        tw: "預期",
        ko: "예기",
        vi: "mong đợi",
        th: "ความคาดหวัง",
        my: "မျှော်လင့်ချက်",
        km: "ការរំពឹងទុក",
      },
      furigana: [
        {
          rb: "予期",
          rt: "よき",
        },
      ],
      kanjiInfo: [
        {
          char: "予",
          on: ["ヨ", "シャ"],
          kun: ["あらかじ.め"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 755,
      kanji: "予算",
      reading: "よさん",
      meanings: {
        ja: "予算",
        en: "budget",
        zh: "预算",
        tw: "預算",
        ko: "예산",
        vi: "ngân sách",
        th: "งบประมาณ",
        my: "ဘတ်ဂျက်",
        km: "ថវិកា",
      },
      furigana: [
        {
          rb: "予算",
          rt: "よさん",
        },
      ],
      kanjiInfo: [
        {
          char: "予",
          on: ["ヨ", "シャ"],
          kun: ["あらかじ.め"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 756,
      kanji: "予測",
      reading: "よそく",
      meanings: {
        ja: "予測",
        en: "prediction",
        zh: "预测",
        tw: "預測",
        ko: "예측",
        vi: "dự đoán",
        th: "การคาดการณ์",
        my: "ခန့်မှန်းချက်",
        km: "ការព្យាករ",
      },
      furigana: [
        {
          rb: "予測",
          rt: "よそく",
        },
      ],
      kanjiInfo: [
        {
          char: "予",
          on: ["ヨ", "シャ"],
          kun: ["あらかじ.め"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "測",
          on: ["ソク"],
          kun: ["はか.る"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 757,
      kanji: "ヨット",
      reading: "ヨット",
      meanings: {
        ja: "ヨット",
        en: "yacht",
        zh: "游艇",
        tw: "遊艇",
        ko: "요트",
        vi: "du thuyền",
        th: "เรือยอชต์",
        my: "ယော့",
        km: "នាវាយ៉ាត",
      },
      furigana: [
        {
          rb: "ヨット",
          rt: "ヨット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 758,
      kanji: "夜中",
      reading: "よなか",
      meanings: {
        ja: "夜中",
        en: "midnight",
        zh: "半夜",
        tw: "半夜",
        ko: "한밤중",
        vi: "nửa đêm",
        th: "เที่ยงคืน",
        my: "ညအလယ်",
        km: "អំឡុងអាធ្រាត្រ",
      },
      furigana: [
        {
          rb: "夜中",
          rt: "よなか",
        },
      ],
      kanjiInfo: [
        {
          char: "夜",
          on: ["ヤ"],
          kun: ["よ", "よる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 759,
      kanji: "予報",
      reading: "よほう",
      meanings: {
        ja: "予報",
        en: "forecast",
        zh: "预报",
        tw: "預報",
        ko: "예보",
        vi: "dự báo",
        th: "พยากรณ์",
        my: "ခန့်မှန်းစာ",
        km: "ការព្យាករ",
      },
      furigana: [
        {
          rb: "予報",
          rt: "よほう",
        },
      ],
      kanjiInfo: [
        {
          char: "予",
          on: ["ヨ", "シャ"],
          kun: ["あらかじ.め"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "報",
          on: ["ホウ"],
          kun: ["むく.いる"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 760,
      kanji: "予防",
      reading: "よぼう",
      meanings: {
        ja: "予防",
        en: "prevention",
        zh: "预防",
        tw: "預防",
        ko: "예방",
        vi: "phòng ngừa",
        th: "การป้องกัน",
        my: "ကာကွယ်မှု",
        km: "ការការពារ",
      },
      furigana: [
        {
          rb: "予防",
          rt: "よぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "予",
          on: ["ヨ", "シャ"],
          kun: ["あらかじ.め"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "防",
          on: ["ボウ"],
          kun: ["ふせ.ぐ"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 761,
      kanji: "読み",
      reading: "よみ",
      meanings: {
        ja: "読み",
        en: "reading",
        zh: "读音",
        tw: "讀音",
        ko: "읽기",
        vi: "cách đọc",
        th: "การอ่าน",
        my: "ဖတ်ခြင်း",
        km: "ការអាន",
      },
      furigana: [
        {
          rb: "読み",
          rt: "よみ",
        },
      ],
      kanjiInfo: [
        {
          char: "読",
          on: ["ドク", "トク", "トウ"],
          kun: ["よ.む", "-よ.み"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 762,
      kanji: "嫁",
      reading: "よめ",
      meanings: {
        ja: "嫁",
        en: "bride",
        zh: "新娘",
        tw: "新娘",
        ko: "며느리",
        vi: "cô dâu",
        th: "เจ้าสาว",
        my: "ဧည့်မိန်းမ",
        km: "ភរិយា",
      },
      furigana: [
        {
          rb: "嫁",
          rt: "よめ",
        },
      ],
      kanjiInfo: [
        {
          char: "嫁",
          on: ["カ"],
          kun: ["よめ", "とつ.ぐ", "い.く", "ゆ.く"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 763,
      kanji: "余裕",
      reading: "よゆう",
      meanings: {
        ja: "余裕",
        en: "surplus",
        zh: "余裕",
        tw: "餘裕",
        ko: "여유",
        vi: "dư dả",
        th: "ส่วนเกิน",
        my: "ပမာဏပို",
        km: "កំណត់លើស",
      },
      furigana: [
        {
          rb: "余裕",
          rt: "よゆう",
        },
      ],
      kanjiInfo: [
        {
          char: "余",
          on: ["ヨ"],
          kun: ["あま.る", "あま.り", "あま.す", "あんま.り"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "裕",
          on: ["ユウ"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 764,
      kanji: "喜び",
      reading: "よろこび",
      meanings: {
        ja: "喜び",
        en: "joy",
        zh: "喜悦",
        tw: "喜悅",
        ko: "기쁨",
        vi: "niềm vui",
        th: "ความสุข",
        my: "ပျော်ရွှင်မှု",
        km: "សេចក្តីអំណរ",
      },
      furigana: [
        {
          rb: "喜び",
          rt: "よろこび",
        },
      ],
      kanjiInfo: [
        {
          char: "喜",
          on: ["キ"],
          kun: ["よろこ.ぶ", "よろこ.ばす"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 765,
      kanji: "四",
      reading: "よん",
      meanings: {
        ja: "四",
        en: "four",
        zh: "四",
        tw: "四",
        ko: "넷",
        vi: "bốn",
        th: "สี่",
        my: "လေး",
        km: "បួន",
      },
      furigana: [
        {
          rb: "四",
          rt: "よん",
        },
      ],
      kanjiInfo: [
        {
          char: "四",
          on: ["シ"],
          kun: ["よ", "よ.つ", "よっ.つ", "よん"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 766,
      kanji: "ライター",
      reading: "ライター",
      meanings: {
        ja: "ライター",
        en: "lighter",
        zh: "打火机",
        tw: "打火機",
        ko: "라이터",
        vi: "bật lửa",
        th: "ไฟแช็ก",
        my: "မီးဖို",
        km: "បិទភ្លើង",
      },
      furigana: [
        {
          rb: "ライター",
          rt: "ライター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 767,
      kanji: "楽",
      reading: "らく",
      meanings: {
        ja: "楽",
        en: "comfort",
        zh: "舒适",
        tw: "舒適",
        ko: "편안함",
        vi: "thoải mái",
        th: "ความสบาย",
        my: "အဆင်ပြေမှု",
        km: "ភាពផាសុខភាព",
      },
      furigana: [
        {
          rb: "楽",
          rt: "らく",
        },
      ],
      kanjiInfo: [
        {
          char: "楽",
          on: ["ガク", "ラク", "ゴウ"],
          kun: ["たの.しい", "たの.しむ", "この.む"],
          strokes: 13,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 768,
      kanji: "ラケット",
      reading: "ラケット",
      meanings: {
        ja: "ラケット",
        en: "racket",
        zh: "球拍",
        tw: "球拍",
        ko: "라켓",
        vi: "vợt",
        th: "ไม้ตี",
        my: "ရాకက်",
        km: "រ៉ាកែត",
      },
      furigana: [
        {
          rb: "ラケット",
          rt: "ラケット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 769,
      kanji: "利益",
      reading: "りえき",
      meanings: {
        ja: "利益",
        en: "profit",
        zh: "利益",
        tw: "利益",
        ko: "이익",
        vi: "lợi ích",
        th: "กำไร",
        my: "အကျိုး",
        km: "ប្រាក់ចំណេញ",
      },
      furigana: [
        {
          rb: "利益",
          rt: "りえき",
        },
      ],
      kanjiInfo: [
        {
          char: "利",
          on: ["リ"],
          kun: ["き.く"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "益",
          on: ["エキ", "ヤク"],
          kun: ["ま.す"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 770,
      kanji: "理解",
      reading: "りかい",
      meanings: {
        ja: "理解",
        en: "understanding",
        zh: "理解",
        tw: "理解",
        ko: "이해",
        vi: "hiểu biết",
        th: "ความเข้าใจ",
        my: "နားလည်မှု",
        km: "ការយល់ដឹង",
      },
      furigana: [
        {
          rb: "理解",
          rt: "りかい",
        },
      ],
      kanjiInfo: [
        {
          char: "理",
          on: ["リ"],
          kun: ["ことわり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 771,
      kanji: "陸",
      reading: "りく",
      meanings: {
        ja: "陸",
        en: "land",
        zh: "陆地",
        tw: "陸地",
        ko: "육지",
        vi: "đất liền",
        th: "แผ่นดิน",
        my: "မြေကြီး",
        km: "ដីគោក",
      },
      furigana: [
        {
          rb: "陸",
          rt: "りく",
        },
      ],
      kanjiInfo: [
        {
          char: "陸",
          on: ["リク", "ロク"],
          kun: ["おか"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 772,
      kanji: "離婚",
      reading: "りこん",
      meanings: {
        ja: "離婚",
        en: "divorce",
        zh: "离婚",
        tw: "離婚",
        ko: "이혼",
        vi: "ly hôn",
        th: "การหย่า",
        my: "ဆွဲပေါ်ခြင်း",
        km: "ការលែងលះ",
      },
      furigana: [
        {
          rb: "離婚",
          rt: "りこん",
        },
      ],
      kanjiInfo: [
        {
          char: "離",
          on: ["リ"],
          kun: ["はな.れる", "はな.す"],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "婚",
          on: ["コン"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 773,
      kanji: "理想",
      reading: "りそう",
      meanings: {
        ja: "理想",
        en: "ideal",
        zh: "理想",
        tw: "理想",
        ko: "이상",
        vi: "lý tưởng",
        th: "อุดมคติ",
        my: "အိပ်မက်",
        km: "គោលដៅ",
      },
      furigana: [
        {
          rb: "理想",
          rt: "りそう",
        },
      ],
      kanjiInfo: [
        {
          char: "理",
          on: ["リ"],
          kun: ["ことわり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "想",
          on: ["ソウ", "ソ"],
          kun: ["おも.う"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 774,
      kanji: "率",
      reading: "りつ",
      meanings: {
        ja: "率",
        en: "rate",
        zh: "比率",
        tw: "比率",
        ko: "비율",
        vi: "tỉ lệ",
        th: "อัตรา",
        my: "နှုန်း",
        km: "អត្រា",
      },
      furigana: [
        {
          rb: "率",
          rt: "りつ",
        },
      ],
      kanjiInfo: [
        {
          char: "率",
          on: ["ソツ", "リツ", "シュツ"],
          kun: ["ひき.いる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 775,
      kanji: "留学",
      reading: "りゅうがく",
      meanings: {
        ja: "留学",
        en: "studying abroad",
        zh: "留学",
        tw: "留學",
        ko: "유학",
        vi: "du học",
        th: "เรียนต่างประเทศ",
        my: "နိုင်ငံခြားတွင်ပညာသင်",
        km: "សិក្សាក្រៅប្រទេស",
      },
      furigana: [
        {
          rb: "留学",
          rt: "りゅうがく",
        },
      ],
      kanjiInfo: [
        {
          char: "留",
          on: ["リュウ", "ル"],
          kun: ["と.める", "と.まる", "とど.める", "とど.まる", "るうぶる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 776,
      kanji: "流行",
      reading: "りゅうこう",
      meanings: {
        ja: "流行",
        en: "fashion",
        zh: "流行",
        tw: "流行",
        ko: "유행",
        vi: "thời trang",
        th: "แฟชั่น",
        my: "ဖက်ရှင်",
        km: "និន្នាការ",
      },
      furigana: [
        {
          rb: "流行",
          rt: "りゅうこう",
        },
      ],
      kanjiInfo: [
        {
          char: "流",
          on: ["リュウ", "ル"],
          kun: ["なが.れる", "なが.れ", "なが.す", "-なが.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 777,
      kanji: "量",
      reading: "りょう",
      meanings: {
        ja: "量",
        en: "quantity",
        zh: "数量",
        tw: "數量",
        ko: "양",
        vi: "số lượng",
        th: "ปริมาณ",
        my: "ပမာဏ",
        km: "បរិមាណ",
      },
      furigana: [
        {
          rb: "量",
          rt: "りょう",
        },
      ],
      kanjiInfo: [
        {
          char: "量",
          on: ["リョウ"],
          kun: ["はか.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 778,
      kanji: "寮",
      reading: "りょう",
      meanings: {
        ja: "寮",
        en: "dormitory",
        zh: "宿舍",
        tw: "宿舍",
        ko: "기숙사",
        vi: "ký túc xá",
        th: "หอพัก",
        my: "ကျောင်းသားအိမ်",
        km: "ផ្ទះស្នាក់នៅ",
      },
      furigana: [
        {
          rb: "寮",
          rt: "りょう",
        },
      ],
      kanjiInfo: [
        {
          char: "寮",
          on: ["リョウ"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 779,
      kanji: "両替",
      reading: "りょうがえ",
      meanings: {
        ja: "両替",
        en: "money exchange",
        zh: "兑换",
        tw: "兌換",
        ko: "환전",
        vi: "đổi tiền",
        th: "แลกเงิน",
        my: "ငွေပြောင်း",
        km: "ប្តូរប្រាក់",
      },
      furigana: [
        {
          rb: "両替",
          rt: "りょうがえ",
        },
      ],
      kanjiInfo: [
        {
          char: "両",
          on: ["リョウ"],
          kun: ["てる", "ふたつ"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "替",
          on: ["タイ"],
          kun: ["か.える", "か.え-", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 780,
      kanji: "料金",
      reading: "りょうきん",
      meanings: {
        ja: "料金",
        en: "fee",
        zh: "费用",
        tw: "費用",
        ko: "요금",
        vi: "chi phí",
        th: "ค่าใช้จ่าย",
        my: "ကြေး",
        km: "ថ្លៃសេវា",
      },
      furigana: [
        {
          rb: "料金",
          rt: "りょうきん",
        },
      ],
      kanjiInfo: [
        {
          char: "料",
          on: ["リョウ"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 781,
      kanji: "例",
      reading: "れい",
      meanings: {
        ja: "例",
        en: "example",
        zh: "例子",
        tw: "例子",
        ko: "예",
        vi: "ví dụ",
        th: "ตัวอย่าง",
        my: "ဥပမာ",
        km: "ឧទាហរណ៍",
      },
      furigana: [
        {
          rb: "例",
          rt: "れい",
        },
      ],
      kanjiInfo: [
        {
          char: "例",
          on: ["レイ"],
          kun: ["たと.える"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 782,
      kanji: "礼",
      reading: "れい",
      meanings: {
        ja: "礼",
        en: "thanks",
        zh: "礼貌",
        tw: "禮貌",
        ko: "예의",
        vi: "lời cảm ơn",
        th: "คำขอบคุณ",
        my: "ကျေးဇူးတင်ခြင်း",
        km: "ការអរគុណ",
      },
      furigana: [
        {
          rb: "礼",
          rt: "れい",
        },
      ],
      kanjiInfo: [
        {
          char: "礼",
          on: ["レイ", "ライ"],
          kun: [],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 783,
      kanji: "例外",
      reading: "れいがい",
      meanings: {
        ja: "例外",
        en: "exception",
        zh: "例外",
        tw: "例外",
        ko: "예외",
        vi: "ngoại lệ",
        th: "ข้อยกเว้น",
        my: "အထူးအခြေအနေ",
        km: "ករណីលើកលែង",
      },
      furigana: [
        {
          rb: "例外",
          rt: "れいがい",
        },
      ],
      kanjiInfo: [
        {
          char: "例",
          on: ["レイ"],
          kun: ["たと.える"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 784,
      kanji: "礼儀",
      reading: "れいぎ",
      meanings: {
        ja: "礼儀",
        en: "manners",
        zh: "礼仪",
        tw: "禮儀",
        ko: "예의범절",
        vi: "lễ nghi",
        th: "มารยาท",
        my: "ယဥ်ကျေးမှု",
        km: "មរណីយកម្ម",
      },
      furigana: [
        {
          rb: "礼儀",
          rt: "れいぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "礼",
          on: ["レイ", "ライ"],
          kun: [],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "儀",
          on: ["ギ"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 785,
      kanji: "冷静",
      reading: "れいせい",
      meanings: {
        ja: "冷静",
        en: "calmness",
        zh: "冷静",
        tw: "冷靜",
        ko: "냉静",
        vi: "bình tĩnh",
        th: "ความสงบ",
        my: "သက်သာမှု",
        km: "ភាពត្រជាក់",
      },
      furigana: [
        {
          rb: "冷静",
          rt: "れいせい",
        },
      ],
      kanjiInfo: [
        {
          char: "冷",
          on: ["レイ"],
          kun: [
            "つめ.たい",
            "ひ.える",
            "ひ.や",
            "ひ.ややか",
            "ひ.やす",
            "ひ.やかす",
            "さ.める",
            "さ.ます",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "静",
          on: ["セイ", "ジョウ"],
          kun: ["しず-", "しず.か", "しず.まる", "しず.める"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 786,
      kanji: "列",
      reading: "れつ",
      meanings: {
        ja: "列",
        en: "row",
        zh: "行列",
        tw: "行列",
        ko: "열",
        vi: "hàng",
        th: "แถว",
        my: "တန်း",
        km: "ជួរ",
      },
      furigana: [
        {
          rb: "列",
          rt: "れつ",
        },
      ],
      kanjiInfo: [
        {
          char: "列",
          on: ["レツ", "レ"],
          kun: [],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 787,
      kanji: "列車",
      reading: "れっしゃ",
      meanings: {
        ja: "列車",
        en: "train",
        zh: "列车",
        tw: "列車",
        ko: "열차",
        vi: "tàu hỏa",
        th: "รถไฟ",
        my: "ရထား",
        km: "រថភ្លើង",
      },
      furigana: [
        {
          rb: "列車",
          rt: "れっしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "列",
          on: ["レツ", "レ"],
          kun: [],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 788,
      kanji: "レベル",
      reading: "レベル",
      meanings: {
        ja: "レベル",
        en: "level",
        zh: "水平",
        tw: "水平",
        ko: "레벨",
        vi: "cấp độ",
        th: "ระดับ",
        my: "အဆင့်",
        km: "កម្រិត",
      },
      furigana: [
        {
          rb: "レベル",
          rt: "レベル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 789,
      kanji: "連想",
      reading: "れんそう",
      meanings: {
        ja: "連想",
        en: "association",
        zh: "联想",
        tw: "聯想",
        ko: "연상",
        vi: "liên tưởng",
        th: "การเชื่อมโยง",
        my: "ဆက်စပ်မှု",
        km: "ការតភ្ជាប់",
      },
      furigana: [
        {
          rb: "連想",
          rt: "れんそう",
        },
      ],
      kanjiInfo: [
        {
          char: "連",
          on: ["レン"],
          kun: ["つら.なる", "つら.ねる", "つ.れる", "-づ.れ"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "想",
          on: ["ソウ", "ソ"],
          kun: ["おも.う"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 790,
      kanji: "連続",
      reading: "れんぞく",
      meanings: {
        ja: "連続",
        en: "continuation",
        zh: "连续",
        tw: "連續",
        ko: "연속",
        vi: "liên tục",
        th: "ต่อเนื่อง",
        my: "ဆက်လက်",
        km: "បន្ត",
      },
      furigana: [
        {
          rb: "連続",
          rt: "れんぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "連",
          on: ["レン"],
          kun: ["つら.なる", "つら.ねる", "つ.れる", "-づ.れ"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 791,
      kanji: "老人",
      reading: "ろうじん",
      meanings: {
        ja: "老人",
        en: "old person",
        zh: "老人",
        tw: "老人",
        ko: "노인",
        vi: "người già",
        th: "คนแก่",
        my: "အိုသူ",
        km: "មនុស្សចាស់",
      },
      furigana: [
        {
          rb: "老人",
          rt: "ろうじん",
        },
      ],
      kanjiInfo: [
        {
          char: "老",
          on: ["ロウ"],
          kun: ["お.いる", "ふ.ける"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 792,
      kanji: "労働",
      reading: "ろうどう",
      meanings: {
        ja: "労働",
        en: "labor",
        zh: "劳动",
        tw: "勞動",
        ko: "노동",
        vi: "lao động",
        th: "แรงงาน",
        my: "အလုပ်သမား",
        km: "ការងារ",
      },
      furigana: [
        {
          rb: "労働",
          rt: "ろうどう",
        },
      ],
      kanjiInfo: [
        {
          char: "労",
          on: ["ロウ"],
          kun: [
            "ろう.する",
            "いたわ.る",
            "いた.ずき",
            "ねぎら",
            "つか.れる",
            "ねぎら.う",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "働",
          on: ["ドウ"],
          kun: ["はたら.く"],
          strokes: 13,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 793,
      kanji: "ロケット",
      reading: "ロケット",
      meanings: {
        ja: "ロケット",
        en: "rocket",
        zh: "火箭",
        tw: "火箭",
        ko: "로켓",
        vi: "tên lửa",
        th: "จรวด",
        my: "ရောကက်",
        km: "រ៉ុកខិត",
      },
      furigana: [
        {
          rb: "ロケット",
          rt: "ロケット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 794,
      kanji: "論争",
      reading: "ろんそう",
      meanings: {
        ja: "論争",
        en: "dispute",
        zh: "争论",
        tw: "爭論",
        ko: "논쟁",
        vi: "tranh luận",
        th: "ข้อโต้แย้ง",
        my: "အငြင်းပွားမှု",
        km: "ការអះអាង",
      },
      furigana: [
        {
          rb: "論争",
          rt: "ろんそう",
        },
      ],
      kanjiInfo: [
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "争",
          on: ["ソウ"],
          kun: ["あらそ.う", "いか.でか"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 795,
      kanji: "論文",
      reading: "ろんぶん",
      meanings: {
        ja: "論文",
        en: "thesis",
        zh: "论文",
        tw: "論文",
        ko: "논문",
        vi: "luận văn",
        th: "วิทยานิพนธ์",
        my: "သုတေသနစာတမ်း",
        km: "និក្ខេបបទ",
      },
      furigana: [
        {
          rb: "論文",
          rt: "ろんぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 796,
      kanji: "輪",
      reading: "わ",
      meanings: {
        ja: "輪",
        en: "ring",
        zh: "环",
        tw: "環",
        ko: "고리",
        vi: "vòng",
        th: "วงแหวน",
        my: "စက်ဝိုင်း",
        km: "រង្វង់",
      },
      furigana: [
        {
          rb: "輪",
          rt: "わ",
        },
      ],
      kanjiInfo: [
        {
          char: "輪",
          on: ["リン"],
          kun: ["わ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 797,
      kanji: "ワイン",
      reading: "ワイン",
      meanings: {
        ja: "ワイン",
        en: "wine",
        zh: "葡萄酒",
        tw: "葡萄酒",
        ko: "와인",
        vi: "rượu vang",
        th: "ไวน์",
        my: "ဝိုင်",
        km: "ស្រា",
      },
      furigana: [
        {
          rb: "ワイン",
          rt: "ワイン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 798,
      kanji: "別れ",
      reading: "わかれ",
      meanings: {
        ja: "別れ",
        en: "parting",
        zh: "分别",
        tw: "分別",
        ko: "이별",
        vi: "chia tay",
        th: "การจากลา",
        my: "နုတ်ဆက်မှု",
        km: "ការចែកចាយ",
      },
      furigana: [
        {
          rb: "別れ",
          rt: "わかれ",
        },
      ],
      kanjiInfo: [
        {
          char: "別",
          on: ["ベツ"],
          kun: ["わか.れる", "わ.ける"],
          strokes: 7,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 799,
      kanji: "脇",
      reading: "わき",
      meanings: {
        ja: "脇",
        en: "armpit",
        zh: "腋下",
        tw: "腋下",
        ko: "겨드랑이",
        vi: "nách",
        th: "รักแร้",
        my: "မေးလက်",
        km: "ក្លៀក",
      },
      furigana: [
        {
          rb: "脇",
          rt: "わき",
        },
      ],
      kanjiInfo: [
        {
          char: "脇",
          on: ["キョウ"],
          kun: ["わき", "わけ"],
          strokes: 10,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 800,
      kanji: "綿",
      reading: "わた",
      meanings: {
        ja: "綿",
        en: "cotton plant",
        zh: "棉花",
        tw: "棉花",
        ko: "목화",
        vi: "cây bông",
        th: "ฝ้าย",
        my: "ဖျား",
        km: "កប្បាស",
      },
      furigana: [
        {
          rb: "綿",
          rt: "わた",
        },
      ],
      kanjiInfo: [
        {
          char: "綿",
          on: ["メン"],
          kun: ["わた"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
