export const n3part12 = {
  Lesson12: [
    {
      id: 551,
      kanji: "刑事",
      reading: "けいじ",
      meanings: {
        ja: "犯罪捜査を担当する警察官。",
        en: "(police) detective",
        zh: "刑警；侦探（警方）",
        tw: "刑警；（警方）偵探",
        ko: "형사",
        vi: "cảnh sát hình sự",
        th: "สายสืบ/ตำรวจสืบสวน",
        my: "ရဲဖြစ်မှုန့်ရှာအရာရှိ",
        km: "ប្រធានការ​ប៉ូលិសស៊ើបអង្កេត",
      },
      furigana: [
        {
          rb: "刑事",
          rt: "けいじ",
        },
      ],
      kanjiInfo: [
        {
          char: "刑",
          on: ["ケイ"],
          kun: [],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 552,
      kanji: "芸術",
      reading: "げいじゅつ",
      meanings: {
        ja: "美・表現を目的とする創作活動。",
        en: "art (the arts)",
        zh: "艺术",
        tw: "藝術",
        ko: "예술",
        vi: "nghệ thuật",
        th: "ศิลปะ",
        my: "အနုပညာ",
        km: "សិល្បៈ",
      },
      furigana: [
        {
          rb: "芸術",
          rt: "げいじゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "芸",
          on: ["ゲイ", "ウン"],
          kun: ["う.える", "のり", "わざ"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "術",
          on: ["ジュツ"],
          kun: ["すべ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 553,
      kanji: "契約",
      reading: "けいやく",
      meanings: {
        ja: "当事者間の取り決め。契約。",
        en: "contract; agreement",
        zh: "契约；合约",
        tw: "契約；合約",
        ko: "계약",
        vi: "hợp đồng",
        th: "สัญญา",
        my: "စာချုပ်",
        km: "កិច្ចសន្យា",
      },
      furigana: [
        {
          rb: "契約",
          rt: "けいやく",
        },
      ],
      kanjiInfo: [
        {
          char: "契",
          on: ["ケイ"],
          kun: ["ちぎ.る"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "約",
          on: ["ヤク"],
          kun: ["つづ.まる", "つづ.める", "つづま.やか"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 554,
      kanji: "経由",
      reading: "けいゆ",
      meanings: {
        ja: "通過して行くこと。〜を経由。",
        en: "via; by way of",
        zh: "经由；经过",
        tw: "經由；經過",
        ko: "경유",
        vi: "đi qua; thông qua",
        th: "ผ่านทาง; โดยผ่าน",
        my: "…ကနေလမ်းလျှောက်",
        km: "តាមរយៈ; កាត់ផ្លូវតាម",
      },
      furigana: [
        {
          rb: "経由",
          rt: "けいゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "経",
          on: ["ケイ", "キョウ", "キン"],
          kun: ["へ.る", "た.つ", "たていと", "はか.る", "のり"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "由",
          on: ["ユ", "ユウ", "ユイ"],
          kun: ["よし", "よ.る"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 555,
      kanji: "ケース",
      reading: "ケース",
      meanings: {
        ja: "容器・入れ物。事例。",
        en: "case (container); case (instance)",
        zh: "盒/容器；案例",
        tw: "盒/容器；案例",
        ko: "케이스(용기/사례)",
        vi: "hộp/bao; trường hợp",
        th: "กล่อง/เคส; กรณี",
        my: "ဘူး/အိတ်; ကိစ္စ",
        km: "ប្រអប់/ស្រោម; ករណី",
      },
      furigana: [
        {
          rb: "ケース",
          rt: "ケース",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 556,
      kanji: "ゲーム",
      reading: "ゲーム",
      meanings: {
        ja: "遊戯。試合。テレビゲーム等。",
        en: "game",
        zh: "游戏",
        tw: "遊戲",
        ko: "게임",
        vi: "trò chơi",
        th: "เกม",
        my: "ဂိမ်း",
        km: "ហ្គេម",
      },
      furigana: [
        {
          rb: "ゲーム",
          rt: "ゲーム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 557,
      kanji: "劇",
      reading: "げき",
      meanings: {
        ja: "演劇。ドラマ。",
        en: "drama; play (theater)",
        zh: "戏剧；舞台剧",
        tw: "戲劇；舞台劇",
        ko: "연극; 드라마",
        vi: "kịch; vở kịch",
        th: "ละครเวที; ละคร",
        my: "ဇာတ်လမ်းပြဇာတ်",
        km: "ល្ខោន; ឈុតកំប្លែង",
      },
      furigana: [
        {
          rb: "劇",
          rt: "げき",
        },
      ],
      kanjiInfo: [
        {
          char: "劇",
          on: ["ゲキ"],
          kun: [],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 558,
      kanji: "劇場",
      reading: "げきじょう",
      meanings: {
        ja: "演劇や上映を行う施設。",
        en: "theater; playhouse",
        zh: "剧场；戏院",
        tw: "劇場；戲院",
        ko: "극장",
        vi: "nhà hát; rạp kịch",
        th: "โรงละคร",
        my: "ရုပ်ရှင်/ဇာတ်ရုံ",
        km: "โรงละคร; រោងល្ខោន",
      },
      furigana: [
        {
          rb: "劇場",
          rt: "げきじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "劇",
          on: ["ゲキ"],
          kun: [],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 559,
      kanji: "化粧",
      reading: "けしょう",
      meanings: {
        ja: "顔などに施すメイク。",
        en: "makeup; cosmetics",
        zh: "化妆",
        tw: "化妝",
        ko: "화장",
        vi: "trang điểm",
        th: "แต่งหน้า",
        my: "အလှပြင်",
        km: "ការតុបតែងមុខ",
      },
      furigana: [
        {
          rb: "化粧",
          rt: "けしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "粧",
          on: ["ショウ"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 560,
      kanji: "血液",
      reading: "けつえき",
      meanings: {
        ja: "体内を循環する血。",
        en: "blood",
        zh: "血液",
        tw: "血液",
        ko: "혈액",
        vi: "máu",
        th: "เลือด",
        my: "သွေး",
        km: "ឈាម",
      },
      furigana: [
        {
          rb: "血液",
          rt: "けつえき",
        },
      ],
      kanjiInfo: [
        {
          char: "血",
          on: ["ケツ"],
          kun: ["ち"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "液",
          on: ["エキ"],
          kun: [],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 561,
      kanji: "結果",
      reading: "けっか",
      meanings: {
        ja: "物事の最終的な成り行き。",
        en: "result; outcome",
        zh: "结果",
        tw: "結果",
        ko: "결과",
        vi: "kết quả",
        th: "ผลลัพธ์",
        my: "ရလဒ်",
        km: "លទ្ធផល",
      },
      furigana: [
        {
          rb: "結果",
          rt: "けっか",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "果",
          on: ["カ"],
          kun: [
            "は.たす",
            "はた.す",
            "-は.たす",
            "は.てる",
            "-は.てる",
            "は.て",
          ],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 562,
      kanji: "欠陥",
      reading: "けっかん",
      meanings: {
        ja: "不備・不完全な点。欠点。",
        en: "defect; flaw",
        zh: "缺陷；瑕疵",
        tw: "缺陷；瑕疵",
        ko: "결함",
        vi: "khuyết điểm; lỗi",
        th: "ข้อบกพร่อง",
        my: "ချို့ယွင်းချက်",
        km: "ខ្វះខាត; ខូចខាត",
      },
      furigana: [
        {
          rb: "欠陥",
          rt: "けっかん",
        },
      ],
      kanjiInfo: [
        {
          char: "欠",
          on: ["ケツ", "ケン"],
          kun: ["か.ける", "か.く"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "陥",
          on: ["カン"],
          kun: ["おちい.る", "おとしい.れる"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 563,
      kanji: "決心",
      reading: "けっしん",
      meanings: {
        ja: "固く心に決めること。",
        en: "determination; resolve",
        zh: "决心；下定决心",
        tw: "決心；下定決心",
        ko: "결심",
        vi: "quyết tâm",
        th: "ตั้งใจแน่วแน่; ตัดสินใจเด็ดขาด",
        my: "ဆုံးဖြတ်ချက်ကောင်း",
        km: "សេចក្តីសម្រេចចិត្ត",
      },
      furigana: [
        {
          rb: "決心",
          rt: "けっしん",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 564,
      kanji: "欠席",
      reading: "けっせき",
      meanings: {
        ja: "出席しないこと。",
        en: "absence (from attendance)",
        zh: "缺席",
        tw: "缺席",
        ko: "결석",
        vi: "vắng mặt",
        th: "ขาดเรียน/ขาดประชุม",
        my: "လစာမတက်မှု",
        km: "អវត្តមាន",
      },
      furigana: [
        {
          rb: "欠席",
          rt: "けっせき",
        },
      ],
      kanjiInfo: [
        {
          char: "欠",
          on: ["ケツ", "ケン"],
          kun: ["か.ける", "か.く"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "席",
          on: ["セキ"],
          kun: ["むしろ"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 565,
      kanji: "決定",
      reading: "けってい",
      meanings: {
        ja: "決めること。決まること。",
        en: "decision; determination",
        zh: "决定",
        tw: "決定",
        ko: "결정",
        vi: "quyết định",
        th: "การตัดสินใจ",
        my: "ဆုံးဖြတ်ချက်",
        km: "ការសម្រេចចិត្ត",
      },
      furigana: [
        {
          rb: "決定",
          rt: "けってい",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 566,
      kanji: "欠点",
      reading: "けってん",
      meanings: {
        ja: "よくない点。短所。",
        en: "fault; shortcoming",
        zh: "缺点；短处",
        tw: "缺點；短處",
        ko: "결점; 단점",
        vi: "khuyết điểm; nhược điểm",
        th: "ข้อเสีย; จุดบกพร่อง",
        my: "အားနည်းချက်",
        km: "ខ្វះខាត; ចំណុចខ្សោយ",
      },
      furigana: [
        {
          rb: "欠点",
          rt: "けってん",
        },
      ],
      kanjiInfo: [
        {
          char: "欠",
          on: ["ケツ", "ケン"],
          kun: ["か.ける", "か.く"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 567,
      kanji: "結論",
      reading: "けつろん",
      meanings: {
        ja: "論じた結果としての締めくくり。",
        en: "conclusion",
        zh: "结论",
        tw: "結論",
        ko: "결론",
        vi: "kết luận",
        th: "ข้อสรุป",
        my: "သတ်မှတ်ချက် (နိဂုံး)",
        km: "សេចក្តីសន្និដ្ឋាន",
      },
      furigana: [
        {
          rb: "結論",
          rt: "けつろん",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 568,
      kanji: "煙",
      reading: "けむり",
      meanings: {
        ja: "物が燃えて生じる白/黒い気体。",
        en: "smoke",
        zh: "烟",
        tw: "煙",
        ko: "연기",
        vi: "khói",
        th: "ควัน",
        my: "ခိုးမှောက်",
        km: "ផ្សែង",
      },
      furigana: [
        {
          rb: "煙",
          rt: "けむり",
        },
      ],
      kanjiInfo: [
        {
          char: "煙",
          on: ["エン"],
          kun: ["けむ.る", "けむり", "けむ.い"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 569,
      kanji: "券",
      reading: "けん",
      meanings: {
        ja: "権利・サービスを受ける証票。",
        en: "ticket; coupon; voucher",
        zh: "券；票据",
        tw: "券；票券",
        ko: "권; 티켓; 쿠폰",
        vi: "vé; phiếu; voucher",
        th: "ตั๋ว; คูปอง",
        my: "လက်မှတ်; ကူပွန်",
        km: "សំបុត្រ; គូப்பុង; វោឈ័រ",
      },
      furigana: [
        {
          rb: "券",
          rt: "けん",
        },
      ],
      kanjiInfo: [
        {
          char: "券",
          on: ["ケン"],
          kun: [],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 570,
      kanji: "県",
      reading: "けん",
      meanings: {
        ja: "日本の地方公共団体の単位。",
        en: "prefecture (Japan)",
        zh: "县（日本地方行政区）",
        tw: "縣（日本地方行政區）",
        ko: "현(일본 행정구역)",
        vi: "tỉnh (đơn vị hành chính Nhật)",
        th: "จังหวัด (ญี่ปุ่น)",
        my: "ပြည်နယ်တစ်ခု (ဂျပန်)",
        km: "ខេត្ត (ជប៉ុន)",
      },
      furigana: [
        {
          rb: "県",
          rt: "けん",
        },
      ],
      kanjiInfo: [
        {
          char: "県",
          on: ["ケン"],
          kun: ["か.ける"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 571,
      kanji: "見解",
      reading: "けんかい",
      meanings: {
        ja: "物事に対する考え方・意見。",
        en: "opinion; view; perspective",
        zh: "见解；看法",
        tw: "見解；看法",
        ko: "견해; 의견",
        vi: "quan điểm; ý kiến",
        th: "ทรรศนะ; ความเห็น",
        my: "ထင်မြင်ချက်",
        km: "ទស្សនៈ; មតិយោបល់",
      },
      furigana: [
        {
          rb: "見解",
          rt: "けんかい",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 572,
      kanji: "限界",
      reading: "げんかい",
      meanings: {
        ja: "それ以上できない境。",
        en: "limit; boundary; threshold",
        zh: "界限；极限",
        tw: "界限；極限",
        ko: "한계",
        vi: "giới hạn",
        th: "ขีดจำกัด",
        my: "အကန့်အသတ်",
        km: "ព្រំដែន; កម្រិតអតិបរិមា",
      },
      furigana: [
        {
          rb: "限界",
          rt: "げんかい",
        },
      ],
      kanjiInfo: [
        {
          char: "限",
          on: ["ゲン"],
          kun: ["かぎ.る", "かぎ.り", "-かぎ.り"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "界",
          on: ["カイ"],
          kun: [],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 573,
      kanji: "現金",
      reading: "げんきん",
      meanings: {
        ja: "手元の金。キャッシュ。",
        en: "cash",
        zh: "现金",
        tw: "現金",
        ko: "현금",
        vi: "tiền mặt",
        th: "เงินสด",
        my: "ငွေသား",
        km: "សាច់ប្រាក់",
      },
      furigana: [
        {
          rb: "現金",
          rt: "げんきん",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 574,
      kanji: "言語",
      reading: "げんご",
      meanings: {
        ja: "人間が用いるコミュニケーションの体系。",
        en: "language",
        zh: "语言",
        tw: "語言",
        ko: "언어",
        vi: "ngôn ngữ",
        th: "ภาษา",
        my: "ဘာသာစကား",
        km: "ភាសា",
      },
      furigana: [
        {
          rb: "言語",
          rt: "げんご",
        },
      ],
      kanjiInfo: [
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 575,
      kanji: "健康",
      reading: "けんこう",
      meanings: {
        ja: "からだ・心が正常で丈夫なこと。",
        en: "health",
        zh: "健康",
        tw: "健康",
        ko: "건강",
        vi: "sức khỏe",
        th: "สุขภาพ",
        my: "ကျန်းမာရေး",
        km: "សុខភាព",
      },
      furigana: [
        {
          rb: "健康",
          rt: "けんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "健",
          on: ["ケン"],
          kun: ["すこ.やか"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "康",
          on: ["コウ"],
          kun: [],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 576,
      kanji: "検査",
      reading: "けんさ",
      meanings: {
        ja: "調べて確かめること。検査。",
        en: "inspection; examination; test",
        zh: "检查；检验",
        tw: "檢查；檢驗",
        ko: "검사",
        vi: "kiểm tra; xét nghiệm",
        th: "การตรวจ; การตรวจสอบ",
        my: "စစ်ဆေးမှု; စမ်းသပ်မှု",
        km: "ការត្រួតពិនិត្យ; ការតេស្ត",
      },
      furigana: [
        {
          rb: "検査",
          rt: "けんさ",
        },
      ],
      kanjiInfo: [
        {
          char: "検",
          on: ["ケン"],
          kun: ["しら.べる"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "査",
          on: ["サ"],
          kun: [],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 577,
      kanji: "現在",
      reading: "げんざい",
      meanings: {
        ja: "いま。今この時点。",
        en: "the present; now; current",
        zh: "现在；当前",
        tw: "現在；當前",
        ko: "현재",
        vi: "hiện tại",
        th: "ปัจจุบัน",
        my: "လက်ရှိ",
        km: "បច្ចុប្បន្ន",
      },
      furigana: [
        {
          rb: "現在",
          rt: "げんざい",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "在",
          on: ["ザイ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 578,
      kanji: "現実",
      reading: "げんじつ",
      meanings: {
        ja: "実際に存在・起こっていること。",
        en: "reality",
        zh: "现实",
        tw: "現實",
        ko: "현실",
        vi: "thực tế",
        th: "ความเป็นจริง",
        my: "ကန့်ကွက်မရှိသော အဖြစ်အပျက်",
        km: "ការពិតនៃជីវិត; ភាពជាក់ស្តែង",
      },
      furigana: [
        {
          rb: "現実",
          rt: "げんじつ",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 579,
      kanji: "現象",
      reading: "げんしょう",
      meanings: {
        ja: "観察される物事の表れ。",
        en: "phenomenon",
        zh: "现象",
        tw: "現象",
        ko: "현상",
        vi: "hiện tượng",
        th: "ปรากฏการณ์",
        my: "ဖြစ်စဉ်",
        km: "បាតុភូត",
      },
      furigana: [
        {
          rb: "現象",
          rt: "げんしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "象",
          on: ["ショウ", "ゾウ"],
          kun: ["かたど.る"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 580,
      kanji: "現状",
      reading: "げんじょう",
      meanings: {
        ja: "現在のありさま。今の状態。",
        en: "present condition; status quo",
        zh: "现状；现况",
        tw: "現狀；現況",
        ko: "현상태; 현황",
        vi: "tình trạng hiện tại; hiện trạng",
        th: "สภาพปัจจุบัน",
        my: "လက်ရှိအခြေအနေ",
        km: "ស្ថានភាពបច្ចុប្បន្ន",
      },
      furigana: [
        {
          rb: "現状",
          rt: "げんじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "状",
          on: ["ジョウ"],
          kun: [],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 581,
      kanji: "建設",
      reading: "けんせつ",
      meanings: {
        ja: "建物や施設をつくること。",
        en: "construction (building)",
        zh: "建设；建筑",
        tw: "建設；建築",
        ko: "건설",
        vi: "xây dựng",
        th: "การก่อสร้าง",
        my: "ဆောက်လုပ်မှု",
        km: "សំណង់; ស្ថាបនា",
      },
      furigana: [
        {
          rb: "建設",
          rt: "けんせつ",
        },
      ],
      kanjiInfo: [
        {
          char: "建",
          on: ["ケン", "コン"],
          kun: ["た.てる", "た.て", "-だ.て", "た.つ"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "設",
          on: ["セツ"],
          kun: ["もう.ける"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 582,
      kanji: "現代",
      reading: "げんだい",
      meanings: {
        ja: "今に近い時代。現代。",
        en: "the present age; modern times",
        zh: "现代",
        tw: "現代",
        ko: "현대",
        vi: "hiện đại; thời nay",
        th: "สมัยปัจจุบัน; ยุคสมัยใหม่",
        my: "ခေတ်သစ်; လက်ရှိခေတ်",
        km: "សម័យទំនើប; សម័យបច្ចុប្បន್ನ",
      },
      furigana: [
        {
          rb: "現代",
          rt: "げんだい",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 583,
      kanji: "建築",
      reading: "けんちく",
      meanings: {
        ja: "建物を設計・建造すること。",
        en: "architecture; construction",
        zh: "建筑（学）；建造",
        tw: "建築；建造",
        ko: "건축",
        vi: "kiến trúc; xây dựng",
        th: "สถาปัตยกรรม; การก่อสร้าง",
        my: "အဆောက်အဦဒီဇိုင်/ဆောက်လုပ်",
        km: "ស្ថាបត្យកម្ម; សំណង់",
      },
      furigana: [
        {
          rb: "建築",
          rt: "けんちく",
        },
      ],
      kanjiInfo: [
        {
          char: "建",
          on: ["ケン", "コン"],
          kun: ["た.てる", "た.て", "-だ.て", "た.つ"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "築",
          on: ["チク"],
          kun: ["きず.く"],
          strokes: 16,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 584,
      kanji: "見当",
      reading: "けんとう",
      meanings: {
        ja: "およその推量・見込み。",
        en: "estimate; guess; aim",
        zh: "估计；推测；方向感",
        tw: "估計；推測；方向",
        ko: "짐작; 추정; 방향 (감)",
        vi: "ước lượng; phỏng đoán; phương hướng",
        th: "การคาดคะเน; การกะคร่าว ๆ",
        my: "ခန့်မှန်းချက်; လမ်းညွှန်အား",
        km: "ការប៉ាន់ស្មាន; ការសន្មត់",
      },
      furigana: [
        {
          rb: "見当",
          rt: "けんとう",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 585,
      kanji: "検討",
      reading: "けんとう",
      meanings: {
        ja: "よく調べ考えること。",
        en: "consideration; examination",
        zh: "检讨；研究；考虑",
        tw: "檢討；研究；考慮",
        ko: "검토",
        vi: "xem xét; khảo cứu",
        th: "การพิจารณา; การตรวจทาน",
        my: "သေချာစွာ စစ်ဆေးစဥ်းစားခြင်း",
        km: "ការពិចារណា; ពិនិត្យជ្រាលជ្រៅ",
      },
      furigana: [
        {
          rb: "検討",
          rt: "けんとう",
        },
      ],
      kanjiInfo: [
        {
          char: "検",
          on: ["ケン"],
          kun: ["しら.べる"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "討",
          on: ["トウ"],
          kun: ["う.つ"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 586,
      kanji: "現場",
      reading: "げんば",
      meanings: {
        ja: "実際に事が行われる場所。",
        en: "site; scene (on-site)",
        zh: "现场",
        tw: "現場",
        ko: "현장",
        vi: "hiện trường; nơi làm việc",
        th: "สถานที่เกิดเหตุ/หน้างาน",
        my: "ဖြစ်စဉ် နေရာ/လုပ်ငန်းခွင်",
        km: "ទីតាំងព្រឹត្តិការណ៍; កន្លែងធ្វើការ",
      },
      furigana: [
        {
          rb: "現場",
          rt: "げんば",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 587,
      kanji: "憲法",
      reading: "けんぽう",
      meanings: {
        ja: "国家の基本法。",
        en: "constitution (national charter)",
        zh: "宪法",
        tw: "憲法",
        ko: "헌법",
        vi: "hiến pháp",
        th: "รัฐธรรมนูญ",
        my: "နိုင်ငံသားခံစာချုပ် (အခြေခံဥပဒေ)",
        km: "រដ្ឋធម្មនុញ្ញ",
      },
      furigana: [
        {
          rb: "憲法",
          rt: "けんぽう",
        },
      ],
      kanjiInfo: [
        {
          char: "憲",
          on: ["ケン"],
          kun: [],
          strokes: 16,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "法",
          on: ["ホウ", "ハッ", "ホッ", "フラン"],
          kun: ["のり"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 588,
      kanji: "権利",
      reading: "けんり",
      meanings: {
        ja: "法律・慣習で認められた力。",
        en: "right; entitlement",
        zh: "权利",
        tw: "權利",
        ko: "권리",
        vi: "quyền lợi",
        th: "สิทธิ",
        my: "အခွင့်အရေး",
        km: "សិទ្ធិ",
      },
      furigana: [
        {
          rb: "権利",
          rt: "けんり",
        },
      ],
      kanjiInfo: [
        {
          char: "権",
          on: ["ケン", "ゴン"],
          kun: ["おもり", "かり", "はか.る"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "利",
          on: ["リ"],
          kun: ["き.く"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 589,
      kanji: "後",
      reading: "ご",
      meanings: {
        ja: "あと。のち。〜の後。",
        en: "after; later; afterward",
        zh: "之后；以后",
        tw: "之後；以後",
        ko: "후; 이후",
        vi: "sau; về sau",
        th: "หลังจาก; ภายหลัง",
        my: "နောက်ပိုင်း; အပြီး",
        km: "ក្រោយ; បន្ទាប់ពី",
      },
      furigana: [
        {
          rb: "後",
          rt: "ご",
        },
      ],
      kanjiInfo: [
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 590,
      kanji: "碁",
      reading: "ご",
      meanings: {
        ja: "囲碁。ボードゲームの一種。",
        en: "go (board game)",
        zh: "围棋",
        tw: "圍棋",
        ko: "바둑",
        vi: "cờ vây",
        th: "หมากล้อม",
        my: "ဂို (အစားထိုးကစားခွင်)",
        km: "ឆឡេង (កីឡាផ្ទាំង)",
      },
      furigana: [
        {
          rb: "碁",
          rt: "ご",
        },
      ],
      kanjiInfo: [
        {
          char: "碁",
          on: ["ゴ"],
          kun: [],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 591,
      kanji: "恋",
      reading: "こい",
      meanings: {
        ja: "異性などに寄せる愛情。",
        en: "(romantic) love",
        zh: "恋爱（之情）",
        tw: "戀愛（之情）",
        ko: "사랑(연정)",
        vi: "tình yêu lãng mạn",
        th: "ความรักแบบหนุ่มสาว",
        my: "မော်ကွန်းဆန်သောချစ်ခြင်း",
        km: "សេចក្តីស្រលាញ់ (រ៉ូមែនទិក)",
      },
      furigana: [
        {
          rb: "恋",
          rt: "こい",
        },
      ],
      kanjiInfo: [
        {
          char: "恋",
          on: ["レン"],
          kun: ["こ.う", "こい", "こい.しい"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 592,
      kanji: "恋人",
      reading: "こいびと",
      meanings: {
        ja: "愛し合う相手。恋人。",
        en: "lover; boyfriend/girlfriend; partner",
        zh: "恋人；男女朋友",
        tw: "情人；男女朋友",
        ko: "연인",
        vi: "người yêu",
        th: "คนรัก; แฟน",
        my: "ချစ်သူ",
        km: "សង្សារ; គូស្នេហ៍",
      },
      furigana: [
        {
          rb: "恋人",
          rt: "こいびと",
        },
      ],
      kanjiInfo: [
        {
          char: "恋",
          on: ["レン"],
          kun: ["こ.う", "こい", "こい.しい"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 593,
      kanji: "幸運",
      reading: "こううん",
      meanings: {
        ja: "よい運。ラッキー。",
        en: "good luck; fortune",
        zh: "好运；幸运",
        tw: "好運；幸運",
        ko: "행운",
        vi: "vận may; may mắn",
        th: "โชคดี",
        my: "ကံကောင်းမှု",
        km: "សំណាងល្អ",
      },
      furigana: [
        {
          rb: "幸運",
          rt: "こううん",
        },
      ],
      kanjiInfo: [
        {
          char: "幸",
          on: ["コウ"],
          kun: ["さいわ.い", "さち", "しあわ.せ"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 594,
      kanji: "講演",
      reading: "こうえん",
      meanings: {
        ja: "多人数の前での口頭発表。",
        en: "lecture (public talk)",
        zh: "演讲；讲座",
        tw: "演講；講座",
        ko: "강연",
        vi: "bài diễn thuyết",
        th: "การบรรยาย",
        my: "မိန့်ခွန်းပြောခြင်း",
        km: "សុន្ទរកថាសាធារណៈ",
      },
      furigana: [
        {
          rb: "講演",
          rt: "こうえん",
        },
      ],
      kanjiInfo: [
        {
          char: "講",
          on: ["コウ"],
          kun: [],
          strokes: 17,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "演",
          on: ["エン"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 595,
      kanji: "効果",
      reading: "こうか",
      meanings: {
        ja: "ある働きかけの及ぼす結果。",
        en: "effect; efficacy",
        zh: "效果；效应",
        tw: "效果；效應",
        ko: "효과",
        vi: "hiệu quả; tác dụng",
        th: "ผลกระทบ; ประสิทธิผล",
        my: "အကျိုးသက်ရောက်မှု",
        km: "ផលប៉ះពាល់; ប្រសិទ្ធភាព",
      },
      furigana: [
        {
          rb: "効果",
          rt: "こうか",
        },
      ],
      kanjiInfo: [
        {
          char: "効",
          on: ["コウ"],
          kun: ["き.く", "ききめ", "なら.う"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "果",
          on: ["カ"],
          kun: [
            "は.たす",
            "はた.す",
            "-は.たす",
            "は.てる",
            "-は.てる",
            "は.て",
          ],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 596,
      kanji: "硬貨",
      reading: "こうか",
      meanings: {
        ja: "金属の貨幣。",
        en: "coin (metal money)",
        zh: "硬币",
        tw: "硬幣",
        ko: "동전",
        vi: "đồng xu; tiền xu",
        th: "เหรียญกษาปณ์",
        my: "ဒင်္ဂါးပြား",
        km: "កាក់",
      },
      furigana: [
        {
          rb: "硬貨",
          rt: "こうか",
        },
      ],
      kanjiInfo: [
        {
          char: "硬",
          on: ["コウ"],
          kun: ["かた.い"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "貨",
          on: ["カ"],
          kun: ["たから"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 597,
      kanji: "合格",
      reading: "ごうかく",
      meanings: {
        ja: "試験などに受かること。",
        en: "pass (an exam); qualification",
        zh: "合格；通过考试",
        tw: "合格；通過考試",
        ko: "합격",
        vi: "đậu; đạt",
        th: "สอบผ่าน; ผ่านเกณฑ์",
        my: "စာမေးပွဲအောင်",
        km: "ជាប់ប្រឡូក; ជាប់តេស្ត",
      },
      furigana: [
        {
          rb: "合格",
          rt: "ごうかく",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "格",
          on: ["カク", "コウ", "キャク", "ゴウ"],
          kun: [],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 598,
      kanji: "交換",
      reading: "こうかん",
      meanings: {
        ja: "取り替えること。やり取り。",
        en: "exchange; swap; replacement",
        zh: "交换；调换",
        tw: "交換；調換",
        ko: "교환",
        vi: "trao đổi; đổi",
        th: "การแลกเปลี่ยน; เปลี่ยน",
        my: "ဖလှယ်ခြင်း",
        km: "ការប្តូរ; ផ្លាស់ប្តូរ",
      },
      furigana: [
        {
          rb: "交換",
          rt: "こうかん",
        },
      ],
      kanjiInfo: [
        {
          char: "交",
          on: ["コウ"],
          kun: [
            "まじ.わる",
            "まじ.える",
            "ま.じる",
            "まじ.る",
            "ま.ざる",
            "ま.ぜる",
            "-か.う",
            "か.わす",
            "かわ.す",
            "こもごも",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "換",
          on: ["カン"],
          kun: ["か.える", "-か.える", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 599,
      kanji: "航空",
      reading: "こうくう",
      meanings: {
        ja: "空を飛ぶ交通・運送。",
        en: "aviation; air transport",
        zh: "航空；空运",
        tw: "航空；空運",
        ko: "항공",
        vi: "hàng không",
        th: "การบิน; ขนส่งทางอากาศ",
        my: "လေကြောင်း",
        km: "អាកាសចរណ៍",
      },
      furigana: [
        {
          rb: "航空",
          rt: "こうくう",
        },
      ],
      kanjiInfo: [
        {
          char: "航",
          on: ["コウ"],
          kun: [],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 600,
      kanji: "光景",
      reading: "こうけい",
      meanings: {
        ja: "目に映る場面。ながめ。",
        en: "scene; sight; spectacle",
        zh: "光景；景象",
        tw: "光景；景象",
        ko: "광경; 장면",
        vi: "quang cảnh; cảnh tượng",
        th: "ภาพเหตุการณ์; ทิวทัศน์",
        my: "မြင်ကွင်း; အမြင်",
        km: "ទេសភាព; ឈុតហេតុ",
      },
      furigana: [
        {
          rb: "光景",
          rt: "こうけい",
        },
      ],
      kanjiInfo: [
        {
          char: "光",
          on: ["コウ"],
          kun: ["ひか.る", "ひかり"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "景",
          on: ["ケイ"],
          kun: [],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
