export const n3part7 = {
  Lesson7: [
    {
      id: 301,
      kanji: "生まれ",
      reading: "うまれ",
      meanings: {
        ja: "誕生すること・生まれたこと。",
        en: "birth; being born",
        zh: "出生；诞生",
        tw: "出生；誕生",
        ko: "출생",
        vi: "sự sinh ra",
        th: "การเกิด",
        my: "မွေးဖွားခြင်း",
        km: "កំណើត",
      },
      furigana: [
        {
          rb: "生まれ",
          rt: "うまれ",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 302,
      kanji: "有無",
      reading: "うむ",
      meanings: {
        ja: "あるかないか。",
        en: "presence or absence; existence or nonexistence",
        zh: "有无；是否存在",
        tw: "有無；是否存在",
        ko: "유무",
        vi: "có hay không; sự tồn tại",
        th: "มีหรือไม่มี",
        my: "ရှိ/မရှိ",
        km: "មាន ឬ គ្មាន",
      },
      furigana: [
        {
          rb: "有無",
          rt: "うむ",
        },
      ],
      kanjiInfo: [
        {
          char: "有",
          on: ["ユウ", "ウ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 303,
      kanji: "梅",
      reading: "うめ",
      meanings: {
        ja: "ウメの木やその実。",
        en: "Japanese apricot (Prunus mume); plum blossom",
        zh: "梅花；梅子",
        tw: "梅花；梅子",
        ko: "매화; 매실",
        vi: "mai Nhật; quả mơ Nhật",
        th: "ต้นบ๊วย/ดอกบ๊วย; ผลบ๊วย",
        my: "နာနတ်ပန်း; နာနတ်သီး",
        km: "ផ្កា​ម៉េ; ផ្លែម៉េ (ume)",
      },
      furigana: [
        {
          rb: "梅",
          rt: "うめ",
        },
      ],
      kanjiInfo: [
        {
          char: "梅",
          on: ["バイ"],
          kun: ["うめ"],
          strokes: 10,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 304,
      kanji: "噂",
      reading: "うわさ",
      meanings: {
        ja: "人々の間で言いふらされる話。",
        en: "rumor; gossip",
        zh: "传闻；流言",
        tw: "傳聞；流言",
        ko: "소문",
        vi: "tin đồn",
        th: "ข่าวลือ",
        my: "သမွ်သတင်း; အတင်းပြောသံ",
        km: "ពាក្យចចាមអារាម",
      },
      furigana: [
        {
          rb: "噂",
          rt: "うわさ",
        },
      ],
      kanjiInfo: [
        {
          char: "噂",
          on: ["ソン"],
          kun: ["うわさ"],
          strokes: 15,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 305,
      kanji: "運",
      reading: "うん",
      meanings: {
        ja: "幸運・不運などのめぐり合わせ。",
        en: "luck; fortune",
        zh: "运气",
        tw: "運氣",
        ko: "운",
        vi: "vận may",
        th: "โชค; วาสนา",
        my: "ကံကြမ္မာ",
        km: "សំណាង",
      },
      furigana: [
        {
          rb: "運",
          rt: "うん",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 306,
      kanji: "運転",
      reading: "うんてん",
      meanings: {
        ja: "車や機械などを操作して動かすこと。",
        en: "driving; operation (of a vehicle/machine)",
        zh: "驾驶；操作（车辆/机器）",
        tw: "駕駛；操作（車輛/機器）",
        ko: "운전; 운행",
        vi: "lái; vận hành",
        th: "การขับขี่; การเดินเครื่อง",
        my: "မောင်းနှင်ခြင်း; စက်အလုပ်လုပ်စေခြင်း",
        km: "បើកបរ; ដំណើរការ (យានយន្ត/ម៉ាស៊ីន)",
      },
      furigana: [
        {
          rb: "運転",
          rt: "うんてん",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 307,
      kanji: "柄",
      reading: "え",
      meanings: {
        ja: "道具などの持つ部分。",
        en: "handle; grip (of a tool)",
        zh: "柄；把手",
        tw: "柄；把手",
        ko: "손잡이",
        vi: "cán; tay cầm",
        th: "ด้ามจับ",
        my: "လက်ကိုင်",
        km: "ដំបងកាន់; ដៃកាន់",
      },
      furigana: [
        {
          rb: "柄",
          rt: "え",
        },
      ],
      kanjiInfo: [
        {
          char: "柄",
          on: ["ヘイ"],
          kun: ["がら", "え", "つか"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 308,
      kanji: "永遠",
      reading: "えいえん",
      meanings: {
        ja: "いつまでも続くこと。",
        en: "eternity; forever",
        zh: "永远",
        tw: "永遠",
        ko: "영원",
        vi: "vĩnh viễn",
        th: "นิรันดร์",
        my: "ထာဝရ",
        km: "អស់កល្បជានិច្ច",
      },
      furigana: [
        {
          rb: "永遠",
          rt: "えいえん",
        },
      ],
      kanjiInfo: [
        {
          char: "永",
          on: ["エイ"],
          kun: ["なが.い"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "遠",
          on: ["エン", "オン"],
          kun: ["とお.い"],
          strokes: 13,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 309,
      kanji: "永久",
      reading: "えいきゅう",
      meanings: {
        ja: "長く変わらないこと。永久に続くこと。",
        en: "permanence; perpetuity; eternity",
        zh: "永久；长久",
        tw: "永久；長久",
        ko: "영구",
        vi: "vĩnh cửu",
        th: "ถาวร; ตลอดกาล",
        my: "အပြီးအပျက်မရှိသော; အမြဲတမ်း",
        km: "អចិន្ត្រៃយ៍; អស់កល្ប",
      },
      furigana: [
        {
          rb: "永久",
          rt: "えいきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "永",
          on: ["エイ"],
          kun: ["なが.い"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "久",
          on: ["キュウ", "ク"],
          kun: ["ひさ.しい"],
          strokes: 3,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 310,
      kanji: "影響",
      reading: "えいきょう",
      meanings: {
        ja: "他に及ぼす作用。",
        en: "influence; effect; impact",
        zh: "影响",
        tw: "影響",
        ko: "영향",
        vi: "ảnh hưởng; tác động",
        th: "อิทธิพล; ผลกระทบ",
        my: "သက်ရောက်မှု",
        km: "ឥទ្ធិពល; ផលប៉ះពាល់",
      },
      furigana: [
        {
          rb: "影響",
          rt: "えいきょう",
        },
      ],
      kanjiInfo: [
        {
          char: "影",
          on: ["エイ"],
          kun: ["かげ"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "響",
          on: ["キョウ"],
          kun: ["ひび.く"],
          strokes: 20,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 311,
      kanji: "営業",
      reading: "えいぎょう",
      meanings: {
        ja: "事業を営むこと；店の開店時間。",
        en: "business operations; open for business",
        zh: "营业；经营",
        tw: "營業；經營",
        ko: "영업",
        vi: "kinh doanh; mở cửa",
        th: "การประกอบธุรกิจ; เปิดทำการ",
        my: "စီးပွားရေးလုပ်ငန်း; ဆိုင်ဖွင့်ခြင်း",
        km: "ប្រតិបត្តិការអាជីវកម្ម; បើកឱ្យសេវា",
      },
      furigana: [
        {
          rb: "営業",
          rt: "えいぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "営",
          on: ["エイ"],
          kun: ["いとな.む", "いとな.み"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 312,
      kanji: "衛星",
      reading: "えいせい",
      meanings: {
        ja: "惑星の周りを回る天体。",
        en: "(natural) satellite",
        zh: "卫星（天然）",
        tw: "衛星（天然）",
        ko: "위성 (자연위성)",
        vi: "vệ tinh (tự nhiên)",
        th: "ดาวบริวาร (ธรรมชาติ)",
        my: "အာကာသ ဂြိုလ်တိုက် (သဘာဝ)",
        km: "ផ្កាយរង្វង់ (ធម្មជាតិ)",
      },
      furigana: [
        {
          rb: "衛星",
          rt: "えいせい",
        },
      ],
      kanjiInfo: [
        {
          char: "衛",
          on: ["エイ", "エ"],
          kun: [],
          strokes: 16,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "星",
          on: ["セイ", "ショウ"],
          kun: ["ほし", "-ぼし"],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 313,
      kanji: "栄養",
      reading: "えいよう",
      meanings: {
        ja: "体の成長・健康に必要な物質。",
        en: "nutrition; nourishment",
        zh: "营养",
        tw: "營養",
        ko: "영양",
        vi: "dinh dưỡng",
        th: "โภชนาการ",
        my: "အာဟာရ",
        km: "អាហារូបត្ថម្ភ",
      },
      furigana: [
        {
          rb: "栄養",
          rt: "えいよう",
        },
      ],
      kanjiInfo: [
        {
          char: "栄",
          on: ["エイ", "ヨウ"],
          kun: ["さか.える", "は.え", "-ば.え", "は.える", "え"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "養",
          on: ["ヨウ", "リョウ"],
          kun: ["やしな.う"],
          strokes: 15,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 314,
      kanji: "笑顔",
      reading: "えがお",
      meanings: {
        ja: "笑っている顔。",
        en: "smiling face; smile",
        zh: "笑脸；微笑",
        tw: "笑臉；微笑",
        ko: "웃는 얼굴; 미소",
        vi: "khuôn mặt mỉm cười; nụ cười",
        th: "ใบหน้ายิ้มแย้ม; รอยยิ้ม",
        my: "ပြုံးနေလျောက်မျက်နှာ; ပြုံး",
        km: "មុខញញឹម; ស្នាមញញឹម",
      },
      furigana: [
        {
          rb: "笑顔",
          rt: "えがお",
        },
      ],
      kanjiInfo: [
        {
          char: "笑",
          on: ["ショウ"],
          kun: ["わら.う", "え.む"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "顔",
          on: ["ガン"],
          kun: ["かお"],
          strokes: 18,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 315,
      kanji: "餌",
      reading: "えさ",
      meanings: {
        ja: "動物に与える食べ物。",
        en: "feed; bait (for animals)",
        zh: "饲料；诱饵",
        tw: "飼料；餌",
        ko: "먹이; 미끼",
        vi: "thức ăn (cho động vật); mồi",
        th: "อาหารสัตว์; เหยื่อ",
        my: "မွေးတိရစ္ဆာန်အစာ; အမူး",
        km: "អាហារ​សត្វ; ចំណី",
      },
      furigana: [
        {
          rb: "餌",
          rt: "えさ",
        },
      ],
      kanjiInfo: [
        {
          char: "餌",
          on: ["ジ", "ニ"],
          kun: ["え", "えば", "えさ", "もち"],
          strokes: 14,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 316,
      kanji: "エネルギー",
      reading: "エネルギー",
      meanings: {
        ja: "エネルギー。仕事をする能力。",
        en: "energy",
        zh: "能量",
        tw: "能量",
        ko: "에너지",
        vi: "năng lượng",
        th: "พลังงาน",
        my: "စွမ်းအင်",
        km: "ថាមពល",
      },
      furigana: [
        {
          rb: "エネルギー",
          rt: "エネルギー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 317,
      kanji: "円",
      reading: "えん",
      meanings: {
        ja: "日本の通貨単位。",
        en: "yen (Japanese currency)",
        zh: "日元",
        tw: "日圓",
        ko: "엔화",
        vi: "yên (tiền Nhật)",
        th: "เงินเยน",
        my: "ယန်း (ဂျပန်ငွေ)",
        km: "យេន (រូបិយប័ណ្ណជប៉ុន)",
      },
      furigana: [
        {
          rb: "円",
          rt: "えん",
        },
      ],
      kanjiInfo: [
        {
          char: "円",
          on: ["エン"],
          kun: ["まる.い", "まる", "まど", "まど.か", "まろ.やか"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 318,
      kanji: "延期",
      reading: "えんき",
      meanings: {
        ja: "期日をのばすこと。",
        en: "postponement; deferment",
        zh: "延期",
        tw: "延期",
        ko: "연기",
        vi: "hoãn lại",
        th: "การเลื่อนออกไป",
        my: "နောက်တော်တိုးခြင်း",
        km: "ពន្យារពេល",
      },
      furigana: [
        {
          rb: "延期",
          rt: "えんき",
        },
      ],
      kanjiInfo: [
        {
          char: "延",
          on: ["エン"],
          kun: ["の.びる", "の.べる", "の.べ", "の.ばす"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 319,
      kanji: "演技",
      reading: "えんぎ",
      meanings: {
        ja: "役を演じること。",
        en: "acting; performance",
        zh: "表演（演技）",
        tw: "演技；表演",
        ko: "연기",
        vi: "diễn xuất",
        th: "การแสดง (บทบาท)",
        my: "သရုပ်ဆောင်ချက်",
        km: "ការសម្តែង",
      },
      furigana: [
        {
          rb: "演技",
          rt: "えんぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "演",
          on: ["エン"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "技",
          on: ["ギ"],
          kun: ["わざ"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 320,
      kanji: "援助",
      reading: "えんじょ",
      meanings: {
        ja: "力を貸して助けること。",
        en: "assistance; aid; support",
        zh: "援助；帮助",
        tw: "援助；協助",
        ko: "원조; 지원",
        vi: "viện trợ; hỗ trợ",
        th: "ความช่วยเหลือ",
        my: "အကူအညီ",
        km: "ជំនួយ; អន្តរាគមន៍",
      },
      furigana: [
        {
          rb: "援助",
          rt: "えんじょ",
        },
      ],
      kanjiInfo: [
        {
          char: "援",
          on: ["エン"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "助",
          on: ["ジョ"],
          kun: ["たす.ける", "たす.かる", "す.ける", "すけ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 321,
      kanji: "エンジン",
      reading: "エンジン",
      meanings: {
        ja: "機械を動かす原動機。",
        en: "engine",
        zh: "引擎；发动机",
        tw: "引擎；發動機",
        ko: "엔진",
        vi: "động cơ",
        th: "เครื่องยนต์",
        my: "အင်ဂျင်",
        km: "ម៉ាស៊ីន",
      },
      furigana: [
        {
          rb: "エンジン",
          rt: "エンジン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 322,
      kanji: "演説",
      reading: "えんぜつ",
      meanings: {
        ja: "多くの人の前でする公式な話。",
        en: "speech (public address)",
        zh: "演说；演讲",
        tw: "演說；演講",
        ko: "연설",
        vi: "bài diễn thuyết",
        th: "สุนทรพจน์; การปราศรัย",
        my: "မိန့်ခွန်း",
        km: "សុន្ទរកថា",
      },
      furigana: [
        {
          rb: "演説",
          rt: "えんぜつ",
        },
      ],
      kanjiInfo: [
        {
          char: "演",
          on: ["エン"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "説",
          on: ["セツ", "ゼイ"],
          kun: ["と.く"],
          strokes: 14,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 323,
      kanji: "演奏",
      reading: "えんそう",
      meanings: {
        ja: "音楽を楽器などでかなでること。",
        en: "musical performance",
        zh: "演奏",
        tw: "演奏",
        ko: "연주",
        vi: "biểu diễn nhạc",
        th: "การบรรเลงดนตรี",
        my: "တီးဝိုင်းသီချင်း ဖျော်ဖြေခြင်း",
        km: "ការសម្តែងតន្រ្តី",
      },
      furigana: [
        {
          rb: "演奏",
          rt: "えんそう",
        },
      ],
      kanjiInfo: [
        {
          char: "演",
          on: ["エン"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "奏",
          on: ["ソウ"],
          kun: ["かな.でる"],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 324,
      kanji: "老い",
      reading: "おい",
      meanings: {
        ja: "年をとること。老齢。",
        en: "old age; aging",
        zh: "衰老；老年",
        tw: "衰老；老年",
        ko: "늙음; 노년",
        vi: "tuổi già; sự lão hóa",
        th: "ความชรา",
        my: "အိုမင်းခြင်း",
        km: "ភាពចាស់",
      },
      furigana: [
        {
          rb: "老い",
          rt: "おい",
        },
      ],
      kanjiInfo: [
        {
          char: "老",
          on: ["ロウ"],
          kun: ["お.いる", "ふ.ける"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 325,
      kanji: "王",
      reading: "おう",
      meanings: {
        ja: "国の君主。王様。",
        en: "king; monarch",
        zh: "国王；君主",
        tw: "國王；君主",
        ko: "왕",
        vi: "vua",
        th: "กษัตริย์",
        my: "ဘုရင်",
        km: "ព្រះរាជា",
      },
      furigana: [
        {
          rb: "王",
          rt: "おう",
        },
      ],
      kanjiInfo: [
        {
          char: "王",
          on: ["オウ", "-ノウ"],
          kun: [],
          strokes: 4,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 326,
      kanji: "応援",
      reading: "おうえん",
      meanings: {
        ja: "励ますこと・支援すること。",
        en: "support; cheering; encouragement",
        zh: "支援；加油",
        tw: "支援；加油",
        ko: "응원; 지원",
        vi: "cổ vũ; ủng hộ",
        th: "การให้กำลังใจ; สนับสนุน",
        my: "အားပေးမှု; အထောက်အပံ့",
        km: "គាំទ្រ; លើកទឹកចិត្ត",
      },
      furigana: [
        {
          rb: "応援",
          rt: "おうえん",
        },
      ],
      kanjiInfo: [
        {
          char: "応",
          on: ["オウ", "ヨウ", "-ノウ"],
          kun: ["あた.る", "まさに", "こた.える"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "援",
          on: ["エン"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 327,
      kanji: "王様",
      reading: "おうさま",
      meanings: {
        ja: "王。敬称を伴った言い方。",
        en: "king (honorific form)",
        zh: "国王（敬称）",
        tw: "國王（敬稱）",
        ko: "임금님",
        vi: "đức vua",
        th: "องค์กษัตริย์",
        my: "ဘုရင်ကြီး",
        km: "ព្រះមហាក្សត្រ",
      },
      furigana: [
        {
          rb: "王様",
          rt: "おうさま",
        },
      ],
      kanjiInfo: [
        {
          char: "王",
          on: ["オウ", "-ノウ"],
          kun: [],
          strokes: 4,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
        {
          char: "様",
          on: ["ヨウ", "ショウ"],
          kun: ["さま", "さん"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 328,
      kanji: "王子",
      reading: "おうじ",
      meanings: {
        ja: "国王の息子。王子。",
        en: "prince",
        zh: "王子；王子殿下",
        tw: "王子",
        ko: "왕자",
        vi: "hoàng tử",
        th: "เจ้าชาย",
        my: "မင်းသား",
        km: "ព្រះអង្គម្ចាស់",
      },
      furigana: [
        {
          rb: "王子",
          rt: "おうじ",
        },
      ],
      kanjiInfo: [
        {
          char: "王",
          on: ["オウ", "-ノウ"],
          kun: [],
          strokes: 4,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 329,
      kanji: "横断",
      reading: "おうだん",
      meanings: {
        ja: "横に渡ること。",
        en: "crossing (a road); traversal",
        zh: "横穿；横越",
        tw: "橫越；橫斷",
        ko: "횡단",
        vi: "băng qua; đi ngang",
        th: "การข้าม (ถนน)",
        my: "ဖြတ်ကျော်ခြင်း",
        km: "ឆ្លងកាត់ផ្លូវ",
      },
      furigana: [
        {
          rb: "横断",
          rt: "おうだん",
        },
      ],
      kanjiInfo: [
        {
          char: "横",
          on: ["オウ"],
          kun: ["よこ"],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 330,
      kanji: "大家",
      reading: "おおや",
      meanings: {
        ja: "賃貸物件の所有者。",
        en: "landlord; landlady",
        zh: "房东",
        tw: "房東",
        ko: "집주인",
        vi: "chủ nhà (cho thuê)",
        th: "เจ้าของบ้านเช่า",
        my: "အိမ်ရှင် (ငှားသူ)",
        km: "ម្ចាស់ផ្ទះជួល",
      },
      furigana: [
        {
          rb: "大家",
          rt: "おおや",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 331,
      kanji: "丘",
      reading: "おか",
      meanings: {
        ja: "小高い山・丘陵。",
        en: "hill; knoll",
        zh: "小山；丘陵",
        tw: "小山丘；丘陵",
        ko: "언덕",
        vi: "đồi",
        th: "เนินเขา",
        my: "တောင်ကုန်း",
        km: "កំពូលភ្នំតូច; ភ្នំទន់",
      },
      furigana: [
        {
          rb: "丘",
          rt: "おか",
        },
      ],
      kanjiInfo: [
        {
          char: "丘",
          on: ["キュウ"],
          kun: ["おか"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 332,
      kanji: "沖",
      reading: "おき",
      meanings: {
        ja: "岸から離れた海上。",
        en: "offing; open sea (off the coast)",
        zh: "近海外海；外海",
        tw: "外海；近岸外海",
        ko: "먼바다 (연안 바깥)",
        vi: "biển khơi (ngoài khơi)",
        th: "ทะเลนอกฝั่ง",
        my: "ကမ်းခြေပြင်ပပင်လယ်",
        km: "សមុទ្រខាងក្រៅជិតឆ្នេរ",
      },
      furigana: [
        {
          rb: "沖",
          rt: "おき",
        },
      ],
      kanjiInfo: [
        {
          char: "沖",
          on: ["チュウ"],
          kun: ["おき", "おきつ", "ちゅう.する", "わく"],
          strokes: 7,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 333,
      kanji: "奥",
      reading: "おく",
      meanings: {
        ja: "内部の深い所；奥まった所。",
        en: "inner part; depths; back (of something)",
        zh: "深处；里面",
        tw: "深處；裡面",
        ko: "안쪽 깊은 곳",
        vi: "bên trong sâu; phía trong",
        th: "ส่วนลึก/ด้านในสุด",
        my: "အတွင်းအမြင့်ဆုံးနေရာ",
        km: "ខាងក្នុងជ្រៅ; ដោយស្និទ្ធ",
      },
      furigana: [
        {
          rb: "奥",
          rt: "おく",
        },
      ],
      kanjiInfo: [
        {
          char: "奥",
          on: ["オウ"],
          kun: ["おく", "おく.まる", "くま"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 334,
      kanji: "お辞儀",
      reading: "おじぎ",
      meanings: {
        ja: "礼として頭を下げること。",
        en: "bow (as a greeting or courtesy)",
        zh: "鞠躬",
        tw: "鞠躬",
        ko: "인사로 허리 숙임",
        vi: "cúi chào",
        th: "การโค้งคำนับ",
        my: "ခါးကိုင်း၍ ဂౌరవဖြင့် မင်္ဂလာပါပြောခြင်း",
        km: "ការជប់ក្បាលជាសក្ការៈ",
      },
      furigana: [
        {
          rb: "お辞儀",
          rt: "おじぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "辞",
          on: ["ジ"],
          kun: ["や.める", "いな.む"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "儀",
          on: ["ギ"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 335,
      kanji: "お喋り",
      reading: "おしゃべり",
      meanings: {
        ja: "気軽なお話・おしゃべり。",
        en: "chatter; chatting; talkative person",
        zh: "闲聊；话多的人",
        tw: "聊天；健談的人",
        ko: "수다; 수다스러운 사람",
        vi: "tán gẫu; người hay nói",
        th: "การคุยเล่น; คนช่างคุย",
        my: "စကားများသူ; စကားဝိုင်း",
        km: "និយាយលេង; មនុស្សច្រើនបេះដូង",
      },
      furigana: [
        {
          rb: "お喋り",
          rt: "おしゃべり",
        },
      ],
      kanjiInfo: [
        {
          char: "喋",
          on: ["チョウ", "トウ"],
          kun: ["しゃべ.る", "ついば.む"],
          strokes: 12,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 336,
      kanji: "汚染",
      reading: "おせん",
      meanings: {
        ja: "よごれること。環境の汚れ。",
        en: "pollution; contamination",
        zh: "污染",
        tw: "汙染",
        ko: "오염",
        vi: "ô nhiễm",
        th: "มลพิษ; การปนเปื้อน",
        my: "ညစ်ညမ်းမှု",
        km: "ការបំពុល",
      },
      furigana: [
        {
          rb: "汚染",
          rt: "おせん",
        },
      ],
      kanjiInfo: [
        {
          char: "汚",
          on: ["オ"],
          kun: [
            "けが.す",
            "けが.れる",
            "けが.らわしい",
            "よご.す",
            "よご.れる",
            "きたな.い",
          ],
          strokes: 6,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "染",
          on: ["セン"],
          kun: ["そ.める", "そ.まる", "し.みる", "し.み"],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 337,
      kanji: "お互い",
      reading: "おたがい",
      meanings: {
        ja: "双方・互い。",
        en: "each other; one another; mutual",
        zh: "彼此；互相",
        tw: "彼此；互相",
        ko: "서로; 상호",
        vi: "lẫn nhau",
        th: "กันและกัน; ซึ่งกันและกัน",
        my: "တစ်ချိန်တည်း; အပြန်အလှန်",
        km: "គ្នាទៅវិញទៅមក; អន្តរសហការ",
      },
      furigana: [
        {
          rb: "お互い",
          rt: "おたがい",
        },
      ],
      kanjiInfo: [
        {
          char: "互",
          on: ["ゴ"],
          kun: ["たが.い", "かたみ.に"],
          strokes: 4,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 338,
      kanji: "鬼",
      reading: "おに",
      meanings: {
        ja: "日本の伝説上の怪物。",
        en: "ogre; demon (in Japanese folklore)",
        zh: "鬼；妖怪",
        tw: "鬼；妖怪",
        ko: "도깨비; 귀신",
        vi: "quỷ; yêu quái",
        th: "ยักษ์/ปีศาจ (นิทานญี่ปุ่น)",
        my: "ဘီလူး; နတ်ဆိုး",
        km: "អារក្ស; ឧត្ដម",
      },
      furigana: [
        {
          rb: "鬼",
          rt: "おに",
        },
      ],
      kanjiInfo: [
        {
          char: "鬼",
          on: ["キ"],
          kun: ["おに", "おに-"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 339,
      kanji: "帯",
      reading: "おび",
      meanings: {
        ja: "着物に締める帯。",
        en: "obi (kimono sash); belt",
        zh: "带子（和服腰带）",
        tw: "帶子（和服腰帶）",
        ko: "오비(기모노 띠)",
        vi: "dây obi (thắt lưng kimono)",
        th: "ผ้าโอบิ (ผ้าคาดกิโมโน)",
        my: "အိုဘီ (ကိမိုနို ဝတ်သိပ်ခါး‌بယ်)",
        km: "ខ្សែក្រវាត់អូប៊ី (គីមណូ)",
      },
      furigana: [
        {
          rb: "帯",
          rt: "おび",
        },
      ],
      kanjiInfo: [
        {
          char: "帯",
          on: ["タイ"],
          kun: ["お.びる", "おび"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 340,
      kanji: "お昼",
      reading: "おひる",
      meanings: {
        ja: "昼食；昼の時間。",
        en: "lunch; midday",
        zh: "午饭；中午",
        tw: "午餐；中午",
        ko: "점심; 한낮",
        vi: "bữa trưa; giữa trưa",
        th: "มื้อกลางวัน; เที่ยงวัน",
        my: "နေ့လယ်စာ; နေ့လယ်",
        km: "អាហារថ្ងៃត្រង់; ថ្ងៃត្រង់",
      },
      furigana: [
        {
          rb: "お昼",
          rt: "おひる",
        },
      ],
      kanjiInfo: [
        {
          char: "昼",
          on: ["チュウ"],
          kun: ["ひる"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 341,
      kanji: "オフィス",
      reading: "オフィス",
      meanings: {
        ja: "事務所；仕事場。",
        en: "office; workplace",
        zh: "办公室；办公处",
        tw: "辦公室",
        ko: "오피스; 사무실",
        vi: "văn phòng",
        th: "สำนักงาน",
        my: "ရုံး; ရုံးခန်း",
        km: "ការិយាល័យ",
      },
      furigana: [
        {
          rb: "オフィス",
          rt: "オフィス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 342,
      kanji: "思い出",
      reading: "おもいで",
      meanings: {
        ja: "過去を思い起こす記憶。",
        en: "memory; recollection",
        zh: "回忆；回想",
        tw: "回憶；回想",
        ko: "추억; 회상",
        vi: "kỷ niệm; hồi ức",
        th: "ความทรงจำ",
        my: "အတွေးအခေါ်မှတ်ဉာဏ်",
        km: "អនុស្សាវរីយ៍; ការចងចាំ",
      },
      furigana: [
        {
          rb: "思い出",
          rt: "おもいで",
        },
      ],
      kanjiInfo: [
        {
          char: "思",
          on: ["シ"],
          kun: ["おも.う", "おもえら.く", "おぼ.す"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 343,
      kanji: "泳ぎ",
      reading: "およぎ",
      meanings: {
        ja: "泳ぐこと。水泳。",
        en: "swimming",
        zh: "游泳",
        tw: "游泳",
        ko: "수영",
        vi: "bơi lội",
        th: "การว่ายน้ำ",
        my: "ရေကူးခြင်း",
        km: "ហែលទឹក",
      },
      furigana: [
        {
          rb: "泳ぎ",
          rt: "およぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "泳",
          on: ["エイ"],
          kun: ["およ.ぐ"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 344,
      kanji: "音",
      reading: "おん",
      meanings: {
        ja: "聞こえる振動。音。",
        en: "sound (audible noise)",
        zh: "声音；响声",
        tw: "聲音",
        ko: "소리",
        vi: "âm thanh",
        th: "เสียง",
        my: "အသံ",
        km: "សំឡេង",
      },
      furigana: [
        {
          rb: "音",
          rt: "おん",
        },
      ],
      kanjiInfo: [
        {
          char: "音",
          on: ["オン", "イン", "-ノン"],
          kun: ["おと", "ね"],
          strokes: 9,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 345,
      kanji: "恩",
      reading: "おん",
      meanings: {
        ja: "受けた好意・めぐみ。",
        en: "favor; kindness (received); obligation",
        zh: "恩惠；情义",
        tw: "恩惠；情義",
        ko: "은혜",
        vi: "ân huệ",
        th: "พระคุณ; บุญคุณ",
        my: "ကျေးဇူး; အကျိုးခံစားမှု",
        km: "គុណ; គុណធម៌",
      },
      furigana: [
        {
          rb: "恩",
          rt: "おん",
        },
      ],
      kanjiInfo: [
        {
          char: "恩",
          on: ["オン"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 346,
      kanji: "温度",
      reading: "おんど",
      meanings: {
        ja: "熱さ・冷たさの程度。",
        en: "temperature",
        zh: "温度",
        tw: "溫度",
        ko: "온도",
        vi: "nhiệt độ",
        th: "อุณหภูมิ",
        my: "အပူချိန်",
        km: "សីតុណ្ហភាព",
      },
      furigana: [
        {
          rb: "温度",
          rt: "おんど",
        },
      ],
      kanjiInfo: [
        {
          char: "温",
          on: ["オン"],
          kun: [
            "あたた.か",
            "あたた.かい",
            "あたた.まる",
            "あたた.める",
            "ぬく",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "度",
          on: ["ド", "ト", "タク"],
          kun: ["たび", "-た.い"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 347,
      kanji: "可",
      reading: "か",
      meanings: {
        ja: "よいと認めること。可。",
        en: "approval; pass (grade of 'acceptable')",
        zh: "可；合格（评语）",
        tw: "可；及格（評語）",
        ko: "가 (합격/허가)",
        vi: "khả; đạt (mức chấp nhận)",
        th: "ผ่าน; อนุมัติ",
        my: "လက်ခံနိုင်သည် ('ကောင်း' အဆင့်)",
        km: "អនុម័ត; ត្រូវបានជាប់ ('គ្រប់គ្រាន់')",
      },
      furigana: [
        {
          rb: "可",
          rt: "か",
        },
      ],
      kanjiInfo: [
        {
          char: "可",
          on: ["カ", "コク"],
          kun: ["-べ.き", "-べ.し"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 348,
      kanji: "蚊",
      reading: "か",
      meanings: {
        ja: "吸血する小さな昆虫。",
        en: "mosquito",
        zh: "蚊子",
        tw: "蚊子",
        ko: "모기",
        vi: "muỗi",
        th: "ยุง",
        my: "ဖယောင်း",
        km: "មូស",
      },
      furigana: [
        {
          rb: "蚊",
          rt: "か",
        },
      ],
      kanjiInfo: [
        {
          char: "蚊",
          on: ["ブン"],
          kun: ["か"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 349,
      kanji: "課",
      reading: "か",
      meanings: {
        ja: "学校の授業・会社の部署。",
        en: "lesson; section/department (in a company)",
        zh: "课；课题；科室",
        tw: "課；部門",
        ko: "과 (수업/부서)",
        vi: "bài học; ban/bộ phận",
        th: "บทเรียน; แผนก",
        my: "သင်ခန်းစာ; ဌာန",
        km: "មេរៀន; ផ្នែក (ក្រុមហ៊ុន)",
      },
      furigana: [
        {
          rb: "課",
          rt: "か",
        },
      ],
      kanjiInfo: [
        {
          char: "課",
          on: ["カ"],
          kun: [],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 350,
      kanji: "カー",
      reading: "カー",
      meanings: {
        ja: "自動車（口語）。",
        en: "car (loanword)",
        zh: "汽车（外来语）",
        tw: "車（外來語）",
        ko: "카(자동차, 외래어)",
        vi: "xe hơi (từ mượn)",
        th: "รถยนต์ (คำยืม)",
        my: "ကား (ဆယ်လ်လုံးအသုံး)",
        km: "ឡាន (ពាក្យបន្ថែមពីបរទេស)",
      },
      furigana: [
        {
          rb: "カー",
          rt: "カー",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
