export const n4part8 = {
  Lesson8: [
    {
      id: 318,
      kanji: "苦い",
      reading: "にがい",
      meanings: {
        ja: "苦い",
        en: "bitter",
        zh: "苦的",
        tw: "苦的",
        ko: "쓴",
        vi: "đắng",
        th: "ขม",
        my: "စပ်",
        km: "ជូរ",
      },
      furigana: [
        {
          rb: "苦い",
          rt: "にがい",
        },
      ],
      kanjiInfo: [
        {
          char: "苦",
          on: ["ク"],
          kun: [
            "くる.しい",
            "-ぐる.しい",
            "くる.しむ",
            "くる.しめる",
            "にが.い",
            "にが.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 319,
      kanji: "柔らかい",
      reading: "やわらかい",
      meanings: {
        ja: "柔らかい",
        en: "soft",
        zh: "柔软的",
        tw: "柔軟的",
        ko: "부드러운",
        vi: "mềm",
        th: "นุ่ม",
        my: "နူးညံ့သော",
        km: "ទន់",
      },
      furigana: [
        {
          rb: "柔らかい",
          rt: "やわらかい",
        },
      ],
      kanjiInfo: [
        {
          char: "柔",
          on: ["ジュウ", "ニュウ"],
          kun: ["やわ.らか", "やわ.らかい", "やわ", "やわ.ら"],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 320,
      kanji: "厳しい",
      reading: "きびしい",
      meanings: {
        ja: "厳しい",
        en: "severe",
        zh: "严格的",
        tw: "嚴格的",
        ko: "엄격한",
        vi: "nghiêm khắc",
        th: "เข้มงวด",
        my: "ကြီးကြပ်သော",
        km: "តឹងរឹង",
      },
      furigana: [
        {
          rb: "厳しい",
          rt: "きびしい",
        },
      ],
      kanjiInfo: [
        {
          char: "厳",
          on: ["ゲン", "ゴン"],
          kun: ["おごそ.か", "きび.しい", "いか.めしい", "いつくし"],
          strokes: 17,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 321,
      kanji: "深い",
      reading: "ふかい",
      meanings: {
        ja: "深い",
        en: "deep",
        zh: "深的",
        tw: "深的",
        ko: "깊은",
        vi: "sâu",
        th: "ลึก",
        my: "နက်သော",
        km: "ជ្រៅ",
      },
      furigana: [
        {
          rb: "深い",
          rt: "ふかい",
        },
      ],
      kanjiInfo: [
        {
          char: "深",
          on: ["シン"],
          kun: ["ふか.い", "-ぶか.い", "ふか.まる", "ふか.める", "み-"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 322,
      kanji: "悲しい",
      reading: "かなしい",
      meanings: {
        ja: "悲しい",
        en: "sad",
        zh: "悲伤的",
        tw: "悲傷的",
        ko: "슬픈",
        vi: "buồn",
        th: "เศร้า",
        my: "ဝမ်းနည်းသော",
        km: "ក្លៀវក្លា",
      },
      furigana: [
        {
          rb: "悲しい",
          rt: "かなしい",
        },
      ],
      kanjiInfo: [
        {
          char: "悲",
          on: ["ヒ"],
          kun: ["かな.しい", "かな.しむ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 323,
      kanji: "浅い",
      reading: "あさい",
      meanings: {
        ja: "浅い",
        en: "shallow",
        zh: "浅的",
        tw: "淺的",
        ko: "얕은",
        vi: "nông",
        th: "ตื้น",
        my: "ပါးနပ်သော",
        km: "រាក់",
      },
      furigana: [
        {
          rb: "浅い",
          rt: "あさい",
        },
      ],
      kanjiInfo: [
        {
          char: "浅",
          on: ["セン"],
          kun: ["あさ.い"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 324,
      kanji: "怖い",
      reading: "こわい",
      meanings: {
        ja: "怖い",
        en: "scary",
        zh: "可怕的",
        tw: "可怕的",
        ko: "무서운",
        vi: "đáng sợ",
        th: "น่ากลัว",
        my: "ကြောက်မက်ဖွယ်",
        km: "គួរឱ្យភ័យ",
      },
      furigana: [
        {
          rb: "怖い",
          rt: "こわい",
        },
      ],
      kanjiInfo: [
        {
          char: "怖",
          on: ["フ", "ホ"],
          kun: ["こわ.い", "こわ.がる", "お.じる", "おそ.れる"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 325,
      kanji: "恥ずかしい",
      reading: "はずかしい",
      meanings: {
        ja: "恥ずかしい",
        en: "embarrassing",
        zh: "害羞的",
        tw: "害羞的",
        ko: "부끄러운",
        vi: "xấu hổ",
        th: "น่าอาย",
        my: "အရှက်ရသော",
        km: "អៀន",
      },
      furigana: [
        {
          rb: "恥ずかしい",
          rt: "はずかしい",
        },
      ],
      kanjiInfo: [
        {
          char: "恥",
          on: ["チ"],
          kun: ["は.じる", "はじ", "は.じらう", "は.ずかしい"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 326,
      kanji: "美しい",
      reading: "うつくしい",
      meanings: {
        ja: "美しい",
        en: "beautiful",
        zh: "美丽的",
        tw: "美麗的",
        ko: "아름다운",
        vi: "đẹp",
        th: "สวยงาม",
        my: "လှပသော",
        km: "ស្រស់ស្អាត",
      },
      furigana: [
        {
          rb: "美しい",
          rt: "うつくしい",
        },
      ],
      kanjiInfo: [
        {
          char: "美",
          on: ["ビ", "ミ"],
          kun: ["うつく.しい"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 327,
      kanji: "素晴らしい",
      reading: "すばらしい",
      meanings: {
        ja: "素晴らしい",
        en: "wonderful",
        zh: "极好的",
        tw: "極好的",
        ko: "훌륭한",
        vi: "tuyệt vời",
        th: "ยอดเยี่ยม",
        my: "လှပအံ့သြဖွယ်",
        km: "អស្ចារ្យ",
      },
      furigana: [
        {
          rb: "素晴らしい",
          rt: "すばらしい",
        },
      ],
      kanjiInfo: [
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "晴",
          on: ["セイ"],
          kun: ["は.れる", "は.れ", "は.れ-", "-ば.れ", "は.らす"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 328,
      kanji: "細かい",
      reading: "こまかい",
      meanings: {
        ja: "細かい",
        en: "small; fine",
        zh: "细小的",
        tw: "細小的",
        ko: "작은; 세밀한",
        vi: "nhỏ; chi tiết",
        th: "ละเอียด",
        my: "အသေးစိတ်",
        km: "លម្អិត",
      },
      furigana: [
        {
          rb: "細かい",
          rt: "こまかい",
        },
      ],
      kanjiInfo: [
        {
          char: "細",
          on: ["サイ"],
          kun: ["ほそ.い", "ほそ.る", "こま.か", "こま.かい"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 329,
      kanji: "珍しい",
      reading: "めずらしい",
      meanings: {
        ja: "珍しい",
        en: "rare",
        zh: "稀罕的",
        tw: "稀罕的",
        ko: "드문",
        vi: "hiếm",
        th: "หายาก",
        my: "ရှားပါးသော",
        km: "កម្រ",
      },
      furigana: [
        {
          rb: "珍しい",
          rt: "めずらしい",
        },
      ],
      kanjiInfo: [
        {
          char: "珍",
          on: ["チン"],
          kun: ["めずら.しい", "たから"],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 330,
      kanji: "寂しい",
      reading: "さびしい",
      meanings: {
        ja: "寂しい",
        en: "lonely",
        zh: "寂寞的",
        tw: "寂寞的",
        ko: "외로운",
        vi: "cô đơn",
        th: "เหงา",
        my: "အထီးကျန်သော",
        km: "ឯកែង",
      },
      furigana: [
        {
          rb: "寂しい",
          rt: "さびしい",
        },
      ],
      kanjiInfo: [
        {
          char: "寂",
          on: ["ジャク", "セキ"],
          kun: ["さび", "さび.しい", "さび.れる", "さみ.しい"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 331,
      kanji: "凄い",
      reading: "すごい",
      meanings: {
        ja: "凄い",
        en: "terrible; amazing",
        zh: "厉害的",
        tw: "厲害的",
        ko: "굉장한",
        vi: "ghê gớm; tuyệt vời",
        th: "สุดยอด",
        my: "ကြောက်မက်ဖွယ် / အရမ်းအံ့သြ",
        km: "អស្ចារ្យ / គួរឱ្យភ័យ",
      },
      furigana: [
        {
          rb: "凄い",
          rt: "すごい",
        },
      ],
      kanjiInfo: [
        {
          char: "凄",
          on: ["セイ", "サイ"],
          kun: ["さむ.い", "すご.い", "すさ.まじい"],
          strokes: 10,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 332,
      kanji: "正しい",
      reading: "ただしい",
      meanings: {
        ja: "正しい",
        en: "right; correct",
        zh: "正确的",
        tw: "正確的",
        ko: "옳은",
        vi: "đúng",
        th: "ถูกต้อง",
        my: "မှန်ကန်သော",
        km: "ត្រឹមត្រូវ",
      },
      furigana: [
        {
          rb: "正しい",
          rt: "ただしい",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 333,
      kanji: "眠い",
      reading: "ねむい",
      meanings: {
        ja: "眠い",
        en: "sleepy",
        zh: "困的",
        tw: "睏的",
        ko: "졸린",
        vi: "buồn ngủ",
        th: "ง่วงนอน",
        my: "အိပ်ငိုက်သော",
        km: "ងងុយគេង",
      },
      furigana: [
        {
          rb: "眠い",
          rt: "ねむい",
        },
      ],
      kanjiInfo: [
        {
          char: "眠",
          on: ["ミン"],
          kun: ["ねむ.る", "ねむ.い"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 334,
      kanji: "優しい",
      reading: "やさしい",
      meanings: {
        ja: "優しい",
        en: "tender; kind",
        zh: "温柔的",
        tw: "溫柔的",
        ko: "상냥한",
        vi: "hiền lành",
        th: "อ่อนโยน",
        my: "နူးညံ့သိမ်မွေ့သော",
        km: "ទន់ភ្លន់",
      },
      furigana: [
        {
          rb: "優しい",
          rt: "やさしい",
        },
      ],
      kanjiInfo: [
        {
          char: "優",
          on: ["ユウ", "ウ"],
          kun: ["やさ.しい", "すぐ.れる", "まさ.る"],
          strokes: 17,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
