export const n4part11 = {
  Lesson11: [
    {
      id: 378,
      kanji: "踏む",
      reading: "ふむ",
      meanings: {
        ja: "踏む",
        en: "to step on",
        zh: "踩",
        tw: "踩",
        ko: "밟다",
        vi: "giẫm",
        th: "เหยียบ",
        my: "နင်းသည်",
        km: "ដើរលើ",
      },
      furigana: [
        {
          rb: "踏む",
          rt: "ふむ",
        },
      ],
      kanjiInfo: [
        {
          char: "踏",
          on: ["トウ"],
          kun: ["ふ.む", "ふ.まえる"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 379,
      kanji: "盗む",
      reading: "ぬすむ",
      meanings: {
        ja: "盗む",
        en: "to steal",
        zh: "偷",
        tw: "偷",
        ko: "훔치다",
        vi: "ăn trộm",
        th: "ขโมย",
        my: "ခိုးသည်",
        km: "លួច",
      },
      furigana: [
        {
          rb: "盗む",
          rt: "ぬすむ",
        },
      ],
      kanjiInfo: [
        {
          char: "盗",
          on: ["トウ"],
          kun: ["ぬす.む", "ぬす.み"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 380,
      kanji: "鳴る",
      reading: "なる",
      meanings: {
        ja: "鳴る",
        en: "to sound",
        zh: "响",
        tw: "響",
        ko: "울리다",
        vi: "reo; kêu",
        th: "ดังขึ้น",
        my: "မြည်သည်",
        km: "រំពង",
      },
      furigana: [
        {
          rb: "鳴る",
          rt: "なる",
        },
      ],
      kanjiInfo: [
        {
          char: "鳴",
          on: ["メイ"],
          kun: ["な.く", "な.る", "な.らす"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 381,
      kanji: "生きる",
      reading: "いきる",
      meanings: {
        ja: "生きる",
        en: "to live",
        zh: "活",
        tw: "活",
        ko: "살다",
        vi: "sống",
        th: "มีชีวิต",
        my: "အသက်ရှင်သည်",
        km: "រស់",
      },
      furigana: [
        {
          rb: "生きる",
          rt: "いきる",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 382,
      kanji: "沸く",
      reading: "わく",
      meanings: {
        ja: "沸く",
        en: "to grow hot (e.g. water)",
        zh: "沸腾",
        tw: "沸騰",
        ko: "끓다",
        vi: "sôi",
        th: "เดือด",
        my: "ပေါက်သည်",
        km: "រំពុះ",
      },
      furigana: [
        {
          rb: "沸く",
          rt: "わく",
        },
      ],
      kanjiInfo: [
        {
          char: "沸",
          on: ["フツ"],
          kun: ["わ.く", "わ.かす"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 383,
      kanji: "折る",
      reading: "おる",
      meanings: {
        ja: "折る",
        en: "to break",
        zh: "折断",
        tw: "折斷",
        ko: "꺾다",
        vi: "bẻ gãy",
        th: "หัก",
        my: "ခွဲသည်",
        km: "បែកបាក់",
      },
      furigana: [
        {
          rb: "折る",
          rt: "おる",
        },
      ],
      kanjiInfo: [
        {
          char: "折",
          on: ["セツ", "シャク"],
          kun: ["お.る", "おり", "お.り", "-お.り", "お.れる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 384,
      kanji: "聞こえる",
      reading: "きこえる",
      meanings: {
        ja: "聞こえる",
        en: "to be heard",
        zh: "听见",
        tw: "聽見",
        ko: "들리다",
        vi: "nghe thấy",
        th: "ได้ยิน",
        my: "ကြားရသည်",
        km: "ឮ",
      },
      furigana: [
        {
          rb: "聞こえる",
          rt: "きこえる",
        },
      ],
      kanjiInfo: [
        {
          char: "聞",
          on: ["ブン", "モン"],
          kun: ["き.く", "き.こえる"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 385,
      kanji: "壊す",
      reading: "こわす",
      meanings: {
        ja: "壊す",
        en: "to break",
        zh: "弄坏",
        tw: "弄壞",
        ko: "망가뜨리다",
        vi: "làm hỏng",
        th: "ทำลาย",
        my: "ဖျက်သည်",
        km: "បំបាក់",
      },
      furigana: [
        {
          rb: "壊す",
          rt: "こわす",
        },
      ],
      kanjiInfo: [
        {
          char: "壊",
          on: ["カイ", "エ"],
          kun: ["こわ.す", "こわ.れる", "やぶ.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 386,
      kanji: "怒る",
      reading: "おこる",
      meanings: {
        ja: "怒る",
        en: "to get angry",
        zh: "生气",
        tw: "生氣",
        ko: "화내다",
        vi: "giận dữ",
        th: "โกรธ",
        my: "စိတ်ဆိုးသည်",
        km: "ខឹង",
      },
      furigana: [
        {
          rb: "怒る",
          rt: "おこる",
        },
      ],
      kanjiInfo: [
        {
          char: "怒",
          on: ["ド", "ヌ"],
          kun: ["いか.る", "おこ.る"],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 387,
      kanji: "止む",
      reading: "やむ",
      meanings: {
        ja: "止む",
        en: "to cease",
        zh: "停止",
        tw: "停止",
        ko: "그치다",
        vi: "ngừng",
        th: "หยุด",
        my: "ရပ်သည်",
        km: "ឈប់",
      },
      furigana: [
        {
          rb: "止む",
          rt: "やむ",
        },
      ],
      kanjiInfo: [
        {
          char: "止",
          on: ["シ"],
          kun: [
            "と.まる",
            "-ど.まり",
            "と.める",
            "-と.める",
            "-ど.め",
            "とど.める",
            "とど.め",
            "とど.まる",
            "や.める",
            "や.む",
            "-や.む",
            "よ.す",
            "-さ.す",
            "-さ.し",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 388,
      kanji: "拾う",
      reading: "ひろう",
      meanings: {
        ja: "拾う",
        en: "to pick up",
        zh: "捡",
        tw: "撿",
        ko: "줍다",
        vi: "nhặt lên",
        th: "เก็บขึ้น",
        my: "拾သည်",
        km: "ប្រមូល",
      },
      furigana: [
        {
          rb: "拾う",
          rt: "ひろう",
        },
      ],
      kanjiInfo: [
        {
          char: "拾",
          on: ["シュウ", "ジュウ"],
          kun: ["ひろ.う"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 389,
      kanji: "比べる",
      reading: "くらべる",
      meanings: {
        ja: "比べる",
        en: "to compare",
        zh: "比较",
        tw: "比較",
        ko: "비교하다",
        vi: "so sánh",
        th: "เปรียบเทียบ",
        my: "နှိုင်းယှဉ်သည်",
        km: "ប្រៀបធៀប",
      },
      furigana: [
        {
          rb: "比べる",
          rt: "くらべる",
        },
      ],
      kanjiInfo: [
        {
          char: "比",
          on: ["ヒ"],
          kun: ["くら.べる"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 390,
      kanji: "焼く",
      reading: "やく",
      meanings: {
        ja: "焼く",
        en: "to burn",
        zh: "烧",
        tw: "烤",
        ko: "굽다",
        vi: "nướng",
        th: "ย่าง",
        my: "ကြော်သည်",
        km: "ដុត",
      },
      furigana: [
        {
          rb: "焼く",
          rt: "やく",
        },
      ],
      kanjiInfo: [
        {
          char: "焼",
          on: ["ショウ"],
          kun: ["や.く", "や.き", "や.き-", "-や.き", "や.ける"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 391,
      kanji: "建てる",
      reading: "たてる",
      meanings: {
        ja: "建てる",
        en: "to build",
        zh: "建造",
        tw: "建造",
        ko: "짓다",
        vi: "xây dựng",
        th: "สร้าง",
        my: "ဆောက်သည်",
        km: "សង់",
      },
      furigana: [
        {
          rb: "建てる",
          rt: "たてる",
        },
      ],
      kanjiInfo: [
        {
          char: "建",
          on: ["ケン", "コン"],
          kun: ["た.てる", "た.て", "-だ.て", "た.つ"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 392,
      kanji: "通る",
      reading: "とおる",
      meanings: {
        ja: "通る",
        en: "to go by",
        zh: "通过",
        tw: "通過",
        ko: "지나가다",
        vi: "đi qua",
        th: "ผ่าน",
        my: "ဖြတ်သန်းသည်",
        km: "ឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "通る",
          rt: "とおる",
        },
      ],
      kanjiInfo: [
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 393,
      kanji: "過ぎる",
      reading: "すぎる",
      meanings: {
        ja: "過ぎる",
        en: "to pass through",
        zh: "经过",
        tw: "經過",
        ko: "지나치다",
        vi: "vượt quá",
        th: "ผ่านไป",
        my: "ကျော်သွားသည်",
        km: "ឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "過ぎる",
          rt: "すぎる",
        },
      ],
      kanjiInfo: [
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 394,
      kanji: "止める",
      reading: "やめる",
      meanings: {
        ja: "止める",
        en: "to stop (an activity)",
        zh: "停止",
        tw: "停止",
        ko: "그만두다",
        vi: "ngừng lại",
        th: "หยุด",
        my: "ရပ်လိုက်သည်",
        km: "ឈប់",
      },
      furigana: [
        {
          rb: "止める",
          rt: "やめる",
        },
      ],
      kanjiInfo: [
        {
          char: "止",
          on: ["シ"],
          kun: [
            "と.まる",
            "-ど.まり",
            "と.める",
            "-と.める",
            "-ど.め",
            "とど.める",
            "とど.め",
            "とど.まる",
            "や.める",
            "や.む",
            "-や.む",
            "よ.す",
            "-さ.す",
            "-さ.し",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 395,
      kanji: "壊れる",
      reading: "こわれる",
      meanings: {
        ja: "壊れる",
        en: "to be broken",
        zh: "坏了",
        tw: "壞掉",
        ko: "망가지다",
        vi: "bị hỏng",
        th: "พัง",
        my: "ပျက်သည်",
        km: "បាក់",
      },
      furigana: [
        {
          rb: "壊れる",
          rt: "こわれる",
        },
      ],
      kanjiInfo: [
        {
          char: "壊",
          on: ["カイ", "エ"],
          kun: ["こわ.す", "こわ.れる", "やぶ.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 396,
      kanji: "揺れる",
      reading: "ゆれる",
      meanings: {
        ja: "揺れる",
        en: "to shake",
        zh: "摇动",
        tw: "搖動",
        ko: "흔들리다",
        vi: "rung lắc",
        th: "สั่นไหว",
        my: "တုန်လှုပ်သည်",
        km: "ញ័រ",
      },
      furigana: [
        {
          rb: "揺れる",
          rt: "ゆれる",
        },
      ],
      kanjiInfo: [
        {
          char: "揺",
          on: ["ヨウ"],
          kun: [
            "ゆ.れる",
            "ゆ.る",
            "ゆ.らぐ",
            "ゆ.るぐ",
            "ゆ.する",
            "ゆ.さぶる",
            "ゆ.すぶる",
            "うご.く",
          ],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 397,
      kanji: "落る",
      reading: "おちる",
      meanings: {
        ja: "落ちる",
        en: "to fall",
        zh: "落下",
        tw: "掉落",
        ko: "떨어지다",
        vi: "rơi",
        th: "ตก",
        my: "ကျသည်",
        km: "ធ្លាក់",
      },
      furigana: [
        {
          rb: "落る",
          rt: "おちる",
        },
      ],
      kanjiInfo: [
        {
          char: "落",
          on: ["ラク"],
          kun: ["お.ちる", "お.ち", "お.とす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 398,
      kanji: "祈る",
      reading: "いのる",
      meanings: {
        ja: "祈る",
        en: "to pray",
        zh: "祈祷",
        tw: "祈禱",
        ko: "기도하다",
        vi: "cầu nguyện",
        th: "อธิษฐาน",
        my: "ဆုတောင်းသည်",
        km: "អធិស្ឋាន",
      },
      furigana: [
        {
          rb: "祈る",
          rt: "いのる",
        },
      ],
      kanjiInfo: [
        {
          char: "祈",
          on: ["キ"],
          kun: ["いの.る"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 399,
      kanji: "起こす",
      reading: "おこす",
      meanings: {
        ja: "起こす",
        en: "to raise",
        zh: "叫醒",
        tw: "叫醒",
        ko: "깨우다",
        vi: "đánh thức",
        th: "ปลุก",
        my: "နိုးစေသည်",
        km: "បញ្ចុះឲ្យភ្ញាក់",
      },
      furigana: [
        {
          rb: "起こす",
          rt: "おこす",
        },
      ],
      kanjiInfo: [
        {
          char: "起",
          on: ["キ"],
          kun: ["お.きる", "お.こる", "お.こす", "おこ.す", "た.つ"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 400,
      kanji: "致す",
      reading: "いたす",
      meanings: {
        ja: "致す",
        en: "to do",
        zh: "做",
        tw: "做",
        ko: "하다 (겸양)",
        vi: "làm (khiêm nhường)",
        th: "ทำ (ถ่อมตัว)",
        my: "ဆောင်ရွက်သည်",
        km: "ធ្វើ (សម្តែងថាខ្ជាប់ខ្ជួន)",
      },
      furigana: [
        {
          rb: "致す",
          rt: "いたす",
        },
      ],
      kanjiInfo: [
        {
          char: "致",
          on: ["チ"],
          kun: ["いた.す"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 401,
      kanji: "噛む",
      reading: "かむ",
      meanings: {
        ja: "噛む",
        en: "to bite",
        zh: "咬",
        tw: "咬",
        ko: "물다",
        vi: "cắn",
        th: "กัด",
        my: "ကိုက်သည်",
        km: "ខាំ",
      },
      furigana: [
        {
          rb: "噛む",
          rt: "かむ",
        },
      ],
      kanjiInfo: [
        {
          char: "噛",
          on: ["コウ", "ゴウ"],
          kun: ["か.む", "か.じる"],
          strokes: 15,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 402,
      kanji: "思う",
      reading: "おもう",
      meanings: {
        ja: "思う",
        en: "to think",
        zh: "想",
        tw: "想",
        ko: "생각하다",
        vi: "nghĩ",
        th: "คิด",
        my: "ထင်သည်",
        km: "គិត",
      },
      furigana: [
        {
          rb: "思う",
          rt: "おもう",
        },
      ],
      kanjiInfo: [
        {
          char: "思",
          on: ["シ"],
          kun: ["おも.う", "おもえら.く", "おぼ.す"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 403,
      kanji: "申し上げる",
      reading: "もうしあげる",
      meanings: {
        ja: "申し上げる",
        en: "to say (humble)",
        zh: "说 (谦语)",
        tw: "說 (謙語)",
        ko: "말씀드리다",
        vi: "thưa (khiêm nhường)",
        th: "กล่าว (ถ่อมตัว)",
        my: "ပြောပါသည် (ယဉ်ကြည်)",
        km: "និយាយ (ទន់ភ្លន់)",
      },
      furigana: [
        {
          rb: "申し上げる",
          rt: "もうしあげる",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 404,
      kanji: "迎える",
      reading: "むかえる",
      meanings: {
        ja: "迎える",
        en: "to go out to meet",
        zh: "迎接",
        tw: "迎接",
        ko: "맞이하다",
        vi: "đón tiếp",
        th: "ต้อนรับ",
        my: "ကြိုဆိုသည်",
        km: "ទទួល",
      },
      furigana: [
        {
          rb: "迎える",
          rt: "むかえる",
        },
      ],
      kanjiInfo: [
        {
          char: "迎",
          on: ["ゲイ"],
          kun: ["むか.える"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 405,
      kanji: "触る",
      reading: "さわる",
      meanings: {
        ja: "触る",
        en: "to touch",
        zh: "触摸",
        tw: "觸摸",
        ko: "만지다",
        vi: "chạm",
        th: "สัมผัส",
        my: "ထိသည်",
        km: "ប៉ះ",
      },
      furigana: [
        {
          rb: "触る",
          rt: "さわる",
        },
      ],
      kanjiInfo: [
        {
          char: "触",
          on: ["ショク"],
          kun: ["ふ.れる", "さわ.る", "さわ"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 406,
      kanji: "捕まえる",
      reading: "つかまえる",
      meanings: {
        ja: "捕まえる",
        en: "to catch",
        zh: "抓住",
        tw: "抓住",
        ko: "잡다",
        vi: "bắt",
        th: "จับ",
        my: "ဖမ်းသည်",
        km: "ចាប់",
      },
      furigana: [
        {
          rb: "捕まえる",
          rt: "つかまえる",
        },
      ],
      kanjiInfo: [
        {
          char: "捕",
          on: ["ホ"],
          kun: [
            "と.らえる",
            "と.らわれる",
            "と.る",
            "とら.える",
            "とら.われる",
            "つか.まえる",
            "つか.まる",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 407,
      kanji: "寄る",
      reading: "よる",
      meanings: {
        ja: "寄る",
        en: "to approach",
        zh: "靠近",
        tw: "靠近",
        ko: "다가가다",
        vi: "ghé vào",
        th: "เข้าใกล้",
        my: "နီးစပ်သည်",
        km: "ជិត",
      },
      furigana: [
        {
          rb: "寄る",
          rt: "よる",
        },
      ],
      kanjiInfo: [
        {
          char: "寄",
          on: ["キ"],
          kun: ["よ.る", "-よ.り", "よ.せる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 408,
      kanji: "決まる",
      reading: "きまる",
      meanings: {
        ja: "決まる",
        en: "to be decided",
        zh: "决定",
        tw: "決定",
        ko: "정해지다",
        vi: "được quyết định",
        th: "ถูกกำหนด",
        my: "ဆုံးဖြတ်ထားသည်",
        km: "សម្រេច",
      },
      furigana: [
        {
          rb: "決まる",
          rt: "きまる",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 409,
      kanji: "開く",
      reading: "ひらく",
      meanings: {
        ja: "開く",
        en: "to open",
        zh: "打开",
        tw: "打開",
        ko: "열다",
        vi: "mở",
        th: "เปิด",
        my: "ဖွင့်သည်",
        km: "បើក",
      },
      furigana: [
        {
          rb: "開く",
          rt: "ひらく",
        },
      ],
      kanjiInfo: [
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 410,
      kanji: "逃げる",
      reading: "にげる",
      meanings: {
        ja: "逃げる",
        en: "to run away",
        zh: "逃跑",
        tw: "逃跑",
        ko: "도망가다",
        vi: "chạy trốn",
        th: "หนี",
        my: "ပြေးသည်",
        km: "រត់គេច",
      },
      furigana: [
        {
          rb: "逃げる",
          rt: "にげる",
        },
      ],
      kanjiInfo: [
        {
          char: "逃",
          on: ["トウ"],
          kun: ["に.げる", "に.がす", "のが.す", "のが.れる"],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 411,
      kanji: "包む",
      reading: "つつむ",
      meanings: {
        ja: "包む",
        en: "to wrap up",
        zh: "包裹",
        tw: "包裹",
        ko: "싸다",
        vi: "gói",
        th: "ห่อ",
        my: "ထုပ်သည်",
        km: "រុំ",
      },
      furigana: [
        {
          rb: "包む",
          rt: "つつむ",
        },
      ],
      kanjiInfo: [
        {
          char: "包",
          on: ["ホウ"],
          kun: ["つつ.む", "くる.む"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 412,
      kanji: "飾る",
      reading: "かざる",
      meanings: {
        ja: "飾る",
        en: "to decorate",
        zh: "装饰",
        tw: "裝飾",
        ko: "장식하다",
        vi: "trang trí",
        th: "ตกแต่ง",
        my: "အလှဆင်သည်",
        km: "តុបតែង",
      },
      furigana: [
        {
          rb: "飾る",
          rt: "かざる",
        },
      ],
      kanjiInfo: [
        {
          char: "飾",
          on: ["ショク"],
          kun: ["かざ.る", "かざ.り"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 413,
      kanji: "止める",
      reading: "とめる",
      meanings: {
        ja: "止める",
        en: "to stop",
        zh: "停止",
        tw: "停止",
        ko: "멈추다",
        vi: "dừng",
        th: "หยุด",
        my: "ရပ်သည်",
        km: "ឈប់",
      },
      furigana: [
        {
          rb: "止める",
          rt: "とめる",
        },
      ],
      kanjiInfo: [
        {
          char: "止",
          on: ["シ"],
          kun: [
            "と.まる",
            "-ど.まり",
            "と.める",
            "-と.める",
            "-ど.め",
            "とど.める",
            "とど.め",
            "とど.まる",
            "や.める",
            "や.む",
            "-や.む",
            "よ.す",
            "-さ.す",
            "-さ.し",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 414,
      kanji: "頑張る",
      reading: "がんばる",
      meanings: {
        ja: "頑張る",
        en: "to persevere",
        zh: "努力",
        tw: "努力",
        ko: "열심히 하다",
        vi: "cố gắng",
        th: "พยายาม",
        my: "ကြိုးစားသည်",
        km: "ខំប្រឹងប្រែង",
      },
      furigana: [
        {
          rb: "頑張る",
          rt: "がんばる",
        },
      ],
      kanjiInfo: [
        {
          char: "頑",
          on: ["ガン"],
          kun: ["かたく.な"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "張",
          on: ["チョウ"],
          kun: ["は.る", "-は.り", "-ば.り"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 415,
      kanji: "投げる",
      reading: "なげる",
      meanings: {
        ja: "投げる",
        en: "to throw",
        zh: "投掷",
        tw: "投擲",
        ko: "던지다",
        vi: "ném",
        th: "ขว้าง",
        my: "ပစ်သည်",
        km: "បោះ",
      },
      furigana: [
        {
          rb: "投げる",
          rt: "なげる",
        },
      ],
      kanjiInfo: [
        {
          char: "投",
          on: ["トウ"],
          kun: ["な.げる", "-な.げ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 416,
      kanji: "受ける",
      reading: "うける",
      meanings: {
        ja: "受ける",
        en: "to receive",
        zh: "接受",
        tw: "接受",
        ko: "받다",
        vi: "nhận",
        th: "รับ",
        my: "လက်ခံသည်",
        km: "ទទួល",
      },
      furigana: [
        {
          rb: "受ける",
          rt: "うける",
        },
      ],
      kanjiInfo: [
        {
          char: "受",
          on: ["ジュ"],
          kun: ["う.ける", "-う.け", "う.かる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 417,
      kanji: "間違える",
      reading: "まちがえる",
      meanings: {
        ja: "間違える",
        en: "to make a mistake (in)",
        zh: "弄错",
        tw: "弄錯",
        ko: "틀리다",
        vi: "nhầm lẫn",
        th: "ทำผิด",
        my: "မှားသည်",
        km: "ខុស",
      },
      furigana: [
        {
          rb: "間違える",
          rt: "まちがえる",
        },
      ],
      kanjiInfo: [
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "違",
          on: ["イ"],
          kun: [
            "ちが.う",
            "ちが.い",
            "ちが.える",
            "-ちが.える",
            "たが.う",
            "たが.える",
          ],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 418,
      kanji: "足りる",
      reading: "たりる",
      meanings: {
        ja: "足りる",
        en: "to be sufficient",
        zh: "足够",
        tw: "足夠",
        ko: "충분하다",
        vi: "đủ",
        th: "เพียงพอ",
        my: "လုံလောက်သည်",
        km: "គ្រប់គ្រាន់",
      },
      furigana: [
        {
          rb: "足りる",
          rt: "たりる",
        },
      ],
      kanjiInfo: [
        {
          char: "足",
          on: ["ソク"],
          kun: ["あし", "た.りる", "た.る", "た.す"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 419,
      kanji: "行う",
      reading: "おこなう",
      meanings: {
        ja: "行う",
        en: "to perform",
        zh: "进行",
        tw: "進行",
        ko: "행하다",
        vi: "thực hiện",
        th: "ดำเนินการ",
        my: "ဆောင်ရွက်သည်",
        km: "អនុវត្ត",
      },
      furigana: [
        {
          rb: "行う",
          rt: "おこなう",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 420,
      kanji: "無くなる",
      reading: "なくなる",
      meanings: {
        ja: "無くなる",
        en: "to be lost (e.g. luggage)",
        zh: "丢失",
        tw: "遺失",
        ko: "없어지다",
        vi: "bị mất",
        th: "หายไป",
        my: "ပျောက်သွားသည်",
        km: "បាត់",
      },
      furigana: [
        {
          rb: "無くなる",
          rt: "なくなる",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 421,
      kanji: "痩せる",
      reading: "やせる",
      meanings: {
        ja: "痩せる",
        en: "to become thin",
        zh: "瘦",
        tw: "瘦",
        ko: "마르다",
        vi: "gầy đi",
        th: "ผอมลง",
        my: "ပိန်သည်",
        km: "ស្គម",
      },
      furigana: [
        {
          rb: "痩せる",
          rt: "やせる",
        },
      ],
      kanjiInfo: [
        {
          char: "痩",
          on: ["ソウ", "チュウ", "シュウ", "シュ"],
          kun: ["や.せる"],
          strokes: 12,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 422,
      kanji: "決める",
      reading: "きめる",
      meanings: {
        ja: "決める",
        en: "to decide",
        zh: "决定",
        tw: "決定",
        ko: "결정하다",
        vi: "quyết định",
        th: "ตัดสินใจ",
        my: "ဆုံးဖြတ်သည်",
        km: "សម្រេចចិត្ត",
      },
      furigana: [
        {
          rb: "決める",
          rt: "きめる",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 423,
      kanji: "調べる",
      reading: "しらべる",
      meanings: {
        ja: "調べる",
        en: "to examine",
        zh: "调查",
        tw: "調查",
        ko: "조사하다",
        vi: "điều tra",
        th: "ตรวจสอบ",
        my: "စစ်ဆေးသည်",
        km: "ស៊ើបអង្កេត",
      },
      furigana: [
        {
          rb: "調べる",
          rt: "しらべる",
        },
      ],
      kanjiInfo: [
        {
          char: "調",
          on: ["チョウ"],
          kun: ["しら.べる", "しら.べ", "ととの.う", "ととの.える"],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 424,
      kanji: "光る",
      reading: "ひかる",
      meanings: {
        ja: "光る",
        en: "to shine",
        zh: "发光",
        tw: "發光",
        ko: "빛나다",
        vi: "chiếu sáng",
        th: "ส่องแสง",
        my: "လင်းလက်သည်",
        km: "ភ្លឺចែងចាំង",
      },
      furigana: [
        {
          rb: "光る",
          rt: "ひかる",
        },
      ],
      kanjiInfo: [
        {
          char: "光",
          on: ["コウ"],
          kun: ["ひか.る", "ひかり"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 425,
      kanji: "捨てる",
      reading: "すてる",
      meanings: {
        ja: "捨てる",
        en: "to throw away",
        zh: "扔掉",
        tw: "丟掉",
        ko: "버리다",
        vi: "vứt bỏ",
        th: "ทิ้ง",
        my: "စွန့်ပစ်သည်",
        km: "បោះចោល",
      },
      furigana: [
        {
          rb: "捨てる",
          rt: "すてる",
        },
      ],
      kanjiInfo: [
        {
          char: "捨",
          on: ["シャ"],
          kun: ["す.てる"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 426,
      kanji: "知らせる",
      reading: "しらせる",
      meanings: {
        ja: "知らせる",
        en: "to notify",
        zh: "通知",
        tw: "通知",
        ko: "알리다",
        vi: "thông báo",
        th: "แจ้งให้ทราบ",
        my: "အသိပေးသည်",
        km: "ជូនដំណឹង",
      },
      furigana: [
        {
          rb: "知らせる",
          rt: "しらせる",
        },
      ],
      kanjiInfo: [
        {
          char: "知",
          on: ["チ"],
          kun: ["し.る", "し.らせる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 427,
      kanji: "始める",
      reading: "はじめる",
      meanings: {
        ja: "始める",
        en: "to start",
        zh: "开始",
        tw: "開始",
        ko: "시작하다",
        vi: "bắt đầu",
        th: "เริ่ม",
        my: "စတင်သည်",
        km: "ចាប់ផ្ដើម",
      },
      furigana: [
        {
          rb: "始める",
          rt: "はじめる",
        },
      ],
      kanjiInfo: [
        {
          char: "始",
          on: ["シ"],
          kun: ["はじ.める", "-はじ.める", "はじ.まる"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
