export const n4part13 = {
  Lesson13: [
    {
      id: 478,
      kanji: "慣れる",
      reading: "なれる",
      meanings: {
        ja: "慣れる",
        en: "to get used to",
        zh: "习惯",
        tw: "習慣",
        ko: "익숙해지다",
        vi: "quen với",
        th: "คุ้นเคย",
        my: "အကျင့်ရသည်",
        km: "ស៊ាំ",
      },
      furigana: [
        {
          rb: "慣れる",
          rt: "なれる",
        },
      ],
      kanjiInfo: [
        {
          char: "慣",
          on: ["カン"],
          kun: ["な.れる", "な.らす"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 479,
      kanji: "手伝う",
      reading: "てつだう",
      meanings: {
        ja: "手伝う",
        en: "to help",
        zh: "帮忙",
        tw: "幫忙",
        ko: "돕다",
        vi: "giúp đỡ",
        th: "ช่วยเหลือ",
        my: "ကူညီသည်",
        km: "ជួយ",
      },
      furigana: [
        {
          rb: "手伝う",
          rt: "てつだう",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "伝",
          on: ["デン", "テン"],
          kun: [
            "つた.わる",
            "つた.える",
            "つた.う",
            "つだ.う",
            "-づた.い",
            "つて",
          ],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 480,
      kanji: "笑う",
      reading: "わらう",
      meanings: {
        ja: "笑う",
        en: "to laugh",
        zh: "笑",
        tw: "笑",
        ko: "웃다",
        vi: "cười",
        th: "หัวเราะ",
        my: "ရယ်သည်",
        km: "សើច",
      },
      furigana: [
        {
          rb: "笑う",
          rt: "わらう",
        },
      ],
      kanjiInfo: [
        {
          char: "笑",
          on: ["ショウ"],
          kun: ["わら.う", "え.む"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 481,
      kanji: "運ぶ",
      reading: "はこぶ",
      meanings: {
        ja: "運ぶ",
        en: "to carry",
        zh: "搬运",
        tw: "搬運",
        ko: "나르다",
        vi: "mang, vận chuyển",
        th: "ขนย้าย",
        my: "သယ်ဆောင်သည်",
        km: "ដឹកជញ្ជូន",
      },
      furigana: [
        {
          rb: "運ぶ",
          rt: "はこぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 482,
      kanji: "下る",
      reading: "さがる",
      meanings: {
        ja: "下る",
        en: "to come down",
        zh: "下降",
        tw: "下降",
        ko: "내려가다",
        vi: "đi xuống",
        th: "ลดลง",
        my: "ဆင်းသည်",
        km: "ចុះ",
      },
      furigana: [
        {
          rb: "下る",
          rt: "さがる",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 483,
      kanji: "褒める",
      reading: "ほめる",
      meanings: {
        ja: "褒める",
        en: "to praise",
        zh: "称赞",
        tw: "稱讚",
        ko: "칭찬하다",
        vi: "khen ngợi",
        th: "ชมเชย",
        my: "ချီးမွမ်းသည်",
        km: "សរសើរ",
      },
      furigana: [
        {
          rb: "褒める",
          rt: "ほめる",
        },
      ],
      kanjiInfo: [
        {
          char: "褒",
          on: ["ホウ"],
          kun: ["ほ.める"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 484,
      kanji: "空く",
      reading: "すく",
      meanings: {
        ja: "空く",
        en: "to become less crowded",
        zh: "变空",
        tw: "變空",
        ko: "비다",
        vi: "vắng",
        th: "ว่างลง",
        my: "လွတ်သည်",
        km: "ទំនេរ",
      },
      furigana: [
        {
          rb: "空く",
          rt: "すく",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 485,
      kanji: "合う",
      reading: "あう",
      meanings: {
        ja: "合う",
        en: "to come together",
        zh: "合适",
        tw: "合適",
        ko: "맞다",
        vi: "phù hợp",
        th: "เข้ากัน",
        my: "ကိုက်ညီသည်",
        km: "សម",
      },
      furigana: [
        {
          rb: "合う",
          rt: "あう",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 486,
      kanji: "遅れる",
      reading: "おくれる",
      meanings: {
        ja: "遅れる",
        en: "to be late",
        zh: "迟到",
        tw: "遲到",
        ko: "늦다",
        vi: "trễ",
        th: "สาย",
        my: "နောက်ကျသည်",
        km: "យឺត",
      },
      furigana: [
        {
          rb: "遅れる",
          rt: "おくれる",
        },
      ],
      kanjiInfo: [
        {
          char: "遅",
          on: ["チ"],
          kun: ["おく.れる", "おく.らす", "おそ.い"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 487,
      kanji: "見つかる",
      reading: "みつかる",
      meanings: {
        ja: "見つかる",
        en: "to be found",
        zh: "被找到",
        tw: "被找到",
        ko: "발견되다",
        vi: "được tìm thấy",
        th: "ถูกพบ",
        my: "တွေ့ရသည်",
        km: "រកឃើញ",
      },
      furigana: [
        {
          rb: "見つかる",
          rt: "みつかる",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 488,
      kanji: "召し上がる",
      reading: "めしあがる",
      meanings: {
        ja: "召し上がる",
        en: "to eat (honorific)",
        zh: "吃（尊敬）",
        tw: "吃（尊敬）",
        ko: "드시다",
        vi: "ăn (kính ngữ)",
        th: "รับประทาน (ยกย่อง)",
        my: "စားသည် (ဂုဏ်ထူး)",
        km: "បរិភោគ (កិត្តិយស)",
      },
      furigana: [
        {
          rb: "召し上がる",
          rt: "めしあがる",
        },
      ],
      kanjiInfo: [
        {
          char: "召",
          on: ["ショウ"],
          kun: ["め.す"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 489,
      kanji: "太る",
      reading: "ふとる",
      meanings: {
        ja: "太る",
        en: "to put on weight",
        zh: "发胖",
        tw: "發胖",
        ko: "살이 찌다",
        vi: "tăng cân",
        th: "อ้วนขึ้น",
        my: "၀ လုံးသည်",
        km: "ធាត់",
      },
      furigana: [
        {
          rb: "太る",
          rt: "ふとる",
        },
      ],
      kanjiInfo: [
        {
          char: "太",
          on: ["タイ", "タ"],
          kun: ["ふと.い", "ふと.る"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 490,
      kanji: "直る",
      reading: "なおる",
      meanings: {
        ja: "直る",
        en: "to get mended",
        zh: "修好",
        tw: "修好",
        ko: "고쳐지다",
        vi: "được sửa",
        th: "ถูกซ่อม",
        my: "ပြန်သိမ်းသည်",
        km: "ជួសជុលរួច",
      },
      furigana: [
        {
          rb: "直る",
          rt: "なおる",
        },
      ],
      kanjiInfo: [
        {
          char: "直",
          on: ["チョク", "ジキ", "ジカ"],
          kun: [
            "ただ.ちに",
            "なお.す",
            "-なお.す",
            "なお.る",
            "なお.き",
            "す.ぐ",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 491,
      kanji: "集める",
      reading: "あつめる",
      meanings: {
        ja: "集める",
        en: "to collect",
        zh: "收集",
        tw: "收集",
        ko: "모으다",
        vi: "thu thập",
        th: "รวบรวม",
        my: "စုဆောင်းသည်",
        km: "ប្រមូល",
      },
      furigana: [
        {
          rb: "集める",
          rt: "あつめる",
        },
      ],
      kanjiInfo: [
        {
          char: "集",
          on: ["シュウ"],
          kun: ["あつ.まる", "あつ.める", "つど.う"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 492,
      kanji: "直す",
      reading: "なおす",
      meanings: {
        ja: "直す",
        en: "to repair",
        zh: "修理",
        tw: "修理",
        ko: "고치다",
        vi: "sửa chữa",
        th: "ซ่อม",
        my: "ပြင်သည်",
        km: "ជួសជុល",
      },
      furigana: [
        {
          rb: "直す",
          rt: "なおす",
        },
      ],
      kanjiInfo: [
        {
          char: "直",
          on: ["チョク", "ジキ", "ジカ"],
          kun: [
            "ただ.ちに",
            "なお.す",
            "-なお.す",
            "なお.る",
            "なお.き",
            "す.ぐ",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 493,
      kanji: "続く",
      reading: "つづく",
      meanings: {
        ja: "続く",
        en: "to continue",
        zh: "继续",
        tw: "繼續",
        ko: "계속되다",
        vi: "tiếp tục",
        th: "ต่อเนื่อง",
        my: "ဆက်လက်သည်",
        km: "បន្ត",
      },
      furigana: [
        {
          rb: "続く",
          rt: "つづく",
        },
      ],
      kanjiInfo: [
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 494,
      kanji: "払う",
      reading: "はらう",
      meanings: {
        ja: "払う",
        en: "to pay (money)",
        zh: "支付",
        tw: "支付",
        ko: "지불하다",
        vi: "trả tiền",
        th: "จ่ายเงิน",
        my: "ပေးဆောင်သည်",
        km: "បង់",
      },
      furigana: [
        {
          rb: "払う",
          rt: "はらう",
        },
      ],
      kanjiInfo: [
        {
          char: "払",
          on: ["フツ", "ヒツ", "ホツ"],
          kun: ["はら.う", "-はら.い", "-ばら.い"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 495,
      kanji: "焼ける",
      reading: "やける",
      meanings: {
        ja: "焼ける",
        en: "to burn",
        zh: "烧着",
        tw: "燒著",
        ko: "타다",
        vi: "bị cháy",
        th: "ไหม้",
        my: "လောင်ကျွမ်းသည်",
        km: "ឆេះ",
      },
      furigana: [
        {
          rb: "焼ける",
          rt: "やける",
        },
      ],
      kanjiInfo: [
        {
          char: "焼",
          on: ["ショウ"],
          kun: ["や.く", "や.き", "や.き-", "-や.き", "や.ける"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 496,
      kanji: "冷える",
      reading: "ひえる",
      meanings: {
        ja: "冷える",
        en: "to grow cold",
        zh: "变冷",
        tw: "變冷",
        ko: "식다",
        vi: "lạnh đi",
        th: "เย็นลง",
        my: "အေးလာသည်",
        km: "ត្រជាក់",
      },
      furigana: [
        {
          rb: "冷える",
          rt: "ひえる",
        },
      ],
      kanjiInfo: [
        {
          char: "冷",
          on: ["レイ"],
          kun: [
            "つめ.たい",
            "ひ.える",
            "ひ.や",
            "ひ.ややか",
            "ひ.やす",
            "ひ.やかす",
            "さ.める",
            "さ.ます",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 497,
      kanji: "点く",
      reading: "つく",
      meanings: {
        ja: "点く",
        en: "to be lit (lamp)",
        zh: "点亮",
        tw: "點亮",
        ko: "켜지다",
        vi: "sáng lên",
        th: "ติดไฟ",
        my: "မီးလင်းသည်",
        km: "ភ្លើងភ្លឺ",
      },
      furigana: [
        {
          rb: "点く",
          rt: "つく",
        },
      ],
      kanjiInfo: [
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 498,
      kanji: "続ける",
      reading: "つづける",
      meanings: {
        ja: "続ける",
        en: "to continue",
        zh: "继续",
        tw: "繼續",
        ko: "계속하다",
        vi: "tiếp tục",
        th: "ทำต่อไป",
        my: "ဆက်လက်လုပ်သည်",
        km: "បន្តធ្វើ",
      },
      furigana: [
        {
          rb: "続ける",
          rt: "つづける",
        },
      ],
      kanjiInfo: [
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 499,
      kanji: "落す",
      reading: "おとす",
      meanings: {
        ja: "落とす",
        en: "to drop",
        zh: "掉下",
        tw: "掉下",
        ko: "떨어뜨리다",
        vi: "làm rơi",
        th: "ทำตก",
        my: "ချသည်",
        km: "ទម្លាក់",
      },
      furigana: [
        {
          rb: "落す",
          rt: "おとす",
        },
      ],
      kanjiInfo: [
        {
          char: "落",
          on: ["ラク"],
          kun: ["お.ちる", "お.ち", "お.とす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 500,
      kanji: "割れる",
      reading: "われる",
      meanings: {
        ja: "割れる",
        en: "to break",
        zh: "破裂",
        tw: "破裂",
        ko: "깨지다",
        vi: "vỡ",
        th: "แตก",
        my: "ကွဲသည်",
        km: "បែក",
      },
      furigana: [
        {
          rb: "割れる",
          rt: "われる",
        },
      ],
      kanjiInfo: [
        {
          char: "割",
          on: ["カツ"],
          kun: ["わ.る", "わり", "わ.り", "わ.れる", "さ.く"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 501,
      kanji: "濡れる",
      reading: "ぬれる",
      meanings: {
        ja: "濡れる",
        en: "to get wet",
        zh: "弄湿",
        tw: "弄濕",
        ko: "젖다",
        vi: "ướt",
        th: "เปียก",
        my: "စိုသည်",
        km: "សើម",
      },
      furigana: [
        {
          rb: "濡れる",
          rt: "ぬれる",
        },
      ],
      kanjiInfo: [
        {
          char: "濡",
          on: ["ジュ", "ニュ"],
          kun: [
            "ぬれ.る",
            "ぬら.す",
            "ぬ.れる",
            "ぬ.らす",
            "うるお.い",
            "うるお.う",
            "うるお.す",
          ],
          strokes: 17,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 502,
      kanji: "倒れる",
      reading: "たおれる",
      meanings: {
        ja: "倒れる",
        en: "to fall over",
        zh: "倒下",
        tw: "倒下",
        ko: "넘어지다",
        vi: "ngã",
        th: "ล้มลง",
        my: "လဲသည်",
        km: "ដួល",
      },
      furigana: [
        {
          rb: "倒れる",
          rt: "たおれる",
        },
      ],
      kanjiInfo: [
        {
          char: "倒",
          on: ["トウ"],
          kun: [
            "たお.れる",
            "-だお.れ",
            "たお.す",
            "さかさま",
            "さかさ",
            "さかしま",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 503,
      kanji: "考える",
      reading: "かんがえる",
      meanings: {
        ja: "考える",
        en: "to think (about)",
        zh: "思考",
        tw: "思考",
        ko: "생각하다",
        vi: "suy nghĩ",
        th: "คิด",
        my: "ထင်မြင်သည်",
        km: "គិត",
      },
      furigana: [
        {
          rb: "考える",
          rt: "かんがえる",
        },
      ],
      kanjiInfo: [
        {
          char: "考",
          on: ["コウ"],
          kun: ["かんが.える", "かんが.え"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 504,
      kanji: "向かう",
      reading: "むかう",
      meanings: {
        ja: "向かう",
        en: "to face",
        zh: "面向",
        tw: "面向",
        ko: "향하다",
        vi: "hướng tới",
        th: "มุ่งหน้า",
        my: "သို့ရောက်သည်",
        km: "ទៅរក",
      },
      furigana: [
        {
          rb: "向かう",
          rt: "むかう",
        },
      ],
      kanjiInfo: [
        {
          char: "向",
          on: ["コウ"],
          kun: [
            "む.く",
            "む.い",
            "-む.き",
            "む.ける",
            "-む.け",
            "む.かう",
            "む.かい",
            "む.こう",
            "む.こう-",
            "むこ",
            "むか.い",
          ],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 505,
      kanji: "移る",
      reading: "うつる",
      meanings: {
        ja: "移る",
        en: "to move (house)",
        zh: "搬迁",
        tw: "搬遷",
        ko: "옮기다",
        vi: "chuyển nhà",
        th: "ย้าย",
        my: "ရွေ့ပြောင်းသည်",
        km: "ផ្លាស់ទី",
      },
      furigana: [
        {
          rb: "移る",
          rt: "うつる",
        },
      ],
      kanjiInfo: [
        {
          char: "移",
          on: ["イ"],
          kun: ["うつ.る", "うつ.す"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 506,
      kanji: "動く",
      reading: "うごく",
      meanings: {
        ja: "動く",
        en: "to move",
        zh: "移动",
        tw: "移動",
        ko: "움직이다",
        vi: "chuyển động",
        th: "เคลื่อนไหว",
        my: "လှုပ်ရှားသည်",
        km: "ផ្លាស់ទី",
      },
      furigana: [
        {
          rb: "動く",
          rt: "うごく",
        },
      ],
      kanjiInfo: [
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 507,
      kanji: "植える",
      reading: "うえる",
      meanings: {
        ja: "植える",
        en: "to plant",
        zh: "种植",
        tw: "種植",
        ko: "심다",
        vi: "trồng",
        th: "ปลูก",
        my: "စိုက်သည်",
        km: "ដាំដុះ",
      },
      furigana: [
        {
          rb: "植える",
          rt: "うえる",
        },
      ],
      kanjiInfo: [
        {
          char: "植",
          on: ["ショク"],
          kun: ["う.える", "う.わる"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 508,
      kanji: "汚れる",
      reading: "よごれる",
      meanings: {
        ja: "汚れる",
        en: "to get dirty",
        zh: "弄脏",
        tw: "弄髒",
        ko: "더러워지다",
        vi: "bị bẩn",
        th: "สกปรก",
        my: "ညစ်ပတ်သည်",
        km: "កខ្វក់",
      },
      furigana: [
        {
          rb: "汚れる",
          rt: "よごれる",
        },
      ],
      kanjiInfo: [
        {
          char: "汚",
          on: ["オ"],
          kun: [
            "けが.す",
            "けが.れる",
            "けが.らわしい",
            "よご.す",
            "よご.れる",
            "きたな.い",
          ],
          strokes: 6,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 509,
      kanji: "勝つ",
      reading: "かつ",
      meanings: {
        ja: "勝つ",
        en: "to win",
        zh: "赢",
        tw: "贏",
        ko: "이기다",
        vi: "thắng",
        th: "ชนะ",
        my: "အောင်မြင်သည်",
        km: "ឈ្នះ",
      },
      furigana: [
        {
          rb: "勝つ",
          rt: "かつ",
        },
      ],
      kanjiInfo: [
        {
          char: "勝",
          on: ["ショウ"],
          kun: ["か.つ", "-が.ち", "まさ.る", "すぐ.れる", "かつ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 510,
      kanji: "取り替える",
      reading: "とりかえる",
      meanings: {
        ja: "取り替える",
        en: "to exchange",
        zh: "更换",
        tw: "更換",
        ko: "바꾸다",
        vi: "đổi",
        th: "แลกเปลี่ยน",
        my: "လဲသည်",
        km: "ផ្លាស់ប្តូរ",
      },
      furigana: [
        {
          rb: "取り替える",
          rt: "とりかえる",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "替",
          on: ["タイ"],
          kun: ["か.える", "か.え-", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 511,
      kanji: "急ぐ",
      reading: "いそぐ",
      meanings: {
        ja: "急ぐ",
        en: "to hurry",
        zh: "赶快",
        tw: "趕快",
        ko: "서두르다",
        vi: "vội vàng",
        th: "รีบ",
        my: "အလျင်အမြန်",
        km: "ប្រញាប់",
      },
      furigana: [
        {
          rb: "急ぐ",
          rt: "いそぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "急",
          on: ["キュウ"],
          kun: ["いそ.ぐ", "いそ.ぎ", "せ.く"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 512,
      kanji: "参る",
      reading: "まいる",
      meanings: {
        ja: "参る",
        en: "to go",
        zh: "去 (谦让)",
        tw: "去 (謙讓)",
        ko: "가다 (겸양)",
        vi: "đi (khiêm nhường)",
        th: "ไป (ถ่อมตัว)",
        my: "သွားသည် (လျှော့စား)",
        km: "ទៅ (ថាខ្ជាប់ខ្ជួន)",
      },
      furigana: [
        {
          rb: "参る",
          rt: "まいる",
        },
      ],
      kanjiInfo: [
        {
          char: "参",
          on: ["サン", "シン"],
          kun: ["まい.る", "まい-", "まじわる", "みつ"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 513,
      kanji: "間に合う",
      reading: "まにあう",
      meanings: {
        ja: "間に合う",
        en: "to be in time (for)",
        zh: "赶上",
        tw: "趕上",
        ko: "제시간에 맞다",
        vi: "kịp",
        th: "ทันเวลา",
        my: "အချိန်မီ",
        km: "ទាន់ពេល",
      },
      furigana: [
        {
          rb: "間に合う",
          rt: "まにあう",
        },
      ],
      kanjiInfo: [
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 514,
      kanji: "戻る",
      reading: "もどる",
      meanings: {
        ja: "戻る",
        en: "to turn back",
        zh: "返回",
        tw: "返回",
        ko: "돌아가다",
        vi: "quay lại",
        th: "กลับ",
        my: "ပြန်သွားသည်",
        km: "ត្រឡប់",
      },
      furigana: [
        {
          rb: "戻る",
          rt: "もどる",
        },
      ],
      kanjiInfo: [
        {
          char: "戻",
          on: ["レイ"],
          kun: ["もど.す", "もど.る"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 515,
      kanji: "込む",
      reading: "こむ",
      meanings: {
        ja: "込む",
        en: "to be crowded",
        zh: "拥挤",
        tw: "擁擠",
        ko: "붐비다",
        vi: "đông đúc",
        th: "แออัด",
        my: "စည်ကားသည်",
        km: "តក់ស្ទះ",
      },
      furigana: [
        {
          rb: "込む",
          rt: "こむ",
        },
      ],
      kanjiInfo: [
        {
          char: "込",
          on: [],
          kun: ["-こ.む", "こ.む", "こ.み", "-こ.み", "こ.める"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 516,
      kanji: "訪ねる",
      reading: "たずねる",
      meanings: {
        ja: "訪ねる",
        en: "to visit",
        zh: "访问",
        tw: "訪問",
        ko: "방문하다",
        vi: "thăm",
        th: "เยี่ยม",
        my: "အလည်သွားသည်",
        km: "ទស្សនា",
      },
      furigana: [
        {
          rb: "訪ねる",
          rt: "たずねる",
        },
      ],
      kanjiInfo: [
        {
          char: "訪",
          on: ["ホウ"],
          kun: ["おとず.れる", "たず.ねる", "と.う"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 517,
      kanji: "下げる",
      reading: "さげる",
      meanings: {
        ja: "下げる",
        en: "to hang",
        zh: "降低",
        tw: "降低",
        ko: "내리다",
        vi: "hạ xuống",
        th: "ลดลง",
        my: "ချသည်",
        km: "បន្ថយ",
      },
      furigana: [
        {
          rb: "下げる",
          rt: "さげる",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 518,
      kanji: "乗り換える",
      reading: "のりかえる",
      meanings: {
        ja: "乗り換える",
        en: "to transfer (trains)",
        zh: "换乘",
        tw: "換乘",
        ko: "갈아타다",
        vi: "chuyển tàu",
        th: "เปลี่ยนรถไฟ",
        my: "တပ်စီးပြောင်းသည်",
        km: "ផ្លាស់រថភ្លើង",
      },
      furigana: [
        {
          rb: "乗り換える",
          rt: "のりかえる",
        },
      ],
      kanjiInfo: [
        {
          char: "乗",
          on: ["ジョウ", "ショウ"],
          kun: ["の.る", "-の.り", "の.せる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "換",
          on: ["カン"],
          kun: ["か.える", "-か.える", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 519,
      kanji: "別れる",
      reading: "わかれる",
      meanings: {
        ja: "別れる",
        en: "to part (people)",
        zh: "分手",
        tw: "分手",
        ko: "헤어지다",
        vi: "chia tay",
        th: "แยกทาง",
        my: "ခွာသည်",
        km: "លែង",
      },
      furigana: [
        {
          rb: "別れる",
          rt: "わかれる",
        },
      ],
      kanjiInfo: [
        {
          char: "別",
          on: ["ベツ"],
          kun: ["わか.れる", "わ.ける"],
          strokes: 7,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 520,
      kanji: "眠る",
      reading: "ねむる",
      meanings: {
        ja: "眠る",
        en: "to sleep",
        zh: "睡觉",
        tw: "睡覺",
        ko: "잠들다",
        vi: "ngủ",
        th: "นอนหลับ",
        my: "အိပ်သည်",
        km: "ដេក",
      },
      furigana: [
        {
          rb: "眠る",
          rt: "ねむる",
        },
      ],
      kanjiInfo: [
        {
          char: "眠",
          on: ["ミン"],
          kun: ["ねむ.る", "ねむ.い"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 521,
      kanji: "上がる",
      reading: "あがる",
      meanings: {
        ja: "上がる",
        en: "to rise",
        zh: "上升",
        tw: "上升",
        ko: "오르다",
        vi: "tăng lên",
        th: "สูงขึ้น",
        my: "တက်သည်",
        km: "ឡើង",
      },
      furigana: [
        {
          rb: "上がる",
          rt: "あがる",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 522,
      kanji: "集まる",
      reading: "あつまる",
      meanings: {
        ja: "集まる",
        en: "to gather",
        zh: "聚集",
        tw: "聚集",
        ko: "모이다",
        vi: "tụ tập",
        th: "รวมตัว",
        my: "စုဝေးသည်",
        km: "ប្រមូលផ្តុំ",
      },
      furigana: [
        {
          rb: "集まる",
          rt: "あつまる",
        },
      ],
      kanjiInfo: [
        {
          char: "集",
          on: ["シュウ"],
          kun: ["あつ.まる", "あつ.める", "つど.う"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
