export const n1part33 = {
  Lesson33: [
    {
      id: 1601,
      kanji: "婿",
      reading: "むこ",
      meanings: {
        ja: "婿",
        en: "husband; son-in-law",
        zh: "女婿",
        tw: "女婿",
        ko: "사위",
        vi: "con rể",
        th: "ลูกเขย",
        my: "မျိုးသားသားမျိုး",
        km: "កូនប្រសា",
      },
      furigana: [
        {
          rb: "婿",
          rt: "むこ",
        },
      ],
      kanjiInfo: [
        {
          char: "婿",
          on: ["セイ"],
          kun: ["むこ"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1602,
      kanji: "無言",
      reading: "むごん",
      meanings: {
        ja: "無言",
        en: "silence (no speaking)",
        zh: "无言",
        tw: "無言",
        ko: "무언",
        vi: "im lặng",
        th: "นิ่งเงียบ",
        my: "အသံမထွက်ဘဲတိုတောင်း",
        km: "ស្ងៀមស្ងាត់",
      },
      furigana: [
        {
          rb: "無言",
          rt: "むごん",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1603,
      kanji: "結び",
      reading: "むすび",
      meanings: {
        ja: "結び",
        en: "ending; knot",
        zh: "结尾；结",
        tw: "結尾；結",
        ko: "매듭; 맺음",
        vi: "kết; phần kết",
        th: "ตอนจบ; ปม",
        my: "ဆက်သွယ်ခြင်း/အဆုံး",
        km: "ចុងបញ្ចប់; កញ្ចក់",
      },
      furigana: [
        {
          rb: "結び",
          rt: "むすび",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1604,
      kanji: "結び付き",
      reading: "むすびつき",
      meanings: {
        ja: "結び付き",
        en: "connection; relation",
        zh: "联系",
        tw: "連結；關聯",
        ko: "연결; 결부",
        vi: "liên kết",
        th: "ความเชื่อมโยง",
        my: "ချိတ်ဆက်မှု",
        km: "ការភ្ជាប់",
      },
      furigana: [
        {
          rb: "結び付き",
          rt: "むすびつき",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1605,
      kanji: "無線",
      reading: "むせん",
      meanings: {
        ja: "無線",
        en: "radio; wireless",
        zh: "无线电",
        tw: "無線",
        ko: "무선",
        vi: "vô tuyến",
        th: "วิทยุไร้สาย",
        my: "ကြိုးမဲ့",
        km: "គ្មានខ្សែ",
      },
      furigana: [
        {
          rb: "無線",
          rt: "むせん",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "線",
          on: ["セン"],
          kun: ["すじ"],
          strokes: 15,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1606,
      kanji: "無駄遣い",
      reading: "むだづかい",
      meanings: {
        ja: "無駄遣い",
        en: "waste (money/time)",
        zh: "浪费",
        tw: "浪費",
        ko: "낭비",
        vi: "lãng phí",
        th: "ฟุ่มเฟือย",
        my: "ဖျက်သိမ်းသုံး",
        km: "ចំណាយខាត",
      },
      furigana: [
        {
          rb: "無駄遣い",
          rt: "むだづかい",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "駄",
          on: ["ダ", "タ"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "遣",
          on: ["ケン"],
          kun: ["つか.う", "-つか.い", "-づか.い", "つか.わす", "や.る"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1607,
      kanji: "無断",
      reading: "むだん",
      meanings: {
        ja: "無断",
        en: "without permission",
        zh: "擅自",
        tw: "擅自",
        ko: "무단",
        vi: "tự ý",
        th: "โดยพลการ",
        my: "ခွင့်မယူဘဲ",
        km: "ដោយគ្មានអនុញ្ញាត",
      },
      furigana: [
        {
          rb: "無断",
          rt: "むだん",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1608,
      kanji: "無知",
      reading: "むち",
      meanings: {
        ja: "無知",
        en: "ignorance",
        zh: "无知",
        tw: "無知",
        ko: "무지",
        vi: "ngu dốt",
        th: "ไม่รู้",
        my: "မဲမဲလွန်း",
        km: "អគ្គិភ័យ/អព្យាក្រឹត (មិនដឹង)",
      },
      furigana: [
        {
          rb: "無知",
          rt: "むち",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "知",
          on: ["チ"],
          kun: ["し.る", "し.らせる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1609,
      kanji: "無念",
      reading: "むねん",
      meanings: {
        ja: "無念",
        en: "regret; mortification",
        zh: "懊恼；遗憾",
        tw: "懊惱；遺憾",
        ko: "분함; 유감",
        vi: "tiếc nuối",
        th: "เสียใจเสียดาย",
        my: "စိတ်ညစ်တယ်",
        km: "សោកស្តាយ",
      },
      furigana: [
        {
          rb: "無念",
          rt: "むねん",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "念",
          on: ["ネン"],
          kun: [],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1610,
      kanji: "無能",
      reading: "むのう",
      meanings: {
        ja: "無能",
        en: "incompetence",
        zh: "无能",
        tw: "無能",
        ko: "무능",
        vi: "bất tài",
        th: "ไร้ความสามารถ",
        my: "အရည်အချင်းမရှိ",
        km: "អសមត្ថភាព",
      },
      furigana: [
        {
          rb: "無能",
          rt: "むのう",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1611,
      kanji: "斑",
      reading: "むら",
      meanings: {
        ja: "斑",
        en: "mottling; unevenness",
        zh: "斑驳；不均匀",
        tw: "斑駁；不均勻",
        ko: "얼룩; 들쭉날쭉",
        vi: "loang lổ; không đều",
        th: "เป็นปื้น; ไม่สม่ำเสมอ",
        my: "အပြားအဆာ",
        km: "មិនស្មើ",
      },
      furigana: [
        {
          rb: "斑",
          rt: "むら",
        },
      ],
      kanjiInfo: [
        {
          char: "斑",
          on: ["ハン"],
          kun: ["ふ", "まだら"],
          strokes: 12,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1612,
      kanji: "名産",
      reading: "めいさん",
      meanings: {
        ja: "名産",
        en: "local specialty",
        zh: "名产",
        tw: "名產",
        ko: "명산품",
        vi: "đặc sản",
        th: "ของขึ้นชื่อ",
        my: "နာမည်ကြီးထွက်ပစ္စည်း",
        km: "ផលិតផលល្បី",
      },
      furigana: [
        {
          rb: "名産",
          rt: "めいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1613,
      kanji: "名称",
      reading: "めいしょう",
      meanings: {
        ja: "名称",
        en: "name; designation",
        zh: "名称",
        tw: "名稱",
        ko: "명칭",
        vi: "tên gọi",
        th: "ชื่อเรียก",
        my: "အမည်",
        km: "ឈ្មោះ",
      },
      furigana: [
        {
          rb: "名称",
          rt: "めいしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "称",
          on: ["ショウ"],
          kun: [
            "たた.える",
            "とな.える",
            "あ.げる",
            "かな.う",
            "はか.り",
            "はか.る",
            "ほめ.る",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1614,
      kanji: "命中",
      reading: "めいちゅう",
      meanings: {
        ja: "命中",
        en: "direct hit",
        zh: "命中",
        tw: "命中",
        ko: "명중",
        vi: "trúng đích",
        th: "โดนเป้า",
        my: "ပစ်မှတ်တောက်တယ်",
        km: "វាយត្រូវគោលដៅ",
      },
      furigana: [
        {
          rb: "命中",
          rt: "めいちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1615,
      kanji: "名簿",
      reading: "めいぼ",
      meanings: {
        ja: "名簿",
        en: "register; roster",
        zh: "名册",
        tw: "名冊",
        ko: "명부",
        vi: "danh bạ",
        th: "บัญชีรายชื่อ",
        my: "အမည်စာရင်း",
        km: "បញ្ជីឈ្មោះ",
      },
      furigana: [
        {
          rb: "名簿",
          rt: "めいぼ",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "簿",
          on: ["ボ"],
          kun: [],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1616,
      kanji: "名誉",
      reading: "めいよ",
      meanings: {
        ja: "名誉",
        en: "honor",
        zh: "名誉",
        tw: "名譽",
        ko: "명예",
        vi: "vinh dự",
        th: "เกียรติยศ",
        my: "ဂုဏ်ရည်",
        km: "កិត្តិយស",
      },
      furigana: [
        {
          rb: "名誉",
          rt: "めいよ",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "誉",
          on: ["ヨ"],
          kun: ["ほま.れ", "ほ.める"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1617,
      kanji: "メーカー",
      reading: "メーカー",
      meanings: {
        ja: "メーカー",
        en: "manufacturer",
        zh: "制造商",
        tw: "製造商",
        ko: "제조사",
        vi: "nhà sản xuất",
        th: "ผู้ผลิต",
        my: "ထုတ်လုပ်သူ",
        km: "ក្រុមហ៊ុនផលិត",
      },
      furigana: [
        {
          rb: "メーカー",
          rt: "メーカー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1618,
      kanji: "目方",
      reading: "めかた",
      meanings: {
        ja: "目方",
        en: "weight",
        zh: "重量",
        tw: "重量",
        ko: "무게",
        vi: "trọng lượng",
        th: "น้ำหนัก",
        my: "အလေးချိန်",
        km: "ទម្ងន់",
      },
      furigana: [
        {
          rb: "目方",
          rt: "めかた",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1619,
      kanji: "恵み",
      reading: "めぐみ",
      meanings: {
        ja: "恵み",
        en: "blessing; grace",
        zh: "恩惠",
        tw: "恩惠",
        ko: "은혜",
        vi: "ân huệ",
        th: "พร/ความเมตตา",
        my: "ကျေးဇူး",
        km: "ពរ",
      },
      furigana: [
        {
          rb: "恵み",
          rt: "めぐみ",
        },
      ],
      kanjiInfo: [
        {
          char: "恵",
          on: ["ケイ", "エ"],
          kun: ["めぐ.む", "めぐ.み"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1620,
      kanji: "雌",
      reading: "めす",
      meanings: {
        ja: "雌",
        en: "female (animal)",
        zh: "雌性（动物）",
        tw: "雌（動物）",
        ko: "암컷",
        vi: "con cái (động vật)",
        th: "เพศเมีย (สัตว์)",
        my: "မ (တိရစ္ဆာန်)",
        km: "សត្វព្រាយមា",
      },
      furigana: [
        {
          rb: "雌",
          rt: "めす",
        },
      ],
      kanjiInfo: [
        {
          char: "雌",
          on: ["シ"],
          kun: ["め-", "めす", "めん"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1621,
      kanji: "目付き",
      reading: "めつき",
      meanings: {
        ja: "目付き",
        en: "look (in the eyes)",
        zh: "眼神",
        tw: "眼神",
        ko: "눈빛",
        vi: "ánh mắt",
        th: "แววตา",
        my: "မျက်လုံးအလှေ့",
        km: "ទឹកមុខភ្នែក",
      },
      furigana: [
        {
          rb: "目付き",
          rt: "めつき",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1622,
      kanji: "滅亡",
      reading: "めつぼう",
      meanings: {
        ja: "滅亡",
        en: "ruin; downfall",
        zh: "灭亡",
        tw: "滅亡",
        ko: "멸망",
        vi: "diệt vong",
        th: "ล่มสลาย",
        my: "ပျက်စီးမှု",
        km: "បរាជ័យ/មរណភាព",
      },
      furigana: [
        {
          rb: "滅亡",
          rt: "めつぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "滅",
          on: ["メツ"],
          kun: ["ほろ.びる", "ほろ.ぶ", "ほろ.ぼす"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "亡",
          on: ["ボウ", "モウ"],
          kun: ["な.い", "な.き-", "ほろ.びる", "ほろ.ぶ", "ほろ.ぼす"],
          strokes: 3,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1623,
      kanji: "メディア",
      reading: "メディア",
      meanings: {
        ja: "メディア",
        en: "media",
        zh: "媒体",
        tw: "媒體",
        ko: "미디어",
        vi: "truyền thông",
        th: "สื่อ",
        my: "မီဒီယာ",
        km: "មេឌៀ",
      },
      furigana: [
        {
          rb: "メディア",
          rt: "メディア",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1624,
      kanji: "目途",
      reading: "めど",
      meanings: {
        ja: "目途",
        en: "aim; prospect",
        zh: "目标；眉目",
        tw: "目標；眉目",
        ko: "목도(목표)",
        vi: "mục tiêu; triển vọng",
        th: "เป้าหมาย/เค้าโครง",
        my: "ပန်းတိုင်",
        km: "គោលដៅ",
      },
      furigana: [
        {
          rb: "目途",
          rt: "めど",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "途",
          on: ["ト"],
          kun: ["みち"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1625,
      kanji: "目盛",
      reading: "めもり",
      meanings: {
        ja: "目盛",
        en: "scale; graduation",
        zh: "刻度",
        tw: "刻度",
        ko: "눈금",
        vi: "vạch chia",
        th: "สเกล",
        my: "မျက်နှာပြင်အနှုန်း",
        km: "សញ្ញាចំណាត់ថ្នាក់",
      },
      furigana: [
        {
          rb: "目盛",
          rt: "めもり",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "盛",
          on: ["セイ", "ジョウ"],
          kun: ["も.る", "さか.る", "さか.ん"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1626,
      kanji: "メロディー",
      reading: "メロディー",
      meanings: {
        ja: "メロディー",
        en: "melody",
        zh: "旋律",
        tw: "旋律",
        ko: "멜로디",
        vi: "giai điệu",
        th: "ทำนอง",
        my: "သီချင်းတေးသံ",
        km: "មេឡូឌី",
      },
      furigana: [
        {
          rb: "メロディー",
          rt: "メロディー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1627,
      kanji: "面会",
      reading: "めんかい",
      meanings: {
        ja: "面会",
        en: "meeting; interview",
        zh: "会见",
        tw: "會見",
        ko: "면회",
        vi: "gặp mặt",
        th: "พบหน้า",
        my: "တွေ့မြင်မှု",
        km: "ជួបសម្ភាសន៍",
      },
      furigana: [
        {
          rb: "面会",
          rt: "めんかい",
        },
      ],
      kanjiInfo: [
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1628,
      kanji: "免除",
      reading: "めんじょ",
      meanings: {
        ja: "免除",
        en: "exemption",
        zh: "免除",
        tw: "免除",
        ko: "면제",
        vi: "miễn trừ",
        th: "ยกเว้น",
        my: "လွှတ်",
        km: "លើកលែង",
      },
      furigana: [
        {
          rb: "免除",
          rt: "めんじょ",
        },
      ],
      kanjiInfo: [
        {
          char: "免",
          on: ["メン"],
          kun: ["まぬか.れる", "まぬが.れる"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "除",
          on: ["ジョ", "ジ"],
          kun: ["のぞ.く", "-よ.け"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1629,
      kanji: "面目",
      reading: "めんぼく",
      meanings: {
        ja: "面目",
        en: "face; honor",
        zh: "面目",
        tw: "面目",
        ko: "면목",
        vi: "thể diện",
        th: "หน้าใหญ่ใจโต/ศักดิ์ศรี",
        my: "မျက်နှာမူ",
        km: "មុខមាត់",
      },
      furigana: [
        {
          rb: "面目",
          rt: "めんぼく",
        },
      ],
      kanjiInfo: [
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1630,
      kanji: "面目",
      reading: "めんもく",
      meanings: {
        ja: "面目",
        en: "face; appearance",
        zh: "体面",
        tw: "體面",
        ko: "면목",
        vi: "thể diện",
        th: "ศักดิ์ศรี",
        my: "ဂုဏ်သိက္ခာ",
        km: "កិត្តិយស",
      },
      furigana: [
        {
          rb: "面目",
          rt: "めんもく",
        },
      ],
      kanjiInfo: [
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1631,
      kanji: "申込",
      reading: "もうしこみ",
      meanings: {
        ja: "申込",
        en: "application",
        zh: "申请",
        tw: "申請",
        ko: "신청",
        vi: "đăng ký",
        th: "สมัคร",
        my: "လျှောက်လွှာ",
        km: "ពាក្យស្នើសុំ",
      },
      furigana: [
        {
          rb: "申込",
          rt: "もうしこみ",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "込",
          on: [],
          kun: ["-こ.む", "こ.む", "こ.み", "-こ.み", "こ.める"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1632,
      kanji: "申出",
      reading: "もうしで",
      meanings: {
        ja: "申出",
        en: "proposal; request",
        zh: "提出；申请",
        tw: "提出；申請",
        ko: "신고; 제의",
        vi: "đề xuất",
        th: "ยื่นเสนอ",
        my: "တင်သွင်းတောင်းဆို",
        km: "ស្នើសុំ",
      },
      furigana: [
        {
          rb: "申出",
          rt: "もうしで",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1633,
      kanji: "申し分",
      reading: "もうしぶん",
      meanings: {
        ja: "申し分",
        en: "complaint; objection",
        zh: "不满；缺点",
        tw: "不滿；缺失",
        ko: "불평; 흠",
        vi: "phàn nàn; khiếm khuyết",
        th: "ข้อครหา; ข้อตำหนิ",
        my: "တိုင်ကြားချက်",
        km: "ពាក្យបណ្ដឹង",
      },
      furigana: [
        {
          rb: "申し分",
          rt: "もうしぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1634,
      kanji: "盲点",
      reading: "もうてん",
      meanings: {
        ja: "盲点",
        en: "blind spot",
        zh: "盲点",
        tw: "盲點",
        ko: "사각지대",
        vi: "điểm mù",
        th: "จุดบอด",
        my: "အမြင်မရှိဒေသ",
        km: "ចំណុចខ្វាក់",
      },
      furigana: [
        {
          rb: "盲点",
          rt: "もうてん",
        },
      ],
      kanjiInfo: [
        {
          char: "盲",
          on: ["モウ"],
          kun: ["めくら"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1635,
      kanji: "モーテル",
      reading: "モーテル",
      meanings: {
        ja: "モーテル",
        en: "motel",
        zh: "汽车旅馆",
        tw: "汽車旅館",
        ko: "모텔",
        vi: "nhà nghỉ (motel)",
        th: "โมเทล",
        my: "မိုတယ်",
        km: "ម៉ូតែល",
      },
      furigana: [
        {
          rb: "モーテル",
          rt: "モーテル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1636,
      kanji: "目録",
      reading: "もくろく",
      meanings: {
        ja: "目録",
        en: "catalogue",
        zh: "目录",
        tw: "目錄",
        ko: "목록",
        vi: "mục lục",
        th: "สารบัญ/แคตตาล็อก",
        my: "ဇယားစာရင်း",
        km: "បញ្ជីមេ",
      },
      furigana: [
        {
          rb: "目録",
          rt: "もくろく",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "録",
          on: ["ロク"],
          kun: ["しる.す", "と.る"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1637,
      kanji: "目論見",
      reading: "もくろみ",
      meanings: {
        ja: "目論見",
        en: "plan; scheme",
        zh: "计划；打算",
        tw: "計畫；打算",
        ko: "계략; 계획",
        vi: "toan tính",
        th: "แผนการ",
        my: "အစီအစဉ်",
        km: "ផែនការ",
      },
      furigana: [
        {
          rb: "目論見",
          rt: "もくろみ",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1638,
      kanji: "模型",
      reading: "もけい",
      meanings: {
        ja: "模型",
        en: "model (scale)",
        zh: "模型",
        tw: "模型",
        ko: "모형",
        vi: "mô hình",
        th: "แบบจำลอง",
        my: "မော်ဒယ်",
        km: "គំរូតូច",
      },
      furigana: [
        {
          rb: "模型",
          rt: "もけい",
        },
      ],
      kanjiInfo: [
        {
          char: "模",
          on: ["モ", "ボ"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "型",
          on: ["ケイ"],
          kun: ["かた", "-がた"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1639,
      kanji: "模索",
      reading: "もさく",
      meanings: {
        ja: "模索",
        en: "groping for; searching",
        zh: "摸索",
        tw: "摸索",
        ko: "모색",
        vi: "mò mẫm tìm",
        th: "ค้นหาหนทาง",
        my: "ရှာဖွေမြိုက်",
        km: "ស្វែងរក",
      },
      furigana: [
        {
          rb: "模索",
          rt: "もさく",
        },
      ],
      kanjiInfo: [
        {
          char: "模",
          on: ["モ", "ボ"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "索",
          on: ["サク"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1640,
      kanji: "持ち切り",
      reading: "もちきり",
      meanings: {
        ja: "持ち切り",
        en: "hot topic; all the talk",
        zh: "热门话题",
        tw: "熱門話題",
        ko: "화제일색",
        vi: "chủ đề nóng",
        th: "หัวข้อร้อนแรง",
        my: "အလုပ်စကားအများဆုံး",
        km: "ប្រធានបទក្តៅ",
      },
      furigana: [
        {
          rb: "持ち切り",
          rt: "もちきり",
        },
      ],
      kanjiInfo: [
        {
          char: "持",
          on: ["ジ"],
          kun: ["も.つ", "-も.ち", "も.てる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1641,
      kanji: "目下",
      reading: "もっか",
      meanings: {
        ja: "目下",
        en: "at present; currently",
        zh: "目前",
        tw: "目前",
        ko: "목하; 현재",
        vi: "hiện tại",
        th: "ขณะนี้",
        my: "လက်ရှိ",
        km: "បច្ចុប្បន្ន",
      },
      furigana: [
        {
          rb: "目下",
          rt: "もっか",
        },
      ],
      kanjiInfo: [
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1642,
      kanji: "モニター",
      reading: "モニター",
      meanings: {
        ja: "モニター",
        en: "monitor; display",
        zh: "显示器；监视器",
        tw: "顯示器；監視器",
        ko: "모니터",
        vi: "màn hình",
        th: "จอภาพ",
        my: "မော်နီတာ",
        km: "ម៉ូនីទ័រ",
      },
      furigana: [
        {
          rb: "モニター",
          rt: "モニター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1643,
      kanji: "物好き",
      reading: "ものずき",
      meanings: {
        ja: "物好き",
        en: "idle curiosity",
        zh: "好奇心重的人",
        tw: "好奇的人",
        ko: "호기심 많은 사람",
        vi: "người hiếu kỳ",
        th: "คนขี้สงสัย",
        my: "စိတ်ဝင်စားလွန်းသူ",
        km: "អ្នកចូលចិត្តចម្លែក",
      },
      furigana: [
        {
          rb: "物好き",
          rt: "ものずき",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1644,
      kanji: "模範",
      reading: "もはん",
      meanings: {
        ja: "模範",
        en: "model; exemplar",
        zh: "模范",
        tw: "模範",
        ko: "모범",
        vi: "mô phạm",
        th: "แบบอย่าง",
        my: "နမူနာကောင်း",
        km: "គំរូល្អ",
      },
      furigana: [
        {
          rb: "模範",
          rt: "もはん",
        },
      ],
      kanjiInfo: [
        {
          char: "模",
          on: ["モ", "ボ"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "範",
          on: ["ハン"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1645,
      kanji: "模倣",
      reading: "もほう",
      meanings: {
        ja: "模倣",
        en: "imitation",
        zh: "模仿",
        tw: "模仿",
        ko: "모방",
        vi: "bắt chước",
        th: "เลียนแบบ",
        my: "ဇာတိတူ",
        km: "ការស្ទួន",
      },
      furigana: [
        {
          rb: "模倣",
          rt: "もほう",
        },
      ],
      kanjiInfo: [
        {
          char: "模",
          on: ["モ", "ボ"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "倣",
          on: ["ホウ"],
          kun: ["なら.う"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1646,
      kanji: "股",
      reading: "もも",
      meanings: {
        ja: "股",
        en: "thigh; groin",
        zh: "大腿；胯",
        tw: "大腿；胯",
        ko: "넓적다리; 서혜부",
        vi: "đùi; háng",
        th: "ต้นขา; ขาหนีบ",
        my: "ပေါက်; တင်ပါးအောက်",
        km: "ផ្ទៃភ្លៅ",
      },
      furigana: [
        {
          rb: "股",
          rt: "もも",
        },
      ],
      kanjiInfo: [
        {
          char: "股",
          on: ["コ"],
          kun: ["また", "もも"],
          strokes: 8,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1647,
      kanji: "腿",
      reading: "もも",
      meanings: {
        ja: "腿",
        en: "thigh",
        zh: "大腿",
        tw: "大腿",
        ko: "넓적다리",
        vi: "bắp đùi",
        th: "ต้นขา",
        my: "ပေါက် (တင်ပါး)",
        km: "ភ្លៅ",
      },
      furigana: [
        {
          rb: "腿",
          rt: "もも",
        },
      ],
      kanjiInfo: [
        {
          char: "腿",
          on: ["タイ"],
          kun: ["もも"],
          strokes: 13,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1648,
      kanji: "矢",
      reading: "や",
      meanings: {
        ja: "矢",
        en: "arrow",
        zh: "箭",
        tw: "箭",
        ko: "화살",
        vi: "mũi tên",
        th: "ลูกศร",
        my: "မြား",
        km: "ព្រួញ",
      },
      furigana: [
        {
          rb: "矢",
          rt: "や",
        },
      ],
      kanjiInfo: [
        {
          char: "矢",
          on: ["シ"],
          kun: ["や"],
          strokes: 5,
          grade: 2,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1649,
      kanji: "野外",
      reading: "やがい",
      meanings: {
        ja: "野外",
        en: "outdoors",
        zh: "野外",
        tw: "野外",
        ko: "야외",
        vi: "ngoài trời",
        th: "กลางแจ้ง",
        my: "ပြင်လသာ",
        km: "ក្រៅដើម",
      },
      furigana: [
        {
          rb: "野外",
          rt: "やがい",
        },
      ],
      kanjiInfo: [
        {
          char: "野",
          on: ["ヤ", "ショ"],
          kun: ["の", "の-"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1650,
      kanji: "夜具",
      reading: "やぐ",
      meanings: {
        ja: "夜具",
        en: "bedding",
        zh: "寝具",
        tw: "寢具",
        ko: "침구",
        vi: "chăn nệm",
        th: "เครื่องนอน",
        my: "အိပ်ရာပစ္စည်း",
        km: "គ្រឿងគេង",
      },
      furigana: [
        {
          rb: "夜具",
          rt: "やぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "夜",
          on: ["ヤ"],
          kun: ["よ", "よる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "具",
          on: ["グ"],
          kun: ["そな.える", "つぶさ.に"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
