export const n1part6 = {
  Lesson6: [
    {
      id: 251,
      kanji: "ドライブイン",
      reading: "ドライブイン",
      meanings: {
        ja: "ドライブイン",
        en: "drive-in (restaurant/theater)",
        zh: "免下车服务处",
        tw: "免下車服務處",
        ko: "드라이브인(식당/극장)",
        vi: "dịch vụ drive-in",
        th: "ไดรฟ์อิน (บริการไม่ต้องลงจากรถ)",
        my: "ကားမဆင်းဘဲ ဝန်ဆောင်မှု",
        km: "សេវា drive-in",
      },
      furigana: [
        {
          rb: "ドライブイン",
          rt: "ドライブイン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 252,
      kanji: "トラブル",
      reading: "トラブル",
      meanings: {
        ja: "トラブル",
        en: "trouble; problem",
        zh: "麻烦；故障",
        tw: "麻煩；故障",
        ko: "문제; 트러블",
        vi: "rắc rối",
        th: "ปัญหา/ขัดข้อง",
        my: "ပြဿနာ",
        km: "បញ្ហា",
      },
      furigana: [
        {
          rb: "トラブル",
          rt: "トラブル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 253,
      kanji: "トランジスター",
      reading: "トランジスター",
      meanings: {
        ja: "トランジスター",
        en: "transistor",
        zh: "晶体管",
        tw: "電晶體",
        ko: "트랜지스터",
        vi: "transistor",
        th: "ทรานซิสเตอร์",
        my: "ထရန်စစ္စတာ",
        km: "ត្រាន់ស៊ីស្ត័រ",
      },
      furigana: [
        {
          rb: "トランジスター",
          rt: "トランジスター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 254,
      kanji: "取扱",
      reading: "とりあつかい",
      meanings: {
        ja: "取扱",
        en: "handling; treatment",
        zh: "处理；对待",
        tw: "處理；對待",
        ko: "취급; 다룸",
        vi: "xử lý; đối đãi",
        th: "การจัดการ; การปฏิบัติ",
        my: "ကိုင်တွယ်မှု",
        km: "ការដោះស្រាយ; ប្រព្រឹត្ត",
      },
      furigana: [
        {
          rb: "取扱",
          rt: "とりあつかい",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "扱",
          on: ["ソウ", "キュウ"],
          kun: ["あつか.い", "あつか.う", "あつか.る", "こ.く"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 255,
      kanji: "鳥居",
      reading: "とりい",
      meanings: {
        ja: "鳥居",
        en: "torii (Shinto gate)",
        zh: "鸟居（神社门）",
        tw: "鳥居（神社門）",
        ko: "도리이(신사문)",
        vi: "cổng torii",
        th: "โทริอิ (ประตูศินโต)",
        my: "တိုရီအိ",
        km: "ទ្វារ​តូរី",
      },
      furigana: [
        {
          rb: "鳥居",
          rt: "とりい",
        },
      ],
      kanjiInfo: [
        {
          char: "鳥",
          on: ["チョウ"],
          kun: ["とり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "居",
          on: ["キョ", "コ"],
          kun: ["い.る", "-い", "お.る"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 256,
      kanji: "取り替え",
      reading: "とりかえ",
      meanings: {
        ja: "取り替え",
        en: "exchange; replacement",
        zh: "更换；交换",
        tw: "更換；交換",
        ko: "교환; 교체",
        vi: "thay; đổi",
        th: "เปลี่ยน; แลก",
        my: "လဲပြောင်း/အစားထိုး",
        km: "ប្តូរ; ជំនួស",
      },
      furigana: [
        {
          rb: "取り替え",
          rt: "とりかえ",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "替",
          on: ["タイ"],
          kun: ["か.える", "か.え-", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 257,
      kanji: "取締り",
      reading: "とりしまり",
      meanings: {
        ja: "取締り",
        en: "crackdown; control",
        zh: "取缔；整治",
        tw: "取締；整治",
        ko: "단속",
        vi: "trấn áp; kiểm soát",
        th: "การกวดขัน",
        my: "ဒဏ်ခတ်ထိန်းချုပ်",
        km: "ការដាក់ទណ្ឌាល/ត្រួតពិនិត្យ",
      },
      furigana: [
        {
          rb: "取締り",
          rt: "とりしまり",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "締",
          on: ["テイ"],
          kun: ["し.まる", "し.まり", "し.める", "-し.め", "-じ.め"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 258,
      kanji: "取引",
      reading: "とりひき",
      meanings: {
        ja: "取引",
        en: "transactions; dealings",
        zh: "交易",
        tw: "交易",
        ko: "거래",
        vi: "giao dịch",
        th: "การทำธุรกรรม",
        my: "စီးပွားရေး လုပ်ရပ်",
        km: "ការជួញដូរ",
      },
      furigana: [
        {
          rb: "取引",
          rt: "とりひき",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "引",
          on: ["イン"],
          kun: ["ひ.く", "ひ.ける"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 259,
      kanji: "ドリル",
      reading: "ドリル",
      meanings: {
        ja: "ドリル",
        en: "drill (bit/tool)",
        zh: "钻头；练习册",
        tw: "鑽頭；練習本",
        ko: "드릴",
        vi: "mũi khoan; drill",
        th: "สว่าน; แบบฝึกหัด",
        my: "ဒရിൽ",
        km: "ដ្រីល",
      },
      furigana: [
        {
          rb: "ドリル",
          rt: "ドリル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 260,
      kanji: "度忘れ",
      reading: "どわすれ",
      meanings: {
        ja: "度忘れ",
        en: "lapse of memory; mental blank",
        zh: "一时想不起来",
        tw: "一時想不起",
        ko: "깜빡 잊음",
        vi: "chợt quên",
        th: "ลืมกะทันหัน",
        my: "မိနစ်ပိုင်း မေ့သွား",
        km: "ភ្លេចភ្លាំងភ្លែត",
      },
      furigana: [
        {
          rb: "度忘れ",
          rt: "どわすれ",
        },
      ],
      kanjiInfo: [
        {
          char: "度",
          on: ["ド", "ト", "タク"],
          kun: ["たび", "-た.い"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "忘",
          on: ["ボウ"],
          kun: ["わす.れる"],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 261,
      kanji: "問屋",
      reading: "とんや",
      meanings: {
        ja: "問屋",
        en: "wholesaler",
        zh: "批发商",
        tw: "批發商",
        ko: "도매상",
        vi: "nhà bán buôn",
        th: "ผู้ค้าส่ง",
        my: "ဆိုင်လက်ကား",
        km: "ហាងលក់លើស",
      },
      furigana: [
        {
          rb: "問屋",
          rt: "とんや",
        },
      ],
      kanjiInfo: [
        {
          char: "問",
          on: ["モン"],
          kun: ["と.う", "と.い", "とん"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "屋",
          on: ["オク"],
          kun: ["や"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 262,
      kanji: "内閣",
      reading: "ないかく",
      meanings: {
        ja: "内閣",
        en: "cabinet (government)",
        zh: "内阁",
        tw: "內閣",
        ko: "내각",
        vi: "nội các",
        th: "คณะรัฐมนตรี",
        my: "အတွင်းအကယ်ဒ်/ကာဘිනက်",
        km: "រដ្ឋាភិបាលក្រុមរដ្ឋមន្ត្រី",
      },
      furigana: [
        {
          rb: "内閣",
          rt: "ないかく",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "閣",
          on: ["カク"],
          kun: [],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 263,
      kanji: "内緒",
      reading: "ないしょ",
      meanings: {
        ja: "内緒",
        en: "secrecy; private",
        zh: "秘密",
        tw: "秘密",
        ko: "비밀",
        vi: "bí mật",
        th: "เป็นความลับ",
        my: "လျှို့ဝှက်",
        km: "សម្ងាត់",
      },
      furigana: [
        {
          rb: "内緒",
          rt: "ないしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "緒",
          on: ["ショ", "チョ"],
          kun: ["お", "いとぐち"],
          strokes: 14,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 264,
      kanji: "内心",
      reading: "ないしん",
      meanings: {
        ja: "内心",
        en: "inner thoughts; heart of hearts",
        zh: "内心；心底",
        tw: "內心；心底",
        ko: "내심",
        vi: "trong thâm tâm",
        th: "ในใจลึกๆ",
        my: "စိတ်အတွင်းပိုင်း",
        km: "ក្នុងចិត្ដ",
      },
      furigana: [
        {
          rb: "内心",
          rt: "ないしん",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 265,
      kanji: "ナイター",
      reading: "ナイター",
      meanings: {
        ja: "ナイター",
        en: "night game (e.g., baseball)",
        zh: "夜间比赛",
        tw: "夜間比賽",
        ko: "야간 경기",
        vi: "trận đấu ban đêm",
        th: "การแข่งขันกลางคืน",
        my: "ညပိုင်းပြိုင်ပွဲ",
        km: "ការប្រកួតពេលយប់",
      },
      furigana: [
        {
          rb: "ナイター",
          rt: "ナイター",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 266,
      kanji: "内部",
      reading: "ないぶ",
      meanings: {
        ja: "内部",
        en: "interior; inside",
        zh: "内部",
        tw: "內部",
        ko: "내부",
        vi: "nội bộ; bên trong",
        th: "ภายใน",
        my: "အတွင်းပိုင်း",
        km: "ខាងក្នុង",
      },
      furigana: [
        {
          rb: "内部",
          rt: "ないぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 267,
      kanji: "内乱",
      reading: "ないらん",
      meanings: {
        ja: "内乱",
        en: "civil war; internal strife",
        zh: "内乱",
        tw: "內亂",
        ko: "내란",
        vi: "nội loạn",
        th: "สงครามกลางเมือง",
        my: "ပြည်တွင်းပဋိပက္ခ",
        km: "ជម្លោះក្នុងប្រទេស",
      },
      furigana: [
        {
          rb: "内乱",
          rt: "ないらん",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "乱",
          on: ["ラン", "ロン"],
          kun: [
            "みだ.れる",
            "みだ.る",
            "みだ.す",
            "みだ",
            "おさ.める",
            "わた.る",
          ],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 268,
      kanji: "内陸",
      reading: "ないりく",
      meanings: {
        ja: "内陸",
        en: "inland",
        zh: "内陆",
        tw: "內陸",
        ko: "내륙",
        vi: "nội địa",
        th: "ในแผ่นดิน; ไม่ติดทะเล",
        my: "ပြည်တွင်းပိုင်း",
        km: "ក្នុងដី",
      },
      furigana: [
        {
          rb: "内陸",
          rt: "ないりく",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "陸",
          on: ["リク", "ロク"],
          kun: ["おか"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 269,
      kanji: "苗",
      reading: "なえ",
      meanings: {
        ja: "苗",
        en: "seedling; young plant",
        zh: "幼苗",
        tw: "幼苗",
        ko: "모종",
        vi: "cây con",
        th: "ต้นกล้า",
        my: "ရိုးတင်စေ့ငယ်",
        km: "កូនដំណាំ",
      },
      furigana: [
        {
          rb: "苗",
          rt: "なえ",
        },
      ],
      kanjiInfo: [
        {
          char: "苗",
          on: ["ビョウ", "ミョウ"],
          kun: ["なえ", "なわ-"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 270,
      kanji: "流し",
      reading: "ながし",
      meanings: {
        ja: "流し",
        en: "sink (kitchen)",
        zh: "洗碗槽",
        tw: "流理台水槽",
        ko: "싱크대",
        vi: "bồn rửa (bếp)",
        th: "อ่างล้างจาน",
        my: "မီးဖိုထိုင် မြင့်တင်",
        km: "លាងចាន (តូបផ្ទះបាយ)",
      },
      furigana: [
        {
          rb: "流し",
          rt: "ながし",
        },
      ],
      kanjiInfo: [
        {
          char: "流",
          on: ["リュウ", "ル"],
          kun: ["なが.れる", "なが.れ", "なが.す", "-なが.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 271,
      kanji: "中程",
      reading: "なかほど",
      meanings: {
        ja: "中程",
        en: "middle; halfway",
        zh: "中间；半途",
        tw: "中間；半途",
        ko: "중간쯤",
        vi: "giữa chừng",
        th: "ช่วงกลาง",
        my: "အလယ်ခန့်",
        km: "កណ្ដាល",
      },
      furigana: [
        {
          rb: "中程",
          rt: "なかほど",
        },
      ],
      kanjiInfo: [
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "程",
          on: ["テイ"],
          kun: ["ほど", "-ほど"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 272,
      kanji: "渚",
      reading: "なぎさ",
      meanings: {
        ja: "渚",
        en: "water's edge; beach",
        zh: "水滨；海滨",
        tw: "水濱；海濱",
        ko: "물가; 바닷가",
        vi: "bờ nước; bãi biển",
        th: "ริมน้ำ/ชายหาด",
        my: "ရေကမ္ဘာအနား",
        km: "ច្រាំងទឹក/ឆ្នេរ",
      },
      furigana: [
        {
          rb: "渚",
          rt: "なぎさ",
        },
      ],
      kanjiInfo: [
        {
          char: "渚",
          on: ["ショ"],
          kun: ["なぎさ"],
          strokes: 11,
          grade: 9,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 273,
      kanji: "仲人",
      reading: "なこうど",
      meanings: {
        ja: "仲人",
        en: "matchmaker; go-between",
        zh: "媒人",
        tw: "媒人",
        ko: "중매인",
        vi: "ông/bà mai",
        th: "แม่สื่อ/พ่อสื่อ",
        my: "ရည်းစားမှုညှိနှိုင်းသူ",
        km: "អ្នកប្រតិភូស្នេហ៍",
      },
      furigana: [
        {
          rb: "仲人",
          rt: "なこうど",
        },
      ],
      kanjiInfo: [
        {
          char: "仲",
          on: ["チュウ"],
          kun: ["なか"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 274,
      kanji: "名残",
      reading: "なごり",
      meanings: {
        ja: "名残",
        en: "remains; traces; parting memory",
        zh: "余韵；遗迹",
        tw: "餘韻；遺留",
        ko: "여운; 자취",
        vi: "dấu vết; dư âm",
        th: "ร่องรอย/ความทรงจำค้าง",
        my: "လက်ကျန်အမွေလက္ခဏာ",
        km: "សំណល់; អារម្មណ៍នៅសល់",
      },
      furigana: [
        {
          rb: "名残",
          rt: "なごり",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "残",
          on: ["ザン", "サン"],
          kun: ["のこ.る", "のこ.す", "そこな.う", "のこ.り"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 275,
      kanji: "情け",
      reading: "なさけ",
      meanings: {
        ja: "情け",
        en: "compassion; mercy",
        zh: "怜悯；同情",
        tw: "憐憫；同情",
        ko: "정; 동정심",
        vi: "lòng trắc ẩn",
        th: "ความเมตตาสงสาร",
        my: "စိတ်မနာသနားမှု",
        km: "មេត្តាករុណា",
      },
      furigana: [
        {
          rb: "情け",
          rt: "なさけ",
        },
      ],
      kanjiInfo: [
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 276,
      kanji: "雪崩",
      reading: "なだれ",
      meanings: {
        ja: "雪崩",
        en: "avalanche",
        zh: "雪崩",
        tw: "雪崩",
        ko: "눈사태",
        vi: "tuyết lở",
        th: "หิมะถล่ม",
        my: "နှင်းတောင်ကျပ်ကျ",
        km: "ព្រិលរលំ",
      },
      furigana: [
        {
          rb: "雪崩",
          rt: "なだれ",
        },
      ],
      kanjiInfo: [
        {
          char: "雪",
          on: ["セツ"],
          kun: ["ゆき"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "崩",
          on: ["ホウ"],
          kun: ["くず.れる", "-くず.れ", "くず.す"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 277,
      kanji: "ナプキン",
      reading: "ナプキン",
      meanings: {
        ja: "ナプキン",
        en: "napkin",
        zh: "餐巾",
        tw: "餐巾",
        ko: "냅킨",
        vi: "khăn ăn",
        th: "ผ้าเช็ดปาก",
        my: "ন্যাপকင်/餐巾布",
        km: "កន្សែងតុ",
      },
      furigana: [
        {
          rb: "ナプキン",
          rt: "ナプキン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 278,
      kanji: "名札",
      reading: "なふだ",
      meanings: {
        ja: "名札",
        en: "name tag; name plate",
        zh: "名牌；名签",
        tw: "名牌；名籤",
        ko: "이름표",
        vi: "bảng tên",
        th: "ป้ายชื่อ",
        my: "အမည်တံဆိပ်",
        km: "ផ្លាកឈ្មោះ",
      },
      furigana: [
        {
          rb: "名札",
          rt: "なふだ",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "札",
          on: ["サツ"],
          kun: ["ふだ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 279,
      kanji: "生身",
      reading: "なまみ",
      meanings: {
        ja: "生身",
        en: "living flesh; in the flesh",
        zh: "活生生的身体",
        tw: "活生生的身體",
        ko: "살아있는 몸",
        vi: "thân thể sống",
        th: "เนื้อหนังมังสา",
        my: "အသက်ရှင်သော ကိုယ်ကို",
        km: "សាច់ឈាមរស់",
      },
      furigana: [
        {
          rb: "生身",
          rt: "なまみ",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "身",
          on: ["シン"],
          kun: ["み"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 280,
      kanji: "鉛",
      reading: "なまり",
      meanings: {
        ja: "鉛",
        en: "lead (Pb)",
        zh: "铅",
        tw: "鉛",
        ko: "연 (Pb)",
        vi: "chì (Pb)",
        th: "ตะกั่ว (Pb)",
        my: "ဆီးစီ (Pb)",
        km: "សំបុកដែក Pb",
      },
      furigana: [
        {
          rb: "鉛",
          rt: "なまり",
        },
      ],
      kanjiInfo: [
        {
          char: "鉛",
          on: ["エン"],
          kun: ["なまり"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 281,
      kanji: "悩み",
      reading: "なやみ",
      meanings: {
        ja: "悩み",
        en: "trouble; worry",
        zh: "烦恼；困扰",
        tw: "煩惱；困擾",
        ko: "고민; 근심",
        vi: "nỗi phiền não",
        th: "ความกลุ้มใจ/ปัญหา",
        my: "စိတ်ပူပန်မှု",
        km: "កង្វល់",
      },
      furigana: [
        {
          rb: "悩み",
          rt: "なやみ",
        },
      ],
      kanjiInfo: [
        {
          char: "悩",
          on: ["ノウ"],
          kun: ["なや.む", "なや.ます", "なや.ましい", "なやみ"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 282,
      kanji: "慣れ",
      reading: "なれ",
      meanings: {
        ja: "慣れ",
        en: "habit; experience; getting used to",
        zh: "习惯；熟练",
        tw: "習慣；熟練",
        ko: "익숙함; 숙련",
        vi: "sự quen; kinh nghiệm",
        th: "ความคุ้นเคย/ความชำนาญ",
        my: "စွဲလန်းကျင့်သား",
        km: "ភាពជាប់ទាក់ទាញ/ចេះកាន់តែស្ទាត់",
      },
      furigana: [
        {
          rb: "慣れ",
          rt: "なれ",
        },
      ],
      kanjiInfo: [
        {
          char: "慣",
          on: ["カン"],
          kun: ["な.れる", "な.らす"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 283,
      kanji: "荷",
      reading: "に",
      meanings: {
        ja: "荷",
        en: "load; baggage; cargo",
        zh: "货物；行李",
        tw: "貨物；行李",
        ko: "짐; 화물",
        vi: "hàng; hành lý",
        th: "สัมภาระ; สินค้า",
        my: "အထုပ်အပိုး",
        km: "ទំនិញ; ឥវ៉ាន់",
      },
      furigana: [
        {
          rb: "荷",
          rt: "に",
        },
      ],
      kanjiInfo: [
        {
          char: "荷",
          on: ["カ"],
          kun: ["に"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 284,
      kanji: "憎しみ",
      reading: "にくしみ",
      meanings: {
        ja: "憎しみ",
        en: "hatred",
        zh: "憎恨",
        tw: "憎恨",
        ko: "증오",
        vi: "hận thù",
        th: "ความเกลียดชัง",
        my: "မုန်းတီးမှု",
        km: "សេចក្ដីស្អប់",
      },
      furigana: [
        {
          rb: "憎しみ",
          rt: "にくしみ",
        },
      ],
      kanjiInfo: [
        {
          char: "憎",
          on: ["ゾウ"],
          kun: ["にく.む", "にく.い", "にく.らしい", "にく.しみ"],
          strokes: 14,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 285,
      kanji: "肉親",
      reading: "にくしん",
      meanings: {
        ja: "肉親",
        en: "blood relative",
        zh: "至亲",
        tw: "至親",
        ko: "육친",
        vi: "ruột thịt",
        th: "ญาติสายเลือด",
        my: "သွေးဆုံးရင်းသား",
        km: "សាច់ញាតិឈាម",
      },
      furigana: [
        {
          rb: "肉親",
          rt: "にくしん",
        },
      ],
      kanjiInfo: [
        {
          char: "肉",
          on: ["ニク"],
          kun: ["しし"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "親",
          on: ["シン"],
          kun: ["おや", "おや-", "した.しい", "した.しむ"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 286,
      kanji: "肉体",
      reading: "にくたい",
      meanings: {
        ja: "肉体",
        en: "the body; flesh",
        zh: "肉体；身体",
        tw: "肉體；身軀",
        ko: "육체",
        vi: "thể xác",
        th: "ร่างกาย",
        my: "ကိုယ်ခံခန္ဓာ",
        km: "រាងកាយ",
      },
      furigana: [
        {
          rb: "肉体",
          rt: "にくたい",
        },
      ],
      kanjiInfo: [
        {
          char: "肉",
          on: ["ニク"],
          kun: ["しし"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 287,
      kanji: "西日",
      reading: "にしび",
      meanings: {
        ja: "西日",
        en: "westering sun; afternoon sun",
        zh: "夕照；西晒阳光",
        tw: "夕照；西曬",
        ko: "서쪽 햇빛",
        vi: "nắng chiều hướng tây",
        th: "แดดบ่ายจากทิศตะวันตก",
        my: "အနောက်အရပ် နေခြည်",
        km: "ពន្លឺថ្ងៃពីលិច",
      },
      furigana: [
        {
          rb: "西日",
          rt: "にしび",
        },
      ],
      kanjiInfo: [
        {
          char: "西",
          on: ["セイ", "サイ", "ス"],
          kun: ["にし"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 288,
      kanji: "にせ物",
      reading: "にせもの",
      meanings: {
        ja: "にせ物",
        en: "counterfeit; fake",
        zh: "假货",
        tw: "假貨",
        ko: "가짜",
        vi: "đồ giả",
        th: "ของปลอม",
        my: "အတု",
        km: "វត្ថុក្លែងក្លាយ",
      },
      furigana: [
        {
          rb: "にせ物",
          rt: "にせもの",
        },
      ],
      kanjiInfo: [
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 289,
      kanji: "荷造り",
      reading: "にづくり",
      meanings: {
        ja: "荷造り",
        en: "packing (luggage)",
        zh: "打包",
        tw: "打包",
        ko: "짐싸기",
        vi: "đóng gói hành lý",
        th: "การจัดกระเป๋า/แพ็คของ",
        my: "ထုပ်ပိုးခြင်း",
        km: "ការបូមកាបូប/វេចខ្ចប់",
      },
      furigana: [
        {
          rb: "荷造り",
          rt: "にづくり",
        },
      ],
      kanjiInfo: [
        {
          char: "荷",
          on: ["カ"],
          kun: ["に"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "造",
          on: ["ゾウ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 290,
      kanji: "ニュアンス",
      reading: "ニュアンス",
      meanings: {
        ja: "ニュアンス",
        en: "nuance",
        zh: "细微差别；意味",
        tw: "語氣/細微差別",
        ko: "뉘앙스",
        vi: "sắc thái",
        th: "นัย/ความต่างเล็กน้อย",
        my: "ရောင်အရိပ်အသွေး",
        km: "ន្យូអង់ស៍",
      },
      furigana: [
        {
          rb: "ニュアンス",
          rt: "ニュアンス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 291,
      kanji: "入手",
      reading: "にゅうしゅ",
      meanings: {
        ja: "入手",
        en: "acquisition; obtaining",
        zh: "获得；取得",
        tw: "取得；獲得",
        ko: "입수",
        vi: "thu được; lấy được",
        th: "ได้มา; ครอบครอง",
        my: "ရရှိသက်သာ",
        km: "ទទួលបាន",
      },
      furigana: [
        {
          rb: "入手",
          rt: "にゅうしゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 292,
      kanji: "入賞",
      reading: "にゅうしょう",
      meanings: {
        ja: "入賞",
        en: "winning a prize",
        zh: "获奖",
        tw: "得獎",
        ko: "입상",
        vi: "đoạt giải",
        th: "ได้รับรางวัล",
        my: "ဆုရရှိ",
        km: "បានពានរង្វាន់",
      },
      furigana: [
        {
          rb: "入賞",
          rt: "にゅうしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "賞",
          on: ["ショウ"],
          kun: ["ほ.める"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 293,
      kanji: "入浴",
      reading: "にゅうよく",
      meanings: {
        ja: "入浴",
        en: "bathing",
        zh: "入浴；洗澡",
        tw: "入浴；洗澡",
        ko: "입욕",
        vi: "tắm",
        th: "อาบน้ำ",
        my: "ရေချိုး",
        km: "ងូតទឹក",
      },
      furigana: [
        {
          rb: "入浴",
          rt: "にゅうよく",
        },
      ],
      kanjiInfo: [
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "浴",
          on: ["ヨク"],
          kun: ["あ.びる", "あ.びせる"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 294,
      kanji: "尿",
      reading: "にょう",
      meanings: {
        ja: "尿",
        en: "urine",
        zh: "尿",
        tw: "尿",
        ko: "뇨; 오줌",
        vi: "nước tiểu",
        th: "ปัสสาวะ",
        my: "ဆီး",
        km: "ទឹកនោម",
      },
      furigana: [
        {
          rb: "尿",
          rt: "にょう",
        },
      ],
      kanjiInfo: [
        {
          char: "尿",
          on: ["ニョウ"],
          kun: ["ゆばり", "いばり", "しと"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 295,
      kanji: "認識",
      reading: "にんしき",
      meanings: {
        ja: "認識",
        en: "recognition; awareness",
        zh: "认识；认知",
        tw: "認識；認知",
        ko: "인식",
        vi: "nhận thức",
        th: "การรับรู้",
        my: "အသိအမှတ်ပြု/သိမြင်",
        km: "ការយល់ដឹង",
      },
      furigana: [
        {
          rb: "認識",
          rt: "にんしき",
        },
      ],
      kanjiInfo: [
        {
          char: "認",
          on: ["ニン"],
          kun: ["みと.める", "したた.める"],
          strokes: 14,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "識",
          on: ["シキ"],
          kun: ["し.る", "しる.す"],
          strokes: 19,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 296,
      kanji: "妊娠",
      reading: "にんしん",
      meanings: {
        ja: "妊娠",
        en: "pregnancy",
        zh: "妊娠；怀孕",
        tw: "妊娠；懷孕",
        ko: "임신",
        vi: "mang thai",
        th: "การตั้งครรภ์",
        my: "ကိုယ်ဝန်ဆောင်",
        km: "មានផ្ទៃពោះ",
      },
      furigana: [
        {
          rb: "妊娠",
          rt: "にんしん",
        },
      ],
      kanjiInfo: [
        {
          char: "妊",
          on: ["ニン", "ジン"],
          kun: ["はら.む", "みごも.る"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "娠",
          on: ["シン"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 297,
      kanji: "任務",
      reading: "にんむ",
      meanings: {
        ja: "任務",
        en: "duty; mission",
        zh: "任务",
        tw: "任務",
        ko: "임무",
        vi: "nhiệm vụ",
        th: "ภารกิจ",
        my: "တာဝန်",
        km: "ភារកិច្ច",
      },
      furigana: [
        {
          rb: "任務",
          rt: "にんむ",
        },
      ],
      kanjiInfo: [
        {
          char: "任",
          on: ["ニン"],
          kun: ["まか.せる", "まか.す"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "務",
          on: ["ム"],
          kun: ["つと.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 298,
      kanji: "任命",
      reading: "にんめい",
      meanings: {
        ja: "任命",
        en: "appointment (to a post)",
        zh: "任命",
        tw: "任命",
        ko: "임명",
        vi: "bổ nhiệm",
        th: "แต่งตั้ง",
        my: "အလုပ်တင်မြှောက်/အခန့်အနား",
        km: "តែងតាំង",
      },
      furigana: [
        {
          rb: "任命",
          rt: "にんめい",
        },
      ],
      kanjiInfo: [
        {
          char: "任",
          on: ["ニン"],
          kun: ["まか.せる", "まか.す"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 299,
      kanji: "主",
      reading: "ぬし",
      meanings: {
        ja: "主",
        en: "head; owner (household)",
        zh: "主人；户主",
        tw: "主人；戶主",
        ko: "주인; 호주",
        vi: "chủ; chủ hộ",
        th: "เจ้าของ; หัวหน้าครอบครัว",
        my: "အိမ်ရှင်/အိမ်ဦးစီး",
        km: "ម្ចាស់ផ្ទះ",
      },
      furigana: [
        {
          rb: "主",
          rt: "ぬし",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 300,
      kanji: "沼",
      reading: "ぬま",
      meanings: {
        ja: "沼",
        en: "marsh; swamp",
        zh: "沼泽",
        tw: "沼澤",
        ko: "늪",
        vi: "đầm lầy",
        th: "บึง/หนองน้ำ",
        my: "မစ္ဆထောင်",
        km: "ព្រៃទឹក/បឹងល្បាក់",
      },
      furigana: [
        {
          rb: "沼",
          rt: "ぬま",
        },
      ],
      kanjiInfo: [
        {
          char: "沼",
          on: ["ショウ"],
          kun: ["ぬま"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
