export const n1part41 = {
  Lesson41: [
    {
      id: 1960,
      kanji: "ぞんざい",
      reading: "ぞんざい",
      meanings: {
        ja: "ぞんざい（粗雑な）",
        en: "rough; careless",
        zh: "粗鲁；草率",
        tw: "粗魯；草率",
        ko: "거칠다; 대충하다",
        vi: "cẩu thả; thô lỗ",
        th: "หยาบคาย; ลวก ๆ",
        my: "ရိုင်းပြောင်သော; မသေချာသော",
        km: "មិនប្រុងប្រយ័ត្ន; ធ្វើយ៉ាងស្មានស្មាន",
      },
      furigana: [
        {
          rb: "ぞんざい",
          rt: "ぞんざい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1961,
      kanji: "大胆",
      reading: "だいたん",
      meanings: {
        ja: "大胆（思い切った）",
        en: "bold; daring",
        zh: "大胆；勇敢",
        tw: "大膽；勇敢",
        ko: "대담하다; 용감하다",
        vi: "can đảm; táo bạo",
        th: "กล้าหาญ; ใจกล้า",
        my: "အကြံအစည်ကြီးသော; သတ္တိရှိသော",
        km: "ក្លាហាន; មានទំនុកចិត្ត",
      },
      furigana: [
        {
          rb: "大胆",
          rt: "だいたん",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "胆",
          on: ["タン"],
          kun: ["きも"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1962,
      kanji: "台無し",
      reading: "だいなし",
      meanings: {
        ja: "台無し（めちゃくちゃ）",
        en: "spoiled; ruined",
        zh: "搞砸；毁掉",
        tw: "弄壞；毀掉",
        ko: "망치다; 엉망되다",
        vi: "bị hỏng; bị phá",
        th: "พังพินาศ; เสียหาย",
        my: "ပျက်စီးသော; မအောင်မြင်သော",
        km: "ខូចខាត; បរាជ័យ",
      },
      furigana: [
        {
          rb: "台無し",
          rt: "だいなし",
        },
      ],
      kanjiInfo: [
        {
          char: "台",
          on: ["ダイ", "タイ"],
          kun: ["うてな", "われ", "つかさ"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1963,
      kanji: "大部",
      reading: "たいぶ",
      meanings: {
        ja: "大部（分量の多い）",
        en: "lengthy; voluminous",
        zh: "篇幅很长",
        tw: "篇幅長",
        ko: "분량이 많다",
        vi: "dài; nhiều trang",
        th: "ยาวมาก; หนามาก",
        my: "စာအုပ်အရွယ်အစားကြီးသော",
        km: "វែងៗ; ច្រើនទំព័រ",
      },
      furigana: [
        {
          rb: "大部",
          rt: "たいぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1964,
      kanji: "タイムリー",
      reading: "タイムリー",
      meanings: {
        ja: "タイムリー（適時の）",
        en: "timely; opportune",
        zh: "及时的",
        tw: "及時的",
        ko: "시기적절한",
        vi: "đúng lúc",
        th: "ตรงเวลา; เหมาะสม",
        my: "အချိန်မှန်သော",
        km: "ត្រឹមត្រូវពេលវេលា",
      },
      furigana: [
        {
          rb: "タイムリー",
          rt: "タイムリー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1965,
      kanji: "巧み",
      reading: "たくみ",
      meanings: {
        ja: "巧み（上手な）",
        en: "skillful; clever",
        zh: "巧妙；熟练",
        tw: "巧妙；熟練",
        ko: "숙련된; 교묘한",
        vi: "khéo léo; tinh xảo",
        th: "ชำนาญ; แยบยล",
        my: "ကျွမ်းကျင်သော",
        km: "មានជំនាញ; ឆ្លាតវៃ",
      },
      furigana: [
        {
          rb: "巧み",
          rt: "たくみ",
        },
      ],
      kanjiInfo: [
        {
          char: "巧",
          on: ["コウ"],
          kun: ["たく.み", "たく.む", "うま.い"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1966,
      kanji: "達者",
      reading: "たっしゃ",
      meanings: {
        ja: "達者（健康な）",
        en: "in good health; skillful",
        zh: "健康；熟练",
        tw: "健康；熟練",
        ko: "건강하다; 능숙하다",
        vi: "khỏe mạnh; thành thạo",
        th: "แข็งแรง; ชำนาญ",
        my: "ကျန်းမာသော; ကျွမ်းကျင်သော",
        km: "សុខភាពល្អ; ជំនាញល្អ",
      },
      furigana: [
        {
          rb: "達者",
          rt: "たっしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "達",
          on: ["タツ", "ダ"],
          kun: ["-たち"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "者",
          on: ["シャ"],
          kun: ["もの"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1967,
      kanji: "だぶだぶ",
      reading: "だぶだぶ",
      meanings: {
        ja: "だぶだぶ（服が大きい）",
        en: "baggy; loose (clothing)",
        zh: "宽大的（衣服）",
        tw: "寬鬆的（衣服）",
        ko: "헐렁한 (옷)",
        vi: "rộng (quần áo)",
        th: "หลวม (เสื้อผ้า)",
        my: "အဝတ်လွှတ်သော",
        km: "ធំល្មម; អាកាសចេញចូល",
      },
      furigana: [
        {
          rb: "だぶだぶ",
          rt: "だぶだぶ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1968,
      kanji: "多様",
      reading: "たよう",
      meanings: {
        ja: "多様（いろいろな）",
        en: "diverse; various",
        zh: "多样",
        tw: "多樣",
        ko: "다양하다",
        vi: "đa dạng",
        th: "หลากหลาย",
        my: "အမျိုးအစားစုံလင်သော",
        km: "ច្រើនប្រភេទ",
      },
      furigana: [
        {
          rb: "多様",
          rt: "たよう",
        },
      ],
      kanjiInfo: [
        {
          char: "多",
          on: ["タ"],
          kun: ["おお.い", "まさ.に", "まさ.る"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "様",
          on: ["ヨウ", "ショウ"],
          kun: ["さま", "さん"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1969,
      kanji: "単一",
      reading: "たんいつ",
      meanings: {
        ja: "単一（ひとつの）",
        en: "single; simple",
        zh: "单一",
        tw: "單一",
        ko: "단일",
        vi: "đơn nhất",
        th: "อย่างเดียว",
        my: "တစ်ခုတည်းသော",
        km: "តែមួយ",
      },
      furigana: [
        {
          rb: "単一",
          rt: "たんいつ",
        },
      ],
      kanjiInfo: [
        {
          char: "単",
          on: ["タン"],
          kun: ["ひとえ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1970,
      kanji: "単調",
      reading: "たんちょう",
      meanings: {
        ja: "単調（変化のない）",
        en: "monotonous; dull",
        zh: "单调",
        tw: "單調",
        ko: "단조롭다",
        vi: "đơn điệu",
        th: "น่าเบื่อ; เดิมๆ",
        my: "တစ်မျိုးတည်းသာရှိသော",
        km: "ធុញថប់; ដដែលៗ",
      },
      furigana: [
        {
          rb: "単調",
          rt: "たんちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "単",
          on: ["タン"],
          kun: ["ひとえ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "調",
          on: ["チョウ"],
          kun: ["しら.べる", "しら.べ", "ととの.う", "ととの.える"],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1971,
      kanji: "単独",
      reading: "たんどく",
      meanings: {
        ja: "単独（ひとりで）",
        en: "sole; independent",
        zh: "单独",
        tw: "單獨",
        ko: "단독으로",
        vi: "một mình",
        th: "คนเดียว",
        my: "တစ်ဦးတည်းဖြစ်သော",
        km: "ម្នាក់ឯង",
      },
      furigana: [
        {
          rb: "単独",
          rt: "たんどく",
        },
      ],
      kanjiInfo: [
        {
          char: "単",
          on: ["タン"],
          kun: ["ひとえ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "独",
          on: ["ドク", "トク"],
          kun: ["ひと.り"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1972,
      kanji: "知的",
      reading: "ちてき",
      meanings: {
        ja: "知的（頭のいい）",
        en: "intellectual; smart",
        zh: "有智慧的",
        tw: "有智慧的",
        ko: "지적인",
        vi: "trí tuệ",
        th: "มีปัญญา",
        my: "ဉာဏ်အရှိဆုံးသော",
        km: "ឆ្លាតវៃ",
      },
      furigana: [
        {
          rb: "知的",
          rt: "ちてき",
        },
      ],
      kanjiInfo: [
        {
          char: "知",
          on: ["チ"],
          kun: ["し.る", "し.らせる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "的",
          on: ["テキ"],
          kun: ["まと"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1973,
      kanji: "重宝",
      reading: "ちょうほう",
      meanings: {
        ja: "重宝（便利な）",
        en: "useful; convenient",
        zh: "方便；有用",
        tw: "方便；有用",
        ko: "편리하다; 유용하다",
        vi: "tiện lợi; hữu ích",
        th: "สะดวก; มีประโยชน์",
        my: "အသုံးဝင်သော",
        km: "មានប្រយោជន៍",
      },
      furigana: [
        {
          rb: "重宝",
          rt: "ちょうほう",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "宝",
          on: ["ホウ"],
          kun: ["たから"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1974,
      kanji: "著名",
      reading: "ちょめい",
      meanings: {
        ja: "著名（有名な）",
        en: "famous; well-known",
        zh: "著名",
        tw: "著名",
        ko: "유명한",
        vi: "nổi tiếng",
        th: "มีชื่อเสียง",
        my: "အဆင့်မြင့်ကျော်ကြားသော",
        km: "ល្បីល្បាញ",
      },
      furigana: [
        {
          rb: "著名",
          rt: "ちょめい",
        },
      ],
      kanjiInfo: [
        {
          char: "著",
          on: ["チョ", "チャク"],
          kun: ["あらわ.す", "いちじる.しい"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1975,
      kanji: "通常",
      reading: "つうじょう",
      meanings: {
        ja: "通常（ふつうの）",
        en: "usual; normal",
        zh: "通常",
        tw: "通常",
        ko: "보통의",
        vi: "thông thường",
        th: "ปกติ",
        my: "ပုံမှန်သော",
        km: "ធម្មតា",
      },
      furigana: [
        {
          rb: "通常",
          rt: "つうじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "常",
          on: ["ジョウ"],
          kun: ["つね", "とこ-"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1976,
      kanji: "痛切",
      reading: "つうせつ",
      meanings: {
        ja: "痛切（強く感じる）",
        en: "keen; heartfelt",
        zh: "深切；强烈",
        tw: "深切；強烈",
        ko: "절실한",
        vi: "sâu sắc",
        th: "เจ็บปวดใจ",
        my: "ခံစားချက်ပြင်းပြင်းထန်ထန်ရှိသော",
        km: "យ៉ាងជ្រាលជ្រៅ",
      },
      furigana: [
        {
          rb: "痛切",
          rt: "つうせつ",
        },
      ],
      kanjiInfo: [
        {
          char: "痛",
          on: ["ツウ"],
          kun: ["いた.い", "いた.む", "いた.ましい", "いた.める"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1977,
      kanji: "手軽",
      reading: "てがる",
      meanings: {
        ja: "手軽（簡単な）",
        en: "easy; simple",
        zh: "简单；方便",
        tw: "簡單；方便",
        ko: "간편하다",
        vi: "dễ dàng; tiện lợi",
        th: "ง่าย; สะดวก",
        my: "လွယ်ကူသော",
        km: "ងាយស្រួល",
      },
      furigana: [
        {
          rb: "手軽",
          rt: "てがる",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "軽",
          on: ["ケイ", "キョウ", "キン"],
          kun: ["かる.い", "かろ.やか", "かろ.んじる"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1978,
      kanji: "適宜",
      reading: "てきぎ",
      meanings: {
        ja: "適宜（ちょうどよい）",
        en: "suitable; appropriate",
        zh: "适当",
        tw: "適當",
        ko: "적절하다",
        vi: "phù hợp",
        th: "เหมาะสม",
        my: "သင့်တော်သော",
        km: "សមរម្យ",
      },
      furigana: [
        {
          rb: "適宜",
          rt: "てきぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "適",
          on: ["テキ"],
          kun: ["かな.う"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "宜",
          on: ["ギ"],
          kun: ["よろ.しい", "よろ.しく"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1979,
      kanji: "手近",
      reading: "てぢか",
      meanings: {
        ja: "手近（身近な）",
        en: "near; familiar",
        zh: "手边的",
        tw: "手邊的",
        ko: "가까운",
        vi: "gần; quen thuộc",
        th: "ใกล้ตัว",
        my: "နီးစပ်သော",
        km: "នៅជិត",
      },
      furigana: [
        {
          rb: "手近",
          rt: "てぢか",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "近",
          on: ["キン", "コン"],
          kun: ["ちか.い"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1980,
      kanji: "露骨",
      reading: "ろこつ",
      meanings: {
        ja: "露骨（はっきり見える）",
        en: "blunt; outspoken",
        zh: "露骨；直率",
        tw: "露骨；直率",
        ko: "노골적인",
        vi: "thẳng thắn",
        th: "พูดตรง; เปิดเผย",
        my: "ပြောသွားပြောလာဖြစ်သော",
        km: "ត្រង់ត្រង់",
      },
      furigana: [
        {
          rb: "露骨",
          rt: "ろこつ",
        },
      ],
      kanjiInfo: [
        {
          char: "露",
          on: ["ロ", "ロウ"],
          kun: ["つゆ"],
          strokes: 21,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "骨",
          on: ["コツ"],
          kun: ["ほね"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1981,
      kanji: "ロマンチック",
      reading: "ロマンチック",
      meanings: {
        ja: "ロマンチック（愛情のある）",
        en: "romantic",
        zh: "浪漫的",
        tw: "浪漫的",
        ko: "로맨틱한",
        vi: "lãng mạn",
        th: "โรแมนติก",
        my: "စိတ်အနွေးထွေးသော",
        km: "រ៉ូមែនទិច",
      },
      furigana: [
        {
          rb: "ロマンチック",
          rt: "ロマンチック",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1982,
      kanji: "シック",
      reading: "シック",
      meanings: {
        ja: "シック（上品な）",
        en: "chic; stylish",
        zh: "雅致；时髦",
        tw: "雅緻；時髦",
        ko: "세련된",
        vi: "thanh lịch",
        th: "มีสไตล์; เรียบหรู",
        my: "ဖက်ရှင်ကျသော",
        km: "ទាន់សម័យ",
      },
      furigana: [
        {
          rb: "シック",
          rt: "シック",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1983,
      kanji: "質素",
      reading: "しっそ",
      meanings: {
        ja: "質素（簡素な）",
        en: "simple; frugal",
        zh: "朴素；节俭",
        tw: "樸素；節儉",
        ko: "소박한; 검소한",
        vi: "giản dị; tiết kiệm",
        th: "เรียบง่าย; ประหยัด",
        my: "ရိုးရိုးသပ်သပ်ဖြစ်သော",
        km: "សាមញ្ញ; សន្សំសំចៃ",
      },
      furigana: [
        {
          rb: "質素",
          rt: "しっそ",
        },
      ],
      kanjiInfo: [
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1984,
      kanji: "淑やか",
      reading: "しとやか",
      meanings: {
        ja: "淑やか（上品で静か）",
        en: "graceful; gentle",
        zh: "端庄；文雅",
        tw: "端莊；文雅",
        ko: "단아한; 얌전한",
        vi: "duyên dáng; nhã nhặn",
        th: "อ่อนหวาน; สุภาพ",
        my: "သိမ်မွေ့သော",
        km: "សោភា; សុភាពរាបសា",
      },
      furigana: [
        {
          rb: "淑やか",
          rt: "しとやか",
        },
      ],
      kanjiInfo: [
        {
          char: "淑",
          on: ["シュク"],
          kun: ["しと.やか"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1985,
      kanji: "しなやか",
      reading: "しなやか",
      meanings: {
        ja: "しなやか（柔らかい）",
        en: "supple; flexible",
        zh: "柔软；灵活",
        tw: "柔軟；靈活",
        ko: "유연한",
        vi: "mềm mại; linh hoạt",
        th: "อ่อนนุ่ม; ยืดหยุ่น",
        my: "နူးညံ့လှပသော",
        km: "ទន់ភ្លន់",
      },
      furigana: [
        {
          rb: "しなやか",
          rt: "しなやか",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1986,
      kanji: "若干",
      reading: "じゃっかん",
      meanings: {
        ja: "若干（少し）",
        en: "some; a few",
        zh: "若干；一些",
        tw: "若干；一些",
        ko: "약간",
        vi: "một vài",
        th: "บางส่วน",
        my: "အနည်းငယ်",
        km: "បន្តិច",
      },
      furigana: [
        {
          rb: "若干",
          rt: "じゃっかん",
        },
      ],
      kanjiInfo: [
        {
          char: "若",
          on: ["ジャク", "ニャク", "ニャ"],
          kun: [
            "わか.い",
            "わか-",
            "も.しくわ",
            "も.し",
            "も.しくは",
            "ごと.し",
          ],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "干",
          on: ["カン"],
          kun: ["ほ.す", "ほ.し-", "-ぼ.し", "ひ.る"],
          strokes: 3,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1987,
      kanji: "ジャンボ",
      reading: "ジャンボ",
      meanings: {
        ja: "ジャンボ（巨大な）",
        en: "jumbo; huge",
        zh: "巨大的",
        tw: "巨大的",
        ko: "거대한",
        vi: "khổng lồ",
        th: "ใหญ่โต",
        my: "အရွယ်အစားကြီးသော",
        km: "ធំធេង",
      },
      furigana: [
        {
          rb: "ジャンボ",
          rt: "ジャンボ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1988,
      kanji: "柔軟",
      reading: "じゅうなん",
      meanings: {
        ja: "柔軟（柔らかい）",
        en: "flexible; adaptable",
        zh: "柔软；灵活",
        tw: "柔軟；靈活",
        ko: "유연한",
        vi: "linh hoạt",
        th: "ยืดหยุ่น",
        my: "အလျင်အမြန်လိုက်လျောနိုင်သော",
        km: "បត់បែនបាន",
      },
      furigana: [
        {
          rb: "柔軟",
          rt: "じゅうなん",
        },
      ],
      kanjiInfo: [
        {
          char: "柔",
          on: ["ジュウ", "ニュウ"],
          kun: ["やわ.らか", "やわ.らかい", "やわ", "やわ.ら"],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "軟",
          on: ["ナン"],
          kun: ["やわ.らか", "やわ.らかい"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1989,
      kanji: "種々",
      reading: "しゅじゅ",
      meanings: {
        ja: "種々（いろいろな）",
        en: "various; diverse",
        zh: "各种各样",
        tw: "各種各樣",
        ko: "여러 가지",
        vi: "nhiều loại",
        th: "หลายชนิด",
        my: "အမျိုးအစားစုံလင်သော",
        km: "ច្រើនប្រភេទ",
      },
      furigana: [
        {
          rb: "種々",
          rt: "しゅじゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "種",
          on: ["シュ"],
          kun: ["たね", "-ぐさ"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1990,
      kanji: "敏感",
      reading: "びんかん",
      meanings: {
        ja: "敏感（感じやすい）",
        en: "sensitive",
        zh: "敏感",
        tw: "敏感",
        ko: "민감하다",
        vi: "nhạy cảm",
        th: "ไวต่อสิ่งเร้า",
        my: "ခံစားလွယ်သော",
        km: "ប្រតិកម្មលឿន",
      },
      furigana: [
        {
          rb: "敏感",
          rt: "びんかん",
        },
      ],
      kanjiInfo: [
        {
          char: "敏",
          on: ["ビン"],
          kun: ["さとい"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "感",
          on: ["カン"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1991,
      kanji: "貧弱",
      reading: "ひんじゃく",
      meanings: {
        ja: "貧弱（弱々しい）",
        en: "poor; weak",
        zh: "贫弱",
        tw: "貧弱",
        ko: "빈약하다",
        vi: "yếu; nghèo nàn",
        th: "อ่อนแอ",
        my: "အားနည်းသော",
        km: "ខ្សោយ",
      },
      furigana: [
        {
          rb: "貧弱",
          rt: "ひんじゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "貧",
          on: ["ヒン", "ビン"],
          kun: ["まず.しい"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "弱",
          on: ["ジャク"],
          kun: ["よわ.い", "よわ.る", "よわ.まる", "よわ.める"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1992,
      kanji: "頻繁",
      reading: "ひんぱん",
      meanings: {
        ja: "頻繁（しばしば）",
        en: "frequent",
        zh: "频繁",
        tw: "頻繁",
        ko: "빈번하다",
        vi: "thường xuyên",
        th: "บ่อยครั้ง",
        my: "မကြာခဏ",
        km: "ញឹកញាប់",
      },
      furigana: [
        {
          rb: "頻繁",
          rt: "ひんぱん",
        },
      ],
      kanjiInfo: [
        {
          char: "頻",
          on: ["ヒン"],
          kun: ["しき.りに"],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "繁",
          on: ["ハン"],
          kun: ["しげ.る", "しげ.く"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1993,
      kanji: "貧乏",
      reading: "びんぼう",
      meanings: {
        ja: "貧乏（お金がない）",
        en: "poor; poverty-stricken",
        zh: "贫穷",
        tw: "貧窮",
        ko: "가난하다",
        vi: "nghèo",
        th: "ยากจน",
        my: "ဆင်းရဲသော",
        km: "ក្រីក្រ",
      },
      furigana: [
        {
          rb: "貧乏",
          rt: "びんぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "貧",
          on: ["ヒン", "ビン"],
          kun: ["まず.しい"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "乏",
          on: ["ボウ"],
          kun: ["とぼ.しい", "とも.しい"],
          strokes: 4,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1994,
      kanji: "不意",
      reading: "ふい",
      meanings: {
        ja: "不意（突然の）",
        en: "sudden; unexpected",
        zh: "突然",
        tw: "突然",
        ko: "뜻밖의",
        vi: "đột nhiên",
        th: "กะทันหัน",
        my: "မမျှော်လင့်ပဲဖြစ်သော",
        km: "ភ្លាមៗ",
      },
      furigana: [
        {
          rb: "不意",
          rt: "ふい",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1995,
      kanji: "不可欠",
      reading: "ふかけつ",
      meanings: {
        ja: "不可欠（必要な）",
        en: "indispensable; essential",
        zh: "不可缺少",
        tw: "不可缺少",
        ko: "필수적인",
        vi: "thiết yếu",
        th: "จำเป็น",
        my: "အရေးကြီးသော",
        km: "សំខាន់ណាស់",
      },
      furigana: [
        {
          rb: "不可欠",
          rt: "ふかけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "可",
          on: ["カ", "コク"],
          kun: ["-べ.き", "-べ.し"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "欠",
          on: ["ケツ", "ケン"],
          kun: ["か.ける", "か.く"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1996,
      kanji: "ぶかぶか",
      reading: "ぶかぶか",
      meanings: {
        ja: "ぶかぶか（服が大きい）",
        en: "too large (clothing)",
        zh: "宽松（衣服）",
        tw: "寬鬆（衣服）",
        ko: "헐렁한 (옷)",
        vi: "rộng (quần áo)",
        th: "หลวม (เสื้อผ้า)",
        my: "အဝတ်လွှတ်သော",
        km: "ធំល្មម",
      },
      furigana: [
        {
          rb: "ぶかぶか",
          rt: "ぶかぶか",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1997,
      kanji: "不吉",
      reading: "ふきつ",
      meanings: {
        ja: "不吉（縁起が悪い）",
        en: "ominous; unlucky",
        zh: "不祥；不吉利",
        tw: "不祥；不吉利",
        ko: "불길하다",
        vi: "xui xẻo",
        th: "โชคร้าย",
        my: "ဆိုးရွားသော",
        km: "អាក្រក់",
      },
      furigana: [
        {
          rb: "不吉",
          rt: "ふきつ",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "吉",
          on: ["キチ", "キツ"],
          kun: ["よし"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1998,
      kanji: "不順",
      reading: "ふじゅん",
      meanings: {
        ja: "不順（順調でない）",
        en: "irregular; unseasonable",
        zh: "不顺",
        tw: "不順",
        ko: "불순하다",
        vi: "không thuận",
        th: "ไม่ราบรื่น",
        my: "မမှန်ကန်သော",
        km: "មិនប្រក្រតី",
      },
      furigana: [
        {
          rb: "不順",
          rt: "ふじゅん",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "順",
          on: ["ジュン"],
          kun: [],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1999,
      kanji: "不当",
      reading: "ふとう",
      meanings: {
        ja: "不当（正しくない）",
        en: "unfair; improper",
        zh: "不当；不公正",
        tw: "不當；不公正",
        ko: "부당하다",
        vi: "bất công",
        th: "ไม่ยุติธรรม",
        my: "မမှန်သော",
        km: "មិនត្រឹមត្រូវ",
      },
      furigana: [
        {
          rb: "不当",
          rt: "ふとう",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2000,
      kanji: "無難",
      reading: "ぶなん",
      meanings: {
        ja: "無難（安全な）",
        en: "safe; acceptable",
        zh: "安全；無難",
        tw: "安全；無難",
        ko: "무난하다",
        vi: "an toàn",
        th: "ปลอดภัย",
        my: "လုံခြုံသော",
        km: "សុវត្ថិភាព",
      },
      furigana: [
        {
          rb: "無難",
          rt: "ぶなん",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "難",
          on: ["ナン"],
          kun: [
            "かた.い",
            "-がた.い",
            "むずか.しい",
            "むづか.しい",
            "むつか.しい",
            "-にく.い",
          ],
          strokes: 18,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2001,
      kanji: "普遍",
      reading: "ふへん",
      meanings: {
        ja: "普遍（広く通じる）",
        en: "universal; general",
        zh: "普遍",
        tw: "普遍",
        ko: "보편적인",
        vi: "phổ biến",
        th: "ทั่วไป",
        my: "အများသုံးသော",
        km: "ទូទៅ",
      },
      furigana: [
        {
          rb: "普遍",
          rt: "ふへん",
        },
      ],
      kanjiInfo: [
        {
          char: "普",
          on: ["フ"],
          kun: ["あまね.く", "あまねし"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "遍",
          on: ["ヘン"],
          kun: ["あまね.く"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2002,
      kanji: "不明",
      reading: "ふめい",
      meanings: {
        ja: "不明（わからない）",
        en: "unclear; unknown",
        zh: "不明",
        tw: "不明",
        ko: "불명확하다",
        vi: "không rõ",
        th: "ไม่ชัดเจน",
        my: "မသိရသော",
        km: "មិនច្បាស់",
      },
      furigana: [
        {
          rb: "不明",
          rt: "ふめい",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2003,
      kanji: "不良",
      reading: "ふりょう",
      meanings: {
        ja: "不良（悪い）",
        en: "bad; poor",
        zh: "不良",
        tw: "不良",
        ko: "불량하다",
        vi: "xấu",
        th: "ไม่ดี",
        my: "မကောင်းသော",
        km: "អាក្រក់",
      },
      furigana: [
        {
          rb: "不良",
          rt: "ふりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "良",
          on: ["リョウ"],
          kun: ["よ.い", "-よ.い", "い.い", "-い.い"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2004,
      kanji: "ふんだん",
      reading: "ふんだん",
      meanings: {
        ja: "ふんだん（たくさん）",
        en: "plentiful; abundant",
        zh: "充足；丰富",
        tw: "充足；豐富",
        ko: "풍부하다",
        vi: "dồi dào",
        th: "มากมาย",
        my: "ကြွယ်ဝသော",
        km: "ច្រើន",
      },
      furigana: [
        {
          rb: "ふんだん",
          rt: "ふんだん",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2005,
      kanji: "平常",
      reading: "へいじょう",
      meanings: {
        ja: "平常（いつもどおり）",
        en: "normal; usual",
        zh: "平常",
        tw: "平常",
        ko: "평상시",
        vi: "bình thường",
        th: "ปกติ",
        my: "ပုံမှန်",
        km: "ធម្មតា",
      },
      furigana: [
        {
          rb: "平常",
          rt: "へいじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "平",
          on: ["ヘイ", "ビョウ", "ヒョウ"],
          kun: ["たい.ら", "たい.らげる", "ひら"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "常",
          on: ["ジョウ"],
          kun: ["つね", "とこ-"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2006,
      kanji: "ぺこぺこ",
      reading: "ぺこぺこ",
      meanings: {
        ja: "ぺこぺこ（お腹がすく）",
        en: "very hungry",
        zh: "饿扁了",
        tw: "餓扁了",
        ko: "배고프다",
        vi: "đói bụng",
        th: "หิวมาก",
        my: "ဆာလောင်",
        km: "ឃ្លានខ្លាំង",
      },
      furigana: [
        {
          rb: "ぺこぺこ",
          rt: "ぺこぺこ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2007,
      kanji: "ベスト",
      reading: "ベスト",
      meanings: {
        ja: "ベスト（最も良い）",
        en: "best; optimal",
        zh: "最好",
        tw: "最好",
        ko: "최고의",
        vi: "tốt nhất",
        th: "ดีที่สุด",
        my: "အကောင်းဆုံး",
        km: "ល្អបំផុត",
      },
      furigana: [
        {
          rb: "ベスト",
          rt: "ベスト",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2008,
      kanji: "真ん前",
      reading: "まんまえ",
      meanings: {
        ja: "真ん前（正面）",
        en: "right in front",
        zh: "正前方",
        tw: "正前方",
        ko: "정면",
        vi: "ngay trước mặt",
        th: "ตรงหน้า",
        my: "ရှေ့တန်းမှာတယ်",
        km: "នៅពីមុខ",
      },
      furigana: [
        {
          rb: "真ん前",
          rt: "まんまえ",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2009,
      kanji: "未開",
      reading: "みかい",
      meanings: {
        ja: "未開（文明の発達していない）",
        en: "uncivilized; undeveloped",
        zh: "未开化",
        tw: "未開化",
        ko: "미개하다",
        vi: "chưa phát triển",
        th: "ยังไม่เจริญ",
        my: "ဖွံ့ဖြိုးမှုနည်းသော",
        km: "មិនទាន់អភិវឌ្ឍ",
      },
      furigana: [
        {
          rb: "未開",
          rt: "みかい",
        },
      ],
      kanjiInfo: [
        {
          char: "未",
          on: ["ミ", "ビ"],
          kun: ["いま.だ", "ま.だ", "ひつじ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
