export const n1part54 = {
  Lesson54: [
    {
      id: 2588,
      kanji: "きまりわるい",
      reading: "きまりわるい",
      meanings: {
        ja: "きまり悪い／恥ずかしい・気まずい",
        en: "feeling awkward; embarrassed",
        zh: "尴尬；不好意思",
        tw: "尷尬；不好意思",
        ko: "쑥스럽다; 어색하다",
        vi: "ngượng ngùng; khó xử",
        th: "อาย; รู้สึกกระดาก",
        my: "အရှက်ပေါက်; မအဆင်ပြေ",
        km: "ខ្មាស់អៀន; អស់ស្បើយ",
      },
      furigana: [
        {
          rb: "きまりわるい",
          rt: "きまりわるい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2589,
      kanji: "強",
      reading: "きょう",
      meanings: {
        ja: "接尾辞：〜強／少し多い",
        en: "suffix: a little over (number)",
        zh: "后缀：～多一点",
        tw: "後綴：～多一點",
        ko: "접미사: 약간 넘는",
        vi: "hậu tố: hơn một chút",
        th: "ปัจฉัย: มากกว่าเล็กน้อย",
        my: "နောက်ဆက်: အနည်းငယ်ပို",
        km: "បច្ច័យបន្ត: បន្តិចលើស",
      },
      furigana: [
        {
          rb: "強",
          rt: "きょう",
        },
      ],
      kanjiInfo: [
        {
          char: "強",
          on: ["キョウ", "ゴウ"],
          kun: ["つよ.い", "つよ.まる", "つよ.める", "し.いる", "こわ.い"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2590,
      kanji: "～狂",
      reading: "～きょう",
      meanings: {
        ja: "接尾辞：〜狂／熱中する人",
        en: "suffix: mania; enthusiast",
        zh: "后缀：～狂（狂热者）",
        tw: "後綴：～狂（狂熱者）",
        ko: "접미사: ~광 (열성팬)",
        vi: "hậu tố: người cuồng; mê",
        th: "ปัจฉัย: คนคลั่งไคล้",
        my: "နောက်ဆက်: တော်တော်ဝင်ကျင်သူ",
        km: "បច្ច័យបន្ត: អ្នកស្រលាញ់ខ្លាំង",
      },
      furigana: [
        {
          rb: "～狂",
          rt: "～きょう",
        },
      ],
      kanjiInfo: [
        {
          char: "狂",
          on: ["キョウ"],
          kun: ["くる.う", "くる.おしい", "くるお.しい"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2591,
      kanji: "きらびやか",
      reading: "きらびやか",
      meanings: {
        ja: "きらびやか／華やかで美しい",
        en: "gorgeous; dazzling; ornate",
        zh: "华丽；灿烂",
        tw: "華麗；燦爛",
        ko: "화려한; 눈부신",
        vi: "lộng lẫy; rực rỡ",
        th: "หรูหรา; สวยงาม",
        my: "အလှတရားပြည့်ဝသော",
        km: "ស្រស់ស្អាត; ភ្លឺថ្លា",
      },
      furigana: [
        {
          rb: "きらびやか",
          rt: "きらびやか",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2592,
      kanji: "～きり",
      reading: "～きり",
      meanings: {
        ja: "接尾辞：〜きり／だけ・以来",
        en: "suffix: only; since",
        zh: "后缀：～仅；以来",
        tw: "後綴：～僅；以來",
        ko: "접미사: ~만; 이후로",
        vi: "hậu tố: chỉ; kể từ",
        th: "ปัจฉัย: เท่านั้น; ตั้งแต่",
        my: "နောက်ဆက်: သာ; စ၍",
        km: "បច្ច័យបន្ត: តែប៉ុណ្ណោះ; ចាប់តាំងពី",
      },
      furigana: [
        {
          rb: "～きり",
          rt: "～きり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2593,
      kanji: "くぐる",
      reading: "くぐる",
      meanings: {
        ja: "くぐる／潜る・通り抜ける",
        en: "to go through; to pass under",
        zh: "钻过；穿过",
        tw: "鑽過；穿過",
        ko: "통과하다; 빠져나가다",
        vi: "luồn qua; chui qua",
        th: "ลอดผ่าน; ผ่านเข้าไป",
        my: "ဖြတ်ကျော်သည်",
        km: "ឆ្លងកាត់; លោតចូល",
      },
      furigana: [
        {
          rb: "くぐる",
          rt: "くぐる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2594,
      kanji: "くじ (～をひく)",
      reading: "くじ (～をひく)",
      meanings: {
        ja: "くじ（を引く）／抽選をする",
        en: "to draw a lottery",
        zh: "抽签；抽奖",
        tw: "抽籤；抽獎",
        ko: "추첨하다",
        vi: "rút thăm; bốc thăm",
        th: "จับฉลาก",
        my: "ထီဆွဲသည်",
        km: "ចាប់ឆ្នោត",
      },
      furigana: [
        {
          rb: "くじ (～をひく)",
          rt: "くじ （～をひく）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2595,
      kanji: "くじびき",
      reading: "くじびき",
      meanings: {
        ja: "くじ引き／抽選",
        en: "lottery; draw",
        zh: "抽签；抽奖",
        tw: "抽籤；抽獎",
        ko: "추첨",
        vi: "rút thăm",
        th: "จับสลาก",
        my: "ထီစစ်ခြင်း",
        km: "ការចាប់ឆ្នោត",
      },
      furigana: [
        {
          rb: "くじびき",
          rt: "くじびき",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2596,
      kanji: "くすぐったい",
      reading: "くすぐったい",
      meanings: {
        ja: "くすぐったい／くすぐりに弱い",
        en: "ticklish; embarrassed",
        zh: "怕痒；害羞",
        tw: "怕癢；害羞",
        ko: "간지럽다; 부끄럽다",
        vi: "nhột; ngượng",
        th: "จั๊กจี้; เขิน",
        my: "ခပ်သိမ်းခြင်း",
        km: "រមួល; ខ្មាស់អៀន",
      },
      furigana: [
        {
          rb: "くすぐったい",
          rt: "くすぐったい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2597,
      kanji: "当～",
      reading: "とう～",
      meanings: {
        ja: "接頭辞：当〜／この・現在の",
        en: "prefix: this; current",
        zh: "前缀：当～（此）",
        tw: "前綴：當～（此）",
        ko: "접두사: 당~ (현재의)",
        vi: "tiền tố: hiện tại; này",
        th: "คำนำหน้า: นี้; ปัจจุบัน",
        my: "နာမဝိသေသန: ယခု",
        km: "បុព្វបទ: នេះ; បច្ចុប្បន្ន",
      },
      furigana: [
        {
          rb: "当～",
          rt: "とう～",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2598,
      kanji: "あくどい",
      reading: "あくどい",
      meanings: {
        ja: "あくどい／派手すぎる・悪質",
        en: "gaudy; malicious; vicious",
        zh: "过分华丽；恶毒",
        tw: "過分華麗；惡毒",
        ko: "지나치게 화려한; 악랄한",
        vi: "loè loẹt; độc ác",
        th: "ฉูดฉาดเกินไป; ชั่วร้าย",
        my: "အလွန်တောက်ပသော; ဆိုးရွားသော",
        km: "ខ្លាំងពេក; អាក្រក់",
      },
      furigana: [
        {
          rb: "あくどい",
          rt: "あくどい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2599,
      kanji: "あざ",
      reading: "あざ",
      meanings: {
        ja: "あざ／痣・青あざ",
        en: "bruise; birthmark",
        zh: "瘀伤；胎记",
        tw: "瘀傷；胎記",
        ko: "멍; 점",
        vi: "vết bầm; nốt ruồi",
        th: "รอยช้ำ; ปาน",
        my: "အသားနီ",
        km: "ស្នាម; ដេញ",
      },
      furigana: [
        {
          rb: "あざ",
          rt: "あざ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2600,
      kanji: "あせる (こえが～)",
      reading: "あせる (こえが～)",
      meanings: {
        ja: "あせる（声が〜）／褪せる・色が落ちる",
        en: "to fade (color or voice)",
        zh: "褪色；变淡",
        tw: "褪色；變淡",
        ko: "바래다",
        vi: "phai màu; mờ",
        th: "ซีดจาง",
        my: "အရောင်ကျွမ်းခြင်း",
        km: "ស្លេក; ខ្សោយ",
      },
      furigana: [
        {
          rb: "あせる (こえが～)",
          rt: "あせる （こえが～）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2601,
      kanji: "あつらえる",
      reading: "あつらえる",
      meanings: {
        ja: "あつらえる／注文して作る",
        en: "to order; to have made to order",
        zh: "订做；定制",
        tw: "訂做；定制",
        ko: "맞추다; 주문하다",
        vi: "đặt làm theo yêu cầu",
        th: "สั่งทำพิเศษ",
        my: "အကြိုမှာထားသည်",
        km: "បញ្ជាទិញជាក់លាក់",
      },
      furigana: [
        {
          rb: "あつらえる",
          rt: "あつらえる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2602,
      kanji: "～宛",
      reading: "～あて",
      meanings: {
        ja: "接尾辞：〜宛／宛先",
        en: "suffix: addressed to",
        zh: "后缀：～致；寄给",
        tw: "後綴：～致；寄給",
        ko: "접미사: ~앞",
        vi: "hậu tố: gửi đến",
        th: "ปัจฉัย: ถึง (ผู้รับ)",
        my: "နောက်ဆက်: သို့",
        km: "បច្ច័យបន្ត: ទៅកាន់",
      },
      furigana: [
        {
          rb: "～宛",
          rt: "～あて",
        },
      ],
      kanjiInfo: [
        {
          char: "宛",
          on: ["エン"],
          kun: ["あ.てる", "-あて", "-づつ", "あたか.も"],
          strokes: 8,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 2603,
      kanji: "ありのまま",
      reading: "ありのまま",
      meanings: {
        ja: "ありのまま／実際のまま",
        en: "as it is; the truth; reality",
        zh: "如实；真实",
        tw: "如實；真實",
        ko: "있는 그대로",
        vi: "đúng như thật",
        th: "ตามความเป็นจริง",
        my: "အဖြစ်အပျက်အတိုင်း",
        km: "តាមពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "ありのまま",
          rt: "ありのまま",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2604,
      kanji: "ありふれる",
      reading: "ありふれる",
      meanings: {
        ja: "ありふれる／どこにでもある",
        en: "to be common; to be ordinary",
        zh: "常见；平凡",
        tw: "常見；平凡",
        ko: "흔하다",
        vi: "phổ biến; tầm thường",
        th: "ธรรมดา; ทั่วไป",
        my: "တွေ့မြင်နည်း",
        km: "ធម្មតា; មានជាញឹកញាប់",
      },
      furigana: [
        {
          rb: "ありふれる",
          rt: "ありふれる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2605,
      kanji: "アルカリ",
      reading: "アルカリ",
      meanings: {
        ja: "アルカリ／アルカリ性物質",
        en: "alkali; alkaline",
        zh: "碱；碱性",
        tw: "鹼；鹼性",
        ko: "알칼리",
        vi: "kiềm",
        th: "ด่าง",
        my: "အယ်လ်ကာလိုင်း",
        km: "អាល់កាលី",
      },
      furigana: [
        {
          rb: "アルカリ",
          rt: "アルカリ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2606,
      kanji: "～合せ",
      reading: "～あわせ",
      meanings: {
        ja: "接尾辞：〜合せ／一緒にすること",
        en: "suffix: combination; matching",
        zh: "后缀：～结合；组合",
        tw: "後綴：～結合；組合",
        ko: "접미사: ~합치기",
        vi: "hậu tố: kết hợp",
        th: "ปัจฉัย: รวมกัน",
        my: "နောက်ဆက်: ပေါင်းစည်းမှု",
        km: "បច្ច័យបន្ត: បញ្ចូលគ្នា",
      },
      furigana: [
        {
          rb: "～合せ",
          rt: "～あわせ",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2607,
      kanji: "イェス",
      reading: "イェス",
      meanings: {
        ja: "イェス／はい・肯定",
        en: "yes",
        zh: "是的",
        tw: "是的",
        ko: "예; 응",
        vi: "vâng; có",
        th: "ใช่; ครับ/ค่ะ",
        my: "ဟုတ်ကဲ့",
        km: "បាទ/ចាស",
      },
      furigana: [
        {
          rb: "イェス",
          rt: "イェス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2608,
      kanji: "いかに",
      reading: "いかに",
      meanings: {
        ja: "いかに／どのように・どれほど",
        en: "how; in what way; how much",
        zh: "如何；多么",
        tw: "如何；多麼",
        ko: "어떻게; 얼마나",
        vi: "như thế nào; bao nhiêu",
        th: "อย่างไร; แค่ไหน",
        my: "ဘယ်လို; ဘယ်လောက်",
        km: "យ៉ាងដូចម្តេច; ប៉ុន្មាន",
      },
      furigana: [
        {
          rb: "いかに",
          rt: "いかに",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2609,
      kanji: "いかにも",
      reading: "いかにも",
      meanings: {
        ja: "いかにも／本当に・まさに",
        en: "indeed; really; truly",
        zh: "的确；确实",
        tw: "的確；確實",
        ko: "정말로; 참으로",
        vi: "quả thật; đúng là",
        th: "จริง ๆ; แท้จริง",
        my: "အမှန်တကယ်",
        km: "ពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "いかにも",
          rt: "いかにも",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2610,
      kanji: "活ける",
      reading: "いける",
      meanings: {
        ja: "活ける／（花を）生ける・生け花をする",
        en: "to arrange flowers",
        zh: "插花",
        tw: "插花",
        ko: "꽃꽂이하다",
        vi: "cắm hoa",
        th: "จัดดอกไม้",
        my: "ပန်းအံ့သည်",
        km: "រៀបផ្កា",
      },
      furigana: [
        {
          rb: "活ける",
          rt: "いける",
        },
      ],
      kanjiInfo: [
        {
          char: "活",
          on: ["カツ"],
          kun: ["い.きる", "い.かす", "い.ける"],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2611,
      kanji: "いじる",
      reading: "いじる",
      meanings: {
        ja: "いじる／触る・いじくる",
        en: "to touch; to fiddle with",
        zh: "摆弄；抚弄",
        tw: "擺弄；撫弄",
        ko: "만지작거리다",
        vi: "nghịch; chạm",
        th: "จับเล่น; แหย่",
        my: "လှန့်ပေါက်ခြင်း",
        km: "លេងនឹង; ប៉ះ",
      },
      furigana: [
        {
          rb: "いじる",
          rt: "いじる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2612,
      kanji: "いたって",
      reading: "いたって",
      meanings: {
        ja: "いたって／非常に・きわめて",
        en: "very; extremely",
        zh: "非常；极其",
        tw: "非常；極其",
        ko: "매우; 극히",
        vi: "rất; vô cùng",
        th: "อย่างมาก; สุด ๆ",
        my: "အလွန်အမင်း",
        km: "ខ្លាំងណាស់",
      },
      furigana: [
        {
          rb: "いたって",
          rt: "いたって",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2613,
      kanji: "～署",
      reading: "～しょ",
      meanings: {
        ja: "接尾辞：〜署／〜オフィス・〜局",
        en: "suffix: office; bureau",
        zh: "后缀：～署（机关／局）",
        tw: "後綴：～署（機關／局）",
        ko: "접미사: ~서(사무소·국)",
        vi: "hậu tố: sở; cục; văn phòng",
        th: "ปัจฉัย: สำนักงาน ~; กรม ~",
        my: "နောက်ဆက်：~署 (ရုံး/ဌာန)",
        km: "បច្ច័យបន្ត៖ ~署 ការិយាល័យ/ក្រសួង",
      },
      furigana: [
        {
          rb: "～署",
          rt: "～しょ",
        },
      ],
      kanjiInfo: [
        {
          char: "署",
          on: ["ショ"],
          kun: [],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2614,
      kanji: "～症",
      reading: "～しょう",
      meanings: {
        ja: "接尾辞：〜症／病気・症候群",
        en: "suffix: disease; syndrome",
        zh: "后缀：～症（疾病/综合征）",
        tw: "後綴：～症（疾病/症候群）",
        ko: "접미사: ~증(질환)",
        vi: "hậu tố: chứng bệnh; hội chứng",
        th: "ปัจฉัย: โรค ~; กลุ่มอาการ ~",
        my: "နောက်ဆက်：~症 (ရောဂါ)",
        km: "បច្ច័យបន្ត៖ ~ជំងឺ",
      },
      furigana: [
        {
          rb: "～症",
          rt: "～しょう",
        },
      ],
      kanjiInfo: [
        {
          char: "症",
          on: ["ショウ"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2615,
      kanji: "～証",
      reading: "～しょう",
      meanings: {
        ja: "接尾辞：〜証／証明書・〜カード",
        en: "suffix: certificate; proof",
        zh: "后缀：～证（证明）",
        tw: "後綴：～證（證明）",
        ko: "접미사: ~증(증명서)",
        vi: "hậu tố: giấy chứng; chứng nhận",
        th: "ปัจฉัย: ใบรับรอง ~",
        my: "နောက်ဆက်：~証 (မှတ်တမ်းလက်မှတ်)",
        km: "បច្ច័យបន្ត៖ ~វិញ្ញាបនបត្រ",
      },
      furigana: [
        {
          rb: "～証",
          rt: "～しょう",
        },
      ],
      kanjiInfo: [
        {
          char: "証",
          on: ["ショウ"],
          kun: ["あかし"],
          strokes: 12,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2616,
      kanji: "～嬢",
      reading: "～じょう",
      meanings: {
        ja: "接尾辞：〜嬢／お嬢さん・Miss",
        en: "suffix: Miss; young lady",
        zh: "后缀：～嬢（小姐）",
        tw: "後綴：～嬢（小姐）",
        ko: "접미사: ~양",
        vi: "hậu tố: tiểu thư; cô ~",
        th: "ปัจฉัย: คุณหนู ~; มิส",
        my: "နောက်ဆက်：~嬢 (မိန်းကလေး)",
        km: "បច្ច័យបន្ត៖ កញ្ញា ~",
      },
      furigana: [
        {
          rb: "～嬢",
          rt: "～じょう",
        },
      ],
      kanjiInfo: [
        {
          char: "嬢",
          on: ["ジョウ"],
          kun: ["むすめ"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2617,
      kanji: "～心",
      reading: "～しん",
      meanings: {
        ja: "接尾辞：〜心／心・気持ち・志向",
        en: "suffix: mindset; -mindedness",
        zh: "后缀：～心（心态/…之心）",
        tw: "後綴：～心（心態/…之心）",
        ko: "접미사: ~심",
        vi: "hậu tố: lòng; tinh thần",
        th: "ปัจฉัย: ใจ/ความรู้สึก ~",
        my: "နောက်ဆက်：~心 (စိတ်/မြင်ကွင်း)",
        km: "បច្ច័យបន្ត៖ ~ចិត្ត",
      },
      furigana: [
        {
          rb: "～心",
          rt: "～しん",
        },
      ],
      kanjiInfo: [
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2618,
      kanji: "すがすがしい",
      reading: "すがすがしい",
      meanings: {
        ja: "清々しい／さわやかで気持ちよい",
        en: "refreshing; bracing",
        zh: "清爽；神清气爽",
        tw: "清爽；神清氣爽",
        ko: "상쾌하다; 산뜻하다",
        vi: "sảng khoái; trong lành",
        th: "สดชื่น; โล่งสบาย",
        my: "လန်းဆန်းပြီးစိတ်သက်သာ",
        km: "ស្រស់ស្រាយ; ធូរស្បើយ",
      },
      furigana: [
        {
          rb: "すがすがしい",
          rt: "すがすがしい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2619,
      kanji: "すくう (みずを～)",
      reading: "すくう (みずを～)",
      meanings: {
        ja: "掬う：水をすくう／汲み取る",
        en: "to scoop (up) water",
        zh: "舀起（水）",
        tw: "舀起（水）",
        ko: "물 등을 떠올리다",
        vi: "múc (nước) lên",
        th: "ตักน้ำขึ้น",
        my: "ရေကို စုဆုံး/ခွီထိုးယူ",
        km: "ចាក់ទឹកឡើង; យុទ្ទន្ត",
      },
      furigana: [
        {
          rb: "すくう (みずを～)",
          rt: "すくう （みずを～）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2620,
      kanji: "ずぶぬれ",
      reading: "ずぶぬれ",
      meanings: {
        ja: "ずぶ濡れ／全身びしょ濡れ",
        en: "soaked; drenched",
        zh: "全身湿透",
        tw: "全身溼透",
        ko: "흠뻑 젖음",
        vi: "ướt sũng",
        th: "เปียกโชก",
        my: "စိုထိုင်းလျှံ",
        km: "សើមជ្រាបទឹក",
      },
      furigana: [
        {
          rb: "ずぶぬれ",
          rt: "ずぶぬれ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2621,
      kanji: "すみやか",
      reading: "すみやか",
      meanings: {
        ja: "速やか／迅速な・遅滞のない",
        en: "prompt; swift; expeditious",
        zh: "迅速；及时",
        tw: "迅速；及時",
        ko: "신속한; 지체 없는",
        vi: "nhanh chóng; kịp thời",
        th: "รวดเร็ว; ทันที",
        my: "လျင်မြန်; နှောင့်နှေးမရှိ",
        km: "រហ័ស; គ្មានពន្យារ",
      },
      furigana: [
        {
          rb: "すみやか",
          rt: "すみやか",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2622,
      kanji: "すれちがい",
      reading: "すれちがい",
      meanings: {
        ja: "すれ違い／行き違い・食い違い",
        en: "passing by; a miss; mismatch",
        zh: "擦肩而过；误会",
        tw: "擦肩而過；誤會",
        ko: "스쳐 지나감; 엇갈림",
        vi: "lướt qua; lạc nhịp; hiểu lầm",
        th: "สวนทางกัน; คลาดกัน",
        my: "擦れ違い; အမြင်ပေါင်းမတော်",
        km: "ឆ្លងកាត់គ្នា; ខុសគ្នា",
      },
      furigana: [
        {
          rb: "すれちがい",
          rt: "すれちがい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2623,
      kanji: "整然",
      reading: "せいぜん",
      meanings: {
        ja: "整然／秩序正しい・きちんと",
        en: "orderly; in good order",
        zh: "井然有序",
        tw: "井然有序",
        ko: "정연함; 질서정연",
        vi: "ngăn nắp; có trật tự",
        th: "เป็นระเบียบเรียบร้อย",
        my: "အစီအစဉ်ပြေ",
        km: "មានរបៀបរៀបរយ",
      },
      furigana: [
        {
          rb: "整然",
          rt: "せいぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "整",
          on: ["セイ"],
          kun: ["ととの.える", "ととの.う"],
          strokes: 16,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "然",
          on: ["ゼン", "ネン"],
          kun: ["しか", "しか.り", "しか.し", "さ"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2624,
      kanji: "そこら",
      reading: "そこら",
      meanings: {
        ja: "そこら／そのあたり・そこらへん",
        en: "around there; nearby; those",
        zh: "那一带；附近",
        tw: "那一帶；附近",
        ko: "그 근처; 그 정도",
        vi: "quanh đó; vùng đó",
        th: "แถวนั้น; บริเวณนั้น",
        my: "အဲဒီနေရာလည်ပတ်",
        km: "តំបន់នោះ; ចំងាយនោះ",
      },
      furigana: [
        {
          rb: "そこら",
          rt: "そこら",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2625,
      kanji: "そらす",
      reading: "そらす",
      meanings: {
        ja: "逸らす／そむける・（話題を）そらす",
        en: "to avert; to turn aside; to divert",
        zh: "转移；避开",
        tw: "轉移；避開",
        ko: "돌리다; 피하다",
        vi: "tránh; lái (chuyện)",
        th: "บ่ายเบี่ยง; หันเห",
        my: "ရှောင်ရှားဖယ်ရွား",
        km: "បង្វែរ; បញ្ចៀស",
      },
      furigana: [
        {
          rb: "そらす",
          rt: "そらす",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2626,
      kanji: "そり (～にのる)",
      reading: "そり (～にのる)",
      meanings: {
        ja: "そり（に乗る）／雪ぞり",
        en: "sled; to ride a sled",
        zh: "雪橇；乘雪橇",
        tw: "雪橇；乘雪橇",
        ko: "썰매; 썰매를 타다",
        vi: "xe trượt tuyết; đi xe trượt",
        th: "เลื่อนหิมะ; นั่งเลื่อน",
        my: "စက်တင် (စပ်ပြိုင်) စီးသည်",
        km: "ឡានរអិលលើព្រិល; ជិះឡានរអិល",
      },
      furigana: [
        {
          rb: "そり (～にのる)",
          rt: "そり （～にのる）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2627,
      kanji: "それゆえ",
      reading: "それゆえ",
      meanings: {
        ja: "それ故／だから・ゆえに",
        en: "therefore; for that reason",
        zh: "因此；所以",
        tw: "因此；所以",
        ko: "그러므로; 고로",
        vi: "vì thế; cho nên",
        th: "ดังนั้น; เพราะฉะนั้น",
        my: "ထို့ကြောင့်",
        km: "ដូច្នេះហើយ",
      },
      furigana: [
        {
          rb: "それゆえ",
          rt: "それゆえ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2628,
      kanji: "たくましい",
      reading: "たくましい",
      meanings: {
        ja: "たくましい／逞しい・力強い",
        en: "robust; strong; resilient",
        zh: "强健；刚强",
        tw: "強健；剛強",
        ko: "씩씩한; 탄탄한",
        vi: "rắn rỏi; cường tráng",
        th: "แข็งแรง; ทนทาน",
        my: "အားကောင်းတယ်; စိုက်ထူ",
        km: "រឹងមាំ; ខ្លាំងក្លា",
      },
      furigana: [
        {
          rb: "たくましい",
          rt: "たくましい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2629,
      kanji: "だったら",
      reading: "だったら",
      meanings: {
        ja: "だったら／それなら・もしそうなら",
        en: "if so; in that case",
        zh: "如果那样；既然如此",
        tw: "如果那樣；既然如此",
        ko: "그렇다면; 그러면",
        vi: "nếu vậy; trong trường hợp đó",
        th: "ถ้าอย่างนั้น",
        my: "အဲဒါဆိုရင်",
        km: "បើដូច្នោះទេ",
      },
      furigana: [
        {
          rb: "だったら",
          rt: "だったら",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2630,
      kanji: "だと",
      reading: "だと",
      meanings: {
        ja: "だと／『〜だと』の引用・断定（口語）",
        en: "quotative/assertive '...da to'; if it's (said) that ...",
        zh: "口语引用「…だと」；若说…",
        tw: "口語引用「…だと」；若說…",
        ko: "구어 인용 '~다고'; '~라면'",
        vi: "dạng trích dẫn '...da to'; nếu (nói) rằng",
        th: "รูปอ้างคำพูด '...ว่า'",
        my: "စကားပြောအနေဖြင့် '...တဲ့' အဓိပ္ပာယ်",
        km: "សំណួលពាក្យបណ្ដុំ '...ដែរ' / បើថា",
      },
      furigana: [
        {
          rb: "だと",
          rt: "だと",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2631,
      kanji: "たやすい",
      reading: "たやすい",
      meanings: {
        ja: "たやすい／容易だ・簡単だ",
        en: "easy; simple; effortless",
        zh: "容易；简单",
        tw: "容易；簡單",
        ko: "쉽다; 용이하다",
        vi: "dễ dàng; đơn giản",
        th: "ง่ายดาย",
        my: "လွယ်ကူ",
        km: "ងាយស្រួល",
      },
      furigana: [
        {
          rb: "たやすい",
          rt: "たやすい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2632,
      kanji: "だるい",
      reading: "だるい",
      meanings: {
        ja: "だるい／体が重く元気がない",
        en: "sluggish; weary; listless",
        zh: "疲乏；无力",
        tw: "疲乏；無力",
        ko: "나른하다; 축 늘어지다",
        vi: "mệt mỏi; uể oải",
        th: "อ่อนเพลีย; เหนื่อยล้า",
        my: "ပင်ပန်းနွမ်းနယ်",
        km: "អស់កម្លាំង; សរសាយ",
      },
      furigana: [
        {
          rb: "だるい",
          rt: "だるい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2633,
      kanji: "畜生",
      reading: "ちくしょう",
      meanings: {
        ja: "畜生！（感動詞）／ちくしょう",
        en: "damn it! (interjection)",
        zh: "可恶！",
        tw: "可惡！",
        ko: "젠장!",
        vi: "chết tiệt!",
        th: "บ้าจริง!",
        my: "အိုးမရေ!",
        km: "អសំណាង! ឬ ចុះឲ្យ!",
      },
      furigana: [
        {
          rb: "畜生",
          rt: "ちくしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "畜",
          on: ["チク"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2634,
      kanji: "～著",
      reading: "～ちょ",
      meanings: {
        ja: "接尾辞：〜著／著者・執筆者",
        en: "suffix: author; written by",
        zh: "后缀：～著（作者）",
        tw: "後綴：～著（作者）",
        ko: "접미사: ~저(저자)",
        vi: "hậu tố: tác giả",
        th: "ปัจฉัย: ผู้แต่ง ~",
        my: "နောက်ဆက်：~著 (ရေးသူ)",
        km: "បច្ច័យបន្ត៖ អ្នកនិពន្ធ ~",
      },
      furigana: [
        {
          rb: "～著",
          rt: "～ちょ",
        },
      ],
      kanjiInfo: [
        {
          char: "著",
          on: ["チョ", "チャク"],
          kun: ["あらわ.す", "いちじる.しい"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2635,
      kanji: "超",
      reading: "ちょう",
      meanings: {
        ja: "接頭辞：超〜／スーパー・非常に",
        en: "prefix: super-; ultra-",
        zh: "前缀：超～（超级）",
        tw: "前綴：超～（超級）",
        ko: "접두사: 초~; 매우",
        vi: "tiền tố: siêu-; cực kỳ",
        th: "คำนำหน้า: ซูเปอร์; อย่างยิ่ง",
        my: "နာမဝိသေသန：super-, အလွန်",
        km: "បុព្វបទ៖ ឆ្លៀត/ជាងធម្មតា",
      },
      furigana: [
        {
          rb: "超",
          rt: "ちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "超",
          on: ["チョウ"],
          kun: ["こ.える", "こ.す"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2636,
      kanji: "つかの間",
      reading: "つかのま",
      meanings: {
        ja: "つかの間／ほんの短い間",
        en: "a brief moment; fleeting",
        zh: "转瞬；刹那",
        tw: "轉瞬；剎那",
        ko: "잠깐; 짧은 순간",
        vi: "thoáng chốc; chốc lát",
        th: "ชั่วพริบตา; เพียงครู่",
        my: "အတောအတွင်းတိုတောင်း",
        km: "រយៈពេលខ្លី",
      },
      furigana: [
        {
          rb: "つかの間",
          rt: "つかのま",
        },
      ],
      kanjiInfo: [
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2637,
      kanji: "つくづく",
      reading: "つくづく",
      meanings: {
        ja: "つくづく／しみじみ・よくよく",
        en: "deeply; keenly; truly",
        zh: "深深地；由衷地",
        tw: "深深地；由衷地",
        ko: "절실히; 곰곰이",
        vi: "thấm thía; sâu sắc",
        th: "อย่างลึกซึ้ง",
        my: "နက်နင်းစွာ; အနက်ကိုယ်တိုင်",
        km: "បេះដូងជ្រាលជ្រៅ",
      },
      furigana: [
        {
          rb: "つくづく",
          rt: "つくづく",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
