export const n1part19 = {
  Lesson19: [
    {
      id: 901,
      kanji: "自立",
      reading: "じりつ",
      meanings: {
        ja: "自立",
        en: "independence",
        zh: "独立",
        tw: "自立",
        ko: "자립",
        vi: "tự lập",
        th: "ความเป็นอิสระ",
        my: "လွတ်လပ်မှု",
        km: "ឯករាជ្យភាព",
      },
      furigana: [
        {
          rb: "自立",
          rt: "じりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "立",
          on: ["リツ", "リュウ", "リットル"],
          kun: [
            "た.つ",
            "-た.つ",
            "た.ち-",
            "た.てる",
            "-た.てる",
            "た.て-",
            "たて-",
            "-た.て",
            "-だ.て",
            "-だ.てる",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 902,
      kanji: "指令",
      reading: "しれい",
      meanings: {
        ja: "指令",
        en: "order; directive",
        zh: "指令",
        tw: "指令",
        ko: "지령",
        vi: "mệnh lệnh",
        th: "คำสั่ง",
        my: "ညွှန်ကြားချက်",
        km: "ការបញ្ជា",
      },
      furigana: [
        {
          rb: "指令",
          rt: "しれい",
        },
      ],
      kanjiInfo: [
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "令",
          on: ["レイ"],
          kun: [],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 903,
      kanji: "陣",
      reading: "じん",
      meanings: {
        ja: "陣",
        en: "battle formation",
        zh: "阵营",
        tw: "陣營",
        ko: "진영",
        vi: "trận địa",
        th: "แนวรบ",
        my: "တပ်စည်း",
        km: "ជួរទាហាន",
      },
      furigana: [
        {
          rb: "陣",
          rt: "じん",
        },
      ],
      kanjiInfo: [
        {
          char: "陣",
          on: ["ジン"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 904,
      kanji: "進化",
      reading: "しんか",
      meanings: {
        ja: "進化",
        en: "evolution",
        zh: "进化",
        tw: "進化",
        ko: "진화",
        vi: "tiến hóa",
        th: "วิวัฒนาการ",
        my: "တိုးတက်မှု",
        km: "ការវិវត្ត",
      },
      furigana: [
        {
          rb: "進化",
          rt: "しんか",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 905,
      kanji: "人格",
      reading: "じんかく",
      meanings: {
        ja: "人格",
        en: "personality",
        zh: "人格",
        tw: "人格",
        ko: "인격",
        vi: "nhân cách",
        th: "บุคลิกภาพ",
        my: "ပုဂ္ဂိုလ်သိက္ခာ",
        km: "លក្ខណៈផ្ទាល់ខ្លួន",
      },
      furigana: [
        {
          rb: "人格",
          rt: "じんかく",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "格",
          on: ["カク", "コウ", "キャク", "ゴウ"],
          kun: [],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 906,
      kanji: "審議",
      reading: "しんぎ",
      meanings: {
        ja: "審議",
        en: "deliberation",
        zh: "审议",
        tw: "審議",
        ko: "심의",
        vi: "thẩm nghị",
        th: "การพิจารณา",
        my: "ဆွေးနွေးစိစစ်ခြင်း",
        km: "ការពិភាក្សា",
      },
      furigana: [
        {
          rb: "審議",
          rt: "しんぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "審",
          on: ["シン"],
          kun: ["つまび.らか", "つぶさ.に"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 907,
      kanji: "審査",
      reading: "しんさ",
      meanings: {
        ja: "審査",
        en: "examination; judging",
        zh: "审查",
        tw: "審查",
        ko: "심사",
        vi: "thẩm tra",
        th: "การตรวจสอบ",
        my: "စစ်ဆေးခြင်း",
        km: "ការត្រួតពិនិត្យ",
      },
      furigana: [
        {
          rb: "審査",
          rt: "しんさ",
        },
      ],
      kanjiInfo: [
        {
          char: "審",
          on: ["シン"],
          kun: ["つまび.らか", "つぶさ.に"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "査",
          on: ["サ"],
          kun: [],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 908,
      kanji: "人材",
      reading: "じんざい",
      meanings: {
        ja: "人材",
        en: "talent; capable person",
        zh: "人才",
        tw: "人才",
        ko: "인재",
        vi: "nhân tài",
        th: "บุคลากร",
        my: "စွမ်းရည်ရှိသူ",
        km: "ធនធានមនុស្ស",
      },
      furigana: [
        {
          rb: "人材",
          rt: "じんざい",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "材",
          on: ["ザイ"],
          kun: [],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 909,
      kanji: "紳士",
      reading: "しんし",
      meanings: {
        ja: "紳士",
        en: "gentleman",
        zh: "绅士",
        tw: "紳士",
        ko: "신사",
        vi: "quý ông",
        th: "สุภาพบุรุษ",
        my: "အကျင့်ရှိသူ",
        km: "បុរសសុភាព",
      },
      furigana: [
        {
          rb: "紳士",
          rt: "しんし",
        },
      ],
      kanjiInfo: [
        {
          char: "紳",
          on: ["シン"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "士",
          on: ["シ"],
          kun: ["さむらい"],
          strokes: 3,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 910,
      kanji: "真実",
      reading: "しんじつ",
      meanings: {
        ja: "真実",
        en: "truth",
        zh: "真相",
        tw: "真實",
        ko: "진실",
        vi: "sự thật",
        th: "ความจริง",
        my: "အမှန်တရား",
        km: "ភាពពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "真実",
          rt: "しんじつ",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 911,
      kanji: "信者",
      reading: "しんじゃ",
      meanings: {
        ja: "信者",
        en: "believer",
        zh: "信徒",
        tw: "信徒",
        ko: "신자",
        vi: "tín đồ",
        th: "ผู้ศรัทธา",
        my: "ယုံကြည်သူ",
        km: "អ្នកជឿ",
      },
      furigana: [
        {
          rb: "信者",
          rt: "しんじゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "信",
          on: ["シン"],
          kun: [],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "者",
          on: ["シャ"],
          kun: ["もの"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 912,
      kanji: "真珠",
      reading: "しんじゅ",
      meanings: {
        ja: "真珠",
        en: "pearl",
        zh: "珍珠",
        tw: "珍珠",
        ko: "진주",
        vi: "ngọc trai",
        th: "ไข่มุก",
        my: "မုခ်ခဲ",
        km: "គ្រឿងអលង្ការ",
      },
      furigana: [
        {
          rb: "真珠",
          rt: "しんじゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "珠",
          on: ["シュ"],
          kun: ["たま"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 913,
      kanji: "進出",
      reading: "しんしゅつ",
      meanings: {
        ja: "進出",
        en: "advance (into a market)",
        zh: "进入",
        tw: "進出",
        ko: "진출",
        vi: "mở rộng",
        th: "ขยายเข้าสู่",
        my: "ထုတ်လုပ်မှုတိုးချဲ့ခြင်း",
        km: "ការចូលទៅក្នុងទីផ្សារ",
      },
      furigana: [
        {
          rb: "進出",
          rt: "しんしゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 914,
      kanji: "心情",
      reading: "しんじょう",
      meanings: {
        ja: "心情",
        en: "feelings; sentiment",
        zh: "心情",
        tw: "心情",
        ko: "심정",
        vi: "tâm trạng",
        th: "อารมณ์",
        my: "စိတ်ခံစားမှု",
        km: "អារម្មណ៍",
      },
      furigana: [
        {
          rb: "心情",
          rt: "しんじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 915,
      kanji: "新人",
      reading: "しんじん",
      meanings: {
        ja: "新人",
        en: "newcomer; rookie",
        zh: "新人",
        tw: "新人",
        ko: "신인",
        vi: "người mới",
        th: "คนใหม่",
        my: "အသစ်",
        km: "មនុស្សថ្មី",
      },
      furigana: [
        {
          rb: "新人",
          rt: "しんじん",
        },
      ],
      kanjiInfo: [
        {
          char: "新",
          on: ["シン"],
          kun: ["あたら.しい", "あら.た", "あら-", "にい-"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 916,
      kanji: "神聖",
      reading: "しんせい",
      meanings: {
        ja: "神聖",
        en: "sacred; holy",
        zh: "神圣",
        tw: "神聖",
        ko: "신성",
        vi: "thiêng liêng",
        th: "ศักดิ์สิทธิ์",
        my: "သန့်ရှင်းသော",
        km: "បរិសុទ្ធ",
      },
      furigana: [
        {
          rb: "神聖",
          rt: "しんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "神",
          on: ["シン", "ジン"],
          kun: ["かみ", "かん-", "こう-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "聖",
          on: ["セイ", "ショウ"],
          kun: ["ひじり"],
          strokes: 13,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 917,
      kanji: "親善",
      reading: "しんぜん",
      meanings: {
        ja: "親善",
        en: "friendship; goodwill",
        zh: "友好",
        tw: "親善",
        ko: "친선",
        vi: "hữu nghị",
        th: "มิตรภาพ",
        my: "အကြင်နာ",
        km: "មិត្តភាព",
      },
      furigana: [
        {
          rb: "親善",
          rt: "しんぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "親",
          on: ["シン"],
          kun: ["おや", "おや-", "した.しい", "した.しむ"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "善",
          on: ["ゼン"],
          kun: ["よ.い", "い.い", "よ.く", "よし.とする"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 918,
      kanji: "真相",
      reading: "しんそう",
      meanings: {
        ja: "真相",
        en: "real situation; truth",
        zh: "真相",
        tw: "真相",
        ko: "진상",
        vi: "sự thật",
        th: "ข้อเท็จจริง",
        my: "အမှန်တကယ်အဖြစ်အပျက်",
        km: "ភាពពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "真相",
          rt: "しんそう",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "相",
          on: ["ソウ", "ショウ"],
          kun: ["あい-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 919,
      kanji: "人体",
      reading: "じんたい",
      meanings: {
        ja: "人体",
        en: "human body",
        zh: "人体",
        tw: "人體",
        ko: "인체",
        vi: "cơ thể người",
        th: "ร่างกายมนุษย์",
        my: "ကိုယ်ခန္ဓာ",
        km: "រាងកាយមនុស្ស",
      },
      furigana: [
        {
          rb: "人体",
          rt: "じんたい",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 920,
      kanji: "新築",
      reading: "しんちく",
      meanings: {
        ja: "新築",
        en: "new building",
        zh: "新建筑",
        tw: "新建築",
        ko: "신축",
        vi: "tòa nhà mới",
        th: "อาคารใหม่",
        my: "အဆောက်အအုံအသစ်",
        km: "អគារថ្មី",
      },
      furigana: [
        {
          rb: "新築",
          rt: "しんちく",
        },
      ],
      kanjiInfo: [
        {
          char: "新",
          on: ["シン"],
          kun: ["あたら.しい", "あら.た", "あら-", "にい-"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "築",
          on: ["チク"],
          kun: ["きず.く"],
          strokes: 16,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 921,
      kanji: "心中",
      reading: "しんじゅう",
      meanings: {
        ja: "心中",
        en: "double suicide",
        zh: "心中自杀",
        tw: "心中自殺",
        ko: "심중자살",
        vi: "tự sát đôi",
        th: "ฆ่าตัวตายร่วมกัน",
        my: "အတူတကွသေခြင်း",
        km: "អត្តឃាតជាគូ",
      },
      furigana: [
        {
          rb: "心中",
          rt: "しんじゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 922,
      kanji: "進呈",
      reading: "しんてい",
      meanings: {
        ja: "進呈",
        en: "presentation (of a gift)",
        zh: "赠送",
        tw: "贈呈",
        ko: "진정",
        vi: "tặng",
        th: "มอบให้",
        my: "ပေးအပ်ခြင်း",
        km: "ការផ្តល់ជូន",
      },
      furigana: [
        {
          rb: "進呈",
          rt: "しんてい",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "呈",
          on: ["テイ"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 923,
      kanji: "進展",
      reading: "しんてん",
      meanings: {
        ja: "進展",
        en: "progress; development",
        zh: "进展",
        tw: "進展",
        ko: "진전",
        vi: "tiến triển",
        th: "ความคืบหน้า",
        my: "တိုးတက်မှု",
        km: "ការរីកចម្រើន",
      },
      furigana: [
        {
          rb: "進展",
          rt: "しんてん",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "展",
          on: ["テン"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 924,
      kanji: "神殿",
      reading: "しんでん",
      meanings: {
        ja: "神殿",
        en: "temple; shrine",
        zh: "神殿",
        tw: "神殿",
        ko: "신전",
        vi: "đền thờ",
        th: "วิหาร",
        my: "ဘုရားကျောင်း",
        km: "វត្តអារាម",
      },
      furigana: [
        {
          rb: "神殿",
          rt: "しんでん",
        },
      ],
      kanjiInfo: [
        {
          char: "神",
          on: ["シン", "ジン"],
          kun: ["かみ", "かん-", "こう-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "殿",
          on: ["デン", "テン"],
          kun: ["との", "-どの"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 925,
      kanji: "進度",
      reading: "しんど",
      meanings: {
        ja: "進度",
        en: "progress (of work)",
        zh: "进度",
        tw: "進度",
        ko: "진도",
        vi: "tiến độ",
        th: "ความคืบหน้า",
        my: "အဆင့်တိုးတက်မှု",
        km: "ល្បឿនការងារ",
      },
      furigana: [
        {
          rb: "進度",
          rt: "しんど",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "度",
          on: ["ド", "ト", "タク"],
          kun: ["たび", "-た.い"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 926,
      kanji: "振動",
      reading: "しんどう",
      meanings: {
        ja: "振動",
        en: "vibration; oscillation",
        zh: "振动",
        tw: "振動",
        ko: "진동",
        vi: "rung động",
        th: "การสั่นสะเทือน",
        my: "တုန့်ပြန်မှု",
        km: "ការរញ្ជួយ",
      },
      furigana: [
        {
          rb: "振動",
          rt: "しんどう",
        },
      ],
      kanjiInfo: [
        {
          char: "振",
          on: ["シン"],
          kun: ["ふ.る", "ふ.れる", "ふ.るう"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 927,
      kanji: "新入生",
      reading: "しんにゅうせい",
      meanings: {
        ja: "新入生",
        en: "new student",
        zh: "新生",
        tw: "新生",
        ko: "신입생",
        vi: "tân sinh viên",
        th: "นักเรียนใหม่",
        my: "ကျောင်းသားအသစ်",
        km: "សិស្សថ្មី",
      },
      furigana: [
        {
          rb: "新入生",
          rt: "しんにゅうせい",
        },
      ],
      kanjiInfo: [
        {
          char: "新",
          on: ["シン"],
          kun: ["あたら.しい", "あら.た", "あら-", "にい-"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 928,
      kanji: "信任",
      reading: "しんにん",
      meanings: {
        ja: "信任",
        en: "trust; confidence",
        zh: "信任",
        tw: "信任",
        ko: "신임",
        vi: "tin tưởng",
        th: "ความไว้วางใจ",
        my: "ယုံကြည်ခြင်း",
        km: "ទុកចិត្ត",
      },
      furigana: [
        {
          rb: "信任",
          rt: "しんにん",
        },
      ],
      kanjiInfo: [
        {
          char: "信",
          on: ["シン"],
          kun: [],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "任",
          on: ["ニン"],
          kun: ["まか.せる", "まか.す"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 929,
      kanji: "神秘",
      reading: "しんぴ",
      meanings: {
        ja: "神秘",
        en: "mystery",
        zh: "神秘",
        tw: "神秘",
        ko: "신비",
        vi: "bí ẩn",
        th: "ลึกลับ",
        my: "နွှယ်တောင့်ခြင်း",
        km: "ភាពអាថ៌កំបាំង",
      },
      furigana: [
        {
          rb: "神秘",
          rt: "しんぴ",
        },
      ],
      kanjiInfo: [
        {
          char: "神",
          on: ["シン", "ジン"],
          kun: ["かみ", "かん-", "こう-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "秘",
          on: ["ヒ"],
          kun: ["ひ.める", "ひそ.か", "かく.す"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 930,
      kanji: "辛抱",
      reading: "しんぼう",
      meanings: {
        ja: "辛抱",
        en: "patience; endurance",
        zh: "忍耐",
        tw: "忍耐",
        ko: "인내",
        vi: "chịu đựng",
        th: "ความอดทน",
        my: "သည်းခံမှု",
        km: "ការអត់ធ្មត់",
      },
      furigana: [
        {
          rb: "辛抱",
          rt: "しんぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "辛",
          on: ["シン"],
          kun: ["から.い", "つら.い", "-づら.い", "かのと"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "抱",
          on: ["ホウ"],
          kun: ["だ.く", "いだ.く", "かか.える"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 931,
      kanji: "人民",
      reading: "じんみん",
      meanings: {
        ja: "人民",
        en: "people; citizens",
        zh: "人民",
        tw: "人民",
        ko: "인민",
        vi: "nhân dân",
        th: "ประชาชน",
        my: "ပြည်သူ",
        km: "ប្រជាជន",
      },
      furigana: [
        {
          rb: "人民",
          rt: "じんみん",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "民",
          on: ["ミン"],
          kun: ["たみ"],
          strokes: 5,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 932,
      kanji: "侵略",
      reading: "しんりゃく",
      meanings: {
        ja: "侵略",
        en: "invasion",
        zh: "侵略",
        tw: "侵略",
        ko: "침략",
        vi: "xâm lược",
        th: "การรุกราน",
        my: "စစ်ထိုးဝင်ခြင်း",
        km: "ការលុកលុយ",
      },
      furigana: [
        {
          rb: "侵略",
          rt: "しんりゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "侵",
          on: ["シン"],
          kun: ["おか.す"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "略",
          on: ["リャク"],
          kun: [
            "ほぼ",
            "はぶ.く",
            "おか.す",
            "おさ.める",
            "はかりごと",
            "はか.る",
          ],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 933,
      kanji: "診療",
      reading: "しんりょう",
      meanings: {
        ja: "診療",
        en: "medical consultation",
        zh: "诊疗",
        tw: "診療",
        ko: "진료",
        vi: "chẩn trị",
        th: "การตรวจรักษา",
        my: "ကုသမှု",
        km: "ការព្យាបាល",
      },
      furigana: [
        {
          rb: "診療",
          rt: "しんりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "診",
          on: ["シン"],
          kun: ["み.る"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "療",
          on: ["リョウ"],
          kun: [],
          strokes: 17,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 934,
      kanji: "粋",
      reading: "すい",
      meanings: {
        ja: "粋",
        en: "chic; refinement",
        zh: "精粹",
        tw: "風雅",
        ko: "세련됨",
        vi: "tinh tế",
        th: "สง่างาม",
        my: "ပြေလပ်မှု",
        km: "ភាពឆើតឆាយ",
      },
      furigana: [
        {
          rb: "粋",
          rt: "すい",
        },
      ],
      kanjiInfo: [
        {
          char: "粋",
          on: ["スイ"],
          kun: ["いき"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 935,
      kanji: "水源",
      reading: "すいげん",
      meanings: {
        ja: "水源",
        en: "water source",
        zh: "水源",
        tw: "水源",
        ko: "수원",
        vi: "nguồn nước",
        th: "ต้นน้ำ",
        my: "ရေအမြစ်",
        km: "ប្រភពទឹក",
      },
      furigana: [
        {
          rb: "水源",
          rt: "すいげん",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "源",
          on: ["ゲン"],
          kun: ["みなもと"],
          strokes: 13,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 936,
      kanji: "推進",
      reading: "すいしん",
      meanings: {
        ja: "推進",
        en: "promotion; propulsion",
        zh: "推进",
        tw: "推進",
        ko: "추진",
        vi: "thúc đẩy",
        th: "การส่งเสริม",
        my: "တိုးတက်စေခြင်း",
        km: "ការលើកទឹកចិត្ត",
      },
      furigana: [
        {
          rb: "推進",
          rt: "すいしん",
        },
      ],
      kanjiInfo: [
        {
          char: "推",
          on: ["スイ"],
          kun: ["お.す"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 937,
      kanji: "吹奏",
      reading: "すいそう",
      meanings: {
        ja: "吹奏",
        en: "playing a wind instrument",
        zh: "吹奏",
        tw: "吹奏",
        ko: "취주",
        vi: "thổi nhạc cụ",
        th: "การเป่านกหวีด",
        my: "ပေါက်တူဖျော်ဖြေမှု",
        km: "ការផ្លុំភ្លេង",
      },
      furigana: [
        {
          rb: "吹奏",
          rt: "すいそう",
        },
      ],
      kanjiInfo: [
        {
          char: "吹",
          on: ["スイ"],
          kun: ["ふ.く"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "奏",
          on: ["ソウ"],
          kun: ["かな.でる"],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 938,
      kanji: "推測",
      reading: "すいそく",
      meanings: {
        ja: "推測",
        en: "guess; inference",
        zh: "推测",
        tw: "推測",
        ko: "추측",
        vi: "phỏng đoán",
        th: "การคาดเดา",
        my: "ခန့်မှန်းခြင်း",
        km: "ការសន្និដ្ឋាន",
      },
      furigana: [
        {
          rb: "推測",
          rt: "すいそく",
        },
      ],
      kanjiInfo: [
        {
          char: "推",
          on: ["スイ"],
          kun: ["お.す"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "測",
          on: ["ソク"],
          kun: ["はか.る"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 939,
      kanji: "水田",
      reading: "すいでん",
      meanings: {
        ja: "水田",
        en: "paddy field",
        zh: "水田",
        tw: "水田",
        ko: "논",
        vi: "ruộng lúa nước",
        th: "นาข้าวน้ำ",
        my: "စပါးဝါခင်း",
        km: "ស្រែទឹក",
      },
      furigana: [
        {
          rb: "水田",
          rt: "すいでん",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "田",
          on: ["デン"],
          kun: ["た"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 940,
      kanji: "推理",
      reading: "すいり",
      meanings: {
        ja: "推理",
        en: "reasoning; inference",
        zh: "推理",
        tw: "推理",
        ko: "추리",
        vi: "suy luận",
        th: "การใช้เหตุผล",
        my: "ခန့်မှန်းဆေးခြင်း",
        km: "ការវិភាគហេតុផល",
      },
      furigana: [
        {
          rb: "推理",
          rt: "すいり",
        },
      ],
      kanjiInfo: [
        {
          char: "推",
          on: ["スイ"],
          kun: ["お.す"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "理",
          on: ["リ"],
          kun: ["ことわり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 941,
      kanji: "数詞",
      reading: "すうし",
      meanings: {
        ja: "数詞",
        en: "numeral",
        zh: "数词",
        tw: "數詞",
        ko: "수사",
        vi: "số từ",
        th: "คำบอกจำนวน",
        my: "ဂဏန်းနာမဝိသေသန",
        km: "ពាក្យលេខ",
      },
      furigana: [
        {
          rb: "数詞",
          rt: "すうし",
        },
      ],
      kanjiInfo: [
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 942,
      kanji: "崇拝",
      reading: "すうはい",
      meanings: {
        ja: "崇拝",
        en: "worship; adoration",
        zh: "崇拜",
        tw: "崇拜",
        ko: "숭배",
        vi: "tôn thờ",
        th: "บูชา",
        my: "လေးမြတ်ခြင်း",
        km: "ការគោរពបូជា",
      },
      furigana: [
        {
          rb: "崇拝",
          rt: "すうはい",
        },
      ],
      kanjiInfo: [
        {
          char: "崇",
          on: ["スウ"],
          kun: ["あが.める"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "拝",
          on: ["ハイ"],
          kun: ["おが.む", "おろが.む"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 943,
      kanji: "救い",
      reading: "すくい",
      meanings: {
        ja: "救い",
        en: "relief; help",
        zh: "拯救",
        tw: "救贖",
        ko: "구원",
        vi: "sự cứu giúp",
        th: "การช่วยเหลือ",
        my: "ကယ်ဆယ်ခြင်း",
        km: "ការជួយសង្គ្រោះ",
      },
      furigana: [
        {
          rb: "救い",
          rt: "すくい",
        },
      ],
      kanjiInfo: [
        {
          char: "救",
          on: ["キュウ"],
          kun: ["すく.う"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 944,
      kanji: "進み",
      reading: "すすみ",
      meanings: {
        ja: "進み",
        en: "progress; advancement",
        zh: "进展",
        tw: "進展",
        ko: "진전",
        vi: "tiến bộ",
        th: "ความก้าวหน้า",
        my: "တိုးတက်မှု",
        km: "ការរីកចម្រើន",
      },
      furigana: [
        {
          rb: "進み",
          rt: "すすみ",
        },
      ],
      kanjiInfo: [
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 945,
      kanji: "裾",
      reading: "すそ",
      meanings: {
        ja: "裾",
        en: "hem; bottom edge",
        zh: "下摆",
        tw: "衣襬",
        ko: "자락",
        vi: "vạt áo",
        th: "ชายเสื้อ",
        my: "အောက်ခြေ",
        km: "បាតសម្លៀកបំពាក់",
      },
      furigana: [
        {
          rb: "裾",
          rt: "すそ",
        },
      ],
      kanjiInfo: [
        {
          char: "裾",
          on: ["キョ", "コ"],
          kun: ["すそ"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 946,
      kanji: "スタジオ",
      reading: "スタジオ",
      meanings: {
        ja: "スタジオ",
        en: "studio",
        zh: "摄影棚",
        tw: "攝影棚",
        ko: "스튜디오",
        vi: "phòng thu",
        th: "สตูดิโอ",
        my: "စတူဒီယို",
        km: "ស្ទូឌីយោ",
      },
      furigana: [
        {
          rb: "スタジオ",
          rt: "スタジオ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 947,
      kanji: "スチーム",
      reading: "スチーム",
      meanings: {
        ja: "スチーム",
        en: "steam",
        zh: "蒸汽",
        tw: "蒸氣",
        ko: "스팀",
        vi: "hơi nước",
        th: "ไอน้ำ",
        my: "အငွေ့",
        km: "ចំហាយទឹក",
      },
      furigana: [
        {
          rb: "スチーム",
          rt: "スチーム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 948,
      kanji: "ストライキ",
      reading: "ストライキ",
      meanings: {
        ja: "ストライキ",
        en: "strike (industrial)",
        zh: "罢工",
        tw: "罷工",
        ko: "파업",
        vi: "đình công",
        th: "การนัดหยุดงาน",
        my: "အလုပ်ပိတ်",
        km: "ការធ្វើបាតុកម្ម",
      },
      furigana: [
        {
          rb: "ストライキ",
          rt: "ストライキ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 949,
      kanji: "スト",
      reading: "スト",
      meanings: {
        ja: "スト",
        en: "strike (abbr.)",
        zh: "罢工",
        tw: "罷工",
        ko: "파업",
        vi: "đình công",
        th: "หยุดงาน",
        my: "အလုပ်ပိတ်",
        km: "ការធ្វើបាតុកម្ម",
      },
      furigana: [
        {
          rb: "スト",
          rt: "スト",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 950,
      kanji: "ストロー",
      reading: "ストロー",
      meanings: {
        ja: "ストロー",
        en: "straw (drinking)",
        zh: "吸管",
        tw: "吸管",
        ko: "빨대",
        vi: "ống hút",
        th: "หลอดดูดน้ำ",
        my: "မြွေခွံမြှောင်",
        km: "បំពង់ផឹកទឹក",
      },
      furigana: [
        {
          rb: "ストロー",
          rt: "ストロー",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
