export const n1part27 = {
  Lesson27: [
    {
      id: 1301,
      kanji: "実業家",
      reading: "じつぎょうか",
      meanings: {
        ja: "実業家",
        en: "businessperson",
        zh: "实业家",
        tw: "實業家",
        ko: "실업가",
        vi: "doanh nhân",
        th: "นักธุรกิจ",
        my: "စီးပွားရေးရှင်",
        km: "អ្នកសហគ្រិន",
      },
      furigana: [
        {
          rb: "実業家",
          rt: "じつぎょうか",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1302,
      kanji: "躾",
      reading: "しつけ",
      meanings: {
        ja: "躾",
        en: "discipline; upbringing",
        zh: "教养",
        tw: "教養",
        ko: "훈육",
        vi: "rèn luyện",
        th: "อบรม",
        my: "သင်ကြားနှိုးဆော်ခြင်း",
        km: "ការបង្រៀនវិន័យ",
      },
      furigana: [
        {
          rb: "躾",
          rt: "しつけ",
        },
      ],
      kanjiInfo: [
        {
          char: "躾",
          on: [],
          kun: ["しつ.ける", "しつけ"],
          strokes: 16,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1303,
      kanji: "実践",
      reading: "じっせん",
      meanings: {
        ja: "実践",
        en: "practice (as opposed to theory)",
        zh: "实践",
        tw: "實踐",
        ko: "실천",
        vi: "thực hành",
        th: "การปฏิบัติจริง",
        my: "အကောင်အထည်ဖော်ခြင်း",
        km: "អនុវត្ត",
      },
      furigana: [
        {
          rb: "実践",
          rt: "じっせん",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "践",
          on: ["セン"],
          kun: ["ふ.む"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1304,
      kanji: "実態",
      reading: "じったい",
      meanings: {
        ja: "実態",
        en: "real condition; true state",
        zh: "实际情况",
        tw: "實際情況",
        ko: "실태",
        vi: "thực trạng",
        th: "สภาพจริง",
        my: "အမှန်တကယ်အခြေအနေ",
        km: "ស្ថានភាពពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "実態",
          rt: "じったい",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "態",
          on: ["タイ"],
          kun: ["わざ.と"],
          strokes: 14,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1305,
      kanji: "失調",
      reading: "しっちょう",
      meanings: {
        ja: "失調",
        en: "lack of harmony",
        zh: "失调",
        tw: "失調",
        ko: "실조",
        vi: "mất cân bằng",
        th: "ความไม่สมดุล",
        my: "မညီမျှမှု",
        km: "ភាពមិនសមតុល្យ",
      },
      furigana: [
        {
          rb: "失調",
          rt: "しっちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "失",
          on: ["シツ"],
          kun: ["うしな.う", "う.せる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "調",
          on: ["チョウ"],
          kun: ["しら.べる", "しら.べ", "ととの.う", "ととの.える"],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1306,
      kanji: "嫉妬",
      reading: "しっと",
      meanings: {
        ja: "嫉妬",
        en: "jealousy",
        zh: "嫉妒",
        tw: "嫉妒",
        ko: "질투",
        vi: "ghen tuông",
        th: "ความอิจฉา",
        my: "အလျှာတ",
        km: "ការច្រណែន",
      },
      furigana: [
        {
          rb: "嫉妬",
          rt: "しっと",
        },
      ],
      kanjiInfo: [
        {
          char: "嫉",
          on: ["シツ"],
          kun: ["そね.む", "ねた.む", "にく.む"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
        {
          char: "妬",
          on: ["ト", "ツ"],
          kun: ["ねた.む", "そね.む", "つも.る", "ふさ.ぐ"],
          strokes: 8,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1307,
      kanji: "実費",
      reading: "じっぴ",
      meanings: {
        ja: "実費",
        en: "actual expenses",
        zh: "实际费用",
        tw: "實際費用",
        ko: "실비",
        vi: "chi phí thực tế",
        th: "ค่าใช้จ่ายจริง",
        my: "အမှန်တကယ်ကုန်ကျစရိတ်",
        km: "ចំណាយពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "実費",
          rt: "じっぴ",
        },
      ],
      kanjiInfo: [
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "費",
          on: ["ヒ"],
          kun: ["つい.やす", "つい.える"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1308,
      kanji: "指摘",
      reading: "してき",
      meanings: {
        ja: "指摘",
        en: "pointing out",
        zh: "指出",
        tw: "指出",
        ko: "지적",
        vi: "chỉ ra",
        th: "ชี้ให้เห็น",
        my: "ညွှန်ပြခြင်း",
        km: "បញ្ជាក់",
      },
      furigana: [
        {
          rb: "指摘",
          rt: "してき",
        },
      ],
      kanjiInfo: [
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "摘",
          on: ["テキ"],
          kun: ["つ.む"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1309,
      kanji: "自転",
      reading: "じてん",
      meanings: {
        ja: "自転",
        en: "rotation (on an axis)",
        zh: "自转",
        tw: "自轉",
        ko: "자전",
        vi: "tự quay",
        th: "การหมุนรอบตัวเอง",
        my: "ကိုယ်ပိုင်ဝန်းလည်မှု",
        km: "បង្វិលជុំ",
      },
      furigana: [
        {
          rb: "自転",
          rt: "じてん",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1310,
      kanji: "助動詞",
      reading: "じょどうし",
      meanings: {
        ja: "助動詞",
        en: "auxiliary verb",
        zh: "助动词",
        tw: "助動詞",
        ko: "조동사",
        vi: "trợ động từ",
        th: "คำกริยาช่วย",
        my: "အကူကြိယာ",
        km: "កិរិយាសព្ទជំនួយ",
      },
      furigana: [
        {
          rb: "助動詞",
          rt: "じょどうし",
        },
      ],
      kanjiInfo: [
        {
          char: "助",
          on: ["ジョ"],
          kun: ["たす.ける", "たす.かる", "す.ける", "すけ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1311,
      kanji: "シナリオ",
      reading: "シナリオ",
      meanings: {
        ja: "シナリオ",
        en: "scenario; script",
        zh: "剧本",
        tw: "劇本",
        ko: "시나리오",
        vi: "kịch bản",
        th: "บทภาพยนตร์",
        my: "ဇာတ်ညွှန်း",
        km: "ស៊ីណារីយ៉ូ",
      },
      furigana: [
        {
          rb: "シナリオ",
          rt: "シナリオ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1312,
      kanji: "屎尿",
      reading: "しにょう",
      meanings: {
        ja: "屎尿",
        en: "excreta",
        zh: "屎尿",
        tw: "屎尿",
        ko: "대소변",
        vi: "phân và nước tiểu",
        th: "อุจจาระปัสสาวะ",
        my: "အညစ်အကြေး",
        km: "អាសនៈនិងទឹកនោម",
      },
      furigana: [
        {
          rb: "屎尿",
          rt: "しにょう",
        },
      ],
      kanjiInfo: [
        {
          char: "屎",
          on: ["シ", "キ"],
          kun: ["くそ"],
          strokes: 9,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
        {
          char: "尿",
          on: ["ニョウ"],
          kun: ["ゆばり", "いばり", "しと"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1313,
      kanji: "地主",
      reading: "じぬし",
      meanings: {
        ja: "地主",
        en: "landowner",
        zh: "地主",
        tw: "地主",
        ko: "지주",
        vi: "địa chủ",
        th: "เจ้าของที่ดิน",
        my: "မြေရှင်",
        km: "ម្ចាស់ដី",
      },
      furigana: [
        {
          rb: "地主",
          rt: "じぬし",
        },
      ],
      kanjiInfo: [
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1314,
      kanji: "芝",
      reading: "しば",
      meanings: {
        ja: "芝",
        en: "lawn; turf",
        zh: "草坪",
        tw: "草坪",
        ko: "잔디",
        vi: "bãi cỏ",
        th: "สนามหญ้า",
        my: "မြက်ခင်း",
        km: "ស្មៅ",
      },
      furigana: [
        {
          rb: "芝",
          rt: "しば",
        },
      ],
      kanjiInfo: [
        {
          char: "芝",
          on: ["シ"],
          kun: ["しば"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1315,
      kanji: "始発",
      reading: "しはつ",
      meanings: {
        ja: "始発",
        en: "first departure (train/bus)",
        zh: "首班车",
        tw: "首班車",
        ko: "첫차",
        vi: "chuyến đầu",
        th: "เที่ยวแรก",
        my: "ပထမဆုံးထွက်ခွာ",
        km: "ដំណើរទីមួយ",
      },
      furigana: [
        {
          rb: "始発",
          rt: "しはつ",
        },
      ],
      kanjiInfo: [
        {
          char: "始",
          on: ["シ"],
          kun: ["はじ.める", "-はじ.める", "はじ.まる"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1316,
      kanji: "耳鼻科",
      reading: "じびか",
      meanings: {
        ja: "耳鼻科",
        en: "otolaryngology (ENT)",
        zh: "耳鼻喉科",
        tw: "耳鼻喉科",
        ko: "이비인후과",
        vi: "khoa tai mũi họng",
        th: "โสต ศอ นาสิก",
        my: "နားနှာခေါင်းလည်",
        km: "ផ្នែកត្រចៀកច្រមុះបំពង់ក",
      },
      furigana: [
        {
          rb: "耳鼻科",
          rt: "じびか",
        },
      ],
      kanjiInfo: [
        {
          char: "耳",
          on: ["ジ"],
          kun: ["みみ"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "鼻",
          on: ["ビ"],
          kun: ["はな"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1317,
      kanji: "私物",
      reading: "しぶつ",
      meanings: {
        ja: "私物",
        en: "personal belongings",
        zh: "私人物品",
        tw: "私人物品",
        ko: "사물; 개인 소지품",
        vi: "đồ cá nhân",
        th: "ของส่วนตัว",
        my: "ကိုယ်ပိုင်ပစ္စည်း",
        km: "ទ្រព្យសម្បត្តិផ្ទាល់ខ្លួន",
      },
      furigana: [
        {
          rb: "私物",
          rt: "しぶつ",
        },
      ],
      kanjiInfo: [
        {
          char: "私",
          on: ["シ"],
          kun: ["わたくし", "わたし"],
          strokes: 7,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1318,
      kanji: "司法",
      reading: "しほう",
      meanings: {
        ja: "司法",
        en: "judiciary; administration of justice",
        zh: "司法",
        tw: "司法",
        ko: "사법",
        vi: "tư pháp",
        th: "ตุลาการ",
        my: "တရားရေးစိုးစံ",
        km: "យុត្តិធម៌",
      },
      furigana: [
        {
          rb: "司法",
          rt: "しほう",
        },
      ],
      kanjiInfo: [
        {
          char: "司",
          on: ["シ"],
          kun: ["つかさど.る"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "法",
          on: ["ホウ", "ハッ", "ホッ", "フラン"],
          kun: ["のり"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1319,
      kanji: "始末",
      reading: "しまつ",
      meanings: {
        ja: "始末",
        en: "management; disposal; dealing with",
        zh: "处理；收拾",
        tw: "收拾；處理",
        ko: "처리; 수습",
        vi: "xử lý; thu xếp",
        th: "จัดการ",
        my: "ကိုင်တွယ်ခြင်း",
        km: "ដោះស្រាយ",
      },
      furigana: [
        {
          rb: "始末",
          rt: "しまつ",
        },
      ],
      kanjiInfo: [
        {
          char: "始",
          on: ["シ"],
          kun: ["はじ.める", "-はじ.める", "はじ.まる"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "末",
          on: ["マツ", "バツ"],
          kun: ["すえ", "うら", "うれ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1320,
      kanji: "使命",
      reading: "しめい",
      meanings: {
        ja: "使命",
        en: "mission; duty",
        zh: "使命",
        tw: "使命",
        ko: "사명",
        vi: "sứ mệnh",
        th: "ภารกิจ",
        my: "တာဝန်မြတ်",
        km: "បេសកកម្ម",
      },
      furigana: [
        {
          rb: "使命",
          rt: "しめい",
        },
      ],
      kanjiInfo: [
        {
          char: "使",
          on: ["シ"],
          kun: ["つか.う", "つか.い", "-つか.い", "-づか.い"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1321,
      kanji: "地元",
      reading: "じもと",
      meanings: {
        ja: "地元",
        en: "local; one's hometown area",
        zh: "当地；本地",
        tw: "當地；在地",
        ko: "지역",
        vi: "địa phương",
        th: "ท้องถิ่น",
        my: "ဒေသခံ",
        km: "មូលដ្ឋាន",
      },
      furigana: [
        {
          rb: "地元",
          rt: "じもと",
        },
      ],
      kanjiInfo: [
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "元",
          on: ["ゲン", "ガン"],
          kun: ["もと"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1322,
      kanji: "視野",
      reading: "しや",
      meanings: {
        ja: "視野",
        en: "field of vision; outlook",
        zh: "视野",
        tw: "視野",
        ko: "시야",
        vi: "tầm nhìn",
        th: "ขอบเขตการมองเห็น",
        my: "မြင်ကွင်း",
        km: "វិស័យទស្សនៈ",
      },
      furigana: [
        {
          rb: "視野",
          rt: "しや",
        },
      ],
      kanjiInfo: [
        {
          char: "視",
          on: ["シ"],
          kun: ["み.る"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "野",
          on: ["ヤ", "ショ"],
          kun: ["の", "の-"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1323,
      kanji: "社交",
      reading: "しゃこう",
      meanings: {
        ja: "社交",
        en: "social life; socializing",
        zh: "社交",
        tw: "社交",
        ko: "사교",
        vi: "giao tế xã hội",
        th: "การเข้าสังคม",
        my: "လူမှုရေးဆက်ဆံရေး",
        km: "សង្គមភាព",
      },
      furigana: [
        {
          rb: "社交",
          rt: "しゃこう",
        },
      ],
      kanjiInfo: [
        {
          char: "社",
          on: ["シャ"],
          kun: ["やしろ"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "交",
          on: ["コウ"],
          kun: [
            "まじ.わる",
            "まじ.える",
            "ま.じる",
            "まじ.る",
            "ま.ざる",
            "ま.ぜる",
            "-か.う",
            "か.わす",
            "かわ.す",
            "こもごも",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1324,
      kanji: "ジャズ",
      reading: "ジャズ",
      meanings: {
        ja: "ジャズ",
        en: "jazz",
        zh: "爵士乐",
        tw: "爵士樂",
        ko: "재즈",
        vi: "nhạc jazz",
        th: "แจ๊ส",
        my: "ဂျက်ဇ်",
        km: "តន្ត្រីជាស",
      },
      furigana: [
        {
          rb: "ジャズ",
          rt: "ジャズ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1325,
      kanji: "謝絶",
      reading: "しゃぜつ",
      meanings: {
        ja: "謝絶",
        en: "refusal; declining",
        zh: "谢绝",
        tw: "謝絕",
        ko: "사절",
        vi: "từ chối",
        th: "ปฏิเสธ",
        my: "ငြင်းပယ်ခြင်း",
        km: "បដិសេធ",
      },
      furigana: [
        {
          rb: "謝絶",
          rt: "しゃぜつ",
        },
      ],
      kanjiInfo: [
        {
          char: "謝",
          on: ["シャ"],
          kun: ["あやま.る"],
          strokes: 17,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "絶",
          on: ["ゼツ"],
          kun: ["た.える", "た.やす", "た.つ"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1326,
      kanji: "社宅",
      reading: "しゃたく",
      meanings: {
        ja: "社宅",
        en: "company housing",
        zh: "公司宿舍",
        tw: "公司宿舍",
        ko: "사택",
        vi: "nhà công ty",
        th: "บ้านพักพนักงาน",
        my: "အလုပ်အကိုင်အိမ်",
        km: "ផ្ទះក្រុមហ៊ុន",
      },
      furigana: [
        {
          rb: "社宅",
          rt: "しゃたく",
        },
      ],
      kanjiInfo: [
        {
          char: "社",
          on: ["シャ"],
          kun: ["やしろ"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "宅",
          on: ["タク"],
          kun: [],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1327,
      kanji: "三味線",
      reading: "しゃみせん",
      meanings: {
        ja: "三味線",
        en: "shamisen (JP three-string lute)",
        zh: "三味线",
        tw: "三味線",
        ko: "샤미센",
        vi: "đàn shamisen",
        th: "ชามิเซ็น",
        my: "ဂျပန်သုံးကြိုးဂီတယန္တရား",
        km: "ឧបករណ៍តន្ត្រីសាមិសេន",
      },
      furigana: [
        {
          rb: "三味線",
          rt: "しゃみせん",
        },
      ],
      kanjiInfo: [
        {
          char: "三",
          on: ["サン", "ゾウ"],
          kun: ["み", "み.つ", "みっ.つ"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "線",
          on: ["セン"],
          kun: ["すじ"],
          strokes: 15,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1328,
      kanji: "斜面",
      reading: "しゃめん",
      meanings: {
        ja: "斜面",
        en: "slope; incline",
        zh: "斜坡",
        tw: "斜坡",
        ko: "비탈면",
        vi: "sườn dốc",
        th: "ทางลาด",
        my: "မြေချော်",
        km: "ផ្ទៃលំអៀង",
      },
      furigana: [
        {
          rb: "斜面",
          rt: "しゃめん",
        },
      ],
      kanjiInfo: [
        {
          char: "斜",
          on: ["シャ"],
          kun: ["なな.め", "はす"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1329,
      kanji: "砂利",
      reading: "じゃり",
      meanings: {
        ja: "砂利",
        en: "gravel",
        zh: "碎石",
        tw: "碎石",
        ko: "자갈",
        vi: "sỏi",
        th: "กรวด",
        my: "ကျောက်ဖျဉ်",
        km: "ថ្មតូចៗ",
      },
      furigana: [
        {
          rb: "砂利",
          rt: "じゃり",
        },
      ],
      kanjiInfo: [
        {
          char: "砂",
          on: ["サ", "シャ"],
          kun: ["すな"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "利",
          on: ["リ"],
          kun: ["き.く"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1330,
      kanji: "ジャンパー",
      reading: "ジャンパー",
      meanings: {
        ja: "ジャンパー",
        en: "jumper; jacket",
        zh: "夹克",
        tw: "夾克",
        ko: "점퍼",
        vi: "áoแจ็คเก็ต",
        th: "เสื้อแจ็กเก็ต",
        my: "ဂျမ်ပါ",
        km: "អាវក្រៅ",
      },
      furigana: [
        {
          rb: "ジャンパー",
          rt: "ジャンパー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1331,
      kanji: "ジャンプ",
      reading: "ジャンプ",
      meanings: {
        ja: "ジャンプ",
        en: "jump",
        zh: "跳跃",
        tw: "跳躍",
        ko: "점프",
        vi: "nhảy",
        th: "กระโดด",
        my: "ခုန်ခြင်း",
        km: "លោត",
      },
      furigana: [
        {
          rb: "ジャンプ",
          rt: "ジャンプ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1332,
      kanji: "ジャンル",
      reading: "ジャンル",
      meanings: {
        ja: "ジャンル",
        en: "genre",
        zh: "体裁；类别",
        tw: "類型",
        ko: "장르",
        vi: "thể loại",
        th: "ประเภท",
        my: "အမျိုးအစား",
        km: "ប្រភេទ",
      },
      furigana: [
        {
          rb: "ジャンル",
          rt: "ジャンル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1333,
      kanji: "主",
      reading: "しゅ",
      meanings: {
        ja: "主",
        en: "master; lord",
        zh: "主人",
        tw: "主人",
        ko: "주인",
        vi: "chủ",
        th: "เจ้านาย",
        my: "ပိုင်ရှင်",
        km: "ម្ចាស់",
      },
      furigana: [
        {
          rb: "主",
          rt: "しゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1334,
      kanji: "種",
      reading: "しゅ",
      meanings: {
        ja: "種",
        en: "kind; species",
        zh: "种类",
        tw: "種類",
        ko: "종(류)",
        vi: "giống loài",
        th: "ชนิด",
        my: "အမျိုးအစား",
        km: "ប្រភេទ",
      },
      furigana: [
        {
          rb: "種",
          rt: "しゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "種",
          on: ["シュ"],
          kun: ["たね", "-ぐさ"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1335,
      kanji: "私有",
      reading: "しゆう",
      meanings: {
        ja: "私有",
        en: "private ownership",
        zh: "私有",
        tw: "私有",
        ko: "사유",
        vi: "sở hữu tư nhân",
        th: "กรรมสิทธิ์ส่วนบุคคล",
        my: "ကိုယ်ပိုင်ပိုင်ဆိုင်မှု",
        km: "កម្មសិទ្ធិឯកជន",
      },
      furigana: [
        {
          rb: "私有",
          rt: "しゆう",
        },
      ],
      kanjiInfo: [
        {
          char: "私",
          on: ["シ"],
          kun: ["わたくし", "わたし"],
          strokes: 7,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "有",
          on: ["ユウ", "ウ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1336,
      kanji: "収益",
      reading: "しゅうえき",
      meanings: {
        ja: "収益",
        en: "earnings; revenue",
        zh: "收益",
        tw: "收益",
        ko: "수익",
        vi: "doanh thu",
        th: "รายได้",
        my: "ဝင်ငွေ",
        km: "ចំណូល",
      },
      furigana: [
        {
          rb: "収益",
          rt: "しゅうえき",
        },
      ],
      kanjiInfo: [
        {
          char: "収",
          on: ["シュウ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "益",
          on: ["エキ", "ヤク"],
          kun: ["ま.す"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1337,
      kanji: "修学",
      reading: "しゅうがく",
      meanings: {
        ja: "修学",
        en: "study; learning",
        zh: "修学",
        tw: "修學",
        ko: "수학(學)",
        vi: "học tập",
        th: "การศึกษา",
        my: "လေ့လာရေး",
        km: "សិក្សា",
      },
      furigana: [
        {
          rb: "修学",
          rt: "しゅうがく",
        },
      ],
      kanjiInfo: [
        {
          char: "修",
          on: ["シュウ", "シュ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1338,
      kanji: "周期",
      reading: "しゅうき",
      meanings: {
        ja: "周期",
        en: "cycle; period",
        zh: "周期",
        tw: "週期",
        ko: "주기",
        vi: "chu kỳ",
        th: "รอบ",
        my: "အကြိမ်ဝန်း",
        km: "វដ្ត",
      },
      furigana: [
        {
          rb: "周期",
          rt: "しゅうき",
        },
      ],
      kanjiInfo: [
        {
          char: "周",
          on: ["シュウ"],
          kun: ["まわ.り"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1339,
      kanji: "衆議院",
      reading: "しゅうぎいん",
      meanings: {
        ja: "衆議院",
        en: "House of Representatives (Japan)",
        zh: "众议院（日本）",
        tw: "眾議院（日本）",
        ko: "중의원",
        vi: "Hạ viện (Nhật)",
        th: "สภาผู้แทนราษฎร (ญี่ปุ่น)",
        my: "အမျိုးသားလွှတ်တော်အောက်လွှတ်တော်",
        km: "សភាតំណាងរាស្ដ្រ",
      },
      furigana: [
        {
          rb: "衆議院",
          rt: "しゅうぎいん",
        },
      ],
      kanjiInfo: [
        {
          char: "衆",
          on: ["シュウ", "シュ"],
          kun: ["おお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "院",
          on: ["イン"],
          kun: [],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1340,
      kanji: "就業",
      reading: "しゅうぎょう",
      meanings: {
        ja: "就業",
        en: "employment; starting work",
        zh: "就业",
        tw: "就業",
        ko: "취업; 근무 시작",
        vi: "việc làm",
        th: "การจ้างงาน",
        my: "အလုပ်ဝင်ခြင်း",
        km: "មានការងារ",
      },
      furigana: [
        {
          rb: "就業",
          rt: "しゅうぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "就",
          on: ["シュウ", "ジュ"],
          kun: ["つ.く", "つ.ける"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1341,
      kanji: "従業員",
      reading: "じゅうぎょういん",
      meanings: {
        ja: "従業員",
        en: "employee",
        zh: "员工",
        tw: "員工",
        ko: "종업원",
        vi: "nhân viên",
        th: "พนักงาน",
        my: "ဝန်ထမ်း",
        km: "បុគ្គលិក",
      },
      furigana: [
        {
          rb: "従業員",
          rt: "じゅうぎょういん",
        },
      ],
      kanjiInfo: [
        {
          char: "従",
          on: ["ジュウ", "ショウ", "ジュ"],
          kun: ["したが.う", "したが.える", "より"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "員",
          on: ["イン"],
          kun: [],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1342,
      kanji: "集計",
      reading: "しゅうけい",
      meanings: {
        ja: "集計",
        en: "totalization; tally",
        zh: "汇总",
        tw: "彙總",
        ko: "집계",
        vi: "tổng hợp",
        th: "รวมยอด",
        my: "စုစုပေါင်းရေးသားခြင်း",
        km: "ចុះសរុប",
      },
      furigana: [
        {
          rb: "集計",
          rt: "しゅうけい",
        },
      ],
      kanjiInfo: [
        {
          char: "集",
          on: ["シュウ"],
          kun: ["あつ.まる", "あつ.める", "つど.う"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "計",
          on: ["ケイ"],
          kun: ["はか.る", "はか.らう"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1343,
      kanji: "襲撃",
      reading: "しゅうげき",
      meanings: {
        ja: "襲撃",
        en: "raid; attack",
        zh: "袭击",
        tw: "襲擊",
        ko: "습격",
        vi: "tập kích",
        th: "จู่โจม",
        my: "ထိုးစစ်",
        km: "វាយប្រហារ",
      },
      furigana: [
        {
          rb: "襲撃",
          rt: "しゅうげき",
        },
      ],
      kanjiInfo: [
        {
          char: "襲",
          on: ["シュウ"],
          kun: ["おそ.う", "かさ.ね"],
          strokes: 22,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "撃",
          on: ["ゲキ"],
          kun: ["う.つ"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1344,
      kanji: "収支",
      reading: "しゅうし",
      meanings: {
        ja: "収支",
        en: "income and expenditure",
        zh: "收支",
        tw: "收支",
        ko: "수지",
        vi: "thu chi",
        th: "รายรับรายจ่าย",
        my: "ဝင်ငွေထွက်ငွေ",
        km: "ចំណូលចំណាយ",
      },
      furigana: [
        {
          rb: "収支",
          rt: "しゅうし",
        },
      ],
      kanjiInfo: [
        {
          char: "収",
          on: ["シュウ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "支",
          on: ["シ"],
          kun: ["ささ.える", "つか.える", "か.う"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1345,
      kanji: "終始",
      reading: "しゅうし",
      meanings: {
        ja: "終始",
        en: "from beginning to end; consistently",
        zh: "始终",
        tw: "始終",
        ko: "시종",
        vi: "từ đầu đến cuối",
        th: "ตลอด",
        my: "အစဉ်အမြဲ",
        km: "ជានិច្ច",
      },
      furigana: [
        {
          rb: "終始",
          rt: "しゅうし",
        },
      ],
      kanjiInfo: [
        {
          char: "終",
          on: ["シュウ"],
          kun: ["お.わる", "-お.わる", "おわ.る", "お.える", "つい", "つい.に"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "始",
          on: ["シ"],
          kun: ["はじ.める", "-はじ.める", "はじ.まる"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1346,
      kanji: "修士",
      reading: "しゅうし",
      meanings: {
        ja: "修士",
        en: "master's degree",
        zh: "硕士",
        tw: "碩士",
        ko: "석사",
        vi: "thạc sĩ",
        th: "ปริญญาโท",
        my: "မzás္တာဘွဲ့",
        km: "បរិញ្ញាបត្រជាន់ខ្ពស់",
      },
      furigana: [
        {
          rb: "修士",
          rt: "しゅうし",
        },
      ],
      kanjiInfo: [
        {
          char: "修",
          on: ["シュウ", "シュ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "士",
          on: ["シ"],
          kun: ["さむらい"],
          strokes: 3,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1347,
      kanji: "従事",
      reading: "じゅうじ",
      meanings: {
        ja: "従事",
        en: "engage in (work)",
        zh: "从事",
        tw: "從事",
        ko: "종사",
        vi: "hành nghề",
        th: "ประกอบอาชีพ",
        my: "လုပ်ငန်းလုပ်ကိုင်",
        km: "ចូលរួមធ្វើការ",
      },
      furigana: [
        {
          rb: "従事",
          rt: "じゅうじ",
        },
      ],
      kanjiInfo: [
        {
          char: "従",
          on: ["ジュウ", "ショウ", "ジュ"],
          kun: ["したが.う", "したが.える", "より"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1348,
      kanji: "終日",
      reading: "しゅうじつ",
      meanings: {
        ja: "終日",
        en: "all day; the whole day",
        zh: "整天",
        tw: "整天",
        ko: "종일",
        vi: "suốt ngày",
        th: "ทั้งวัน",
        my: "တစ်နေ့လုံး",
        km: "ថ្ងៃមូល",
      },
      furigana: [
        {
          rb: "終日",
          rt: "しゅうじつ",
        },
      ],
      kanjiInfo: [
        {
          char: "終",
          on: ["シュウ"],
          kun: ["お.わる", "-お.わる", "おわ.る", "お.える", "つい", "つい.に"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1349,
      kanji: "充実",
      reading: "じゅうじつ",
      meanings: {
        ja: "充実",
        en: "being fulfilling; enrichment",
        zh: "充实",
        tw: "充實",
        ko: "충실",
        vi: "đầy đủ; phong phú",
        th: "ครบถ้วนสมบูรณ์",
        my: "ပြည့်စုံမှု",
        km: "ភាពពេញលេញ",
      },
      furigana: [
        {
          rb: "充実",
          rt: "じゅうじつ",
        },
      ],
      kanjiInfo: [
        {
          char: "充",
          on: ["ジュウ"],
          kun: ["あ.てる", "み.たす"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "実",
          on: ["ジツ", "シツ"],
          kun: ["み", "みの.る", "まこと", "みの", "みち.る"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1350,
      kanji: "収集",
      reading: "しゅうしゅう",
      meanings: {
        ja: "収集",
        en: "collection; gathering",
        zh: "收集",
        tw: "收集",
        ko: "수집",
        vi: "sưu tầm",
        th: "สะสม",
        my: "စုဆောင်းခြင်း",
        km: "ប្រមូលផ្តុំ",
      },
      furigana: [
        {
          rb: "収集",
          rt: "しゅうしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "収",
          on: ["シュウ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "集",
          on: ["シュウ"],
          kun: ["あつ.まる", "あつ.める", "つど.う"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
