export const n1part23 = {
  Lesson23: [
    {
      id: 1101,
      kanji: "足し算",
      reading: "たしざん",
      meanings: {
        ja: "足し算",
        en: "addition",
        zh: "加法",
        tw: "加法",
        ko: "덧셈",
        vi: "phép cộng",
        th: "การบวก",
        my: "ပေါင်းခြင်း",
        km: "បូកលេខ",
      },
      furigana: [
        {
          rb: "足し算",
          rt: "たしざん",
        },
      ],
      kanjiInfo: [
        {
          char: "足",
          on: ["ソク"],
          kun: ["あし", "た.りる", "た.る", "た.す"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1102,
      kanji: "多数決",
      reading: "たすうけつ",
      meanings: {
        ja: "多数決",
        en: "majority decision",
        zh: "多数决定",
        tw: "多數決",
        ko: "다수결",
        vi: "biểu quyết theo đa số",
        th: "การตัดสินโดยเสียงข้างมาก",
        my: "အများစုဆုံးဖြတ်ခြင်း",
        km: "ការសម្រេចដោយភាគច្រើន",
      },
      furigana: [
        {
          rb: "多数決",
          rt: "たすうけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "多",
          on: ["タ"],
          kun: ["おお.い", "まさ.に", "まさ.る"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1103,
      kanji: "助け",
      reading: "たすけ",
      meanings: {
        ja: "助け",
        en: "help; assistance",
        zh: "帮助",
        tw: "幫助",
        ko: "도움",
        vi: "sự giúp đỡ",
        th: "ความช่วยเหลือ",
        my: "အကူအညီ",
        km: "ជំនួយ",
      },
      furigana: [
        {
          rb: "助け",
          rt: "たすけ",
        },
      ],
      kanjiInfo: [
        {
          char: "助",
          on: ["ジョ"],
          kun: ["たす.ける", "たす.かる", "す.ける", "すけ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1104,
      kanji: "抱っこ",
      reading: "だっこ",
      meanings: {
        ja: "抱っこ",
        en: "holding a baby in one’s arms",
        zh: "抱着（婴儿）",
        tw: "抱（小孩）",
        ko: "안기",
        vi: "ôm em bé",
        th: "อุ้มเด็ก",
        my: "ကလေးကိုဖက်ခြင်း",
        km: "អោបកូន",
      },
      furigana: [
        {
          rb: "抱っこ",
          rt: "だっこ",
        },
      ],
      kanjiInfo: [
        {
          char: "抱",
          on: ["ホウ"],
          kun: ["だ.く", "いだ.く", "かか.える"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1105,
      kanji: "脱出",
      reading: "だっしゅつ",
      meanings: {
        ja: "脱出",
        en: "escape",
        zh: "逃脱",
        tw: "脫出",
        ko: "탈출",
        vi: "thoát khỏi",
        th: "หลบหนี",
        my: "လွတ်မြောက်ခြင်း",
        km: "ការជះចេញ",
      },
      furigana: [
        {
          rb: "脱出",
          rt: "だっしゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "脱",
          on: ["ダツ"],
          kun: ["ぬ.ぐ", "ぬ.げる"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1106,
      kanji: "達成",
      reading: "たっせい",
      meanings: {
        ja: "達成",
        en: "achievement",
        zh: "达成",
        tw: "達成",
        ko: "달성",
        vi: "đạt được",
        th: "บรรลุ",
        my: "အောင်မြင်ခြင်း",
        km: "សម្រេចបាន",
      },
      furigana: [
        {
          rb: "達成",
          rt: "たっせい",
        },
      ],
      kanjiInfo: [
        {
          char: "達",
          on: ["タツ", "ダ"],
          kun: ["-たち"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1107,
      kanji: "脱退",
      reading: "だったい",
      meanings: {
        ja: "脱退",
        en: "withdrawal (from a group)",
        zh: "退出",
        tw: "退出",
        ko: "탈퇴",
        vi: "rút lui",
        th: "ถอนตัวออก",
        my: "ထွက်ခြင်း",
        km: "ចាកចេញ",
      },
      furigana: [
        {
          rb: "脱退",
          rt: "だったい",
        },
      ],
      kanjiInfo: [
        {
          char: "脱",
          on: ["ダツ"],
          kun: ["ぬ.ぐ", "ぬ.げる"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1108,
      kanji: "建前",
      reading: "たてまえ",
      meanings: {
        ja: "建前",
        en: "public stance; facade",
        zh: "原则",
        tw: "表面立場",
        ko: "명분",
        vi: "lý do bề ngoài",
        th: "เหตุผลภายนอก",
        my: "အပြင်ဖက်အကြောင်းပြချက်",
        km: "មូលហេតុផ្លូវការ",
      },
      furigana: [
        {
          rb: "建前",
          rt: "たてまえ",
        },
      ],
      kanjiInfo: [
        {
          char: "建",
          on: ["ケン", "コン"],
          kun: ["た.てる", "た.て", "-だ.て", "た.つ"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1109,
      kanji: "他動詞",
      reading: "たどうし",
      meanings: {
        ja: "他動詞",
        en: "transitive verb",
        zh: "他动词",
        tw: "他動詞",
        ko: "타동사",
        vi: "ngoại động từ",
        th: "คำกริยาใช้กรรม",
        my: "အပြန်အလှန်ကြိယာ",
        km: "កិរិយាសព្ទប្រើកម្ម",
      },
      furigana: [
        {
          rb: "他動詞",
          rt: "たどうし",
        },
      ],
      kanjiInfo: [
        {
          char: "他",
          on: ["タ"],
          kun: ["ほか"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1110,
      kanji: "他方",
      reading: "たほう",
      meanings: {
        ja: "他方",
        en: "one side; on the other hand",
        zh: "另一方面",
        tw: "另一方面",
        ko: "한편",
        vi: "mặt khác",
        th: "อีกด้านหนึ่ง",
        my: "တစ်ဖက်ခြမ်း",
        km: "ចំណុចម្ខាងទៀត",
      },
      furigana: [
        {
          rb: "他方",
          rt: "たほう",
        },
      ],
      kanjiInfo: [
        {
          char: "他",
          on: ["タ"],
          kun: ["ほか"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1111,
      kanji: "多忙",
      reading: "たぼう",
      meanings: {
        ja: "多忙",
        en: "very busy",
        zh: "繁忙",
        tw: "繁忙",
        ko: "매우 바쁨",
        vi: "rất bận",
        th: "ยุ่งมาก",
        my: "အလွန်အမင်းအလုပ်များ",
        km: "រវល់ខ្លាំង",
      },
      furigana: [
        {
          rb: "多忙",
          rt: "たぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "多",
          on: ["タ"],
          kun: ["おお.い", "まさ.に", "まさ.る"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "忙",
          on: ["ボウ", "モウ"],
          kun: ["いそが.しい", "せわ.しい", "おそ.れる", "うれえるさま"],
          strokes: 6,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1112,
      kanji: "魂",
      reading: "たましい",
      meanings: {
        ja: "魂",
        en: "soul",
        zh: "灵魂",
        tw: "靈魂",
        ko: "영혼",
        vi: "linh hồn",
        th: "จิตวิญญาณ",
        my: "ဝိညာဉ်",
        km: "ព្រលឹង",
      },
      furigana: [
        {
          rb: "魂",
          rt: "たましい",
        },
      ],
      kanjiInfo: [
        {
          char: "魂",
          on: ["コン"],
          kun: ["たましい", "たま"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1113,
      kanji: "溜まり",
      reading: "たまり",
      meanings: {
        ja: "溜まり",
        en: "pool; accumulation",
        zh: "积聚",
        tw: "積聚",
        ko: "모임; 축적",
        vi: "tích tụ",
        th: "การสะสม",
        my: "စုဆောင်းမှု",
        km: "ការប្រមូលផ្តុំ",
      },
      furigana: [
        {
          rb: "溜まり",
          rt: "たまり",
        },
      ],
      kanjiInfo: [
        {
          char: "溜",
          on: ["リュウ"],
          kun: ["た.まる", "たま.る", "た.める", "したた.る", "たまり", "ため"],
          strokes: 13,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1114,
      kanji: "弛み",
      reading: "たるみ",
      meanings: {
        ja: "弛み",
        en: "slack; looseness",
        zh: "松弛",
        tw: "鬆弛",
        ko: "늘어짐",
        vi: "chùng xuống",
        th: "หย่อนคล้อย",
        my: "ပျောင်းခြင်း",
        km: "ស្រាលសន្លប់",
      },
      furigana: [
        {
          rb: "弛み",
          rt: "たるみ",
        },
      ],
      kanjiInfo: [
        {
          char: "弛",
          on: ["チ", "シ"],
          kun: ["たる.む", "たる.める", "たゆ.む", "ゆる.む", "ゆる.み"],
          strokes: 6,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1115,
      kanji: "タレント",
      reading: "タレント",
      meanings: {
        ja: "タレント",
        en: "TV personality",
        zh: "艺人",
        tw: "藝人",
        ko: "연예인",
        vi: "người nổi tiếng",
        th: "คนดัง",
        my: "တီဗွီအဖြစ်အပျက်",
        km: "តារាទូរទស្សន៍",
      },
      furigana: [
        {
          rb: "タレント",
          rt: "タレント",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1116,
      kanji: "タワー",
      reading: "タワー",
      meanings: {
        ja: "タワー",
        en: "tower",
        zh: "塔",
        tw: "塔",
        ko: "타워",
        vi: "tháp",
        th: "หอคอย",
        my: "မြှောက်တင်အဆောက်အအုံ",
        km: "ប៉ម",
      },
      furigana: [
        {
          rb: "タワー",
          rt: "タワー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1117,
      kanji: "短歌",
      reading: "たんか",
      meanings: {
        ja: "短歌",
        en: "tanka (poem)",
        zh: "短歌",
        tw: "短歌",
        ko: "단가",
        vi: "bài thơ tanka",
        th: "กลอนญี่ปุ่น (tanka)",
        my: "ဂျပန်အနှစ်ချုပ်ကဗျာ",
        km: "កំណាព្យតង់កា",
      },
      furigana: [
        {
          rb: "短歌",
          rt: "たんか",
        },
      ],
      kanjiInfo: [
        {
          char: "短",
          on: ["タン"],
          kun: ["みじか.い"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "歌",
          on: ["カ"],
          kun: ["うた", "うた.う"],
          strokes: 14,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1118,
      kanji: "担架",
      reading: "たんか",
      meanings: {
        ja: "担架",
        en: "stretcher",
        zh: "担架",
        tw: "擔架",
        ko: "들것",
        vi: "cáng cứu thương",
        th: "เปลหาม",
        my: "နောက်ခံစင်္ကြံ",
        km: "សាឡាំង",
      },
      furigana: [
        {
          rb: "担架",
          rt: "たんか",
        },
      ],
      kanjiInfo: [
        {
          char: "担",
          on: ["タン"],
          kun: ["かつ.ぐ", "にな.う"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "架",
          on: ["カ"],
          kun: ["か.ける", "か.かる"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1119,
      kanji: "短気",
      reading: "たんき",
      meanings: {
        ja: "短気",
        en: "short temper",
        zh: "急躁",
        tw: "急躁",
        ko: "성미 급함",
        vi: "nóng tính",
        th: "อารมณ์ร้อน",
        my: "စိတ်ပူလွယ်ခြင်း",
        km: "សភាពខឹងងាយ",
      },
      furigana: [
        {
          rb: "短気",
          rt: "たんき",
        },
      ],
      kanjiInfo: [
        {
          char: "短",
          on: ["タン"],
          kun: ["みじか.い"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1120,
      kanji: "団結",
      reading: "だんけつ",
      meanings: {
        ja: "団結",
        en: "unity",
        zh: "团结",
        tw: "團結",
        ko: "단결",
        vi: "đoàn kết",
        th: "ความสามัคคี",
        my: "သဟဇာတ",
        km: "សាមគ្គីភាព",
      },
      furigana: [
        {
          rb: "団結",
          rt: "だんけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "団",
          on: ["ダン", "トン"],
          kun: ["かたまり", "まる.い"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1121,
      kanji: "探検",
      reading: "たんけん",
      meanings: {
        ja: "探検",
        en: "exploration",
        zh: "探险",
        tw: "探險",
        ko: "탐험",
        vi: "thám hiểm",
        th: "การสำรวจ",
        my: "စူးစမ်းရေး",
        km: "ការស្ទង់អង្កេត",
      },
      furigana: [
        {
          rb: "探検",
          rt: "たんけん",
        },
      ],
      kanjiInfo: [
        {
          char: "探",
          on: ["タン"],
          kun: ["さぐ.る", "さが.す"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "検",
          on: ["ケン"],
          kun: ["しら.べる"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1122,
      kanji: "断言",
      reading: "だんげん",
      meanings: {
        ja: "断言",
        en: "assertion",
        zh: "断言",
        tw: "斷言",
        ko: "단언",
        vi: "khẳng định",
        th: "การยืนยันอย่างมั่นใจ",
        my: "အတည်ပြုခြင်း",
        km: "ការបញ្ជាក់",
      },
      furigana: [
        {
          rb: "断言",
          rt: "だんげん",
        },
      ],
      kanjiInfo: [
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1123,
      kanji: "短縮",
      reading: "たんしゅく",
      meanings: {
        ja: "短縮",
        en: "shortening",
        zh: "缩短",
        tw: "縮短",
        ko: "단축",
        vi: "rút ngắn",
        th: "การย่อ",
        my: "အတိုချုပ်ခြင်း",
        km: "ការកាត់បន្ថយ",
      },
      furigana: [
        {
          rb: "短縮",
          rt: "たんしゅく",
        },
      ],
      kanjiInfo: [
        {
          char: "短",
          on: ["タン"],
          kun: ["みじか.い"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "縮",
          on: ["シュク"],
          kun: ["ちぢ.む", "ちぢ.まる", "ちぢ.める", "ちぢ.れる", "ちぢ.らす"],
          strokes: 17,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1124,
      kanji: "炭素",
      reading: "たんそ",
      meanings: {
        ja: "炭素",
        en: "carbon",
        zh: "碳素",
        tw: "碳素",
        ko: "탄소",
        vi: "cacbon",
        th: "คาร์บอน",
        my: "ကာဗွန်",
        km: "កាបូន",
      },
      furigana: [
        {
          rb: "炭素",
          rt: "たんそ",
        },
      ],
      kanjiInfo: [
        {
          char: "炭",
          on: ["タン"],
          kun: ["すみ"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1125,
      kanji: "短大",
      reading: "たんだい",
      meanings: {
        ja: "短大",
        en: "junior college",
        zh: "短期大学",
        tw: "短期大學",
        ko: "단기대학",
        vi: "trường cao đẳng",
        th: "วิทยาลัย",
        my: "အနည်းဆုံးတက္ကသိုလ်",
        km: "វិទ្យាស្ថានឧត្តមសិក្សា",
      },
      furigana: [
        {
          rb: "短大",
          rt: "たんだい",
        },
      ],
      kanjiInfo: [
        {
          char: "短",
          on: ["タン"],
          kun: ["みじか.い"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1126,
      kanji: "旦那",
      reading: "だんな",
      meanings: {
        ja: "旦那",
        en: "husband; master",
        zh: "丈夫",
        tw: "老公",
        ko: "남편",
        vi: "chồng",
        th: "สามี",
        my: "အိမ်ထောင်သူ",
        km: "ប្ដី",
      },
      furigana: [
        {
          rb: "旦那",
          rt: "だんな",
        },
      ],
      kanjiInfo: [
        {
          char: "旦",
          on: ["タン", "ダン"],
          kun: ["あき.らか", "あきら", "ただし", "あさ", "あした"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "那",
          on: ["ナ", "ダ"],
          kun: ["なに", "なんぞ", "いかん"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1127,
      kanji: "短波",
      reading: "たんぱ",
      meanings: {
        ja: "短波",
        en: "shortwave radio",
        zh: "短波",
        tw: "短波",
        ko: "단파",
        vi: "sóng ngắn",
        th: "คลื่นสั้น",
        my: "အလှည့်တိုလှိုင်း",
        km: "រលកខ្លី",
      },
      furigana: [
        {
          rb: "短波",
          rt: "たんぱ",
        },
      ],
      kanjiInfo: [
        {
          char: "短",
          on: ["タン"],
          kun: ["みじか.い"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "波",
          on: ["ハ"],
          kun: ["なみ"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1128,
      kanji: "蛋白質",
      reading: "たんぱくしつ",
      meanings: {
        ja: "蛋白質",
        en: "protein",
        zh: "蛋白质",
        tw: "蛋白質",
        ko: "단백질",
        vi: "chất đạm",
        th: "โปรตีน",
        my: "ပရိုတိန်း",
        km: "ប្រូតេអ៊ីន",
      },
      furigana: [
        {
          rb: "蛋白質",
          rt: "たんぱくしつ",
        },
      ],
      kanjiInfo: [
        {
          char: "蛋",
          on: ["タン"],
          kun: [],
          strokes: 11,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
        {
          char: "白",
          on: ["ハク", "ビャク"],
          kun: ["しろ", "しら-", "しろ.い"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1129,
      kanji: "ダンプ",
      reading: "ダンプ",
      meanings: {
        ja: "ダンプ",
        en: "dump; dump truck",
        zh: "倾卸卡车",
        tw: "卡車",
        ko: "덤프",
        vi: "xe ben",
        th: "รถดัมพ์",
        my: "ဆောက်လုပ်ရေးကား",
        km: "ឡានដាក់បាយ",
      },
      furigana: [
        {
          rb: "ダンプ",
          rt: "ダンプ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1130,
      kanji: "断面",
      reading: "だんめん",
      meanings: {
        ja: "断面",
        en: "cross section",
        zh: "横截面",
        tw: "橫切面",
        ko: "단면",
        vi: "mặt cắt ngang",
        th: "หน้าตัด",
        my: "အတုံးဖြတ်",
        km: "ផ្នែកកាត់",
      },
      furigana: [
        {
          rb: "断面",
          rt: "だんめん",
        },
      ],
      kanjiInfo: [
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1131,
      kanji: "弾力",
      reading: "だんりょく",
      meanings: {
        ja: "弾力",
        en: "elasticity",
        zh: "弹力",
        tw: "彈力",
        ko: "탄력",
        vi: "độ đàn hồi",
        th: "ความยืดหยุ่น",
        my: "တင်းတိပ်",
        km: "ភាពយឺតយ៉ាវ",
      },
      furigana: [
        {
          rb: "弾力",
          rt: "だんりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "弾",
          on: ["ダン", "タン"],
          kun: [
            "ひ.く",
            "-ひ.き",
            "はず.む",
            "たま",
            "はじ.く",
            "はじ.ける",
            "ただ.す",
            "はじ.きゆみ",
          ],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1132,
      kanji: "治安",
      reading: "ちあん",
      meanings: {
        ja: "治安",
        en: "public order",
        zh: "治安",
        tw: "治安",
        ko: "치안",
        vi: "trị an",
        th: "ความสงบเรียบร้อย",
        my: "တည်ငြိမ်ရေး",
        km: "សន្តិសុខសាធារណៈ",
      },
      furigana: [
        {
          rb: "治安",
          rt: "ちあん",
        },
      ],
      kanjiInfo: [
        {
          char: "治",
          on: ["ジ", "チ"],
          kun: ["おさ.める", "おさ.まる", "なお.る", "なお.す"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "安",
          on: ["アン"],
          kun: ["やす.い", "やす.まる", "やす", "やす.らか"],
          strokes: 6,
          grade: 3,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1133,
      kanji: "チームワーク",
      reading: "チームワーク",
      meanings: {
        ja: "チームワーク",
        en: "teamwork",
        zh: "团队合作",
        tw: "團隊合作",
        ko: "팀워크",
        vi: "làm việc nhóm",
        th: "การทำงานเป็นทีม",
        my: "အဖွဲ့လိုက်အလုပ်လုပ်ခြင်း",
        km: "ការងារជាក្រុម",
      },
      furigana: [
        {
          rb: "チームワーク",
          rt: "チームワーク",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1134,
      kanji: "チェンジ",
      reading: "チェンジ",
      meanings: {
        ja: "チェンジ",
        en: "change; exchange",
        zh: "交换",
        tw: "交換",
        ko: "체인지",
        vi: "thay đổi",
        th: "การเปลี่ยน",
        my: "ပြောင်းလဲခြင်း",
        km: "ការផ្លាស់ប្តូរ",
      },
      furigana: [
        {
          rb: "チェンジ",
          rt: "チェンジ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1135,
      kanji: "畜産",
      reading: "ちくさん",
      meanings: {
        ja: "畜産",
        en: "livestock industry",
        zh: "畜牧业",
        tw: "畜牧業",
        ko: "축산",
        vi: "chăn nuôi",
        th: "ปศุสัตว์",
        my: "မွေးမြူရေး",
        km: "ចិញ្ចឹមសត្វ",
      },
      furigana: [
        {
          rb: "畜産",
          rt: "ちくさん",
        },
      ],
      kanjiInfo: [
        {
          char: "畜",
          on: ["チク"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1136,
      kanji: "蓄積",
      reading: "ちくせき",
      meanings: {
        ja: "蓄積",
        en: "accumulation",
        zh: "积累",
        tw: "累積",
        ko: "축적",
        vi: "tích lũy",
        th: "การสะสม",
        my: "စုဆောင်းခြင်း",
        km: "ការប្រមូលផ្តុំ",
      },
      furigana: [
        {
          rb: "蓄積",
          rt: "ちくせき",
        },
      ],
      kanjiInfo: [
        {
          char: "蓄",
          on: ["チク"],
          kun: ["たくわ.える"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "積",
          on: ["セキ"],
          kun: ["つ.む", "-づ.み", "つ.もる", "つ.もり"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1137,
      kanji: "地形",
      reading: "ちけい",
      meanings: {
        ja: "地形",
        en: "terrain",
        zh: "地形",
        tw: "地形",
        ko: "지형",
        vi: "địa hình",
        th: "ภูมิประเทศ",
        my: "မြေပြင်သဏ္ဌာန်",
        km: "ផ្ទៃដី",
      },
      furigana: [
        {
          rb: "地形",
          rt: "ちけい",
        },
      ],
      kanjiInfo: [
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "形",
          on: ["ケイ", "ギョウ"],
          kun: ["かた", "-がた", "かたち", "なり"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1138,
      kanji: "知性",
      reading: "ちせい",
      meanings: {
        ja: "知性",
        en: "intellect",
        zh: "智慧",
        tw: "知性",
        ko: "지성",
        vi: "trí tuệ",
        th: "ปัญญา",
        my: "ဗုဒ္ဓိ",
        km: "បញ្ញា",
      },
      furigana: [
        {
          rb: "知性",
          rt: "ちせい",
        },
      ],
      kanjiInfo: [
        {
          char: "知",
          on: ["チ"],
          kun: ["し.る", "し.らせる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "性",
          on: ["セイ", "ショウ"],
          kun: ["さが"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1139,
      kanji: "乳",
      reading: "ちち",
      meanings: {
        ja: "乳",
        en: "milk; breast",
        zh: "乳; 奶",
        tw: "乳; 奶",
        ko: "젖",
        vi: "sữa",
        th: "น้ำนม",
        my: "နို့",
        km: "ទឹកដោះ",
      },
      furigana: [
        {
          rb: "乳",
          rt: "ちち",
        },
      ],
      kanjiInfo: [
        {
          char: "乳",
          on: ["ニュウ"],
          kun: ["ちち", "ち"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1140,
      kanji: "秩序",
      reading: "ちつじょ",
      meanings: {
        ja: "秩序",
        en: "order; discipline",
        zh: "秩序",
        tw: "秩序",
        ko: "질서",
        vi: "trật tự",
        th: "ระเบียบ",
        my: "အစဉ်အလာ",
        km: "របៀបរៀបរយ",
      },
      furigana: [
        {
          rb: "秩序",
          rt: "ちつじょ",
        },
      ],
      kanjiInfo: [
        {
          char: "秩",
          on: ["チツ"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "序",
          on: ["ジョ"],
          kun: ["つい.で", "ついで"],
          strokes: 7,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1141,
      kanji: "窒息",
      reading: "ちっそく",
      meanings: {
        ja: "窒息",
        en: "suffocation",
        zh: "窒息",
        tw: "窒息",
        ko: "질식",
        vi: "ngạt thở",
        th: "ขาดอากาศหายใจ",
        my: "အသက်ရှူမဝခြင်း",
        km: "ស្លាប់ដោយសារសង្ស័យ",
      },
      furigana: [
        {
          rb: "窒息",
          rt: "ちっそく",
        },
      ],
      kanjiInfo: [
        {
          char: "窒",
          on: ["チツ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "息",
          on: ["ソク"],
          kun: ["いき"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1142,
      kanji: "着手",
      reading: "ちゃくしゅ",
      meanings: {
        ja: "着手",
        en: "starting work",
        zh: "着手",
        tw: "著手",
        ko: "착수",
        vi: "bắt đầu",
        th: "เริ่มทำงาน",
        my: "စတင်ဆောင်ရွက်ခြင်း",
        km: "ចាប់ផ្តើមអនុវត្ត",
      },
      furigana: [
        {
          rb: "着手",
          rt: "ちゃくしゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1143,
      kanji: "着色",
      reading: "ちゃくしょく",
      meanings: {
        ja: "着色",
        en: "coloring",
        zh: "着色",
        tw: "著色",
        ko: "착색",
        vi: "tô màu",
        th: "การระบายสี",
        my: "အရောင်ထည့်ခြင်း",
        km: "លាបពណ៌",
      },
      furigana: [
        {
          rb: "着色",
          rt: "ちゃくしょく",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "色",
          on: ["ショク", "シキ"],
          kun: ["いろ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1144,
      kanji: "着席",
      reading: "ちゃくせき",
      meanings: {
        ja: "着席",
        en: "taking a seat",
        zh: "就座",
        tw: "就座",
        ko: "착석",
        vi: "ngồi xuống",
        th: "นั่งลง",
        my: "ထိုင်ခြင်း",
        km: "អង្គុយ",
      },
      furigana: [
        {
          rb: "着席",
          rt: "ちゃくせき",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "席",
          on: ["セキ"],
          kun: ["むしろ"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1145,
      kanji: "着目",
      reading: "ちゃくもく",
      meanings: {
        ja: "着目",
        en: "attention",
        zh: "关注",
        tw: "注目",
        ko: "주목",
        vi: "chú ý",
        th: "การให้ความสนใจ",
        my: "ဂရုပြုခြင်း",
        km: "ការផ្តោតអារម្មណ៍",
      },
      furigana: [
        {
          rb: "着目",
          rt: "ちゃくもく",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1146,
      kanji: "着陸",
      reading: "ちゃくりく",
      meanings: {
        ja: "着陸",
        en: "landing",
        zh: "着陆",
        tw: "著陸",
        ko: "착륙",
        vi: "hạ cánh",
        th: "การลงจอด",
        my: "မြေပြင်ဆင်းခြင်း",
        km: "ចុះចត",
      },
      furigana: [
        {
          rb: "着陸",
          rt: "ちゃくりく",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "陸",
          on: ["リク", "ロク"],
          kun: ["おか"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1147,
      kanji: "着工",
      reading: "ちゃっこう",
      meanings: {
        ja: "着工",
        en: "commencement of construction",
        zh: "开工",
        tw: "開工",
        ko: "착공",
        vi: "khởi công",
        th: "เริ่มก่อสร้าง",
        my: "တည်ဆောက်ခြင်းစတင်ခြင်း",
        km: "ចាប់ផ្តើមសំណង់",
      },
      furigana: [
        {
          rb: "着工",
          rt: "ちゃっこう",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "工",
          on: ["コウ", "ク", "グ"],
          kun: [],
          strokes: 3,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1148,
      kanji: "茶の間",
      reading: "ちゃのま",
      meanings: {
        ja: "茶の間",
        en: "living room",
        zh: "起居室",
        tw: "客廳",
        ko: "거실",
        vi: "phòng khách",
        th: "ห้องนั่งเล่น",
        my: "အခန်းလှန်",
        km: "បន្ទប់ទទួលភ្ញៀវ",
      },
      furigana: [
        {
          rb: "茶の間",
          rt: "ちゃのま",
        },
      ],
      kanjiInfo: [
        {
          char: "茶",
          on: ["チャ", "サ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1149,
      kanji: "茶の湯",
      reading: "ちゃのゆ",
      meanings: {
        ja: "茶の湯",
        en: "tea ceremony",
        zh: "茶道",
        tw: "茶道",
        ko: "다도",
        vi: "trà đạo",
        th: "พิธีชงชา",
        my: "လက်ဖက်ရည်အခမ်းအနား",
        km: "ពិធីតែ",
      },
      furigana: [
        {
          rb: "茶の湯",
          rt: "ちゃのゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "茶",
          on: ["チャ", "サ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "湯",
          on: ["トウ"],
          kun: ["ゆ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1150,
      kanji: "チャンネル",
      reading: "チャンネル",
      meanings: {
        ja: "チャンネル",
        en: "channel",
        zh: "频道",
        tw: "頻道",
        ko: "채널",
        vi: "kênh",
        th: "ช่อง",
        my: "ချန်နယ်",
        km: "ឆានែល",
      },
      furigana: [
        {
          rb: "チャンネル",
          rt: "チャンネル",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
