export const n1part21 = {
  Lesson21: [
    {
      id: 1001,
      kanji: "設立",
      reading: "せつりつ",
      meanings: {
        ja: "設立",
        en: "establishment; founding",
        zh: "设立",
        tw: "設立",
        ko: "설립",
        vi: "thành lập",
        th: "การก่อตั้ง",
        my: "တည်ထောင်ခြင်း",
        km: "ការបង្កើត",
      },
      furigana: [
        {
          rb: "設立",
          rt: "せつりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "設",
          on: ["セツ"],
          kun: ["もう.ける"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "立",
          on: ["リツ", "リュウ", "リットル"],
          kun: [
            "た.つ",
            "-た.つ",
            "た.ち-",
            "た.てる",
            "-た.てる",
            "た.て-",
            "たて-",
            "-た.て",
            "-だ.て",
            "-だ.てる",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1002,
      kanji: "攻め",
      reading: "せめ",
      meanings: {
        ja: "攻め",
        en: "attack (n.)",
        zh: "进攻（名）",
        tw: "進攻（名）",
        ko: "공격(명)",
        vi: "tấn công (danh)",
        th: "การบุก",
        my: "တိုက်ခိုက်မှု",
        km: "ការវាយប្រហារ",
      },
      furigana: [
        {
          rb: "攻め",
          rt: "せめ",
        },
      ],
      kanjiInfo: [
        {
          char: "攻",
          on: ["コウ"],
          kun: ["せ.める"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1003,
      kanji: "ゼリー",
      reading: "ゼリー",
      meanings: {
        ja: "ゼリー",
        en: "jelly; jello",
        zh: "果冻",
        tw: "果凍",
        ko: "젤리",
        vi: "thạch",
        th: "เยลลี่",
        my: "ဂျెలလီ",
        km: "ជេលី",
      },
      furigana: [
        {
          rb: "ゼリー",
          rt: "ゼリー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1004,
      kanji: "セレモニー",
      reading: "セレモニー",
      meanings: {
        ja: "セレモニー",
        en: "ceremony",
        zh: "典礼；仪式",
        tw: "典禮；儀式",
        ko: "세리머니; 의식",
        vi: "nghi lễ",
        th: "พิธี",
        my: "အခမ်းအနား",
        km: "ពិធីការណ៍",
      },
      furigana: [
        {
          rb: "セレモニー",
          rt: "セレモニー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1005,
      kanji: "世論",
      reading: "せろん",
      meanings: {
        ja: "世論",
        en: "public opinion",
        zh: "舆论",
        tw: "輿論",
        ko: "여론",
        vi: "dư luận",
        th: "ความเห็นสาธารณะ",
        my: "ပြည်သူ့အမြင်",
        km: "មតិសាធារណៈ",
      },
      furigana: [
        {
          rb: "世論",
          rt: "せろん",
        },
      ],
      kanjiInfo: [
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1006,
      kanji: "繊維",
      reading: "せんい",
      meanings: {
        ja: "繊維",
        en: "fiber",
        zh: "纤维",
        tw: "纖維",
        ko: "섬유",
        vi: "sợi; chất xơ",
        th: "เส้นใย",
        my: "တစ်စင်းစင်း(ဖိုဘာ)",
        km: "សរសៃ",
      },
      furigana: [
        {
          rb: "繊維",
          rt: "せんい",
        },
      ],
      kanjiInfo: [
        {
          char: "繊",
          on: ["セン"],
          kun: [],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "維",
          on: ["イ"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1007,
      kanji: "全快",
      reading: "ぜんかい",
      meanings: {
        ja: "全快",
        en: "complete recovery",
        zh: "痊愈",
        tw: "痊癒",
        ko: "완쾌",
        vi: "bình phục hoàn toàn",
        th: "หายดี",
        my: "ပြန်ကောင်းလုံးဝ",
        km: "ជាសះស្បើយ",
      },
      furigana: [
        {
          rb: "全快",
          rt: "ぜんかい",
        },
      ],
      kanjiInfo: [
        {
          char: "全",
          on: ["ゼン"],
          kun: ["まった.く", "すべ.て"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "快",
          on: ["カイ"],
          kun: ["こころよ.い"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1008,
      kanji: "宣教",
      reading: "せんきょう",
      meanings: {
        ja: "宣教",
        en: "missionary work",
        zh: "传教",
        tw: "宣教",
        ko: "선교",
        vi: "truyền giáo",
        th: "งานเผยแผ่ศาสนา",
        my: "မစ္စနာရီလုပ်ငန်း",
        km: "ការប្រកាសសាសនា",
      },
      furigana: [
        {
          rb: "宣教",
          rt: "せんきょう",
        },
      ],
      kanjiInfo: [
        {
          char: "宣",
          on: ["セン"],
          kun: ["のたま.う"],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "教",
          on: ["キョウ"],
          kun: ["おし.える", "おそ.わる"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1009,
      kanji: "宣言",
      reading: "せんげん",
      meanings: {
        ja: "宣言",
        en: "declaration",
        zh: "宣言",
        tw: "宣言",
        ko: "선언",
        vi: "tuyên ngôn",
        th: "ประกาศ",
        my: "ကြေညာချက်",
        km: "សេចក្តីប្រកាស",
      },
      furigana: [
        {
          rb: "宣言",
          rt: "せんげん",
        },
      ],
      kanjiInfo: [
        {
          char: "宣",
          on: ["セン"],
          kun: ["のたま.う"],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1010,
      kanji: "戦災",
      reading: "せんさい",
      meanings: {
        ja: "戦災",
        en: "war damage",
        zh: "战灾",
        tw: "戰災",
        ko: "전재",
        vi: "thiệt hại do chiến tranh",
        th: "ความเสียหายจากสงคราม",
        my: "စစ်ဘေးအန္တရာယ်",
        km: "គ្រោះមហន្តរាយសង្គ្រាម",
      },
      furigana: [
        {
          rb: "戦災",
          rt: "せんさい",
        },
      ],
      kanjiInfo: [
        {
          char: "戦",
          on: ["セン"],
          kun: ["いくさ", "たたか.う", "おのの.く", "そよ.ぐ", "わなな.く"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "災",
          on: ["サイ"],
          kun: ["わざわ.い"],
          strokes: 7,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1011,
      kanji: "専修",
      reading: "せんしゅう",
      meanings: {
        ja: "専修",
        en: "specialization",
        zh: "专修",
        tw: "專修",
        ko: "전수/전공수업",
        vi: "chuyên tu",
        th: "การเรียนเฉพาะทาง",
        my: "အထူးပြုလေ့လာ",
        km: "ការសិក្សាពិសេស",
      },
      furigana: [
        {
          rb: "専修",
          rt: "せんしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "専",
          on: ["セン"],
          kun: ["もっぱ.ら"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "修",
          on: ["シュウ", "シュ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1012,
      kanji: "戦術",
      reading: "せんじゅつ",
      meanings: {
        ja: "戦術",
        en: "tactics",
        zh: "战术",
        tw: "戰術",
        ko: "전술",
        vi: "chiến thuật",
        th: "ยุทธวิธี",
        my: "ยุทธဗျူဟာသေး",
        km: "យុទ្ធសាស្ត្រ(តាក់ស៊ីក)",
      },
      furigana: [
        {
          rb: "戦術",
          rt: "せんじゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "戦",
          on: ["セン"],
          kun: ["いくさ", "たたか.う", "おのの.く", "そよ.ぐ", "わなな.く"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "術",
          on: ["ジュツ"],
          kun: ["すべ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1013,
      kanji: "センス",
      reading: "センス",
      meanings: {
        ja: "センス",
        en: "sense; taste",
        zh: "品味；感觉",
        tw: "品味；感覺",
        ko: "감각; 센스",
        vi: "cảm quan; gu",
        th: "เซนส์; รสนิยม",
        my: "ခံစားချက်/ဂု",
        km: "រសជាតិ; អារម្មណ៍",
      },
      furigana: [
        {
          rb: "センス",
          rt: "センス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1014,
      kanji: "潜水",
      reading: "せんすい",
      meanings: {
        ja: "潜水",
        en: "diving",
        zh: "潜水",
        tw: "潛水",
        ko: "잠수",
        vi: "lặn",
        th: "ดำน้ำ",
        my: "မျော‌့ရေ",
        km: "លោតទឹក/潜水",
      },
      furigana: [
        {
          rb: "潜水",
          rt: "せんすい",
        },
      ],
      kanjiInfo: [
        {
          char: "潜",
          on: ["セン"],
          kun: ["ひそ.む", "もぐ.る", "かく.れる", "くぐ.る", "ひそ.める"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1015,
      kanji: "全盛",
      reading: "ぜんせい",
      meanings: {
        ja: "全盛",
        en: "heyday",
        zh: "全盛期",
        tw: "全盛期",
        ko: "전성기",
        vi: "thời hoàng kim",
        th: "ยุครุ่งเรือง",
        my: "တိုးတက်ထွန်းကားဆုံးကာလ",
        km: "រុងរឿងខ្លាំងបំផុត",
      },
      furigana: [
        {
          rb: "全盛",
          rt: "ぜんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "全",
          on: ["ゼン"],
          kun: ["まった.く", "すべ.て"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "盛",
          on: ["セイ", "ジョウ"],
          kun: ["も.る", "さか.る", "さか.ん"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1016,
      kanji: "先代",
      reading: "せんだい",
      meanings: {
        ja: "先代",
        en: "previous generation",
        zh: "上一代",
        tw: "上一代",
        ko: "선대",
        vi: "đời trước",
        th: "รุ่นก่อน",
        my: "ယခင်မျိုးစိတ်",
        km: "ជំនាន់មុន",
      },
      furigana: [
        {
          rb: "先代",
          rt: "せんだい",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1017,
      kanji: "先だって",
      reading: "せんだって",
      meanings: {
        ja: "先だって",
        en: "the other day; recently",
        zh: "前几天",
        tw: "前幾天",
        ko: "요전에",
        vi: "mới đây",
        th: "เมื่อวันก่อน",
        my: "မကြာသေးမီက",
        km: "ម្សិលមិញៗ",
      },
      furigana: [
        {
          rb: "先だって",
          rt: "せんだって",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1018,
      kanji: "先着",
      reading: "せんちゃく",
      meanings: {
        ja: "先着",
        en: "first arrival",
        zh: "先到",
        tw: "先到",
        ko: "선착",
        vi: "đến trước",
        th: "ถึงก่อน",
        my: "ဦးစွာရောက်",
        km: "មកដល់មុន",
      },
      furigana: [
        {
          rb: "先着",
          rt: "せんちゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1019,
      kanji: "前提",
      reading: "ぜんてい",
      meanings: {
        ja: "前提",
        en: "premise; condition",
        zh: "前提；条件",
        tw: "前提；條件",
        ko: "전제",
        vi: "tiền đề; điều kiện",
        th: "ข้อกำหนดเบื้องต้น",
        my: "အခြေခံအချက်",
        km: "លក្ខខណ្ឌដើម",
      },
      furigana: [
        {
          rb: "前提",
          rt: "ぜんてい",
        },
      ],
      kanjiInfo: [
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "提",
          on: ["テイ", "チョウ", "ダイ"],
          kun: ["さ.げる"],
          strokes: 12,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1020,
      kanji: "前途",
      reading: "ぜんと",
      meanings: {
        ja: "前途",
        en: "future prospects",
        zh: "前途",
        tw: "前途",
        ko: "전도",
        vi: "tiền đồ",
        th: "อนาคตข้างหน้า",
        my: "အနာဂတ်အလားအလာ",
        km: "អនាគតខាងមុខ",
      },
      furigana: [
        {
          rb: "前途",
          rt: "ぜんと",
        },
      ],
      kanjiInfo: [
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "途",
          on: ["ト"],
          kun: ["みち"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1021,
      kanji: "戦闘",
      reading: "せんとう",
      meanings: {
        ja: "戦闘",
        en: "combat; battle",
        zh: "战斗",
        tw: "戰鬥",
        ko: "전투",
        vi: "chiến đấu",
        th: "การรบ",
        my: "စစ်တိုက်ပွဲ",
        km: "យុទ្ធប្រយុទ្ធ",
      },
      furigana: [
        {
          rb: "戦闘",
          rt: "せんとう",
        },
      ],
      kanjiInfo: [
        {
          char: "戦",
          on: ["セン"],
          kun: ["いくさ", "たたか.う", "おのの.く", "そよ.ぐ", "わなな.く"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "闘",
          on: ["トウ"],
          kun: ["たたか.う", "あらそ.う"],
          strokes: 18,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1022,
      kanji: "潜入",
      reading: "せんにゅう",
      meanings: {
        ja: "潜入",
        en: "infiltration",
        zh: "潜入",
        tw: "潛入",
        ko: "침투",
        vi: "thâm nhập",
        th: "แฝงตัวเข้าไป",
        my: "လျှို့ဝှက်စွန့်ဝင်",
        km: "គ្រាងចូល",
      },
      furigana: [
        {
          rb: "潜入",
          rt: "せんにゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "潜",
          on: ["セン"],
          kun: ["ひそ.む", "もぐ.る", "かく.れる", "くぐ.る", "ひそ.める"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1023,
      kanji: "船舶",
      reading: "せんぱく",
      meanings: {
        ja: "船舶",
        en: "ships; vessels",
        zh: "船舶",
        tw: "船舶",
        ko: "선박",
        vi: "tàu thuyền",
        th: "เรือพาณิชย์",
        my: "သင်္ဘောများ",
        km: "នាវាចរ",
      },
      furigana: [
        {
          rb: "船舶",
          rt: "せんぱく",
        },
      ],
      kanjiInfo: [
        {
          char: "船",
          on: ["セン"],
          kun: ["ふね", "ふな-"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "舶",
          on: ["ハク"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1024,
      kanji: "全滅",
      reading: "ぜんめつ",
      meanings: {
        ja: "全滅",
        en: "annihilation; wipeout",
        zh: "全灭",
        tw: "全滅",
        ko: "전멸",
        vi: "tiêu diệt hoàn toàn",
        th: "ถูกล้างบาง",
        my: "ပျက်စီးကုန်",
        km: "ផុតសង្ឃឹមទាំងស្រុង",
      },
      furigana: [
        {
          rb: "全滅",
          rt: "ぜんめつ",
        },
      ],
      kanjiInfo: [
        {
          char: "全",
          on: ["ゼン"],
          kun: ["まった.く", "すべ.て"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "滅",
          on: ["メツ"],
          kun: ["ほろ.びる", "ほろ.ぶ", "ほろ.ぼす"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1025,
      kanji: "専用",
      reading: "せんよう",
      meanings: {
        ja: "専用",
        en: "exclusive use",
        zh: "专用",
        tw: "專用",
        ko: "전용",
        vi: "chuyên dụng",
        th: "ใช้เฉพาะ",
        my: "သီးသန့်အသုံး",
        km: "ប្រើប្រាស់ពិសេស",
      },
      furigana: [
        {
          rb: "専用",
          rt: "せんよう",
        },
      ],
      kanjiInfo: [
        {
          char: "専",
          on: ["セン"],
          kun: ["もっぱ.ら"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1026,
      kanji: "占領",
      reading: "せんりょう",
      meanings: {
        ja: "占領",
        en: "occupation",
        zh: "占领",
        tw: "佔領",
        ko: "점령",
        vi: "chiếm đóng",
        th: "ยึดครอง",
        my: "ချုပ်ခေါင်းယူခြင်း",
        km: "កាន់កាប់",
      },
      furigana: [
        {
          rb: "占領",
          rt: "せんりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "占",
          on: ["セン"],
          kun: ["し.める", "うらな.う"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "領",
          on: ["リョウ"],
          kun: ["えり"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1027,
      kanji: "戦力",
      reading: "せんりょく",
      meanings: {
        ja: "戦力",
        en: "war potential; capability",
        zh: "战力",
        tw: "戰力",
        ko: "전력",
        vi: "sức mạnh chiến đấu",
        th: "กำลังรบ",
        my: "စစ်ဗல",
        km: "កម្លាំងយោធា",
      },
      furigana: [
        {
          rb: "戦力",
          rt: "せんりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "戦",
          on: ["セン"],
          kun: ["いくさ", "たたか.う", "おのの.く", "そよ.ぐ", "わなな.く"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1028,
      kanji: "前例",
      reading: "ぜんれい",
      meanings: {
        ja: "前例",
        en: "precedent",
        zh: "前例",
        tw: "前例",
        ko: "전례",
        vi: "tiền lệ",
        th: "แบบอย่างก่อน",
        my: "လက်ရှိမတိုင်မီဥပမာ",
        km: "ដំណើរមុន",
      },
      furigana: [
        {
          rb: "前例",
          rt: "ぜんれい",
        },
      ],
      kanjiInfo: [
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "例",
          on: ["レイ"],
          kun: ["たと.える"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1029,
      kanji: "総会",
      reading: "そうかい",
      meanings: {
        ja: "総会",
        en: "general meeting",
        zh: "大会；股东大会",
        tw: "大會；股東會",
        ko: "총회",
        vi: "đại hội; họp toàn thể",
        th: "การประชุมใหญ่",
        my: "အထွေထွေအစည်းအဝေး",
        km: "សន្និបាតទូទៅ",
      },
      furigana: [
        {
          rb: "総会",
          rt: "そうかい",
        },
      ],
      kanjiInfo: [
        {
          char: "総",
          on: ["ソウ"],
          kun: ["す.べて", "すべ.て", "ふさ"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1030,
      kanji: "創刊",
      reading: "そうかん",
      meanings: {
        ja: "創刊",
        en: "launch of first issue",
        zh: "创刊",
        tw: "創刊",
        ko: "창간",
        vi: "khai sáng (số đầu)",
        th: "ออกฉบับปฐมฤกษ์",
        my: "မဂ္ဂဇင်း/စာနယ်ဇင်း စတင်ထုတ်",
        km: "ការចាប់ផ្ដើមច្បាប់ទី១",
      },
      furigana: [
        {
          rb: "創刊",
          rt: "そうかん",
        },
      ],
      kanjiInfo: [
        {
          char: "創",
          on: ["ソウ", "ショウ"],
          kun: ["つく.る", "はじ.める", "きず", "けず.しける"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "刊",
          on: ["カン"],
          kun: [],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1031,
      kanji: "雑木",
      reading: "ぞうき",
      meanings: {
        ja: "雑木",
        en: "assorted small trees",
        zh: "杂木",
        tw: "雜木",
        ko: "잡목",
        vi: "cây tạp",
        th: "ไม้พุ่มหลากชนิด",
        my: "သစ်ပင်ကွဲမျိုး",
        km: "ដើមឈើចម្រុះ",
      },
      furigana: [
        {
          rb: "雑木",
          rt: "ぞうき",
        },
      ],
      kanjiInfo: [
        {
          char: "雑",
          on: ["ザツ", "ゾウ"],
          kun: ["まじ.える", "まじ.る"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "木",
          on: ["ボク", "モク"],
          kun: ["き", "こ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1032,
      kanji: "増強",
      reading: "ぞうきょう",
      meanings: {
        ja: "増強",
        en: "reinforcement; buildup",
        zh: "增强",
        tw: "增強",
        ko: "증강",
        vi: "tăng cường",
        th: "เสริมกำลัง",
        my: "တိုးမြှင့်",
        km: "បន្ថែមកម្លាំង",
      },
      furigana: [
        {
          rb: "増強",
          rt: "ぞうきょう",
        },
      ],
      kanjiInfo: [
        {
          char: "増",
          on: ["ゾウ"],
          kun: ["ま.す", "ま.し", "ふ.える", "ふ.やす"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "強",
          on: ["キョウ", "ゴウ"],
          kun: ["つよ.い", "つよ.まる", "つよ.める", "し.いる", "こわ.い"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1033,
      kanji: "送金",
      reading: "そうきん",
      meanings: {
        ja: "送金",
        en: "remittance",
        zh: "汇款",
        tw: "匯款",
        ko: "송금",
        vi: "chuyển tiền",
        th: "โอนเงิน",
        my: "ငွေလွှဲ",
        km: "ផ្ញើលុយ",
      },
      furigana: [
        {
          rb: "送金",
          rt: "そうきん",
        },
      ],
      kanjiInfo: [
        {
          char: "送",
          on: ["ソウ"],
          kun: ["おく.る"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1034,
      kanji: "走行",
      reading: "そうこう",
      meanings: {
        ja: "走行",
        en: "running/driving (vehicle)",
        zh: "行驶",
        tw: "行駛",
        ko: "주행",
        vi: "chạy xe",
        th: "วิ่ง (ยานพาหนะ)",
        my: "မောင်းနှင်ခြင်း",
        km: "បើកបរ",
      },
      furigana: [
        {
          rb: "走行",
          rt: "そうこう",
        },
      ],
      kanjiInfo: [
        {
          char: "走",
          on: ["ソウ"],
          kun: ["はし.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1035,
      kanji: "総合",
      reading: "そうごう",
      meanings: {
        ja: "総合",
        en: "synthesis; integrated",
        zh: "综合",
        tw: "綜合",
        ko: "종합",
        vi: "tổng hợp",
        th: "บูรณาการ",
        my: "စုစည်းမှု",
        km: "សរុបរួម",
      },
      furigana: [
        {
          rb: "総合",
          rt: "そうごう",
        },
      ],
      kanjiInfo: [
        {
          char: "総",
          on: ["ソウ"],
          kun: ["す.べて", "すべ.て", "ふさ"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1036,
      kanji: "捜索",
      reading: "そうさく",
      meanings: {
        ja: "捜索",
        en: "search (for missing)",
        zh: "搜寻",
        tw: "搜尋",
        ko: "수색",
        vi: "tìm kiếm (người/vật mất)",
        th: "ค้นหา (ผู้สูญหาย)",
        my: "ရှာဖွေမြှောက်",
        km: "ស្វែងរក",
      },
      furigana: [
        {
          rb: "捜索",
          rt: "そうさく",
        },
      ],
      kanjiInfo: [
        {
          char: "捜",
          on: ["ソウ", "シュ", "シュウ"],
          kun: ["さが.す"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "索",
          on: ["サク"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1037,
      kanji: "蔵相",
      reading: "ぞうしょう",
      meanings: {
        ja: "蔵相",
        en: "Minister of Finance (JP)",
        zh: "大藏相（财务大臣）",
        tw: "大藏相（財務大臣）",
        ko: "대장상(재무대신)",
        vi: "Bộ trưởng Tài chính (Nhật)",
        th: "รัฐมนตรีว่าการกระทรวงการคลัง (ญี่ปุ่น)",
        my: "ငွေကြေးဝန်ကြီး(ယသ) ",
        km: "រដ្ឋមន្ត្រីហិរញ្ញវត្ថុ (ជប៉ុន)",
      },
      furigana: [
        {
          rb: "蔵相",
          rt: "ぞうしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "蔵",
          on: ["ゾウ", "ソウ"],
          kun: ["くら", "おさ.める", "かく.れる"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "相",
          on: ["ソウ", "ショウ"],
          kun: ["あい-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1038,
      kanji: "装飾",
      reading: "そうしょく",
      meanings: {
        ja: "装飾",
        en: "decoration; ornamentation",
        zh: "装饰",
        tw: "裝飾",
        ko: "장식",
        vi: "trang trí",
        th: "การตกแต่ง",
        my: "အလှပြင်",
        km: "ការតុបតែង",
      },
      furigana: [
        {
          rb: "装飾",
          rt: "そうしょく",
        },
      ],
      kanjiInfo: [
        {
          char: "装",
          on: ["ソウ", "ショウ"],
          kun: ["よそお.う", "よそお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "飾",
          on: ["ショク"],
          kun: ["かざ.る", "かざ.り"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1039,
      kanji: "増進",
      reading: "ぞうしん",
      meanings: {
        ja: "増進",
        en: "promotion; improvement",
        zh: "增进",
        tw: "增進",
        ko: "증진",
        vi: "tăng tiến; cải thiện",
        th: "ส่งเสริม; เพิ่มพูน",
        my: "တိုးတက်မှု",
        km: "ជំរុញឲ្យកើន",
      },
      furigana: [
        {
          rb: "増進",
          rt: "ぞうしん",
        },
      ],
      kanjiInfo: [
        {
          char: "増",
          on: ["ゾウ"],
          kun: ["ま.す", "ま.し", "ふ.える", "ふ.やす"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1040,
      kanji: "相対",
      reading: "そうたい",
      meanings: {
        ja: "相対",
        en: "relativity; relative",
        zh: "相对",
        tw: "相對",
        ko: "상대",
        vi: "tính tương đối",
        th: "ความสัมพันธ์แบบสัมพัทธ์",
        my: "ဆက်ဆံရေးအပြန်အလှန်",
        km: "ទំនាក់ទំនងសមាមាត្រ",
      },
      furigana: [
        {
          rb: "相対",
          rt: "そうたい",
        },
      ],
      kanjiInfo: [
        {
          char: "相",
          on: ["ソウ", "ショウ"],
          kun: ["あい-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1041,
      kanji: "騒動",
      reading: "そうどう",
      meanings: {
        ja: "騒動",
        en: "riot; disturbance",
        zh: "骚动",
        tw: "騷動",
        ko: "소동",
        vi: "náo loạn",
        th: "ความวุ่นวาย",
        my: "တရာင်းမှု",
        km: "ចលាចរ",
      },
      furigana: [
        {
          rb: "騒動",
          rt: "そうどう",
        },
      ],
      kanjiInfo: [
        {
          char: "騒",
          on: ["ソウ"],
          kun: ["さわ.ぐ", "うれい", "さわ.がしい"],
          strokes: 18,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1042,
      kanji: "遭難",
      reading: "そうなん",
      meanings: {
        ja: "遭難",
        en: "disaster; shipwreck",
        zh: "遇难",
        tw: "遇難",
        ko: "조난",
        vi: "gặp nạn",
        th: "ประสบภัย",
        my: "ထိခိုက်မိခြင်း",
        km: "ជួបគ្រោះថ្នាក់",
      },
      furigana: [
        {
          rb: "遭難",
          rt: "そうなん",
        },
      ],
      kanjiInfo: [
        {
          char: "遭",
          on: ["ソウ"],
          kun: ["あ.う", "あ.わせる"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "難",
          on: ["ナン"],
          kun: [
            "かた.い",
            "-がた.い",
            "むずか.しい",
            "むづか.しい",
            "むつか.しい",
            "-にく.い",
          ],
          strokes: 18,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1043,
      kanji: "相場",
      reading: "そうば",
      meanings: {
        ja: "相場",
        en: "market price",
        zh: "行情；市价",
        tw: "行情；市價",
        ko: "시세",
        vi: "giá thị trường",
        th: "ราคาตลาด",
        my: "စျေးကွက်ဈေး",
        km: "តម្លៃទីផ្សារ",
      },
      furigana: [
        {
          rb: "相場",
          rt: "そうば",
        },
      ],
      kanjiInfo: [
        {
          char: "相",
          on: ["ソウ", "ショウ"],
          kun: ["あい-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1044,
      kanji: "装備",
      reading: "そうび",
      meanings: {
        ja: "装備",
        en: "equipment; gear",
        zh: "装备",
        tw: "裝備",
        ko: "장비",
        vi: "trang bị",
        th: "อุปกรณ์",
        my: "ကိရိယာပစ္စည်း",
        km: "ឧបករណ៍",
      },
      furigana: [
        {
          rb: "装備",
          rt: "そうび",
        },
      ],
      kanjiInfo: [
        {
          char: "装",
          on: ["ソウ", "ショウ"],
          kun: ["よそお.う", "よそお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "備",
          on: ["ビ"],
          kun: ["そな.える", "そな.わる", "つぶさ.に"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1045,
      kanji: "創立",
      reading: "そうりつ",
      meanings: {
        ja: "創立",
        en: "establishment; founding",
        zh: "创立",
        tw: "創立",
        ko: "창립",
        vi: "sáng lập",
        th: "ก่อตั้ง",
        my: "တည်ထောင်ခြင်း",
        km: "បង្កើតឡើង",
      },
      furigana: [
        {
          rb: "創立",
          rt: "そうりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "創",
          on: ["ソウ", "ショウ"],
          kun: ["つく.る", "はじ.める", "きず", "けず.しける"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "立",
          on: ["リツ", "リュウ", "リットル"],
          kun: [
            "た.つ",
            "-た.つ",
            "た.ち-",
            "た.てる",
            "-た.てる",
            "た.て-",
            "たて-",
            "-た.て",
            "-だ.て",
            "-だ.てる",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1046,
      kanji: "ソース",
      reading: "ソース",
      meanings: {
        ja: "ソース",
        en: "sauce",
        zh: "酱汁",
        tw: "醬汁",
        ko: "소스",
        vi: "nước xốt",
        th: "ซอส",
        my: "ဆော့စ်",
        km: "ស៊ុប/សូស",
      },
      furigana: [
        {
          rb: "ソース",
          rt: "ソース",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1047,
      kanji: "促進",
      reading: "そくしん",
      meanings: {
        ja: "促進",
        en: "promotion; acceleration",
        zh: "促进",
        tw: "促進",
        ko: "촉진",
        vi: "thúc đẩy",
        th: "เร่งส่งเสริม",
        my: "ဖြို့အားပေး",
        km: "ជំរុញ",
      },
      furigana: [
        {
          rb: "促進",
          rt: "そくしん",
        },
      ],
      kanjiInfo: [
        {
          char: "促",
          on: ["ソク"],
          kun: ["うなが.す"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1048,
      kanji: "束縛",
      reading: "そくばく",
      meanings: {
        ja: "束縛",
        en: "restraint; restriction",
        zh: "束缚",
        tw: "束縛",
        ko: "속박",
        vi: "ràng buộc",
        th: "ผูกมัด",
        my: "ဖက်သိမ်းမှု",
        km: "ចងចាប់",
      },
      furigana: [
        {
          rb: "束縛",
          rt: "そくばく",
        },
      ],
      kanjiInfo: [
        {
          char: "束",
          on: ["ソク"],
          kun: ["たば", "たば.ねる", "つか", "つか.ねる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "縛",
          on: ["バク"],
          kun: ["しば.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1049,
      kanji: "側面",
      reading: "そくめん",
      meanings: {
        ja: "側面",
        en: "side; aspect",
        zh: "侧面；方面",
        tw: "側面；方面",
        ko: "측면",
        vi: "khía cạnh; mặt bên",
        th: "ด้าน; มุมมอง",
        my: "ဘက်ခြမ်း",
        km: "ជ្រុង/ផ្នែក",
      },
      furigana: [
        {
          rb: "側面",
          rt: "そくめん",
        },
      ],
      kanjiInfo: [
        {
          char: "側",
          on: ["ソク"],
          kun: ["かわ", "がわ", "そば"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1050,
      kanji: "素材",
      reading: "そざい",
      meanings: {
        ja: "素材",
        en: "material; ingredient",
        zh: "素材；材料",
        tw: "素材；材料",
        ko: "소재; 재료",
        vi: "nguyên liệu",
        th: "วัสดุ; ส่วนผสม",
        my: "အစုအဝေး/ကုန်ကြမ်း",
        km: "វត្ថុធាតុ",
      },
      furigana: [
        {
          rb: "素材",
          rt: "そざい",
        },
      ],
      kanjiInfo: [
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "材",
          on: ["ザイ"],
          kun: [],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
