export const n1part1 = {
  Lesson1: [
    {
      id: 1,
      kanji: "現像",
      reading: "げんぞう",
      meanings: {
        ja: "現像",
        en: "development (of film)",
        zh: "冲洗胶片",
        tw: "沖洗底片",
        ko: "현상(필름)",
        vi: "tráng phim",
        th: "ล้างฟิล์ม",
        my: "ဖလင်ဓာတ်ဖွင့်",
        km: "បញ្ចេញរូបពីហ្វីឡាំ",
      },
      furigana: [
        {
          rb: "現像",
          rt: "げんぞう",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "像",
          on: ["ゾウ"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2,
      kanji: "原則",
      reading: "げんそく",
      meanings: {
        ja: "原則",
        en: "principle",
        zh: "原则",
        tw: "原則",
        ko: "원칙",
        vi: "nguyên tắc",
        th: "หลักการ",
        my: "နိဂုံးချုပ် စည်းကမ်း",
        km: "គោលការណ៍",
      },
      furigana: [
        {
          rb: "原則",
          rt: "げんそく",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "則",
          on: ["ソク"],
          kun: ["のっと.る", "のり", "すなわち"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 3,
      kanji: "見地",
      reading: "けんち",
      meanings: {
        ja: "見地",
        en: "point of view",
        zh: "观点",
        tw: "觀點",
        ko: "관점",
        vi: "quan điểm",
        th: "มุมมอง",
        my: "အမြင်",
        km: "ទស្សនៈ",
      },
      furigana: [
        {
          rb: "見地",
          rt: "けんち",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 4,
      kanji: "現地",
      reading: "げんち",
      meanings: {
        ja: "現地",
        en: "actual place; on-site",
        zh: "当地",
        tw: "當地",
        ko: "현지",
        vi: "tại chỗ",
        th: "ในพื้นที่",
        my: "နေရာတိုင်ရာ",
        km: "តំបន់នោះផ្ទាល់",
      },
      furigana: [
        {
          rb: "現地",
          rt: "げんち",
        },
      ],
      kanjiInfo: [
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 5,
      kanji: "限定",
      reading: "げんてい",
      meanings: {
        ja: "限定",
        en: "limit; restriction",
        zh: "限定",
        tw: "限定",
        ko: "한정",
        vi: "giới hạn",
        th: "จำกัด",
        my: "ကန့်သတ်",
        km: "កំណត់",
      },
      furigana: [
        {
          rb: "限定",
          rt: "げんてい",
        },
      ],
      kanjiInfo: [
        {
          char: "限",
          on: ["ゲン"],
          kun: ["かぎ.る", "かぎ.り", "-かぎ.り"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 6,
      kanji: "原点",
      reading: "げんてん",
      meanings: {
        ja: "原点",
        en: "starting point; origin",
        zh: "原点",
        tw: "原點",
        ko: "원점",
        vi: "điểm xuất phát",
        th: "จุดเริ่มต้น",
        my: "အစပိုင်း",
        km: "ចំណុចដើម",
      },
      furigana: [
        {
          rb: "原点",
          rt: "げんてん",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 7,
      kanji: "原典",
      reading: "げんてん",
      meanings: {
        ja: "原典",
        en: "original (text)",
        zh: "原典",
        tw: "原典",
        ko: "원전",
        vi: "nguyên bản (văn bản)",
        th: "ต้นฉบับ",
        my: "မူရင်းစာအုပ်",
        km: "អត្ថបទដើម",
      },
      furigana: [
        {
          rb: "原典",
          rt: "げんてん",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "典",
          on: ["テン", "デン"],
          kun: ["ふみ", "のり"],
          strokes: 8,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 8,
      kanji: "原爆",
      reading: "げんばく",
      meanings: {
        ja: "原爆",
        en: "atomic bomb",
        zh: "原子弹",
        tw: "原子彈",
        ko: "원자폭탄",
        vi: "bom nguyên tử",
        th: "ระเบิดปรมาณู",
        my: "အာတိုမ်ဗုံး",
        km: "គ្រាប់បែកនុយក្លេអឺរ",
      },
      furigana: [
        {
          rb: "原爆",
          rt: "げんばく",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "爆",
          on: ["バク"],
          kun: ["は.ぜる"],
          strokes: 19,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 9,
      kanji: "原文",
      reading: "げんぶん",
      meanings: {
        ja: "原文",
        en: "original text",
        zh: "原文",
        tw: "原文",
        ko: "원문",
        vi: "nguyên văn",
        th: "ต้นฉบับข้อความ",
        my: "မူရင်းစာသား",
        km: "អត្ថបទដើម",
      },
      furigana: [
        {
          rb: "原文",
          rt: "げんぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 10,
      kanji: "倹約",
      reading: "けんやく",
      meanings: {
        ja: "倹約",
        en: "thrift; frugality",
        zh: "节俭",
        tw: "節儉",
        ko: "검약",
        vi: "tiết kiệm",
        th: "ประหยัด",
        my: "ချွေတာမှု",
        km: "សន្សំសំចៃ",
      },
      furigana: [
        {
          rb: "倹約",
          rt: "けんやく",
        },
      ],
      kanjiInfo: [
        {
          char: "倹",
          on: ["ケン"],
          kun: ["つま.しい", "つづまやか"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "約",
          on: ["ヤク"],
          kun: ["つづ.まる", "つづ.める", "つづま.やか"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 11,
      kanji: "原油",
      reading: "げんゆ",
      meanings: {
        ja: "原油",
        en: "crude oil",
        zh: "原油",
        tw: "原油",
        ko: "원유",
        vi: "dầu thô",
        th: "น้ำมันดิบ",
        my: "ရေနံ အသစ်",
        km: "ប្រេងឆៅ",
      },
      furigana: [
        {
          rb: "原油",
          rt: "げんゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "油",
          on: ["ユ", "ユウ"],
          kun: ["あぶら"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 12,
      kanji: "兼用",
      reading: "けんよう",
      meanings: {
        ja: "兼用",
        en: "multi-use; dual purpose",
        zh: "兼用",
        tw: "兼用",
        ko: "겸용",
        vi: "dùng chung/đa dụng",
        th: "ใช้ได้หลายอย่าง",
        my: "နှစ်မျိုးသုံး",
        km: "ប្រើបានច្រើនគោលបំណង",
      },
      furigana: [
        {
          rb: "兼用",
          rt: "けんよう",
        },
      ],
      kanjiInfo: [
        {
          char: "兼",
          on: ["ケン"],
          kun: ["か.ねる", "-か.ねる"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 13,
      kanji: "権力",
      reading: "けんりょく",
      meanings: {
        ja: "権力",
        en: "(political) power",
        zh: "权力",
        tw: "權力",
        ko: "권력",
        vi: "quyền lực",
        th: "อำนาจ",
        my: "အာဏာ",
        km: "អំណាច",
      },
      furigana: [
        {
          rb: "権力",
          rt: "けんりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "権",
          on: ["ケン", "ゴン"],
          kun: ["おもり", "かり", "はか.る"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 14,
      kanji: "言論",
      reading: "げんろん",
      meanings: {
        ja: "言論",
        en: "speech; expression",
        zh: "言论",
        tw: "言論",
        ko: "언론(발언)",
        vi: "ngôn luận",
        th: "การพูด/แสดงความเห็น",
        my: "မိန့်ခွန်း/ထုတ်ဖော်ပြောဆိုမှု",
        km: "សុន្ទរកថា/សម្ដី",
      },
      furigana: [
        {
          rb: "言論",
          rt: "げんろん",
        },
      ],
      kanjiInfo: [
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 15,
      kanji: "語彙",
      reading: "ごい",
      meanings: {
        ja: "語彙",
        en: "vocabulary",
        zh: "词汇",
        tw: "詞彙",
        ko: "어휘",
        vi: "từ vựng",
        th: "คำศัพท์",
        my: "ဝေါဟာရ",
        km: "វាក្យសព្ទ",
      },
      furigana: [
        {
          rb: "語彙",
          rt: "ごい",
        },
      ],
      kanjiInfo: [
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "彙",
          on: ["イ"],
          kun: ["はりねずみ"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 16,
      kanji: "甲",
      reading: "こう",
      meanings: {
        ja: "甲（こう）",
        en: "carapace; shell",
        zh: "甲壳",
        tw: "甲殼",
        ko: "갑각/등딱지",
        vi: "mai cứng",
        th: "กระดอง",
        my: "ခုံကျောအင်္ကျီ(ခွံ)",
        km: "សំបករឹង",
      },
      furigana: [
        {
          rb: "甲",
          rt: "こう",
        },
      ],
      kanjiInfo: [
        {
          char: "甲",
          on: ["コウ", "カン"],
          kun: ["きのえ"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 17,
      kanji: "好意",
      reading: "こうい",
      meanings: {
        ja: "好意",
        en: "kindness; favor",
        zh: "好意",
        tw: "好意",
        ko: "호의",
        vi: "thiện ý",
        th: "น้ำใจ",
        my: "ကရုဏာ",
        km: "មេត្តាករុណា",
      },
      furigana: [
        {
          rb: "好意",
          rt: "こうい",
        },
      ],
      kanjiInfo: [
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 18,
      kanji: "行為",
      reading: "こうい",
      meanings: {
        ja: "行為",
        en: "act; deed",
        zh: "行为",
        tw: "行為",
        ko: "행위",
        vi: "hành vi",
        th: "การกระทำ",
        my: "လုပ်ရပ်",
        km: "អំពើ",
      },
      furigana: [
        {
          rb: "行為",
          rt: "こうい",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "為",
          on: ["イ"],
          kun: ["ため", "な.る", "な.す", "す.る", "たり", "つく.る", "なり"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 19,
      kanji: "合意",
      reading: "ごうい",
      meanings: {
        ja: "合意",
        en: "agreement; consensus",
        zh: "同意/共识",
        tw: "共識",
        ko: "합의",
        vi: "đồng thuận",
        th: "ข้อตกลงร่วม",
        my: "ညှိနှိုင်းသဘောတူချက်",
        km: "កិច្ចព្រមព្រៀង",
      },
      furigana: [
        {
          rb: "合意",
          rt: "ごうい",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 20,
      kanji: "工学",
      reading: "こうがく",
      meanings: {
        ja: "工学",
        en: "engineering",
        zh: "工程学",
        tw: "工程學",
        ko: "공학",
        vi: "kỹ thuật",
        th: "วิศวกรรมศาสตร์",
        my: "အင်ဂျင်နီယာ",
        km: "វិស្វកម្ម",
      },
      furigana: [
        {
          rb: "工学",
          rt: "こうがく",
        },
      ],
      kanjiInfo: [
        {
          char: "工",
          on: ["コウ", "ク", "グ"],
          kun: [],
          strokes: 3,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 21,
      kanji: "抗議",
      reading: "こうぎ",
      meanings: {
        ja: "抗議",
        en: "protest",
        zh: "抗议",
        tw: "抗議",
        ko: "항의",
        vi: "phản đối",
        th: "ประท้วง",
        my: "ဆန္ဒပြ",
        km: "ប្រឆាំង/តវ៉ា",
      },
      furigana: [
        {
          rb: "抗議",
          rt: "こうぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "抗",
          on: ["コウ"],
          kun: ["あらが.う"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 22,
      kanji: "合議",
      reading: "ごうぎ",
      meanings: {
        ja: "合議",
        en: "consultation; deliberation",
        zh: "合议",
        tw: "合議",
        ko: "합의토론",
        vi: "hội ý",
        th: "ปรึกษาหารือ",
        my: "ညှိနှိုင်းထိန်းချုပ်",
        km: "ពិភាក្សារួម",
      },
      furigana: [
        {
          rb: "合議",
          rt: "ごうぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 23,
      kanji: "皇居",
      reading: "こうきょ",
      meanings: {
        ja: "皇居",
        en: "Imperial Palace (Japan)",
        zh: "皇居（日本）",
        tw: "皇居（日本）",
        ko: "고쿄(일본 황거)",
        vi: "Hoàng cung (Nhật)",
        th: "พระราชวังอิมพีเรียล (ญี่ปุ่น)",
        my: "ဂိုက្យို (ဂျပန် ကျိုတော်)",
        km: "ព្រះបរមរាជវាំងជប៉ុន",
      },
      furigana: [
        {
          rb: "皇居",
          rt: "こうきょ",
        },
      ],
      kanjiInfo: [
        {
          char: "皇",
          on: ["コウ", "オウ"],
          kun: [],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "居",
          on: ["キョ", "コ"],
          kun: ["い.る", "-い", "お.る"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 24,
      kanji: "好況",
      reading: "こうきょう",
      meanings: {
        ja: "好況",
        en: "prosperous economic conditions",
        zh: "景气繁荣",
        tw: "景氣繁榮",
        ko: "호황",
        vi: "kinh tế hưng thịnh",
        th: "เศรษฐกิจเฟื่องฟู",
        my: "စီးပွားရေးကောင်း",
        km: "សេដ្ឋកិច្ចល្អ",
      },
      furigana: [
        {
          rb: "好況",
          rt: "こうきょう",
        },
      ],
      kanjiInfo: [
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "況",
          on: ["キョウ"],
          kun: ["まし.て", "いわ.んや", "おもむき"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 25,
      kanji: "鉱業",
      reading: "こうぎょう",
      meanings: {
        ja: "鉱業",
        en: "mining industry",
        zh: "矿业",
        tw: "礦業",
        ko: "광업",
        vi: "khai khoáng",
        th: "อุตสาหกรรมเหมืองแร่",
        my: "သတ္တုတူးဖော်ရေး",
        km: "ឧស្សាហកម្មរ៉ែ",
      },
      furigana: [
        {
          rb: "鉱業",
          rt: "こうぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "鉱",
          on: ["コウ"],
          kun: ["あらがね"],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 26,
      kanji: "興業",
      reading: "こうぎょう",
      meanings: {
        ja: "興業",
        en: "promotion of industry",
        zh: "兴办实业",
        tw: "興辦實業",
        ko: "산업진흥",
        vi: "chấn hưng công nghiệp",
        th: "ส่งเสริมอุตสาหกรรม",
        my: "စက်မှုဖွံ့ဖြိုးတိုးတက်",
        km: "បង្កើនឧស្សាហកម្ម",
      },
      furigana: [
        {
          rb: "興業",
          rt: "こうぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "興",
          on: ["コウ", "キョウ"],
          kun: ["おこ.る", "おこ.す"],
          strokes: 16,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 27,
      kanji: "高原",
      reading: "こうげん",
      meanings: {
        ja: "高原",
        en: "tableland; plateau",
        zh: "高原",
        tw: "高原",
        ko: "고원",
        vi: "cao nguyên",
        th: "ที่ราบสูง",
        my: "ကမ္ဘာမြင့်",
        km: "ជ្រលងភ្នំខ្ពស់",
      },
      furigana: [
        {
          rb: "高原",
          rt: "こうげん",
        },
      ],
      kanjiInfo: [
        {
          char: "高",
          on: ["コウ"],
          kun: ["たか.い", "たか", "-だか", "たか.まる", "たか.める"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 28,
      kanji: "考古学",
      reading: "こうこがく",
      meanings: {
        ja: "考古学",
        en: "archaeology",
        zh: "考古学",
        tw: "考古學",
        ko: "고고학",
        vi: "khảo cổ học",
        th: "โบราณคดี",
        my: "ဟောင်းရိုးရှင်းသုတ",
        km: "បុរាណវិទ្យា",
      },
      furigana: [
        {
          rb: "考古学",
          rt: "こうこがく",
        },
      ],
      kanjiInfo: [
        {
          char: "考",
          on: ["コウ"],
          kun: ["かんが.える", "かんが.え"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "古",
          on: ["コ"],
          kun: ["ふる.い", "ふる-", "-ふる.す"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 29,
      kanji: "工作",
      reading: "こうさく",
      meanings: {
        ja: "工作",
        en: "handicraft; handiwork",
        zh: "手工制作",
        tw: "手工",
        ko: "공작/수공예",
        vi: "thủ công",
        th: "งานประดิษฐ์",
        my: "လက်မှုပညာ",
        km: "សិប្បកម្ម",
      },
      furigana: [
        {
          rb: "工作",
          rt: "こうさく",
        },
      ],
      kanjiInfo: [
        {
          char: "工",
          on: ["コウ", "ク", "グ"],
          kun: [],
          strokes: 3,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 30,
      kanji: "耕作",
      reading: "こうさく",
      meanings: {
        ja: "耕作",
        en: "cultivation (farming)",
        zh: "耕作",
        tw: "耕作",
        ko: "경작",
        vi: "canh tác",
        th: "เพาะปลูก",
        my: "ထွန်ယက်စိုက်ပျိုး",
        km: "កសិកម្មកាប់រោល",
      },
      furigana: [
        {
          rb: "耕作",
          rt: "こうさく",
        },
      ],
      kanjiInfo: [
        {
          char: "耕",
          on: ["コウ"],
          kun: ["たがや.す"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 31,
      kanji: "鉱山",
      reading: "こうざん",
      meanings: {
        ja: "鉱山",
        en: "mine (ore)",
        zh: "矿山",
        tw: "礦山",
        ko: "광산",
        vi: "mỏ (quặng)",
        th: "เหมืองแร่",
        my: "သတ္တုတွင်း",
        km: "រ៉ែ",
      },
      furigana: [
        {
          rb: "鉱山",
          rt: "こうざん",
        },
      ],
      kanjiInfo: [
        {
          char: "鉱",
          on: ["コウ"],
          kun: ["あらがね"],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "山",
          on: ["サン", "セン"],
          kun: ["やま"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 32,
      kanji: "講習",
      reading: "こうしゅう",
      meanings: {
        ja: "講習",
        en: "short course; training class",
        zh: "讲习班",
        tw: "講習",
        ko: "강습",
        vi: "lớp tập huấn",
        th: "คอร์สระยะสั้น",
        my: "သင်တန်းတို",
        km: "ថ្នាក់បណ្ដុះបណ្ដាលខ្លី",
      },
      furigana: [
        {
          rb: "講習",
          rt: "こうしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "講",
          on: ["コウ"],
          kun: [],
          strokes: 17,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "習",
          on: ["シュウ", "ジュ"],
          kun: ["なら.う", "なら.い"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 33,
      kanji: "口述",
      reading: "こうじゅつ",
      meanings: {
        ja: "口述",
        en: "dictation; oral statement",
        zh: "口述",
        tw: "口述",
        ko: "구술",
        vi: "khẩu thuật/đọc chép",
        th: "การบอกให้อ่านตาม",
        my: "ပါးစပ်ဟောပြောရေးသား",
        km: "សរសេរតាមការប្រាប់",
      },
      furigana: [
        {
          rb: "口述",
          rt: "こうじゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "口",
          on: ["コウ", "ク"],
          kun: ["くち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "述",
          on: ["ジュツ"],
          kun: ["の.べる"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 34,
      kanji: "控除",
      reading: "こうじょ",
      meanings: {
        ja: "控除",
        en: "subtraction; (tax) deduction",
        zh: "扣除",
        tw: "扣除",
        ko: "공제",
        vi: "khấu trừ",
        th: "หักลดหย่อน",
        my: "လျော့ချပွန်ဂဏန်း/အခွန်",
        km: "ដកចេញ (ពន្ធ)",
      },
      furigana: [
        {
          rb: "控除",
          rt: "こうじょ",
        },
      ],
      kanjiInfo: [
        {
          char: "控",
          on: ["コウ"],
          kun: ["ひか.える", "ひか.え"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "除",
          on: ["ジョ", "ジ"],
          kun: ["のぞ.く", "-よ.け"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 35,
      kanji: "交渉",
      reading: "こうしょう",
      meanings: {
        ja: "交渉",
        en: "negotiations",
        zh: "谈判",
        tw: "談判",
        ko: "교섭/협상",
        vi: "đàm phán",
        th: "การเจรจา",
        my: "စကားပြောဆွေးနွေး",
        km: "ចរចា",
      },
      furigana: [
        {
          rb: "交渉",
          rt: "こうしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "交",
          on: ["コウ"],
          kun: [
            "まじ.わる",
            "まじ.える",
            "ま.じる",
            "まじ.る",
            "ま.ざる",
            "ま.ぜる",
            "-か.う",
            "か.わす",
            "かわ.す",
            "こもごも",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "渉",
          on: ["ショウ"],
          kun: ["わた.る"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 36,
      kanji: "向上",
      reading: "こうじょう",
      meanings: {
        ja: "向上",
        en: "improvement; elevation",
        zh: "提高",
        tw: "向上",
        ko: "향상",
        vi: "nâng cao",
        th: "พัฒนาให้ดีขึ้น",
        my: "တိုးတက်မွှမ်းမံ",
        km: "កែលម្អ",
      },
      furigana: [
        {
          rb: "向上",
          rt: "こうじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "向",
          on: ["コウ"],
          kun: [
            "む.く",
            "む.い",
            "-む.き",
            "む.ける",
            "-む.け",
            "む.かう",
            "む.かい",
            "む.こう",
            "む.こう-",
            "むこ",
            "むか.い",
          ],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 37,
      kanji: "行進",
      reading: "こうしん",
      meanings: {
        ja: "行進",
        en: "march; parade",
        zh: "行进",
        tw: "行進",
        ko: "행진",
        vi: "diễu hành",
        th: "เดินแถว/สวนสนาม",
        my: "အစည်းအဝေး လှည့်လည်ခြင်း",
        km: "ដើរដង្ហែរ",
      },
      furigana: [
        {
          rb: "行進",
          rt: "こうしん",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "進",
          on: ["シン"],
          kun: ["すす.む", "すす.める"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 38,
      kanji: "香辛料",
      reading: "こうしんりょう",
      meanings: {
        ja: "香辛料",
        en: "spice",
        zh: "香辛料/香料",
        tw: "香辛料",
        ko: "향신료",
        vi: "gia vị cay",
        th: "เครื่องเทศ",
        my: "အမွှေးအကြိုင်",
        km: "គ្រឿងទេស",
      },
      furigana: [
        {
          rb: "香辛料",
          rt: "こうしんりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "香",
          on: ["コウ", "キョウ"],
          kun: ["か", "かお.り", "かお.る"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "辛",
          on: ["シン"],
          kun: ["から.い", "つら.い", "-づら.い", "かのと"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "料",
          on: ["リョウ"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 39,
      kanji: "降水",
      reading: "こうすい",
      meanings: {
        ja: "降水",
        en: "rainfall; precipitation",
        zh: "降水/降雨量",
        tw: "降水/降雨",
        ko: "강수",
        vi: "lượng mưa",
        th: "ปริมาณน้ำฝน",
        my: "မိုးရေချိန်",
        km: "ភ្លៀងធ្លាក់",
      },
      furigana: [
        {
          rb: "降水",
          rt: "こうすい",
        },
      ],
      kanjiInfo: [
        {
          char: "降",
          on: ["コウ", "ゴ"],
          kun: ["お.りる", "お.ろす", "ふ.る", "ふ.り", "くだ.る", "くだ.す"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 40,
      kanji: "洪水",
      reading: "こうずい",
      meanings: {
        ja: "洪水",
        en: "flood",
        zh: "洪水",
        tw: "洪水",
        ko: "홍수",
        vi: "lũ lụt",
        th: "น้ำท่วม",
        my: "ရေဘေး",
        km: "ទឹកជំនន់",
      },
      furigana: [
        {
          rb: "洪水",
          rt: "こうずい",
        },
      ],
      kanjiInfo: [
        {
          char: "洪",
          on: ["コウ"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 41,
      kanji: "合成",
      reading: "ごうせい",
      meanings: {
        ja: "合成",
        en: "composition; synthesis",
        zh: "合成",
        tw: "合成",
        ko: "합성",
        vi: "tổng hợp",
        th: "สังเคราะห์",
        my: "ပေါင်းစည်းမှု",
        km: "សំយោគ",
      },
      furigana: [
        {
          rb: "合成",
          rt: "ごうせい",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 42,
      kanji: "抗争",
      reading: "こうそう",
      meanings: {
        ja: "抗争",
        en: "rivalry; conflict",
        zh: "抗争",
        tw: "抗爭",
        ko: "항쟁/다툼",
        vi: "đấu tranh",
        th: "ความขัดแย้ง",
        my: "ငြင်းပွားမှု",
        km: "ជម្លោះប្រឆាំង",
      },
      furigana: [
        {
          rb: "抗争",
          rt: "こうそう",
        },
      ],
      kanjiInfo: [
        {
          char: "抗",
          on: ["コウ"],
          kun: ["あらが.う"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "争",
          on: ["ソウ"],
          kun: ["あらそ.う", "いか.でか"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 43,
      kanji: "構想",
      reading: "こうそう",
      meanings: {
        ja: "構想",
        en: "plan; concept",
        zh: "构想",
        tw: "構想",
        ko: "구상",
        vi: "ý tưởng/đề án",
        th: "แนวคิด/แผนงาน",
        my: "စိတ်အတွေးကူး",
        km: "គំនិតគម្រោង",
      },
      furigana: [
        {
          rb: "構想",
          rt: "こうそう",
        },
      ],
      kanjiInfo: [
        {
          char: "構",
          on: ["コウ"],
          kun: ["かま.える", "かま.う"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "想",
          on: ["ソウ", "ソ"],
          kun: ["おも.う"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 44,
      kanji: "後退",
      reading: "こうたい",
      meanings: {
        ja: "後退",
        en: "retreat; recession",
        zh: "后退",
        tw: "後退",
        ko: "후퇴",
        vi: "thoái lui",
        th: "ถอยหลัง",
        my: "နောက်ပြန်ဆုတ်",
        km: "ថយក្រោយ",
      },
      furigana: [
        {
          rb: "後退",
          rt: "こうたい",
        },
      ],
      kanjiInfo: [
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 45,
      kanji: "光沢",
      reading: "こうたく",
      meanings: {
        ja: "光沢",
        en: "brilliance; luster",
        zh: "光泽",
        tw: "光澤",
        ko: "광택",
        vi: "độ bóng",
        th: "ความเงางาม",
        my: "တောက်ပမှု",
        km: "ភ្លឺរលោង",
      },
      furigana: [
        {
          rb: "光沢",
          rt: "こうたく",
        },
      ],
      kanjiInfo: [
        {
          char: "光",
          on: ["コウ"],
          kun: ["ひか.る", "ひかり"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "沢",
          on: ["タク"],
          kun: ["さわ", "うるお.い", "うるお.す", "つや"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 46,
      kanji: "公団",
      reading: "こうだん",
      meanings: {
        ja: "公団",
        en: "public corporation",
        zh: "公团/公共机构",
        tw: "公團",
        ko: "공단(공기업)",
        vi: "tập đoàn công",
        th: "รัฐวิสาหกิจ",
        my: "ပုရိဝါဒ အဖွဲ့",
        km: "ស្ថាប័នសាធារណៈ",
      },
      furigana: [
        {
          rb: "公団",
          rt: "こうだん",
        },
      ],
      kanjiInfo: [
        {
          char: "公",
          on: ["コウ", "ク"],
          kun: ["おおやけ"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "団",
          on: ["ダン", "トン"],
          kun: ["かたまり", "まる.い"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 47,
      kanji: "講読",
      reading: "こうどく",
      meanings: {
        ja: "講読",
        en: "reading (study of texts)",
        zh: "讲读",
        tw: "講讀",
        ko: "강독",
        vi: "đọc chú giải",
        th: "อ่านวิเคราะห์",
        my: "စာတမ်းဖတ်သင်",
        km: "អានបកស្រាយ",
      },
      furigana: [
        {
          rb: "講読",
          rt: "こうどく",
        },
      ],
      kanjiInfo: [
        {
          char: "講",
          on: ["コウ"],
          kun: [],
          strokes: 17,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "読",
          on: ["ドク", "トク", "トウ"],
          kun: ["よ.む", "-よ.み"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 48,
      kanji: "購読",
      reading: "こうどく",
      meanings: {
        ja: "購読",
        en: "subscription; buying and reading",
        zh: "订阅",
        tw: "訂閱",
        ko: "구독",
        vi: "đăng ký mua (báo…)",
        th: "สมัครสมาชิกอ่าน",
        my: "စာစောင်စာအုပ် စာရင်းသွင်း",
        km: "ជាវអាន",
      },
      furigana: [
        {
          rb: "購読",
          rt: "こうどく",
        },
      ],
      kanjiInfo: [
        {
          char: "購",
          on: ["コウ"],
          kun: [],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "読",
          on: ["ドク", "トク", "トウ"],
          kun: ["よ.む", "-よ.み"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 49,
      kanji: "購入",
      reading: "こうにゅう",
      meanings: {
        ja: "購入",
        en: "purchase",
        zh: "购买",
        tw: "購買",
        ko: "구매",
        vi: "mua",
        th: "ซื้อ",
        my: "ဝယ်ယူ",
        km: "ទិញ",
      },
      furigana: [
        {
          rb: "購入",
          rt: "こうにゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "購",
          on: ["コウ"],
          kun: [],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 50,
      kanji: "公認",
      reading: "こうにん",
      meanings: {
        ja: "公認",
        en: "official recognition",
        zh: "公认",
        tw: "公認",
        ko: "공인",
        vi: "công nhận chính thức",
        th: "การรับรองอย่างเป็นทางการ",
        my: "အတည်ပြုချက်",
        km: "ការទទួលស្គាល់ផ្លូវការណ៍",
      },
      furigana: [
        {
          rb: "公認",
          rt: "こうにん",
        },
      ],
      kanjiInfo: [
        {
          char: "公",
          on: ["コウ", "ク"],
          kun: ["おおやけ"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "認",
          on: ["ニン"],
          kun: ["みと.める", "したた.める"],
          strokes: 14,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
