export const n1part22 = {
  Lesson22: [
    {
      id: 1051,
      kanji: "阻止",
      reading: "そし",
      meanings: {
        ja: "阻止",
        en: "obstruction; prevention",
        zh: "阻止",
        tw: "阻止",
        ko: "저지",
        vi: "ngăn chặn",
        th: "การขัดขวาง",
        my: "တားဆီးခြင်း",
        km: "ការទប់ស្កាត់",
      },
      furigana: [
        {
          rb: "阻止",
          rt: "そし",
        },
      ],
      kanjiInfo: [
        {
          char: "阻",
          on: ["ソ"],
          kun: ["はば.む"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "止",
          on: ["シ"],
          kun: [
            "と.まる",
            "-ど.まり",
            "と.める",
            "-と.める",
            "-ど.め",
            "とど.める",
            "とど.め",
            "とど.まる",
            "や.める",
            "や.む",
            "-や.む",
            "よ.す",
            "-さ.す",
            "-さ.し",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1052,
      kanji: "訴訟",
      reading: "そしょう",
      meanings: {
        ja: "訴訟",
        en: "lawsuit",
        zh: "诉讼",
        tw: "訴訟",
        ko: "소송",
        vi: "kiện tụng",
        th: "คดีความ",
        my: "တရားစွဲဆိုမှု",
        km: "ដំណើរការក្ដី",
      },
      furigana: [
        {
          rb: "訴訟",
          rt: "そしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "訴",
          on: ["ソ"],
          kun: ["うった.える"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "訟",
          on: ["ショウ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1053,
      kanji: "育ち",
      reading: "そだち",
      meanings: {
        ja: "育ち",
        en: "growth; upbringing",
        zh: "成长；教养",
        tw: "成長；教養",
        ko: "성장; 가정교육",
        vi: "sự trưởng thành",
        th: "การเติบโต",
        my: "ကြီးထွားမှု",
        km: "ការលូតលាស់",
      },
      furigana: [
        {
          rb: "育ち",
          rt: "そだち",
        },
      ],
      kanjiInfo: [
        {
          char: "育",
          on: ["イク"],
          kun: ["そだ.つ", "そだ.ち", "そだ.てる", "はぐく.む"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1054,
      kanji: "措置",
      reading: "そち",
      meanings: {
        ja: "措置",
        en: "measure; step",
        zh: "措施",
        tw: "措施",
        ko: "조치",
        vi: "biện pháp",
        th: "มาตรการ",
        my: "အရေးယူမှု",
        km: "វិធានការ",
      },
      furigana: [
        {
          rb: "措置",
          rt: "そち",
        },
      ],
      kanjiInfo: [
        {
          char: "措",
          on: ["ソ"],
          kun: ["お.く"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "置",
          on: ["チ"],
          kun: ["お.く", "-お.き"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1055,
      kanji: "ソックス",
      reading: "ソックス",
      meanings: {
        ja: "ソックス",
        en: "socks",
        zh: "袜子",
        tw: "襪子",
        ko: "양말",
        vi: "tất (vớ)",
        th: "ถุงเท้า",
        my: " جوراب? -> စုတေ (မြန်မာ) ",
        km: "ស្រោមជើង",
      },
      furigana: [
        {
          rb: "ソックス",
          rt: "ソックス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1056,
      kanji: "外方",
      reading: "そっぽ",
      meanings: {
        ja: "外方（を向く）",
        en: "the other way; elsewhere",
        zh: "另一边",
        tw: "另一邊",
        ko: "딴 데(를 보다)",
        vi: "hướng khác",
        th: "หันไปทางอื่น",
        my: "တစ်ဖက်ဘက်",
        km: "ខាងផ្សេង",
      },
      furigana: [
        {
          rb: "外方",
          rt: "そっぽ",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1057,
      kanji: "ソロ",
      reading: "ソロ",
      meanings: {
        ja: "ソロ",
        en: "solo",
        zh: "独奏／独唱",
        tw: "獨奏／獨唱",
        ko: "솔로",
        vi: "độc tấu/đơn ca",
        th: "โซโล่",
        my: "တစ်ယောက်တည်းဖျော်ဖြေ",
        km: "សន្លង់ឯក",
      },
      furigana: [
        {
          rb: "ソロ",
          rt: "ソロ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1058,
      kanji: "揃い",
      reading: "そろい",
      meanings: {
        ja: "揃い",
        en: "set; assortment",
        zh: "成套；一套",
        tw: "成套；一套",
        ko: "세트",
        vi: "bộ (set)",
        th: "ชุด (เซ็ต)",
        my: "အစု",
        km: "សំណុំ",
      },
      furigana: [
        {
          rb: "揃い",
          rt: "そろい",
        },
      ],
      kanjiInfo: [
        {
          char: "揃",
          on: ["セン"],
          kun: ["そろ.える", "そろ.う", "そろ.い", "き.る"],
          strokes: 12,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1059,
      kanji: "損失",
      reading: "そんしつ",
      meanings: {
        ja: "損失",
        en: "loss (assets)",
        zh: "损失",
        tw: "損失",
        ko: "손실",
        vi: "tổn thất",
        th: "ความสูญเสีย",
        my: "နစ်နာမှု",
        km: "ខាតបង់",
      },
      furigana: [
        {
          rb: "損失",
          rt: "そんしつ",
        },
      ],
      kanjiInfo: [
        {
          char: "損",
          on: ["ソン"],
          kun: [
            "そこ.なう",
            "そこな.う",
            "-そこ.なう",
            "そこ.ねる",
            "-そこ.ねる",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "失",
          on: ["シツ"],
          kun: ["うしな.う", "う.せる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1060,
      kanji: "存続",
      reading: "そんぞく",
      meanings: {
        ja: "存続",
        en: "continuance; survival",
        zh: "存续",
        tw: "存續",
        ko: "존속",
        vi: "tồn tại tiếp tục",
        th: "การคงอยู่ต่อ",
        my: "တည်တံ့တလျှောက်",
        km: "ការបន្តមាន",
      },
      furigana: [
        {
          rb: "存続",
          rt: "そんぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "存",
          on: ["ソン", "ゾン"],
          kun: ["ながら.える", "あ.る", "たも.つ", "と.う"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1061,
      kanji: "ダース",
      reading: "ダース",
      meanings: {
        ja: "ダース",
        en: "Darth (Star Wars)",
        zh: "达斯（星战）",
        tw: "達斯（星戰）",
        ko: "다스(스타워즈)",
        vi: "Darth (Star Wars)",
        th: "ดาร์ธ (สตาร์วอร์ส)",
        my: "Darth (Star Wars)",
        km: "Darth (Star Wars)",
      },
      furigana: [
        {
          rb: "ダース",
          rt: "ダース",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1062,
      kanji: "対応",
      reading: "たいおう",
      meanings: {
        ja: "対応",
        en: "correspondence; handling",
        zh: "对应；应对",
        tw: "對應；應對",
        ko: "대응",
        vi: "đối ứng; xử lý",
        th: "การรับมือ/สอดคล้อง",
        my: "တုံ့ပြန်မှု/ကိုက်ညီမှု",
        km: "ការឆ្លើយតប",
      },
      furigana: [
        {
          rb: "対応",
          rt: "たいおう",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "応",
          on: ["オウ", "ヨウ", "-ノウ"],
          kun: ["あた.る", "まさに", "こた.える"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1063,
      kanji: "大家",
      reading: "たいか",
      meanings: {
        ja: "大家（たいか）",
        en: "master; authority",
        zh: "大家（权威）",
        tw: "大家（權威）",
        ko: "대가",
        vi: "bậc thầy",
        th: "ผู้เชี่ยวชาญใหญ่",
        my: "ကျွမ်းကျင်မြောက်သူ",
        km: "អ្នកឯកទេសធំ",
      },
      furigana: [
        {
          rb: "大家",
          rt: "たいか",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1064,
      kanji: "退化",
      reading: "たいか",
      meanings: {
        ja: "退化",
        en: "degeneration",
        zh: "退化",
        tw: "退化",
        ko: "퇴화",
        vi: "thoái hóa",
        th: "เสื่อมถอย",
        my: "ဆုတ်ယုတ်",
        km: "ធ្លាក់ថយ",
      },
      furigana: [
        {
          rb: "退化",
          rt: "たいか",
        },
      ],
      kanjiInfo: [
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1065,
      kanji: "体格",
      reading: "たいかく",
      meanings: {
        ja: "体格",
        en: "build; physique",
        zh: "体格",
        tw: "體格",
        ko: "체격",
        vi: "thể hình",
        th: "รูปร่าง",
        my: "ခန္ဓာဗေဒပုံစံ",
        km: "រូបរាងខ្លួន",
      },
      furigana: [
        {
          rb: "体格",
          rt: "たいかく",
        },
      ],
      kanjiInfo: [
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "格",
          on: ["カク", "コウ", "キャク", "ゴウ"],
          kun: [],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1066,
      kanji: "大金",
      reading: "たいきん",
      meanings: {
        ja: "大金",
        en: "large amount of money",
        zh: "巨款",
        tw: "鉅款",
        ko: "거액",
        vi: "khoản tiền lớn",
        th: "เงินจำนวนมาก",
        my: "ငွေပမာဏကြီး",
        km: "ប្រាក់ច្រើន",
      },
      furigana: [
        {
          rb: "大金",
          rt: "たいきん",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1067,
      kanji: "待遇",
      reading: "たいぐう",
      meanings: {
        ja: "待遇",
        en: "treatment; conditions",
        zh: "待遇",
        tw: "待遇",
        ko: "대우",
        vi: "đãi ngộ",
        th: "การปฏิบัติต่อ",
        my: "အကျင့်အရာ",
        km: "ការប្រើប្រាស់/បានទទួល",
      },
      furigana: [
        {
          rb: "待遇",
          rt: "たいぐう",
        },
      ],
      kanjiInfo: [
        {
          char: "待",
          on: ["タイ"],
          kun: ["ま.つ", "-ま.ち"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "遇",
          on: ["グウ"],
          kun: ["あ.う"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1068,
      kanji: "対決",
      reading: "たいけつ",
      meanings: {
        ja: "対決",
        en: "confrontation; showdown",
        zh: "对决",
        tw: "對決",
        ko: "대결",
        vi: "đối đầu",
        th: "เผชิญหน้า",
        my: "တော်တော်စုံ",
        km: "ដណ្ដើមគ្នា",
      },
      furigana: [
        {
          rb: "対決",
          rt: "たいけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1069,
      kanji: "体験",
      reading: "たいけん",
      meanings: {
        ja: "体験",
        en: "experience (hands-on)",
        zh: "体验",
        tw: "體驗",
        ko: "체험",
        vi: "trải nghiệm",
        th: "ประสบการณ์ตรง",
        my: "အတွေ့အကြုံ",
        km: "បទពិសោធន៍",
      },
      furigana: [
        {
          rb: "体験",
          rt: "たいけん",
        },
      ],
      kanjiInfo: [
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "験",
          on: ["ケン", "ゲン"],
          kun: ["あかし", "しるし", "ため.す", "ためし"],
          strokes: 18,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1070,
      kanji: "対抗",
      reading: "たいこう",
      meanings: {
        ja: "対抗",
        en: "opposition; rivalry",
        zh: "对抗",
        tw: "對抗",
        ko: "대항",
        vi: "đối kháng",
        th: "ต่อต้าน/แข่ง",
        my: "ခုခံခြင်း",
        km: "ប្រឆាំង",
      },
      furigana: [
        {
          rb: "対抗",
          rt: "たいこう",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "抗",
          on: ["コウ"],
          kun: ["あらが.う"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1071,
      kanji: "退治",
      reading: "たいじ",
      meanings: {
        ja: "退治",
        en: "extermination",
        zh: "消灭",
        tw: "消滅",
        ko: "퇴치",
        vi: "tiêu trừ",
        th: "กำจัด",
        my: "အဆုံးသတ်",
        km: "បំបាត់",
      },
      furigana: [
        {
          rb: "退治",
          rt: "たいじ",
        },
      ],
      kanjiInfo: [
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "治",
          on: ["ジ", "チ"],
          kun: ["おさ.める", "おさ.まる", "なお.る", "なお.す"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1072,
      kanji: "大衆",
      reading: "たいしゅう",
      meanings: {
        ja: "大衆",
        en: "the masses; public",
        zh: "大众",
        tw: "大眾",
        ko: "대중",
        vi: "đại chúng",
        th: "มวลชน",
        my: "ပြည်သူ့ထု",
        km: "សាធារណជន",
      },
      furigana: [
        {
          rb: "大衆",
          rt: "たいしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "衆",
          on: ["シュウ", "シュ"],
          kun: ["おお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1073,
      kanji: "対処",
      reading: "たいしょ",
      meanings: {
        ja: "対処",
        en: "dealing with; coping",
        zh: "应对；处理",
        tw: "應對；處理",
        ko: "대처",
        vi: "ứng phó",
        th: "รับมือ",
        my: "ကိုင်တွယ်ဖြေရှင်း",
        km: "ដោះស្រាយ",
      },
      furigana: [
        {
          rb: "対処",
          rt: "たいしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "処",
          on: ["ショ"],
          kun: ["ところ", "-こ", "お.る"],
          strokes: 5,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1074,
      kanji: "退職",
      reading: "たいしょく",
      meanings: {
        ja: "退職",
        en: "retirement (from job)",
        zh: "退休（离职）",
        tw: "退休（離職）",
        ko: "퇴직",
        vi: "nghỉ việc",
        th: "เกษียณ/ลาออก",
        my: "အလုပ်ထွက်",
        km: "ចូលនិវត្តន៍",
      },
      furigana: [
        {
          rb: "退職",
          rt: "たいしょく",
        },
      ],
      kanjiInfo: [
        {
          char: "退",
          on: ["タイ"],
          kun: [
            "しりぞ.く",
            "しりぞ.ける",
            "ひ.く",
            "の.く",
            "の.ける",
            "ど.く",
          ],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "職",
          on: ["ショク", "ソク"],
          kun: [],
          strokes: 18,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1075,
      kanji: "態勢",
      reading: "たいせい",
      meanings: {
        ja: "態勢",
        en: "posture; readiness",
        zh: "态势；体制",
        tw: "態勢；體勢",
        ko: "태세",
        vi: "thế trận; tư thế",
        th: "ท่าที/ความพร้อม",
        my: "အနေအထား",
        km: "ស្ថានភាពរៀបចំ",
      },
      furigana: [
        {
          rb: "態勢",
          rt: "たいせい",
        },
      ],
      kanjiInfo: [
        {
          char: "態",
          on: ["タイ"],
          kun: ["わざ.と"],
          strokes: 14,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "勢",
          on: ["セイ", "ゼイ"],
          kun: ["いきお.い", "はずみ"],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1076,
      kanji: "対談",
      reading: "たいだん",
      meanings: {
        ja: "対談",
        en: "dialogue; talk",
        zh: "对谈",
        tw: "對談",
        ko: "대담",
        vi: "đối thoại",
        th: "สนทนา",
        my: "ဆွေးနွေးပွဲ",
        km: "សន្ទនា",
      },
      furigana: [
        {
          rb: "対談",
          rt: "たいだん",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "談",
          on: ["ダン"],
          kun: [],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1077,
      kanji: "対等",
      reading: "たいとう",
      meanings: {
        ja: "対等",
        en: "equality (of status)",
        zh: "对等",
        tw: "對等",
        ko: "대등",
        vi: "bình đẳng",
        th: "เท่าเทียม",
        my: "တန်းတူညီမျှ",
        km: "ស្មើភាព",
      },
      furigana: [
        {
          rb: "対等",
          rt: "たいとう",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "等",
          on: ["トウ"],
          kun: ["ひと.しい", "など", "-ら"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1078,
      kanji: "滞納",
      reading: "たいのう",
      meanings: {
        ja: "滞納",
        en: "delinquent payment",
        zh: "拖欠",
        tw: "拖欠",
        ko: "체납",
        vi: "chậm nộp",
        th: "ค้างชำระ",
        my: "ငွေကြေးကျန်ရှိ",
        km: "ខកខានបង់",
      },
      furigana: [
        {
          rb: "滞納",
          rt: "たいのう",
        },
      ],
      kanjiInfo: [
        {
          char: "滞",
          on: ["タイ", "テイ"],
          kun: ["とどこお.る"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "納",
          on: ["ノウ", "ナッ", "ナ", "ナン", "トウ"],
          kun: ["おさ.める", "-おさ.める", "おさ.まる"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1079,
      kanji: "対比",
      reading: "たいひ",
      meanings: {
        ja: "対比",
        en: "contrast (comparison)",
        zh: "对比",
        tw: "對比",
        ko: "대비",
        vi: "đối chiếu",
        th: "การเปรียบเทียบ",
        my: "နှိုင်းယှဉ်",
        km: "ប្រៀបធៀប",
      },
      furigana: [
        {
          rb: "対比",
          rt: "たいひ",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "比",
          on: ["ヒ"],
          kun: ["くら.べる"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1080,
      kanji: "タイピスト",
      reading: "タイピスト",
      meanings: {
        ja: "タイピスト",
        en: "typist",
        zh: "打字员",
        tw: "打字員",
        ko: "타이피스트",
        vi: "người đánh máy",
        th: "พิมพ์ดีด",
        my: "စာတိုက်သမား? -> စာပုံနှိပ် typist",
        km: "អ្នកវាយអក្សរ",
      },
      furigana: [
        {
          rb: "タイピスト",
          rt: "タイピスト",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1081,
      kanji: "大便",
      reading: "だいべん",
      meanings: {
        ja: "大便",
        en: "feces; stool",
        zh: "大便",
        tw: "大便",
        ko: "대변",
        vi: "phân",
        th: "อุจจาระ",
        my: "အဓမ္မ? -> ဝမ်း",
        km: "អាហារសល់(អោហូ)",
      },
      furigana: [
        {
          rb: "大便",
          rt: "だいべん",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "便",
          on: ["ベン", "ビン"],
          kun: ["たよ.り"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1082,
      kanji: "代弁",
      reading: "だいべん",
      meanings: {
        ja: "代弁",
        en: "speaking on behalf",
        zh: "代言",
        tw: "代言",
        ko: "대변",
        vi: "đại diện phát biểu",
        th: "กล่าวแทน",
        my: "ကိုယ်စားပြော",
        km: "តំណាងនិយាយ",
      },
      furigana: [
        {
          rb: "代弁",
          rt: "だいべん",
        },
      ],
      kanjiInfo: [
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "弁",
          on: ["ベン", "ヘン"],
          kun: ["かんむり", "わきま.える", "わ.ける", "はなびら", "あらそ.う"],
          strokes: 5,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1083,
      kanji: "待望",
      reading: "たいぼう",
      meanings: {
        ja: "待望",
        en: "long-awaited; eager waiting",
        zh: "翘首以待",
        tw: "引頸期盼",
        ko: "대망",
        vi: "mong đợi bấy lâu",
        th: "รอคอยอย่างใจจดใจจ่อ",
        my: "စောင်ခြုံမျှော်လင့်",
        km: "រង់ចាំយូរ",
      },
      furigana: [
        {
          rb: "待望",
          rt: "たいぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "待",
          on: ["タイ"],
          kun: ["ま.つ", "-ま.ち"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "望",
          on: ["ボウ", "モウ"],
          kun: ["のぞ.む", "もち"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1084,
      kanji: "台本",
      reading: "だいほん",
      meanings: {
        ja: "台本",
        en: "script (stage/film)",
        zh: "剧本",
        tw: "劇本",
        ko: "대본",
        vi: "kịch bản",
        th: "บทละคร/ภาพยนตร์",
        my: "ဇာတ်ညွှန်း",
        km: "គ្រោងសម្ដែង",
      },
      furigana: [
        {
          rb: "台本",
          rt: "だいほん",
        },
      ],
      kanjiInfo: [
        {
          char: "台",
          on: ["ダイ", "タイ"],
          kun: ["うてな", "われ", "つかさ"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1085,
      kanji: "タイマー",
      reading: "タイマー",
      meanings: {
        ja: "タイマー",
        en: "timer",
        zh: "定时器",
        tw: "計時器",
        ko: "타이머",
        vi: "bộ hẹn giờ",
        th: "ตัวจับเวลา",
        my: "တိုင်မာ",
        km: "ម៉ាស៊ីនកំណត់ពេល",
      },
      furigana: [
        {
          rb: "タイマー",
          rt: "タイマー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1086,
      kanji: "怠慢",
      reading: "たいまん",
      meanings: {
        ja: "怠慢",
        en: "negligence; slackness",
        zh: "怠慢",
        tw: "怠慢",
        ko: "태만",
        vi: "cẩu thả; lười biếng",
        th: "ละเลย/เฉื่อยชา",
        my: "ပျက်စီးပျောင်း",
        km: "ធ្វេសប្រហែស",
      },
      furigana: [
        {
          rb: "怠慢",
          rt: "たいまん",
        },
      ],
      kanjiInfo: [
        {
          char: "怠",
          on: ["タイ"],
          kun: ["おこた.る", "なま.ける"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "慢",
          on: ["マン"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1087,
      kanji: "タイミング",
      reading: "タイミング",
      meanings: {
        ja: "タイミング",
        en: "timing",
        zh: "时机；时点",
        tw: "時機；時點",
        ko: "타이밍",
        vi: "thời điểm",
        th: "จังหวะเวลา",
        my: "အချိန်ချိန်ညှိ",
        km: "ពេលវេលា",
      },
      furigana: [
        {
          rb: "タイミング",
          rt: "タイミング",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1088,
      kanji: "タイム",
      reading: "タイム",
      meanings: {
        ja: "タイム",
        en: "time (record/measure)",
        zh: "时间（纪录）",
        tw: "時間（紀錄）",
        ko: "타임",
        vi: "thời gian (kỷ lục)",
        th: "เวลา (สถิติ)",
        my: "အချိန် (စာရင်း)",
        km: "ពេលវេលា (កំណត់ត្រា)",
      },
      furigana: [
        {
          rb: "タイム",
          rt: "タイム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1089,
      kanji: "対面",
      reading: "たいめん",
      meanings: {
        ja: "対面",
        en: "face-to-face meeting",
        zh: "见面",
        tw: "見面",
        ko: "대면",
        vi: "gặp mặt",
        th: "พบกันต่อหน้า",
        my: "မျက်နှာချင်းဆိုင်",
        km: "ជួបមុខ",
      },
      furigana: [
        {
          rb: "対面",
          rt: "たいめん",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1090,
      kanji: "代用",
      reading: "だいよう",
      meanings: {
        ja: "代用",
        en: "substitution; substitute",
        zh: "代用",
        tw: "代用",
        ko: "대용",
        vi: "thay thế (dùng tạm)",
        th: "ใช้แทน",
        my: "အစားထိုးအသုံး",
        km: "ជំនួសប្រើ",
      },
      furigana: [
        {
          rb: "代用",
          rt: "だいよう",
        },
      ],
      kanjiInfo: [
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1091,
      kanji: "体力",
      reading: "たいりょく",
      meanings: {
        ja: "体力",
        en: "physical strength",
        zh: "体力",
        tw: "體力",
        ko: "체력",
        vi: "thể lực",
        th: "กำลังกาย",
        my: "ကိုယ်ခံအား",
        km: "កម្លាំងរាងកាយ",
      },
      furigana: [
        {
          rb: "体力",
          rt: "たいりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1092,
      kanji: "タイル",
      reading: "タイル",
      meanings: {
        ja: "タイル",
        en: "tile",
        zh: "瓷砖",
        tw: "瓷磚",
        ko: "타일",
        vi: "gạch lát",
        th: "กระเบื้อง",
        my: "တိုင်လ်",
        km: "កម្រាលឥដ្ឋ",
      },
      furigana: [
        {
          rb: "タイル",
          rt: "タイル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1093,
      kanji: "対話",
      reading: "たいわ",
      meanings: {
        ja: "対話",
        en: "dialogue",
        zh: "对话",
        tw: "對話",
        ko: "대화",
        vi: "đối thoại",
        th: "การสนทนา",
        my: "ဆွေးနွေးပွဲ",
        km: "សន្ទនា",
      },
      furigana: [
        {
          rb: "対話",
          rt: "たいわ",
        },
      ],
      kanjiInfo: [
        {
          char: "対",
          on: ["タイ", "ツイ"],
          kun: [
            "あいて",
            "こた.える",
            "そろ.い",
            "つれあ.い",
            "なら.ぶ",
            "むか.う",
          ],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1094,
      kanji: "打開",
      reading: "だかい",
      meanings: {
        ja: "打開",
        en: "breakthrough",
        zh: "打開局面",
        tw: "打開局面",
        ko: "타개",
        vi: "phá vỡ bế tắc",
        th: "ฝ่าวิกฤต",
        my: "အပြစ်လမ်းရှာ",
        km: "ដោះស្រាយបញ្ហា",
      },
      furigana: [
        {
          rb: "打開",
          rt: "だかい",
        },
      ],
      kanjiInfo: [
        {
          char: "打",
          on: ["ダ", "ダース"],
          kun: ["う.つ", "う.ち-", "ぶ.つ"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1095,
      kanji: "焚火",
      reading: "たきび",
      meanings: {
        ja: "焚火",
        en: "bonfire; open fire",
        zh: "篝火",
        tw: "營火/篝火",
        ko: "모닥불",
        vi: "lửa trại",
        th: "กองไฟ",
        my: " မီးဖို့ (လူယ့်)",
        km: "ភ្លើងកំសាន្ត",
      },
      furigana: [
        {
          rb: "焚火",
          rt: "たきび",
        },
      ],
      kanjiInfo: [
        {
          char: "焚",
          on: ["フン", "ホン", "ハン"],
          kun: ["た.く", "や.く", "やきがり"],
          strokes: 12,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
        {
          char: "火",
          on: ["カ"],
          kun: ["ひ", "-び", "ほ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1096,
      kanji: "妥協",
      reading: "だきょう",
      meanings: {
        ja: "妥協",
        en: "compromise",
        zh: "妥协",
        tw: "妥協",
        ko: "타협",
        vi: "thỏa hiệp",
        th: "ประนีประนอม",
        my: "ညှိနှိုင်း",
        km: "សម្រុះសម្រួល",
      },
      furigana: [
        {
          rb: "妥協",
          rt: "だきょう",
        },
      ],
      kanjiInfo: [
        {
          char: "妥",
          on: ["ダ"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "協",
          on: ["キョウ"],
          kun: [],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1097,
      kanji: "丈",
      reading: "たけ",
      meanings: {
        ja: "丈",
        en: "height; length",
        zh: "身高；长度",
        tw: "身高；長度",
        ko: "길이; 키",
        vi: "chiều cao; chiều dài",
        th: "ความสูง/ยาว",
        my: "အမြင့်/အလျား",
        km: "កម្ពស់/ប្រវែង",
      },
      furigana: [
        {
          rb: "丈",
          rt: "たけ",
        },
      ],
      kanjiInfo: [
        {
          char: "丈",
          on: ["ジョウ"],
          kun: ["たけ", "だけ"],
          strokes: 3,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1098,
      kanji: "打撃",
      reading: "だげき",
      meanings: {
        ja: "打撃",
        en: "blow; damage",
        zh: "打击",
        tw: "打擊",
        ko: "타격",
        vi: "đòn giáng; tổn hại",
        th: "แรงกระแทก/ผลกระทบ",
        my: "ခွန်အားတိုက်ခိုက်",
        km: "ការបុកបក់",
      },
      furigana: [
        {
          rb: "打撃",
          rt: "だげき",
        },
      ],
      kanjiInfo: [
        {
          char: "打",
          on: ["ダ", "ダース"],
          kun: ["う.つ", "う.ち-", "ぶ.つ"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "撃",
          on: ["ゲキ"],
          kun: ["う.つ"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1099,
      kanji: "妥結",
      reading: "だけつ",
      meanings: {
        ja: "妥結",
        en: "settlement; agreement",
        zh: "妥协达成",
        tw: "妥協達成",
        ko: "타결",
        vi: "đi đến thỏa thuận",
        th: "ตกลงยุติ",
        my: "သဘောတူဖြေရှင်း",
        km: "ព្រមព្រៀងបាន",
      },
      furigana: [
        {
          rb: "妥結",
          rt: "だけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "妥",
          on: ["ダ"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1100,
      kanji: "駄作",
      reading: "ださく",
      meanings: {
        ja: "駄作",
        en: "poor piece of work",
        zh: "拙作",
        tw: "拙作",
        ko: "졸작",
        vi: "tác phẩm dở",
        th: "ผลงานห่วย",
        my: "ကုန်ကျမကောင်းသည့်အလုပ်",
        km: "ស្នាដៃអន់",
      },
      furigana: [
        {
          rb: "駄作",
          rt: "ださく",
        },
      ],
      kanjiInfo: [
        {
          char: "駄",
          on: ["ダ", "タ"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
