export const n1part17 = {
  Lesson17: [
    {
      id: 801,
      kanji: "圧迫",
      reading: "あっぱく",
      meanings: {
        ja: "圧迫",
        en: "pressure; oppression",
        zh: "压迫",
        tw: "壓迫",
        ko: "압박",
        vi: "áp bức; ép",
        th: "กดดัน; กดทับ",
        my: "ဖိစီးမှု",
        km: "ការរឹតត្បិត",
      },
      furigana: [
        {
          rb: "圧迫",
          rt: "あっぱく",
        },
      ],
      kanjiInfo: [
        {
          char: "圧",
          on: ["アツ", "エン", "オウ"],
          kun: ["お.す", "へ.す", "おさ.える", "お.さえる"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "迫",
          on: ["ハク"],
          kun: ["せま.る"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 802,
      kanji: "圧力",
      reading: "あつりょく",
      meanings: {
        ja: "圧力",
        en: "pressure",
        zh: "压力",
        tw: "壓力",
        ko: "압력",
        vi: "áp lực",
        th: "ความดัน",
        my: "ဖိအား",
        km: "សម្ពាធ",
      },
      furigana: [
        {
          rb: "圧力",
          rt: "あつりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "圧",
          on: ["アツ", "エン", "オウ"],
          kun: ["お.す", "へ.す", "おさ.える", "お.さえる"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 803,
      kanji: "当て",
      reading: "あて",
      meanings: {
        ja: "当て",
        en: "aim; reliance",
        zh: "目标；指望",
        tw: "目標；指望",
        ko: "목표; 의지",
        vi: "mục tiêu; chỗ trông",
        th: "เป้าหมาย; ที่พึ่ง",
        my: "ပန်းတိုင်; ကိုးကားရာ",
        km: "គោលដៅ; ការរំពឹង",
      },
      furigana: [
        {
          rb: "当て",
          rt: "あて",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 804,
      kanji: "当て字",
      reading: "あてじ",
      meanings: {
        ja: "当て字",
        en: "phonetic kanji",
        zh: "借字",
        tw: "借字",
        ko: "당자(음차 한자)",
        vi: "chữ Hán mượn âm",
        th: "ตัวคันจิแทนเสียง",
        my: "အသံအလိုက်ကန်ဂျီ",
        km: "អក្សរខានជីតាមសំឡេង",
      },
      furigana: [
        {
          rb: "当て字",
          rt: "あてじ",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 805,
      kanji: "跡継ぎ",
      reading: "あとつぎ",
      meanings: {
        ja: "跡継ぎ",
        en: "heir; successor",
        zh: "继承人",
        tw: "繼承人",
        ko: "후계자",
        vi: "người thừa kế",
        th: "ทายาท",
        my: "အမွေဆက်တင်",
        km: "អ្នកស្នងមរតក",
      },
      furigana: [
        {
          rb: "跡継ぎ",
          rt: "あとつぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "跡",
          on: ["セキ"],
          kun: ["あと"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "継",
          on: ["ケイ"],
          kun: ["つ.ぐ", "まま-"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 806,
      kanji: "後回し",
      reading: "あとまわし",
      meanings: {
        ja: "後回し",
        en: "postponement; putting off",
        zh: "推迟",
        tw: "延後",
        ko: "미룸",
        vi: "để sau",
        th: "เลื่อนไปทีหลัง",
        my: "နောက်ဆုတ်သတ်မှတ်",
        km: "ពន្យាពេល",
      },
      furigana: [
        {
          rb: "後回し",
          rt: "あとまわし",
        },
      ],
      kanjiInfo: [
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "回",
          on: ["カイ", "エ"],
          kun: [
            "まわ.る",
            "-まわ.る",
            "-まわ.り",
            "まわ.す",
            "-まわ.す",
            "まわ.し-",
            "-まわ.し",
            "もとお.る",
            "か.える",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 807,
      kanji: "油絵",
      reading: "あぶらえ",
      meanings: {
        ja: "油絵",
        en: "oil painting",
        zh: "油画",
        tw: "油畫",
        ko: "유화",
        vi: "tranh sơn dầu",
        th: "ภาพสีน้ำมัน",
        my: "ဆီချိတ်ရုပ်ပုံ",
        km: "រូបគំនូរប្រេង",
      },
      furigana: [
        {
          rb: "油絵",
          rt: "あぶらえ",
        },
      ],
      kanjiInfo: [
        {
          char: "油",
          on: ["ユ", "ユウ"],
          kun: ["あぶら"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "絵",
          on: ["カイ", "エ"],
          kun: [],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 808,
      kanji: "アプローチ",
      reading: "アプローチ",
      meanings: {
        ja: "アプローチ",
        en: "approach (to a problem)",
        zh: "方法；途径",
        tw: "方法；途徑",
        ko: "접근법",
        vi: "cách tiếp cận",
        th: "แนวทาง",
        my: "ဆက်ဆံ/ရောက်ရှိနည်း",
        km: "វិធីការចូលទៅរក",
      },
      furigana: [
        {
          rb: "アプローチ",
          rt: "アプローチ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 809,
      kanji: "雨具",
      reading: "あまぐ",
      meanings: {
        ja: "雨具",
        en: "rain gear",
        zh: "雨具",
        tw: "雨具",
        ko: "우비류",
        vi: "đồ đi mưa",
        th: "อุปกรณ์กันฝน",
        my: "မိုးကာပစ္စည်း",
        km: "ឧបករណ៍ការពារពេលភ្លៀង",
      },
      furigana: [
        {
          rb: "雨具",
          rt: "あまぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "雨",
          on: ["ウ"],
          kun: ["あめ", "あま-", "-さめ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "具",
          on: ["グ"],
          kun: ["そな.える", "つぶさ.に"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 810,
      kanji: "アマチュア",
      reading: "アマチュア",
      meanings: {
        ja: "アマチュア",
        en: "amateur",
        zh: "业余者",
        tw: "業餘者",
        ko: "아마추어",
        vi: "nghiệp dư",
        th: "สมัครเล่น",
        my: "အမားချွာ (မ पेशेवर)",
        km: "ស្ម័គ្រចិត្ត",
      },
      furigana: [
        {
          rb: "アマチュア",
          rt: "アマチュア",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 811,
      kanji: "網",
      reading: "あみ",
      meanings: {
        ja: "網",
        en: "net",
        zh: "网",
        tw: "網",
        ko: "그물",
        vi: "lưới",
        th: "ตาข่าย",
        my: "အဝတ်ခြင်္သေ့/လွှာ",
        km: "សំណាញ់",
      },
      furigana: [
        {
          rb: "網",
          rt: "あみ",
        },
      ],
      kanjiInfo: [
        {
          char: "網",
          on: ["モウ"],
          kun: ["あみ"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 812,
      kanji: "過ち",
      reading: "あやまち",
      meanings: {
        ja: "過ち",
        en: "fault; error",
        zh: "过失",
        tw: "過失",
        ko: "과실; 잘못",
        vi: "lỗi lầm",
        th: "ความผิดพลาด",
        my: "အမှား",
        km: "កំហុស",
      },
      furigana: [
        {
          rb: "過ち",
          rt: "あやまち",
        },
      ],
      kanjiInfo: [
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 813,
      kanji: "歩み",
      reading: "あゆみ",
      meanings: {
        ja: "歩み",
        en: "walking; progress",
        zh: "步伐；进展",
        tw: "步伐；進展",
        ko: "걸음; 진전",
        vi: "bước đi; tiến triển",
        th: "การเดิน; ความคืบหน้า",
        my: "လှည့်လည်ခြင်း; တိုးတက်မှု",
        km: "ការដើរ; ការរីកចម្រើន",
      },
      furigana: [
        {
          rb: "歩み",
          rt: "あゆみ",
        },
      ],
      kanjiInfo: [
        {
          char: "歩",
          on: ["ホ", "ブ", "フ"],
          kun: ["ある.く", "あゆ.む"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 814,
      kanji: "争い",
      reading: "あらそい",
      meanings: {
        ja: "争い",
        en: "conflict; fight",
        zh: "争斗",
        tw: "爭鬥",
        ko: "다툼; 분쟁",
        vi: "tranh chấp",
        th: "ความขัดแย้ง",
        my: "အငြင်းပွားမှု",
        km: "ភាពវិវាទ",
      },
      furigana: [
        {
          rb: "争い",
          rt: "あらそい",
        },
      ],
      kanjiInfo: [
        {
          char: "争",
          on: ["ソウ"],
          kun: ["あらそ.う", "いか.でか"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 815,
      kanji: "アラブ",
      reading: "アラブ",
      meanings: {
        ja: "アラブ",
        en: "Arab",
        zh: "阿拉伯",
        tw: "阿拉伯",
        ko: "아랍",
        vi: "Ả Rập",
        th: "อาหรับ",
        my: "အာရပ်",
        km: "អារ៉ាប់",
      },
      furigana: [
        {
          rb: "アラブ",
          rt: "アラブ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 816,
      kanji: "霰",
      reading: "あられ",
      meanings: {
        ja: "霰",
        en: "hail (small hailstones)",
        zh: "霰",
        tw: "霰",
        ko: "싸라기눈/우박",
        vi: "mưa đá (nhỏ)",
        th: "ลูกเห็บเม็ดเล็ก",
        my: "မိုးရေခဲစ",
        km: "ព្រិលថ្នាំ (គ្រាប់តូច)",
      },
      furigana: [
        {
          rb: "霰",
          rt: "あられ",
        },
      ],
      kanjiInfo: [
        {
          char: "霰",
          on: ["セン", "サン"],
          kun: ["あられ"],
          strokes: 20,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 817,
      kanji: "有り様",
      reading: "ありさま",
      meanings: {
        ja: "有り様",
        en: "state; condition",
        zh: "情况",
        tw: "情況",
        ko: "상태",
        vi: "tình trạng",
        th: "สภาพ",
        my: "အခြေအနေ",
        km: "ស្ថានភាព",
      },
      furigana: [
        {
          rb: "有り様",
          rt: "ありさま",
        },
      ],
      kanjiInfo: [
        {
          char: "有",
          on: ["ユウ", "ウ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "様",
          on: ["ヨウ", "ショウ"],
          kun: ["さま", "さん"],
          strokes: 14,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 818,
      kanji: "アルミ",
      reading: "アルミ",
      meanings: {
        ja: "アルミ",
        en: "aluminum",
        zh: "铝",
        tw: "鋁",
        ko: "알루미늄",
        vi: "nhôm",
        th: "อะลูมิเนียม",
        my: "အလူမီနီယမ်",
        km: "អាលុយមីញ៉ូម",
      },
      furigana: [
        {
          rb: "アルミ",
          rt: "アルミ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 819,
      kanji: "アワー",
      reading: "アワー",
      meanings: {
        ja: "アワー",
        en: "hour",
        zh: "小时",
        tw: "小時",
        ko: "시간",
        vi: "giờ",
        th: "ชั่วโมง",
        my: "နာရီ",
        km: "ម៉ោង",
      },
      furigana: [
        {
          rb: "アワー",
          rt: "アワー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 820,
      kanji: "アンコール",
      reading: "アンコール",
      meanings: {
        ja: "アンコール",
        en: "encore",
        zh: "安可",
        tw: "安可",
        ko: "앙코르",
        vi: "yêu cầu diễn lại",
        th: "อังกอร์ (ขอเพิ่ม)",
        my: "ထပ်ဖော်ပြရန်တောင်းဆို",
        km: "ស្នើឲ្យបន្តសម្ដែង",
      },
      furigana: [
        {
          rb: "アンコール",
          rt: "アンコール",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 821,
      kanji: "暗殺",
      reading: "あんさつ",
      meanings: {
        ja: "暗殺",
        en: "assassination",
        zh: "暗杀",
        tw: "暗殺",
        ko: "암살",
        vi: "ám sát",
        th: "ลอบสังหาร",
        my: "လျှို့ဝှက်သတ်ဖြတ်",
        km: "សម្លាប់លាក់លៀម",
      },
      furigana: [
        {
          rb: "暗殺",
          rt: "あんさつ",
        },
      ],
      kanjiInfo: [
        {
          char: "暗",
          on: ["アン"],
          kun: ["くら.い", "くら.む", "くれ.る"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "殺",
          on: ["サツ", "サイ", "セツ"],
          kun: ["ころ.す", "-ごろ.し", "そ.ぐ", "あや.める"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 822,
      kanji: "暗算",
      reading: "あんざん",
      meanings: {
        ja: "暗算",
        en: "mental arithmetic",
        zh: "心算",
        tw: "心算",
        ko: "암산",
        vi: "tính nhẩm",
        th: "คำนวณในใจ",
        my: "မှတ်မှတ်သားသားတွက်",
        km: "គណនាតាមមាត់",
      },
      furigana: [
        {
          rb: "暗算",
          rt: "あんざん",
        },
      ],
      kanjiInfo: [
        {
          char: "暗",
          on: ["アン"],
          kun: ["くら.い", "くら.む", "くれ.る"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 823,
      kanji: "暗示",
      reading: "あんじ",
      meanings: {
        ja: "暗示",
        en: "hint; suggestion",
        zh: "暗示",
        tw: "暗示",
        ko: "암시",
        vi: "ám chỉ",
        th: "นัย; บอกเป็นนัย",
        my: "ရိပ်မိုးချက်",
        km: "ការជំរុញដោយអនាមិក",
      },
      furigana: [
        {
          rb: "暗示",
          rt: "あんじ",
        },
      ],
      kanjiInfo: [
        {
          char: "暗",
          on: ["アン"],
          kun: ["くら.い", "くら.む", "くれ.る"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "示",
          on: ["ジ", "シ"],
          kun: ["しめ.す"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 824,
      kanji: "安静",
      reading: "あんせい",
      meanings: {
        ja: "安静",
        en: "rest; repose",
        zh: "安静",
        tw: "安靜",
        ko: "안정; 안식",
        vi: "nghỉ ngơi tĩnh dưỡng",
        th: "พักผ่อนนิ่งๆ",
        my: "ငြိမ်သက်နေခြင်း",
        km: "សម្រាកស្ងៀមស្ងាត់",
      },
      furigana: [
        {
          rb: "安静",
          rt: "あんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "安",
          on: ["アン"],
          kun: ["やす.い", "やす.まる", "やす", "やす.らか"],
          strokes: 6,
          grade: 3,
          jlpt: 4,
          radical: null,
        },
        {
          char: "静",
          on: ["セイ", "ジョウ"],
          kun: ["しず-", "しず.か", "しず.まる", "しず.める"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 825,
      kanji: "言い訳",
      reading: "いいわけ",
      meanings: {
        ja: "言い訳",
        en: "excuse",
        zh: "借口",
        tw: "藉口",
        ko: "변명",
        vi: "biện minh",
        th: "แก้ตัว",
        my: "ဆိုထင်ရှားမှု",
        km: "ស្រោចស្រង់",
      },
      furigana: [
        {
          rb: "言い訳",
          rt: "いいわけ",
        },
      ],
      kanjiInfo: [
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "訳",
          on: ["ヤク"],
          kun: ["わけ"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 826,
      kanji: "家出",
      reading: "いえで",
      meanings: {
        ja: "家出",
        en: "running away from home",
        zh: "离家出走",
        tw: "離家出走",
        ko: "가출",
        vi: "bỏ nhà đi",
        th: "หนีออกจากบ้าน",
        my: "အိမ်ထွက်ပြေး",
        km: "រត់ចេញពីផ្ទះ",
      },
      furigana: [
        {
          rb: "家出",
          rt: "いえで",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 827,
      kanji: "異議",
      reading: "いぎ",
      meanings: {
        ja: "異議",
        en: "objection",
        zh: "异议",
        tw: "異議",
        ko: "이의",
        vi: "phản đối",
        th: "คัดค้าน",
        my: "အနိုင်ယူမည်ဟုဆိုခြင်း",
        km: "ប្រឆាំង",
      },
      furigana: [
        {
          rb: "異議",
          rt: "いぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "異",
          on: ["イ"],
          kun: ["こと", "こと.なる", "け"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 828,
      kanji: "生き甲斐",
      reading: "いきがい",
      meanings: {
        ja: "生き甲斐",
        en: "reason for living",
        zh: "人生意义",
        tw: "人生意義",
        ko: "삶의 보람",
        vi: "lý do sống",
        th: "แรงบันดาลใจในการมีชีวิต",
        my: "ဘဝအဓိပ္ပါယ်",
        km: "ហេតុផលរស់នៅ",
      },
      furigana: [
        {
          rb: "生き甲斐",
          rt: "いきがい",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "甲",
          on: ["コウ", "カン"],
          kun: ["きのえ"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "斐",
          on: ["ヒ", "イ"],
          kun: [],
          strokes: 12,
          grade: 9,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 829,
      kanji: "行き違い",
      reading: "いきちがい",
      meanings: {
        ja: "行き違い",
        en: "crossing without meeting; mix-up",
        zh: "错过；误会",
        tw: "錯過；誤會",
        ko: "엇갈림; 오해",
        vi: "lệch hướng; lỡ nhau",
        th: "คลาดกัน; เข้าใจผิด",
        my: "ကြာလိမ့်မည့်အေ",
        km: "ខកខានឆ្លងកាត់គ្នា",
      },
      furigana: [
        {
          rb: "行き違い",
          rt: "いきちがい",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "違",
          on: ["イ"],
          kun: [
            "ちが.う",
            "ちが.い",
            "ちが.える",
            "-ちが.える",
            "たが.う",
            "たが.える",
          ],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 830,
      kanji: "育成",
      reading: "いくせい",
      meanings: {
        ja: "育成",
        en: "nurturing; training",
        zh: "培育",
        tw: "培育",
        ko: "육성",
        vi: "bồi dưỡng",
        th: "บ่มเพาะ; พัฒนา",
        my: "ဖွံ့ဖြိုးတိုးတက်အောင်လုပ်ခြင်း",
        km: "បង្កើតបណ្ដុះបណ្ដាល",
      },
      furigana: [
        {
          rb: "育成",
          rt: "いくせい",
        },
      ],
      kanjiInfo: [
        {
          char: "育",
          on: ["イク"],
          kun: ["そだ.つ", "そだ.ち", "そだ.てる", "はぐく.む"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 831,
      kanji: "異見",
      reading: "いけん",
      meanings: {
        ja: "異見",
        en: "different opinion",
        zh: "不同意见",
        tw: "不同意見",
        ko: "이견",
        vi: "ý kiến khác",
        th: "ความเห็นต่าง",
        my: "အမြင်ကွဲ",
        km: "យោបល់ខុស",
      },
      furigana: [
        {
          rb: "異見",
          rt: "いけん",
        },
      ],
      kanjiInfo: [
        {
          char: "異",
          on: ["イ"],
          kun: ["こと", "こと.なる", "け"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 832,
      kanji: "意向",
      reading: "いこう",
      meanings: {
        ja: "意向",
        en: "intention; will",
        zh: "意向",
        tw: "意向",
        ko: "의향",
        vi: "ý hướng",
        th: "ความประสงค์",
        my: "ရည်ရွယ်ချက်",
        km: "បំណង",
      },
      furigana: [
        {
          rb: "意向",
          rt: "いこう",
        },
      ],
      kanjiInfo: [
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "向",
          on: ["コウ"],
          kun: [
            "む.く",
            "む.い",
            "-む.き",
            "む.ける",
            "-む.け",
            "む.かう",
            "む.かい",
            "む.こう",
            "む.こう-",
            "むこ",
            "むか.い",
          ],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 833,
      kanji: "移行",
      reading: "いこう",
      meanings: {
        ja: "移行",
        en: "transition; shift",
        zh: "过渡",
        tw: "過渡",
        ko: "이행",
        vi: "chuyển đổi",
        th: "เปลี่ยนผ่าน",
        my: "လွှဲပြောင်းခြင်း",
        km: "ផ្លាស់ប្ដូរ",
      },
      furigana: [
        {
          rb: "移行",
          rt: "いこう",
        },
      ],
      kanjiInfo: [
        {
          char: "移",
          on: ["イ"],
          kun: ["うつ.る", "うつ.す"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 834,
      kanji: "移住",
      reading: "いじゅう",
      meanings: {
        ja: "移住",
        en: "migration; relocation",
        zh: "移居",
        tw: "移居",
        ko: "이주",
        vi: "di cư",
        th: "อพยพย้ายถิ่น",
        my: "ပြောင်းရွှေ့နေထိုင်",
        km: "ផ្លាស់ទីរស់នៅ",
      },
      furigana: [
        {
          rb: "移住",
          rt: "いじゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "移",
          on: ["イ"],
          kun: ["うつ.る", "うつ.す"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "住",
          on: ["ジュウ", "ヂュウ", "チュウ"],
          kun: ["す.む", "す.まう", "-ず.まい"],
          strokes: 7,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 835,
      kanji: "衣装",
      reading: "いしょう",
      meanings: {
        ja: "衣装",
        en: "costume; outfit",
        zh: "服装",
        tw: "服裝",
        ko: "의상",
        vi: "y phục",
        th: "เครื่องแต่งกาย",
        my: "ဝတ်စုံ",
        km: "ឯកសណ្ឋាន/សម្លៀកបំពាក់",
      },
      furigana: [
        {
          rb: "衣装",
          rt: "いしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "衣",
          on: ["イ", "エ"],
          kun: ["ころも", "きぬ", "-ぎ"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "装",
          on: ["ソウ", "ショウ"],
          kun: ["よそお.う", "よそお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 836,
      kanji: "異性",
      reading: "いせい",
      meanings: {
        ja: "異性",
        en: "the opposite sex",
        zh: "异性",
        tw: "異性",
        ko: "이성",
        vi: "khác giới",
        th: "เพศตรงข้าม",
        my: "ပြောင်းလဲသောလိင်",
        km: "ភេទផ្ទុយ",
      },
      furigana: [
        {
          rb: "異性",
          rt: "いせい",
        },
      ],
      kanjiInfo: [
        {
          char: "異",
          on: ["イ"],
          kun: ["こと", "こと.なる", "け"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "性",
          on: ["セイ", "ショウ"],
          kun: ["さが"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 837,
      kanji: "遺跡",
      reading: "いせき",
      meanings: {
        ja: "遺跡",
        en: "ruins; archaeological site",
        zh: "遗迹",
        tw: "遺跡",
        ko: "유적",
        vi: "di tích",
        th: "โบราณสถาน",
        my: "ယဉ်ကျေးမှုအမွေအနှစ်",
        km: "បេតិកភណ្ឌបុរាណ",
      },
      furigana: [
        {
          rb: "遺跡",
          rt: "いせき",
        },
      ],
      kanjiInfo: [
        {
          char: "遺",
          on: ["イ", "ユイ"],
          kun: ["のこ.す"],
          strokes: 15,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "跡",
          on: ["セキ"],
          kun: ["あと"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 838,
      kanji: "依存",
      reading: "いぞん",
      meanings: {
        ja: "依存",
        en: "dependence",
        zh: "依存",
        tw: "依存",
        ko: "의존",
        vi: "phụ thuộc",
        th: "พึ่งพา",
        my: "မူတည်ခြင်း",
        km: "អាស្រ័យលើ",
      },
      furigana: [
        {
          rb: "依存",
          rt: "いぞん",
        },
      ],
      kanjiInfo: [
        {
          char: "依",
          on: ["イ", "エ"],
          kun: ["よ.る"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "存",
          on: ["ソン", "ゾン"],
          kun: ["ながら.える", "あ.る", "たも.つ", "と.う"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 839,
      kanji: "委託",
      reading: "いたく",
      meanings: {
        ja: "委託",
        en: "entrustment; consignment",
        zh: "委托",
        tw: "委託",
        ko: "위탁",
        vi: "ủy thác",
        th: "มอบหมาย",
        my: "ဦးစားပေးရန်အပ်နှံ",
        km: "ស្នើសុំឲ្យធ្វើជំនួស",
      },
      furigana: [
        {
          rb: "委託",
          rt: "いたく",
        },
      ],
      kanjiInfo: [
        {
          char: "委",
          on: ["イ"],
          kun: ["ゆだ.ねる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "託",
          on: ["タク"],
          kun: ["かこつ.ける", "かこ.つ", "かこ.つける"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 840,
      kanji: "出世",
      reading: "しゅっせ",
      meanings: {
        ja: "出世",
        en: "success in life; promotion",
        zh: "出人头地",
        tw: "出人頭地",
        ko: "출세",
        vi: "thành đạt",
        th: "เจริญก้าวหน้า",
        my: "အောင်မြင်မှု",
        km: "ជោគជ័យក្នុងជីវិត",
      },
      furigana: [
        {
          rb: "出世",
          rt: "しゅっせ",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 841,
      kanji: "出題",
      reading: "しゅつだい",
      meanings: {
        ja: "出題",
        en: "setting exam questions",
        zh: "出题",
        tw: "出題",
        ko: "출제",
        vi: "ra đề",
        th: "ออกข้อสอบ",
        my: "စာမေးပွဲမေးခွန်း ထုတ်",
        km: "ដាក់សំណួរប្រលង",
      },
      furigana: [
        {
          rb: "出題",
          rt: "しゅつだい",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "題",
          on: ["ダイ"],
          kun: [],
          strokes: 18,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 842,
      kanji: "出動",
      reading: "しゅつどう",
      meanings: {
        ja: "出動",
        en: "mobilization; dispatch",
        zh: "出动",
        tw: "出動",
        ko: "출동",
        vi: "xuất quân/điều động",
        th: "ระดม/ออกปฏิบัติการ",
        my: "တပ်ဖွဲ့လှုပ်ရှား",
        km: "ចេញផ្តើមសកម្មភាព",
      },
      furigana: [
        {
          rb: "出動",
          rt: "しゅつどう",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 843,
      kanji: "出費",
      reading: "しゅっぴ",
      meanings: {
        ja: "出費",
        en: "expenses",
        zh: "开销",
        tw: "開銷",
        ko: "지출",
        vi: "chi phí",
        th: "ค่าใช้จ่าย",
        my: "အသုံးစရိတ်",
        km: "ចំណាយ",
      },
      furigana: [
        {
          rb: "出費",
          rt: "しゅっぴ",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "費",
          on: ["ヒ"],
          kun: ["つい.やす", "つい.える"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 844,
      kanji: "出品",
      reading: "しゅっぴん",
      meanings: {
        ja: "出品",
        en: "exhibiting; putting on display",
        zh: "展出",
        tw: "展出",
        ko: "출품",
        vi: "trưng bày",
        th: "นำออกแสดง",
        my: "ပြသရန်တင်သွင်း",
        km: "បង្ហាញក្នុងពិព័រណ៍",
      },
      furigana: [
        {
          rb: "出品",
          rt: "しゅっぴん",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 845,
      kanji: "主導",
      reading: "しゅどう",
      meanings: {
        ja: "主導",
        en: "leadership; initiative",
        zh: "主导",
        tw: "主導",
        ko: "주도",
        vi: "chủ đạo",
        th: "นำพา",
        my: "ဦးဆောင်မှု",
        km: "ដឹកនាំ",
      },
      furigana: [
        {
          rb: "主導",
          rt: "しゅどう",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "導",
          on: ["ドウ"],
          kun: ["みちび.く"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 846,
      kanji: "主任",
      reading: "しゅにん",
      meanings: {
        ja: "主任",
        en: "person in charge; chief",
        zh: "主任",
        tw: "主任",
        ko: "주임",
        vi: "chủ nhiệm",
        th: "หัวหน้าผู้รับผิดชอบ",
        my: "တာဝန်ခံ",
        km: "អ្នកទទួលខុសត្រូវ",
      },
      furigana: [
        {
          rb: "主任",
          rt: "しゅにん",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "任",
          on: ["ニン"],
          kun: ["まか.せる", "まか.す"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 847,
      kanji: "首脳",
      reading: "しゅのう",
      meanings: {
        ja: "首脳",
        en: "leaders; head",
        zh: "首脑",
        tw: "首腦",
        ko: "수뇌",
        vi: "người đứng đầu",
        th: "ผู้นำระดับสูง",
        my: "ခေါင်းဆောင်အကြီးအကဲ",
        km: "មេដឹកនាំកំពូល",
      },
      furigana: [
        {
          rb: "首脳",
          rt: "しゅのう",
        },
      ],
      kanjiInfo: [
        {
          char: "首",
          on: ["シュ"],
          kun: ["くび"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "脳",
          on: ["ノウ", "ドウ"],
          kun: ["のうずる"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 848,
      kanji: "守備",
      reading: "しゅび",
      meanings: {
        ja: "守備",
        en: "defense (sports/war)",
        zh: "防守",
        tw: "守備",
        ko: "수비",
        vi: "phòng thủ",
        th: "ตั้งรับ",
        my: "ကာကွယ်ရေး",
        km: "ការពារ",
      },
      furigana: [
        {
          rb: "守備",
          rt: "しゅび",
        },
      ],
      kanjiInfo: [
        {
          char: "守",
          on: ["シュ", "ス"],
          kun: ["まも.る", "まも.り", "もり", "-もり", "かみ"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "備",
          on: ["ビ"],
          kun: ["そな.える", "そな.わる", "つぶさ.に"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 849,
      kanji: "手法",
      reading: "しゅほう",
      meanings: {
        ja: "手法",
        en: "technique; method",
        zh: "手法",
        tw: "手法",
        ko: "수법; 기법",
        vi: "phương pháp",
        th: "วิธีการ",
        my: "နည်းလမ်း",
        km: "បច្ចេកទេស",
      },
      furigana: [
        {
          rb: "手法",
          rt: "しゅほう",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "法",
          on: ["ホウ", "ハッ", "ホッ", "フラン"],
          kun: ["のり"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 850,
      kanji: "樹木",
      reading: "じゅもく",
      meanings: {
        ja: "樹木",
        en: "tree(s)",
        zh: "树木",
        tw: "樹木",
        ko: "수목",
        vi: "cây cối",
        th: "ไม้ยืนต้น",
        my: "အ деревоများ",
        km: "ដើមឈើ",
      },
      furigana: [
        {
          rb: "樹木",
          rt: "じゅもく",
        },
      ],
      kanjiInfo: [
        {
          char: "樹",
          on: ["ジュ"],
          kun: ["き"],
          strokes: 16,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "木",
          on: ["ボク", "モク"],
          kun: ["き", "こ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
