export const n1part4 = {
  Lesson4: [
    {
      id: 151,
      kanji: "参照",
      reading: "さんしょう",
      meanings: {
        ja: "参照",
        en: "reference (e.g. to a dictionary)",
        zh: "参照",
        tw: "參照",
        ko: "참조",
        vi: "tham khảo",
        th: "การอ้างอิง",
        my: "ကိုးကားမှု",
        km: "យោង",
      },
      furigana: [
        {
          rb: "参照",
          rt: "さんしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "参",
          on: ["サン", "シン"],
          kun: ["まい.る", "まい-", "まじわる", "みつ"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "照",
          on: ["ショウ"],
          kun: ["て.る", "て.らす", "て.れる"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 152,
      kanji: "参上",
      reading: "さんじょう",
      meanings: {
        ja: "参上",
        en: "calling on; visiting (a superior)",
        zh: "拜访",
        tw: "拜訪",
        ko: "찾아뵘",
        vi: "đến thăm (người trên)",
        th: "เข้าพบ",
        my: "အထက်ကိုသွားလည်",
        km: "ទៅជួបអ្នកលើ",
      },
      furigana: [
        {
          rb: "参上",
          rt: "さんじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "参",
          on: ["サン", "シン"],
          kun: ["まい.る", "まい-", "まじわる", "みつ"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 153,
      kanji: "残高",
      reading: "ざんだか",
      meanings: {
        ja: "残高",
        en: "(bank) balance",
        zh: "余额",
        tw: "餘額",
        ko: "잔액",
        vi: "số dư tài khoản",
        th: "ยอดเงินคงเหลือ",
        my: "လက်ကျန်ငွေ",
        km: "សមតុល្យប្រាក់",
      },
      furigana: [
        {
          rb: "残高",
          rt: "ざんだか",
        },
      ],
      kanjiInfo: [
        {
          char: "残",
          on: ["ザン", "サン"],
          kun: ["のこ.る", "のこ.す", "そこな.う", "のこ.り"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "高",
          on: ["コウ"],
          kun: ["たか.い", "たか", "-だか", "たか.まる", "たか.める"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 154,
      kanji: "サンタクロース",
      reading: "サンタクロース",
      meanings: {
        ja: "サンタクロース",
        en: "Santa Claus",
        zh: "圣诞老人",
        tw: "聖誕老人",
        ko: "산타클로스",
        vi: "ông già Noel",
        th: "ซานตาคลอส",
        my: "စန္တာကလော့စ်",
        km: "សាន់តាខ្លូស",
      },
      furigana: [
        {
          rb: "サンタクロース",
          rt: "サンタクロース",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 155,
      kanji: "桟橋",
      reading: "さんばし",
      meanings: {
        ja: "桟橋",
        en: "wharf; pier",
        zh: "码头",
        tw: "碼頭",
        ko: "선창; 부두",
        vi: "bến tàu",
        th: "ท่าเรือ",
        my: "ဆိပ်ကမ်းတန်း",
        km: "ទំពាំងទន្លេ",
      },
      furigana: [
        {
          rb: "桟橋",
          rt: "さんばし",
        },
      ],
      kanjiInfo: [
        {
          char: "桟",
          on: ["サン", "セン"],
          kun: ["かけはし"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "橋",
          on: ["キョウ"],
          kun: ["はし"],
          strokes: 16,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 156,
      kanji: "賛美",
      reading: "さんび",
      meanings: {
        ja: "賛美",
        en: "praise; admiration",
        zh: "赞美",
        tw: "讚美",
        ko: "찬미",
        vi: "ca ngợi",
        th: "สรรเสริญ",
        my: "ချီးမွမ်းမှု",
        km: "សរសើរ",
      },
      furigana: [
        {
          rb: "賛美",
          rt: "さんび",
        },
      ],
      kanjiInfo: [
        {
          char: "賛",
          on: ["サン"],
          kun: ["たす.ける", "たた.える"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "美",
          on: ["ビ", "ミ"],
          kun: ["うつく.しい"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 157,
      kanji: "山腹",
      reading: "さんぷく",
      meanings: {
        ja: "山腹",
        en: "hillside; mountainside",
        zh: "山腰",
        tw: "山腰",
        ko: "산허리",
        vi: "sườn núi",
        th: "ไหล่เขา",
        my: "တောင်အပေါ်ဘက်",
        km: "ជើងភ្នំ",
      },
      furigana: [
        {
          rb: "山腹",
          rt: "さんぷく",
        },
      ],
      kanjiInfo: [
        {
          char: "山",
          on: ["サン", "セン"],
          kun: ["やま"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "腹",
          on: ["フク"],
          kun: ["はら"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 158,
      kanji: "産婦人科",
      reading: "さんふじんか",
      meanings: {
        ja: "産婦人科",
        en: "obstetrics and gynecology department",
        zh: "妇产科",
        tw: "婦產科",
        ko: "산부인과",
        vi: "khoa sản phụ",
        th: "แผนกสูตินรีเวช",
        my: "မီးယပ်နှင့်မိန်းကလေးရောဂါဌာန",
        km: "ផ្នែកសម្ភពនារី",
      },
      furigana: [
        {
          rb: "産婦人科",
          rt: "さんふじんか",
        },
      ],
      kanjiInfo: [
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "婦",
          on: ["フ"],
          kun: ["よめ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 159,
      kanji: "産物",
      reading: "さんぶつ",
      meanings: {
        ja: "産物",
        en: "product; produce",
        zh: "产品",
        tw: "產品",
        ko: "산물",
        vi: "sản vật",
        th: "ผลผลิต",
        my: "ထုတ်ကုန်",
        km: "ផលិតផល",
      },
      furigana: [
        {
          rb: "産物",
          rt: "さんぶつ",
        },
      ],
      kanjiInfo: [
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 160,
      kanji: "山脈",
      reading: "さんみゃく",
      meanings: {
        ja: "山脈",
        en: "mountain range",
        zh: "山脉",
        tw: "山脈",
        ko: "산맥",
        vi: "dãy núi",
        th: "เทือกเขา",
        my: "တောင်တန်း",
        km: "ជួរភ្នំ",
      },
      furigana: [
        {
          rb: "山脈",
          rt: "さんみゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "山",
          on: ["サン", "セン"],
          kun: ["やま"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "脈",
          on: ["ミャク"],
          kun: ["すじ"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 161,
      kanji: "仕上がり",
      reading: "しあがり",
      meanings: {
        ja: "仕上がり",
        en: "finish; completion",
        zh: "完成",
        tw: "完成",
        ko: "마무리",
        vi: "thành phẩm",
        th: "การเสร็จสิ้น",
        my: "အပြီးသတ်ခြင်း",
        km: "ការបញ្ចប់",
      },
      furigana: [
        {
          rb: "仕上がり",
          rt: "しあがり",
        },
      ],
      kanjiInfo: [
        {
          char: "仕",
          on: ["シ", "ジ"],
          kun: ["つか.える"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 162,
      kanji: "仕上",
      reading: "しあげ",
      meanings: {
        ja: "仕上げ",
        en: "finishing touches",
        zh: "收尾",
        tw: "收尾",
        ko: "마감",
        vi: "hoàn thiện",
        th: "ขั้นตอนสุดท้าย",
        my: "အပြီးသတ်အဆင့်",
        km: "ដំណាក់កាលចុងក្រោយ",
      },
      furigana: [
        {
          rb: "仕上",
          rt: "しあげ",
        },
      ],
      kanjiInfo: [
        {
          char: "仕",
          on: ["シ", "ジ"],
          kun: ["つか.える"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 163,
      kanji: "飼育",
      reading: "しいく",
      meanings: {
        ja: "飼育",
        en: "breeding; raising",
        zh: "饲养",
        tw: "飼養",
        ko: "사육",
        vi: "chăn nuôi",
        th: "การเลี้ยงสัตว์",
        my: "မွေးမြူမှု",
        km: "ចិញ្ចឹមសត្វ",
      },
      furigana: [
        {
          rb: "飼育",
          rt: "しいく",
        },
      ],
      kanjiInfo: [
        {
          char: "飼",
          on: ["シ"],
          kun: ["か.う"],
          strokes: 13,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "育",
          on: ["イク"],
          kun: ["そだ.つ", "そだ.ち", "そだ.てる", "はぐく.む"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 164,
      kanji: "シート",
      reading: "シート",
      meanings: {
        ja: "シート",
        en: "seat; sheet",
        zh: "座位；薄片",
        tw: "座位；薄片",
        ko: "시트",
        vi: "ghế; tấm",
        th: "ที่นั่ง; แผ่น",
        my: "ထိုင်ခုံ; စာရွက်",
        km: "កៅអី; សន្លឹក",
      },
      furigana: [
        {
          rb: "シート",
          rt: "シート",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 165,
      kanji: "潮",
      reading: "しお",
      meanings: {
        ja: "潮",
        en: "tide",
        zh: "潮水",
        tw: "潮水",
        ko: "조수",
        vi: "thuỷ triều",
        th: "น้ำขึ้นน้ำลง",
        my: "လှိုင်းသင့်တက်ခြင်း",
        km: "អូរទឹកជោគ",
      },
      furigana: [
        {
          rb: "潮",
          rt: "しお",
        },
      ],
      kanjiInfo: [
        {
          char: "潮",
          on: ["チョウ"],
          kun: ["しお", "うしお"],
          strokes: 15,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 166,
      kanji: "歯科",
      reading: "しか",
      meanings: {
        ja: "歯科",
        en: "dentistry",
        zh: "牙科",
        tw: "牙科",
        ko: "치과",
        vi: "nha khoa",
        th: "ทันตกรรม",
        my: "သွားကုသမှု",
        km: "ធ្មេញសាស្រ្ត",
      },
      furigana: [
        {
          rb: "歯科",
          rt: "しか",
        },
      ],
      kanjiInfo: [
        {
          char: "歯",
          on: ["シ"],
          kun: ["よわい", "は", "よわ.い", "よわい.する"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 167,
      kanji: "自我",
      reading: "じが",
      meanings: {
        ja: "自我",
        en: "ego",
        zh: "自我",
        tw: "自我",
        ko: "자아",
        vi: "bản ngã",
        th: "อัตตา",
        my: "အသားတင်",
        km: "អាត្មា",
      },
      furigana: [
        {
          rb: "自我",
          rt: "じが",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "我",
          on: ["ガ"],
          kun: ["われ", "わ", "わ.が-", "わが-"],
          strokes: 7,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 168,
      kanji: "自覚",
      reading: "じかく",
      meanings: {
        ja: "自覚",
        en: "self-awareness",
        zh: "自觉",
        tw: "自覺",
        ko: "자각",
        vi: "tự nhận thức",
        th: "การตระหนักรู้ตนเอง",
        my: "မိမိကိုသိရှိခြင်း",
        km: "ការយល់ដឹងខ្លួន",
      },
      furigana: [
        {
          rb: "自覚",
          rt: "じかく",
        },
      ],
      kanjiInfo: [
        {
          char: "自",
          on: ["ジ", "シ"],
          kun: ["みずか.ら", "おの.ずから", "おの.ずと"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "覚",
          on: ["カク"],
          kun: ["おぼ.える", "さ.ます", "さ.める", "さと.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 169,
      kanji: "仕掛",
      reading: "しかけ",
      meanings: {
        ja: "仕掛け",
        en: "device; trick",
        zh: "机关",
        tw: "機關",
        ko: "장치; 트릭",
        vi: "thiết bị; mưu mẹo",
        th: "กลไก; เล่ห์กล",
        my: "အပြုအမူတောင်",
        km: "ឧបករណ៍; ល្បិច",
      },
      furigana: [
        {
          rb: "仕掛",
          rt: "しかけ",
        },
      ],
      kanjiInfo: [
        {
          char: "仕",
          on: ["シ", "ジ"],
          kun: ["つか.える"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "掛",
          on: ["カイ", "ケイ"],
          kun: [
            "か.ける",
            "-か.ける",
            "か.け",
            "-か.け",
            "-が.け",
            "か.かる",
            "-か.かる",
            "-が.かる",
            "か.かり",
            "-が.かり",
            "かかり",
            "-がかり",
          ],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 170,
      kanji: "色彩",
      reading: "しきさい",
      meanings: {
        ja: "色彩",
        en: "color; hue",
        zh: "色彩",
        tw: "色彩",
        ko: "색채",
        vi: "màu sắc",
        th: "สีสัน",
        my: "အရောင်",
        km: "ពណ៌",
      },
      furigana: [
        {
          rb: "色彩",
          rt: "しきさい",
        },
      ],
      kanjiInfo: [
        {
          char: "色",
          on: ["ショク", "シキ"],
          kun: ["いろ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "彩",
          on: ["サイ"],
          kun: ["いろど.る"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 171,
      kanji: "式場",
      reading: "しきじょう",
      meanings: {
        ja: "式場",
        en: "ceremonial hall",
        zh: "礼堂",
        tw: "禮堂",
        ko: "식장",
        vi: "phòng lễ",
        th: "ห้องจัดพิธี",
        my: "အခမ်းအနားခန်းမ",
        km: "សាលាពិធី",
      },
      furigana: [
        {
          rb: "式場",
          rt: "しきじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "式",
          on: ["シキ"],
          kun: [],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 172,
      kanji: "事業",
      reading: "じぎょう",
      meanings: {
        ja: "事業",
        en: "enterprise; business",
        zh: "事业",
        tw: "事業",
        ko: "사업",
        vi: "doanh nghiệp",
        th: "ธุรกิจ",
        my: "လုပ်ငန်း",
        km: "អាជីវកម្ម",
      },
      furigana: [
        {
          rb: "事業",
          rt: "じぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 173,
      kanji: "軽蔑",
      reading: "けいべつ",
      meanings: {
        ja: "軽蔑",
        en: "contempt; disdain",
        zh: "轻蔑",
        tw: "輕蔑",
        ko: "경멸",
        vi: "coi thường",
        th: "ดูถูก",
        my: "အရွံ့အယွင်း",
        km: "មើលងាយ",
      },
      furigana: [
        {
          rb: "軽蔑",
          rt: "けいべつ",
        },
      ],
      kanjiInfo: [
        {
          char: "軽",
          on: ["ケイ", "キョウ", "キン"],
          kun: ["かる.い", "かろ.やか", "かろ.んじる"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "蔑",
          on: ["ベツ"],
          kun: ["ないがしろ", "なみ.する", "くらい", "さげす.む"],
          strokes: 14,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 174,
      kanji: "経歴",
      reading: "けいれき",
      meanings: {
        ja: "経歴",
        en: "career; background",
        zh: "经历",
        tw: "經歷",
        ko: "경력",
        vi: "kinh nghiệm; lý lịch",
        th: "ประวัติการทำงาน",
        my: "အလုပ်အတွေ့အကြုံ",
        km: "ប្រវត្តិការងារ",
      },
      furigana: [
        {
          rb: "経歴",
          rt: "けいれき",
        },
      ],
      kanjiInfo: [
        {
          char: "経",
          on: ["ケイ", "キョウ", "キン"],
          kun: ["へ.る", "た.つ", "たていと", "はか.る", "のり"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "歴",
          on: ["レキ", "レッキ"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 175,
      kanji: "経路",
      reading: "けいろ",
      meanings: {
        ja: "経路",
        en: "route; path",
        zh: "路线",
        tw: "路線",
        ko: "경로",
        vi: "lộ trình",
        th: "เส้นทาง",
        my: "လမ်းကြောင်း",
        km: "ផ្លូវដើរ",
      },
      furigana: [
        {
          rb: "経路",
          rt: "けいろ",
        },
      ],
      kanjiInfo: [
        {
          char: "経",
          on: ["ケイ", "キョウ", "キン"],
          kun: ["へ.る", "た.つ", "たていと", "はか.る", "のり"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "路",
          on: ["ロ", "ル"],
          kun: ["-じ", "みち"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 176,
      kanji: "劇団",
      reading: "げきだん",
      meanings: {
        ja: "劇団",
        en: "theatrical company; troupe",
        zh: "剧团",
        tw: "劇團",
        ko: "극단",
        vi: "đoàn kịch",
        th: "คณะละคร",
        my: "ဇာတ်ကောင်အဖွဲ့",
        km: "ក្រុមល្ខោន",
      },
      furigana: [
        {
          rb: "劇団",
          rt: "げきだん",
        },
      ],
      kanjiInfo: [
        {
          char: "劇",
          on: ["ゲキ"],
          kun: [],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "団",
          on: ["ダン", "トン"],
          kun: ["かたまり", "まる.い"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 177,
      kanji: "激励",
      reading: "げきれい",
      meanings: {
        ja: "激励",
        en: "encouragement",
        zh: "鼓励",
        tw: "激勵",
        ko: "격려",
        vi: "khích lệ",
        th: "ให้กำลังใจ",
        my: "အားပေးမှု",
        km: "លើកទឹកចិត្ត",
      },
      furigana: [
        {
          rb: "激励",
          rt: "げきれい",
        },
      ],
      kanjiInfo: [
        {
          char: "激",
          on: ["ゲキ"],
          kun: ["はげ.しい"],
          strokes: 16,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "励",
          on: ["レイ"],
          kun: ["はげ.む", "はげ.ます"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 178,
      kanji: "ゲスト",
      reading: "ゲスト",
      meanings: {
        ja: "ゲスト",
        en: "guest",
        zh: "客人",
        tw: "客人",
        ko: "게스트",
        vi: "khách",
        th: "แขก",
        my: "ဧည့်သည်",
        km: "ភ្ញៀវ",
      },
      furigana: [
        {
          rb: "ゲスト",
          rt: "ゲスト",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 179,
      kanji: "獣",
      reading: "けだもの",
      meanings: {
        ja: "獣",
        en: "beast; brute",
        zh: "野兽",
        tw: "野獸",
        ko: "짐승",
        vi: "thú vật",
        th: "สัตว์ป่า",
        my: "တိရစ္ဆာန်",
        km: "សត្វព្រៃ",
      },
      furigana: [
        {
          rb: "獣",
          rt: "けだもの",
        },
      ],
      kanjiInfo: [
        {
          char: "獣",
          on: ["ジュウ"],
          kun: ["けもの", "けだもの"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 180,
      kanji: "決",
      reading: "けつ",
      meanings: {
        ja: "決",
        en: "decision; determination",
        zh: "决",
        tw: "決",
        ko: "결정",
        vi: "quyết định",
        th: "การตัดสินใจ",
        my: "ဆုံးဖြတ်ချက်",
        km: "សេចក្តីសម្រេច",
      },
      furigana: [
        {
          rb: "決",
          rt: "けつ",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 181,
      kanji: "決意",
      reading: "けつい",
      meanings: {
        ja: "決意",
        en: "determination; resolution",
        zh: "决心",
        tw: "決心",
        ko: "결의",
        vi: "quyết tâm",
        th: "ตั้งใจ",
        my: "တည်ကြည်မှု",
        km: "សេចក្តីសម្រេចចិត្ត",
      },
      furigana: [
        {
          rb: "決意",
          rt: "けつい",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 182,
      kanji: "結核",
      reading: "けっかく",
      meanings: {
        ja: "結核",
        en: "tuberculosis",
        zh: "结核",
        tw: "結核",
        ko: "결핵",
        vi: "bệnh lao",
        th: "วัณโรค",
        my: "တီဘီရောဂါ",
        km: "ជំងឺរលាកសួត",
      },
      furigana: [
        {
          rb: "結核",
          rt: "けっかく",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "核",
          on: ["カク"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 183,
      kanji: "決議",
      reading: "けつぎ",
      meanings: {
        ja: "決議",
        en: "resolution (of a meeting)",
        zh: "决议",
        tw: "決議",
        ko: "결의안",
        vi: "nghị quyết",
        th: "มติ",
        my: "အကြံပြုချက်",
        km: "សេចក្តីសម្រេចសមាជា",
      },
      furigana: [
        {
          rb: "決議",
          rt: "けつぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 184,
      kanji: "結合",
      reading: "けつごう",
      meanings: {
        ja: "結合",
        en: "combination; union",
        zh: "结合",
        tw: "結合",
        ko: "결합",
        vi: "kết hợp",
        th: "การรวมตัว",
        my: "ပေါင်းစည်းမှု",
        km: "ការរួមបញ្ចូល",
      },
      furigana: [
        {
          rb: "結合",
          rt: "けつごう",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 185,
      kanji: "決算",
      reading: "けっさん",
      meanings: {
        ja: "決算",
        en: "settlement of accounts",
        zh: "结算",
        tw: "結算",
        ko: "결산",
        vi: "quyết toán",
        th: "ปิดบัญชี",
        my: "စာရင်းချုပ်ခြင်း",
        km: "បិទគណនី",
      },
      furigana: [
        {
          rb: "決算",
          rt: "けっさん",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 186,
      kanji: "月謝",
      reading: "げっしゃ",
      meanings: {
        ja: "月謝",
        en: "monthly tuition fee",
        zh: "月费",
        tw: "月費",
        ko: "월사금",
        vi: "học phí hàng tháng",
        th: "ค่าเล่าเรียนรายเดือน",
        my: "လစဉ်အတန်းကြေး",
        km: "ថ្លៃសិក្សារប្រចាំខែ",
      },
      furigana: [
        {
          rb: "月謝",
          rt: "げっしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "謝",
          on: ["シャ"],
          kun: ["あやま.る"],
          strokes: 17,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 187,
      kanji: "決勝",
      reading: "けっしょう",
      meanings: {
        ja: "決勝",
        en: "finals (match)",
        zh: "决赛",
        tw: "決賽",
        ko: "결승",
        vi: "chung kết",
        th: "รอบชิงชนะเลิศ",
        my: "နောက်ဆုံးပြိုင်ပွဲ",
        km: "ការប្រកួតផ្តាច់ព្រ័ត្រ",
      },
      furigana: [
        {
          rb: "決勝",
          rt: "けっしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "勝",
          on: ["ショウ"],
          kun: ["か.つ", "-が.ち", "まさ.る", "すぐ.れる", "かつ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 188,
      kanji: "結晶",
      reading: "けっしょう",
      meanings: {
        ja: "結晶",
        en: "crystal",
        zh: "结晶",
        tw: "結晶",
        ko: "결정체",
        vi: "tinh thể",
        th: "ผลึก",
        my: "ဖွဲ့အစည်းအရောင်ကျက်",
        km: "គ្រីស្តាល់",
      },
      furigana: [
        {
          rb: "結晶",
          rt: "けっしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "晶",
          on: ["ショウ"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 189,
      kanji: "結成",
      reading: "けっせい",
      meanings: {
        ja: "結成",
        en: "formation (of a group)",
        zh: "组成",
        tw: "結成",
        ko: "결성",
        vi: "thành lập",
        th: "การก่อตั้ง",
        my: "ဖွဲ့စည်းမှု",
        km: "បង្កើតក្រុម",
      },
      furigana: [
        {
          rb: "結成",
          rt: "けっせい",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 190,
      kanji: "結束",
      reading: "けっそく",
      meanings: {
        ja: "結束",
        en: "union; solidarity",
        zh: "团结",
        tw: "團結",
        ko: "결속",
        vi: "đoàn kết",
        th: "ความสามัคคี",
        my: "ညီညွတ်မှု",
        km: "ភាពរួបរួម",
      },
      furigana: [
        {
          rb: "結束",
          rt: "けっそく",
        },
      ],
      kanjiInfo: [
        {
          char: "結",
          on: ["ケツ", "ケチ"],
          kun: ["むす.ぶ", "ゆ.う", "ゆ.わえる"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "束",
          on: ["ソク"],
          kun: ["たば", "たば.ねる", "つか", "つか.ねる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 191,
      kanji: "決断",
      reading: "けつだん",
      meanings: {
        ja: "決断",
        en: "decision; determination",
        zh: "决断",
        tw: "決斷",
        ko: "결단",
        vi: "quyết đoán",
        th: "ตัดสินใจอย่างแน่วแน่",
        my: "ဆုံးဖြတ်ချက်ကြီး",
        km: "សេចក្តីសម្រេចចិត្តដាច់ខាត",
      },
      furigana: [
        {
          rb: "決断",
          rt: "けつだん",
        },
      ],
      kanjiInfo: [
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 192,
      kanji: "月賦",
      reading: "げっぷ",
      meanings: {
        ja: "月賦",
        en: "monthly installment",
        zh: "分期付款",
        tw: "分期付款",
        ko: "월부금",
        vi: "trả góp hàng tháng",
        th: "ผ่อนชำระรายเดือน",
        my: "လစဉ်အပေးအယူ",
        km: "បង់រំលស់ប្រចាំខែ",
      },
      furigana: [
        {
          rb: "月賦",
          rt: "げっぷ",
        },
      ],
      kanjiInfo: [
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "賦",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 193,
      kanji: "欠乏",
      reading: "けつぼう",
      meanings: {
        ja: "欠乏",
        en: "deficiency; shortage",
        zh: "缺乏",
        tw: "缺乏",
        ko: "결핍",
        vi: "thiếu hụt",
        th: "ความขาดแคลน",
        my: "မလုံလောက်ခြင်း",
        km: "កង្វះខាត",
      },
      furigana: [
        {
          rb: "欠乏",
          rt: "けつぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "欠",
          on: ["ケツ", "ケン"],
          kun: ["か.ける", "か.く"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "乏",
          on: ["ボウ"],
          kun: ["とぼ.しい", "とも.しい"],
          strokes: 4,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 194,
      kanji: "獣",
      reading: "けもの",
      meanings: {
        ja: "獣",
        en: "beast; animal",
        zh: "野兽",
        tw: "野獸",
        ko: "짐승",
        vi: "thú vật",
        th: "สัตว์ป่า",
        my: "တိရစ္ဆာန်",
        km: "សត្វព្រៃ",
      },
      furigana: [
        {
          rb: "獣",
          rt: "けもの",
        },
      ],
      kanjiInfo: [
        {
          char: "獣",
          on: ["ジュウ"],
          kun: ["けもの", "けだもの"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 195,
      kanji: "家来",
      reading: "けらい",
      meanings: {
        ja: "家来",
        en: "retainer; vassal",
        zh: "家臣",
        tw: "家臣",
        ko: "가신; 신하",
        vi: "gia thần; thuộc hạ",
        th: "ข้ารับใช้/ลูกสมุน",
        my: "အဖွဲ့ဝင်ကျွန်",
        km: "បក្ខពួក",
      },
      furigana: [
        {
          rb: "家来",
          rt: "けらい",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "来",
          on: ["ライ", "タイ"],
          kun: [
            "く.る",
            "きた.る",
            "きた.す",
            "き.たす",
            "き.たる",
            "き",
            "こ",
          ],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 196,
      kanji: "下痢",
      reading: "げり",
      meanings: {
        ja: "下痢",
        en: "diarrhea",
        zh: "腹泻",
        tw: "腹瀉",
        ko: "설사",
        vi: "tiêu chảy",
        th: "ท้องเสีย",
        my: "ဝမ်းလျှော့",
        km: "រាគ",
      },
      furigana: [
        {
          rb: "下痢",
          rt: "げり",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "痢",
          on: ["リ"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 197,
      kanji: "権威",
      reading: "けんい",
      meanings: {
        ja: "権威",
        en: "authority; prestige",
        zh: "权威",
        tw: "權威",
        ko: "권위",
        vi: "quyền uy",
        th: "อำนาจ/บารมี",
        my: "လူမှုအာဏာ",
        km: "អំណាចឥទ្ធិពល",
      },
      furigana: [
        {
          rb: "権威",
          rt: "けんい",
        },
      ],
      kanjiInfo: [
        {
          char: "権",
          on: ["ケン", "ゴン"],
          kun: ["おもり", "かり", "はか.る"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "威",
          on: ["イ"],
          kun: ["おど.す", "おど.し", "おど.かす"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 198,
      kanji: "兼業",
      reading: "けんぎょう",
      meanings: {
        ja: "兼業",
        en: "side job; holding two occupations",
        zh: "兼业",
        tw: "兼業",
        ko: "겸업",
        vi: "kiêm nghề; làm thêm",
        th: "ทำงานควบสองอย่าง",
        my: "အခြေခံအလုပ်အပြင်လုပ်ငန်း",
        km: "ការងារបន្ថែម",
      },
      furigana: [
        {
          rb: "兼業",
          rt: "けんぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "兼",
          on: ["ケン"],
          kun: ["か.ねる", "-か.ねる"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 199,
      kanji: "原形",
      reading: "げんけい",
      meanings: {
        ja: "原形",
        en: "original form",
        zh: "原形",
        tw: "原形",
        ko: "원형",
        vi: "nguyên hình",
        th: "รูปดั้งเดิม",
        my: "မူလရုပ်သဏ္ဌာန်",
        km: "រូបរាងដើម",
      },
      furigana: [
        {
          rb: "原形",
          rt: "げんけい",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "形",
          on: ["ケイ", "ギョウ"],
          kun: ["かた", "-がた", "かたち", "なり"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 200,
      kanji: "原型",
      reading: "げんけい",
      meanings: {
        ja: "原型",
        en: "prototype; archetype",
        zh: "原型",
        tw: "原型",
        ko: "원형; 프로토타입",
        vi: "nguyên mẫu",
        th: "ต้นแบบ",
        my: "မူလပုံစံ",
        km: "គំរូដើម",
      },
      furigana: [
        {
          rb: "原型",
          rt: "げんけい",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "型",
          on: ["ケイ"],
          kun: ["かた", "-がた"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
