export const n1part14 = {
  Lesson14: [
    {
      id: 501,
      kanji: "獲得",
      reading: "かくとく",
      meanings: {
        ja: "獲得",
        en: "acquisition; gain",
        zh: "获得",
        tw: "獲得",
        ko: "획득",
        vi: "thu được",
        th: "การได้รับ",
        my: "ရရှိခြင်း",
        km: "ការទទួលបាន",
      },
      furigana: [
        {
          rb: "獲得",
          rt: "かくとく",
        },
      ],
      kanjiInfo: [
        {
          char: "獲",
          on: ["カク"],
          kun: ["え.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "得",
          on: ["トク"],
          kun: ["え.る", "う.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 502,
      kanji: "楽譜",
      reading: "がくふ",
      meanings: {
        ja: "楽譜",
        en: "musical score",
        zh: "乐谱",
        tw: "樂譜",
        ko: "악보",
        vi: "bản nhạc",
        th: "โน้ตเพลง",
        my: "တေးဂီတစာမျက်နှာ",
        km: "សៀវភៅតន្ត្រី",
      },
      furigana: [
        {
          rb: "楽譜",
          rt: "がくふ",
        },
      ],
      kanjiInfo: [
        {
          char: "楽",
          on: ["ガク", "ラク", "ゴウ"],
          kun: ["たの.しい", "たの.しむ", "この.む"],
          strokes: 13,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "譜",
          on: ["フ"],
          kun: [],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 503,
      kanji: "確保",
      reading: "かくほ",
      meanings: {
        ja: "確保",
        en: "secure; ensure",
        zh: "确保",
        tw: "確保",
        ko: "확보",
        vi: "đảm bảo",
        th: "การรักษาไว้",
        my: "အာမခံခြင်း",
        km: "ធានា",
      },
      furigana: [
        {
          rb: "確保",
          rt: "かくほ",
        },
      ],
      kanjiInfo: [
        {
          char: "確",
          on: ["カク", "コウ"],
          kun: ["たし.か", "たし.かめる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "保",
          on: ["ホ", "ホウ"],
          kun: ["たも.つ"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 504,
      kanji: "革命",
      reading: "かくめい",
      meanings: {
        ja: "革命",
        en: "revolution",
        zh: "革命",
        tw: "革命",
        ko: "혁명",
        vi: "cách mạng",
        th: "การปฏิวัติ",
        my: "တော်လှန်ရေး",
        km: "បដិវត្តន៍",
      },
      furigana: [
        {
          rb: "革命",
          rt: "かくめい",
        },
      ],
      kanjiInfo: [
        {
          char: "革",
          on: ["カク"],
          kun: ["かわ"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 505,
      kanji: "確立",
      reading: "かくりつ",
      meanings: {
        ja: "確立",
        en: "establishment; founding",
        zh: "确立",
        tw: "確立",
        ko: "확립",
        vi: "thiết lập",
        th: "การสถาปนา",
        my: "တည်ထောင်ခြင်း",
        km: "បង្កើតឡើង",
      },
      furigana: [
        {
          rb: "確立",
          rt: "かくりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "確",
          on: ["カク", "コウ"],
          kun: ["たし.か", "たし.かめる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "立",
          on: ["リツ", "リュウ", "リットル"],
          kun: [
            "た.つ",
            "-た.つ",
            "た.ち-",
            "た.てる",
            "-た.てる",
            "た.て-",
            "たて-",
            "-た.て",
            "-だ.て",
            "-だ.てる",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 506,
      kanji: "賭",
      reading: "かけ",
      meanings: {
        ja: "賭け",
        en: "bet; gamble",
        zh: "赌注",
        tw: "賭注",
        ko: "내기",
        vi: "cá cược",
        th: "การเดิมพัน",
        my: "လောင်းကစား",
        km: "ការភ្នាល់",
      },
      furigana: [
        {
          rb: "賭",
          rt: "かけ",
        },
      ],
      kanjiInfo: [
        {
          char: "賭",
          on: ["ト"],
          kun: ["か.ける", "かけ"],
          strokes: 15,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 507,
      kanji: "崖",
      reading: "がけ",
      meanings: {
        ja: "崖",
        en: "cliff",
        zh: "悬崖",
        tw: "懸崖",
        ko: "절벽",
        vi: "vách đá",
        th: "หน้าผา",
        my: "ကမ်းပါး",
        km: "ជម្រាលថ្ម",
      },
      furigana: [
        {
          rb: "崖",
          rt: "がけ",
        },
      ],
      kanjiInfo: [
        {
          char: "崖",
          on: ["ガイ", "ゲ", "ギ"],
          kun: ["がけ", "きし", "はて"],
          strokes: 11,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 508,
      kanji: "駆け足",
      reading: "かけあし",
      meanings: {
        ja: "駆け足",
        en: "running fast",
        zh: "快跑",
        tw: "快跑",
        ko: "달리기",
        vi: "chạy nhanh",
        th: "วิ่งเร็ว",
        my: "မြန်မြန်ပြေးခြင်း",
        km: "រត់លឿន",
      },
      furigana: [
        {
          rb: "駆け足",
          rt: "かけあし",
        },
      ],
      kanjiInfo: [
        {
          char: "駆",
          on: ["ク"],
          kun: ["か.ける", "か.る"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "足",
          on: ["ソク"],
          kun: ["あし", "た.りる", "た.る", "た.す"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 509,
      kanji: "家計",
      reading: "かけい",
      meanings: {
        ja: "家計",
        en: "household economy",
        zh: "家庭收支",
        tw: "家庭收支",
        ko: "가계",
        vi: "kinh tế gia đình",
        th: "การเงินครอบครัว",
        my: "အိမ်ထောင်စီးပွားရေး",
        km: "សេដ្ឋកិច្ចគ្រួសារ",
      },
      furigana: [
        {
          rb: "家計",
          rt: "かけい",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "計",
          on: ["ケイ"],
          kun: ["はか.る", "はか.らう"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 510,
      kanji: "駆けっこ",
      reading: "かけっこ",
      meanings: {
        ja: "駆けっこ",
        en: "foot race",
        zh: "赛跑",
        tw: "賽跑",
        ko: "달리기 시합",
        vi: "chạy đua",
        th: "แข่งวิ่ง",
        my: "ပြိုင်ပြေးခြင်း",
        km: "ប្រកួតរត់",
      },
      furigana: [
        {
          rb: "駆けっこ",
          rt: "かけっこ",
        },
      ],
      kanjiInfo: [
        {
          char: "駆",
          on: ["ク"],
          kun: ["か.ける", "か.る"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 511,
      kanji: "加工",
      reading: "かこう",
      meanings: {
        ja: "加工",
        en: "processing; manufacturing",
        zh: "加工",
        tw: "加工",
        ko: "가공",
        vi: "chế biến",
        th: "การแปรรูป",
        my: "ထုတ်လုပ်ခြင်း",
        km: "ដំណើរការផលិត",
      },
      furigana: [
        {
          rb: "加工",
          rt: "かこう",
        },
      ],
      kanjiInfo: [
        {
          char: "加",
          on: ["カ"],
          kun: ["くわ.える", "くわ.わる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "工",
          on: ["コウ", "ク", "グ"],
          kun: [],
          strokes: 3,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 512,
      kanji: "化合",
      reading: "かごう",
      meanings: {
        ja: "化合",
        en: "chemical combination",
        zh: "化合",
        tw: "化合",
        ko: "화합",
        vi: "hóa hợp",
        th: "การผสมสารเคมี",
        my: "ဓာတုဖွဲ့စည်းမှု",
        km: "សមាសធាតុគីមី",
      },
      furigana: [
        {
          rb: "化合",
          rt: "かごう",
        },
      ],
      kanjiInfo: [
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 513,
      kanji: "箇条書",
      reading: "かじょうがき",
      meanings: {
        ja: "箇条書き",
        en: "itemized form",
        zh: "分条列举",
        tw: "條列",
        ko: "항목별 나열",
        vi: "liệt kê theo mục",
        th: "รายการหัวข้อ",
        my: "အချက်အလက်စာရင်း",
        km: "រាយបញ្ជីជា​ចំណុចៗ",
      },
      furigana: [
        {
          rb: "箇条書",
          rt: "かじょうがき",
        },
      ],
      kanjiInfo: [
        {
          char: "箇",
          on: ["カ", "コ"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "条",
          on: ["ジョウ", "チョウ", "デキ"],
          kun: ["えだ", "すじ"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 514,
      kanji: "頭",
      reading: "かしら",
      meanings: {
        ja: "頭",
        en: "head; chief",
        zh: "头；头目",
        tw: "頭；首領",
        ko: "머리; 두목",
        vi: "đầu; người đứng đầu",
        th: "หัวหน้า",
        my: "ခေါင်းဆောင်",
        km: "មេដឹកនាំ",
      },
      furigana: [
        {
          rb: "頭",
          rt: "かしら",
        },
      ],
      kanjiInfo: [
        {
          char: "頭",
          on: ["トウ", "ズ", "ト"],
          kun: ["あたま", "かしら", "-がしら", "かぶり"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 515,
      kanji: "火星",
      reading: "かせい",
      meanings: {
        ja: "火星",
        en: "Mars (planet)",
        zh: "火星",
        tw: "火星",
        ko: "화성",
        vi: "sao Hỏa",
        th: "ดาวอังคาร",
        my: "ဂြိုဟ်မက်စ်",
        km: "ភពអង្គារ",
      },
      furigana: [
        {
          rb: "火星",
          rt: "かせい",
        },
      ],
      kanjiInfo: [
        {
          char: "火",
          on: ["カ"],
          kun: ["ひ", "-び", "ほ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "星",
          on: ["セイ", "ショウ"],
          kun: ["ほし", "-ぼし"],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 516,
      kanji: "化石",
      reading: "かせき",
      meanings: {
        ja: "化石",
        en: "fossil",
        zh: "化石",
        tw: "化石",
        ko: "화석",
        vi: "hóa thạch",
        th: "ฟอสซิล",
        my: "ကျောက်ဖြစ်",
        km: "ជីវចាស់ (ហ្វូស៊ីល)",
      },
      furigana: [
        {
          rb: "化石",
          rt: "かせき",
        },
      ],
      kanjiInfo: [
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "石",
          on: ["セキ", "シャク", "コク"],
          kun: ["いし"],
          strokes: 5,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 517,
      kanji: "河川",
      reading: "かせん",
      meanings: {
        ja: "河川",
        en: "rivers",
        zh: "河川",
        tw: "河川",
        ko: "하천",
        vi: "sông suối",
        th: "แม่น้ำลำคลอง",
        my: "မြစ်များ",
        km: "ទន្លេ",
      },
      furigana: [
        {
          rb: "河川",
          rt: "かせん",
        },
      ],
      kanjiInfo: [
        {
          char: "河",
          on: ["カ"],
          kun: ["かわ"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "川",
          on: ["セン"],
          kun: ["かわ"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 518,
      kanji: "化繊",
      reading: "かせん",
      meanings: {
        ja: "化繊",
        en: "synthetic fiber",
        zh: "化纤",
        tw: "化纖",
        ko: "합성섬유",
        vi: "sợi tổng hợp",
        th: "เส้นใยสังเคราะห์",
        my: "အနုကြေးငွေအကြွေ",
        km: "សរសៃសំយោគ",
      },
      furigana: [
        {
          rb: "化繊",
          rt: "かせん",
        },
      ],
      kanjiInfo: [
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "繊",
          on: ["セン"],
          kun: [],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 519,
      kanji: "過疎",
      reading: "かそ",
      meanings: {
        ja: "過疎",
        en: "depopulation",
        zh: "人口减少",
        tw: "人口減少",
        ko: "과소",
        vi: "giảm dân số",
        th: "ประชากรลดลง",
        my: "လူဦးရေကျခြင်း",
        km: "ការថយចុះប្រជាជន",
      },
      furigana: [
        {
          rb: "過疎",
          rt: "かそ",
        },
      ],
      kanjiInfo: [
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "疎",
          on: ["ソ", "ショ"],
          kun: ["うと.い", "うと.む", "まば.ら"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 520,
      kanji: "片言",
      reading: "かたこと",
      meanings: {
        ja: "片言",
        en: "broken (language); prattle",
        zh: "半生不熟的话",
        tw: "片言; 不流利的語言",
        ko: "서투른 말",
        vi: "nói bập bõm",
        th: "พูดติดขัด",
        my: "စကားမပြောတော်",
        km: "និយាយមិនច្បាស់",
      },
      furigana: [
        {
          rb: "片言",
          rt: "かたこと",
        },
      ],
      kanjiInfo: [
        {
          char: "片",
          on: ["ヘン"],
          kun: ["かた-", "かた"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 521,
      kanji: "花壇",
      reading: "かだん",
      meanings: {
        ja: "花壇",
        en: "flower bed",
        zh: "花坛",
        tw: "花壇",
        ko: "화단",
        vi: "bồn hoa",
        th: "แปลงดอกไม้",
        my: "ပန်းခြံ",
        km: "ចម្ការផ្កា",
      },
      furigana: [
        {
          rb: "花壇",
          rt: "かだん",
        },
      ],
      kanjiInfo: [
        {
          char: "花",
          on: ["カ", "ケ"],
          kun: ["はな"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "壇",
          on: ["ダン", "タン"],
          kun: [],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 522,
      kanji: "家畜",
      reading: "かちく",
      meanings: {
        ja: "家畜",
        en: "livestock",
        zh: "家畜",
        tw: "家畜",
        ko: "가축",
        vi: "gia súc",
        th: "สัตว์เลี้ยงในฟาร์ม",
        my: "မွေးမြူတိရစ္ဆာန်",
        km: "សត្វចិញ្ចឹម",
      },
      furigana: [
        {
          rb: "家畜",
          rt: "かちく",
        },
      ],
      kanjiInfo: [
        {
          char: "家",
          on: ["カ", "ケ"],
          kun: ["いえ", "や", "うち"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "畜",
          on: ["チク"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 523,
      kanji: "合唱",
      reading: "がっしょう",
      meanings: {
        ja: "合唱",
        en: "chorus; singing together",
        zh: "合唱",
        tw: "合唱",
        ko: "합창",
        vi: "hợp xướng",
        th: "ประสานเสียง",
        my: "အမျှင်သံချို",
        km: "ច្រៀងរួម",
      },
      furigana: [
        {
          rb: "合唱",
          rt: "がっしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "唱",
          on: ["ショウ"],
          kun: ["とな.える"],
          strokes: 11,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 524,
      kanji: "合致",
      reading: "がっち",
      meanings: {
        ja: "合致",
        en: "agreement; coincidence",
        zh: "一致",
        tw: "一致",
        ko: "일치",
        vi: "phù hợp",
        th: "ตรงกัน",
        my: "သဘောတူညီမှု",
        km: "ត្រូវគ្នា",
      },
      furigana: [
        {
          rb: "合致",
          rt: "がっち",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "致",
          on: ["チ"],
          kun: ["いた.す"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 525,
      kanji: "勝手",
      reading: "かって",
      meanings: {
        ja: "勝手",
        en: "one's convenience; selfishness",
        zh: "任性；方便",
        tw: "任性；方便",
        ko: "제멋대로",
        vi: "ích kỷ",
        th: "เห็นแก่ตัว",
        my: "အလိုလိုက်",
        km: "ស្រួលចិត្ត",
      },
      furigana: [
        {
          rb: "勝手",
          rt: "かって",
        },
      ],
      kanjiInfo: [
        {
          char: "勝",
          on: ["ショウ"],
          kun: ["か.つ", "-が.ち", "まさ.る", "すぐ.れる", "かつ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 526,
      kanji: "カット",
      reading: "カット",
      meanings: {
        ja: "カット",
        en: "cut (scene; trim)",
        zh: "剪切；剪辑",
        tw: "剪裁；剪輯",
        ko: "컷",
        vi: "cắt",
        th: "ตัด",
        my: "ဖြတ်တောက်ခြင်း",
        km: "កាត់",
      },
      furigana: [
        {
          rb: "カット",
          rt: "カット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 527,
      kanji: "合併",
      reading: "がっぺい",
      meanings: {
        ja: "合併",
        en: "merger; combination",
        zh: "合并",
        tw: "合併",
        ko: "합병",
        vi: "sáp nhập",
        th: "การควบรวม",
        my: "ပေါင်းစည်းခြင်း",
        km: "ការរួមបញ្ចូល",
      },
      furigana: [
        {
          rb: "合併",
          rt: "がっぺい",
        },
      ],
      kanjiInfo: [
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "併",
          on: ["ヘイ"],
          kun: ["あわ.せる"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 528,
      kanji: "カテゴリー",
      reading: "カテゴリー",
      meanings: {
        ja: "カテゴリー",
        en: "category",
        zh: "类别",
        tw: "類別",
        ko: "카테고리",
        vi: "thể loại",
        th: "หมวดหมู่",
        my: "အမျိုးအစား",
        km: "ប្រភេទ",
      },
      furigana: [
        {
          rb: "カテゴリー",
          rt: "カテゴリー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 529,
      kanji: "金槌",
      reading: "かなづち",
      meanings: {
        ja: "金槌",
        en: "hammer",
        zh: "锤子",
        tw: "鐵鎚",
        ko: "망치",
        vi: "búa",
        th: "ค้อน",
        my: "တုတ်သံ",
        km: "ញញួរ",
      },
      furigana: [
        {
          rb: "金槌",
          rt: "かなづち",
        },
      ],
      kanjiInfo: [
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "槌",
          on: ["ツイ"],
          kun: ["つち"],
          strokes: 13,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 530,
      kanji: "加入",
      reading: "かにゅう",
      meanings: {
        ja: "加入",
        en: "joining; enrollment",
        zh: "加入",
        tw: "加入",
        ko: "가입",
        vi: "gia nhập",
        th: "เข้าร่วม",
        my: "ပါဝင်ခြင်း",
        km: "ចូលរួម",
      },
      furigana: [
        {
          rb: "加入",
          rt: "かにゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "加",
          on: ["カ"],
          kun: ["くわ.える", "くわ.わる"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 531,
      kanji: "株式",
      reading: "かぶしき",
      meanings: {
        ja: "株式",
        en: "stock; share",
        zh: "股票",
        tw: "股票",
        ko: "주식",
        vi: "cổ phiếu",
        th: "หุ้น",
        my: "အခန်းကဏ္ဍရှယ်ယာ",
        km: "ភាគហ៊ុន",
      },
      furigana: [
        {
          rb: "株式",
          rt: "かぶしき",
        },
      ],
      kanjiInfo: [
        {
          char: "株",
          on: ["シュ"],
          kun: ["かぶ"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "式",
          on: ["シキ"],
          kun: [],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 532,
      kanji: "花粉",
      reading: "かふん",
      meanings: {
        ja: "花粉",
        en: "pollen",
        zh: "花粉",
        tw: "花粉",
        ko: "꽃가루",
        vi: "phấn hoa",
        th: "ละอองเกสร",
        my: "ပန်းဖူးမှုန့်",
        km: "ធូលីផ្កា",
      },
      furigana: [
        {
          rb: "花粉",
          rt: "かふん",
        },
      ],
      kanjiInfo: [
        {
          char: "花",
          on: ["カ", "ケ"],
          kun: ["はな"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "粉",
          on: ["フン"],
          kun: ["デシメートル", "こ", "こな"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 533,
      kanji: "貨幣",
      reading: "かへい",
      meanings: {
        ja: "貨幣",
        en: "currency; money",
        zh: "货币",
        tw: "貨幣",
        ko: "화폐",
        vi: "tiền tệ",
        th: "สกุลเงิน",
        my: "ငွေကြေး",
        km: "រូបិយប័ណ្ណ",
      },
      furigana: [
        {
          rb: "貨幣",
          rt: "かへい",
        },
      ],
      kanjiInfo: [
        {
          char: "貨",
          on: ["カ"],
          kun: ["たから"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "幣",
          on: ["ヘイ"],
          kun: ["ぬさ"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 534,
      kanji: "過密",
      reading: "かみつ",
      meanings: {
        ja: "過密",
        en: "overcrowding",
        zh: "过密",
        tw: "過密",
        ko: "과밀",
        vi: "quá đông",
        th: "แออัด",
        my: "အနှောင့်အယှက်",
        km: "ពេញលេញពេក",
      },
      furigana: [
        {
          rb: "過密",
          rt: "かみつ",
        },
      ],
      kanjiInfo: [
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "密",
          on: ["ミツ"],
          kun: ["ひそ.か"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 535,
      kanji: "カムバック",
      reading: "カムバック",
      meanings: {
        ja: "カムバック",
        en: "comeback; return",
        zh: "回归",
        tw: "回歸",
        ko: "컴백",
        vi: "trở lại",
        th: "กลับมาอีกครั้ง",
        my: "ပြန်လည်လာခြင်း",
        km: "ត្រលប់មកវិញ",
      },
      furigana: [
        {
          rb: "カムバック",
          rt: "カムバック",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 536,
      kanji: "カメラマン",
      reading: "カメラマン",
      meanings: {
        ja: "カメラマン",
        en: "photographer",
        zh: "摄影师",
        tw: "攝影師",
        ko: "카메라맨",
        vi: "nhiếp ảnh gia",
        th: "ช่างภาพ",
        my: "ဓာတ်ပုံဆရာ",
        km: "អ្នកថតរូប",
      },
      furigana: [
        {
          rb: "カメラマン",
          rt: "カメラマン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 537,
      kanji: "粥",
      reading: "かゆ",
      meanings: {
        ja: "粥",
        en: "rice porridge",
        zh: "粥",
        tw: "粥",
        ko: "죽",
        vi: "cháo",
        th: "ข้าวต้ม",
        my: "ဆန်ပြုတ်",
        km: "បបរ",
      },
      furigana: [
        {
          rb: "粥",
          rt: "かゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "粥",
          on: ["イク", "シュク", "ジュク"],
          kun: ["かゆ", "かい", "ひさ.ぐ"],
          strokes: 12,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 538,
      kanji: "体付き",
      reading: "からだつき",
      meanings: {
        ja: "体付き",
        en: "body build",
        zh: "体格",
        tw: "體格",
        ko: "체격",
        vi: "thể hình",
        th: "รูปร่าง",
        my: "ခန္ဓာကိုယ်",
        km: "រាងកាយ",
      },
      furigana: [
        {
          rb: "体付き",
          rt: "からだつき",
        },
      ],
      kanjiInfo: [
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 539,
      kanji: "カルテ",
      reading: "カルテ",
      meanings: {
        ja: "カルテ",
        en: "medical chart",
        zh: "病历表",
        tw: "病歷表",
        ko: "진료기록",
        vi: "hồ sơ bệnh án",
        th: "แฟ้มผู้ป่วย",
        my: "လူနာဖိုင်",
        km: "ប្រវត្តិអ្នកជំងឺ",
      },
      furigana: [
        {
          rb: "カルテ",
          rt: "カルテ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 540,
      kanji: "ガレージ",
      reading: "ガレージ",
      meanings: {
        ja: "ガレージ（車庫）",
        en: "garage",
        zh: "车库",
        tw: "車庫",
        ko: "차고",
        vi: "nhà để xe",
        th: "โรงรถ",
        my: "ကားရပ်နားရာ",
        km: "โรงជាងឡាន",
      },
      furigana: [
        {
          rb: "ガレージ",
          rt: "ガレージ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 541,
      kanji: "過労",
      reading: "かろう",
      meanings: {
        ja: "過労",
        en: "overwork",
        zh: "过劳",
        tw: "過勞",
        ko: "과로",
        vi: "làm việc quá sức",
        th: "ทำงานหนักเกินไป",
        my: "အလုပ်အလွန်များခြင်း",
        km: "ការធ្វើការលើសកម្រិត",
      },
      furigana: [
        {
          rb: "過労",
          rt: "かろう",
        },
      ],
      kanjiInfo: [
        {
          char: "過",
          on: ["カ"],
          kun: [
            "す.ぎる",
            "す.ごす",
            "あやま.ち",
            "あやま.つ",
            "よぎ.る",
            "よ.ぎる",
          ],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "労",
          on: ["ロウ"],
          kun: [
            "ろう.する",
            "いたわ.る",
            "いた.ずき",
            "ねぎら",
            "つか.れる",
            "ねぎら.う",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 542,
      kanji: "灌漑",
      reading: "かんがい",
      meanings: {
        ja: "灌漑",
        en: "irrigation",
        zh: "灌溉",
        tw: "灌溉",
        ko: "관개",
        vi: "tưới tiêu",
        th: "ชลประทาน",
        my: "ရေလောင်းခြင်း",
        km: "ស្រោចស្រព",
      },
      furigana: [
        {
          rb: "灌漑",
          rt: "かんがい",
        },
      ],
      kanjiInfo: [
        {
          char: "灌",
          on: ["カン"],
          kun: ["そそ.ぐ"],
          strokes: 20,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
        {
          char: "漑",
          on: ["ガイ", "カイ"],
          kun: ["そそ.ぐ"],
          strokes: 15,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 543,
      kanji: "眼科",
      reading: "がんか",
      meanings: {
        ja: "眼科",
        en: "ophthalmology",
        zh: "眼科",
        tw: "眼科",
        ko: "안과",
        vi: "khoa mắt",
        th: "จักษุวิทยา",
        my: "မျက်စိဌာန",
        km: "ផ្នែកភ្នែក",
      },
      furigana: [
        {
          rb: "眼科",
          rt: "がんか",
        },
      ],
      kanjiInfo: [
        {
          char: "眼",
          on: ["ガン", "ゲン"],
          kun: ["まなこ", "め"],
          strokes: 11,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 544,
      kanji: "眼球",
      reading: "がんきゅう",
      meanings: {
        ja: "眼球",
        en: "eyeball",
        zh: "眼球",
        tw: "眼球",
        ko: "안구",
        vi: "nhãn cầu",
        th: "ลูกตา",
        my: "မျက်စိဘောလုံး",
        km: "ភ្នែក",
      },
      furigana: [
        {
          rb: "眼球",
          rt: "がんきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "眼",
          on: ["ガン", "ゲン"],
          kun: ["まなこ", "め"],
          strokes: 11,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "球",
          on: ["キュウ"],
          kun: ["たま"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 545,
      kanji: "玩具",
      reading: "がんぐ",
      meanings: {
        ja: "玩具",
        en: "toy",
        zh: "玩具",
        tw: "玩具",
        ko: "장난감",
        vi: "đồ chơi",
        th: "ของเล่น",
        my: "ကစားစရာ",
        km: "ប្រដាប់លេង",
      },
      furigana: [
        {
          rb: "玩具",
          rt: "がんぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "玩",
          on: ["ガン"],
          kun: ["もちあそ.ぶ", "もてあそ.ぶ"],
          strokes: 8,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
        {
          char: "具",
          on: ["グ"],
          kun: ["そな.える", "つぶさ.に"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 546,
      kanji: "還元",
      reading: "かんげん",
      meanings: {
        ja: "還元",
        en: "reduction; restoration",
        zh: "还原",
        tw: "還原",
        ko: "환원",
        vi: "hoàn nguyên",
        th: "การคืนกลับ",
        my: "ပြန်လည်ထုတ်ပေးခြင်း",
        km: "ការស្តារឡើងវិញ",
      },
      furigana: [
        {
          rb: "還元",
          rt: "かんげん",
        },
      ],
      kanjiInfo: [
        {
          char: "還",
          on: ["カン"],
          kun: ["かえ.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "元",
          on: ["ゲン", "ガン"],
          kun: ["もと"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 547,
      kanji: "看護",
      reading: "かんご",
      meanings: {
        ja: "看護",
        en: "nursing",
        zh: "护理",
        tw: "護理",
        ko: "간호",
        vi: "điều dưỡng",
        th: "การพยาบาล",
        my: "နားထောင်စောင့်ရှောက်မှု",
        km: "ថែទាំជម្ងឺ",
      },
      furigana: [
        {
          rb: "看護",
          rt: "かんご",
        },
      ],
      kanjiInfo: [
        {
          char: "看",
          on: ["カン"],
          kun: ["み.る"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "護",
          on: ["ゴ"],
          kun: ["まも.る"],
          strokes: 20,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 548,
      kanji: "漢語",
      reading: "かんご",
      meanings: {
        ja: "漢語（中国由来の語）",
        en: "Sino-Japanese word",
        zh: "汉语词汇",
        tw: "漢語詞彙",
        ko: "한자어",
        vi: "từ gốc Hán",
        th: "คำภาษาจีนในภาษาญี่ปุ่น",
        my: "တရုတ်အရင်းအမြစ်စကားလုံး",
        km: "ពាក្យមានប្រភពចិន",
      },
      furigana: [
        {
          rb: "漢語",
          rt: "かんご",
        },
      ],
      kanjiInfo: [
        {
          char: "漢",
          on: ["カン"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 549,
      kanji: "勧告",
      reading: "かんこく",
      meanings: {
        ja: "勧告",
        en: "recommendation; advice",
        zh: "劝告",
        tw: "勸告",
        ko: "권고",
        vi: "khuyến cáo",
        th: "คำแนะนำ",
        my: "အကြံပြုခြင်း",
        km: "ការផ្តល់អនុសាសន៍",
      },
      furigana: [
        {
          rb: "勧告",
          rt: "かんこく",
        },
      ],
      kanjiInfo: [
        {
          char: "勧",
          on: ["カン", "ケン"],
          kun: ["すす.める"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "告",
          on: ["コク"],
          kun: ["つ.げる"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 550,
      kanji: "換算",
      reading: "かんさん",
      meanings: {
        ja: "換算",
        en: "conversion (e.g. yen to dollars)",
        zh: "换算",
        tw: "換算",
        ko: "환산",
        vi: "chuyển đổi (đơn vị tiền)",
        th: "การแปลงค่า",
        my: "ပြောင်းလဲခြင်း",
        km: "ការបំលែង",
      },
      furigana: [
        {
          rb: "換算",
          rt: "かんさん",
        },
      ],
      kanjiInfo: [
        {
          char: "換",
          on: ["カン"],
          kun: ["か.える", "-か.える", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 651,
      kanji: "協定",
      reading: "きょうてい",
      meanings: {
        ja: "協定",
        en: "agreement; pact",
        zh: "协定",
        tw: "協定",
        ko: "협정",
        vi: "hiệp định",
        th: "ข้อตกลง",
        my: "သဘောတူစာချုပ်",
        km: "កិច្ចព្រមព្រៀង",
      },
      furigana: [
        {
          rb: "協定",
          rt: "きょうてい",
        },
      ],
      kanjiInfo: [
        {
          char: "協",
          on: ["キョウ"],
          kun: [],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 652,
      kanji: "郷土",
      reading: "きょうど",
      meanings: {
        ja: "郷土",
        en: "native place; local",
        zh: "乡土",
        tw: "鄉土",
        ko: "향토",
        vi: "quê hương",
        th: "ท้องถิ่น",
        my: "ရာဖြတ်မြေတော်",
        km: "ដីកំណើត",
      },
      furigana: [
        {
          rb: "郷土",
          rt: "きょうど",
        },
      ],
      kanjiInfo: [
        {
          char: "郷",
          on: ["キョウ", "ゴウ"],
          kun: ["さと"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "土",
          on: ["ド", "ト"],
          kun: ["つち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 653,
      kanji: "脅迫",
      reading: "きょうはく",
      meanings: {
        ja: "脅迫",
        en: "threat; intimidation",
        zh: "胁迫",
        tw: "脅迫",
        ko: "협박",
        vi: "đe doạ",
        th: "ข่มขู่",
        my: "တင်းကျပ်ခြိမ်းခြောက်",
        km: "កំហិតគំរាម",
      },
      furigana: [
        {
          rb: "脅迫",
          rt: "きょうはく",
        },
      ],
      kanjiInfo: [
        {
          char: "脅",
          on: ["キョウ"],
          kun: ["おびや.かす", "おど.す", "おど.かす"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "迫",
          on: ["ハク"],
          kun: ["せま.る"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 654,
      kanji: "業務",
      reading: "ぎょうむ",
      meanings: {
        ja: "業務",
        en: "business; duties",
        zh: "业务",
        tw: "業務",
        ko: "업무",
        vi: "nghiệp vụ",
        th: "งาน/ภารกิจ",
        my: "လုပ်ငန်းတာဝန်",
        km: "ភារកិច្ចការងារ",
      },
      furigana: [
        {
          rb: "業務",
          rt: "ぎょうむ",
        },
      ],
      kanjiInfo: [
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "務",
          on: ["ム"],
          kun: ["つと.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 655,
      kanji: "共鳴",
      reading: "きょうめい",
      meanings: {
        ja: "共鳴",
        en: "resonance; sympathy",
        zh: "共鸣",
        tw: "共鳴",
        ko: "공명",
        vi: "cộng hưởng",
        th: "เรโซแนนซ์/สอดคล้อง",
        my: "ထပ်တူဂုဏ်သံ",
        km: "កក់ក្ដៅសមស្រប",
      },
      furigana: [
        {
          rb: "共鳴",
          rt: "きょうめい",
        },
      ],
      kanjiInfo: [
        {
          char: "共",
          on: ["キョウ"],
          kun: ["とも", "とも.に", "-ども"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "鳴",
          on: ["メイ"],
          kun: ["な.く", "な.る", "な.らす"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 656,
      kanji: "郷里",
      reading: "きょうり",
      meanings: {
        ja: "郷里",
        en: "hometown",
        zh: "故乡",
        tw: "故鄉",
        ko: "향리",
        vi: "quê nhà",
        th: "บ้านเกิด",
        my: "ရိပ်သာမြို့",
        km: "ទីកន្លែងកំណើត",
      },
      furigana: [
        {
          rb: "郷里",
          rt: "きょうり",
        },
      ],
      kanjiInfo: [
        {
          char: "郷",
          on: ["キョウ", "ゴウ"],
          kun: ["さと"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "里",
          on: ["リ"],
          kun: ["さと"],
          strokes: 7,
          grade: 2,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 657,
      kanji: "共和",
      reading: "きょうわ",
      meanings: {
        ja: "共和",
        en: "republicanism",
        zh: "共和",
        tw: "共和",
        ko: "공화",
        vi: "chủ nghĩa cộng hòa",
        th: "สาธารณรัฐนิยม",
        my: "ဂိုဏ်းဝါးရေး",
        km: "សាធារណរដ្ឋនិយម",
      },
      furigana: [
        {
          rb: "共和",
          rt: "きょうわ",
        },
      ],
      kanjiInfo: [
        {
          char: "共",
          on: ["キョウ"],
          kun: ["とも", "とも.に", "-ども"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "和",
          on: ["ワ", "オ", "カ"],
          kun: ["やわ.らぐ", "やわ.らげる", "なご.む", "なご.やか", "あ.える"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 658,
      kanji: "局限",
      reading: "きょくげん",
      meanings: {
        ja: "局限",
        en: "limit; restriction",
        zh: "局限",
        tw: "局限",
        ko: "국한",
        vi: "giới hạn",
        th: "จำกัดอยู่ที่",
        my: "ကန့်သတ်ခြင်း",
        km: "កំណត់",
      },
      furigana: [
        {
          rb: "局限",
          rt: "きょくげん",
        },
      ],
      kanjiInfo: [
        {
          char: "局",
          on: ["キョク"],
          kun: ["つぼね"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "限",
          on: ["ゲン"],
          kun: ["かぎ.る", "かぎ.り", "-かぎ.り"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 659,
      kanji: "極端",
      reading: "きょくたん",
      meanings: {
        ja: "極端",
        en: "extreme",
        zh: "极端",
        tw: "極端",
        ko: "극단",
        vi: "cực đoan",
        th: "สุดโต่ง",
        my: "အလွန်အမင်း",
        km: "អតិផរណា",
      },
      furigana: [
        {
          rb: "極端",
          rt: "きょくたん",
        },
      ],
      kanjiInfo: [
        {
          char: "極",
          on: ["キョク", "ゴク"],
          kun: [
            "きわ.める",
            "きわ.まる",
            "きわ.まり",
            "きわ.み",
            "き.める",
            "-ぎ.め",
            "き.まる",
          ],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "端",
          on: ["タン"],
          kun: ["はし", "は", "はた", "-ばた", "はな"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 660,
      kanji: "居住",
      reading: "きょじゅう",
      meanings: {
        ja: "居住",
        en: "residence; living",
        zh: "居住",
        tw: "居住",
        ko: "거주",
        vi: "cư trú",
        th: "พำนักอาศัย",
        my: "နေထိုင်မှု",
        km: "ស្នាក់នៅ",
      },
      furigana: [
        {
          rb: "居住",
          rt: "きょじゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "居",
          on: ["キョ", "コ"],
          kun: ["い.る", "-い", "お.る"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "住",
          on: ["ジュウ", "ヂュウ", "チュウ"],
          kun: ["す.む", "す.まう", "-ず.まい"],
          strokes: 7,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 661,
      kanji: "拒絶",
      reading: "きょぜつ",
      meanings: {
        ja: "拒絶",
        en: "refusal; rejection",
        zh: "拒绝",
        tw: "拒絕",
        ko: "거절",
        vi: "từ chối",
        th: "ปฏิเสธ",
        my: "ငြင်းပယ်",
        km: "បដិសេធ",
      },
      furigana: [
        {
          rb: "拒絶",
          rt: "きょぜつ",
        },
      ],
      kanjiInfo: [
        {
          char: "拒",
          on: ["キョ", "ゴ"],
          kun: ["こば.む"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "絶",
          on: ["ゼツ"],
          kun: ["た.える", "た.やす", "た.つ"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 662,
      kanji: "漁船",
      reading: "ぎょせん",
      meanings: {
        ja: "漁船",
        en: "fishing boat",
        zh: "渔船",
        tw: "漁船",
        ko: "어선",
        vi: "tàu đánh cá",
        th: "เรือประมง",
        my: "ငါးဖမ်းလှေ",
        km: "ទូកនេសាទ",
      },
      furigana: [
        {
          rb: "漁船",
          rt: "ぎょせん",
        },
      ],
      kanjiInfo: [
        {
          char: "漁",
          on: ["ギョ", "リョウ"],
          kun: ["あさ.る"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "船",
          on: ["セン"],
          kun: ["ふね", "ふな-"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 663,
      kanji: "漁村",
      reading: "ぎょそん",
      meanings: {
        ja: "漁村",
        en: "fishing village",
        zh: "渔村",
        tw: "漁村",
        ko: "어촌",
        vi: "làng chài",
        th: "หมู่บ้านประมง",
        my: "ငါးဖမ်းရွာ",
        km: "ភូមិនេសាទ",
      },
      furigana: [
        {
          rb: "漁村",
          rt: "ぎょそん",
        },
      ],
      kanjiInfo: [
        {
          char: "漁",
          on: ["ギョ", "リョウ"],
          kun: ["あさ.る"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "村",
          on: ["ソン"],
          kun: ["むら"],
          strokes: 7,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 664,
      kanji: "拒否",
      reading: "きょひ",
      meanings: {
        ja: "拒否",
        en: "refusal; denial",
        zh: "拒否",
        tw: "拒否",
        ko: "거부",
        vi: "khước từ",
        th: "ปฏิเสธ",
        my: "မလက်ခံ",
        km: "មិនអនុញ្ញាត",
      },
      furigana: [
        {
          rb: "拒否",
          rt: "きょひ",
        },
      ],
      kanjiInfo: [
        {
          char: "拒",
          on: ["キョ", "ゴ"],
          kun: ["こば.む"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "否",
          on: ["ヒ"],
          kun: ["いな", "いや"],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 665,
      kanji: "許容",
      reading: "きょよう",
      meanings: {
        ja: "許容",
        en: "permission; tolerance",
        zh: "允许; 容许",
        tw: "許容",
        ko: "허용",
        vi: "cho phép",
        th: "ยอมรับ/อนุญาต",
        my: "ခွင့်ပြုမှု",
        km: "អនុញ្ញាត",
      },
      furigana: [
        {
          rb: "許容",
          rt: "きょよう",
        },
      ],
      kanjiInfo: [
        {
          char: "許",
          on: ["キョ"],
          kun: ["ゆる.す", "もと"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "容",
          on: ["ヨウ"],
          kun: ["い.れる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 666,
      kanji: "義理",
      reading: "ぎり",
      meanings: {
        ja: "義理",
        en: "duty; obligation",
        zh: "人情世故; 义务",
        tw: "人情／義理",
        ko: "의리",
        vi: "nghĩa tình; bổn phận",
        th: "บุญคุณ/หน้าที่",
        my: "ယဉ်ကျေးမှုအသိဉာဏ်",
        km: "សាច់ញាតិ/គោរពកិត្តិយស",
      },
      furigana: [
        {
          rb: "義理",
          rt: "ぎり",
        },
      ],
      kanjiInfo: [
        {
          char: "義",
          on: ["ギ"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "理",
          on: ["リ"],
          kun: ["ことわり"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 667,
      kanji: "切替",
      reading: "きりかえ",
      meanings: {
        ja: "切替",
        en: "switch; changeover",
        zh: "切换",
        tw: "切換",
        ko: "전환",
        vi: "chuyển đổi",
        th: "สลับ/เปลี่ยน",
        my: "ပြောင်းလဲခြင်း",
        km: "ប្ដូរ",
      },
      furigana: [
        {
          rb: "切替",
          rt: "きりかえ",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "替",
          on: ["タイ"],
          kun: ["か.える", "か.え-", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 668,
      kanji: "気流",
      reading: "きりゅう",
      meanings: {
        ja: "気流",
        en: "air current",
        zh: "气流",
        tw: "氣流",
        ko: "기류",
        vi: "dòng khí",
        th: "กระแสอากาศ",
        my: "လေစီးကြောင်း",
        km: "ស្រក់ខ្យល់",
      },
      furigana: [
        {
          rb: "気流",
          rt: "きりゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "流",
          on: ["リュウ", "ル"],
          kun: ["なが.れる", "なが.れ", "なが.す", "-なが.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 669,
      kanji: "切れ目",
      reading: "きれめ",
      meanings: {
        ja: "切れ目",
        en: "gap; break",
        zh: "间断; 缺口",
        tw: "間斷；缺口",
        ko: "틈새; 끊김",
        vi: "khe hở; đoạn ngắt",
        th: "ช่องว่าง/ช่วงขาดตอน",
        my: "ကြားထဲ/အဆက်ပြတ်",
        km: "ចន្លោះ",
      },
      furigana: [
        {
          rb: "切れ目",
          rt: "きれめ",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 670,
      kanji: "疑惑",
      reading: "ぎわく",
      meanings: {
        ja: "疑惑",
        en: "doubt; suspicion",
        zh: "疑惑",
        tw: "疑惑",
        ko: "의혹",
        vi: "nghi hoặc",
        th: "ข้อกังขา",
        my: "သံသယ",
        km: "សង្ស័យ",
      },
      furigana: [
        {
          rb: "疑惑",
          rt: "ぎわく",
        },
      ],
      kanjiInfo: [
        {
          char: "疑",
          on: ["ギ"],
          kun: ["うたが.う"],
          strokes: 14,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "惑",
          on: ["ワク"],
          kun: ["まど.う"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 671,
      kanji: "近眼",
      reading: "きんがん",
      meanings: {
        ja: "近眼",
        en: "nearsightedness",
        zh: "近视",
        tw: "近視",
        ko: "근시",
        vi: "cận thị",
        th: "สายตาสั้น",
        my: "မျက်စိနီးမြင်",
        km: "ខ្វះសតិសម្បទា? (correct=ខ្សោយភ្នែក-ចក្ខុពិសេស)→ ក្បាលភ្នែកខ្សោយ",
      },
      furigana: [
        {
          rb: "近眼",
          rt: "きんがん",
        },
      ],
      kanjiInfo: [
        {
          char: "近",
          on: ["キン", "コン"],
          kun: ["ちか.い"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "眼",
          on: ["ガン", "ゲン"],
          kun: ["まなこ", "め"],
          strokes: 11,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 672,
      kanji: "緊急",
      reading: "きんきゅう",
      meanings: {
        ja: "緊急",
        en: "emergency; urgent",
        zh: "紧急",
        tw: "緊急",
        ko: "긴급",
        vi: "khẩn cấp",
        th: "ฉุกเฉิน",
        my: "အရေးပေါ်",
        km: "បន្ទាន់",
      },
      furigana: [
        {
          rb: "緊急",
          rt: "きんきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "緊",
          on: ["キン"],
          kun: ["し.める", "し.まる"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "急",
          on: ["キュウ"],
          kun: ["いそ.ぐ", "いそ.ぎ", "せ.く"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 673,
      kanji: "近郊",
      reading: "きんこう",
      meanings: {
        ja: "近郊",
        en: "suburbs; outskirts",
        zh: "近郊",
        tw: "近郊",
        ko: "근교",
        vi: "vùng ven",
        th: "ชานเมือง",
        my: "မြို့ပြဝန်းကျင်",
        km: "ជាយក្រុង",
      },
      furigana: [
        {
          rb: "近郊",
          rt: "きんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "近",
          on: ["キン", "コン"],
          kun: ["ちか.い"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "郊",
          on: ["コウ"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 674,
      kanji: "均衡",
      reading: "きんこう",
      meanings: {
        ja: "均衡",
        en: "balance; equilibrium",
        zh: "均衡",
        tw: "均衡",
        ko: "균형",
        vi: "cân bằng",
        th: "ดุลยภาพ",
        my: "နှိမ့်မြှင့်ညှိနှိုင်း",
        km: "តុល្យភាព",
      },
      furigana: [
        {
          rb: "均衡",
          rt: "きんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "均",
          on: ["キン"],
          kun: ["なら.す"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "衡",
          on: ["コウ"],
          kun: [],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 675,
      kanji: "吟味",
      reading: "ぎんみ",
      meanings: {
        ja: "吟味",
        en: "close examination",
        zh: "斟酌; 考量",
        tw: "斟酌；審酌",
        ko: "심사숙고",
        vi: "cân nhắc kỹ",
        th: "พิจารณาอย่างถี่ถ้วน",
        my: "ညှိနှိုင်းသေချာစွာ",
        km: "ពិនិត្យជិតស្និទ្ធ",
      },
      furigana: [
        {
          rb: "吟味",
          rt: "ぎんみ",
        },
      ],
      kanjiInfo: [
        {
          char: "吟",
          on: ["ギン"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 676,
      kanji: "勤務",
      reading: "きんむ",
      meanings: {
        ja: "勤務",
        en: "service; duty (work)",
        zh: "勤務",
        tw: "勤務",
        ko: "근무",
        vi: "làm việc",
        th: "ปฏิบัติงาน",
        my: "ပါတိုင်းဝန်ထမ်း",
        km: "ការងារ",
      },
      furigana: [
        {
          rb: "勤務",
          rt: "きんむ",
        },
      ],
      kanjiInfo: [
        {
          char: "勤",
          on: ["キン", "ゴン"],
          kun: ["つと.める", "-づと.め", "つと.まる", "いそ.しむ"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "務",
          on: ["ム"],
          kun: ["つと.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 677,
      kanji: "禁物",
      reading: "きんもつ",
      meanings: {
        ja: "禁物",
        en: "taboo; no-no",
        zh: "禁忌",
        tw: "禁忌",
        ko: "금물",
        vi: "điều cấm kỵ",
        th: "ของต้องห้าม",
        my: "မပြုရသောအရာ",
        km: "អ្វីដែលហាមឃាត់",
      },
      furigana: [
        {
          rb: "禁物",
          rt: "きんもつ",
        },
      ],
      kanjiInfo: [
        {
          char: "禁",
          on: ["キン"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 678,
      kanji: "勤労",
      reading: "きんろう",
      meanings: {
        ja: "勤労",
        en: "labor; work",
        zh: "勤劳",
        tw: "勤勞",
        ko: "근로",
        vi: "cần lao/lao động",
        th: "แรงงาน",
        my: "အလုပ်လုပ်မှု",
        km: "ការងារ",
      },
      furigana: [
        {
          rb: "勤労",
          rt: "きんろう",
        },
      ],
      kanjiInfo: [
        {
          char: "勤",
          on: ["キン", "ゴン"],
          kun: ["つと.める", "-づと.め", "つと.まる", "いそ.しむ"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "労",
          on: ["ロウ"],
          kun: [
            "ろう.する",
            "いたわ.る",
            "いた.ずき",
            "ねぎら",
            "つか.れる",
            "ねぎら.う",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 679,
      kanji: "クイズ",
      reading: "クイズ",
      meanings: {
        ja: "クイズ",
        en: "quiz",
        zh: "问答/测验",
        tw: "問答/小測驗",
        ko: "퀴즈",
        vi: "đố vui",
        th: "แบบทดสอบ",
        my: "ဝါသနာမေးခွန်း",
        km: "សំនួរតេស្ត",
      },
      furigana: [
        {
          rb: "クイズ",
          rt: "クイズ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 680,
      kanji: "空間",
      reading: "くうかん",
      meanings: {
        ja: "空間",
        en: "space",
        zh: "空间",
        tw: "空間",
        ko: "공간",
        vi: "không gian",
        th: "พื้นที่/มิติ",
        my: "အတွင်းလေး",
        km: "លំហ",
      },
      furigana: [
        {
          rb: "空間",
          rt: "くうかん",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 681,
      kanji: "空腹",
      reading: "くうふく",
      meanings: {
        ja: "空腹",
        en: "empty stomach; hunger",
        zh: "空腹",
        tw: "空腹",
        ko: "공복",
        vi: "đói bụng",
        th: "ท้องว่าง/หิว",
        my: "ဗိုက်ဆာ",
        km: "ពោះទទេ",
      },
      furigana: [
        {
          rb: "空腹",
          rt: "くうふく",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "腹",
          on: ["フク"],
          kun: ["はら"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 682,
      kanji: "区画",
      reading: "くかく",
      meanings: {
        ja: "区画",
        en: "division; lot",
        zh: "区划",
        tw: "區劃",
        ko: "구획",
        vi: "khu/buồng",
        th: "เขตแบ่ง",
        my: "ခွဲခြားကန့်သတ်",
        km: "ការបែងចែក",
      },
      furigana: [
        {
          rb: "区画",
          rt: "くかく",
        },
      ],
      kanjiInfo: [
        {
          char: "区",
          on: ["ク", "オウ", "コウ"],
          kun: [],
          strokes: 4,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "画",
          on: ["ガ", "カク", "エ", "カイ"],
          kun: ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 683,
      kanji: "区間",
      reading: "くかん",
      meanings: {
        ja: "区間",
        en: "section (e.g., of track)",
        zh: "区间",
        tw: "區間",
        ko: "구간",
        vi: "đoạn (đường…)",
        th: "ช่วง (เส้นทาง)",
        my: "အပိုင်းအခြား",
        km: "ចន្លោះផ្លូវ",
      },
      furigana: [
        {
          rb: "区間",
          rt: "くかん",
        },
      ],
      kanjiInfo: [
        {
          char: "区",
          on: ["ク", "オウ", "コウ"],
          kun: [],
          strokes: 4,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 684,
      kanji: "茎",
      reading: "くき",
      meanings: {
        ja: "茎",
        en: "stalk; stem",
        zh: "茎",
        tw: "莖",
        ko: "줄기",
        vi: "thân cây",
        th: "ก้าน/ลำต้น",
        my: "တံခွန်",
        km: "ដើម/តំបែរ",
      },
      furigana: [
        {
          rb: "茎",
          rt: "くき",
        },
      ],
      kanjiInfo: [
        {
          char: "茎",
          on: ["ケイ", "キョウ"],
          kun: ["くき"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 685,
      kanji: "区切り",
      reading: "くぎり",
      meanings: {
        ja: "区切り",
        en: "pause; division",
        zh: "分段；间歇",
        tw: "分段；停頓",
        ko: "구분; 휴지",
        vi: "ngắt đoạn",
        th: "การแบ่งช่วง/หยุดพัก",
        my: "ခွဲခြားနေရာ",
        km: "ការបំបែក",
      },
      furigana: [
        {
          rb: "区切り",
          rt: "くぎり",
        },
      ],
      kanjiInfo: [
        {
          char: "区",
          on: ["ク", "オウ", "コウ"],
          kun: [],
          strokes: 4,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 686,
      kanji: "愚痴",
      reading: "ぐち",
      meanings: {
        ja: "愚痴",
        en: "grumble; complaint",
        zh: "牢骚",
        tw: "牢騷",
        ko: "하소연",
        vi: "cằn nhằn",
        th: "บ่น",
        my: "အပန်းဖြေမနေရ",
        km: "ពាក្យរអ៊ូរទាំ",
      },
      furigana: [
        {
          rb: "愚痴",
          rt: "ぐち",
        },
      ],
      kanjiInfo: [
        {
          char: "愚",
          on: ["グ"],
          kun: ["おろ.か"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "痴",
          on: ["チ"],
          kun: ["し.れる", "おろか"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 687,
      kanji: "嘴",
      reading: "くちばし",
      meanings: {
        ja: "嘴（くちばし）",
        en: "beak",
        zh: "喙",
        tw: "喙/鳥嘴",
        ko: "부리",
        vi: "mỏ (chim)",
        th: "จะงอยปาก",
        my: "ငှက်နှာ",
        km: "ចង្កោម",
      },
      furigana: [
        {
          rb: "嘴",
          rt: "くちばし",
        },
      ],
      kanjiInfo: [
        {
          char: "嘴",
          on: ["シ"],
          kun: ["くちばし", "はし"],
          strokes: 16,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 688,
      kanji: "屈折",
      reading: "くっせつ",
      meanings: {
        ja: "屈折",
        en: "bending; refraction",
        zh: "屈折",
        tw: "屈折",
        ko: "굴절",
        vi: "khúc xạ; uốn cong",
        th: "หักเห/คดงอ",
        my: "အောက်ချိုး",
        km: "បាក់បែក",
      },
      furigana: [
        {
          rb: "屈折",
          rt: "くっせつ",
        },
      ],
      kanjiInfo: [
        {
          char: "屈",
          on: ["クツ"],
          kun: ["かが.む", "かが.める"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "折",
          on: ["セツ", "シャク"],
          kun: ["お.る", "おり", "お.り", "-お.り", "お.れる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 689,
      kanji: "首飾り",
      reading: "くびかざり",
      meanings: {
        ja: "首飾り",
        en: "necklace",
        zh: "项链",
        tw: "項鍊",
        ko: "목걸이",
        vi: "dây chuyền",
        th: "สร้อยคอ",
        my: "လည်ချောင်းကုံး",
        km: "ខ្សែស្រវាញ",
      },
      furigana: [
        {
          rb: "首飾り",
          rt: "くびかざり",
        },
      ],
      kanjiInfo: [
        {
          char: "首",
          on: ["シュ"],
          kun: ["くび"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "飾",
          on: ["ショク"],
          kun: ["かざ.る", "かざ.り"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 690,
      kanji: "首輪",
      reading: "くびわ",
      meanings: {
        ja: "首輪",
        en: "collar (animal)",
        zh: "颈圈",
        tw: "項圈",
        ko: "목줄",
        vi: "vòng cổ (thú)",
        th: "ปลอกคอสัตว์",
        my: "လည်တံခါးခွာ",
        km: "ខ្សែពួរ",
      },
      furigana: [
        {
          rb: "首輪",
          rt: "くびわ",
        },
      ],
      kanjiInfo: [
        {
          char: "首",
          on: ["シュ"],
          kun: ["くび"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "輪",
          on: ["リン"],
          kun: ["わ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 691,
      kanji: "蔵",
      reading: "くら",
      meanings: {
        ja: "蔵",
        en: "warehouse; storehouse",
        zh: "仓库",
        tw: "倉庫",
        ko: "곳간",
        vi: "kho",
        th: "ยุ้งฉาง/คลัง",
        my: "ဂိုဒေါင်",
        km: "ឃ្លាំង",
      },
      furigana: [
        {
          rb: "蔵",
          rt: "くら",
        },
      ],
      kanjiInfo: [
        {
          char: "蔵",
          on: ["ゾウ", "ソウ"],
          kun: ["くら", "おさ.める", "かく.れる"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 692,
      kanji: "グレー",
      reading: "グレー",
      meanings: {
        ja: "グレー",
        en: "grey",
        zh: "灰色",
        tw: "灰色",
        ko: "회색",
        vi: "màu xám",
        th: "สีเทา",
        my: "မီးခိုးရောင်",
        km: "ពណ៌ប្រផេះ",
      },
      furigana: [
        {
          rb: "グレー",
          rt: "グレー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 693,
      kanji: "クレーン",
      reading: "クレーン",
      meanings: {
        ja: "クレーン",
        en: "crane (machine)",
        zh: "起重机",
        tw: "起重機",
        ko: "크레인",
        vi: "cần cẩu",
        th: "ปั้นจั่น",
        my: "ဗိသုကာကွမ်းကင်",
        km: "ម៉ាស៊ីនកប់",
      },
      furigana: [
        {
          rb: "クレーン",
          rt: "クレーン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 694,
      kanji: "玄人",
      reading: "くろうと",
      meanings: {
        ja: "玄人",
        en: "expert; professional",
        zh: "行家",
        tw: "行家",
        ko: "전문가",
        vi: "chuyên gia",
        th: "ผู้เชี่ยวชาญ",
        my: "ကျွမ်းကျင်သူ",
        km: "អ្នកជំនាញ",
      },
      furigana: [
        {
          rb: "玄人",
          rt: "くろうと",
        },
      ],
      kanjiInfo: [
        {
          char: "玄",
          on: ["ゲン"],
          kun: ["くろ", "くろ.い"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 695,
      kanji: "黒字",
      reading: "くろじ",
      meanings: {
        ja: "黒字",
        en: "surplus; in the black",
        zh: "盈余",
        tw: "盈餘",
        ko: "흑자",
        vi: "thặng dư",
        th: "กำไรเกินดุล",
        my: "ဝင်ငွေကျွနု်ပ်",
        km: "ខាតតិច—>លើសទុន (សុទ្ធ)=លាភ",
      },
      furigana: [
        {
          rb: "黒字",
          rt: "くろじ",
        },
      ],
      kanjiInfo: [
        {
          char: "黒",
          on: ["コク"],
          kun: ["くろ", "くろ.ずむ", "くろ.い"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 696,
      kanji: "軍艦",
      reading: "ぐんかん",
      meanings: {
        ja: "軍艦",
        en: "warship",
        zh: "军舰",
        tw: "軍艦",
        ko: "군함",
        vi: "tàu chiến",
        th: "เรือรบ",
        my: "စစ်ရေယာဉ်",
        km: "នាវាចំហាយយុទ្ធ",
      },
      furigana: [
        {
          rb: "軍艦",
          rt: "ぐんかん",
        },
      ],
      kanjiInfo: [
        {
          char: "軍",
          on: ["グン"],
          kun: ["いくさ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "艦",
          on: ["カン"],
          kun: [],
          strokes: 21,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 697,
      kanji: "軍事",
      reading: "ぐんじ",
      meanings: {
        ja: "軍事",
        en: "military affairs",
        zh: "军事",
        tw: "軍事",
        ko: "군사",
        vi: "quân sự",
        th: "การทหาร",
        my: "စစ်ရေး",
        km: "យោធា",
      },
      furigana: [
        {
          rb: "軍事",
          rt: "ぐんじ",
        },
      ],
      kanjiInfo: [
        {
          char: "軍",
          on: ["グン"],
          kun: ["いくさ"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 698,
      kanji: "君主",
      reading: "くんしゅ",
      meanings: {
        ja: "君主",
        en: "monarch; sovereign",
        zh: "君主",
        tw: "君主",
        ko: "군주",
        vi: "quân chủ",
        th: "พระมหากษัตริย์",
        my: "လူမျိုးထိန်း",
        km: "ព្រះមហាក្សត្រ",
      },
      furigana: [
        {
          rb: "君主",
          rt: "くんしゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "君",
          on: ["クン"],
          kun: ["きみ", "-ぎみ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 699,
      kanji: "群集",
      reading: "ぐんしゅう",
      meanings: {
        ja: "群集",
        en: "crowd",
        zh: "群集",
        tw: "群集",
        ko: "군집/군중",
        vi: "đám đông",
        th: "ฝูงชน",
        my: "လူစုဝေး",
        km: "មហាជន",
      },
      furigana: [
        {
          rb: "群集",
          rt: "ぐんしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "群",
          on: ["グン"],
          kun: ["む.れる", "む.れ", "むら", "むら.がる"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "集",
          on: ["シュウ"],
          kun: ["あつ.まる", "あつ.める", "つど.う"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 700,
      kanji: "群衆",
      reading: "ぐんしゅう",
      meanings: {
        ja: "群衆",
        en: "multitude; crowd",
        zh: "群众",
        tw: "群眾",
        ko: "군중",
        vi: "quần chúng",
        th: "มหาชน/ฝูงชน",
        my: "ပြည်သူအများ",
        km: "សាធារណជន",
      },
      furigana: [
        {
          rb: "群衆",
          rt: "ぐんしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "群",
          on: ["グン"],
          kun: ["む.れる", "む.れ", "むら", "むら.がる"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "衆",
          on: ["シュウ", "シュ"],
          kun: ["おお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
