export const n1part8 = {
  Lesson8: [
    {
      id: 351,
      kanji: "一別",
      reading: "いちべつ",
      meanings: {
        ja: "一別",
        en: "parting",
        zh: "分别",
        tw: "分別",
        ko: "이별",
        vi: "chia tay",
        th: "จากกัน",
        my: "ခွာခြားခြင်း",
        km: "ការផ្តាច់ចេញ",
      },
      furigana: [
        {
          rb: "一別",
          rt: "いちべつ",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "別",
          on: ["ベツ"],
          kun: ["わか.れる", "わ.ける"],
          strokes: 7,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 352,
      kanji: "一面",
      reading: "いちめん",
      meanings: {
        ja: "一面",
        en: "one side; whole surface",
        zh: "一面；整个表面",
        tw: "一面；整個表面",
        ko: "한쪽 면; 전체",
        vi: "một mặt; toàn bộ",
        th: "ด้านเดียว; ทั้งหมด",
        my: "တစ်ဖက်ခြမ်း; အနှစ်သာရ",
        km: "ផ្ទៃមួយ; ទាំងមូល",
      },
      furigana: [
        {
          rb: "一面",
          rt: "いちめん",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 353,
      kanji: "一目",
      reading: "いちもく",
      meanings: {
        ja: "一目",
        en: "a glance",
        zh: "一眼",
        tw: "一眼",
        ko: "한눈",
        vi: "cái nhìn",
        th: "มองแวบเดียว",
        my: "တစ်ချက်မြင်ခြင်း",
        km: "ការមើលម្តង",
      },
      furigana: [
        {
          rb: "一目",
          rt: "いちもく",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 354,
      kanji: "一連",
      reading: "いちれん",
      meanings: {
        ja: "一連",
        en: "series",
        zh: "一连串",
        tw: "一連串",
        ko: "일련",
        vi: "chuỗi",
        th: "ชุดต่อเนื่อง",
        my: "အဆက်အဆက်",
        km: "ស៊េរី",
      },
      furigana: [
        {
          rb: "一連",
          rt: "いちれん",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "連",
          on: ["レン"],
          kun: ["つら.なる", "つら.ねる", "つ.れる", "-づ.れ"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 355,
      kanji: "一括",
      reading: "いっかつ",
      meanings: {
        ja: "一括",
        en: "lump sum; all together",
        zh: "总括；一次性",
        tw: "總括；一次性",
        ko: "일괄",
        vi: "gộp chung; một lần",
        th: "รวมเป็นหนึ่งเดียว",
        my: "စုစည်း",
        km: "ជារួម",
      },
      furigana: [
        {
          rb: "一括",
          rt: "いっかつ",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "括",
          on: ["カツ"],
          kun: ["くく.る"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 356,
      kanji: "一気",
      reading: "いっき",
      meanings: {
        ja: "一気",
        en: "in one breath",
        zh: "一口气",
        tw: "一口氣",
        ko: "한숨에",
        vi: "một hơi",
        th: "ในคราวเดียว",
        my: "တစ်ချက်တည်း",
        km: "ម្តងទាំងអស់",
      },
      furigana: [
        {
          rb: "一気",
          rt: "いっき",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 357,
      kanji: "一見",
      reading: "いっけん",
      meanings: {
        ja: "一見",
        en: "a look; apparently",
        zh: "一看；乍看",
        tw: "一看；乍看",
        ko: "언뜻 보기",
        vi: "thoạt nhìn",
        th: "มองดูคร่าวๆ",
        my: "မြင်တိုင်းမြင်ချင်း",
        km: "មើលឃើញម្តង",
      },
      furigana: [
        {
          rb: "一見",
          rt: "いっけん",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 358,
      kanji: "一切",
      reading: "いっさい",
      meanings: {
        ja: "一切",
        en: "all; everything",
        zh: "一切；全部",
        tw: "一切；全部",
        ko: "일절; 모든 것",
        vi: "tất cả",
        th: "ทั้งหมด",
        my: "အားလုံး",
        km: "ទាំងអស់",
      },
      furigana: [
        {
          rb: "一切",
          rt: "いっさい",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 359,
      kanji: "一変",
      reading: "いっぺん",
      meanings: {
        ja: "一変",
        en: "complete change",
        zh: "完全改变",
        tw: "完全改變",
        ko: "일변",
        vi: "thay đổi hoàn toàn",
        th: "เปลี่ยนไปสิ้นเชิง",
        my: "ပြောင်းလဲသွား",
        km: "បម្លែងទាំងស្រុង",
      },
      furigana: [
        {
          rb: "一変",
          rt: "いっぺん",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "変",
          on: ["ヘン"],
          kun: ["か.わる", "か.わり", "か.える"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 360,
      kanji: "意図",
      reading: "いと",
      meanings: {
        ja: "意図",
        en: "intention",
        zh: "意图",
        tw: "意圖",
        ko: "의도",
        vi: "ý đồ",
        th: "เจตนา",
        my: "အဓိပ္ပါယ်ထားချက်",
        km: "បំណង",
      },
      furigana: [
        {
          rb: "意図",
          rt: "いと",
        },
      ],
      kanjiInfo: [
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "図",
          on: ["ズ", "ト"],
          kun: ["え", "はか.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 361,
      kanji: "稲光",
      reading: "いなびかり",
      meanings: {
        ja: "稲光",
        en: "lightning",
        zh: "闪电",
        tw: "閃電",
        ko: "번개",
        vi: "tia chớp",
        th: "ฟ้าแลบ",
        my: "မိုးပါးမုန်တိုင်း",
        km: "ផ្គរលាន់",
      },
      furigana: [
        {
          rb: "稲光",
          rt: "いなびかり",
        },
      ],
      kanjiInfo: [
        {
          char: "稲",
          on: ["トウ", "テ"],
          kun: ["いね", "いな-"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "光",
          on: ["コウ"],
          kun: ["ひか.る", "ひかり"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 362,
      kanji: "祈り",
      reading: "いのり",
      meanings: {
        ja: "祈り",
        en: "prayer",
        zh: "祈祷",
        tw: "祈禱",
        ko: "기도",
        vi: "lời cầu nguyện",
        th: "การอธิษฐาน",
        my: "ဆုတောင်းခြင်း",
        km: "ការអធិស្ឋាន",
      },
      furigana: [
        {
          rb: "祈り",
          rt: "いのり",
        },
      ],
      kanjiInfo: [
        {
          char: "祈",
          on: ["キ"],
          kun: ["いの.る"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 363,
      kanji: "移民",
      reading: "いみん",
      meanings: {
        ja: "移民",
        en: "immigrant",
        zh: "移民",
        tw: "移民",
        ko: "이민",
        vi: "người nhập cư",
        th: "ผู้อพยพ",
        my: "ပြောင်းရွှေ့နေထိုင်သူ",
        km: "ជនអន្តោប្រវេសន៍",
      },
      furigana: [
        {
          rb: "移民",
          rt: "いみん",
        },
      ],
      kanjiInfo: [
        {
          char: "移",
          on: ["イ"],
          kun: ["うつ.る", "うつ.す"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "民",
          on: ["ミン"],
          kun: ["たみ"],
          strokes: 5,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 364,
      kanji: "意欲",
      reading: "いよく",
      meanings: {
        ja: "意欲",
        en: "will; desire",
        zh: "意愿",
        tw: "意願",
        ko: "의욕",
        vi: "mong muốn",
        th: "ความตั้งใจ",
        my: "အလိုဆန္ဒ",
        km: "បំណងប្រាថ្នា",
      },
      furigana: [
        {
          rb: "意欲",
          rt: "いよく",
        },
      ],
      kanjiInfo: [
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "欲",
          on: ["ヨク"],
          kun: ["ほっ.する", "ほ.しい"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 365,
      kanji: "威力",
      reading: "いりょく",
      meanings: {
        ja: "威力",
        en: "power",
        zh: "威力",
        tw: "威力",
        ko: "위력",
        vi: "sức mạnh",
        th: "อำนาจ",
        my: "အာဏာတန်ခိုး",
        km: "អំណាច",
      },
      furigana: [
        {
          rb: "威力",
          rt: "いりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "威",
          on: ["イ"],
          kun: ["おど.す", "おど.し", "おど.かす"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 366,
      kanji: "衣類",
      reading: "いるい",
      meanings: {
        ja: "衣類",
        en: "clothing",
        zh: "衣物",
        tw: "衣物",
        ko: "의류",
        vi: "quần áo",
        th: "เสื้อผ้า",
        my: "အဝတ်အထည်",
        km: "សម្លៀកបំពាក់",
      },
      furigana: [
        {
          rb: "衣類",
          rt: "いるい",
        },
      ],
      kanjiInfo: [
        {
          char: "衣",
          on: ["イ", "エ"],
          kun: ["ころも", "きぬ", "-ぎ"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "類",
          on: ["ルイ"],
          kun: ["たぐ.い"],
          strokes: 18,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 367,
      kanji: "異論",
      reading: "いろん",
      meanings: {
        ja: "異論",
        en: "different opinion",
        zh: "异议",
        tw: "異議",
        ko: "이론",
        vi: "ý kiến khác",
        th: "ความเห็นต่าง",
        my: "အမြင်မတူခြင်း",
        km: "គំនិតខុសគ្នា",
      },
      furigana: [
        {
          rb: "異論",
          rt: "いろん",
        },
      ],
      kanjiInfo: [
        {
          char: "異",
          on: ["イ"],
          kun: ["こと", "こと.なる", "け"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 368,
      kanji: "印鑑",
      reading: "いんかん",
      meanings: {
        ja: "印鑑",
        en: "seal; stamp",
        zh: "印章",
        tw: "印章",
        ko: "도장",
        vi: "con dấu",
        th: "ตราประทับ",
        my: "တံဆိပ်",
        km: "ត្រា",
      },
      furigana: [
        {
          rb: "印鑑",
          rt: "いんかん",
        },
      ],
      kanjiInfo: [
        {
          char: "印",
          on: ["イン"],
          kun: ["しるし", "-じるし", "しる.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "鑑",
          on: ["カン"],
          kun: ["かんが.みる", "かがみ"],
          strokes: 23,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 369,
      kanji: "隠居",
      reading: "いんきょ",
      meanings: {
        ja: "隠居",
        en: "retirement",
        zh: "退休",
        tw: "退休",
        ko: "은거",
        vi: "nghỉ hưu",
        th: "เกษียณ",
        my: "အနားယူခြင်း",
        km: "ចូលនិវត្តន៍",
      },
      furigana: [
        {
          rb: "隠居",
          rt: "いんきょ",
        },
      ],
      kanjiInfo: [
        {
          char: "隠",
          on: ["イン", "オン"],
          kun: ["かく.す", "かく.し", "かく.れる", "よ.る"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "居",
          on: ["キョ", "コ"],
          kun: ["い.る", "-い", "お.る"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 370,
      kanji: "インターチェンジ",
      reading: "インターチェンジ",
      meanings: {
        ja: "インターチェンジ",
        en: "interchange",
        zh: "立体交叉",
        tw: "交流道",
        ko: "인터체인지",
        vi: "nút giao",
        th: "ทางแยกต่างระดับ",
        my: "လမ်းဆုံ",
        km: "ចំណតផ្លូវ",
      },
      furigana: [
        {
          rb: "インターチェンジ",
          rt: "インターチェンジ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 371,
      kanji: "インターフォン",
      reading: "インターフォン",
      meanings: {
        ja: "インターフォン",
        en: "intercom",
        zh: "对讲机",
        tw: "對講機",
        ko: "인터폰",
        vi: "máy liên lạc nội bộ",
        th: "อินเตอร์คอม",
        my: "အတွင်းဆက်သွယ်စနစ်",
        km: "ម៉ាស៊ីនសន្ទនា",
      },
      furigana: [
        {
          rb: "インターフォン",
          rt: "インターフォン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 372,
      kanji: "インテリ",
      reading: "インテリ",
      meanings: {
        ja: "インテリ",
        en: "intellectual",
        zh: "知识分子",
        tw: "知識份子",
        ko: "지식인",
        vi: "trí thức",
        th: "ปัญญาชน",
        my: "ဗဟုသုတရှိသူ",
        km: "បុគ្គលមានចំណេះដឹង",
      },
      furigana: [
        {
          rb: "インテリ",
          rt: "インテリ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 373,
      kanji: "インフォメーション",
      reading: "インフォメーション",
      meanings: {
        ja: "案内",
        en: "information",
        zh: "信息",
        tw: "資訊",
        ko: "인포메이션",
        vi: "thông tin",
        th: "ข้อมูล",
        my: "သတင်းအချက်အလက်",
        km: "ពត៌មាន",
      },
      furigana: [
        {
          rb: "インフォメーション",
          rt: "インフォメーション",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 374,
      kanji: "インフレ",
      reading: "インフレ",
      meanings: {
        ja: "インフレ",
        en: "inflation",
        zh: "通货膨胀",
        tw: "通貨膨脹",
        ko: "인플레이션",
        vi: "lạm phát",
        th: "เงินเฟ้อ",
        my: "ငွေတန်ဖိုးကျဆင်းမှု",
        km: "អតិផរណា",
      },
      furigana: [
        {
          rb: "インフレ",
          rt: "インフレ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 375,
      kanji: "受け入れ",
      reading: "うけいれ",
      meanings: {
        ja: "受け入れ",
        en: "acceptance",
        zh: "接受",
        tw: "接受",
        ko: "수용",
        vi: "chấp nhận",
        th: "การยอมรับ",
        my: "လက်ခံခြင်း",
        km: "ការទទួល",
      },
      furigana: [
        {
          rb: "受け入れ",
          rt: "うけいれ",
        },
      ],
      kanjiInfo: [
        {
          char: "受",
          on: ["ジュ"],
          kun: ["う.ける", "-う.け", "う.かる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 376,
      kanji: "受身",
      reading: "うけみ",
      meanings: {
        ja: "受身",
        en: "passive form",
        zh: "被动式",
        tw: "被動式",
        ko: "수동태",
        vi: "thể bị động",
        th: "รูปถูกกระทำ",
        my: "ခံစားပုံ",
        km: "ទម្រង់ទទួល",
      },
      furigana: [
        {
          rb: "受身",
          rt: "うけみ",
        },
      ],
      kanjiInfo: [
        {
          char: "受",
          on: ["ジュ"],
          kun: ["う.ける", "-う.け", "う.かる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "身",
          on: ["シン"],
          kun: ["み"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 377,
      kanji: "受持ち",
      reading: "うけもち",
      meanings: {
        ja: "受持ち",
        en: "in charge",
        zh: "负责",
        tw: "負責",
        ko: "담당",
        vi: "phụ trách",
        th: "รับผิดชอบ",
        my: "တာဝန်ယူခြင်း",
        km: "ទទួលខុសត្រូវ",
      },
      furigana: [
        {
          rb: "受持ち",
          rt: "うけもち",
        },
      ],
      kanjiInfo: [
        {
          char: "受",
          on: ["ジュ"],
          kun: ["う.ける", "-う.け", "う.かる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "持",
          on: ["ジ"],
          kun: ["も.つ", "-も.ち", "も.てる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 378,
      kanji: "動き",
      reading: "うごき",
      meanings: {
        ja: "動き",
        en: "movement",
        zh: "动向",
        tw: "動向",
        ko: "움직임",
        vi: "chuyển động",
        th: "การเคลื่อนไหว",
        my: "ရွေ့လျားမှု",
        km: "ចលនា",
      },
      furigana: [
        {
          rb: "動き",
          rt: "うごき",
        },
      ],
      kanjiInfo: [
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 379,
      kanji: "嘘つき",
      reading: "うそつき",
      meanings: {
        ja: "嘘つき",
        en: "liar",
        zh: "骗子",
        tw: "騙子",
        ko: "거짓말쟁이",
        vi: "kẻ nói dối",
        th: "คนโกหก",
        my: "အတုပြောသူ",
        km: "អ្នកកុហក",
      },
      furigana: [
        {
          rb: "嘘つき",
          rt: "うそつき",
        },
      ],
      kanjiInfo: [
        {
          char: "嘘",
          on: ["キョ", "コ"],
          kun: ["うそ", "ふ.く"],
          strokes: 14,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 380,
      kanji: "うたた寝",
      reading: "うたたね",
      meanings: {
        ja: "うたた寝",
        en: "doze; nap",
        zh: "打盹",
        tw: "打盹",
        ko: "선잠",
        vi: "ngủ gật",
        th: "งีบหลับ",
        my: "အိပ်ငိုက်ခြင်း",
        km: "ងងុយដេក",
      },
      furigana: [
        {
          rb: "うたた寝",
          rt: "うたたね",
        },
      ],
      kanjiInfo: [
        {
          char: "寝",
          on: ["シン"],
          kun: ["ね.る", "ね.かす", "い.ぬ", "みたまや", "や.める"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 381,
      kanji: "打ち消し",
      reading: "うちけし",
      meanings: {
        ja: "打ち消し",
        en: "negation",
        zh: "否定",
        tw: "否定",
        ko: "부정",
        vi: "phủ định",
        th: "การปฏิเสธ",
        my: "ငြင်းပယ်ခြင်း",
        km: "ការផ្ទុយ",
      },
      furigana: [
        {
          rb: "打ち消し",
          rt: "うちけし",
        },
      ],
      kanjiInfo: [
        {
          char: "打",
          on: ["ダ", "ダース"],
          kun: ["う.つ", "う.ち-", "ぶ.つ"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "消",
          on: ["ショウ"],
          kun: ["き.える", "け.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 382,
      kanji: "団扇",
      reading: "うちわ",
      meanings: {
        ja: "団扇",
        en: "fan (uchiwa)",
        zh: "团扇",
        tw: "團扇",
        ko: "부채",
        vi: "quạt giấy",
        th: "พัดญี่ปุ่น",
        my: "လက်ပန်",
        km: "កង្ហារ",
      },
      furigana: [
        {
          rb: "団扇",
          rt: "うちわ",
        },
      ],
      kanjiInfo: [
        {
          char: "団",
          on: ["ダン", "トン"],
          kun: ["かたまり", "まる.い"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "扇",
          on: ["セン"],
          kun: ["おうぎ"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 383,
      kanji: "内訳",
      reading: "うちわけ",
      meanings: {
        ja: "内訳",
        en: "itemization",
        zh: "明细",
        tw: "明細",
        ko: "내역",
        vi: "chi tiết",
        th: "รายละเอียด",
        my: "အသေးစိတ်",
        km: "សេចក្តីលម្អិត",
      },
      furigana: [
        {
          rb: "内訳",
          rt: "うちわけ",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "訳",
          on: ["ヤク"],
          kun: ["わけ"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 384,
      kanji: "写し",
      reading: "うつし",
      meanings: {
        ja: "写し",
        en: "copy",
        zh: "副本",
        tw: "副本",
        ko: "사본",
        vi: "bản sao",
        th: "สำเนา",
        my: "အတု",
        km: "ច្បាប់ចម្លង",
      },
      furigana: [
        {
          rb: "写し",
          rt: "うつし",
        },
      ],
      kanjiInfo: [
        {
          char: "写",
          on: ["シャ", "ジャ"],
          kun: ["うつ.す", "うつ.る", "うつ-", "うつ.し"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 385,
      kanji: "訴え",
      reading: "うったえ",
      meanings: {
        ja: "訴え",
        en: "lawsuit",
        zh: "诉讼",
        tw: "訴訟",
        ko: "소송",
        vi: "vụ kiện",
        th: "การฟ้องร้อง",
        my: "တရားစွဲမှု",
        km: "ការក្ដី",
      },
      furigana: [
        {
          rb: "訴え",
          rt: "うったえ",
        },
      ],
      kanjiInfo: [
        {
          char: "訴",
          on: ["ソ"],
          kun: ["うった.える"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 386,
      kanji: "空ろ",
      reading: "うつろ",
      meanings: {
        ja: "空ろ",
        en: "hollow; vacant",
        zh: "空洞",
        tw: "空洞",
        ko: "텅빈",
        vi: "trống rỗng",
        th: "ว่างเปล่า",
        my: "အလွတ်",
        km: "ទទេ",
      },
      furigana: [
        {
          rb: "空ろ",
          rt: "うつろ",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 387,
      kanji: "器",
      reading: "うつわ",
      meanings: {
        ja: "器",
        en: "container; bowl",
        zh: "容器",
        tw: "容器",
        ko: "그릇",
        vi: "bát; vật chứa",
        th: "ภาชนะ",
        my: "အိုးအိမ်",
        km: "បំពង់",
      },
      furigana: [
        {
          rb: "器",
          rt: "うつわ",
        },
      ],
      kanjiInfo: [
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 388,
      kanji: "腕前",
      reading: "うでまえ",
      meanings: {
        ja: "腕前",
        en: "skill; ability",
        zh: "本领",
        tw: "本領",
        ko: "솜씨",
        vi: "tay nghề",
        th: "ฝีมือ",
        my: "အရည်အသွေး",
        km: "សមត្ថភាព",
      },
      furigana: [
        {
          rb: "腕前",
          rt: "うでまえ",
        },
      ],
      kanjiInfo: [
        {
          char: "腕",
          on: ["ワン"],
          kun: ["うで"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 389,
      kanji: "雨天",
      reading: "うてん",
      meanings: {
        ja: "雨天",
        en: "rainy weather",
        zh: "雨天",
        tw: "雨天",
        ko: "우천",
        vi: "trời mưa",
        th: "สภาพอากาศฝนตก",
        my: "မိုးရက်",
        km: "ថ្ងៃភ្លៀង",
      },
      furigana: [
        {
          rb: "雨天",
          rt: "うてん",
        },
      ],
      kanjiInfo: [
        {
          char: "雨",
          on: ["ウ"],
          kun: ["あめ", "あま-", "-さめ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "天",
          on: ["テン"],
          kun: ["あまつ", "あめ", "あま-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 390,
      kanji: "梅干し",
      reading: "うめぼし",
      meanings: {
        ja: "梅干し",
        en: "umeboshi (pickled plum)",
        zh: "梅干",
        tw: "梅乾",
        ko: "우메보시(절임자두)",
        vi: "mơ muối (umeboshi)",
        th: "บ๊วยดองญี่ปุ่น",
        my: "အမဲဘောစီချဴ",
        km: "ប៉េងប៉ោះជូរ(ប៊ូយដងជប៉ុន)",
      },
      furigana: [
        {
          rb: "梅干し",
          rt: "うめぼし",
        },
      ],
      kanjiInfo: [
        {
          char: "梅",
          on: ["バイ"],
          kun: ["うめ"],
          strokes: 10,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
        {
          char: "干",
          on: ["カン"],
          kun: ["ほ.す", "ほ.し-", "-ぼ.し", "ひ.る"],
          strokes: 3,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 391,
      kanji: "裏返し",
      reading: "うらがえし",
      meanings: {
        ja: "裏返し",
        en: "inside out; upside down",
        zh: "翻里朝外；颠倒",
        tw: "翻面；顛倒",
        ko: "뒤집힘",
        vi: "lộn trái; lật ngược",
        th: "กลับด้าน/กลับในออก",
        my: "ထပ်ပြီးပြောင်းပြန်လုပ်ခြင်း",
        km: "ត្រឡប់ខ្នង",
      },
      furigana: [
        {
          rb: "裏返し",
          rt: "うらがえし",
        },
      ],
      kanjiInfo: [
        {
          char: "裏",
          on: ["リ"],
          kun: ["うら"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "返",
          on: ["ヘン"],
          kun: ["かえ.す", "-かえ.す", "かえ.る", "-かえ.る"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 392,
      kanji: "売り出し",
      reading: "うりだし",
      meanings: {
        ja: "売り出し",
        en: "bargain sale; launching (product)",
        zh: "特卖；推出",
        tw: "特賣；推出",
        ko: "세일; 출시",
        vi: "đợt giảm giá; tung ra",
        th: "การลดราคา; เปิดตัวสินค้า",
        my: "စျေးအားလုံးလျှော့ချရောင်း",
        km: "លក់បញ្ចុះតម្លៃ; ចេញផលិតផល",
      },
      furigana: [
        {
          rb: "売り出し",
          rt: "うりだし",
        },
      ],
      kanjiInfo: [
        {
          char: "売",
          on: ["バイ"],
          kun: ["う.る", "う.れる"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 393,
      kanji: "浮気",
      reading: "うわき",
      meanings: {
        ja: "浮気",
        en: "cheating; unfaithfulness",
        zh: "出轨；花心",
        tw: "劈腿；花心",
        ko: "바람; 외도",
        vi: "ngoại tình",
        th: "นอกใจ",
        my: "ဖောက်ပြန်ခြင်း",
        km: "ក្បត់",
      },
      furigana: [
        {
          rb: "浮気",
          rt: "うわき",
        },
      ],
      kanjiInfo: [
        {
          char: "浮",
          on: ["フ"],
          kun: ["う.く", "う.かれる", "う.かぶ", "う.かべる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 394,
      kanji: "運営",
      reading: "うんえい",
      meanings: {
        ja: "運営",
        en: "operation; management",
        zh: "运营；经营",
        tw: "營運；經營",
        ko: "운영",
        vi: "vận hành; quản lý",
        th: "การบริหารจัดการ",
        my: "စီမံခန့်ခွဲမှု",
        km: "ការគ្រប់គ្រងដំណើរការ",
      },
      furigana: [
        {
          rb: "運営",
          rt: "うんえい",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "営",
          on: ["エイ"],
          kun: ["いとな.む", "いとな.み"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 395,
      kanji: "運送",
      reading: "うんそう",
      meanings: {
        ja: "運送",
        en: "transport; freight",
        zh: "运输",
        tw: "運送",
        ko: "운송",
        vi: "vận chuyển",
        th: "การขนส่ง",
        my: "ပို့ဆောင်ရေး",
        km: "ដឹកជញ្ជូន",
      },
      furigana: [
        {
          rb: "運送",
          rt: "うんそう",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "送",
          on: ["ソウ"],
          kun: ["おく.る"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 396,
      kanji: "運賃",
      reading: "うんちん",
      meanings: {
        ja: "運賃",
        en: "fare (passenger)",
        zh: "车/船费",
        tw: "運費（乘客票價）",
        ko: "운임(승차요금)",
        vi: "cước phí (vé đi lại)",
        th: "ค่าโดยสาร",
        my: "ခရီးကြေး",
        km: "ថ្លៃដំណើរ",
      },
      furigana: [
        {
          rb: "運賃",
          rt: "うんちん",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "賃",
          on: ["チン"],
          kun: [],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 397,
      kanji: "運搬",
      reading: "うんぱん",
      meanings: {
        ja: "運搬",
        en: "transport; carriage",
        zh: "搬运",
        tw: "運搬",
        ko: "운반",
        vi: "vận tải; khuân vác",
        th: "การขนย้าย",
        my: "တင်ပို့ခြင်း",
        km: "ដឹកយក",
      },
      furigana: [
        {
          rb: "運搬",
          rt: "うんぱん",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "搬",
          on: ["ハン"],
          kun: [],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 398,
      kanji: "運命",
      reading: "うんめい",
      meanings: {
        ja: "運命",
        en: "fate; destiny",
        zh: "命运",
        tw: "命運",
        ko: "운명",
        vi: "định mệnh",
        th: "ชะตากรรม",
        my: "ကံကြမ္မာ",
        km: "វាសនា",
      },
      furigana: [
        {
          rb: "運命",
          rt: "うんめい",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 399,
      kanji: "運輸",
      reading: "うんゆ",
      meanings: {
        ja: "運輸",
        en: "transportation (industry)",
        zh: "运输业",
        tw: "運輸",
        ko: "운수(운송업)",
        vi: "ngành vận tải",
        th: "การคมนาคมขนส่ง",
        my: "ပို့ဆောင်ရေးလုပ်ငန်း",
        km: "វិស័យដឹកជញ្ជូន",
      },
      furigana: [
        {
          rb: "運輸",
          rt: "うんゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "輸",
          on: ["ユ", "シュ"],
          kun: [],
          strokes: 16,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 400,
      kanji: "運用",
      reading: "うんよう",
      meanings: {
        ja: "運用",
        en: "utilization; operation",
        zh: "运用；运营",
        tw: "運用；營運",
        ko: "운용",
        vi: "vận dụng; vận hành",
        th: "การใช้งาน/บริหาร",
        my: "အသုံးချခြင်း",
        km: "ការប្រើប្រាស់; ដំណើរការ",
      },
      furigana: [
        {
          rb: "運用",
          rt: "うんよう",
        },
      ],
      kanjiInfo: [
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
