export const n1part20 = {
  Lesson20: [
    {
      id: 951,
      kanji: "ストロボ",
      reading: "ストロボ",
      meanings: {
        ja: "ストロボ",
        en: "strobe light",
        zh: "频闪灯",
        tw: "閃光燈",
        ko: "스트로보",
        vi: "đèn nháy",
        th: "ไฟแฟลช",
        my: "ဖလက်မီး",
        km: "ពន្លឺផ្លឹប",
      },
      furigana: [
        {
          rb: "ストロボ",
          rt: "ストロボ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 952,
      kanji: "スプリング",
      reading: "スプリング",
      meanings: {
        ja: "スプリング",
        en: "spring (coil)",
        zh: "弹簧",
        tw: "彈簧",
        ko: "스프링",
        vi: "lò xo",
        th: "สปริง",
        my: "နွေဦး",
        km: "និទាឃរដូវ",
      },
      furigana: [
        {
          rb: "スプリング",
          rt: "スプリング",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 953,
      kanji: "スペース",
      reading: "スペース",
      meanings: {
        ja: "スペース",
        en: "space",
        zh: "空间",
        tw: "空間",
        ko: "스페이스",
        vi: "không gian",
        th: "พื้นที่",
        my: "နေရာ",
        km: "ទីទំនេរ",
      },
      furigana: [
        {
          rb: "スペース",
          rt: "スペース",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 954,
      kanji: "スポーツカー",
      reading: "スポーツカー",
      meanings: {
        ja: "スポーツカー",
        en: "sports car",
        zh: "跑车",
        tw: "跑車",
        ko: "스포츠카",
        vi: "xe thể thao",
        th: "รถสปอร์ต",
        my: "အားကစားကား",
        km: "ឡានកីឡា",
      },
      furigana: [
        {
          rb: "スポーツカー",
          rt: "スポーツカー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 955,
      kanji: "スラックス",
      reading: "スラックス",
      meanings: {
        ja: "スラックス",
        en: "slacks",
        zh: "休闲裤",
        tw: "西裝褲",
        ko: "슬랙스",
        vi: "quần tây",
        th: "กางเกงสแล็ค",
        my: "ဘောင်းဘီ",
        km: "ខោវែង",
      },
      furigana: [
        {
          rb: "スラックス",
          rt: "スラックス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 956,
      kanji: "ずれ",
      reading: "ずれ",
      meanings: {
        ja: "ずれ",
        en: "gap; deviation",
        zh: "偏差",
        tw: "偏差",
        ko: "어긋남",
        vi: "sai lệch",
        th: "ช่องว่าง",
        my: "လျော့နည်းခြင်း",
        km: "ការខុសគ្នា",
      },
      furigana: [
        {
          rb: "ずれ",
          rt: "ずれ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 957,
      kanji: "生育",
      reading: "せいいく",
      meanings: {
        ja: "生育",
        en: "growth; development",
        zh: "生长",
        tw: "生育",
        ko: "생육",
        vi: "sinh trưởng",
        th: "การเจริญเติบโต",
        my: "အဆင့်တိုးတက်မှု",
        km: "ការលូតលាស់",
      },
      furigana: [
        {
          rb: "生育",
          rt: "せいいく",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "育",
          on: ["イク"],
          kun: ["そだ.つ", "そだ.ち", "そだ.てる", "はぐく.む"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 958,
      kanji: "成育",
      reading: "せいいく",
      meanings: {
        ja: "成育",
        en: "growth to maturity",
        zh: "成长",
        tw: "成長",
        ko: "성육",
        vi: "trưởng thành",
        th: "การเติบโต",
        my: "ကြီးပြင်းခြင်း",
        km: "ការលូតលាស់",
      },
      furigana: [
        {
          rb: "成育",
          rt: "せいいく",
        },
      ],
      kanjiInfo: [
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "育",
          on: ["イク"],
          kun: ["そだ.つ", "そだ.ち", "そだ.てる", "はぐく.む"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 959,
      kanji: "成果",
      reading: "せいか",
      meanings: {
        ja: "成果",
        en: "result; achievement",
        zh: "成果",
        tw: "成果",
        ko: "성과",
        vi: "thành quả",
        th: "ผลลัพธ์",
        my: "အောင်မြင်မှု",
        km: "លទ្ធផល",
      },
      furigana: [
        {
          rb: "成果",
          rt: "せいか",
        },
      ],
      kanjiInfo: [
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "果",
          on: ["カ"],
          kun: [
            "は.たす",
            "はた.す",
            "-は.たす",
            "は.てる",
            "-は.てる",
            "は.て",
          ],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 960,
      kanji: "正解",
      reading: "せいかい",
      meanings: {
        ja: "正解",
        en: "correct answer",
        zh: "正确答案",
        tw: "正確答案",
        ko: "정답",
        vi: "đáp án đúng",
        th: "คำตอบที่ถูกต้อง",
        my: "ဖြေဖြူးမှန်ကန်ခြင်း",
        km: "ចម្លើយត្រឹមត្រូវ",
      },
      furigana: [
        {
          rb: "正解",
          rt: "せいかい",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 961,
      kanji: "正義",
      reading: "せいぎ",
      meanings: {
        ja: "正義",
        en: "justice",
        zh: "正义",
        tw: "正義",
        ko: "정의",
        vi: "chính nghĩa",
        th: "ความยุติธรรม",
        my: "တရားမျှတမှု",
        km: "យុត្តិធម៌",
      },
      furigana: [
        {
          rb: "正義",
          rt: "せいぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "義",
          on: ["ギ"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 962,
      kanji: "生計",
      reading: "せいけい",
      meanings: {
        ja: "生計",
        en: "livelihood",
        zh: "生计",
        tw: "生計",
        ko: "생계",
        vi: "kế sinh nhai",
        th: "การดำรงชีพ",
        my: "အသက်မွေးမှု",
        km: "ជីវភាពរស់នៅ",
      },
      furigana: [
        {
          rb: "生計",
          rt: "せいけい",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "計",
          on: ["ケイ"],
          kun: ["はか.る", "はか.らう"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 963,
      kanji: "政権",
      reading: "せいけん",
      meanings: {
        ja: "政権",
        en: "political power",
        zh: "政权",
        tw: "政權",
        ko: "정권",
        vi: "chính quyền",
        th: "รัฐบาล",
        my: "အာဏာပိုင်",
        km: "អំណាចនយោបាយ",
      },
      furigana: [
        {
          rb: "政権",
          rt: "せいけん",
        },
      ],
      kanjiInfo: [
        {
          char: "政",
          on: ["セイ", "ショウ"],
          kun: ["まつりごと", "まん"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "権",
          on: ["ケン", "ゴン"],
          kun: ["おもり", "かり", "はか.る"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 964,
      kanji: "星座",
      reading: "せいざ",
      meanings: {
        ja: "星座",
        en: "constellation",
        zh: "星座",
        tw: "星座",
        ko: "별자리",
        vi: "chòm sao",
        th: "ราศี",
        my: "နက္ခတ်",
        km: "រូបសញ្ញារបស់តារា",
      },
      furigana: [
        {
          rb: "星座",
          rt: "せいざ",
        },
      ],
      kanjiInfo: [
        {
          char: "星",
          on: ["セイ", "ショウ"],
          kun: ["ほし", "-ぼし"],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "座",
          on: ["ザ"],
          kun: ["すわ.る"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 965,
      kanji: "制裁",
      reading: "せいさい",
      meanings: {
        ja: "制裁",
        en: "sanction",
        zh: "制裁",
        tw: "制裁",
        ko: "제재",
        vi: "trừng phạt",
        th: "การลงโทษ",
        my: "ပြစ်မှုအပေါ်အရေးယူခြင်း",
        km: "ទណ្ឌកម្ម",
      },
      furigana: [
        {
          rb: "制裁",
          rt: "せいさい",
        },
      ],
      kanjiInfo: [
        {
          char: "制",
          on: ["セイ"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "裁",
          on: ["サイ"],
          kun: ["た.つ", "さば.く"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 966,
      kanji: "政策",
      reading: "せいさく",
      meanings: {
        ja: "政策",
        en: "policy",
        zh: "政策",
        tw: "政策",
        ko: "정책",
        vi: "chính sách",
        th: "นโยบาย",
        my: "မူဝါဒ",
        km: "គោលនយោបាយ",
      },
      furigana: [
        {
          rb: "政策",
          rt: "せいさく",
        },
      ],
      kanjiInfo: [
        {
          char: "政",
          on: ["セイ", "ショウ"],
          kun: ["まつりごと", "まん"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "策",
          on: ["サク"],
          kun: [],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 967,
      kanji: "生死",
      reading: "せいし",
      meanings: {
        ja: "生死",
        en: "life and death",
        zh: "生死",
        tw: "生死",
        ko: "생사",
        vi: "sinh tử",
        th: "ชีวิตและความตาย",
        my: "အသက်ရှင်မှုနှင့်သေခြင်း",
        km: "ជីវិតនិងសេចក្ដីស្លាប់",
      },
      furigana: [
        {
          rb: "生死",
          rt: "せいし",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "死",
          on: ["シ"],
          kun: ["し.ぬ", "し.に-"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 968,
      kanji: "静止",
      reading: "せいし",
      meanings: {
        ja: "静止",
        en: "stillness",
        zh: "静止",
        tw: "靜止",
        ko: "정지",
        vi: "đứng yên",
        th: "นิ่ง",
        my: "တိတ်ဆိတ်မှု",
        km: "ស្ងប់ស្ងាត់",
      },
      furigana: [
        {
          rb: "静止",
          rt: "せいし",
        },
      ],
      kanjiInfo: [
        {
          char: "静",
          on: ["セイ", "ジョウ"],
          kun: ["しず-", "しず.か", "しず.まる", "しず.める"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "止",
          on: ["シ"],
          kun: [
            "と.まる",
            "-ど.まり",
            "と.める",
            "-と.める",
            "-ど.め",
            "とど.める",
            "とど.め",
            "とど.まる",
            "や.める",
            "や.む",
            "-や.む",
            "よ.す",
            "-さ.す",
            "-さ.し",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 969,
      kanji: "成熟",
      reading: "せいじゅく",
      meanings: {
        ja: "成熟",
        en: "maturity",
        zh: "成熟",
        tw: "成熟",
        ko: "성숙",
        vi: "trưởng thành",
        th: "ความเป็นผู้ใหญ่",
        my: "အရွယ်ရောက်ခြင်း",
        km: "ភាពចាស់ទុំ",
      },
      furigana: [
        {
          rb: "成熟",
          rt: "せいじゅく",
        },
      ],
      kanjiInfo: [
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "熟",
          on: ["ジュク"],
          kun: ["う.れる"],
          strokes: 15,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 970,
      kanji: "青春",
      reading: "せいしゅん",
      meanings: {
        ja: "青春",
        en: "youth",
        zh: "青春",
        tw: "青春",
        ko: "청춘",
        vi: "tuổi trẻ",
        th: "วัยหนุ่มสาว",
        my: "လူငယ်အရွယ်",
        km: "យុវវ័យ",
      },
      furigana: [
        {
          rb: "青春",
          rt: "せいしゅん",
        },
      ],
      kanjiInfo: [
        {
          char: "青",
          on: ["セイ", "ショウ"],
          kun: ["あお", "あお-", "あお.い"],
          strokes: 8,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "春",
          on: ["シュン"],
          kun: ["はる"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 971,
      kanji: "聖書",
      reading: "せいしょ",
      meanings: {
        ja: "聖書",
        en: "Bible",
        zh: "圣经",
        tw: "聖經",
        ko: "성경",
        vi: "Kinh Thánh",
        th: "คัมภีร์ไบเบิล",
        my: "သမ္မာကျမ်း",
        km: "ព្រះគម្ពីរ",
      },
      furigana: [
        {
          rb: "聖書",
          rt: "せいしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "聖",
          on: ["セイ", "ショウ"],
          kun: ["ひじり"],
          strokes: 13,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 972,
      kanji: "盛装",
      reading: "せいそう",
      meanings: {
        ja: "盛装",
        en: "dressing up",
        zh: "盛装",
        tw: "盛裝",
        ko: "성장",
        vi: "ăn mặc chỉnh tề",
        th: "แต่งกายหรูหรา",
        my: "အလှအပတင်ဆင်မှု",
        km: "សម្លៀកបំពាក់ស្អាតៗ",
      },
      furigana: [
        {
          rb: "盛装",
          rt: "せいそう",
        },
      ],
      kanjiInfo: [
        {
          char: "盛",
          on: ["セイ", "ジョウ"],
          kun: ["も.る", "さか.る", "さか.ん"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "装",
          on: ["ソウ", "ショウ"],
          kun: ["よそお.う", "よそお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 973,
      kanji: "清濁",
      reading: "せいだく",
      meanings: {
        ja: "清濁",
        en: "good and evil",
        zh: "清浊",
        tw: "清濁",
        ko: "청탁",
        vi: "thiện và ác",
        th: "ดีและชั่ว",
        my: "ကောင်းခြင်းနဲ့ဆိုးခြင်း",
        km: "ល្អនិងអាក្រក់",
      },
      furigana: [
        {
          rb: "清濁",
          rt: "せいだく",
        },
      ],
      kanjiInfo: [
        {
          char: "清",
          on: ["セイ", "ショウ", "シン"],
          kun: ["きよ.い", "きよ.まる", "きよ.める"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "濁",
          on: ["ダク", "ジョク"],
          kun: ["にご.る", "にご.す"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 974,
      kanji: "制定",
      reading: "せいてい",
      meanings: {
        ja: "制定",
        en: "enactment",
        zh: "制定",
        tw: "制定",
        ko: "제정",
        vi: "ban hành",
        th: "การตรากฎหมาย",
        my: "ဥပဒေထုတ်ခြင်း",
        km: "ការចេញច្បាប់",
      },
      furigana: [
        {
          rb: "制定",
          rt: "せいてい",
        },
      ],
      kanjiInfo: [
        {
          char: "制",
          on: ["セイ"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 975,
      kanji: "製鉄",
      reading: "せいてつ",
      meanings: {
        ja: "製鉄",
        en: "iron manufacturing",
        zh: "炼铁",
        tw: "煉鐵",
        ko: "제철",
        vi: "luyện thép",
        th: "การผลิตเหล็ก",
        my: "သံဖြူထုတ်လုပ်ခြင်း",
        km: "ផលិតដែក",
      },
      furigana: [
        {
          rb: "製鉄",
          rt: "せいてつ",
        },
      ],
      kanjiInfo: [
        {
          char: "製",
          on: ["セイ"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "鉄",
          on: ["テツ"],
          kun: ["くろがね"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 976,
      kanji: "晴天",
      reading: "せいてん",
      meanings: {
        ja: "晴天",
        en: "clear weather",
        zh: "晴天",
        tw: "晴天",
        ko: "맑은 날",
        vi: "trời quang",
        th: "อากาศแจ่มใส",
        my: "အပူရှည်နေ့",
        km: "ថ្ងៃមានព្រះអាទិត្យ",
      },
      furigana: [
        {
          rb: "晴天",
          rt: "せいてん",
        },
      ],
      kanjiInfo: [
        {
          char: "晴",
          on: ["セイ"],
          kun: ["は.れる", "は.れ", "は.れ-", "-ば.れ", "は.らす"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "天",
          on: ["テン"],
          kun: ["あまつ", "あめ", "あま-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 977,
      kanji: "制服",
      reading: "せいふく",
      meanings: {
        ja: "制服",
        en: "uniform",
        zh: "制服",
        tw: "制服",
        ko: "제복",
        vi: "đồng phục",
        th: "เครื่องแบบ",
        my: "အသားတင်",
        km: "ឯកសណ្ឋាន",
      },
      furigana: [
        {
          rb: "制服",
          rt: "せいふく",
        },
      ],
      kanjiInfo: [
        {
          char: "制",
          on: ["セイ"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "服",
          on: ["フク"],
          kun: [],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 978,
      kanji: "征服",
      reading: "せいふく",
      meanings: {
        ja: "征服",
        en: "conquest",
        zh: "征服",
        tw: "征服",
        ko: "정복",
        vi: "chinh phục",
        th: "การพิชิต",
        my: "အနိုင်ယူခြင်း",
        km: "ការឈ្នះ",
      },
      furigana: [
        {
          rb: "征服",
          rt: "せいふく",
        },
      ],
      kanjiInfo: [
        {
          char: "征",
          on: ["セイ"],
          kun: [],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "服",
          on: ["フク"],
          kun: [],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 979,
      kanji: "製法",
      reading: "せいほう",
      meanings: {
        ja: "製法",
        en: "manufacturing method",
        zh: "制造方法",
        tw: "製法",
        ko: "제법",
        vi: "phương pháp sản xuất",
        th: "วิธีการผลิต",
        my: "ထုတ်လုပ်နည်းလမ်း",
        km: "វិធីផលិត",
      },
      furigana: [
        {
          rb: "製法",
          rt: "せいほう",
        },
      ],
      kanjiInfo: [
        {
          char: "製",
          on: ["セイ"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "法",
          on: ["ホウ", "ハッ", "ホッ", "フラン"],
          kun: ["のり"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 980,
      kanji: "税務署",
      reading: "ぜいむしょ",
      meanings: {
        ja: "税務署",
        en: "tax office",
        zh: "税务局",
        tw: "稅務局",
        ko: "세무서",
        vi: "sở thuế",
        th: "สำนักงานสรรพากร",
        my: "အခွန်ဌာန",
        km: "ការិយាល័យពន្ធ",
      },
      furigana: [
        {
          rb: "税務署",
          rt: "ぜいむしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "税",
          on: ["ゼイ"],
          kun: [],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "務",
          on: ["ム"],
          kun: ["つと.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "署",
          on: ["ショ"],
          kun: [],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 981,
      kanji: "制約",
      reading: "せいやく",
      meanings: {
        ja: "制約",
        en: "restriction; limitation",
        zh: "制约",
        tw: "制約",
        ko: "제약",
        vi: "hạn chế",
        th: "ข้อจำกัด",
        my: "ကန့်သတ်ချက်",
        km: "ការរឹតត្បិត",
      },
      furigana: [
        {
          rb: "制約",
          rt: "せいやく",
        },
      ],
      kanjiInfo: [
        {
          char: "制",
          on: ["セイ"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "約",
          on: ["ヤク"],
          kun: ["つづ.まる", "つづ.める", "つづま.やか"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 982,
      kanji: "勢力",
      reading: "せいりょく",
      meanings: {
        ja: "勢力",
        en: "influence; power",
        zh: "势力",
        tw: "勢力",
        ko: "세력",
        vi: "thế lực",
        th: "อิทธิพล",
        my: "အာဏာသုံးခြင်း",
        km: "ឥទ្ធិពល",
      },
      furigana: [
        {
          rb: "勢力",
          rt: "せいりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "勢",
          on: ["セイ", "ゼイ"],
          kun: ["いきお.い", "はずみ"],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 983,
      kanji: "整列",
      reading: "せいれつ",
      meanings: {
        ja: "整列",
        en: "lining up",
        zh: "排队",
        tw: "排隊",
        ko: "정렬",
        vi: "xếp hàng",
        th: "เข้าแถว",
        my: "အတန်းစီခြင်း",
        km: "ចុះជួរ",
      },
      furigana: [
        {
          rb: "整列",
          rt: "せいれつ",
        },
      ],
      kanjiInfo: [
        {
          char: "整",
          on: ["セイ"],
          kun: ["ととの.える", "ととの.う"],
          strokes: 16,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "列",
          on: ["レツ", "レ"],
          kun: [],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 984,
      kanji: "セール",
      reading: "セール",
      meanings: {
        ja: "セール",
        en: "sale (discount)",
        zh: "特卖",
        tw: "特賣",
        ko: "세일",
        vi: "giảm giá",
        th: "ลดราคา",
        my: "လျှော့စျေး",
        km: "ការលក់ថោក",
      },
      furigana: [
        {
          rb: "セール",
          rt: "セール",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 985,
      kanji: "伜",
      reading: "せがれ",
      meanings: {
        ja: "伜",
        en: "son (humble)",
        zh: "儿子",
        tw: "兒子",
        ko: "아들",
        vi: "con trai",
        th: "ลูกชาย",
        my: "သား",
        km: "កូនប្រុស",
      },
      furigana: [
        {
          rb: "伜",
          rt: "せがれ",
        },
      ],
      kanjiInfo: [
        {
          char: "伜",
          on: ["サイ", "ソツ", "ソチ"],
          kun: ["せがれ"],
          strokes: 6,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 986,
      kanji: "責務",
      reading: "せきむ",
      meanings: {
        ja: "責務",
        en: "duty; obligation",
        zh: "责任",
        tw: "責任",
        ko: "책무",
        vi: "nghĩa vụ",
        th: "หน้าที่",
        my: "တာဝန်",
        km: "ភារកិច្ច",
      },
      furigana: [
        {
          rb: "責務",
          rt: "せきむ",
        },
      ],
      kanjiInfo: [
        {
          char: "責",
          on: ["セキ"],
          kun: ["せ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "務",
          on: ["ム"],
          kun: ["つと.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 987,
      kanji: "セクション",
      reading: "セクション",
      meanings: {
        ja: "セクション",
        en: "section; department",
        zh: "部门",
        tw: "部門",
        ko: "섹션",
        vi: "bộ phận",
        th: "แผนก",
        my: "ဌာန",
        km: "ផ្នែក",
      },
      furigana: [
        {
          rb: "セクション",
          rt: "セクション",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 988,
      kanji: "世辞",
      reading: "せじ",
      meanings: {
        ja: "世辞",
        en: "flattery; compliment",
        zh: "奉承",
        tw: "奉承",
        ko: "아첨",
        vi: "nịnh hót",
        th: "การยกยอ",
        my: "ကျေးဇူးပြုခြင်း",
        km: "ការសរសើរពេក",
      },
      furigana: [
        {
          rb: "世辞",
          rt: "せじ",
        },
      ],
      kanjiInfo: [
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "辞",
          on: ["ジ"],
          kun: ["や.める", "いな.む"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 989,
      kanji: "世帯",
      reading: "せたい",
      meanings: {
        ja: "世帯",
        en: "household",
        zh: "家庭",
        tw: "家庭",
        ko: "세대",
        vi: "hộ gia đình",
        th: "ครอบครัว",
        my: "အိမ်ထောင်စု",
        km: "គ្រួសារ",
      },
      furigana: [
        {
          rb: "世帯",
          rt: "せたい",
        },
      ],
      kanjiInfo: [
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "帯",
          on: ["タイ"],
          kun: ["お.びる", "おび"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 990,
      kanji: "是正",
      reading: "ぜせい",
      meanings: {
        ja: "是正",
        en: "correction",
        zh: "纠正",
        tw: "糾正",
        ko: "시정",
        vi: "sửa chữa",
        th: "การแก้ไข",
        my: "ပြင်ဆင်ခြင်း",
        km: "ការកែតម្រូវ",
      },
      furigana: [
        {
          rb: "是正",
          rt: "ぜせい",
        },
      ],
      kanjiInfo: [
        {
          char: "是",
          on: ["ゼ", "シ"],
          kun: ["これ", "この", "ここ"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 991,
      kanji: "世代",
      reading: "せだい",
      meanings: {
        ja: "世代",
        en: "generation",
        zh: "世代",
        tw: "世代",
        ko: "세대",
        vi: "thế hệ",
        th: "รุ่น",
        my: "မျိုးဆက်",
        km: "ជំនាន់",
      },
      furigana: [
        {
          rb: "世代",
          rt: "せだい",
        },
      ],
      kanjiInfo: [
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 992,
      kanji: "切開",
      reading: "せっかい",
      meanings: {
        ja: "切開",
        en: "incision; cut",
        zh: "切开",
        tw: "切開",
        ko: "절개",
        vi: "rạch",
        th: "การผ่า",
        my: "အဖြတ်",
        km: "ការកាត់",
      },
      furigana: [
        {
          rb: "切開",
          rt: "せっかい",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 993,
      kanji: "セックス",
      reading: "セックス",
      meanings: {
        ja: "セックス",
        en: "sex",
        zh: "性行为",
        tw: "性行為",
        ko: "섹스",
        vi: "quan hệ tình dục",
        th: "เพศสัมพันธ์",
        my: "လိင်ဆက်ဆံရေး",
        km: "ការរួមភេទ",
      },
      furigana: [
        {
          rb: "セックス",
          rt: "セックス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 994,
      kanji: "接触",
      reading: "せっしょく",
      meanings: {
        ja: "接触",
        en: "contact",
        zh: "接触",
        tw: "接觸",
        ko: "접촉",
        vi: "tiếp xúc",
        th: "การสัมผัส",
        my: "ထိတွေ့ခြင်း",
        km: "ការប៉ះពាល់",
      },
      furigana: [
        {
          rb: "接触",
          rt: "せっしょく",
        },
      ],
      kanjiInfo: [
        {
          char: "接",
          on: ["セツ", "ショウ"],
          kun: ["つ.ぐ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "触",
          on: ["ショク"],
          kun: ["ふ.れる", "さわ.る", "さわ"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 995,
      kanji: "接続詞",
      reading: "せつぞくし",
      meanings: {
        ja: "接続詞",
        en: "conjunction",
        zh: "连接词",
        tw: "連接詞",
        ko: "접속사",
        vi: "liên từ",
        th: "คำเชื่อม",
        my: "ဆက်စပ်ဝါကျ",
        km: "ពាក្យតភ្ជាប់",
      },
      furigana: [
        {
          rb: "接続詞",
          rt: "せつぞくし",
        },
      ],
      kanjiInfo: [
        {
          char: "接",
          on: ["セツ", "ショウ"],
          kun: ["つ.ぐ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 996,
      kanji: "設置",
      reading: "せっち",
      meanings: {
        ja: "設置",
        en: "establishment",
        zh: "设置",
        tw: "設置",
        ko: "설치",
        vi: "lắp đặt",
        th: "ติดตั้ง",
        my: "တပ်ဆင်ခြင်း",
        km: "ដំឡើង",
      },
      furigana: [
        {
          rb: "設置",
          rt: "せっち",
        },
      ],
      kanjiInfo: [
        {
          char: "設",
          on: ["セツ"],
          kun: ["もう.ける"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "置",
          on: ["チ"],
          kun: ["お.く", "-お.き"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 997,
      kanji: "折衷",
      reading: "せっちゅう",
      meanings: {
        ja: "折衷",
        en: "compromise",
        zh: "折衷",
        tw: "折衷",
        ko: "절충",
        vi: "thoả hiệp",
        th: "ประนีประนอม",
        my: "အကြံတူညီခြင်း",
        km: "សម្របសម្រួល",
      },
      furigana: [
        {
          rb: "折衷",
          rt: "せっちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "折",
          on: ["セツ", "シャク"],
          kun: ["お.る", "おり", "お.り", "-お.り", "お.れる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "衷",
          on: ["チュウ"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 998,
      kanji: "設定",
      reading: "せってい",
      meanings: {
        ja: "設定",
        en: "setting; configuration",
        zh: "设定",
        tw: "設定",
        ko: "설정",
        vi: "cài đặt",
        th: "การตั้งค่า",
        my: "သတ်မှတ်ခြင်း",
        km: "ការកំណត់",
      },
      furigana: [
        {
          rb: "設定",
          rt: "せってい",
        },
      ],
      kanjiInfo: [
        {
          char: "設",
          on: ["セツ"],
          kun: ["もう.ける"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 999,
      kanji: "説得",
      reading: "せっとく",
      meanings: {
        ja: "説得",
        en: "persuasion",
        zh: "说服",
        tw: "說服",
        ko: "설득",
        vi: "thuyết phục",
        th: "การชักชวน",
        my: "နားလည်အောင်ပြောခြင်း",
        km: "ការឆ្លើយបញ្ចុះបញ្ចូល",
      },
      furigana: [
        {
          rb: "説得",
          rt: "せっとく",
        },
      ],
      kanjiInfo: [
        {
          char: "説",
          on: ["セツ", "ゼイ"],
          kun: ["と.く"],
          strokes: 14,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "得",
          on: ["トク"],
          kun: ["え.る", "う.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1000,
      kanji: "絶版",
      reading: "ぜっぱん",
      meanings: {
        ja: "絶版",
        en: "out of print",
        zh: "绝版",
        tw: "絕版",
        ko: "절판",
        vi: "ngừng xuất bản",
        th: "เลิกพิมพ์",
        my: "ထုတ်ပေးမှုရပ်ဆိုင်းခြင်း",
        km: "ឈប់បោះពុម្ព",
      },
      furigana: [
        {
          rb: "絶版",
          rt: "ぜっぱん",
        },
      ],
      kanjiInfo: [
        {
          char: "絶",
          on: ["ゼツ"],
          kun: ["た.える", "た.やす", "た.つ"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "版",
          on: ["ハン"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
