export const n1part31 = {
  Lesson31: [
    {
      id: 1501,
      kanji: "放置",
      reading: "ほうち",
      meanings: {
        ja: "放置",
        en: "leaving as is; neglecting",
        zh: "放置",
        tw: "放置",
        ko: "방치",
        vi: "bỏ mặc",
        th: "ปล่อยทิ้งไว้",
        my: "အလိုလိုထားခြင်း",
        km: "ទុកឲ្យស្រមោល",
      },
      furigana: [
        {
          rb: "放置",
          rt: "ほうち",
        },
      ],
      kanjiInfo: [
        {
          char: "放",
          on: ["ホウ"],
          kun: [
            "はな.す",
            "-っぱな.し",
            "はな.つ",
            "はな.れる",
            "こ.く",
            "ほう.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "置",
          on: ["チ"],
          kun: ["お.く", "-お.き"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1502,
      kanji: "膨張",
      reading: "ぼうちょう",
      meanings: {
        ja: "膨張",
        en: "expansion; swelling",
        zh: "膨胀",
        tw: "膨脹",
        ko: "팽창",
        vi: "mở rộng",
        th: "การขยายตัว",
        my: "အကျယ်ချဲ့ခြင်း",
        km: "ពង្រីក",
      },
      furigana: [
        {
          rb: "膨張",
          rt: "ぼうちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "膨",
          on: ["ボウ"],
          kun: ["ふく.らむ", "ふく.れる"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "張",
          on: ["チョウ"],
          kun: ["は.る", "-は.り", "-ば.り"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1503,
      kanji: "法廷",
      reading: "ほうてい",
      meanings: {
        ja: "法廷",
        en: "court of law",
        zh: "法庭",
        tw: "法庭",
        ko: "법정",
        vi: "tòa án",
        th: "ศาล",
        my: "တရားရုံး",
        km: "តុលាការ",
      },
      furigana: [
        {
          rb: "法廷",
          rt: "ほうてい",
        },
      ],
      kanjiInfo: [
        {
          char: "法",
          on: ["ホウ", "ハッ", "ホッ", "フラン"],
          kun: ["のり"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "廷",
          on: ["テイ"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1504,
      kanji: "報道",
      reading: "ほうどう",
      meanings: {
        ja: "報道",
        en: "news report",
        zh: "报道",
        tw: "報導",
        ko: "보도",
        vi: "đưa tin",
        th: "ข่าวสาร",
        my: "သတင်းထုတ်ပြန်ခြင်း",
        km: "ការផ្សាយព័ត៌មាន",
      },
      furigana: [
        {
          rb: "報道",
          rt: "ほうどう",
        },
      ],
      kanjiInfo: [
        {
          char: "報",
          on: ["ホウ"],
          kun: ["むく.いる"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "道",
          on: ["ドウ", "トウ"],
          kun: ["みち", "いう"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1505,
      kanji: "冒頭",
      reading: "ぼうとう",
      meanings: {
        ja: "冒頭",
        en: "beginning; opening",
        zh: "开头",
        tw: "開頭",
        ko: "서두",
        vi: "phần mở đầu",
        th: "ตอนต้น",
        my: "အစပိုင်း",
        km: "ដើមបទ",
      },
      furigana: [
        {
          rb: "冒頭",
          rt: "ぼうとう",
        },
      ],
      kanjiInfo: [
        {
          char: "冒",
          on: ["ボウ"],
          kun: ["おか.す"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "頭",
          on: ["トウ", "ズ", "ト"],
          kun: ["あたま", "かしら", "-がしら", "かぶり"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1506,
      kanji: "暴動",
      reading: "ぼうどう",
      meanings: {
        ja: "暴動",
        en: "riot; insurrection",
        zh: "暴动",
        tw: "暴動",
        ko: "폭동",
        vi: "bạo động",
        th: "การจลาจล",
        my: "အရေးအခင်း",
        km: "ការបះបោរ",
      },
      furigana: [
        {
          rb: "暴動",
          rt: "ぼうどう",
        },
      ],
      kanjiInfo: [
        {
          char: "暴",
          on: ["ボウ", "バク"],
          kun: ["あば.く", "あば.れる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1507,
      kanji: "褒美",
      reading: "ほうび",
      meanings: {
        ja: "褒美",
        en: "reward; prize",
        zh: "奖赏",
        tw: "獎賞",
        ko: "포상",
        vi: "phần thưởng",
        th: "รางวัล",
        my: "ဆုချီးမြှင့်မှု",
        km: "រង្វាន់",
      },
      furigana: [
        {
          rb: "褒美",
          rt: "ほうび",
        },
      ],
      kanjiInfo: [
        {
          char: "褒",
          on: ["ホウ"],
          kun: ["ほ.める"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "美",
          on: ["ビ", "ミ"],
          kun: ["うつく.しい"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1508,
      kanji: "暴風",
      reading: "ぼうふう",
      meanings: {
        ja: "暴風",
        en: "storm; gale",
        zh: "暴风",
        tw: "暴風",
        ko: "폭풍",
        vi: "bão",
        th: "พายุแรง",
        my: "လေပြွန်",
        km: "ខ្យល់កន្ត្រាក់",
      },
      furigana: [
        {
          rb: "暴風",
          rt: "ぼうふう",
        },
      ],
      kanjiInfo: [
        {
          char: "暴",
          on: ["ボウ", "バク"],
          kun: ["あば.く", "あば.れる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1509,
      kanji: "暴力",
      reading: "ぼうりょく",
      meanings: {
        ja: "暴力",
        en: "violence",
        zh: "暴力",
        tw: "暴力",
        ko: "폭력",
        vi: "bạo lực",
        th: "ความรุนแรง",
        my: "အကြမ်းဖက်မှု",
        km: "អំពើហិង្សា",
      },
      furigana: [
        {
          rb: "暴力",
          rt: "ぼうりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "暴",
          on: ["ボウ", "バク"],
          kun: ["あば.く", "あば.れる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1510,
      kanji: "飽和",
      reading: "ほうわ",
      meanings: {
        ja: "飽和",
        en: "saturation",
        zh: "饱和",
        tw: "飽和",
        ko: "포화",
        vi: "bão hòa",
        th: "อิ่มตัว",
        my: "ပြည့်နှက်ခြင်း",
        km: "ពេញលេញ",
      },
      furigana: [
        {
          rb: "飽和",
          rt: "ほうわ",
        },
      ],
      kanjiInfo: [
        {
          char: "飽",
          on: ["ホウ"],
          kun: ["あ.きる", "あ.かす", "あ.く"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "和",
          on: ["ワ", "オ", "カ"],
          kun: ["やわ.らぐ", "やわ.らげる", "なご.む", "なご.やか", "あ.える"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1511,
      kanji: "ホース",
      reading: "ホース",
      meanings: {
        ja: "ホース",
        en: "hose",
        zh: "软管",
        tw: "水管",
        ko: "호스",
        vi: "ống nước",
        th: "สายยาง",
        my: "ရေပိုက်",
        km: "បំពង់ទឹក",
      },
      furigana: [
        {
          rb: "ホース",
          rt: "ホース",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1512,
      kanji: "ポーズ",
      reading: "ポーズ",
      meanings: {
        ja: "ポーズ",
        en: "pose; posture",
        zh: "姿势",
        tw: "姿勢",
        ko: "포즈",
        vi: "tư thế",
        th: "ท่าทาง",
        my: "အပြုအမူ",
        km: "សមតារ",
      },
      furigana: [
        {
          rb: "ポーズ",
          rt: "ポーズ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1513,
      kanji: "ホール",
      reading: "ホール",
      meanings: {
        ja: "ホール",
        en: "hall; venue",
        zh: "大厅",
        tw: "大廳",
        ko: "홀",
        vi: "sảnh; hội trường",
        th: "ห้องโถง",
        my: "မင်္ဂလာခန်းမ",
        km: "សាលាធំ",
      },
      furigana: [
        {
          rb: "ホール",
          rt: "ホール",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1514,
      kanji: "保温",
      reading: "ほおん",
      meanings: {
        ja: "保温",
        en: "heat retention",
        zh: "保温",
        tw: "保溫",
        ko: "보온",
        vi: "giữ nhiệt",
        th: "เก็บความร้อน",
        my: "အပူထားရှိခြင်း",
        km: "រក្សាកម្ដៅ",
      },
      furigana: [
        {
          rb: "保温",
          rt: "ほおん",
        },
      ],
      kanjiInfo: [
        {
          char: "保",
          on: ["ホ", "ホウ"],
          kun: ["たも.つ"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "温",
          on: ["オン"],
          kun: [
            "あたた.か",
            "あたた.かい",
            "あたた.まる",
            "あたた.める",
            "ぬく",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1515,
      kanji: "捕獲",
      reading: "ほかく",
      meanings: {
        ja: "捕獲",
        en: "capture",
        zh: "捕获",
        tw: "捕獲",
        ko: "포획",
        vi: "bắt giữ",
        th: "การจับกุม",
        my: "ဖမ်းဆီးခြင်း",
        km: "ចាប់យក",
      },
      furigana: [
        {
          rb: "捕獲",
          rt: "ほかく",
        },
      ],
      kanjiInfo: [
        {
          char: "捕",
          on: ["ホ"],
          kun: [
            "と.らえる",
            "と.らわれる",
            "と.る",
            "とら.える",
            "とら.われる",
            "つか.まえる",
            "つか.まる",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "獲",
          on: ["カク"],
          kun: ["え.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1516,
      kanji: "保管",
      reading: "ほかん",
      meanings: {
        ja: "保管",
        en: "custody; storage",
        zh: "保管",
        tw: "保管",
        ko: "보관",
        vi: "bảo quản",
        th: "เก็บรักษา",
        my: "သိမ်းဆည်းမှု",
        km: "រក្សាទុក",
      },
      furigana: [
        {
          rb: "保管",
          rt: "ほかん",
        },
      ],
      kanjiInfo: [
        {
          char: "保",
          on: ["ホ", "ホウ"],
          kun: ["たも.つ"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "管",
          on: ["カン"],
          kun: ["くだ"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1517,
      kanji: "補給",
      reading: "ほきゅう",
      meanings: {
        ja: "補給",
        en: "supply; replenishment",
        zh: "补给",
        tw: "補給",
        ko: "보급",
        vi: "tiếp tế",
        th: "เสบียง",
        my: "ဖြည့်တင်းပေးခြင်း",
        km: "ផ្គត់ផ្គង់",
      },
      furigana: [
        {
          rb: "補給",
          rt: "ほきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "補",
          on: ["ホ"],
          kun: ["おぎな.う"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "給",
          on: ["キュウ"],
          kun: ["たま.う", "たも.う", "-たま.え"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1518,
      kanji: "補強",
      reading: "ほきょう",
      meanings: {
        ja: "補強",
        en: "reinforcement",
        zh: "加固",
        tw: "補強",
        ko: "보강",
        vi: "gia cố",
        th: "เสริมแรง",
        my: "အခိုင်အမာပြုခြင်း",
        km: "បង្កើនភាពរឹង",
      },
      furigana: [
        {
          rb: "補強",
          rt: "ほきょう",
        },
      ],
      kanjiInfo: [
        {
          char: "補",
          on: ["ホ"],
          kun: ["おぎな.う"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "強",
          on: ["キョウ", "ゴウ"],
          kun: ["つよ.い", "つよ.まる", "つよ.める", "し.いる", "こわ.い"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1519,
      kanji: "募金",
      reading: "ぼきん",
      meanings: {
        ja: "募金",
        en: "fundraising; donation",
        zh: "募捐",
        tw: "募款",
        ko: "모금",
        vi: "quyên góp tiền",
        th: "ระดมทุน",
        my: "ငွေကောက်ခံမှု",
        km: "ប្រមូលថវិកា",
      },
      furigana: [
        {
          rb: "募金",
          rt: "ぼきん",
        },
      ],
      kanjiInfo: [
        {
          char: "募",
          on: ["ボ"],
          kun: ["つの.る"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1520,
      kanji: "牧師",
      reading: "ぼくし",
      meanings: {
        ja: "牧師",
        en: "pastor; minister",
        zh: "牧师",
        tw: "牧師",
        ko: "목사",
        vi: "mục sư",
        th: "บาทหลวง",
        my: "သခင်ဝတ်ပြုသူ",
        km: "អ្នកបូជា",
      },
      furigana: [
        {
          rb: "牧師",
          rt: "ぼくし",
        },
      ],
      kanjiInfo: [
        {
          char: "牧",
          on: ["ボク"],
          kun: ["まき"],
          strokes: 8,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
        {
          char: "師",
          on: ["シ"],
          kun: ["いくさ"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1521,
      kanji: "捕鯨",
      reading: "ほげい",
      meanings: {
        ja: "捕鯨",
        en: "whaling",
        zh: "捕鲸",
        tw: "捕鯨",
        ko: "포경",
        vi: "săn cá voi",
        th: "ล่าวาฬ",
        my: "ဝေ့ဖမ်းခြင်း",
        km: "បង្ក្រាបត្រីទឹកជ្រៅ",
      },
      furigana: [
        {
          rb: "捕鯨",
          rt: "ほげい",
        },
      ],
      kanjiInfo: [
        {
          char: "捕",
          on: ["ホ"],
          kun: [
            "と.らえる",
            "と.らわれる",
            "と.る",
            "とら.える",
            "とら.われる",
            "つか.まえる",
            "つか.まる",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "鯨",
          on: ["ゲイ"],
          kun: ["くじら"],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1522,
      kanji: "保険",
      reading: "ほけん",
      meanings: {
        ja: "保険",
        en: "insurance",
        zh: "保险",
        tw: "保險",
        ko: "보험",
        vi: "bảo hiểm",
        th: "ประกันภัย",
        my: "အာမခံ",
        km: "ធានារ៉ាប់រង",
      },
      furigana: [
        {
          rb: "保険",
          rt: "ほけん",
        },
      ],
      kanjiInfo: [
        {
          char: "保",
          on: ["ホ", "ホウ"],
          kun: ["たも.つ"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "険",
          on: ["ケン"],
          kun: ["けわ.しい"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1523,
      kanji: "母校",
      reading: "ぼこう",
      meanings: {
        ja: "母校",
        en: "alma mater",
        zh: "母校",
        tw: "母校",
        ko: "모교",
        vi: "trường cũ",
        th: "โรงเรียนเก่า",
        my: "အရင်တက်ခဲ့တဲ့ကျောင်း",
        km: "សាលាដើម",
      },
      furigana: [
        {
          rb: "母校",
          rt: "ぼこう",
        },
      ],
      kanjiInfo: [
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "校",
          on: ["コウ", "キョウ"],
          kun: [],
          strokes: 10,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1524,
      kanji: "母国",
      reading: "ぼこく",
      meanings: {
        ja: "母国",
        en: "home country",
        zh: "祖国",
        tw: "祖國",
        ko: "모국",
        vi: "quê hương",
        th: "ประเทศบ้านเกิด",
        my: "မွေးရာနိုင်ငံ",
        km: "ប្រទេសមាតុភូមិ",
      },
      furigana: [
        {
          rb: "母国",
          rt: "ぼこく",
        },
      ],
      kanjiInfo: [
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "国",
          on: ["コク"],
          kun: ["くに"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1525,
      kanji: "ポジション",
      reading: "ポジション",
      meanings: {
        ja: "ポジション",
        en: "position",
        zh: "位置",
        tw: "位置",
        ko: "포지션",
        vi: "vị trí",
        th: "ตำแหน่ง",
        my: "အနေအထား",
        km: "ទីតាំង",
      },
      furigana: [
        {
          rb: "ポジション",
          rt: "ポジション",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1526,
      kanji: "干し物",
      reading: "ほしもの",
      meanings: {
        ja: "干し物",
        en: "dried items (e.g. laundry or fish)",
        zh: "晾晒物",
        tw: "曬的東西",
        ko: "말린 것",
        vi: "đồ phơiแห้ง",
        th: "ของตากแห้ง",
        my: "အခြောက်အရာ",
        km: "វត្ថុស្ងួត",
      },
      furigana: [
        {
          rb: "干し物",
          rt: "ほしもの",
        },
      ],
      kanjiInfo: [
        {
          char: "干",
          on: ["カン"],
          kun: ["ほ.す", "ほ.し-", "-ぼ.し", "ひ.る"],
          strokes: 3,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1527,
      kanji: "保守",
      reading: "ほしゅ",
      meanings: {
        ja: "保守",
        en: "maintenance; conservatism",
        zh: "保守",
        tw: "保守",
        ko: "보수",
        vi: "bảo thủ; bảo trì",
        th: "อนุรักษ์/บำรุงรักษา",
        my: "ထိန်းသိမ်းမှု",
        km: "ថែទាំ/អភិរក្ស",
      },
      furigana: [
        {
          rb: "保守",
          rt: "ほしゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "保",
          on: ["ホ", "ホウ"],
          kun: ["たも.つ"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "守",
          on: ["シュ", "ス"],
          kun: ["まも.る", "まも.り", "もり", "-もり", "かみ"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1528,
      kanji: "補充",
      reading: "ほじゅう",
      meanings: {
        ja: "補充",
        en: "replenishment",
        zh: "补充",
        tw: "補充",
        ko: "보충",
        vi: "bổ sung",
        th: "เติมเต็ม",
        my: "ဖြည့်စွက်ခြင်း",
        km: "បន្ថែម",
      },
      furigana: [
        {
          rb: "補充",
          rt: "ほじゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "補",
          on: ["ホ"],
          kun: ["おぎな.う"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "充",
          on: ["ジュウ"],
          kun: ["あ.てる", "み.たす"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1529,
      kanji: "補助",
      reading: "ほじょ",
      meanings: {
        ja: "補助",
        en: "assistance; aid",
        zh: "辅助",
        tw: "輔助",
        ko: "보조",
        vi: "hỗ trợ",
        th: "ช่วยเหลือ",
        my: "အကူအညီ",
        km: "ជំនួយ",
      },
      furigana: [
        {
          rb: "補助",
          rt: "ほじょ",
        },
      ],
      kanjiInfo: [
        {
          char: "補",
          on: ["ホ"],
          kun: ["おぎな.う"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "助",
          on: ["ジョ"],
          kun: ["たす.ける", "たす.かる", "す.ける", "すけ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1530,
      kanji: "舗装",
      reading: "ほそう",
      meanings: {
        ja: "舗装",
        en: "paving (road)",
        zh: "铺路",
        tw: "鋪路",
        ko: "포장(도로)",
        vi: "lát đường",
        th: "ปูถนน",
        my: "လမ်းသွယ်ခြင်း",
        km: "បេតុងលើផ្លូវ",
      },
      furigana: [
        {
          rb: "舗装",
          rt: "ほそう",
        },
      ],
      kanjiInfo: [
        {
          char: "舗",
          on: ["ホ"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "装",
          on: ["ソウ", "ショウ"],
          kun: ["よそお.う", "よそお.い"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1531,
      kanji: "補足",
      reading: "ほそく",
      meanings: {
        ja: "補足",
        en: "supplement",
        zh: "补充",
        tw: "補足",
        ko: "보충",
        vi: "bổ túc",
        th: "เพิ่มเติม",
        my: "ဖြည့်စွက်ချက်",
        km: "បន្ថែម",
      },
      furigana: [
        {
          rb: "補足",
          rt: "ほそく",
        },
      ],
      kanjiInfo: [
        {
          char: "補",
          on: ["ホ"],
          kun: ["おぎな.う"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "足",
          on: ["ソク"],
          kun: ["あし", "た.りる", "た.る", "た.す"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1532,
      kanji: "墓地",
      reading: "ぼち",
      meanings: {
        ja: "墓地",
        en: "cemetery",
        zh: "墓地",
        tw: "墓地",
        ko: "묘지",
        vi: "nghĩa trang",
        th: "สุสาน",
        my: "သင်္ချိုင်း",
        km: "ផ្នូររួម",
      },
      furigana: [
        {
          rb: "墓地",
          rt: "ぼち",
        },
      ],
      kanjiInfo: [
        {
          char: "墓",
          on: ["ボ"],
          kun: ["はか"],
          strokes: 13,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1533,
      kanji: "発作",
      reading: "ほっさ",
      meanings: {
        ja: "発作",
        en: "fit; attack (medical)",
        zh: "发作",
        tw: "發作",
        ko: "발작",
        vi: "cơn (bệnh)",
        th: "อาการกำเริบ",
        my: "ရုတ်တရက်ဖြစ်ပွားမှု",
        km: "ជំងឺផ្តាសាយ/ឆក់",
      },
      furigana: [
        {
          rb: "発作",
          rt: "ほっさ",
        },
      ],
      kanjiInfo: [
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1534,
      kanji: "没収",
      reading: "ぼっしゅう",
      meanings: {
        ja: "没収",
        en: "confiscation; seizure",
        zh: "没收",
        tw: "沒收",
        ko: "몰수",
        vi: "tịch thu",
        th: "ยึด",
        my: "သိမ်းဆည်းခြင်း",
        km: "យកដាច់",
      },
      furigana: [
        {
          rb: "没収",
          rt: "ぼっしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "没",
          on: ["ボツ", "モツ"],
          kun: ["おぼ.れる", "しず.む", "ない"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "収",
          on: ["シュウ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1535,
      kanji: "発足",
      reading: "ほっそく",
      meanings: {
        ja: "発足",
        en: "launch; start",
        zh: "成立",
        tw: "發足",
        ko: "발족",
        vi: "thành lập",
        th: "เริ่มต้น",
        my: "စတင်ခြင်း",
        km: "ចាប់ផ្តើម",
      },
      furigana: [
        {
          rb: "発足",
          rt: "ほっそく",
        },
      ],
      kanjiInfo: [
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "足",
          on: ["ソク"],
          kun: ["あし", "た.りる", "た.る", "た.す"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1536,
      kanji: "ポット",
      reading: "ポット",
      meanings: {
        ja: "ポット",
        en: "pot; kettle",
        zh: "壶",
        tw: "壺",
        ko: "포트",
        vi: "bình",
        th: "กาน้ำ",
        my: "အိုး",
        km: "ធុងទឹក",
      },
      furigana: [
        {
          rb: "ポット",
          rt: "ポット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1537,
      kanji: "没落",
      reading: "ぼつらく",
      meanings: {
        ja: "没落",
        en: "ruin; downfall",
        zh: "没落",
        tw: "沒落",
        ko: "몰락",
        vi: "sụp đổ",
        th: "ล่มสลาย",
        my: "ပျက်စီးခြင်း",
        km: "ការបាក់បែក",
      },
      furigana: [
        {
          rb: "没落",
          rt: "ぼつらく",
        },
      ],
      kanjiInfo: [
        {
          char: "没",
          on: ["ボツ", "モツ"],
          kun: ["おぼ.れる", "しず.む", "ない"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "落",
          on: ["ラク"],
          kun: ["お.ちる", "お.ち", "お.とす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1538,
      kanji: "保養",
      reading: "ほよう",
      meanings: {
        ja: "保養",
        en: "recuperation; health preservation",
        zh: "保养",
        tw: "保養",
        ko: "보양",
        vi: "dưỡng sức",
        th: "พักฟื้น",
        my: "ကျန်းမာရေးထိန်းသိမ်းမှု",
        km: "ថែរក្សាសុខភាព",
      },
      furigana: [
        {
          rb: "保養",
          rt: "ほよう",
        },
      ],
      kanjiInfo: [
        {
          char: "保",
          on: ["ホ", "ホウ"],
          kun: ["たも.つ"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "養",
          on: ["ヨウ", "リョウ"],
          kun: ["やしな.う"],
          strokes: 15,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1539,
      kanji: "捕虜",
      reading: "ほりょ",
      meanings: {
        ja: "捕虜",
        en: "prisoner (of war)",
        zh: "俘虏",
        tw: "俘虜",
        ko: "포로",
        vi: "tù binh",
        th: "เชลยศึก",
        my: "စစ်အကျဉ်းသား",
        km: "អ្នកទោសសង្គ្រាម",
      },
      furigana: [
        {
          rb: "捕虜",
          rt: "ほりょ",
        },
      ],
      kanjiInfo: [
        {
          char: "捕",
          on: ["ホ"],
          kun: [
            "と.らえる",
            "と.らわれる",
            "と.る",
            "とら.える",
            "とら.われる",
            "つか.まえる",
            "つか.まる",
          ],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "虜",
          on: ["リョ", "ロ"],
          kun: ["とりこ", "とりく"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1540,
      kanji: "ボルト",
      reading: "ボルト",
      meanings: {
        ja: "ボルト（電圧の単位）",
        en: "volt",
        zh: "伏特",
        tw: "伏特",
        ko: "볼트",
        vi: "vôn",
        th: "โวลต์",
        my: "ဗို့",
        km: "វ៉ុល",
      },
      furigana: [
        {
          rb: "ボルト",
          rt: "ボルト",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1541,
      kanji: "本格",
      reading: "ほんかく",
      meanings: {
        ja: "本格（本来の形式）",
        en: "authentic; genuine; original method",
        zh: "正宗；地道",
        tw: "正宗；地道",
        ko: "본격",
        vi: "chính thức; đúng kiểu",
        th: "ของแท้; ตามแบบจริง",
        my: "အမှန်တကယ်သော",
        km: "ដើមបរិសុទ្ធ",
      },
      furigana: [
        {
          rb: "本格",
          rt: "ほんかく",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "格",
          on: ["カク", "コウ", "キャク", "ゴウ"],
          kun: [],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1542,
      kanji: "本館",
      reading: "ほんかん",
      meanings: {
        ja: "本館（別館に対して）",
        en: "main building (as opposed to an annex)",
        zh: "主楼",
        tw: "主樓",
        ko: "본관",
        vi: "toà chính",
        th: "อาคารหลัก",
        my: "အဓိကအဆောက်အအုံ",
        km: "អគារសំខាន់",
      },
      furigana: [
        {
          rb: "本館",
          rt: "ほんかん",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "館",
          on: ["カン"],
          kun: ["やかた", "たて"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1543,
      kanji: "本気",
      reading: "ほんき",
      meanings: {
        ja: "本気（まじめな気持ち）",
        en: "seriousness; earnestness",
        zh: "认真；当真",
        tw: "認真；當真",
        ko: "진심",
        vi: "nghiêm túc",
        th: "จริงจัง",
        my: "တကယ်ကြိုးစားခြင်း",
        km: "យកចិត្តទុកដាក់ពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "本気",
          rt: "ほんき",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1544,
      kanji: "本国",
      reading: "ほんごく",
      meanings: {
        ja: "本国（母国）",
        en: "home country",
        zh: "本国；祖国",
        tw: "本國；祖國",
        ko: "본국",
        vi: "quê hương",
        th: "ประเทศบ้านเกิด",
        my: "မိခင်နိုင်ငံ",
        km: "ប្រទេសមាតុភូមិ",
      },
      furigana: [
        {
          rb: "本国",
          rt: "ほんごく",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "国",
          on: ["コク"],
          kun: ["くに"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1545,
      kanji: "本質",
      reading: "ほんしつ",
      meanings: {
        ja: "本質（物事の本来の性質）",
        en: "essence; true nature",
        zh: "本质",
        tw: "本質",
        ko: "본질",
        vi: "bản chất",
        th: "แก่นแท้",
        my: "အဓိကသဘောတရား",
        km: "ធាតុសារៈសំខាន់",
      },
      furigana: [
        {
          rb: "本質",
          rt: "ほんしつ",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1546,
      kanji: "本体",
      reading: "ほんたい",
      meanings: {
        ja: "本体（主要部分）",
        en: "main body; substance",
        zh: "本体",
        tw: "本體",
        ko: "본체",
        vi: "phần chính",
        th: "ตัวหลัก",
        my: "အဓိကအစိတ်အပိုင်း",
        km: "រាងដើម",
      },
      furigana: [
        {
          rb: "本体",
          rt: "ほんたい",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1547,
      kanji: "本音",
      reading: "ほんね",
      meanings: {
        ja: "本音（本当の気持ち）",
        en: "true feelings; real intention",
        zh: "真心话",
        tw: "真心話",
        ko: "본심",
        vi: "cảm xúc thật",
        th: "ความรู้สึกที่แท้จริง",
        my: "စစ်မှန်သောစိတ်ခံစားမှု",
        km: "អារម្មណ៍ពិតប្រាកដ",
      },
      furigana: [
        {
          rb: "本音",
          rt: "ほんね",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "音",
          on: ["オン", "イン", "-ノン"],
          kun: ["おと", "ね"],
          strokes: 9,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1548,
      kanji: "本能",
      reading: "ほんのう",
      meanings: {
        ja: "本能（生まれつきの行動）",
        en: "instinct",
        zh: "本能",
        tw: "本能",
        ko: "본능",
        vi: "bản năng",
        th: "สัญชาตญาณ",
        my: "အပြုအမူသဘာဝ",
        km: "សញ្ញាសត្វ",
      },
      furigana: [
        {
          rb: "本能",
          rt: "ほんのう",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1549,
      kanji: "本場",
      reading: "ほんば",
      meanings: {
        ja: "本場（発祥地や中心地）",
        en: "birthplace; home (of something)",
        zh: "发源地",
        tw: "發源地",
        ko: "본고장",
        vi: "nơi gốc",
        th: "ถิ่นกำเนิด",
        my: "မူလနေရာ",
        km: "ទីកន្លែងដើម",
      },
      furigana: [
        {
          rb: "本場",
          rt: "ほんば",
        },
      ],
      kanjiInfo: [
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1550,
      kanji: "ポンプ",
      reading: "ポンプ",
      meanings: {
        ja: "ポンプ（液体をくみ上げる機械）",
        en: "pump",
        zh: "泵",
        tw: "幫浦",
        ko: "펌프",
        vi: "máy bơm",
        th: "ปั๊ม",
        my: "ရေစုပ်စက်",
        km: "ម៉ាស៊ីនបូមទឹក",
      },
      furigana: [
        {
          rb: "ポンプ",
          rt: "ポンプ",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
