export const n1part3 = {
  Lesson3: [
    {
      id: 101,
      kanji: "コントロール",
      reading: "コントロール",
      meanings: {
        ja: "コントロール（制御）",
        en: "control",
        zh: "控制",
        tw: "控制",
        ko: "컨트롤; 제어",
        vi: "điều khiển",
        th: "ควบคุม",
        my: "ထိန်းချုပ်ခြင်း",
        km: "ការគ្រប់គ្រង",
      },
      furigana: [
        {
          rb: "コントロール",
          rt: "コントロール",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 102,
      kanji: "コンパス",
      reading: "コンパス",
      meanings: {
        ja: "コンパス（円を描く道具）",
        en: "compass (for drawing circles)",
        zh: "圆规",
        tw: "圓規",
        ko: "컴퍼스",
        vi: "com-pa",
        th: "วงเวียน",
        my: "ကွင်းဖျား",
        km: "ខ្នាតគូរវង់",
      },
      furigana: [
        {
          rb: "コンパス",
          rt: "コンパス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 103,
      kanji: "根本",
      reading: "こんぽん",
      meanings: {
        ja: "根本",
        en: "root; foundation",
        zh: "根本; 基础",
        tw: "根本; 基礎",
        ko: "근본",
        vi: "gốc rễ; nền tảng",
        th: "พื้นฐาน",
        my: "အခြေခံအမြစ်",
        km: "គ្រឹះសម្បទាន",
      },
      furigana: [
        {
          rb: "根本",
          rt: "こんぽん",
        },
      ],
      kanjiInfo: [
        {
          char: "根",
          on: ["コン"],
          kun: ["ね", "-ね"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 104,
      kanji: "財",
      reading: "ざい",
      meanings: {
        ja: "財（財産）",
        en: "wealth; fortune",
        zh: "财富",
        tw: "財富",
        ko: "재산",
        vi: "tài sản",
        th: "ทรัพย์สิน",
        my: "ပစ္စည်းဥစ္စာ",
        km: "ទ្រព្យសម្បត្តិ",
      },
      furigana: [
        {
          rb: "財",
          rt: "ざい",
        },
      ],
      kanjiInfo: [
        {
          char: "財",
          on: ["ザイ", "サイ", "ゾク"],
          kun: ["たから"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 105,
      kanji: "再会",
      reading: "さいかい",
      meanings: {
        ja: "再会",
        en: "meeting again; reunion",
        zh: "重逢",
        tw: "重逢",
        ko: "재회",
        vi: "gặp lại",
        th: "พบกันอีกครั้ง",
        my: "ပြန်တွေ့ခြင်း",
        km: "ជួបជុំម្ដងទៀត",
      },
      furigana: [
        {
          rb: "再会",
          rt: "さいかい",
        },
      ],
      kanjiInfo: [
        {
          char: "再",
          on: ["サイ", "サ"],
          kun: ["ふたた.び"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 106,
      kanji: "災害",
      reading: "さいがい",
      meanings: {
        ja: "災害",
        en: "disaster; calamity",
        zh: "灾害",
        tw: "災害",
        ko: "재해",
        vi: "thiên tai",
        th: "ภัยพิบัติ",
        my: "ဘေးအန္တရာယ်",
        km: "គ្រោះថ្នាក់ធម្មជាតិ",
      },
      furigana: [
        {
          rb: "災害",
          rt: "さいがい",
        },
      ],
      kanjiInfo: [
        {
          char: "災",
          on: ["サイ"],
          kun: ["わざわ.い"],
          strokes: 7,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "害",
          on: ["ガイ"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 107,
      kanji: "細菌",
      reading: "さいきん",
      meanings: {
        ja: "細菌",
        en: "bacterium",
        zh: "细菌",
        tw: "細菌",
        ko: "세균",
        vi: "vi khuẩn",
        th: "แบคทีเรีย",
        my: "ဘက်တီးရီးယား",
        km: "បាក់តេរី",
      },
      furigana: [
        {
          rb: "細菌",
          rt: "さいきん",
        },
      ],
      kanjiInfo: [
        {
          char: "細",
          on: ["サイ"],
          kun: ["ほそ.い", "ほそ.る", "こま.か", "こま.かい"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "菌",
          on: ["キン"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 108,
      kanji: "細工",
      reading: "さいく",
      meanings: {
        ja: "細工",
        en: "workmanship; craftsmanship",
        zh: "工艺; 手工",
        tw: "工藝; 手工",
        ko: "세공; 솜씨",
        vi: "chế tác",
        th: "งานฝีมือ",
        my: "လက်မှုပညာ",
        km: "សិប្បកម្ម",
      },
      furigana: [
        {
          rb: "細工",
          rt: "さいく",
        },
      ],
      kanjiInfo: [
        {
          char: "細",
          on: ["サイ"],
          kun: ["ほそ.い", "ほそ.る", "こま.か", "こま.かい"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "工",
          on: ["コウ", "ク", "グ"],
          kun: [],
          strokes: 3,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 109,
      kanji: "採掘",
      reading: "さいくつ",
      meanings: {
        ja: "採掘",
        en: "mining; excavation",
        zh: "开采",
        tw: "開採",
        ko: "채굴",
        vi: "khai thác mỏ",
        th: "ขุดเจาะ",
        my: "တူးဖော်ခြင်း",
        km: "ជីកយក",
      },
      furigana: [
        {
          rb: "採掘",
          rt: "さいくつ",
        },
      ],
      kanjiInfo: [
        {
          char: "採",
          on: ["サイ"],
          kun: ["と.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "掘",
          on: ["クツ"],
          kun: ["ほ.る"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 110,
      kanji: "サイクル",
      reading: "サイクル",
      meanings: {
        ja: "サイクル（周期）",
        en: "cycle",
        zh: "循环",
        tw: "循環",
        ko: "주기; 사이클",
        vi: "chu kỳ",
        th: "วงจร",
        my: "လှည့်ပတ်ခြင်း",
        km: "វដ្ត",
      },
      furigana: [
        {
          rb: "サイクル",
          rt: "サイクル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 111,
      kanji: "採決",
      reading: "さいけつ",
      meanings: {
        ja: "採決（投票で決めること）",
        en: "vote",
        zh: "表决",
        tw: "表決",
        ko: "표결",
        vi: "biểu quyết",
        th: "ลงคะแนนเสียง",
        my: "မဲပေးဆုံးဖြတ်ခြင်း",
        km: "ការបោះឆ្នោតសម្រេច",
      },
      furigana: [
        {
          rb: "採決",
          rt: "さいけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "採",
          on: ["サイ"],
          kun: ["と.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "決",
          on: ["ケツ"],
          kun: ["き.める", "-ぎ.め", "き.まる", "さ.く"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 112,
      kanji: "再建",
      reading: "さいけん",
      meanings: {
        ja: "再建",
        en: "reconstruction; rebuilding",
        zh: "重建",
        tw: "重建",
        ko: "재건",
        vi: "tái thiết",
        th: "สร้างใหม่",
        my: "ပြန်လည်တည်ဆောက်ခြင်း",
        km: "ស្តារឡើងវិញ",
      },
      furigana: [
        {
          rb: "再建",
          rt: "さいけん",
        },
      ],
      kanjiInfo: [
        {
          char: "再",
          on: ["サイ", "サ"],
          kun: ["ふたた.び"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "建",
          on: ["ケン", "コン"],
          kun: ["た.てる", "た.て", "-だ.て", "た.つ"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 113,
      kanji: "再現",
      reading: "さいげん",
      meanings: {
        ja: "再現",
        en: "reappearance; reproduction",
        zh: "再现",
        tw: "再現",
        ko: "재현",
        vi: "tái hiện",
        th: "แสดงอีกครั้ง",
        my: "ပြန်လည်ပေါ်ပေါက်ခြင်း",
        km: "បង្ហាញឡើងវិញ",
      },
      furigana: [
        {
          rb: "再現",
          rt: "さいげん",
        },
      ],
      kanjiInfo: [
        {
          char: "再",
          on: ["サイ", "サ"],
          kun: ["ふたた.び"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 114,
      kanji: "財源",
      reading: "ざいげん",
      meanings: {
        ja: "財源",
        en: "financial resources; source of funds",
        zh: "财源",
        tw: "財源",
        ko: "재원",
        vi: "nguồn tài chính",
        th: "แหล่งเงินทุน",
        my: "ငွေကြေးအရင်းအမြစ်",
        km: "ប្រភពហិរញ្ញវត្ថុ",
      },
      furigana: [
        {
          rb: "財源",
          rt: "ざいげん",
        },
      ],
      kanjiInfo: [
        {
          char: "財",
          on: ["ザイ", "サイ", "ゾク"],
          kun: ["たから"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "源",
          on: ["ゲン"],
          kun: ["みなもと"],
          strokes: 13,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 115,
      kanji: "在庫",
      reading: "ざいこ",
      meanings: {
        ja: "在庫",
        en: "inventory; stock",
        zh: "库存",
        tw: "庫存",
        ko: "재고",
        vi: "hàng tồn kho",
        th: "สินค้าคงคลัง",
        my: "ကုန်ပစ္စည်းအရှုံး",
        km: "ស្តុកទំនិញ",
      },
      furigana: [
        {
          rb: "在庫",
          rt: "ざいこ",
        },
      ],
      kanjiInfo: [
        {
          char: "在",
          on: ["ザイ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "庫",
          on: ["コ", "ク"],
          kun: ["くら"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 116,
      kanji: "採算",
      reading: "さいさん",
      meanings: {
        ja: "採算",
        en: "profitability",
        zh: "收益",
        tw: "收益",
        ko: "수지; 이익",
        vi: "lợi nhuận",
        th: "กำไร",
        my: "အမြတ်အမြန်",
        km: "ប្រាក់ចំណេញ",
      },
      furigana: [
        {
          rb: "採算",
          rt: "さいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "採",
          on: ["サイ"],
          kun: ["と.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 117,
      kanji: "サイズ",
      reading: "サイズ",
      meanings: {
        ja: "サイズ（大きさ）",
        en: "size",
        zh: "尺寸",
        tw: "尺寸",
        ko: "사이즈; 크기",
        vi: "kích thước",
        th: "ขนาด",
        my: "အရွယ်အစား",
        km: "ទំហំ",
      },
      furigana: [
        {
          rb: "サイズ",
          rt: "サイズ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 118,
      kanji: "再生",
      reading: "さいせい",
      meanings: {
        ja: "再生",
        en: "regeneration; playback",
        zh: "再生",
        tw: "再生",
        ko: "재생",
        vi: "tái sinh; phát lại",
        th: "เล่นซ้ำ/เกิดใหม่",
        my: "ပြန်လည်ဖြစ်ပေါ်ခြင်း",
        km: "ការស្តារឡើងវិញ",
      },
      furigana: [
        {
          rb: "再生",
          rt: "さいせい",
        },
      ],
      kanjiInfo: [
        {
          char: "再",
          on: ["サイ", "サ"],
          kun: ["ふたた.び"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 119,
      kanji: "財政",
      reading: "ざいせい",
      meanings: {
        ja: "財政",
        en: "public finance; fiscal policy",
        zh: "财政",
        tw: "財政",
        ko: "재정",
        vi: "tài chính công",
        th: "การคลัง",
        my: "ငွေကြေးအုပ်ချုပ်မှု",
        km: "ហិរញ្ញវត្ថុសាធារណៈ",
      },
      furigana: [
        {
          rb: "財政",
          rt: "ざいせい",
        },
      ],
      kanjiInfo: [
        {
          char: "財",
          on: ["ザイ", "サイ", "ゾク"],
          kun: ["たから"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "政",
          on: ["セイ", "ショウ"],
          kun: ["まつりごと", "まん"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 120,
      kanji: "最善",
      reading: "さいぜん",
      meanings: {
        ja: "最善",
        en: "the very best",
        zh: "最善",
        tw: "最善",
        ko: "최선",
        vi: "tốt nhất",
        th: "ดีที่สุด",
        my: "အကောင်းဆုံး",
        km: "ល្អបំផុត",
      },
      furigana: [
        {
          rb: "最善",
          rt: "さいぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "最",
          on: ["サイ", "シュ"],
          kun: ["もっと.も", "つま"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "善",
          on: ["ゼン"],
          kun: ["よ.い", "い.い", "よ.く", "よし.とする"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 121,
      kanji: "採択",
      reading: "さいたく",
      meanings: {
        ja: "採択",
        en: "adoption (of a proposal)",
        zh: "采纳",
        tw: "採納",
        ko: "채택",
        vi: "thông qua",
        th: "นำมาใช้/ยอมรับ",
        my: "လက်ခံသုံးစွဲခြင်း",
        km: "ការទទួលយក",
      },
      furigana: [
        {
          rb: "採択",
          rt: "さいたく",
        },
      ],
      kanjiInfo: [
        {
          char: "採",
          on: ["サイ"],
          kun: ["と.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "択",
          on: ["タク"],
          kun: ["えら.ぶ"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 122,
      kanji: "栽培",
      reading: "さいばい",
      meanings: {
        ja: "栽培",
        en: "cultivation; growing (plants)",
        zh: "栽培",
        tw: "栽培",
        ko: "재배",
        vi: "trồng trọt",
        th: "เพาะปลูก",
        my: "စိုက်ပျိုးခြင်း",
        km: "ដាំដុះ",
      },
      furigana: [
        {
          rb: "栽培",
          rt: "さいばい",
        },
      ],
      kanjiInfo: [
        {
          char: "栽",
          on: ["サイ"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "培",
          on: ["バイ"],
          kun: ["つちか.う"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 123,
      kanji: "再発",
      reading: "さいはつ",
      meanings: {
        ja: "再発",
        en: "recurrence",
        zh: "复发",
        tw: "復發",
        ko: "재발",
        vi: "tái phát",
        th: "เกิดซ้ำ",
        my: "ပြန်လည်ဖြစ်ပေါ်ခြင်း",
        km: "កើតឡើងម្ដងទៀត",
      },
      furigana: [
        {
          rb: "再発",
          rt: "さいはつ",
        },
      ],
      kanjiInfo: [
        {
          char: "再",
          on: ["サイ", "サ"],
          kun: ["ふたた.び"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 124,
      kanji: "細胞",
      reading: "さいぼう",
      meanings: {
        ja: "細胞",
        en: "cell (biology)",
        zh: "细胞",
        tw: "細胞",
        ko: "세포",
        vi: "tế bào",
        th: "เซลล์",
        my: "ဆဲလ်",
        km: "កោសិកា",
      },
      furigana: [
        {
          rb: "細胞",
          rt: "さいぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "細",
          on: ["サイ"],
          kun: ["ほそ.い", "ほそ.る", "こま.か", "こま.かい"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "胞",
          on: ["ホウ"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 125,
      kanji: "採用",
      reading: "さいよう",
      meanings: {
        ja: "採用",
        en: "employment; adoption (of method)",
        zh: "采用; 录用",
        tw: "採用; 錄用",
        ko: "채용",
        vi: "tuyển dụng",
        th: "รับเข้า/ใช้",
        my: "အလုပ်ခန့်ခြင်း",
        km: "ការជ្រើសរើស",
      },
      furigana: [
        {
          rb: "採用",
          rt: "さいよう",
        },
      ],
      kanjiInfo: [
        {
          char: "採",
          on: ["サイ"],
          kun: ["と.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 126,
      kanji: "竿",
      reading: "さお",
      meanings: {
        ja: "竿（釣り竿など）",
        en: "rod; pole",
        zh: "竿子",
        tw: "竿子",
        ko: "막대기; 낚싯대",
        vi: "cần (câu cá)",
        th: "คันเบ็ด/ไม้ยาว",
        my: "တိုင်",
        km: "ដំបង",
      },
      furigana: [
        {
          rb: "竿",
          rt: "さお",
        },
      ],
      kanjiInfo: [
        {
          char: "竿",
          on: ["カン"],
          kun: ["さお"],
          strokes: 9,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 127,
      kanji: "差額",
      reading: "さがく",
      meanings: {
        ja: "差額",
        en: "balance; difference in amount",
        zh: "差额",
        tw: "差額",
        ko: "차액",
        vi: "khoản chênh lệch",
        th: "ส่วนต่างราคา",
        my: "အပိုငွေ/ခွဲခြားငွေ",
        km: "ប្រាក់ខុសគ្នា",
      },
      furigana: [
        {
          rb: "差額",
          rt: "さがく",
        },
      ],
      kanjiInfo: [
        {
          char: "差",
          on: ["サ"],
          kun: ["さ.す", "さ.し"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "額",
          on: ["ガク"],
          kun: ["ひたい"],
          strokes: 18,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 128,
      kanji: "杯",
      reading: "さかずき",
      meanings: {
        ja: "杯（さかずき）",
        en: "sake cup",
        zh: "酒杯",
        tw: "酒杯",
        ko: "술잔",
        vi: "chén rượu",
        th: "ถ้วยสาเก",
        my: "ဝိုင်ခွက်",
        km: "ពាងស្រា",
      },
      furigana: [
        {
          rb: "杯",
          rt: "さかずき",
        },
      ],
      kanjiInfo: [
        {
          char: "杯",
          on: ["ハイ"],
          kun: ["さかずき"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 129,
      kanji: "逆立ち",
      reading: "さかだち",
      meanings: {
        ja: "逆立ち",
        en: "handstand",
        zh: "倒立",
        tw: "倒立",
        ko: "물구나무서기",
        vi: "trồng cây chuối",
        th: "ยืนกลับหัว",
        my: "အဖြောင့်နောက်အထောက်",
        km: "ឈរទ្រេត",
      },
      furigana: [
        {
          rb: "逆立ち",
          rt: "さかだち",
        },
      ],
      kanjiInfo: [
        {
          char: "逆",
          on: ["ギャク", "ゲキ"],
          kun: ["さか", "さか.さ", "さか.らう"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "立",
          on: ["リツ", "リュウ", "リットル"],
          kun: [
            "た.つ",
            "-た.つ",
            "た.ち-",
            "た.てる",
            "-た.てる",
            "た.て-",
            "たて-",
            "-た.て",
            "-だ.て",
            "-だ.てる",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 130,
      kanji: "詐欺",
      reading: "さぎ",
      meanings: {
        ja: "詐欺",
        en: "fraud; scam",
        zh: "诈骗",
        tw: "詐騙",
        ko: "사기",
        vi: "lừa đảo",
        th: "ฉ้อโกง",
        my: "လိမ်လည်မှု",
        km: "ការលួចបន្លំ",
      },
      furigana: [
        {
          rb: "詐欺",
          rt: "さぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "詐",
          on: ["サ"],
          kun: ["いつわ.る"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "欺",
          on: ["ギ"],
          kun: ["あざむ.く"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 131,
      kanji: "削減",
      reading: "さくげん",
      meanings: {
        ja: "削減",
        en: "reduction; cut",
        zh: "削减",
        tw: "削減",
        ko: "삭감",
        vi: "giảm bớt",
        th: "ลดลง",
        my: "လျှော့ချခြင်း",
        km: "កាត់បន្ថយ",
      },
      furigana: [
        {
          rb: "削減",
          rt: "さくげん",
        },
      ],
      kanjiInfo: [
        {
          char: "削",
          on: ["サク"],
          kun: ["けず.る", "はつ.る", "そ.ぐ"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "減",
          on: ["ゲン"],
          kun: ["へ.る", "へ.らす"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 132,
      kanji: "錯誤",
      reading: "さくご",
      meanings: {
        ja: "錯誤",
        en: "mistake; error",
        zh: "错误",
        tw: "錯誤",
        ko: "착오",
        vi: "sai lầm",
        th: "ความผิดพลาด",
        my: "မှားယွင်းမှု",
        km: "កំហុស",
      },
      furigana: [
        {
          rb: "錯誤",
          rt: "さくご",
        },
      ],
      kanjiInfo: [
        {
          char: "錯",
          on: ["サク", "シャク"],
          kun: [],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "誤",
          on: ["ゴ"],
          kun: ["あやま.る", "-あやま.る"],
          strokes: 14,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 133,
      kanji: "作戦",
      reading: "さくせん",
      meanings: {
        ja: "作戦",
        en: "strategy; tactics",
        zh: "作战; 策略",
        tw: "作戰; 策略",
        ko: "작전; 전략",
        vi: "chiến lược",
        th: "ยุทธการ/กลยุทธ์",
        my: "နည်းလမ်းစစ်ဆင်ရေး",
        km: "យុទ្ធសាស្រ្ត",
      },
      furigana: [
        {
          rb: "作戦",
          rt: "さくせん",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "戦",
          on: ["セン"],
          kun: ["いくさ", "たたか.う", "おのの.く", "そよ.ぐ", "わなな.く"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 134,
      kanji: "叫び",
      reading: "さけび",
      meanings: {
        ja: "叫び",
        en: "shout; scream",
        zh: "喊叫",
        tw: "喊叫",
        ko: "외침",
        vi: "tiếng hét",
        th: "เสียงตะโกน",
        my: "အော်ဟစ်သံ",
        km: "ស្រែក",
      },
      furigana: [
        {
          rb: "叫び",
          rt: "さけび",
        },
      ],
      kanjiInfo: [
        {
          char: "叫",
          on: ["キョウ"],
          kun: ["さけ.ぶ"],
          strokes: 6,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 135,
      kanji: "指図",
      reading: "さしず",
      meanings: {
        ja: "指図",
        en: "directions; orders",
        zh: "指示",
        tw: "指示",
        ko: "지시",
        vi: "chỉ dẫn",
        th: "คำสั่ง",
        my: "ညွှန်ကြားချက်",
        km: "ការណែនាំ",
      },
      furigana: [
        {
          rb: "指図",
          rt: "さしず",
        },
      ],
      kanjiInfo: [
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "図",
          on: ["ズ", "ト"],
          kun: ["え", "はか.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 136,
      kanji: "座談会",
      reading: "ざだんかい",
      meanings: {
        ja: "座談会",
        en: "symposium; round-table talk",
        zh: "座谈会",
        tw: "座談會",
        ko: "좌담회",
        vi: "tọa đàm",
        th: "เสวนา",
        my: "ညှိနှိုင်းပွဲ",
        km: "សន្និសីទជជែក",
      },
      furigana: [
        {
          rb: "座談会",
          rt: "ざだんかい",
        },
      ],
      kanjiInfo: [
        {
          char: "座",
          on: ["ザ"],
          kun: ["すわ.る"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "談",
          on: ["ダン"],
          kun: [],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 137,
      kanji: "雑貨",
      reading: "ざっか",
      meanings: {
        ja: "雑貨",
        en: "miscellaneous goods",
        zh: "杂货",
        tw: "雜貨",
        ko: "잡화",
        vi: "hàng tạp hóa",
        th: "ของจิปาถะ",
        my: "အမျိုးအစားပစ္စည်း",
        km: "ទំនិញចម្រុះ",
      },
      furigana: [
        {
          rb: "雑貨",
          rt: "ざっか",
        },
      ],
      kanjiInfo: [
        {
          char: "雑",
          on: ["ザツ", "ゾウ"],
          kun: ["まじ.える", "まじ.る"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "貨",
          on: ["カ"],
          kun: ["たから"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 138,
      kanji: "殺人",
      reading: "さつじん",
      meanings: {
        ja: "殺人",
        en: "murder; homicide",
        zh: "杀人",
        tw: "殺人",
        ko: "살인",
        vi: "giết người",
        th: "ฆาตกรรม",
        my: "လူသတ်မှု",
        km: "ការសម្លាប់មនុស្ស",
      },
      furigana: [
        {
          rb: "殺人",
          rt: "さつじん",
        },
      ],
      kanjiInfo: [
        {
          char: "殺",
          on: ["サツ", "サイ", "セツ"],
          kun: ["ころ.す", "-ごろ.し", "そ.ぐ", "あや.める"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 139,
      kanji: "雑談",
      reading: "ざつだん",
      meanings: {
        ja: "雑談",
        en: "chatting; small talk",
        zh: "闲聊",
        tw: "閒聊",
        ko: "잡담",
        vi: "tán gẫu",
        th: "พูดคุยทั่วไป",
        my: "စကားပြောခြင်း",
        km: "និយាយលេង",
      },
      furigana: [
        {
          rb: "雑談",
          rt: "ざつだん",
        },
      ],
      kanjiInfo: [
        {
          char: "雑",
          on: ["ザツ", "ゾウ"],
          kun: ["まじ.える", "まじ.る"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "談",
          on: ["ダン"],
          kun: [],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 140,
      kanji: "最中",
      reading: "さなか",
      meanings: {
        ja: "最中（〜のさなか）",
        en: "in the middle of",
        zh: "正当...之中",
        tw: "正當...之中",
        ko: "한창 ...중에",
        vi: "đang lúc",
        th: "ในระหว่าง",
        my: "အလယ်မှာ",
        km: "កណ្ដាលនៃ",
      },
      furigana: [
        {
          rb: "最中",
          rt: "さなか",
        },
      ],
      kanjiInfo: [
        {
          char: "最",
          on: ["サイ", "シュ"],
          kun: ["もっと.も", "つま"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 141,
      kanji: "座標",
      reading: "ざひょう",
      meanings: {
        ja: "座標",
        en: "coordinate",
        zh: "坐标",
        tw: "座標",
        ko: "좌표",
        vi: "tọa độ",
        th: "พิกัด",
        my: "အတိုင်းအတာချင်း",
        km: "កូអរដោនេ",
      },
      furigana: [
        {
          rb: "座標",
          rt: "ざひょう",
        },
      ],
      kanjiInfo: [
        {
          char: "座",
          on: ["ザ"],
          kun: ["すわ.る"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "標",
          on: ["ヒョウ"],
          kun: ["しるべ", "しるし"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 142,
      kanji: "寒気",
      reading: "さむけ",
      meanings: {
        ja: "寒気（さむけ）",
        en: "chill; shiver",
        zh: "寒气",
        tw: "寒氣",
        ko: "오한",
        vi: "ớn lạnh",
        th: "หนาวสั่น",
        my: "အေးလှုပ်ခြင်း",
        km: "ការភ្ញាក់អាឡាត",
      },
      furigana: [
        {
          rb: "寒気",
          rt: "さむけ",
        },
      ],
      kanjiInfo: [
        {
          char: "寒",
          on: ["カン"],
          kun: ["さむ.い"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 143,
      kanji: "侍",
      reading: "さむらい",
      meanings: {
        ja: "侍",
        en: "samurai; warrior",
        zh: "武士",
        tw: "武士",
        ko: "사무라이",
        vi: "võ sĩ",
        th: "ซามูไร",
        my: "စမူရိုင်း",
        km: "សាមូរាយ",
      },
      furigana: [
        {
          rb: "侍",
          rt: "さむらい",
        },
      ],
      kanjiInfo: [
        {
          char: "侍",
          on: ["ジ", "シ"],
          kun: ["さむらい", "はべ.る"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 144,
      kanji: "作用",
      reading: "さよう",
      meanings: {
        ja: "作用",
        en: "action; effect",
        zh: "作用",
        tw: "作用",
        ko: "작용",
        vi: "tác dụng",
        th: "ผลกระทบ",
        my: "အကျိုးသက်ရောက်မှု",
        km: "អំពើ; ផលប៉ះពាល់",
      },
      furigana: [
        {
          rb: "作用",
          rt: "さよう",
        },
      ],
      kanjiInfo: [
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 145,
      kanji: "酸",
      reading: "さん",
      meanings: {
        ja: "酸",
        en: "acid",
        zh: "酸",
        tw: "酸",
        ko: "산",
        vi: "axit",
        th: "กรด",
        my: "အက်စစ်",
        km: "អាស៊ីត",
      },
      furigana: [
        {
          rb: "酸",
          rt: "さん",
        },
      ],
      kanjiInfo: [
        {
          char: "酸",
          on: ["サン"],
          kun: ["す.い"],
          strokes: 14,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 146,
      kanji: "山岳",
      reading: "さんがく",
      meanings: {
        ja: "山岳",
        en: "mountain range",
        zh: "山岳",
        tw: "山岳",
        ko: "산악",
        vi: "núi non",
        th: "ภูเขา",
        my: "တောင်တန်း",
        km: "ភ្នំ",
      },
      furigana: [
        {
          rb: "山岳",
          rt: "さんがく",
        },
      ],
      kanjiInfo: [
        {
          char: "山",
          on: ["サン", "セン"],
          kun: ["やま"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "岳",
          on: ["ガク"],
          kun: ["たけ"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 147,
      kanji: "参議院",
      reading: "さんぎいん",
      meanings: {
        ja: "参議院（日本の国会の上院）",
        en: "House of Councillors (Japan)",
        zh: "参议院",
        tw: "參議院",
        ko: "참의원",
        vi: "Thượng viện Nhật Bản",
        th: "วุฒิสภาญี่ปุ่น",
        my: "အကြံပေးအဖွဲ့",
        km: "ព្រឹទ្ធសភា",
      },
      furigana: [
        {
          rb: "参議院",
          rt: "さんぎいん",
        },
      ],
      kanjiInfo: [
        {
          char: "参",
          on: ["サン", "シン"],
          kun: ["まい.る", "まい-", "まじわる", "みつ"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "議",
          on: ["ギ"],
          kun: [],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "院",
          on: ["イン"],
          kun: [],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 148,
      kanji: "産休",
      reading: "さんきゅう",
      meanings: {
        ja: "産休（出産休暇）",
        en: "maternity leave",
        zh: "产假",
        tw: "產假",
        ko: "출산휴가",
        vi: "nghỉ sinh",
        th: "ลาคลอด",
        my: "မွေးဖွားခြင်းအပန်း",
        km: "វិស្សមកាលសម្រាលកូន",
      },
      furigana: [
        {
          rb: "産休",
          rt: "さんきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 149,
      kanji: "残金",
      reading: "ざんきん",
      meanings: {
        ja: "残金",
        en: "remaining money",
        zh: "余额",
        tw: "餘額",
        ko: "잔금",
        vi: "tiền còn lại",
        th: "เงินที่เหลือ",
        my: "ကျန်ငွေ",
        km: "ប្រាក់នៅសល់",
      },
      furigana: [
        {
          rb: "残金",
          rt: "ざんきん",
        },
      ],
      kanjiInfo: [
        {
          char: "残",
          on: ["ザン", "サン"],
          kun: ["のこ.る", "のこ.す", "そこな.う", "のこ.り"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 150,
      kanji: "産出",
      reading: "さんしゅつ",
      meanings: {
        ja: "産出",
        en: "production; yield",
        zh: "产出",
        tw: "產出",
        ko: "산출",
        vi: "sản xuất",
        th: "การผลิต",
        my: "ထုတ်လုပ်ခြင်း",
        km: "ផលិតកម្ម",
      },
      furigana: [
        {
          rb: "産出",
          rt: "さんしゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
