export const n1part42 = {
  Lesson42: [
    {
      id: 2010,
      kanji: "未婚",
      reading: "みこん",
      meanings: {
        ja: "未婚",
        en: "unmarried",
        zh: "未婚",
        tw: "未婚",
        ko: "미혼",
        vi: "chưa kết hôn",
        th: "ยังไม่แต่งงาน",
        my: "အိမ်ထောင်မရှိသေးသူ",
        km: "មិនទាន់រៀបការទេ",
      },
      furigana: [
        {
          rb: "未婚",
          rt: "みこん",
        },
      ],
      kanjiInfo: [
        {
          char: "未",
          on: ["ミ", "ビ"],
          kun: ["いま.だ", "ま.だ", "ひつじ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "婚",
          on: ["コン"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2011,
      kanji: "未熟",
      reading: "みじゅく",
      meanings: {
        ja: "未熟",
        en: "unripe; inexperienced",
        zh: "未成熟",
        tw: "未成熟",
        ko: "미숙함",
        vi: "chưa thành thạo",
        th: "ยังไม่ชำนาญ",
        my: "အတွေ့အကြုံနည်းသော",
        km: "មិនទាន់ជាប់ជាផ្លូវការទេ",
      },
      furigana: [
        {
          rb: "未熟",
          rt: "みじゅく",
        },
      ],
      kanjiInfo: [
        {
          char: "未",
          on: ["ミ", "ビ"],
          kun: ["いま.だ", "ま.だ", "ひつじ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "熟",
          on: ["ジュク"],
          kun: ["う.れる"],
          strokes: 15,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2012,
      kanji: "未知",
      reading: "みち",
      meanings: {
        ja: "未知",
        en: "unknown",
        zh: "未知",
        tw: "未知",
        ko: "미지",
        vi: "chưa biết",
        th: "ไม่รู้จัก",
        my: "မသိရသေးသော",
        km: "មិនស្គាល់",
      },
      furigana: [
        {
          rb: "未知",
          rt: "みち",
        },
      ],
      kanjiInfo: [
        {
          char: "未",
          on: ["ミ", "ビ"],
          kun: ["いま.だ", "ま.だ", "ひつじ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "知",
          on: ["チ"],
          kun: ["し.る", "し.らせる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2013,
      kanji: "身近",
      reading: "みぢか",
      meanings: {
        ja: "身近",
        en: "near oneself; familiar",
        zh: "身边的",
        tw: "身邊的",
        ko: "가까운",
        vi: "gần gũi",
        th: "ใกล้ตัว",
        my: "နီးစပ်သော",
        km: "នៅជិតខ្លួន",
      },
      furigana: [
        {
          rb: "身近",
          rt: "みぢか",
        },
      ],
      kanjiInfo: [
        {
          char: "身",
          on: ["シン"],
          kun: ["み"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "近",
          on: ["キン", "コン"],
          kun: ["ちか.い"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2014,
      kanji: "密接",
      reading: "みっせつ",
      meanings: {
        ja: "密接",
        en: "close (relationship)",
        zh: "密切",
        tw: "密切",
        ko: "밀접한",
        vi: "mật thiết",
        th: "ใกล้ชิด",
        my: "နီးစပ်အနက်ရှိသော",
        km: "ជិតស្និទ្ធ",
      },
      furigana: [
        {
          rb: "密接",
          rt: "みっせつ",
        },
      ],
      kanjiInfo: [
        {
          char: "密",
          on: ["ミツ"],
          kun: ["ひそ.か"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "接",
          on: ["セツ", "ショウ"],
          kun: ["つ.ぐ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2015,
      kanji: "未定",
      reading: "みてい",
      meanings: {
        ja: "未定",
        en: "not yet decided",
        zh: "未定",
        tw: "未定",
        ko: "미정",
        vi: "chưa quyết định",
        th: "ยังไม่ตัดสินใจ",
        my: "မဆုံးဖြတ်ရသေးသော",
        km: "មិនទាន់សម្រេច",
      },
      furigana: [
        {
          rb: "未定",
          rt: "みてい",
        },
      ],
      kanjiInfo: [
        {
          char: "未",
          on: ["ミ", "ビ"],
          kun: ["いま.だ", "ま.だ", "ひつじ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2016,
      kanji: "無意味",
      reading: "むいみ",
      meanings: {
        ja: "無意味",
        en: "meaningless",
        zh: "无意义",
        tw: "無意義",
        ko: "무의미한",
        vi: "vô nghĩa",
        th: "ไม่มีความหมาย",
        my: "အဓိပ္ပါယ်မရှိသော",
        km: "គ្មានអត្ថន័យ",
      },
      furigana: [
        {
          rb: "無意味",
          rt: "むいみ",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "意",
          on: ["イ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2017,
      kanji: "無口",
      reading: "むくち",
      meanings: {
        ja: "無口",
        en: "taciturn",
        zh: "沉默寡言",
        tw: "沉默寡言",
        ko: "말이 적은",
        vi: "ít nói",
        th: "เงียบขรึม",
        my: "နူးညံ့သက်သက်မပြောသော",
        km: "ស្ងាត់",
      },
      furigana: [
        {
          rb: "無口",
          rt: "むくち",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "口",
          on: ["コウ", "ク"],
          kun: ["くち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2018,
      kanji: "無効",
      reading: "むこう",
      meanings: {
        ja: "無効",
        en: "invalid",
        zh: "无效",
        tw: "無效",
        ko: "무효",
        vi: "không hợp lệ",
        th: "ไม่ถูกต้อง",
        my: "မတရားသော",
        km: "អសកម្ម",
      },
      furigana: [
        {
          rb: "無効",
          rt: "むこう",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "効",
          on: ["コウ"],
          kun: ["き.く", "ききめ", "なら.う"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2019,
      kanji: "無邪気",
      reading: "むじゃき",
      meanings: {
        ja: "無邪気",
        en: "innocent",
        zh: "天真无邪",
        tw: "天真無邪",
        ko: "천진난만한",
        vi: "ngây thơ",
        th: "ไร้เดียงสา",
        my: "မူမမှန်သော",
        km: "ស្មោះស្មូត្រ",
      },
      furigana: [
        {
          rb: "無邪気",
          rt: "むじゃき",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "邪",
          on: ["ジャ"],
          kun: ["よこし.ま"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2020,
      kanji: "無茶",
      reading: "むちゃ",
      meanings: {
        ja: "無茶",
        en: "absurd; reckless",
        zh: "胡闹",
        tw: "胡鬧",
        ko: "무리한",
        vi: "vô lý",
        th: "ไร้เหตุผล",
        my: "အဓိပ္ပါယ်မရှိသော",
        km: "ឥតមានហេតុផល",
      },
      furigana: [
        {
          rb: "無茶",
          rt: "むちゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "茶",
          on: ["チャ", "サ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2021,
      kanji: "無茶苦茶",
      reading: "むちゃくちゃ",
      meanings: {
        ja: "無茶苦茶",
        en: "nonsensical; chaotic",
        zh: "乱七八糟",
        tw: "亂七八糟",
        ko: "엉망진창",
        vi: "hỗn độn",
        th: "ยุ่งเหยิง",
        my: "အဆင်မပြေသော",
        km: "រញ្ជួយរញ្ជាយ",
      },
      furigana: [
        {
          rb: "無茶苦茶",
          rt: "むちゃくちゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "茶",
          on: ["チャ", "サ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "苦",
          on: ["ク"],
          kun: [
            "くる.しい",
            "-ぐる.しい",
            "くる.しむ",
            "くる.しめる",
            "にが.い",
            "にが.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "茶",
          on: ["チャ", "サ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2022,
      kanji: "無用",
      reading: "むよう",
      meanings: {
        ja: "無用",
        en: "useless",
        zh: "无用",
        tw: "無用",
        ko: "쓸모없는",
        vi: "vô dụng",
        th: "ไม่มีประโยชน์",
        my: "အသုံးမဝင်သော",
        km: "គ្មានប្រយោជន៍",
      },
      furigana: [
        {
          rb: "無用",
          rt: "むよう",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2023,
      kanji: "明白",
      reading: "めいはく",
      meanings: {
        ja: "明白",
        en: "obvious",
        zh: "明显",
        tw: "明顯",
        ko: "명백한",
        vi: "rõ ràng",
        th: "ชัดเจน",
        my: "ပေါ်လွင်သော",
        km: "ច្បាស់លាស់",
      },
      furigana: [
        {
          rb: "明白",
          rt: "めいはく",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "白",
          on: ["ハク", "ビャク"],
          kun: ["しろ", "しら-", "しろ.い"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2024,
      kanji: "明瞭",
      reading: "めいりょう",
      meanings: {
        ja: "明瞭",
        en: "clear",
        zh: "清晰",
        tw: "清晰",
        ko: "명료한",
        vi: "rõ ràng",
        th: "ชัดเจน",
        my: "ရှင်းလင်းသော",
        km: "ច្បាស់",
      },
      furigana: [
        {
          rb: "明瞭",
          rt: "めいりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "瞭",
          on: ["リョウ"],
          kun: ["あきらか"],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2025,
      kanji: "明朗",
      reading: "めいろう",
      meanings: {
        ja: "明朗",
        en: "cheerful",
        zh: "开朗",
        tw: "開朗",
        ko: "명랑한",
        vi: "vui vẻ",
        th: "ร่าเริง",
        my: "ဝမ်းမြောက်သော",
        km: "រីករាយ",
      },
      furigana: [
        {
          rb: "明朗",
          rt: "めいろう",
        },
      ],
      kanjiInfo: [
        {
          char: "明",
          on: ["メイ", "ミョウ", "ミン"],
          kun: [
            "あ.かり",
            "あか.るい",
            "あか.るむ",
            "あか.らむ",
            "あき.らか",
            "あ.ける",
            "-あ.け",
            "あ.く",
            "あ.くる",
            "あ.かす",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "朗",
          on: ["ロウ"],
          kun: ["ほが.らか", "あき.らか"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2026,
      kanji: "猛烈",
      reading: "もうれつ",
      meanings: {
        ja: "猛烈",
        en: "fierce; intense",
        zh: "猛烈",
        tw: "猛烈",
        ko: "맹렬한",
        vi: "mãnh liệt",
        th: "รุนแรง",
        my: "ပြင်းထန်သော",
        km: "ខ្លាំង",
      },
      furigana: [
        {
          rb: "猛烈",
          rt: "もうれつ",
        },
      ],
      kanjiInfo: [
        {
          char: "猛",
          on: ["モウ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "烈",
          on: ["レツ"],
          kun: ["はげ.しい"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2027,
      kanji: "野生",
      reading: "やせい",
      meanings: {
        ja: "野生",
        en: "wild",
        zh: "野生",
        tw: "野生",
        ko: "야생의",
        vi: "hoang dã",
        th: "ป่า",
        my: "သဘာဝတောတွင်းရှိသော",
        km: "ព្រៃផ្សៃ",
      },
      furigana: [
        {
          rb: "野生",
          rt: "やせい",
        },
      ],
      kanjiInfo: [
        {
          char: "野",
          on: ["ヤ", "ショ"],
          kun: ["の", "の-"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 2028,
      kanji: "ヤング",
      reading: "ヤング",
      meanings: {
        ja: "ヤング",
        en: "young",
        zh: "年轻",
        tw: "年輕",
        ko: "젊은",
        vi: "trẻ",
        th: "หนุ่มสาว",
        my: "လူငယ်",
        km: "វ័យក្មេង",
      },
      furigana: [
        {
          rb: "ヤング",
          rt: "ヤング",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2029,
      kanji: "有益",
      reading: "ゆうえき",
      meanings: {
        ja: "有益",
        en: "beneficial",
        zh: "有益",
        tw: "有益",
        ko: "유익한",
        vi: "có lợi",
        th: "เป็นประโยชน์",
        my: "အကျိုးရှိသော",
        km: "មានប្រយោជន៍",
      },
      furigana: [
        {
          rb: "有益",
          rt: "ゆうえき",
        },
      ],
      kanjiInfo: [
        {
          char: "有",
          on: ["ユウ", "ウ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "益",
          on: ["エキ", "ヤク"],
          kun: ["ま.す"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2030,
      kanji: "勇敢",
      reading: "ゆうかん",
      meanings: {
        ja: "勇敢",
        en: "brave",
        zh: "勇敢",
        tw: "勇敢",
        ko: "용감한",
        vi: "dũng cảm",
        th: "กล้าหาญ",
        my: "သတ္တိရှိသော",
        km: "ក្លាហាន",
      },
      furigana: [
        {
          rb: "勇敢",
          rt: "ゆうかん",
        },
      ],
      kanjiInfo: [
        {
          char: "勇",
          on: ["ユウ"],
          kun: ["いさ.む"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "敢",
          on: ["カン"],
          kun: ["あ.えて", "あ.えない", "あ.えず"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2031,
      kanji: "優美",
      reading: "ゆうび",
      meanings: {
        ja: "優美",
        en: "graceful",
        zh: "优美",
        tw: "優美",
        ko: "우아한",
        vi: "duyên dáng",
        th: "งดงาม",
        my: "လှပသပ်ရပ်သော",
        km: "ស្រស់ស្អាត",
      },
      furigana: [
        {
          rb: "優美",
          rt: "ゆうび",
        },
      ],
      kanjiInfo: [
        {
          char: "優",
          on: ["ユウ", "ウ"],
          kun: ["やさ.しい", "すぐ.れる", "まさ.る"],
          strokes: 17,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "美",
          on: ["ビ", "ミ"],
          kun: ["うつく.しい"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2032,
      kanji: "有望",
      reading: "ゆうぼう",
      meanings: {
        ja: "有望",
        en: "promising",
        zh: "有前途",
        tw: "有前途",
        ko: "유망한",
        vi: "đầy triển vọng",
        th: "มีอนาคต",
        my: "အနာဂတ်ကောင်းသော",
        km: "មានអនាគតល្អ",
      },
      furigana: [
        {
          rb: "有望",
          rt: "ゆうぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "有",
          on: ["ユウ", "ウ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "望",
          on: ["ボウ", "モウ"],
          kun: ["のぞ.む", "もち"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2033,
      kanji: "有力",
      reading: "ゆうりょく",
      meanings: {
        ja: "有力",
        en: "influential",
        zh: "有影响力",
        tw: "有影響力",
        ko: "유력한",
        vi: "có ảnh hưởng",
        th: "ทรงอิทธิพล",
        my: "အာဏာရှိသော",
        km: "មានឥទ្ធិពល",
      },
      furigana: [
        {
          rb: "有力",
          rt: "ゆうりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "有",
          on: ["ユウ", "ウ"],
          kun: ["あ.る"],
          strokes: 6,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2034,
      kanji: "ユニーク",
      reading: "ユニーク",
      meanings: {
        ja: "ユニーク",
        en: "unique",
        zh: "独特",
        tw: "獨特",
        ko: "독특한",
        vi: "độc đáo",
        th: "ไม่เหมือนใคร",
        my: "ထူးခြားသော",
        km: "មានលក្ខណៈពិសេស",
      },
      furigana: [
        {
          rb: "ユニーク",
          rt: "ユニーク",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2035,
      kanji: "緩やか",
      reading: "ゆるやか",
      meanings: {
        ja: "緩やか",
        en: "gentle; slow",
        zh: "缓和",
        tw: "緩和",
        ko: "완만한",
        vi: "dịu dàng",
        th: "ค่อยเป็นค่อยไป",
        my: "နှေးကွေးသော",
        km: "ប៉ុនប៉ង",
      },
      furigana: [
        {
          rb: "緩やか",
          rt: "ゆるやか",
        },
      ],
      kanjiInfo: [
        {
          char: "緩",
          on: ["カン"],
          kun: ["ゆる.い", "ゆる.やか", "ゆる.む", "ゆる.める"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2036,
      kanji: "良好",
      reading: "りょうこう",
      meanings: {
        ja: "良好",
        en: "good",
        zh: "良好",
        tw: "良好",
        ko: "양호한",
        vi: "tốt",
        th: "ดี",
        my: "ကောင်းမွန်သော",
        km: "ល្អ",
      },
      furigana: [
        {
          rb: "良好",
          rt: "りょうこう",
        },
      ],
      kanjiInfo: [
        {
          char: "良",
          on: ["リョウ"],
          kun: ["よ.い", "-よ.い", "い.い", "-い.い"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2037,
      kanji: "良質",
      reading: "りょうしつ",
      meanings: {
        ja: "良質",
        en: "good quality",
        zh: "优质",
        tw: "優質",
        ko: "양질",
        vi: "chất lượng tốt",
        th: "คุณภาพดี",
        my: "အရည်အသွေးကောင်းသော",
        km: "គុណភាពល្អ",
      },
      furigana: [
        {
          rb: "良質",
          rt: "りょうしつ",
        },
      ],
      kanjiInfo: [
        {
          char: "良",
          on: ["リョウ"],
          kun: ["よ.い", "-よ.い", "い.い", "-い.い"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 2038,
      kanji: "ルーズ",
      reading: "ルーズ",
      meanings: {
        ja: "ルーズ",
        en: "loose; careless",
        zh: "松散",
        tw: "鬆散",
        ko: "느슨한",
        vi: "lỏng lẻo",
        th: "ไม่รัดกุม",
        my: "အပေါ်ယံ",
        km: "មិនប្រុងប្រយ័ត្ន",
      },
      furigana: [
        {
          rb: "ルーズ",
          rt: "ルーズ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2039,
      kanji: "冷酷",
      reading: "れいこく",
      meanings: {
        ja: "冷酷",
        en: "cruel",
        zh: "冷酷",
        tw: "冷酷",
        ko: "냉혹한",
        vi: "tàn nhẫn",
        th: "โหดร้าย",
        my: "စိုက်ထုတ်မရှိသော",
        km: "សាហាវ",
      },
      furigana: [
        {
          rb: "冷酷",
          rt: "れいこく",
        },
      ],
      kanjiInfo: [
        {
          char: "冷",
          on: ["レイ"],
          kun: [
            "つめ.たい",
            "ひ.える",
            "ひ.や",
            "ひ.ややか",
            "ひ.やす",
            "ひ.やかす",
            "さ.める",
            "さ.ます",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "酷",
          on: ["コク"],
          kun: ["ひど.い"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2040,
      kanji: "冷淡",
      reading: "れいたん",
      meanings: {
        ja: "冷淡",
        en: "cold; indifferent",
        zh: "冷淡",
        tw: "冷淡",
        ko: "냉담한",
        vi: "lạnh nhạt",
        th: "เย็นชา",
        my: "အေးမြသော",
        km: "អាក្រក់ចិត្ត",
      },
      furigana: [
        {
          rb: "冷淡",
          rt: "れいたん",
        },
      ],
      kanjiInfo: [
        {
          char: "冷",
          on: ["レイ"],
          kun: [
            "つめ.たい",
            "ひ.える",
            "ひ.や",
            "ひ.ややか",
            "ひ.やす",
            "ひ.やかす",
            "さ.める",
            "さ.ます",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "淡",
          on: ["タン"],
          kun: ["あわ.い"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2041,
      kanji: "華やか",
      reading: "はなやか",
      meanings: {
        ja: "華やか",
        en: "bright and beautiful",
        zh: "华丽",
        tw: "華麗",
        ko: "화려한",
        vi: "lộng lẫy",
        th: "หรูหรา",
        my: "အလှတရားပြည့်နှက်သော",
        km: "ស្រស់ស្អាត",
      },
      furigana: [
        {
          rb: "華やか",
          rt: "はなやか",
        },
      ],
      kanjiInfo: [
        {
          char: "華",
          on: ["カ", "ケ"],
          kun: ["はな"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2042,
      kanji: "遥か",
      reading: "はるか",
      meanings: {
        ja: "遥か",
        en: "far away",
        zh: "遥远",
        tw: "遙遠",
        ko: "아득한",
        vi: "xa xôi",
        th: "ไกลโพ้น",
        my: "ဝေးလံသော",
        km: "ឆ្ងាយ",
      },
      furigana: [
        {
          rb: "遥か",
          rt: "はるか",
        },
      ],
      kanjiInfo: [
        {
          char: "遥",
          on: ["ヨウ"],
          kun: ["はる.か"],
          strokes: 12,
          grade: 9,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2043,
      kanji: "万能",
      reading: "ばんのう",
      meanings: {
        ja: "万能",
        en: "all-purpose",
        zh: "万能",
        tw: "萬能",
        ko: "만능의",
        vi: "đa năng",
        th: "อเนกประสงค์",
        my: "အရာအားလုံးပြုနိုင်သော",
        km: "អាចប្រើបានគ្រប់យ៉ាង",
      },
      furigana: [
        {
          rb: "万能",
          rt: "ばんのう",
        },
      ],
      kanjiInfo: [
        {
          char: "万",
          on: ["マン", "バン"],
          kun: ["よろず"],
          strokes: 3,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2044,
      kanji: "悲惨",
      reading: "ひさん",
      meanings: {
        ja: "悲惨",
        en: "tragic; miserable",
        zh: "悲惨",
        tw: "悲慘",
        ko: "비참한",
        vi: "bi thảm",
        th: "น่าสังเวช",
        my: "ဆိုးရွားသော",
        km: "អាក្រក់",
      },
      furigana: [
        {
          rb: "悲惨",
          rt: "ひさん",
        },
      ],
      kanjiInfo: [
        {
          char: "悲",
          on: ["ヒ"],
          kun: ["かな.しい", "かな.しむ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "惨",
          on: ["サン", "ザン"],
          kun: ["みじ.め", "いた.む", "むご.い"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2045,
      kanji: "密か",
      reading: "ひそか",
      meanings: {
        ja: "密か",
        en: "secret",
        zh: "秘密",
        tw: "秘密",
        ko: "은밀한",
        vi: "bí mật",
        th: "ลับๆ",
        my: "လျှို့ဝှက်သော",
        km: "សម្ងាត់",
      },
      furigana: [
        {
          rb: "密か",
          rt: "ひそか",
        },
      ],
      kanjiInfo: [
        {
          char: "密",
          on: ["ミツ"],
          kun: ["ひそ.か"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 2046,
      kanji: "びっしょり",
      reading: "びっしょり",
      meanings: {
        ja: "びっしょり",
        en: "soaking wet",
        zh: "湿透",
        tw: "濕透",
        ko: "흠뻑 젖은",
        vi: "ướt sũng",
        th: "เปียกโชก",
        my: "စိုလွန်းသော",
        km: "សើម",
      },
      furigana: [
        {
          rb: "びっしょり",
          rt: "びっしょり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 2047,
      kanji: "必然",
      reading: "ひつぜん",
      meanings: {
        ja: "必然",
        en: "inevitable",
        zh: "必然",
        tw: "必然",
        ko: "필연적인",
        vi: "tất yếu",
        th: "หลีกเลี่ยงไม่ได้",
        my: "မလွတ်မြောက်နိုင်သော",
        km: "ចាំបាច់",
      },
      furigana: [
        {
          rb: "必然",
          rt: "ひつぜん",
        },
      ],
      kanjiInfo: [
        {
          char: "必",
          on: ["ヒツ"],
          kun: ["かなら.ず"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "然",
          on: ["ゼン", "ネン"],
          kun: ["しか", "しか.り", "しか.し", "さ"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2048,
      kanji: "人柄",
      reading: "ひとがら",
      meanings: {
        ja: "人柄",
        en: "character; personality",
        zh: "人品",
        tw: "人品",
        ko: "인품",
        vi: "tính cách",
        th: "นิสัย",
        my: "လူ့သဘောထား",
        km: "សភាពបុគ្គល",
      },
      furigana: [
        {
          rb: "人柄",
          rt: "ひとがら",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "柄",
          on: ["ヘイ"],
          kun: ["がら", "え", "つか"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
