export const n1part28 = {
  Lesson28: [
    {
      id: 1351,
      kanji: "十字路",
      reading: "じゅうじろ",
      meanings: {
        ja: "十字路",
        en: "crossroads; intersection",
        zh: "十字路口",
        tw: "十字路口",
        ko: "사거리",
        vi: "ngã tư",
        th: "ทางแยกสี่แยก",
        my: "လမ်းခွဲ (၄လမ်း)",
        km: "ចំណុចផ្លូវឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "十字路",
          rt: "じゅうじろ",
        },
      ],
      kanjiInfo: [
        {
          char: "十",
          on: ["ジュウ", "ジッ", "ジュッ"],
          kun: ["とお", "と", "そ"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "路",
          on: ["ロ", "ル"],
          kun: ["-じ", "みち"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1352,
      kanji: "執着",
      reading: "しゅうじゃく",
      meanings: {
        ja: "執着",
        en: "attachment; fixation",
        zh: "执着",
        tw: "執著",
        ko: "집착",
        vi: "chấp trước",
        th: "ความยึดติด",
        my: "မက်ကြိုးလမ်းတယ်",
        km: "ការចិត្តចងក្រង",
      },
      furigana: [
        {
          rb: "執着",
          rt: "しゅうじゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "執",
          on: ["シツ", "シュウ"],
          kun: ["と.る"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1353,
      kanji: "執着",
      reading: "しゅうちゃく",
      meanings: {
        ja: "執着",
        en: "attachment; fixation",
        zh: "执着",
        tw: "執著",
        ko: "집착",
        vi: "chấp trước",
        th: "ความยึดติด",
        my: "မက်ကြိုးလမ်းတယ်",
        km: "ការចិត្តចងក្រង",
      },
      furigana: [
        {
          rb: "執着",
          rt: "しゅうちゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "執",
          on: ["シツ", "シュウ"],
          kun: ["と.る"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1354,
      kanji: "重複",
      reading: "じゅうふく",
      meanings: {
        ja: "重複",
        en: "duplication; overlap",
        zh: "重复",
        tw: "重複",
        ko: "중복",
        vi: "trùng lặp",
        th: "ซ้ำซ้อน",
        my: "တူညီမှု/တင်ပို",
        km: "ភាពស្ទួន",
      },
      furigana: [
        {
          rb: "重複",
          rt: "じゅうふく",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "複",
          on: ["フク"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1355,
      kanji: "収容",
      reading: "しゅうよう",
      meanings: {
        ja: "収容",
        en: "accommodation; housing",
        zh: "收容",
        tw: "收容",
        ko: "수용",
        vi: "chứa; thu dung",
        th: "รองรับ; จัดให้อยู่",
        my: "အေးခိုပေးခြင်း",
        km: "ទ្រទ្រង់ស្នាក់នៅ",
      },
      furigana: [
        {
          rb: "収容",
          rt: "しゅうよう",
        },
      ],
      kanjiInfo: [
        {
          char: "収",
          on: ["シュウ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "容",
          on: ["ヨウ"],
          kun: ["い.れる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1356,
      kanji: "従来",
      reading: "じゅうらい",
      meanings: {
        ja: "従来",
        en: "up to now; conventional",
        zh: "以往；传统的",
        tw: "以往；傳統的",
        ko: "종래; 기존",
        vi: "từ trước đến nay",
        th: "ตามเดิม; แต่ก่อนมา",
        my: "ယခင်ကတည်းဟူ၍",
        km: "តាមរបៀបពីមុន",
      },
      furigana: [
        {
          rb: "従来",
          rt: "じゅうらい",
        },
      ],
      kanjiInfo: [
        {
          char: "従",
          on: ["ジュウ", "ショウ", "ジュ"],
          kun: ["したが.う", "したが.える", "より"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "来",
          on: ["ライ", "タイ"],
          kun: [
            "く.る",
            "きた.る",
            "きた.す",
            "き.たす",
            "き.たる",
            "き",
            "こ",
          ],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1357,
      kanji: "守衛",
      reading: "しゅえい",
      meanings: {
        ja: "守衛",
        en: "security guard",
        zh: "门卫；保安",
        tw: "門衛；保全",
        ko: "수위; 경비원",
        vi: "bảo vệ",
        th: "ยาม; รปภ.",
        my: "လုံခြုံရေးယာမ",
        km: "យាមសន្តិសុខ",
      },
      furigana: [
        {
          rb: "守衛",
          rt: "しゅえい",
        },
      ],
      kanjiInfo: [
        {
          char: "守",
          on: ["シュ", "ス"],
          kun: ["まも.る", "まも.り", "もり", "-もり", "かみ"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "衛",
          on: ["エイ", "エ"],
          kun: [],
          strokes: 16,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1358,
      kanji: "主演",
      reading: "しゅえん",
      meanings: {
        ja: "主演",
        en: "starring; leading role",
        zh: "主演",
        tw: "主演",
        ko: "주연",
        vi: "đóng vai chính",
        th: "แสดงนำ",
        my: "အဓိကဝတ်မြတ်",
        km: "តួឯក",
      },
      furigana: [
        {
          rb: "主演",
          rt: "しゅえん",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "演",
          on: ["エン"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1359,
      kanji: "主観",
      reading: "しゅかん",
      meanings: {
        ja: "主観",
        en: "subjectivity",
        zh: "主观",
        tw: "主觀",
        ko: "주관",
        vi: "chủ quan",
        th: "เชิงอัตวิสัย",
        my: "ပုဂ္ဂိုလ်ရေးမြင်ကွင်း",
        km: "主관/ជោគជ័យ? -> 主觀: មតិយ៉ាងផ្ទាល់ខ្លួន",
      },
      furigana: [
        {
          rb: "主観",
          rt: "しゅかん",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "観",
          on: ["カン"],
          kun: ["み.る", "しめ.す"],
          strokes: 18,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1360,
      kanji: "修行",
      reading: "しゅぎょう",
      meanings: {
        ja: "修行（鍛錬）",
        en: "training; ascetic practice",
        zh: "修行；修炼",
        tw: "修行；修煉",
        ko: "수행; 수련",
        vi: "tu luyện; rèn luyện",
        th: "การฝึกฝน (บำเพ็ญ)",
        my: "သင်ကြားစဉ်/သီလဆောက်",
        km: "ការប្រឹក្សាបណ្តុះបណ្តា",
      },
      furigana: [
        {
          rb: "修行",
          rt: "しゅぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "修",
          on: ["シュウ", "シュ"],
          kun: ["おさ.める", "おさ.まる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1361,
      kanji: "塾",
      reading: "じゅく",
      meanings: {
        ja: "塾",
        en: "cram school",
        zh: "补习班",
        tw: "補習班",
        ko: "학원(주로 입시)",
        vi: "lò luyện thi",
        th: "โรงเรียนกวดวิชา",
        my: "စာသင်စု",
        km: "សាលាបង្រៀនបន្ថែម",
      },
      furigana: [
        {
          rb: "塾",
          rt: "じゅく",
        },
      ],
      kanjiInfo: [
        {
          char: "塾",
          on: ["ジュク"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1362,
      kanji: "祝賀",
      reading: "しゅくが",
      meanings: {
        ja: "祝賀",
        en: "celebration; congratulation",
        zh: "祝贺",
        tw: "祝賀",
        ko: "축하",
        vi: "chúc mừng",
        th: "การเฉลิมฉลอง",
        my: "အခမ်းအနားဆင်နွှဲ",
        km: "ពិធីអបអរសាទរ",
      },
      furigana: [
        {
          rb: "祝賀",
          rt: "しゅくが",
        },
      ],
      kanjiInfo: [
        {
          char: "祝",
          on: ["シュク", "シュウ"],
          kun: ["いわ.う"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "賀",
          on: ["ガ"],
          kun: [],
          strokes: 12,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1363,
      kanji: "宿命",
      reading: "しゅくめい",
      meanings: {
        ja: "宿命",
        en: "fate; destiny",
        zh: "宿命",
        tw: "宿命",
        ko: "숙명",
        vi: "định mệnh",
        th: "ชะตากรรม",
        my: "ကံစီရင်",
        km: "វាសនា",
      },
      furigana: [
        {
          rb: "宿命",
          rt: "しゅくめい",
        },
      ],
      kanjiInfo: [
        {
          char: "宿",
          on: ["シュク"],
          kun: ["やど", "やど.る", "やど.す"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1364,
      kanji: "手芸",
      reading: "しゅげい",
      meanings: {
        ja: "手芸",
        en: "handicrafts; needlework",
        zh: "手工艺",
        tw: "手工藝",
        ko: "수공예",
        vi: "thủ công mỹ nghệ",
        th: "งานฝีมือ",
        my: "လက်မှုပညာ",
        km: "ក្បាច់ដៃ",
      },
      furigana: [
        {
          rb: "手芸",
          rt: "しゅげい",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "芸",
          on: ["ゲイ", "ウン"],
          kun: ["う.える", "のり", "わざ"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1365,
      kanji: "主権",
      reading: "しゅけん",
      meanings: {
        ja: "主権",
        en: "sovereignty",
        zh: "主权",
        tw: "主權",
        ko: "주권",
        vi: "chủ quyền",
        th: "อธิปไตย",
        my: "ဆွေလက္ခဏာ? -> အာဏာပိုင်ခွင့်",
        km: "អធិបតេយ្យភាព",
      },
      furigana: [
        {
          rb: "主権",
          rt: "しゅけん",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "権",
          on: ["ケン", "ゴン"],
          kun: ["おもり", "かり", "はか.る"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1366,
      kanji: "主催",
      reading: "しゅさい",
      meanings: {
        ja: "主催",
        en: "hosting; sponsorship",
        zh: "主办",
        tw: "主辦",
        ko: "주최",
        vi: "chủ trì; tổ chức",
        th: "เป็นเจ้าภาพจัด",
        my: "ဦးစီးကျင်းပမှု",
        km: "ជាអ្នកប្រារព្ធ",
      },
      furigana: [
        {
          rb: "主催",
          rt: "しゅさい",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "催",
          on: ["サイ"],
          kun: ["もよう.す", "もよお.す"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1367,
      kanji: "取材",
      reading: "しゅざい",
      meanings: {
        ja: "取材",
        en: "news gathering; coverage",
        zh: "采访取材",
        tw: "採訪取材",
        ko: "취재",
        vi: "thu thập tư liệu",
        th: "เก็บข้อมูลข่าว",
        my: "သတင်းရှာဖွေမှု",
        km: "ការប្រមូលព័ត៌មាន",
      },
      furigana: [
        {
          rb: "取材",
          rt: "しゅざい",
        },
      ],
      kanjiInfo: [
        {
          char: "取",
          on: ["シュ"],
          kun: ["と.る", "と.り", "と.り-", "とり", "-ど.り"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "材",
          on: ["ザイ"],
          kun: [],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1368,
      kanji: "趣旨",
      reading: "しゅし",
      meanings: {
        ja: "趣旨",
        en: "purpose; intent",
        zh: "宗旨；要旨",
        tw: "宗旨；主旨",
        ko: "취지",
        vi: "ý hướng; mục đích",
        th: "เจตนารมณ์",
        my: "ဝိစိတျာ/ရည္ရွယ်ချက်",
        km: "គោលបំណង",
      },
      furigana: [
        {
          rb: "趣旨",
          rt: "しゅし",
        },
      ],
      kanjiInfo: [
        {
          char: "趣",
          on: ["シュ"],
          kun: ["おもむき", "おもむ.く"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "旨",
          on: ["シ"],
          kun: ["むね", "うま.い"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1369,
      kanji: "主食",
      reading: "しゅしょく",
      meanings: {
        ja: "主食",
        en: "staple food",
        zh: "主食",
        tw: "主食",
        ko: "주식(주요 음식)",
        vi: "lương thực chính",
        th: "อาหารหลัก",
        my: "အခြေခံအစားအစာ",
        km: "អាហារចំបង",
      },
      furigana: [
        {
          rb: "主食",
          rt: "しゅしょく",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "食",
          on: ["ショク", "ジキ"],
          kun: ["く.う", "く.らう", "た.べる", "は.む"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1370,
      kanji: "主人公",
      reading: "しゅじんこう",
      meanings: {
        ja: "主人公",
        en: "protagonist; main character",
        zh: "主人公",
        tw: "主人翁",
        ko: "주인공",
        vi: "nhân vật chính",
        th: "ตัวเอก",
        my: "အဓိကဇာတ်ကောင်",
        km: "តួឯក",
      },
      furigana: [
        {
          rb: "主人公",
          rt: "しゅじんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "公",
          on: ["コウ", "ク"],
          kun: ["おおやけ"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1371,
      kanji: "主体",
      reading: "しゅたい",
      meanings: {
        ja: "主体",
        en: "main body; subject",
        zh: "主体",
        tw: "主體",
        ko: "주체",
        vi: "chủ thể",
        th: "องค์ประธาน/แกนหลัก",
        my: "အဓိကကဏ္ဍ",
        km: "អង្គចម្បង",
      },
      furigana: [
        {
          rb: "主体",
          rt: "しゅたい",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "体",
          on: ["タイ", "テイ"],
          kun: ["からだ", "かたち"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1372,
      kanji: "主題",
      reading: "しゅだい",
      meanings: {
        ja: "主題",
        en: "theme; subject",
        zh: "主题",
        tw: "主題",
        ko: "주제",
        vi: "chủ đề",
        th: "หัวข้อ",
        my: "အဓိကအကြောင်းအရာ",
        km: "ប្រធានបទ",
      },
      furigana: [
        {
          rb: "主題",
          rt: "しゅだい",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "題",
          on: ["ダイ"],
          kun: [],
          strokes: 18,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1373,
      kanji: "出演",
      reading: "しゅつえん",
      meanings: {
        ja: "出演",
        en: "appearance (on stage/screen)",
        zh: "出演",
        tw: "出演",
        ko: "출연",
        vi: "biểu diễn; xuất hiện",
        th: "แสดง (บนเวที/จอ)",
        my: "ဖျော်ဖြေပွဲတင်ဆက်",
        km: "ការចូលរួមលេង",
      },
      furigana: [
        {
          rb: "出演",
          rt: "しゅつえん",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "演",
          on: ["エン"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1374,
      kanji: "出血",
      reading: "しゅっけつ",
      meanings: {
        ja: "出血",
        en: "bleeding",
        zh: "出血",
        tw: "出血",
        ko: "출혈",
        vi: "chảy máu",
        th: "เลือดออก",
        my: "သွေးယို",
        km: "ឈាមហូរ",
      },
      furigana: [
        {
          rb: "出血",
          rt: "しゅっけつ",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "血",
          on: ["ケツ"],
          kun: ["ち"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1375,
      kanji: "出現",
      reading: "しゅつげん",
      meanings: {
        ja: "出現",
        en: "appearance; emergence",
        zh: "出现",
        tw: "出現",
        ko: "출현",
        vi: "xuất hiện",
        th: "ปรากฏขึ้น",
        my: "ပေါ်ထွက်လာမှု",
        km: "បង្ហាញខ្លួន",
      },
      furigana: [
        {
          rb: "出現",
          rt: "しゅつげん",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "現",
          on: ["ゲン"],
          kun: ["あらわ.れる", "あらわ.す", "うつつ", "うつ.つ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1376,
      kanji: "出産",
      reading: "しゅっさん",
      meanings: {
        ja: "出産",
        en: "childbirth; delivery",
        zh: "分娩；生产",
        tw: "生產；分娩",
        ko: "출산",
        vi: "sinh nở",
        th: "การคลอดบุตร",
        my: "ဖွားမြင်ခြင်း",
        km: "សម្រាលកូន",
      },
      furigana: [
        {
          rb: "出産",
          rt: "しゅっさん",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1377,
      kanji: "出社",
      reading: "しゅっしゃ",
      meanings: {
        ja: "出社（出勤）",
        en: "going to work",
        zh: "上班",
        tw: "上班",
        ko: "출사/출근",
        vi: "đi làm",
        th: "ไปทำงาน",
        my: "အလုပ်သို့ရောက်",
        km: "ទៅធ្វើការ",
      },
      furigana: [
        {
          rb: "出社",
          rt: "しゅっしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "社",
          on: ["シャ"],
          kun: ["やしろ"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1378,
      kanji: "出生",
      reading: "しゅっしょう",
      meanings: {
        ja: "出生",
        en: "birth",
        zh: "出生",
        tw: "出生",
        ko: "출생",
        vi: "sự sinh ra",
        th: "การเกิด",
        my: "မွေးဖွားခြင်း",
        km: "កំណើត",
      },
      furigana: [
        {
          rb: "出生",
          rt: "しゅっしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1379,
      kanji: "出生",
      reading: "しゅっせい",
      meanings: {
        ja: "出生",
        en: "birth",
        zh: "出生",
        tw: "出生",
        ko: "출생",
        vi: "sự sinh ra",
        th: "การเกิด",
        my: "မွေးဖွားခြင်း",
        km: "កំណើត",
      },
      furigana: [
        {
          rb: "出生",
          rt: "しゅっせい",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1380,
      kanji: "微量",
      reading: "びりょう",
      meanings: {
        ja: "微量",
        en: "trace amount; tiny quantity",
        zh: "微量",
        tw: "微量",
        ko: "미량",
        vi: "vi lượng",
        th: "ปริมาณน้อยมาก",
        my: "အလွန်နည်းငယ်",
        km: "បរិមាណតិចតួច",
      },
      furigana: [
        {
          rb: "微量",
          rt: "びりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "微",
          on: ["ビ"],
          kun: ["かす.か"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "量",
          on: ["リョウ"],
          kun: ["はか.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1381,
      kanji: "昼飯",
      reading: "ひるめし",
      meanings: {
        ja: "昼飯（昼食）",
        en: "lunch",
        zh: "午饭",
        tw: "午飯",
        ko: "점심",
        vi: "bữa trưa",
        th: "อาหารกลางวัน",
        my: "နေ့လည်စာ",
        km: "អាហារថ្ងៃត្រង់",
      },
      furigana: [
        {
          rb: "昼飯",
          rt: "ひるめし",
        },
      ],
      kanjiInfo: [
        {
          char: "昼",
          on: ["チュウ"],
          kun: ["ひる"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "飯",
          on: ["ハン"],
          kun: ["めし"],
          strokes: 12,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1382,
      kanji: "比例",
      reading: "ひれい",
      meanings: {
        ja: "比例",
        en: "proportion; proportionality",
        zh: "比例",
        tw: "比例",
        ko: "비례",
        vi: "tỷ lệ thuận",
        th: "สัดส่วน; แปรผันตรง",
        my: "အချိုးအစား",
        km: "សមាមាត្រ",
      },
      furigana: [
        {
          rb: "比例",
          rt: "ひれい",
        },
      ],
      kanjiInfo: [
        {
          char: "比",
          on: ["ヒ"],
          kun: ["くら.べる"],
          strokes: 4,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "例",
          on: ["レイ"],
          kun: ["たと.える"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1383,
      kanji: "疲労",
      reading: "ひろう",
      meanings: {
        ja: "疲労",
        en: "fatigue; exhaustion",
        zh: "疲劳",
        tw: "疲勞",
        ko: "피로",
        vi: "mệt mỏi",
        th: "ความเหนื่อยล้า",
        my: "ပင်ပန်းနွမ်းနယ်",
        km: "ភាពនឿយហត់",
      },
      furigana: [
        {
          rb: "疲労",
          rt: "ひろう",
        },
      ],
      kanjiInfo: [
        {
          char: "疲",
          on: ["ヒ"],
          kun: ["つか.れる", "-づか.れ", "つか.らす"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "労",
          on: ["ロウ"],
          kun: [
            "ろう.する",
            "いたわ.る",
            "いた.ずき",
            "ねぎら",
            "つか.れる",
            "ねぎら.う",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1384,
      kanji: "貧困",
      reading: "ひんこん",
      meanings: {
        ja: "貧困",
        en: "poverty",
        zh: "贫困",
        tw: "貧困",
        ko: "빈곤",
        vi: "nghèo đói",
        th: "ความยากจน",
        my: "ဆင်းရဲမှု",
        km: "ភាពក្រីក្រ",
      },
      furigana: [
        {
          rb: "貧困",
          rt: "ひんこん",
        },
      ],
      kanjiInfo: [
        {
          char: "貧",
          on: ["ヒン", "ビン"],
          kun: ["まず.しい"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "困",
          on: ["コン"],
          kun: ["こま.る"],
          strokes: 7,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1385,
      kanji: "品質",
      reading: "ひんしつ",
      meanings: {
        ja: "品質",
        en: "quality (product/service)",
        zh: "品质",
        tw: "品質",
        ko: "품질",
        vi: "chất lượng",
        th: "คุณภาพ",
        my: "အရည်အသွေး",
        km: "គុណភាព",
      },
      furigana: [
        {
          rb: "品質",
          rt: "ひんしつ",
        },
      ],
      kanjiInfo: [
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "質",
          on: ["シツ", "シチ", "チ"],
          kun: ["たち", "ただ.す", "もと", "わりふ"],
          strokes: 15,
          grade: 5,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1386,
      kanji: "品種",
      reading: "ひんしゅ",
      meanings: {
        ja: "品種",
        en: "type; variety",
        zh: "品种",
        tw: "品種",
        ko: "품종",
        vi: "giống; loại",
        th: "สายพันธุ์/ประเภท",
        my: "အမျိုးအစား",
        km: "ពូជ/ប្រភេទ",
      },
      furigana: [
        {
          rb: "品種",
          rt: "ひんしゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "種",
          on: ["シュ"],
          kun: ["たね", "-ぐさ"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1387,
      kanji: "ヒント",
      reading: "ヒント",
      meanings: {
        ja: "ヒント",
        en: "hint; clue",
        zh: "提示；线索",
        tw: "提示；線索",
        ko: "힌트",
        vi: "gợi ý",
        th: "คำใบ้",
        my: "ချanyon? -> အကြံပြုချက်သေးသေး",
        km: "គំនិតព្រមាន",
      },
      furigana: [
        {
          rb: "ヒント",
          rt: "ヒント",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1388,
      kanji: "ファイト",
      reading: "ファイト",
      meanings: {
        ja: "ファイト",
        en: "fight; fighting spirit",
        zh: "斗志；加油",
        tw: "鬥志；加油",
        ko: "파이팅; 투지",
        vi: "chiến đấu; cố lên",
        th: "สู้ ๆ",
        my: "ဒုက္ခကို ခံစား၍ တိုက်စစ်",
        km: "សម្ដីលើកទឹកចិត្ត",
      },
      furigana: [
        {
          rb: "ファイト",
          rt: "ファイト",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1389,
      kanji: "ファイル",
      reading: "ファイル",
      meanings: {
        ja: "ファイル",
        en: "file (folder)",
        zh: "文件夹",
        tw: "資料夾",
        ko: "파일",
        vi: "tập hồ sơ",
        th: "แฟ้มเอกสาร",
        my: "ဖိုင်/စာရင်းကဒ်",
        km: "ឯកសារក្រដាស",
      },
      furigana: [
        {
          rb: "ファイル",
          rt: "ファイル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1390,
      kanji: "ファン",
      reading: "ファン",
      meanings: {
        ja: "ファン",
        en: "fan (enthusiast)",
        zh: "粉丝；迷",
        tw: "粉絲；迷",
        ko: "팬",
        vi: "người hâm mộ",
        th: "แฟนคลับ",
        my: "ရှည်လျားပရိသတ်",
        km: "អ្នកគាំទ្រ",
      },
      furigana: [
        {
          rb: "ファン",
          rt: "ファン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1391,
      kanji: "フィルタ",
      reading: "フィルタ",
      meanings: {
        ja: "フィルタ",
        en: "filter",
        zh: "滤器；过滤器",
        tw: "濾器；濾網",
        ko: "필터",
        vi: "bộ lọc",
        th: "ตัวกรอง",
        my: "စစ်ထုတ်ကိရိယာ",
        km: "តម្រង",
      },
      furigana: [
        {
          rb: "フィルタ",
          rt: "フィルタ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1392,
      kanji: "封",
      reading: "ふう",
      meanings: {
        ja: "封（封をする）",
        en: "seal; sealing",
        zh: "封；封缄",
        tw: "封；封緘",
        ko: "봉(봉하다)",
        vi: "niêm phong",
        th: "ผนึก/ปิดผนึก",
        my: "မုဒိမ်းတံဆိပ်? -> မှတ်တံဆိပ်ပိတ်",
        km: "បិទមេដៃ",
      },
      furigana: [
        {
          rb: "封",
          rt: "ふう",
        },
      ],
      kanjiInfo: [
        {
          char: "封",
          on: ["フウ", "ホウ"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1393,
      kanji: "封鎖",
      reading: "ふうさ",
      meanings: {
        ja: "封鎖",
        en: "blockade; lockdown",
        zh: "封锁",
        tw: "封鎖",
        ko: "봉쇄",
        vi: "ph phong toả",
        th: "ปิดล้อม/ปิดกั้น",
        my: "ပိတ်ဆိုင်း",
        km: "បិទទ្វារ/បិទផ្លូវ",
      },
      furigana: [
        {
          rb: "封鎖",
          rt: "ふうさ",
        },
      ],
      kanjiInfo: [
        {
          char: "封",
          on: ["フウ", "ホウ"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "鎖",
          on: ["サ"],
          kun: ["くさり", "とざ.す"],
          strokes: 18,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1394,
      kanji: "風車",
      reading: "ふうしゃ",
      meanings: {
        ja: "風車",
        en: "windmill",
        zh: "风车",
        tw: "風車",
        ko: "풍차",
        vi: "cối xay gió",
        th: "กังหันลม",
        my: "လေလှိုင်းစက်",
        km: "កង្ហារ​ខ្យល់",
      },
      furigana: [
        {
          rb: "風車",
          rt: "ふうしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1395,
      kanji: "風習",
      reading: "ふうしゅう",
      meanings: {
        ja: "風習",
        en: "custom; tradition",
        zh: "风俗习惯",
        tw: "風俗習慣",
        ko: "풍습",
        vi: "phong tục",
        th: "ขนบธรรมเนียม",
        my: "အလေ့အထ",
        km: "ទម្លាប់",
      },
      furigana: [
        {
          rb: "風習",
          rt: "ふうしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "習",
          on: ["シュウ", "ジュ"],
          kun: ["なら.う", "なら.い"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1396,
      kanji: "風俗",
      reading: "ふうぞく",
      meanings: {
        ja: "風俗（習慣）",
        en: "manners; customs",
        zh: "风俗",
        tw: "風俗",
        ko: "풍속",
        vi: "phong tục; lối sống",
        th: "ขนบธรรมเนียม",
        my: "ရိုးရာထုံးတမ်း",
        km: "ទម្លាប់សង្គម",
      },
      furigana: [
        {
          rb: "風俗",
          rt: "ふうぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "俗",
          on: ["ゾク"],
          kun: [],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1397,
      kanji: "ブーツ",
      reading: "ブーツ",
      meanings: {
        ja: "ブーツ",
        en: "boots",
        zh: "靴靴？→靴子",
        tw: "長靴/靴子",
        ko: "부츠",
        vi: "ủng/giàyบูท",
        th: "รองเท้าบูท",
        my: "ဘုတ်စီးဖိနပ်",
        km: "ស្បែកជើងប៊ូត",
      },
      furigana: [
        {
          rb: "ブーツ",
          rt: "ブーツ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1398,
      kanji: "風土",
      reading: "ふうど",
      meanings: {
        ja: "風土",
        en: "natural features; climate & culture",
        zh: "风土",
        tw: "風土",
        ko: "풍토",
        vi: "phong thổ",
        th: "ภูมิประเทศและวัฒนธรรมท้องถิ่น",
        my: "ဒေသဆိုင်ရာ လေယာဉ်... → ပတ်ဝန်းကျင်လက္ခဏာ",
        km: "ធម្មជាតិតំបន់",
      },
      furigana: [
        {
          rb: "風土",
          rt: "ふうど",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "土",
          on: ["ド", "ト"],
          kun: ["つち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1399,
      kanji: "ブーム",
      reading: "ブーム",
      meanings: {
        ja: "ブーム",
        en: "boom; craze",
        zh: "热潮",
        tw: "熱潮；風潮",
        ko: "붐; 유행",
        vi: "cơn sốt; trào lưu",
        th: "กระแสฮิต",
        my: "လူကြိုက်အားပေးလှုပ်ရှားမှု",
        km: "លំហូរខ្លាំង",
      },
      furigana: [
        {
          rb: "ブーム",
          rt: "ブーム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1400,
      kanji: "フォーム",
      reading: "フォーム",
      meanings: {
        ja: "フォーム",
        en: "form; format",
        zh: "表单；形式",
        tw: "表單；形式",
        ko: "폼; 형식",
        vi: "mẫu; hình thức",
        th: "แบบฟอร์ม; รูปแบบ",
        my: "ဖောင်; ပုံစံ",
        km: "សំបុត្រ/ទម្រង់",
      },
      furigana: [
        {
          rb: "フォーム",
          rt: "フォーム",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
