export const n1part9 = {
  Lesson9: [
    {
      id: 401,
      kanji: "エアメール",
      reading: "エアメール",
      meanings: {
        ja: "エアメール",
        en: "airmail",
        zh: "航空邮件",
        tw: "航空郵件",
        ko: "항공우편",
        vi: "thư hàng không",
        th: "ไปรษณีย์อากาศ",
        my: "လေကြောင်းလျင်မြန်စာ",
        km: "សំបុត្រតាមយន្តហោះ",
      },
      furigana: [
        {
          rb: "エアメール",
          rt: "エアメール",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 402,
      kanji: "英字",
      reading: "えいじ",
      meanings: {
        ja: "英字",
        en: "English letter (alphabet)",
        zh: "英文字母",
        tw: "英文字母",
        ko: "영문자",
        vi: "chữ cái tiếng Anh",
        th: "ตัวอักษรภาษาอังกฤษ",
        my: "အင်္ဂလိပ်အက္ခရာ",
        km: "អក្សរអង់គ្លេស",
      },
      furigana: [
        {
          rb: "英字",
          rt: "えいじ",
        },
      ],
      kanjiInfo: [
        {
          char: "英",
          on: ["エイ"],
          kun: ["はなぶさ"],
          strokes: 8,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "字",
          on: ["ジ"],
          kun: ["あざ", "あざな", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 403,
      kanji: "映写",
      reading: "えいしゃ",
      meanings: {
        ja: "映写",
        en: "projection",
        zh: "放映",
        tw: "放映/投影",
        ko: "영사",
        vi: "trình chiếu",
        th: "ฉายภาพ",
        my: "ရုပ်ရှင်ချန်ပြခြင်း",
        km: "បញ្ចាំង",
      },
      furigana: [
        {
          rb: "映写",
          rt: "えいしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "映",
          on: ["エイ"],
          kun: ["うつ.る", "うつ.す", "は.える", "-ば.え"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "写",
          on: ["シャ", "ジャ"],
          kun: ["うつ.す", "うつ.る", "うつ-", "うつ.し"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 404,
      kanji: "映像",
      reading: "えいぞう",
      meanings: {
        ja: "映像",
        en: "image (on a screen); video",
        zh: "影像；视频",
        tw: "影像；影片",
        ko: "영상",
        vi: "hình ảnh; video",
        th: "ภาพ/วิดีโอ",
        my: "ရုပ်ပုံ/ဗီဒီယို",
        km: "រូបភាព; វីដេអូ",
      },
      furigana: [
        {
          rb: "映像",
          rt: "えいぞう",
        },
      ],
      kanjiInfo: [
        {
          char: "映",
          on: ["エイ"],
          kun: ["うつ.る", "うつ.す", "は.える", "-ば.え"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "像",
          on: ["ゾウ"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 405,
      kanji: "英雄",
      reading: "えいゆう",
      meanings: {
        ja: "英雄",
        en: "hero",
        zh: "英雄",
        tw: "英雄",
        ko: "영웅",
        vi: "anh hùng",
        th: "วีรบุรุษ",
        my: "သူရဲကောင်း",
        km: "វីរបុរស",
      },
      furigana: [
        {
          rb: "英雄",
          rt: "えいゆう",
        },
      ],
      kanjiInfo: [
        {
          char: "英",
          on: ["エイ"],
          kun: ["はなぶさ"],
          strokes: 8,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "雄",
          on: ["ユウ"],
          kun: ["お-", "おす", "おん"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 406,
      kanji: "液",
      reading: "えき",
      meanings: {
        ja: "液",
        en: "liquid",
        zh: "液体",
        tw: "液體",
        ko: "액체",
        vi: "chất lỏng",
        th: "ของเหลว",
        my: "ဓာတ်ရည်/ရည်",
        km: "រាវ",
      },
      furigana: [
        {
          rb: "液",
          rt: "えき",
        },
      ],
      kanjiInfo: [
        {
          char: "液",
          on: ["エキ"],
          kun: [],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 407,
      kanji: "閲覧",
      reading: "えつらん",
      meanings: {
        ja: "閲覧",
        en: "inspection; browsing",
        zh: "阅览；查看",
        tw: "閱覽；瀏覽",
        ko: "열람",
        vi: "xem; duyệt",
        th: "การอ่าน/ตรวจดู",
        my: "ဖတ်ရှုခြင်း",
        km: "អានពិនិត្យ",
      },
      furigana: [
        {
          rb: "閲覧",
          rt: "えつらん",
        },
      ],
      kanjiInfo: [
        {
          char: "閲",
          on: ["エツ"],
          kun: ["けみ.する"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "覧",
          on: ["ラン"],
          kun: ["み.る"],
          strokes: 17,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 408,
      kanji: "獲物",
      reading: "えもの",
      meanings: {
        ja: "獲物",
        en: "prey; catch",
        zh: "猎物",
        tw: "獵物",
        ko: "먹잇감; 사냥감",
        vi: "con mồi",
        th: "เหยื่อ/ของล่า",
        my: "အမဲစာ",
        km: "គោលដៅប្រមាញ់",
      },
      furigana: [
        {
          rb: "獲物",
          rt: "えもの",
        },
      ],
      kanjiInfo: [
        {
          char: "獲",
          on: ["カク"],
          kun: ["え.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 409,
      kanji: "襟",
      reading: "えり",
      meanings: {
        ja: "襟",
        en: "collar",
        zh: "衣领",
        tw: "衣領",
        ko: "깃; 칼라",
        vi: "cổ áo",
        th: "ปกเสื้อ",
        my: "အင်္ကျီလည်ပင်း",
        km: "កអាវ",
      },
      furigana: [
        {
          rb: "襟",
          rt: "えり",
        },
      ],
      kanjiInfo: [
        {
          char: "襟",
          on: ["キン"],
          kun: ["えり"],
          strokes: 18,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 410,
      kanji: "縁側",
      reading: "えんがわ",
      meanings: {
        ja: "縁側",
        en: "engawa (veranda)",
        zh: "日式走廊（緣側）",
        tw: "緣側（日式簷廊）",
        ko: "엔가와(일식 툇마루)",
        vi: "hiên nhà kiểu Nhật (engawa)",
        th: "เฉลียงแบบญี่ปุ่น",
        my: "ဂျပန်ပေါင်မုခ်",
        km: "របងសែន (Engawa)",
      },
      furigana: [
        {
          rb: "縁側",
          rt: "えんがわ",
        },
      ],
      kanjiInfo: [
        {
          char: "縁",
          on: ["エン", "-ネン"],
          kun: ["ふち", "ふち.どる", "ゆかり", "よすが", "へり", "えにし"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "側",
          on: ["ソク"],
          kun: ["かわ", "がわ", "そば"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 411,
      kanji: "沿岸",
      reading: "えんがん",
      meanings: {
        ja: "沿岸",
        en: "coast",
        zh: "沿岸",
        tw: "沿岸",
        ko: "연안",
        vi: "ven biển",
        th: "ชายฝั่ง",
        my: "ကမ်းရိုးတန်း",
        km: "តំបន់តាមឆ្នេរ",
      },
      furigana: [
        {
          rb: "沿岸",
          rt: "えんがん",
        },
      ],
      kanjiInfo: [
        {
          char: "沿",
          on: ["エン"],
          kun: ["そ.う", "-ぞ.い"],
          strokes: 8,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "岸",
          on: ["ガン"],
          kun: ["きし"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 412,
      kanji: "演出",
      reading: "えんしゅつ",
      meanings: {
        ja: "演出",
        en: "direction (stage/film)",
        zh: "导演（舞台/影视）",
        tw: "導演（舞台/影視）",
        ko: "연출",
        vi: "dựng cảnh; đạo diễn",
        th: "กำกับการแสดง",
        my: "ဇာတ်ကောင်စီမံ (ရင်ပြင်/ရုပ်ရှင်)",
        km: "ដឹកនាំការសម្ដែង",
      },
      furigana: [
        {
          rb: "演出",
          rt: "えんしゅつ",
        },
      ],
      kanjiInfo: [
        {
          char: "演",
          on: ["エン"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 413,
      kanji: "エンジニア",
      reading: "エンジニア",
      meanings: {
        ja: "エンジニア",
        en: "engineer",
        zh: "工程师",
        tw: "工程師",
        ko: "엔지니어",
        vi: "kỹ sư",
        th: "วิศวกร",
        my: "အင်ဂျင်နီယာ",
        km: "វិស្វករ",
      },
      furigana: [
        {
          rb: "エンジニア",
          rt: "エンジニア",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 414,
      kanji: "沿線",
      reading: "えんせん",
      meanings: {
        ja: "沿線",
        en: "along a railway line",
        zh: "沿线",
        tw: "沿線",
        ko: "연선(철도 주변)",
        vi: "dọc tuyến đường sắt",
        th: "ตามแนวเส้นทางรถไฟ",
        my: "ရထားလိုင်းဘေး",
        km: "តាមបណ្តោយផ្លូវរថ​ភ្លើង",
      },
      furigana: [
        {
          rb: "沿線",
          rt: "えんせん",
        },
      ],
      kanjiInfo: [
        {
          char: "沿",
          on: ["エン"],
          kun: ["そ.う", "-ぞ.い"],
          strokes: 8,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "線",
          on: ["セン"],
          kun: ["すじ"],
          strokes: 15,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 415,
      kanji: "縁談",
      reading: "えんだん",
      meanings: {
        ja: "縁談",
        en: "marriage proposal",
        zh: "婚事；提亲",
        tw: "婚事；提親",
        ko: "혼담",
        vi: "chuyện hôn nhân",
        th: "ทาบทามแต่งงาน",
        my: "လက်ထပ်တာဝန်",
        km: "ការផ្តល់អាពាហ៍ពិពាហ៍",
      },
      furigana: [
        {
          rb: "縁談",
          rt: "えんだん",
        },
      ],
      kanjiInfo: [
        {
          char: "縁",
          on: ["エン", "-ネン"],
          kun: ["ふち", "ふち.どる", "ゆかり", "よすが", "へり", "えにし"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "談",
          on: ["ダン"],
          kun: [],
          strokes: 15,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 416,
      kanji: "遠方",
      reading: "えんぽう",
      meanings: {
        ja: "遠方",
        en: "distant place",
        zh: "远方",
        tw: "遠方",
        ko: "먼 곳",
        vi: "nơi xa",
        th: "ที่ไกล",
        my: "ဝေးဝေးလံလံနေရာ",
        km: "ទីកន្លែងឆ្ងាយ",
      },
      furigana: [
        {
          rb: "遠方",
          rt: "えんぽう",
        },
      ],
      kanjiInfo: [
        {
          char: "遠",
          on: ["エン", "オン"],
          kun: ["とお.い"],
          strokes: 13,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 417,
      kanji: "応急",
      reading: "おうきゅう",
      meanings: {
        ja: "応急",
        en: "emergency; first-aid",
        zh: "应急",
        tw: "應急",
        ko: "응급",
        vi: "cấp cứu; khẩn cấp",
        th: "ฉุกเฉิน",
        my: "အရေးပေါ်",
        km: "បន្ទាន់",
      },
      furigana: [
        {
          rb: "応急",
          rt: "おうきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "応",
          on: ["オウ", "ヨウ", "-ノウ"],
          kun: ["あた.る", "まさに", "こた.える"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "急",
          on: ["キュウ"],
          kun: ["いそ.ぐ", "いそ.ぎ", "せ.く"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 418,
      kanji: "黄金",
      reading: "おうごん",
      meanings: {
        ja: "黄金",
        en: "gold (Au)",
        zh: "黄金；金",
        tw: "黃金；金",
        ko: "황금; 금",
        vi: "vàng",
        th: "ทองคำ",
        my: "ရွှေ",
        km: "មាស",
      },
      furigana: [
        {
          rb: "黄金",
          rt: "おうごん",
        },
      ],
      kanjiInfo: [
        {
          char: "黄",
          on: ["コウ", "オウ"],
          kun: ["き", "こ-"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 419,
      kanji: "往診",
      reading: "おうしん",
      meanings: {
        ja: "往診",
        en: "doctor's home visit",
        zh: "出诊",
        tw: "出診",
        ko: "왕진",
        vi: "khám tại nhà",
        th: "หมอไปตรวจถึงบ้าน",
        my: "ဆရာဝန်အိမ်သို့လာពិនិត្យ",
        km: "ពេទ្យទៅពិនិត្យផ្ទះ",
      },
      furigana: [
        {
          rb: "往診",
          rt: "おうしん",
        },
      ],
      kanjiInfo: [
        {
          char: "往",
          on: ["オウ"],
          kun: ["い.く", "いにしえ", "さき.に", "ゆ.く"],
          strokes: 8,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "診",
          on: ["シン"],
          kun: ["み.る"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 420,
      kanji: "応募",
      reading: "おうぼ",
      meanings: {
        ja: "応募",
        en: "application",
        zh: "应募；申请",
        tw: "應徵；申請",
        ko: "응모; 지원",
        vi: "ứng tuyển; đăng ký",
        th: "สมัคร/ยื่นใบสมัคร",
        my: "အလုပ်လျှောက်လွှာ/လျှောက်ထား",
        km: "ដាក់ពាក្យ",
      },
      furigana: [
        {
          rb: "応募",
          rt: "おうぼ",
        },
      ],
      kanjiInfo: [
        {
          char: "応",
          on: ["オウ", "ヨウ", "-ノウ"],
          kun: ["あた.る", "まさに", "こた.える"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "募",
          on: ["ボ"],
          kun: ["つの.る"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 421,
      kanji: "大方",
      reading: "おおかた",
      meanings: {
        ja: "大方",
        en: "the greater part; most",
        zh: "大部分",
        tw: "大部分",
        ko: "대부분",
        vi: "phần lớn",
        th: "ส่วนใหญ่",
        my: "အများစု",
        km: "ភាគច្រើន",
      },
      furigana: [
        {
          rb: "大方",
          rt: "おおかた",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 422,
      kanji: "大筋",
      reading: "おおすじ",
      meanings: {
        ja: "大筋",
        en: "outline; gist",
        zh: "大纲；要点",
        tw: "大綱；要點",
        ko: "대강; 요지",
        vi: "đại ý; khái quát",
        th: "โครงหลัก; ใจความ",
        my: "အကြမ်းဖျဉ်း",
        km: "សេចក្តីសង្ខេប",
      },
      furigana: [
        {
          rb: "大筋",
          rt: "おおすじ",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "筋",
          on: ["キン"],
          kun: ["すじ"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 423,
      kanji: "大空",
      reading: "おおぞら",
      meanings: {
        ja: "大空",
        en: "wide open sky",
        zh: "苍穹；广阔天空",
        tw: "廣闊天空",
        ko: "넓은 하늘",
        vi: "bầu trời rộng lớn",
        th: "ท้องฟ้าอันกว้างใหญ่",
        my: "ဝန်းကျင်ကောင်းကင်ကြီး",
        km: "មេឋឦសាន",
      },
      furigana: [
        {
          rb: "大空",
          rt: "おおぞら",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 424,
      kanji: "大水",
      reading: "おおみず",
      meanings: {
        ja: "大水",
        en: "flood",
        zh: "洪水",
        tw: "洪水",
        ko: "큰물; 홍수",
        vi: "lũ lụt",
        th: "น้ำท่วม",
        my: "ရေငင်",
        km: "ទឹកជំនន់",
      },
      furigana: [
        {
          rb: "大水",
          rt: "おおみず",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 425,
      kanji: "行い",
      reading: "おこない",
      meanings: {
        ja: "行い",
        en: "deed; conduct",
        zh: "行为；举止",
        tw: "行為；舉止",
        ko: "행실; 행위",
        vi: "hành vi; việc làm",
        th: "การกระทำ",
        my: "အပြုအမူ",
        km: "អាកប្បកិរិយា",
      },
      furigana: [
        {
          rb: "行い",
          rt: "おこない",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 426,
      kanji: "お産",
      reading: "おさん",
      meanings: {
        ja: "お産",
        en: "childbirth",
        zh: "分娩；生产",
        tw: "生產",
        ko: "출산",
        vi: "sinh nở",
        th: "การคลอด",
        my: "မီးဖွား",
        km: "សម្រាលកូន",
      },
      furigana: [
        {
          rb: "お産",
          rt: "おさん",
        },
      ],
      kanjiInfo: [
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 427,
      kanji: "雄",
      reading: "おす",
      meanings: {
        ja: "雄（動物）",
        en: "male (animal)",
        zh: "雄性（动物）",
        tw: "雄性（動物）",
        ko: "수컷(동물)",
        vi: "con đực (động vật)",
        th: "ตัวผู้ (สัตว์)",
        my: "အMale (တိရစ္ဆာန်)",
        km: "ប្រុស (សត្វ)",
      },
      furigana: [
        {
          rb: "雄",
          rt: "おす",
        },
      ],
      kanjiInfo: [
        {
          char: "雄",
          on: ["ユウ"],
          kun: ["お-", "おす", "おん"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 428,
      kanji: "御世辞",
      reading: "おせじ",
      meanings: {
        ja: "お世辞",
        en: "flattery",
        zh: "恭维；拍马屁",
        tw: "奉承；恭維",
        ko: "아첨",
        vi: "tâng bốc",
        th: "ประจบสอพลอ",
        my: "ချီးမွမ်းခြင်း(လွန်စွာ)",
        km: "បោកបទ/សរសើរពេក",
      },
      furigana: [
        {
          rb: "御世辞",
          rt: "おせじ",
        },
      ],
      kanjiInfo: [
        {
          char: "御",
          on: ["ギョ", "ゴ"],
          kun: ["おん-", "お-", "み-"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "辞",
          on: ["ジ"],
          kun: ["や.める", "いな.む"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 429,
      kanji: "恐れ",
      reading: "おそれ",
      meanings: {
        ja: "恐れ",
        en: "fear; dread",
        zh: "恐惧",
        tw: "恐懼",
        ko: "두려움",
        vi: "nỗi sợ",
        th: "ความหวาดกลัว",
        my: "ကြောက်ရွံ့မှု",
        km: "ការភ័យខល",
      },
      furigana: [
        {
          rb: "恐れ",
          rt: "おそれ",
        },
      ],
      kanjiInfo: [
        {
          char: "恐",
          on: ["キョウ"],
          kun: ["おそ.れる", "おそ.る", "おそ.ろしい", "こわ.い", "こわ.がる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 430,
      kanji: "落ち着き",
      reading: "おちつき",
      meanings: {
        ja: "落ち着き",
        en: "calmness; composure",
        zh: "冷静；镇静",
        tw: "冷靜；沉著",
        ko: "침착함",
        vi: "bình tĩnh",
        th: "ความสงบเยือกเย็น",
        my: "တည်ငြိမ်မှု",
        km: "ភាពស្ងប់ស្ងាត់",
      },
      furigana: [
        {
          rb: "落ち着き",
          rt: "おちつき",
        },
      ],
      kanjiInfo: [
        {
          char: "落",
          on: ["ラク"],
          kun: ["お.ちる", "お.ち", "お.とす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 431,
      kanji: "落葉",
      reading: "おちば",
      meanings: {
        ja: "落葉",
        en: "fallen leaves",
        zh: "落叶",
        tw: "落葉",
        ko: "낙엽",
        vi: "lá rụng",
        th: "ใบไม้ร่วง",
        my: "ရွက်ခြောက်ကျ",
        km: "ស្លឹកឈើជ្រុះ",
      },
      furigana: [
        {
          rb: "落葉",
          rt: "おちば",
        },
      ],
      kanjiInfo: [
        {
          char: "落",
          on: ["ラク"],
          kun: ["お.ちる", "お.ち", "お.とす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "葉",
          on: ["ヨウ"],
          kun: ["は"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 432,
      kanji: "乙",
      reading: "おつ",
      meanings: {
        ja: "乙（第二当事者）",
        en: "the second party",
        zh: "乙方（第二当事人）",
        tw: "乙方（第二當事人）",
        ko: "을(제2 당사자)",
        vi: "bên B (bên thứ hai)",
        th: "ฝ่ายที่สอง",
        my: "တတိယအဖွဲ့(အဘ)",
        km: "ភាគីទី២",
      },
      furigana: [
        {
          rb: "乙",
          rt: "おつ",
        },
      ],
      kanjiInfo: [
        {
          char: "乙",
          on: ["オツ", "イツ"],
          kun: ["おと-", "きのと"],
          strokes: 1,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 433,
      kanji: "お使い",
      reading: "おつかい",
      meanings: {
        ja: "お使い",
        en: "errand",
        zh: "差事；跑腿",
        tw: "差事；跑腿",
        ko: "심부름",
        vi: "việc sai vặt",
        th: "ไปธุระให้",
        my: "အလုပ်ပို့",
        km: "ការចាត់ការ",
      },
      furigana: [
        {
          rb: "お使い",
          rt: "おつかい",
        },
      ],
      kanjiInfo: [
        {
          char: "使",
          on: ["シ"],
          kun: ["つか.う", "つか.い", "-つか.い", "-づか.い"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 434,
      kanji: "お手上げ",
      reading: "おてあげ",
      meanings: {
        ja: "お手上げ",
        en: "being at a loss; giving up",
        zh: "束手无策",
        tw: "束手無策",
        ko: "어쩔 도리 없음",
        vi: "bó tay",
        th: "จนปัญญา",
        my: "အကြံမဲ့သွား",
        km: "អស់វិធី",
      },
      furigana: [
        {
          rb: "お手上げ",
          rt: "おてあげ",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 435,
      kanji: "お供",
      reading: "おとも",
      meanings: {
        ja: "お供",
        en: "attendant; companion (to accompany)",
        zh: "随从；陪同者",
        tw: "隨從；陪同者",
        ko: "수행; 동행",
        vi: "người đi theo; tháp tùng",
        th: "ผู้ติดตาม",
        my: "ပါသွားသူ",
        km: "អ្នករួមដំណើរ",
      },
      furigana: [
        {
          rb: "お供",
          rt: "おとも",
        },
      ],
      kanjiInfo: [
        {
          char: "供",
          on: ["キョウ", "ク", "クウ", "グ"],
          kun: ["そな.える", "とも", "-ども"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 436,
      kanji: "同い年",
      reading: "おないどし",
      meanings: {
        ja: "同い年",
        en: "same age",
        zh: "同岁",
        tw: "同歲",
        ko: "동갑",
        vi: "đồng trang lứa",
        th: "อายุเท่ากัน",
        my: "အသက်တူ",
        km: "អាយុស្មើ",
      },
      furigana: [
        {
          rb: "同い年",
          rt: "おないどし",
        },
      ],
      kanjiInfo: [
        {
          char: "同",
          on: ["ドウ"],
          kun: ["おな.じ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 437,
      kanji: "お袋",
      reading: "おふくろ",
      meanings: {
        ja: "お袋（母）",
        en: "(one's) mother (colloq.)",
        zh: "老妈（口语）",
        tw: "老媽（口語）",
        ko: "어무니/어머니(구어)",
        vi: "mẹ (thân mật)",
        th: "แม่ (ภาษาพูด)",
        my: "အမေ (စကားပြော)",
        km: "ម៉ែ (ប្រើក្នុងការសន្ទនា)",
      },
      furigana: [
        {
          rb: "お袋",
          rt: "おふくろ",
        },
      ],
      kanjiInfo: [
        {
          char: "袋",
          on: ["タイ", "ダイ"],
          kun: ["ふくろ"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 438,
      kanji: "覚え",
      reading: "おぼえ",
      meanings: {
        ja: "覚え",
        en: "memory; recollection",
        zh: "记忆；印象",
        tw: "記憶；印象",
        ko: "기억; 기억력",
        vi: "trí nhớ",
        th: "ความจำ",
        my: "မှတ်ဉာဏ်",
        km: "ការចងចាំ",
      },
      furigana: [
        {
          rb: "覚え",
          rt: "おぼえ",
        },
      ],
      kanjiInfo: [
        {
          char: "覚",
          on: ["カク"],
          kun: ["おぼ.える", "さ.ます", "さ.める", "さと.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 439,
      kanji: "お宮",
      reading: "おみや",
      meanings: {
        ja: "お宮（神社）",
        en: "Shinto shrine",
        zh: "神社",
        tw: "神社",
        ko: "신사",
        vi: "đền Thần đạo",
        th: "ศาลเจ้า(ชินโต)",
        my: "ရှင်တို神社",
        km: "ប្រាសាទឯិន់តោ (Shinto)",
      },
      furigana: [
        {
          rb: "お宮",
          rt: "おみや",
        },
      ],
      kanjiInfo: [
        {
          char: "宮",
          on: ["キュウ", "グウ", "ク", "クウ"],
          kun: ["みや"],
          strokes: 10,
          grade: 3,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 440,
      kanji: "思い付き",
      reading: "おもいつき",
      meanings: {
        ja: "思い付き",
        en: "idea; inspiration",
        zh: "主意；灵感",
        tw: "靈機一動；想法",
        ko: "문득 든 생각",
        vi: "ý tưởng chợt đến",
        th: "ไอเดียฉับพลัน",
        my: "လက်ခဏထင်လာသည့်အကြမ်းအနား",
        km: "គំនិតរហ័សរហួន",
      },
      furigana: [
        {
          rb: "思い付き",
          rt: "おもいつき",
        },
      ],
      kanjiInfo: [
        {
          char: "思",
          on: ["シ"],
          kun: ["おも.う", "おもえら.く", "おぼ.す"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 441,
      kanji: "趣",
      reading: "おもむき",
      meanings: {
        ja: "趣",
        en: "charm; atmosphere; meaning",
        zh: "情趣；意味",
        tw: "風趣；旨趣",
        ko: "운치; 취지",
        vi: "phong vị; ý nghĩa",
        th: "เสน่ห์/บรรยากาศ/ความหมาย",
        my: "အငွေ့အသက်; အဓိပ္ပါယ်",
        km: "អត្ថន័យ; ទឹកចិត្ត",
      },
      furigana: [
        {
          rb: "趣",
          rt: "おもむき",
        },
      ],
      kanjiInfo: [
        {
          char: "趣",
          on: ["シュ"],
          kun: ["おもむき", "おもむ.く"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 442,
      kanji: "親父",
      reading: "おやじ",
      meanings: {
        ja: "親父（父）",
        en: "one's father (informal)",
        zh: "老爸（口语）",
        tw: "老爸（口語）",
        ko: "아버지(구어)",
        vi: "bố (thân mật)",
        th: "พ่อ (ภาษาพูด)",
        my: "အဖေ (စကားပြော)",
        km: "ប៉ា (ភាសានិយម)",
      },
      furigana: [
        {
          rb: "親父",
          rt: "おやじ",
        },
      ],
      kanjiInfo: [
        {
          char: "親",
          on: ["シン"],
          kun: ["おや", "おや-", "した.しい", "した.しむ"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 443,
      kanji: "折",
      reading: "おり",
      meanings: {
        ja: "折（おり）",
        en: "opportunity; occasion",
        zh: "时机；机会",
        tw: "機會；時候",
        ko: "기회; 때",
        vi: "dịp; cơ hội",
        th: "โอกาส",
        my: "အခွင့်အရေး",
        km: "ឱកាស",
      },
      furigana: [
        {
          rb: "折",
          rt: "おり",
        },
      ],
      kanjiInfo: [
        {
          char: "折",
          on: ["セツ", "シャク"],
          kun: ["お.る", "おり", "お.り", "-お.り", "お.れる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 444,
      kanji: "檻",
      reading: "おり",
      meanings: {
        ja: "檻",
        en: "cage",
        zh: "笼子",
        tw: "籠子",
        ko: "우리",
        vi: "lồng; chuồng",
        th: "กรง",
        my: "ခြောက်/ကန်တော့ပိတ်",
        km: "គោក",
      },
      furigana: [
        {
          rb: "檻",
          rt: "おり",
        },
      ],
      kanjiInfo: [
        {
          char: "檻",
          on: ["カン"],
          kun: ["おり", "おばしま", "てすり"],
          strokes: 19,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 445,
      kanji: "オリエンテーション",
      reading: "オリエンテーション",
      meanings: {
        ja: "オリエンテーション",
        en: "orientation",
        zh: "说明会；入门介绍",
        tw: "說明會；導向",
        ko: "오리엔테이션",
        vi: "buổi định hướng",
        th: "ปฐมนิเทศ",
        my: "မိတ်ဆက်ညွှန်ကြားပွဲ",
        km: "សិក្ខាសាលាប្រាប់ណែនាំ",
      },
      furigana: [
        {
          rb: "オリエンテーション",
          rt: "オリエンテーション",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 446,
      kanji: "織物",
      reading: "おりもの",
      meanings: {
        ja: "織物",
        en: "textile",
        zh: "纺织品",
        tw: "紡織品",
        ko: "직물",
        vi: "dệt vải; hàng dệt",
        th: "สิ่งทอ",
        my: "အထည်",
        km: "វាយនភណ្ឌ",
      },
      furigana: [
        {
          rb: "織物",
          rt: "おりもの",
        },
      ],
      kanjiInfo: [
        {
          char: "織",
          on: ["ショク", "シキ"],
          kun: ["お.る", "お.り", "おり", "-おり", "-お.り"],
          strokes: 18,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 447,
      kanji: "オンライン",
      reading: "オンライン",
      meanings: {
        ja: "オンライン",
        en: "online",
        zh: "在线的",
        tw: "線上的",
        ko: "온라인",
        vi: "trực tuyến",
        th: "ออนไลน์",
        my: "အွန်လိုင်း",
        km: "លើបណ្តាញ",
      },
      furigana: [
        {
          rb: "オンライン",
          rt: "オンライン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 448,
      kanji: "カーペット",
      reading: "カーペット",
      meanings: {
        ja: "カーペット",
        en: "carpet",
        zh: "地毯",
        tw: "地毯",
        ko: "카펫",
        vi: "thảm",
        th: "พรม",
        my: "ခေတ်မီပြား (ခေတ်)",
        km: "កម្រាលព្រំ",
      },
      furigana: [
        {
          rb: "カーペット",
          rt: "カーペット",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 449,
      kanji: "改悪",
      reading: "かいあく",
      meanings: {
        ja: "改悪",
        en: "change for the worse",
        zh: "改坏；恶化",
        tw: "改惡；惡化",
        ko: "개악",
        vi: "cải xấu; làm tệ đi",
        th: "เปลี่ยนให้แย่ลง",
        my: "ပိုဆိုးသွားခြင်း",
        km: "ធ្វើឲ្យអាក្រក់ឡើង",
      },
      furigana: [
        {
          rb: "改悪",
          rt: "かいあく",
        },
      ],
      kanjiInfo: [
        {
          char: "改",
          on: ["カイ"],
          kun: ["あらた.める", "あらた.まる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "悪",
          on: ["アク", "オ"],
          kun: [
            "わる.い",
            "わる-",
            "あ.し",
            "にく.い",
            "-にく.い",
            "ああ",
            "いずくに",
            "いずくんぞ",
            "にく.む",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 450,
      kanji: "海運",
      reading: "かいうん",
      meanings: {
        ja: "海運",
        en: "maritime transport",
        zh: "海运",
        tw: "海運",
        ko: "해운",
        vi: "vận tải đường biển",
        th: "การขนส่งทางทะเล",
        my: "ကမ်းရိုးတန်းပို့ဆောင်ရေး",
        km: "ដឹកជញ្ជូនតាមសមុទ្រ",
      },
      furigana: [
        {
          rb: "海運",
          rt: "かいうん",
        },
      ],
      kanjiInfo: [
        {
          char: "海",
          on: ["カイ"],
          kun: ["うみ"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
