export const n2part5 = {
  Lesson5: [
    {
      id: 201,
      kanji: "ダム",
      reading: "ダム",
      meanings: {
        ja: "ダム",
        en: "dam",
        zh: "水坝",
        tw: "水壩",
        ko: "댐",
        vi: "đập nước",
        th: "เขื่อน",
        my: "တံတားရေ",
        km: "ទំនប់",
      },
      furigana: [
        {
          rb: "ダム",
          rt: "ダム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 202,
      kanji: "溜息",
      reading: "ためいき",
      meanings: {
        ja: "溜息",
        en: "sigh",
        zh: "叹气",
        tw: "嘆氣",
        ko: "한숨",
        vi: "tiếng thở dài",
        th: "ถอนหายใจ",
        my: "အသက်ရှူလွှတ်",
        km: "ដកដង្ហើមយូរ",
      },
      furigana: [
        {
          rb: "溜息",
          rt: "ためいき",
        },
      ],
      kanjiInfo: [
        {
          char: "溜",
          on: ["リュウ"],
          kun: ["た.まる", "たま.る", "た.める", "したた.る", "たまり", "ため"],
          strokes: 13,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
        {
          char: "息",
          on: ["ソク"],
          kun: ["いき"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 203,
      kanji: "オーケストラ",
      reading: "オーケストラ",
      meanings: {
        ja: "オーケストラ",
        en: "orchestra",
        zh: "管弦乐队",
        tw: "管弦樂隊",
        ko: "오케스트라",
        vi: "dàn nhạc giao hưởng",
        th: "วงออเคสตรา",
        my: "စည်းရာတီး",
        km: "វង្សតន្រ្តី",
      },
      furigana: [
        {
          rb: "オーケストラ",
          rt: "オーケストラ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 204,
      kanji: "大通り",
      reading: "おおどおり",
      meanings: {
        ja: "大通り",
        en: "main street",
        zh: "大街",
        tw: "大街",
        ko: "큰길",
        vi: "đại lộ",
        th: "ถนนใหญ่",
        my: "လမ်းကြီး",
        km: "ផ្លូវធំ",
      },
      furigana: [
        {
          rb: "大通り",
          rt: "おおどおり",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 205,
      kanji: "オートメーション",
      reading: "オートメーション",
      meanings: {
        ja: "オートメーション",
        en: "automation",
        zh: "自动化",
        tw: "自動化",
        ko: "자동화",
        vi: "tự động hóa",
        th: "ระบบอัตโนมัติ",
        my: "အလိုအလျောက်",
        km: "ស្វ័យប្រវត្តិ",
      },
      furigana: [
        {
          rb: "オートメーション",
          rt: "オートメーション",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 206,
      kanji: "お帰り",
      reading: "おかえり",
      meanings: {
        ja: "お帰り",
        en: "return; welcome back",
        zh: "回家",
        tw: "回來",
        ko: "다녀옴",
        vi: "về nhà",
        th: "กลับบ้าน",
        my: "ပြန်လာ",
        km: "ត្រឡប់",
      },
      furigana: [
        {
          rb: "お帰り",
          rt: "おかえり",
        },
      ],
      kanjiInfo: [
        {
          char: "帰",
          on: ["キ"],
          kun: ["かえ.る", "かえ.す", "おく.る", "とつ.ぐ"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 207,
      kanji: "お代わり",
      reading: "おかわり",
      meanings: {
        ja: "お代わり",
        en: "another helping",
        zh: "再来一份",
        tw: "再來一份",
        ko: "한 그릇 더",
        vi: "xin thêm",
        th: "ขอเพิ่ม",
        my: "နောက်ထပ်တစ်လုံး",
        km: "បន្ថែមទៀត",
      },
      furigana: [
        {
          rb: "お代わり",
          rt: "おかわり",
        },
      ],
      kanjiInfo: [
        {
          char: "代",
          on: ["ダイ", "タイ"],
          kun: [
            "か.わる",
            "かわ.る",
            "かわ.り",
            "か.わり",
            "-がわ.り",
            "-が.わり",
            "か.える",
            "よ",
            "しろ",
          ],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 208,
      kanji: "屋外",
      reading: "おくがい",
      meanings: {
        ja: "屋外",
        en: "outdoors",
        zh: "室外",
        tw: "戶外",
        ko: "야외",
        vi: "ngoài trời",
        th: "กลางแจ้ง",
        my: "အပြင်ဘက်",
        km: "ខាងក្រៅ",
      },
      furigana: [
        {
          rb: "屋外",
          rt: "おくがい",
        },
      ],
      kanjiInfo: [
        {
          char: "屋",
          on: ["オク"],
          kun: ["や"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 209,
      kanji: "送り仮名",
      reading: "おくりがな",
      meanings: {
        ja: "送り仮名",
        en: "kana suffix (after kanji)",
        zh: "送假名",
        tw: "送假名",
        ko: "오쿠리가나",
        vi: "okurigana",
        th: "อคุริกานะ",
        my: "အိုခူရိဂနာ",
        km: "អូគុរិកាណា",
      },
      furigana: [
        {
          rb: "送り仮名",
          rt: "おくりがな",
        },
      ],
      kanjiInfo: [
        {
          char: "送",
          on: ["ソウ"],
          kun: ["おく.る"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "仮",
          on: ["カ", "ケ"],
          kun: ["かり", "かり-"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 210,
      kanji: "伯父",
      reading: "おじ",
      meanings: {
        ja: "伯父",
        en: "uncle (older than parent)",
        zh: "伯父",
        tw: "伯父",
        ko: "백부",
        vi: "bác trai",
        th: "ลุง",
        my: "ဦး",
        km: "ពូ",
      },
      furigana: [
        {
          rb: "伯父",
          rt: "おじ",
        },
      ],
      kanjiInfo: [
        {
          char: "伯",
          on: ["ハク"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 211,
      kanji: "叔父",
      reading: "おじ",
      meanings: {
        ja: "叔父",
        en: "uncle (younger than parent)",
        zh: "叔父",
        tw: "叔父",
        ko: "숙부",
        vi: "chú",
        th: "อา (ผช.)",
        my: "ဦးငယ်",
        km: "អ៊ំ (តូច)",
      },
      furigana: [
        {
          rb: "叔父",
          rt: "おじ",
        },
      ],
      kanjiInfo: [
        {
          char: "叔",
          on: ["シュク"],
          kun: [],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 212,
      kanji: "伯父さん",
      reading: "おじさん",
      meanings: {
        ja: "伯父さん",
        en: "uncle (older than parent)",
        zh: "伯父",
        tw: "伯父",
        ko: "백부님",
        vi: "bác trai",
        th: "ลุง",
        my: "ဦးကြီး",
        km: "ពូ",
      },
      furigana: [
        {
          rb: "伯父さん",
          rt: "おじさん",
        },
      ],
      kanjiInfo: [
        {
          char: "伯",
          on: ["ハク"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 213,
      kanji: "小父さん",
      reading: "おじさん",
      meanings: {
        ja: "小父さん",
        en: "uncle; middle-aged man",
        zh: "叔叔",
        tw: "叔叔",
        ko: "아저씨",
        vi: "chú; bác",
        th: "ลุง/อา",
        my: "ဦးလေး",
        km: "អ៊ំ",
      },
      furigana: [
        {
          rb: "小父さん",
          rt: "おじさん",
        },
      ],
      kanjiInfo: [
        {
          char: "小",
          on: ["ショウ"],
          kun: ["ちい.さい", "こ-", "お-", "さ-"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 214,
      kanji: "叔父さん",
      reading: "おじさん",
      meanings: {
        ja: "叔父さん",
        en: "uncle (younger than parent)",
        zh: "叔父",
        tw: "叔父",
        ko: "숙부님",
        vi: "chú",
        th: "อา",
        my: "ဦးငယ်",
        km: "អ៊ំ (តូច)",
      },
      furigana: [
        {
          rb: "叔父さん",
          rt: "おじさん",
        },
      ],
      kanjiInfo: [
        {
          char: "叔",
          on: ["シュク"],
          kun: [],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 215,
      kanji: "お出掛け",
      reading: "おでかけ",
      meanings: {
        ja: "お出掛け",
        en: "about to go out",
        zh: "出门",
        tw: "出門",
        ko: "외출",
        vi: "ra ngoài",
        th: "ออกไปข้างนอก",
        my: "ထွက်သွား",
        km: "ចេញទៅក្រៅ",
      },
      furigana: [
        {
          rb: "お出掛け",
          rt: "おでかけ",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "掛",
          on: ["カイ", "ケイ"],
          kun: [
            "か.ける",
            "-か.ける",
            "か.け",
            "-か.け",
            "-が.け",
            "か.かる",
            "-か.かる",
            "-が.かる",
            "か.かり",
            "-が.かり",
            "かかり",
            "-がかり",
          ],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 216,
      kanji: "お手伝いさん",
      reading: "おてつだいさん",
      meanings: {
        ja: "お手伝いさん",
        en: "maid",
        zh: "女佣",
        tw: "女傭",
        ko: "가정부",
        vi: "người giúp việc",
        th: "แม่บ้าน",
        my: "အိမ်အလုပ်သမား",
        km: "អ្នកជួយការងារ",
      },
      furigana: [
        {
          rb: "お手伝いさん",
          rt: "おてつだいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "伝",
          on: ["デン", "テン"],
          kun: [
            "つた.わる",
            "つた.える",
            "つた.う",
            "つだ.う",
            "-づた.い",
            "つて",
          ],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 217,
      kanji: "落し物",
      reading: "おとしもの",
      meanings: {
        ja: "落し物",
        en: "lost property",
        zh: "遗失物",
        tw: "遺失物",
        ko: "분실물",
        vi: "đồ thất lạc",
        th: "ของหาย",
        my: "ပျောက်ဆုံးပစ္စည်း",
        km: "វត្ថុបាត់",
      },
      furigana: [
        {
          rb: "落し物",
          rt: "おとしもの",
        },
      ],
      kanjiInfo: [
        {
          char: "落",
          on: ["ラク"],
          kun: ["お.ちる", "お.ち", "お.とす"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 218,
      kanji: "各々",
      reading: "おのおの",
      meanings: {
        ja: "各々",
        en: "each",
        zh: "各自",
        tw: "各自",
        ko: "각자",
        vi: "mỗi người",
        th: "แต่ละคน",
        my: "တစ်ဦးချင်း",
        km: "នីមួយៗ",
      },
      furigana: [
        {
          rb: "各々",
          rt: "おのおの",
        },
      ],
      kanjiInfo: [
        {
          char: "各",
          on: ["カク"],
          kun: ["おのおの"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 219,
      kanji: "伯母",
      reading: "おば",
      meanings: {
        ja: "伯母",
        en: "aunt (older than parent)",
        zh: "伯母",
        tw: "伯母",
        ko: "백모",
        vi: "bác gái",
        th: "ป้า",
        my: "အဒေါ်ကြီး",
        km: "ពូស្រី",
      },
      furigana: [
        {
          rb: "伯母",
          rt: "おば",
        },
      ],
      kanjiInfo: [
        {
          char: "伯",
          on: ["ハク"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 220,
      kanji: "叔母",
      reading: "おば",
      meanings: {
        ja: "叔母",
        en: "aunt (younger than parent)",
        zh: "叔母",
        tw: "叔母",
        ko: "숙모",
        vi: "cô/dì",
        th: "น้า (ผญ.)",
        my: "အဒေါ်ငယ်",
        km: "អ៊ំស្រី",
      },
      furigana: [
        {
          rb: "叔母",
          rt: "おば",
        },
      ],
      kanjiInfo: [
        {
          char: "叔",
          on: ["シュク"],
          kun: [],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 221,
      kanji: "小母さん",
      reading: "おばさん",
      meanings: {
        ja: "小母さん",
        en: "aunt; middle-aged woman",
        zh: "阿姨",
        tw: "阿姨",
        ko: "아줌마",
        vi: "cô; dì",
        th: "ป้า/น้า",
        my: "အဒေါ်လေး",
        km: "អ៊ំស្រី",
      },
      furigana: [
        {
          rb: "小母さん",
          rt: "おばさん",
        },
      ],
      kanjiInfo: [
        {
          char: "小",
          on: ["ショウ"],
          kun: ["ちい.さい", "こ-", "お-", "さ-"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 222,
      kanji: "お参り",
      reading: "おまいり",
      meanings: {
        ja: "お参り",
        en: "visit (to a shrine)",
        zh: "参拜",
        tw: "參拜",
        ko: "참배",
        vi: "viếng thăm đền",
        th: "ไปไหว้ศาลเจ้า",
        my: "ဘုရားအားဖွင့်",
        km: "ការទៅគោរព",
      },
      furigana: [
        {
          rb: "お参り",
          rt: "おまいり",
        },
      ],
      kanjiInfo: [
        {
          char: "参",
          on: ["サン", "シン"],
          kun: ["まい.る", "まい-", "まじわる", "みつ"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 223,
      kanji: "お休み",
      reading: "おやすみ",
      meanings: {
        ja: "お休み",
        en: "holiday; rest",
        zh: "休息",
        tw: "休息",
        ko: "휴식",
        vi: "nghỉ ngơi",
        th: "พักผ่อน",
        my: "အနားယူ",
        km: "សម្រាក",
      },
      furigana: [
        {
          rb: "お休み",
          rt: "おやすみ",
        },
      ],
      kanjiInfo: [
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 224,
      kanji: "親指",
      reading: "おやゆび",
      meanings: {
        ja: "親指",
        en: "thumb",
        zh: "拇指",
        tw: "拇指",
        ko: "엄지손가락",
        vi: "ngón cái",
        th: "นิ้วหัวแม่มือ",
        my: "လက်မ",
        km: "ម្រាមដៃធំ",
      },
      furigana: [
        {
          rb: "親指",
          rt: "おやゆび",
        },
      ],
      kanjiInfo: [
        {
          char: "親",
          on: ["シン"],
          kun: ["おや", "おや-", "した.しい", "した.しむ"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 225,
      kanji: "オルガン",
      reading: "オルガン",
      meanings: {
        ja: "オルガン",
        en: "organ (musical instrument)",
        zh: "风琴",
        tw: "風琴",
        ko: "오르간",
        vi: "đàn organ",
        th: "ออร์แกน",
        my: "အော်ဂန်",
        km: "អ៊រហ្គាន់",
      },
      furigana: [
        {
          rb: "オルガン",
          rt: "オルガン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 226,
      kanji: "恩恵",
      reading: "おんけい",
      meanings: {
        ja: "恩恵",
        en: "grace; blessing",
        zh: "恩惠",
        tw: "恩惠",
        ko: "은혜",
        vi: "ân huệ",
        th: "พระคุณ",
        my: "ကျေးဇူး",
        km: "ពរ",
      },
      furigana: [
        {
          rb: "恩恵",
          rt: "おんけい",
        },
      ],
      kanjiInfo: [
        {
          char: "恩",
          on: ["オン"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "恵",
          on: ["ケイ", "エ"],
          kun: ["めぐ.む", "めぐ.み"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 227,
      kanji: "温室",
      reading: "おんしつ",
      meanings: {
        ja: "温室",
        en: "greenhouse",
        zh: "温室",
        tw: "溫室",
        ko: "온실",
        vi: "nhà kính",
        th: "เรือนกระจก",
        my: "အပင်အိမ်",
        km: "ផ្ទះកញ្ចក់",
      },
      furigana: [
        {
          rb: "温室",
          rt: "おんしつ",
        },
      ],
      kanjiInfo: [
        {
          char: "温",
          on: ["オン"],
          kun: [
            "あたた.か",
            "あたた.かい",
            "あたた.まる",
            "あたた.める",
            "ぬく",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "室",
          on: ["シツ"],
          kun: ["むろ"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 228,
      kanji: "温泉",
      reading: "おんせん",
      meanings: {
        ja: "温泉",
        en: "hot spring",
        zh: "温泉",
        tw: "溫泉",
        ko: "온천",
        vi: "suối nước nóng",
        th: "บ่อน้ำพุร้อน",
        my: "ရေနွေးငွေ့",
        km: "ទឹកក្តៅធម្មជាតិ",
      },
      furigana: [
        {
          rb: "温泉",
          rt: "おんせん",
        },
      ],
      kanjiInfo: [
        {
          char: "温",
          on: ["オン"],
          kun: [
            "あたた.か",
            "あたた.かい",
            "あたた.まる",
            "あたた.める",
            "ぬく",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "泉",
          on: ["セン"],
          kun: ["いずみ"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 229,
      kanji: "温帯",
      reading: "おんたい",
      meanings: {
        ja: "温帯",
        en: "temperate zone",
        zh: "温带",
        tw: "溫帶",
        ko: "온대",
        vi: "vùng ôn đới",
        th: "เขตอบอุ่น",
        my: "အပူပိုင်း",
        km: "តំបន់ត្រជាក់ក្តៅ",
      },
      furigana: [
        {
          rb: "温帯",
          rt: "おんたい",
        },
      ],
      kanjiInfo: [
        {
          char: "温",
          on: ["オン"],
          kun: [
            "あたた.か",
            "あたた.かい",
            "あたた.まる",
            "あたた.める",
            "ぬく",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "帯",
          on: ["タイ"],
          kun: ["お.びる", "おび"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 230,
      kanji: "御中",
      reading: "おんちゅう",
      meanings: {
        ja: "御中",
        en: "... and Company",
        zh: "御中",
        tw: "御中",
        ko: "귀중",
        vi: "kính gửi",
        th: "เรียน (ถึงบริษัท)",
        my: "အဖွဲ့သို့",
        km: "គោរពជូន",
      },
      furigana: [
        {
          rb: "御中",
          rt: "おんちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "御",
          on: ["ギョ", "ゴ"],
          kun: ["おん-", "お-", "み-"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 231,
      kanji: "カーブ",
      reading: "カーブ",
      meanings: {
        ja: "カーブ",
        en: "curve",
        zh: "弯曲",
        tw: "彎曲",
        ko: "커브",
        vi: "đường cong",
        th: "โค้ง",
        my: "အချိုး",
        km: "កោង",
      },
      furigana: [
        {
          rb: "カーブ",
          rt: "カーブ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 232,
      kanji: "開会",
      reading: "かいかい",
      meanings: {
        ja: "開会",
        en: "opening of a meeting",
        zh: "开会",
        tw: "開會",
        ko: "개회",
        vi: "khai mạc",
        th: "เปิดการประชุม",
        my: "အစည်းအဝေးဖွင့်",
        km: "បើកប្រជុំ",
      },
      furigana: [
        {
          rb: "開会",
          rt: "かいかい",
        },
      ],
      kanjiInfo: [
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 233,
      kanji: "会館",
      reading: "かいかん",
      meanings: {
        ja: "会館",
        en: "meeting hall",
        zh: "会馆",
        tw: "會館",
        ko: "회관",
        vi: "hội trường",
        th: "หอประชุม",
        my: "မင်းထိုက်",
        km: "សាលប្រជុំ",
      },
      furigana: [
        {
          rb: "会館",
          rt: "かいかん",
        },
      ],
      kanjiInfo: [
        {
          char: "会",
          on: ["カイ", "エ"],
          kun: ["あ.う", "あ.わせる", "あつ.まる"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "館",
          on: ["カン"],
          kun: ["やかた", "たて"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 234,
      kanji: "改札",
      reading: "かいさつ",
      meanings: {
        ja: "改札",
        en: "ticket gate",
        zh: "检票口",
        tw: "檢票口",
        ko: "개찰구",
        vi: "cổng soát vé",
        th: "ประตูตรวจตั๋ว",
        my: "လက်မှတ်စစ်ဝင်ပေါက်",
        km: "ច្រកត្រួតពិនិត្យសំបុត្រ",
      },
      furigana: [
        {
          rb: "改札",
          rt: "かいさつ",
        },
      ],
      kanjiInfo: [
        {
          char: "改",
          on: ["カイ"],
          kun: ["あらた.める", "あらた.まる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "札",
          on: ["サツ"],
          kun: ["ふだ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 235,
      kanji: "解散",
      reading: "かいさん",
      meanings: {
        ja: "解散",
        en: "dissolution",
        zh: "解散",
        tw: "解散",
        ko: "해산",
        vi: "giải tán",
        th: "ยุบ/เลิก",
        my: "ဖြိုခွဲ",
        km: "រំលាយ",
      },
      furigana: [
        {
          rb: "解散",
          rt: "かいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "散",
          on: ["サン"],
          kun: [
            "ち.る",
            "ち.らす",
            "-ち.らす",
            "ち.らかす",
            "ち.らかる",
            "ち.らばる",
            "ばら",
            "ばら.ける",
          ],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 236,
      kanji: "海水浴",
      reading: "かいすいよく",
      meanings: {
        ja: "海水浴",
        en: "swimming in the ocean",
        zh: "海水浴",
        tw: "海水浴",
        ko: "해수욕",
        vi: "tắm biển",
        th: "เล่นน้ำทะเล",
        my: "ပင်လယ်ထဲရေကစား",
        km: "ងូតទឹកសមុទ្រ",
      },
      furigana: [
        {
          rb: "海水浴",
          rt: "かいすいよく",
        },
      ],
      kanjiInfo: [
        {
          char: "海",
          on: ["カイ"],
          kun: ["うみ"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "浴",
          on: ["ヨク"],
          kun: ["あ.びる", "あ.びせる"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 237,
      kanji: "回数",
      reading: "かいすう",
      meanings: {
        ja: "回数",
        en: "number of times",
        zh: "次数",
        tw: "次數",
        ko: "횟수",
        vi: "số lần",
        th: "จำนวนครั้ง",
        my: "ကြိမ်",
        km: "ចំនួនដង",
      },
      furigana: [
        {
          rb: "回数",
          rt: "かいすう",
        },
      ],
      kanjiInfo: [
        {
          char: "回",
          on: ["カイ", "エ"],
          kun: [
            "まわ.る",
            "-まわ.る",
            "-まわ.り",
            "まわ.す",
            "-まわ.す",
            "まわ.し-",
            "-まわ.し",
            "もとお.る",
            "か.える",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 238,
      kanji: "回数券",
      reading: "かいすうけん",
      meanings: {
        ja: "回数券",
        en: "coupon tickets",
        zh: "回数券",
        tw: "回數券",
        ko: "회수권",
        vi: "vé tập",
        th: "ตั๋วชุด",
        my: "လက်မှတ်အစု",
        km: "សំបុត្រជាកញ្ចប់",
      },
      furigana: [
        {
          rb: "回数券",
          rt: "かいすうけん",
        },
      ],
      kanjiInfo: [
        {
          char: "回",
          on: ["カイ", "エ"],
          kun: [
            "まわ.る",
            "-まわ.る",
            "-まわ.り",
            "まわ.す",
            "-まわ.す",
            "まわ.し-",
            "-まわ.し",
            "もとお.る",
            "か.える",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "券",
          on: ["ケン"],
          kun: [],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 239,
      kanji: "改正",
      reading: "かいせい",
      meanings: {
        ja: "改正",
        en: "revision; amendment",
        zh: "修正",
        tw: "修正",
        ko: "개정",
        vi: "sửa đổi",
        th: "แก้ไข",
        my: "ပြင်ဆင်",
        km: "កែប្រែ",
      },
      furigana: [
        {
          rb: "改正",
          rt: "かいせい",
        },
      ],
      kanjiInfo: [
        {
          char: "改",
          on: ["カイ"],
          kun: ["あらた.める", "あらた.まる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 240,
      kanji: "快晴",
      reading: "かいせい",
      meanings: {
        ja: "快晴",
        en: "clear weather",
        zh: "晴朗",
        tw: "晴朗",
        ko: "쾌청",
        vi: "trời quang đãng",
        th: "อากาศแจ่มใส",
        my: "အနက်ရောင်မိုဃ်းမရှိ",
        km: "អាកាសថ្លា",
      },
      furigana: [
        {
          rb: "快晴",
          rt: "かいせい",
        },
      ],
      kanjiInfo: [
        {
          char: "快",
          on: ["カイ"],
          kun: ["こころよ.い"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "晴",
          on: ["セイ"],
          kun: ["は.れる", "は.れ", "は.れ-", "-ば.れ", "は.らす"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 241,
      kanji: "解説",
      reading: "かいせつ",
      meanings: {
        ja: "解説",
        en: "explanation",
        zh: "解说",
        tw: "解說",
        ko: "해설",
        vi: "giải thích",
        th: "คำอธิบาย",
        my: "ရှင်းပြ",
        km: "ការពន្យល់",
      },
      furigana: [
        {
          rb: "解説",
          rt: "かいせつ",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "説",
          on: ["セツ", "ゼイ"],
          kun: ["と.く"],
          strokes: 14,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 242,
      kanji: "改造",
      reading: "かいぞう",
      meanings: {
        ja: "改造",
        en: "remodeling",
        zh: "改造",
        tw: "改造",
        ko: "개조",
        vi: "cải tạo",
        th: "ดัดแปลง",
        my: "ပြန်ဆောက်",
        km: "កែប្រែ",
      },
      furigana: [
        {
          rb: "改造",
          rt: "かいぞう",
        },
      ],
      kanjiInfo: [
        {
          char: "改",
          on: ["カイ"],
          kun: ["あらた.める", "あらた.まる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "造",
          on: ["ゾウ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 243,
      kanji: "開通",
      reading: "かいつう",
      meanings: {
        ja: "開通",
        en: "opening (of a road/line)",
        zh: "开通",
        tw: "開通",
        ko: "개통",
        vi: "khai thông",
        th: "เปิดใช้",
        my: "ဖွင့်လမ်း",
        km: "បើកផ្លូវ",
      },
      furigana: [
        {
          rb: "開通",
          rt: "かいつう",
        },
      ],
      kanjiInfo: [
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 244,
      kanji: "回転",
      reading: "かいてん",
      meanings: {
        ja: "回転",
        en: "rotation",
        zh: "回转",
        tw: "回轉",
        ko: "회전",
        vi: "xoay vòng",
        th: "หมุนเวียน",
        my: "လှည့်",
        km: "បង្វិល",
      },
      furigana: [
        {
          rb: "回転",
          rt: "かいてん",
        },
      ],
      kanjiInfo: [
        {
          char: "回",
          on: ["カイ", "エ"],
          kun: [
            "まわ.る",
            "-まわ.る",
            "-まわ.り",
            "まわ.す",
            "-まわ.す",
            "まわ.し-",
            "-まわ.し",
            "もとお.る",
            "か.える",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 245,
      kanji: "解答",
      reading: "かいとう",
      meanings: {
        ja: "解答",
        en: "answer (solution)",
        zh: "解答",
        tw: "解答",
        ko: "해답",
        vi: "lời giải",
        th: "คำตอบ",
        my: "အဖြေ",
        km: "ចម្លើយ",
      },
      furigana: [
        {
          rb: "解答",
          rt: "かいとう",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "答",
          on: ["トウ"],
          kun: ["こた.える", "こた.え"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 246,
      kanji: "回答",
      reading: "かいとう",
      meanings: {
        ja: "回答",
        en: "reply",
        zh: "回答",
        tw: "回答",
        ko: "회답",
        vi: "hồi đáp",
        th: "การตอบ",
        my: "ပြန်စာ",
        km: "ការឆ្លើយតប",
      },
      furigana: [
        {
          rb: "回答",
          rt: "かいとう",
        },
      ],
      kanjiInfo: [
        {
          char: "回",
          on: ["カイ", "エ"],
          kun: [
            "まわ.る",
            "-まわ.る",
            "-まわ.り",
            "まわ.す",
            "-まわ.す",
            "まわ.し-",
            "-まわ.し",
            "もとお.る",
            "か.える",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "答",
          on: ["トウ"],
          kun: ["こた.える", "こた.え"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 247,
      kanji: "外部",
      reading: "がいぶ",
      meanings: {
        ja: "外部",
        en: "outside (external)",
        zh: "外部",
        tw: "外部",
        ko: "외부",
        vi: "bên ngoài",
        th: "ภายนอก",
        my: "အပြင်ဘက်",
        km: "ខាងក្រៅ",
      },
      furigana: [
        {
          rb: "外部",
          rt: "がいぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 248,
      kanji: "解放",
      reading: "かいほう",
      meanings: {
        ja: "解放",
        en: "liberation; release",
        zh: "解放",
        tw: "解放",
        ko: "해방",
        vi: "giải phóng",
        th: "ปลดปล่อย",
        my: "လွှတ်",
        km: "ការរំដោះ",
      },
      furigana: [
        {
          rb: "解放",
          rt: "かいほう",
        },
      ],
      kanjiInfo: [
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "放",
          on: ["ホウ"],
          kun: [
            "はな.す",
            "-っぱな.し",
            "はな.つ",
            "はな.れる",
            "こ.く",
            "ほう.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 249,
      kanji: "開放",
      reading: "かいほう",
      meanings: {
        ja: "開放",
        en: "opening (of doors/windows)",
        zh: "开放",
        tw: "開放",
        ko: "개방",
        vi: "mở cửa",
        th: "เปิด",
        my: "ဖွင့်",
        km: "បើក",
      },
      furigana: [
        {
          rb: "開放",
          rt: "かいほう",
        },
      ],
      kanjiInfo: [
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "放",
          on: ["ホウ"],
          kun: [
            "はな.す",
            "-っぱな.し",
            "はな.つ",
            "はな.れる",
            "こ.く",
            "ほう.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 250,
      kanji: "海洋",
      reading: "かいよう",
      meanings: {
        ja: "海洋",
        en: "ocean",
        zh: "海洋",
        tw: "海洋",
        ko: "해양",
        vi: "đại dương",
        th: "มหาสมุทร",
        my: "ပင်လယ်ကြီး",
        km: "សមុទ្រ",
      },
      furigana: [
        {
          rb: "海洋",
          rt: "かいよう",
        },
      ],
      kanjiInfo: [
        {
          char: "海",
          on: ["カイ"],
          kun: ["うみ"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "洋",
          on: ["ヨウ"],
          kun: [],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
