export const n2part3 = {
  Lesson3: [
    {
      id: 101,
      kanji: "図形",
      reading: "ずけい",
      meanings: {
        ja: "図形／形や図",
        en: "figure; diagram",
        zh: "圖形",
        tw: "圖形",
        ko: "도형",
        vi: "hình dạng; sơ đồ",
        th: "รูปทรง; แผนภาพ",
        my: "ပုံသဏ္ဍာန်",
        km: "រូបរាង",
      },
      furigana: [
        {
          rb: "図形",
          rt: "ずけい",
        },
      ],
      kanjiInfo: [
        {
          char: "図",
          on: ["ズ", "ト"],
          kun: ["え", "はか.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "形",
          on: ["ケイ", "ギョウ"],
          kun: ["かた", "-がた", "かたち", "なり"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 102,
      kanji: "鈴",
      reading: "すず",
      meanings: {
        ja: "鈴／ベルのような音の出るもの",
        en: "bell (often globular)",
        zh: "鈴",
        tw: "鈴鐺",
        ko: "방울",
        vi: "chuông nhỏ",
        th: "กระดิ่ง",
        my: "ခေါင်းလောင်း",
        km: "កណ្តឹងតូច",
      },
      furigana: [
        {
          rb: "鈴",
          rt: "すず",
        },
      ],
      kanjiInfo: [
        {
          char: "鈴",
          on: ["レイ", "リン"],
          kun: ["すず"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 103,
      kanji: "スタート",
      reading: "スタート",
      meanings: {
        ja: "スタート／始まり",
        en: "start; beginning",
        zh: "開始",
        tw: "開始",
        ko: "시작",
        vi: "bắt đầu",
        th: "เริ่มต้น",
        my: "အစပြုခြင်း",
        km: "ចាប់ផ្តើម",
      },
      furigana: [
        {
          rb: "スタート",
          rt: "スタート",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 104,
      kanji: "スチュワーデス",
      reading: "スチュワーデス",
      meanings: {
        ja: "スチュワーデス／客室乗務員",
        en: "stewardess; flight attendant",
        zh: "空中小姐",
        tw: "空服員",
        ko: "승무원",
        vi: "tiếp viên hàng không",
        th: "พนักงานต้อนรับบนเครื่องบิน",
        my: "လေယာဉ်မှူးအမျိုးသမီး",
        km: "អ្នកបម្រើលើយន្តហោះ",
      },
      furigana: [
        {
          rb: "スチュワーデス",
          rt: "スチュワーデス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 105,
      kanji: "ステージ",
      reading: "ステージ",
      meanings: {
        ja: "ステージ／舞台",
        en: "stage (platform)",
        zh: "舞台",
        tw: "舞台",
        ko: "무대",
        vi: "sân khấu",
        th: "เวที",
        my: "မင်းဇါတ်စင်",
        km: "ឆាក",
      },
      furigana: [
        {
          rb: "ステージ",
          rt: "ステージ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 106,
      kanji: "ストッキング",
      reading: "ストッキング",
      meanings: {
        ja: "ストッキング／女性用の長い靴下",
        en: "stockings",
        zh: "長襪",
        tw: "絲襪",
        ko: "스타킹",
        vi: "vớ dài",
        th: "ถุงน่อง",
        my: "အရှည်ပြတ်ခြင်း",
        km: "ស្រោមជើងវែង",
      },
      furigana: [
        {
          rb: "ストッキング",
          rt: "ストッキング",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 107,
      kanji: "ストップ",
      reading: "ストップ",
      meanings: {
        ja: "ストップ／止まること",
        en: "stop; halt",
        zh: "停止",
        tw: "停止",
        ko: "멈춤",
        vi: "dừng lại",
        th: "หยุด",
        my: "ရပ်နားခြင်း",
        km: "ឈប់",
      },
      furigana: [
        {
          rb: "ストップ",
          rt: "ストップ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 108,
      kanji: "頭脳",
      reading: "ずのう",
      meanings: {
        ja: "頭脳／頭の働き",
        en: "head; intellect",
        zh: "頭腦",
        tw: "頭腦",
        ko: "두뇌",
        vi: "trí óc",
        th: "สมอง",
        my: "ဉာဏ်",
        km: "ខួរក្បាល",
      },
      furigana: [
        {
          rb: "頭脳",
          rt: "ずのう",
        },
      ],
      kanjiInfo: [
        {
          char: "頭",
          on: ["トウ", "ズ", "ト"],
          kun: ["あたま", "かしら", "-がしら", "かぶり"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "脳",
          on: ["ノウ", "ドウ"],
          kun: ["のうずる"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 109,
      kanji: "スピーカー",
      reading: "スピーカー",
      meanings: {
        ja: "スピーカー／音を出す装置",
        en: "speaker",
        zh: "喇叭",
        tw: "喇叭",
        ko: "스피커",
        vi: "loa",
        th: "ลำโพง",
        my: "စပီကာ",
        km: "ឡោ",
      },
      furigana: [
        {
          rb: "スピーカー",
          rt: "スピーカー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 110,
      kanji: "図表",
      reading: "ずひょう",
      meanings: {
        ja: "図表／グラフや表",
        en: "chart; diagram",
        zh: "圖表",
        tw: "圖表",
        ko: "도표",
        vi: "biểu đồ",
        th: "แผนภูมิ",
        my: "ဇယား",
        km: "តារាង",
      },
      furigana: [
        {
          rb: "図表",
          rt: "ずひょう",
        },
      ],
      kanjiInfo: [
        {
          char: "図",
          on: ["ズ", "ト"],
          kun: ["え", "はか.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "表",
          on: ["ヒョウ"],
          kun: ["おもて", "-おもて", "あらわ.す", "あらわ.れる", "あら.わす"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 111,
      kanji: "住まい",
      reading: "すまい",
      meanings: {
        ja: "住まい／住む場所",
        en: "dwelling; residence",
        zh: "住所",
        tw: "住所",
        ko: "주거; 집",
        vi: "nơi ở",
        th: "ที่อยู่อาศัย",
        my: "နေရာ",
        km: "ទីលំនៅ",
      },
      furigana: [
        {
          rb: "住まい",
          rt: "すまい",
        },
      ],
      kanjiInfo: [
        {
          char: "住",
          on: ["ジュウ", "ヂュウ", "チュウ"],
          kun: ["す.む", "す.まう", "-ず.まい"],
          strokes: 7,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 112,
      kanji: "相撲",
      reading: "すもう",
      meanings: {
        ja: "相撲／日本の伝統的な格闘技",
        en: "sumo (wrestling)",
        zh: "相撲",
        tw: "相撲",
        ko: "스모",
        vi: "đô vật sumo",
        th: "ซูโม่",
        my: "စုမိုကာယ",
        km: "សូម៉ូ",
      },
      furigana: [
        {
          rb: "相撲",
          rt: "すもう",
        },
      ],
      kanjiInfo: [
        {
          char: "相",
          on: ["ソウ", "ショウ"],
          kun: ["あい-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "撲",
          on: ["ボク"],
          kun: [],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 113,
      kanji: "スライド",
      reading: "スライド",
      meanings: {
        ja: "スライド／投影用の写真",
        en: "slide (for projection)",
        zh: "投影片",
        tw: "投影片",
        ko: "슬라이드",
        vi: "ảnh chiếu",
        th: "สไลด์",
        my: "အလင်းပုံ",
        km: "ស្លាយ",
      },
      furigana: [
        {
          rb: "スライド",
          rt: "スライド",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 114,
      kanji: "スリッパ",
      reading: "スリッパ",
      meanings: {
        ja: "スリッパ／室内用の履物",
        en: "slippers",
        zh: "拖鞋",
        tw: "拖鞋",
        ko: "슬리퍼",
        vi: "dép đi trong nhà",
        th: "รองเท้าแตะในบ้าน",
        my: "အိမ်တွင်းဖိနပ်",
        km: "ស្បែកជើងផ្ទះ",
      },
      furigana: [
        {
          rb: "スリッパ",
          rt: "スリッパ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 115,
      kanji: "寸法",
      reading: "すんぽう",
      meanings: {
        ja: "寸法／長さや大きさ",
        en: "measurement; size",
        zh: "尺寸",
        tw: "尺寸",
        ko: "치수",
        vi: "kích thước",
        th: "ขนาด",
        my: "အရွယ်အစား",
        km: "វិមាត្រ",
      },
      furigana: [
        {
          rb: "寸法",
          rt: "すんぽう",
        },
      ],
      kanjiInfo: [
        {
          char: "寸",
          on: ["スン"],
          kun: [],
          strokes: 3,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "法",
          on: ["ホウ", "ハッ", "ホッ", "フラン"],
          kun: ["のり"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 116,
      kanji: "税関",
      reading: "ぜいかん",
      meanings: {
        ja: "税関／輸出入を監督する所",
        en: "customs",
        zh: "海關",
        tw: "海關",
        ko: "세관",
        vi: "hải quan",
        th: "ศุลกากร",
        my: "သွင်းကုန်နှင့်ထုတ်ကုန်ဦးစီးဌာန",
        km: "សេវារដ្ឋបាលគយ",
      },
      furigana: [
        {
          rb: "税関",
          rt: "ぜいかん",
        },
      ],
      kanjiInfo: [
        {
          char: "税",
          on: ["ゼイ"],
          kun: [],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "関",
          on: ["カン"],
          kun: ["せき", "-ぜき", "かか.わる", "からくり", "かんぬき"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 117,
      kanji: "製作",
      reading: "せいさく",
      meanings: {
        ja: "製作／機械・道具を作る",
        en: "manufacture; production",
        zh: "製作",
        tw: "製作",
        ko: "제작",
        vi: "chế tạo",
        th: "ผลิต",
        my: "ထုတ်လုပ်ခြင်း",
        km: "ផលិតកម្ម",
      },
      furigana: [
        {
          rb: "製作",
          rt: "せいさく",
        },
      ],
      kanjiInfo: [
        {
          char: "製",
          on: ["セイ"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 118,
      kanji: "制作",
      reading: "せいさく",
      meanings: {
        ja: "制作／作品などを作る",
        en: "creation (film, art)",
        zh: "製作 (藝術等)",
        tw: "製作 (藝術)",
        ko: "제작 (예술)",
        vi: "sản xuất (phim, nghệ thuật)",
        th: "สร้าง (ผลงานศิลป์)",
        my: "ဖန်တီးမှု",
        km: "បង្កើតស្នាដៃ",
      },
      furigana: [
        {
          rb: "制作",
          rt: "せいさく",
        },
      ],
      kanjiInfo: [
        {
          char: "制",
          on: ["セイ"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 119,
      kanji: "清書",
      reading: "せいしょ",
      meanings: {
        ja: "清書／きれいに書き直す",
        en: "fair copy; clean writing",
        zh: "清稿",
        tw: "清稿",
        ko: "정서",
        vi: "chép lại sạch",
        th: "เขียนใหม่ให้เรียบร้อย",
        my: "ပြန်ရေးခြင်း",
        km: "សរសេរឡើងវិញឱ្យស្អាត",
      },
      furigana: [
        {
          rb: "清書",
          rt: "せいしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "清",
          on: ["セイ", "ショウ", "シン"],
          kun: ["きよ.い", "きよ.まる", "きよ.める"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 120,
      kanji: "青少年",
      reading: "せいしょうねん",
      meanings: {
        ja: "青少年／若い人たち",
        en: "young people; youth",
        zh: "青少年",
        tw: "青少年",
        ko: "청소년",
        vi: "thanh thiếu niên",
        th: "เยาวชน",
        my: "လူငယ်",
        km: "យុវជន",
      },
      furigana: [
        {
          rb: "青少年",
          rt: "せいしょうねん",
        },
      ],
      kanjiInfo: [
        {
          char: "青",
          on: ["セイ", "ショウ"],
          kun: ["あお", "あお-", "あお.い"],
          strokes: 8,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "少",
          on: ["ショウ"],
          kun: ["すく.ない", "すこ.し"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 121,
      kanji: "整数",
      reading: "せいすう",
      meanings: {
        ja: "整数／整数の数",
        en: "integer",
        zh: "整數",
        tw: "整數",
        ko: "정수",
        vi: "số nguyên",
        th: "จำนวนเต็ม",
        my: "အပြည့်အတင်းအနံဉ်",
        km: "ចំនួនគត់",
      },
      furigana: [
        {
          rb: "整数",
          rt: "せいすう",
        },
      ],
      kanjiInfo: [
        {
          char: "整",
          on: ["セイ"],
          kun: ["ととの.える", "ととの.う"],
          strokes: 16,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 122,
      kanji: "清掃",
      reading: "せいそう",
      meanings: {
        ja: "清掃／掃除すること",
        en: "cleaning",
        zh: "清掃",
        tw: "清掃",
        ko: "청소",
        vi: "vệ sinh",
        th: "ทำความสะอาด",
        my: "သန့်ရှင်းရေး",
        km: "សម្អាត",
      },
      furigana: [
        {
          rb: "清掃",
          rt: "せいそう",
        },
      ],
      kanjiInfo: [
        {
          char: "清",
          on: ["セイ", "ショウ", "シン"],
          kun: ["きよ.い", "きよ.まる", "きよ.める"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "掃",
          on: ["ソウ", "シュ"],
          kun: ["は.く"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 123,
      kanji: "生存",
      reading: "せいぞん",
      meanings: {
        ja: "生存／生きて存在すること",
        en: "existence; survival",
        zh: "生存",
        tw: "生存",
        ko: "생존",
        vi: "tồn tại; sinh tồn",
        th: "มีชีวิตอยู่",
        my: "အသက်ရှင်နေတာ",
        km: "រស់រានមានជីវិត",
      },
      furigana: [
        {
          rb: "生存",
          rt: "せいぞん",
        },
      ],
      kanjiInfo: [
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "存",
          on: ["ソン", "ゾン"],
          kun: ["ながら.える", "あ.る", "たも.つ", "と.う"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 124,
      kanji: "政党",
      reading: "せいとう",
      meanings: {
        ja: "政党／政治団体",
        en: "political party",
        zh: "政黨",
        tw: "政黨",
        ko: "정당",
        vi: "đảng chính trị",
        th: "พรรคการเมือง",
        my: "နိုင်ငံရေးပါတီ",
        km: "គណបក្សនយោបាយ",
      },
      furigana: [
        {
          rb: "政党",
          rt: "せいとう",
        },
      ],
      kanjiInfo: [
        {
          char: "政",
          on: ["セイ", "ショウ"],
          kun: ["まつりごと", "まん"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "党",
          on: ["トウ"],
          kun: ["なかま", "むら"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 125,
      kanji: "性能",
      reading: "せいのう",
      meanings: {
        ja: "性能／機械などの能力",
        en: "ability; performance",
        zh: "性能",
        tw: "性能",
        ko: "성능",
        vi: "hiệu suất; năng lực",
        th: "สมรรถนะ",
        my: "စွမ်းဆောင်ရည်",
        km: "សមត្ថភាព",
      },
      furigana: [
        {
          rb: "性能",
          rt: "せいのう",
        },
      ],
      kanjiInfo: [
        {
          char: "性",
          on: ["セイ", "ショウ"],
          kun: ["さが"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 126,
      kanji: "整備",
      reading: "せいび",
      meanings: {
        ja: "整備／整える・修理する",
        en: "maintenance; servicing",
        zh: "維修",
        tw: "維修",
        ko: "정비",
        vi: "bảo dưỡng",
        th: "บำรุงรักษา",
        my: "ပြုပြင်ထိန်းသိမ်းခြင်း",
        km: "ថែទាំជួសជុល",
      },
      furigana: [
        {
          rb: "整備",
          rt: "せいび",
        },
      ],
      kanjiInfo: [
        {
          char: "整",
          on: ["セイ"],
          kun: ["ととの.える", "ととの.う"],
          strokes: 16,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "備",
          on: ["ビ"],
          kun: ["そな.える", "そな.わる", "つぶさ.に"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 127,
      kanji: "成分",
      reading: "せいぶん",
      meanings: {
        ja: "成分／構成するもの",
        en: "ingredient; component",
        zh: "成分",
        tw: "成分",
        ko: "성분",
        vi: "thành phần",
        th: "ส่วนประกอบ",
        my: "ပါဝင်ပစ္စည်း",
        km: "សមាសធាតុ",
      },
      furigana: [
        {
          rb: "成分",
          rt: "せいぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 128,
      kanji: "性別",
      reading: "せいべつ",
      meanings: {
        ja: "性別／男女の区別",
        en: "sex; gender",
        zh: "性別",
        tw: "性別",
        ko: "성별",
        vi: "giới tính",
        th: "เพศ",
        my: "လိင်အမျိုးအစား",
        km: "ភេទ",
      },
      furigana: [
        {
          rb: "性別",
          rt: "せいべつ",
        },
      ],
      kanjiInfo: [
        {
          char: "性",
          on: ["セイ", "ショウ"],
          kun: ["さが"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "別",
          on: ["ベツ"],
          kun: ["わか.れる", "わ.ける"],
          strokes: 7,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 129,
      kanji: "正方形",
      reading: "せいほうけい",
      meanings: {
        ja: "正方形／四つの辺が等しい形",
        en: "square (shape)",
        zh: "正方形",
        tw: "正方形",
        ko: "정사각형",
        vi: "hình vuông",
        th: "สี่เหลี่ยมจัตุรัส",
        my: "စတုဂံ",
        km: "ការ៉េ",
      },
      furigana: [
        {
          rb: "正方形",
          rt: "せいほうけい",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "方",
          on: ["ホウ"],
          kun: ["かた", "-かた", "-がた"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "形",
          on: ["ケイ", "ギョウ"],
          kun: ["かた", "-がた", "かたち", "なり"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 130,
      kanji: "正門",
      reading: "せいもん",
      meanings: {
        ja: "正門／主要な入口",
        en: "main gate",
        zh: "正門",
        tw: "正門",
        ko: "정문",
        vi: "cổng chính",
        th: "ประตูหลัก",
        my: "အဓိကတံခါးဝ",
        km: "ច្រកចូលសំខាន់",
      },
      furigana: [
        {
          rb: "正門",
          rt: "せいもん",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "門",
          on: ["モン"],
          kun: ["かど", "と"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 131,
      kanji: "成立",
      reading: "せいりつ",
      meanings: {
        ja: "成立／できあがること",
        en: "formation; establishment",
        zh: "成立",
        tw: "成立",
        ko: "성립",
        vi: "hình thành",
        th: "ก่อตั้ง",
        my: "တည်ထောင်ခြင်း",
        km: "បង្កើតឡើង",
      },
      furigana: [
        {
          rb: "成立",
          rt: "せいりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "成",
          on: ["セイ", "ジョウ"],
          kun: ["な.る", "な.す", "-な.す"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "立",
          on: ["リツ", "リュウ", "リットル"],
          kun: [
            "た.つ",
            "-た.つ",
            "た.ち-",
            "た.てる",
            "-た.てる",
            "た.て-",
            "たて-",
            "-た.て",
            "-だ.て",
            "-だ.てる",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 132,
      kanji: "西暦",
      reading: "せいれき",
      meanings: {
        ja: "西暦／キリスト暦",
        en: "Common Era; AD",
        zh: "西曆",
        tw: "西曆",
        ko: "서력",
        vi: "Công nguyên",
        th: "คริสต์ศักราช",
        my: "အနောက်နှစ်",
        km: "គ្រឹស្តសករាជ",
      },
      furigana: [
        {
          rb: "西暦",
          rt: "せいれき",
        },
      ],
      kanjiInfo: [
        {
          char: "西",
          on: ["セイ", "サイ", "ス"],
          kun: ["にし"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "暦",
          on: ["レキ", "リャク"],
          kun: ["こよみ"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 133,
      kanji: "赤道",
      reading: "せきどう",
      meanings: {
        ja: "赤道／地球の中心を通る線",
        en: "equator",
        zh: "赤道",
        tw: "赤道",
        ko: "적도",
        vi: "xích đạo",
        th: "เส้นศูนย์สูตร",
        my: "အကြောင်းတန်း",
        km: "ស្មើ",
      },
      furigana: [
        {
          rb: "赤道",
          rt: "せきどう",
        },
      ],
      kanjiInfo: [
        {
          char: "赤",
          on: ["セキ", "シャク"],
          kun: ["あか", "あか-", "あか.い", "あか.らむ", "あか.らめる"],
          strokes: 7,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "道",
          on: ["ドウ", "トウ"],
          kun: ["みち", "いう"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 134,
      kanji: "接近",
      reading: "せっきん",
      meanings: {
        ja: "接近／近づくこと",
        en: "approach; getting closer",
        zh: "接近",
        tw: "接近",
        ko: "접근",
        vi: "tiếp cận",
        th: "เข้าใกล้",
        my: "နီးစပ်လာခြင်း",
        km: "ចូលជិត",
      },
      furigana: [
        {
          rb: "接近",
          rt: "せっきん",
        },
      ],
      kanjiInfo: [
        {
          char: "接",
          on: ["セツ", "ショウ"],
          kun: ["つ.ぐ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "近",
          on: ["キン", "コン"],
          kun: ["ちか.い"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 135,
      kanji: "接続",
      reading: "せつぞく",
      meanings: {
        ja: "接続／つなぐこと",
        en: "connection",
        zh: "連接",
        tw: "連接",
        ko: "연결",
        vi: "kết nối",
        th: "เชื่อมต่อ",
        my: "ချိတ်ဆက်ခြင်း",
        km: "តភ្ជាប់",
      },
      furigana: [
        {
          rb: "接続",
          rt: "せつぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "接",
          on: ["セツ", "ショウ"],
          kun: ["つ.ぐ"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 136,
      kanji: "瀬戸物",
      reading: "せともの",
      meanings: {
        ja: "瀬戸物／陶器",
        en: "earthenware; pottery",
        zh: "陶器",
        tw: "陶瓷",
        ko: "도자기",
        vi: "đồ sứ; gốm",
        th: "เครื่องปั้นดินเผา",
        my: "ပန်းကန်ချိုင့်",
        km: "ដំណាក់កាលដីឥដ្ឋ",
      },
      furigana: [
        {
          rb: "瀬戸物",
          rt: "せともの",
        },
      ],
      kanjiInfo: [
        {
          char: "瀬",
          on: ["ライ"],
          kun: ["せ"],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "戸",
          on: ["コ"],
          kun: ["と"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 137,
      kanji: "ゼミ",
      reading: "ゼミ",
      meanings: {
        ja: "ゼミ／少人数の授業",
        en: "seminar",
        zh: "討論課",
        tw: "研討課",
        ko: "세미나",
        vi: "hội thảo",
        th: "สัมมนา",
        my: "ဆွေးနွေးပွဲ",
        km: "សិក្ខាសាលា",
      },
      furigana: [
        {
          rb: "ゼミ",
          rt: "ゼミ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 138,
      kanji: "セメント",
      reading: "セメント",
      meanings: {
        ja: "セメント／建築用材料",
        en: "cement",
        zh: "水泥",
        tw: "水泥",
        ko: "시멘트",
        vi: "xi măng",
        th: "ปูนซีเมนต์",
        my: "စီမံ့",
        km: "ស៊ីមង់",
      },
      furigana: [
        {
          rb: "セメント",
          rt: "セメント",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 139,
      kanji: "台詞",
      reading: "せりふ",
      meanings: {
        ja: "台詞／芝居で言う言葉",
        en: "spoken line (in a play)",
        zh: "台詞",
        tw: "台詞",
        ko: "대사",
        vi: "lời thoại",
        th: "บทพูด",
        my: "ဇာတ်လမ်းစကား",
        km: "សន្ទនា",
      },
      furigana: [
        {
          rb: "台詞",
          rt: "せりふ",
        },
      ],
      kanjiInfo: [
        {
          char: "台",
          on: ["ダイ", "タイ"],
          kun: ["うてな", "われ", "つかさ"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 140,
      kanji: "栓",
      reading: "せん",
      meanings: {
        ja: "栓／液体を止めるもの",
        en: "stopper; plug",
        zh: "塞子",
        tw: "塞子",
        ko: "마개",
        vi: "nút chai",
        th: "จุก; ฝา",
        my: "ပိတ်ကပ်",
        km: "គម្រប",
      },
      furigana: [
        {
          rb: "栓",
          rt: "せん",
        },
      ],
      kanjiInfo: [
        {
          char: "栓",
          on: ["セン"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 141,
      kanji: "前後",
      reading: "ぜんご",
      meanings: {
        ja: "前後／前と後ろ",
        en: "front and rear; before and after",
        zh: "前後",
        tw: "前後",
        ko: "전후",
        vi: "trước và sau",
        th: "ก่อนและหลัง",
        my: "အရှေ့နဲ့နောက်",
        km: "មុខនិងក្រោយ",
      },
      furigana: [
        {
          rb: "前後",
          rt: "ぜんご",
        },
      ],
      kanjiInfo: [
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "後",
          on: ["ゴ", "コウ"],
          kun: ["のち", "うし.ろ", "うしろ", "あと", "おく.れる"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 142,
      kanji: "全集",
      reading: "ぜんしゅう",
      meanings: {
        ja: "全集／全ての作品",
        en: "complete works",
        zh: "全集",
        tw: "全集",
        ko: "전집",
        vi: "toàn tập",
        th: "ชุดผลงานครบ",
        my: "စာအုပ်စုအပြည့်",
        km: "ស្នាដៃពេញ",
      },
      furigana: [
        {
          rb: "全集",
          rt: "ぜんしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "全",
          on: ["ゼン"],
          kun: ["まった.く", "すべ.て"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "集",
          on: ["シュウ"],
          kun: ["あつ.まる", "あつ.める", "つど.う"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 143,
      kanji: "扇子",
      reading: "せんす",
      meanings: {
        ja: "扇子／折りたたみのうちわ",
        en: "folding fan",
        zh: "摺扇",
        tw: "摺扇",
        ko: "부채",
        vi: "quạt xếp",
        th: "พัดพับ",
        my: "အုပ်ပန်",
        km: "កង្ហារបត់",
      },
      furigana: [
        {
          rb: "扇子",
          rt: "せんす",
        },
      ],
      kanjiInfo: [
        {
          char: "扇",
          on: ["セン"],
          kun: ["おうぎ"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 144,
      kanji: "専制",
      reading: "せんせい",
      meanings: {
        ja: "専制／独裁政治",
        en: "despotism; autocracy",
        zh: "專制",
        tw: "專制",
        ko: "전제정치",
        vi: "chuyên chế",
        th: "เผด็จการ",
        my: "အာဏာရှင်",
        km: "អំណាចផ្តាច់ការ",
      },
      furigana: [
        {
          rb: "専制",
          rt: "せんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "専",
          on: ["セン"],
          kun: ["もっぱ.ら"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "制",
          on: ["セイ"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 145,
      kanji: "先々月",
      reading: "せんせんげつ",
      meanings: {
        ja: "先々月／二ヶ月前",
        en: "month before last",
        zh: "上上個月",
        tw: "上上個月",
        ko: "지지난달",
        vi: "tháng trước nữa",
        th: "สองเดือนก่อน",
        my: "နှစ်လမတိုင်မီ",
        km: "ខែមុនពីរ",
      },
      furigana: [
        {
          rb: "先々月",
          rt: "せんせんげつ",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 146,
      kanji: "先々週",
      reading: "せんせんしゅう",
      meanings: {
        ja: "先々週／二週間前",
        en: "week before last",
        zh: "上上週",
        tw: "上上週",
        ko: "지지난주",
        vi: "tuần trước nữa",
        th: "สองสัปดาห์ก่อน",
        my: "ပတ်စဉ်နှစ်ပတ်လုံး",
        km: "សប្ដាហ៍មុនពីរ",
      },
      furigana: [
        {
          rb: "先々週",
          rt: "せんせんしゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
        {
          char: "週",
          on: ["シュウ"],
          kun: [],
          strokes: 11,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 147,
      kanji: "先祖",
      reading: "せんぞ",
      meanings: {
        ja: "先祖／家族の昔の人",
        en: "ancestor",
        zh: "祖先",
        tw: "祖先",
        ko: "조상",
        vi: "tổ tiên",
        th: "บรรพบุรุษ",
        my: "အဖိုးအဖွား",
        km: "បុព្វបុរស",
      },
      furigana: [
        {
          rb: "先祖",
          rt: "せんぞ",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "祖",
          on: ["ソ"],
          kun: [],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 148,
      kanji: "先端",
      reading: "せんたん",
      meanings: {
        ja: "先端／物の先の部分",
        en: "pointed end; tip",
        zh: "尖端",
        tw: "尖端",
        ko: "첨단",
        vi: "đầu nhọn; tiên phong",
        th: "ปลายสุด",
        my: "တွန်တံ",
        km: "ចុងស្រួច",
      },
      furigana: [
        {
          rb: "先端",
          rt: "せんたん",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "端",
          on: ["タン"],
          kun: ["はし", "は", "はた", "-ばた", "はな"],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 149,
      kanji: "センチ",
      reading: "センチ",
      meanings: {
        ja: "センチ／センチメートル",
        en: "centimeter",
        zh: "公分",
        tw: "公分",
        ko: "센티미터",
        vi: "xentimét",
        th: "เซนติเมตร",
        my: "စင်တီမီတာ",
        km: "សង់ទីម៉ែត្រ",
      },
      furigana: [
        {
          rb: "センチ",
          rt: "センチ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 150,
      kanji: "先頭",
      reading: "せんとう",
      meanings: {
        ja: "先頭／列の前",
        en: "head (of a line); front",
        zh: "隊首",
        tw: "隊首",
        ko: "선두",
        vi: "đầu hàng",
        th: "หัวแถว",
        my: "အဖွဲ့ဦး",
        km: "មុខជួរ",
      },
      furigana: [
        {
          rb: "先頭",
          rt: "せんとう",
        },
      ],
      kanjiInfo: [
        {
          char: "先",
          on: ["セン"],
          kun: ["さき", "ま.ず"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "頭",
          on: ["トウ", "ズ", "ト"],
          kun: ["あたま", "かしら", "-がしら", "かぶり"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
