export const n2part16 = {
  Lesson16: [
    {
      id: 751,
      kanji: "表紙",
      reading: "ひょうし",
      meanings: {
        ja: "表紙",
        en: "cover (of a book)",
        zh: "封面",
        tw: "封面",
        ko: "표지",
        vi: "bìa (sách)",
        th: "ปกหนังสือ",
        my: "စာအုပ်အဖုံး",
        km: "ក្របសៀវភៅ",
      },
      furigana: [
        {
          rb: "表紙",
          rt: "ひょうし",
        },
      ],
      kanjiInfo: [
        {
          char: "表",
          on: ["ヒョウ"],
          kun: ["おもて", "-おもて", "あらわ.す", "あらわ.れる", "あら.わす"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "紙",
          on: ["シ"],
          kun: ["かみ"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 752,
      kanji: "標識",
      reading: "ひょうしき",
      meanings: {
        ja: "標識",
        en: "sign",
        zh: "标识",
        tw: "標識",
        ko: "표지",
        vi: "biển báo",
        th: "ป้ายสัญลักษณ์",
        my: "အမှတ်အသား",
        km: "សញ្ញា",
      },
      furigana: [
        {
          rb: "標識",
          rt: "ひょうしき",
        },
      ],
      kanjiInfo: [
        {
          char: "標",
          on: ["ヒョウ"],
          kun: ["しるべ", "しるし"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "識",
          on: ["シキ"],
          kun: ["し.る", "しる.す"],
          strokes: 19,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 753,
      kanji: "標準",
      reading: "ひょうじゅん",
      meanings: {
        ja: "標準",
        en: "standard",
        zh: "标准",
        tw: "標準",
        ko: "표준",
        vi: "tiêu chuẩn",
        th: "มาตรฐาน",
        my: "စံ",
        km: "ស្តង់ដារ",
      },
      furigana: [
        {
          rb: "標準",
          rt: "ひょうじゅん",
        },
      ],
      kanjiInfo: [
        {
          char: "標",
          on: ["ヒョウ"],
          kun: ["しるべ", "しるし"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "準",
          on: ["ジュン"],
          kun: [
            "じゅん.じる",
            "じゅん.ずる",
            "なぞら.える",
            "のり",
            "ひと.しい",
            "みずもり",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 754,
      kanji: "標本",
      reading: "ひょうほん",
      meanings: {
        ja: "標本",
        en: "specimen",
        zh: "标本",
        tw: "標本",
        ko: "표본",
        vi: "mẫu vật",
        th: "ตัวอย่าง (ตัวอย่างวิทยาศาสตร์)",
        my: "နမူနာ",
        km: "គំរូ",
      },
      furigana: [
        {
          rb: "標本",
          rt: "ひょうほん",
        },
      ],
      kanjiInfo: [
        {
          char: "標",
          on: ["ヒョウ"],
          kun: ["しるべ", "しるし"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "本",
          on: ["ホン"],
          kun: ["もと"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 755,
      kanji: "評論",
      reading: "ひょうろん",
      meanings: {
        ja: "評論",
        en: "criticism; critique",
        zh: "评论",
        tw: "評論",
        ko: "평론",
        vi: "phê bình",
        th: "วิจารณ์",
        my: "ဝေဖန်ချက်",
        km: "វិភាគវិចារណកថា",
      },
      furigana: [
        {
          rb: "評論",
          rt: "ひょうろん",
        },
      ],
      kanjiInfo: [
        {
          char: "評",
          on: ["ヒョウ"],
          kun: [],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 756,
      kanji: "ビルディング",
      reading: "ビルディング",
      meanings: {
        ja: "ビルディング",
        en: "multi-floor building",
        zh: "大楼",
        tw: "大樓",
        ko: "빌딩",
        vi: "tòa nhà nhiều tầng",
        th: "อาคารหลายชั้น",
        my: "ဆိုဒ်ကြီးအဆောက်အဦ",
        km: "អគារពហុជាន់",
      },
      furigana: [
        {
          rb: "ビルディング",
          rt: "ビルディング",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 757,
      kanji: "昼寝",
      reading: "ひるね",
      meanings: {
        ja: "昼寝",
        en: "(afternoon) nap",
        zh: "午睡",
        tw: "午睡",
        ko: "낮잠",
        vi: "ngủ trưa",
        th: "งีบตอนบ่าย",
        my: "နေ့ခင်းအိပ်",
        km: "គេងថ្ងៃ",
      },
      furigana: [
        {
          rb: "昼寝",
          rt: "ひるね",
        },
      ],
      kanjiInfo: [
        {
          char: "昼",
          on: ["チュウ"],
          kun: ["ひる"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "寝",
          on: ["シン"],
          kun: ["ね.る", "ね.かす", "い.ぬ", "みたまや", "や.める"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 758,
      kanji: "広さ",
      reading: "ひろさ",
      meanings: {
        ja: "広さ",
        en: "area",
        zh: "面积",
        tw: "面積",
        ko: "넓이",
        vi: "diện tích",
        th: "พื้นที่",
        my: "ဧရိယာ",
        km: "ផ្ទៃក្រឡា",
      },
      furigana: [
        {
          rb: "広さ",
          rt: "ひろさ",
        },
      ],
      kanjiInfo: [
        {
          char: "広",
          on: ["コウ"],
          kun: ["ひろ.い", "ひろ.まる", "ひろ.める", "ひろ.がる", "ひろ.げる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 759,
      kanji: "広場",
      reading: "ひろば",
      meanings: {
        ja: "広場",
        en: "public square",
        zh: "广场",
        tw: "廣場",
        ko: "광장",
        vi: "quảng trường",
        th: "ลานสาธารณะ",
        my: "လယ်ကွင်းလူထု",
        km: "ទីលានសាធារណៈ",
      },
      furigana: [
        {
          rb: "広場",
          rt: "ひろば",
        },
      ],
      kanjiInfo: [
        {
          char: "広",
          on: ["コウ"],
          kun: ["ひろ.い", "ひろ.まる", "ひろ.める", "ひろ.がる", "ひろ.げる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 760,
      kanji: "ピンク",
      reading: "ピンク",
      meanings: {
        ja: "ピンク",
        en: "pink",
        zh: "粉红色",
        tw: "粉紅色",
        ko: "분홍색",
        vi: "màu hồng",
        th: "สีชมพู",
        my: "ပန်းရောင်",
        km: "ពណ៌ផ្កាឈូក",
      },
      furigana: [
        {
          rb: "ピンク",
          rt: "ピンク",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 761,
      kanji: "便箋",
      reading: "びんせん",
      meanings: {
        ja: "便箋",
        en: "writing paper (stationery)",
        zh: "信纸",
        tw: "信紙",
        ko: "편지지",
        vi: "giấy viết thư",
        th: "กระดาษเขียนจดหมาย",
        my: "စာရေးကတ်",
        km: "ក្រដាសសំបុត្រ",
      },
      furigana: [
        {
          rb: "便箋",
          rt: "びんせん",
        },
      ],
      kanjiInfo: [
        {
          char: "便",
          on: ["ベン", "ビン"],
          kun: ["たよ.り"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "箋",
          on: ["セン"],
          kun: ["ふだ"],
          strokes: 14,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 762,
      kanji: "瓶詰",
      reading: "びんづめ",
      meanings: {
        ja: "瓶詰",
        en: "bottling; bottled",
        zh: "装瓶；瓶装",
        tw: "裝瓶；瓶裝",
        ko: "병에 담음",
        vi: "đóng chai",
        th: "บรรจุขวด",
        my: "ပုလင်းထည့်",
        km: "ដាក់ដប",
      },
      furigana: [
        {
          rb: "瓶詰",
          rt: "びんづめ",
        },
      ],
      kanjiInfo: [
        {
          char: "瓶",
          on: ["ビン", "ヘイ"],
          kun: ["かめ"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "詰",
          on: ["キツ", "キチ"],
          kun: ["つ.める", "つ.め", "-づ.め", "つ.まる", "つ.む"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 763,
      kanji: "ファスナー",
      reading: "ファスナー",
      meanings: {
        ja: "ファスナー",
        en: "zip fastener; zipper",
        zh: "拉链",
        tw: "拉鍊",
        ko: "지퍼",
        vi: "khóa kéo",
        th: "ซิป",
        my: "ဇစ်ပေါက်",
        km: "ហ្ស៊ីអ៊ឺរ",
      },
      furigana: [
        {
          rb: "ファスナー",
          rt: "ファスナー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 764,
      kanji: "風船",
      reading: "ふうせん",
      meanings: {
        ja: "風船",
        en: "balloon (toy/decoration)",
        zh: "气球",
        tw: "氣球",
        ko: "풍선",
        vi: "bóng bay",
        th: "ลูกโป่ง",
        my: "ပုံးအမြှောက်",
        km: "ប៉ុង",
      },
      furigana: [
        {
          rb: "風船",
          rt: "ふうせん",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "船",
          on: ["セン"],
          kun: ["ふね", "ふな-"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 765,
      kanji: "不運",
      reading: "ふうん",
      meanings: {
        ja: "不運",
        en: "misfortune",
        zh: "不幸/倒霉",
        tw: "不幸/倒楣",
        ko: "불운",
        vi: "xui xẻo",
        th: "เคราะห์ร้าย",
        my: "ကံမကောင်းမှု",
        km: "អសំណាង",
      },
      furigana: [
        {
          rb: "不運",
          rt: "ふうん",
        },
      ],
      kanjiInfo: [
        {
          char: "不",
          on: ["フ", "ブ"],
          kun: [],
          strokes: 4,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "運",
          on: ["ウン"],
          kun: ["はこ.ぶ"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 766,
      kanji: "普及",
      reading: "ふきゅう",
      meanings: {
        ja: "普及",
        en: "diffusion; spread",
        zh: "普及",
        tw: "普及",
        ko: "보급",
        vi: "phổ cập",
        th: "แพร่หลาย",
        my: "ဖြန့်ချိမှု",
        km: "ការផ្សព្វផ្សាយលាតសន្ធឹង",
      },
      furigana: [
        {
          rb: "普及",
          rt: "ふきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "普",
          on: ["フ"],
          kun: ["あまね.く", "あまねし"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "及",
          on: ["キュウ"],
          kun: ["およ.ぶ", "およ.び", "および", "およ.ぼす"],
          strokes: 3,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 767,
      kanji: "付近",
      reading: "ふきん",
      meanings: {
        ja: "付近",
        en: "neighborhood; vicinity",
        zh: "附近",
        tw: "附近",
        ko: "부근",
        vi: "khu vực lân cận",
        th: "บริเวณใกล้เคียง",
        my: "နားလည်ပတ်ဝန်းကျင်",
        km: "តំបន់ជិតខាង",
      },
      furigana: [
        {
          rb: "付近",
          rt: "ふきん",
        },
      ],
      kanjiInfo: [
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "近",
          on: ["キン", "コン"],
          kun: ["ちか.い"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 768,
      kanji: "副詞",
      reading: "ふくし",
      meanings: {
        ja: "副詞",
        en: "adverb",
        zh: "副词",
        tw: "副詞",
        ko: "부사",
        vi: "trạng từ",
        th: "คำวิเศษณ์",
        my: "ကိန်းဝါချုပ် (副詞)",
        km: "គុណកិរិយា(វាក្យសព្ទ)",
      },
      furigana: [
        {
          rb: "副詞",
          rt: "ふくし",
        },
      ],
      kanjiInfo: [
        {
          char: "副",
          on: ["フク"],
          kun: [],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 769,
      kanji: "複写",
      reading: "ふくしゃ",
      meanings: {
        ja: "複写",
        en: "copying; duplication",
        zh: "复写",
        tw: "複寫",
        ko: "복사",
        vi: "sao chép",
        th: "คัดลอก",
        my: "မိတ္တူကူး",
        km: "ចម្លង",
      },
      furigana: [
        {
          rb: "複写",
          rt: "ふくしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "複",
          on: ["フク"],
          kun: [],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "写",
          on: ["シャ", "ジャ"],
          kun: ["うつ.す", "うつ.る", "うつ-", "うつ.し"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 770,
      kanji: "符号",
      reading: "ふごう",
      meanings: {
        ja: "符号",
        en: "sign; code; symbol",
        zh: "符号",
        tw: "符號",
        ko: "부호",
        vi: "ký hiệu",
        th: "สัญลักษณ์/รหัส",
        my: "သင်္ကေတ",
        km: "និមិត្តសញ្ញា/កូដ",
      },
      furigana: [
        {
          rb: "符号",
          rt: "ふごう",
        },
      ],
      kanjiInfo: [
        {
          char: "符",
          on: ["フ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "号",
          on: ["ゴウ"],
          kun: ["さけ.ぶ", "よびな"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 771,
      kanji: "夫妻",
      reading: "ふさい",
      meanings: {
        ja: "夫妻",
        en: "husband and wife",
        zh: "夫妇",
        tw: "夫妻",
        ko: "부부",
        vi: "vợ chồng",
        th: "สามีภรรยา",
        my: "ဇနီးမောင်နှံ",
        km: "ប្តីប្រពន្ធ",
      },
      furigana: [
        {
          rb: "夫妻",
          rt: "ふさい",
        },
      ],
      kanjiInfo: [
        {
          char: "夫",
          on: ["フ", "フウ", "ブ"],
          kun: ["おっと", "それ"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "妻",
          on: ["サイ"],
          kun: ["つま"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 772,
      kanji: "無沙汰",
      reading: "ぶさた",
      meanings: {
        ja: "無沙汰",
        en: "not writing or contacting for a while",
        zh: "久未联系",
        tw: "久未聯絡",
        ko: "오랫동안 소식 없음",
        vi: "lâu không liên lạc",
        th: "ไม่ได้ติดต่อมานาน",
        my: "ကြာကြာမဆက်သွယ်",
        km: "យូរហើយមិនទាក់ទង",
      },
      furigana: [
        {
          rb: "無沙汰",
          rt: "ぶさた",
        },
      ],
      kanjiInfo: [
        {
          char: "無",
          on: ["ム", "ブ"],
          kun: ["な.い"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "沙",
          on: ["サ", "シャ"],
          kun: ["すな", "よなげる"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "汰",
          on: ["タ", "タイ"],
          kun: ["おご.る", "にご.る", "よな.げる"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 773,
      kanji: "武士",
      reading: "ぶし",
      meanings: {
        ja: "武士",
        en: "samurai",
        zh: "武士",
        tw: "武士",
        ko: "무사",
        vi: "võ sĩ (samurai)",
        th: "ซามูไร",
        my: "ဂန္ဓဝင်တပ်သား",
        km: "សាមូរាយ",
      },
      furigana: [
        {
          rb: "武士",
          rt: "ぶし",
        },
      ],
      kanjiInfo: [
        {
          char: "武",
          on: ["ブ", "ム"],
          kun: ["たけ", "たけ.し"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "士",
          on: ["シ"],
          kun: ["さむらい"],
          strokes: 3,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 774,
      kanji: "部首",
      reading: "ぶしゅ",
      meanings: {
        ja: "部首",
        en: "radical (of a kanji)",
        zh: "部首",
        tw: "部首",
        ko: "부수",
        vi: "bộ thủ (chữ Hán)",
        th: "บุชุ (รากอักษรคันจิ)",
        my: "ခန်းဂျိ အမူအရာ",
        km: "គន្លឹះអក្សរខាន់ជី",
      },
      furigana: [
        {
          rb: "部首",
          rt: "ぶしゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "首",
          on: ["シュ"],
          kun: ["くび"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 775,
      kanji: "襖",
      reading: "ふすま",
      meanings: {
        ja: "襖",
        en: "fusuma (sliding screen)",
        zh: "襖（推拉門）",
        tw: "襖（拉門）",
        ko: "후스마(미닫이문)",
        vi: "cửa trượt fusuma",
        th: "บานเลื่อนฟุสึมะ",
        my: "ဖူစုမာ တံခါး",
        km: "ទ្វាររអិលហ្វុសុម៉ា",
      },
      furigana: [
        {
          rb: "襖",
          rt: "ふすま",
        },
      ],
      kanjiInfo: [
        {
          char: "襖",
          on: ["オウ"],
          kun: ["ふすま", "あお"],
          strokes: 17,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 776,
      kanji: "附属",
      reading: "ふぞく",
      meanings: {
        ja: "附属",
        en: "being attached; affiliated",
        zh: "附属",
        tw: "附屬",
        ko: "부속",
        vi: "phụ thuộc/đính kèm",
        th: "เป็นส่วนที่แนบ/สังกัด",
        my: "အညီအဖွဲ့",
        km: "ភ្ជាប់/អនុវត្តក្រោម",
      },
      furigana: [
        {
          rb: "附属",
          rt: "ふぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "附",
          on: ["フ"],
          kun: ["つ.ける", "つ.く"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "属",
          on: ["ゾク", "ショク"],
          kun: ["さかん", "つく", "やから"],
          strokes: 12,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 777,
      kanji: "蓋",
      reading: "ふた",
      meanings: {
        ja: "蓋",
        en: "cover; lid",
        zh: "盖子",
        tw: "蓋子",
        ko: "뚜껑",
        vi: "nắp đậy",
        th: "ฝาปิด",
        my: "အဖုံး",
        km: "គំរប",
      },
      furigana: [
        {
          rb: "蓋",
          rt: "ふた",
        },
      ],
      kanjiInfo: [
        {
          char: "蓋",
          on: ["ガイ", "カイ", "コウ"],
          kun: ["ふた", "けだ.し", "おお.う", "かさ", "かこう"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 778,
      kanji: "ぶつぶつ",
      reading: "ぶつぶつ",
      meanings: {
        ja: "ぶつぶつ",
        en: "muttering; grumbling",
        zh: "嘟囔；抱怨",
        tw: "嘟囔；抱怨",
        ko: "중얼중얼; 투덜거림",
        vi: "lầm bầm; cằn nhằn",
        th: "บ่นพึมพำ",
        my: "ပေါင်ပေါင်ပြော",
        km: "បួសបួយ/បក់បាក់",
      },
      furigana: [
        {
          rb: "ぶつぶつ",
          rt: "ぶつぶつ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 779,
      kanji: "船便",
      reading: "ふなびん",
      meanings: {
        ja: "船便",
        en: "surface mail (by ship)",
        zh: "海运邮件",
        tw: "海運郵件",
        ko: "선편 우편",
        vi: "bưu kiện đường biển",
        th: "ไปรษณีย์ทางเรือ",
        my: "ရေကြောင်းစာပို့",
        km: "ប្រៃសណីយ៍តាមនាវា",
      },
      furigana: [
        {
          rb: "船便",
          rt: "ふなびん",
        },
      ],
      kanjiInfo: [
        {
          char: "船",
          on: ["セン"],
          kun: ["ふね", "ふな-"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "便",
          on: ["ベン", "ビン"],
          kun: ["たよ.り"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 780,
      kanji: "部品",
      reading: "ぶひん",
      meanings: {
        ja: "部品",
        en: "parts; components",
        zh: "部件",
        tw: "零件",
        ko: "부품",
        vi: "linh kiện",
        th: "ชิ้นส่วน",
        my: "အစိတ်အပိုင်း",
        km: "គ្រឿងបន្លាស់",
      },
      furigana: [
        {
          rb: "部品",
          rt: "ぶひん",
        },
      ],
      kanjiInfo: [
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 781,
      kanji: "吹雪",
      reading: "ふぶき",
      meanings: {
        ja: "吹雪",
        en: "snow storm; blizzard",
        zh: "暴风雪",
        tw: "暴風雪",
        ko: "눈보라",
        vi: "bão tuyết",
        th: "พายุหิมะ",
        my: "မိုးနှင်းခေါင်",
        km: "ព្យុះഹិម",
      },
      furigana: [
        {
          rb: "吹雪",
          rt: "ふぶき",
        },
      ],
      kanjiInfo: [
        {
          char: "吹",
          on: ["スイ"],
          kun: ["ふ.く"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "雪",
          on: ["セツ"],
          kun: ["ゆき"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 782,
      kanji: "父母",
      reading: "ふぼ",
      meanings: {
        ja: "父母",
        en: "father and mother; parents",
        zh: "父母",
        tw: "父母",
        ko: "부모",
        vi: "cha mẹ",
        th: "บิดามารดา",
        my: "မိဘ",
        km: "ឪពុកម្តាយ",
      },
      furigana: [
        {
          rb: "父母",
          rt: "ふぼ",
        },
      ],
      kanjiInfo: [
        {
          char: "父",
          on: ["フ"],
          kun: ["ちち"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "母",
          on: ["ボ"],
          kun: ["はは", "も"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 783,
      kanji: "踏切",
      reading: "ふみきり",
      meanings: {
        ja: "踏切",
        en: "railway crossing",
        zh: "道口/铁路平交道",
        tw: "平交道",
        ko: "건널목",
        vi: "đường băng qua đường sắt",
        th: "ทางข้ามรถไฟ",
        my: "ရထားဖြတ်လမ်း",
        km: "ចំណុចឆ្លងផ្លូវរថភ្លើង",
      },
      furigana: [
        {
          rb: "踏切",
          rt: "ふみきり",
        },
      ],
      kanjiInfo: [
        {
          char: "踏",
          on: ["トウ"],
          kun: ["ふ.む", "ふ.まえる"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 784,
      kanji: "麓",
      reading: "ふもと",
      meanings: {
        ja: "麓",
        en: "foot (of a mountain/hill)",
        zh: "山脚",
        tw: "山腳",
        ko: "산기슭",
        vi: "chân núi",
        th: "เชิงเขา",
        my: "တောင်ပေါ်ခြေတော်",
        km: "ជើងភ្នំ",
      },
      furigana: [
        {
          rb: "麓",
          rt: "ふもと",
        },
      ],
      kanjiInfo: [
        {
          char: "麓",
          on: ["ロク"],
          kun: ["ふもと"],
          strokes: 19,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 785,
      kanji: "フライパン",
      reading: "フライパン",
      meanings: {
        ja: "フライパン",
        en: "fry pan",
        zh: "煎锅",
        tw: "平底鍋",
        ko: "프라이팬",
        vi: "chảo rán",
        th: "กระทะทอด",
        my: "ဖရိုင်ပန်",
        km: "ខ្ទះ",
      },
      furigana: [
        {
          rb: "フライパン",
          rt: "フライパン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 786,
      kanji: "ブラウス",
      reading: "ブラウス",
      meanings: {
        ja: "ブラウス",
        en: "blouse",
        zh: "女衬衫",
        tw: "女襯衫",
        ko: "블라우스",
        vi: "áo kiểu nữ",
        th: "เสื้อบลาวส์",
        my: "အမျိုးသမီးအင်္ကျီ",
        km: "អាវប្លាវ",
      },
      furigana: [
        {
          rb: "ブラウス",
          rt: "ブラウス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 787,
      kanji: "ブラシ",
      reading: "ブラシ",
      meanings: {
        ja: "ブラシ",
        en: "brush",
        zh: "刷子",
        tw: "刷子",
        ko: "브러시",
        vi: "bàn chải/cọ",
        th: "แปรง/บรัช",
        my: "ဘရပ်ရှ်",
        km: "ជក់/បន្ទះដុស",
      },
      furigana: [
        {
          rb: "ブラシ",
          rt: "ブラシ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 788,
      kanji: "プラットホーム",
      reading: "プラットホーム",
      meanings: {
        ja: "プラットホーム",
        en: "platform (railway)",
        zh: "站台",
        tw: "月台",
        ko: "플랫폼(승강장)",
        vi: "sân ga",
        th: "ชานชาลา",
        my: "ဘူတာခုံ",
        km: "ជាន់រថភ្លើង",
      },
      furigana: [
        {
          rb: "プラットホーム",
          rt: "プラットホーム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 789,
      kanji: "振り仮名",
      reading: "ふりがな",
      meanings: {
        ja: "振り仮名",
        en: "furigana",
        zh: "假名注音",
        tw: "假名註音",
        ko: "후리가나(발음표기)",
        vi: "chú kana (furigana)",
        th: "ฟุริกานะ",
        my: "ဖူရီဂနာ",
        km: "ហ៊ុរិកាណា",
      },
      furigana: [
        {
          rb: "振り仮名",
          rt: "ふりがな",
        },
      ],
      kanjiInfo: [
        {
          char: "振",
          on: ["シン"],
          kun: ["ふ.る", "ふ.れる", "ふ.るう"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "仮",
          on: ["カ", "ケ"],
          kun: ["かり", "かり-"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 790,
      kanji: "プリント",
      reading: "プリント",
      meanings: {
        ja: "プリント",
        en: "print; handout",
        zh: "打印；講義",
        tw: "講義/影印",
        ko: "프린트물",
        vi: "bản in/tài liệu phát",
        th: "เอกสารพิมพ์",
        my: "ပရင့်စာရွက်",
        km: "បោះពុម្ព/ឯកសារចែក",
      },
      furigana: [
        {
          rb: "プリント",
          rt: "プリント",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 791,
      kanji: "故郷",
      reading: "ふるさと",
      meanings: {
        ja: "故郷",
        en: "hometown",
        zh: "故乡",
        tw: "故鄉",
        ko: "고향",
        vi: "quê hương",
        th: "บ้านเกิด",
        my: "မွေးရပ်မြေ",
        km: "ស្រុកកំណើត",
      },
      furigana: [
        {
          rb: "故郷",
          rt: "ふるさと",
        },
      ],
      kanjiInfo: [
        {
          char: "故",
          on: ["コ"],
          kun: ["ゆえ", "ふる.い", "もと"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "郷",
          on: ["キョウ", "ゴウ"],
          kun: ["さと"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 792,
      kanji: "古里",
      reading: "ふるさと",
      meanings: {
        ja: "古里",
        en: "hometown",
        zh: "故里",
        tw: "故里",
        ko: "고향",
        vi: "quê nhà",
        th: "บ้านเกิดเมืองนอน",
        my: "ဇာတိမြေ",
        km: "ស្រុកដើម",
      },
      furigana: [
        {
          rb: "古里",
          rt: "ふるさと",
        },
      ],
      kanjiInfo: [
        {
          char: "古",
          on: ["コ"],
          kun: ["ふる.い", "ふる-", "-ふる.す"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "里",
          on: ["リ"],
          kun: ["さと"],
          strokes: 7,
          grade: 2,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 793,
      kanji: "ブローチ",
      reading: "ブローチ",
      meanings: {
        ja: "ブローチ",
        en: "brooch",
        zh: "胸针",
        tw: "胸針",
        ko: "브로치",
        vi: "trâm cài",
        th: "เข็มกลัด",
        my: "ဘရွတ်ချ်",
        km: "គ្រាប់ដេក/ខ្សែពាក់",
      },
      furigana: [
        {
          rb: "ブローチ",
          rt: "ブローチ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 794,
      kanji: "プログラム",
      reading: "プログラム",
      meanings: {
        ja: "プログラム",
        en: "program (of events)",
        zh: "节目单",
        tw: "節目單/流程",
        ko: "프로그램(행사)",
        vi: "chương trình (sự kiện)",
        th: "กำหนดการงาน",
        my: "အစီအစဉ်",
        km: "កម្មវិធី",
      },
      furigana: [
        {
          rb: "プログラム",
          rt: "プログラム",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 795,
      kanji: "風呂敷",
      reading: "ふろしき",
      meanings: {
        ja: "風呂敷",
        en: "furoshiki (wrapping cloth)",
        zh: "包袱布",
        tw: "風呂敷",
        ko: "후로시키",
        vi: "khăn gói furoshiki",
        th: "ผ้าห่อของฟุโระชิกิ",
        my: "ဖုရိုရှိကီး",
        km: "ក្រណាត់រុំ",
      },
      furigana: [
        {
          rb: "風呂敷",
          rt: "ふろしき",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "呂",
          on: ["ロ", "リョ"],
          kun: ["せぼね"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "敷",
          on: ["フ"],
          kun: ["し.く", "-し.き"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 796,
      kanji: "噴火",
      reading: "ふんか",
      meanings: {
        ja: "噴火",
        en: "eruption",
        zh: "喷发",
        tw: "噴發",
        ko: "분화(화산)",
        vi: "phun trào (núi lửa)",
        th: "การปะทุ",
        my: "ပေါက်ကွဲ (မီးတောင်)",
        km: "ផុតភ្លើងភ្នំអាណាព្យុះ",
      },
      furigana: [
        {
          rb: "噴火",
          rt: "ふんか",
        },
      ],
      kanjiInfo: [
        {
          char: "噴",
          on: ["フン"],
          kun: ["ふ.く"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "火",
          on: ["カ"],
          kun: ["ひ", "-び", "ほ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 797,
      kanji: "分解",
      reading: "ぶんかい",
      meanings: {
        ja: "分解",
        en: "disassembly; decomposition",
        zh: "分解",
        tw: "分解",
        ko: "분해",
        vi: "tháo rời/ phân giải",
        th: "แยกส่วน",
        my: "ခွဲထုတ်ခြင်း",
        km: "បំបែក",
      },
      furigana: [
        {
          rb: "分解",
          rt: "ぶんかい",
        },
      ],
      kanjiInfo: [
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "解",
          on: ["カイ", "ゲ"],
          kun: [
            "と.く",
            "と.かす",
            "と.ける",
            "ほど.く",
            "ほぐ.す",
            "わか.る",
            "さと.る",
          ],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 798,
      kanji: "文芸",
      reading: "ぶんげい",
      meanings: {
        ja: "文芸",
        en: "literature (belles-lettres)",
        zh: "文艺",
        tw: "文藝",
        ko: "문예",
        vi: "văn nghệ/văn chương",
        th: "วรรณศิลป์",
        my: "စာပေနှင့်အနုပညာ",
        km: "វង្សនាការ",
      },
      furigana: [
        {
          rb: "文芸",
          rt: "ぶんげい",
        },
      ],
      kanjiInfo: [
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "芸",
          on: ["ゲイ", "ウン"],
          kun: ["う.える", "のり", "わざ"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 799,
      kanji: "文献",
      reading: "ぶんけん",
      meanings: {
        ja: "文献",
        en: "literature; references",
        zh: "文献",
        tw: "文獻",
        ko: "문헌",
        vi: "tài liệu tham khảo",
        th: "เอกสารอ้างอิง",
        my: "စာတမ်းအရင်းအမြစ်",
        km: "ឯកសារយោង",
      },
      furigana: [
        {
          rb: "文献",
          rt: "ぶんけん",
        },
      ],
      kanjiInfo: [
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "献",
          on: ["ケン", "コン"],
          kun: ["たてまつ.る"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 800,
      kanji: "噴水",
      reading: "ふんすい",
      meanings: {
        ja: "噴水",
        en: "water fountain",
        zh: "喷泉",
        tw: "噴泉",
        ko: "분수",
        vi: "đài phun nước",
        th: "น้ำพุ",
        my: "ရေမြှုပ်",
        km: "ទឹកផ្សះ",
      },
      furigana: [
        {
          rb: "噴水",
          rt: "ふんすい",
        },
      ],
      kanjiInfo: [
        {
          char: "噴",
          on: ["フン"],
          kun: ["ふ.く"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
