export const n2part26 = {
  Lesson26: [
    {
      id: 1260,
      kanji: "心得る",
      reading: "こころえる",
      meanings: {
        ja: "心得る",
        en: "to know",
        zh: "懂得",
        tw: "懂得",
        ko: "알다",
        vi: "biết rõ",
        th: "เข้าใจ",
        my: "နားလည်သည်",
        km: "យល់",
      },
      furigana: [
        {
          rb: "心得る",
          rt: "こころえる",
        },
      ],
      kanjiInfo: [
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "得",
          on: ["トク"],
          kun: ["え.る", "う.る"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1261,
      kanji: "腰掛ける",
      reading: "こしかける",
      meanings: {
        ja: "腰掛ける",
        en: "to sit (down)",
        zh: "坐下",
        tw: "坐下",
        ko: "앉다",
        vi: "ngồi xuống",
        th: "นั่งลง",
        my: "ထိုင်သည်",
        km: "អង្គុយ",
      },
      furigana: [
        {
          rb: "腰掛ける",
          rt: "こしかける",
        },
      ],
      kanjiInfo: [
        {
          char: "腰",
          on: ["ヨウ"],
          kun: ["こし"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "掛",
          on: ["カイ", "ケイ"],
          kun: [
            "か.ける",
            "-か.ける",
            "か.け",
            "-か.け",
            "-が.け",
            "か.かる",
            "-か.かる",
            "-が.かる",
            "か.かり",
            "-が.かり",
            "かかり",
            "-がかり",
          ],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1262,
      kanji: "擦る",
      reading: "こする",
      meanings: {
        ja: "擦る",
        en: "to rub",
        zh: "摩擦",
        tw: "摩擦",
        ko: "문지르다",
        vi: "chà sát",
        th: "ถู",
        my: "ဖိသည်",
        km: "ត្រូវស្រាស",
      },
      furigana: [
        {
          rb: "擦る",
          rt: "こする",
        },
      ],
      kanjiInfo: [
        {
          char: "擦",
          on: ["サツ"],
          kun: ["す.る", "す.れる", "-ず.れ", "こす.る", "こす.れる"],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1263,
      kanji: "言付ける",
      reading: "ことづける",
      meanings: {
        ja: "言付ける",
        en: "to have someone send (a message)",
        zh: "托人带口信",
        tw: "託人帶口信",
        ko: "전언을 부탁하다",
        vi: "nhờ nhắn",
        th: "ฝากบอก",
        my: "မက်ဆေ့ပို့ရန်ပေးသည်",
        km: "ផ្ញើសារតាម",
      },
      furigana: [
        {
          rb: "言付ける",
          rt: "ことづける",
        },
      ],
      kanjiInfo: [
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1264,
      kanji: "堪える",
      reading: "こらえる",
      meanings: {
        ja: "堪える",
        en: "to bear",
        zh: "忍受",
        tw: "忍受",
        ko: "참다",
        vi: "chịu đựng",
        th: "อดทน",
        my: "ခံနိုင်သည်",
        km: "អត់ធ្មត់",
      },
      furigana: [
        {
          rb: "堪える",
          rt: "こらえる",
        },
      ],
      kanjiInfo: [
        {
          char: "堪",
          on: ["カン", "タン"],
          kun: ["た.える", "たま.る", "こら.える", "こた.える"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1265,
      kanji: "転がす",
      reading: "ころがす",
      meanings: {
        ja: "転がす",
        en: "to roll (something)",
        zh: "滚动",
        tw: "滾動",
        ko: "굴리다",
        vi: "lăn (cái gì đó)",
        th: "กลิ้ง",
        my: "လှဲသည်",
        km: "រុញ",
      },
      furigana: [
        {
          rb: "転がす",
          rt: "ころがす",
        },
      ],
      kanjiInfo: [
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1266,
      kanji: "転がる",
      reading: "ころがる",
      meanings: {
        ja: "転がる",
        en: "to roll",
        zh: "滚动",
        tw: "滾動",
        ko: "구르다",
        vi: "lăn lộn",
        th: "กลิ้ง",
        my: "လှဲသွားသည်",
        km: "រមៀល",
      },
      furigana: [
        {
          rb: "転がる",
          rt: "ころがる",
        },
      ],
      kanjiInfo: [
        {
          char: "転",
          on: ["テン"],
          kun: [
            "ころ.がる",
            "ころ.げる",
            "ころ.がす",
            "ころ.ぶ",
            "まろ.ぶ",
            "うたた",
            "うつ.る",
            "くる.めく",
          ],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1267,
      kanji: "捜す",
      reading: "さがす",
      meanings: {
        ja: "捜す",
        en: "to search for",
        zh: "寻找",
        tw: "尋找",
        ko: "찾다",
        vi: "tìm kiếm",
        th: "ค้นหา",
        my: "ရှာဖွေသည်",
        km: "ស្វែងរក",
      },
      furigana: [
        {
          rb: "捜す",
          rt: "さがす",
        },
      ],
      kanjiInfo: [
        {
          char: "捜",
          on: ["ソウ", "シュ", "シュウ"],
          kun: ["さが.す"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1268,
      kanji: "遡る",
      reading: "さかのぼる",
      meanings: {
        ja: "遡る",
        en: "to go upstream; to go back (in time)",
        zh: "溯",
        tw: "溯",
        ko: "거슬러 올라가다",
        vi: "ngược dòng; quay lại",
        th: "ย้อนกลับ",
        my: "နောက်သို့သွားသည်",
        km: "ថយក្រោយ",
      },
      furigana: [
        {
          rb: "遡る",
          rt: "さかのぼる",
        },
      ],
      kanjiInfo: [
        {
          char: "遡",
          on: ["ソ", "サク"],
          kun: ["さかのぼ.る"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1269,
      kanji: "探る",
      reading: "さぐる",
      meanings: {
        ja: "探る",
        en: "to feel around for",
        zh: "探查",
        tw: "探查",
        ko: "탐색하다",
        vi: "thăm dò",
        th: "สำรวจ",
        my: "လက်ဖြင့်摸သည်",
        km: "ស៊ើបអង្កេត",
      },
      furigana: [
        {
          rb: "探る",
          rt: "さぐる",
        },
      ],
      kanjiInfo: [
        {
          char: "探",
          on: ["タン"],
          kun: ["さぐ.る", "さが.す"],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1270,
      kanji: "囁く",
      reading: "ささやく",
      meanings: {
        ja: "囁く",
        en: "to whisper",
        zh: "耳语",
        tw: "耳語",
        ko: "속삭이다",
        vi: "thì thầm",
        th: "กระซิบ",
        my: "ချဲ့စကားပြောသည်",
        km: "ញញឹម",
      },
      furigana: [
        {
          rb: "囁く",
          rt: "ささやく",
        },
      ],
      kanjiInfo: [
        {
          char: "囁",
          on: ["ショウ"],
          kun: ["ささや.く"],
          strokes: 21,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1271,
      kanji: "錆びる",
      reading: "さびる",
      meanings: {
        ja: "錆びる",
        en: "to rust",
        zh: "生锈",
        tw: "生鏽",
        ko: "녹슬다",
        vi: "gỉ sét",
        th: "ขึ้นสนิม",
        my: "သံကျင်သည်",
        km: "ច្រេះ",
      },
      furigana: [
        {
          rb: "錆びる",
          rt: "さびる",
        },
      ],
      kanjiInfo: [
        {
          char: "錆",
          on: ["ショウ", "セイ"],
          kun: ["さび", "くわ.しい"],
          strokes: 16,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1272,
      kanji: "妨げる",
      reading: "さまたげる",
      meanings: {
        ja: "妨げる",
        en: "to disturb",
        zh: "妨碍",
        tw: "妨礙",
        ko: "방해하다",
        vi: "cản trở",
        th: "กีดขวาง",
        my: "နှောင့်ယှက်သည်",
        km: "រារាំង",
      },
      furigana: [
        {
          rb: "妨げる",
          rt: "さまたげる",
        },
      ],
      kanjiInfo: [
        {
          char: "妨",
          on: ["ボウ"],
          kun: ["さまた.げる"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1273,
      kanji: "仕上がる",
      reading: "しあがる",
      meanings: {
        ja: "仕上がる",
        en: "to be finished",
        zh: "完成",
        tw: "完成",
        ko: "완성되다",
        vi: "hoàn thành",
        th: "เสร็จสิ้น",
        my: "ပြီးစီးသည်",
        km: "បញ្ចប់",
      },
      furigana: [
        {
          rb: "仕上がる",
          rt: "しあがる",
        },
      ],
      kanjiInfo: [
        {
          char: "仕",
          on: ["シ", "ジ"],
          kun: ["つか.える"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1274,
      kanji: "敷く",
      reading: "しく",
      meanings: {
        ja: "敷く",
        en: "to spread out",
        zh: "铺",
        tw: "鋪",
        ko: "깔다",
        vi: "trải ra",
        th: "ปู",
        my: "ခင်းသည်",
        km: "បំពាក់",
      },
      furigana: [
        {
          rb: "敷く",
          rt: "しく",
        },
      ],
      kanjiInfo: [
        {
          char: "敷",
          on: ["フ"],
          kun: ["し.く", "-し.き"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1275,
      kanji: "茂る",
      reading: "しげる",
      meanings: {
        ja: "茂る",
        en: "to grow thickly",
        zh: "茂盛",
        tw: "茂盛",
        ko: "무성하다",
        vi: "mọc um tùm",
        th: "เติบโตหนาแน่น",
        my: "ထူထပ်သည်",
        km: "ដុះឡើងច្រើន",
      },
      furigana: [
        {
          rb: "茂る",
          rt: "しげる",
        },
      ],
      kanjiInfo: [
        {
          char: "茂",
          on: ["モ"],
          kun: ["しげ.る"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1276,
      kanji: "静まる",
      reading: "しずまる",
      meanings: {
        ja: "静まる",
        en: "to become quiet",
        zh: "平静",
        tw: "平靜",
        ko: "조용해지다",
        vi: "lắng xuống",
        th: "สงบลง",
        my: "ငြိမ်သက်သည်",
        km: "ស្ងប់ស្ងាត់",
      },
      furigana: [
        {
          rb: "静まる",
          rt: "しずまる",
        },
      ],
      kanjiInfo: [
        {
          char: "静",
          on: ["セイ", "ジョウ"],
          kun: ["しず-", "しず.か", "しず.まる", "しず.める"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1277,
      kanji: "縛る",
      reading: "しばる",
      meanings: {
        ja: "縛る",
        en: "to tie",
        zh: "绑",
        tw: "綁",
        ko: "묶다",
        vi: "trói buộc",
        th: "มัด",
        my: "ချည်သည်",
        km: "ចង",
      },
      furigana: [
        {
          rb: "縛る",
          rt: "しばる",
        },
      ],
      kanjiInfo: [
        {
          char: "縛",
          on: ["バク"],
          kun: ["しば.る"],
          strokes: 16,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1278,
      kanji: "絞る",
      reading: "しぼる",
      meanings: {
        ja: "絞る",
        en: "to wring",
        zh: "拧",
        tw: "擰",
        ko: "짜다",
        vi: "vắt",
        th: "บีบคั้น",
        my: "ဖိသည်",
        km: "ក្រឡុក",
      },
      furigana: [
        {
          rb: "絞る",
          rt: "しぼる",
        },
      ],
      kanjiInfo: [
        {
          char: "絞",
          on: ["コウ"],
          kun: ["しぼ.る", "し.める", "し.まる"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1279,
      kanji: "締め切る",
      reading: "しめきる",
      meanings: {
        ja: "締め切る",
        en: "to close up",
        zh: "截止",
        tw: "截止",
        ko: "마감하다",
        vi: "hạn chót",
        th: "ปิดรับ",
        my: "အဆုံးသတ်သည်",
        km: "បិទបញ្ចប់",
      },
      furigana: [
        {
          rb: "締め切る",
          rt: "しめきる",
        },
      ],
      kanjiInfo: [
        {
          char: "締",
          on: ["テイ"],
          kun: ["し.まる", "し.まり", "し.める", "-し.め", "-じ.め"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1280,
      kanji: "しゃがむ",
      reading: "しゃがむ",
      meanings: {
        ja: "しゃがむ",
        en: "to squat",
        zh: "蹲下",
        tw: "蹲下",
        ko: "쭈그리고 앉다",
        vi: "ngồi xổm",
        th: "นั่งยอง",
        my: "ထိုင်နိမ့်",
        km: "អង្គុយទាប",
      },
      furigana: [
        {
          rb: "しゃがむ",
          rt: "しゃがむ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1281,
      kanji: "しゃぶる",
      reading: "しゃぶる",
      meanings: {
        ja: "しゃぶる",
        en: "to suck",
        zh: "吮吸",
        tw: "吮吸",
        ko: "빨다",
        vi: "mút",
        th: "ดูด",
        my: "စုပ်သည်",
        km: "បំពង់",
      },
      furigana: [
        {
          rb: "しゃぶる",
          rt: "しゃぶる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1282,
      kanji: "略す",
      reading: "りゃくす",
      meanings: {
        ja: "略す",
        en: "to abbreviate",
        zh: "省略",
        tw: "省略",
        ko: "생략하다",
        vi: "lược bỏ",
        th: "ย่อ",
        my: "အကျဉ်းချုပ်သည်",
        km: "កាត់ឃាត់",
      },
      furigana: [
        {
          rb: "略す",
          rt: "りゃくす",
        },
      ],
      kanjiInfo: [
        {
          char: "略",
          on: ["リャク"],
          kun: [
            "ほぼ",
            "はぶ.く",
            "おか.す",
            "おさ.める",
            "はかりごと",
            "はか.る",
          ],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1283,
      kanji: "論ずる",
      reading: "ろんずる",
      meanings: {
        ja: "論ずる",
        en: "to discuss",
        zh: "讨论",
        tw: "討論",
        ko: "논하다",
        vi: "thảo luận",
        th: "อภิปราย",
        my: "ဆွေးနွေးသည်",
        km: "ពិភាក្សា",
      },
      furigana: [
        {
          rb: "論ずる",
          rt: "ろんずる",
        },
      ],
      kanjiInfo: [
        {
          char: "論",
          on: ["ロン"],
          kun: ["あげつら.う"],
          strokes: 15,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1284,
      kanji: "詫びる",
      reading: "わびる",
      meanings: {
        ja: "詫びる",
        en: "to apologize",
        zh: "道歉",
        tw: "道歉",
        ko: "사과하다",
        vi: "xin lỗi",
        th: "ขอโทษ",
        my: "တောင်းပန်သည်",
        km: "អភ័យទោស",
      },
      furigana: [
        {
          rb: "詫びる",
          rt: "わびる",
        },
      ],
      kanjiInfo: [
        {
          char: "詫",
          on: ["タ"],
          kun: ["わび", "わび.しい", "かこつ", "わ.びる", "わび.る"],
          strokes: 13,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1285,
      kanji: "扇ぐ",
      reading: "あおぐ",
      meanings: {
        ja: "扇ぐ",
        en: "to fan",
        zh: "扇风",
        tw: "扇風",
        ko: "부채질하다",
        vi: "quạt",
        th: "พัด",
        my: "လေနဲ့လိမ်းသည်",
        km: "កាព្យ",
      },
      furigana: [
        {
          rb: "扇ぐ",
          rt: "あおぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "扇",
          on: ["セン"],
          kun: ["おうぎ"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1286,
      kanji: "呆れる",
      reading: "あきれる",
      meanings: {
        ja: "呆れる",
        en: "to be amazed",
        zh: "惊呆",
        tw: "驚呆",
        ko: "어이없다",
        vi: "ngạc nhiên",
        th: "ตะลึง",
        my: "အံ့ဩသည်",
        km: "ភ្ញាក់ផ្អើល",
      },
      furigana: [
        {
          rb: "呆れる",
          rt: "あきれる",
        },
      ],
      kanjiInfo: [
        {
          char: "呆",
          on: ["ホウ"],
          kun: ["ほけ.る", "ぼ.ける", "あき.れる", "おろか"],
          strokes: 7,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1287,
      kanji: "憧れる",
      reading: "あこがれる",
      meanings: {
        ja: "憧れる",
        en: "to long for",
        zh: "憧憬",
        tw: "憧憬",
        ko: "동경하다",
        vi: "ngưỡng mộ",
        th: "ใฝ่ฝัน",
        my: "အိပ်မက်မက်သည်",
        km: "ចង់បាន",
      },
      furigana: [
        {
          rb: "憧れる",
          rt: "あこがれる",
        },
      ],
      kanjiInfo: [
        {
          char: "憧",
          on: ["ショウ", "トウ", "ドウ"],
          kun: ["あこが.れる"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1288,
      kanji: "味わう",
      reading: "あじわう",
      meanings: {
        ja: "味わう",
        en: "to taste",
        zh: "品味",
        tw: "品味",
        ko: "맛보다",
        vi: "nếm",
        th: "ลิ้มรส",
        my: "အရသာခံစားသည်",
        km: "រសជាតិ",
      },
      furigana: [
        {
          rb: "味わう",
          rt: "あじわう",
        },
      ],
      kanjiInfo: [
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1289,
      kanji: "当てはまる",
      reading: "あてはまる",
      meanings: {
        ja: "当てはまる",
        en: "to apply (of a rule)",
        zh: "适用",
        tw: "適用",
        ko: "들어맞다",
        vi: "áp dụng (phù hợp)",
        th: "ใช้ได้",
        my: "သင့်လျော်သည်",
        km: "អនុវត្ត",
      },
      furigana: [
        {
          rb: "当てはまる",
          rt: "あてはまる",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1290,
      kanji: "当てはめる",
      reading: "あてはめる",
      meanings: {
        ja: "当てはめる",
        en: "to apply",
        zh: "应用",
        tw: "應用",
        ko: "적용하다",
        vi: "áp dụng",
        th: "ประยุกต์ใช้",
        my: "အသုံးချသည်",
        km: "អនុវត្ត",
      },
      furigana: [
        {
          rb: "当てはめる",
          rt: "あてはめる",
        },
      ],
      kanjiInfo: [
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1291,
      kanji: "暴れる",
      reading: "あばれる",
      meanings: {
        ja: "暴れる",
        en: "to act violently",
        zh: "胡闹",
        tw: "胡鬧",
        ko: "날뛰다",
        vi: "hung hăng",
        th: "อาละวาด",
        my: "အကြမ်းဖက်ပြုသည်",
        km: "ឈ្លានពាន",
      },
      furigana: [
        {
          rb: "暴れる",
          rt: "あばれる",
        },
      ],
      kanjiInfo: [
        {
          char: "暴",
          on: ["ボウ", "バク"],
          kun: ["あば.く", "あば.れる"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1292,
      kanji: "甘やかす",
      reading: "あまやかす",
      meanings: {
        ja: "甘やかす",
        en: "to pamper",
        zh: "娇纵",
        tw: "嬌縱",
        ko: "응석부리게 하다",
        vi: "nuông chiều",
        th: "ตามใจ",
        my: "အလွဲမခံသည်",
        km: "លើកទឹកចិត្ត",
      },
      furigana: [
        {
          rb: "甘やかす",
          rt: "あまやかす",
        },
      ],
      kanjiInfo: [
        {
          char: "甘",
          on: ["カン"],
          kun: ["あま.い", "あま.える", "あま.やかす", "うま.い"],
          strokes: 5,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1293,
      kanji: "余る",
      reading: "あまる",
      meanings: {
        ja: "余る",
        en: "to remain",
        zh: "剩余",
        tw: "剩餘",
        ko: "남다",
        vi: "còn lại",
        th: "เหลืออยู่",
        my: "ကျန်သည်",
        km: "នៅសល់",
      },
      furigana: [
        {
          rb: "余る",
          rt: "あまる",
        },
      ],
      kanjiInfo: [
        {
          char: "余",
          on: ["ヨ"],
          kun: ["あま.る", "あま.り", "あま.す", "あんま.り"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1294,
      kanji: "編む",
      reading: "あむ",
      meanings: {
        ja: "編む",
        en: "to knit",
        zh: "编织",
        tw: "編織",
        ko: "뜨개질하다",
        vi: "đan",
        th: "ถัก",
        my: "နက်သည်",
        km: "ទាត់",
      },
      furigana: [
        {
          rb: "編む",
          rt: "あむ",
        },
      ],
      kanjiInfo: [
        {
          char: "編",
          on: ["ヘン"],
          kun: ["あ.む", "-あ.み"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1295,
      kanji: "改める",
      reading: "あらためる",
      meanings: {
        ja: "改める",
        en: "to change",
        zh: "改变",
        tw: "改變",
        ko: "고치다",
        vi: "thay đổi",
        th: "เปลี่ยนแปลง",
        my: "ပြောင်းလဲသည်",
        km: "ផ្លាស់ប្ដូរ",
      },
      furigana: [
        {
          rb: "改める",
          rt: "あらためる",
        },
      ],
      kanjiInfo: [
        {
          char: "改",
          on: ["カイ"],
          kun: ["あらた.める", "あらた.まる"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1296,
      kanji: "荒れる",
      reading: "あれる",
      meanings: {
        ja: "荒れる",
        en: "to become stormy",
        zh: "荒芜",
        tw: "荒蕪",
        ko: "거칠어지다",
        vi: "hoang vu; nổi bão",
        th: "แปรปรวน",
        my: "မတည်ငြိမ်",
        km: "រញ្ជួយ",
      },
      furigana: [
        {
          rb: "荒れる",
          rt: "あれる",
        },
      ],
      kanjiInfo: [
        {
          char: "荒",
          on: ["コウ"],
          kun: [
            "あ.らす",
            "あ.れる",
            "あら.い",
            "すさ.ぶ",
            "すさ.む",
            "あ.らし",
          ],
          strokes: 9,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1297,
      kanji: "言い出す",
      reading: "いいだす",
      meanings: {
        ja: "言い出す",
        en: "to begin to say",
        zh: "说出口",
        tw: "說出口",
        ko: "말하기 시작하다",
        vi: "bắt đầu nói",
        th: "เริ่มพูด",
        my: "စကားပြောစ",
        km: "ចាប់ផ្តើមនិយាយ",
      },
      furigana: [
        {
          rb: "言い出す",
          rt: "いいだす",
        },
      ],
      kanjiInfo: [
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1298,
      kanji: "言い付ける",
      reading: "いいつける",
      meanings: {
        ja: "言い付ける",
        en: "to tell (to do)",
        zh: "吩咐",
        tw: "吩咐",
        ko: "지시하다",
        vi: "ra lệnh",
        th: "สั่ง",
        my: "အမိန့်ပေးသည်",
        km: "បញ្ជា",
      },
      furigana: [
        {
          rb: "言い付ける",
          rt: "いいつける",
        },
      ],
      kanjiInfo: [
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1299,
      kanji: "一定",
      reading: "いってい",
      meanings: {
        ja: "一定",
        en: "to fix; to set",
        zh: "规定",
        tw: "規定",
        ko: "정하다",
        vi: "ấn định",
        th: "กำหนด",
        my: "သတ်မှတ်သည်",
        km: "កំណត់",
      },
      furigana: [
        {
          rb: "一定",
          rt: "いってい",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1300,
      kanji: "威張る",
      reading: "いばる",
      meanings: {
        ja: "威張る",
        en: "to put on airs",
        zh: "自大",
        tw: "自大",
        ko: "거만하다",
        vi: "vênh váo",
        th: "หยิ่งผยอง",
        my: "အကျင့်ဆိုးကြီးသည်",
        km: "អួត",
      },
      furigana: [
        {
          rb: "威張る",
          rt: "いばる",
        },
      ],
      kanjiInfo: [
        {
          char: "威",
          on: ["イ"],
          kun: ["おど.す", "おど.し", "おど.かす"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "張",
          on: ["チョウ"],
          kun: ["は.る", "-は.り", "-ば.り"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1301,
      kanji: "嫌がる",
      reading: "いやがる",
      meanings: {
        ja: "嫌がる",
        en: "to appear uncomfortable (with)",
        zh: "讨厌",
        tw: "討厭",
        ko: "싫어하다",
        vi: "ghét",
        th: "ไม่ชอบ",
        my: "မကြိုက်",
        km: "ស្អប់",
      },
      furigana: [
        {
          rb: "嫌がる",
          rt: "いやがる",
        },
      ],
      kanjiInfo: [
        {
          char: "嫌",
          on: ["ケン", "ゲン"],
          kun: ["きら.う", "きら.い", "いや"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1302,
      kanji: "煎る",
      reading: "いる",
      meanings: {
        ja: "煎る",
        en: "to roast",
        zh: "炒",
        tw: "炒",
        ko: "볶다",
        vi: "rang",
        th: "คั่ว",
        my: "ကြော်သည်",
        km: "ចៀន",
      },
      furigana: [
        {
          rb: "煎る",
          rt: "いる",
        },
      ],
      kanjiInfo: [
        {
          char: "煎",
          on: ["セン"],
          kun: ["せん.じる", "い.る", "に.る"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1303,
      kanji: "炒る",
      reading: "いる",
      meanings: {
        ja: "炒る",
        en: "to roast",
        zh: "炒",
        tw: "炒",
        ko: "볶다",
        vi: "rang",
        th: "คั่ว",
        my: "ကြော်သည်",
        km: "ចៀន",
      },
      furigana: [
        {
          rb: "炒る",
          rt: "いる",
        },
      ],
      kanjiInfo: [
        {
          char: "炒",
          on: ["ソウ", "ショウ"],
          kun: ["い.る", "いた.める"],
          strokes: 8,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1304,
      kanji: "飢える",
      reading: "うえる",
      meanings: {
        ja: "飢える",
        en: "to starve",
        zh: "饥饿",
        tw: "飢餓",
        ko: "굶주리다",
        vi: "đói khát",
        th: "หิวโหย",
        my: "ဆာလောင်",
        km: "ឃ្លាន",
      },
      furigana: [
        {
          rb: "飢える",
          rt: "うえる",
        },
      ],
      kanjiInfo: [
        {
          char: "飢",
          on: ["キ"],
          kun: ["う.える"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1305,
      kanji: "浮ぶ",
      reading: "うかぶ",
      meanings: {
        ja: "浮ぶ",
        en: "to float",
        zh: "漂浮",
        tw: "漂浮",
        ko: "떠오르다",
        vi: "nổi",
        th: "ลอยขึ้น",
        my: "ရေနှင့်ပေါ်သည်",
        km: "អណ្ដែត",
      },
      furigana: [
        {
          rb: "浮ぶ",
          rt: "うかぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "浮",
          on: ["フ"],
          kun: ["う.く", "う.かれる", "う.かぶ", "う.かべる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1306,
      kanji: "浮かべる",
      reading: "うかべる",
      meanings: {
        ja: "浮かべる",
        en: "to float",
        zh: "浮起",
        tw: "浮起",
        ko: "떠올리다",
        vi: "làm nổi",
        th: "ทำให้ลอย",
        my: "တက်ပေါ်စေသည်",
        km: "អណ្ដែតឡើង",
      },
      furigana: [
        {
          rb: "浮かべる",
          rt: "うかべる",
        },
      ],
      kanjiInfo: [
        {
          char: "浮",
          on: ["フ"],
          kun: ["う.く", "う.かれる", "う.かぶ", "う.かべる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1307,
      kanji: "浮く",
      reading: "うく",
      meanings: {
        ja: "浮く",
        en: "to float",
        zh: "浮动",
        tw: "浮動",
        ko: "뜨다",
        vi: "nổi",
        th: "ลอย",
        my: "ပေါ်သည်",
        km: "អណ្ដែត",
      },
      furigana: [
        {
          rb: "浮く",
          rt: "うく",
        },
      ],
      kanjiInfo: [
        {
          char: "浮",
          on: ["フ"],
          kun: ["う.く", "う.かれる", "う.かぶ", "う.かべる"],
          strokes: 10,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1308,
      kanji: "承る",
      reading: "うけたまわる",
      meanings: {
        ja: "承る",
        en: "to hear (humble)",
        zh: "听取",
        tw: "聽取",
        ko: "삼가 듣다",
        vi: "nghe (khiêm nhường)",
        th: "ฟัง (สุภาพ)",
        my: "နိမ့်ချမှုနဲ့နားထောင်သည်",
        km: "ស្តាប់",
      },
      furigana: [
        {
          rb: "承る",
          rt: "うけたまわる",
        },
      ],
      kanjiInfo: [
        {
          char: "承",
          on: ["ショウ", "ジョウ"],
          kun: ["うけたまわ.る", "う.ける"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1309,
      kanji: "受け持つ",
      reading: "うけもつ",
      meanings: {
        ja: "受け持つ",
        en: "to take charge of",
        zh: "负责",
        tw: "負責",
        ko: "맡다",
        vi: "phụ trách",
        th: "รับผิดชอบ",
        my: "တာဝန်ယူသည်",
        km: "ទទួលខុសត្រូវ",
      },
      furigana: [
        {
          rb: "受け持つ",
          rt: "うけもつ",
        },
      ],
      kanjiInfo: [
        {
          char: "受",
          on: ["ジュ"],
          kun: ["う.ける", "-う.け", "う.かる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "持",
          on: ["ジ"],
          kun: ["も.つ", "-も.ち", "も.てる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
