export const n2part1 = {
  Lesson1: [
    {
      id: 1,
      kanji: "就任",
      reading: "しゅうにん",
      meanings: {
        ja: "就任",
        en: "assumption of office; inauguration",
        zh: "就任",
        tw: "就任",
        ko: "취임",
        vi: "nhậm chức",
        th: "เข้ารับตำแหน่ง",
        my: "ရာထူးထမ်းဆောင်ခြင်း",
        km: "ចូលកាន់តំណែង",
      },
      furigana: [
        {
          rb: "就任",
          rt: "しゅうにん",
        },
      ],
      kanjiInfo: [
        {
          char: "就",
          on: ["シュウ", "ジュ"],
          kun: ["つ.く", "つ.ける"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "任",
          on: ["ニン"],
          kun: ["まか.せる", "まか.す"],
          strokes: 6,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 2,
      kanji: "周辺",
      reading: "しゅうへん",
      meanings: {
        ja: "周辺",
        en: "periphery; surrounding area; circumference",
        zh: "周边; 周围",
        tw: "周邊; 四周",
        ko: "주변; 둘레",
        vi: "vùng lân cận; chu vi",
        th: "บริเวณรอบๆ",
        my: "ပတ်ဝန်းကျင်",
        km: "បរិវេណ; ជុំវិញ",
      },
      furigana: [
        {
          rb: "周辺",
          rt: "しゅうへん",
        },
      ],
      kanjiInfo: [
        {
          char: "周",
          on: ["シュウ"],
          kun: ["まわ.り"],
          strokes: 8,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "辺",
          on: ["ヘン"],
          kun: ["あた.り", "ほと.り", "-べ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 3,
      kanji: "重役",
      reading: "じゅうやく",
      meanings: {
        ja: "重役",
        en: "(company) director; executive",
        zh: "董事; 高层主管",
        tw: "董事; 高層主管",
        ko: "임원; 중역",
        vi: "giám đốc; lãnh đạo",
        th: "ผู้บริหารระดับสูง",
        my: "အုပ်ချူပ်အရာရှိ",
        km: "អ្នកគ្រប់គ្រងកំពូល",
      },
      furigana: [
        {
          rb: "重役",
          rt: "じゅうやく",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "役",
          on: ["ヤク", "エキ"],
          kun: [],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 4,
      kanji: "終了",
      reading: "しゅうりょう",
      meanings: {
        ja: "終了",
        en: "end; completion",
        zh: "结束",
        tw: "結束",
        ko: "종료",
        vi: "kết thúc",
        th: "สิ้นสุด",
        my: "အဆုံးသတ်",
        km: "បញ្ចប់",
      },
      furigana: [
        {
          rb: "終了",
          rt: "しゅうりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "終",
          on: ["シュウ"],
          kun: ["お.わる", "-お.わる", "おわ.る", "お.える", "つい", "つい.に"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "了",
          on: ["リョウ"],
          kun: [],
          strokes: 2,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 5,
      kanji: "重量",
      reading: "じゅうりょう",
      meanings: {
        ja: "重量",
        en: "weight (heaviness)",
        zh: "重量",
        tw: "重量",
        ko: "중량",
        vi: "trọng lượng",
        th: "น้ำหนัก",
        my: "အလေးချိန်",
        km: "ទំងន់",
      },
      furigana: [
        {
          rb: "重量",
          rt: "じゅうりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "量",
          on: ["リョウ"],
          kun: ["はか.る"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 6,
      kanji: "重力",
      reading: "じゅうりょく",
      meanings: {
        ja: "重力",
        en: "gravity",
        zh: "重力",
        tw: "重力",
        ko: "중력",
        vi: "trọng lực",
        th: "แรงโน้มถ่วง",
        my: "သိLaunchGravity",
        km: "ថាមពលទំនាញ",
      },
      furigana: [
        {
          rb: "重力",
          rt: "じゅうりょく",
        },
      ],
      kanjiInfo: [
        {
          char: "重",
          on: ["ジュウ", "チョウ"],
          kun: [
            "え",
            "おも.い",
            "おも.り",
            "おも.なう",
            "かさ.ねる",
            "かさ.なる",
            "おも",
          ],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "力",
          on: ["リョク", "リキ", "リイ"],
          kun: ["ちから"],
          strokes: 2,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 7,
      kanji: "熟語",
      reading: "じゅくご",
      meanings: {
        ja: "熟語（漢語・慣用句）",
        en: "kanji compound; idiom",
        zh: "熟语; 汉字复合词",
        tw: "熟語; 漢字複合詞",
        ko: "숙어; 한자합성어",
        vi: "thành ngữ; từ ghép Hán",
        th: "สำนวน; คำประสมคันจิ",
        my: "စကားပုံ/အကြောင်းဝေါဟာရ",
        km: "សុពលពាក្យ; សព្វនាម",
      },
      furigana: [
        {
          rb: "熟語",
          rt: "じゅくご",
        },
      ],
      kanjiInfo: [
        {
          char: "熟",
          on: ["ジュク"],
          kun: ["う.れる"],
          strokes: 15,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 8,
      kanji: "祝日",
      reading: "しゅくじつ",
      meanings: {
        ja: "祝日",
        en: "national holiday",
        zh: "法定节假日",
        tw: "國定假日",
        ko: "공휴일",
        vi: "ngày nghỉ lễ",
        th: "วันหยุดราชการ",
        my: "အများပြည်သူအားလပ်",
        km: "ថ្ងៃឈប់សម្រាកជាតិ",
      },
      furigana: [
        {
          rb: "祝日",
          rt: "しゅくじつ",
        },
      ],
      kanjiInfo: [
        {
          char: "祝",
          on: ["シュク", "シュウ"],
          kun: ["いわ.う"],
          strokes: 9,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 9,
      kanji: "縮小",
      reading: "しゅくしょう",
      meanings: {
        ja: "縮小",
        en: "reduction; shrinkage",
        zh: "缩小",
        tw: "縮小",
        ko: "축소",
        vi: "thu nhỏ; giảm bớt",
        th: "ย่อขนาด; ลดลง",
        my: "ကျုံ့ခွာမှု",
        km: "បង្រ្កាបទំហំ",
      },
      furigana: [
        {
          rb: "縮小",
          rt: "しゅくしょう",
        },
      ],
      kanjiInfo: [
        {
          char: "縮",
          on: ["シュク"],
          kun: ["ちぢ.む", "ちぢ.まる", "ちぢ.める", "ちぢ.れる", "ちぢ.らす"],
          strokes: 17,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "小",
          on: ["ショウ"],
          kun: ["ちい.さい", "こ-", "お-", "さ-"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 10,
      kanji: "受験",
      reading: "じゅけん",
      meanings: {
        ja: "受験（入試など）",
        en: "taking an exam (esp. entrance)",
        zh: "应试（尤指入学考试）",
        tw: "應試（尤指入學考）",
        ko: "수험; 시험응시",
        vi: "dự thi (đặc biệt thi vào trường)",
        th: "เข้าสอบ (โดยเฉพาะสอบเข้า)",
        my: "စာမေးပွဲဝင်",
        km: "ចូលប្រឡង (ពិសេសប្រឡងចូល)",
      },
      furigana: [
        {
          rb: "受験",
          rt: "じゅけん",
        },
      ],
      kanjiInfo: [
        {
          char: "受",
          on: ["ジュ"],
          kun: ["う.ける", "-う.け", "う.かる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "験",
          on: ["ケン", "ゲン"],
          kun: ["あかし", "しるし", "ため.す", "ためし"],
          strokes: 18,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 11,
      kanji: "主語",
      reading: "しゅご",
      meanings: {
        ja: "主語",
        en: "subject (grammar)",
        zh: "主语",
        tw: "主語",
        ko: "주어",
        vi: "chủ ngữ",
        th: "ประธาน (ไวยากรณ์)",
        my: "ပုစၥာ",
        km: "ប្រធាន",
      },
      furigana: [
        {
          rb: "主語",
          rt: "しゅご",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 12,
      kanji: "主人",
      reading: "しゅじん",
      meanings: {
        ja: "主人（家長・夫）",
        en: "head of household; husband; master",
        zh: "家主; 丈夫; 主人",
        tw: "家主; 丈夫; 主人",
        ko: "가장; 남편; 주인",
        vi: "chủ nhà; chồng; ông chủ",
        th: "หัวหน้าครอบครัว; สามี; เจ้านาย",
        my: "အိမ်ထောင်ရှင်; လင်; ပိုင်ရှင်",
        km: "មេផ្ទះ; ប្ដី; ម្ចាស់",
      },
      furigana: [
        {
          rb: "主人",
          rt: "しゅじん",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 13,
      kanji: "出勤",
      reading: "しゅっきん",
      meanings: {
        ja: "出勤",
        en: "going to work; attendance (at work)",
        zh: "上班",
        tw: "上班",
        ko: "출근",
        vi: "đi làm",
        th: "ไปทำงาน",
        my: "အလုပ်သို့သွား",
        km: "ទៅធ្វើការ",
      },
      furigana: [
        {
          rb: "出勤",
          rt: "しゅっきん",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "勤",
          on: ["キン", "ゴン"],
          kun: ["つと.める", "-づと.め", "つと.まる", "いそ.しむ"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 14,
      kanji: "述語",
      reading: "じゅつご",
      meanings: {
        ja: "述語",
        en: "predicate (grammar)",
        zh: "述语",
        tw: "述語",
        ko: "술어",
        vi: "vị ngữ",
        th: "ภาคแสดง",
        my: "ဝိသေသနပိုင်း",
        km: "វិភាគពាក្យ (술어)",
      },
      furigana: [
        {
          rb: "述語",
          rt: "じゅつご",
        },
      ],
      kanjiInfo: [
        {
          char: "述",
          on: ["ジュツ"],
          kun: ["の.べる"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 15,
      kanji: "出張",
      reading: "しゅっちょう",
      meanings: {
        ja: "出張",
        en: "business trip",
        zh: "出差",
        tw: "出差",
        ko: "출장",
        vi: "đi công tác",
        th: "ไปทำงานต่างถิ่น",
        my: "လုပ်ငန်းခရီး",
        km: "ធ្វើដំណើរការងារ",
      },
      furigana: [
        {
          rb: "出張",
          rt: "しゅっちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "張",
          on: ["チョウ"],
          kun: ["は.る", "-は.り", "-ば.り"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 16,
      kanji: "寿命",
      reading: "じゅみょう",
      meanings: {
        ja: "寿命",
        en: "lifespan; life expectancy",
        zh: "寿命",
        tw: "壽命",
        ko: "수명",
        vi: "tuổi thọ",
        th: "อายุขัย",
        my: "အသက်တာကြာချိန်",
        km: "អាយុកាល",
      },
      furigana: [
        {
          rb: "寿命",
          rt: "じゅみょう",
        },
      ],
      kanjiInfo: [
        {
          char: "寿",
          on: ["ジュ", "ス", "シュウ"],
          kun: ["ことぶき", "ことぶ.く", "ことほ.ぐ"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 17,
      kanji: "主役",
      reading: "しゅやく",
      meanings: {
        ja: "主役",
        en: "leading role",
        zh: "主角",
        tw: "主角",
        ko: "주역; 주연",
        vi: "vai chính",
        th: "บทนำ",
        my: "အဓိကဇာတ်ကောင်",
        km: "តួឯក",
      },
      furigana: [
        {
          rb: "主役",
          rt: "しゅやく",
        },
      ],
      kanjiInfo: [
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "役",
          on: ["ヤク", "エキ"],
          kun: [],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 18,
      kanji: "受話器",
      reading: "じゅわき",
      meanings: {
        ja: "受話器（電話）",
        en: "telephone receiver/handset",
        zh: "(电话) 听筒",
        tw: "（電話）聽筒",
        ko: "수화기",
        vi: "ống nghe điện thoại",
        th: "หูโทรศัพท์",
        my: "တယ်လီဖုန်းလက်ကိုင်",
        km: "ទូរស័ព្ទដៃកាន់ (ស្វាគមន៍)",
      },
      furigana: [
        {
          rb: "受話器",
          rt: "じゅわき",
        },
      ],
      kanjiInfo: [
        {
          char: "受",
          on: ["ジュ"],
          kun: ["う.ける", "-う.け", "う.かる"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 19,
      kanji: "循環",
      reading: "じゅんかん",
      meanings: {
        ja: "循環",
        en: "circulation; cycle",
        zh: "循环",
        tw: "循環",
        ko: "순환",
        vi: "tuần hoàn; vòng tuần hoàn",
        th: "การหมุนเวียน",
        my: "လည်ပတ်မှု",
        km: "វដ្តសរសេរ/សាច់ឈាម",
      },
      furigana: [
        {
          rb: "循環",
          rt: "じゅんかん",
        },
      ],
      kanjiInfo: [
        {
          char: "循",
          on: ["ジュン"],
          kun: [],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "環",
          on: ["カン"],
          kun: ["わ"],
          strokes: 17,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 20,
      kanji: "巡査",
      reading: "じゅんさ",
      meanings: {
        ja: "巡査（警官）",
        en: "police officer (constable)",
        zh: "巡警",
        tw: "巡警",
        ko: "순사; 경찰관",
        vi: "cảnh sát tuần tra",
        th: "ตำรวจ",
        my: "ရဲသား",
        km: "ប៉ូលិស",
      },
      furigana: [
        {
          rb: "巡査",
          rt: "じゅんさ",
        },
      ],
      kanjiInfo: [
        {
          char: "巡",
          on: ["ジュン"],
          kun: ["めぐ.る", "めぐ.り"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "査",
          on: ["サ"],
          kun: [],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 21,
      kanji: "順序",
      reading: "じゅんじょ",
      meanings: {
        ja: "順序",
        en: "order; sequence",
        zh: "顺序",
        tw: "順序",
        ko: "순서",
        vi: "thứ tự",
        th: "ลำดับ",
        my: "အစဉ်",
        km: "លំដាប់",
      },
      furigana: [
        {
          rb: "順序",
          rt: "じゅんじょ",
        },
      ],
      kanjiInfo: [
        {
          char: "順",
          on: ["ジュン"],
          kun: [],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "序",
          on: ["ジョ"],
          kun: ["つい.で", "ついで"],
          strokes: 7,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 22,
      kanji: "純情",
      reading: "じゅんじょう",
      meanings: {
        ja: "純情",
        en: "pure heart; innocence",
        zh: "纯情; 天真",
        tw: "純情; 天真",
        ko: "순정",
        vi: "trong sáng; ngây thơ",
        th: "ใจบริสุทธิ์",
        my: "သန့်ရှင်းသောနှုတ်",
        km: "សុិបធម៌ស្អាត",
      },
      furigana: [
        {
          rb: "純情",
          rt: "じゅんじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "純",
          on: ["ジュン"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 23,
      kanji: "消化",
      reading: "しょうか",
      meanings: {
        ja: "消化（食べ物）",
        en: "digestion (of food)",
        zh: "消化",
        tw: "消化",
        ko: "소화",
        vi: "tiêu hoá",
        th: "การย่อยอาหาร",
        my: "အစာခြေ",
        km: "រំលាយអាហារ",
      },
      furigana: [
        {
          rb: "消化",
          rt: "しょうか",
        },
      ],
      kanjiInfo: [
        {
          char: "消",
          on: ["ショウ"],
          kun: ["き.える", "け.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 24,
      kanji: "小学生",
      reading: "しょうがくせい",
      meanings: {
        ja: "小学生",
        en: "elementary school student",
        zh: "小学生",
        tw: "小學生",
        ko: "초등학생",
        vi: "học sinh tiểu học",
        th: "นักเรียนประถม",
        my: "ပထမတန်းကျောင်းသား",
        km: "សិស្សបឋម",
      },
      furigana: [
        {
          rb: "小学生",
          rt: "しょうがくせい",
        },
      ],
      kanjiInfo: [
        {
          char: "小",
          on: ["ショウ"],
          kun: ["ちい.さい", "こ-", "お-", "さ-"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 25,
      kanji: "将棋",
      reading: "しょうぎ",
      meanings: {
        ja: "将棋",
        en: "shogi (Japanese chess)",
        zh: "将棋",
        tw: "將棋",
        ko: "쇼기",
        vi: "cờ tướng Nhật (shogi)",
        th: "โชกิ (หมากรุกญี่ปุ่น)",
        my: "Shogi ဂိမ်း",
        km: "សូគី (ឈ chess ជប៉ុន)",
      },
      furigana: [
        {
          rb: "将棋",
          rt: "しょうぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "将",
          on: ["ショウ", "ソウ"],
          kun: ["まさ.に", "はた", "まさ", "ひきい.る", "もって"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "棋",
          on: ["キ"],
          kun: ["ご"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 26,
      kanji: "蒸気",
      reading: "じょうき",
      meanings: {
        ja: "蒸気",
        en: "steam; vapor",
        zh: "蒸汽",
        tw: "蒸氣",
        ko: "증기",
        vi: "hơi nước",
        th: "ไอน้ำ",
        my: "အသွန်း",
        km: "ចំហាយ",
      },
      furigana: [
        {
          rb: "蒸気",
          rt: "じょうき",
        },
      ],
      kanjiInfo: [
        {
          char: "蒸",
          on: ["ジョウ", "セイ"],
          kun: ["む.す", "む.れる", "む.らす"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 27,
      kanji: "定規",
      reading: "じょうぎ",
      meanings: {
        ja: "定規",
        en: "(measuring) ruler",
        zh: "尺; 直尺",
        tw: "尺; 直尺",
        ko: "자 (자루)",
        vi: "thước kẻ",
        th: "ไม้บรรทัด",
        my: "尺/အလျားပမာဏ尺",
        km: "បន្ទាត់វាស់",
      },
      furigana: [
        {
          rb: "定規",
          rt: "じょうぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "規",
          on: ["キ"],
          kun: [],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 28,
      kanji: "上級",
      reading: "じょうきゅう",
      meanings: {
        ja: "上級",
        en: "upper/advanced level",
        zh: "高级",
        tw: "高級",
        ko: "상급",
        vi: "trình độ cao",
        th: "ระดับสูง",
        my: "အဆင့်မြင့်ကောက်",
        km: "កម្រិតខ្ពស់",
      },
      furigana: [
        {
          rb: "上級",
          rt: "じょうきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "級",
          on: ["キュウ"],
          kun: [],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 29,
      kanji: "商業",
      reading: "しょうぎょう",
      meanings: {
        ja: "商業",
        en: "commerce; business",
        zh: "商业",
        tw: "商業",
        ko: "상업",
        vi: "thương nghiệp",
        th: "การพาณิชย์",
        my: "အရောင်းအဝယ်လုပ်ငန်း",
        km: "ពាណិជ្ជកម្ម",
      },
      furigana: [
        {
          rb: "商業",
          rt: "しょうぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "商",
          on: ["ショウ"],
          kun: ["あきな.う"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 30,
      kanji: "賞金",
      reading: "しょうきん",
      meanings: {
        ja: "賞金",
        en: "prize money; reward",
        zh: "奖金",
        tw: "獎金",
        ko: "상금",
        vi: "tiền thưởng",
        th: "เงินรางวัล",
        my: "ဆုကြေး",
        km: "ប្រាក់រង្វាន់",
      },
      furigana: [
        {
          rb: "賞金",
          rt: "しょうきん",
        },
      ],
      kanjiInfo: [
        {
          char: "賞",
          on: ["ショウ"],
          kun: ["ほ.める"],
          strokes: 15,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 31,
      kanji: "上下",
      reading: "じょうげ",
      meanings: {
        ja: "上下",
        en: "top and bottom; up and down",
        zh: "上下",
        tw: "上下",
        ko: "상하",
        vi: "trên và dưới",
        th: "บนล่าง",
        my: "အပေါ်အောက်",
        km: "លើក្រោម",
      },
      furigana: [
        {
          rb: "上下",
          rt: "じょうげ",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 32,
      kanji: "障子",
      reading: "しょうじ",
      meanings: {
        ja: "障子（紙戸）",
        en: "shoji (paper sliding door)",
        zh: "纸拉门（障子）",
        tw: "紙拉門（障子）",
        ko: "쇼지 (종이 미닫이문)",
        vi: "cửa trượt giấy (shoji)",
        th: "ประตูกระดาษญี่ปุ่น",
        my: "စာရွက်ပေါင်းတံခါး",
        km: "ទ្វារក្រដាសសូជី",
      },
      furigana: [
        {
          rb: "障子",
          rt: "しょうじ",
        },
      ],
      kanjiInfo: [
        {
          char: "障",
          on: ["ショウ"],
          kun: ["さわ.る"],
          strokes: 14,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 33,
      kanji: "商社",
      reading: "しょうしゃ",
      meanings: {
        ja: "商社",
        en: "trading company",
        zh: "贸易公司",
        tw: "貿易公司",
        ko: "상사",
        vi: "công ty thương mại",
        th: "บริษัทการค้า",
        my: "ကုန်သွယ်ရေးကုမ္ပဏီ",
        km: "ក្រុមហ៊ុនពាណិជ្ជកម្ម",
      },
      furigana: [
        {
          rb: "商社",
          rt: "しょうしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "商",
          on: ["ショウ"],
          kun: ["あきな.う"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "社",
          on: ["シャ"],
          kun: ["やしろ"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 34,
      kanji: "乗車",
      reading: "じょうしゃ",
      meanings: {
        ja: "乗車",
        en: "boarding (a train, bus, etc.)",
        zh: "乘车",
        tw: "乘車",
        ko: "승차",
        vi: "lên xe/tàu",
        th: "ขึ้นรถ/รถไฟ",
        my: "ယာဉ်တက်ခြင်း",
        km: "ឡើងយានយន្ត",
      },
      furigana: [
        {
          rb: "乗車",
          rt: "じょうしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "乗",
          on: ["ジョウ", "ショウ"],
          kun: ["の.る", "-の.り", "の.せる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 35,
      kanji: "上旬",
      reading: "じょうじゅん",
      meanings: {
        ja: "上旬（1日〜10日ごろ）",
        en: "first third of a month (days 1–10)",
        zh: "上旬",
        tw: "上旬",
        ko: "상순",
        vi: "thượng tuần",
        th: "ต้นเดือน (วันที่ 1–10)",
        my: "လအစ (၁–၁၀ရက်)",
        km: "ដើមខែ (១–១០)",
      },
      furigana: [
        {
          rb: "上旬",
          rt: "じょうじゅん",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "旬",
          on: ["ジュン", "シュン"],
          kun: [],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 36,
      kanji: "小数",
      reading: "しょうすう",
      meanings: {
        ja: "小数（分数・少数）",
        en: "decimal; fraction (small number)",
        zh: "小数; 少量",
        tw: "小數; 少量",
        ko: "소수(點); 소수(적은 수)",
        vi: "số thập phân; số ít",
        th: "เลขทศนิยม; จำนวนน้อย",
        my: "ဒဿမ; အနည်းငယ်",
        km: "ទសភាគ; ចំនួនតិច",
      },
      furigana: [
        {
          rb: "小数",
          rt: "しょうすう",
        },
      ],
      kanjiInfo: [
        {
          char: "小",
          on: ["ショウ"],
          kun: ["ちい.さい", "こ-", "お-", "さ-"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 37,
      kanji: "商店",
      reading: "しょうてん",
      meanings: {
        ja: "商店",
        en: "shop; store",
        zh: "商店",
        tw: "商店",
        ko: "상점",
        vi: "cửa hàng",
        th: "ร้านค้า",
        my: "ဆိုင်",
        km: "ហាង",
      },
      furigana: [
        {
          rb: "商店",
          rt: "しょうてん",
        },
      ],
      kanjiInfo: [
        {
          char: "商",
          on: ["ショウ"],
          kun: ["あきな.う"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "店",
          on: ["テン"],
          kun: ["みせ", "たな"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 38,
      kanji: "焦点",
      reading: "しょうてん",
      meanings: {
        ja: "焦点",
        en: "focus; focal point",
        zh: "焦点",
        tw: "焦點",
        ko: "초점",
        vi: "tiêu điểm",
        th: "จุดโฟกัส",
        my: "အလင်းအာရုံစိုက်ချက်",
        km: "ចំណុចផ្តោត",
      },
      furigana: [
        {
          rb: "焦点",
          rt: "しょうてん",
        },
      ],
      kanjiInfo: [
        {
          char: "焦",
          on: ["ショウ"],
          kun: [
            "こ.げる",
            "こ.がす",
            "こ.がれる",
            "あせ.る",
            "じ.れる",
            "じ.らす",
          ],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 39,
      kanji: "消毒",
      reading: "しょうどく",
      meanings: {
        ja: "消毒",
        en: "disinfection; sterilization",
        zh: "消毒",
        tw: "消毒",
        ko: "소독",
        vi: "khử trùng",
        th: "ฆ่าเชื้อ",
        my: "ပိုးသတ်",
        km: "សំអាតមេរោគ",
      },
      furigana: [
        {
          rb: "消毒",
          rt: "しょうどく",
        },
      ],
      kanjiInfo: [
        {
          char: "消",
          on: ["ショウ"],
          kun: ["き.える", "け.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "毒",
          on: ["ドク"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 40,
      kanji: "勝敗",
      reading: "しょうはい",
      meanings: {
        ja: "勝敗",
        en: "victory or defeat; outcome",
        zh: "胜败",
        tw: "勝敗",
        ko: "승패",
        vi: "thắng bại",
        th: "แพ้ชนะ",
        my: "နှင်/ရှုံး",
        km: "ឈ្នះចាញ់",
      },
      furigana: [
        {
          rb: "勝敗",
          rt: "しょうはい",
        },
      ],
      kanjiInfo: [
        {
          char: "勝",
          on: ["ショウ"],
          kun: ["か.つ", "-が.ち", "まさ.る", "すぐ.れる", "かつ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "敗",
          on: ["ハイ"],
          kun: ["やぶ.れる"],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 41,
      kanji: "蒸発",
      reading: "じょうはつ",
      meanings: {
        ja: "蒸発",
        en: "evaporation",
        zh: "蒸发",
        tw: "蒸發",
        ko: "증발",
        vi: "bốc hơi",
        th: "การระเหย",
        my: "အငယ်မြူ",
        km: "ការរលាយទៅឧស្ម័ន",
      },
      furigana: [
        {
          rb: "蒸発",
          rt: "じょうはつ",
        },
      ],
      kanjiInfo: [
        {
          char: "蒸",
          on: ["ジョウ", "セイ"],
          kun: ["む.す", "む.れる", "む.らす"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 42,
      kanji: "勝負",
      reading: "しょうぶ",
      meanings: {
        ja: "勝負",
        en: "match; contest; victory or defeat",
        zh: "胜负; 比赛",
        tw: "勝負; 比賽",
        ko: "승부; 시합",
        vi: "trận đấu; thắng bại",
        th: "การแข่งขัน; แพ้ชนะ",
        my: "ယှဉ်ပြိုင်ပွဲ",
        km: "ការប្រកួត; ឈ្នះចាញ់",
      },
      furigana: [
        {
          rb: "勝負",
          rt: "しょうぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "勝",
          on: ["ショウ"],
          kun: ["か.つ", "-が.ち", "まさ.る", "すぐ.れる", "かつ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "負",
          on: ["フ"],
          kun: ["ま.ける", "ま.かす", "お.う"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 43,
      kanji: "小便",
      reading: "しょうべん",
      meanings: {
        ja: "小便（尿）",
        en: "urine; pee",
        zh: "小便; 尿",
        tw: "小便; 尿",
        ko: "소변",
        vi: "nước tiểu",
        th: "ปัสสาวะ",
        my: "ဆီး",
        km: "ទឹកនោម",
      },
      furigana: [
        {
          rb: "小便",
          rt: "しょうべん",
        },
      ],
      kanjiInfo: [
        {
          char: "小",
          on: ["ショウ"],
          kun: ["ちい.さい", "こ-", "お-", "さ-"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "便",
          on: ["ベン", "ビン"],
          kun: ["たよ.り"],
          strokes: 9,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 44,
      kanji: "消防署",
      reading: "しょうぼうしょ",
      meanings: {
        ja: "消防署",
        en: "fire station",
        zh: "消防局; 消防站",
        tw: "消防局; 消防隊",
        ko: "소방서",
        vi: "trạm cứu hỏa",
        th: "สถานีดับเพลิง",
        my: "မီးသတ်ဌာန",
        km: "ស្ថានីយ៍អគ្គិភ័យ",
      },
      furigana: [
        {
          rb: "消防署",
          rt: "しょうぼうしょ",
        },
      ],
      kanjiInfo: [
        {
          char: "消",
          on: ["ショウ"],
          kun: ["き.える", "け.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "防",
          on: ["ボウ"],
          kun: ["ふせ.ぐ"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "署",
          on: ["ショ"],
          kun: [],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 45,
      kanji: "正面",
      reading: "しょうめん",
      meanings: {
        ja: "正面",
        en: "front; facade",
        zh: "正面",
        tw: "正面",
        ko: "정면",
        vi: "chính diện; mặt trước",
        th: "ด้านหน้า",
        my: "ရှေ့ဘက်",
        km: "ខាងមុខ",
      },
      furigana: [
        {
          rb: "正面",
          rt: "しょうめん",
        },
      ],
      kanjiInfo: [
        {
          char: "正",
          on: ["セイ", "ショウ"],
          kun: ["ただ.しい", "ただ.す", "まさ", "まさ.に"],
          strokes: 5,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 46,
      kanji: "消耗",
      reading: "しょうもう",
      meanings: {
        ja: "消耗",
        en: "exhaustion; consumption (wear and tear)",
        zh: "消耗; 耗损",
        tw: "消耗; 損耗",
        ko: "소모",
        vi: "hao mòn; tiêu hao",
        th: "สึกหรอ; ใช้หมด",
        my: "ကုန်စားမှု",
        km: "ការប្រើប្រាស់ច្រើន; ខូចខាត",
      },
      furigana: [
        {
          rb: "消耗",
          rt: "しょうもう",
        },
      ],
      kanjiInfo: [
        {
          char: "消",
          on: ["ショウ"],
          kun: ["き.える", "け.す"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "耗",
          on: ["モウ", "コウ"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 47,
      kanji: "初級",
      reading: "しょきゅう",
      meanings: {
        ja: "初級",
        en: "elementary level; beginner",
        zh: "初级",
        tw: "初級",
        ko: "초급",
        vi: "sơ cấp",
        th: "ระดับต้น",
        my: "အခြေခံအဆင့်",
        km: "កម្រិតដំបូង",
      },
      furigana: [
        {
          rb: "初級",
          rt: "しょきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "初",
          on: ["ショ"],
          kun: [
            "はじ.め",
            "はじ.めて",
            "はつ",
            "はつ-",
            "うい-",
            "-そ.める",
            "-ぞ.め",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "級",
          on: ["キュウ"],
          kun: [],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 48,
      kanji: "助教授",
      reading: "じょきょうじゅ",
      meanings: {
        ja: "助教授",
        en: "assistant professor (old title; now often 准教授)",
        zh: "副教授（旧称）",
        tw: "助理教授（舊稱）",
        ko: "조교수",
        vi: "phó giáo sư (trợ giảng, cũ)",
        th: "ผู้ช่วยศาสตราจารย์",
        my: "အဆင့် ပါရဂူအကူ",
        km: "បណ្ឌិតបង្គោល (ជួយបង្រៀន)",
      },
      furigana: [
        {
          rb: "助教授",
          rt: "じょきょうじゅ",
        },
      ],
      kanjiInfo: [
        {
          char: "助",
          on: ["ジョ"],
          kun: ["たす.ける", "たす.かる", "す.ける", "すけ"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "教",
          on: ["キョウ"],
          kun: ["おし.える", "おそ.わる"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "授",
          on: ["ジュ"],
          kun: ["さず.ける", "さず.かる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 49,
      kanji: "食塩",
      reading: "しょくえん",
      meanings: {
        ja: "食塩",
        en: "table salt",
        zh: "食盐",
        tw: "食鹽",
        ko: "식염; 소금",
        vi: "muối ăn",
        th: "เกลือปรุงอาหาร",
        my: "စားဖို့အဓာတ်ဆား",
        km: "អំបិលសម្រាប់បរិភោគ",
      },
      furigana: [
        {
          rb: "食塩",
          rt: "しょくえん",
        },
      ],
      kanjiInfo: [
        {
          char: "食",
          on: ["ショク", "ジキ"],
          kun: ["く.う", "く.らう", "た.べる", "は.む"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "塩",
          on: ["エン"],
          kun: ["しお"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 50,
      kanji: "職人",
      reading: "しょくにん",
      meanings: {
        ja: "職人",
        en: "craftsman; artisan",
        zh: "工匠",
        tw: "工匠",
        ko: "장인",
        vi: "thợ thủ công",
        th: "ช่างฝีมือ",
        my: "လက်မှုပညာရှင်",
        km: "ជាង; សិប្បករ",
      },
      furigana: [
        {
          rb: "職人",
          rt: "しょくにん",
        },
      ],
      kanjiInfo: [
        {
          char: "職",
          on: ["ショク", "ソク"],
          kun: [],
          strokes: 18,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
