export const n2part34 = {
  Lesson34: [
    {
      id: 1634,
      kanji: "うなずく",
      reading: "うなずく",
      meanings: {
        ja: "うなずく",
        en: "to nod",
        zh: "点头",
        tw: "點頭",
        ko: "고개를 끄덕이다",
        vi: "gật đầu",
        th: "พยักหน้า",
        my: "ခေါင်းညိတ်",
        km: "頷く",
      },
      furigana: [
        {
          rb: "うなずく",
          rt: "うなずく",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1635,
      kanji: "上～",
      reading: "うわ～",
      meanings: {
        ja: "上～",
        en: "upper ~",
        zh: "上～",
        tw: "上～",
        ko: "상~",
        vi: "trên ~",
        th: "ด้านบน ~",
        my: "အပေါ် ~",
        km: "លើ ~",
      },
      furigana: [
        {
          rb: "上～",
          rt: "うわ～",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1636,
      kanji: "ええと",
      reading: "ええと",
      meanings: {
        ja: "ええと",
        en: "let me see...",
        zh: "那个...",
        tw: "那個...",
        ko: "저기...",
        vi: "à...",
        th: "เอ่อ...",
        my: "အဲ...",
        km: "អ៊ើ...",
      },
      furigana: [
        {
          rb: "ええと",
          rt: "ええと",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1637,
      kanji: "絵の具",
      reading: "えのぐ",
      meanings: {
        ja: "絵の具",
        en: "paint",
        zh: "颜料",
        tw: "顏料",
        ko: "물감",
        vi: "màu vẽ",
        th: "สีน้ำ",
        my: "အရောင်ဆေး",
        km: "ពណ៌គូរ",
      },
      furigana: [
        {
          rb: "絵の具",
          rt: "えのぐ",
        },
      ],
      kanjiInfo: [
        {
          char: "絵",
          on: ["カイ", "エ"],
          kun: [],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "具",
          on: ["グ"],
          kun: ["そな.える", "つぶさ.に"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1638,
      kanji: "～園",
      reading: "～えん",
      meanings: {
        ja: "～園",
        en: "garden; park",
        zh: "～园",
        tw: "～園",
        ko: "~원",
        vi: "vườn ~",
        th: "สวน ~",
        my: "ဥယျာဉ် ~",
        km: "សួន ~",
      },
      furigana: [
        {
          rb: "～園",
          rt: "～えん",
        },
      ],
      kanjiInfo: [
        {
          char: "園",
          on: ["エン"],
          kun: ["その"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1639,
      kanji: "御～",
      reading: "おん～",
      meanings: {
        ja: "御～",
        en: "honorific prefix",
        zh: "御～",
        tw: "御～",
        ko: "어느~",
        vi: "ngự ~",
        th: "御~",
        my: "ဂျု ~",
        km: "御~",
      },
      furigana: [
        {
          rb: "御～",
          rt: "おん～",
        },
      ],
      kanjiInfo: [
        {
          char: "御",
          on: ["ギョ", "ゴ"],
          kun: ["おん-", "お-", "み-"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1640,
      kanji: "～頭",
      reading: "～とう",
      meanings: {
        ja: "～頭",
        en: "head (counter)",
        zh: "～头",
        tw: "～頭",
        ko: "~두",
        vi: "đầu ~ (đếm)",
        th: "หัว ~",
        my: "ဦးခေါင်း ~",
        km: "ក្បាល ~",
      },
      furigana: [
        {
          rb: "～頭",
          rt: "～とう",
        },
      ],
      kanjiInfo: [
        {
          char: "頭",
          on: ["トウ", "ズ", "ト"],
          kun: ["あたま", "かしら", "-がしら", "かぶり"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1641,
      kanji: "～等",
      reading: "～とう",
      meanings: {
        ja: "～等",
        en: "etc.; rank",
        zh: "～等",
        tw: "～等",
        ko: "~등",
        vi: "cấp ~",
        th: "ระดับ ~",
        my: "အဆင့် ~",
        km: "ថ្នាក់ ~",
      },
      furigana: [
        {
          rb: "～等",
          rt: "～とう",
        },
      ],
      kanjiInfo: [
        {
          char: "等",
          on: ["トウ"],
          kun: ["ひと.しい", "など", "-ら"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1642,
      kanji: "～島",
      reading: "～とう",
      meanings: {
        ja: "～島",
        en: "island",
        zh: "～岛",
        tw: "～島",
        ko: "~도",
        vi: "đảo ~",
        th: "เกาะ ~",
        my: "ကျွန်း ~",
        km: "កោះ ~",
      },
      furigana: [
        {
          rb: "～島",
          rt: "～とう",
        },
      ],
      kanjiInfo: [
        {
          char: "島",
          on: ["トウ"],
          kun: ["しま"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1643,
      kanji: "同～",
      reading: "どう～",
      meanings: {
        ja: "同～",
        en: "same ~",
        zh: "同～",
        tw: "同～",
        ko: "동~",
        vi: "cùng ~",
        th: "เดียวกัน ~",
        my: "တူညီသော ~",
        km: "ដូចគ្នា ~",
      },
      furigana: [
        {
          rb: "同～",
          rt: "どう～",
        },
      ],
      kanjiInfo: [
        {
          char: "同",
          on: ["ドウ"],
          kun: ["おな.じ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1644,
      kanji: "～道",
      reading: "～どう",
      meanings: {
        ja: "～道",
        en: "road; way",
        zh: "～道",
        tw: "～道",
        ko: "~도",
        vi: "đường ~",
        th: "ถนน ~",
        my: "လမ်း ~",
        km: "ផ្លូវ ~",
      },
      furigana: [
        {
          rb: "～道",
          rt: "～どう",
        },
      ],
      kanjiInfo: [
        {
          char: "道",
          on: ["ドウ", "トウ"],
          kun: ["みち", "いう"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1645,
      kanji: "どういたしまして (かん)",
      reading: "どういたしまして (かん)",
      meanings: {
        ja: "どういたしまして",
        en: "you're welcome",
        zh: "不客气",
        tw: "不客氣",
        ko: "천만에요",
        vi: "không có gì",
        th: "ไม่เป็นไร",
        my: "စိတ်မရှိပါ",
        km: "អញ្ជើញ",
      },
      furigana: [
        {
          rb: "どういたしまして (かん)",
          rt: "どういたしまして （かん）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1646,
      kanji: "～通り",
      reading: "～とおり",
      meanings: {
        ja: "～通り",
        en: "street; way",
        zh: "～街",
        tw: "～街",
        ko: "~거리",
        vi: "đường ~",
        th: "ถนน ~",
        my: "လမ်း ~",
        km: "ផ្លូវ ~",
      },
      furigana: [
        {
          rb: "～通り",
          rt: "～とおり",
        },
      ],
      kanjiInfo: [
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1647,
      kanji: "～ところ",
      reading: "～ところ",
      meanings: {
        ja: "～所",
        en: "place",
        zh: "～处",
        tw: "～處",
        ko: "~곳",
        vi: "nơi ~",
        th: "ที่ ~",
        my: "နေရာ ~",
        km: "កន្លែង ~",
      },
      furigana: [
        {
          rb: "～ところ",
          rt: "～ところ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1648,
      kanji: "とっくに",
      reading: "とっくに",
      meanings: {
        ja: "とっくに",
        en: "long ago; already",
        zh: "早就",
        tw: "早就",
        ko: "이미",
        vi: "từ lâu",
        th: "นานแล้ว",
        my: "အတော်ကြာပြီ",
        km: "យូរហើយ",
      },
      furigana: [
        {
          rb: "とっくに",
          rt: "とっくに",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1649,
      kanji: "殿",
      reading: "どの",
      meanings: {
        ja: "殿",
        en: "Mr.; lord",
        zh: "殿",
        tw: "殿",
        ko: "님",
        vi: "ngài",
        th: "ท่าน",
        my: "ဦးလေး",
        km: "លោក ~",
      },
      furigana: [
        {
          rb: "殿",
          rt: "どの",
        },
      ],
      kanjiInfo: [
        {
          char: "殿",
          on: ["デン", "テン"],
          kun: ["との", "-どの"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1650,
      kanji: "ともかく",
      reading: "ともかく",
      meanings: {
        ja: "ともかく",
        en: "anyhow; at any rate",
        zh: "姑且",
        tw: "姑且",
        ko: "아무튼",
        vi: "dù sao",
        th: "อย่างไรก็ดี",
        my: "အကယ်၍",
        km: "គ្រប់វិធី",
      },
      furigana: [
        {
          rb: "ともかく",
          rt: "ともかく",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1651,
      kanji: "～内",
      reading: "～ない",
      meanings: {
        ja: "～内",
        en: "inside ~",
        zh: "～内",
        tw: "～內",
        ko: "~내",
        vi: "bên trong ~",
        th: "ภายใน ~",
        my: "အတွင်း ~",
        km: "ខាងក្នុង ~",
      },
      furigana: [
        {
          rb: "～内",
          rt: "～ない",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1652,
      kanji: "長～",
      reading: "なが～",
      meanings: {
        ja: "長～",
        en: "long ~",
        zh: "长～",
        tw: "長～",
        ko: "장~",
        vi: "dài ~",
        th: "ยาว ~",
        my: "ရှည် ~",
        km: "វែង ~",
      },
      furigana: [
        {
          rb: "長～",
          rt: "なが～",
        },
      ],
      kanjiInfo: [
        {
          char: "長",
          on: ["チョウ"],
          kun: ["なが.い", "おさ"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1653,
      kanji: "なにしろ",
      reading: "なにしろ",
      meanings: {
        ja: "なにしろ",
        en: "at any rate",
        zh: "无论如何",
        tw: "無論如何",
        ko: "아무튼",
        vi: "dù sao",
        th: "อย่างไรก็",
        my: "ဘာဖြစ်ဖြစ်",
        km: "យ៉ាងណាក៏ដោយ",
      },
      furigana: [
        {
          rb: "なにしろ",
          rt: "なにしろ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1654,
      kanji: "何々",
      reading: "なになに",
      meanings: {
        ja: "何々",
        en: "what",
        zh: "什么",
        tw: "什麼",
        ko: "무엇",
        vi: "cái gì",
        th: "อะไร",
        my: "ဘာ",
        km: "អ្វី",
      },
      furigana: [
        {
          rb: "何々",
          rt: "なになに",
        },
      ],
      kanjiInfo: [
        {
          char: "何",
          on: ["カ"],
          kun: ["なに", "なん", "なに-", "なん-"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1655,
      kanji: "なんとなく",
      reading: "なんとなく",
      meanings: {
        ja: "なんとなく",
        en: "somehow",
        zh: "不知为何",
        tw: "不知為何",
        ko: "왠지",
        vi: "không hiểu sao",
        th: "ไม่รู้ทำไม",
        my: "အချို့ကြောင့်",
        km: "មិនដឹងហេតុអ្វី",
      },
      furigana: [
        {
          rb: "なんとなく",
          rt: "なんとなく",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1656,
      kanji: "なんとも",
      reading: "なんとも",
      meanings: {
        ja: "なんとも",
        en: "nothing (with neg. verb)",
        zh: "什么也不",
        tw: "什麼也不",
        ko: "아무것도",
        vi: "không gì",
        th: "ไม่มีอะไร",
        my: "ဘာမှမဟုတ်",
        km: "គ្មានអ្វី",
      },
      furigana: [
        {
          rb: "なんとも",
          rt: "なんとも",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1657,
      kanji: "～難い",
      reading: "～がたい",
      meanings: {
        ja: "～難い",
        en: "hard to ~",
        zh: "难以～",
        tw: "難以～",
        ko: "~하기 어렵다",
        vi: "khó ~",
        th: "ยากที่จะ ~",
        my: "ခက်ခဲ",
        km: "ពិបាក ~",
      },
      furigana: [
        {
          rb: "～難い",
          rt: "～がたい",
        },
      ],
      kanjiInfo: [
        {
          char: "難",
          on: ["ナン"],
          kun: [
            "かた.い",
            "-がた.い",
            "むずか.しい",
            "むづか.しい",
            "むつか.しい",
            "-にく.い",
          ],
          strokes: 18,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1658,
      kanji: "ねじ",
      reading: "ねじ",
      meanings: {
        ja: "ねじ",
        en: "screw",
        zh: "螺丝",
        tw: "螺絲",
        ko: "나사",
        vi: "ốc vít",
        th: "น็อต",
        my: "ဝက်အူ",
        km: "វីស",
      },
      furigana: [
        {
          rb: "ねじ",
          rt: "ねじ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1659,
      kanji: "～年生",
      reading: "～ねんせい",
      meanings: {
        ja: "～年生",
        en: "year student",
        zh: "～年级",
        tw: "～年級",
        ko: "~학년",
        vi: "năm thứ ~",
        th: "ปีการศึกษา ~",
        my: "တန်း ~",
        km: "ថ្នាក់ទី ~",
      },
      furigana: [
        {
          rb: "～年生",
          rt: "～ねんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "生",
          on: ["セイ", "ショウ"],
          kun: [
            "い.きる",
            "い.かす",
            "い.ける",
            "う.まれる",
            "うま.れる",
            "う.まれ",
            "うまれ",
            "う.む",
            "お.う",
            "は.える",
            "は.やす",
            "き",
            "なま",
            "なま-",
            "な.る",
            "な.す",
            "む.す",
            "-う",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1660,
      kanji: "のこぎり",
      reading: "のこぎり",
      meanings: {
        ja: "のこぎり",
        en: "saw (tool)",
        zh: "锯子",
        tw: "鋸子",
        ko: "톱",
        vi: "cưa",
        th: "เลื่อย",
        my: "လွှ",
        km: "រណារ",
      },
      furigana: [
        {
          rb: "のこぎり",
          rt: "のこぎり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1661,
      kanji: "はい (かん)",
      reading: "はい (かん)",
      meanings: {
        ja: "はい",
        en: "yes; okay",
        zh: "是",
        tw: "是",
        ko: "네",
        vi: "vâng",
        th: "ค่ะ/ครับ",
        my: "ဟုတ်ပါတယ်",
        km: "បាទ/ចាស",
      },
      furigana: [
        {
          rb: "はい (かん)",
          rt: "はい （かん）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1662,
      kanji: "バイバイ",
      reading: "バイバイ",
      meanings: {
        ja: "バイバイ",
        en: "bye-bye",
        zh: "拜拜",
        tw: "掰掰",
        ko: "바이바이",
        vi: "tạm biệt",
        th: "บ๊ายบาย",
        my: "နေပြီးပါ",
        km: "លាហើយ",
      },
      furigana: [
        {
          rb: "バイバイ",
          rt: "バイバイ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1663,
      kanji: "ばからしい",
      reading: "ばからしい",
      meanings: {
        ja: "ばからしい",
        en: "absurd; foolish",
        zh: "荒唐",
        tw: "荒唐",
        ko: "어리석다",
        vi: "ngu ngốc",
        th: "โง่เขลา",
        my: "အနိမ့်ဆုံး",
        km: "ឆ្កួត",
      },
      furigana: [
        {
          rb: "ばからしい",
          rt: "ばからしい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1664,
      kanji: "～泊",
      reading: "～はく",
      meanings: {
        ja: "～泊",
        en: "night(s) stay",
        zh: "～宿",
        tw: "～宿",
        ko: "~박",
        vi: "~ đêm",
        th: "~ คืน",
        my: "ည ~",
        km: "យប់ ~",
      },
      furigana: [
        {
          rb: "～泊",
          rt: "～はく",
        },
      ],
      kanjiInfo: [
        {
          char: "泊",
          on: ["ハク"],
          kun: ["と.まる", "と.める"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1665,
      kanji: "バケツ",
      reading: "バケツ",
      meanings: {
        ja: "バケツ",
        en: "bucket",
        zh: "桶",
        tw: "水桶",
        ko: "양동이",
        vi: "xô",
        th: "ถังน้ำ",
        my: "ဒလီ",
        km: "ធុង",
      },
      furigana: [
        {
          rb: "バケツ",
          rt: "バケツ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1666,
      kanji: "始めに",
      reading: "はじめに",
      meanings: {
        ja: "始めに",
        en: "at first",
        zh: "首先",
        tw: "首先",
        ko: "처음에",
        vi: "ban đầu",
        th: "ตอนแรก",
        my: "အစတွင်",
        km: "ដំបូង",
      },
      furigana: [
        {
          rb: "始めに",
          rt: "はじめに",
        },
      ],
      kanjiInfo: [
        {
          char: "始",
          on: ["シ"],
          kun: ["はじ.める", "-はじ.める", "はじ.まる"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1667,
      kanji: "初めに",
      reading: "はじめに",
      meanings: {
        ja: "初めに",
        en: "at first",
        zh: "首先",
        tw: "首先",
        ko: "처음에",
        vi: "lúc đầu",
        th: "ในตอนแรก",
        my: "အစ",
        km: "ដំបូង",
      },
      furigana: [
        {
          rb: "初めに",
          rt: "はじめに",
        },
      ],
      kanjiInfo: [
        {
          char: "初",
          on: ["ショ"],
          kun: [
            "はじ.め",
            "はじ.めて",
            "はつ",
            "はつ-",
            "うい-",
            "-そ.める",
            "-ぞ.め",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1668,
      kanji: "はじめまして",
      reading: "はじめまして",
      meanings: {
        ja: "はじめまして",
        en: "nice to meet you",
        zh: "初次见面",
        tw: "初次見面",
        ko: "처음 뵙겠습니다",
        vi: "rất hân hạnh",
        th: "ยินดีที่ได้รู้จัก",
        my: "တွေ့ရတာဝမ်းသာပါတယ်",
        km: "រីករាយដែលបានជួប",
      },
      furigana: [
        {
          rb: "はじめまして",
          rt: "はじめまして",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1669,
      kanji: "～発",
      reading: "～はつ",
      meanings: {
        ja: "～発",
        en: "departure; originating from",
        zh: "～发",
        tw: "～發",
        ko: "~발",
        vi: "xuất phát từ ~",
        th: "ออกจาก ~",
        my: "ထွက်ခြင်း ~",
        km: "ចេញពី ~",
      },
      furigana: [
        {
          rb: "～発",
          rt: "～はつ",
        },
      ],
      kanjiInfo: [
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1670,
      kanji: "ばね",
      reading: "ばね",
      meanings: {
        ja: "ばね",
        en: "spring (coil)",
        zh: "弹簧",
        tw: "彈簧",
        ko: "스프링",
        vi: "lò xo",
        th: "สปริง",
        my: "နွေဦး",
        km: "និទាឃ",
      },
      furigana: [
        {
          rb: "ばね",
          rt: "ばね",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1671,
      kanji: "はめる",
      reading: "はめる",
      meanings: {
        ja: "はめる",
        en: "to insert; to put in",
        zh: "嵌入",
        tw: "嵌入",
        ko: "끼우다",
        vi: "lắp vào",
        th: "สวมใส่",
        my: "တပ်ဆင်သည်",
        km: "បញ្ចូល",
      },
      furigana: [
        {
          rb: "はめる",
          rt: "はめる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1672,
      kanji: "反～",
      reading: "はん～",
      meanings: {
        ja: "反～",
        en: "anti- ~",
        zh: "反～",
        tw: "反～",
        ko: "반~",
        vi: "phản ~",
        th: "ต่อต้าน ~",
        my: "ဆန့်ကျင် ~",
        km: "ប្រឆាំង ~",
      },
      furigana: [
        {
          rb: "反～",
          rt: "はん～",
        },
      ],
      kanjiInfo: [
        {
          char: "反",
          on: ["ハン", "ホン", "タン", "ホ"],
          kun: ["そ.る", "そ.らす", "かえ.す", "かえ.る", "-かえ.る"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1673,
      kanji: "万歳",
      reading: "ばんざい",
      meanings: {
        ja: "万歳",
        en: "banzai; hurrah",
        zh: "万岁",
        tw: "萬歲",
        ko: "만세",
        vi: "vạn tuế",
        th: "บันไซ",
        my: "ဗန်ဇေ",
        km: "អបអរសាទរ",
      },
      furigana: [
        {
          rb: "万歳",
          rt: "ばんざい",
        },
      ],
      kanjiInfo: [
        {
          char: "万",
          on: ["マン", "バン"],
          kun: ["よろず"],
          strokes: 3,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "歳",
          on: ["サイ", "セイ"],
          kun: ["とし", "とせ", "よわい"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1674,
      kanji: "～番目",
      reading: "～ばんめ",
      meanings: {
        ja: "～番目",
        en: "ordinal number",
        zh: "第～号",
        tw: "第～號",
        ko: "~번째",
        vi: "thứ ~",
        th: "ลำดับที่ ~",
        my: "အမှတ်စဉ် ~",
        km: "លំដាប់ ~",
      },
      furigana: [
        {
          rb: "～番目",
          rt: "～ばんめ",
        },
      ],
      kanjiInfo: [
        {
          char: "番",
          on: ["バン"],
          kun: ["つが.い"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "目",
          on: ["モク", "ボク"],
          kun: ["め", "-め", "ま-"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1675,
      kanji: "非～",
      reading: "ひ～",
      meanings: {
        ja: "非～",
        en: "non- ~",
        zh: "非～",
        tw: "非～",
        ko: "비~",
        vi: "phi ~",
        th: "ไม่ใช่ ~",
        my: "မ ~",
        km: "មិនមែន ~",
      },
      furigana: [
        {
          rb: "非～",
          rt: "ひ～",
        },
      ],
      kanjiInfo: [
        {
          char: "非",
          on: ["ヒ"],
          kun: ["あら.ず"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1676,
      kanji: "～費",
      reading: "～ひ",
      meanings: {
        ja: "～費",
        en: "expense; cost",
        zh: "～费",
        tw: "～費",
        ko: "~비",
        vi: "chi phí ~",
        th: "ค่าใช้จ่าย ~",
        my: "ကုန်ကျစရိတ် ~",
        km: "ចំណាយ ~",
      },
      furigana: [
        {
          rb: "～費",
          rt: "～ひ",
        },
      ],
      kanjiInfo: [
        {
          char: "費",
          on: ["ヒ"],
          kun: ["つい.やす", "つい.える"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1677,
      kanji: "一～",
      reading: "ひと～",
      meanings: {
        ja: "一～",
        en: "one ~",
        zh: "一～",
        tw: "一～",
        ko: "한~",
        vi: "một ~",
        th: "หนึ่ง ~",
        my: "တစ် ~",
        km: "មួយ ~",
      },
      furigana: [
        {
          rb: "一～",
          rt: "ひと～",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1678,
      kanji: "ひとまず",
      reading: "ひとまず",
      meanings: {
        ja: "ひとまず",
        en: "for the present",
        zh: "暂且",
        tw: "暫且",
        ko: "우선",
        vi: "trước mắt",
        th: "ก่อนอื่น",
        my: "ယာယီ",
        km: "បណ្តោះអាសន្ន",
      },
      furigana: [
        {
          rb: "ひとまず",
          rt: "ひとまず",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1679,
      kanji: "ひとりでに",
      reading: "ひとりでに",
      meanings: {
        ja: "ひとりでに",
        en: "by itself; automatically",
        zh: "自然而然",
        tw: "自然而然",
        ko: "저절로",
        vi: "tự nhiên",
        th: "เอง",
        my: "အလိုအလျောက်",
        km: "ដោយស្វ័យប្រវត្តិ",
      },
      furigana: [
        {
          rb: "ひとりでに",
          rt: "ひとりでに",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1680,
      kanji: "ひゃっかじてん",
      reading: "ひゃっかじてん",
      meanings: {
        ja: "ひゃっかじてん",
        en: "encyclopedia",
        zh: "百科辞典",
        tw: "百科辭典",
        ko: "백과사전",
        vi: "bách khoa toàn thư",
        th: "สารานุกรม",
        my: "ဗဟုသုတအဘိဓာန်",
        km: "វចនានុក្រមសព្វវចន",
      },
      furigana: [
        {
          rb: "ひゃっかじてん",
          rt: "ひゃっかじてん",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1681,
      kanji: "～病",
      reading: "～びょう",
      meanings: {
        ja: "～病",
        en: "illness",
        zh: "～病",
        tw: "～病",
        ko: "~병",
        vi: "bệnh ~",
        th: "โรค ~",
        my: "ရောဂါ ~",
        km: "ជំងឺ ~",
      },
      furigana: [
        {
          rb: "～病",
          rt: "～びょう",
        },
      ],
      kanjiInfo: [
        {
          char: "病",
          on: ["ビョウ", "ヘイ"],
          kun: ["や.む", "-や.み", "やまい"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1682,
      kanji: "～部",
      reading: "～ぶ",
      meanings: {
        ja: "～部",
        en: "club; part",
        zh: "～部",
        tw: "～部",
        ko: "~부",
        vi: "bộ ~",
        th: "ส่วน ~",
        my: "ဌာန ~",
        km: "ផ្នែក ~",
      },
      furigana: [
        {
          rb: "～部",
          rt: "～ぶ",
        },
      ],
      kanjiInfo: [
        {
          char: "部",
          on: ["ブ"],
          kun: ["-べ"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1683,
      kanji: "～風",
      reading: "～ふう",
      meanings: {
        ja: "～風",
        en: "style; manner",
        zh: "～风",
        tw: "～風",
        ko: "~풍",
        vi: "kiểu ~",
        th: "แบบ ~",
        my: "စတိုင် ~",
        km: "រចនាប័ទ្ម ~",
      },
      furigana: [
        {
          rb: "～風",
          rt: "～ふう",
        },
      ],
      kanjiInfo: [
        {
          char: "風",
          on: ["フウ", "フ"],
          kun: ["かぜ", "かざ-"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
  ],
};
