export const n2part2 = {
  Lesson2: [
    {
      id: 51,
      kanji: "職場",
      reading: "しょくば",
      meanings: {
        ja: "職場",
        en: "(one's) workplace; post",
        zh: "职场; 工作单位",
        tw: "職場; 工作單位",
        ko: "직장; 근무지",
        vi: "nơi làm việc",
        th: "ที่ทำงาน",
        my: "အလုပ်နေရာ",
        km: "កន្លែងធ្វើការ",
      },
      furigana: [
        {
          rb: "職場",
          rt: "しょくば",
        },
      ],
      kanjiInfo: [
        {
          char: "職",
          on: ["ショク", "ソク"],
          kun: [],
          strokes: 18,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "場",
          on: ["ジョウ", "チョウ"],
          kun: ["ば"],
          strokes: 12,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 52,
      kanji: "書籍",
      reading: "しょせき",
      meanings: {
        ja: "書籍",
        en: "books; publications",
        zh: "书籍",
        tw: "書籍",
        ko: "서적",
        vi: "sách vở; ấn phẩm",
        th: "ตำรา; หนังสือ",
        my: "စာအုပ်များ",
        km: "សៀវភៅ",
      },
      furigana: [
        {
          rb: "書籍",
          rt: "しょせき",
        },
      ],
      kanjiInfo: [
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "籍",
          on: ["セキ"],
          kun: [],
          strokes: 20,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 53,
      kanji: "食器",
      reading: "しょっき",
      meanings: {
        ja: "食器",
        en: "tableware; dishes",
        zh: "餐具",
        tw: "餐具",
        ko: "식기",
        vi: "bộ đồ ăn",
        th: "ภาชนะบนโต๊ะอาหาร",
        my: "စားပွဲတင်ပန်းကန်ခွက်",
        km: "ប្រដាប់ចានចង្កឹះ",
      },
      furigana: [
        {
          rb: "食器",
          rt: "しょっき",
        },
      ],
      kanjiInfo: [
        {
          char: "食",
          on: ["ショク", "ジキ"],
          kun: ["く.う", "く.らう", "た.べる", "は.む"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 54,
      kanji: "ショップ",
      reading: "ショップ",
      meanings: {
        ja: "ショップ",
        en: "shop; store",
        zh: "店铺",
        tw: "商店",
        ko: "숍; 가게",
        vi: "cửa hàng",
        th: "ร้านค้า",
        my: "ဆိုင်",
        km: "ហាង",
      },
      furigana: [
        {
          rb: "ショップ",
          rt: "ショップ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 55,
      kanji: "書店",
      reading: "しょてん",
      meanings: {
        ja: "書店",
        en: "bookshop; bookstore",
        zh: "书店",
        tw: "書店",
        ko: "서점",
        vi: "nhà sách",
        th: "ร้านหนังสือ",
        my: "စာအုပ်ဆိုင်",
        km: "ហាងសៀវភៅ",
      },
      furigana: [
        {
          rb: "書店",
          rt: "しょてん",
        },
      ],
      kanjiInfo: [
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "店",
          on: ["テン"],
          kun: ["みせ", "たな"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 56,
      kanji: "書道",
      reading: "しょどう",
      meanings: {
        ja: "書道",
        en: "calligraphy (East Asian)",
        zh: "书法",
        tw: "書法",
        ko: "서예",
        vi: "thư pháp",
        th: "ศิลปะคัดลายมือ",
        my: "စာလက်ရေးအနုပညာ",
        km: "សិល្បៈសរសេរ (សៀវភៅ)",
      },
      furigana: [
        {
          rb: "書道",
          rt: "しょどう",
        },
      ],
      kanjiInfo: [
        {
          char: "書",
          on: ["ショ"],
          kun: ["か.く", "-が.き", "-がき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "道",
          on: ["ドウ", "トウ"],
          kun: ["みち", "いう"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 57,
      kanji: "初歩",
      reading: "しょほ",
      meanings: {
        ja: "初歩",
        en: "basics; rudiments",
        zh: "入门; 初步",
        tw: "入門; 初步",
        ko: "초보; 기초",
        vi: "sơ bộ; căn bản",
        th: "ขั้นต้น; พื้นฐาน",
        my: "မူလအခြေခံ",
        km: "មូលដ្ឋានដំបូង",
      },
      furigana: [
        {
          rb: "初歩",
          rt: "しょほ",
        },
      ],
      kanjiInfo: [
        {
          char: "初",
          on: ["ショ"],
          kun: [
            "はじ.め",
            "はじ.めて",
            "はつ",
            "はつ-",
            "うい-",
            "-そ.める",
            "-ぞ.め",
          ],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "歩",
          on: ["ホ", "ブ", "フ"],
          kun: ["ある.く", "あゆ.む"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 58,
      kanji: "白髪",
      reading: "しらが",
      meanings: {
        ja: "白髪",
        en: "white hair; gray hair",
        zh: "白发",
        tw: "白髮",
        ko: "백발",
        vi: "tóc bạc",
        th: "ผมหงอก",
        my: "ဆံပင်ဖြူ",
        km: "សក់ស",
      },
      furigana: [
        {
          rb: "白髪",
          rt: "しらが",
        },
      ],
      kanjiInfo: [
        {
          char: "白",
          on: ["ハク", "ビャク"],
          kun: ["しろ", "しら-", "しろ.い"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "髪",
          on: ["ハツ"],
          kun: ["かみ"],
          strokes: 14,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 59,
      kanji: "シリーズ",
      reading: "シリーズ",
      meanings: {
        ja: "シリーズ",
        en: "series",
        zh: "系列",
        tw: "系列",
        ko: "시리즈",
        vi: "loạt; series",
        th: "ชุดซีรีส์",
        my: "စီးရီး",
        km: "ស៊េរី",
      },
      furigana: [
        {
          rb: "シリーズ",
          rt: "シリーズ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 60,
      kanji: "私立",
      reading: "しりつ",
      meanings: {
        ja: "私立",
        en: "private (institution)",
        zh: "私立",
        tw: "私立",
        ko: "사립",
        vi: "tư lập",
        th: "เอกชน",
        my: "ကိုယ်ပိုင်",
        km: "ឯកជន",
      },
      furigana: [
        {
          rb: "私立",
          rt: "しりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "私",
          on: ["シ"],
          kun: ["わたくし", "わたし"],
          strokes: 7,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
        {
          char: "立",
          on: ["リツ", "リュウ", "リットル"],
          kun: [
            "た.つ",
            "-た.つ",
            "た.ち-",
            "た.てる",
            "-た.てる",
            "た.て-",
            "たて-",
            "-た.て",
            "-だ.て",
            "-だ.てる",
          ],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 61,
      kanji: "資料",
      reading: "しりょう",
      meanings: {
        ja: "資料",
        en: "materials; data",
        zh: "资料; 材料",
        tw: "資料; 材料",
        ko: "자료",
        vi: "tư liệu; tài liệu",
        th: "เอกสารข้อมูล",
        my: "အချက်အလက်များ",
        km: "ឯកសារ; ទិន្នន័យ",
      },
      furigana: [
        {
          rb: "資料",
          rt: "しりょう",
        },
      ],
      kanjiInfo: [
        {
          char: "資",
          on: ["シ"],
          kun: [],
          strokes: 13,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "料",
          on: ["リョウ"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 62,
      kanji: "汁",
      reading: "しる",
      meanings: {
        ja: "汁",
        en: "juice; soup; broth",
        zh: "汁; 汤",
        tw: "汁; 湯",
        ko: "즙; 국물",
        vi: "nước (súp/ép)",
        th: "น้ำซุป; น้ำผลไม้",
        my: "ရည်; ရေနွေးဓါတ်",
        km: "ទឹក; ស៊ុប",
      },
      furigana: [
        {
          rb: "汁",
          rt: "しる",
        },
      ],
      kanjiInfo: [
        {
          char: "汁",
          on: ["ジュウ"],
          kun: ["しる", "-しる", "つゆ"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 63,
      kanji: "素人",
      reading: "しろうと",
      meanings: {
        ja: "素人",
        en: "amateur; layperson",
        zh: "外行; 业余",
        tw: "外行; 業餘",
        ko: "아마추어; 비전문가",
        vi: "nghiệp dư",
        th: "มือสมัครเล่น",
        my: "素人/ လက်မှတ်မပါ",
        km: "មិនជំនាញ; សិស្ស",
      },
      furigana: [
        {
          rb: "素人",
          rt: "しろうと",
        },
      ],
      kanjiInfo: [
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 64,
      kanji: "芯",
      reading: "しん",
      meanings: {
        ja: "芯（芯・しん）",
        en: "core; wick; lead (of pencil)",
        zh: "芯; 中心",
        tw: "芯; 心",
        ko: "심; 심지",
        vi: "lõi; tim; ruột bút chì",
        th: "ไส้; แกน",
        my: "နှုတ်ကများ; အလယ်န္တိ",
        km: "ស្នូល; ឆ្អឹងខ្ចី",
      },
      furigana: [
        {
          rb: "芯",
          rt: "しん",
        },
      ],
      kanjiInfo: [
        {
          char: "芯",
          on: ["シン"],
          kun: [],
          strokes: 7,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 65,
      kanji: "新幹線",
      reading: "しんかんせん",
      meanings: {
        ja: "新幹線",
        en: "Shinkansen; bullet train",
        zh: "新干线",
        tw: "新幹線",
        ko: "신칸센",
        vi: "tàu siêu tốc Shinkansen",
        th: "รถไฟชินคันเซ็น",
        my: "ရှင်ကန်စင် ရထား",
        km: "រថភ្លើងល្បឿនលឿន",
      },
      furigana: [
        {
          rb: "新幹線",
          rt: "しんかんせん",
        },
      ],
      kanjiInfo: [
        {
          char: "新",
          on: ["シン"],
          kun: ["あたら.しい", "あら.た", "あら-", "にい-"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "幹",
          on: ["カン"],
          kun: ["みき"],
          strokes: 13,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "線",
          on: ["セン"],
          kun: ["すじ"],
          strokes: 15,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 66,
      kanji: "真空",
      reading: "しんくう",
      meanings: {
        ja: "真空",
        en: "vacuum",
        zh: "真空",
        tw: "真空",
        ko: "진공",
        vi: "chân không",
        th: "สุญญากาศ",
        my: "ဗက်ချူမ်",
        km: "សុញ្ញាកាស",
      },
      furigana: [
        {
          rb: "真空",
          rt: "しんくう",
        },
      ],
      kanjiInfo: [
        {
          char: "真",
          on: ["シン"],
          kun: ["ま", "ま-", "まこと"],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 67,
      kanji: "人事",
      reading: "じんじ",
      meanings: {
        ja: "人事（じんじ）",
        en: "personnel affairs; HR",
        zh: "人事; 人力资源",
        tw: "人事",
        ko: "인사(人事)",
        vi: "nhân sự",
        th: "งานบุคคล",
        my: "လူ့ဝန်ထမ်းရေးရာ",
        km: "បុគ្គលិកការងារ",
      },
      furigana: [
        {
          rb: "人事",
          rt: "じんじ",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 68,
      kanji: "心身",
      reading: "しんしん",
      meanings: {
        ja: "心身",
        en: "mind and body",
        zh: "身心",
        tw: "身心",
        ko: "심신",
        vi: "tâm thân; thể xác và tinh thần",
        th: "กายและใจ",
        my: "စိတ်နှင့်ကိုယ်",
        km: "ចិត្តនិងកាយ",
      },
      furigana: [
        {
          rb: "心身",
          rt: "しんしん",
        },
      ],
      kanjiInfo: [
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "身",
          on: ["シン"],
          kun: ["み"],
          strokes: 7,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 69,
      kanji: "申請",
      reading: "しんせい",
      meanings: {
        ja: "申請",
        en: "application; petition",
        zh: "申请",
        tw: "申請",
        ko: "신청",
        vi: "đơn xin; đăng ký",
        th: "การยื่นคำร้อง",
        my: "လျှောက်လွှာတင်",
        km: "ពាក្យស្នើសុំ",
      },
      furigana: [
        {
          rb: "申請",
          rt: "しんせい",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "請",
          on: ["セイ", "シン", "ショウ"],
          kun: ["こ.う", "う.ける"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 70,
      kanji: "人造",
      reading: "じんぞう",
      meanings: {
        ja: "人造",
        en: "artificial; man-made",
        zh: "人造; 人工",
        tw: "人造; 人工",
        ko: "인조",
        vi: "nhân tạo",
        th: "เทียม; ประดิษฐ์",
        my: "အကောင်အထည်ဖော်လွယ်",
        km: "សិប្ប নির্মাণ",
      },
      furigana: [
        {
          rb: "人造",
          rt: "じんぞう",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "造",
          on: ["ゾウ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 71,
      kanji: "寝台",
      reading: "しんだい",
      meanings: {
        ja: "寝台",
        en: "bed; couch",
        zh: "寝台; 床",
        tw: "寢台; 床",
        ko: "침대",
        vi: "giường nằm",
        th: "เตียงนอน",
        my: "ကုတ်တံတား/တယား",
        km: "គ្រែ",
      },
      furigana: [
        {
          rb: "寝台",
          rt: "しんだい",
        },
      ],
      kanjiInfo: [
        {
          char: "寝",
          on: ["シン"],
          kun: ["ね.る", "ね.かす", "い.ぬ", "みたまや", "や.める"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "台",
          on: ["ダイ", "タイ"],
          kun: ["うてな", "われ", "つかさ"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 72,
      kanji: "診断",
      reading: "しんだん",
      meanings: {
        ja: "診断",
        en: "diagnosis",
        zh: "诊断",
        tw: "診斷",
        ko: "진단",
        vi: "chẩn đoán",
        th: "การวินิจฉัย",
        my: "ရောဂါခွဲခြား",
        km: "វិនិច្ឆ័យ",
      },
      furigana: [
        {
          rb: "診断",
          rt: "しんだん",
        },
      ],
      kanjiInfo: [
        {
          char: "診",
          on: ["シン"],
          kun: ["み.る"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "断",
          on: ["ダン"],
          kun: ["た.つ", "ことわ.る", "さだ.める"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 73,
      kanji: "侵入",
      reading: "しんにゅう",
      meanings: {
        ja: "侵入",
        en: "intrusion; invasion",
        zh: "侵入; 入侵",
        tw: "侵入; 入侵",
        ko: "침입",
        vi: "xâm nhập",
        th: "บุกรุก",
        my: "ကျူးကျော်ဝင်ရောက်",
        km: "លុកលុយចូល",
      },
      furigana: [
        {
          rb: "侵入",
          rt: "しんにゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "侵",
          on: ["シン"],
          kun: ["おか.す"],
          strokes: 9,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 74,
      kanji: "人文科学",
      reading: "じんぶんかがく",
      meanings: {
        ja: "人文科学",
        en: "humanities",
        zh: "人文科学",
        tw: "人文科學",
        ko: "인문과학",
        vi: "khoa học nhân văn",
        th: "มนุษยศาสตร์",
        my: "အညာပညာ",
        km: "វិទ្យាសាស្ត្រមនុស្សធម៌",
      },
      furigana: [
        {
          rb: "人文科学",
          rt: "じんぶんかがく",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "文",
          on: ["ブン", "モン"],
          kun: ["ふみ", "あや"],
          strokes: 4,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 75,
      kanji: "人命",
      reading: "じんめい",
      meanings: {
        ja: "人命",
        en: "(human) life",
        zh: "人命",
        tw: "人命",
        ko: "인명",
        vi: "tính mạng con người",
        th: "ชีวิตมนุษย์",
        my: "လူ့အသက်",
        km: "ជីវិតមនុស្ស",
      },
      furigana: [
        {
          rb: "人命",
          rt: "じんめい",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "命",
          on: ["メイ", "ミョウ"],
          kun: ["いのち"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 76,
      kanji: "深夜",
      reading: "しんや",
      meanings: {
        ja: "深夜",
        en: "late at night; midnight hours",
        zh: "深夜",
        tw: "深夜",
        ko: "심야",
        vi: "đêm khuya",
        th: "ดึกดื่น",
        my: "ညသန်းခေါင်",
        km: "យប់ល្ងាច",
      },
      furigana: [
        {
          rb: "深夜",
          rt: "しんや",
        },
      ],
      kanjiInfo: [
        {
          char: "深",
          on: ["シン"],
          kun: ["ふか.い", "-ぶか.い", "ふか.まる", "ふか.める", "み-"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "夜",
          on: ["ヤ"],
          kun: ["よ", "よる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 77,
      kanji: "森林",
      reading: "しんりん",
      meanings: {
        ja: "森林",
        en: "forest; woods",
        zh: "森林",
        tw: "森林",
        ko: "삼림; 숲",
        vi: "rừng; lâm",
        th: "ป่าไม้",
        my: "တောရွာ",
        km: "ព្រៃឈើ",
      },
      furigana: [
        {
          rb: "森林",
          rt: "しんりん",
        },
      ],
      kanjiInfo: [
        {
          char: "森",
          on: ["シン"],
          kun: ["もり"],
          strokes: 12,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "林",
          on: ["リン"],
          kun: ["はやし"],
          strokes: 8,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 78,
      kanji: "親類",
      reading: "しんるい",
      meanings: {
        ja: "親類",
        en: "relatives; kin",
        zh: "亲戚",
        tw: "親戚",
        ko: "친척",
        vi: "họ hàng",
        th: "ญาติ",
        my: "ဆွေမျိုး",
        km: "សាច់ញាតិ",
      },
      furigana: [
        {
          rb: "親類",
          rt: "しんるい",
        },
      ],
      kanjiInfo: [
        {
          char: "親",
          on: ["シン"],
          kun: ["おや", "おや-", "した.しい", "した.しむ"],
          strokes: 16,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "類",
          on: ["ルイ"],
          kun: ["たぐ.い"],
          strokes: 18,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 79,
      kanji: "針路",
      reading: "しんろ",
      meanings: {
        ja: "針路",
        en: "course; direction (navigation)",
        zh: "航向; 进路",
        tw: "航向; 進路",
        ko: "침로; 진로",
        vi: "lộ trình; hướng đi",
        th: "ทิศทาง (เดินเรือ/บิน)",
        my: "လမ်းကြောင်း (航路)",
        km: "ទិសដៅ; មគ្គុទ្ទេសក៍",
      },
      furigana: [
        {
          rb: "針路",
          rt: "しんろ",
        },
      ],
      kanjiInfo: [
        {
          char: "針",
          on: ["シン"],
          kun: ["はり"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "路",
          on: ["ロ", "ル"],
          kun: ["-じ", "みち"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 80,
      kanji: "神話",
      reading: "しんわ",
      meanings: {
        ja: "神話",
        en: "myth; mythology",
        zh: "神话",
        tw: "神話",
        ko: "신화",
        vi: "thần thoại",
        th: "ตำนาน; เทวตำนาน",
        my: "ဒဏ္ဍာရီ",
        km: "រឿងព្រេង",
      },
      furigana: [
        {
          rb: "神話",
          rt: "しんわ",
        },
      ],
      kanjiInfo: [
        {
          char: "神",
          on: ["シン", "ジン"],
          kun: ["かみ", "かん-", "こう-"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 81,
      kanji: "水産",
      reading: "すいさん",
      meanings: {
        ja: "水産",
        en: "fisheries; aquatic products",
        zh: "水产",
        tw: "水產",
        ko: "수산",
        vi: "ngư nghiệp; thủy sản",
        th: "ประมง; สินค้าทะเล",
        my: "ရေမွေအစားအစာ",
        km: "ផលិតផលសមុទ្រ",
      },
      furigana: [
        {
          rb: "水産",
          rt: "すいさん",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 82,
      kanji: "炊事",
      reading: "すいじ",
      meanings: {
        ja: "炊事",
        en: "cooking (household)",
        zh: "炊事; 做饭",
        tw: "炊事; 做飯",
        ko: "취사",
        vi: "nấu ăn",
        th: "การทำครัว",
        my: "အစားအစာချက်ပြုတ်",
        km: "ចម្អិនអាហារ",
      },
      furigana: [
        {
          rb: "炊事",
          rt: "すいじ",
        },
      ],
      kanjiInfo: [
        {
          char: "炊",
          on: ["スイ"],
          kun: ["た.く", "-だ.き"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 83,
      kanji: "水蒸気",
      reading: "すいじょうき",
      meanings: {
        ja: "水蒸気",
        en: "water vapour",
        zh: "水蒸气",
        tw: "水蒸氣",
        ko: "수증기",
        vi: "hơi nước",
        th: "ไอน้ำ",
        my: "ရေနွေးမီးမွှား",
        km: "ចំហាយទឹក",
      },
      furigana: [
        {
          rb: "水蒸気",
          rt: "すいじょうき",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "蒸",
          on: ["ジョウ", "セイ"],
          kun: ["む.す", "む.れる", "む.らす"],
          strokes: 13,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 84,
      kanji: "水素",
      reading: "すいそ",
      meanings: {
        ja: "水素",
        en: "hydrogen (H)",
        zh: "氢; 氢气",
        tw: "氫; 氫氣",
        ko: "수소",
        vi: "hiđrô",
        th: "ไฮโดรเจน",
        my: "ဟိုက်ဒရဂျင်",
        km: "អ៊ីដ្រូសែន",
      },
      furigana: [
        {
          rb: "水素",
          rt: "すいそ",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "素",
          on: ["ソ", "ス"],
          kun: ["もと"],
          strokes: 10,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 85,
      kanji: "推定",
      reading: "すいてい",
      meanings: {
        ja: "推定",
        en: "estimation; presumption",
        zh: "推定; 估计",
        tw: "推定; 估計",
        ko: "추정",
        vi: "suy đoán; ước tính",
        th: "การประมาณ; สันนิษฐาน",
        my: "ခန့်မှန်းခြင်း",
        km: "ប៉ាន់ស្មាន",
      },
      furigana: [
        {
          rb: "推定",
          rt: "すいてい",
        },
      ],
      kanjiInfo: [
        {
          char: "推",
          on: ["スイ"],
          kun: ["お.す"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 86,
      kanji: "水滴",
      reading: "すいてき",
      meanings: {
        ja: "水滴",
        en: "water droplet",
        zh: "水滴",
        tw: "水滴",
        ko: "물방울",
        vi: "giọt nước",
        th: "หยดน้ำ",
        my: "ရေမှုန်",
        km: "បន្ទះទឹក",
      },
      furigana: [
        {
          rb: "水滴",
          rt: "すいてき",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "滴",
          on: ["テキ"],
          kun: ["しずく", "したた.る"],
          strokes: 14,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 87,
      kanji: "水筒",
      reading: "すいとう",
      meanings: {
        ja: "水筒",
        en: "canteen; water bottle",
        zh: "水壶",
        tw: "水壺",
        ko: "물통; 수통",
        vi: "bình nước",
        th: "กระติกน้ำ",
        my: "ရေပုလင်း/ရေရော်",
        km: "កែវទឹក; ដបទឹក",
      },
      furigana: [
        {
          rb: "水筒",
          rt: "すいとう",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "筒",
          on: ["トウ"],
          kun: ["つつ"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 88,
      kanji: "随筆",
      reading: "ずいひつ",
      meanings: {
        ja: "随筆",
        en: "essay; miscellany",
        zh: "随笔; 散文",
        tw: "隨筆; 散文",
        ko: "수필",
        vi: "tùy bút",
        th: "ความเรียง",
        my: "ဆောင်းပါး",
        km: "អត្ថបទសរសេរ",
      },
      furigana: [
        {
          rb: "随筆",
          rt: "ずいひつ",
        },
      ],
      kanjiInfo: [
        {
          char: "随",
          on: ["ズイ"],
          kun: ["まにま.に", "したが.う"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "筆",
          on: ["ヒツ"],
          kun: ["ふで"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 89,
      kanji: "水分",
      reading: "すいぶん",
      meanings: {
        ja: "水分",
        en: "moisture; water content",
        zh: "水分; 含水量",
        tw: "水分; 含水量",
        ko: "수분",
        vi: "độ ẩm; nước",
        th: "ความชื้น",
        my: "စိုထိုင်းဆ",
        km: "សំណើម",
      },
      furigana: [
        {
          rb: "水分",
          rt: "すいぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 90,
      kanji: "水平線",
      reading: "すいへいせん",
      meanings: {
        ja: "水平線",
        en: "horizon (at sea)",
        zh: "水平线",
        tw: "水平線",
        ko: "수평선",
        vi: "đường chân trời (biển)",
        th: "เส้นขอบฟ้า (ทะเล)",
        my: "သောကာပျံတန်း",
        km: "ព្រំប្រទល់មេឃ (សមុទ្រ)",
      },
      furigana: [
        {
          rb: "水平線",
          rt: "すいへいせん",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "平",
          on: ["ヘイ", "ビョウ", "ヒョウ"],
          kun: ["たい.ら", "たい.らげる", "ひら"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "線",
          on: ["セン"],
          kun: ["すじ"],
          strokes: 15,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 91,
      kanji: "水面",
      reading: "すいめん",
      meanings: {
        ja: "水面",
        en: "water surface",
        zh: "水面",
        tw: "水面",
        ko: "수면(물 표면)",
        vi: "mặt nước",
        th: "ผิวน้ำ",
        my: "ရေနပေါ်",
        km: "មុខទឹក",
      },
      furigana: [
        {
          rb: "水面",
          rt: "すいめん",
        },
      ],
      kanjiInfo: [
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "面",
          on: ["メン", "ベン"],
          kun: ["おも", "おもて", "つら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 92,
      kanji: "末っ子",
      reading: "すえっこ",
      meanings: {
        ja: "末っ子",
        en: "youngest child",
        zh: "老幺; 最小的孩子",
        tw: "老么; 最小的孩子",
        ko: "막내",
        vi: "con út",
        th: "ลูกคนสุดท้อง",
        my: "မောင်/နှ妹အောင်ဆုံး",
        km: "កូនក្បែរចុង",
      },
      furigana: [
        {
          rb: "末っ子",
          rt: "すえっこ",
        },
      ],
      kanjiInfo: [
        {
          char: "末",
          on: ["マツ", "バツ"],
          kun: ["すえ", "うら", "うれ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 93,
      kanji: "スカーフ",
      reading: "スカーフ",
      meanings: {
        ja: "スカーフ",
        en: "scarf",
        zh: "围巾; 丝巾",
        tw: "圍巾; 絲巾",
        ko: "스카프",
        vi: "khăn choàng",
        th: "ผ้าพันคอ",
        my: "လည်ပင်းပေါ်",
        km: "កន្សែងព័ទ្ធក",
      },
      furigana: [
        {
          rb: "スカーフ",
          rt: "スカーフ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 94,
      kanji: "図鑑",
      reading: "ずかん",
      meanings: {
        ja: "図鑑",
        en: "illustrated reference book",
        zh: "图鉴",
        tw: "圖鑑",
        ko: "도감",
        vi: "sách tra cứu có hình",
        th: "หนังสือภาพสารานุกรม",
        my: "ပုံတော်စာအုပ်",
        km: "សៀវភៅរូបភាពយោង",
      },
      furigana: [
        {
          rb: "図鑑",
          rt: "ずかん",
        },
      ],
      kanjiInfo: [
        {
          char: "図",
          on: ["ズ", "ト"],
          kun: ["え", "はか.る"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "鑑",
          on: ["カン"],
          kun: ["かんが.みる", "かがみ"],
          strokes: 23,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 95,
      kanji: "隙",
      reading: "すき",
      meanings: {
        ja: "隙（すき）",
        en: "gap; opening; chance",
        zh: "缝隙; 破绽; 机会",
        tw: "縫隙; 破綻; 機會",
        ko: "틈; 허점",
        vi: "khe hở; sơ hở",
        th: "ช่องว่าง; โอกาส",
        my: "ပေါက်ဝင်ရာ; အခွင့်",
        km: "ចន្លោះ; ឱកាស",
      },
      furigana: [
        {
          rb: "隙",
          rt: "すき",
        },
      ],
      kanjiInfo: [
        {
          char: "隙",
          on: ["ゲキ", "キャク", "ケキ"],
          kun: ["すき", "す.く", "す.かす", "ひま"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 96,
      kanji: "杉",
      reading: "すぎ",
      meanings: {
        ja: "杉（すぎ）",
        en: "Japanese cedar (Cryptomeria japonica)",
        zh: "杉树（柳杉）",
        tw: "杉樹（柳杉）",
        ko: "삼나무",
        vi: "cây tuyết tùng Nhật (sugi)",
        th: "ต้นสนซุงิ (ญี่ปุ่น)",
        my: "စူဂိ သစ်",
        km: "ដើមស៊ុគី",
      },
      furigana: [
        {
          rb: "杉",
          rt: "すぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "杉",
          on: ["サン"],
          kun: ["すぎ"],
          strokes: 7,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 97,
      kanji: "好き嫌い",
      reading: "すききらい",
      meanings: {
        ja: "好き嫌い",
        en: "likes and dislikes",
        zh: "好恶",
        tw: "好惡",
        ko: "좋고 싫음",
        vi: "sở thích và ác cảm",
        th: "ความชอบไม่ชอบ",
        my: "ကြိုက်နှစ်သက်/မကြိုက်",
        km: "ចូលចិត្តនិងមិនចូលចិត្ត",
      },
      furigana: [
        {
          rb: "好き嫌い",
          rt: "すききらい",
        },
      ],
      kanjiInfo: [
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "嫌",
          on: ["ケン", "ゲン"],
          kun: ["きら.う", "きら.い", "いや"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 98,
      kanji: "好き好き",
      reading: "すきずき",
      meanings: {
        ja: "好き好き",
        en: "matter of taste",
        zh: "因人而异的喜好",
        tw: "各有所好",
        ko: "호불호의 문제",
        vi: "tùy khẩu vị; tùy sở thích",
        th: "แล้วแต่รสนิยม",
        my: "ရေပန်းစားမှုကွဲပြား",
        km: "ចំណង់ញាប់ញ័រ​ផ្ទាល់ខ្លួន",
      },
      furigana: [
        {
          rb: "好き好き",
          rt: "すきずき",
        },
      ],
      kanjiInfo: [
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "好",
          on: ["コウ"],
          kun: ["この.む", "す.く", "よ.い", "い.い"],
          strokes: 6,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 99,
      kanji: "隙間",
      reading: "すきま",
      meanings: {
        ja: "隙間",
        en: "crevice; gap; space",
        zh: "缝隙; 空隙",
        tw: "縫隙; 空隙",
        ko: "틈새",
        vi: "khe hở",
        th: "ช่องว่าง",
        my: "ပေါက်ကွဲ; အားထား",
        km: "រន្ធរាងតូច",
      },
      furigana: [
        {
          rb: "隙間",
          rt: "すきま",
        },
      ],
      kanjiInfo: [
        {
          char: "隙",
          on: ["ゲキ", "キャク", "ケキ"],
          kun: ["すき", "す.く", "す.かす", "ひま"],
          strokes: 13,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 100,
      kanji: "スクール",
      reading: "スクール",
      meanings: {
        ja: "スクール",
        en: "school",
        zh: "学校",
        tw: "學校",
        ko: "스쿨; 학교",
        vi: "trường học",
        th: "โรงเรียน",
        my: "ကျောင်း",
        km: "សាលារៀន",
      },
      furigana: [
        {
          rb: "スクール",
          rt: "スクール",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
