export const n2part8 = {
  Lesson8: [
    {
      id: 351,
      kanji: "漁業",
      reading: "ぎょぎょう",
      meanings: {
        ja: "漁業",
        en: "fishing industry",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "漁業",
          rt: "ぎょぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "漁",
          on: ["ギョ", "リョウ"],
          kun: ["あさ.る"],
          strokes: 14,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 352,
      kanji: "曲線",
      reading: "きょくせん",
      meanings: {
        ja: "曲線",
        en: "curve",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "曲線",
          rt: "きょくせん",
        },
      ],
      kanjiInfo: [
        {
          char: "曲",
          on: ["キョク"],
          kun: ["ま.がる", "ま.げる", "くま"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "線",
          on: ["セン"],
          kun: ["すじ"],
          strokes: 15,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 353,
      kanji: "規律",
      reading: "きりつ",
      meanings: {
        ja: "規律",
        en: "order; discipline",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "規律",
          rt: "きりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "規",
          on: ["キ"],
          kun: [],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "律",
          on: ["リツ", "リチ", "レツ"],
          kun: [],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 354,
      kanji: "金魚",
      reading: "きんぎょ",
      meanings: {
        ja: "金魚",
        en: "goldfish (Carassius auratus)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "金魚",
          rt: "きんぎょ",
        },
      ],
      kanjiInfo: [
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "魚",
          on: ["ギョ"],
          kun: ["うお", "さかな", "-ざかな"],
          strokes: 11,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 355,
      kanji: "区域",
      reading: "くいき",
      meanings: {
        ja: "区域",
        en: "area; zone",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "区域",
          rt: "くいき",
        },
      ],
      kanjiInfo: [
        {
          char: "区",
          on: ["ク", "オウ", "コウ"],
          kun: [],
          strokes: 4,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "域",
          on: ["イキ"],
          kun: [],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 356,
      kanji: "偶数",
      reading: "ぐうすう",
      meanings: {
        ja: "偶数",
        en: "even number",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "偶数",
          rt: "ぐうすう",
        },
      ],
      kanjiInfo: [
        {
          char: "偶",
          on: ["グウ"],
          kun: ["たま"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 357,
      kanji: "空想",
      reading: "くうそう",
      meanings: {
        ja: "空想",
        en: "daydream; fantasy",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "空想",
          rt: "くうそう",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "想",
          on: ["ソウ", "ソ"],
          kun: ["おも.う"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 358,
      kanji: "空中",
      reading: "くうちゅう",
      meanings: {
        ja: "空中",
        en: "in the air; sky",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "空中",
          rt: "くうちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 359,
      kanji: "クーラー",
      reading: "クーラー",
      meanings: {
        ja: "クーラー",
        en: "air conditioner",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "クーラー",
          rt: "クーラー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 360,
      kanji: "釘",
      reading: "くぎ",
      meanings: {
        ja: "釘",
        en: "nail",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "釘",
          rt: "くぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "釘",
          on: ["テイ", "チョウ"],
          kun: ["くぎ"],
          strokes: 10,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 361,
      kanji: "櫛",
      reading: "くし",
      meanings: {
        ja: "櫛",
        en: "comb",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "櫛",
          rt: "くし",
        },
      ],
      kanjiInfo: [
        {
          char: "櫛",
          on: ["シツ"],
          kun: ["くし", "くしけず.る"],
          strokes: 17,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 362,
      kanji: "苦情",
      reading: "くじょう",
      meanings: {
        ja: "苦情",
        en: "complaint",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "苦情",
          rt: "くじょう",
        },
      ],
      kanjiInfo: [
        {
          char: "苦",
          on: ["ク"],
          kun: [
            "くる.しい",
            "-ぐる.しい",
            "くる.しむ",
            "くる.しめる",
            "にが.い",
            "にが.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "情",
          on: ["ジョウ", "セイ"],
          kun: ["なさ.け"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 363,
      kanji: "苦心",
      reading: "くしん",
      meanings: {
        ja: "苦心",
        en: "pains; hard effort",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "苦心",
          rt: "くしん",
        },
      ],
      kanjiInfo: [
        {
          char: "苦",
          on: ["ク"],
          kun: [
            "くる.しい",
            "-ぐる.しい",
            "くる.しむ",
            "くる.しめる",
            "にが.い",
            "にが.る",
          ],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 364,
      kanji: "屑",
      reading: "くず",
      meanings: {
        ja: "屑",
        en: "scraps; waste",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "屑",
          rt: "くず",
        },
      ],
      kanjiInfo: [
        {
          char: "屑",
          on: ["セツ"],
          kun: ["くず", "いさぎよ.い"],
          strokes: 10,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 365,
      kanji: "薬指",
      reading: "くすりゆび",
      meanings: {
        ja: "薬指",
        en: "ring finger",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "薬指",
          rt: "くすりゆび",
        },
      ],
      kanjiInfo: [
        {
          char: "薬",
          on: ["ヤク"],
          kun: ["くすり"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 366,
      kanji: "唇",
      reading: "くちびる",
      meanings: {
        ja: "唇",
        en: "lip",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "唇",
          rt: "くちびる",
        },
      ],
      kanjiInfo: [
        {
          char: "唇",
          on: ["シン"],
          kun: ["くちびる"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 367,
      kanji: "口紅",
      reading: "くちべに",
      meanings: {
        ja: "口紅",
        en: "lipstick",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "口紅",
          rt: "くちべに",
        },
      ],
      kanjiInfo: [
        {
          char: "口",
          on: ["コウ", "ク"],
          kun: ["くち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "紅",
          on: ["コウ", "ク"],
          kun: ["べに", "くれない", "あか.い"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 368,
      kanji: "句読点",
      reading: "くとうてん",
      meanings: {
        ja: "句読点",
        en: "punctuation mark",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "句読点",
          rt: "くとうてん",
        },
      ],
      kanjiInfo: [
        {
          char: "句",
          on: ["ク"],
          kun: [],
          strokes: 5,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
        {
          char: "読",
          on: ["ドク", "トク", "トウ"],
          kun: ["よ.む", "-よ.み"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 369,
      kanji: "工夫",
      reading: "くふう",
      meanings: {
        ja: "工夫",
        en: "ingenuity; devising (a way)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "工夫",
          rt: "くふう",
        },
      ],
      kanjiInfo: [
        {
          char: "工",
          on: ["コウ", "ク", "グ"],
          kun: [],
          strokes: 3,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "夫",
          on: ["フ", "フウ", "ブ"],
          kun: ["おっと", "それ"],
          strokes: 4,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 370,
      kanji: "区分",
      reading: "くぶん",
      meanings: {
        ja: "区分",
        en: "division; classification",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "区分",
          rt: "くぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "区",
          on: ["ク", "オウ", "コウ"],
          kun: [],
          strokes: 4,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 371,
      kanji: "組合せ",
      reading: "くみあわせ",
      meanings: {
        ja: "組合せ",
        en: "combination",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "組合せ",
          rt: "くみあわせ",
        },
      ],
      kanjiInfo: [
        {
          char: "組",
          on: ["ソ"],
          kun: ["く.む", "くみ", "-ぐみ"],
          strokes: 11,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 372,
      kanji: "クリーニング",
      reading: "クリーニング",
      meanings: {
        ja: "クリーニング",
        en: "cleaning (dry cleaning, etc.)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "クリーニング",
          rt: "クリーニング",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 373,
      kanji: "稽古",
      reading: "けいこ",
      meanings: {
        ja: "稽古",
        en: "practice; training (arts, sports)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "稽古",
          rt: "けいこ",
        },
      ],
      kanjiInfo: [
        {
          char: "稽",
          on: ["ケイ"],
          kun: ["かんが.える", "とど.める"],
          strokes: 15,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
        {
          char: "古",
          on: ["コ"],
          kun: ["ふる.い", "ふる-", "-ふる.す"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 374,
      kanji: "敬語",
      reading: "けいご",
      meanings: {
        ja: "敬語",
        en: "honorific language",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "敬語",
          rt: "けいご",
        },
      ],
      kanjiInfo: [
        {
          char: "敬",
          on: ["ケイ", "キョウ"],
          kun: ["うやま.う"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "語",
          on: ["ゴ"],
          kun: ["かた.る", "かた.らう"],
          strokes: 14,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 375,
      kanji: "蛍光灯",
      reading: "けいこうとう",
      meanings: {
        ja: "蛍光灯",
        en: "fluorescent lamp",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "蛍光灯",
          rt: "けいこうとう",
        },
      ],
      kanjiInfo: [
        {
          char: "蛍",
          on: ["ケイ"],
          kun: ["ほたる"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "光",
          on: ["コウ"],
          kun: ["ひか.る", "ひかり"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "灯",
          on: ["トウ"],
          kun: ["ひ", "ほ-", "ともしび", "とも.す", "あかり"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 376,
      kanji: "形式",
      reading: "けいしき",
      meanings: {
        ja: "形式",
        en: "form (as opposed to substance)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "形式",
          rt: "けいしき",
        },
      ],
      kanjiInfo: [
        {
          char: "形",
          on: ["ケイ", "ギョウ"],
          kun: ["かた", "-がた", "かたち", "なり"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "式",
          on: ["シキ"],
          kun: [],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 377,
      kanji: "継続",
      reading: "けいぞく",
      meanings: {
        ja: "継続",
        en: "continuation",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "継続",
          rt: "けいぞく",
        },
      ],
      kanjiInfo: [
        {
          char: "継",
          on: ["ケイ"],
          kun: ["つ.ぐ", "まま-"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 378,
      kanji: "毛糸",
      reading: "けいと",
      meanings: {
        ja: "毛糸",
        en: "knitting wool; yarn",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "毛糸",
          rt: "けいと",
        },
      ],
      kanjiInfo: [
        {
          char: "毛",
          on: ["モウ"],
          kun: ["け"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "糸",
          on: ["シ"],
          kun: ["いと"],
          strokes: 6,
          grade: 1,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 379,
      kanji: "経度",
      reading: "けいど",
      meanings: {
        ja: "経度",
        en: "longitude",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "経度",
          rt: "けいど",
        },
      ],
      kanjiInfo: [
        {
          char: "経",
          on: ["ケイ", "キョウ", "キン"],
          kun: ["へ.る", "た.つ", "たていと", "はか.る", "のり"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "度",
          on: ["ド", "ト", "タク"],
          kun: ["たび", "-た.い"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 380,
      kanji: "系統",
      reading: "けいとう",
      meanings: {
        ja: "系統",
        en: "system; lineage",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "系統",
          rt: "けいとう",
        },
      ],
      kanjiInfo: [
        {
          char: "系",
          on: ["ケイ"],
          kun: [],
          strokes: 7,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "統",
          on: ["トウ"],
          kun: ["す.べる"],
          strokes: 12,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 381,
      kanji: "芸能",
      reading: "げいのう",
      meanings: {
        ja: "芸能",
        en: "public entertainment; performing arts",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "芸能",
          rt: "げいのう",
        },
      ],
      kanjiInfo: [
        {
          char: "芸",
          on: ["ゲイ", "ウン"],
          kun: ["う.える", "のり", "わざ"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 382,
      kanji: "競馬",
      reading: "けいば",
      meanings: {
        ja: "競馬",
        en: "horse racing",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "競馬",
          rt: "けいば",
        },
      ],
      kanjiInfo: [
        {
          char: "競",
          on: ["キョウ", "ケイ"],
          kun: ["きそ.う", "せ.る", "くら.べる"],
          strokes: 20,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "馬",
          on: ["バ"],
          kun: ["うま", "うま-", "ま"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 383,
      kanji: "警備",
      reading: "けいび",
      meanings: {
        ja: "警備",
        en: "security; guard; defense",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "警備",
          rt: "けいび",
        },
      ],
      kanjiInfo: [
        {
          char: "警",
          on: ["ケイ"],
          kun: ["いまし.める"],
          strokes: 19,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "備",
          on: ["ビ"],
          kun: ["そな.える", "そな.わる", "つぶさ.に"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 384,
      kanji: "形容詞",
      reading: "けいようし",
      meanings: {
        ja: "形容詞",
        en: "adjective",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "形容詞",
          rt: "けいようし",
        },
      ],
      kanjiInfo: [
        {
          char: "形",
          on: ["ケイ", "ギョウ"],
          kun: ["かた", "-がた", "かたち", "なり"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "容",
          on: ["ヨウ"],
          kun: ["い.れる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 385,
      kanji: "形容動詞",
      reading: "けいようどうし",
      meanings: {
        ja: "形容動詞",
        en: "adjectival noun (na-adjective)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "形容動詞",
          rt: "けいようどうし",
        },
      ],
      kanjiInfo: [
        {
          char: "形",
          on: ["ケイ", "ギョウ"],
          kun: ["かた", "-がた", "かたち", "なり"],
          strokes: 7,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "容",
          on: ["ヨウ"],
          kun: ["い.れる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "動",
          on: ["ドウ"],
          kun: ["うご.く", "うご.かす"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "詞",
          on: ["シ"],
          kun: ["ことば"],
          strokes: 12,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 386,
      kanji: "外科",
      reading: "げか",
      meanings: {
        ja: "外科",
        en: "surgery (medical department)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "外科",
          rt: "げか",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 387,
      kanji: "毛皮",
      reading: "けがわ",
      meanings: {
        ja: "毛皮",
        en: "fur (pelt)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "毛皮",
          rt: "けがわ",
        },
      ],
      kanjiInfo: [
        {
          char: "毛",
          on: ["モウ"],
          kun: ["け"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "皮",
          on: ["ヒ"],
          kun: ["かわ"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 388,
      kanji: "激増",
      reading: "げきぞう",
      meanings: {
        ja: "激増",
        en: "sharp increase",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "激増",
          rt: "げきぞう",
        },
      ],
      kanjiInfo: [
        {
          char: "激",
          on: ["ゲキ"],
          kun: ["はげ.しい"],
          strokes: 16,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "増",
          on: ["ゾウ"],
          kun: ["ま.す", "ま.し", "ふ.える", "ふ.やす"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 389,
      kanji: "下車",
      reading: "げしゃ",
      meanings: {
        ja: "下車",
        en: "alighting (from a train, etc.)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "下車",
          rt: "げしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 390,
      kanji: "下旬",
      reading: "げじゅん",
      meanings: {
        ja: "下旬",
        en: "last third of a month",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "下旬",
          rt: "げじゅん",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "旬",
          on: ["ジュン", "シュン"],
          kun: [],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 391,
      kanji: "下水",
      reading: "げすい",
      meanings: {
        ja: "下水",
        en: "drainage; sewer",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "下水",
          rt: "げすい",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "水",
          on: ["スイ"],
          kun: ["みず", "みず-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 392,
      kanji: "桁",
      reading: "けた",
      meanings: {
        ja: "桁",
        en: "digit; order of magnitude; (bridge) beam",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "桁",
          rt: "けた",
        },
      ],
      kanjiInfo: [
        {
          char: "桁",
          on: ["コウ"],
          kun: ["けた"],
          strokes: 10,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 393,
      kanji: "下駄",
      reading: "げた",
      meanings: {
        ja: "下駄",
        en: "geta (wooden clogs)",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "下駄",
          rt: "げた",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "駄",
          on: ["ダ", "タ"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 394,
      kanji: "血圧",
      reading: "けつあつ",
      meanings: {
        ja: "血圧",
        en: "blood pressure",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "血圧",
          rt: "けつあつ",
        },
      ],
      kanjiInfo: [
        {
          char: "血",
          on: ["ケツ"],
          kun: ["ち"],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "圧",
          on: ["アツ", "エン", "オウ"],
          kun: ["お.す", "へ.す", "おさ.える", "お.さえる"],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 395,
      kanji: "月給",
      reading: "げっきゅう",
      meanings: {
        ja: "月給",
        en: "monthly salary",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "月給",
          rt: "げっきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "給",
          on: ["キュウ"],
          kun: ["たま.う", "たも.う", "-たま.え"],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 396,
      kanji: "傑作",
      reading: "けっさく",
      meanings: {
        ja: "傑作",
        en: "masterpiece",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "傑作",
          rt: "けっさく",
        },
      ],
      kanjiInfo: [
        {
          char: "傑",
          on: ["ケツ"],
          kun: ["すぐ.れる"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "作",
          on: ["サク", "サ"],
          kun: ["つく.る", "つく.り", "-づく.り"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 397,
      kanji: "月末",
      reading: "げつまつ",
      meanings: {
        ja: "月末",
        en: "end of the month",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "月末",
          rt: "げつまつ",
        },
      ],
      kanjiInfo: [
        {
          char: "月",
          on: ["ゲツ", "ガツ"],
          kun: ["つき"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "末",
          on: ["マツ", "バツ"],
          kun: ["すえ", "うら", "うれ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 398,
      kanji: "気配",
      reading: "けはい",
      meanings: {
        ja: "気配",
        en: "sign; indication; hint",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "気配",
          rt: "けはい",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "配",
          on: ["ハイ"],
          kun: ["くば.る"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 399,
      kanji: "見学",
      reading: "けんがく",
      meanings: {
        ja: "見学",
        en: "inspection; study visit; field trip",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "見学",
          rt: "けんがく",
        },
      ],
      kanjiInfo: [
        {
          char: "見",
          on: ["ケン"],
          kun: ["み.る", "み.える", "み.せる"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "学",
          on: ["ガク"],
          kun: ["まな.ぶ"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 400,
      kanji: "原稿",
      reading: "げんこう",
      meanings: {
        ja: "原稿",
        en: "manuscript; draft",
        zh: "",
        tw: "",
        ko: "",
        vi: "",
        th: "",
        my: "",
        km: "",
      },
      furigana: [
        {
          rb: "原稿",
          rt: "げんこう",
        },
      ],
      kanjiInfo: [
        {
          char: "原",
          on: ["ゲン"],
          kun: ["はら"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "稿",
          on: ["コウ"],
          kun: ["わら", "したがき"],
          strokes: 15,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
