export const n2part21 = {
  Lesson21: [
    {
      id: 1001,
      kanji: "爪",
      reading: "つめ",
      meanings: {
        ja: "爪",
        en: "nail (e.g. fingernail)",
        zh: "指甲",
        tw: "指甲",
        ko: "손톱",
        vi: "móng tay",
        th: "เล็บ",
        my: "လက်သည်း",
        km: "ក្រចក",
      },
      furigana: [
        {
          rb: "爪",
          rt: "つめ",
        },
      ],
      kanjiInfo: [
        {
          char: "爪",
          on: ["ソウ"],
          kun: ["つめ", "つま-"],
          strokes: 4,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1002,
      kanji: "艶",
      reading: "つや",
      meanings: {
        ja: "艶",
        en: "gloss; luster",
        zh: "光泽",
        tw: "光澤",
        ko: "윤기",
        vi: "độ bóng",
        th: "ความเงา",
        my: "ပွလင်းမှု",
        km: "ពន្លឺ",
      },
      furigana: [
        {
          rb: "艶",
          rt: "つや",
        },
      ],
      kanjiInfo: [
        {
          char: "艶",
          on: ["エン"],
          kun: ["つや", "なま.めかしい", "あで.やか", "つや.めく", "なま.めく"],
          strokes: 19,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1003,
      kanji: "手洗い",
      reading: "てあらい",
      meanings: {
        ja: "手洗い",
        en: "washing one's hands",
        zh: "洗手",
        tw: "洗手",
        ko: "손 씻기",
        vi: "rửa tay",
        th: "ล้างมือ",
        my: "လက်ဆေးခြင်း",
        km: "លាងដៃ",
      },
      furigana: [
        {
          rb: "手洗い",
          rt: "てあらい",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "洗",
          on: ["セン"],
          kun: ["あら.う"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1004,
      kanji: "定員",
      reading: "ていいん",
      meanings: {
        ja: "定員",
        en: "fixed number (of people)",
        zh: "定员",
        tw: "定員",
        ko: "정원",
        vi: "sức chứa",
        th: "จำนวนคนที่กำหนด",
        my: "သတ်မှတ်အရေအတွက်",
        km: "ចំនួនកំណត់",
      },
      furigana: [
        {
          rb: "定員",
          rt: "ていいん",
        },
      ],
      kanjiInfo: [
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "員",
          on: ["イン"],
          kun: [],
          strokes: 10,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1005,
      kanji: "定価",
      reading: "ていか",
      meanings: {
        ja: "定価",
        en: "list price",
        zh: "定价",
        tw: "定價",
        ko: "정가",
        vi: "giá niêm yết",
        th: "ราคาป้าย",
        my: "တင်ထားသည့်စျေး",
        km: "តម្លៃកំណត់",
      },
      furigana: [
        {
          rb: "定価",
          rt: "ていか",
        },
      ],
      kanjiInfo: [
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "価",
          on: ["カ", "ケ"],
          kun: ["あたい"],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1006,
      kanji: "低下",
      reading: "ていか",
      meanings: {
        ja: "低下",
        en: "fall; decline",
        zh: "下降",
        tw: "下降",
        ko: "저하",
        vi: "suy giảm",
        th: "การลดลง",
        my: "ကျဆင်းမှု",
        km: "ការធ្លាក់ចុះ",
      },
      furigana: [
        {
          rb: "低下",
          rt: "ていか",
        },
      ],
      kanjiInfo: [
        {
          char: "低",
          on: ["テイ"],
          kun: ["ひく.い", "ひく.める", "ひく.まる"],
          strokes: 7,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1007,
      kanji: "定期券",
      reading: "ていきけん",
      meanings: {
        ja: "定期券",
        en: "commuter pass",
        zh: "月票",
        tw: "月票",
        ko: "정기권",
        vi: "vé tháng",
        th: "ตั๋วเดือน",
        my: "လစဉ်လက်မှတ်",
        km: "សំបុត្រប្រចាំខែ",
      },
      furigana: [
        {
          rb: "定期券",
          rt: "ていきけん",
        },
      ],
      kanjiInfo: [
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "券",
          on: ["ケン"],
          kun: [],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1008,
      kanji: "定休日",
      reading: "ていきゅうび",
      meanings: {
        ja: "定休日",
        en: "regular holiday",
        zh: "固定休息日",
        tw: "固定休息日",
        ko: "정기휴일",
        vi: "ngày nghỉ định kỳ",
        th: "วันหยุดประจำ",
        my: "အပိတ်ရက်",
        km: "ថ្ងៃឈប់សម្រាកប្រចាំ",
      },
      furigana: [
        {
          rb: "定休日",
          rt: "ていきゅうび",
        },
      ],
      kanjiInfo: [
        {
          char: "定",
          on: ["テイ", "ジョウ"],
          kun: ["さだ.める", "さだ.まる", "さだ.か"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1009,
      kanji: "停止",
      reading: "ていし",
      meanings: {
        ja: "停止",
        en: "stoppage; suspension",
        zh: "停止",
        tw: "停止",
        ko: "정지",
        vi: "dừng lại",
        th: "การหยุด",
        my: "ရပ်နား",
        km: "ការឈប់",
      },
      furigana: [
        {
          rb: "停止",
          rt: "ていし",
        },
      ],
      kanjiInfo: [
        {
          char: "停",
          on: ["テイ"],
          kun: ["と.める", "と.まる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "止",
          on: ["シ"],
          kun: [
            "と.まる",
            "-ど.まり",
            "と.める",
            "-と.める",
            "-ど.め",
            "とど.める",
            "とど.め",
            "とど.まる",
            "や.める",
            "や.む",
            "-や.む",
            "よ.す",
            "-さ.す",
            "-さ.し",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1010,
      kanji: "停車",
      reading: "ていしゃ",
      meanings: {
        ja: "停車",
        en: "stopping (of a train)",
        zh: "停车",
        tw: "停車",
        ko: "정차",
        vi: "tàu dừng",
        th: "การจอดรถไฟ",
        my: "ရထားရပ်",
        km: "រថភ្លើងឈប់",
      },
      furigana: [
        {
          rb: "停車",
          rt: "ていしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "停",
          on: ["テイ"],
          kun: ["と.める", "と.まる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1011,
      kanji: "出入り",
      reading: "でいり",
      meanings: {
        ja: "出入り",
        en: "going in and out",
        zh: "出入",
        tw: "出入",
        ko: "출입",
        vi: "ra vào",
        th: "การเข้าออก",
        my: "ဝင်ထွက်",
        km: "ចូលចេញ",
      },
      furigana: [
        {
          rb: "出入り",
          rt: "でいり",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1012,
      kanji: "出入口",
      reading: "でいりぐち",
      meanings: {
        ja: "出入口",
        en: "exit and entrance",
        zh: "出入口",
        tw: "出入口",
        ko: "출입구",
        vi: "cửa ra vào",
        th: "ทางเข้าออก",
        my: "ဝင်ထွက်ဝ",
        km: "ច្រកចេញចូល",
      },
      furigana: [
        {
          rb: "出入口",
          rt: "でいりぐち",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "口",
          on: ["コウ", "ク"],
          kun: ["くち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1013,
      kanji: "手入れ",
      reading: "ていれ",
      meanings: {
        ja: "手入れ",
        en: "care; maintenance",
        zh: "护理",
        tw: "護理",
        ko: "손질",
        vi: "chăm sóc",
        th: "การดูแล",
        my: "ပြုပြင်ထိန်းသိမ်း",
        km: "ថែទាំ",
      },
      furigana: [
        {
          rb: "手入れ",
          rt: "ていれ",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1014,
      kanji: "テーマ",
      reading: "テーマ",
      meanings: {
        ja: "テーマ",
        en: "theme",
        zh: "主题",
        tw: "主題",
        ko: "테마",
        vi: "chủ đề",
        th: "หัวข้อ",
        my: "အဓိကအကြောင်းအရာ",
        km: "ប្រធានបទ",
      },
      furigana: [
        {
          rb: "テーマ",
          rt: "テーマ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1015,
      kanji: "出来上がり",
      reading: "できあがり",
      meanings: {
        ja: "出来上がり",
        en: "completion; finish",
        zh: "完成",
        tw: "完成",
        ko: "완성",
        vi: "hoàn thành",
        th: "เสร็จสิ้น",
        my: "ပြီးစီးခြင်း",
        km: "បញ្ចប់",
      },
      furigana: [
        {
          rb: "出来上がり",
          rt: "できあがり",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "来",
          on: ["ライ", "タイ"],
          kun: [
            "く.る",
            "きた.る",
            "きた.す",
            "き.たす",
            "き.たる",
            "き",
            "こ",
          ],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1016,
      kanji: "手首",
      reading: "てくび",
      meanings: {
        ja: "手首",
        en: "wrist",
        zh: "手腕",
        tw: "手腕",
        ko: "손목",
        vi: "cổ tay",
        th: "ข้อมือ",
        my: "ဒယ်ခေါင်း",
        km: "កដៃ",
      },
      furigana: [
        {
          rb: "手首",
          rt: "てくび",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "首",
          on: ["シュ"],
          kun: ["くび"],
          strokes: 9,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1017,
      kanji: "凸凹",
      reading: "でこぼこ",
      meanings: {
        ja: "凸凹",
        en: "unevenness",
        zh: "凹凸",
        tw: "凹凸",
        ko: "울퉁불퉁",
        vi: "gồ ghề",
        th: "ขรุขระ",
        my: "မညီမျှမှု",
        km: "អ Uneven",
      },
      furigana: [
        {
          rb: "凸凹",
          rt: "でこぼこ",
        },
      ],
      kanjiInfo: [
        {
          char: "凸",
          on: ["トツ"],
          kun: ["でこ"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "凹",
          on: ["オウ"],
          kun: ["くぼ.む", "へこ.む", "ぼこ"],
          strokes: 5,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1018,
      kanji: "弟子",
      reading: "でし",
      meanings: {
        ja: "弟子",
        en: "pupil; apprentice",
        zh: "弟子",
        tw: "弟子",
        ko: "제자",
        vi: "đệ tử",
        th: "ศิษย์",
        my: "ကျောင်းသား",
        km: "សិស្ស",
      },
      furigana: [
        {
          rb: "弟子",
          rt: "でし",
        },
      ],
      kanjiInfo: [
        {
          char: "弟",
          on: ["テイ", "ダイ", "デ"],
          kun: ["おとうと"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1019,
      kanji: "手帳",
      reading: "てちょう",
      meanings: {
        ja: "手帳",
        en: "notebook; planner",
        zh: "手册",
        tw: "手冊",
        ko: "수첩",
        vi: "sổ tay",
        th: "สมุดบันทึก",
        my: "မှတ်စုစာအုပ်",
        km: "សៀវភៅកំណត់ត្រា",
      },
      furigana: [
        {
          rb: "手帳",
          rt: "てちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "帳",
          on: ["チョウ"],
          kun: ["とばり"],
          strokes: 11,
          grade: 3,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1020,
      kanji: "鉄橋",
      reading: "てっきょう",
      meanings: {
        ja: "鉄橋",
        en: "railway bridge",
        zh: "铁桥",
        tw: "鐵橋",
        ko: "철교",
        vi: "cầu sắt",
        th: "สะพานรถไฟ",
        my: "မီးရထားတံတား",
        km: "ស្ពានដែក",
      },
      furigana: [
        {
          rb: "鉄橋",
          rt: "てっきょう",
        },
      ],
      kanjiInfo: [
        {
          char: "鉄",
          on: ["テツ"],
          kun: ["くろがね"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "橋",
          on: ["キョウ"],
          kun: ["はし"],
          strokes: 16,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1021,
      kanji: "手続き",
      reading: "てつづき",
      meanings: {
        ja: "手続き",
        en: "procedure",
        zh: "手续",
        tw: "手續",
        ko: "절차",
        vi: "thủ tục",
        th: "ขั้นตอน",
        my: "နည်းလမ်း",
        km: "នីតិវិធី",
      },
      furigana: [
        {
          rb: "手続き",
          rt: "てつづき",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "続",
          on: ["ゾク", "ショク", "コウ", "キョウ"],
          kun: ["つづ.く", "つづ.ける", "つぐ.ない"],
          strokes: 13,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1022,
      kanji: "鉄砲",
      reading: "てっぽう",
      meanings: {
        ja: "鉄砲",
        en: "gun",
        zh: "枪",
        tw: "槍",
        ko: "총",
        vi: "súng",
        th: "ปืน",
        my: "ထောက်လှမ်း",
        km: "កាំភ្លើង",
      },
      furigana: [
        {
          rb: "鉄砲",
          rt: "てっぽう",
        },
      ],
      kanjiInfo: [
        {
          char: "鉄",
          on: ["テツ"],
          kun: ["くろがね"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "砲",
          on: ["ホウ"],
          kun: [],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1023,
      kanji: "テニスコート",
      reading: "テニスコート",
      meanings: {
        ja: "テニスコート",
        en: "tennis court",
        zh: "网球场",
        tw: "網球場",
        ko: "테니스코트",
        vi: "sân tennis",
        th: "สนามเทนนิส",
        my: "တင်းနစ်ကွင်း",
        km: "ត្រឡាចទន់",
      },
      furigana: [
        {
          rb: "テニスコート",
          rt: "テニスコート",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1024,
      kanji: "手拭い",
      reading: "てぬぐい",
      meanings: {
        ja: "手拭い",
        en: "(hand) towel",
        zh: "手巾",
        tw: "手巾",
        ko: "수건",
        vi: "khăn tay",
        th: "ผ้าเช็ดมือ",
        my: "လက်သန့်ပေါက်",
        km: "កន្សែងដៃ",
      },
      furigana: [
        {
          rb: "手拭い",
          rt: "てぬぐい",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "拭",
          on: ["ショク", "シキ"],
          kun: ["ぬぐ.う", "ふ.く"],
          strokes: 9,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1025,
      kanji: "手前",
      reading: "てまえ",
      meanings: {
        ja: "手前",
        en: "before oneself",
        zh: "眼前",
        tw: "眼前",
        ko: "앞",
        vi: "trước mặt",
        th: "เบื้องหน้า",
        my: "ရှေ့မှာ",
        km: "ចំពោះមុខ",
      },
      furigana: [
        {
          rb: "手前",
          rt: "てまえ",
        },
      ],
      kanjiInfo: [
        {
          char: "手",
          on: ["シュ", "ズ"],
          kun: ["て", "て-", "-て", "た-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "前",
          on: ["ゼン"],
          kun: ["まえ", "-まえ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1026,
      kanji: "出迎え",
      reading: "でむかえ",
      meanings: {
        ja: "出迎え",
        en: "meeting; reception",
        zh: "迎接",
        tw: "迎接",
        ko: "마중",
        vi: "đón tiếp",
        th: "การต้อนรับ",
        my: "ကြိုဆိုခြင်း",
        km: "ការទទួល",
      },
      furigana: [
        {
          rb: "出迎え",
          rt: "でむかえ",
        },
      ],
      kanjiInfo: [
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "迎",
          on: ["ゲイ"],
          kun: ["むか.える"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1027,
      kanji: "展開",
      reading: "てんかい",
      meanings: {
        ja: "展開",
        en: "development",
        zh: "展开",
        tw: "展開",
        ko: "전개",
        vi: "triển khai",
        th: "การขยาย",
        my: "ဖွံ့ဖြိုးတိုးတက်မှု",
        km: "ការពង្រីក",
      },
      furigana: [
        {
          rb: "展開",
          rt: "てんかい",
        },
      ],
      kanjiInfo: [
        {
          char: "展",
          on: ["テン"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "開",
          on: ["カイ"],
          kun: [
            "ひら.く",
            "ひら.き",
            "-びら.き",
            "ひら.ける",
            "あ.く",
            "あ.ける",
          ],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1028,
      kanji: "伝記",
      reading: "でんき",
      meanings: {
        ja: "伝記",
        en: "biography",
        zh: "传记",
        tw: "傳記",
        ko: "전기",
        vi: "tiểu sử",
        th: "ชีวประวัติ",
        my: "အသက်တာရာဇဝင်",
        km: "ប្រវត្តិរូប",
      },
      furigana: [
        {
          rb: "伝記",
          rt: "でんき",
        },
      ],
      kanjiInfo: [
        {
          char: "伝",
          on: ["デン", "テン"],
          kun: [
            "つた.わる",
            "つた.える",
            "つた.う",
            "つだ.う",
            "-づた.い",
            "つて",
          ],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "記",
          on: ["キ"],
          kun: ["しる.す"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1029,
      kanji: "電球",
      reading: "でんきゅう",
      meanings: {
        ja: "電球",
        en: "light bulb",
        zh: "灯泡",
        tw: "燈泡",
        ko: "전구",
        vi: "bóng đèn",
        th: "หลอดไฟ",
        my: "မီးလုံး",
        km: "អំពូលភ្លើង",
      },
      furigana: [
        {
          rb: "電球",
          rt: "でんきゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "電",
          on: ["デン"],
          kun: [],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "球",
          on: ["キュウ"],
          kun: ["たま"],
          strokes: 11,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1030,
      kanji: "点数",
      reading: "てんすう",
      meanings: {
        ja: "点数",
        en: "marks; points",
        zh: "分数",
        tw: "分數",
        ko: "점수",
        vi: "điểm số",
        th: "คะแนน",
        my: "အမှတ်",
        km: "ពិន្ទុ",
      },
      furigana: [
        {
          rb: "点数",
          rt: "てんすう",
        },
      ],
      kanjiInfo: [
        {
          char: "点",
          on: ["テン"],
          kun: [
            "つ.ける",
            "つ.く",
            "た.てる",
            "さ.す",
            "とぼ.す",
            "とも.す",
            "ぼち",
          ],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "数",
          on: ["スウ", "ス", "サク", "ソク", "シュ"],
          kun: ["かず", "かぞ.える", "しばしば", "せ.める", "わずらわ.しい"],
          strokes: 13,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1031,
      kanji: "伝染",
      reading: "でんせん",
      meanings: {
        ja: "伝染",
        en: "contagion; infection",
        zh: "传染",
        tw: "傳染",
        ko: "전염",
        vi: "lây nhiễm",
        th: "การติดต่อโรค",
        my: "ပိုးပျံ့",
        km: "ជំងឺឆ្លង",
      },
      furigana: [
        {
          rb: "伝染",
          rt: "でんせん",
        },
      ],
      kanjiInfo: [
        {
          char: "伝",
          on: ["デン", "テン"],
          kun: [
            "つた.わる",
            "つた.える",
            "つた.う",
            "つだ.う",
            "-づた.い",
            "つて",
          ],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "染",
          on: ["セン"],
          kun: ["そ.める", "そ.まる", "し.みる", "し.み"],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1032,
      kanji: "電池",
      reading: "でんち",
      meanings: {
        ja: "電池",
        en: "battery",
        zh: "电池",
        tw: "電池",
        ko: "배터리",
        vi: "pin; ắc quy",
        th: "แบตเตอรี่",
        my: "ဘက်ထရီ",
        km: "ថ្ម",
      },
      furigana: [
        {
          rb: "電池",
          rt: "でんち",
        },
      ],
      kanjiInfo: [
        {
          char: "電",
          on: ["デン"],
          kun: [],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "池",
          on: ["チ"],
          kun: ["いけ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1033,
      kanji: "電柱",
      reading: "でんちゅう",
      meanings: {
        ja: "電柱",
        en: "utility pole",
        zh: "电线杆",
        tw: "電線桿",
        ko: "전봇대",
        vi: "cột điện",
        th: "เสาไฟฟ้า",
        my: "မီးစက်တိုင်",
        km: "សសរអគ្គិសនី",
      },
      furigana: [
        {
          rb: "電柱",
          rt: "でんちゅう",
        },
      ],
      kanjiInfo: [
        {
          char: "電",
          on: ["デン"],
          kun: [],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "柱",
          on: ["チュウ"],
          kun: ["はしら"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1034,
      kanji: "天皇",
      reading: "てんのう",
      meanings: {
        ja: "天皇",
        en: "Emperor of Japan",
        zh: "天皇",
        tw: "天皇",
        ko: "일왕",
        vi: "Thiên Hoàng Nhật Bản",
        th: "จักรพรรดิญี่ปุ่น",
        my: "ဂျပန်မင်းကြီး",
        km: "ស្ដេចជប៉ុន",
      },
      furigana: [
        {
          rb: "天皇",
          rt: "てんのう",
        },
      ],
      kanjiInfo: [
        {
          char: "天",
          on: ["テン"],
          kun: ["あまつ", "あめ", "あま-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "皇",
          on: ["コウ", "オウ"],
          kun: [],
          strokes: 9,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
  ],
};
