export const n2part15 = {
  Lesson15: [
    {
      id: 701,
      kanji: "肌着",
      reading: "はだぎ",
      meanings: {
        ja: "肌着",
        en: "underwear",
        zh: "内衣",
        tw: "內衣",
        ko: "속옷",
        vi: "đồ lót",
        th: "ชุดชั้นใน",
        my: "အတွင်းခံဝတ်စုံ",
        km: "សម្លៀកបំពាក់ក្នុង",
      },
      furigana: [
        {
          rb: "肌着",
          rt: "はだぎ",
        },
      ],
      kanjiInfo: [
        {
          char: "肌",
          on: ["キ"],
          kun: ["はだ"],
          strokes: 6,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 702,
      kanji: "鉢",
      reading: "はち",
      meanings: {
        ja: "鉢",
        en: "bowl",
        zh: "钵；碗",
        tw: "鉢；碗",
        ko: "바리；그릇",
        vi: "bát/tô",
        th: "ชาม/อ่าง",
        my: "လောင်းဗင်",
        km: "ចានជ្រៅ/ប៊ូឡ",
      },
      furigana: [
        {
          rb: "鉢",
          rt: "はち",
        },
      ],
      kanjiInfo: [
        {
          char: "鉢",
          on: ["ハチ", "ハツ"],
          kun: [],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 703,
      kanji: "×",
      reading: "ばつ",
      meanings: {
        ja: "バツ（×）",
        en: "one's circumstances or condition",
        zh: "处境；情况",
        tw: "處境；情況",
        ko: "사정/형편",
        vi: "hoàn cảnh/tình trạng",
        th: "สภาพความเป็นอยู่",
        my: "အခြေအနေ",
        km: "ស្ថានភាព",
      },
      furigana: [
        {
          rb: "×",
          rt: "ばつ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 704,
      kanji: "発揮",
      reading: "はっき",
      meanings: {
        ja: "発揮",
        en: "show (of power)",
        zh: "发挥",
        tw: "發揮",
        ko: "발휘",
        vi: "phát huy",
        th: "แสดงออก",
        my: "ခွဲထုတ်ဖော်ပြ",
        km: "បង្ហាញសមត្ថភាព",
      },
      furigana: [
        {
          rb: "発揮",
          rt: "はっき",
        },
      ],
      kanjiInfo: [
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "揮",
          on: ["キ"],
          kun: ["ふる.う"],
          strokes: 12,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 705,
      kanji: "バック",
      reading: "バック",
      meanings: {
        ja: "バック",
        en: "back",
        zh: "背部；後方",
        tw: "背部；後方",
        ko: "뒤/백",
        vi: "phía sau",
        th: "ด้านหลัง",
        my: "ကျောဘက်",
        km: "ខាងក្រោយ",
      },
      furigana: [
        {
          rb: "バック",
          rt: "バック",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 706,
      kanji: "発想",
      reading: "はっそう",
      meanings: {
        ja: "発想",
        en: "idea",
        zh: "构想；点子",
        tw: "構想；點子",
        ko: "발상",
        vi: "ý tưởng",
        th: "ความคิด",
        my: "အယူအဆ",
        km: "គំនិត",
      },
      furigana: [
        {
          rb: "発想",
          rt: "はっそう",
        },
      ],
      kanjiInfo: [
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "想",
          on: ["ソウ", "ソ"],
          kun: ["おも.う"],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 707,
      kanji: "発電",
      reading: "はつでん",
      meanings: {
        ja: "発電",
        en: "generation of electricity",
        zh: "发电",
        tw: "發電",
        ko: "발전",
        vi: "phát điện",
        th: "การผลิตกระแสไฟฟ้า",
        my: "မီးဖိုဓာတ်အားထုတ်",
        km: "ផលិតអគ្គិសនី",
      },
      furigana: [
        {
          rb: "発電",
          rt: "はつでん",
        },
      ],
      kanjiInfo: [
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "電",
          on: ["デン"],
          kun: [],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 708,
      kanji: "発売",
      reading: "はつばい",
      meanings: {
        ja: "発売",
        en: "sale; release",
        zh: "发售；上市",
        tw: "發售；上市",
        ko: "발매",
        vi: "phát hành/bán ra",
        th: "วางจำหน่าย",
        my: "ရောင်းချမှု",
        km: "បញ្ចេញលក់",
      },
      furigana: [
        {
          rb: "発売",
          rt: "はつばい",
        },
      ],
      kanjiInfo: [
        {
          char: "発",
          on: ["ハツ", "ホツ"],
          kun: ["た.つ", "あば.く", "おこ.る", "つか.わす", "はな.つ"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "売",
          on: ["バイ"],
          kun: ["う.る", "う.れる"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 709,
      kanji: "話合い",
      reading: "はなしあい",
      meanings: {
        ja: "話し合い",
        en: "discussion",
        zh: "商谈；商议",
        tw: "商談；商議",
        ko: "의논/협의",
        vi: "thảo luận",
        th: "การปรึกษาหารือ",
        my: "ဆွေးနွေးမှု",
        km: "ពិភាក្សា",
      },
      furigana: [
        {
          rb: "話合い",
          rt: "はなしあい",
        },
      ],
      kanjiInfo: [
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "合",
          on: ["ゴウ", "ガッ", "カッ"],
          kun: [
            "あ.う",
            "-あ.う",
            "あ.い",
            "あい-",
            "-あ.い",
            "-あい",
            "あ.わす",
            "あ.わせる",
            "-あ.わせる",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 710,
      kanji: "花火",
      reading: "はなび",
      meanings: {
        ja: "花火",
        en: "fireworks",
        zh: "烟花",
        tw: "煙火",
        ko: "불꽃놀이",
        vi: "pháo hoa",
        th: "ดอกไม้ไฟ",
        my: "မီးပန်း",
        km: "ផ្ទុះភ្លើង",
      },
      furigana: [
        {
          rb: "花火",
          rt: "はなび",
        },
      ],
      kanjiInfo: [
        {
          char: "花",
          on: ["カ", "ケ"],
          kun: ["はな"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "火",
          on: ["カ"],
          kun: ["ひ", "-び", "ほ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 711,
      kanji: "花嫁",
      reading: "はなよめ",
      meanings: {
        ja: "花嫁",
        en: "bride",
        zh: "新娘",
        tw: "新娘",
        ko: "신부",
        vi: "cô dâu",
        th: "เจ้าสาว",
        my: "ကိုယ်ထိုက်မင်းသမီး",
        km: "កូនភ្លោះស្រី(ក្ដី ព្រះវស្សា) / កូនក្រមុំ",
      },
      furigana: [
        {
          rb: "花嫁",
          rt: "はなよめ",
        },
      ],
      kanjiInfo: [
        {
          char: "花",
          on: ["カ", "ケ"],
          kun: ["はな"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "嫁",
          on: ["カ"],
          kun: ["よめ", "とつ.ぐ", "い.く", "ゆ.く"],
          strokes: 13,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 712,
      kanji: "破片",
      reading: "はへん",
      meanings: {
        ja: "破片",
        en: "fragment",
        zh: "碎片",
        tw: "碎片",
        ko: "파편",
        vi: "mảnh vỡ",
        th: "เศษชิ้นส่วน",
        my: "အလျှာ",
        km: "បំណែក",
      },
      furigana: [
        {
          rb: "破片",
          rt: "はへん",
        },
      ],
      kanjiInfo: [
        {
          char: "破",
          on: ["ハ"],
          kun: ["やぶ.る", "やぶ.れる", "わ.れる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "片",
          on: ["ヘン"],
          kun: ["かた-", "かた"],
          strokes: 4,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 713,
      kanji: "歯磨き",
      reading: "はみがき",
      meanings: {
        ja: "歯磨き",
        en: "dental brushing; toothpaste",
        zh: "刷牙；牙膏",
        tw: "刷牙；牙膏",
        ko: "양치질; 치약",
        vi: "đánh răng; kem đánh răng",
        th: "การแปรงฟัน; ยาสีฟัน",
        my: "သွားတိုက်; သွားပိန်း",
        km: "ដុសធ្មេញ; ថ្នាំដុសធ្មេញ",
      },
      furigana: [
        {
          rb: "歯磨き",
          rt: "はみがき",
        },
      ],
      kanjiInfo: [
        {
          char: "歯",
          on: ["シ"],
          kun: ["よわい", "は", "よわ.い", "よわい.する"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "磨",
          on: ["マ"],
          kun: ["みが.く", "す.る"],
          strokes: 16,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 714,
      kanji: "早口",
      reading: "はやくち",
      meanings: {
        ja: "早口",
        en: "fast-talking",
        zh: "说话快",
        tw: "說話快",
        ko: "말이 빠름",
        vi: "nói nhanh",
        th: "พูดเร็ว",
        my: "စကားလွှတ်လျှင်မြန်",
        km: "និយាយលឿន",
      },
      furigana: [
        {
          rb: "早口",
          rt: "はやくち",
        },
      ],
      kanjiInfo: [
        {
          char: "早",
          on: ["ソウ", "サッ"],
          kun: ["はや.い", "はや", "はや-", "はや.まる", "はや.める", "さ-"],
          strokes: 6,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
        {
          char: "口",
          on: ["コウ", "ク"],
          kun: ["くち"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 715,
      kanji: "針金",
      reading: "はりがね",
      meanings: {
        ja: "針金",
        en: "wire",
        zh: "金属丝",
        tw: "金屬線",
        ko: "철사",
        vi: "dây kẽm",
        th: "ลวด",
        my: "ချည်ကြိုးသံ",
        km: "ខ្សែដែក",
      },
      furigana: [
        {
          rb: "針金",
          rt: "はりがね",
        },
      ],
      kanjiInfo: [
        {
          char: "針",
          on: ["シン"],
          kun: ["はり"],
          strokes: 10,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "金",
          on: ["キン", "コン", "ゴン"],
          kun: ["かね", "かな-", "-がね"],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 716,
      kanji: "反映",
      reading: "はんえい",
      meanings: {
        ja: "反映",
        en: "reflection (of light)",
        zh: "反映",
        tw: "反映",
        ko: "반영",
        vi: "phản chiếu/phan ánh",
        th: "การสะท้อน",
        my: "တုန့်ပြန်တောက်ပ",
        km: "ឆ្លុះបញ្ចាំង",
      },
      furigana: [
        {
          rb: "反映",
          rt: "はんえい",
        },
      ],
      kanjiInfo: [
        {
          char: "反",
          on: ["ハン", "ホン", "タン", "ホ"],
          kun: ["そ.る", "そ.らす", "かえ.す", "かえ.る", "-かえ.る"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "映",
          on: ["エイ"],
          kun: ["うつ.る", "うつ.す", "は.える", "-ば.え"],
          strokes: 9,
          grade: 6,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 717,
      kanji: "半径",
      reading: "はんけい",
      meanings: {
        ja: "半径",
        en: "radius",
        zh: "半径",
        tw: "半徑",
        ko: "반지름",
        vi: "bán kính",
        th: "รัศมี",
        my: "အချင်းဝက်",
        km: "កាំ",
      },
      furigana: [
        {
          rb: "半径",
          rt: "はんけい",
        },
      ],
      kanjiInfo: [
        {
          char: "半",
          on: ["ハン"],
          kun: ["なか.ば"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "径",
          on: ["ケイ"],
          kun: ["みち", "こみち", "さしわたし", "ただちに"],
          strokes: 8,
          grade: 4,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 718,
      kanji: "判子",
      reading: "はんこ",
      meanings: {
        ja: "判子",
        en: "seal (used in lieu of a signature)",
        zh: "印章",
        tw: "印章",
        ko: "도장",
        vi: "con dấu",
        th: "ตราประทับ",
        my: "တံဆိပ်ထိုး",
        km: "ត្រា",
      },
      furigana: [
        {
          rb: "判子",
          rt: "はんこ",
        },
      ],
      kanjiInfo: [
        {
          char: "判",
          on: ["ハン", "バン"],
          kun: ["わか.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 719,
      kanji: "判事",
      reading: "はんじ",
      meanings: {
        ja: "判事",
        en: "judge",
        zh: "法官",
        tw: "法官",
        ko: "판사",
        vi: "thẩm phán",
        th: "ผู้พิพากษา",
        my: "တရားသူကြီး",
        km: "ចៅក្រម",
      },
      furigana: [
        {
          rb: "判事",
          rt: "はんじ",
        },
      ],
      kanjiInfo: [
        {
          char: "判",
          on: ["ハン", "バン"],
          kun: ["わか.る"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 720,
      kanji: "番地",
      reading: "ばんち",
      meanings: {
        ja: "番地",
        en: "house number",
        zh: "门牌号",
        tw: "門牌號",
        ko: "번지",
        vi: "số nhà",
        th: "บ้านเลขที่",
        my: "အိမ်နံပါတ်",
        km: "លេខផ្ទះ",
      },
      furigana: [
        {
          rb: "番地",
          rt: "ばんち",
        },
      ],
      kanjiInfo: [
        {
          char: "番",
          on: ["バン"],
          kun: ["つが.い"],
          strokes: 12,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "地",
          on: ["チ", "ジ"],
          kun: [],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 721,
      kanji: "パンツ",
      reading: "パンツ",
      meanings: {
        ja: "パンツ",
        en: "underpants",
        zh: "内裤",
        tw: "內褲",
        ko: "팬티",
        vi: "quần lót",
        th: "กางเกงใน",
        my: "ဘောင်းဘီအတွင်း",
        km: "ខោក្នុង",
      },
      furigana: [
        {
          rb: "パンツ",
          rt: "パンツ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 722,
      kanji: "バンド",
      reading: "バンド",
      meanings: {
        ja: "バンド",
        en: "band (group of musicians)",
        zh: "乐队",
        tw: "樂隊",
        ko: "밴드",
        vi: "ban nhạc",
        th: "วงดนตรี",
        my: "တီးဝိုင်း",
        km: "ក្រុមតន្រ្តី",
      },
      furigana: [
        {
          rb: "バンド",
          rt: "バンド",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 723,
      kanji: "半島",
      reading: "はんとう",
      meanings: {
        ja: "半島",
        en: "peninsula",
        zh: "半岛",
        tw: "半島",
        ko: "반도",
        vi: "bán đảo",
        th: "คาบสมุทร",
        my: "ကမ်းပါးပြည်ထောင်",
        km: "ប្រទេសកោះពាក់កណ្តាល",
      },
      furigana: [
        {
          rb: "半島",
          rt: "はんとう",
        },
      ],
      kanjiInfo: [
        {
          char: "半",
          on: ["ハン"],
          kun: ["なか.ば"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "島",
          on: ["トウ"],
          kun: ["しま"],
          strokes: 10,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 724,
      kanji: "ハンドル",
      reading: "ハンドル",
      meanings: {
        ja: "ハンドル",
        en: "handle",
        zh: "把手；方向盘",
        tw: "把手；方向盤",
        ko: "손잡이; 핸들",
        vi: "tay cầm; vô lăng",
        th: "ที่จับ; พวงมาลัย",
        my: "ကိုင်ကွက်; ဟန်ဒယ်",
        km: "ដាប់ប៊្លូ; ចង្កូត",
      },
      furigana: [
        {
          rb: "ハンドル",
          rt: "ハンドル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 725,
      kanji: "日当たり",
      reading: "ひあたり",
      meanings: {
        ja: "日当たり",
        en: "exposure to the sun",
        zh: "日照",
        tw: "日照",
        ko: "채광",
        vi: "hướng nắng/ánh nắng rọi",
        th: "แสงแดดส่องถึง",
        my: "နေထိုးခြင်း",
        km: "ពន្លឺថ្ងៃចូល",
      },
      furigana: [
        {
          rb: "日当たり",
          rt: "ひあたり",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "当",
          on: ["トウ"],
          kun: [
            "あ.たる",
            "あ.たり",
            "あ.てる",
            "あ.て",
            "まさ.に",
            "まさ.にべし",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 726,
      kanji: "日帰り",
      reading: "ひがえり",
      meanings: {
        ja: "日帰り",
        en: "day trip",
        zh: "当天往返",
        tw: "當天來回",
        ko: "당일치기",
        vi: "đi về trong ngày",
        th: "ไปกลับวันเดียว",
        my: "တနေ့ခရီး",
        km: "ទេសចរណ៍មួយថ្ងៃ",
      },
      furigana: [
        {
          rb: "日帰り",
          rt: "ひがえり",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "帰",
          on: ["キ"],
          kun: ["かえ.る", "かえ.す", "おく.る", "とつ.ぐ"],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 727,
      kanji: "日陰",
      reading: "ひかげ",
      meanings: {
        ja: "日陰",
        en: "shade",
        zh: "阴处",
        tw: "陰處",
        ko: "그늘",
        vi: "bóng râm",
        th: "ร่มเงา",
        my: "နေအောက်",
        km: "ស្រមោល",
      },
      furigana: [
        {
          rb: "日陰",
          rt: "ひかげ",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "陰",
          on: ["イン"],
          kun: ["かげ", "かげ.る"],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 728,
      kanji: "引算",
      reading: "ひきざん",
      meanings: {
        ja: "引き算",
        en: "subtraction",
        zh: "减法",
        tw: "減法",
        ko: "뺄셈",
        vi: "phép trừ",
        th: "การลบ (คณิต)",
        my: "နုတ်ခြင်း",
        km: "សកម្មភាពដក",
      },
      furigana: [
        {
          rb: "引算",
          rt: "ひきざん",
        },
      ],
      kanjiInfo: [
        {
          char: "引",
          on: ["イン"],
          kun: ["ひ.く", "ひ.ける"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "算",
          on: ["サン"],
          kun: ["そろ"],
          strokes: 14,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 729,
      kanji: "引分け",
      reading: "ひきわけ",
      meanings: {
        ja: "引き分け",
        en: "draw (in competition)",
        zh: "平局",
        tw: "和局",
        ko: "무승부",
        vi: "hòa (tỉ số)",
        th: "เสมอ",
        my: "ပြိုင်ပွဲစနစ်တူ",
        km: "ស្មើ",
      },
      furigana: [
        {
          rb: "引分け",
          rt: "ひきわけ",
        },
      ],
      kanjiInfo: [
        {
          char: "引",
          on: ["イン"],
          kun: ["ひ.く", "ひ.ける"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 730,
      kanji: "陽射",
      reading: "ひざし",
      meanings: {
        ja: "日差し（陽射し）",
        en: "sunlight",
        zh: "阳光",
        tw: "陽光",
        ko: "햇빛",
        vi: "ánh nắng",
        th: "แสงแดด",
        my: "နေအလင်း",
        km: "ពន្លឺថ្ងៃ",
      },
      furigana: [
        {
          rb: "陽射",
          rt: "ひざし",
        },
      ],
      kanjiInfo: [
        {
          char: "陽",
          on: ["ヨウ"],
          kun: ["ひ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "射",
          on: ["シャ"],
          kun: ["い.る", "さ.す", "う.つ"],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 731,
      kanji: "肘",
      reading: "ひじ",
      meanings: {
        ja: "肘",
        en: "elbow",
        zh: "胳膊肘",
        tw: "手肘",
        ko: "팔꿈치",
        vi: "khuỷu tay",
        th: "ศอก",
        my: "တံတောင်",
        km: "កែងដៃ",
      },
      furigana: [
        {
          rb: "肘",
          rt: "ひじ",
        },
      ],
      kanjiInfo: [
        {
          char: "肘",
          on: ["チュウ"],
          kun: ["ひじ"],
          strokes: 7,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 732,
      kanji: "ピストル",
      reading: "ピストル",
      meanings: {
        ja: "ピストル",
        en: "pistol",
        zh: "手枪",
        tw: "手槍",
        ko: "권총",
        vi: "súng lục",
        th: "ปืนพก",
        my: "ပြစ်စတိုး",
        km: "កាំភ្លើងខ្លី",
      },
      furigana: [
        {
          rb: "ピストル",
          rt: "ピストル",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 733,
      kanji: "ビタミン",
      reading: "ビタミン",
      meanings: {
        ja: "ビタミン",
        en: "vitamin",
        zh: "维生素",
        tw: "維他命",
        ko: "비타민",
        vi: "vitamin",
        th: "วิตามิน",
        my: "ဗီတာမင်",
        km: "វីតាមីន",
      },
      furigana: [
        {
          rb: "ビタミン",
          rt: "ビタミン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 734,
      kanji: "筆記",
      reading: "ひっき",
      meanings: {
        ja: "筆記",
        en: "(taking) notes",
        zh: "记笔记",
        tw: "記筆記",
        ko: "필기",
        vi: "ghi chép",
        th: "การจดบันทึก",
        my: "မှတ်စုရေး",
        km: "កំណត់សម្គាល់",
      },
      furigana: [
        {
          rb: "筆記",
          rt: "ひっき",
        },
      ],
      kanjiInfo: [
        {
          char: "筆",
          on: ["ヒツ"],
          kun: ["ふで"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "記",
          on: ["キ"],
          kun: ["しる.す"],
          strokes: 10,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 735,
      kanji: "筆者",
      reading: "ひっしゃ",
      meanings: {
        ja: "筆者",
        en: "writer",
        zh: "笔者；作者",
        tw: "筆者；作者",
        ko: "필자",
        vi: "tác giả (người viết)",
        th: "ผู้เขียน",
        my: "ရေးသားသူ",
        km: "អ្នកនិពន្ធ",
      },
      furigana: [
        {
          rb: "筆者",
          rt: "ひっしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "筆",
          on: ["ヒツ"],
          kun: ["ふで"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "者",
          on: ["シャ"],
          kun: ["もの"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 736,
      kanji: "必需品",
      reading: "ひつじゅひん",
      meanings: {
        ja: "必需品",
        en: "necessities",
        zh: "必需品",
        tw: "必需品",
        ko: "필수품",
        vi: "vật thiết yếu",
        th: "ของจำเป็น",
        my: "လိုအပ်သည့်ပစ္စည်း",
        km: "វត្ថុចាំបាច់",
      },
      furigana: [
        {
          rb: "必需品",
          rt: "ひつじゅひん",
        },
      ],
      kanjiInfo: [
        {
          char: "必",
          on: ["ヒツ"],
          kun: ["かなら.ず"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "需",
          on: ["ジュ"],
          kun: [],
          strokes: 14,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 737,
      kanji: "人差指",
      reading: "ひとさしゆび",
      meanings: {
        ja: "人差し指",
        en: "index finger",
        zh: "食指",
        tw: "食指",
        ko: "집게손가락",
        vi: "ngón trỏ",
        th: "นิ้วชี้",
        my: "လက်ချောင်းညွှန်",
        km: "ម្រាមដៃសញ្ញា",
      },
      furigana: [
        {
          rb: "人差指",
          rt: "ひとさしゆび",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "差",
          on: ["サ"],
          kun: ["さ.す", "さ.し"],
          strokes: 10,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 738,
      kanji: "一通り",
      reading: "ひととおり",
      meanings: {
        ja: "一通り",
        en: "generally; more or less",
        zh: "大致；大体",
        tw: "大致；大體",
        ko: "대강; 대체로",
        vi: "đại khái; nhìn chung",
        th: "โดยรวม; คร่าว ๆ",
        my: "ဆောင်ရွက်ရုံသာ",
        km: "ទូទៅៗ",
      },
      furigana: [
        {
          rb: "一通り",
          rt: "ひととおり",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 739,
      kanji: "人通り",
      reading: "ひとどおり",
      meanings: {
        ja: "人通り",
        en: "pedestrian traffic",
        zh: "行人往来",
        tw: "行人往來",
        ko: "유동인구",
        vi: "lượng người qua lại",
        th: "คนสัญจรไปมา",
        my: "လူသွားလာမှု",
        km: "ចរាចររបស់អ្នកដឹកជញ្ជូន",
      },
      furigana: [
        {
          rb: "人通り",
          rt: "ひとどおり",
        },
      ],
      kanjiInfo: [
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "通",
          on: ["ツウ", "ツ"],
          kun: [
            "とお.る",
            "とお.り",
            "-とお.り",
            "-どお.り",
            "とお.す",
            "とお.し",
            "-どお.し",
            "かよ.う",
          ],
          strokes: 10,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 740,
      kanji: "瞳",
      reading: "ひとみ",
      meanings: {
        ja: "瞳",
        en: "pupil (of the eye)",
        zh: "瞳孔",
        tw: "瞳孔",
        ko: "동공",
        vi: "đồng tử",
        th: "รูม่านตา",
        my: "မျက်ကာတွင်း",
        km: "រន្ធភ្នែក",
      },
      furigana: [
        {
          rb: "瞳",
          rt: "ひとみ",
        },
      ],
      kanjiInfo: [
        {
          char: "瞳",
          on: ["ドウ", "トウ"],
          kun: ["ひとみ"],
          strokes: 17,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 741,
      kanji: "一休み",
      reading: "ひとやすみ",
      meanings: {
        ja: "一休み",
        en: "(short) rest",
        zh: "稍作休息",
        tw: "稍作休息",
        ko: "한숨 돌림",
        vi: "nghỉ một lát",
        th: "พักสั้น ๆ",
        my: "နားခဏယူ",
        km: "សម្រាកបន្តិច",
      },
      furigana: [
        {
          rb: "一休み",
          rt: "ひとやすみ",
        },
      ],
      kanjiInfo: [
        {
          char: "一",
          on: ["イチ", "イツ"],
          kun: ["ひと-", "ひと.つ"],
          strokes: 1,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "休",
          on: ["キュウ"],
          kun: ["やす.む", "やす.まる", "やす.める"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 742,
      kanji: "独り言",
      reading: "ひとりごと",
      meanings: {
        ja: "独り言",
        en: "soliloquy; talking to oneself",
        zh: "自言自语",
        tw: "自言自語",
        ko: "혼잣말",
        vi: "lẩm bẩm một mình",
        th: "พึมพำกับตัวเอง",
        my: "ကိုယ်တိုင်ပြောခြင်း",
        km: "និយាយម្នាក់ឯង",
      },
      furigana: [
        {
          rb: "独り言",
          rt: "ひとりごと",
        },
      ],
      kanjiInfo: [
        {
          char: "独",
          on: ["ドク", "トク"],
          kun: ["ひと.り"],
          strokes: 9,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "言",
          on: ["ゲン", "ゴン"],
          kun: ["い.う", "こと"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 743,
      kanji: "ビニール",
      reading: "ビニール",
      meanings: {
        ja: "ビニール",
        en: "vinyl",
        zh: "乙烯基；塑料",
        tw: "乙烯基；塑膠",
        ko: "비닐",
        vi: "ni-lông/vinyl",
        th: "ไวนิล",
        my: "ဗီနီးလ်",
        km: "វីនីល",
      },
      furigana: [
        {
          rb: "ビニール",
          rt: "ビニール",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 744,
      kanji: "皮肉",
      reading: "ひにく",
      meanings: {
        ja: "皮肉",
        en: "irony; sarcasm",
        zh: "讽刺；挖苦",
        tw: "諷刺；挖苦",
        ko: "빈정거림/풍자",
        vi: "mỉa mai/châm biếm",
        th: "ประชดประชัน",
        my: "ရယ်စရာထင်စေသောစကား",
        km: "ប្រមាថ/សម្ដីច្រឡំ",
      },
      furigana: [
        {
          rb: "皮肉",
          rt: "ひにく",
        },
      ],
      kanjiInfo: [
        {
          char: "皮",
          on: ["ヒ"],
          kun: ["かわ"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "肉",
          on: ["ニク"],
          kun: ["しし"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 745,
      kanji: "日日",
      reading: "ひにち",
      meanings: {
        ja: "日にち",
        en: "date (of a planned event)",
        zh: "日期",
        tw: "日期",
        ko: "날짜",
        vi: "ngày (đã định)",
        th: "วันที่ (นัดหมาย)",
        my: "ရက်စွဲ",
        km: "កាលបរិច្ឆេទ",
      },
      furigana: [
        {
          rb: "日日",
          rt: "ひにち",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 746,
      kanji: "日の入り",
      reading: "ひのいり",
      meanings: {
        ja: "日の入り",
        en: "sunset",
        zh: "日落",
        tw: "日落",
        ko: "일몰",
        vi: "hoàng hôn",
        th: "พระอาทิตย์ตก",
        my: "နေဝင်ရာ",
        km: "អាស្តមិញ",
      },
      furigana: [
        {
          rb: "日の入り",
          rt: "ひのいり",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 747,
      kanji: "日の出",
      reading: "ひので",
      meanings: {
        ja: "日の出",
        en: "sunrise",
        zh: "日出",
        tw: "日出",
        ko: "일출",
        vi: "bình minh",
        th: "พระอาทิตย์ขึ้น",
        my: "နေထွက်",
        km: "រះព្រះអាទិត្យ",
      },
      furigana: [
        {
          rb: "日の出",
          rt: "ひので",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "出",
          on: ["シュツ", "スイ"],
          kun: ["で.る", "-で", "だ.す", "-だ.す", "い.でる", "い.だす"],
          strokes: 5,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 748,
      kanji: "響き",
      reading: "ひびき",
      meanings: {
        ja: "響き",
        en: "echo; resonance",
        zh: "回声；共鸣",
        tw: "回聲；共鳴",
        ko: "울림; 메아리",
        vi: "tiếng vang; cộng hưởng",
        th: "เสียงสะท้อน",
        my: "အသံပြန်",
        km: "សំឡេងរំញ័រ/ត្រឡប់",
      },
      furigana: [
        {
          rb: "響き",
          rt: "ひびき",
        },
      ],
      kanjiInfo: [
        {
          char: "響",
          on: ["キョウ"],
          kun: ["ひび.く"],
          strokes: 20,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 749,
      kanji: "皮膚",
      reading: "ひふ",
      meanings: {
        ja: "皮膚",
        en: "skin",
        zh: "皮肤",
        tw: "皮膚",
        ko: "피부",
        vi: "da (cơ thể)",
        th: "ผิวหนัง",
        my: "အသားအရေ",
        km: "ស្បែក",
      },
      furigana: [
        {
          rb: "皮膚",
          rt: "ひふ",
        },
      ],
      kanjiInfo: [
        {
          char: "皮",
          on: ["ヒ"],
          kun: ["かわ"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "膚",
          on: ["フ"],
          kun: ["はだ"],
          strokes: 15,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 750,
      kanji: "美容",
      reading: "びよう",
      meanings: {
        ja: "美容",
        en: "beauty (care)",
        zh: "美容",
        tw: "美容",
        ko: "미용",
        vi: "làm đẹp",
        th: "ความงาม",
        my: "အလှပြင်",
        km: "សម្រស់",
      },
      furigana: [
        {
          rb: "美容",
          rt: "びよう",
        },
      ],
      kanjiInfo: [
        {
          char: "美",
          on: ["ビ", "ミ"],
          kun: ["うつく.しい"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "容",
          on: ["ヨウ"],
          kun: ["い.れる"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
