export const n2part14 = {
  Lesson14: [
    {
      id: 651,
      kanji: "灯油",
      reading: "とうゆ",
      meanings: {
        ja: "灯油",
        en: "kerosene",
        zh: "煤油",
        tw: "煤油",
        ko: "등유",
        vi: "dầu hỏa",
        th: "น้ำมันก๊าด",
        my: "မီးဆီ",
        km: "ប្រេងកាត",
      },
      furigana: [
        {
          rb: "灯油",
          rt: "とうゆ",
        },
      ],
      kanjiInfo: [
        {
          char: "灯",
          on: ["トウ"],
          kun: ["ひ", "ほ-", "ともしび", "とも.す", "あかり"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "油",
          on: ["ユ", "ユウ"],
          kun: ["あぶら"],
          strokes: 8,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 652,
      kanji: "童話",
      reading: "どうわ",
      meanings: {
        ja: "童話",
        en: "children's story",
        zh: "童话",
        tw: "童話",
        ko: "동화",
        vi: "truyện thiếu nhi",
        th: "นิทานเด็ก",
        my: "ကလေးပုံပြင်",
        km: "រឿងនិទានកុមារ",
      },
      furigana: [
        {
          rb: "童話",
          rt: "どうわ",
        },
      ],
      kanjiInfo: [
        {
          char: "童",
          on: ["ドウ"],
          kun: ["わらべ"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 653,
      kanji: "特色",
      reading: "とくしょく",
      meanings: {
        ja: "特色",
        en: "characteristic",
        zh: "特色",
        tw: "特色",
        ko: "특색",
        vi: "đặc sắc",
        th: "ลักษณะพิเศษ",
        my: "ထူးခြားမှု",
        km: "លក្ខណៈពិសេស",
      },
      furigana: [
        {
          rb: "特色",
          rt: "とくしょく",
        },
      ],
      kanjiInfo: [
        {
          char: "特",
          on: ["トク"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "色",
          on: ["ショク", "シキ"],
          kun: ["いろ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 654,
      kanji: "特売",
      reading: "とくばい",
      meanings: {
        ja: "特売",
        en: "special sale",
        zh: "特卖",
        tw: "特賣",
        ko: "특매",
        vi: "bán đặc biệt",
        th: "ลดราคาพิเศษ",
        my: "အထူးစျေးချိုသာ",
        km: "លក់ពិសេស",
      },
      furigana: [
        {
          rb: "特売",
          rt: "とくばい",
        },
      ],
      kanjiInfo: [
        {
          char: "特",
          on: ["トク"],
          kun: [],
          strokes: 10,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "売",
          on: ["バイ"],
          kun: ["う.る", "う.れる"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 655,
      kanji: "床の間",
      reading: "とこのま",
      meanings: {
        ja: "床の間",
        en: "tokonoma (alcove)",
        zh: "床间",
        tw: "床間",
        ko: "도코노마",
        vi: "hốc tường trang trí",
        th: "โทโคโนมา",
        my: "အလှဆင်အောက်ခြင်း",
        km: "ជ្រុងតុគូ",
      },
      furigana: [
        {
          rb: "床の間",
          rt: "とこのま",
        },
      ],
      kanjiInfo: [
        {
          char: "床",
          on: ["ショウ"],
          kun: ["とこ", "ゆか"],
          strokes: 7,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 656,
      kanji: "都心",
      reading: "としん",
      meanings: {
        ja: "都心",
        en: "city centre (esp. of Tokyo)",
        zh: "市中心",
        tw: "市中心",
        ko: "도심",
        vi: "trung tâm thành phố",
        th: "ใจกลางเมือง",
        my: "မြို့မဗဟို",
        km: "កណ្តាលទីក្រុង",
      },
      furigana: [
        {
          rb: "都心",
          rt: "としん",
        },
      ],
      kanjiInfo: [
        {
          char: "都",
          on: ["ト", "ツ"],
          kun: ["みやこ"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "心",
          on: ["シン"],
          kun: ["こころ", "-ごころ"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 657,
      kanji: "戸棚",
      reading: "とだな",
      meanings: {
        ja: "戸棚",
        en: "cupboard",
        zh: "橱柜",
        tw: "櫥櫃",
        ko: "찬장",
        vi: "tủ bếp",
        th: "ตู้เก็บของ",
        my: "အဝတ်အထည်သိုလှောင်ခန်း",
        km: "ទូឥវ៉ាន់",
      },
      furigana: [
        {
          rb: "戸棚",
          rt: "とだな",
        },
      ],
      kanjiInfo: [
        {
          char: "戸",
          on: ["コ"],
          kun: ["と"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "棚",
          on: ["ホウ"],
          kun: ["たな", "-だな"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 658,
      kanji: "丼",
      reading: "どんぶり",
      meanings: {
        ja: "丼",
        en: "porcelain bowl",
        zh: "大碗",
        tw: "大碗",
        ko: "덮밥그릇",
        vi: "bát tô",
        th: "ชามใบใหญ่",
        my: "ခွက်တစ်အိုးကြီး",
        km: "ចានជ្រៅ",
      },
      furigana: [
        {
          rb: "丼",
          rt: "どんぶり",
        },
      ],
      kanjiInfo: [
        {
          char: "丼",
          on: ["トン", "タン", "ショウ", "セイ"],
          kun: ["どんぶり"],
          strokes: 5,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 659,
      kanji: "内科",
      reading: "ないか",
      meanings: {
        ja: "内科",
        en: "internal medicine",
        zh: "内科",
        tw: "內科",
        ko: "내과",
        vi: "nội khoa",
        th: "อายุรกรรม",
        my: "အတွင်းရောဂါပညာ",
        km: "វេជ្ជសាស្ត្រខាងក្នុង",
      },
      furigana: [
        {
          rb: "内科",
          rt: "ないか",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 660,
      kanji: "内線",
      reading: "ないせん",
      meanings: {
        ja: "内線",
        en: "phone extension",
        zh: "内线",
        tw: "內線",
        ko: "내선",
        vi: "máy nhánh",
        th: "เบอร์ภายใน",
        my: "အတွင်းဖုန်းမှတ်တမ်း",
        km: "លេខផ្ទៃក្នុង",
      },
      furigana: [
        {
          rb: "内線",
          rt: "ないせん",
        },
      ],
      kanjiInfo: [
        {
          char: "内",
          on: ["ナイ", "ダイ"],
          kun: ["うち"],
          strokes: 4,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
        {
          char: "線",
          on: ["セン"],
          kun: ["すじ"],
          strokes: 15,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 661,
      kanji: "ナイロン",
      reading: "ナイロン",
      meanings: {
        ja: "ナイロン",
        en: "nylon",
        zh: "尼龙",
        tw: "尼龍",
        ko: "나일론",
        vi: "ni lông",
        th: "ไนลอน",
        my: "နိုင်လြန်း",
        km: "នាយឡុង",
      },
      furigana: [
        {
          rb: "ナイロン",
          rt: "ナイロン",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 662,
      kanji: "仲直り",
      reading: "なかなおり",
      meanings: {
        ja: "仲直り",
        en: "reconciliation",
        zh: "和好",
        tw: "和好",
        ko: "화해",
        vi: "làm hòa",
        th: "คืนดี",
        my: "ပြန်လည်ချစ်ကြည်",
        km: "សម្រុះសម្រួល",
      },
      furigana: [
        {
          rb: "仲直り",
          rt: "なかなおり",
        },
      ],
      kanjiInfo: [
        {
          char: "仲",
          on: ["チュウ"],
          kun: ["なか"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "直",
          on: ["チョク", "ジキ", "ジカ"],
          kun: [
            "ただ.ちに",
            "なお.す",
            "-なお.す",
            "なお.る",
            "なお.き",
            "す.ぐ",
          ],
          strokes: 8,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 663,
      kanji: "中指",
      reading: "なかゆび",
      meanings: {
        ja: "中指",
        en: "middle finger",
        zh: "中指",
        tw: "中指",
        ko: "중지",
        vi: "ngón giữa",
        th: "นิ้วกลาง",
        my: "လက်ချောင်းအလယ်",
        km: "ម្រាមដៃកណ្ដាល",
      },
      furigana: [
        {
          rb: "中指",
          rt: "なかゆび",
        },
      ],
      kanjiInfo: [
        {
          char: "中",
          on: ["チュウ"],
          kun: ["なか", "うち", "あた.る"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "指",
          on: ["シ"],
          kun: ["ゆび", "さ.す", "-さ.し"],
          strokes: 9,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 664,
      kanji: "仲良し",
      reading: "なかよし",
      meanings: {
        ja: "仲良し",
        en: "close friendship",
        zh: "好朋友",
        tw: "好朋友",
        ko: "절친",
        vi: "bạn thân",
        th: "เพื่อนสนิท",
        my: "မိတ်ဖက်နီးစပ်",
        km: "មិត្តភក្តិជិតស្និទ្ធ",
      },
      furigana: [
        {
          rb: "仲良し",
          rt: "なかよし",
        },
      ],
      kanjiInfo: [
        {
          char: "仲",
          on: ["チュウ"],
          kun: ["なか"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "良",
          on: ["リョウ"],
          kun: ["よ.い", "-よ.い", "い.い", "-い.い"],
          strokes: 7,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 665,
      kanji: "謎謎",
      reading: "なぞなぞ",
      meanings: {
        ja: "謎謎",
        en: "riddle",
        zh: "谜语",
        tw: "謎語",
        ko: "수수께끼",
        vi: "câu đố",
        th: "ปริศนา",
        my: "မေးပဟေဠိ",
        km: "ល្បែងសួរចម្លើយ",
      },
      furigana: [
        {
          rb: "謎謎",
          rt: "なぞなぞ",
        },
      ],
      kanjiInfo: [
        {
          char: "謎",
          on: ["メイ", "ベイ"],
          kun: ["なぞ"],
          strokes: 16,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
        {
          char: "謎",
          on: ["メイ", "ベイ"],
          kun: ["なぞ"],
          strokes: 16,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 666,
      kanji: "何分",
      reading: "なにぶん",
      meanings: {
        ja: "何分",
        en: "some",
        zh: "多少",
        tw: "多少",
        ko: "아무쪼록",
        vi: "dù sao",
        th: "อย่างไรก็ตาม",
        my: "အချို့",
        km: "បន្តិច",
      },
      furigana: [
        {
          rb: "何分",
          rt: "なにぶん",
        },
      ],
      kanjiInfo: [
        {
          char: "何",
          on: ["カ"],
          kun: ["なに", "なん", "なに-", "なん-"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "分",
          on: ["ブン", "フン", "ブ"],
          kun: ["わ.ける", "わ.け", "わ.かれる", "わ.かる", "わ.かつ"],
          strokes: 4,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 667,
      kanji: "並木",
      reading: "なみき",
      meanings: {
        ja: "並木",
        en: "roadside trees",
        zh: "林荫道",
        tw: "林蔭道",
        ko: "가로수",
        vi: "hàng cây ven đường",
        th: "ต้นไม้ริมถนน",
        my: "လမ်းဘေးသစ်",
        km: "ដើមឈើតាមដងផ្លូវ",
      },
      furigana: [
        {
          rb: "並木",
          rt: "なみき",
        },
      ],
      kanjiInfo: [
        {
          char: "並",
          on: ["ヘイ", "ホウ"],
          kun: ["な.み", "なみ", "なら.べる", "なら.ぶ", "なら.びに"],
          strokes: 8,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "木",
          on: ["ボク", "モク"],
          kun: ["き", "こ-"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 668,
      kanji: "南極",
      reading: "なんきょく",
      meanings: {
        ja: "南極",
        en: "South Pole",
        zh: "南极",
        tw: "南極",
        ko: "남극",
        vi: "Nam Cực",
        th: "ขั้วโลกใต้",
        my: "တောင်ဘက်အအေး",
        km: "ប៉ូលខាងត្បូង",
      },
      furigana: [
        {
          rb: "南極",
          rt: "なんきょく",
        },
      ],
      kanjiInfo: [
        {
          char: "南",
          on: ["ナン", "ナ"],
          kun: ["みなみ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "極",
          on: ["キョク", "ゴク"],
          kun: [
            "きわ.める",
            "きわ.まる",
            "きわ.まり",
            "きわ.み",
            "き.める",
            "-ぎ.め",
            "き.まる",
          ],
          strokes: 12,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 669,
      kanji: "ナンバー",
      reading: "ナンバー",
      meanings: {
        ja: "ナンバー",
        en: "number",
        zh: "号码",
        tw: "號碼",
        ko: "넘버",
        vi: "số",
        th: "หมายเลข",
        my: "နံပါတ်",
        km: "លេខ",
      },
      furigana: [
        {
          rb: "ナンバー",
          rt: "ナンバー",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 670,
      kanji: "南米",
      reading: "なんべい",
      meanings: {
        ja: "南米",
        en: "South America",
        zh: "南美洲",
        tw: "南美洲",
        ko: "남미",
        vi: "Nam Mỹ",
        th: "อเมริกาใต้",
        my: "တောင်အမေရိက",
        km: "អាមេរិកខាងត្បូង",
      },
      furigana: [
        {
          rb: "南米",
          rt: "なんべい",
        },
      ],
      kanjiInfo: [
        {
          char: "南",
          on: ["ナン", "ナ"],
          kun: ["みなみ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "米",
          on: ["ベイ", "マイ", "メエトル"],
          kun: ["こめ", "よね"],
          strokes: 6,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 671,
      kanji: "南北",
      reading: "なんぼく",
      meanings: {
        ja: "南北",
        en: "north and south",
        zh: "南北",
        tw: "南北",
        ko: "남북",
        vi: "Nam và Bắc",
        th: "เหนือและใต้",
        my: "တောင်မြောက်",
        km: "ជើង និង ត្បូង",
      },
      furigana: [
        {
          rb: "南北",
          rt: "なんぼく",
        },
      ],
      kanjiInfo: [
        {
          char: "南",
          on: ["ナン", "ナ"],
          kun: ["みなみ"],
          strokes: 9,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "北",
          on: ["ホク"],
          kun: ["きた"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 672,
      kanji: "日時",
      reading: "にちじ",
      meanings: {
        ja: "日時",
        en: "date and time (of a meeting)",
        zh: "日期和时间",
        tw: "日期和時間",
        ko: "일시",
        vi: "ngày giờ",
        th: "วันและเวลา",
        my: "နေ့ရက်နှင့်အချိန်",
        km: "កាលបរិច្ឆេទ និងម៉ោង",
      },
      furigana: [
        {
          rb: "日時",
          rt: "にちじ",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "時",
          on: ["ジ"],
          kun: ["とき", "-どき"],
          strokes: 10,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 673,
      kanji: "日用品",
      reading: "にちようひん",
      meanings: {
        ja: "日用品",
        en: "daily necessities",
        zh: "日用品",
        tw: "日用品",
        ko: "일용품",
        vi: "đồ dùng hàng ngày",
        th: "ของใช้ประจำวัน",
        my: "နေ့စဉ်အသုံးအဆောင်",
        km: "របស់ប្រើប្រាស់ប្រចាំថ្ងៃ",
      },
      furigana: [
        {
          rb: "日用品",
          rt: "にちようひん",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "用",
          on: ["ヨウ"],
          kun: ["もち.いる"],
          strokes: 5,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "品",
          on: ["ヒン", "ホン"],
          kun: ["しな"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 674,
      kanji: "日課",
      reading: "にっか",
      meanings: {
        ja: "日課",
        en: "daily routine",
        zh: "日课",
        tw: "日課",
        ko: "일과",
        vi: "công việc hằng ngày",
        th: "กิจวัตรประจำวัน",
        my: "နေ့စဉ်အလုပ်ဆောင်များ",
        km: "កិច្ចការប្រចាំថ្ងៃ",
      },
      furigana: [
        {
          rb: "日課",
          rt: "にっか",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "課",
          on: ["カ"],
          kun: [],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 675,
      kanji: "日程",
      reading: "にってい",
      meanings: {
        ja: "日程",
        en: "schedule",
        zh: "日程",
        tw: "日程",
        ko: "일정",
        vi: "lịch trình",
        th: "กำหนดการ",
        my: "အချိန်ဇယား",
        km: "កាលវិភាគ",
      },
      furigana: [
        {
          rb: "日程",
          rt: "にってい",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "程",
          on: ["テイ"],
          kun: ["ほど", "-ほど"],
          strokes: 12,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 676,
      kanji: "入社",
      reading: "にゅうしゃ",
      meanings: {
        ja: "入社",
        en: "joining a company",
        zh: "入社",
        tw: "入社",
        ko: "입사",
        vi: "vào công ty",
        th: "เข้าบริษัท",
        my: "ကုမ္ပဏီဝင်ခြင်း",
        km: "ចូលក្រុមហ៊ុន",
      },
      furigana: [
        {
          rb: "入社",
          rt: "にゅうしゃ",
        },
      ],
      kanjiInfo: [
        {
          char: "入",
          on: ["ニュウ", "ジュ"],
          kun: ["い.る", "-い.る", "-い.り", "い.れる", "-い.れ", "はい.る"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "社",
          on: ["シャ"],
          kun: ["やしろ"],
          strokes: 7,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 677,
      kanji: "女房",
      reading: "にょうぼう",
      meanings: {
        ja: "女房",
        en: "wife (esp. one's own wife)",
        zh: "妻子",
        tw: "妻子",
        ko: "아내",
        vi: "vợ (cách gọi cũ)",
        th: "ภรรยา",
        my: "ဇနီး",
        km: "ប្រពន្ធ",
      },
      furigana: [
        {
          rb: "女房",
          rt: "にょうぼう",
        },
      ],
      kanjiInfo: [
        {
          char: "女",
          on: ["ジョ", "ニョ", "ニョウ"],
          kun: ["おんな", "め"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "房",
          on: ["ボウ"],
          kun: ["ふさ"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 678,
      kanji: "ネックレス",
      reading: "ネックレス",
      meanings: {
        ja: "ネックレス",
        en: "necklace",
        zh: "项链",
        tw: "項鍊",
        ko: "목걸이",
        vi: "dây chuyền",
        th: "สร้อยคอ",
        my: "လည်ဆွဲ",
        km: "ខ្សែក",
      },
      furigana: [
        {
          rb: "ネックレス",
          rt: "ネックレス",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 679,
      kanji: "寝間着",
      reading: "ねまき",
      meanings: {
        ja: "寝間着",
        en: "nightclothes",
        zh: "睡衣",
        tw: "睡衣",
        ko: "잠옷",
        vi: "quần áo ngủ",
        th: "ชุดนอน",
        my: "အိပ်ယပ်",
        km: "ឈុតគេង",
      },
      furigana: [
        {
          rb: "寝間着",
          rt: "ねまき",
        },
      ],
      kanjiInfo: [
        {
          char: "寝",
          on: ["シン"],
          kun: ["ね.る", "ね.かす", "い.ぬ", "みたまや", "や.める"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 680,
      kanji: "寝巻",
      reading: "ねまき",
      meanings: {
        ja: "寝巻",
        en: "nightclothes",
        zh: "睡衣",
        tw: "睡衣",
        ko: "잠옷",
        vi: "đồ ngủ",
        th: "เสื้อผ้านอน",
        my: "အိပ်ယပ်",
        km: "ឈុតគេង",
      },
      furigana: [
        {
          rb: "寝巻",
          rt: "ねまき",
        },
      ],
      kanjiInfo: [
        {
          char: "寝",
          on: ["シン"],
          kun: ["ね.る", "ね.かす", "い.ぬ", "みたまや", "や.める"],
          strokes: 13,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "巻",
          on: ["カン", "ケン"],
          kun: ["ま.く", "まき", "ま.き"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 681,
      kanji: "狙い",
      reading: "ねらい",
      meanings: {
        ja: "狙い",
        en: "aim (of a gun)",
        zh: "瞄准",
        tw: "瞄準",
        ko: "조준",
        vi: "nhắm mục tiêu",
        th: "เล็งเป้า",
        my: "ပစ်မှတ်ထားမှု",
        km: "គោលដៅ",
      },
      furigana: [
        {
          rb: "狙い",
          rt: "ねらい",
        },
      ],
      kanjiInfo: [
        {
          char: "狙",
          on: ["ソ", "ショ"],
          kun: ["ねら.う", "ねら.い"],
          strokes: 8,
          grade: 8,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 682,
      kanji: "年度",
      reading: "ねんど",
      meanings: {
        ja: "年度",
        en: "fiscal year (usu. April 1 to March 31 in Japan)",
        zh: "财政年度",
        tw: "財政年度",
        ko: "년도",
        vi: "năm tài chính",
        th: "ปีงบประมาณ",
        my: "ငွေစာရင်းနှစ်",
        km: "ឆ្នាំសារពើពន្ធ",
      },
      furigana: [
        {
          rb: "年度",
          rt: "ねんど",
        },
      ],
      kanjiInfo: [
        {
          char: "年",
          on: ["ネン"],
          kun: ["とし"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "度",
          on: ["ド", "ト", "タク"],
          kun: ["たび", "-た.い"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 683,
      kanji: "農産物",
      reading: "のうさんぶつ",
      meanings: {
        ja: "農産物",
        en: "agricultural produce",
        zh: "农产品",
        tw: "農產品",
        ko: "농산물",
        vi: "nông sản",
        th: "ผลผลิตทางการเกษตร",
        my: "စိုက်ပျိုးထွက်",
        km: "ផលិតផលកសិកម្ម",
      },
      furigana: [
        {
          rb: "農産物",
          rt: "のうさんぶつ",
        },
      ],
      kanjiInfo: [
        {
          char: "農",
          on: ["ノウ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "物",
          on: ["ブツ", "モツ"],
          kun: ["もの", "もの-"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 684,
      kanji: "農村",
      reading: "のうそん",
      meanings: {
        ja: "農村",
        en: "agricultural community",
        zh: "农村",
        tw: "農村",
        ko: "농촌",
        vi: "nông thôn",
        th: "ชนบท",
        my: "ကျေးရွာ",
        km: "ភូមិ",
      },
      furigana: [
        {
          rb: "農村",
          rt: "のうそん",
        },
      ],
      kanjiInfo: [
        {
          char: "農",
          on: ["ノウ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "村",
          on: ["ソン"],
          kun: ["むら"],
          strokes: 7,
          grade: 1,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 685,
      kanji: "濃度",
      reading: "のうど",
      meanings: {
        ja: "濃度",
        en: "concentration",
        zh: "浓度",
        tw: "濃度",
        ko: "농도",
        vi: "nồng độ",
        th: "ความเข้มข้น",
        my: "ကျစ်လျစ်မှု",
        km: "កម្រាស់",
      },
      furigana: [
        {
          rb: "濃度",
          rt: "のうど",
        },
      ],
      kanjiInfo: [
        {
          char: "濃",
          on: ["ノウ"],
          kun: ["こ.い"],
          strokes: 16,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "度",
          on: ["ド", "ト", "タク"],
          kun: ["たび", "-た.い"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 686,
      kanji: "農薬",
      reading: "のうやく",
      meanings: {
        ja: "農薬",
        en: "agricultural chemical (pesticide)",
        zh: "农药",
        tw: "農藥",
        ko: "농약",
        vi: "thuốc trừ sâu",
        th: "ยาฆ่าแมลง",
        my: "လယ်ယာဆေး",
        km: "ថ្នាំកសិកម្ម",
      },
      furigana: [
        {
          rb: "農薬",
          rt: "のうやく",
        },
      ],
      kanjiInfo: [
        {
          char: "農",
          on: ["ノウ"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "薬",
          on: ["ヤク"],
          kun: ["くすり"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 687,
      kanji: "能率",
      reading: "のうりつ",
      meanings: {
        ja: "能率",
        en: "efficiency",
        zh: "效率",
        tw: "效率",
        ko: "능률",
        vi: "năng suất",
        th: "ประสิทธิภาพ",
        my: "ထိရောက်မှု",
        km: "ប្រសិទ្ធភាព",
      },
      furigana: [
        {
          rb: "能率",
          rt: "のうりつ",
        },
      ],
      kanjiInfo: [
        {
          char: "能",
          on: ["ノウ"],
          kun: ["よ.く", "あた.う"],
          strokes: 10,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
        {
          char: "率",
          on: ["ソツ", "リツ", "シュツ"],
          kun: ["ひき.いる"],
          strokes: 11,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 688,
      kanji: "上り",
      reading: "のぼり",
      meanings: {
        ja: "上り",
        en: "ascent",
        zh: "上升",
        tw: "上升",
        ko: "오름",
        vi: "lên dốc",
        th: "การขึ้น",
        my: "တက်ခြင်း",
        km: "ឡើង",
      },
      furigana: [
        {
          rb: "上り",
          rt: "のぼり",
        },
      ],
      kanjiInfo: [
        {
          char: "上",
          on: ["ジョウ", "ショウ", "シャン"],
          kun: [
            "うえ",
            "-うえ",
            "うわ-",
            "かみ",
            "あ.げる",
            "-あ.げる",
            "あ.がる",
            "-あ.がる",
            "あ.がり",
            "-あ.がり",
            "のぼ.る",
            "のぼ.り",
            "のぼ.せる",
            "のぼ.す",
            "たてまつ.る",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 689,
      kanji: "糊",
      reading: "のり",
      meanings: {
        ja: "糊",
        en: "paste",
        zh: "浆糊",
        tw: "漿糊",
        ko: "풀",
        vi: "hồ dán",
        th: "กาว",
        my: "ဆေးပေါ့",
        km: "កាវ",
      },
      furigana: [
        {
          rb: "糊",
          rt: "のり",
        },
      ],
      kanjiInfo: [
        {
          char: "糊",
          on: ["コ", "ゴ", "コツ"],
          kun: ["のり"],
          strokes: 15,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 690,
      kanji: "乗換",
      reading: "のりかえ",
      meanings: {
        ja: "乗換",
        en: "transfer (trains)",
        zh: "换乘",
        tw: "換乘",
        ko: "환승",
        vi: "đổi tàu",
        th: "เปลี่ยนรถ",
        my: "ယာဉ်ပြောင်း",
        km: "ប្តូររថយន្ត/រថភ្លើង",
      },
      furigana: [
        {
          rb: "乗換",
          rt: "のりかえ",
        },
      ],
      kanjiInfo: [
        {
          char: "乗",
          on: ["ジョウ", "ショウ"],
          kun: ["の.る", "-の.り", "の.せる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "換",
          on: ["カン"],
          kun: ["か.える", "-か.える", "か.わる"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 691,
      kanji: "乗り越し",
      reading: "のりこし",
      meanings: {
        ja: "乗り越し",
        en: "riding past (one's station)",
        zh: "坐过站",
        tw: "坐過站",
        ko: "초과 승차",
        vi: "đi quá trạm",
        th: "นั่งเลยป้าย",
        my: "ဘူတာကျော်",
        km: "ឆ្លងស្ថានីយ",
      },
      furigana: [
        {
          rb: "乗り越し",
          rt: "のりこし",
        },
      ],
      kanjiInfo: [
        {
          char: "乗",
          on: ["ジョウ", "ショウ"],
          kun: ["の.る", "-の.り", "の.せる"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "越",
          on: ["エツ", "オツ"],
          kun: ["こ.す", "-こ.す", "-ご.し", "こ.える", "-ご.え"],
          strokes: 12,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 692,
      kanji: "灰色",
      reading: "はいいろ",
      meanings: {
        ja: "灰色",
        en: "grey",
        zh: "灰色",
        tw: "灰色",
        ko: "회색",
        vi: "màu xám",
        th: "สีเทา",
        my: "မီးခိုးရောင်",
        km: "ប្រផេះ",
      },
      furigana: [
        {
          rb: "灰色",
          rt: "はいいろ",
        },
      ],
      kanjiInfo: [
        {
          char: "灰",
          on: ["カイ"],
          kun: ["はい"],
          strokes: 6,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
        {
          char: "色",
          on: ["ショク", "シキ"],
          kun: ["いろ"],
          strokes: 6,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 693,
      kanji: "俳句",
      reading: "はいく",
      meanings: {
        ja: "俳句",
        en: "haiku",
        zh: "俳句",
        tw: "俳句",
        ko: "하이쿠",
        vi: "thơ haiku",
        th: "กลอนไฮกุ",
        my: "ဟိုင်ကူ",
        km: "កំណាព្យហៃគូ",
      },
      furigana: [
        {
          rb: "俳句",
          rt: "はいく",
        },
      ],
      kanjiInfo: [
        {
          char: "俳",
          on: ["ハイ"],
          kun: [],
          strokes: 10,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
        {
          char: "句",
          on: ["ク"],
          kun: [],
          strokes: 5,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 694,
      kanji: "売店",
      reading: "ばいてん",
      meanings: {
        ja: "売店",
        en: "stand; kiosk",
        zh: "小卖部",
        tw: "小賣部",
        ko: "매점",
        vi: "quầy bán hàng",
        th: "ร้านขายของเล็ก",
        my: "ဆိုင်တန်းငယ်",
        km: "ហាងតូច",
      },
      furigana: [
        {
          rb: "売店",
          rt: "ばいてん",
        },
      ],
      kanjiInfo: [
        {
          char: "売",
          on: ["バイ"],
          kun: ["う.る", "う.れる"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "店",
          on: ["テン"],
          kun: ["みせ", "たな"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 695,
      kanji: "売買",
      reading: "ばいばい",
      meanings: {
        ja: "売買",
        en: "trade",
        zh: "买卖",
        tw: "買賣",
        ko: "매매",
        vi: "mua bán",
        th: "การซื้อขาย",
        my: "ဝယ်ရောင်း",
        km: "ទិញលក់",
      },
      furigana: [
        {
          rb: "売買",
          rt: "ばいばい",
        },
      ],
      kanjiInfo: [
        {
          char: "売",
          on: ["バイ"],
          kun: ["う.る", "う.れる"],
          strokes: 7,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "買",
          on: ["バイ"],
          kun: ["か.う"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 696,
      kanji: "秤",
      reading: "はかり",
      meanings: {
        ja: "秤",
        en: "scales (weighing)",
        zh: "秤",
        tw: "秤",
        ko: "저울",
        vi: "cái cân",
        th: "ตาชั่ง",
        my: "ခွဲတံ",
        km: "តង់សា/ត្របែក",
      },
      furigana: [
        {
          rb: "秤",
          rt: "はかり",
        },
      ],
      kanjiInfo: [
        {
          char: "秤",
          on: ["ショウ", "ヒン", "ビン"],
          kun: ["はかり"],
          strokes: 10,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 697,
      kanji: "吐き気",
      reading: "はきけ",
      meanings: {
        ja: "吐き気",
        en: "nausea",
        zh: "恶心",
        tw: "噁心",
        ko: "메스꺼움",
        vi: "buồn nôn",
        th: "คลื่นไส้",
        my: "အန်ချင်ခြင်း",
        km: "ក្អួតក្អាល់",
      },
      furigana: [
        {
          rb: "吐き気",
          rt: "はきけ",
        },
      ],
      kanjiInfo: [
        {
          char: "吐",
          on: ["ト"],
          kun: ["は.く", "つ.く"],
          strokes: 6,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 698,
      kanji: "歯車",
      reading: "はぐるま",
      meanings: {
        ja: "歯車",
        en: "gear",
        zh: "齿轮",
        tw: "齒輪",
        ko: "톱니바퀴",
        vi: "bánh răng",
        th: "เฟือง",
        my: "ဂီယာ",
        km: "ឌឺងហ្គោ",
      },
      furigana: [
        {
          rb: "歯車",
          rt: "はぐるま",
        },
      ],
      kanjiInfo: [
        {
          char: "歯",
          on: ["シ"],
          kun: ["よわい", "は", "よわ.い", "よわい.する"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "車",
          on: ["シャ"],
          kun: ["くるま"],
          strokes: 7,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 699,
      kanji: "梯子",
      reading: "はしご",
      meanings: {
        ja: "梯子",
        en: "ladder",
        zh: "梯子",
        tw: "梯子",
        ko: "사다리",
        vi: "thang",
        th: "บันไดพาด",
        my: "စကာလှေက",
        km: "ជណ្ដើរ",
      },
      furigana: [
        {
          rb: "梯子",
          rt: "はしご",
        },
      ],
      kanjiInfo: [
        {
          char: "梯",
          on: ["テイ", "タイ"],
          kun: ["はしご"],
          strokes: 11,
          grade: 9,
          jlpt: 0,
          radical: null,
        },
        {
          char: "子",
          on: ["シ", "ス", "ツ"],
          kun: ["こ", "-こ", "ね"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 700,
      kanji: "パターン",
      reading: "パターン",
      meanings: {
        ja: "パターン",
        en: "pattern",
        zh: "图案",
        tw: "圖案",
        ko: "패턴",
        vi: "mẫu; khuôn mẫu",
        th: "รูปแบบ",
        my: "ပုံစံ",
        km: "គំរូ",
      },
      furigana: [
        {
          rb: "パターン",
          rt: "パターン",
        },
      ],
      kanjiInfo: [],
    },
  ],
};
