export const n2part35 = {
  Lesson35: [
    {
      id: 1684,
      kanji: "副～",
      reading: "ふく～",
      meanings: {
        ja: "副～",
        en: "vice-; deputy",
        zh: "副～",
        tw: "副～",
        ko: "부~",
        vi: "phó ~",
        th: "รอง ~",
        my: "အပေါ်စီးပွားရေး",
        km: "អនុ~",
      },
      furigana: [
        {
          rb: "副～",
          rt: "ふく～",
        },
      ],
      kanjiInfo: [
        {
          char: "副",
          on: ["フク"],
          kun: [],
          strokes: 11,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1685,
      kanji: "ふざける",
      reading: "ふざける",
      meanings: {
        ja: "ふざける",
        en: "to joke; to fool around",
        zh: "开玩笑",
        tw: "開玩笑",
        ko: "장난치다",
        vi: "đùa giỡn",
        th: "ล้อเล่น",
        my: "ကစား",
        km: "លេងសើច",
      },
      furigana: [
        {
          rb: "ふざける",
          rt: "ふざける",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1686,
      kanji: "ぶらさげる",
      reading: "ぶらさげる",
      meanings: {
        ja: "ぶらさげる",
        en: "to hang; to suspend",
        zh: "挂",
        tw: "掛",
        ko: "매달다",
        vi: "treo",
        th: "แขวน",
        my: "แขวน",
        km: "ព្យួរ",
      },
      furigana: [
        {
          rb: "ぶらさげる",
          rt: "ぶらさげる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1687,
      kanji: "～振り",
      reading: "～ぶり",
      meanings: {
        ja: "～振り",
        en: "style; manner",
        zh: "～样子",
        tw: "～樣子",
        ko: "~모습",
        vi: "cách ~",
        th: "ลักษณะ ~",
        my: "ပုံစံ ~",
        km: "របៀប ~",
      },
      furigana: [
        {
          rb: "～振り",
          rt: "～ぶり",
        },
      ],
      kanjiInfo: [
        {
          char: "振",
          on: ["シン"],
          kun: ["ふ.る", "ふ.れる", "ふ.るう"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1688,
      kanji: "古～",
      reading: "ふる～",
      meanings: {
        ja: "古～",
        en: "old ~",
        zh: "古～",
        tw: "古～",
        ko: "고~",
        vi: "cũ ~",
        th: "เก่า ~",
        my: "ဟောင်း ~",
        km: "ចាស់ ~",
      },
      furigana: [
        {
          rb: "古～",
          rt: "ふる～",
        },
      ],
      kanjiInfo: [
        {
          char: "古",
          on: ["コ"],
          kun: ["ふる.い", "ふる-", "-ふる.す"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1689,
      kanji: "へそ",
      reading: "へそ",
      meanings: {
        ja: "へそ",
        en: "navel",
        zh: "肚脐",
        tw: "肚臍",
        ko: "배꼽",
        vi: "rốn",
        th: "สะดือ",
        my: "ဗိုက်တောင့်",
        km: "ផ្ចិតពោះ",
      },
      furigana: [
        {
          rb: "へそ",
          rt: "へそ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1690,
      kanji: "～遍",
      reading: "～へん",
      meanings: {
        ja: "～遍",
        en: "times; occurrences",
        zh: "～遍",
        tw: "～遍",
        ko: "~번",
        vi: "lần ~",
        th: "ครั้ง ~",
        my: "ကြိမ် ~",
        km: "ដង ~",
      },
      furigana: [
        {
          rb: "～遍",
          rt: "～へん",
        },
      ],
      kanjiInfo: [
        {
          char: "遍",
          on: ["ヘン"],
          kun: ["あまね.く"],
          strokes: 12,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1691,
      kanji: "～弁",
      reading: "～べん",
      meanings: {
        ja: "～弁",
        en: "dialect; speech",
        zh: "～话",
        tw: "～話",
        ko: "~방언",
        vi: "phương ngữ ~",
        th: "สำเนียง ~",
        my: "စကားလုံး ~",
        km: "ប្រភេទភាសា ~",
      },
      furigana: [
        {
          rb: "～弁",
          rt: "～べん",
        },
      ],
      kanjiInfo: [
        {
          char: "弁",
          on: ["ベン", "ヘン"],
          kun: ["かんむり", "わきま.える", "わ.ける", "はなびら", "あらそ.う"],
          strokes: 5,
          grade: 5,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1692,
      kanji: "～歩",
      reading: "～ほ",
      meanings: {
        ja: "～歩",
        en: "step(s)",
        zh: "～步",
        tw: "～步",
        ko: "~보",
        vi: "bước ~",
        th: "ก้าว ~",
        my: "ခြေ ~",
        km: "ជំហាន ~",
      },
      furigana: [
        {
          rb: "～歩",
          rt: "～ほ",
        },
      ],
      kanjiInfo: [
        {
          char: "歩",
          on: ["ホ", "ブ", "フ"],
          kun: ["ある.く", "あゆ.む"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1693,
      kanji: "～ぽい",
      reading: "～ぽい",
      meanings: {
        ja: "～ぽい",
        en: "-ish; like ~",
        zh: "有点～",
        tw: "有點～",
        ko: "~스러운",
        vi: "hơi ~",
        th: "คล้าย ~",
        my: "စွမ်းဆောင်မှု",
        km: "ដូចជា ~",
      },
      furigana: [
        {
          rb: "～ぽい",
          rt: "～ぽい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1694,
      kanji: "～ほう (ひかく)",
      reading: "～ほう (ひかく)",
      meanings: {
        ja: "～方",
        en: "the ~ (comparison)",
        zh: "～方",
        tw: "～方",
        ko: "~쪽",
        vi: "phía ~",
        th: "ด้าน ~",
        my: "ဘက် ~",
        km: "ផ្នែក ~",
      },
      furigana: [
        {
          rb: "～ほう (ひかく)",
          rt: "～ほう （ひかく）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1695,
      kanji: "防～",
      reading: "ぼう～",
      meanings: {
        ja: "防～",
        en: "prevention ~",
        zh: "防～",
        tw: "防～",
        ko: "방~",
        vi: "phòng ~",
        th: "ป้องกัน ~",
        my: "ကာကွယ်ရေး ~",
        km: "ការពារ ~",
      },
      furigana: [
        {
          rb: "防～",
          rt: "ぼう～",
        },
      ],
      kanjiInfo: [
        {
          char: "防",
          on: ["ボウ"],
          kun: ["ふせ.ぐ"],
          strokes: 7,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1696,
      kanji: "ぼろ",
      reading: "ぼろ",
      meanings: {
        ja: "ぼろ",
        en: "rag; tattered",
        zh: "破布",
        tw: "破布",
        ko: "누더기",
        vi: "rách nát",
        th: "ผ้าขี้ริ้ว",
        my: "အ၀တ်အပျက်",
        km: "ក្រណាត់ចាស់",
      },
      furigana: [
        {
          rb: "ぼろ",
          rt: "ぼろ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1697,
      kanji: "ほんの～",
      reading: "ほんの～",
      meanings: {
        ja: "ほんの～",
        en: "mere ~",
        zh: "仅仅～",
        tw: "僅僅～",
        ko: "그저 ~",
        vi: "chỉ ~",
        th: "เพียง ~",
        my: "သာ ~",
        km: "ត្រឹមតែ ~",
      },
      furigana: [
        {
          rb: "ほんの～",
          rt: "ほんの～",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1698,
      kanji: "毎～",
      reading: "まい～",
      meanings: {
        ja: "毎～",
        en: "every ~",
        zh: "每～",
        tw: "每～",
        ko: "매~",
        vi: "mỗi ~",
        th: "ทุก ~",
        my: "တိုင်း ~",
        km: "រាល់ ~",
      },
      furigana: [
        {
          rb: "毎～",
          rt: "まい～",
        },
      ],
      kanjiInfo: [
        {
          char: "毎",
          on: ["マイ"],
          kun: ["ごと", "-ごと.に"],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1699,
      kanji: "またぐ",
      reading: "またぐ",
      meanings: {
        ja: "またぐ",
        en: "to straddle; to step over",
        zh: "跨过",
        tw: "跨過",
        ko: "가랑이를 벌리다",
        vi: "bước qua",
        th: "ก้าวข้าม",
        my: "ကျော်",
        km: "ឆ្លងកាត់",
      },
      furigana: [
        {
          rb: "またぐ",
          rt: "またぐ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1700,
      kanji: "まぶた",
      reading: "まぶた",
      meanings: {
        ja: "まぶた",
        en: "eyelid",
        zh: "眼皮",
        tw: "眼皮",
        ko: "눈꺼풀",
        vi: "mí mắt",
        th: "เปลือกตา",
        my: "မျက်ခုံး",
        km: "ត្របកភ្នែក",
      },
      furigana: [
        {
          rb: "まぶた",
          rt: "まぶた",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1701,
      kanji: "未～",
      reading: "み～",
      meanings: {
        ja: "未～",
        en: "un-; not yet",
        zh: "未～",
        tw: "未～",
        ko: "미~",
        vi: "chưa ~",
        th: "ยังไม่ ~",
        my: "မ ~",
        km: "មិនទាន់ ~",
      },
      furigana: [
        {
          rb: "未～",
          rt: "み～",
        },
      ],
      kanjiInfo: [
        {
          char: "未",
          on: ["ミ", "ビ"],
          kun: ["いま.だ", "ま.だ", "ひつじ"],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1702,
      kanji: "みじめ",
      reading: "みじめ",
      meanings: {
        ja: "みじめ",
        en: "miserable",
        zh: "悲惨",
        tw: "悲慘",
        ko: "비참하다",
        vi: "khốn khổ",
        th: "น่าสังเวช",
        my: "ဒုက္ခရောက်",
        km: "អាក្រក់",
      },
      furigana: [
        {
          rb: "みじめ",
          rt: "みじめ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1703,
      kanji: "～みたい",
      reading: "～みたい",
      meanings: {
        ja: "～みたい",
        en: "like; similar to",
        zh: "像～",
        tw: "像～",
        ko: "~처럼",
        vi: "giống như ~",
        th: "เหมือน ~",
        my: "ကဲ့သို့",
        km: "ដូចជា ~",
      },
      furigana: [
        {
          rb: "～みたい",
          rt: "～みたい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1704,
      kanji: "みっともない",
      reading: "みっともない",
      meanings: {
        ja: "みっともない",
        en: "shameful",
        zh: "丢脸",
        tw: "丟臉",
        ko: "창피하다",
        vi: "xấu hổ",
        th: "น่าอับอาย",
        my: "အရှက်",
        km: "អៀន",
      },
      furigana: [
        {
          rb: "みっともない",
          rt: "みっともない",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1705,
      kanji: "ミリ (メートル)",
      reading: "ミリ (メートル)",
      meanings: {
        ja: "ミリ (メートル)",
        en: "millimeter",
        zh: "毫米",
        tw: "毫米",
        ko: "밀리미터",
        vi: "milimét",
        th: "มิลลิเมตร",
        my: "မီလီမီတာ",
        km: "មិល្លីម៉ែត្រ",
      },
      furigana: [
        {
          rb: "ミリ (メートル)",
          rt: "みり （めえとる）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1706,
      kanji: "民主～",
      reading: "みんしゅ～",
      meanings: {
        ja: "民主～",
        en: "democratic ~",
        zh: "民主～",
        tw: "民主～",
        ko: "민주~",
        vi: "dân chủ ~",
        th: "ประชาธิปไตย ~",
        my: "ဒီမိုကရေစီ ~",
        km: "ប្រជាធិបតេយ្យ ~",
      },
      furigana: [
        {
          rb: "民主～",
          rt: "みんしゅ～",
        },
      ],
      kanjiInfo: [
        {
          char: "民",
          on: ["ミン"],
          kun: ["たみ"],
          strokes: 5,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
        {
          char: "主",
          on: ["シュ", "ス", "シュウ"],
          kun: ["ぬし", "おも", "あるじ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1707,
      kanji: "～向け",
      reading: "～むけ",
      meanings: {
        ja: "～向け",
        en: "intended for ~",
        zh: "面向～",
        tw: "面向～",
        ko: "~용",
        vi: "dành cho ~",
        th: "สำหรับ ~",
        my: "အတွက် ~",
        km: "សម្រាប់ ~",
      },
      furigana: [
        {
          rb: "～向け",
          rt: "～むけ",
        },
      ],
      kanjiInfo: [
        {
          char: "向",
          on: ["コウ"],
          kun: [
            "む.く",
            "む.い",
            "-む.き",
            "む.ける",
            "-む.け",
            "む.かう",
            "む.かい",
            "む.こう",
            "む.こう-",
            "むこ",
            "むか.い",
          ],
          strokes: 6,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1708,
      kanji: "名～",
      reading: "めい～",
      meanings: {
        ja: "名～",
        en: "famous ~",
        zh: "名～",
        tw: "名～",
        ko: "명~",
        vi: "nổi tiếng ~",
        th: "ชื่อดัง ~",
        my: "ကျော်ကြား ~",
        km: "ល្បី ~",
      },
      furigana: [
        {
          rb: "名～",
          rt: "めい～",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1709,
      kanji: "～名",
      reading: "～めい",
      meanings: {
        ja: "～名",
        en: "person(s)",
        zh: "～名",
        tw: "～名",
        ko: "~명",
        vi: "người ~",
        th: "คน ~",
        my: "ယောက် ~",
        km: "នាក់ ~",
      },
      furigana: [
        {
          rb: "～名",
          rt: "～めい",
        },
      ],
      kanjiInfo: [
        {
          char: "名",
          on: ["メイ", "ミョウ"],
          kun: ["な", "-な"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1710,
      kanji: "めちゃくちゃ",
      reading: "めちゃくちゃ",
      meanings: {
        ja: "めちゃくちゃ",
        en: "messy; absurd",
        zh: "乱七八糟",
        tw: "亂七八糟",
        ko: "엉망",
        vi: "bừa bộn",
        th: "ยุ่งเหยิง",
        my: "အပေါ混乱",
        km: "រញ្ជួយ",
      },
      furigana: [
        {
          rb: "めちゃくちゃ",
          rt: "めちゃくちゃ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1711,
      kanji: "めでたい",
      reading: "めでたい",
      meanings: {
        ja: "めでたい",
        en: "auspicious; happy",
        zh: "可喜",
        tw: "可喜",
        ko: "경사스럽다",
        vi: "đáng mừng",
        th: "น่ายินดี",
        my: "အလွန်ကောင်း",
        km: "គួរអបអរសាទរ",
      },
      furigana: [
        {
          rb: "めでたい",
          rt: "めでたい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1712,
      kanji: "めまい",
      reading: "めまい",
      meanings: {
        ja: "めまい",
        en: "dizziness",
        zh: "头晕",
        tw: "頭暈",
        ko: "어지럼증",
        vi: "chóng mặt",
        th: "เวียนหัว",
        my: "မူးဝြေ့",
        km: "វង្វេង",
      },
      furigana: [
        {
          rb: "めまい",
          rt: "めまい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1713,
      kanji: "申し訳ない",
      reading: "もうしわけない",
      meanings: {
        ja: "申し訳ない",
        en: "I'm sorry",
        zh: "对不起",
        tw: "對不起",
        ko: "죄송합니다",
        vi: "xin lỗi",
        th: "ขอโทษ",
        my: "တောင်းပန်ပါတယ်",
        km: "សុំទោស",
      },
      furigana: [
        {
          rb: "申し訳ない",
          rt: "もうしわけない",
        },
      ],
      kanjiInfo: [
        {
          char: "申",
          on: ["シン"],
          kun: ["もう.す", "もう.し-", "さる"],
          strokes: 5,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
        {
          char: "訳",
          on: ["ヤク"],
          kun: ["わけ"],
          strokes: 11,
          grade: 6,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1714,
      kanji: "もしかしたら",
      reading: "もしかしたら",
      meanings: {
        ja: "もしかしたら",
        en: "perhaps",
        zh: "也许",
        tw: "也許",
        ko: "어쩌면",
        vi: "có lẽ",
        th: "อาจจะ",
        my: "ဖြစ်နိုင်ပါသည်",
        km: "ប្រហែលជា",
      },
      furigana: [
        {
          rb: "もしかしたら",
          rt: "もしかしたら",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1715,
      kanji: "もたれる",
      reading: "もたれる",
      meanings: {
        ja: "もたれる",
        en: "to lean on; to be indigested",
        zh: "靠; 难消化",
        tw: "靠; 難消化",
        ko: "기대다; 체하다",
        vi: "dựa vào; khó tiêu",
        th: "พิง; ย่อยยาก",
        my: "များလျော်",
        km: "ពឹងផ្អែក",
      },
      furigana: [
        {
          rb: "もたれる",
          rt: "もたれる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1716,
      kanji: "～もち",
      reading: "～もち",
      meanings: {
        ja: "～持ち",
        en: "having ~",
        zh: "有～",
        tw: "有～",
        ko: "~가진",
        vi: "có ~",
        th: "มี ~",
        my: "ပါဝင် ~",
        km: "មាន ~",
      },
      furigana: [
        {
          rb: "～もち",
          rt: "～もち",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1717,
      kanji: "～問",
      reading: "～もん",
      meanings: {
        ja: "～問",
        en: "question(s)",
        zh: "～问",
        tw: "～問",
        ko: "~문",
        vi: "câu hỏi ~",
        th: "คำถาม ~",
        my: "မေးခွန်း ~",
        km: "សំណួរ ~",
      },
      furigana: [
        {
          rb: "～問",
          rt: "～もん",
        },
      ],
      kanjiInfo: [
        {
          char: "問",
          on: ["モン"],
          kun: ["と.う", "と.い", "とん"],
          strokes: 11,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1718,
      kanji: "～夜",
      reading: "～や",
      meanings: {
        ja: "～夜",
        en: "night(s)",
        zh: "～夜",
        tw: "～夜",
        ko: "~야",
        vi: "đêm ~",
        th: "คืน ~",
        my: "ည ~",
        km: "យប់ ~",
      },
      furigana: [
        {
          rb: "～夜",
          rt: "～や",
        },
      ],
      kanjiInfo: [
        {
          char: "夜",
          on: ["ヤ"],
          kun: ["よ", "よる"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1719,
      kanji: "やかましい",
      reading: "やかましい",
      meanings: {
        ja: "やかましい",
        en: "noisy; strict",
        zh: "吵闹",
        tw: "吵鬧",
        ko: "시끄럽다",
        vi: "ồn ào",
        th: "เสียงดัง",
        my: "ဆူညံ",
        km: "រំខាន",
      },
      furigana: [
        {
          rb: "やかましい",
          rt: "やかましい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1720,
      kanji: "やかん",
      reading: "やかん",
      meanings: {
        ja: "やかん",
        en: "kettle",
        zh: "水壶",
        tw: "水壺",
        ko: "주전자",
        vi: "ấm đun nước",
        th: "กาต้มน้ำ",
        my: "ရေနွေးစက်",
        km: "កាដុតទឹក",
      },
      furigana: [
        {
          rb: "やかん",
          rt: "やかん",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1721,
      kanji: "やたらに",
      reading: "やたらに",
      meanings: {
        ja: "やたらに",
        en: "recklessly",
        zh: "胡乱地",
        tw: "胡亂地",
        ko: "함부로",
        vi: "bừa bãi",
        th: "สุ่มสี่สุ่มห้า",
        my: "အလျားအမြား",
        km: "មិនគិត",
      },
      furigana: [
        {
          rb: "やたらに",
          rt: "やたらに",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1722,
      kanji: "やっつける",
      reading: "やっつける",
      meanings: {
        ja: "やっつける",
        en: "to beat; to attack",
        zh: "打败",
        tw: "打敗",
        ko: "해치우다",
        vi: "đánh bại",
        th: "เอาชนะ",
        my: "ရိုက်နိမ့်",
        km: "ឈ្នះ",
      },
      furigana: [
        {
          rb: "やっつける",
          rt: "やっつける",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1723,
      kanji: "やっぱり",
      reading: "やっぱり",
      meanings: {
        ja: "やっぱり",
        en: "as expected; after all",
        zh: "果然",
        tw: "果然",
        ko: "역시",
        vi: "quả nhiên",
        th: "ตามคาด",
        my: "ထင်တာပဲ",
        km: "ដូចបានគិត",
      },
      furigana: [
        {
          rb: "やっぱり",
          rt: "やっぱり",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1724,
      kanji: "やむをえない",
      reading: "やむをえない",
      meanings: {
        ja: "やむをえない",
        en: "unavoidable",
        zh: "不得已",
        tw: "不得已",
        ko: "어쩔 수 없다",
        vi: "không tránh khỏi",
        th: "หลีกเลี่ยงไม่ได้",
        my: "မဖြစ်မနို",
        km: "មិនអាចជៀស",
      },
      furigana: [
        {
          rb: "やむをえない",
          rt: "やむをえない",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1725,
      kanji: "悠々",
      reading: "ゆうゆう",
      meanings: {
        ja: "悠々",
        en: "leisurely; calm",
        zh: "悠然",
        tw: "悠然",
        ko: "유유히",
        vi: "thong thả",
        th: "อย่างสบายๆ",
        my: "အေးဆေး",
        km: "ស្ងប់ស្ងាត់",
      },
      furigana: [
        {
          rb: "悠々",
          rt: "ゆうゆう",
        },
      ],
      kanjiInfo: [
        {
          char: "悠",
          on: ["ユウ"],
          kun: [],
          strokes: 11,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "々",
          on: [],
          kun: [],
          strokes: 0,
          grade: 0,
          jlpt: 0,
          radical: null,
        },
      ],
    },
    {
      id: 1726,
      kanji: "翌～",
      reading: "よく～",
      meanings: {
        ja: "翌～",
        en: "the next ~",
        zh: "翌～",
        tw: "翌～",
        ko: "익~",
        vi: "ngày hôm sau ~",
        th: "วันถัดไป ~",
        my: "နောက်နေ့ ~",
        km: "ថ្ងៃបន្ទាប់ ~",
      },
      furigana: [
        {
          rb: "翌～",
          rt: "よく～",
        },
      ],
      kanjiInfo: [
        {
          char: "翌",
          on: ["ヨク"],
          kun: [],
          strokes: 11,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1727,
      kanji: "よこす",
      reading: "よこす",
      meanings: {
        ja: "よこす",
        en: "to send; to hand over",
        zh: "递送",
        tw: "遞送",
        ko: "보내다",
        vi: "gửi",
        th: "ส่ง",
        my: "ပို့",
        km: "ផ្ញើ",
      },
      furigana: [
        {
          rb: "よこす",
          rt: "よこす",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1728,
      kanji: "～等",
      reading: "～ら",
      meanings: {
        ja: "～等",
        en: "et cetera; and so on",
        zh: "～等",
        tw: "～等",
        ko: "~등",
        vi: "~ v.v.",
        th: "~ เป็นต้น",
        my: "စသည်တို့",
        km: "ជាដើម",
      },
      furigana: [
        {
          rb: "～等",
          rt: "～ら",
        },
      ],
      kanjiInfo: [
        {
          char: "等",
          on: ["トウ"],
          kun: ["ひと.しい", "など", "-ら"],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1729,
      kanji: "たんす",
      reading: "たんす",
      meanings: {
        ja: "たんす",
        en: "dresser; wardrobe",
        zh: "衣柜",
        tw: "衣櫃",
        ko: "옷장",
        vi: "tủ quần áo",
        th: "ตู้เสื้อผ้า",
        my: "အလှပေါင်းစုံ",
        km: "ទូអាវ",
      },
      furigana: [
        {
          rb: "たんす",
          rt: "たんす",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1730,
      kanji: "ちぎる",
      reading: "ちぎる",
      meanings: {
        ja: "ちぎる",
        en: "to tear to pieces",
        zh: "撕碎",
        tw: "撕碎",
        ko: "찢다",
        vi: "xé vụn",
        th: "ฉีก",
        my: "ပျက်စီး",
        km: "撕",
      },
      furigana: [
        {
          rb: "ちぎる",
          rt: "ちぎる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1731,
      kanji: "～着",
      reading: "～ちゃく",
      meanings: {
        ja: "～着",
        en: "arrival; counter for suits",
        zh: "～着",
        tw: "～着",
        ko: "~착",
        vi: "đến nơi ~",
        th: "ถึง ~",
        my: "ရောက် ~",
        km: "ដល់ ~",
      },
      furigana: [
        {
          rb: "～着",
          rt: "～ちゃく",
        },
      ],
      kanjiInfo: [
        {
          char: "着",
          on: ["チャク", "ジャク"],
          kun: ["き.る", "き.せる", "つ.く", "つ.ける"],
          strokes: 12,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1732,
      kanji: "長～",
      reading: "ちょう～",
      meanings: {
        ja: "長～",
        en: "chief; long ~",
        zh: "长～",
        tw: "長～",
        ko: "장~",
        vi: "dài ~",
        th: "ยาว ~",
        my: "ရှည် ~",
        km: "វែង ~",
      },
      furigana: [
        {
          rb: "長～",
          rt: "ちょう～",
        },
      ],
      kanjiInfo: [
        {
          char: "長",
          on: ["チョウ"],
          kun: ["なが.い", "おさ"],
          strokes: 8,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1733,
      kanji: "～庁",
      reading: "～ちょう",
      meanings: {
        ja: "～庁",
        en: "government office",
        zh: "～厅",
        tw: "～廳",
        ko: "~청",
        vi: "cơ quan ~",
        th: "กรม ~",
        my: "ဌာန ~",
        km: "ស្ថាប័ន ~",
      },
      furigana: [
        {
          rb: "～庁",
          rt: "～ちょう",
        },
      ],
      kanjiInfo: [
        {
          char: "庁",
          on: ["チョウ", "テイ"],
          kun: ["やくしょ"],
          strokes: 5,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
  ],
};
