export const n2part31 = {
  Lesson31: [
    {
      id: 1484,
      kanji: "おかまいなく",
      reading: "おかまいなく",
      meanings: {
        ja: "どうぞお気遣いなく",
        en: "please don’t bother (about me)",
        zh: "不必麻烦",
        tw: "不用麻煩",
        ko: "신경 쓰지 마세요",
        vi: "xin đừng bận tâm",
        th: "ไม่ต้องลำบากนะ",
        my: "စိတ်မချရပါနှင့်",
        km: "កុំខ្វល់ខ្វាយទេ",
      },
      furigana: [
        {
          rb: "おかまいなく",
          rt: "おかまいなく",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1485,
      kanji: "お気の毒に",
      reading: "おきのどくに",
      meanings: {
        ja: "お気の毒です",
        en: "my sympathies; I’m sorry to hear that",
        zh: "真不幸/我表示同情",
        tw: "真不幸／我表示同情",
        ko: "안됐다; 유감입니다",
        vi: "thật đáng tiếc",
        th: "น่าเห็นใจจัง",
        my: "သနားကြင်နာတယ်",
        km: "សោកស្តាយណាស់",
      },
      furigana: [
        {
          rb: "お気の毒に",
          rt: "おきのどくに",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "毒",
          on: ["ドク"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1486,
      kanji: "お元気で",
      reading: "おげんきで",
      meanings: {
        ja: "お元気で（別れの挨拶）",
        en: "take care; stay well",
        zh: "保重",
        tw: "保重",
        ko: "건강하세요",
        vi: "giữ gìn sức khỏe nhé",
        th: "ดูแลสุขภาพด้วยนะ",
        my: "ကျန်းမာပါစေ",
        km: "សុខភាពល្អៗ",
      },
      furigana: [
        {
          rb: "お元気で",
          rt: "おげんきで",
        },
      ],
      kanjiInfo: [
        {
          char: "元",
          on: ["ゲン", "ガン"],
          kun: ["もと"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1487,
      kanji: "お邪魔します",
      reading: "おじゃまします",
      meanings: {
        ja: "（訪問時の挨拶）失礼します",
        en: "excuse me for intruding",
        zh: "打扰了",
        tw: "打擾了",
        ko: "실례합니다(방문 인사)",
        vi: "xin phép làm phiền",
        th: "ขออนุญาตรบกวน",
        my: "အဆင်မပြေတာရှိရင်တဆင့်",
        km: "សុំទោស ខ្ញុំរំខាន",
      },
      furigana: [
        {
          rb: "お邪魔します",
          rt: "おじゃまします",
        },
      ],
      kanjiInfo: [
        {
          char: "邪",
          on: ["ジャ"],
          kun: ["よこし.ま"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "魔",
          on: ["マ"],
          kun: [],
          strokes: 21,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1488,
      kanji: "お世話になりました",
      reading: "おせわになりました",
      meanings: {
        ja: "お世話になりました（感謝）",
        en: "thank you for your help",
        zh: "承蒙照顾",
        tw: "承蒙照顧",
        ko: "신세 많이졌습니다",
        vi: "cảm ơn đã giúp đỡ",
        th: "ขอบคุณที่ดูแล",
        my: "ကူညီပေးသဖြင့် ကျေးဇူးတင်ပါတယ်",
        km: "អរគុណចំពោះការថែទាំ",
      },
      furigana: [
        {
          rb: "お世話になりました",
          rt: "おせわになりました",
        },
      ],
      kanjiInfo: [
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1489,
      kanji: "お大事に",
      reading: "おだいじに",
      meanings: {
        ja: "（病人へ）お大事に",
        en: "take care of yourself (get well)",
        zh: "请多保重",
        tw: "請多保重",
        ko: "몸조심하세요",
        vi: "giữ gìn sức khỏe nhé",
        th: "หายไว ๆ นะ",
        my: "အ rápido အနားယူပါ",
        km: "សូមជាសះស្បើយឆាប់ៗ",
      },
      furigana: [
        {
          rb: "お大事に",
          rt: "おだいじに",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1490,
      kanji: "お願いします",
      reading: "おねがいします",
      meanings: {
        ja: "お願いします（依頼）",
        en: "please; I request",
        zh: "拜托/麻烦了",
        tw: "拜託／麻煩了",
        ko: "부탁합니다",
        vi: "làm ơn",
        th: "กรุณาด้วย",
        my: "ကျေးဇူးပြု၍",
        km: "សូមបម្រុង",
      },
      furigana: [
        {
          rb: "お願いします",
          rt: "おねがいします",
        },
      ],
      kanjiInfo: [
        {
          char: "願",
          on: ["ガン"],
          kun: ["ねが.う", "-ねがい"],
          strokes: 19,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1491,
      kanji: "おはよう",
      reading: "おはよう",
      meanings: {
        ja: "おはよう（挨拶）",
        en: "good morning",
        zh: "早安",
        tw: "早安",
        ko: "좋은 아침",
        vi: "chào buổi sáng",
        th: "สวัสดีตอนเช้า",
        my: "မင်္ဂလာနံနက်ခင်းပါ",
        km: "អរុណសួស្តី",
      },
      furigana: [
        {
          rb: "おはよう",
          rt: "おはよう",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1492,
      kanji: "お待たせしました",
      reading: "おまたせしました",
      meanings: {
        ja: "お待たせしました",
        en: "thank you for waiting",
        zh: "让您久等了",
        tw: "讓您久等了",
        ko: "기다리게 해서 죄송합니다",
        vi: "xin lỗi đã để chờ",
        th: "ขอโทษที่ให้รอ",
        my: "စောင့်စေလိုက်တာတောင်းပန်ပါတယ်",
        km: "សូមទោស ដែលឲ្យរង់ចាំ",
      },
      furigana: [
        {
          rb: "お待たせしました",
          rt: "おまたせしました",
        },
      ],
      kanjiInfo: [
        {
          char: "待",
          on: ["タイ"],
          kun: ["ま.つ", "-ま.ち"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1493,
      kanji: "お待ちください",
      reading: "おまちください",
      meanings: {
        ja: "少々お待ちください",
        en: "please wait a moment",
        zh: "请稍等",
        tw: "請稍等",
        ko: "잠시만 기다려 주세요",
        vi: "xin vui lòng đợi",
        th: "กรุณารอสักครู่",
        my: "ခဏစောင့်ပါ",
        km: "សូមរង់ចាំអញ្ចឹង",
      },
      furigana: [
        {
          rb: "お待ちください",
          rt: "おまちください",
        },
      ],
      kanjiInfo: [
        {
          char: "待",
          on: ["タイ"],
          kun: ["ま.つ", "-ま.ち"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1494,
      kanji: "おまちどおさま",
      reading: "おまちどおさま",
      meanings: {
        ja: "お待ちどうさま",
        en: "sorry to keep you waiting",
        zh: "久等了",
        tw: "久等了",
        ko: "오래 기다리셨습니다",
        vi: "đã để anh/chị đợi lâu",
        th: "ให้รอนาน ขอโทษด้วย",
        my: "စောင့်နေရက်ရတော့",
        km: "រង់ចាំយូរហើយ",
      },
      furigana: [
        {
          rb: "おまちどおさま",
          rt: "おまちどおさま",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1495,
      kanji: "おめでたい",
      reading: "おめでたい",
      meanings: {
        ja: "めでたい・祝い事にふさわしい",
        en: "auspicious; happy (occasion)",
        zh: "可喜可贺的",
        tw: "可喜可賀的",
        ko: "경사스러운",
        vi: "đáng mừng",
        th: "น่ายินดี",
        my: "မျက်နှာသာကောင်းသော",
        km: "មានសេចក្ដីសុខ",
      },
      furigana: [
        {
          rb: "おめでたい",
          rt: "おめでたい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1496,
      kanji: "おやつ",
      reading: "おやつ",
      meanings: {
        ja: "間食・おやつ",
        en: "snack",
        zh: "点心/零食",
        tw: "點心／零食",
        ko: "간식",
        vi: "đồ ăn vặt",
        th: "ของว่าง",
        my: "အလတ်စားစားစရာ",
        km: "អាហារសម្រន់",
      },
      furigana: [
        {
          rb: "おやつ",
          rt: "おやつ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1497,
      kanji: "女の人",
      reading: "おんなのひと",
      meanings: {
        ja: "女性",
        en: "woman",
        zh: "女人",
        tw: "女人",
        ko: "여자",
        vi: "phụ nữ",
        th: "ผู้หญิง",
        my: "မိန်းမ",
        km: "ស្ត្រី",
      },
      furigana: [
        {
          rb: "女の人",
          rt: "おんなのひと",
        },
      ],
      kanjiInfo: [
        {
          char: "女",
          on: ["ジョ", "ニョ", "ニョウ"],
          kun: ["おんな", "め"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1498,
      kanji: "～日",
      reading: "～か",
      meanings: {
        ja: "月日（ついたち・みっか等）の“～日”",
        en: "the …th day of month (–ka)",
        zh: "几号（日期后缀）",
        tw: "幾號（日期後綴）",
        ko: "…일(날짜 접미사)",
        vi: "ngày … (trong tháng)",
        th: "วันที่ …",
        my: "လရက် …",
        km: "ថ្ងៃទី …",
      },
      furigana: [
        {
          rb: "～日",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1499,
      kanji: "～下",
      reading: "～か",
      meanings: {
        ja: "下位・下部を表す",
        en: "lower; under … (suffix)",
        zh: "下、次等",
        tw: "下、次等",
        ko: "하(下)·아래 …",
        vi: "hạ/ở dưới …",
        th: "ส่วนล่าง/ชั้นล่าง",
        my: "အောက်ပိုင်း …",
        km: "កម្រិតក្រោម …",
      },
      furigana: [
        {
          rb: "～下",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1500,
      kanji: "～化",
      reading: "～か",
      meanings: {
        ja: "…化（～になる/する）",
        en: "–ization; change into …",
        zh: "…化",
        tw: "…化",
        ko: "…화",
        vi: "… hoá",
        th: "…ควบ/กลายเป็น",
        my: "… တော့/ဖြစ်",
        km: "… ការ​បម្លែង",
      },
      furigana: [
        {
          rb: "～化",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1501,
      kanji: "～科",
      reading: "～か",
      meanings: {
        ja: "学科・診療科など",
        en: "department; subject",
        zh: "科（學科/科室）",
        tw: "科（學科／科別）",
        ko: "과(科)",
        vi: "khoa; bộ môn",
        th: "แผนก/สาขา",
        my: "ဌာန/ဘာသာရပ်",
        km: "មហាវិទ្យាល័យ/មន្ទីរ",
      },
      furigana: [
        {
          rb: "～科",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1502,
      kanji: "～歌",
      reading: "～か",
      meanings: {
        ja: "歌（校歌・国歌など）",
        en: "song (e.g., school anthem)",
        zh: "…歌",
        tw: "…歌",
        ko: "…가(歌)",
        vi: "bài hát …",
        th: "เพลง …",
        my: "… တေး",
        km: "ចម្រៀង …",
      },
      furigana: [
        {
          rb: "～歌",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "歌",
          on: ["カ"],
          kun: ["うた", "うた.う"],
          strokes: 14,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1503,
      kanji: "～画",
      reading: "～が",
      meanings: {
        ja: "絵・映画等を表す",
        en: "picture/film …",
        zh: "…画/画面",
        tw: "…畫",
        ko: "…화(畫)",
        vi: "hình/ảnh/phim …",
        th: "ภาพ/ภาพยนตร์ …",
        my: "ရုပ်ပုံ/ရုပ်ရှင် …",
        km: "រូប/ភាពយន្ត …",
      },
      furigana: [
        {
          rb: "～画",
          rt: "～が",
        },
      ],
      kanjiInfo: [
        {
          char: "画",
          on: ["ガ", "カク", "エ", "カイ"],
          kun: ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1504,
      kanji: "外～",
      reading: "がい～",
      meanings: {
        ja: "外・外国の意",
        en: "outer; foreign …",
        zh: "外/国外 …",
        tw: "外／國外 …",
        ko: "외-/대외 …",
        vi: "ngoại/ở ngoài …",
        th: "นอก/ต่างประเทศ …",
        my: "ပြင်/နိုင်ငံပြင် …",
        km: "ក្រៅ/បរទេស …",
      },
      furigana: [
        {
          rb: "外～",
          rt: "がい～",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1505,
      kanji: "～外",
      reading: "～がい",
      meanings: {
        ja: "範囲外・区域外",
        en: "outside; out of …",
        zh: "…以外/…之外",
        tw: "…以外",
        ko: "… 외; … 밖",
        vi: "ngoài …",
        th: "นอกเหนือ …",
        my: "… ယဟုတ်ခြင်းပြင်ပ",
        km: "ក្រៅពី …",
      },
      furigana: [
        {
          rb: "～外",
          rt: "～がい",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1506,
      kanji: "各～",
      reading: "かく～",
      meanings: {
        ja: "各・それぞれの",
        en: "each; every …",
        zh: "各…",
        tw: "各…",
        ko: "각 …",
        vi: "các …; mỗi …",
        th: "แต่ละ …",
        my: "တစ်ခုချင်းစီ …",
        km: "នីមួយៗ …",
      },
      furigana: [
        {
          rb: "各～",
          rt: "かく～",
        },
      ],
      kanjiInfo: [
        {
          char: "各",
          on: ["カク"],
          kun: ["おのおの"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1507,
      kanji: "かしこまりました",
      reading: "かしこまりました",
      meanings: {
        ja: "承知しました（丁寧）",
        en: "certainly; understood",
        zh: "明白了（敬语）",
        tw: "明白了（敬語）",
        ko: "알겠습니다",
        vi: "vâng, tôi rõ",
        th: "รับทราบครับ/ค่ะ",
        my: "နားလည်ပြီးပါသည်",
        km: "យល់ព្រមហើយ",
      },
      furigana: [
        {
          rb: "かしこまりました",
          rt: "かしこまりました",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1508,
      kanji: "かじる",
      reading: "かじる",
      meanings: {
        ja: "かじる・少しかじる",
        en: "to nibble; to dabble in",
        zh: "啃；略懂",
        tw: "啃；略懂",
        ko: "깨물다; 조금 배우다",
        vi: "gặm; biết lõm bõm",
        th: "แทะ; รู้แบบผิวเผิน",
        my: "နည်းနည်းသာ လေ့လာသည်",
        km: "ខាំ; ស្គាល់តិចតួច",
      },
      furigana: [
        {
          rb: "かじる",
          rt: "かじる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1509,
      kanji: "～がち",
      reading: "～がち",
      meanings: {
        ja: "…しがち・傾向がある",
        en: "tending to; apt to …",
        zh: "容易…；常常…",
        tw: "容易…；常常…",
        ko: "…하는 경향이 있다",
        vi: "hay …; có xu hướng …",
        th: "มักจะ …",
        my: "… စရာများတတ်",
        km: "មានទំនោរ …",
      },
      furigana: [
        {
          rb: "～がち",
          rt: "～がち",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1510,
      kanji: "兼ねる",
      reading: "かねる",
      meanings: {
        ja: "…しかねる（丁寧否定補助）",
        en: "to be unable to; cannot",
        zh: "难以…；不能…",
        tw: "難以…；不能…",
        ko: "…하기 어렵다",
        vi: "khó mà …; không thể",
        th: "ไม่อาจ … ได้",
        my: "လုပ်ဖို့နိုင်ခြင်းမရှိ",
        km: "មិនអាច…បាន",
      },
      furigana: [
        {
          rb: "兼ねる",
          rt: "かねる",
        },
      ],
      kanjiInfo: [
        {
          char: "兼",
          on: ["ケン"],
          kun: ["か.ねる", "-か.ねる"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1511,
      kanji: "かび（～がはえる）",
      reading: "かび (～がはえる)",
      meanings: {
        ja: "黴（かび）が生える",
        en: "mold; (mold) grows",
        zh: "霉/长霉",
        tw: "霉／發霉",
        ko: "곰팡이(가 피다)",
        vi: "mốc; (bị) mốc",
        th: "เชื้อรา; เกิดรา",
        my: "ခုံပိုး/ဖုန် (ပေါက်)",
        km: "ពុល/ផ្សិត (កើត)",
      },
      furigana: [
        {
          rb: "かび（～がはえる）",
          rt: "かび （～がはえる）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1512,
      kanji: "構いません",
      reading: "かまいません",
      meanings: {
        ja: "差し支えありません",
        en: "no problem; I don’t mind",
        zh: "没关系",
        tw: "沒關係",
        ko: "괜찮습니다",
        vi: "không sao",
        th: "ไม่เป็นไร",
        my: "မစိုးရိမ်ပါ",
        km: "មិនអីទេ",
      },
      furigana: [
        {
          rb: "構いません",
          rt: "かまいません",
        },
      ],
      kanjiInfo: [
        {
          char: "構",
          on: ["コウ"],
          kun: ["かま.える", "かま.う"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1513,
      kanji: "からかう",
      reading: "からかう",
      meanings: {
        ja: "からかう・冷やかす",
        en: "to tease; make fun of",
        zh: "戏弄；取笑",
        tw: "戲弄；取笑",
        ko: "놀리다",
        vi: "trêu chọc",
        th: "ล้อเล่น",
        my: "ကလိကလွှာလုပ်",
        km: "លេងកំប្លែង",
      },
      furigana: [
        {
          rb: "からかう",
          rt: "からかう",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1514,
      kanji: "かるた",
      reading: "かるた",
      meanings: {
        ja: "日本のカード遊び",
        en: "karuta (Japanese card game)",
        zh: "歌留多（日本纸牌）",
        tw: "歌留多（日本紙牌）",
        ko: "가루타",
        vi: "bài karuta",
        th: "การ์ดเกมคารุตะ",
        my: "ကာရူတား ကစားပွဲ",
        km: "ល្បែងកាត Karuta",
      },
      furigana: [
        {
          rb: "かるた",
          rt: "かるた",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1515,
      kanji: "～刊",
      reading: "～かん",
      meanings: {
        ja: "刊行物・月刊/週刊など",
        en: "–edition; –publication",
        zh: "…刊",
        tw: "…刊",
        ko: "…간(刊)",
        vi: "… san (báo/kỳ)",
        th: "…ฉบับ/…ราย",
        my: "… စာမ刊",
        km: "… បោះពុម្ព",
      },
      furigana: [
        {
          rb: "～刊",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "刊",
          on: ["カン"],
          kun: [],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1516,
      kanji: "～間",
      reading: "～かん",
      meanings: {
        ja: "期間・…の間",
        en: "for … (period); during …",
        zh: "…期间",
        tw: "…期間",
        ko: "…간(間)",
        vi: "trong …; suốt …",
        th: "ช่วง…",
        my: "… အတွင်း",
        km: "អំឡុង …",
      },
      furigana: [
        {
          rb: "～間",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1517,
      kanji: "～巻",
      reading: "～かん",
      meanings: {
        ja: "巻（本の巻数）",
        en: "volume (of books)",
        zh: "…卷",
        tw: "…卷",
        ko: "…권(卷)",
        vi: "quyển/tập …",
        th: "เล่มที่ …",
        my: "အုပ်/တွဲ …",
        km: "ភាគ …",
      },
      furigana: [
        {
          rb: "～巻",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "巻",
          on: ["カン", "ケン"],
          kun: ["ま.く", "まき", "ま.き"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1518,
      kanji: "～館",
      reading: "～かん",
      meanings: {
        ja: "館（図書館・美術館など）",
        en: "–hall; –building; –museum",
        zh: "…馆",
        tw: "…館",
        ko: "…관(館)",
        vi: "… quán/viện",
        th: "…館/…พิพิธภัณฑ์",
        my: "… ထောင်/ဗဟိုဌာန",
        km: "… សារមន្ទីរ/វិទ្យាស្ថាន",
      },
      furigana: [
        {
          rb: "～館",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "館",
          on: ["カン"],
          kun: ["やかた", "たて"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1519,
      kanji: "～感",
      reading: "～かん",
      meanings: {
        ja: "感覚・感じ",
        en: "sense; feeling of …",
        zh: "…感",
        tw: "…感",
        ko: "…감(感)",
        vi: "cảm giác …",
        th: "ความรู้สึก…",
        my: "ခံစားချက် …",
        km: "អារម្មណ៍ …",
      },
      furigana: [
        {
          rb: "～感",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "感",
          on: ["カン"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1520,
      kanji: "乾杯",
      reading: "かんぱい",
      meanings: {
        ja: "乾杯！（発声）",
        en: "cheers!",
        zh: "干杯！",
        tw: "乾杯！",
        ko: "건배!",
        vi: "cạn ly!",
        th: "ชนแก้ว!",
        my: "ကန်ပိုင်!",
        km: "ចៀសកែវ!",
      },
      furigana: [
        {
          rb: "乾杯",
          rt: "かんぱい",
        },
      ],
      kanjiInfo: [
        {
          char: "乾",
          on: ["カン", "ケン"],
          kun: ["かわ.く", "かわ.かす", "ほ.す", "ひ.る", "いぬい"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "杯",
          on: ["ハイ"],
          kun: ["さかずき"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1521,
      kanji: "～期",
      reading: "～き",
      meanings: {
        ja: "時期・期間",
        en: "period; term",
        zh: "…期",
        tw: "…期",
        ko: "…기(期)",
        vi: "thời kỳ …",
        th: "ช่วง…/ระยะ…",
        my: "ကာလ …",
        km: "រដូវ/អំឡុង…",
      },
      furigana: [
        {
          rb: "～期",
          rt: "～き",
        },
      ],
      kanjiInfo: [
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1522,
      kanji: "～器",
      reading: "～き",
      meanings: {
        ja: "器具・機器",
        en: "utensil; device",
        zh: "…器",
        tw: "…器",
        ko: "…기(器)",
        vi: "dụng cụ …",
        th: "อุปกรณ์…",
        my: "ပစ္စည်း …",
        km: "ឧបករណ៍ …",
      },
      furigana: [
        {
          rb: "～器",
          rt: "～き",
        },
      ],
      kanjiInfo: [
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1523,
      kanji: "～機",
      reading: "～き",
      meanings: {
        ja: "機械/飛行機など",
        en: "machine; aircraft",
        zh: "…机/机器/飞机",
        tw: "…機（機械/飛機）",
        ko: "…기(機)",
        vi: "máy/phi cơ …",
        th: "เครื่อง…/เครื่องบิน…",
        my: "စက်/လေယာဉ် …",
        km: "ម៉ាស៊ីន/យន្តហោះ …",
      },
      furigana: [
        {
          rb: "～機",
          rt: "～き",
        },
      ],
      kanjiInfo: [
        {
          char: "機",
          on: ["キ"],
          kun: ["はた"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1524,
      kanji: "きっかけ",
      reading: "きっかけ",
      meanings: {
        ja: "手がかり・きっかけ",
        en: "trigger; chance; cue",
        zh: "契机；机会",
        tw: "契機；契機",
        ko: "계기; 실마리",
        vi: "cái cớ; dịp",
        th: "จุดเริ่ม/โอกาส",
        my: "အခါအခွင့်",
        km: "ឱកាស; ចំណុចចាប់ផ្តើម",
      },
      furigana: [
        {
          rb: "きっかけ",
          rt: "きっかけ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1525,
      kanji: "～気味",
      reading: "～ぎみ",
      meanings: {
        ja: "やや…の傾向",
        en: "a little; somewhat …-ish",
        zh: "略带…；有点…",
        tw: "略帶…；有點…",
        ko: "…기미; 다소 …한",
        vi: "hơi …; có vẻ …",
        th: "ออกจะ…/นิด ๆ",
        my: "… ပါးပါး",
        km: "បន្តិច…",
      },
      furigana: [
        {
          rb: "～気味",
          rt: "～ぎみ",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1526,
      kanji: "～教",
      reading: "～きょう",
      meanings: {
        ja: "宗教・～教",
        en: "religion; sect",
        zh: "…教",
        tw: "…教",
        ko: "…교(敎)",
        vi: "tôn giáo …",
        th: "ศาสนา…",
        my: "ဘာသာ …",
        km: "សាសនា …",
      },
      furigana: [
        {
          rb: "～教",
          rt: "～きょう",
        },
      ],
      kanjiInfo: [
        {
          char: "教",
          on: ["キョウ"],
          kun: ["おし.える", "おそ.わる"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1527,
      kanji: "～行",
      reading: "～ぎょう",
      meanings: {
        ja: "行（行数）",
        en: "line (of text)",
        zh: "…行（行数）",
        tw: "…行（行數）",
        ko: "…행(行)",
        vi: "dòng …",
        th: "บรรทัดที่ …",
        my: "စာကြောင်း …",
        km: "ជួរដេក …",
      },
      furigana: [
        {
          rb: "～行",
          rt: "～ぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1528,
      kanji: "～業",
      reading: "～ぎょう",
      meanings: {
        ja: "企業・産業",
        en: "business; industry",
        zh: "…业/产业",
        tw: "…業/產業",
        ko: "…업(業)",
        vi: "ngành nghề …",
        th: "อุตสาหกรรม…",
        my: "လုပ်ငန်း…",
        km: "វិស័យ …",
      },
      furigana: [
        {
          rb: "～業",
          rt: "～ぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1529,
      kanji: "共産～",
      reading: "きょうさん～",
      meanings: {
        ja: "共産主義の/共産～",
        en: "communist …",
        zh: "共产…",
        tw: "共產…",
        ko: "공산 …",
        vi: "cộng sản …",
        th: "คอมมิวนิสต์…",
        my: "ကမ္မူမြင့် …",
        km: "កុម្មុយនិស្ត …",
      },
      furigana: [
        {
          rb: "共産～",
          rt: "きょうさん～",
        },
      ],
      kanjiInfo: [
        {
          char: "共",
          on: ["キョウ"],
          kun: ["とも", "とも.に", "-ども"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1530,
      kanji: "～きる",
      reading: "～きる",
      meanings: {
        ja: "完全に…する",
        en: "do completely; to the end",
        zh: "彻底…；完全…",
        tw: "徹底…；完全…",
        ko: "완전히 …해내다",
        vi: "làm hết; làm trọn",
        th: "ทำจนหมด/จนสุด",
        my: "အပြည့်အဝ … လုပ်",
        km: "ធ្វើអស់សព្វគ្រប់",
      },
      furigana: [
        {
          rb: "～きる",
          rt: "～きる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1531,
      kanji: "～切れ",
      reading: "～きれ",
      meanings: {
        ja: "切れ端/品切れ",
        en: "slice/piece; running out",
        zh: "切片；断货",
        tw: "切片；缺貨",
        ko: "조각; 품절",
        vi: "miếng; hết hàng",
        th: "ชิ้น; ของหมด",
        my: "အဆစ်/ကုန်ခမ်း",
        km: "បំណែក; ផលិតផលអស់",
      },
      furigana: [
        {
          rb: "～切れ",
          rt: "～きれ",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1532,
      kanji: "気を付ける",
      reading: "きをつける",
      meanings: {
        ja: "注意する",
        en: "to be careful; pay attention",
        zh: "注意；当心",
        tw: "注意；當心",
        ko: "조심하다; 주의하다",
        vi: "chú ý; cẩn thận",
        th: "ระวัง",
        my: "ဂရုစိုက်",
        km: "ប្រយ័ត្ន",
      },
      furigana: [
        {
          rb: "気を付ける",
          rt: "きをつける",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1533,
      kanji: "空～",
      reading: "くう～",
      meanings: {
        ja: "空・空中の/空（から）の",
        en: "air/sky …; empty …",
        zh: "空中…；空（空的）…",
        tw: "空中…；空（空的）…",
        ko: "공중-/공(空)…",
        vi: "không/ trên không …; rỗng …",
        th: "อากาศ/ท้องฟ้า…; ว่าง/เปล่า…",
        my: "လေ/မဲ …; ဗလာ …",
        km: "អាកាស/មេឃ …; ទទេ …",
      },
      furigana: [
        {
          rb: "空～",
          rt: "くう～",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1484,
      kanji: "おかまいなく",
      reading: "おかまいなく",
      meanings: {
        ja: "どうぞお気遣いなく",
        en: "please don’t bother (about me)",
        zh: "不必麻烦",
        tw: "不用麻煩",
        ko: "신경 쓰지 마세요",
        vi: "xin đừng bận tâm",
        th: "ไม่ต้องลำบากนะ",
        my: "စိတ်မချရပါနှင့်",
        km: "កុំខ្វល់ខ្វាយទេ",
      },
      furigana: [
        {
          rb: "おかまいなく",
          rt: "おかまいなく",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1485,
      kanji: "お気の毒に",
      reading: "おきのどくに",
      meanings: {
        ja: "お気の毒です",
        en: "my sympathies; I’m sorry to hear that",
        zh: "真不幸/我表示同情",
        tw: "真不幸／我表示同情",
        ko: "안됐다; 유감입니다",
        vi: "thật đáng tiếc",
        th: "น่าเห็นใจจัง",
        my: "သနားကြင်နာတယ်",
        km: "សោកស្តាយណាស់",
      },
      furigana: [
        {
          rb: "お気の毒に",
          rt: "おきのどくに",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "毒",
          on: ["ドク"],
          kun: [],
          strokes: 8,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1486,
      kanji: "お元気で",
      reading: "おげんきで",
      meanings: {
        ja: "お元気で（別れの挨拶）",
        en: "take care; stay well",
        zh: "保重",
        tw: "保重",
        ko: "건강하세요",
        vi: "giữ gìn sức khỏe nhé",
        th: "ดูแลสุขภาพด้วยนะ",
        my: "ကျန်းမာပါစေ",
        km: "សុខភាពល្អៗ",
      },
      furigana: [
        {
          rb: "お元気で",
          rt: "おげんきで",
        },
      ],
      kanjiInfo: [
        {
          char: "元",
          on: ["ゲン", "ガン"],
          kun: ["もと"],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1487,
      kanji: "お邪魔します",
      reading: "おじゃまします",
      meanings: {
        ja: "（訪問時の挨拶）失礼します",
        en: "excuse me for intruding",
        zh: "打扰了",
        tw: "打擾了",
        ko: "실례합니다(방문 인사)",
        vi: "xin phép làm phiền",
        th: "ขออนุญาตรบกวน",
        my: "အဆင်မပြေတာရှိရင်တဆင့်",
        km: "សុំទោស ខ្ញុំរំខាន",
      },
      furigana: [
        {
          rb: "お邪魔します",
          rt: "おじゃまします",
        },
      ],
      kanjiInfo: [
        {
          char: "邪",
          on: ["ジャ"],
          kun: ["よこし.ま"],
          strokes: 8,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
        {
          char: "魔",
          on: ["マ"],
          kun: [],
          strokes: 21,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1488,
      kanji: "お世話になりました",
      reading: "おせわになりました",
      meanings: {
        ja: "お世話になりました（感謝）",
        en: "thank you for your help",
        zh: "承蒙照顾",
        tw: "承蒙照顧",
        ko: "신세 많이졌습니다",
        vi: "cảm ơn đã giúp đỡ",
        th: "ขอบคุณที่ดูแล",
        my: "ကူညီပေးသဖြင့် ကျေးဇူးတင်ပါတယ်",
        km: "អរគុណចំពោះការថែទាំ",
      },
      furigana: [
        {
          rb: "お世話になりました",
          rt: "おせわになりました",
        },
      ],
      kanjiInfo: [
        {
          char: "世",
          on: ["セイ", "セ", "ソウ"],
          kun: ["よ"],
          strokes: 5,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
        {
          char: "話",
          on: ["ワ"],
          kun: ["はな.す", "はなし"],
          strokes: 13,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1489,
      kanji: "お大事に",
      reading: "おだいじに",
      meanings: {
        ja: "（病人へ）お大事に",
        en: "take care of yourself (get well)",
        zh: "请多保重",
        tw: "請多保重",
        ko: "몸조심하세요",
        vi: "giữ gìn sức khỏe nhé",
        th: "หายไว ๆ นะ",
        my: "အ rápido အနားယူပါ",
        km: "សូមជាសះស្បើយឆាប់ៗ",
      },
      furigana: [
        {
          rb: "お大事に",
          rt: "おだいじに",
        },
      ],
      kanjiInfo: [
        {
          char: "大",
          on: ["ダイ", "タイ"],
          kun: ["おお-", "おお.きい", "-おお.いに"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "事",
          on: ["ジ", "ズ"],
          kun: ["こと", "つか.う", "つか.える"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1490,
      kanji: "お願いします",
      reading: "おねがいします",
      meanings: {
        ja: "お願いします（依頼）",
        en: "please; I request",
        zh: "拜托/麻烦了",
        tw: "拜託／麻煩了",
        ko: "부탁합니다",
        vi: "làm ơn",
        th: "กรุณาด้วย",
        my: "ကျေးဇူးပြု၍",
        km: "សូមបម្រុង",
      },
      furigana: [
        {
          rb: "お願いします",
          rt: "おねがいします",
        },
      ],
      kanjiInfo: [
        {
          char: "願",
          on: ["ガン"],
          kun: ["ねが.う", "-ねがい"],
          strokes: 19,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1491,
      kanji: "おはよう",
      reading: "おはよう",
      meanings: {
        ja: "おはよう（挨拶）",
        en: "good morning",
        zh: "早安",
        tw: "早安",
        ko: "좋은 아침",
        vi: "chào buổi sáng",
        th: "สวัสดีตอนเช้า",
        my: "မင်္ဂလာနံနက်ခင်းပါ",
        km: "អរុណសួស្តី",
      },
      furigana: [
        {
          rb: "おはよう",
          rt: "おはよう",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1492,
      kanji: "お待たせしました",
      reading: "おまたせしました",
      meanings: {
        ja: "お待たせしました",
        en: "thank you for waiting",
        zh: "让您久等了",
        tw: "讓您久等了",
        ko: "기다리게 해서 죄송합니다",
        vi: "xin lỗi đã để chờ",
        th: "ขอโทษที่ให้รอ",
        my: "စောင့်စေလိုက်တာတောင်းပန်ပါတယ်",
        km: "សូមទោស ដែលឲ្យរង់ចាំ",
      },
      furigana: [
        {
          rb: "お待たせしました",
          rt: "おまたせしました",
        },
      ],
      kanjiInfo: [
        {
          char: "待",
          on: ["タイ"],
          kun: ["ま.つ", "-ま.ち"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1493,
      kanji: "お待ちください",
      reading: "おまちください",
      meanings: {
        ja: "少々お待ちください",
        en: "please wait a moment",
        zh: "请稍等",
        tw: "請稍等",
        ko: "잠시만 기다려 주세요",
        vi: "xin vui lòng đợi",
        th: "กรุณารอสักครู่",
        my: "ခဏစောင့်ပါ",
        km: "សូមរង់ចាំអញ្ចឹង",
      },
      furigana: [
        {
          rb: "お待ちください",
          rt: "おまちください",
        },
      ],
      kanjiInfo: [
        {
          char: "待",
          on: ["タイ"],
          kun: ["ま.つ", "-ま.ち"],
          strokes: 9,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1494,
      kanji: "おまちどおさま",
      reading: "おまちどおさま",
      meanings: {
        ja: "お待ちどうさま",
        en: "sorry to keep you waiting",
        zh: "久等了",
        tw: "久等了",
        ko: "오래 기다리셨습니다",
        vi: "đã để anh/chị đợi lâu",
        th: "ให้รอนาน ขอโทษด้วย",
        my: "စောင့်နေရက်ရတော့",
        km: "រង់ចាំយូរហើយ",
      },
      furigana: [
        {
          rb: "おまちどおさま",
          rt: "おまちどおさま",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1495,
      kanji: "おめでたい",
      reading: "おめでたい",
      meanings: {
        ja: "めでたい・祝い事にふさわしい",
        en: "auspicious; happy (occasion)",
        zh: "可喜可贺的",
        tw: "可喜可賀的",
        ko: "경사스러운",
        vi: "đáng mừng",
        th: "น่ายินดี",
        my: "မျက်နှာသာကောင်းသော",
        km: "មានសេចក្ដីសុខ",
      },
      furigana: [
        {
          rb: "おめでたい",
          rt: "おめでたい",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1496,
      kanji: "おやつ",
      reading: "おやつ",
      meanings: {
        ja: "間食・おやつ",
        en: "snack",
        zh: "点心/零食",
        tw: "點心／零食",
        ko: "간식",
        vi: "đồ ăn vặt",
        th: "ของว่าง",
        my: "အလတ်စားစားစရာ",
        km: "អាហារសម្រន់",
      },
      furigana: [
        {
          rb: "おやつ",
          rt: "おやつ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1497,
      kanji: "女の人",
      reading: "おんなのひと",
      meanings: {
        ja: "女性",
        en: "woman",
        zh: "女人",
        tw: "女人",
        ko: "여자",
        vi: "phụ nữ",
        th: "ผู้หญิง",
        my: "မိန်းမ",
        km: "ស្ត្រី",
      },
      furigana: [
        {
          rb: "女の人",
          rt: "おんなのひと",
        },
      ],
      kanjiInfo: [
        {
          char: "女",
          on: ["ジョ", "ニョ", "ニョウ"],
          kun: ["おんな", "め"],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "人",
          on: ["ジン", "ニン"],
          kun: ["ひと", "-り", "-と"],
          strokes: 2,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1498,
      kanji: "～日",
      reading: "～か",
      meanings: {
        ja: "月日（ついたち・みっか等）の“～日”",
        en: "the …th day of month (–ka)",
        zh: "几号（日期后缀）",
        tw: "幾號（日期後綴）",
        ko: "…일(날짜 접미사)",
        vi: "ngày … (trong tháng)",
        th: "วันที่ …",
        my: "လရက် …",
        km: "ថ្ងៃទី …",
      },
      furigana: [
        {
          rb: "～日",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "日",
          on: ["ニチ", "ジツ"],
          kun: ["ひ", "-び", "-か"],
          strokes: 4,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1499,
      kanji: "～下",
      reading: "～か",
      meanings: {
        ja: "下位・下部を表す",
        en: "lower; under … (suffix)",
        zh: "下、次等",
        tw: "下、次等",
        ko: "하(下)·아래 …",
        vi: "hạ/ở dưới …",
        th: "ส่วนล่าง/ชั้นล่าง",
        my: "အောက်ပိုင်း …",
        km: "កម្រិតក្រោម …",
      },
      furigana: [
        {
          rb: "～下",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "下",
          on: ["カ", "ゲ"],
          kun: [
            "した",
            "しも",
            "もと",
            "さ.げる",
            "さ.がる",
            "くだ.る",
            "くだ.り",
            "くだ.す",
            "-くだ.す",
            "くだ.さる",
            "お.ろす",
            "お.りる",
          ],
          strokes: 3,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1500,
      kanji: "～化",
      reading: "～か",
      meanings: {
        ja: "…化（～になる/する）",
        en: "–ization; change into …",
        zh: "…化",
        tw: "…化",
        ko: "…화",
        vi: "… hoá",
        th: "…ควบ/กลายเป็น",
        my: "… တော့/ဖြစ်",
        km: "… ការ​បម្លែង",
      },
      furigana: [
        {
          rb: "～化",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "化",
          on: ["カ", "ケ"],
          kun: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
          strokes: 4,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1501,
      kanji: "～科",
      reading: "～か",
      meanings: {
        ja: "学科・診療科など",
        en: "department; subject",
        zh: "科（學科/科室）",
        tw: "科（學科／科別）",
        ko: "과(科)",
        vi: "khoa; bộ môn",
        th: "แผนก/สาขา",
        my: "ဌာန/ဘာသာရပ်",
        km: "មហាវិទ្យាល័យ/មន្ទីរ",
      },
      furigana: [
        {
          rb: "～科",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "科",
          on: ["カ"],
          kun: [],
          strokes: 9,
          grade: 2,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1502,
      kanji: "～歌",
      reading: "～か",
      meanings: {
        ja: "歌（校歌・国歌など）",
        en: "song (e.g., school anthem)",
        zh: "…歌",
        tw: "…歌",
        ko: "…가(歌)",
        vi: "bài hát …",
        th: "เพลง …",
        my: "… တေး",
        km: "ចម្រៀង …",
      },
      furigana: [
        {
          rb: "～歌",
          rt: "～か",
        },
      ],
      kanjiInfo: [
        {
          char: "歌",
          on: ["カ"],
          kun: ["うた", "うた.う"],
          strokes: 14,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1503,
      kanji: "～画",
      reading: "～が",
      meanings: {
        ja: "絵・映画等を表す",
        en: "picture/film …",
        zh: "…画/画面",
        tw: "…畫",
        ko: "…화(畫)",
        vi: "hình/ảnh/phim …",
        th: "ภาพ/ภาพยนตร์ …",
        my: "ရုပ်ပုံ/ရုပ်ရှင် …",
        km: "រូប/ភាពយន្ត …",
      },
      furigana: [
        {
          rb: "～画",
          rt: "～が",
        },
      ],
      kanjiInfo: [
        {
          char: "画",
          on: ["ガ", "カク", "エ", "カイ"],
          kun: ["えが.く", "かく.する", "かぎ.る", "はかりごと", "はか.る"],
          strokes: 8,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1504,
      kanji: "外～",
      reading: "がい～",
      meanings: {
        ja: "外・外国の意",
        en: "outer; foreign …",
        zh: "外/国外 …",
        tw: "外／國外 …",
        ko: "외-/대외 …",
        vi: "ngoại/ở ngoài …",
        th: "นอก/ต่างประเทศ …",
        my: "ပြင်/နိုင်ငံပြင် …",
        km: "ក្រៅ/បរទេស …",
      },
      furigana: [
        {
          rb: "外～",
          rt: "がい～",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1505,
      kanji: "～外",
      reading: "～がい",
      meanings: {
        ja: "範囲外・区域外",
        en: "outside; out of …",
        zh: "…以外/…之外",
        tw: "…以外",
        ko: "… 외; … 밖",
        vi: "ngoài …",
        th: "นอกเหนือ …",
        my: "… ယဟုတ်ခြင်းပြင်ပ",
        km: "ក្រៅពី …",
      },
      furigana: [
        {
          rb: "～外",
          rt: "～がい",
        },
      ],
      kanjiInfo: [
        {
          char: "外",
          on: ["ガイ", "ゲ"],
          kun: ["そと", "ほか", "はず.す", "はず.れる", "と-"],
          strokes: 5,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1506,
      kanji: "各～",
      reading: "かく～",
      meanings: {
        ja: "各・それぞれの",
        en: "each; every …",
        zh: "各…",
        tw: "各…",
        ko: "각 …",
        vi: "các …; mỗi …",
        th: "แต่ละ …",
        my: "တစ်ခုချင်းစီ …",
        km: "នីមួយៗ …",
      },
      furigana: [
        {
          rb: "各～",
          rt: "かく～",
        },
      ],
      kanjiInfo: [
        {
          char: "各",
          on: ["カク"],
          kun: ["おのおの"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1507,
      kanji: "かしこまりました",
      reading: "かしこまりました",
      meanings: {
        ja: "承知しました（丁寧）",
        en: "certainly; understood",
        zh: "明白了（敬语）",
        tw: "明白了（敬語）",
        ko: "알겠습니다",
        vi: "vâng, tôi rõ",
        th: "รับทราบครับ/ค่ะ",
        my: "နားလည်ပြီးပါသည်",
        km: "យល់ព្រមហើយ",
      },
      furigana: [
        {
          rb: "かしこまりました",
          rt: "かしこまりました",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1508,
      kanji: "かじる",
      reading: "かじる",
      meanings: {
        ja: "かじる・少しかじる",
        en: "to nibble; to dabble in",
        zh: "啃；略懂",
        tw: "啃；略懂",
        ko: "깨물다; 조금 배우다",
        vi: "gặm; biết lõm bõm",
        th: "แทะ; รู้แบบผิวเผิน",
        my: "နည်းနည်းသာ လေ့လာသည်",
        km: "ខាំ; ស្គាល់តិចតួច",
      },
      furigana: [
        {
          rb: "かじる",
          rt: "かじる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1509,
      kanji: "～がち",
      reading: "～がち",
      meanings: {
        ja: "…しがち・傾向がある",
        en: "tending to; apt to …",
        zh: "容易…；常常…",
        tw: "容易…；常常…",
        ko: "…하는 경향이 있다",
        vi: "hay …; có xu hướng …",
        th: "มักจะ …",
        my: "… စရာများတတ်",
        km: "មានទំនោរ …",
      },
      furigana: [
        {
          rb: "～がち",
          rt: "～がち",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1510,
      kanji: "兼ねる",
      reading: "かねる",
      meanings: {
        ja: "…しかねる（丁寧否定補助）",
        en: "to be unable to; cannot",
        zh: "难以…；不能…",
        tw: "難以…；不能…",
        ko: "…하기 어렵다",
        vi: "khó mà …; không thể",
        th: "ไม่อาจ … ได้",
        my: "လုပ်ဖို့နိုင်ခြင်းမရှိ",
        km: "មិនអាច…បាន",
      },
      furigana: [
        {
          rb: "兼ねる",
          rt: "かねる",
        },
      ],
      kanjiInfo: [
        {
          char: "兼",
          on: ["ケン"],
          kun: ["か.ねる", "-か.ねる"],
          strokes: 10,
          grade: 8,
          jlpt: 1,
          radical: null,
        },
      ],
    },
    {
      id: 1511,
      kanji: "かび（～がはえる）",
      reading: "かび (～がはえる)",
      meanings: {
        ja: "黴（かび）が生える",
        en: "mold; (mold) grows",
        zh: "霉/长霉",
        tw: "霉／發霉",
        ko: "곰팡이(가 피다)",
        vi: "mốc; (bị) mốc",
        th: "เชื้อรา; เกิดรา",
        my: "ခုံပိုး/ဖုန် (ပေါက်)",
        km: "ពុល/ផ្សិត (កើត)",
      },
      furigana: [
        {
          rb: "かび（～がはえる）",
          rt: "かび （～がはえる）",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1512,
      kanji: "構いません",
      reading: "かまいません",
      meanings: {
        ja: "差し支えありません",
        en: "no problem; I don’t mind",
        zh: "没关系",
        tw: "沒關係",
        ko: "괜찮습니다",
        vi: "không sao",
        th: "ไม่เป็นไร",
        my: "မစိုးရိမ်ပါ",
        km: "មិនអីទេ",
      },
      furigana: [
        {
          rb: "構いません",
          rt: "かまいません",
        },
      ],
      kanjiInfo: [
        {
          char: "構",
          on: ["コウ"],
          kun: ["かま.える", "かま.う"],
          strokes: 14,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1513,
      kanji: "からかう",
      reading: "からかう",
      meanings: {
        ja: "からかう・冷やかす",
        en: "to tease; make fun of",
        zh: "戏弄；取笑",
        tw: "戲弄；取笑",
        ko: "놀리다",
        vi: "trêu chọc",
        th: "ล้อเล่น",
        my: "ကလိကလွှာလုပ်",
        km: "លេងកំប្លែង",
      },
      furigana: [
        {
          rb: "からかう",
          rt: "からかう",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1514,
      kanji: "かるた",
      reading: "かるた",
      meanings: {
        ja: "日本のカード遊び",
        en: "karuta (Japanese card game)",
        zh: "歌留多（日本纸牌）",
        tw: "歌留多（日本紙牌）",
        ko: "가루타",
        vi: "bài karuta",
        th: "การ์ดเกมคารุตะ",
        my: "ကာရူတား ကစားပွဲ",
        km: "ល្បែងកាត Karuta",
      },
      furigana: [
        {
          rb: "かるた",
          rt: "かるた",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1515,
      kanji: "～刊",
      reading: "～かん",
      meanings: {
        ja: "刊行物・月刊/週刊など",
        en: "–edition; –publication",
        zh: "…刊",
        tw: "…刊",
        ko: "…간(刊)",
        vi: "… san (báo/kỳ)",
        th: "…ฉบับ/…ราย",
        my: "… စာမ刊",
        km: "… បោះពុម្ព",
      },
      furigana: [
        {
          rb: "～刊",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "刊",
          on: ["カン"],
          kun: [],
          strokes: 5,
          grade: 5,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1516,
      kanji: "～間",
      reading: "～かん",
      meanings: {
        ja: "期間・…の間",
        en: "for … (period); during …",
        zh: "…期间",
        tw: "…期間",
        ko: "…간(間)",
        vi: "trong …; suốt …",
        th: "ช่วง…",
        my: "… အတွင်း",
        km: "អំឡុង …",
      },
      furigana: [
        {
          rb: "～間",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "間",
          on: ["カン", "ケン"],
          kun: ["あいだ", "ま", "あい"],
          strokes: 12,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1517,
      kanji: "～巻",
      reading: "～かん",
      meanings: {
        ja: "巻（本の巻数）",
        en: "volume (of books)",
        zh: "…卷",
        tw: "…卷",
        ko: "…권(卷)",
        vi: "quyển/tập …",
        th: "เล่มที่ …",
        my: "အုပ်/တွဲ …",
        km: "ភាគ …",
      },
      furigana: [
        {
          rb: "～巻",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "巻",
          on: ["カン", "ケン"],
          kun: ["ま.く", "まき", "ま.き"],
          strokes: 9,
          grade: 6,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1518,
      kanji: "～館",
      reading: "～かん",
      meanings: {
        ja: "館（図書館・美術館など）",
        en: "–hall; –building; –museum",
        zh: "…馆",
        tw: "…館",
        ko: "…관(館)",
        vi: "… quán/viện",
        th: "…館/…พิพิธภัณฑ์",
        my: "… ထောင်/ဗဟိုဌာန",
        km: "… សារមន្ទីរ/វិទ្យាស្ថាន",
      },
      furigana: [
        {
          rb: "～館",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "館",
          on: ["カン"],
          kun: ["やかた", "たて"],
          strokes: 16,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1519,
      kanji: "～感",
      reading: "～かん",
      meanings: {
        ja: "感覚・感じ",
        en: "sense; feeling of …",
        zh: "…感",
        tw: "…感",
        ko: "…감(感)",
        vi: "cảm giác …",
        th: "ความรู้สึก…",
        my: "ခံစားချက် …",
        km: "អារម្មណ៍ …",
      },
      furigana: [
        {
          rb: "～感",
          rt: "～かん",
        },
      ],
      kanjiInfo: [
        {
          char: "感",
          on: ["カン"],
          kun: [],
          strokes: 13,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1520,
      kanji: "乾杯",
      reading: "かんぱい",
      meanings: {
        ja: "乾杯！（発声）",
        en: "cheers!",
        zh: "干杯！",
        tw: "乾杯！",
        ko: "건배!",
        vi: "cạn ly!",
        th: "ชนแก้ว!",
        my: "ကန်ပိုင်!",
        km: "ចៀសកែវ!",
      },
      furigana: [
        {
          rb: "乾杯",
          rt: "かんぱい",
        },
      ],
      kanjiInfo: [
        {
          char: "乾",
          on: ["カン", "ケン"],
          kun: ["かわ.く", "かわ.かす", "ほ.す", "ひ.る", "いぬい"],
          strokes: 11,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
        {
          char: "杯",
          on: ["ハイ"],
          kun: ["さかずき"],
          strokes: 8,
          grade: 8,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1521,
      kanji: "～期",
      reading: "～き",
      meanings: {
        ja: "時期・期間",
        en: "period; term",
        zh: "…期",
        tw: "…期",
        ko: "…기(期)",
        vi: "thời kỳ …",
        th: "ช่วง…/ระยะ…",
        my: "ကာလ …",
        km: "រដូវ/អំឡុង…",
      },
      furigana: [
        {
          rb: "～期",
          rt: "～き",
        },
      ],
      kanjiInfo: [
        {
          char: "期",
          on: ["キ", "ゴ"],
          kun: [],
          strokes: 12,
          grade: 3,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1522,
      kanji: "～器",
      reading: "～き",
      meanings: {
        ja: "器具・機器",
        en: "utensil; device",
        zh: "…器",
        tw: "…器",
        ko: "…기(器)",
        vi: "dụng cụ …",
        th: "อุปกรณ์…",
        my: "ပစ္စည်း …",
        km: "ឧបករណ៍ …",
      },
      furigana: [
        {
          rb: "～器",
          rt: "～き",
        },
      ],
      kanjiInfo: [
        {
          char: "器",
          on: ["キ"],
          kun: ["うつわ"],
          strokes: 15,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1523,
      kanji: "～機",
      reading: "～き",
      meanings: {
        ja: "機械/飛行機など",
        en: "machine; aircraft",
        zh: "…机/机器/飞机",
        tw: "…機（機械/飛機）",
        ko: "…기(機)",
        vi: "máy/phi cơ …",
        th: "เครื่อง…/เครื่องบิน…",
        my: "စက်/လေယာဉ် …",
        km: "ម៉ាស៊ីន/យន្តហោះ …",
      },
      furigana: [
        {
          rb: "～機",
          rt: "～き",
        },
      ],
      kanjiInfo: [
        {
          char: "機",
          on: ["キ"],
          kun: ["はた"],
          strokes: 16,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1524,
      kanji: "きっかけ",
      reading: "きっかけ",
      meanings: {
        ja: "手がかり・きっかけ",
        en: "trigger; chance; cue",
        zh: "契机；机会",
        tw: "契機；契機",
        ko: "계기; 실마리",
        vi: "cái cớ; dịp",
        th: "จุดเริ่ม/โอกาส",
        my: "အခါအခွင့်",
        km: "ឱកាស; ចំណុចចាប់ផ្តើម",
      },
      furigana: [
        {
          rb: "きっかけ",
          rt: "きっかけ",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1525,
      kanji: "～気味",
      reading: "～ぎみ",
      meanings: {
        ja: "やや…の傾向",
        en: "a little; somewhat …-ish",
        zh: "略带…；有点…",
        tw: "略帶…；有點…",
        ko: "…기미; 다소 …한",
        vi: "hơi …; có vẻ …",
        th: "ออกจะ…/นิด ๆ",
        my: "… ပါးပါး",
        km: "បន្តិច…",
      },
      furigana: [
        {
          rb: "～気味",
          rt: "～ぎみ",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "味",
          on: ["ミ"],
          kun: ["あじ", "あじ.わう"],
          strokes: 8,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1526,
      kanji: "～教",
      reading: "～きょう",
      meanings: {
        ja: "宗教・～教",
        en: "religion; sect",
        zh: "…教",
        tw: "…教",
        ko: "…교(敎)",
        vi: "tôn giáo …",
        th: "ศาสนา…",
        my: "ဘာသာ …",
        km: "សាសនា …",
      },
      furigana: [
        {
          rb: "～教",
          rt: "～きょう",
        },
      ],
      kanjiInfo: [
        {
          char: "教",
          on: ["キョウ"],
          kun: ["おし.える", "おそ.わる"],
          strokes: 11,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1527,
      kanji: "～行",
      reading: "～ぎょう",
      meanings: {
        ja: "行（行数）",
        en: "line (of text)",
        zh: "…行（行数）",
        tw: "…行（行數）",
        ko: "…행(行)",
        vi: "dòng …",
        th: "บรรทัดที่ …",
        my: "စာကြောင်း …",
        km: "ជួរដេក …",
      },
      furigana: [
        {
          rb: "～行",
          rt: "～ぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "行",
          on: ["コウ", "ギョウ", "アン"],
          kun: [
            "い.く",
            "ゆ.く",
            "-ゆ.き",
            "-ゆき",
            "-い.き",
            "-いき",
            "おこな.う",
            "おこ.なう",
          ],
          strokes: 6,
          grade: 2,
          jlpt: 4,
          radical: null,
        },
      ],
    },
    {
      id: 1528,
      kanji: "～業",
      reading: "～ぎょう",
      meanings: {
        ja: "企業・産業",
        en: "business; industry",
        zh: "…业/产业",
        tw: "…業/產業",
        ko: "…업(業)",
        vi: "ngành nghề …",
        th: "อุตสาหกรรม…",
        my: "လုပ်ငန်း…",
        km: "វិស័យ …",
      },
      furigana: [
        {
          rb: "～業",
          rt: "～ぎょう",
        },
      ],
      kanjiInfo: [
        {
          char: "業",
          on: ["ギョウ", "ゴウ"],
          kun: ["わざ"],
          strokes: 13,
          grade: 3,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1529,
      kanji: "共産～",
      reading: "きょうさん～",
      meanings: {
        ja: "共産主義の/共産～",
        en: "communist …",
        zh: "共产…",
        tw: "共產…",
        ko: "공산 …",
        vi: "cộng sản …",
        th: "คอมมิวนิสต์…",
        my: "ကမ္မူမြင့် …",
        km: "កុម្មុយនិស្ត …",
      },
      furigana: [
        {
          rb: "共産～",
          rt: "きょうさん～",
        },
      ],
      kanjiInfo: [
        {
          char: "共",
          on: ["キョウ"],
          kun: ["とも", "とも.に", "-ども"],
          strokes: 6,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
        {
          char: "産",
          on: ["サン"],
          kun: ["う.む", "う.まれる", "うぶ-", "む.す"],
          strokes: 11,
          grade: 4,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1530,
      kanji: "～きる",
      reading: "～きる",
      meanings: {
        ja: "完全に…する",
        en: "do completely; to the end",
        zh: "彻底…；完全…",
        tw: "徹底…；完全…",
        ko: "완전히 …해내다",
        vi: "làm hết; làm trọn",
        th: "ทำจนหมด/จนสุด",
        my: "အပြည့်အဝ … လုပ်",
        km: "ធ្វើអស់សព្វគ្រប់",
      },
      furigana: [
        {
          rb: "～きる",
          rt: "～きる",
        },
      ],
      kanjiInfo: [],
    },
    {
      id: 1531,
      kanji: "～切れ",
      reading: "～きれ",
      meanings: {
        ja: "切れ端/品切れ",
        en: "slice/piece; running out",
        zh: "切片；断货",
        tw: "切片；缺貨",
        ko: "조각; 품절",
        vi: "miếng; hết hàng",
        th: "ชิ้น; ของหมด",
        my: "အဆစ်/ကုန်ခမ်း",
        km: "បំណែក; ផលិតផលអស់",
      },
      furigana: [
        {
          rb: "～切れ",
          rt: "～きれ",
        },
      ],
      kanjiInfo: [
        {
          char: "切",
          on: ["セツ", "サイ"],
          kun: [
            "き.る",
            "-き.る",
            "き.り",
            "-き.り",
            "-ぎ.り",
            "き.れる",
            "-き.れる",
            "き.れ",
            "-き.れ",
            "-ぎ.れ",
          ],
          strokes: 4,
          grade: 2,
          jlpt: 3,
          radical: null,
        },
      ],
    },
    {
      id: 1532,
      kanji: "気を付ける",
      reading: "きをつける",
      meanings: {
        ja: "注意する",
        en: "to be careful; pay attention",
        zh: "注意；当心",
        tw: "注意；當心",
        ko: "조심하다; 주의하다",
        vi: "chú ý; cẩn thận",
        th: "ระวัง",
        my: "ဂရုစိုက်",
        km: "ប្រយ័ត្ន",
      },
      furigana: [
        {
          rb: "気を付ける",
          rt: "きをつける",
        },
      ],
      kanjiInfo: [
        {
          char: "気",
          on: ["キ", "ケ"],
          kun: ["いき", "き"],
          strokes: 6,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
        {
          char: "付",
          on: ["フ"],
          kun: [
            "つ.ける",
            "-つ.ける",
            "-づ.ける",
            "つ.け",
            "つ.け-",
            "-つ.け",
            "-づ.け",
            "-づけ",
            "つ.く",
            "-づ.く",
            "つ.き",
            "-つ.き",
            "-つき",
            "-づ.き",
            "-づき",
          ],
          strokes: 5,
          grade: 4,
          jlpt: 2,
          radical: null,
        },
      ],
    },
    {
      id: 1533,
      kanji: "空～",
      reading: "くう～",
      meanings: {
        ja: "空・空中の/空（から）の",
        en: "air/sky …; empty …",
        zh: "空中…；空（空的）…",
        tw: "空中…；空（空的）…",
        ko: "공중-/공(空)…",
        vi: "không/ trên không …; rỗng …",
        th: "อากาศ/ท้องฟ้า…; ว่าง/เปล่า…",
        my: "လေ/မဲ …; ဗလာ …",
        km: "អាកាស/មេឃ …; ទទេ …",
      },
      furigana: [
        {
          rb: "空～",
          rt: "くう～",
        },
      ],
      kanjiInfo: [
        {
          char: "空",
          on: ["クウ"],
          kun: [
            "そら",
            "あ.く",
            "あ.き",
            "あ.ける",
            "から",
            "す.く",
            "す.かす",
            "むな.しい",
          ],
          strokes: 8,
          grade: 1,
          jlpt: 4,
          radical: null,
        },
      ],
    },
  ],
};
