export const n5part_nouns2 = {
  Lesson2: [
    { id: 1, kanji: "駅", reading: "えき", meanings: { id: "stasiun", en: "station", zh: "车站", tw: "車站" } },
    { id: 2, kanji: "バス停", reading: "バスてい", meanings: { id: "halte bus", en: "bus stop", zh: "公交车站", tw: "公車站" } },
    { id: 3, kanji: "公園", reading: "こうえん", meanings: { id: "taman", en: "park", zh: "公园", tw: "公園" } },
    { id: 4, kanji: "神社", reading: "じんじゃ", meanings: { id: "kuil Shinto", en: "Shinto shrine", zh: "神社", tw: "神社" } },
    { id: 5, kanji: "お寺", reading: "おてら", meanings: { id: "kuil Buddha", en: "temple", zh: "寺庙", tw: "寺廟" } },
    { id: 6, kanji: "道", reading: "みち", meanings: { id: "jalan", en: "road; street", zh: "道路", tw: "道路" } },
    { id: 7, kanji: "家", reading: "いえ", meanings: { id: "rumah", en: "house", zh: "家", tw: "家" } },
    { id: 8, kanji: "部屋", reading: "へや", meanings: { id: "kamar", en: "room", zh: "房间", tw: "房間" } },
    { id: 9, kanji: "台所", reading: "だいどころ", meanings: { id: "dapur", en: "kitchen", zh: "厨房", tw: "廚房" } },
    { id: 10, kanji: "トイレ", reading: "トイレ", meanings: { id: "toilet", en: "toilet; restroom", zh: "厕所", tw: "廁所" } },
    { id: 11, kanji: "玄関", reading: "げんかん", meanings: { id: "pintu masuk", en: "entrance", zh: "玄关", tw: "玄關" } },
    { id: 12, kanji: "階段", reading: "かいだん", meanings: { id: "tangga", en: "stairs", zh: "楼梯", tw: "樓梯" } },
    { id: 13, kanji: "エレベーター", reading: "エレベーター", meanings: { id: "lift", en: "elevator", zh: "电梯", tw: "電梯" } },
    { id: 14, kanji: "エスカレーター", reading: "エスカレーター", meanings: { id: "eskalator", en: "escalator", zh: "自动扶梯", tw: "自動扶梯" } },
    { id: 15, kanji: "教室", reading: "きょうしつ", meanings: { id: "kelas", en: "classroom", zh: "教室", tw: "教室" } },
    { id: 16, kanji: "机", reading: "つくえ", meanings: { id: "meja", en: "desk", zh: "书桌", tw: "書桌" } },
    { id: 17, kanji: "椅子", reading: "いす", meanings: { id: "kursi", en: "chair", zh: "椅子", tw: "椅子" } },
    { id: 18, kanji: "窓", reading: "まど", meanings: { id: "jendela", en: "window", zh: "窗户", tw: "窗戶" } },
    { id: 19, kanji: "ドア", reading: "ドア", meanings: { id: "pintu", en: "door", zh: "门", tw: "門" } },
    { id: 20, kanji: "戸", reading: "と", meanings: { id: "pintu geser", en: "sliding door", zh: "门（推拉）", tw: "門（推拉）" } },
    { id: 21, kanji: "天気", reading: "てんき", meanings: { id: "cuaca", en: "weather", zh: "天气", tw: "天氣" } },
    { id: 22, kanji: "空", reading: "そら", meanings: { id: "langit", en: "sky", zh: "天空", tw: "天空" } },
    { id: 23, kanji: "雨", reading: "あめ", meanings: { id: "hujan", en: "rain", zh: "雨", tw: "雨" } },
    { id: 24, kanji: "雪", reading: "ゆき", meanings: { id: "salju", en: "snow", zh: "雪", tw: "雪" } },
    { id: 25, kanji: "風", reading: "かぜ", meanings: { id: "angin", en: "wind", zh: "风", tw: "風" } },
    { id: 26, kanji: "山", reading: "やま", meanings: { id: "gunung", en: "mountain", zh: "山", tw: "山" } },
    { id: 27, kanji: "川", reading: "かわ", meanings: { id: "sungai", en: "river", zh: "河", tw: "河" } },
    { id: 28, kanji: "海", reading: "うみ", meanings: { id: "laut", en: "sea", zh: "海", tw: "海" } },
    { id: 29, kanji: "湖", reading: "みずうみ", meanings: { id: "danau", en: "lake", zh: "湖", tw: "湖" } },
    { id: 30, kanji: "森", reading: "もり", meanings: { id: "hutan", en: "forest", zh: "森林", tw: "森林" } },
    { id: 31, kanji: "木", reading: "き", meanings: { id: "pohon", en: "tree", zh: "树", tw: "樹" } },
    { id: 32, kanji: "花", reading: "はな", meanings: { id: "bunga", en: "flower", zh: "花", tw: "花" } },
    { id: 33, kanji: "草", reading: "くさ", meanings: { id: "rumput", en: "grass", zh: "草", tw: "草" } },
    { id: 34, kanji: "石", reading: "いし", meanings: { id: "batu", en: "stone", zh: "石头", tw: "石頭" } },
    { id: 35, kanji: "犬", reading: "いぬ", meanings: { id: "anjing", en: "dog", zh: "狗", tw: "狗" } },
    { id: 36, kanji: "猫", reading: "ねこ", meanings: { id: "kucing", en: "cat", zh: "猫", tw: "貓" } },
    { id: 37, kanji: "鳥", reading: "とり", meanings: { id: "burung", en: "bird", zh: "鸟", tw: "鳥" } },
    { id: 38, kanji: "魚", reading: "さかな", meanings: { id: "ikan", en: "fish", zh: "鱼", tw: "魚" } },
    { id: 39, kanji: "牛", reading: "うし", meanings: { id: "sapi", en: "cow", zh: "牛", tw: "牛" } },
    { id: 40, kanji: "馬", reading: "うま", meanings: { id: "kuda", en: "horse", zh: "马", tw: "馬" } },
    { id: 41, kanji: "豚", reading: "ぶた", meanings: { id: "babi", en: "pig", zh: "猪", tw: "豬" } },
    { id: 42, kanji: "鶏肉", reading: "とりにく", meanings: { id: "daging ayam", en: "chicken meat", zh: "鸡肉", tw: "雞肉" } },
    { id: 43, kanji: "牛肉", reading: "ぎゅうにく", meanings: { id: "daging sapi", en: "beef", zh: "牛肉", tw: "牛肉" } },
    { id: 44, kanji: "野菜", reading: "やさい", meanings: { id: "sayur", en: "vegetable", zh: "蔬菜", tw: "蔬菜" } },
    { id: 45, kanji: "果物", reading: "くだもの", meanings: { id: "buah", en: "fruit", zh: "水果", tw: "水果" } },
    { id: 46, kanji: "ご飯", reading: "ごはん", meanings: { id: "nasi; makan", en: "rice; meal", zh: "饭", tw: "飯" } },
    { id: 47, kanji: "パン", reading: "パン", meanings: { id: "roti", en: "bread", zh: "面包", tw: "麵包" } },
    { id: 48, kanji: "麺", reading: "めん", meanings: { id: "mi", en: "noodles", zh: "面条", tw: "麵條" } },
    { id: 49, kanji: "肉", reading: "にく", meanings: { id: "daging", en: "meat", zh: "肉", tw: "肉" } },
    { id: 50, kanji: "水", reading: "みず", meanings: { id: "air", en: "water", zh: "水", tw: "水" } },
  ],
};
