export const n5part_nouns3 = {
  Lesson3: [
    { id: 1, kanji: "お茶", reading: "おちゃ", meanings: { id: "teh", en: "tea", zh: "茶", tw: "茶" } },
    { id: 2, kanji: "コーヒー", reading: "コーヒー", meanings: { id: "kopi", en: "coffee", zh: "咖啡", tw: "咖啡" } },
    { id: 3, kanji: "牛乳", reading: "ぎゅうにゅう", meanings: { id: "susu sapi", en: "milk", zh: "牛奶", tw: "牛奶" } },
    { id: 4, kanji: "ジュース", reading: "ジュース", meanings: { id: "jus", en: "juice", zh: "果汁", tw: "果汁" } },
    { id: 5, kanji: "酒", reading: "さけ", meanings: { id: "sake; minuman keras", en: "alcohol; sake", zh: "酒", tw: "酒" } },
    { id: 6, kanji: "朝ご飯", reading: "あさごはん", meanings: { id: "sarapan", en: "breakfast", zh: "早餐", tw: "早餐" } },
    { id: 7, kanji: "昼ご飯", reading: "ひるごはん", meanings: { id: "makan siang", en: "lunch", zh: "午饭", tw: "午飯" } },
    { id: 8, kanji: "晩ご飯", reading: "ばんごはん", meanings: { id: "makan malam", en: "dinner", zh: "晚饭", tw: "晚飯" } },
    { id: 9, kanji: "弁当", reading: "べんとう", meanings: { id: "bekal", en: "boxed lunch", zh: "便当", tw: "便當" } },
    { id: 10, kanji: "菓子", reading: "かし", meanings: { id: "kue; permen", en: "sweets; snacks", zh: "点心", tw: "點心" } },
    { id: 11, kanji: "ケーキ", reading: "ケーキ", meanings: { id: "kue", en: "cake", zh: "蛋糕", tw: "蛋糕" } },
    { id: 12, kanji: "飴", reading: "あめ", meanings: { id: "permen", en: "candy", zh: "糖果", tw: "糖果" } },
    { id: 13, kanji: "皿", reading: "さら", meanings: { id: "piring", en: "plate", zh: "盘子", tw: "盤子" } },
    { id: 14, kanji: "箸", reading: "はし", meanings: { id: "sumpit", en: "chopsticks", zh: "筷子", tw: "筷子" } },
    { id: 15, kanji: "スプーン", reading: "スプーン", meanings: { id: "sendok", en: "spoon", zh: "勺子", tw: "湯匙" } },
    { id: 16, kanji: "フォーク", reading: "フォーク", meanings: { id: "garpu", en: "fork", zh: "叉子", tw: "叉子" } },
    { id: 17, kanji: "コップ", reading: "コップ", meanings: { id: "gelas", en: "cup; glass", zh: "杯子", tw: "杯子" } },
    { id: 18, kanji: "茶碗", reading: "ちゃわん", meanings: { id: "mangkuk", en: "rice bowl", zh: "碗", tw: "碗" } },
    { id: 19, kanji: "包丁", reading: "ほうちょう", meanings: { id: "pisau dapur", en: "kitchen knife", zh: "菜刀", tw: "菜刀" } },
    { id: 20, kanji: "鍋", reading: "なべ", meanings: { id: "panci", en: "pot; pan", zh: "锅", tw: "鍋" } },
    { id: 21, kanji: "冷蔵庫", reading: "れいぞうこ", meanings: { id: "lemari es", en: "refrigerator", zh: "冰箱", tw: "冰箱" } },
    { id: 22, kanji: "テレビ", reading: "テレビ", meanings: { id: "televisi", en: "television", zh: "电视", tw: "電視" } },
    { id: 23, kanji: "ラジオ", reading: "ラジオ", meanings: { id: "radio", en: "radio", zh: "收音机", tw: "收音機" } },
    { id: 24, kanji: "コンピューター", reading: "コンピューター", meanings: { id: "komputer", en: "computer", zh: "电脑", tw: "電腦" } },
    { id: 25, kanji: "携帯電話", reading: "けいたいでんわ", meanings: { id: "HP genggam", en: "cell phone", zh: "手机", tw: "手機" } },
    { id: 26, kanji: "スマートフォン", reading: "スマートフォン", meanings: { id: "smartphone", en: "smartphone", zh: "智能手机", tw: "智慧型手機" } },
    { id: 27, kanji: "電話", reading: "でんわ", meanings: { id: "telepon", en: "telephone", zh: "电话", tw: "電話" } },
    { id: 28, kanji: "手紙", reading: "てがみ", meanings: { id: "surat", en: "letter", zh: "信", tw: "信" } },
    { id: 29, kanji: "はがき", reading: "はがき", meanings: { id: "kartu pos", en: "postcard", zh: "明信片", tw: "明信片" } },
    { id: 30, kanji: "封筒", reading: "ふうとう", meanings: { id: "amplop", en: "envelope", zh: "信封", tw: "信封" } },
    { id: 31, kanji: "切手", reading: "きって", meanings: { id: "perangko", en: "stamp", zh: "邮票", tw: "郵票" } },
    { id: 32, kanji: "雑誌", reading: "ざっし", meanings: { id: "majalah", en: "magazine", zh: "杂志", tw: "雜誌" } },
    { id: 33, kanji: "新聞", reading: "しんぶん", meanings: { id: "koran", en: "newspaper", zh: "报纸", tw: "報紙" } },
    { id: 34, kanji: "本", reading: "ほん", meanings: { id: "buku", en: "book", zh: "书", tw: "書" } },
    { id: 35, kanji: "ノート", reading: "ノート", meanings: { id: "buku catatan", en: "notebook", zh: "笔记本", tw: "筆記本" } },
    { id: 36, kanji: "教科書", reading: "きょうかしょ", meanings: { id: "buku pelajaran", en: "textbook", zh: "教科书", tw: "教科書" } },
    { id: 37, kanji: "辞書", reading: "じしょ", meanings: { id: "kamus", en: "dictionary", zh: "词典", tw: "詞典" } },
    { id: 38, kanji: "地図", reading: "ちず", meanings: { id: "peta", en: "map", zh: "地图", tw: "地圖" } },
    { id: 39, kanji: "時計", reading: "とけい", meanings: { id: "jam", en: "clock; watch", zh: "钟表", tw: "鐘錶" } },
    { id: 40, kanji: "カメラ", reading: "カメラ", meanings: { id: "kamera", en: "camera", zh: "照相机", tw: "相機" } },
    { id: 41, kanji: "写真", reading: "しゃしん", meanings: { id: "foto", en: "photo", zh: "照片", tw: "照片" } },
    { id: 42, kanji: "ビデオ", reading: "ビデオ", meanings: { id: "video", en: "video", zh: "录像", tw: "錄影" } },
    { id: 43, kanji: "映画", reading: "えいが", meanings: { id: "film", en: "movie", zh: "电影", tw: "電影" } },
    { id: 44, kanji: "音楽", reading: "おんがく", meanings: { id: "musik", en: "music", zh: "音乐", tw: "音樂" } },
    { id: 45, kanji: "歌", reading: "うた", meanings: { id: "lagu", en: "song", zh: "歌曲", tw: "歌曲" } },
    { id: 46, kanji: "ピアノ", reading: "ピアノ", meanings: { id: "piano", en: "piano", zh: "钢琴", tw: "鋼琴" } },
    { id: 47, kanji: "ギター", reading: "ギター", meanings: { id: "gitar", en: "guitar", zh: "吉他", tw: "吉他" } },
    { id: 48, kanji: "スポーツ", reading: "スポーツ", meanings: { id: "olahraga", en: "sport", zh: "运动", tw: "運動" } },
    { id: 49, kanji: "サッカー", reading: "サッカー", meanings: { id: "sepak bola", en: "soccer", zh: "足球", tw: "足球" } },
    { id: 50, kanji: "野球", reading: "やきゅう", meanings: { id: "bisbol", en: "baseball", zh: "棒球", tw: "棒球" } },
  ],
};
