export const n5part_nouns1 = {
  Lesson1: [
    { id: 1,  kanji: "人", reading: "ひと", meanings: { id: "orang", en: "person", zh: "人", tw: "人" } },
    { id: 2,  kanji: "子供", reading: "こども", meanings: { id: "anak", en: "child", zh: "孩子", tw: "孩子" } },
    { id: 3,  kanji: "男", reading: "おとこ", meanings: { id: "laki-laki", en: "man; male", zh: "男人", tw: "男人" } },
    { id: 4,  kanji: "男の子", reading: "おとこのこ", meanings: { id: "anak laki-laki", en: "boy", zh: "男孩", tw: "男孩" } },
    { id: 5,  kanji: "女", reading: "おんな", meanings: { id: "perempuan", en: "woman; female", zh: "女人", tw: "女人" } },
    { id: 6,  kanji: "女の子", reading: "おんなのこ", meanings: { id: "anak perempuan", en: "girl", zh: "女孩", tw: "女孩" } },
    { id: 7,  kanji: "先生", reading: "せんせい", meanings: { id: "guru; sensei", en: "teacher", zh: "老师", tw: "老師" } },
    { id: 8,  kanji: "学生", reading: "がくせい", meanings: { id: "pelajar", en: "student", zh: "学生", tw: "學生" } },
    { id: 9,  kanji: "外国人", reading: "がいこくじん", meanings: { id: "orang asing", en: "foreigner", zh: "外国人", tw: "外國人" } },
    { id: 10, kanji: "日本人", reading: "にほんじん", meanings: { id: "orang Jepang", en: "Japanese person", zh: "日本人", tw: "日本人" } },
    { id: 11, kanji: "友達", reading: "ともだち", meanings: { id: "teman", en: "friend", zh: "朋友", tw: "朋友" } },
    { id: 12, kanji: "名前", reading: "なまえ", meanings: { id: "nama", en: "name", zh: "名字", tw: "名字" } },
    { id: 13, kanji: "父", reading: "ちち", meanings: { id: "ayah (sendiri)", en: "father (mine)", zh: "父亲（自称）", tw: "父親（自稱）" } },
    { id: 14, kanji: "母", reading: "はは", meanings: { id: "ibu (sendiri)", en: "mother (mine)", zh: "母亲（自称）", tw: "母親（自稱）" } },
    { id: 15, kanji: "お父さん", reading: "おとうさん", meanings: { id: "ayah", en: "father", zh: "父亲", tw: "父親" } },
    { id: 16, kanji: "お母さん", reading: "おかあさん", meanings: { id: "ibu", en: "mother", zh: "母亲", tw: "母親" } },
    { id: 17, kanji: "兄", reading: "あに", meanings: { id: "kakak laki-laki (sendiri)", en: "older brother (mine)", zh: "哥哥（自称）", tw: "哥哥（自稱）" } },
    { id: 18, kanji: "姉", reading: "あね", meanings: { id: "kakak perempuan (sendiri)", en: "older sister (mine)", zh: "姐姐（自称）", tw: "姐姐（自稱）" } },
    { id: 19, kanji: "弟", reading: "おとうと", meanings: { id: "adik laki-laki", en: "younger brother", zh: "弟弟", tw: "弟弟" } },
    { id: 20, kanji: "妹", reading: "いもうと", meanings: { id: "adik perempuan", en: "younger sister", zh: "妹妹", tw: "妹妹" } },
    { id: 21, kanji: "お兄さん", reading: "おにいさん", meanings: { id: "kakak laki-laki", en: "older brother", zh: "哥哥", tw: "哥哥" } },
    { id: 22, kanji: "お姉さん", reading: "おねえさん", meanings: { id: "kakak perempuan", en: "older sister", zh: "姐姐", tw: "姐姐" } },
    { id: 23, kanji: "伯父", reading: "おじ", meanings: { id: "paman", en: "uncle", zh: "伯父／叔父", tw: "伯父／叔父" } },
    { id: 24, kanji: "伯母", reading: "おば", meanings: { id: "bibi", en: "aunt", zh: "伯母／叔母", tw: "伯母／叔母" } },
    { id: 25, kanji: "家族", reading: "かぞく", meanings: { id: "keluarga", en: "family", zh: "家人；家庭", tw: "家人；家庭" } },
    { id: 26, kanji: "夫", reading: "おっと", meanings: { id: "suami", en: "husband", zh: "丈夫", tw: "丈夫" } },
    { id: 27, kanji: "妻", reading: "つま", meanings: { id: "istri", en: "wife", zh: "妻子", tw: "妻子" } },
    { id: 28, kanji: "子", reading: "こ", meanings: { id: "anak; anak kecil", en: "child", zh: "孩子", tw: "孩子" } },
    { id: 29, kanji: "赤ちゃん", reading: "あかちゃん", meanings: { id: "bayi", en: "baby", zh: "婴儿", tw: "嬰兒" } },
    { id: 30, kanji: "医者", reading: "いしゃ", meanings: { id: "dokter", en: "doctor", zh: "医生", tw: "醫生" } },
    { id: 31, kanji: "学校", reading: "がっこう", meanings: { id: "sekolah", en: "school", zh: "学校", tw: "學校" } },
    { id: 32, kanji: "小学校", reading: "しょうがっこう", meanings: { id: "SD", en: "elementary school", zh: "小学", tw: "小學" } },
    { id: 33, kanji: "中学校", reading: "ちゅうがっこう", meanings: { id: "SMP", en: "junior high school", zh: "初中", tw: "國中" } },
    { id: 34, kanji: "高校", reading: "こうこう", meanings: { id: "SMA", en: "high school", zh: "高中", tw: "高中" } },
    { id: 35, kanji: "大学", reading: "だいがく", meanings: { id: "universitas", en: "university", zh: "大学", tw: "大學" } },
    { id: 36, kanji: "会社", reading: "かいしゃ", meanings: { id: "perusahaan", en: "company", zh: "公司", tw: "公司" } },
    { id: 37, kanji: "病院", reading: "びょういん", meanings: { id: "rumah sakit", en: "hospital", zh: "医院", tw: "醫院" } },
    { id: 38, kanji: "銀行", reading: "ぎんこう", meanings: { id: "bank", en: "bank", zh: "银行", tw: "銀行" } },
    { id: 39, kanji: "郵便局", reading: "ゆうびんきょく", meanings: { id: "kantor pos", en: "post office", zh: "邮局", tw: "郵局" } },
    { id: 40, kanji: "図書館", reading: "としょかん", meanings: { id: "perpustakaan", en: "library", zh: "图书馆", tw: "圖書館" } },
    { id: 41, kanji: "映画館", reading: "えいがかん", meanings: { id: "bioskop", en: "cinema", zh: "电影院", tw: "電影院" } },
    { id: 42, kanji: "喫茶店", reading: "きっさてん", meanings: { id: "kedai kopi", en: "coffee shop", zh: "咖啡馆", tw: "咖啡館" } },
    { id: 43, kanji: "レストラン", reading: "レストラン", meanings: { id: "restoran", en: "restaurant", zh: "餐馆", tw: "餐館" } },
    { id: 44, kanji: "ホテル", reading: "ホテル", meanings: { id: "hotel", en: "hotel", zh: "旅馆", tw: "旅館" } },
    { id: 45, kanji: "店", reading: "みせ", meanings: { id: "toko; kedai", en: "shop; store", zh: "店铺", tw: "店舖" } },
    { id: 46, kanji: "スーパー", reading: "スーパー", meanings: { id: "supermarket", en: "supermarket", zh: "超市", tw: "超市" } },
    { id: 47, kanji: "デパート", reading: "デパート", meanings: { id: "toserba", en: "department store", zh: "百货商店", tw: "百貨公司" } },
    { id: 48, kanji: "八百屋", reading: "やおや", meanings: { id: "toko sayur", en: "greengrocer", zh: "蔬果店", tw: "蔬果店" } },
    { id: 49, kanji: "花屋", reading: "はなや", meanings: { id: "toko bunga", en: "florist", zh: "花店", tw: "花店" } },
    { id: 50, kanji: "本屋", reading: "ほんや", meanings: { id: "toko buku", en: "bookstore", zh: "书店", tw: "書店" } },
  ],
};
